### ISSUE TITLE
[MD] About getting id from all chats

### ISSUE THREAD

**Issue by VEXG** [adiwajshing/Baileys#1001]
**question**
Since Baileys-MD does not support `chats.all()`, Is there an alternative to get id from all chats in my whatsapp?.

**Comment by Zobin33** [comment]
Ahhh Yes, How i Get All Chats In Multi Device, Is Important

**Comment by frmdeveloper** [comment]
Baileys-md only accepts messages.
Not saving messages.

**Comment by BochilGaming** [comment]
> **question** Since Baileys-MD does not support `chats.all()`, Is there an alternative to get id from all chats in my whatsapp?.

You can listen event `message.upsert` and save the id, pushName,  etc

**Comment by Zobin33** [comment]
> > **question** Since Baileys-MD does not support `chats.all()`, Is there an alternative to get id from all chats in my whatsapp?.
> 
> You can listen event `message.upsert` and save the id, pushName, etc

Get All Id Lol Not Chat Update, Sometimes Is Very Needed

**Comment by Zobin33** [comment]
> Baileys-md only accepts messages. Not saving messages.

I Know, But, There Some WAY to Get All Jids Or Messages?

**Comment by BochilGaming** [comment]
> > > **question** Since Baileys-MD does not support `chats.all()`, Is there an alternative to get id from all chats in my whatsapp?.
> > 
> > 
> > You can listen event `message.upsert` and save the id, pushName, etc
> 
> Get All Id Lol Not Chat Update, Sometimes Is Very Needed

Yes, I know. but if you save it you can get chat list instead of all chats

**Comment by Zobin33** [comment]
> > > > **question** Since Baileys-MD does not support `chats.all()`, Is there an alternative to get id from all chats in my whatsapp?.
> > > 
> > > 
> > > You can listen event `message.upsert` and save the id, pushName, etc
> > 
> > 
> > Get All Id Lol Not Chat Update, Sometimes Is Very Needed
> 
> Yes, I know. but if you save it you can get chat list instead of all chats

For Messages, Is Work, But How I Get All Jids?

**Comment by Zobin33** [comment]
Well, I dong Have Choices, I Will Create Some Chats Db

**Comment by BochilGaming** [comment]
> > > > > **question** Since Baileys-MD does not support `chats.all()`, Is there an alternative to get id from all chats in my whatsapp?.
> > > > 
> > > > 
> > > > You can listen event `message.upsert` and save the id, pushName, etc
> > > 
> > > 
> > > Get All Id Lol Not Chat Update, Sometimes Is Very Needed
> > 
> > 
> > Yes, I know. but if you save it you can get chat list instead of all chats
> 
> For Messages, Is Work, But How I Get All Jids?

save jid, etc into database, and you can get all jid in database
