### ISSUE TITLE
How to validate number is registered on whatsapp or not Baileys

### ISSUE THREAD

**Issue by Denver1997** [adiwajshing/Baileys#1003]
How to validate number is registered on whatsapp or not

**Comment by BochilGaming** [comment]
```js
await conn.isOnWhatsApp ('62223612')
```
in legacy

**Comment by Denver1997** [comment]
Can you send app.post 
Full code for checking number and get it's name

**Comment by Denver1997** [comment]
How to get name of registered number

**Comment by aislanspeedio** [comment]
@Denver1997 have you discovered how to get the registered number's name?
