### ISSUE TITLE
[MD] read chats on multi device

### ISSUE THREAD

**Issue by kauanzito** [adiwajshing/Baileys#1004]
many users are complaining that there hasn't been a read chat for MD yet.

**Comment by jackcokk** [comment]
"read chat"
You may want to be more specific than that

**Comment by kauanzito** [comment]
> "ler bate-papo" Você pode querer ser mais específico do que isso

I tried to be straight to the point and not stall like some others

**Comment by viniciusgdr** [comment]
This function already exists on Baileys MD, there are no bugs here.

Read the Documentation

Example:
`await sock.sendReadReceipt(id, participant, [messageID])`

**Comment by kauanzito** [comment]
> Esta função já existe no Baileys MD, não há bugs aqui.
> 
> Leia a documentação
> 
> Exemplo: `await sock.sendReadReceipt(id, participant, [messageID])`



thanks for letting me know, friend
