### ISSUE TITLE
[MD] [BUG] no response in groups

### ISSUE THREAD

**Issue by kauanzito** [adiwajshing/Baileys#1005]
When I try to perform group commands it gives this error: "TypeError: nodeCrypto.randomInt is not a function"

**Comment by AkirahX** [comment]
Code?

**Comment by kauanzito** [comment]
> Code?

funny that i didn't find anything about

**Comment by viniciusgdr** [comment]
Could you send the code? Is your baileys updated? Could you send a print of the error?
