### ISSUE TITLE
[BUG] Getting "Cmd" with type "upgrade_md_prod" during initial connection

### ISSUE THREAD

**Issue by yonatann** [adiwajshing/Baileys#1006]
**Describe the bug**
During the connection sequence the first message that is received is:

`["Cmd",{"type":"upgrade_md_prod","version":"2.2126.11"}]`

Since no secret is received, the authInfo object cannot be populated appropriately, and the connection will close.

**To Reproduce**
1. Run the example and scan the QR with a multi-device enabled WA account

**Expected behavior**
Connection should be successful

**Environment (please complete the following information):**
 - Local test on mac OS
 - Using default values.
 - No
 - No

**Additional context**
Using clean clone from `93e272f9bf0a4c8b7b484d80bc8857612446f349`

**Comment by yonatann** [comment]
After digging a bit in the WA web code, it seems this message indicates that the client needs to be upgraded to the mulit-device version.

Isn't this supposed to be supported already?
Am I configuring it wrong?

**Comment by adiwajshing** [comment]
https://github.com/adiwajshing/Baileys/tree/multi-device 🙏

**Comment by EricAlvarez292** [comment]
Do you also have this version/fixed for [Baileys npm](https://www.npmjs.com/package/baileys)?
