### ISSUE TITLE
To get the name of some person Baileys

### ISSUE THREAD

**Issue by Denver1997** [adiwajshing/Baileys#1009]
To get the name of some person Baileys

**Comment by Gimenz** [comment]
u mean get name from WA User? read the docs pls before you asking here, or you can find on the closed issue.

[WAContact](https://adiwajshing.github.io/Baileys/interfaces/wacontact.html)

**Comment by Denver1997** [comment]
Not resolved

I use this code for get users status
const status = await conn.getStatus ("xyz@c.us") // leave empty to get your own status
console.log("status: " + status)

But can't find code for get user name

**Comment by Gimenz** [comment]
you can try this function, [#L722](https://github.com/Nurutomo/wabot-aq/blob/2c9cb0034a6d4bbbf2b91df4d5da97c0c9404218/lib/simple.js#L722)

or `conn.contacts['123@s.whatsapp.net']`
