### ISSUE TITLE
Documentation on the structure of classes

### ISSUE THREAD

**Issue by AZMCode** [adiwajshing/Baileys#101]
Possibly using typedoc? or jsdoc? in any case the shape of module classes could be added.

**Comment by AZMCode** [comment]
I've searched around the code and found there are JSDoc comments. Why is this not generated somewhere?

**Comment by adiwajshing** [comment]
I dunno, haven't felt the need to do so. Please feel free to submit a PR.

**Comment by AZMCode** [comment]
Am I right in assuming this project is moving to typescript?
In that case it might be better to wait until the whole codebase is moved, so typedoc can use it.

**Comment by adiwajshing** [comment]
It's already in typescript. Did you find any JS code?

**Comment by AZMCode** [comment]
Nope, it's just the sidebar on the main page says 70-something percent javascript. Makes sense why all the files i opened so far were ts.
Ill try to begin working on a PR with typedoc.

**Comment by AZMCode** [comment]
> I dunno, haven't felt the need to do so. Please feel free to submit a PR.
https://github.com/adiwajshing/Baileys/pull/104
Feelin' free indeed

**Comment by adiwajshing** [comment]
merged PR. Thanks
