### ISSUE TITLE
Need help about if group includes one person, do not join to it.

### ISSUE THREAD

**Issue by valco72** [adiwajshing/Baileys#1013]
I just add if group lenght is more than 35 do not join any groups.
But need to add if group includes xx and xx2 numbers do not join to it.
My codes are this.
Need help.

`let linkRegex = /chat.whatsapp.com\/([0-9A-Za-z]{20,24})/i
const botsjid = [
    "xx1@s.whatsapp.net",
    "xx2@s.whatsapp.net"
]

let handler = async (m, { conn, text }) => {
    let [_, code] = text.match(linkRegex) || []
    if (!code) throw 'Link bulunamadı.'
    const chats = conn.chats.all()
    const groups = chats.filter(v => v.jid.endsWith('g.us'))
    const groupsIn = groups.filter(v => !v.read_only)
    if (groupsIn.length >= 99) throw 'Botun bu numarası yeterli grup sayısına ulaşmıştır. Diğer numaraları eklemeyi deneyiniz. Diğer numaralar için .numberlist yazabilirsiniz.'
    let resa = await conn.revokeInvite(code)
    let gruptabotvar = await conn.groupMetadata(resa.gid).participants.includes(botsjid)
    let members = gruptabotvar.participants.filter(member => member).map(member => member.jid).includes(botsjid)
    if (member) {
        await conn.revokeInvite(code)
        m.reply('Bu grupta zaten aktif olarak bir bot bulunmakta.')
    } else {
    let res = await conn.acceptInvite(code)
    m.reply(`Gruba katılma başarılı. ${res.gid}\n\nEğer bot grubunuzda çalışmazsa grubunuzun buglu jidi vardır. Bot o gruplarda çalışmamaktadır. Farklı bir sorun olduğunu düşünüyorsanız *.destekgrup* yazarak bizlere danışabilirsiniz. 2021 Kasım ayından önce kurulmuş gruplarda deneyiniz.`)
    //m.reply('Botun sistemini geçici süre değiştirdik. Bir süre aşağıdaki gruplarda kullanılacak:\n\n1- x')
    } 
}
handler.help = ['join <chat.whatsapp.com>']
handler.tags = ['premium']
handler.owner = true
handler.command = /^join$/i
handler.private = true

module.exports = handler
`

**Comment by erickythierry** [comment]
just make a checker. when entering the group, it checks the number of participants and then checks if there is any unwanted participant, if you can't be in the group, the script automatically exits

**Comment by valco72** [comment]
> just make a checker. when entering the group, it checks the number of participants and then checks if there is any unwanted participant, if you can't be in the group, the script automatically exits

Can you explain with codes?
