### ISSUE TITLE
Get contact by id

### ISSUE THREAD

**Issue by JonazBR** [adiwajshing/Baileys#1015]
get contact info by contact id

example:

sock.getContact('558296823418@s.whatsap.net')
Response:
[{
pushname: 'Jonaz',
lastSeen: '12:30',
status: 'hi'
}]

**Comment by Gimenz** [comment]
get contact in md or in normal?
 in baileys maybe you can try
```js
client.contacts['number@s.whatsapp.net']
```
response : 

 ```js
{
  notify: 'Ir. Prof. Dr. Jambrong',
  jid: 'number@s.whatsapp.net',
  dm_duration: '0',
  dm_t: '0',
  name: 'Ir. Prof. Dr. Jambrong',
  index: 'I'
}
```

if on md, i think it not available yet

**Comment by JonazBR** [comment]
> get contact in md or in normal? in baileys maybe you can try
> 
> ```js
> client.contacts['number@s.whatsapp.net']
> ```
> 
> response :
> 
> ```js
> {
>  notify: 'Ir. Prof. Dr. Jambrong',
>  jid: 'number@s.whatsapp.net',
>  dm_duration: '0',
>  dm_t: '0',
>  name: 'Ir. Prof. Dr. Jambrong',
>  index: 'I'
> }
> ```
> 
> if on md, i think it not available yet

md, =(

**Comment by vishwajit76** [comment]
any update?
