### ISSUE TITLE
[BUG] Baileys Error

### ISSUE THREAD

**Issue by itsMySky** [adiwajshing/Baileys#1020]
BaileysError: Unexpected status in 'query': Internal Server Error(500)
![IMG-20211216-WA0070](https://user-images.githubusercontent.com/80798056/146290778-c7a60bbf-3e0e-463e-b3c4-7ca774ff7ca9.jpg)

**Comment by OyenDCraft** [comment]
![IMG-20211216-WA0031](https://user-images.githubusercontent.com/84307428/146294650-dc6603e5-c13b-4ece-8560-376101a3b925.jpg)

Baileys error

**Comment by Kauefranca** [comment]
duplicated of #1019 

you need to change the client version:
client.version = [2, 2140, 14]
