### ISSUE TITLE
[BUG] BAILEYS ERROR INTERNAL SERVER

### ISSUE THREAD

**Issue by Tmgr26** [adiwajshing/Baileys#1021]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by zadik-hacker** [comment]
this.version = [2, 2140, 14] , it works but it keeps dropping and giving a query and you have to keep reconnecting

**Comment by itsMySky** [comment]
change groupMetadata

const groupMetadata = isGroup ? await conn.groupMetadata(from) : 'query'.toString
