### ISSUE TITLE
[BUG] Baileys Error

### ISSUE THREAD

**Issue by OyenDCraft** [adiwajshing/Baileys#1028]
![IMG-20211216-WA0031](https://user-images.githubusercontent.com/84307428/146294917-08378056-e678-49a0-944d-b7cf84d68a79.jpg)

Baileys Internal Server Error

**Comment by itsMySky** [comment]
Change  client version 

this.version = [2, 2140, 12]
Or
this.version = [2, 2140, 14]

**Comment by zadik-hacker** [comment]
this.version = [2, 2140, 14] , it works but it keeps dropping and giving a query and you have to keep reconnecting

**Comment by viniciusgdr** [comment]
I recommend seeing version updates at: [this website of whatsapp](https://web.whatsapp.com/check-update?version=1&platform=web)

**Comment by viniciusgdr** [comment]
> Eu recomendo ver as atualizações de versão em: [este site do Whatsapp](https://web.whatsapp.com/check-update?version=1&platform=web)

The Current Version is the "2.2147.16"

**Comment by itsMySky** [comment]
change groupMetadata

const groupMetadata = isGroup ? await conn.groupMetadata(from) : 'query'.toString

**Comment by OyenDCraft** [comment]
> 

![Uploading Screenshot_2021-12-16-10-26-36-50_96079702262017ccfd2f2f70f93088e6.jpg…]()


Error

**Comment by OyenDCraft** [comment]
> Change client version
> 
> this.version = [2, 2140, 12] Or this.version = [2, 2140, 14]

![Uploading Screenshot_2021-12-16-10-26-36-50_96079702262017ccfd2f2f70f93088e6.jpg…]()
