### ISSUE TITLE
Trouble Quoting messages

### ISSUE THREAD

**Issue by AZMCode** [adiwajshing/Baileys#103]
```
const { WAClient, MessageType, getNotificationType } = require("@adiwajshing/baileys");
(async()=>{
    const client = new WAClient()
    await client.connect()
    client.setOnUnreadMessage(true,async (obj)=>{
        const [notifType, msgType] = getNotificationType(obj);
        const options = {quoted: await client.loadMessage(obj.key.remoteJid,obj.message[msgType].contextInfo.stanzaId)}
        client.sendMessage(obj.key.remoteJid,"MessageBack",MessageType.extendedText,options);
    })
})()
```
Listens to inbound messages, and answers with "MessageBack", *quoting whatever the inbound message was quoting*, with a little help from client.loadMessage. However the quote doesn't appear to work. Quoted is spelled correctly, and the object I'm feeding the sendMessage function seems to fit the pattern as expected.

**Comment by AZMCode** [comment]
I've debugged it for a bit to make sure it's nothing obvious on my side.

**Comment by adiwajshing** [comment]
Sorry for the late reply, but is this a single chat or group?

**Comment by AZMCode** [comment]
Group

**Comment by adiwajshing** [comment]
I can't seem to reproduce the issue. Does this happen will all kinds of quotations on the group or only when quoting a quoted message's quote?

**Comment by AZMCode** [comment]
> I can't seem to reproduce the issue. Does this happen will all kinds of quotations on the group or only when quoting a quoted message's quote?

This might be the most confusing sentence I've heard XD
I'll test it out. Consider I have been running this code on Termux, so that might be what breaks it.

**Comment by AZMCode** [comment]
Umm... I tried to run the sample code from github master, but it crashes, both on Termux and Ubuntu

```
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module './6.Groups'
Require stack:
- /home/adriano/Documents/Personal/otherPeoplesProjects/baileystest/node_modules/@adiwajshing/baileys/lib/WAConnection/WAConnection.js
- /home/adriano/Documents/Personal/otherPeoplesProjects/baileystest/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/adriano/Documents/Personal/otherPeoplesProjects/baileystest/node_modules/@adiwajshing/baileys/lib/WAConnection/WAConnection.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/adriano/Documents/Personal/otherPeoplesProjects/baileystest/node_modules/@adiwajshing/baileys/lib/WAConnection/WAConnection.js',
    '/home/adriano/Documents/Personal/otherPeoplesProjects/baileystest/index.js'
  ]
}
```

**Comment by AZMCode** [comment]
Should i test from npm package?

**Comment by AZMCode** [comment]
I've run the sample code from ubuntu and it still doesn't quote. Ill try just quoting the initial message

**Comment by AZMCode** [comment]
```
const { WAClient, MessageType, getNotificationType } = require("@adiwajshing/baileys");
(async()=>{
    const client = new WAClient()
    await client.connect()
    client.setOnUnreadMessage(true,async (obj)=>{
        const [notifType, msgType] = getNotificationType(obj);
        client.sendMessage(obj.key.remoteJid,"MessageBack",MessageType.extendedText,{quoted: obj});
    })
})()
```
Tried this, and still no quote, even in ubuntu

**Comment by AZMCode** [comment]
It should also be of note I'm the only person in the group chat, for testing purposes, and thus every message quoted and quoting is mine.

**Comment by AZMCode** [comment]
Quickly tested it out on an actual group chat (-10 Charm), but the bug is still there.

**Comment by adiwajshing** [comment]
Thanks for the test, I'm not sure what's causing this -- it works perfectly well on my phone. What version of WA are you on?

**Comment by AZMCode** [comment]
2.20.198.5

**Comment by adiwajshing** [comment]
I think I figured the issue out, could you please try it again with the latest commit? Thanks.

**Comment by AZMCode** [comment]
Appreciate it, imma test rn.

**Comment by galiazzi** [comment]
I have this problem only in group chats

https://github.com/adiwajshing/Baileys/blob/4c646e3e02f15d7b34cb677aee16b78df0867ea2/src/WAConnection/6.MessagesSend.ts#L153

I change this line to this: 

```js
const participant = quoted.key.fromMe ? this.user.jid : (quoted.participant || quoted.key.participant || quoted.key.remoteJid)
```

And works, considering `quoted.participant`

**Comment by adiwajshing** [comment]
I'll implement the same change, thanks.
