### ISSUE TITLE
this.version = [2, 2140, 14] , it works but it keeps dropping and giving a query and you have to keep reconnecting

### ISSUE THREAD

**Issue by itsMySky** [adiwajshing/Baileys#1030]
this.version = [2, 2140, 14] , it works but it keeps dropping and giving a query and you have to keep reconnecting

_Originally posted by @zadik-hacker in https://github.com/adiwajshing/Baileys/issues/1028#issuecomment-995382535_

**Comment by viniciusgdr** [comment]
I recommend seeing version updates at: [This Website of WhatsApp](https://web.whatsapp.com/check-update?version=1&platform=web)
