### ISSUE TITLE
[BUG] [MD]

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#1031]
![Screenshot_20211216-095153](https://user-images.githubusercontent.com/80396521/146299418-e87d0137-303f-4582-9ca8-3a424504f14a.png)

**Comment by mateuscdor** [comment]
update version: "2.2147.16"

**Comment by AkirahX** [comment]
> update version: "2.2147.16"

This solution is not for MD

--------------------------

Is this situation only when starting with a token already created or not even loading the QRCode?

**Comment by shinainaru** [comment]
I also have the same problem,
when starting with tokens already created on November 25th. Can not login.


But my 2nd number doesn't have a problem like this, I scanned the QRCode 1 week ago

**Comment by frmdeveloper** [comment]
### The problem has gone away on its own. Accidentally
![Screenshot_20211216-175538](https://user-images.githubusercontent.com/80396521/146358883-1cb32e2b-cfc1-4de9-a083-1758b658c02c.png)

**Comment by shinainaru** [comment]
_It might be different from what happened to me, So I have to repeat to get the token back_


**Before Scan QRCode again**
![...](https://user-images.githubusercontent.com/90768067/146379960-9b2400d4-8a04-4ac9-95b6-b4b4bc6f4c42.jpg)


**After Scan QR Code again**
![...](https://user-images.githubusercontent.com/90768067/146379952-8abee12a-21c0-4f2b-b47e-dab74b02d15e.jpg)

**Comment by PurpShell** [comment]
so if your issue is gone just close the issue what the fuck dude

**Comment by frmdeveloper** [comment]
Closed #1031.

**Comment by AkirahX** [comment]
> Closed #1031.

Use the button to close this issue bro 😐
