### ISSUE TITLE
[BUG] o

### ISSUE THREAD

**Issue by OyenDCraft** [adiwajshing/Baileys#1032]
O

**Comment by zennn08** [comment]
but what i see is 400 bad requests 😂, so the problem is in your code, not in baileys

**Comment by zennn08** [comment]
> 

lol
why did you edit your comment 😂

**Comment by OyenDCraft** [comment]
> > 
> 
> lol why did you edit your comment 😂

O

**Comment by zennn08** [comment]
> > > 
> > 
> > 
> > lol why did you edit your comment 😂
> 
> O

please close this issue
