### ISSUE TITLE
[MD] CANT SEND GIF Video

### ISSUE THREAD

**Issue by ThisMe124** [adiwajshing/Baileys#1040]
Help me please why can't I add a tenor gif feature for my bot feature, I use web api can you please explain and advise, thank you

**Comment by AkirahX** [comment]
How are you trying?  Can you post the code please?

**Comment by ThisMe124** [comment]
> How are you trying? Can you post the code please?

Wait

**Comment by ThisMe124** [comment]
This Code
```
await fetchJson('https://api.cyberdoge.ga/anime?act=kiss')
h = p.url
me.sendMessage(from, { video: { url: h }, caption: "hello!", gifPlayback: true }) 
``` 
@AkirahX

**Comment by AkirahX** [comment]
> 

You are trying to send in .gif format, this function is only for videos (.mp4 for example).

Convert the .gif to .mp4 and send it, you can use ffmpeg or some npm/yarn package

**Comment by ThisMe124** [comment]
> > This Code
> > ```
> > var p = await fetchJson('https://api.cyberdoge.ga/anime?act=kiss')
> > h = p.url
> > me.sendMessage(from, { video: { url: h }, caption: "hello!", gifPlayback: true }) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @AkirahX
> 
> You are trying to send in .gif format, this function is only for videos (.mp4 for example).
> 
> Convert the .gif to .mp4 and send it, you can use ffmpeg or some npm/yarn package

Oh Okay Thnks

**Comment by ThisMe124** [comment]
🙂
