### ISSUE TITLE
[BUG] reconnect every few seconds

### ISSUE THREAD

**Issue by RDTUTORIAL** [adiwajshing/Baileys#1044]
I run whatsaap bot and every few seconds it always reconnects and it's very annoying, I also tried several whatsapp bot programs on github and the results are the same, I've used various modified whatsapp and original whatsapp and it didn't stop the reconnect

**Comment by Denver1997** [comment]
Same issue with me

**Comment by AkirahX** [comment]
Using the version legacy or MD?

**Comment by RDTUTORIAL** [comment]
> Using the version legacy or MD?
> 
> Post code and/or log

Code : https://github.com/MhankBarBar/termux-wabot
there is no error log, 

there is no error log, 
could the problem be because of my whatsapp or the terminal i am using?

**Comment by AkirahX** [comment]
> > Using the version legacy or MD?
> > Post code and/or log
> 
> Code : https://github.com/MhankBarBar/termux-wabot there is no error log, could the problem be because of my whatsapp or the terminal i am using?

In the terminal does not show anything when the connection is closed?  Right analysis, the error should be shown.

------------

Try to update packages

Run on terminal: 
`npm update`
