### ISSUE TITLE
[MD] externalAdReply in MD?

### ISSUE THREAD

**Issue by unknowkzr** [adiwajshing/Baileys#1045]
How to add externalAdReply In MD like normal baileys?

**Comment by WhyEtzz** [comment]
sock.sendMessage(from, {text: teks, contextInfo:{"externalAdReply": {"title": `${judul}`, "body": `${isi}`, "mediaType": 3,"thumbnail": fs.readFileSync('./media/yourMedia.jpg')}}}, {sendEphemeral: true, quoted: msg, })

**Comment by unknowkzr** [comment]
> sock.sendMessage(from, {text: teks, contextInfo:{"externalAdReply": {"title": `${judul}`, "body": `${isi}`, "mediaType": 3,"thumbnail": fs.readFileSync('./media/yourMedia.jpg')}}}, {sendEphemeral: true, quoted: msg, })

Thankkk youu👍
