### ISSUE TITLE
After qr code scan

### ISSUE THREAD

**Issue by Cosangeles33** [adiwajshing/Baileys#1046]
**Describe the bug**
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
backend_nodejs       |     at prepareSecretKey (internal/crypto/keys.js:322:11)
backend_nodejs       |     at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:9)
backend_nodejs       |     at new Cipheriv (internal/crypto/cipher.js:225:22)
backend_nodejs       |     at Object.createCipheriv (crypto.js:123:10)
backend_nodejs       |     at Object.aesEncrypt (/backend_nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:108:24)
backend_nodejs       |     at WAConnection.sendBinary (/backend_nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:321:26)
backend_nodejs       |     at WAConnection.<anonymous> (/backend_nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:86:18)
backend_nodejs       |     at WAConnection.emit (events.js:326:22)
backend_nodejs       |     at WAConnection.EventEmitter.emit (domain.js:483:12)
backend_nodejs       |     at WAConnection.emit (/backend_nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)

**Comment by ohuser441** [comment]
Leave from Multi-Device beta program on WhatsApp
