### ISSUE TITLE
MD how to get the profile name

### ISSUE THREAD

**Issue by bigbdigital** [adiwajshing/Baileys#1047]
Please, help me.

I have almost everything well mapped, but I couldn't find a reliable place to get the profile name. Can someone help me?

tks

**Comment by SlimGee** [comment]
I've been looking this too, Is there any other way?

**Comment by Zobin33** [comment]
> I've been looking this too, Is there any other way?

Maybe in mesages.upsert you can save the jids and pushname to json, so you can easily get them

**Comment by Krakinz** [comment]
Can Someone give a real life example or better solve the issue please
