### ISSUE TITLE
How do I trigger registerCallback conditionally

### ISSUE THREAD

**Issue by izqalan** [adiwajshing/Baileys#105]
how do i make `registerCallback()` can only be trigger when the message is `hello`?

**Comment by adiwajshing** [comment]
Check if the text in the message matches?

client.onUnreadMessage (msg => {
 if(msg.message?.conversation.includes("hello") {
   // do whatever you want here
 }
})

**Comment by izqalan** [comment]
Sorry if I'm not clear.

From my understanding `registerCallback` will only trigger if the `massage data` matches the `registerCallback()` parameters. in the case below  `registerCallback(['action', 'add:relay', 'message'])` will only be trigger when the `massage data` includes `action`, `add:relay`, and `message`.
```
// massage data
[
  'action',
  { add: 'relay' },
  [ [ 'message', null, [WebMessageInfo] ] ]
]
```
```
registerCallback(['action', 'add:relay', 'message'], json => {
  // do something

});

// this also will trigger the callback
registerCallback(['action', 'add:relay', null], json => {
  // do something

});
```
I'm wondering if something like `registerCallback(['action', 'add:relay', 'some_trigger_word'])` is possible or is it even possible to include `[WebMessageInfo]` in `registerCallback()` param.

**Comment by adiwajshing** [comment]
Ah, no that's not possible because it's not a scalable approach. Most likely you will want to look for keywords rather than a single word.

A simple check before you do something with the message should work fine.
