### ISSUE TITLE
[MD][QUESTION] How do I disconnect a session? 

### ISSUE THREAD

**Issue by Diden05** [adiwajshing/Baileys#1051]
Everyone has questions about how to connect, but I have the opposite :)
How to disconnect session, sock.logout () doesn't work :)

**Comment by unknowkzr** [comment]
> Everyone has questions about how to connect, but I have the opposite :) How to disconnect session, sock.logout () doesn't work :)

What do you mean?
You wanna scan for new session?

**Comment by Diden05** [comment]
> What do you mean?
> You wanna scan for new session?

Yes, a start new session

**Comment by unknowkzr** [comment]
> > What do you mean?
> > You wanna scan for new session?
> 
> Yes, a start new session

Just delete current session

**Comment by Diden05** [comment]
> Just delete current session
session file?

**Comment by unknowkzr** [comment]
> > Just delete current session
> > session file?

Ya session file
it probably session.json

**Comment by Diden05** [comment]
> Ya session file
> it probably session.json

Unfortunately, this does not solve my problem, but I got the idea. It's strange why there is no logout function

**Comment by dncore40** [comment]
you can try sock.logout().then(()=>{//do delete file session in here}) and after that you can try login again. it works in my case
