### ISSUE TITLE
[MD][QUESTION] logger level ?

### ISSUE THREAD

**Issue by unknowkzr** [adiwajshing/Baileys#1054]
const conn = makeWASocket({
        logger: pino({ level: 'debug' }),
        printQRInTerminal: false,
        browser: ['Beta Multi Device','Safari','1.0.0'],
        auth: state
})

Other than 'debug' Is there any another level?

**Comment by AlenSaito1** [comment]
https://github.com/pinojs/pino/blob/master/docs/api.md#level-string

**Comment by unknowkzr** [comment]
> https://github.com/pinojs/pino/blob/master/docs/api.md#level-string

umm Thank?
i guess
