### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by iagovianamonteiro** [adiwajshing/Baileys#1056]
{"level":20,"time":1640142600070,"pid":6956,"hostname":"rr100","recv":{"from":"558698087850@s.whatsapp.net","id":"1640039074-933","t":"1640142600"},"sent":{"id":"1640039074-933","to":"558698087850@s.whatsapp.net","class":"call","**type":"terminate**"},"msg":"sent \"call\" ack"}

Hi! I'm trying to listen for an event that captures the data "type":"terminate", as in the log above. Can someone help me.
I've tried it like this:

sock.ws.on("CB:call", (m) => {
    console.log("Chamada de telefone");
  });

In this case, I pick up the calls but I want to pick them up only when I finish.

**Comment by qiedanz** [comment]
> {"level":20,"time":1640142600070,"pid":6956,"hostname":"rr100","recv":{"from":"[558698087850@s.whatsapp.net](mailto:558698087850@s.whatsapp.net)","id":"1640039074-933","t":"1640142600"},"sent":{"id":"1640039074-933","to":"[558698087850@s.whatsapp.net](mailto:558698087850@s.whatsapp.net)","class":"call","**type":"terminate**"},"msg":"sent "call" ack"}
> 
> Hi! I'm trying to listen for an event that captures the data "type":"terminate", as in the log above. Can someone help me. I've tried it like this:
> 
> sock.ws.on("CB:call", (m) => { console.log("Chamada de telefone"); });
> 
> In this case, I pick up the calls but I want to pick them up only when I finish.

msdsh dimwngwrti swmogs hsrimu mwnywnsngksn
