### ISSUE TITLE
How to use client.close() in baileys-md like regular baileys ?

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#1067]
How to use ```conn.close()```
 in baileys-md like regular baileys ?
___

I tried using ```sock.end()```
But my WhatsApp is still online & tick 2
And how to reconnect without restarting nodejs ?

**Comment by muhamad-fadla** [comment]
hmm same issues

**Comment by zennn08** [comment]
maybe you can try sock.ws.close()
