### ISSUE TITLE
bailey-md branch, Cannot find module '@adiwajshing/baileys-md' [BUG] 

### ISSUE THREAD

**Issue by aderayendra** [adiwajshing/Baileys#1068]
so on 21st Dec 2021 I installed baileys-md using 
> yarn add github:adiwajshing/baileys#multi-device

It worked great until today,
today I saw you just committed few changes so I decided to update the baileys-md as well,
as soon I updated it, typescript kept complaining 
> Cannot find module '@adiwajshing/baileys-md' or its corresponding type declarations .ts(2307)

I did not know what went wrong, so I tried creating a new project and added baileys-md to it, unfortunately it's still the same

can you give me some insights?

**Comment by lyfe00011** [comment]
> so on 21st Dec 2021 I installed baileys-md using
> 
> > yarn add github:adiwajshing/baileys#multi-device
> 
> It worked great until today, today I saw you just committed few changes so I decided to update the baileys-md as well, as soon I updated it, typescript kept complaining
> 
> > Cannot find module '@adiwajshing/baileys-md' or its corresponding type declarations .ts(2307)
> 
> I did not know what went wrong, so I tried creating a new project and added baileys-md to it, unfortunately it's still the same
> 
> can you give me some insights?

rm -rf node_modules/@adiwajshing/baileys-md 
yarn upgrade @adiwajshing/baileys-md

**Comment by aderayendra** [comment]
> > so on 21st Dec 2021 I installed baileys-md using
> > 
> > > yarn add github:adiwajshing/baileys#multi-device
> > 
> > It worked great until today, today I saw you just committed few changes so I decided to update the baileys-md as well, as soon I updated it, typescript kept complaining
> > 
> > > Cannot find module '@adiwajshing/baileys-md' or its corresponding type declarations .ts(2307)
> > 
> > I did not know what went wrong, so I tried creating a new project and added baileys-md to it, unfortunately it's still the same
> > 
> > can you give me some insights?
> 
> rm -rf node_modules/@adiwajshing/baileys-md 
> yarn upgrade @adiwajshing/baileys-md

Unfortunately it doesn't help, I did mention that I created a whole new project and added baileys-md to it, but typescript complaint the same

**Comment by JeanJunior18** [comment]
Same issue

**Comment by PurpShell** [comment]
Guys

**Comment by PurpShell** [comment]
Missing something?

**Comment by PurpShell** [comment]
> **__I install baileys-MD/baileys and it is giving me a cannot find import error (or main property error on CJS)__**
> //
> __**"lib" folder missing after installation from github**__

> Just do: `cd node_modules/@adiwajshing/[baileys-md or baileys]` then `npm i typescript -g` then `tsc`

Taken from WAWebSockets at [`#faq`](https://discord.com/channels/725839806084546610/855153774841298994/903369123000614972), join [here](https://discord.gg/WeJM5FP9GG)

**Comment by Flam3rboy** [comment]
@PurpShell I've tried your solution, however I get these type errors:
```ts
src/LegacySocket/auth.ts:7:7 - error TS2742: The inferred type of 'makeAuthSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

7 const makeAuthSocket = (config: LegacySocketConfig) => {
        ~~~~~~~~~~~~~~

src/LegacySocket/chats.ts:6:7 - error TS2742: The inferred type of 'makeChatsSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

6 const makeChatsSocket = (config: LegacySocketConfig) => {
        ~~~~~~~~~~~~~~~

src/LegacySocket/groups.ts:6:7 - error TS2742: The inferred type of 'makeGroupsSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

6 const makeGroupsSocket = (config: LegacySocketConfig) => {
        ~~~~~~~~~~~~~~~~

src/LegacySocket/index.ts:5:7 - error TS2742: The inferred type of 'makeLegacySocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

5 const makeLegacySocket = (config: Partial<LegacySocketConfig>) => (
        ~~~~~~~~~~~~~~~~

src/LegacySocket/messages.ts:15:7 - error TS2742: The inferred type of 'makeMessagesSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

15 const makeMessagesSocket = (config: LegacySocketConfig) => {
         ~~~~~~~~~~~~~~~~~~

src/Socket/chats.ts:11:14 - error TS2742: The inferred type of 'makeChatsSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

11 export const makeChatsSocket = (config: SocketConfig) => {
                ~~~~~~~~~~~~~~~

src/Socket/groups.ts:6:14 - error TS2742: The inferred type of 'makeGroupsSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

6 export const makeGroupsSocket = (config: SocketConfig) => {
               ~~~~~~~~~~~~~~~~

src/Socket/index.ts:6:7 - error TS2742: The inferred type of 'makeWASocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

6 const makeWASocket = (config: Partial<SocketConfig>) => (
        ~~~~~~~~~~~~

src/Socket/messages-recv.ts:26:14 - error TS2742: The inferred type of 'makeMessagesRecvSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

26 export const makeMessagesRecvSocket = (config: SocketConfig) => {
                ~~~~~~~~~~~~~~~~~~~~~~

src/Socket/messages-send.ts:10:14 - error TS2742: The inferred type of 'makeMessagesSocket' cannot be named without a reference to '@adiwajshing/baileys/node_modules/@types/ws'. This is likely not portable. A type annotation is necessary.

10 export const makeMessagesSocket = (config: SocketConfig) => {
                ~~~~~~~~~~~~~~~~~~
```

**Comment by Flam3rboy** [comment]
ok I fixed it by adding a explicit return type to the makeSocket function:
```ts
export const makeSocket = ({
	waWebSocketUrl, 
	connectTimeoutMs, 
	logger, 
	agent, 
	keepAliveIntervalMs,
	version,
	browser,
	auth: initialAuthState,
	printQRInTerminal,
	defaultQueryTimeoutMs
}: SocketConfig): typeof makeSocket &  {ws: WebSocket} => {
```

**Comment by Inevitable-Dev** [comment]
@Flam3rboy Where did you add this code?

**Comment by Flam3rboy** [comment]
@Inevitable-Dev in src/Socket/socket.ts
