### ISSUE TITLE
MD - Can't sendMessage to all contact [BUG]

### ISSUE THREAD

**Issue by justClizz** [adiwajshing/Baileys#1069]
**Describe the bug**
If bot get trigger from contact A, he responds.
But, on other contacts, he don't responds.

**To Reproduce**
1. Running normal code
2. Don't see some error on the console
3. Send message to bot number
4. Bot number don't respons

**Expected behavior**
Bot number can answer all trigger

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like?
 
   logger: P({ level: 'fatal' }),
    auth: state,
    browser: ["AIKO WEB SERVICE","Safari","1.0.0"],

 - Do you have multiple clients on the same IP? Nope
 - Are you using a proxy? No

**Additional context**
(Nothing)

**Comment by justClizz** [comment]
Anyway, i use MD

**Comment by justClizz** [comment]
Ok, the bug just get dissapiering. Idk, but... Yeah. The bug solved

**Comment by ThisMe124** [comment]
WOKWOKWKKW
