### ISSUE TITLE
cannot connect when state=connecting

### ISSUE THREAD

**Issue by NezukoChans28** [adiwajshing/Baileys#1071]
![Screenshot_20211224-223321](https://user-images.githubusercontent.com/87556399/147362418-731914fc-1e53-4f95-a376-5f446ca5ee71.png)

I want to make an alternative to access the QR code via web localhost, but every time I want to request a QR code, it appears like this in my terminal

**Comment by adithadirizki** [comment]
you must to close the previous connection

**Comment by NezukoChans28** [comment]
What Do You Means?
