### ISSUE TITLE
Audio Send [BUG]

### ISSUE THREAD

**Issue by FoxyCodeX** [adiwajshing/Baileys#1076]
I get this Error when I want to send audio file from Website:
```js
/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:230
const { user, server } = (0, WABinary_1.jidDecode)(jid);
          ^

TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.
    at relayMessage (/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:230:17)
    at Object.sendMessage (/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:391:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And, this is my code:
```js
mp3 = await getBuffer(anu.result.audio.link)
            teks = `*✨┃Here\'s your music!*`
            m.reply(m.chat, teks)
            codex.sendMessage(
    m.chat, 
    { audio: { url: mp3 }, mimetype: 'audio/mp4' },
    { url: mp3 }
)
```

I hope you can help, thx! :)

**Comment by DikaArdnt** [comment]
> I get this Error when I want to send audio file from Website:
> 
> ```js
> /data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:230
> const { user, server } = (0, WABinary_1.jidDecode)(jid);
>           ^
> 
> TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.
>     at relayMessage (/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:230:17)
>     at Object.sendMessage (/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:391:23)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> And, this is my code:
> 
> ```js
> mp3 = await getBuffer(anu.result.audio.link)
>             teks = `*✨┃Here\'s your music!*`
>             m.reply(m.chat, teks)
>             codex.sendMessage(
>     m.chat, 
>     { audio: { url: mp3 }, mimetype: 'audio/mp4' },
>     { url: mp3 }
> )
> ```
> 
> I hope you can help, thx! :)

if you want to send audio through buffer you should use

let buffer = await getBuffer(url)
conn.sendMessage(m.chat, { audio: buffer, mimetype: 'audio/mp4' }, { quoted: m })

**Comment by FoxyCodeX** [comment]
> if you want to send audio through buffer you should use
> 
> let buffer = await getBuffer(url) conn.sendMessage(m.chat, { audio: buffer, mimetype: 'audio/mp4' }, { quoted: m })

Alr, but still error

**Comment by DikaArdnt** [comment]
> > if you want to send audio through buffer you should use
> > let buffer = await getBuffer(url) conn.sendMessage(m.chat, { audio: buffer, mimetype: 'audio/mp4' }, { quoted: m })
> 
> Alr, but still error

more stable using url

Example:
conn.sendMessage(m.chat, { audio: { url: 'https://btones.b-cdn.net/fetch/14/145257dd66fb8861c646b06fe70bae2a.mp3' }, mimetype: 'audio/mpeg' }, { quoted: m })
Or
conn.sendMessage(m.chat, { audio: { url: './example.mp3' }, mimetype: 'audio/mpeg' }, { quoted: m })

**Comment by PurpShell** [comment]
> > I get this Error when I want to send audio file from Website:
> > ```js
> > /data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:230
> > const { user, server } = (0, WABinary_1.jidDecode)(jid);
> >           ^
> > 
> > TypeError: Cannot destructure property 'user' of '(0 , WABinary_1.jidDecode)(...)' as it is undefined.
> >     at relayMessage (/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:230:17)
> >     at Object.sendMessage (/data/data/com.termux/files/home/CodeX/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-send.js:391:23)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And, this is my code:
> > ```js
> > mp3 = await getBuffer(anu.result.audio.link)
> >             teks = `*✨┃Here\'s your music!*`
> >             m.reply(m.chat, teks)
> >             codex.sendMessage(
> >     m.chat, 
> >     { audio: { url: mp3 }, mimetype: 'audio/mp4' },
> >     { url: mp3 }
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope you can help, thx! :)
> 
> if you want to send audio through buffer you should use
> 
> let buffer = await getBuffer(url) conn.sendMessage(m.chat, { audio: buffer, mimetype: 'audio/mp4' }, { quoted: m })

buffers are bad, use a stream :+1:

**Comment by DikaArdnt** [comment]
Close
