### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qiedanz** [adiwajshing/Baileys#1077]
![](https://d.top4top.io/p_2185zbram1.png)
I don't run this script

**Comment by FoxyCodeX** [comment]
> ![](https://camo.githubusercontent.com/f2e000c01d7ccd21365cb4e9f4def2d87919426520b947e46d4fea655cee7d27/68747470733a2f2f642e746f7034746f702e696f2f705f323138357a6272616d312e706e67) I don't run this script

Have you installed the @adiwajshing/baileys package?

**Comment by mateuscdor** [comment]
> > ![](https://camo.githubusercontent.com/f2e000c01d7ccd21365cb4e9f4def2d87919426520b947e46d4fea655cee7d27/68747470733a2f2f642e746f7034746f702e696f2f705f323138357a6272616d312e706e67) I don't run this script
> 
> Have you installed the @adiwajshing/baileys package?

This error appears when it doesn't compile a lib

**Comment by qiedanz** [comment]
> > ![](https://camo.githubusercontent.com/f2e000c01d7ccd21365cb4e9f4def2d87919426520b947e46d4fea655cee7d27/68747470733a2f2f642e746f7034746f702e696f2f705f323138357a6272616d312e706e67) Saya tidak menjalankan skrip ini
> 
> Sudahkah Anda menginstal paket @adiwajshing/baileys?

I did, but when I checked the module lib directory, it wasn't there, why is that?

**Comment by qiedanz** [comment]
> > ![](https://camo.githubusercontent.com/f2e000c01d7ccd21365cb4e9f4def2d87919426520b947e46d4fea655cee7d27/68747470733a2f2f642e746f7034746f702e696f2f705f323138357a6272616d312e706e67) I don't run this script
> 
> Have you installed the @adiwajshing/baileys package?

I did, but when I check the module lib directory, it's not there, why is that?

**Comment by PurpShell** [comment]
> **__I install baileys-MD/baileys and it is giving me a cannot find import error (or main property error on CJS)__**
> //
> __**"lib" folder missing after installation from github**__

> Just do: cd node_modules/@adiwajshing/baileys-md or baileys then npm i typescript -g then tsc

Taken from WAWebSockets at [`#faq`](https://discord.com/channels/725839806084546610/855153774841298994/903369123000614972), join [here](https://discord.gg/WeJM5FP9GG)

**Comment by qiedanz** [comment]
thanks
