### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by olab-dev** [adiwajshing/Baileys#1080]
Minta nomor rehan wangsaft banj adishungsing ☝️😅

**Comment by Zobin33** [comment]
> Minta nomor rehan wangsaft banj adishungsing ☝️😅

it's not funny

**Comment by DikaArdnt** [comment]
> Minta nomor rehan wangsaft banj adishungsing ☝️😅

Close

**Comment by olab-dev** [comment]
ga bisa diajak becanda ajg

**Comment by Zobin33** [comment]
> ga bisa diajak becanda ajg

Lawak Open Issue Kek Bocil Baru lahir, dikira ini tempat chat
