### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fatur-wabotaq** [adiwajshing/Baileys#1081]
Woi banj bogor,lop yu adishingsunj 😘🥰😍🤩

**Comment by fatur-wabotaq** [comment]
> Woi banj bogor,lop yu adishingsunj 😘🥰😍🤩

muach 😍🥳

**Comment by fatur-wabotaq** [comment]
Galang cepu ajg ga jadi fitnah xfar kontol anak pepek

**Comment by xfar05** [comment]
> Galang cepu ajg ga jadi fitnah xfar kontol anak pepek

Pepek mamak kau, kau kira lawakan fitnah2 orang pepek,mana wa kau sini kalo ga seneng

**Comment by xfar05** [comment]
> Galang cepu ajg ga jadi fitnah xfar kontol anak pepek

Send no wa kau sini kontol

**Comment by xfar05** [comment]
Dikira tempat maen2 disinj ajg
