### ISSUE TITLE
[BUG - MD] TypeError: Cannot destructure property 'mediaKey' of 'object null' as it is null.

### ISSUE THREAD

**Issue by JonazBR** [adiwajshing/Baileys#1082]
![image](https://user-images.githubusercontent.com/56744848/147391627-9b74489a-004b-4daa-8c2e-ceec9d3303d9.png)
![image](https://user-images.githubusercontent.com/56744848/147391637-de9ca194-85eb-4555-bd81-9dd31183e9be.png)
![image](https://user-images.githubusercontent.com/56744848/147391645-72cefc65-d9c1-4aa3-b72d-2081961d2321.png)

**Comment by PurpShell** [comment]
literally just get the stream, what are you even doing
