### ISSUE TITLE
Could not find a declaration file 

### ISSUE THREAD

**Issue by imReCoder** [adiwajshing/Baileys#1085]
Can anyone heplp regarding this error ?

 Starting compilation in watch mode...

node_modules/@adiwajshing/baileys-md/lib/WABinary/index.d.ts(17,24): error TS7016: Could not find a declaration file for module '../../WABinary/Binary'. 'D:/Projects/Whatsapp Sender New/whatsapp-sender-backend/node_modules/@adiwajshing/baileys-md/WABinary/Binary.js' implicitly has an 'any' type.

4:19:49 PM - Found 1 error. Watching for file changes.

Code---------------------------------------------------------------------------------------------------------------------------------

```

import { Boom } from "@hapi/boom"
import makeWASocket, { DisconnectReason, AnyMessageContent, delay, useSingleFileAuthState } from '@adiwajshing/baileys-md'
import P from "pino"

const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')

// start a connection
const startSock = () => {

const sock = makeWASocket({
    logger: P({ level: 'trace' }),
    printQRInTerminal: true,
    auth: state,
    // implement to handle retries
    getMessage: async (key) => {
        return {
            conversation: 'hello'
        }
    }
})

const sendMessageWTyping = async(msg: AnyMessageContent, jid: string) => {
    await sock.presenceSubscribe(jid)
    await delay(500)

    await sock.sendPresenceUpdate('composing', jid)
    await delay(2000)

    await sock.sendPresenceUpdate('paused', jid)

    await sock.sendMessage(jid, msg)
}

sock.ev.on('messages.upsert', async (m:any) => {
    console.log(JSON.stringify(m, undefined, 2))
    
    const msg = m.messages[0]
    if(!msg.key.fromMe && m.type === 'notify') {
        console.log('replying to', m.messages[0].key.remoteJid)
        await sock!.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])
        await sendMessageWTyping({ text: 'Hello there!' }, msg.key.remoteJid)
    }
    
})

sock.ev.on('messages.update', m => console.log(m))
sock.ev.on('presence.update', m => console.log(m))
sock.ev.on('chats.update', m => console.log(m))
sock.ev.on('contacts.update', m => console.log(m))

sock.ev.on('connection.update', (update) => {
    const { connection, lastDisconnect } = update
    if(connection === 'close') {
        // reconnect if not logged out
        if((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {
            startSock()
        } else {
            console.log('connection closed')
        }
    }
    
    console.log('connection update', update)
})
// listen for when the auth credentials is updated
sock.ev.on('creds.update', saveState)

return sock
}

startSock()
```

**Comment by mateuscdor** [comment]
you need to post script.
there's no way to help without the code.

**Comment by imReCoder** [comment]
> you need to post script. there's no way to help without the code.

// import P from "pino"
import { Boom } from "@hapi/boom"
import makeWASocket, { DisconnectReason, AnyMessageContent, delay, useSingleFileAuthState } from '@adiwajshing/baileys-md'
import P from "pino"

const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')

// start a connection
const startSock = () => {
    
    const sock = makeWASocket({
        logger: P({ level: 'trace' }),
        printQRInTerminal: true,
        auth: state,
        // implement to handle retries
        getMessage: async (key) => {
            return {
                conversation: 'hello'
            }
        }
    })

    const sendMessageWTyping = async(msg: AnyMessageContent, jid: string) => {
        await sock.presenceSubscribe(jid)
        await delay(500)

        await sock.sendPresenceUpdate('composing', jid)
        await delay(2000)

        await sock.sendPresenceUpdate('paused', jid)

        await sock.sendMessage(jid, msg)
    }
    
    sock.ev.on('messages.upsert', async (m:any) => {
        console.log(JSON.stringify(m, undefined, 2))
        
        const msg = m.messages[0]
        if(!msg.key.fromMe && m.type === 'notify') {
            console.log('replying to', m.messages[0].key.remoteJid)
            await sock!.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])
            await sendMessageWTyping({ text: 'Hello there!' }, msg.key.remoteJid)
        }
        
    })

    sock.ev.on('messages.update', m => console.log(m))
    sock.ev.on('presence.update', m => console.log(m))
    sock.ev.on('chats.update', m => console.log(m))
    sock.ev.on('contacts.update', m => console.log(m))

    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            // reconnect if not logged out
            if((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {
                startSock()
            } else {
                console.log('connection closed')
            }
        }
        
        console.log('connection update', update)
    })
    // listen for when the auth credentials is updated
    sock.ev.on('creds.update', saveState)

    return sock
}

startSock()

**Comment by imReCoder** [comment]
> you need to post script. there's no way to help without the code.

i have added the code can you please check what i am doing wrong

**Comment by imReCoder** [comment]
if anyone with same problem, just add this in your tsconfig file

**Comment by networkException** [comment]
Why is this closed? It's obviously not a solution to disable type checking here.
