### ISSUE TITLE
One thumbnail and caption for all messages in a loop

### ISSUE THREAD

**Issue by tmandinyenya** [adiwajshing/Baileys#109]
`
data.jsonData.forEach(async element => {

                    let responseFile = await axios.get(element.sourceFilePath, {responseType: 'arraybuffer'})
                    let bufferFile = Buffer.from(responseFile.data,"utf-8")
                    content = bufferFile

                    let fileLink = element.sourceFilePath
                    let myarr = fileLink.split(".");
    
                    let fileExtension = myarr[1]

                    if(fileExtension == "jpg" || fileExtension == "jpeg")
                    {
                        options.mimetype = 'image/jpeg'
                    }
                    else if(fileExtension == "png")
                    {
                        options.mimetype = 'image/png'
                    }
                    else if(fileExtension == "gif")
                    {
                        options.mimetype = 'video/gif'
                    }

                    options.filename = "profile-pic"+Math.floor(Math.random() * 1000)+"."+fileExtension
                    options.caption = element.caption
                    type = MessageType.image

                   const response = await client.sendMessage(m.key.remoteJid, content, type, options)
                   console.log("sent message with ID '" + response.messageID + "' successfully: " + (response.status === 200))

                });`
For all messages sent in the loop they have the same caption and thumbnail. The files are different as well as caption. Am I missing something, Please assist.

**Comment by adiwajshing** [comment]
The problem is that you're mutating the same object while the operation is going on. This should fix:

``` ts

data.jsonData.forEach(async element => {

                let responseFile = await axios.get(element.sourceFilePath, {responseType: 'arraybuffer'})
                let bufferFile = Buffer.from(responseFile.data,"utf-8")
                // declare the variable inside
                const content = bufferFile

                let fileLink = element.sourceFilePath
                let myarr = fileLink.split(".");

                let fileExtension = myarr[1]
                // declare the variable inside
               const options = {}

                if(fileExtension == "jpg" || fileExtension == "jpeg")
                {
                    options.mimetype = 'image/jpeg'
                }
                else if(fileExtension == "png")
                {
                    options.mimetype = 'image/png'
                }
                else if(fileExtension == "gif")
                {
                    options.mimetype = 'video/gif'
                }

                options.filename = "profile-pic"+Math.floor(Math.random() * 1000)+"."+fileExtension
                options.caption = element.caption
                type = MessageType.image

               const response = await client.sendMessage(m.key.remoteJid, content, type, options)
               console.log("sent message with ID '" + response.messageID + "' successfully: " + (response.status === 200))
})

```

**Comment by tmandinyenya** [comment]
Thank you so much. I really appreciate its now working. Im closing.
