### ISSUE TITLE
PDF file preview not show

### ISSUE THREAD

**Issue by mi-khatri** [adiwajshing/Baileys#1090]
hello everyone,
when i try to send pdf file in msg then there is not generate pdf preview on receiver side.
I try all of the code above but no result

My code is
"con.sendMessage( jid , { url: urls }, MessageType.document, { caption: "", mimetype: Mimetype.pdf, filename: "File.pdf", thumbnail: jpegBase64 })"

but no luck

Please help

**Comment by mateuscdor** [comment]
Thumbnail?
