### ISSUE TITLE
iphone users can't hear mp3

### ISSUE THREAD

**Issue by minanseo** [adiwajshing/Baileys#1091]
Hello  audio MP3 cant work on iphone users

Any suggestions?

`export async function sendMessageAudioText(conn, groups, audioBuffer, text) {
  await conn.connect()
  return new Promise(async function (resolve, reject) {
    for (var i = 0; i < groups.length; i++) {
     await conn.sendMessage(groups[i], audioBuffer, MessageType.audio, { mimetype: Mimetype.mp4Audio })
      console.log('sent to group : ' + groups[i])
    }
    resolve(groups)`

**Comment by BochilGaming** [comment]
Convert your audio using ffmpeg
```
ffmpeg -i -y original.mp3  -vn -ar 44100 -ac 2 -b:a 192k encode.mp3 
```

**Comment by minanseo** [comment]
> Convert your audio using ffmpeg
> 
> ```
> ffmpeg -i -y original.mp3  -vn -ar 44100 -ac 2 -b:a 192k encode.mp3 
> ```

Thanks gan, i will try

**Comment by mateuscdor** [comment]
close issue

**Comment by VEXG** [comment]
ios user cannot use mp4/audio mimetype format, instead use document type and use the mp3 mimetype

**Comment by rn0x** [comment]
Create a new folder eg files
Inside the files folder make a bash script
Name it ffmpeg.sh and put the code below
Then put the audio files that you want to work on iPhone into the files folder
And run the script sh ffmpeg.sh or bash ffmpeg.sh


```bash
#!/bin/bash
echo "Welcome to use ffmpeg-sh!"

mkdir ./backup

for file in ./*.mp3
do
  if test -f $file; then
    echo "============= $file start compressing =================="
    ffmpeg -i $file -vn -ab 128k -ar 44100 -f ipod "$file.mp3"
    mv $file backup && mv "$file.mp3" $file
  fi
done

echo "Congratulations, all files have been done for you!"
```

**Comment by r-po** [comment]
> Create a new folder eg files Inside the files folder make a bash script Name it ffmpeg.sh and put the code below Then put the audio files that you want to work on iPhone into the files folder And run the script sh ffmpeg.sh or bash ffmpeg.sh
> 
> ```shell
> #!/bin/bash
> echo "Welcome to use ffmpeg-sh!"
> 
> mkdir ./backup
> 
> for file in ./*.mp3
> do
>   if test -f $file; then
>     echo "============= $file start compressing =================="
>     ffmpeg -i $file -vn -ab 128k -ar 44100 -f ipod "$file.mp3"
>     mv $file backup && mv "$file.mp3" $file
>   fi
> done
> 
> echo "Congratulations, all files have been done for you!"
> ```

We've tried this solution but -f ipod is not being recognized, any suggestions?

**Comment by vyxxr** [comment]
Anyone solved this problem? I tried all solutions above, but still not working.

**Comment by textarea** [comment]
Try with mp4
