### ISSUE TITLE
unexpected error: TypeError: makeWASocket is not a function

### ISSUE THREAD

**Issue by babakmhz** [adiwajshing/Baileys#1092]
Hi there!

As explained in Readme.md on "multi-device" branch I'm trying to make a socket and connect to WhatsApp web via this code:

`import makeWASocket from '@adiwajshing/baileys-md'

 const sock = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true
    })`

and here's the result => unexpected error: TypeError: makeWASocket is not a function.
any suggestions?

Thanks.

**Comment by unknowkzr** [comment]
> Hi there!
> 
> As explained in Readme.md on "multi-device" branch I'm trying to make a socket and connect to WhatsApp web via this code:
> 
> `import makeWASocket from '@adiwajshing/baileys-md'
> 
> const sock = makeWASocket({ // can provide additional config here printQRInTerminal: true })`
> 
> and here's the result => unexpected error: TypeError: makeWASocket is not a function. any suggestions?
> 
> Thanks.

try require()

**Comment by reinforcers** [comment]
> > Hi there!
> > As explained in Readme.md on "multi-device" branch I'm trying to make a socket and connect to WhatsApp web via this code:
> > `import makeWASocket from '@adiwajshing/baileys-md'
> > const sock = makeWASocket({ // can provide additional config here printQRInTerminal: true })`
> > and here's the result => unexpected error: TypeError: makeWASocket is not a function. any suggestions?
> > Thanks.
> 
> try require()

I have same problem, I try require and still got the error makeWASocket is not a function. using @adiwajshing/baileys@4.0.0 from npm
`const makeWASocket = require('@adiwajshing/baileys')
const sock = makeWASocket({ printQRInTerminal: true })`

**Comment by KENPRAEL** [comment]
Hi @babakmhz , is there any solution for fixed this case?

**Comment by isoazevedo** [comment]
I had the same problem and after searching I found this solution .

const makeWASocket = require('@adiwajshing/baileys').default;

**Comment by h4775346** [comment]
> I had the same problem and after searching I found this solution .
> 
> const makeWASocket = require('@adiwajshing/baileys').default;

Perfect, That Works for me

**Comment by elbiozard** [comment]
Hello!
I have the same problem. Where do I embed this snippet? "const makeWASocket = require('@adiwajshing/baileys').default;"
I included it in the example.ts file and I have the same error.

**Comment by agungprayogi291** [comment]
i have the same proble .
const makeWASocket = require('@adiwajshing/baileys').default;

**Comment by Simoncosta** [comment]
I have the same problem.
const makeWASocket = require('@adiwajshing/baileys').default;

**Comment by 19Maury85** [comment]
me too

**Comment by reinforcers** [comment]
update, using @adiwajshing/baileys@4.1.0 from npm js I change to this

```
const makeWASocket = require('@adiwajshing/baileys').default
const { DisconnectReason } = require('@adiwajshing/baileys')
const { Boom } = require('@hapi/boom')

async function connectToWhatsApp () {
    const sock = makeWASocket({
        // can provide additional config here
        printQRInTerminal: true
    })
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ' + lastDisconnect.error + ', reconnecting ' + shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        } 
    })
    sock.ev.on('messages.upsert', async (m) => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        await sock.sendMessage(m.messages[0].key.remoteJid, { text: 'Hello there!' })
    })
}
// run in main file
connectToWhatsApp()
```
run the code without error on node 16 but can't login, keep generating new QR

**Comment by reinforcers** [comment]
> I have the same problem @reinforcers. Any news about this?

basically you need the auth option to be able to login. so, combine the basic above with the `useSingleFileAuthState` described on the docs this what I got
```
const makeWASocket = require('@adiwajshing/baileys').default
const { DisconnectReason, useSingleFileAuthState } = require('@adiwajshing/baileys')
const { Boom } = require('@hapi/boom')
const fs = require('fs')

async function connectToWhatsApp () {
    const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')
    // will use the given state to connect
    // so if valid credentials are available -- it'll connect without QR
    const sock = makeWASocket({
        // can provide additional config here
        auth: state,
        printQRInTerminal: true
    })
    // this will be called as soon as the credentials are updated
    sock.ev.on('creds.update', saveState)
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ' + lastDisconnect.error + ', reconnecting ' + shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        } 
    })
    sock.ev.on('messages.upsert', async (m) => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        await sock.sendMessage(m.messages[0].key.remoteJid, { text: 'Hello there!' })
    })
}
// run in main file
connectToWhatsApp()
```

**Comment by pkral3** [comment]
just use:
import makeWASocket from '@adiwajshing/baileys'
const sock = makeWASocket.default()
