### ISSUE TITLE
[MD] How to detect if a message is an image?

### ISSUE THREAD

**Issue by justClizz** [adiwajshing/Baileys#1097]
How to detect if a message is an image?

Example: I send some image message, and the code will respond by sending

**Comment by VEXG** [comment]
just add "[MD]" in ur title to know that u are using bail MD

**Comment by justClizz** [comment]
> just add "[MD]" in ur title to know that u are using bail MD

ok

**Comment by DikaArdnt** [comment]
> How to detect if a message is an image?
> 
> Example: I send some image message, and the code will respond by sending

type = Object.keys(mek.message)[0]
if (type == 'imageMessage') {
    console.log('this is image')
} else console.log('not image')

this is the method i use

**Comment by justClizz** [comment]
> > How to detect if a message is an image?
> > Example: I send some image message, and the code will respond by sending
> 
> type = Object.keys(mek.message)[0] if (type == 'imageMessage') { console.log('this is image') } else console.log('not image')
> 
> this is the method i use

ok, thats work! Thanks!

**Comment by justClizz** [comment]
One more thing, how to download media from chat?

**Comment by mateuscdor** [comment]
https://github.com/adiwajshing/baileys/tree/multi-device#downloading-media-messages
Check the developer's page

**Comment by justClizz** [comment]
> https://github.com/adiwajshing/baileys/tree/multi-device#downloading-media-messages Check the developer's page

its not working

**Comment by mateuscdor** [comment]
@justClizz  
client.ev.on('messages.upsert', async (m) => 
 {
    const msg = m.messages[0]  
    const type = Object.keys(msg.message)[0]
    if( type == 'imageMessage' ) {.....}
})

**Comment by justClizz** [comment]
> @justClizz client.ev.on('messages.upsert', async (m) => { const msg = m.messages[0] const type = Object.keys(msg.message)[0] if( type == 'imageMessage' ) {.....} })
> 
> > 'conversation'
> > 'imageMessage'
> > 'videoMessage'
> > 'documentMessage'
> > 'extendedTextMessage'
> > 'buttonsResponseMessage'
> > 'listResponseMessage'
> > 'templateButtonReplyMessage'
> > 'messageContextInfo'

```
        client.ev.on('messages.upsert', async (m) =>
{
const msg = m.messages[0]
const type = Object.keys(msg.message)[0]
if( type == 'imageMessage' ){
const stream = await downloadContentFromMessage(m.message.imageMessage, 'image')
        let buffer = Buffer.from([])
        for await(const chunk of stream) {
            buffer = Buffer.concat([buffer, chunk])
        }

        await writeFile('./my-download.jpeg', buffer)
}
```
        
like this?
