### ISSUE TITLE
onDisconnect

### ISSUE THREAD

**Issue by keef3ar** [adiwajshing/Baileys#11]
onDisconnect event isn't works when disable network on connected phone

**Comment by adiwajshing** [comment]
onDisconnect () works when one loses the internet connection on the device running Baileys. However, if you want to check if the phone is connected, you can run the following query:

``` javascript
    client.query (["admin", "test"])
    .then ([response, q] => {
        console.log ("connected to phone: " + response.Pong)
    })
```

Though it'll timeout when you're not connected to the phone, in which case there won't be a response. I'll implement a timeout functionality for this and #12

**Comment by adiwajshing** [comment]
A timeout is implemented in the latest version. Closing this.
