### ISSUE TITLE
How to send audioMessage?

### ISSUE THREAD

**Issue by gfarias** [adiwajshing/Baileys#110]
We can't find an example of how to send an audioMessage. We are recording via browser with mic permission and it returns a .wav file which we're trying to send as follows:
```javascript
const filebuffer = ... // our array buffer from websocket (audio/wav)
const id = 'abcd@s.whatsapp.net'
const buffer = Buffer.from(filebuffer, "binary")
conn.sendMessage(id, buffer, MessageType.audio, { mimetype: 'audio/wav' })
  .then(async ( m ) => {})
  .catch((e) => console.log(e))
```

But we're getting the following error:
```javascript
Error: Unexpected status code: 400
    at ....../node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:121:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Your guidance is greatly appreciated.

**Comment by adiwajshing** [comment]
As far as I know, WA supports only `mp3` files -- so you'll have to convert to mp3 before sending. Or you can send the audio as `MessageType.document`

**Comment by gfarias** [comment]
Thanks for the fast response. We've tried sending as document but the end user receives it as an attachment, not as a voice message. I'll try sending as mp3 and I'll update the conversation for future reference.

**Comment by gfarias** [comment]
I can confirm that sending an mp3 file as audioMessage works good. Closing the issue.

**Comment by gfarias** [comment]
I'm reopening this issue because even when sending an mp3 file it has differences with an audioMessage sent from the mobile application, see the following:

The first one was sent with iPhone and the second one via Baileys. One has my avatar and duration and the other one doesn't. Any ideas?

![Audios](https://inteam-assets.s3.amazonaws.com/IMG_1022.jpg)

**Comment by gfarias** [comment]
Reopening

**Comment by adiwajshing** [comment]
Interesting, I'll look into it

**Comment by adiwajshing** [comment]
@gfarias so, I had a chance to look at this issue -- I never receive audio messages with a thumbnail -- neither am I able to send audio messages with a thumbnail. If you could possibly provide the message body of the audio message with the thumbnail, I could possibly reproduce

**Comment by sostenesapollo** [comment]
i'm getting the same error..

**Comment by arakattack** [comment]
It works but audio wave is missing.
