### ISSUE TITLE
[MD] Cant scanning

### ISSUE THREAD

**Issue by unknowkzr** [adiwajshing/Baileys#1100]
Hi I try scanning more than 10x
but always error
even the session is not save
here the picture of error
it say 410 error restart required()
![Screenshot_20211230-102159_Termux](https://user-images.githubusercontent.com/76149388/147719431-e23fc83c-c329-4573-b600-4e0416152a9d.jpg)

**Comment by mateuscdor** [comment]
this message is not an error and it is also not a bug.

your init script is incorrect.

use the example provided.

**Comment by unknowkzr** [comment]
> this message is not an error and it is also not a bug.
> 
> your init script is incorrect.
> 
> use the example provided.

init script?
do you mean the makeWAsocket?

**Comment by mateuscdor** [comment]
https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts

**Comment by unknowkzr** [comment]
> https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts

Im sorry
that not resolve my problem
it still stuck cant login

**Comment by mateuscdor** [comment]
Check your device if you are using the sd or md version?

 if (connection === 'close')
 {          
   lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut ? startSock() : console.log(...)
}

Poste seu código ou projeto no github para analisarmos..

**Comment by BochilGaming** [comment]
> > https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts
> 
> Im sorry that not resolve my problem it still stuck cant login

You need restart your socket after connect,  see example.ts

**Comment by unknowkzr** [comment]
> > > https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts
> > 
> > 
> > Im sorry that not resolve my problem it still stuck cant login
> 
> You need restart your socket after connect, see example.ts

Restart socket?
im use Shiraori-MD
Can you tell me?

**Comment by BochilGaming** [comment]
> > > > https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts
> > > 
> > > 
> > > Im sorry that not resolve my problem it still stuck cant login
> > 
> > 
> > You need restart your socket after connect, see example.ts
> 
> Restart socket? im use Shiraori-MD Can you tell me?

https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts#L56

**Comment by unknowkzr** [comment]
> > > > > https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts
> > > > 
> > > > 
> > > > Im sorry that not resolve my problem it still stuck cant login
> > > 
> > > 
> > > You need restart your socket after connect, see example.ts
> > 
> > 
> > Restart socket? im use Shiraori-MD Can you tell me?
> 
> https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts#L56 that code will restart socket

Wtf??!!!
