### ISSUE TITLE
how to check number its use whatsapp or not

### ISSUE THREAD

**Issue by Cloud-Dark** [adiwajshing/Baileys#1101]
hi dear, i want to ask
how to check on number use whatsapp or not?
thanks

**Comment by DikaArdnt** [comment]
> hi dear, i want to ask how to check on number use whatsapp or not? thanks

maybe what you mean is
conn.isOnWhatsApp('62xxx')

**Comment by KENPRAEL** [comment]
const exists = await conn.isOnWhatsApp(waNumber);
if (exists) {
	console.log('Use whatsapp');
} else {
	console.log('Not use whatsapp');
}
