### ISSUE TITLE
How to Stop QR Generating

### ISSUE THREAD

**Issue by KENPRAEL** [adiwajshing/Baileys#1102]
Hi Sir,

after connect, can not stop QR even by closing the connection, the QR generation keep running even until Too Many Request error.

If user not scan the QR will be problem because can not stop QR Generating. How to stop it?

I'm sorry for my mistake add Bug label for this question. This is just question not Bug.

Thank you

**Comment by babakmhz** [comment]
Hi there,

Is that multi-device branch that you are using?

**Comment by KENPRAEL** [comment]
Hi,
No, I'm not.
