### ISSUE TITLE
[BUG] [MD] _a.child is not a function

### ISSUE THREAD

**Issue by DentaStudio** [adiwajshing/Baileys#1104]
![image](https://user-images.githubusercontent.com/69065410/147737464-c01f705f-0f03-4a26-af57-66044198f036.png)

how to fix that?

**Comment by jackcokk** [comment]
![image](https://user-images.githubusercontent.com/91759091/147826510-8f0df5c6-0e2b-47ff-bff9-6be39cc2023b.png)

**Comment by DentaStudio** [comment]
> ![image](https://user-images.githubusercontent.com/91759091/147826510-8f0df5c6-0e2b-47ff-bff9-6be39cc2023b.png)

![image](https://user-images.githubusercontent.com/69065410/147838489-572202fa-6a5d-4ff9-b601-b489d0c0cb97.png)

**Comment by DentaStudio** [comment]
![Screenshot_2022-01-29-20-13-32-62.jpg](https://user-images.githubusercontent.com/69065410/151660596-7e4783ac-4ec8-465f-9167-ecfd713ec420.jpg)

yeah, i get this bug again in baileys new version

**Comment by jackcokk** [comment]
This is unlikely an issue with Baileys but rather with your npm. Can you show us how you added Baileys to your project?

**Comment by DentaStudio** [comment]
```javascript
.....

//MAIN MODULE
const baileys = global.baileys = require("@adiwajshing/baileys");

//
const fs = require("fs");
const util = require('util');
const moment = require("moment-timezone");
const path = require("path");
const os = require("os")

.....
```

**Comment by DentaStudio** [comment]
im add the module with yarn
and build with tsc

**Comment by DentaStudio** [comment]
- @jackcokk 

nevermind, okay i have found the solution. it turned out that the problem was in the logger, and I entered my logger so it wouldn't spam the console, so I reprogrammed it and that's where the problem is. sorrry :D
