### ISSUE TITLE
[MD][Questions] How to track the moment of scanning QR on the device in events?

### ISSUE THREAD

**Issue by Diden05** [adiwajshing/Baileys#1106]
%subj%

**Comment by PurpShell** [comment]
You automatically get logged in

**Comment by Diden05** [comment]
> You automatically get logged in

yes, but I need to track the status for the connected app, qr scan, connected, disconnected, etc.

**Comment by mateuscdor** [comment]
@Diden05 
Check the repository
ViStepRU > callme > issue

**Comment by Diden05** [comment]
Thanks!
