### ISSUE TITLE
How can I identify broadcast messages

### ISSUE THREAD

**Issue by MarcosDLR** [adiwajshing/Baileys#1107]
I would like to ignore the broadcast messages from the chat-update event

**Comment by mateuscdor** [comment]
const msg = message.messages[0] 
client.ev.on('messages.upsert', async (message) =>
{
   if (msg.key && msg.key.remoteJid == 'status@broadcast') return
}

**Comment by MarcosDLR** [comment]
Thanks

**Comment by marcusgir** [comment]
How can I block the message from "status@broadcast"
