### ISSUE TITLE
[Feature suggestion] Package and release with CI

### ISSUE THREAD

**Issue by AZMCode** [adiwajshing/Baileys#111]
As it stands right now, the npm package builds itself on the target machine, instead of before publishing. Github actions could automatically build and package the specific files needed for a significant boost with respect to install time.

Github Actions could also build new documentation every time a push is made to master, and publish the docs in the project's Github Pages site.

I'm aware this is low priority, just thought to lease this here for when there's enough time.

**Comment by adiwajshing** [comment]
I really love the idea. Right now, I'm planning a V3 release with a bunch of really nice features like automatic chat & contact maintainence, phone pinging & an event emitter based syntax.

It would be great if you could contribute to the GitHub actions!

**Comment by AZMCode** [comment]
Ill do my best in my free time, chief!
I actually think i have a template for this
