### ISSUE TITLE
How to Get Sender Whatsapp Number?

### ISSUE THREAD

**Issue by KENPRAEL** [adiwajshing/Baileys#1110]
Hi Sir,

I'm not using MD version, how to get sender whatsapp number when sending the message or how to get connected phone whatsapp number?

**Comment by mateuscdor** [comment]
client.ev.on('messages.upsert', async (message) =>
{ .....
const msg = message.messages[0] 
msg.key.remoteJid // Retrun 


//Extra
     const isGroup       = msg.key.remoteJid.endsWith('@g.us')
      const isPrivate     = msg.key.remoteJid.endsWith('@s.whatsapp.net')

.....})

**Comment by KENPRAEL** [comment]
Sorry Sir, I am not using MD, how to do in standard version?

**Comment by mateuscdor** [comment]
> Desculpe senhor, não estou usando MD, como faço na versão padrão?

use legacy version

**Comment by imronpuji** [comment]
you can try it brooo,
const conn = new WAConnection() ;

   await conn.on('open', async () => {
	    // save credentials whenever updated
	    console.log (`credentials updated!`)
	    const authInfo = await conn.base64EncodedAuthInfo() // get all the auth info we need to restore this session
	    let user = await conn.user
	   	console.log(user)
	   
	})

**Comment by imronpuji** [comment]
you can get the number when you have scanned your qr code

**Comment by KENPRAEL** [comment]
Hi Bro,

base64EncodedAuthInfo is for get authentication info/session, what function/property to get the sender Whatsapp number?

**Comment by BochilGaming** [comment]
> Hi Bro,
> 
> base64EncodedAuthInfo is for get authentication info/session, what function/property to get the sender Whatsapp number?
```js
conn.connect().then(() => {
  console.log(conn.user.jid) // connected phone whatsapp number
})
conn.on('chat-update', (chatUpdate) => {
if (!chatUpdate.hasNewMessage) return
if (!chatUpdate.messages && !chatUpdate.count) return
let m = chatUpdate.messages.all()[0]
let sender =  m.key.fromMe ? conn.user.jid : m.participant ? m.participant : m.key.participant ? m.key.participant : m.key.remoteJid // sender whatsapp number 
})
```

**Comment by KENPRAEL** [comment]
@BochilGaming its work, thank you very much for your help
