### ISSUE TITLE
How to send url and call button messages?

### ISSUE THREAD

**Issue by kythepublic** [adiwajshing/Baileys#1111]
How to send url and call button messages?.
Like this :

**// send a buttons message!
const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1}
]

const buttonMessage = {
    contentText: "Hi it's button message",
    footerText: 'Hello World',
    buttons: buttons,
    headerType: 1
}**

**Comment by mateuscdor** [comment]
?
https://github.com/adiwajshing/baileys/tree/multi-device#non-media-messages

//send a template message!
const templateButtons = ...

**Comment by kythepublic** [comment]
I don't use MD. is it only in MD only?

**Comment by mateuscdor** [comment]
aren't you using legacy?

**Comment by kythepublic** [comment]
Done fixed. thx
