### ISSUE TITLE
Rate-limit reached after QR code scan on multi-device branch

### ISSUE THREAD

**Issue by babakmhz** [adiwajshing/Baileys#1112]
Hello Everyone,

Here's the issue that i'm facing:
After scanning QR code on multi-device branch (i'm using example.ts with "sock.ev.on('connection-update'...)" callback commented) it'll fail on login attempt with response: 

{"level":30,"time":1640949318456,"pid":62790,"hostname":"whatsapp-test","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"outp
[conn.txt](https://github.com/adiwajshing/Baileys/files/7796058/conn.txt)
ut":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Multi-device beta not joined"},"headers":{}}},"msg":"connection closed"}

And when I un-comment the "sock.ev.on('connection-update'...)" callback, it's like too many requests sent and my device will be logged out,

Any Suggestions?

**Comment by mateuscdor** [comment]
post your code

  use the example file to understand how it works.

**Comment by babakmhz** [comment]
I'm using example.ts, it doesn't work

**Comment by babakmhz** [comment]
> I'm using example.ts in Example directory, it doesn't work

**Comment by mateuscdor** [comment]
remove all commen event: // sock.ev.on('connection.update'....

old sock.ev.on('creds.update', saveState)
replace: sock.ev.on("creds.update", () => saveState());

This 403 error
means that the communication structure with whatsapp is out of the standards.

are you using 1 device or multiple devices? sd or md?
check your whatsapp app if it's like md!

are you running in typescript or javascript?

**Comment by jackcokk** [comment]
"Multi-device beta not joined" sounds like a pretty obvious error message to me

**Comment by babakmhz** [comment]
> my whats: 557391776616
> 
> When opening the conn.txt file I realized that the structure of your code is wrong.
> 
> you cannot comment on some features.
> 
> are you running in typescript or javascript?

I'm, running in typescript.
I'm not a javascript/typescript developer, would you please tell me which features I should not comment?
Thanks.

**Comment by babakmhz** [comment]
> "Multi-device beta not joined" sounds like a pretty obvious error message to me

I already joined "Multi-device beta" on my device, but sometimes on logging in it's like it's sending too many requests and my device will be logged out.
Any suggestions?

**Comment by jackcokk** [comment]
> I'm, running in typescript. I'm not a javascript/typescript developer, would you please tell me which features I should not comment? Thanks.

It is best to try a project first without changing things you do not understand about it. Then adjust it to your needs.

> I already joined "Multi-device beta" on my device, but sometimes on logging in it's like it's sending too many requests and my device will be logged out. Any suggestions?

You have to attach logs. As always in online forums: we do not see your screen.

**Comment by babakmhz** [comment]
> > I'm, running in typescript. I'm not a javascript/typescript developer, would you please tell me which features I should not comment? Thanks.
> 
> It is best to try a project first without changing things you do not understand about it. Then adjust it to your needs.
> 
> > I already joined "Multi-device beta" on my device, but sometimes on logging in it's like it's sending too many requests and my device will be logged out. Any suggestions?
> 
> You have to attach logs. As always in online forums: we do not see your screen.

I know about sending logs in online forums :) I just wanted to know if anyone faced it before!
Anyway, It didn't reproduce now, if it happens again, I'll let you know
