### ISSUE TITLE
[MD] Fix proposal for lack in snapshot sync to solve missing contacts

### ISSUE THREAD

**Issue by burstfreeze** [adiwajshing/Baileys#1114]
Baileys does not handle mutations from snapshots, or at least not in the way to do the actual processing - at the moment it only feeds the hash generator https://github.com/adiwajshing/Baileys/blob/multi-device/src/Utils/chat-utils.ts#L350 but it does not use the actual information.

That way snapshot events go missing since they do not appear in the patch itself. 

At the moment, Baileys only pushes mutations from the patches to the stack but we also need to use the patches from the snapshot.

I found out that the fix is more or less simply to do something along the lines of `let mutations = await decodeSyncdMutations(records ...etc...)` in `decodeSyncdSnapshot` and return the results in order to add them to the `appStateChunk.totalMutations`. As it's done in https://github.com/tulir/whatsmeow/blob/666a92779bf58d5fe6446135aac4ba9f9829217d/appstate/decode.go#L259

`proto.ISyncdRecord` also already is a valid parameter for `decodeSyncdMutations` :)

I can PR a commit which however skips the `ltGenerator` validation for the snapshot as events seem to process twice in that case since Baileys is build around a different assumption. Not sure how useful that is for you.

**Comment by burstfreeze** [comment]
(Bump to avoid stale label)

**Comment by adiwajshing** [comment]
@burstfreeze I think this should resolve the issue https://github.com/adiwajshing/Baileys/pull/696/commits/d15bde5d17d61e2872d96321768464693de58c7e

Feel free to reopen or raise a PR if something is off.

**Comment by adiwajshing** [comment]
Thanks for bringing it to attention as well

**Comment by burstfreeze** [comment]
I have to thank you Adhiraj, it works on the affected device so I would say the fix is complete, amazing!
