### ISSUE TITLE
[BUG] Message not supported

### ISSUE THREAD

**Issue by ShineiIchijo** [adiwajshing/Baileys#1115]
Actually I've been trying to send image message with buttons in it. It's working for most of the groups where dissapearing messages are turned off but it isn't working for groups where dissapearing messages are turned on. Can you please look into it? Thank you.

**Comment by unknowkzr** [comment]
> Actually I've been trying to send image message with buttons in it. It's working for most of the groups where dissapearing messages are turned off but it isn't working for groups where dissapearing messages are turned on. Can you please look into it? Thank you.

use ephemeral
