### ISSUE TITLE
Nothing major 

### ISSUE THREAD

**Issue by Cyberkingcr7** [adiwajshing/Baileys#1116]
Hi how do you declare button message... I managed to make buttons but doesn't respond. Please help

**Comment by mateuscdor** [comment]
post your code!

 { index: 1, quickReplyButton: { displayText: '✅ - yes'  ,  id: `here`  }},


1)  client.ev.on('messages.upsert', async (message) =>
2) message.messages[0].message.buttonsResponseMessage.selectedButtonId  >>> id:`here`

**Comment by Fredwuz** [comment]
what version of Baileys are you using MultiDevice or Default?
