### ISSUE TITLE
[BUG] MD fromMe Wrong (Error caused by refactoring commit)

### ISSUE THREAD

**Issue by danielteodorodt** [adiwajshing/Baileys#1126]
**Describe the bug**
When you send a message from your cell phone, fromMe, it appears "false" but it is actually "true" and remoteJid is also wrong.

**To Reproduce**
1. Sends a phone message and checks the Baileys notification.

**Expected behavior**
fromMe should be "true" instead of "false" and remoteJid should be the number itself.

**Comment by adiwajshing** [comment]
Thanks for pointing it out, should be fixed here: https://github.com/adiwajshing/Baileys/pull/696/commits/6c08f0cd76077fbeb0f1cbe2792e86ae8104f047
