### ISSUE TITLE
[BUG] ffmpeg issues

### ISSUE THREAD

**Issue by navetacandra** [adiwajshing/Baileys#1127]
**Describe the bug**
I try send gif image and video with MessageType.video ,and its return 
```shell
'ffmpeg' is not recognized as internal or external command
```

*Sorry for no screen capture, causes my monitor is flickering :)

**Comment by Gimenz** [comment]
you'll need ffmpeg installed to send gif/video message

Are you using Windows? try do follow this tutorial, may can help you => [How to Install FFmpeg on Windows](https://www.wikihow.com/Install-FFmpeg-on-Windows)

**Comment by navetacandra** [comment]
> you'll need ffmpeg installed to send gif/video message
> 
> Are you using Windows? try do follow this tutorial, may can help you => [How to Install FFmpeg on Windows](https://www.wikihow.com/Install-FFmpeg-on-Windows)

How about in repl.it?

**Comment by Gimenz** [comment]
I don't know, I've never used repl.it haha. i hope others tell info

**Comment by BochilGaming** [comment]
> > you'll need ffmpeg installed to send gif/video message
> > Are you using Windows? try do follow this tutorial, may can help you => [How to Install FFmpeg on Windows](https://www.wikihow.com/Install-FFmpeg-on-Windows)
> 
> How about in repl.it?

try [this](https://github.com/BochilGaming/games-wabot/issues/148#issuecomment-990681980)

**Comment by navetacandra** [comment]
> > > you'll need ffmpeg installed to send gif/video message
> > > Are you using Windows? try do follow this tutorial, may can help you => [How to Install FFmpeg on Windows](https://www.wikihow.com/Install-FFmpeg-on-Windows)
> > 
> > 
> > How about in repl.it?
> 
> try [this](https://github.com/BochilGaming/games-wabot/issues/148#issuecomment-990681980)

Oh thank you for your help, do you know why my chocolatey can't install ffmpeg? Its return 404 code

**Comment by Fredwuz** [comment]
Xephire wrote that it would work if you just put the ffmpeg exceutable into the project root directory maybe try this
[Link to the Comment](https://replit.com/talk/ask/Installing-FFmpeg/28721#:~:text=%40ParvaP%20I%20just%20put%20the%20ffmpeg%20executable%20into%20my%20project%20root%20directory.%20See%20https%3A//replit.com/%40Xephire/utils%2Dbot%2Drewrite%23main.py)

**Comment by navetacandra** [comment]
> Xephire wrote that it would work if you just put the ffmpeg exceutable into the project root directory maybe try this [Link to the Comment](https://replit.com/talk/ask/Installing-FFmpeg/28721#:~:text=%40ParvaP%20I%20just%20put%20the%20ffmpeg%20executable%20into%20my%20project%20root%20directory.%20See%20https%3A//replit.com/%40Xephire/utils%2Dbot%2Drewrite%23main.py) as far as it was stated above replit removed the native support of ffmpeg because of spam bots

It's work if i put the ffmpeg in project root without setting the PATH environment?

**Comment by Fredwuz** [comment]
I guess at least that's what Xephire wrote in their comment

**Comment by navetacandra** [comment]
Ffmpeg is require for convert .gif file to .mp4
