### ISSUE TITLE
[bug/error] Mark chat as read 

### ISSUE THREAD

**Issue by dinnos** [adiwajshing/Baileys#113]
Using the function sendReadReceipt(id) the client responses with a 400 status code.

<img width="731" alt="Captura de Pantalla 2020-08-19 a la(s) 0 07 07" src="https://user-images.githubusercontent.com/25092933/90594400-ed996180-e1af-11ea-95ea-dc4c6fc2768b.png">

Context:
- node version: 12.18.3
- lib version: 2.3.1

Code: 

<img width="663" alt="Captura de Pantalla 2020-08-19 a la(s) 0 09 43" src="https://user-images.githubusercontent.com/25092933/90594544-4bc64480-e1b0-11ea-9205-1d5b5cae0b7e.png">

**Comment by adiwajshing** [comment]
So, this could happen because of a few reasons:
1. The chat cannot be read (maybe you've left the group or something)
2. There are no real messages to read (messages that have a `message` property)

The latest commit (a beta for V3.0) automatically tackles these issues, you may want to give that a shot.

**Comment by dinnos** [comment]
Well I'm not really sure about the first point at the time I was testing this functionality, the chat existed on my phone and I had a couple of messages to read.

Well I'm going to test the version you tell me.

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing.

**Comment by SimiPrambos** [comment]
has this issue been resolved?
I've tried in v3, but it's still the same

**Comment by dinnos** [comment]
@SimiPrambos It is solved when you mark them message by message but when you try to do the whole operation I have not checked it, I gave up a bit of integrating it in my API at this moment waiting for the v3 in npm

**Comment by SimiPrambos** [comment]
Oke thanks @adiwajshing it's work
