### ISSUE TITLE
Stop QR Code

### ISSUE THREAD

**Issue by NezukoChans28** [adiwajshing/Baileys#1130]
I want To Stop the QR Code Every 60 seconds, But i Got This error

![Screenshot_20220109-231614](https://user-images.githubusercontent.com/87556399/148690873-e78218d0-5e70-4fd9-82aa-f6f6b66b1578.png)

Everybody can Help me?

**Comment by ghifar1** [comment]
Can you send connection options?

**Comment by NezukoChans28** [comment]
Im not use Connection Option, I Just Use client.logger.level, And i Sett To "warn"
```js
client.logger.level = "warn"
