### ISSUE TITLE
[BUG] [MD] Can't play video in android

### ISSUE THREAD

**Issue by muhamad-fadla** [adiwajshing/Baileys#1132]
**Describe the bug**
I have tried various ways, but the video can't be played on WhatsApp Android, but on PC it can be played.

anyone can help me?

**To Reproduce**
1. normal send message video

**Expected behavior**
the video can be played normally

**Environment (please complete the following information):**
 - Is this on a server? NO
 - What do your `connectOptions` look like? 
  `wa({
		printQRInTerminal: true,
        auth: state,
	})`

 - Do you have multiple clients on the same IP? NO
 - Are you using a proxy? NO

**Additional context**

my script
```
return await sock.sendMessage(jid, {
	caption: "nice"
	footer: db.footer_text,
	templateButtons: [],
	image: {
		url: "https://i.waifu.pics/jncZnqt.gif"
	}
});
```

**Comment by Gimenz** [comment]
WA are detected gif as video, convert .gif into .mp4 first, then send it as video. And you will able to send gif if give { gifPlayback: true } at MessageOption

read here #1040

**Comment by muhamad-fadla** [comment]
owh i see, thanks. it worked
