### ISSUE TITLE
[BUG] can't send list message

### ISSUE THREAD

**Issue by navetacandra** [adiwajshing/Baileys#1133]
**Describe the bug**
I try to send list message and its return error
```javascript
    const rows = [
        {title: 'tes1', description: 'tes1', rowId: 'tes1'},
        {title: 'tes2', description: 'tes2', rowId: 'tes2'}
    ]
    const section = [{ title: 'section', rows: rows }]
    
    const button = {
        buttonText: 'List',
        description: 'list',
        sections: section,
        lisType: 1
    }
    conn.sendMessage(m.from, button, MessageType.listMessage)
```
![IMG_20220110_203002](https://user-images.githubusercontent.com/70505125/148774098-b03e00fd-ebdf-41d7-b86c-56345f0d10fe.jpg)

**Comment by Fredwuz** [comment]
you have to replace `lisType: 1` with `listType: 1`

**Comment by Gimenz** [comment]
why not use conn.sendListMessage() function? 

example at here #574

**Comment by navetacandra** [comment]
> you have to replace `lisType: 1` with `listType: 1`

![IMG_20220111_232904](https://user-images.githubusercontent.com/70505125/148982324-c768f4f2-b49a-40f2-ac8f-b0b1e32088ba.jpg)
It doesn't work

**Comment by Fredwuz** [comment]
Is your Whatsapp account a business account? Because as far as I know business accounts aren't able to send ListMessages

**Comment by navetacandra** [comment]
> Is your Whatsapp account a business account? Because as far as I know business accounts aren't able to send ListMessages

Yeah its bussiness account, its possible?

**Comment by navetacandra** [comment]
Not supported for WhatsApp Bussiness
