### ISSUE TITLE
[BUG] Qr Code Not Generate :(

### ISSUE THREAD

**Issue by ThisMe124** [adiwajshing/Baileys#1137]
I Use MD

**Comment by justClizz** [comment]
Try install **qrcode-terminal**

If you install using pakcage.json, write this in you dependencies:

`"qrcode-terminal": "^0.12.0"`

Or you can run this command in your console:
`npm i qrcode-terminal`

**Comment by ThisMe124** [comment]
> Try install **qrcode-terminal**
> 
> If you install using pakcage.json, write this in you dependencies:
> 
> `"qrcode-terminal": "^0.12.0"`
> 
> Or you can run this command in your console: `npm i qrcode-terminal`

Okeh Itu Jawaban Sayah Di WA Tadi :)

**Comment by ThisMe124** [comment]
GOOD
