### ISSUE TITLE
[BUG] Couldn't login, connection closed

### ISSUE THREAD

**Issue by aryawpratama** [adiwajshing/Baileys#1138]
![image](https://user-images.githubusercontent.com/75900371/148956461-ced91167-62d7-427d-978e-4f4c47374f68.png)

I'm trying to scan the barcode and it always show these logs 
`{"level":30,"time":1641909517744,"pid":674025,"hostname":"nodeserver","class":"baileys","jid":"6285155190901:9@s.whatsapp.net","msg":"registered connection, restart server"}
{"level":30,"time":1641909517745,"pid":674025,"hostname":"nodeserver","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}
Done in 17.27s.`

Any solutions?

**Comment by matheus-santos-moreira** [comment]
it is necessary to restart the connection see https://github.com/adiwajshing/Baileys/blob/multi-device/Example/example.ts
