### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by seunlanlege** [adiwajshing/Baileys#114]
Hey there @adiwajshing, nice work on this :grinning:, esp on the api change 🙌🏽.
Would like to discuss how to go about adding support to this lib for routing requests to WhatsApp servers through a proxy.

**Comment by adiwajshing** [comment]
Glad you like the library. I would love to add this feature. You have any leads on how to proceed?

**Comment by seunlanlege** [comment]
We'd just have to add support for specifying a proxy agent. which can be created with either one of these libs.

https://github.com/TooTallNate/node-socks-proxy-agent
https://github.com/TooTallNate/node-https-proxy-agent
