### ISSUE TITLE
NEW BUG REPORT 

### ISSUE THREAD

**Issue by DioBruh** [adiwajshing/Baileys#1140]
**Describe the bug**

A friend and i found a new bug, the program is showing that we have more contacts than we actually have.
So, i have 144 contacts on my whatsapp but the program is saying i have 177.

**Comment by adithadirizki** [comment]
> **Describe the bug**
> 
> A friend and i found a new bug, the program is showing that we have more contacts than we actually have. So, i have 144 contacts on my whatsapp but the program is saying i have 177.

I also experienced the same thing. Other contacts are (unsaved) contacts you've chatted with and/or contacts from chat group members.

I have 200+ contacts but the result is 43,000+ contacts, it took quite a long time to get that many contacts.

I hope there is an update, to only get saved contacts. @adiwajshing

**Comment by DioBruh** [comment]
thanks dude
