### ISSUE TITLE
[MD] [BUG] Sending spam messages

### ISSUE THREAD

**Issue by justClizz** [adiwajshing/Baileys#1141]
**The bug:**
The code will send the message spam. I did not set him spam messages.

Sample code:
```
const fetch = require("node-fetch")
const P = require(`pino`)
const { default: makeWASocket, DisconnectReason, AnyMessageContent, delay, useSingleFileAuthState, downloadContentFromMessage } = require('@adiwajshing/baileys-md')

const { state, saveState } = useSingleFileAuthState('./auth.json')

const chan = makeWASocket({
    logger: P({ level: 'fatal' }),
    printQRInTerminal: true,
    auth: state,
    browser: ["AIKO WEB SERVICE","Safari","1.0.0"],
})

chan.ev.on('messages.upsert', async m => {
const msg = m.messages[0]
const from = msg.key.remoteJid
const body = { a: 1 };

await fetch(in here is my private API).then(res => res.json()).then(gPeduli => {
const jsoon = JSON.stringify(gPeduli)
const json = JSON.parse(jsoon)

 const trueKah = json.status
 const jawaban = json.message

 if(trueKah === "ready"){
 chan.sendMessage(from, { text: `${jawaban}` })
 } else {
  chan.sendMessage(from, { text: `${jawaban}` })
 }

})
})
```

**Comment by Gimenz** [comment]
yea, maybe because it call API on every getting new message

**Comment by PurpShell** [comment]
> **The bug:** The code will send the message spam. I did not set him spam messages.
> 
> Sample code:
> 
> ```
> const fetch = require("node-fetch")
> const P = require(`pino`)
> const { default: makeWASocket, DisconnectReason, AnyMessageContent, delay, useSingleFileAuthState, downloadContentFromMessage } = require('@adiwajshing/baileys-md')
> 
> const { state, saveState } = useSingleFileAuthState('./auth.json')
> 
> const chan = makeWASocket({
>     logger: P({ level: 'fatal' }),
>     printQRInTerminal: true,
>     auth: state,
>     browser: ["AIKO WEB SERVICE","Safari","1.0.0"],
> })
> 
> chan.ev.on('messages.upsert', async m => {
> const msg = m.messages[0]
> const from = msg.key.remoteJid
> const body = { a: 1 };
> 
> await fetch(in here is my private API).then(res => res.json()).then(gPeduli => {
> const jsoon = JSON.stringify(gPeduli)
> const json = JSON.parse(jsoon)
> 
>  const trueKah = json.status
>  const jawaban = json.message
> 
>  if(trueKah === "ready"){
>  chan.sendMessage(from, { text: `${jawaban}` })
>  } else {
>   chan.sendMessage(from, { text: `${jawaban}` })
>  }
> 
> })
> })
> ```

make sure m.type is "notify" and that the message is not from you

**Comment by Fredwuz** [comment]
```js
if (!msg.key.fromMe && m.type === 'notify') {
}
```
```js
chan.ev.on("messages.upsert", async (m) => {
  const msg = m.messages[0];
  if (!msg.key.fromMe && m.type === "notify") {
    const from = msg.key.remoteJid;
    const body = { a: 1 };

    await fetch(in here is my private API)
      .then((res) => res.json())
      .then((gPeduli) => {
        const jsoon = JSON.stringify(gPeduli);
        const json = JSON.parse(jsoon);

        const trueKah = json.status;
        const jawaban = json.message;

        if (trueKah === "ready") {
          chan.sendMessage(from, { text: `${jawaban}` });
        } else {
          chan.sendMessage(from, { text: `${jawaban}` });
        }
      });
  }
});

```

**Comment by justClizz** [comment]
> ```js
> if (!msg.key.fromMe && m.type === 'notify') {
> }
> ```
> 
> ```js
> chan.ev.on("messages.upsert", async (m) => {
>   const msg = m.messages[0];
>   if (!msg.key.fromMe && m.type === "notify") {
>     const from = msg.key.remoteJid;
>     const body = { a: 1 };
> 
>     await fetch(in here is my private API)
>       .then((res) => res.json())
>       .then((gPeduli) => {
>         const jsoon = JSON.stringify(gPeduli);
>         const json = JSON.parse(jsoon);
> 
>         const trueKah = json.status;
>         const jawaban = json.message;
> 
>         if (trueKah === "ready") {
>           chan.sendMessage(from, { text: `${jawaban}` });
>         } else {
>           chan.sendMessage(from, { text: `${jawaban}` });
>         }
>       });
>   }
> });
> ```

Thanks, the code works!

**Comment by PurpShell** [comment]
> ```js
> if (!msg.key.fromMe && m.type === 'notify') {
> }
> ```
> 
> ```js
> chan.ev.on("messages.upsert", async (m) => {
>   const msg = m.messages[0];
>   if (!msg.key.fromMe && m.type === "notify") {
>     const from = msg.key.remoteJid;
>     const body = { a: 1 };
> 
>     await fetch(in here is my private API)
>       .then((res) => res.json())
>       .then((gPeduli) => {
>         const jsoon = JSON.stringify(gPeduli);
>         const json = JSON.parse(jsoon);
> 
>         const trueKah = json.status;
>         const jawaban = json.message;
> 
>         if (trueKah === "ready") {
>           chan.sendMessage(from, { text: `${jawaban}` });
>         } else {
>           chan.sendMessage(from, { text: `${jawaban}` });
>         }
>       });
>   }
> });
> ```

yk you really shouldn't do that, it just encourages more open issues :slight_smile:
