### ISSUE TITLE
[BUG] [MD] Some messages cannot be seen by the sender or recipient

### ISSUE THREAD

**Issue by Ccccclong** [adiwajshing/Baileys#1145]
**Describe the bug**
After sending whatsapp messages by `socket.sendMessage`, some of the messages can only be seen on the recipient's phone but not the sender's phone, and some cannot be seen at all. Even if all the messages have triggered a `message.upsert` event with the correct message ids.

Any help is appreciated.🙇

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Sent a message by calling `sendMessage(jid, {text: 'message'})`
4. Confirmed the message is sent by listening to `message.upsert` event with the message id returned from `sendMessage`
4. There is a chance that the message cannot be seen on the sender's phone, or even on the recipient's phone. 

**Expected behavior**
Messages that are upserted should be visible on both the sender's or recipient's phone

**Environment:**
 - This is replicable both locally on a Macbook and on EC2 
 - `connectOptions: {
      auth: objectLoadedAndParsedFromStorage,
      logger: Pino({ level: 'debug' }),
    }` 
 - Only one client on the same IP
 - Not using a proxy

**Additional context**
Here is a striped down version of my code to send message.
```typescript
function sendMessage(authenticationState: AuthenticationState, to: string, message: string) {
  const socket = makeWASocket({
    auth: authenticationState,
    logger: Pino({ level: 'debug' }),
  });

  let baileysMessageId: string;
  let isMessageResolved = false;

  socket.ev.on('connection.update', async ({ connection, lastDisconnect }) => {
    if (connection === 'open' && !baileysMessageId) {
      const jid = `${to.replace('+', '')}@s.whatsapp.net`;
      const baileysMessage = await socket.sendMessage(jid, {
        text: message,
      });
      baileysMessageId = baileysMessage.key.id;

      setTimeout(() => {
        if (isMessageResolved) {
          return;
        }
        console.log('timeout');
        isMessageResolved = true;
        socket.end(undefined);
      }, 20000);
    }

    if (connection === 'close' && lastDisconnect.error) {
      const responseStatusCode = (lastDisconnect.error as any).output
        ?.statusCode;

      if (!isMessageResolved) {
        isMessageResolved = true;
        const failureReason = responseStatusCode
          ? `whatsapp-${DisconnectReason[responseStatusCode]}`
          : 'no-response';
        console.log(failureReason);
      }
    }
  });

  socket.ev.on('messages.upsert', ({ messages }) => {
    if (
      baileysMessageId &&
      messages.some((message) => message.key.id === baileysMessageId) &&
      !isMessageResolved
    ) {
      isMessageResolved = true;
      console.log('success');
      socket.end(undefined);
    }
  });
}

```

**Comment by danielteodorodt** [comment]
Same Here
