### ISSUE TITLE
[Doubt] How to implement VPN/reverse-proxy for multiple numbers

### ISSUE THREAD

**Issue by namanambavi** [adiwajshing/Baileys#1148]
I want to implement Baileys for 100+ numbers. I have figured out all the steps and it is working smoothly but due to WhatsApp's limitations and to prevent blocks, I want to implement some sort of VPN that can route connections through various IP addresses.

Can anyone please suggest and help how can we achieve that? I know Baileys has an option of connecting through a proxy server but wanted more guidance on the implementation part for multiple numbers

**Comment by erickythierry** [comment]
a quick idea would be to use multiple docker containers, each one would support 10 bots/numbers and then you could implement a single vpn/proxy for each of the containers.
I don't think anything automatic that already does this but you can develop a specific solution for this with openvpn or squid proxy

**Comment by namanambavi** [comment]
That helps, thank you!

would still appreciate if others can comment in :)

**Comment by morganzysman** [comment]
Hi, same here
