### ISSUE TITLE
[BUG] For "send a list message!" It doesn't work, when I try it, only the text is sent, the list doesn't exist

### ISSUE THREAD

**Issue by CAF-ID** [adiwajshing/Baileys#1149]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by phaticusthiccy** [comment]
You probably don't use original WhatApp. You can update the WhatsApp application you use.
