### ISSUE TITLE
[bug/error] document's name are being "null" while sending documents.

### ISSUE THREAD

**Issue by paritoshpandey966** [adiwajshing/Baileys#115]
I am sending documents using this code

`client.sendMediaMessage('91xxxxxxxxxx@s.whatsapp.net', bufferdata, mimetype, options)`

although document sending is working properly. but its name is going with the value of "null"

i.e. I'm sending "sample.pdf" to 91xxxxxxxxxx

but 91xxxxxxxxxx recieved "null.pdf", though pdf is the same what i sent.

**Comment by adiwajshing** [comment]
Have you tried setting `filename` in options?

**Comment by adiwajshing** [comment]
Because this was already implemented [here](https://github.com/adiwajshing/Baileys/blob/b4298b772e2cee9b190fb240d41eb3c4f0339ceb/src/WAConnection/6.MessagesSend.ts#L133)

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing
