### ISSUE TITLE
[MD] Baileys crashes on 500+ missed messages

### ISSUE THREAD

**Issue by HUGEIT** [adiwajshing/Baileys#1152]
I spammed myself over the night with messages because I recently saw a problem when an instance is offline for a few hours.

I sent a bit more messages than I intended to do but in my case it went the following:

`12037 offline messages/notifications`

it results in a lot of unknown message keys and therefore retry requests. After a while the following pops up:

```
src/Socket/socket.ts:328:17

Code":408,"error":"Request Time-out","message":"Timed Out"},"headers":{}}},"msg":"connection closed"}
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Timed Out
        at /src/Utils/generics.ts:167:13
        at runNextTicks (node:internal/process/task_queues:61:5)
        at listOnTimeout (node:internal/timers:526:9)
        at processTimers (node:internal/timers:500:7) 
    }
```

the connection automatically restarts. then, after a few more seconds, it does:

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

but without a trace to where it's happening. if I search for `1006` I find a line in the `ws` package:

`this._closeCode = 1006;`

I don't know how the website does it but maybe we have to either
-  batch request missing messages for retries, 
- **or make these retries throttle a bit to only doing 50 retries at once?** we could also increase the timeout but this does not sound like the right way to do it. throttling them may also reduce memory footprint which can be an issue as pointed out by #1119

I noticed the stack for the former is `src/Socket/socket.ts:328:17` (startKeepAliveRequest \ waitForMessage \ promiseTimeout) so maybe 
- the input load on the process is so high that the server response to the ping either never arrives to be put on the stack
- or it actually reaches the stack but Baileys cannot work through it in time due to all the other messages from the retry requests coming in

in that case we could either prioritize the keepAlive or what I would prefer to set a limit for the amount of pending requests before the old ones have been responded to so it won't run under full load potentially leading to other issues down the line.

the way it is right now is probably the fastest way since it's using a max of CPU and RAM in a short amount of time however putting a layer of queuing there would probably be much safer with only a percent of decline in performance since we can still have dozens of requests taking place at the same time, it's just that when it hits "hundreds" the issues seem to arise.

do you have any thoughts on this @adiwajshing ?

**Comment by adiwajshing** [comment]
@HUGEIT I think putting retries in a mutex/promise queue would likely resolve this problem -- if you can try it out and verify it solves the problem, would be fantastic

**Comment by adiwajshing** [comment]
Baileys already provides such a tool: https://github.com/adiwajshing/Baileys/blob/multi-device/src/Utils/make-mutex.ts

**Comment by HUGEIT** [comment]
thank you for the comment @adiwajshing 

before I begin may I ask, the Baileys mutex would only allow one request at the time, is that correct?

If so, I am afraid of an issue, the scenario is the following:

- roundtrip latency is 100ms -> each retry costs 100ms
- we have 200 messages waiting
- (_the processing time of each message after being received is not important in this calculation_)

**current implementation**:

- it will take 100ms = ~ **100ms** (+ processing) for all messages to resolve

**if we do the mutex one at a time:**

- it would take 100ms * 200 messages = ~ **20 seconds** (+ processing) to resolve in serial

so, disregarding the processing, doing them one after another may put a huge cost of unnecessary waiting for the network layer. I would suggest having an arbitrary limit (like 50 messages at once) that is slow enough to give some headroom for other tasks (such as the ping in my case) but fast enough to not cause a noticeable performance hit. 

**so in our scenario the time to process would be:**

- 100ms * 4 iterations = ~ **400ms** (+ processing)

this way we could ensure stability (since we have something going on in serial without blocking too much) as well as keeping the performance up (since we put in some parallel that makes it 98% faster than the pure-serial that would take 20 seconds).

please let me hear what you think

**Comment by adiwajshing** [comment]
@HUGEIT you're correct -- but the mutex is non-blocking, it won't stop other queries and work form being done on the process

**Comment by HUGEIT** [comment]
@adiwajshing 

you are right that it will not block the whole Baileys but if we do them in serial it will take very long to get all the recent messages if they have to be retried. like they will not block the rest but they will block each other. 

this is why I ask whether it's okay for you if I come up with something that does them in smaller batches instead so we won't have as much "pending time" for these messages if that makes sense.

**Comment by adiwajshing** [comment]
I don't believe this problem requires this much engineering, primarily because this problem should seldom occur & it taking 20-30s to resolve all failed messages is not a concern in my opinion. Moreover, even if the connection breaks in the middle of retrying -- the remaining messages will be retries on successive connects
