### ISSUE TITLE
How to get messageinfo data like who have reads the message with baileys-md ?

### ISSUE THREAD

**Issue by Mr4sR** [adiwajshing/Baileys#1154]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

How to get messageinfo data like who have reads the message with baileys-md, I want to make the bot able to count how many people have read the message

**Comment by sreza78** [comment]
any answer!?
