### ISSUE TITLE
Join Gaes

### ISSUE THREAD

**Issue by tahaluindo** [adiwajshing/Baileys#1157]
[[**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
](https://github.com/koleksibot)](https://github.com/koleksibot)

**Comment by nugraizy** [comment]
alay

**Comment by hardianto02** [comment]
> adding this issue, make sure you do the

what your problem broo

**Comment by LuanRT** [comment]
Bruh?

**Comment by NadhiraAlifah** [comment]
oakwowkaow

**Comment by Arya-was** [comment]
waduh

**Comment by rayyreall** [comment]
Ok gw hargai kecaperan anda

**Comment by LitRHap** [comment]
> [[**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature/question** ]([https://github.com/koleksibot)](https://github.com/koleksibot](https://github.com/koleksibot)%5D(https://github.com/koleksibot))

oke stah

**Comment by Azyansah** [comment]
penyakit

**Comment by Caliph91** [comment]
> [[**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature/question** ]([https://github.com/koleksibot)](https://github.com/koleksibot](https://github.com/koleksibot)%5D(https://github.com/koleksibot))

Mkst

**Comment by haznkowow** [comment]
gj

**Comment by viniciusgdr** [comment]
????

**Comment by VEXG** [comment]
kampungan banget

**Comment by Errs404** [comment]
Sus

**Comment by Errs404** [comment]
Sus
