### ISSUE TITLE
How to kill session at one terminal.

### ISSUE THREAD

**Issue by M1n007** [adiwajshing/Baileys#116]
I have function just for send message and i try send first message is success but if i send second message has an error 

Error: already connected or connecting
    at WhatsAppWebMessages.connectSlim (/Users/aminudin/projects/nodejs/api/archv-wa-api-master/node_modules/@adiwajshing/baileys/lib/WAConnection/Connect.js:66:19)
    at Promise (/Users/aminudin/projects/nodejs/api/archv-wa-api-master/bin/helpers/waClient.js:12:12)
    at new Promise (<anonymous>)
    at Object.sendMessage (/Users/aminudin/projects/nodejs/api/archv-wa-api-master/bin/helpers/waClient.js:10:63)
    at Object.sendMessage (/Users/aminudin/projects/nodejs/api/archv-wa-api-master/bin/routes/whatsapp/domain.js:22:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7347) UnhandledPromiseRejectionWarning: #<Object>
(node:7347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:7347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

tthis my function

const sendMessage = (phoneNumber, textMessage, sessionCfg) => new Promise((resolve, reject) => {
    const dataSession = sessionCfg;
    client.connectSlim(dataSession)
    .then (async user => {
        const id = `${phoneNumber}@s.whatsapp.net`;
        const sendMessageResult = await client.sendMessage(id, textMessage, MessageType.text);
        const newResult = {
            err:false,
            ...sendMessageResult
        }
        resolve(newResult)
    })
    .catch(err => {
        console.log(err)
        const newResultErr = {
            err:true,
            ...err
        }
        reject(newResultErr)
    })
});

**Comment by adiwajshing** [comment]
It looks like you're calling connect while the connection is already open

**Comment by M1n007** [comment]
> It looks like you're calling connect while the connection is already open. Under what circumstances are you connecting?

i want connect to other session if connection already open and just throw json session, i want make API from this.in the already connected situation

**Comment by adiwajshing** [comment]
Could you try migrating to Baileys 3.0 and see if things work well with that, you can install using: `npm i github:adiwajshing/baileys`

**Comment by M1n007** [comment]
> Could you try migrating to Baileys 3.0 and see if things work well with that, you can install using: `npm i github:adiwajshing/baileys`

ok this solved my problem for connect to another session with error already open, thanks @adiwajshing.

sorry for many question, now i have new problem.

i have 2 session, session A and session B. This my api proses get session :

Hit API Send Message -> Get userId from Bearer -> get user by userId  -> get session by userId -> hit WaClient baileys -> send message

for first session send message was succesfull, but in second session it's failed i don't why not error just message not send. when I tried to use the first session, it was still successful.

thanks before.

**Comment by adiwajshing** [comment]
I can't really say much without seeing the code.

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing
