### ISSUE TITLE
[BUG] (node:11224) UnhandledPromiseRejectionWarning: TypeError: nodeCrypto.randomInt is not a function

### ISSUE THREAD

**Issue by kythepublic** [adiwajshing/Baileys#1163]
![image](https://user-images.githubusercontent.com/59775277/149896477-e2324d61-0a58-469a-819c-fe51919e2322.png)

This error when sending a message to the group.
But if you send a message to a personal it's no problem.
How to fix this?
thx.

**Comment by Jarvis2301** [comment]
![Screenshot_20220118-221829](https://user-images.githubusercontent.com/88648954/149954494-1fd5170f-1e34-408d-ad74-ec16310aaed5.png)

Bug bug again

**Comment by kythepublic** [comment]
> ![Screenshot_20220118-221829](https://user-images.githubusercontent.com/88648954/149954494-1fd5170f-1e34-408d-ad74-ec16310aaed5.png)
> 
> Bug bug again

Looks like this bug/error not same with me.
but i don't know this from baileys or myself

**Comment by lukacat10** [comment]
What version of node do you have?
