### ISSUE TITLE
Getting a response from buttons

### ISSUE THREAD

**Issue by xYAZUWA** [adiwajshing/Baileys#1174]
Dear Developers ,
I want to know that how to get a response from buttons.

Currently I am this codes. But i still got buttons , Without response.

Is this not working?

const Asena = require('../events');
const {
MessageType,
GroupSettingChange,
Mimetype,
MessageOptions
} = require('@adiwajshing/baileys');
const fs = require('fs');
const Config = require('../config')
const axios = require('axios')
const request = require('request');
const os = require('os');

let tk = Config.WORKTYPE == 'public' ? false: true

Asena.addCommand({ pattern: 'thisisalive', fromMe: tk, desc: 'Gives The Button Menu'
}, (async (message, match) => {

var NOTINUSE = ''
if (Config.ALIVEMSG == 'default') MSG = '╭──────────◅\n│\n│🎧ʜᴇʟʟᴏ ᴜꜱᴇʀ\n│╭──────────────╮\n│ 👸🏻Ｉ ＡＭ A L I V E 👸\n│╰──────────────╯\n│\n├►ɪ ᴀᴍ ᴀʟᴏʀᴀ ʙᴏᴛ\n│\n│▻ᴠᴇʀꜱɪᴏɴ - ᴡɪᴛʜ ʙᴜᴛᴛᴏɴꜱ\n│\n├▻ᴅᴇᴠᴇʟᴏᴘᴇʀ - xY̷A̷Z̷U̷W̷A̷\n│\n├▻ᴍᴇɴᴜ ᴄᴏᴍᴍᴀɴᴅ - .alora\n│\n│💞ᴛʜᴀɴᴋ ʏᴏᴜ ꜰᴏʀ ᴜꜱɪɴɢ ᴍᴇ👸\n│\n╰────────────▻\nـــ٨ـہہـ♡ـ٨ـہـ'
else MSG = Config.ALIVEMSG

var PREFIXBTN = '';
if (/[(\W*)]/.test(Config.HANDLERS)) {
PREFIXBTN = Config.HANDLERS.match(/[(\W*)]/)[1][0];
} else {
PREFIXBTN = '.';
}

// send a buttons message!
const buttons = [
{buttonId: PREFIXBTN + 'absysdtxt', buttonText: {displayText: '✆ System status' }, type: 1},
{buttonId: PREFIXBTN + 'abversion', buttonText: {displayText: '☩ Version' }, type: 1}
]

const buttonMessage = {
contentText: '╭──────────◅\n│\n│🎧ʜᴇʟʟᴏ ᴜꜱᴇʀ\n│╭──────────────╮\n│ 👸🏻Ｉ ＡＭ A L I V E 👸\n│╰──────────────╯\n│\n├►ɪ ᴀᴍ ᴀʟᴏʀᴀ ʙᴏᴛ\n│\n│▻ᴠᴇʀꜱɪᴏɴ - ᴡɪᴛʜ ʙᴜᴛᴛᴏɴꜱ\n│\n├▻ᴅᴇᴠᴇʟᴏᴘᴇʀ - xY̷A̷Z̷U̷W̷A̷\n│\n├▻ᴍᴇɴᴜ ᴄᴏᴍᴍᴀɴᴅ - .alora\n│\n│💞ᴛʜᴀɴᴋ ʏᴏᴜ ꜰᴏʀ ᴜꜱɪɴɢ ᴍᴇ👸\n│\n╰────────────▻\nـــ٨ـہہـ♡ـ٨ـہـ',
footerText: '© ǫᴜᴇᴇɴ ᴀʟᴏʀᴀ ᴛᴇꜱᴛ ',
buttons: buttons,
headerType: 1

}

await message.client.sendMessage(message.jid, buttonMessage, MessageType.buttonsMessage)

}));

Asena.addCommand({ pattern: 'absysdtxt', fromMe: tk, desc: 'Gives The Button Menu'
}, (async (message, match) => {

await message.client.sendMessage(message.jid, fs.readFileSync("./media/SYSDTXTLOGO.jpg"), MessageType.image, { caption: '─▹─═─═─═─═─═─═─═─═─═─▹─\n▢Name-AloraDev\n▹Os-Selenium\n▹Memory - 16GB\n▹Processor-AMD RYZEN5\n▹Language -English/Sinhala/Azeric/Turkish\n▹Image size-730Mb\n▹Image from -:fusufs/\n▹Wa Web Library - Baileys (^3.5.2)\n▹Whatsapp Ver.-3.3234.9\n▹FrameWork-Node.js/Javascript/Shell\n▹Hosted in-Github\n▹Deployed in-Heroku\n▹Upload Speed-Not Measurable\n▹Download Speed-Not Measurable\n\n\n➣✾ـٰٰٰٰٖٖٖٖٜ۬ـٰٰٰٖٖٖٜ۬ـٰٰٖٖٜ۬ـٰٖٜ۬ـٰٖٜ۬ـٰٰٖٖٜ۬ـٰٰٰٖٖٖٜ۬ـٰٰٰٰٖٖٖٖٜ۬ـٰٰٰٖٖٖٜ۬ـٰٰٖٖٜ۬ـٰٖٜ۬ـٰٖٜ۬ـٰٰٖٖٜ۬ـٰٰٰٖٖٖٜ۬ـٰٰٰٰٖٖٖٖٜ۬✾➣'})
}));

Asena.addCommand({ pattern: 'abversion', fromMe: tk, desc: 'Gives The Button Menu'
}, (async (message, match) => {

await message.client.sendMessage(message.jid, fs.readFileSync("./media/VERSLOGO.jpg"), MessageType.image, { caption: 'MS.ALORA V2.2.9'})
}));

All this discussion is about bots 🌝
Help Appreciated ❤

**Comment by SL-Alpha-X** [comment]
Yeah i have the same problem 🚶 but no answer 🥲

**Comment by HansakaBro** [comment]
> Yeah i have the same problem 🚶 but no answer 🥲

: ( Yep

**Comment by SL-Alpha-X** [comment]
> Yeah i have the same problem 🚶 but no answer 🥲

![Polish_20220123_172550485](https://user-images.githubusercontent.com/85741405/150677184-cf675f33-1e40-418d-986a-66d710e038e6.jpg)


**I mean how to get response like this?** 🙁

**Comment by Fredwuz** [comment]
If the user clicks on a `buttonsMessage` or a `templateButtonReplyMessage` the message has the `buttonsMessage` or `templateButtonReplyMessage`  object and that object has the `selectedId` attribute 
you can set the `selectedId` when creating the buttons
```js
const buttons = [
  {
    buttonId: PREFIXBTN + "absysdtxt",       //like you did here
    buttonText: { displayText: "✆ System status" },
    type: 1,
  },
  {
    buttonId: PREFIXBTN + "abversion",
    buttonText: { displayText: "☩ Version" },
    type: 1,
  },
];
```
I hope this is what you searched

**Comment by SL-Alpha-X** [comment]
thanks whatever that would be help full to us ;)

> `buttonsMessage`පරිශීලකයා a හෝ a මත ක්ලික් කළහොත් `templateButtonReplyMessage`පණිවිඩයේ `buttonsMessage`හෝ `templateButtonReplyMessage` වස්තුව තිබේ නම් සහ එම වස්තුවේ `selectedId`ගුණාංගය තිබේ නම් ඔබට බොත්තම් සෑදීමේදී එය සැකසිය හැක.`selectedId`
> 
> ```js
> const  buttons  =  [ 
>   { 
>     buttonId : PREFIXBTN  +  "absysdtxt" ,        //ඔබ මෙහි කළා වගේ 
>     buttonText : {  displayText : "✆ System status"  } , 
>     type : 1 , 
>   } , 
>   { 
>     buttonId : PREFIXBTN  +  "abversion" , button
>      Text : { display Text : "☩ අනුවාදය" } , වර්ගය : 1 , } , ] ;  
>     
>   
> ```
> 
> ඔබ සෙවූ දේ මෙය යැයි මම බලාපොරොත්තු වෙමි

thanks whatever that would be help full to us ;)

**Comment by SL-Alpha-X** [comment]
> If the user clicks on a `buttonsMessage` or a `templateButtonReplyMessage` the message has the `buttonsMessage` or `templateButtonReplyMessage` object and that object has the `selectedId` attribute you can set the `selectedId` when creating the buttons
> 
> ```js
> const buttons = [
>   {
>     buttonId: PREFIXBTN + "absysdtxt",       //like you did here
>     buttonText: { displayText: "✆ System status" },
>     type: 1,
>   },
>   {
>     buttonId: PREFIXBTN + "abversion",
>     buttonText: { displayText: "☩ Version" },
>     type: 1,
>   },
> ];
> ```
> 
> I hope this is what you searched

Can u give example adding `selecteId`

**Comment by HansakaBro** [comment]
> If the user clicks on a `buttonsMessage` or a `templateButtonReplyMessage` the message has the `buttonsMessage` or `templateButtonReplyMessage` object and that object has the `selectedId` attribute you can set the `selectedId` when creating the buttons
> 
> ```js
> const buttons = [
>   {
>     buttonId: PREFIXBTN + "absysdtxt",       //like you did here
>     buttonText: { displayText: "✆ System status" },
>     type: 1,
>   },
>   {
>     buttonId: PREFIXBTN + "abversion",
>     buttonText: { displayText: "☩ Version" },
>     type: 1,
>   },
> ];
> ```
> 
> I hope this is what you searched

Thanks bro 💞

**Comment by xYAZUWA** [comment]
Thank you very Much Mr.FREDWUZ

**Comment by freefugga** [comment]
Can we get some example for adding `selectedId` please @Fredwuz
