### ISSUE TITLE
[Feature Request] A helper function to create a new authentication state

### ISSUE THREAD

**Issue by PokeGuys** [adiwajshing/Baileys#1175]
Right now, `useSingleFileAuthState()` is coupled with file store. It is impossible to use our own storage implementation.

Is it possible to extract the `AuthenticationState` creation logic into a separate function?

Thanks.

**Comment by adiwajshing** [comment]
`useSingleFileAuthState` **Is** a helper function meant to help in understanding how the baileys auth state works. Internally, the auth state is implementation agnostic, you could use a SQL DB or Mongo or FS, it does not care. I would strongly recommend you read the `useSingleFileAuthState` implementation [here](https://github.com/adiwajshing/Baileys/blob/e7c2d4e117925f16967de86810775e22d035ef5a/src/Utils/auth-utils.ts#L116)

**Comment by PokeGuys** [comment]
so you are saying if I need to implement different FS with auth state basically I need to copy entire `useSingleFileAuthState` and replace the `saveState` logic?

Because AFAIK, if I want to use a different FS, I need to understand the implementation of auth state. It doesn't feel like the implementation is agnostic tho. Without the knowledge of Signal protocol, I won't even understand how to construct the `keys` property and the needs of handling special key type. And it does not even mentioned in the documentation of how the keys state should be constructed.

If auth state implementation should be agnostic, isn't that providing a helper function to create auth state is the right way?

Thanks.

**Comment by adiwajshing** [comment]
No, you misunderstand. `useSingleFileAuthState` provides an implementation of the `SignalKeyStore` interface -- as long as you implement the `SignalKeyStore` interface, you can use any implementation to save your auth state

**Comment by PokeGuys** [comment]
Thank you for the clarification. I guess i just got confused when I saw the `KEY_MAP` and thought the `SignalKeyStore` needs a specific key value mapping format.

**Comment by Pegorino82** [comment]
> agnostic

hi, did you implement this? could you share please?)
