### ISSUE TITLE
i have problem to sending some types files (PDF,ZIP)

### ISSUE THREAD

**Issue by Fabiancalderon5987** [adiwajshing/Baileys#1189]
hi  :) i need help  because to send files(pdf or zip) the first sendin is correctly but second throw error

ERROR [2022-01-27 13:36:55.635 +0000] (2128): Error in uploading to mmg.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type))
    class: "Baileys"

first send for postman is work
![image](https://user-images.githubusercontent.com/96252285/151370489-60531f77-2929-4628-b786-38c09ce0100e.png)
the second o plus throw error
![image](https://user-images.githubusercontent.com/96252285/151370620-bd7ff8ed-5826-4ce7-b68c-5a5f647d25c1.png)
console nodejs throw this next
![image](https://user-images.githubusercontent.com/96252285/151370844-5edac1fe-7c8b-4a7c-8630-4707f0b2d668.png)
note:
with images not throw error i can send image multiple times

my code is next
`if (filetype == 'pdf') {
	const buffer = await getBuffer(url);
		 conn.sendMessage(number, buffer, MessageType.document, { mimetype:Mimetype.pdf}).then(response => {
				 res.status(200).json({
					status: true,
					response: response,
					buffer,
				});
			}).catch(err => {
				 res.json({
					status: false,
					response: err,
					number,
				});
				console.log('gagal')
			});`
![image](https://user-images.githubusercontent.com/96252285/151371574-28d7dceb-acf6-4f4b-b75b-3d0d3cc7ac78.png)

information
server : centos 7
nodejs version :  v10.24.1
@adiwajshing/baileys : 3.4.1

**Comment by Fabiancalderon5987** [comment]
Hi i update for the last version and its works :)

**Comment by lisandroprada** [comment]
> Hi i update for the last version and its works :)

Hi Fabián. I'd like to contact you. I need a method to send/attach PDF
