### ISSUE TITLE
[BUG] Decrypting sticker images always fails

### ISSUE THREAD

**Issue by cryptoAlgorithm** [adiwajshing/Baileys#1193]
**Describe the bug**
Downloading images of sticker messages constantly fails with the following stack trace:
<img width="723" alt="Screenshot 2022-01-28 at 8 53 57 AM" src="https://user-images.githubusercontent.com/64193267/151468090-4b33dd8f-98da-4e4e-ab55-394150e5c0fa.png">

**To Reproduce**
Send a sticker, attempt to download sticker messages in the `messages.upsert` event
Using the same code as the readme example to download and save media

**Expected behavior**
The sticker image gets downloaded and saved without any exceptions

**Environment (please complete the following information):**
 - Is this on a server? No, running locally on nodeJS
 - What do your `connectOptions` look like? ```makeWASocket({
            printQRInTerminal: true,
            logger: log,
            auth: state
        });```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
Using baileys 4.0.0 from nom with a multi-device connection

**Comment by Gimenz** [comment]
can you send the code?

**Comment by cryptoAlgorithm** [comment]
```js
import { writeFile } from 'fs/promises'
import { downloadContentFromMessage } from '@adiwajshing/baileys'

sock.ev.on('messages.upsert', async ({ messages }) => {
    const m = messages[0]

    if (!m.message) return // if there is no text or media message
    const messageType = Object.keys (m.message)[0]// get what type of message it is -- text, image, video
    // if the message is an image
    if (messageType === 'stickerMessage') {
        // download stream
        const stream = await downloadContentFromMessage(m.message.stickerMessage, 'sticker')
        let buffer = Buffer.from([])
        for await(const chunk of stream) {
            buffer = Buffer.concat([buffer, chunk])
        }
        // save to file
        await writeFile('./my-download.jpeg', buffer)
    }
}
```

^ basically the code from the readme, but with modifications to download stickers

**Comment by rlucredio** [comment]
Please is there any update to this issue? It doesn't seem solved to me.
