### ISSUE TITLE
How to prepare STICKER to be sent?

### ISSUE THREAD

**Issue by erickythierry** [adiwajshing/Baileys#1194]
when I try to send an animated sticker larger than 1mb, it is sent as a static sticker
I would like to know how to use the **media preparation function** to be sent. I believe this bug occurs because the webp file is of a size that makes it impossible to process the animation in time

**To Reproduce**
1. get a video or gif with more than 10s in good resolution
2. convert to animated webp (I use ffmpeg)
3. send normally as a sticker
4. the sticker sent arrives as static

**Comment by xfrcc** [comment]
try using 512x512 resolution
