### ISSUE TITLE
Example in javascript v4.0.0

### ISSUE THREAD

**Issue by SapiZonk** [adiwajshing/Baileys#1196]
Hi, in v.4.0.0 (for legacy web or for MD) is there example in javascript? not in typescript, thanks

**Comment by mateuscdor** [comment]
> Hi, in v.4.0.0 (for legacy web or for MD) is there example in javascript? not in typescript, thanks

run tsc to compile to js

**Comment by Othales** [comment]
const P = require('pino')
const { delay, DisconnectReason, useSingleFileAuthState } = require('@adiwajshing/baileys')
const makeWASocket = require('@adiwajshing/baileys').default;


// start a connection
const startSock = () => {

    const { state, saveState } = useSingleFileAuthState('./auth.json')
    
    const sock = makeWASocket({
        logger: P({ level: 'fatal' }),
        printQRInTerminal: true,
        auth: state,
    });

    const sendMessageWTyping = async(msg, jid) => {
        await sock.presenceSubscribe(jid)
        await delay(500)

        await sock.sendPresenceUpdate('composing', jid)
        await delay(2000)

        await sock.sendPresenceUpdate('paused', jid)

        await sock.sendMessage(jid, msg)
    }

    sock.ev.on('chats.set', item => console.log(`recv ${item.chats.length} chats (is latest: ${item.isLatest})`))
    sock.ev.on('messages.set', item => console.log(`recv ${item.messages.length} messages (is latest: ${item.isLatest})`))
    sock.ev.on('contacts.set', item => console.log(`recv ${item.contacts.length} contacts`))

    sock.ev.on('messages.upsert', async m => {
        console.log(JSON.stringify(m, undefined, 2))

        const msg = m.messages[0]
        if(!msg.key.fromMe && m.type === 'notify') {
            console.log('replying to', m.messages[0].key.remoteJid)
            await sock.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])
            await sendMessageWTyping({ text: 'Olá' }, msg.key.remoteJid)
        }
    })

    sock.ev.on('messages.update', m => console.log(m))
    sock.ev.on('message-receipt.update', m => console.log(m))
    sock.ev.on('presence.update', m => console.log(m))
    sock.ev.on('chats.update', m => console.log(m))
    sock.ev.on('contacts.upsert', m => console.log(m))


    // listen for when the auth credentials is updated
    sock.ev.on('creds.update', saveState)



    sock.ev.on('connection.update', function (update, connection2) {
        let _a, _b;
        let connection = update.connection, lastDisconnect = update.lastDisconnect;
        if (connection === 'close') {
            // reconnect if not logged out
            if (((_b = (_a = lastDisconnect.error) === null || _a === void 0 ? void 0 : _a.output) === null || _b === void 0 ? void 0 : _b.statusCode) !== DisconnectReason.loggedOut) {
                
                startSock()
                

            }
            else {
                console.log('connection closed');
            }
        }
        console.log('connection update', update);
    });


    return sock
}

startSock()

**Comment by SapiZonk** [comment]
> const P = require('pino') const { delay, DisconnectReason, useSingleFileAuthState } = require('@adiwajshing/baileys') const makeWASocket = require('@adiwajshing/baileys').default;
> 
> // start a connection const startSock = () => {
> 
> ```
> const { state, saveState } = useSingleFileAuthState('./auth.json')
> 
> const sock = makeWASocket({
>     logger: P({ level: 'fatal' }),
>     printQRInTerminal: true,
>     auth: state,
> });
> 
> const sendMessageWTyping = async(msg, jid) => {
>     await sock.presenceSubscribe(jid)
>     await delay(500)
> 
>     await sock.sendPresenceUpdate('composing', jid)
>     await delay(2000)
> 
>     await sock.sendPresenceUpdate('paused', jid)
> 
>     await sock.sendMessage(jid, msg)
> }
> 
> sock.ev.on('chats.set', item => console.log(`recv ${item.chats.length} chats (is latest: ${item.isLatest})`))
> sock.ev.on('messages.set', item => console.log(`recv ${item.messages.length} messages (is latest: ${item.isLatest})`))
> sock.ev.on('contacts.set', item => console.log(`recv ${item.contacts.length} contacts`))
> 
> sock.ev.on('messages.upsert', async m => {
>     console.log(JSON.stringify(m, undefined, 2))
> 
>     const msg = m.messages[0]
>     if(!msg.key.fromMe && m.type === 'notify') {
>         console.log('replying to', m.messages[0].key.remoteJid)
>         await sock.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])
>         await sendMessageWTyping({ text: 'Olá' }, msg.key.remoteJid)
>     }
> })
> 
> sock.ev.on('messages.update', m => console.log(m))
> sock.ev.on('message-receipt.update', m => console.log(m))
> sock.ev.on('presence.update', m => console.log(m))
> sock.ev.on('chats.update', m => console.log(m))
> sock.ev.on('contacts.upsert', m => console.log(m))
> 
> 
> // listen for when the auth credentials is updated
> sock.ev.on('creds.update', saveState)
> 
> 
> 
> sock.ev.on('connection.update', function (update, connection2) {
>     let _a, _b;
>     let connection = update.connection, lastDisconnect = update.lastDisconnect;
>     if (connection === 'close') {
>         // reconnect if not logged out
>         if (((_b = (_a = lastDisconnect.error) === null || _a === void 0 ? void 0 : _a.output) === null || _b === void 0 ? void 0 : _b.statusCode) !== DisconnectReason.loggedOut) {
>             
>             startSock()
>             
> 
>         }
>         else {
>             console.log('connection closed');
>         }
>     }
>     console.log('connection update', update);
> });
> 
> 
> return sock
> ```
> 
> }
> 
> startSock()

Thanks for you respone

but i have this error while is send message

(node:8772) UnhandledPromiseRejectionWarning: TypeError: nodeCrypto.diffieHellman is not a function
    at Object.exports.calculateAgreement (C:\Users\Andy\Desktop\MD\node_modules\libsignal\src\curve.js:80:23)
    at SessionBuilder.initSession (C:\Users\Andy\Desktop\MD\node_modules\libsignal\src\session_builder.js:106:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.6289518515611.0 [as awaitable] (C:\Users\Andy\Desktop\MD\node_modules\libsignal\src\session_builder.js:30:29)
    at async _asyncQueueExecutor (C:\Users\Andy\Desktop\MD\node_modules\libsignal\src\queue_job.js:20:29)
(node:8772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

i think it can't send message

**Comment by scriptbypavan** [comment]
Yes the same is happening with me

**Comment by scriptbypavan** [comment]
![image](https://user-images.githubusercontent.com/69261587/151805575-3861c201-03ea-4d9f-a4a1-96f999c9d8f6.png)

**Comment by scriptbypavan** [comment]
What is the node version you are using ?

**Comment by Othales** [comment]
I test here and work 
My node version v16.13.1

i send code in pastebin 

https://pastebin.com/raw/t8Kavy0b

**Comment by scriptbypavan** [comment]
**nodeCrypto.diffieHellman is not a function**  this error is due to node version, for me it solved with node 16.3.2

**Comment by Millena543** [comment]
> **nodeCrypto.diffieHellman não é uma função** este erro é devido à versão do nó, para mim resolveu com o nó 16.3.2

how can i update my version?

**Comment by rezadaulay** [comment]
Please check this https://github.com/rezadaulay/javascript-example-of-whatsapp-baileys
