### ISSUE TITLE
[MD] ButtonsMessage, listMessage not responding in private chat

### ISSUE THREAD

**Issue by FarhannnnX** [adiwajshing/Baileys#1198]
Please help if you know how to solve listMessage,buttonsMessage don't respond in private chat, but respond in group chat.

Thanks.

**Comment by scriptbypavan** [comment]
can you put your code here

**Comment by Gimenz** [comment]
are you using WABusiness ?

**Comment by FarhannnnX** [comment]
> are you using WABusiness ?

yes, but before that, even though using WABusiness, it just didn't respond

**Comment by AkirahX** [comment]
> > are you using WABusiness ?
> 
> yes, but before that, even though using WABusiness, it just didn't respond

Poste your code bro, we can't just help with what you've given us

**Comment by Fxc7** [comment]
> > > are you using WABusiness ?
> > 
> > 
> > yes, but before that, even though using WABusiness, it just didn't respond
> 
> Poste your code bro, we can't just help with what you've given us
> 
> Here it works perfectly



sorry i forgot the code, This is the code below

```javaScript
async function sendListMessage(jid, sections, quoted) {
    const listMessage = {
        text: "Please Select The Menu You Want To See",
	footer: "All Free Features Without Verify",
	title: "\n\t\t\tWhatsApp Bot Multi-Device",
	buttonText: "Choose Here",
	sections
    };
    return await client.sendMessage(jid, listMessage, { quoted });
}

const sections = [{
    title: "Downloader",
    rows: [
        { title: "menu downloader", rowId: prefix +"menu1", description: "Special Menu To Download Youtube, TikTok Etc" }
    ]
}, {
    title: "maker",
    rows: [
        { title: "menu Maker", rowId: prefix +"menu2", description: "Menu for image maker etc" }
    ]
}]

await sendListMessage(from, sections, m);
```

**Comment by FarhannnnX** [comment]
> > > are you using WABusiness ?
> > 
> > 
> > yes, but before that, even though using WABusiness, it just didn't respond
> 
> Poste your code bro, we can't just help with what you've given us
> 
> Here it works perfectly



sorry i forgot the code, This is the code below

```javaScript
async function sendListMessage(jid, sections, quoted) {
    const listMessage = {
        text: "Please Select The Menu You Want To See",
	footer: "All Free Features Without Verify",
	title: "\n\t\t\tWhatsApp Bot Multi-Device",
	buttonText: "Choose Here",
	sections
    };
    return await client.sendMessage(jid, listMessage, { quoted });
}

const sections = [{
    title: "Downloader",
    rows: [
        { title: "menu downloader", rowId: prefix +"menu1", description: "Special Menu To Download Youtube, TikTok Etc" }
    ]
}, {
    title: "maker",
    rows: [
        { title: "menu Maker", rowId: prefix +"menu2", description: "Menu for image maker etc" }
    ]
}]

await sendListMessage(from, sections, m);
```

**Comment by AkirahX** [comment]
> > > > are you using WABusiness ?
> > > 
> > > 
> > > yes, but before that, even though using WABusiness, it just didn't respond
> > 
> > 
> > Poste your code bro, we can't just help with what you've given us
> > Here it works perfectly
> 
> sorry i forgot the code, This is the code below
> 
> ```js
> async function sendListMessage(jid, sections, quoted) {
>     const listMessage = {
>         text: "Please Select The Menu You Want To See",
> 	footer: "All Free Features Without Verify",
> 	title: "\n\t\t\tWhatsApp Bot Multi-Device",
> 	buttonText: "Choose Here",
> 	sections
>     };
>     return await client.sendMessage(jid, listMessage, { quoted });
> }
> 
> const sections = [{
>     title: "Downloader",
>     rows: [
>         { title: "menu downloader", rowId: prefix +"menu1", description: "Special Menu To Download Youtube, TikTok Etc" }
>     ]
> }, {
>     title: "maker",
>     rows: [
>         { title: "menu Maker", rowId: prefix +"menu2", description: "Menu for image maker etc" }
>     ]
> }]
> 
> await sendListMessage(from, sections, m);
> ```

Are you not treating the answers?  just indicate the rowId with a command from your system and expect this to work?
