### ISSUE TITLE
  client.login() problem without internet on connected phone

### ISSUE THREAD

**Issue by keef3ar** [adiwajshing/Baileys#12]
how to know that connected phone is offline when calling client.login(auth_info)?
It throws no error or event.

**Comment by adiwajshing** [comment]
WhatsApp does not tell you if the phone is disconnected. The connection is kept alive till the phone connects to the internet, after which the connection is established automatically.

**Comment by adiwajshing** [comment]
In the latest version, you can query the following:

``` javascript
client.isPhoneConnected ()
.then (connected => console.log("phone connected: " + connected) )
```

**Comment by areltiyan** [comment]
> In the latest version, you can query the following:
> 
> ```js
> client.isPhoneConnected ()
> .then (connected => console.log("phone connected: " + connected) )
> ```

hir sir, how in Latest version?
