### ISSUE TITLE
[BUG] BUG

### ISSUE THREAD

**Issue by rizka32** [adiwajshing/Baileys#1207]
![IMG-20220204-WA0075](https://user-images.githubusercontent.com/68932997/152517159-9a4a3bdb-c138-40c5-9616-292f9657b859.jpeg)

How to fix this bug? Can you help me? 🙏🏻
On baileys version 4.0.0
And fix pleasee🙏🏻

**Comment by VEXG** [comment]
update baileys, someone just pr the fixes

tip:
press "win + prtsc" or "win + shift + s" to screenshot

**Comment by Millena543** [comment]
> 

![Screenshot_20220211_105022](https://user-images.githubusercontent.com/90538533/153604052-3d8004cd-d43b-4735-aeaa-839a4f244573.jpg)

I did that and it didn't work

**Comment by Millena543** [comment]
H

> > Estou com o mesmo problema, alguém sabe como resolver?
> 
> IRMÃO. ele só disse para você atualizar
> 
> `npm update`ou`yarn update`

I tried this command and it was not accepted
