### ISSUE TITLE
"status@broadcast"

### ISSUE THREAD

**Issue by marcusgir** [adiwajshing/Baileys#1208]
How can I block the message from "status@broadcast"

**Comment by FarhannnnX** [comment]
if (message.key && message.key.remoteJid == "status@broadcast") return;

I hope this helps.

> How can I block the message from "status@broadcast"

**Comment by marcusgir** [comment]
Thank you

**Comment by AkirahX** [comment]
> Thank you

Close if you already got the solution

**Comment by lu4t** [comment]
@AkirahX , @FarhannnnX , is there any place where I could find all the message.key values produced by sock.ev?
Thanks!

**Comment by AkirahX** [comment]
> @AkirahX , @FarhannnnX , is there any place where I could find all the message.key values produced by sock.ev? Thanks!

`console.log(message.key)`

Não entendi muito bem o que deseja, mas creio que seja isso...

**Comment by lu4t** [comment]
> > @AkirahX , @FarhannnnX , is there any place where I could find all the message.key values produced by sock.ev? Thanks!
> 
> `console.log(message.key)` ?
> 
> I don't quite understand what you want, but I think that's it.

thanks for your answer. 
I was asking about a doc where where I can explore the json schemas. Just to make sure there's no msg type missing on the read.me / examples.
I will find out.

**Comment by FarhannnnX** [comment]
> @AkirahX , @FarhannnnX , is there any place where I could find all the message.key values produced by sock.ev? Thanks!

what do you mean by this??
[https://github.com/adiwajshing/Baileys#handling-events](https://github.com/adiwajshing/Baileys#handling-events)

**Comment by lu4t** [comment]
thanks for your answers @FarhannnnX and @AkirahX ; what I meant is: 

Imagine I get a msg with the following schema (just an example):
´´´
{"key":{"remoteJid":"5XXXXXXXXX77@s.whatsapp.net","fromMe":false,"id":"29F68D840EEEEEEEE0BF3C00AB1BC8"},"messageTimestamp":1645550012,"pushName":"XXXXX N","messageStubType":2,"messageStubParameters":["No message found"]}
´´´
is there a way I can find the set of json schemas used/produced by baileys, so that I can know what kind of wa communication / msg / signaling is producing this particular msg schema?, 

Example: I am interested in knowing under which circumstances the object will have "messageStubType" key.

I checked https://github.com/sigalor/whatsapp-web-reveng as suggested on the repo read.me, but I cannot find an easy way to get an answer when you want to map keys on the json object to real wa protocol signaling.

**Comment by AkirahX** [comment]
> thanks for your answers @FarhannnnX and @AkirahX ; what I meant is:
> 
> Imagine I get a msg with the following schema (just an example): `{"key":{"remoteJid":"5XXXXXXXXX77@s.whatsapp.net","fromMe":false,"id":"29F68D840EEEEEEEE0BF3C00AB1BC8"},"messageTimestamp":1645550012,"pushName":"XXXXX N","messageStubType":2,"messageStubParameters":["No message found"]}` is there a way I can find the set of json schemas used/produced by baileys, so that I can know what kind of wa communication / msg / signaling is producing this particular msg schema?,
> 
> Example: I am interested in knowing under which circumstances the object will have `"messageStubType"` key.
> 
> I checked https://github.com/sigalor/whatsapp-web-reveng as suggested on the repo read.me, but I cannot find an easy way to get an answer when you want to map keys on the json object to real wa protocol signaling.

That's what you're looking for, it's not formatted in JSON but there I have all the data that can be obtained from a message.

https://adiwajshing.github.io/Baileys/modules/proto.html

**Comment by lu4t** [comment]
> > thanks for your answers @FarhannnnX and @AkirahX ; what I meant is:
> > Imagine I get a msg with the following schema (just an example): `{"key":{"remoteJid":"5XXXXXXXXX77@s.whatsapp.net","fromMe":false,"id":"29F68D840EEEEEEEE0BF3C00AB1BC8"},"messageTimestamp":1645550012,"pushName":"XXXXX N","messageStubType":2,"messageStubParameters":["No message found"]}` is there a way I can find the set of json schemas used/produced by baileys, so that I can know what kind of wa communication / msg / signaling is producing this particular msg schema?,
> > Example: I am interested in knowing under which circumstances the object will have `"messageStubType"` key.
> > I checked https://github.com/sigalor/whatsapp-web-reveng as suggested on the repo read.me, but I cannot find an easy way to get an answer when you want to map keys on the json object to real wa protocol signaling.
> 
> That's what you're looking for, it's not formatted in JSON but there I have all the data that can be obtained from a message.
> 
> https://adiwajshing.github.io/Baileys/modules/proto.html

Thanks!. This is what I was looking for. :)
