### ISSUE TITLE
 Problem to connect with qr

### ISSUE THREAD

**Issue by IoTCloudStudio** [adiwajshing/Baileys#121]
Dear, I am having a problem when scanning the qr. It returns the following error to me. I understand that the error may be the smartphone but I would like to be sure and if you can guide / help me to solve the inconvenience.
Thank you in advance!
Error-> encountered error: Error: duplicate key: -1597341368546, values: {"jid":"5493413077211@c.us","count":0,"t":"1597341368","mute":"0","spam":"false","messages":[]}, {"jid":"5493464510989@c.us","count":0,"t":"1597341368","mute":"0","spam":"false","messages":[]}

**Comment by adiwajshing** [comment]
This is Baileys 2.0 -- can you try with the latest commit? This should be fixed. Thanks
