### ISSUE TITLE
[BUG] AnyWASocket cannot running

### ISSUE THREAD

**Issue by tommoholmes** [adiwajshing/Baileys#1212]
are you forget add AnyWASocket,
in readme you mention AnyWASocket, but when I try not running, and then I check your code
https://github.com/adiwajshing/Baileys/blob/master/src/index.ts
you missing add AnyWASocket

**Comment by VEXG** [comment]
check the baileys node module folder, it seems the module is not compiled to js

**Comment by Millena543** [comment]
> a pasta do módulo do nó baileys, parece que o módulo não está compilado para js

How can I resolve this?
