### ISSUE TITLE
[BUG] First time message didnt appear on bot MD

### ISSUE THREAD

**Issue by hbinduni** [adiwajshing/Baileys#1215]
i have my bot running using `baileys-md`, but when i try to send first time message from new contact that never chat with my phone bot before, i didnt get the message. i only get the notification but the message empty like this:

```
messages.upsert => notify. {"messages":[{"key":{"remoteJid":"62xxxx@s.whatsapp.net","fromMe":false,"id":"0D0403A780F79F518976E924E2A85746"},"messageTimestamp":1644384552,"pushName":"Vera"}],"type":"notify"}
```

but on the phone, i can see it send message `Test1` into my bot.
Sending the second msg has no issue. i get the message as normal as this:

```
messages.upsert => notify. {"messages":[{"key":{"remoteJid":"62xxxxxx@s.whatsapp.net","fromMe":false,"id":"1E808E96AFB1E0B6B6A18F3EE5CCDFAB"},"messageTimestamp":1644384666,"pushName":"Vera","message":{"conversation":"Test2","messageContextInfo":{"deviceListMetadata":{"recipientKeyHash":"a1IeF7BM1RXW+g==","recipientTimestamp":"1643898991"},"deviceListMetadataVersion":2}}}],"type":"notify"}
```

sending first message using phone that have chat with my bot has no issue. only if the phone is never chat with my bot before, their first message not appear but the second msg appear.

**Comment by AkirahX** [comment]
Verify all params of received message

**Comment by hbinduni** [comment]
> 

do you have any workaround for this issue? i use the bot for onboarding service. it wont work if new chat user are unable to recognize their msg by the bot

**Comment by canove** [comment]
maybe related to https://github.com/adiwajshing/Baileys/issues/928
following...

**Comment by adiwajshing** [comment]
I think this should resolve the issue https://github.com/adiwajshing/Baileys/commit/913b38493c863af7f8bac056a5664291512d36c2

**Comment by hbinduni** [comment]
> I think this should resolve the issue [913b384](https://github.com/adiwajshing/Baileys/commit/913b38493c863af7f8bac056a5664291512d36c2)

i try the latest update, but when i start the bot. i have this error message:

```
(node:91820) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'decode' of undefined
    at Object.processHandshake (/Users/binduni/projects-nodejs/api-kado9/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:100:78)
    at WebSocket.validateConnection (/Users/binduni/projects-nodejs/api-kado9/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:147:30)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by canove** [comment]
> 

@hbinduni , I don't think this error has something to do with this issue. It seems like an error at handshake stage. Maybe you need to clean your authState and read QR code again.

**Comment by hbinduni** [comment]
Thank you @adiwajshing  @canove . i clean up all and rebuild and it run ok now. Thank you very much

**Comment by hbinduni** [comment]
> I think this should resolve the issue [913b384](https://github.com/adiwajshing/Baileys/commit/913b38493c863af7f8bac056a5664291512d36c2)

Hi @adiwajshing i try your update with new number. i get the error as you mention but still the message didnt recognize.
is there any way to get the message that user send to us when this error happen? like get previous message by id or something? thank you.

`{"level":50,"time":1645320552226,"pid":35267,"hostname":"192.168.1.7","msgId":"86FEA1435CD803CBC2E89ED094E443FD","params":["No message found"],"msg":"failure in decrypting message"}`

**Comment by canove** [comment]
Same here.

Looking at code, I think it is already sending a retry after that error. And looks like it is occuring less after @adiwajshing  change, but it still looses a few messages.

It's always the first message of a contact that never talked with my number before.

**Comment by enoksaju** [comment]
same issue:
i try changed the code from [913b384](https://github.com/adiwajshing/Baileys/commit/913b38493c863af7f8bac056a5664291512d36c2), but randomly message is decoded and not decode many times, not possible get the text from new contacts first message.

**Comment by andrody** [comment]
Same problem here, i didnt get the message of new contacts, but second on it works

**Comment by athasamid** [comment]
Any update on this?

**Comment by hbinduni** [comment]
this still an issue? not fixed yet?

**Comment by Zedmerlol** [comment]
+1

**Comment by nasruldev** [comment]
+1
