### ISSUE TITLE
[MD] How to grab contact phone ?

### ISSUE THREAD

**Issue by thaziz** [adiwajshing/Baileys#1219]
how do i get contacts on my phone? thank you

**Comment by jrCleber** [comment]
The **makIngMemoryStore** function creates a data file containing all **chat**, **contact** and **message** information.

```javascript
const store = makeInMemoryStore({});

setInterval(() => store.writeToFile('./dataStore.json'), 10_000);
```
And then you read the file.

```javascript
store.readFromFile(dataStorePath);

const contactsList = store.contacts;

console.log('Contact list: ', contactsList);
```

**Comment by thaziz** [comment]
> The **makIngMemoryStore** function creates a data file containing all **chat**, **contact** and **message** information.
> 
> ```js
> const store = makeInMemoryStore({});
> 
> setInterval(() => store.writeToFile('./dataStore.json'), 10_000);
> ```
> 
> And then you read the file.
> 
> ```js
> store.readFromFile(dataStorePath);
> 
> const contactsList = store.contacts;
> 
> console.log('Contact list: ', contactsList);
> ```
> 
> And finally, pass the **BaileysEventEmitter** as a parameter for the **bind** function to listen for events and update the files.
> 
> ```js
> store.bind(sock.ev);
> ```
> 
> Or:
> 
> ```js
> sock.ev.on('contacts.upsert', (contacts: Contact[]) => {
>     console.log(contacts);
> });
> ```
error sir,  Cannot find name 'makeInMemoryStore'
![image](https://user-images.githubusercontent.com/34264066/153528964-09a5a9e4-bb97-4df6-9569-826b3f58cba5.png)

**Comment by jrCleber** [comment]
Install the data management package: `npm install --save @adiwajshing/keyed-db`

Import the function:
```javascript
import { makeInMemoryStore } from '@adiwajshing/baileys'
```

**Comment by jrCleber** [comment]
Are you running the code on a node server?
Because without knowledge of nodejs, you will never be able to run this code!
