### ISSUE TITLE
Stream error

### ISSUE THREAD

**Issue by clecio81** [adiwajshing/Baileys#1225]
TypeError: Cannot use 'in' operator to search for 'stream' in file.mp4

Code
sock.ev.on('messages.upsert', async (m) => {
const msg = m.messages[0]
		
		if(msg.message.conversation == "8136") {
			console.log('replying to', m.messages[0].key.remoteJid)
     sock.sendMessage(m.messages[0].key.remoteJid, {
     video: "./video.mp4", 
        caption: "hello!",
        gifPlayback: true       
		})
    }
})

**Comment by Gimenz** [comment]
try use this, video: { url: './video.mp4' }

**Comment by clecio81** [comment]
Ok, thank you very much, i will implement

**Comment by lanmower** [comment]
I have the same issue using url

**Comment by lanmower** [comment]
So in my case I accidentally tried
  await client.sendMessage(message.key.remoteJid, {document: fs.readFileSync(filename) })
after reading the source, since its no where in the readme

sends it without a filename so I tried 
  await client.sendMessage(message.key.remoteJid, {document: {url:filename}})
which didn't send anything but didn't report an error

adding a filename: field didn't help either

**Comment by clecio81** [comment]
I switched to the MD version, it worked but it doesn't open the gif files

**Comment by lanmower** [comment]
Also on MD

I managed to get it to send a file by pointing url to the pdf now

However nothing I've tried changes the filename from file

**Comment by lanmower** [comment]
So I did eventually get it to send a pdf without preview, and I did
eventually figure out it had to be document type, took a while to figure
out how to name the file.

I would suggest having some more examples, especially for the document
type, in the readme

**Comment by clecio81** [comment]
I'm giving up on baileys, many problems that don't have an effective method to fix the error, and when they fix a new error, I surrender.

**Comment by zakinshk** [comment]
@clecio81 


Criaram um grupo no whatsapp do Baileys Brazil
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**Comment by clecio81** [comment]
> @clecio81
> 
> Criaram um grupo no whatsapp do Baileys Brazil https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL
> O Link foi redefinido

**Comment by lanmower** [comment]
@clecio81 on the other hand, I'm using it every day, and no longer have to update it the whole time like other libs

**Comment by gandalfhv** [comment]
I need to send files of any format, .xls, .log, etc. Is there any way to do it? "document" always sends as pdf. I didn't find anything in the README
