### ISSUE TITLE
[BUG] Presence subscribe is not working.

### ISSUE THREAD

**Issue by ReiDx** [adiwajshing/Baileys#1226]
Due to the update made by WhatsApp 12 hours ago, we can no longer receive the presence data of any number that we do not message. It gives a stream error.

**Comment by bluej4ker** [comment]
same error

**Comment by halper03** [comment]
> Due to the update made by WhatsApp 12 hours ago, we can no longer receive the presence data of any number that we do not message. It gives a stream error.

Hello @ReiDx now working?
please add me telegram:halper03

**Comment by ewar0401** [comment]
> 

Hello @ReiDx  can you share your solition ? 
Telegram: d1vloper

**Comment by sensuslankoylu** [comment]
there is no solution.whatsapp stopped to provide presence updates when you are not contact to target number before.
if you want to contact target number you will want to send message but when you do this you will be banned

**Comment by enskpl** [comment]
Any solutions?

**Comment by pkral3** [comment]
Well getChatIsOnline() in https://github.com/orkestral/venom/blob/master/src/lib/wapi/wapi.js is still working ok today, it must be similar.
