### ISSUE TITLE
PLEASE HELP ME WITH THIS PROBLEM

### ISSUE THREAD

**Issue by Millena543** [adiwajshing/Baileys#1229]
![Screenshot_20220210_123057](https://user-images.githubusercontent.com/90538533/153615067-d0de1fed-fec4-48be-ba90-520c833372d6.jpg)

The problem came up randomly and I still haven't been able to solve it

**Comment by AkirahX** [comment]
Code?

**Comment by Millena543** [comment]
> Código?

?
