### ISSUE TITLE
Report and Block a number

### ISSUE THREAD

**Issue by codeerror90** [adiwajshing/Baileys#1230]
There is a way to report and block the numbers that make spam by private message to our bots, currently I know how to block but I would like to send a report and block.

**Comment by ferhacks** [comment]
Why would you want to report? Just block and that's it.

**Comment by AkirahX** [comment]
Reporting on whatsapp is useless, just block as said above

**Comment by DroidzinDev** [comment]
Também estou precisando

**Comment by danufirda** [comment]
I also want to report and block, this is useful because I have access to multiple whatsapp accounts and can be used to report one whatsapp user
