### ISSUE TITLE
Question regarding reconnect on Request Time-Out

### ISSUE THREAD

**Issue by swdmnd** [adiwajshing/Baileys#1237]
> Ya'll the connection will inevitably time out, after a couple hours due to many reasons:
> 1. server cycling
> 2. gateways restarting
> 3. server scale up/down
> 4. etc
> 
> So please write your code that can reconnect automatically
> 
> _Originally posted by @adiwajshing in https://github.com/adiwajshing/Baileys/issues/697#issuecomment-940067811_

Does anyone have the idea on how to do this? I traced the error and it came from  a deep promise rejection buried in a series of protocols or whatever it is. Timeout primarily happens on trying to get pending messages (relayMessage) and trying to resend message (sendAgain iirc). The main culprit is in Utils/generic.ts : promiseTimeout. How do I handle this timeout promise rejection from the main code?

**Comment by ajiehatajie** [comment]
same issue

**Comment by HUGEIT** [comment]
`it came from a deep promise rejection buried in a series of protocols or whatever it is` is a very long synonym for "I just spent a minute paraphrasing rather than simply posting it"

**Comment by swdmnd** [comment]
> `it came from a deep promise rejection buried in a series of protocols or whatever it is` is a very long synonym for "I just spent a minute paraphrasing rather than simply posting it"

Exactly. I tried to make it clear but I don't know what that stack of function calling is called. So, how do we catch that rejection from the main code?

**Comment by HUGEIT** [comment]
my man just post the fucking text so we have something to work with. 

either
A) there is something in the console when Baileys ends
B ) your computer has exploded 

and seeing you are still connected to the internet makes the odds look very bad for case B.


summary: post the console output, no matter how useless it may seem

**Comment by swdmnd** [comment]
Well, the fucking question has been asked for many times already in this repo here, THE FREAKING SAME ERROR 408 CONNECTION TIMED-OUT (it's there in thread of the quoted comment by the way, and many more if I search 'timeout', 'timed-out'). Same console output, and has been explained beautifully on why that happens, but the solution (reconnect every few hours) doesn't seem applicable (there'd be a lot of downtime because the error can't be caught), has been asked on how to do that, but I can't find the answer.

Sigh, sorry. I'm too noob for this. I'm out.

**Comment by HUGEIT** [comment]
> Well, the fucking question has been asked for many times already in this repo here, THE FREAKING SAME ERROR 408 CONNECTION TIMED-OUT (it's there in thread of the quoted comment by the way

there are 0 (zero) mentions of 408 in the linked thread.
