### ISSUE TITLE
get contact by id

### ISSUE THREAD

**Issue by JonazBR** [adiwajshing/Baileys#1238]
example
await sock.getContact('558299695883@s.whatsapp.net').then(async r => {
// return {
 pushname: 'Jonaz'
 and other infos
}
})

**Comment by zennn08** [comment]
Maybe you can try this

```Javascript
const store = makeInMemoryStore({})

console.log(store.contacts['558299695883@s.whatsapp.net'])

// or you can create your own function

sock.getContact = function(id) { return store.contacts[id] }
```
It's will return
```Javascript
{
id: "558299695883@s.whatsapp.net",
notify: "Jonaz" // etc
}
```

**Comment by JonazBR** [comment]
> Maybe you can try this
> 
> ```js
> const store = makeInMemoryStore({})
> 
> console.log(store.contacts['558299695883@s.whatsapp.net'])
> 
> // or you can create your own function
> 
> sock.getContact = function(id) { return store.contacts[id] }
> ```
> 
> It's will return
> 
> ```js
> {
> id: "558299695883@s.whatsapp.net",
> notify: "Jonaz" // etc
> }
> ```

this reutned undefined =(
