### ISSUE TITLE
How To Forward a Document Message? 

### ISSUE THREAD

**Issue by WhatTheSemvak** [adiwajshing/Baileys#1239]
I make an pdf Document, but its can't be forwarded manually, so i tried to Force forward the Document using this code

> client.sendMessage(`${q}@s.whatsapp.net`,` doc, MessageType.document, {mimetype:Mimetype.pdf})

but its doesn't work, i reply the doc but its doesn't work
how to fix this?

**Comment by FaizBastomi** [comment]
If you are using Baileys v3, you can forward messages with forwardMessage(), 
```js
con.forwardMessage(chatId, IMessage)
```
if you are using Baileys v4 you can use sendMessage().
```js
con.sendMessage(chatId, { forward: IMessage })
```
