### ISSUE TITLE
[BUG] "BaileysError: Unexpected error in login"

### ISSUE THREAD

**Issue by mhb96** [adiwajshing/Baileys#1241]
Hey guys, I just encountered this error: "Unexpected error in login" while connecting. 

I have encountered this error before but I found a solution which was to update the version to the latest version (found on whatapp web).

But after some months later, I am now getting the same error again, but this time I dont know why (Yes, I have already made sure the version is updated).

What other reasons could there be to receive this error? How can I fix it?

**Comment by AkirahX** [comment]
You are using Baileys 3.5 or 4.0?

**Comment by mhb96** [comment]
3.5.3 to be exact

**Comment by AkirahX** [comment]
> 3.5.3 to be exact. Sorry for not mentioning it before. After coming back after two months, I was oblivious there was a whole new version released.

Ok, verify if you whatsapp is on beta program for whatsapp web or not.

If you use whatsapp beta from play store already on this program automatically.

If you are unable to connect on version 3.5.3, try returning to the "non-beta" version.

**Comment by mhb96** [comment]
Ok, so I havent updated my whatsapp yet, meaning Im not using the multidevice beta, nor have I signed up for it. Im multidevice free.

**Comment by justandoctor** [comment]
resolveu?
