### ISSUE TITLE
How To Get profile picture or Info My WhatsApp ???

### ISSUE THREAD

**Issue by Feeza19** [adiwajshing/Baileys#1242]
My Code:
io.emit('authenticated', conn.user.img + " </br>(" + conn.user.jid + ")")

conn.user.img cannot preview
i need profile picture

Versi:
"@adiwajshing/baileys": "^3.5.2"

**Comment by Feeza19** [comment]
> ```js
> const { jidNormalizedUser } = require('@adiwajshing/baileys')
> await sock.profilePictureUrl(jidNormalizedUser(sock.user.id))
> ```

Please Give Me Example Bro...

**Comment by BochilGaming** [comment]
maaf sebelumnya saya pikir Anda menggunakan versi 4x. ini adalah kode untuk baileys 3.5.2
```js
let url = await conn.getProfilePicture(conn.user.jid)
io.emit('authenticated', `${url} ("${conn.user.jid}")`)
```
