### ISSUE TITLE
[BUG] MP3 audio can't be played on devices (iOS/Android)

### ISSUE THREAD

**Issue by pedroayres** [adiwajshing/Baileys#1243]
audio MP3 do not play on iphone/android users

Code 1:
```javascript

await sock.sendMessage(id, {
      audio: { "https://cdn.discordapp.com/attachments/856962301836263424/943573228524294174/8f41ba31-a7fe-4e2f-a1c0-60c9b75d8020.mp3" },
      ptt: true,
    });


```

Code 2:
```javascript
await sock.sendMessage(
    id, 
    { audio: { url: "https://cdn.discordapp.com/attachments/856962301836263424/943573228524294174/8f41ba31-a7fe-4e2f-a1c0-60c9b75d8020.mp3" }, mimetype: 'audio/mp4' },
    { url: "https://cdn.discordapp.com/attachments/856962301836263424/943573228524294174/8f41ba31-a7fe-4e2f-a1c0-60c9b75d8020.mp3" },
)

```

**Comment by Gimenz** [comment]
based on #896 

set the mimetype...

supported mimes : 
iOS: audio/mpeg 
Android : audio/mp4

let's try 

```js
let mimetype = getDevice(message.id) == 'ios' ? 'audio/mpeg' : 'audio/mp4'

await sock.sendMessage(id, {
      audio: { url: "https://cdn.discordapp.com/attachments/856962301836263424/943573228524294174/8f41ba31-a7fe-4e2f-a1c0-60c9b75d8020.mp3" },
      ptt: true,
      mimetype
    });

```

it will send as WA Playable Audio

CMIIW

**Comment by pedroayres** [comment]
Didn’t work 😢

**Comment by moskoweb** [comment]
Here I managed to solve it by checking ```getDevice``` by contact number.

```
if(extension == 'ogg'){
    mimetype = 'audio/ogg';
} else {
    mimetype = getDevice(phone) == 'ios' ? 'audio/mpeg' : 'audio/mp4';
}

session.sendMessage(phone, { audio: { url: file }, ptt: true, mimetype: mimetype })
```

**Comment by RocketPainel** [comment]
I managed to solve the problem, you need to convert the audios to .opus, you can do this with fluent-ffmpeg.

example:

                                import * as ffmpeg from 'fluent-ffmpeg'
                                import { createReadStream } from 'fs'
                                
`				const final_path = `./src/whatsapp/files/audios/${file.filename.split('.')[0]}.opus`

				const audio_file = await ffmpeg(createReadStream(file.path))
				.output(final_path)
				.audioCodec('libopus')
				.run();
`
