### ISSUE TITLE
[BUG] Error 405 when connecting

### ISSUE THREAD

**Issue by burstfreeze** [adiwajshing/Baileys#1246]
Connecting with an older version will cause a statusCode `405`, setting it to a more recent version results in `401`.

Thanks to @SheIITear we now know that creating a new session with [2, 2204, 13] works.

Looking forward to the genius who finds out how to migrate sessions across versions.

**Comment by SheIITear** [comment]
Version 2.2204.13 with fresh login works for me.

**Comment by erickythierry** [comment]
my bot stopped at that moment too. giving this error 405

**Comment by S0c5** [comment]
Well me too Method Not Allowed here.

**Comment by Luxemburgo** [comment]
Same error 405 here

**Comment by mateusmirandaalmeida** [comment]
The guys at Z-API (https://z-api.io/) have already discovered.
Just update whatsapp version to 2.2204.13

**Comment by 4l3dx** [comment]
You can do this
```
({
	logger: P({ level: 'fatal' }),
	printQRInTerminal: true,
	auth: state,
	version: [2, 2204, 13] // add this line

})
```

**Comment by erickmunozr** [comment]
I'm trying for js but I keep getting the 405 error, with ts it already works

**Comment by muhamad-fadla** [comment]
> Version 2.2204.13 with fresh login works for me.

not working for me

```javascript
let sock = WASocket({
	printQRInTerminal: true,
	version: "2.2204.13",
})
```

**Comment by muhamad-fadla** [comment]
> > > Version 2.2204.13 with fresh login works for me.
> > 
> > 
> > not working for me
> > ```js
> > let sock = WASocket({
> > 	printQRInTerminal: true,
> > 	version: "2.2204.13",
> > })
> > ```
> 
> change version like this: `let sock = WASocket({ printQRInTerminal: true, version: [2, 2204, 13], })` it's works for me.

It's work! Thank you

**Comment by gstdm** [comment]
In which folder should I change the version?

**Comment by BochilGaming** [comment]
> In which folder should I change the version?

you don't need to change your code if you use the latest commit from branch main

**Comment by muzafferkadir** [comment]
> > > Version 2.2204.13 with fresh login works for me.
> > 
> > 
> > not working for me
> > ```js
> > let sock = WASocket({
> > 	printQRInTerminal: true,
> > 	version: "2.2204.13",
> > })
> > ```
> 
> change version like this: `let sock = WASocket({ printQRInTerminal: true, version: [2, 2204, 13], })` it's works for me.

I changed version but it is not working: 
Error : `"message":"Restart Required"`

**Comment by DineshValor** [comment]
Still getting error 405 after updating to latest app version + updated version in @adiwajshing/baileys-md/ ---> Default/index.
Rescan code too,
But error still here in ShiraoriBot.

**Comment by BochilGaming** [comment]
> > > > Version 2.2204.13 with fresh login works for me.
> > > 
> > > 
> > > not working for me
> > > ```js
> > > let sock = WASocket({
> > > 	printQRInTerminal: true,
> > > 	version: "2.2204.13",
> > > })
> > > ```
> > 
> > 
> > change version like this: `let sock = WASocket({ printQRInTerminal: true, version: [2, 2204, 13], })` it's works for me.
> 
> I changed version but it is not working: Error : `"message":"Restart Required"`

you need to restart sock after scanning. try using example.ts without any changes, it works

**Comment by BochilGaming** [comment]
> Still getting error 405 after updating to latest app version + updated version in @adiwajshing/baileys-md/ ---> Default/index. Rescan code too, But error still here in ShiraoriBot.

Use branch master
```
npm i github:adiwajshing/baileys
```

**Comment by DineshValor** [comment]
> > Still getting error 405 after updating to latest app version + updated version in @adiwajshing/baileys-md/ ---> Default/index. Rescan code too, But error still here in ShiraoriBot.
> 
> Use branch master
> 
> ```
> npm i github:adiwajshing/baileys
> ```

Ok thanx for the tip, let me try it

**Comment by DineshValor** [comment]
> 



> > Still getting error 405 after updating to latest app version + updated version in @adiwajshing/baileys-md/ ---> Default/index. Rescan code too, But error still here in ShiraoriBot.
> 
> Use branch master
> 
> ```
> npm i github:adiwajshing/baileys
> ```

Nope, not working, maybe need to update bot script too, that i can't do.
Show error "@adhirajsingh/baileys-md/lib/index.js" not found.

**Comment by erickmunozr** [comment]
I already added the version parameter but it still doesn't connect, it doesn't generate the qr code.

  const sock = makeWASocket({
    logger: P({ level: 'trace' }),
    printQRInTerminal: true,
    auth: state,
    version: "2.2204.13", 
  });

{"level":10,"time":1645103295856,"pid":2143,"hostname":"MacBook-Air-de-Erick.local","fromMe":false,"frame":{"tag":"failure","attrs":{"reason":"405","location":"atn"},"content":null},"msg":"communication"}

**Comment by DineshValor** [comment]
> I already added the version parameter but it still doesn't connect, it doesn't generate the qr code.
> 
> const sock = makeWASocket({ logger: P({ level: 'trace' }), printQRInTerminal: true, auth: state, version: "2.2204.13", });
> 
> {"level":10,"time":1645103295856,"pid":2143,"hostname":"MacBook-Air-de-Erick.local","fromMe":false,"frame":{"tag":"failure","attrs":{"reason":"405","location":"atn"},"content":null},"msg":"communication"}

Change version in main.js file, i already done it and now bot working.

**Comment by muhamad-fadla** [comment]
> I already added the version parameter but it still doesn't connect, it doesn't generate the qr code.
> 
> const sock = makeWASocket({ logger: P({ level: 'trace' }), printQRInTerminal: true, auth: state, version: "2.2204.13", });
> 
> {"level":10,"time":1645103295856,"pid":2143,"hostname":"MacBook-Air-de-Erick.local","fromMe":false,"frame":{"tag":"failure","attrs":{"reason":"405","location":"atn"},"content":null},"msg":"communication"}

bro, there's already an answer above

**Comment by muhamad-fadla** [comment]
```javascript
let sock = WASocket({ 
    printQRInTerminal: true, 
    version: [2, 2204, 13],
 })
```

**Comment by jrCleber** [comment]
> "2.2204.13"

Thanks! It works here.

**Comment by jrCleber** [comment]
> ```js
> let  sock  =  WASocket ( {  
>     printQRInTerminal : true ,  
>     version : [ 2 ,  2204 ,  13 ] , 
>  } )
> ```

Thanks! It works here.

**Comment by frmdeveloper** [comment]
NEW ERROR

```json
{
  "connection": "close",
  "lastDisconnect": {
    "error": {
      "data": {
        "tag": "stream:error",
        "attrs": {},
        "content": [
          {
            "tag": "conflict",
            "attrs": {
              "type": "replaced"
            },
            "content": null
          }
        ]
      },
      "isBoom": true,
      "isServer": false,
      "output": {
        "statusCode": 410,
        "payload": {
          "statusCode": 410,
          "error": "Gone",
          "message": "Stream Errored"
        },
        "headers": {}
      }
    },
    "date": "2022-02-18T12:42:29.076Z"
  }
}
```

**Comment by DineshValor** [comment]
> 

Did you rescan the qr code from latest whatsapp version!?

**Comment by muzafferkadir** [comment]
> NEW ERROR
> 
> ```json
> {
>   "connection": "close",
>   "lastDisconnect": {
>     "error": {
>       "data": {
>         "tag": "stream:error",
>         "attrs": {},
>         "content": [
>           {
>             "tag": "conflict",
>             "attrs": {
>               "type": "replaced"
>             },
>             "content": null
>           }
>         ]
>       },
>       "isBoom": true,
>       "isServer": false,
>       "output": {
>         "statusCode": 410,
>         "payload": {
>           "statusCode": 410,
>           "error": "Gone",
>           "message": "Stream Errored"
>         },
>         "headers": {}
>       }
>     },
>     "date": "2022-02-18T12:42:29.076Z"
>   }
> }
> ```

Same error

**Comment by frmdeveloper** [comment]
> NEW ERROR
> 
> ```json
> {
>   "connection": "close",
>   "lastDisconnect": {
>     "error": {
>       "data": {
>         "tag": "stream:error",
>         "attrs": {},
>         "content": [
>           {
>             "tag": "conflict",
>             "attrs": {
>               "type": "replaced"
>             },
>             "content": null
>           }
>         ]
>       },
>       "isBoom": true,
>       "isServer": false,
>       "output": {
>         "statusCode": 410,
>         "payload": {
>           "statusCode": 410,
>           "error": "Gone",
>           "message": "Stream Errored"
>         },
>         "headers": {}
>       }
>     },
>     "date": "2022-02-18T12:42:29.076Z"
>   }
> }
> ```

already can, accidentally

**Comment by muzafferkadir** [comment]
```
{"level":30,"time":1645191167694,"pid":93920,"hostname":"Muzaffer-MacBook-Air.local","class":"baileys",
"error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,
"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},
"headers":{}}},"msg":"connection closed"}
```

I am using `version: "2.2204.13"` . When I run example.ts there is no problem, but in version 4.0.0 I get this error

**Comment by jrCleber** [comment]
@muzafferkadir 

You need to pass an array with the version number!

```js
 let sock = makeWASocket({  
    printQRInTerminal: true,  
    version: [2, 2204, 13], 
 })
 ```

**Comment by muzafferkadir** [comment]
> @muzafferkadir
> 
> You need to pass an array with the version number!
> 
> ```js
>  const sock = makeWASocket({  
>     printQRInTerminal: true,  
>     version: [2, 2204, 13], 
>  })
> ```

So did i. However, I am getting an error.
