### ISSUE TITLE
Greeting message

### ISSUE THREAD

**Issue by iamjcharly** [adiwajshing/Baileys#125]
Hi is there a way to send a greeting message or manage the firste message?
When a first message is delivered the console send a error sometimes  like this:
UnhandledPromiseRejectionWarning: Error: duplicate key

**Comment by adiwajshing** [comment]
Is this on the latest commit or on the npm version?

**Comment by iamjcharly** [comment]
Sorry I got the last commit and the error was fixed, but I have the doubt if is there a way to send or detect the first message to send a greeting message

**Comment by adiwajshing** [comment]
Yeah, you can check if there are any prior messages via:
``` ts

const {messages} = await conn.loadMessages (jid, 5)
if (messages.length === 1) { // assuming you just got the first message from them
  console.log ('new chat')
  await conn.sendMessage (jid, 'hello there!', MessageType.text)
}

```
