### ISSUE TITLE
[BUG] MD close after that it closes

### ISSUE THREAD

**Issue by KunzxD404** [adiwajshing/Baileys#1250]
Why am I connected after starting and after that it closes even though I have changed networks several times
![Screenshot_20220217-191314_Termux](https://user-images.githubusercontent.com/91834999/154480096-6cf4c2fa-1d5f-4e92-886d-4536d302baa0.jpg)

**Comment by BochilGaming** [comment]
Try use the latest commit from the master branch

**Comment by zakirkun** [comment]
> 

LOL, he said using latest branch master
masa gitu aja gatau...
