### ISSUE TITLE
[BUG] Contacts don't sync properly

### ISSUE THREAD

**Issue by zek** [adiwajshing/Baileys#1251]
**Describe the bug**
I can't see synced contacts properly. Especially if there's a number in your directory who is not in whatsapp, rest contatcs don't sync. 

I'm forcing sync with following command but still no luck

```
await sock.authState.keys.set({'app-state-sync-version': {"critical_unblock_low": null}})
await sock.resyncAppState(["critical_unblock_low"]);
```

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by burstfreeze** [comment]
@zek what do you mean by "properly"? Also add a log to your issue, there is most likely an error message somewhere.
