### ISSUE TITLE
[BUG]  Audio fails to send

### ISSUE THREAD

**Issue by Lucas-LIOM** [adiwajshing/Baileys#1252]
I wanted to send a welcome message through audio in a random way, I installed all the audios and they work perfectly when they are set directly, but in the random way it doesn't work at all, I tried to change the names, I changed the folders and really I don't know what happens, whoever has the solution please send it below

# This is the code I put together, apparently working
![commands](https://user-images.githubusercontent.com/92343590/154530863-10e2cb67-a620-4685-9936-0986e5073ccf.png)=
```ruby
let randomVoice = fs.readFileSync('./assets/media/randoms/utils/randomvoicesprotocol.txt').toString().split('\n') 
let voiceAud = randomVoice[Math.floor(Math.random() * randomVoice.length)]
const voiceLineProtocolo = fs.readFileSync(`./assets/media/voices/${voiceAud}`) 
await custom.sendMessage(from, voiceLineProtocolo, MessageType.audio, { quoted: mek, mimetype: "audio/mp4", ptt: true})
```

# These are the voices (audios) that are uploaded, work flawlessly, tested and approved
![voices in mp3](https://user-images.githubusercontent.com/92343590/154530882-ab5c7343-f476-4191-9c55-de57b7579333.png)

# This is the random form in text, in this case it would take the name of the audio in txt and send it through mp3
![voices in txt](https://user-images.githubusercontent.com/92343590/154530890-1301b839-f0c2-4611-b282-4d5db7e29bb8.png)

# This is error
![image](https://user-images.githubusercontent.com/92343590/154532098-337d773e-fa9c-4ef1-9243-ad6db5b8a3dc.png)

**Comment by tonvital** [comment]
Use the "path" library to set the absolute file path.

**Comment by Lucas-LIOM** [comment]
It worked, but it gives the same thing, it can read only the last txt in the RandomVoices file, the rest gives the same error

![image](https://user-images.githubusercontent.com/92343590/154550531-eda8eda2-5165-41f6-a051-33ff660aa57b.png)

The "menu" command is where the audio will be sent, see that the command I gave above worked without problems, but the command below gave an error, that's the point

![image](https://user-images.githubusercontent.com/92343590/154550852-522e9ec3-5e00-4a6c-8b0e-c7a9907d6266.png)


It can only read the last audio, but the ones above it gives error

Now the code is like this, I believe it's a reading problem but I can't decipher it

```ruby
let randomVoice = path('./assets/media/randoms/utils/randomvoicesprotocol.txt').toString().split('\n') 
let voiceAud = randomVoice[Math.floor(Math.random() * randomVoice.length)]
const voiceLineProtocolo = path(`./assets/media/voices/${voiceAud}`) 
await custom.sendMessage(from, voiceLineProtocolo, MessageType.audio, { quoted: mek, mimetype: "audio/mp4", ptt: true}) 
```

**Comment by Lucas-LIOM** [comment]
> You don't have such a file, you're providing wrong path to it.

See the prints I sent above, the files are existing and they work if I select one by one, my problem is to make it read randomly

**Comment by SheIITear** [comment]
> > You don't have such a file, you're providing wrong path to it.
> 
> See the prints I sent above, the files are existing and they work if I select one by one, my problem is to make it read randomly

Then how is your logic/code of getting a random fail 'baileys bug'?

**Comment by Lucas-LIOM** [comment]
> > > You don't have such a file, you're providing wrong path to it.
> > 
> > See the prints I sent above, the files are existing and they work if I select one by one, my problem is to make it read randomly
> 
> Then how does your logic/code failing become a 'baileys bug'?
> 

Came here to ask for help, if I can't help, end your journey here, I apologize for naming the problem a "bug"

**Comment by zakinshk** [comment]
@Lucas-LIOM 

Criaram um grupo no whatsapp do Baileys Brazil
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL
