### ISSUE TITLE
[BUG] sendMessage with quoted option gives error.

### ISSUE THREAD

**Issue by 0zl** [adiwajshing/Baileys#1253]
**Describe the bug**
Tried to send message for replying/quote previous messages with _quoted option_ gives looped errors.
```js
makeInMemoryStore({
    logger: P().child({ level: 'warn', stream: 'store' })
})
        
/* .... */

sendMessage(Jid, { text: 'Hello' }, { quoted: messages[0] })
```
```
TypeError [Error]: this.isZero is not a function
    node_modules\long\src\long.js:474:14
    WAProto\index.js:211:93:106
    WAProto\index.js:214:11:76
    WAProto\index.js:468:34:76
    WAProto\index.js:228:44:60
    WAProto\index.js:256:57:62
    WAProto\index.js:467:92:78
    WAProto\index.js:592:77:54
    WAProto\index.js:59376:37
```
Error behavior occurs with `makeInMemoryStore.writeToFile` tickers/interval from `example.ts`

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Receive simple message, and reply back with quoted previous message
4. Wait for `makeInMemoryStore.writeToFile` trying to store data.
5. Error throwed.

**Expected behavior**
No errors.

**Environment (please complete the following information):**
 - Is this on a server? _No._
 - What do your `connectOptions` look like? _Exactly from example.ts_
 - Do you have multiple clients on the same IP? _No._
 - Are you using a proxy? _No._

**Additional context**
- Using master/main branch of Baileys.
- Using CommonJS instead of ES6

**Comment by WhatTheSemvak** [comment]
You Put An Zero In messages[0], Should You Try Only  {quoted : messages}
