### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lanmower** [adiwajshing/Baileys#1255]
**Describe the bug**
Cant seem to name PDF documents

**To Reproduce**
await client.sendMessage(id, {document: {url:filename}, filename:"test.pdf" })

**Expected behavior**
a file called test.pdf

**Got**

file.pdf

**Comment by Gimenz** [comment]
have you check the property name properly? 
based on your question, i see the wrong property filename 
 just change **filename** to **fileName** 

```js
await client.sendMessage(id, {document: {url:filename}, fileName:"test.pdf" })
```

CMIIW 😃

**Comment by lanmower** [comment]
![image](https://user-images.githubusercontent.com/657315/154650455-57b45412-c42b-409d-aa41-127ef1cda6c6.png)
is the issue the readme then?

**Comment by Gimenz** [comment]
nice 😃 , have you use VSCode right? if so, I'm sure you can find the property name easily.
