### ISSUE TITLE
[BUG]Method Not Allowed

### ISSUE THREAD

**Issue by imReCoder** [adiwajshing/Baileys#1257]
What does this status code means, can anyone help regarding this ?

connection update (not open| not close) {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
} 

{"level":30,"time":1645212914228,"pid":24348,"hostname":"Recoders-Pc","error":{"data":{"reason":"405","location":"odn"},"isBoom":true,"isServer":false,"output":{"statusCode":405,"payload":{"statusCode":405,"error":"Method Not Allowed","message":"Connection Failure"},"headers":{}}},"msg":"connection closed"}
Connection Close (Not Logged Out) Retrying..

![image](https://user-images.githubusercontent.com/28666727/154750723-cb7ace41-f8c9-4f83-aeae-9872967be631.png)

**Comment by fdciabdul** [comment]
update to lates version from github

**Comment by imReCoder** [comment]
Thanks

> Sorry, but this is a duplicate of #1246

Thanks Problem soved
