### ISSUE TITLE
[BUG] Node process crashes, when i send an image (windows)

### ISSUE THREAD

**Issue by guiireal** [adiwajshing/Baileys#1260]
Platform: Windows 10 Pro

I'm trying to host an application on windows, but when I try to send an image, the node process simply ends, without giving any error clues.

Sample:

![image](https://user-images.githubusercontent.com/13739343/154808784-a6972285-0e9b-45aa-a410-fbf32d9b3192.png)

Pino with debug mode (OK)

![image](https://user-images.githubusercontent.com/13739343/154808853-4bb6bd8b-9853-4485-83ff-cfe7d98de804.png)

Sending test command with test code:

![image](https://user-images.githubusercontent.com/13739343/154808868-2d2c9efd-ca98-4d18-a00e-d76bc3652140.png)

Result in terminal, process stopped without giving any error clues

![image](https://user-images.githubusercontent.com/13739343/154808897-bc37fd4e-d8a4-4c77-8ee1-2306513e3fee.png)

**Comment by guiireal** [comment]
Update:

I tried to put a try catch in the code

![image](https://user-images.githubusercontent.com/13739343/154809080-23b5198e-69ac-4dd9-80e6-2b18cd94862d.png)

Same thing, it doesn't return the error

![image](https://user-images.githubusercontent.com/13739343/154809100-01a62f14-9077-4896-939a-a20153e7dd70.png)

**Comment by guiireal** [comment]
Someone?

**Comment by zhinea** [comment]
same issue
