### ISSUE TITLE
get fileName original (video,image,audio) version 3.5.3 message Media?

### ISSUE THREAD

**Issue by gamadoleo** [adiwajshing/Baileys#1266]
Hello everyone, I can download the media files via `const buffer = await conn.downloadMediaMessage(m)` but I always have to save it with a random name, I would like to know if it is possible to get the original name of the file, because in the object message located, but maybe this information is hidden/encrypted, if someone somehow managed to get the name when downloading, please let me know how.

**Comment by Dakauann** [comment]
if you are working with documents you can find the title of the document inside the message object.

**Comment by gamadoleo** [comment]
thanks, actually for the documentMessage type we have the fileName property, but it seems that this property is unique to this type of message (document).

**Comment by gamadoleo** [comment]
> if you are working with documents you can find the title of the document inside the message object.

thanks, actually for the documentMessage type we have the fileName property, but it seems that this property is unique to this type of message (document).

**Comment by zakinshk** [comment]
@gamadoleo @Dakauann 
Criaram um grupo do Baileys Brazil

**Comment by Dakauann** [comment]
> @gamadoleo @Dakauann Criaram um grupo no whatsapp do Baileys Brazil https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

Oh thx man

**Comment by joaopaulosobral** [comment]
> @gamadoleo @Dakauann Criaram um grupo no whatsapp do Baileys Brazil https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

Qual link correto?

**Comment by diogo-palma** [comment]
@gamadoleo @Dakauann  qual o link?
