### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by FarhannnnX** [adiwajshing/Baileys#1267]
When I run the bot Why is it that when I write a session it takes so long, even though I have only turned it off for a few hours, but when I turn it on again the response takes so long .
Sorry in advance, this time there is no solution🙏🙏

**Comment by DikaArdnt** [comment]
> When I run the bot Why is it that when I write a session it takes so long, even though I have only turned it off for a few hours, but when I turn it on again the response takes so long . Sorry in advance, this time there is no solution🙏🙏

deleting all chats before scanning might provide a little solution  🙂🙂

**Comment by FarhannnnX** [comment]
> > When I run the bot Why is it that when I write a session it takes so long, even though I have only turned it off for a few hours, but when I turn it on again the response takes so long . Sorry in advance, this time there is no solution🙏🙏
> 
> deleting all chats before scanning might provide a little solution 🙂🙂

Aaa Thanks for your suggestion, maybe there is another way without re-scan??
