### ISSUE TITLE
sendReadReceipt throwing error 400

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#127]
When using `conn.sendReadReceipt(jid)` it returns a error

```BaileysError: Unexpected status code in 'action': 400
    at WAConnection.query (/conn/WAConnection/0.Base.js:224:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WAConnection.setQuery (/conn/WAConnection/0.Base.js:198:24)
    at async WAConnection.sendReadReceipt (/conn/WAConnection/7.MessagesExtra.js:51:22) {
  status: 400,
  context: { query: [ 'action', [Object], [Array] ], status: 400 }
}```

**Comment by adiwajshing** [comment]
Does your chat have any unread messages?

**Comment by algoz098** [comment]
Yes, it does,

**Comment by algoz098** [comment]
It seems we need a message ID now, or it doesn't work? Cant we just mark the chat as read, and done?

**Comment by adiwajshing** [comment]
WA may have changed something, it didn't need an ID. Can you check by passing the latest message ID of the chat?

Using this:
```  ts
const {messages} = await chat.loadMessages (jid, 20)
const message = messages.reverse().find (m => !m.key.fromMe) // find the latest message not from me

conn.sendReadReceipt(jid, message.key.id)

```

**Comment by algoz098** [comment]
This works!

**Comment by adiwajshing** [comment]
Okay -- this was a cool experiment. I'll make the same change in Baileys so that this is handled automatically and you can just call `conn.sendReadReceipt(jid)`

**Comment by adiwajshing** [comment]
This is implemented as `conn.chatRead(jid)` in the latest commit
