### ISSUE TITLE
[BUG] help

### ISSUE THREAD

**Issue by gstdm** [adiwajshing/Baileys#1270]
I can't send cart messages, help me run the right command

**Comment by binsarjr** [comment]
please don't carelessly add bug labels. join discord if you need help

**Comment by jrCleber** [comment]
Can not! To send cart messages, the item must be registered in the catalog. And you can only do this manually, as whatsapp validates each item individually.

Another thing! When you register an item in the catalog on whatsapp business, an id is generated by whatsapp. And you need that id to send the cart.

**Comment by gstdm** [comment]
> Can not! To send cart messages, the item must be registered in the catalog. And you can only do this manually, as whatsapp validates each item individually.
> 
> Another thing! When you register an item in the catalog on whatsapp business, an id is generated by whatsapp. And you need that id to send the cart.

these are "fake" messages, I've seen these messages sent by baileys in other places.. if you don't get it, thank you anyway.

**Comment by AkirahX** [comment]
> Can not! To send cart messages, the item must be registered in the catalog. And you can only do this manually, as whatsapp validates each item individually.
> 
> Another thing! When you register an item in the catalog on whatsapp business, an id is generated by whatsapp. And you need that id to send the cart.

Na verdade é possível sim.

I don't have any example ready but I leave the link in the documentation about it.

https://adiwajshing.github.io/Baileys/classes/proto.ProductMessage.html#constructor

**Comment by gstdm** [comment]
> > Can not! To send cart messages, the item must be registered in the catalog. And you can only do this manually, as whatsapp validates each item individually.
> > Another thing! When you register an item in the catalog on whatsapp business, an id is generated by whatsapp. And you need that id to send the cart.
> 
> In fact, it is possible.
> 
> I don't have any example ready but I leave the link in the documentation about it.
> 
> https://adiwajshing.github.io/Baileys/classes/proto.ProductMessage.html#constructor

where can i find a ready example?  I was not able to.
