### ISSUE TITLE
How to tag user in group

### ISSUE THREAD

**Issue by joelvitorniino** [adiwajshing/Baileys#1271]
How to tag user in group with @?

```
const metadata = await sock.groupMetadata(m.key.remoteJid, false); 
const array = []; 
metadata.participants.forEach((participant, i) => array[i] = `@${participant.id}`); 
const allMembers = array.toString().split(',').join('\n').split('@s.whatsapp.net').join(''); 

sock.sendMessage(m.key.remoteJid, {
 text: allMembers
});
```

Is not working, what I should make?

**Comment by DwiRizqiH** [comment]
const metadata = await sock.groupMetadata(m.key.remoteJid, false);
const array = metadata.participants.map(all => all.id)
let allMembers = ''
array.forEach((participant, i) => allMembers += `@${array[i].replace('@s.whatsapp.net', '')}\n`)

await sock.sendMessage(from, { text: allMembers, mentions: array })

**Comment by joelvitorniino** [comment]
> const metadata = await sock.groupMetadata(m.key.remoteJid, false);
> const array = metadata.participants.map(all => all.id)
> let allMembers = ''
> array.forEach((participant, i) => allMembers += `@${array[i].replace('@s.whatsapp.net', '')}\n`)
> 
> await sock.sendMessage(m.key.remoteJid, { text: allMembers, mentions: array })

Thanks! It's working

**Comment by zakinshk** [comment]
@joelvitorniino  
Criaram um grupo do Baileys brasil
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**Comment by ycarooliveira** [comment]
Hey @zakinshk send group link again, this one is invalid now
