### ISSUE TITLE
[Questions] How To Set thumbnail  mp4/video in MD

### ISSUE THREAD

**Issue by NadhiraAlifah** [adiwajshing/Baileys#1275]
![carbon (1)](https://user-images.githubusercontent.com/80480704/155304802-d18a17f3-2c48-42e1-9370-f2a3f7b83077.png)

this code not working

**Comment by BochilGaming** [comment]
```js
await conn.sendMessage(from, { 
  video: { url: 'http://your.url' }, 
  jpegThumbnail: BufferThumbnail,
  caption: 'your caption'
}, { quoted:m })
```

**Comment by NadhiraAlifah** [comment]
> ```js
> await conn.sendMessage(from, { 
>   video: { url: 'http://your.url' }, 
>   jpegThumbnail: BufferThumbnail,
>   caption: 'your caption'
> }, { quoted:m })
> ```

okeey thanks

**Comment by NadhiraAlifah** [comment]
Solved
