### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FatihArridho** [adiwajshing/Baileys#1276]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '../Defaults/baileys-version.json'
Require stack:

why is the latest update an error?

**Comment by ilyaborodin** [comment]
Need to change tsconfig to compile json files. Fast solution copy  '..src/Defaults/baileys-version.json' to '..lib/Defaults/baileys-version.json'

**Comment by FatihArridho** [comment]
thanks:D

> Need to change tsconfig to compile json files. Fast solution copy '..src/Defaults/baileys-version.json' to '..lib/Defaults/baileys-version.json'
