### ISSUE TITLE
Baileys (MD) 'Unknown error' ERROR: 400 - DATA: 500 BAD REQUEST

### ISSUE THREAD

**Issue by Bloxoid123** [adiwajshing/Baileys#1282]
This problem appears when I try to send multimedia content or stickers.

example
user sends: "test"

BaileysMD Answers: IMAGE or STICKER

this problem only happens to me on heroku when many people try to use the command
in localhost works fine

any solution?

/app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290
throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });
^
Error: bad-request
at assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:48)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async groupMetadata (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41
at async Promise.all (index 0)
at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51
at async Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:72:17)
at async relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9)
at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:395:17) {
data: 400,
isBoom: true,
isServer: true,
output: {
statusCode: 500,
payload: {
statusCode: 500,
error: 'Internal Server Error',
message: 'An internal server error occurred'
headers: {}
}
}

DEPLOYED ON HEROKU

**Comment by Bintangp02** [comment]
> This problem appears when I try to send multimedia content or stickers.
> 
> example user sends: "test"
> 
> BaileysMD Answers: IMAGE or STICKER
> 
> this problem only happens to me on heroku when many people try to use the command in localhost works fine
> 
> any solution?
> 
> /app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290 throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code }); ^ Error: bad-request at assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15) at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:48) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async groupMetadata (/app/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24) at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41 at async Promise.all (index 0) at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51 at async Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:72:17) at async relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9) at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:395:17) { data: 400, isBoom: true, isServer: true, output: { statusCode: 500, payload: { statusCode: 500, error: 'Internal Server Error', message: 'An internal server error occurred' headers: {} } }
> 
> DEPLOYED ON HEROKU

Indonesian
```
Kejadian ini sama seperti saya :)
```
English
```
This incident also happened to me :)
```

**Comment by tiagoandrepro** [comment]
+1

**Comment by atakanargn** [comment]
+1
