### ISSUE TITLE
Is it possible to detect the event when baileysMD receives a call?

### ISSUE THREAD

**Issue by akashreddy03** [adiwajshing/Baileys#1287]
I want to take certain actions when Baileys receives a call is that possible?

**Comment by banyu-wigara** [comment]
Yes it's, I remember have seen it somewhere in Bailes's discord channel ...

> I want to take certain actions when Baileys receives a call is that possible?

**Comment by gelpiu-developers** [comment]
Something like:

`socket.ws.on(`CB:call`, (node: BinaryNode) => {// your code});`

**Comment by zennn08** [comment]
My Code :

```Javascript
sock.ws.on('CB:action,,call', (json) => {
    console.log(json)
    // Your Code
 })
```

**Comment by gelpiu-developers** [comment]
> My Code :
> 
> ```js
> sock.ws.on('CB:action,,call', (json) => {
>     console.log(json)
>     // Your Code
>  })
> ```

This code was not working for me... The callback was never called...
