### ISSUE TITLE
[BUG] why i don't get qr code

### ISSUE THREAD

**Issue by NadhiraAlifah** [adiwajshing/Baileys#1290]
![image](https://user-images.githubusercontent.com/80480704/155874014-46365977-3a81-4d84-b649-838bf16eff58.png)

**Comment by imReCoder** [comment]
you need to share code, cant say anything without seeing the code

**Comment by NadhiraAlifah** [comment]
> you need to share code, cant say anything without seeing the code
![carbon (2)](https://user-images.githubusercontent.com/80480704/155880896-e27af564-7373-43eb-bc66-62af3e0cfe1e.png)

**Comment by DikaArdnt** [comment]
> ![image](https://user-images.githubusercontent.com/80480704/155874014-46365977-3a81-4d84-b649-838bf16eff58.png)

npm i qrcode-terminal
