### ISSUE TITLE
[BUG] error 428 - possibly not sending pings during message processing?

### ISSUE THREAD

**Issue by HUGEIT** [adiwajshing/Baileys#1292]
this is related to #1152 but instead of `408`, with more messages we see the error `428` coming up.

```

/Baileys/src/Socket/socket.ts:74
			throw new Boom('Connection Closed', { statusCode: DisconnectReason.connectionClosed })

Error: Connection Closed
    at sendRawMessage (/Baileys/src/Socket/socket.ts:74:10)
    at sendNode (/Baileys/src/Socket/socket.ts:84:10)
    at sendMessageAck (/Baileys/src/Socket/messages-recv.ts:65:9)
    at /Baileys/src/Socket/messages-recv.ts:500:12
    at /Baileys/src/Utils/make-mutex.ts:13:12 {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}
```

How it leads up to there:

```second 00: {"tag":"offline_preview","attrs":{"count":"7771","message":"7771" ... 0, 0, 0, 0```

```second 27: connection update { receivedPendingNotifications: true }```

```second 40: recv keep alive```

lots of messages come in, `receipt ack`s and `retry receipt`s  get sent, 

the final message of the pack is:

```second 72: sent \"receipt\" ack```

and then after about a minute of silence the Boom kicks in (no timestamp here).

given that the last `keep alive` is way older than 30 seconds, I suppose something keeps the thread busy in Baileys which then prevents the interval from triggering. since the server hasn't received a ping in a while it may disconnect the socket which leads to the connection loss. or maybe the socket is "overloaded" somehow and closes like that.

I put a log to sending the pings and ran Baileys again, for the remaining ```offline_preview","attrs":{"count":"5405","message":"3824","receipt":"1557","notification":"24","appdata":"0"``` and there is no issue anymore, I can see the pings in regular intervals and it doesn't seem to be "blocked" anymore and is able to perform a full sync.

what do you suggest? is there something else we should put on mutex? maybe the acks for messages?

**Comment by Bloxoid123** [comment]
+1

**Comment by HUGEIT** [comment]
I am surprised so many people seem to have the same issue. or maybe similar issues with the same outcome. interesting

**Comment by HUGEIT** [comment]
just a comment to avoid stale bot

**Comment by HUGEIT** [comment]
@SuyKingsleigh this does not really have to do with the issue at all. it doesn't really matter how you send a message as long as you do not send it while being disconnected or in a bad state such as the situation in my opened issue

**Comment by HUGEIT** [comment]
removing stale

**Comment by HUGEIT** [comment]
@adiwajshing  so a bit of news regarding that, especially with the latest commits - I kept 3 sessions offline for a week, here is what I found:

- *the offline preview count generally does not go far beyond 3000*. on my test phone I have that many messages in an hour but the offline preview only seems to announce the last 300 or so for each chat. no matter if it's a more recent session or a very old one, it's always like 3300 give or take. so whatever we can do to optimize, we won't need to take in account much more than 3000 messages 

.

- I have added a log statement to the `catch` for the pings. this is what throws. it then causes a 
```
connection update {
  connection: 'close', ... Timed Out
```
probably from the console.log in the example.ts. 

what's weird is that I do not see the `using WA v2.2206.9, isLatest: true` coming up again. I suppose the event loop is too busy to even trigger the reconnect logic in example.ts (unless it should not trigger in that case?)

shortly after, Baileys throws a lot of 428 that now get soft-caught instead of resulting in an immediate crash which is nice. however, later down the line, we get back to a 428 that actually breaks the process as before:

```
at sendRawMessage (//src/Socket/socket.ts:74:10)
    at sendNode (//src/Socket/socket.ts:84:10)
    at //src/Socket/messages-recv.ts:123:10
    at assertingPreKeys (//src/Socket/socket.ts:233:9)
    at async sendRetryRequest (//src/Socket/messages-recv.ts:69:3)
    at async //src/Socket/messages-recv.ts:349:18 
```

I think we'd have to reset the stack on a broken connection so it won't try to process messages in a connection that's already disconnected.

maybe the event loop gets so fed up that the most basic things (like event handling in example.ts) don't trigger anymore, causing the connection to drop, it's either that or something described in the next point:

.

- *Baileys incoming ws processing seems to slow down A LOT* when the session has just worked through a lot of messages. even when things have cooled down (no new messages to digest anymore), I found numerous instances of the ping being sent **twice** or more before even the response for the first ping comes in. if we suddenly receive a lot of messages in a previously-running-normally session in a short time, the delay between the pings and the responses starts to spread out again, potentially leaving us to another 'Timed Out" message.

here is an example
<details>
<summary>log - a lot of time can pass between pings, responses and other incoming data</summary>

```

{
  tag: 'iq',
  attrs: { id: 'b.c-35', to: '@s.whatsapp.net', type: 'get', xmlns: 'w:p' },
  content: [ { tag: 'ping', attrs: {} } ]
}

{
  tag: 'iq',
  attrs: { id: 'b.c-36', to: '@s.whatsapp.net', type: 'get', xmlns: 'w:p' },
  content: [ { tag: 'ping', attrs: {} } ]
}

{
  tag: 'iq',
  attrs: { id: 'b.c-37', to: '@s.whatsapp.net', type: 'get', xmlns: 'w:p' },
  content: [ { tag: 'ping', attrs: {} } ]
}
SOME MORE SECONDS PASS
{
  tag: 'iq',
  attrs: { id: 'b.c-38', to: '@s.whatsapp.net', type: 'get', xmlns: 'w:p' },
  content: [ { tag: 'ping', attrs: {} } ]
}
THEN AFTER A WHILE
{"level":50, No sender key for "failure in decrypting message"}
{"level":30,,"sent retry receipt"}
{"level":10,,"class":"receipt","type":"retry","id":"
{"level":10,,"attrs":{"from":"","type":"picture"
{"level":20,,"type":"picture"},"msg":"sent \"notification\" ack"}
{"level":10,,"msgId":"b.c-35","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"b.c-35","t":"1647447921"},"content":null},"msg":"communication"}
{"level":10,,"msg":"recv keep alive"}
WITHIN 4 SECONDS

```

</details>

so either the server starts to stutter or Baileys is busy with something that does not clear up. I suppose it's on Baileys because if I restart the session, ping responses come back instantaneously (or at least the delay is way less than a second and in any case much less than the e.g. 30 seconds that I see when the session was busy before).


--

conclusion: what would probably fix this is having a way to have the pings (and especially their responses) prioritized over things like message processing to give the process some CPU time to actually handle what's important - keeping the connection active.

the issue could also go the reverse way - maybe if we are replying to incoming messages too quickly, it's actually the server that sends out delayed responses. if the server was limited in bandwidth for each session that could very well be possible too but since the whatsapp website is faster than Baileys I tend to blame us at Baileys for now.

**Comment by HUGEIT** [comment]
to complicate things a little, it seems that pino does some debouncing of some sort.

```
               lastDateRecv = new Date()
		console.log(lastDateRecv.getMilliseconds(), "!!0 recv keep alive in console.log")
		logger.trace('recv keep alive')


334 !!0 recv keep alive in console.log
{"time":1647460597850,"re
{"time":1647460597850,"ji
{"time":1647460597850,"ms
{"time":1647460599099,"ms
{"time":1647460599209,"re
{"time":1647460599210,"ji
{"time":1647460599210,"ms
{"time":1647460600837,"ms
{"time":1647460600837,"re
{"time":1647460604334,"msgId":"c.1-7"
{"time":1647460604335,"msg":"recv keep alive"}
```

**Comment by makanSukros** [comment]
I'm not alone, few minutes after connected, im getting error like this

...output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }

**Comment by makanSukros** [comment]
> I'm not alone, few minutes after connected, im getting error like this on function onWhatsApp
> 
> ...output: { statusCode: 428, payload: { statusCode: 428, error: 'Precondition Required', message: 'Connection Closed' }, headers: {} }

related this issue, this issue solved temporary with restarting node service, im trying reconnecting after get this message, but return to mutch loop reconnecting, 

my example script to reconnecting: 


try{
                    if(ex.toString().includes('Connection Closed')){
                        this.conn = this.startSock(function(ex){
                            console.log('Reconnecting Using Precondition Required')
                        });
                    }
                }catch(catchErrorMsg){

                }

is there something wrong with my reconnect algorithm?

**Comment by makanSukros** [comment]
And when I try to re-scan the qr code initially it's normal, I can get new message events and others but when I call the onWhatsApp function the Precondition Required error appears again

**Comment by HUGEIT** [comment]
some more info

I was wrong about the 3000. I have seen logs with more than 10000 messages now. 

I also noticed that the pino logs are not reliable in timing since they seem to be throttled for some reason. I have added simple console.log statements to the ping responses and indeed sometimes there is no response despite the connection being alive.

the problem in that case is that Baileys cancels the connection although the server is sending stuff over (which means the connection is still there, which in turn means Baileys should not cancel) https://github.com/adiwajshing/Baileys/blob/master/src/Socket/socket.ts#L379

I propose a way out of the current promise-based ping check and rather do something like an interval that checks for `lastDateRecv` - which always gets set by whenever the socket receives something instead of solely relying on the ping responses that get delayed for whatever reason.


I searched through the appjs repo for a timeout interval to see if we simply use a bad number but based on the variable name that matched our ms interval I found something interesting. I can't hard link the link in his repo because it exceeds the display limit so here is a screenshot and where to look out for these lines:

![image](https://user-images.githubusercontent.com/94182206/159330957-3c7bdbdb-a9dd-4a38-a30c-36a2d80553f9.png)

in https://github.com/burstfreeze/appjs/blob/master/app/renderer.js 

I can be wrong but it looks like (instead of my proposal to make it reset on every incoming message) that whenever the app receives a stanza this "timeout timer" is cancelled.

there is also an ActivePing that _is accessed in a way_ on stanzas. idk what that is about but it could be something related

![image](https://user-images.githubusercontent.com/94182206/159333286-3554fb0f-80ea-4bce-95ce-5d1c060e905d.png)



I will temporarily disable the `end()` in the ping catch and see how that goes to see if the connection will stay up beyond that.



on another note there is also something called HealthCheck and it seems like it will not launch if there is stuff pending which kind of sounds similar.

![image](https://user-images.githubusercontent.com/94182206/159332683-8e52d280-3827-4568-bcc6-80362256cce1.png)

**Comment by HUGEIT** [comment]
**solved part 1 of the issue**. removed the `end()` from the ping logic and the connection stayed up, it was a second run with 9000 missed messages. the connection even stays up for minutes if we don't send pings at all.

@adiwajshing I would PR changes to the `startKeepAliveRequest()` that look like the following:

- send the ping as it was before, on responses to that set `lastDateRecv` as before
- have every incoming stanza set the `lastDateRecv` as well
- break (`end()`) **only** in the `diff > keepAliveIntervalMs + 5000` condition

in other words, I would remove the promise-based `end()` because the server won't reply to the ping when he's sending a lot of stanzas anyway. the stanzas seem to be substitutes for the ping responses 

for the record: we probably don't even have to send pings at all during normal stanza IO since every message we exchange signals both sides that the connection is still up but I would still keep the sending going, it's just that our processing is too harsh right now.


let me know what you think and I will PR.




**however, any sessions towards 10k pending also run the risk of something else (that is part 2 of the problem)** 

if there are a lot of key exchanges (I guess), we see a 100% CPU usage that blocks all intervals. to test why the pings sometimes aren't even sending I added the following to `example.ts`:

```
setInterval(() => {
	console.log(`interval triggered`)
}, 10_000)
```

the session crashed after a few minutes **without a single execution of the print in the interval**. I highly suspect that there is a synchronous operation in Baileys taking place that puts so much load on the stack that the execution of the simplest things is blocked. I noticed that the singleFileAuthState uses synchronous operations which may cause that. would there be a downside in making them async? a bit concerned about the order of operations so I tried a mutex but unfortunately that did not go far

<img width="290" alt="image" src="https://user-images.githubusercontent.com/94182206/159596015-012f37b4-83b2-4476-96df-a0a39c66f1a7.png">

**Comment by adiwajshing** [comment]
1. PR to set `lastDateRecv` with any incoming stanza sounds good
2. the sync stuff is only for the auth file state, any asynchronous key management store should not have an issue. You could mutex the operations, make the IO async and see if that makes a difference to the CPU

**Comment by HUGEIT** [comment]
1. I was just about to fork for my PR, noticed that you were faster than me, thank you for crediting me on the commit, I really appreciate that!
2. for some reason the mutex won't do anything at all in that context but it's probably a user-error. I will check on my side first and ping you if I run into issues, thank you

**Comment by HUGEIT** [comment]
solved. 20k messages (about 9k of them "real" messages) and no crash. thank you adi

**Comment by HUGEIT** [comment]
please note that 428 can also occur on other queries. I haven't used these so I haven't stumbled across issues with that.

please open a new issue with your specific problem if it also results in a 428 but hasn't been fixed with the current commit.

**Comment by guiguicdd** [comment]
I´m facing the same issue!

![image](https://user-images.githubusercontent.com/50055027/167273759-a20717ce-c8f7-43a4-991d-0799d02901e3.png)
![image](https://user-images.githubusercontent.com/50055027/167273766-9685cdaf-f373-4768-b709-c2669169d876.png)
![image](https://user-images.githubusercontent.com/50055027/167273795-97c38fb7-005c-4f17-9419-4cc12b4748b5.png)
![image](https://user-images.githubusercontent.com/50055027/167273968-cecd6fbf-9a2c-4cdc-b0fe-2e9a29c74401.png)

**Comment by HUGEIT** [comment]
@guiguicdd is the first image the content of the message you send? then it's not related to my issue here, my issue is without taking any action

**Comment by kim-dev-git** [comment]
> Ok, I found a workaround, I created a sock.ev.on('my-new-event', (data) => {params to send message}) and every time I want to send a message, I call sock.ev.emit('my-new-event', data);
> 
> ```
> // @ts-ignore
> sock.ev.on('send-text-message', (body: { jid: string, textMessage: string }) => {
>     sock.sendMessage(body.jid, {text: body.textMessage});
> })
> 
>     // @ts-ignore
>     sock.ev.emit("send-text-message", {jid: "somePhoneNumber@s.whatsapp.net", textMessage: "Hello World!"});
> ```
> 
> I Know that ain't pretty but works fine

Thanks man, this is live saver.
The down side is we cant receive the response either the message is sended or not.

**Comment by moskoweb** [comment]
@HUGEIT This error has happened to me, it seems to be related to the error I had, I wanted to know how you managed to solve this error code problem 1006?

<img width="1243" alt="Captura de Tela 2022-12-23 às 19 28 19" src="https://user-images.githubusercontent.com/6052272/209410581-5d311977-0ddc-4125-b6b8-53119fe809ba.png">

<img width="1261" alt="Captura de Tela 2022-12-23 às 19 28 51" src="https://user-images.githubusercontent.com/6052272/209410585-081ba673-76ca-4f82-b60c-4a6297b9e3cf.png">
