### ISSUE TITLE
[BUG] MD - Messages take long to be send sometimes the are not.

### ISSUE THREAD

**Issue by samuelmunyoki** [adiwajshing/Baileys#1297]
**Describe the bug**
Messages take long to be send sometimes the are not when using the npm module with common javascript, i saw a fix with typescript but not javascript

**Comment by zakinshk** [comment]
@samuelmunyoki 
tem um grupo do baileys-br
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL
