### ISSUE TITLE
How do I get the name of the contact

### ISSUE THREAD

**Issue by yurisanp** [adiwajshing/Baileys#130]
I've seen a question like this one that tells me to use ->https://github.com/adiwajshing/Baileys/issues/119
`const name = conn.chats.get ('1234@s.whatsapp.net').name`

But I need the name of the number on whatsapp because I will receive messages from numbers that are not saved as contacts.

Example (Fabio):
![image](https://user-images.githubusercontent.com/62726473/91762426-b6618200-ebab-11ea-98ba-354af35e883a.png)

**Comment by sthales** [comment]
Try something like ```const name = conn.chats.get ('1234@s.whatsapp.net').notify```

**Comment by yurisanp** [comment]
It didn't work for me, return an undefined!

![image](https://user-images.githubusercontent.com/62726473/91765855-0b06fc00-ebb0-11ea-81db-ae0a9944d88e.png)

**Comment by adiwajshing** [comment]
`const name = conn.chats.get ('1234@s.whatsapp.net').name` -- this should work, does it not?

**Comment by yurisanp** [comment]
![image](https://user-images.githubusercontent.com/62726473/91852031-975c0200-ec36-11ea-9669-288470a0869d.png)

Hi @adiwajshing, I believe that this has been fixed in some of the new versions, this print above is before updating the baileys, remembering that my version was from last Sunday.

![image](https://user-images.githubusercontent.com/62726473/91853280-59f87400-ec38-11ea-82e9-4083ffd4f861.png)

Now it's working:
`const name = conn.chats.get ('1234@s.whatsapp.net').name`
