### ISSUE TITLE
[BUG][MD] groupParticipantsUpdate not promote multiples participants

### ISSUE THREAD

**Issue by moskoweb** [adiwajshing/Baileys#1300]
**Describe the bug**
I tried to promote an array of participants to admin, and it was returning an ide timeout error, it only worked by passing one participant at a time within an array.

```
await sock.groupParticipantsUpdate(
    success.id,
    [participant],
    "promote"
);
```

**Comment by veracity-ind** [comment]
Not working for multiple ids, for since id it is working
