### ISSUE TITLE
[BUG] MD the qr code does not appear, only the code

### ISSUE THREAD

**Issue by KunzxD404** [adiwajshing/Baileys#1302]
Help me:/
![Screenshot_20220301-143613_Termux](https://user-images.githubusercontent.com/91834999/156125706-b496fee4-7891-4de3-8ac6-bab1cfadc076.jpg)

**Comment by VEXG** [comment]
yea, because of this. the qr code module is not installed

![image](https://user-images.githubusercontent.com/83714022/156164165-fb54c6d9-06ee-4e19-b9fe-f51958b5ff89.png)

**Comment by KunzxD404** [comment]
> ya, karena ini. modul kode qr tidak diinstal
> 
> ![gambar](https://user-images.githubusercontent.com/83714022/156164165-fb54c6d9-06ee-4e19-b9fe-f51958b5ff89.png)

apparently not yet, I forgot to add qrcode-terminal to package.json so during installation there is no file😄
