### ISSUE TITLE
[BUG] MD Button lock not responding

### ISSUE THREAD

**Issue by KunzxD404** [adiwajshing/Baileys#1303]
![20220301_201512](https://user-images.githubusercontent.com/91834999/156175595-2d3e3ac7-db90-45d4-919e-fb4fb66a3f9b.jpg)

when using the image, the https error occurs, and I use butloc, do you have any suggestions for me? :/

**Comment by KunzxD404** [comment]
![20220301_202533](https://user-images.githubusercontent.com/91834999/156177261-b0402e65-cfa6-4f62-98f5-d3c6299f04a9.jpg)
In private chat

**Comment by AkirahX** [comment]
Post your code bro, of how it created and how it is "getting" the response from the button.

**Comment by KunzxD404** [comment]
> Post your code bro, of how it created and how it is "getting" the response from the button.

![20220302_074904](https://user-images.githubusercontent.com/91834999/156273508-f654dbdb-0fd6-44d0-8149-42ed2345e5cc.jpg)
case 'play2':
if (!q) return reply(mess.wrongFormat)
srch = `${q}`
var url = await yts(srch)
url = url.videos[0].url
hxz.youtube(url).then(async(data) => {
var butt = [{ buttonId: `/ytmp3 ${url}`, buttonText: { displayText: `🎵 Audio` }, type: 1 }, { buttonId: `/ytmp4 ${url}`, buttonText: { displayText: `🎥 Video` }, type: 1 }]
textplay = `*Judul :* *${data.title}*\n*Size mp4 :* *${data.size}*\n*Size mp3 :* *${data.size_mp3}*`
var teks = `${textplay}`
})
hisoka.sendMessage(from, { caption: textplay, image: {url: `https://i.ibb.co/CPcFJ6c/IMG-20220131-WA0504.jpg`}, buttons: butt, footer: 'KID BOT-MD', mentions: [m.sender]} )  
break

**Comment by AkirahX** [comment]
> > Post your code bro, of how it created and how it is "getting" the response from the button.
> 
> ![20220302_074904](https://user-images.githubusercontent.com/91834999/156273508-f654dbdb-0fd6-44d0-8149-42ed2345e5cc.jpg) case 'play2': if (!q) return reply(mess.wrongFormat) srch = `${q}` var url = await yts(srch) url = url.videos[0].url hxz.youtube(url).then(async(data) => { var butt = [{ buttonId: `/ytmp3 ${url}`, buttonText: { displayText: `🎵 Audio` }, type: 1 }, { buttonId: `/ytmp4 ${url}`, buttonText: { displayText: `🎥 Video` }, type: 1 }] textplay = `*Judul :* *${data.title}*\n*Size mp4 :* *${data.size}*\n*Size mp3 :* *${data.size_mp3}*` var teks = `${textplay}` }) hisoka.sendMessage(from, { caption: textplay, image: {url: `https://i.ibb.co/CPcFJ6c/IMG-20220131-WA0504.jpg`}, buttons: butt, footer: 'KID BOT-MD', mentions: [m.sender]} ) break

Ok, but how are you handling the responses?  (response = click in button)

**Comment by KunzxD404** [comment]
> > > Posting kode Anda bro, bagaimana cara membuatnya dan bagaimana "mendapatkan" respons dari tombol.
> > 
> > 
> > ![20220302_074904](https://user-images.githubusercontent.com/91834999/156273508-f654dbdb-0fd6-44d0-8149-42ed2345e5cc.jpg)case 'play2': if (!q) mengembalikan balasan(mess.wrongFormat) srch = `${q}`var url = menunggu yts(srch) url = url.videos[0].url hxz.youtube(url).then(async(data) => { var butt = [{ buttonId: `/ytmp3 ${url}`, buttonText: { displayText: `🎵 Audio`}, type: 1 }, { buttonId: `/ytmp4 ${url}`, buttonText: { displayText: `🎥 Video`}, type: 1 }] textplay = `*Judul :* *${data.title}*\n*Size mp4 :* *${data.size}*\n*Size mp3 :* *${data.size_mp3}*`var teks = `${textplay}`}) hisoka.sendMessage( from, { caption: textplay, image: {url: `https://i.ibb.co/CPcFJ6c/IMG-20220131-WA0504.jpg`}, keys: butt, footer: 'KID BOT-MD', mentions: [m.sender]} ) break
> 
> Ok, tapi bagaimana Anda menangani tanggapan? (respon = klik tombol)

Iam confused
