### ISSUE TITLE
[BUG] Link preview doesn't work

### ISSUE THREAD

**Issue by akashreddy03** [adiwajshing/Baileys#1304]
I tried sending a link as text but the link preview doesn't appear.
Even tried setting detectLinks to true but after searching the feature in the source I came to realize that there is no such thing as detectLinks. It is removed? If it's really removed then can someone tell me how to implement the code myself?

**Comment by bessajonathan** [comment]
same problem

**Comment by oliveirasilas** [comment]
Is there another way to send a message with preview link in multi-device?

**Comment by TOXIC-DEVIL** [comment]
> Is there another way to send a text message with preview link in multi-device?

**Yes.**

```js
sock.sendMessage(jid, { text: "Hey, Visit github here - https://github.com", detectLinks: true })
```

**Comment by azudindaem** [comment]
Not supported by Whatsapp right now

![unknown](https://user-images.githubusercontent.com/20223047/156928615-22b5583f-cf38-4305-b8e0-25f17dc7d9da.png)

**Comment by bessajonathan** [comment]
@azudindaem ,thank so much.
