### ISSUE TITLE
Whatsapp Beta/MD Can't unset anymore?

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1305]
I have a application with whatsapp connection using baileys 3.
For develop and test, i'm enter in Whatsapp Beta / MD, but now i can't undo this action.
I can revert to previous version?

Thanks

**Comment by PurpShell** [comment]
no

**Comment by zakinshk** [comment]
@drauber 
tem um grupo do baileys brazil
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL
