### ISSUE TITLE
[BUG] TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by kythepublic** [adiwajshing/Baileys#1308]
**Hello everyone. does anyone like me get an error like this? if there is please help**

![image](https://user-images.githubusercontent.com/59775277/156472702-dec9b406-c1c9-4eea-b851-9e55d1f73241.png)

**Error above from this line.**

![image](https://user-images.githubusercontent.com/59775277/156472888-af849381-b32e-40e5-a85c-4cebfb399fdb.png)

**Comment by diezeldev** [comment]
Hi I can not find that line in the project?

Have you added that line?

You do the same thing in try and catch. I think you do not understand what that means.

**Comment by zakirkun** [comment]
Can you explain the code?

**Comment by BochilGaming** [comment]
> **Hello everyone. does anyone like me get an error like this? if there is please help**
> 
> ![image](https://user-images.githubusercontent.com/59775277/156472702-dec9b406-c1c9-4eea-b851-9e55d1f73241.png)
> 
> **Error above from this line.**
> 
> ![image](https://user-images.githubusercontent.com/59775277/156472888-af849381-b32e-40e5-a85c-4cebfb399fdb.png)

m.message return undefined

**Comment by kythepublic** [comment]
> Hi I can not find that line in the project?
> 
> Have you added that line?
> 
> You do the same thing in try and catch. I think you do not understand what that means.

yes bro I'm still learning.
but this error does occur. I tried repeating it with try {} catch because I thought it would be solving.
and I don't repeat it the same thing happened.

the error occurred in the object type. but this only happened once, then back to normal, after normal the same error reappeared.
then what's wrong?

**Comment by kythepublic** [comment]
> Can you explain the code?

Yes, maybe.
then are you guys the same as me?
if not what went wrong?

**Comment by kythepublic** [comment]
> > **Hello everyone. does anyone like me get an error like this? if there is please help**
> > ![image](https://user-images.githubusercontent.com/59775277/156472702-dec9b406-c1c9-4eea-b851-9e55d1f73241.png)
> > **Error above from this line.**
> > ![image](https://user-images.githubusercontent.com/59775277/156472888-af849381-b32e-40e5-a85c-4cebfb399fdb.png)
> 
> m.message return undefined

Yes, maybe.
then are you guys the same as me?
if not what went wrong?

**Comment by BochilGaming** [comment]
> > > **Hello everyone. does anyone like me get an error like this? if there is please help**
> > > ![image](https://user-images.githubusercontent.com/59775277/156472702-dec9b406-c1c9-4eea-b851-9e55d1f73241.png)
> > > **Error above from this line.**
> > > ![image](https://user-images.githubusercontent.com/59775277/156472888-af849381-b32e-40e5-a85c-4cebfb399fdb.png)
> > 
> > 
> > m.message return undefined
> 
> Yes, maybe. then are you guys the same as me? if not what went wrong?

```js
let type = Object.keys(m.message || {})[0]
```
maybe that fixes the problem?
