### ISSUE TITLE
[BUG] [MD] Why do i have to spam the message before i get a bot message?

### ISSUE THREAD

**Issue by NadhiraAlifah** [adiwajshing/Baileys#1309]
![photo_2022-03-03_14-36-07](https://user-images.githubusercontent.com/80480704/156518089-8c085b8a-0690-452d-a766-24b0e6cd3691.jpg)

**Comment by BochilGaming** [comment]
your code?

**Comment by NadhiraAlifah** [comment]
> your code?
![carbon (4)](https://user-images.githubusercontent.com/80480704/156547541-3d019da0-c053-4f6e-9589-9cfd71750dac.png)

**Comment by BochilGaming** [comment]
What code for variable "body"

**Comment by NadhiraAlifah** [comment]
> What code for variable "body"?

  const body = (type === 'conversation') ? m.message.conversation : (type == 'imageMessage') ? m.message.imageMessage.caption : (type == 'videoMessage') ? m.message.videoMessage.caption : (type == 'extendedTextMessage') ? m.message.extendedTextMessage.text : (type == 'buttonsResponseMessage') ? m.message.buttonsResponseMessage.selectedButtonId : (type == 'listResponseMessage') ? m.message.listResponseMessage.singleSelectReply.selectedRowId : (type == 'templateButtonReplyMessage') ? m.message.templateButtonReplyMessage.selectedId : (type === 'messageContextInfo') ? (m.message.buttonsResponseMessage?.selectedButtonId || m.message.listResponseMessage?.title || m.text) : ''

**Comment by BochilGaming** [comment]
Maybe you can try this?
```js
let type = Object.keys(m.message)
type = (!['senderKeyDistributionMessage', 'messageContextInfo'].includes(type[0]) && type[0]) || (type.length >= 3 && type[1] !== 'messageContextInfo' && type[1]) || type[type.length - 1] 
```

**Comment by NadhiraAlifah** [comment]
> Maybe you can try this?
> 
> ```js
> let type = Object.keys(m.message)
> type = (!['senderKeyDistributionMessage', 'messageContextInfo'].includes(type[0]) && type[0]) || (type.length >= 3 && type[1] !== 'messageContextInfo' && type[1]) || type[type.length - 1] 
> ```

okeyy thanks

**Comment by NadhiraAlifah** [comment]
SOLVED

**Comment by BochilGaming** [comment]
@NadhiraAlifah please if labeling a bug make sure that this is really a bug from baileys not your code
