### ISSUE TITLE
MP3 audio messages are unplayable

### ISSUE THREAD

**Issue by talhabalaj** [adiwajshing/Baileys#131]
Hello!
Hope you are doing well. I have encountered an issue while using sending audio messages. I'm using the following code. Even tho, I'm passing the mime type as `audio/mpeg` but the resultant file is an `opus` file. I think that's causing the issue. Can you please look into it?

And also, it would be awesome if you can add `mp3` to your `MimeType` enumeration. 

```javascript
const buffer = fs.readFileSync("test2.mp3")
await client.sendMessage(personId, buffer, MessageType.audio, { mimetype: 'audio/mpeg' });
```
btw, I really appreciate your work or how often you are committing to it. Best of luck!

Thank you

**Comment by talhabalaj** [comment]
I tried both `npm` & `Github` versions of the module.

**Comment by adiwajshing** [comment]
Unfortunately @talhabalaj, WA doesn't accept the `audio/mpeg` mime type -- if you use `audio/mp4` or `audio/ogg` mime type, it'll work. Glad you like the library.

**Comment by talhabalaj** [comment]
Thank you so much, changing to `audio/mp4` worked flawlessly.
