### ISSUE TITLE
How to get name in person by jid?

### ISSUE THREAD

**Issue by razisek** [adiwajshing/Baileys#1310]
***How?***
how to get profile name from a jid ?

**Comment by TOXIC-DEVIL** [comment]
> _**How?**_ how to get profile name from a jid ?

`conn.getName(jid)`

**Comment by jccalbuquerque** [comment]
In version 4.0.1 MD ?

**Comment by pedroayres** [comment]
@razisek Did you find the solution? How? Could you share the code?
