### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by Kryknz** [adiwajshing/Baileys#1319]
**❣️Dear Devs**

I have A Feature Request For You Guys.
In telegram/discord there are many music bots.
I have coded my own bots for those too and now coded for whats app using your best ever lib.
So Is It Possible to plug user-bot in whats app group chat call and play music.
If that can be done then surely one hell of a module can be built and then its gonna be huge.
Just a plug-able Whats app Music User-Bot.
I know it can be done but i just need a way to 
**plug the user-bot in group chat with like:**
 _{client.prefix}joinvc_ command 
**play music using youtube/spotify/soundcloud/joisaavn like:**
 _{client.prefix}play NCS_

╔◇𝐅𝐎𝐑 𝐑𝐄𝐅𝐄𝐑𝐄𝐍𝐂𝐄
║🤖(𝐕𝐥𝐤𝐲𝐫𝐞) 𝐔𝐬𝐞𝐫-𝐁𝐨𝐭: [![Generic badge](https://img.shields.io/badge/🛰️Vlkyre-darkred.svg)](https://vlkyreai.krakinzkon.repl.co)
║🐍𝗪𝗶𝘁𝗵 𝗣𝘆𝘁𝗵𝗼𝗻: [![Generic badge](https://img.shields.io/badge/🕊️Norded-purple.svg)](https://github.com/Kryknz/Norded.git)
║🐞𝗪𝗶𝘁𝗵 𝗝𝗮𝘃𝗮𝗦𝗰𝗿𝗶𝗽𝘁: [![Generic badge](https://img.shields.io/badge/🍺YouTify-darkgreen.svg)](https://github.com/Kryknz/YouTify.git)
╚◇════════════◇꧂

**Comment by Kryknz** [comment]
🙏🏽‍ Hope Fully It Was A Bit Clear To Understand.
🙏🏽‍ Now Waiting For A Reply.

**Comment by rathmerdominik** [comment]
This is not possible at the moment.

They are already researching this, but expect it to take a while

https://discord.gg/qGsA4HYt

Check the progress on this discord under "calls"

**Comment by Kryknz** [comment]
> This is not possible at the moment.
> 
> They are already researching this, but expect it to take a while
> 
> https://discord.gg/qGsA4HYt
> 
> Check the progress on this discord under "calls"

Waiting For The implementation Soon!♥♥
And Will Check It Out Now Thanks For It.
