### ISSUE TITLE
[BUG] scan qr

### ISSUE THREAD

**Issue by medeldiegote** [adiwajshing/Baileys#1320]
Error  when scan qr : "(node:5956) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, 
TypedArray, DataView, or KeyObject. Received undefined "

**Comment by akashkothari98** [comment]
can you share your code?

**Comment by TOXIC-DEVIL** [comment]
> Error when scan qr : "(node:5956) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined "

If you are using multi device and scanning qr of non-multi device then it throws this error. Also please not **Don't use WhatsApp Business, Coz, in WA business, the multi

**Comment by manojsitapara** [comment]
I can think one reason is: may be you are using legacy V3 api and trying to scan qr using multi device whatsapp.
