### ISSUE TITLE
[BUG] Cant Send PDF in MD version

### ISSUE THREAD

**Issue by MatheusMani** [adiwajshing/Baileys#1321]
Hello. I would like help to send a remote pdf in the multi-device version.

I didn't find anything related about

Thanks

**Comment by TOXIC-DEVIL** [comment]
> Hello. I would like help to send a remote pdf in the multi-device version.
> 
> I didn't find anything related about
> 
> Thanks

```js
let jid = "91xxxxxxxxxx@s.whatsapp.net"
sock.sendMessage(jid, { document: pdf, fileName: "MatheusMani" })

**Comment by MatheusMani** [comment]
OK. Sory for Bug Template.
Do I need to declare something? So the code didn't work.
I have the latest bailey md

**Comment by TOXIC-DEVIL** [comment]
> OK. Sory for Bug Template. Do I need to declare something? So the code didn't work. I have the latest bailey md

You can change jid, pdf and filename according to you. And use it.

**Comment by MatheusMani** [comment]
![download](https://user-images.githubusercontent.com/100523578/156888605-bb3d4f23-141f-49ce-9d61-e9d157353097.png)

**Comment by mateuscdor** [comment]
@MatheusMani  me chama no WhatsApp tenho um grupo só com br do baileys
73 91776616

**Comment by FarhannnnX** [comment]
> ![unduh](https://user-images.githubusercontent.com/100523578/156888605-bb3d4f23-141f-49ce-9d61-e9d157353097.png)

you forgot the mimetype

**Comment by arthur-es** [comment]
For those who are trying, here is a working example:

![image](https://user-images.githubusercontent.com/37699234/156944279-15d919f7-92b2-4c9f-a3ca-fa0f5ad0c48b.png)

**Comment by tarikhagustia** [comment]
> For those who are trying, here is a working example:
> 
> ![image](https://user-images.githubusercontent.com/37699234/156944279-15d919f7-92b2-4c9f-a3ca-fa0f5ad0c48b.png)

thanks
