### ISSUE TITLE
Detect if it's a group

### ISSUE THREAD

**Issue by jccalbuquerque** [adiwajshing/Baileys#1324]
How do I check if the message I'm getting is from a group or not?
I saw that remoteJid is different for group.

How could I do this check correctly and securely in version 4.0.1 MD (WASocket)?

**Comment by Leon564** [comment]
try this

`const isGroup = m.key.remoteJid.split('@')[1] == 'g.us';`

**Comment by Leon564** [comment]
Seeing the Jid of the groups is different, I use this

`const isGroup = key.includes('g.us');`

**Comment by jccalbuquerque** [comment]
Thanks.
That's what I'm doing.
I thought there was a method for this and I couldn't find it.
