### ISSUE TITLE
Give us node js examples for multi device

### ISSUE THREAD

**Issue by DARKCRIME1** [adiwajshing/Baileys#1326]
**Give us node js examples for multi device**

**Comment by jackcokk** [comment]
https://github.com/adiwajshing/Baileys/blob/master/README.md

**Comment by DARKCRIME1** [comment]
No i need all in one for node js

**Comment by jackcokk** [comment]
Node.js is not a programming language. It is an environment to run JavaScript code.

**Comment by bitsoncloud** [comment]
https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts

**Comment by DARKCRIME1** [comment]
> 

i know i ask please give me muliti device whatsapp  main script i mean connected part in whatsapp in aasena base

**Comment by ghifar1** [comment]
Just learn javascript
