### ISSUE TITLE
bug - quote own messages

### ISSUE THREAD

**Issue by dinnos** [adiwajshing/Baileys#133]
When you quote your own message, it is sent as if the message belonged to the other person.

The quoted message "Test" it's my own message but appears with name of the contact and not the label "You".

![Screenshot_20200901_191146](https://user-images.githubusercontent.com/25092933/91918123-8e475100-ec87-11ea-8317-bf12e71b5526.jpg)

**Comment by adiwajshing** [comment]
Yeah, this is fixed in the latest commit

**Comment by dinnos** [comment]
Thanks @adiwajshing
