### ISSUE TITLE
[BUG] Image is sent bug Error: No image processing library available shows in console

### ISSUE THREAD

**Issue by arthur-es** [adiwajshing/Baileys#1330]
**Describe the bug**
When I am sending an image in the MD version this weird console error message appears

**To Reproduce**
1. Send a image as shown in printscreen

**Expected behavior**
The error message not to appear on console

**Additional context**

![image](https://user-images.githubusercontent.com/37699234/156944490-4e6107a2-40dc-4451-807b-1c798a836cb8.png)

**Comment by BochilGaming** [comment]
```
npm i sharp
```
or
```
npm i jimp
```

**Comment by zakinshk** [comment]
@arthur-es 
tem um grupo do baileys br
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**Comment by arthur-es** [comment]
> https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

boa tarde! tudo bem? pode me mandar o link atualizado?

**Comment by luisfernandaom** [comment]
> @arthur-es tem um grupo do baileys br https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL

**ainda tem o grupo? se tiver me manda.**
