### ISSUE TITLE
Show data in listmessage

### ISSUE THREAD

**Issue by Mastrios** [adiwajshing/Baileys#1334]
how to display data from database to listMessage and repeat it according to the number of data?

Help me, please

**Comment by prido1** [comment]
`typescript
 let cities = await AdvertCityModel.findAll();;
                //ask for advert city
                let cityList: Array<any> = [
                    {
                        title: "Select City",
                        rows: []
                    }
                ];
                cities.forEach((city: AdvertCityAttributes) => {
                    let row = {
                        title: city.name,
                        rowId: city.id,
                        // description: "your description"
                    }
                    cityList[0].rows.push(row);
                });
                //stage = 4
                userprocess.stage = 4;
                // send res
                let cityListText = 'Here is a list of cities, select a city and submit to continue';
                let cityListFooter = "";
                let cityListTitle = "Advert City";
                let cityListBtnText = "Select City";
                Messages.sendList(
                    this.client, this.jid, cityListTitle, cityList, cityListText, cityListFooter, cityListBtnText);
`
here is  Messages.sendList()

`typescript
 static async sendList(sock: any, id: any, title: any, list: any, text: any, footer: any, btnText: any) {
        // send a buttons message!
        const listMessage = {
            text: text,
            footer: footer,
            title: title,
            buttonText: btnText,
            sections: list
          }

        const sendMsg = await sock.sendMessage(id, listMessage);
        return sendMsg;
    }
`

**Comment by Mastrios** [comment]
Thank you

**Comment by FaizBastomi** [comment]
Don't forget to close this issue when it's resolved :)
