### ISSUE TITLE
ButtonText VS QuickReplyButton

### ISSUE THREAD

**Issue by elbiozard** [adiwajshing/Baileys#1335]
Good day!
I have a doubt, why does the BOT response behave differently in the bot's mobile, depending on the button style?
That is, when using "buttonText(button Message)" the bot's response reaches both mobiles correctly
But if I use "quickReplyButton(templateMessage)" the response on the BOT's mobile does not reach the correct chat but instead reaches the chat of the bot's own number.
I enclose a code image and a short video better illustrating the problem and doubts that I pose.

Thanks!

ButtonText (buttonMessage) VS QuickReplyButton (templateMessage)

![image](https://user-images.githubusercontent.com/44517389/157371208-c6a9432c-d416-49e0-8a5d-45dc22939acd.png)

menu1 = buttonText(buttonMessage)
menu2 = quickReplyButton(templateMessage)

CHAT (Javier) NOT is BOT. Is whatsapp web
CHAT (Number +549 xxxx-3020) is BOT

https://user-images.githubusercontent.com/44517389/157371028-d7e45d64-dcbe-4899-9d8a-f303a0c80565.mp4

**Comment by ferhacks** [comment]
viendo que hablas español, comentaré en español
templateMessage no ha sido pensado para ser usado en números de uso ordinario (ya que si, este tipo los usa whatsapp Bussines api), pero esto realmente afecta solo al bot y no a la persona destinataria, no hay un "arreglo" para eso ya que es algo de WhatsApp, no de baileys, sin embargo en grupos el templateMessage se quedará en el chat , pero te saldrá como si fuera que lo recibiste
