### ISSUE TITLE
tag: conflict error , msg :stream error

### ISSUE THREAD

**Issue by imReCoder** [adiwajshing/Baileys#1336]
Gettign this erro. anyone know the reason behind this ?
Any help will be appreciated 😊😊😊

{"level":50,"time":1646809863449,"pid":20376,"hostname":"Recoders-Pc","error":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"msg":"stream errored out"}
{"level":30,"time":1646809863449,"pid":20376,"hostname":"Recoders-Pc","error":{"data":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Stream Errored"},"headers":{}}},"msg":"connection closed"}

**Comment by ilyaborodin** [comment]
"type":"device_removed", I think u removed connection from wa app in phone

**Comment by imReCoder** [comment]
> 

No I havent

**Comment by pewh** [comment]
same issue since update to master

**Comment by imReCoder** [comment]
> same issue since update to master

Hey did you found any solution ? Please let me know because I am still facing issue

**Comment by carturus** [comment]
In my case,  I had the same behavior when I switch to Ubuntu server 20:

Reconnecting... { attempts: 1, sessionId: 'carturus' }
{"level":40,"time":1654563709184,"pid":30103,"hostname":"carturus","msg":"If your process stalls here, make sure to implement the reconnect logic as shown in https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#:~:text=reconnect"}
{"level":40,"time":1654563709833,"pid":30103,"hostname":"carturus","msg":"no name present, ignoring presence update request..."}
{"level":50,"time":1654563715470,"pid":30103,"hostname":"carturus","error":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"msg":"stream errored out"}
^CRunning cleanup before exit.

I just run with sudo and  I was able to get a stable connection.

**Comment by satriowicaksn** [comment]
Any solution for this issue guys ?
