### ISSUE TITLE
Writing Custom Functionality for Battery

### ISSUE THREAD

**Issue by jccalbuquerque** [adiwajshing/Baileys#1337]
I was monitoring the events for a long time to try to identify which record/event/frame brought information about the battery, but at no time does a record appear that brings this information.

I activated **DEBUG** as indicated in the **README**, there is a lot of information but none about battery.
I kept charging for some time, disconnected from charger and reconnected, but no event is fired.

Has anyone already achieved this?

`const sock = makeWASocket({
    logger: P({ level: 'debug' }),
})`

**Comment by rlucredio** [comment]
Hello @jccalbuquerque did you manage to solve this? I am facing this problem too.

**Comment by zakinshk** [comment]
@jccalbuquerque tem um grupo do whatsapp br
https://chat.whatsapp.com/Lce2fm3rCyS6K99NtDujAL
