### ISSUE TITLE
[MD] Multi session error scanning second qr

### ISSUE THREAD

**Issue by erickmunozr** [adiwajshing/Baileys#1339]
Hi. 

I am trying to connect two or more accounts at the same time in the same service. 

If the sessions are saved in the .json the login is successful, but if scan the qr at the same session shows the following error after scanning the second qr: 

`{"level":20,"time":1646853785986,"pid":34190,"hostname":"MacBook-Air-de-Erick.local","recv":{"from":"573016638798@s.whatsapp.net","type":"devices","id":"4026404660","t":"1646853785"},"sent":{"id":"4026404660","to":"573016638798@s.whatsapp.net","class":"notification","type":"devices"},"msg":"sent \"notification\" ack"}
{"level":50,"time":1646853787829,"pid":34190,"hostname":"MacBook-Air-de-Erick.local","error":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"msg":"stream errored out"}
{"level":30,"time":1646853787829,"pid":34190,"hostname":"MacBook-Air-de-Erick.local","error":{"data":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Stream Errored"},"headers":{}}},"msg":"connection closed"}
connection closed
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored
        at WebSocket.<anonymous> (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:437:13)
        at WebSocket.emit (events.js:315:20)
        at WebSocket.EventEmitter.emit (domain.js:467:12)
        at /Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:229:35
        at Object.decodeFrame (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:143:17)
        at WebSocket.onMessageRecieved (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:207:15)
        at WebSocket.emit (events.js:315:20)
        at WebSocket.EventEmitter.emit (domain.js:467:12)
        at Receiver.receiverOnMessage (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/ws/lib/websocket.js:1093:20)
        at Receiver.emit (events.js:315:20)
        at Receiver.EventEmitter.emit (domain.js:467:12)
        at Receiver.dataMessage (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/ws/lib/receiver.js:507:14)
        at Receiver.getData (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/ws/lib/receiver.js:440:17)
        at Receiver.startLoop (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/ws/lib/receiver.js:148:22)
        at Receiver._write (/Users/erickmunoz/nodejs/prueba_md/Baileys/node_modules/ws/lib/receiver.js:83:10)
        at writeOrBuffer (internal/streams/writable.js:358:12) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-03-09T19:23:07.830Z
  }
}
{"level":30,"time":1646853787831,"pid":34190,"hostname":"MacBook-Air-de-Erick.local","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
{"level":20,"time":1646853792578,"pid":34190,"hostname":"MacBook-Air-de-Erick.local","recv":{"from":"573016638798@s.whatsapp.net","type":"devices","id":"1660592378","t":"1646853792"},"sent":{"id":"1660592378","to":"573016638798@s.whatsapp.net","class":"notification","type":"devices"},"msg":"sent \"notification\" ack"}`

This is my code:

`var sock=[];

const startSock = async (instancia = null) => {
  if (instancia) {

    const { state, saveState } = useSingleFileAuthState('./auth' + instancia + '.json')

    sock[instancia] = makeWASocket({
      logger: P({ level: 'debug' }),
      printQRInTerminal: true,
      auth: state,
      version: [2, 2204, 13],
    });

    sock[instancia].ev.on('chats.set', item => console.log(`recv ${item.chats.length} chats (is latest: ${item.isLatest})`))
    sock[instancia].ev.on('messages.set', item => console.log(`recv ${item.messages.length} messages (is latest: ${item.isLatest})`))
    sock[instancia].ev.on('contacts.set', item => console.log(`recv ${item.contacts.length} contacts`))
    sock[instancia].ev.on('messages.update', m => console.log(m))
    sock[instancia].ev.on('message-receipt.update', m => console.log(m))
    sock[instancia].ev.on('presence.update', m => console.log(m))
    sock[instancia].ev.on('chats.update', m => console.log(m))
    sock[instancia].ev.on('contacts.upsert', m => console.log(m))

    // listen for when the auth credentials is updated
    sock[instancia].ev.on('creds.update', saveState)

    sock[instancia].ev.on('connection.update', function (update, connection2) {
      let _a, _b;
      let connection = update.connection, lastDisconnect = update.lastDisconnect;
      if (connection === 'close') {
        // reconnect if not logged out
        if (((_b = (_a = lastDisconnect.error) === null || _a === void 0 ? void 0 : _a.output) === null || _b === void 0 ? void 0 : _b.statusCode) !== DisconnectReason.loggedOut) {

          console.log("############# llega #############", instancia)
          startSock(instancia)

        }
        else {
          console.log('connection closed');
        }
      }
      console.log('connection update', update);
    });
  }
}`

**Comment by prido1** [comment]
hi did you find a solution to this? having the same issue

**Comment by erickmunozr** [comment]
> hi did you find a solution to this? having the same issue

No

**Comment by Ajay-o-s** [comment]
same issue too

**Comment by 1stmud** [comment]
![image](https://user-images.githubusercontent.com/8487464/158156006-9964fe4e-35a4-4f2f-ab4b-cf07e70ccc3b.png)

why ?

**Comment by 1stmud** [comment]
@erickmunozr  could you help me ?
