### ISSUE TITLE
Connection disconnected after hours

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#134]
This is not a bug i think, but i'm reporting to add information.

I have a connection running 24/7, and after some hours, not certain how much, but more than 8, prob 12. It just close the connection.

I have setup a timeout to run every 4 hours to recreate the connection, and that would solve for me, but leting you know about it.

Thanks

**Comment by adiwajshing** [comment]
You're right WhatsApp closes the connection every few hours. However, `autoReconnect` will solve the problem for you -- no need for a timeout. Have you disabled autoReconnect?

**Comment by algoz098** [comment]
No, i haven't

**Comment by adiwajshing** [comment]
Okay, and does it stay disconnected for you on a connection close?

**Comment by algoz098** [comment]
Well, it usually disconnect late in the nite, and i only reconnect on morning so, i would say yes?

**Comment by adiwajshing** [comment]
I see, can you switch to Baileys 3.0.0 and see if it auto reconnects on its own?

**Comment by algoz098** [comment]
I'm using the github version almost the last commit

**Comment by adiwajshing** [comment]
Seems like something is up with your setup if Baileys is not auto-reconnecting. You mind sharing some of the code here?

**Comment by galiazzi** [comment]
I have this problem too. With auto-reconnect enable.

I maked a test, disabling the auto-reconnect and calling the connect method when a diconnect occures by "close" reason.

![image](https://user-images.githubusercontent.com/816316/92264697-05156180-eeb5-11ea-9f8d-a9289525011c.png)

On reconnect, the login validation its ok, but no messsages are sent and no events are received

I am using this version 
https://github.com/adiwajshing/Baileys/commit/50d50e4ae91ab1b85cbd987eb93028c80df8133a

**Comment by algoz098** [comment]
It seems to be the same here. I was testing other things and stumble in it, i had to realize a disconnect with the setTimeout and now it's working

**Comment by adiwajshing** [comment]
@algoz098 @galiazzi Can ya'll try the latest npm version -- v3.0.0? I have a system running that 24/7 and that works perfectly with `autoReconnect = ReconnectMode.onConnectionLost`

**Comment by galiazzi** [comment]
Ok, I make a test with latest version. 

This weekend, with less use of the api, the problem did not occur

**Comment by algoz098** [comment]
Here as some logs of what is happening to version 3.0.1
```BaileysError: timed out
    at Object.exports.TimedOutError (/WAConnection/Constants.js:27:31)
    at /WAConnection/Utils.js:137:44 {
  status: 408,
  context: { status: 408 }
}````
Will add more information as finding it

**Comment by SimiPrambos** [comment]
Same issue

> Here as some logs of what is happening to version 3.0.1
> 
> ```
>     at Object.exports.TimedOutError (/WAConnection/Constants.js:27:31)
>     at /WAConnection/Utils.js:137:44 {
>   status: 408,
>   context: { status: 408 }
> }````
> Will add more information as finding it
> ```

**Comment by adiwajshing** [comment]
I believe if you change `conn.connectOptions.maxRetries = Infinity` -- these timeout issues will be resolved

**Comment by felangga** [comment]
Sorry for replying this closed issue
But I still have this issue on v3.4.1
