### ISSUE TITLE
. 

### ISSUE THREAD

**Issue by NuevaGeneracionALB** [adiwajshing/Baileys#1341]

**Comment by 4l3dx** [comment]
Maybe is related to #1309

**Comment by viniciusgdr** [comment]
Could you make your question clearer? Impossible to understand. Maybe Latin is your language

**Comment by Dakauann** [comment]
> You are only able to read as a command, the second command, for example: if a member sends a message to the group the first time, is registered in auth_info_multi.json, and is only read as a command, in the second command, and with the function of detecting link, this makes it difficult, by detecting only the second link.

I think what you're trying to explain is referring to the message object containing a senderKeyDistributionMessage. Just select the correct object and the problem is solved. In the next time please write your question clearer.
