### ISSUE TITLE
Error when using this library with Javascript [BUG]

### ISSUE THREAD

**Issue by zennn08** [adiwajshing/Baileys#1342]
**Describe the bug**
So I use this library with javascript. For that of course I have compiled this library using the `tsc` command.

But when I want to run my script, the error appears as below

![image](https://user-images.githubusercontent.com/75623219/157613902-bc7caf03-e6b9-426e-8fc3-d5ad3ffbd480.png)

I looked for where the error was, and I found it.

The `src/Defaults/baileys-version.json` file is not moved when compiling, it will throw an error if you use javascript

In src folder:
![image](https://user-images.githubusercontent.com/75623219/157614533-3239cd69-70f5-4def-a4d6-fc1ada9735b9.png)

In lib folder:
![image](https://user-images.githubusercontent.com/75623219/157614741-d69cea55-3a59-472a-bd20-96b536e05748.png)

So to solve this error, I moved the `src/Defaults/baileys-version.json` file manually to the `lib/Defaults` folder and it worked.

I wish @adiwajshing did something, so I wouldn't do it manually :|

**Comment by FaizBastomi** [comment]
related to #1276 
[comment](https://github.com/adiwajshing/Baileys/issues/1276#issuecomment-1048865878)

**Comment by FaizBastomi** [comment]
related to #1276 
---

Suggestion, use baileys v4.0.1 from npm/yarn registry
How?
```bash
npm install @adiwajshing/baileys@^4.0.1
# or
yarn add @adiwajshing/baileys@^4.0.1
```
