### ISSUE TITLE
Closed Connection, Error : Intentional

### ISSUE THREAD

**Issue by royhan97** [adiwajshing/Baileys#1343]
Hi,

I starting to create new session via Postman, but I got Error like this

Server is listening on http://127.0.0.1:8000
INFO [2022-02-25 15:16:51.615 +0000] (13268): closed connection, reason intentional class: "Baileys"
WARN [2022-02-25 15:16:51.630 +0000] (13268): connect attempt 1 failed: Error: intentional class: "Baileys" error: {}
An error occured during connecting: Error: intentional

Any solution?

Fyi, I use proxy or vpn. Perhaps any setting to handle this proxy connection?

Thank you.

**Comment by royhan97** [comment]
or maybe where (endpoint / ip address) can I open a connection to connect to your whatsapp API?

Pls help. Thanks

**Comment by diezeldev** [comment]
Hi no one will give you his server for free. They cost money to run. 

Try without a proxy first.

**Comment by royhan97** [comment]
OK, I just need an the server IP or hostname in class "Baileys", not the cridentials to connect or something like that.

thanks

**Comment by diezeldev** [comment]
I do not understand what you mean - you want the IP of a proxy?

**Comment by royhan97** [comment]
Oh i'm so sorry. 

I mean, just need the ip/ endpoint to connect the `class: "Baileys"` since I use VPN proxy, so I can whitelist that ip/endpoint `class: "Baileys"` in my VPN/ Proxy used

**Comment by diezeldev** [comment]
Hi, you have to whitelist:

web.whatsapp.com (for the websocket), keep in mind the wss protocol

github.com (Baileys always tries to fetch the version number via github pages)
