### ISSUE TITLE
How to save Auth info to file .json

### ISSUE THREAD

**Issue by CarlosEdd** [adiwajshing/Baileys#1347]
As the title says, i want to save the Auth info to a json file. 
I already tried the example code and nothing. Are there some easy way to save it? like on past versions.

**Comment by BochilGaming** [comment]
https://github.com/adiwajshing/Baileys#saving--restoring-sessions

**Comment by salman0ansari** [comment]
```javascript
let {
    state,
    saveState
} = useSingleFileAuthState("./auth.json")
let sock = makeWASocket({
    auth: state,
    logger: pino({
        level: 'debug',
    }),
    printQRInTerminal: true,
})
```
