### ISSUE TITLE
Name contact not allways displayed

### ISSUE THREAD

**Issue by iamjcharly** [adiwajshing/Baileys#135]
Hi! I'm getting the name but not allways works sometimes is displayed and others not, I'm doing something wrong in my code?
I´m executting this code before replying 

sender = m.key.remoteJid
let contactName = ' '            
      if (conn.chats.get(sender).name) {                
        contactName =' *'+conn.chats.get(sender).name+'* '            
      } else {
        contactName = ' '
      }

**Comment by adiwajshing** [comment]
Can you please update to `v3.0.0` if you haven't updated? Also, are you sure that the contacts whose name you are trying to retrieve have some name set?

**Comment by iamjcharly** [comment]
Yes I'm using the version 3.0.0 also I made some tests with the contacts and sometimes the name's were displayed and others not, but i will check in the last version and I going to do other tests
