### ISSUE TITLE
[BUG] Messages aren't sent to groups (statistically) 

### ISSUE THREAD

**Issue by lukacat10** [adiwajshing/Baileys#1350]
**Describe the bug**
Sometimes the bot sends messages successfully to groups, but the messages don't actually show in the group (others don't see the message). Querying the stanza also seems OK for some reason (from the bot's point of view at least). 

**To Reproduce**
Statistical bug. 

**Expected behavior**
The message is supposed to be sent and shown to everyone. 

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? Default from example. 
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
Usually fixed by removing the group and creating a new one, or resetting the connection (scanning the qr again)

**Comment by diezeldev** [comment]
Hi what does “statistically” mean?

**Comment by lukacat10** [comment]
> Hi what does “statistically” mean?

It happens after a while that the program runs, but no error/any other indication that I could have seen to help investigate the cause.

So I called it "statistically", because it feels random and not related to anything but luck/chance/internal whatsapp bugs.

Thanks

**Comment by tiesco238** [comment]
I have a problem something that might be related. It seems that the format of the jid for group chats has changed. With non-MD, the group jid was something like: 3212345678-1816321673. The new format is like this: +120361021053134389

If I send a message to a group with the old id (the former), it will not sent and the request will be canceled (timeout).

Does somebody knows how to convert a group jid from the non-MD to the MD format?

Thank you,
Matt

**Comment by ahmadkeren** [comment]
Same issue, any solution?

**Comment by tarikhagustia** [comment]
same issue
