### ISSUE TITLE
fetch unread messages

### ISSUE THREAD

**Issue by tiesco238** [adiwajshing/Baileys#1351]
Hi All,

Library is working great!
I just cannot figure out how to get all the unread messages through the WA socket.

Does somebody how to get these messages?
Thanks,
Matt

**Comment by salman0ansari** [comment]
`socket.ev.on("messages.upsert", () => {}`

**Comment by tiesco238** [comment]
thanks @salman0ansari will have a look!

**Comment by diezeldev** [comment]
Hi that will not help you. You have to track the message status yourself. The upsert event will only push ALL messages not just the unread ones.

**Comment by salman0ansari** [comment]
> Okay, but I how can I differentiate read messages from unread messages? The message objects doesn't seem to have status property.
> 
> `{ "key":{ "remoteJid":"xxxxx@c.us", "fromMe":false, "id":"BFE5189AC61DDA99" }, "message":{ "conversation":"Test message" }, "messageTimestamp":"1647511854", "participant":"xxxxxxxxxxxxxxxx@s.whatsapp.net", "ephemeralOutOfSync":false }`

You can map over object you get from `upsert` event see example here
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/53e92af3714ab51ac250b49aa5b41cefbef7a690/src/api/class/instance.js#L162
