### ISSUE TITLE
[BUG] MD sendReadReceipt not triggering chats.update

### ISSUE THREAD

**Issue by pewh** [adiwajshing/Baileys#1357]
**Describe the bug**
When I trigger sendReadReceipt, the WA mark the message as read but no `chats.update` event received.
But when I read message from WA phone/official web, it mark message as read and trigger `chats.update`

**Impact**
The unreadCount is not sync between baileys and phone.

**To Reproduce**
1. tested on master branch
2. ```socket.sendReadReceipt(value.targetId, undefined, [messageIdToBeRead])```
3. message mark as read on WA web & phone
4. no `chats.update` trigger, so chats.unreadCount still 1

**Expected behavior**
sendReadReceipt should trigger `chats.update` if message successfully mark as read.

**Environment (please complete the following information):**
 - Is this on a server? localhost & server
 - What do your `connectOptions` look like? default
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Comment by burstfreeze** [comment]
You have to take care the these states yourself. `chats.update` probably only applies to actions caused by other devices.

**Comment by pewh** [comment]
Ahh it's make sense now, thank you @burstfreeze
