### ISSUE TITLE
[BUG] Cannot receive push notifications on new received message

### ISSUE THREAD

**Issue by textarea** [adiwajshing/Baileys#1359]
Upgrading from Baileys v.3.x to v.4.x I don't receive anymore push notifications on my phone, iPhone but also Android.
If I'm connected also on WhatsApp Desktop I can receive desktop notification, but never on the phone.

**Comment by mariobarril** [comment]
Same here.

**Comment by mtAlves** [comment]
Same here...

**Comment by hernanpatronc** [comment]
Same here @adiwajshing can you please re open?

**Comment by iM0hamed** [comment]
same issue here

**Comment by textarea** [comment]
On WhatsApp Business they work

**Comment by iM0hamed** [comment]
> On WhatsApp Business they work

For me both not working

**Comment by bplacedigital** [comment]
hi, did you fix this problem?

**Comment by TisTatig** [comment]
@bplacedigital @netrixken @iM0hamed @hernanpatronc @mariobarril @mtAlves 

The answer is adding: `sock.sendPresenceUpdate('unavailable');` 
where *sock* refers to the constant declared through `const sock = makeWASocket({....`

I've added that line to the `if (connection === open) {... ` to make sure the presence becomes "unavailable" whenever the connection is open(ed).
