### ISSUE TITLE
🚨 Meta will change verification in qrcode (Problem coming up)

### ISSUE THREAD

**Issue by zakinshk** [adiwajshing/Baileys#1365]
https://engineering.fb.com/2022/03/10/security/code-verify/

@adiwajshing 
### A problem is coming for us users..
whatsapp will change qrcode authentication

**Comment by diezeldev** [comment]
Hi, calm down. Read the article first before posting, adding alarm emojis and tagging the maintainer. 

There is absolutely no indication of Code Verify to have implications on the QR code in any possible way.

**Comment by diezeldev** [comment]
Read the article. This does not affect Baileys in any way.

We could also post alerts about 0.03% chances of meteoroids hitting our planet but this is not relevant to Baileys at all. 


I understand your concerns but it really is not the news that you think it is. Please read the article.

**Comment by SheIITear** [comment]
It literally says:

> *You can now use Code Verify, an open source web browser extension that automatically verifies the authenticity of the WhatsApp Web code being served to your browser. Code Verify confirms that your WhatsApp Web code hasn’t been tampered with or altered.*

This won't have any affect on whatsapp itself.

**Comment by diezeldev** [comment]
Thank you for closing the issue. 

I really appreciate you contributing but for now this really is not relevant to Baileys.
