### ISSUE TITLE
can give me example for javascript ?! :>

### ISSUE THREAD

**Issue by Barqah-Xiex** [adiwajshing/Baileys#1366]
can give me example for javascript ?! :>

**Comment by sreza78** [comment]
[Examples](https://github.com/adiwajshing/Baileys/tree/master/Example)

Typescript is not much different from Javascript

I use this codes in my own project with js

**Comment by nian88** [comment]
check
#1196

**Comment by rezadaulay** [comment]
Please check this https://github.com/rezadaulay/javascript-example-of-whatsapp-baileys
