### ISSUE TITLE
How to get last seen?

### ISSUE THREAD

**Issue by MazenAbdullah** [adiwajshing/Baileys#137]
How to get last seen for WhatsApp ID?

**Comment by adiwajshing** [comment]
``` ts

await conn.requestPresenceUpdate ('1234@s.whatsapp.net')

conn.on ('user-presence', update => {
  // will only be set if user has last seen enabled
  console.log ('user last seen is ' + update.t)
})

```

**Comment by MazenAbdullah** [comment]
example.ts:111:16 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"user-presence"' is not assignable to parameter of type '"received-pong"'.

111     client.on ('user-presence', update => {
                   ~~~~~~~~~~~~~~~

  src/WAConnection/4.Events.ts:331:5
    331     on (event: 'received-pong', listener: () => void): this
            ~~
    The last overload is declared here.


Found 1 error.

**Comment by adiwajshing** [comment]
Apologies, the event is `user-presence-update` and not `user-presence`

**Comment by vjyanand** [comment]
> Apologies, the event is `user-presence-update` and not `user-presence`

I see `user-presence-update` deprecated, alternative?

**Comment by ekucet** [comment]
> > Apologies, the event is `user-presence-update` and not `user-presence`
> 
> I see `user-presence-update` deprecated, alternative?

Yes, can you find any solution? I tried 'chat-update' but this method only if you have a chat with that contact.

**Comment by vjyanand** [comment]
> Yes, did you find any solution?

So far no.

**Comment by ekucet** [comment]
> > Yes, did you find any solution?
> 
> So far no.

this is not good. I opened new issue. I hope any solution will be found.

@adiwajshing :)
