### ISSUE TITLE
[MD] Multiple instances same whatsapp account

### ISSUE THREAD

**Issue by hernanpatronc** [adiwajshing/Baileys#1370]
Hi everyone

Is it possible to connect the same whatsapp account to two different instances of Baileys? And if so, how should the process be?
The use case is having two environments (development and production) and wanting to use the same whatsapp number for each of these environments. I've tried just connecting (eg scanning the qr code) with the same account but it throws an error that no more devices can be linked to the account. I'm using multidevice btw

Thanks in advance

**Comment by HUGEIT** [comment]
you can have 4 linked devices. 3 computers and 1 baileys or 0 computers and 4 baileys does not matter

**Comment by hernanpatronc** [comment]
> you can have 4 linked devices. 3 computers and 1 baileys or 0 computers and 4 baileys does not matter

I, however, cannot have more than one baileys connected for same whatsapp account, do you happen to know why?
