### ISSUE TITLE
New Whatsapp Update

### ISSUE THREAD

**Issue by sreza78** [adiwajshing/Baileys#1371]
**I think beta and legacy merged**
![image](https://user-images.githubusercontent.com/72757502/158680940-f76ef614-764b-45aa-89c0-971798cc2e2c.png)

It will be any changed to this package!?

**Comment by devil-slayer141** [comment]
Well having same issue.. can't scan QR

**Comment by Gimenz** [comment]
yep, i facing same issue

**Comment by FaizBastomi** [comment]
Multi Device has been supported since baileys v4, if you want to move to the latest version of baileys don't forget to read the README, there is a complete way to migrate from baileys v3 to baileys v4

**Comment by krasymyr** [comment]
using a fresh number, reading a qr code from a real device(w/o root), with a true mobile ip, results with an immediate ban with 503 code. regular browser web qr code reading works fine. something seems off.

`{"level":10,"time":1647558465088,"pid":86232,"hostname":"MacBook-Pro.local","fromMe":false,"frame":{"tag":"stream:error","attrs":{"code":"503"},"content":null},"msg":"communication"}

{"level":50,"time":1647558465088,"pid":86232,"hostname":"MacBook-Pro.local","error":{"tag":"stream:error","attrs":{"code":"503"},"content":null},"msg":"stream errored out"}

{"level":30,"time":1647558465088,"pid":86232,"hostname":"MacBook-Pro.local","error":{"data":{"tag":"stream:error","attrs":{"code":"503"},"content":null},"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"Stream Errored"},"headers":{}}},"msg":"connection closed"}`

**Comment by jazz7381** [comment]
any update? i can scan qrcode

**Comment by sreza78** [comment]
i think something will be happened
according to this message from whatsapp
![image](https://user-images.githubusercontent.com/72757502/160270603-d33163fd-b682-490d-8b39-98aefcdaaddd.png)

**Comment by asrofindo** [comment]
is now solved? is v4 able to handle multi device? anyone?

**Comment by xxxmike3** [comment]
hi, how a update to v4?
