### ISSUE TITLE
npmjs Update date?

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1381]
Is there a plan date to publish last commits tos npmjs official repo?

Thanks

**Comment by AkirahX** [comment]
This usually happens every 3 months.

**Comment by mrjoebudi** [comment]
1696 error code 128
1697 error An unknown git error occurred
1698 error command git --no-replace-objects ls-remote ssh://git@github.com/adiwajshing/libsignal-node.git
1699 error git@github.com: Permission denied (publickey).
1699 error fatal: Could not read from remote repository.
1699 error
1699 error Please make sure you have the correct access rights
1699 error and the repository exists.
1700 verbose exit 128

**Comment by MacKey-255** [comment]
Use: `yarn add git+https://github.com/adiwajshing/Baileys.git` or `npm install git+https://github.com/adiwajshing/Baileys.git`. SAlu2s
