### ISSUE TITLE
bans

### ISSUE THREAD

**Issue by prido1** [adiwajshing/Baileys#1383]
Do u think using message templates ( lists, buttons ) increase the chance of getting banned?

**Comment by AkirahX** [comment]
No, based on what I've seen in the community I say that the buttons do not influence the ban, the possibilities remain the same using or not.

**Comment by prido1** [comment]
> No, based on what I've seen in the community I say that the buttons do not influence the ban, the possibilities remain the same using or not.

Ok thanks, i am creating a marketing tool. almost done and i fear it might not work because i have to send like maybe 3 000 messages daily in groups. this number can however be shared across multiple bailey instances and same node app. Any recommendations? or its totally not gonna work lol :)

**Comment by AkirahX** [comment]
> > No, based on what I've seen in the community I say that the buttons do not influence the ban, the possibilities remain the same using or not.
> 
> Ok thanks, i am creating a marketing tool. almost done and i fear it might not work because i have to send like maybe 3 000 messages daily in groups. this number can however be shared across multiple bailey instances and same node app. Any recommendations? or its totally not gonna work lol :)

Try not to send them all at once, use a delay between each message.
