### ISSUE TITLE
How to reply a message wit message id?

### ISSUE THREAD

**Issue by muzafferkadir** [adiwajshing/Baileys#1391]
i want to reply message but i dont have message object. I have only message id and receiver number. How can i send reply message?

**Comment by muzafferkadir** [comment]
> > i want to reply message but i dont have message object. I have only message id and receiver number. How can i send reply message?
> 
> It is not possible, just these 2 pieces of information are not enough.

how i can reach message object? for other informations

**Comment by MacKey-255** [comment]
@muzafferkadir, It is possible, only need save the messages before reply in the store. You can use it code:
```
start() {
    const session_file = this.SESSIONS_DIR + '/' + this.bot_name + '.json',
          store_file = path.join(this.SESSIONS_DIR, this.bot_name + '.data.json');
    const { state, saveState } = useSingleFileAuthState(session_file);
    const { version, isLatest } = await fetchLatestBaileysVersion();

    // Load Store
    this.store = makeInMemoryStore({});
    this.store.readFromFile(store_file);
    // Save Store every 5s
    setInterval(() => this.store.writeToFile(store_file), 5000);

    // Create Client
    this.client = await makeWASocket({
        version,
        printQRInTerminal: false,
        auth: state,
    });

    // All my events ('connection.update', 'messages.upsert', etc ...)
    // ...

    // event for when the auth credentials is updated
    this.client.ev.on('creds.update', saveState);


    // Bind all events with Store
    this.store.bind(this.client.ev);
}

async _forward_ad(msg, remoteJid) {
    if (!validator.isNull(msg)) {
        await this.client.sendMessage(remoteJid, {forward: msg});
    }
}

async _get_message(id, remoteJid) {
    // Get message from store if it exists
    try {
        return await this.store.loadMessage(remoteJid, id, this.client);
    } catch (_) {}
    // If message not found return null
    return null;
}
```
For use forwarding:
```
const message = await this._get_message("XXXXXXXXXXXXXXXXXXXXXXXXXXXX", "XXXXXXXXXXX@s.whatsapp.net");
await this._forward_ad(message, "YYYYYYYYYYYY@s.whatsapp.net");
```
SAlu2s

**Comment by muzafferkadir** [comment]
> @muzafferkadir, It is possible, only need save the messages before reply in the store. You can use it code:
> 
> ```
> start() {
>     const session_file = path.join(this.SESSIONS_DIR, this.bot_name + '.json'),
>           store_file = path.join(this.SESSIONS_DIR, this.bot_name + '.data.json');
>     const { state, saveState } = useSingleFileAuthState(session_file);
>     const { version, isLatest } = await fetchLatestBaileysVersion();
> 
>     // Load Store
>     this.store = makeInMemoryStore({});
>     this.store.readFromFile(store_file);
>     // Save Store every 5s
>     setInterval(() => this.store.writeToFile(store_file), 5000);
> 
>     // Create Client
>     this.client = await makeWASocket({
>         version,
>         printQRInTerminal: false,
>         auth: state,
>     });
> 
>     // All my events ('connection.update', 'messages.upsert', etc ...)
>     // ...
> 
>     // event for when the auth credentials is updated
>     this.client.ev.on('creds.update', saveState);
> 
> 
>     // Bind all events with Store
>     this.store.bind(this.client.ev);
> }
> 
> async _forward_ad(msg, remoteJid) {
>     if (!validator.isNull(msg)) {
>         await this.client.sendMessage(remoteJid, {forward: msg});
>     }
> }
> 
> async _reply_ad(msg, remoteJid, content) {
>     if (!validator.isNull(msg)) {
>         await this.client.sendMessage(remoteJid, content, {quoted: msg});
>     }
> }
> 
> async _get_message(id, remoteJid) {
>     // Get message from store if it exists
>     try {
>         return await this.store.loadMessage(remoteJid, id, this.client);
>     } catch (_) {}
>     // If message not found return null
>     return null;
> }
> ```
> 
> For use reply message:
> 
> ```
> const message = await this._reply_ad("XXXXXXXXXXXXXXXXXXXXXXXXXXXX", "XXXXXXXXXXX@s.whatsapp.net", {text: 'my message'});
> await this._reply_ad(message, "YYYYYYYYYYYY@s.whatsapp.net");
> ```
> 
> For use forwarding message:
> 
> ```
> const message = await this._get_message("XXXXXXXXXXXXXXXXXXXXXXXXXXXX", "XXXXXXXXXXX@s.whatsapp.net");
> await this._forward_ad(message, "YYYYYYYYYYYY@s.whatsapp.net");
> ```
> 
> SAlu2s

can i reply old message? How i can get older message?
