### ISSUE TITLE
How to use relayMessage

### ISSUE THREAD

**Issue by QueenLaurie** [adiwajshing/Baileys#1396]
Hi,anyone know how to use relayMessage for sending Reaction?

**Comment by Kikii-XyZ** [comment]
you can use this
```
let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
		if (quoted == null) return 
		console.log(quoted)
        const reactionMessage = {
            react: {
                text: '😮',
                key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant},
				remoteJid: to,
				fromMe: true
            }
        }
        const sent = await sock.sendMessage(to, reactionMessage)
		return sent
```

**Comment by QueenLaurie** [comment]
> you can use this
> 
> ```
> let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> 		if (quoted == null) return 
> 		console.log(quoted)
>         const reactionMessage = {
>             react: {
>                 text: '😮',
>                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
>             }
>         }
>         const sent = await sock.sendMessage(to, reactionMessage)
> 		return sent
> ```

Ah thanks i will try this

**Comment by QueenLaurie** [comment]
> you can use this
> 
> ```
> let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> 		if (quoted == null) return 
> 		console.log(quoted)
>         const reactionMessage = {
>             react: {
>                 text: '😮',
>                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
>             }
>         }
>         const sent = await sock.sendMessage(to, reactionMessage)
> 		return sent
> ```

Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"

**Comment by Kikii-XyZ** [comment]
> > you can use this
> > ```
> > let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> > 		if (quoted == null) return 
> > 		console.log(quoted)
> >         const reactionMessage = {
> >             react: {
> >                 text: '😮',
> >                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
> >             }
> >         }
> >         const sent = await sock.sendMessage(to, reactionMessage)
> > 		return sent
> > ```
> 
> Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"

can you show me your code?

**Comment by QueenLaurie** [comment]
> > > you can use this
> > > ```
> > > let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> > > 		if (quoted == null) return 
> > > 		console.log(quoted)
> > >         const reactionMessage = {
> > >             react: {
> > >                 text: '😮',
> > >                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
> > >             }
> > >         }
> > >         const sent = await sock.sendMessage(to, reactionMessage)
> > > 		return sent
> > > ```
> > 
> > 
> > Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"
> 
> can you show me your code?

ah it's ok i solved this using relayMessage
here my code

const QuotedMsg = isQuotedMsg ? msg.message.extendedTextMessage.contextInfo : msg;
          const objQuoted = {
            key: {
              remoteJid: from ? from : "",
              id: QuotedMsg.stanzaId ? QuotedMsg.stanzaId : "",
              participant: QuotedMsg.participant ? QuotedMsg.participant : "",
            },
            message: QuotedMsg.quotedMessage ? QuotedMsg.quotedMessage : "",
          };
          const reactionMessage = {
            text: send_emoji,
            key: objQuoted.key,
          };
          const Reactions = generateWAMessageFromContent(
            from,
            proto.Message.fromObject({ reactionMessage: reactionMessage }),
            {}
          );
          await Azusa.relayMessage(from, Reactions .message, { messageId: Reactions .key.id });

**Comment by Kikii-XyZ** [comment]
> > > > you can use this
> > > > ```
> > > > let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> > > > 		if (quoted == null) return 
> > > > 		console.log(quoted)
> > > >         const reactionMessage = {
> > > >             react: {
> > > >                 text: '😮',
> > > >                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
> > > >             }
> > > >         }
> > > >         const sent = await sock.sendMessage(to, reactionMessage)
> > > > 		return sent
> > > > ```
> > > 
> > > 
> > > Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"
> > 
> > 
> > can you show me your code?
> 
> ah it's ok i solved this using relayMessage here my code
> 
> `const QuotedMsg = isQuotedMsg ? msg.message.extendedTextMessage.contextInfo : msg; const objQuoted = { key: { remoteJid: from ? from : "", id: QuotedMsg.stanzaId ? QuotedMsg.stanzaId : "", participant: QuotedMsg.participant ? QuotedMsg.participant : "", }, message: QuotedMsg.quotedMessage ? QuotedMsg.quotedMessage : "", }; const reactionMessage = { text: send_emoji, key: objQuoted.key, }; const Reactions = generateWAMessageFromContent(from, proto.Message.fromObject({ reactionMessage: reactionMessage }), {}); await Azusa.relayMessage(from, Reactions.message, { messageId: Reactions.key.id }); `

great

**Comment by QueenLaurie** [comment]
> > > > > you can use this
> > > > > ```
> > > > > let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> > > > > 		if (quoted == null) return 
> > > > > 		console.log(quoted)
> > > > >         const reactionMessage = {
> > > > >             react: {
> > > > >                 text: '😮',
> > > > >                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
> > > > >             }
> > > > >         }
> > > > >         const sent = await sock.sendMessage(to, reactionMessage)
> > > > > 		return sent
> > > > > ```
> > > > 
> > > > 
> > > > Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"
> > > 
> > > 
> > > can you show me your code?
> > 
> > 
> > ah it's ok i solved this using relayMessage here my code
> > `const QuotedMsg = isQuotedMsg ? msg.message.extendedTextMessage.contextInfo : msg; const objQuoted = { key: { remoteJid: from ? from : "", id: QuotedMsg.stanzaId ? QuotedMsg.stanzaId : "", participant: QuotedMsg.participant ? QuotedMsg.participant : "", }, message: QuotedMsg.quotedMessage ? QuotedMsg.quotedMessage : "", }; const reactionMessage = { text: send_emoji, key: objQuoted.key, }; const Reactions = generateWAMessageFromContent(from, proto.Message.fromObject({ reactionMessage: reactionMessage }), {}); await Azusa.relayMessage(from, Reactions.message, { messageId: Reactions.key.id }); `
> 
> great

thanks for your advice

**Comment by Kikii-XyZ** [comment]
> > > > > > you can use this
> > > > > > ```
> > > > > > let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> > > > > > 		if (quoted == null) return 
> > > > > > 		console.log(quoted)
> > > > > >         const reactionMessage = {
> > > > > >             react: {
> > > > > >                 text: '😮',
> > > > > >                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
> > > > > >             }
> > > > > >         }
> > > > > >         const sent = await sock.sendMessage(to, reactionMessage)
> > > > > > 		return sent
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"
> > > > 
> > > > 
> > > > can you show me your code?
> > > 
> > > 
> > > ah it's ok i solved this using relayMessage here my code
> > > `const QuotedMsg = isQuotedMsg ? msg.message.extendedTextMessage.contextInfo : msg; const objQuoted = { key: { remoteJid: from ? from : "", id: QuotedMsg.stanzaId ? QuotedMsg.stanzaId : "", participant: QuotedMsg.participant ? QuotedMsg.participant : "", }, message: QuotedMsg.quotedMessage ? QuotedMsg.quotedMessage : "", }; const reactionMessage = { text: send_emoji, key: objQuoted.key, }; const Reactions = generateWAMessageFromContent(from, proto.Message.fromObject({ reactionMessage: reactionMessage }), {}); await Azusa.relayMessage(from, Reactions.message, { messageId: Reactions.key.id }); `
> > 
> > 
> > great
> 
> thanks for your advice

you can close this issue

**Comment by erickythierry** [comment]
> > > > > > > you can use this
> > > > > > > ```
> > > > > > > let quoted = m.message.extendedTextMessage.contextInfo ? m.message.extendedTextMessage.contextInfo : null
> > > > > > > 		if (quoted == null) return 
> > > > > > > 		console.log(quoted)
> > > > > > >         const reactionMessage = {
> > > > > > >             react: {
> > > > > > >                 text: '😮',
> > > > > > >                 key: {remoteJid: to, id: quoted.stanzaId, fromMe: false, participant: quoted.participant}
> > > > > > >             }
> > > > > > >         }
> > > > > > >         const sent = await sock.sendMessage(to, reactionMessage)
> > > > > > > 		return sent
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Sorry but it say error "Cannot use 'in' operator to search for 'stream' in undefined"
> > > > > 
> > > > > 
> > > > > can you show me your code?
> > > > 
> > > > 
> > > > ah it's ok i solved this using relayMessage here my code
> > > > `const QuotedMsg = isQuotedMsg ? msg.message.extendedTextMessage.contextInfo : msg; const objQuoted = { key: { remoteJid: from ? from : "", id: QuotedMsg.stanzaId ? QuotedMsg.stanzaId : "", participant: QuotedMsg.participant ? QuotedMsg.participant : "", }, message: QuotedMsg.quotedMessage ? QuotedMsg.quotedMessage : "", }; const reactionMessage = { text: send_emoji, key: objQuoted.key, }; const Reactions = generateWAMessageFromContent(from, proto.Message.fromObject({ reactionMessage: reactionMessage }), {}); await Azusa.relayMessage(from, Reactions.message, { messageId: Reactions.key.id }); `
> > > 
> > > 
> > > great
> > 
> > 
> > thanks for your advice
> 
> you can close this issue

do you know how to remove a reaction ? I already tried to send an empty reaction, I already tried to use the delete message function in the reaction id, I already tried to use relay copying the structure of the reaction message, nothing works 😕
