### ISSUE TITLE
[ASK] Can Baileys Send With Multiple Media

### ISSUE THREAD

**Issue by zakirkun** [adiwajshing/Baileys#1398]
### Halo!
I'll send messages with multiple images, anyone can help me?

**Comment by ramlan442** [comment]
using loop

**Comment by binsarjr** [comment]
Tutup aj kir. Udh selesai juga. Dan harusnya kalau bertanya jangan disini. Issues khusus bug aja. Ada fitur duscussiin atau join ke discord nya
