### ISSUE TITLE
Live Location messages

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [adiwajshing/Baileys#140]
I am trying to adapt the example.ts file to receive live location updates as they occur. If the client starts live location sharing, I see the message. If the client updates their location I do not see a message.

If I change the log level to all:
```
conn.logLevel = MessageLogLevel.all // set to unhandled to see what kind of stuff you can implement
```
I see that the location messages are loaded upon re-connecting.

Any suggestions for what to check would be appreciated.

**Comment by adiwajshing** [comment]
The implementation for live location is a bit tricky, I haven't had a chance to work on that yet.

**Comment by JohnDoeKyrgyz** [comment]
I am able to receive live location updates with the following code:

```
conn.on('message-update',async (m) => {
        console.log(m)

        const messageContent = m.message
        const messageType = Object.keys (messageContent)[0] // message will always contain one key signifying what kind of message

        let sender = m.key.remoteJid

        if (messageType === MessageType.location || messageType === MessageType.liveLocation) {
            const locMessage = m.message[messageType] as WALocationMessage
            console.log(`${sender} sent location (lat: ${locMessage.degreesLatitude}, long: ${locMessage.degreesLongitude})`)

            if (messageType === MessageType.liveLocation) {
                console.log(`${sender} sent live location for duration: ${m.duration/60}`)
            }
        }})
```

In order to receive updates you actually have to open the live location page on the phone that is connected to the account. I notice that when I do this, I see messages that look like this, coming from the phone:

```
[Baileys][9/8/2020, 2:28:11 PM] ad, ["action",null,[["location",{"type":"update","jid":"<redacted>@c.us","elapsed":"3"},{"type":"Buffer","data":[146,1,20,9,219,79,198,248,48,181,69,64,17,183,9,247,202,188,28,82,192,24,92]}]]]
[Baileys][9/8/2020, 2:28:11 PM] ae, ["action",null,[["location",{"type":"update","jid":"<redacted>@c.us","elapsed":"1"},{"type":"Buffer","data":[146,1,27,9,248,42,31,111,95,181,69,64,17,73,166,48,220,38,29,82,192,24,5,37,143,9,30,65,40,78]}]]]
[Baileys][9/8/2020, 2:28:11 PM] af, ["action",null,[["location",{"type":"update","jid":"<redacted>@c.us","elapsed":"2"},{"type":"Buffer","data":[146,1,22,9,96,155,40,89,162,181,69,64,17,216,210,90,187,203,28,82,192,24,65,40,0]}]]]
```

My guess is that the WhatsApp client on the phone is sending these messages to request location updates. When I close the map screen I no longer see location updates. If I can figure out how to send this message on an interval I think I can get WhatsApp to send locations without having to do anything on the phone.

**Comment by adiwajshing** [comment]
Very cool, I'll see if we can trigger this in some way

**Comment by RumTester** [comment]
Did someone figure out how to trigger the live location updates from this library and not by going to the phone that is connected and opening the live location map on it?
