### ISSUE TITLE
Cannot send a message to a group which was created via non-MD whatsapp web [BUG]

### ISSUE THREAD

**Issue by tiesco238** [adiwajshing/Baileys#1400]
**Describe the bug**
Not able to send a message to a group chat for which the group id is in the old format (3212345678-1849326741@g.us). 
It will not arrive at all (results in timeout).

**To Reproduce**
1. Check for groups which have the id structure with a dash '-' (3212345678-1234567890@g.us)
2. Send a message to this group
3. The message will not appear up in the group

**Expected behavior**
The message should be sent and shown as a new message in the group chat

**Environment (please complete the following information):**
 - Is this on a server? no (local)
 - What do your `connectOptions` look like? n/a
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**
Instead if you send a message to a newly created group (with format: 120361021053134389), it will work fine as expected.

Does anyone know how to fix or workaround this bug?

Thank you,
Matt

**Comment by tiesco238** [comment]
any news? I tried different formats: with dash, without, '+' etc. but no luck :(

**Comment by ahmadkeren** [comment]
sama issue

**Comment by tarikhagustia** [comment]
Same issue
