### ISSUE TITLE
[BUG] [MD] downloadContentFromMessage Types are not compatible

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1406]
I'm try download media messages with Multi-Device, but the compilation processes show:

> 
> src/Baileys.ts:53:9 - error TS2345: Argument of type 'IImageMessage | null | undefined' is not assignable to parameter of type 'DownloadableMessage'.
>   Type 'undefined' is not assignable to type 'DownloadableMessage'.
> 
> 53         msg.message.imageMessage,
>            ~~~~~~~~~~~~~~~~~~~~~~~~
> 

When i check for the argument is not null/undefined:

> 
> src/Baileys.ts:57:9 - error TS2345: Argument of type 'IImageMessage' is not assignable to parameter of type 'DownloadableMessage'.
>   Types of property 'mediaKey' are incompatible.
>     Type 'Uint8Array | null | undefined' is not assignable to type 'Uint8Array | undefined'.
>       Type 'null' is not assignable to type 'Uint8Array | undefined'.
> 
> 57         msg.message.imageMessage,
>            ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 

To reproduce:

`
    sock.ev.on('messages.upsert', async m => {
    const msg = m.messages[0];

    if (!msg.message) return; // if there is no text or media message
    const messageType = Object.keys(msg.message)[0]; // get what type of message it is -- text, image, video
    // if the message is an image
    if (
      messageType === 'imageMessage' &&
      msg.message.imageMessage &&
      msg.message.imageMessage !== null
    ) {
      // download stream
      const stream = await downloadContentFromMessage(
        msg.message.imageMessage,
        'image',
      );
      let buffer = Buffer.from([]);
      for await (const chunk of stream) {
        buffer = Buffer.concat([buffer, chunk]);
      }
      // save to file
      await writeFile('./my-download.jpeg', buffer);
    }
`

where am i wrong?

Thanks

**Comment by drauber** [comment]
I Wrote a new file and take this screenshot

![2022-03-23_18-50](https://user-images.githubusercontent.com/4416953/159801894-922e25b1-740c-40be-8224-07edfb4c7285.png)

**Comment by Kikii-XyZ** [comment]
> I'm try download media messages with Multi-Device, but the compilation processes show:
> 
> > src/Baileys.ts:53:9 - error TS2345: Argument of type 'IImageMessage | null | undefined' is not assignable to parameter of type 'DownloadableMessage'.
> > Type 'undefined' is not assignable to type 'DownloadableMessage'.
> > 53         msg.message.imageMessage,
> > ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> When i check for the argument is not null/undefined:
> 
> > src/Baileys.ts:57:9 - error TS2345: Argument of type 'IImageMessage' is not assignable to parameter of type 'DownloadableMessage'.
> > Types of property 'mediaKey' are incompatible.
> > Type 'Uint8Array | null | undefined' is not assignable to type 'Uint8Array | undefined'.
> > Type 'null' is not assignable to type 'Uint8Array | undefined'.
> > 57         msg.message.imageMessage,
> > ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> To reproduce:
> 
> ` sock.ev.on('messages.upsert', async m => { const msg = m.messages[0];
> 
> ```
> if (!msg.message) return; // if there is no text or media message
> const messageType = Object.keys(msg.message)[0]; // get what type of message it is -- text, image, video
> // if the message is an image
> if (
>   messageType === 'imageMessage' &&
>   msg.message.imageMessage &&
>   msg.message.imageMessage !== null
> ) {
>   // download stream
>   const stream = await downloadContentFromMessage(
>     msg.message.imageMessage,
>     'image',
>   );
>   let buffer = Buffer.from([]);
>   for await (const chunk of stream) {
>     buffer = Buffer.concat([buffer, chunk]);
>   }
>   // save to file
>   await writeFile('./my-download.jpeg', buffer);
> }
> ```
> 
> `
> 
> where am i wrong?
> 
> Thanks

try this
```
const decryptMedia = msg.message.imageMessage || msg.message.extendedTextMessage?.contextInfo.quotedMessage.imageMessage
let stream = await downloadContentFromMessage(decryptMedia, "image")
```

**Comment by drauber** [comment]
I have changed my tsconfig.json "strict": true to "strict": false and now it works.

**Comment by drauber** [comment]
Its only a "typescript mismatch".
