### ISSUE TITLE
First QR Code

### ISSUE THREAD

**Issue by plzy86** [adiwajshing/Baileys#141]
generateKeysForAuth method required a string named ref ,but the caller give it a json object.
So if i use qr for the first login ,I always received a string like [object object],...,...

**Comment by adiwajshing** [comment]
I'm sorry I can't assist you if you don't show any code

**Comment by plzy86** [comment]
In 1.Validation.ts at line number 22, it will use this if i first login 
  `const ref = await this.query({json, expect200: true, waitForOpen: false, longTag: true})`
the ref means a query response object,and then call 
`const result = await this.generateKeysForAuth (ref)`
at line number 162
`const qr = [ref, publicKey, this.authInfo.clientID].join(',')`
I always got a string with [object,object],base64,base64 because the ref is a object but not a string
when i  regenerate qr code , at line number 85, the function regenerateQR use the response.ref in place of the response object
that works fine, now i can't login with the first qr code ,unless i use the regenerateQR 
maybe i do some wrong with than ?

**Comment by adiwajshing** [comment]
Ah, I see. Good catch, fixed in the latest commit.
