### ISSUE TITLE
Browser Icon 

### ISSUE THREAD

**Issue by Gimenz** [adiwajshing/Baileys#1410]
![WhatsApp Image 2022-03-25 at 08 32 05](https://user-images.githubusercontent.com/23699593/160037725-e33e5c12-ba4a-4a3b-98f1-07f1dab2f790.jpeg)

based on this screenshot, why is the browser icon not the same as what is in the code

```javascript
const sock = makeWASocket({
        version: WAVersion,
        printQRInTerminal: true,
        logger: pino({ level: 'silent' }),
        auth: state,
        browser: Browsers.macOS('Safari')
    });
```

what I wrote in the code is 'Safari', but on WhatsApp what appears instead is Google Chrome... 😁😁

**Comment by Alhar6i** [comment]
Strange! It does work for me with no issue!

**Comment by Gimenz** [comment]
> Strange! It does work for me with no issue! So it might not a bug.

really? can you send a screenshot ?

**Comment by kaatt** [comment]
It's because of this line:

https://github.com/adiwajshing/Baileys/blob/334f85f8c5fc4251ee94201965c7593a48d36990/src/Utils/validate-connection.ts#L72

**Comment by Gimenz** [comment]
ah thanks, it worked man.
