### ISSUE TITLE
[BUG] - Why can't I install version 4.0.1?

### ISSUE THREAD

**Issue by wagnerfillio** [adiwajshing/Baileys#1413]
I've been trying in various ways to install the new version, but I can't

I tried the commands below

`yarn add github:adiwajshing/baileys` or `yarn add @adiwajshing/baileys`

It seems silly, but I can only install version 3.5.3, informing directly in package.json
`!@adiwajshing/baileys": "^3.5.3"`,

**Comment by drauber** [comment]
Try with 
`yarn add baileys`
Version 4.0.1 is on yarnpkg

**Comment by rafosolima** [comment]
```
yarn add https://github.com/adiwajshing/Baileys
```
