### ISSUE TITLE
[MD] template button send to me the template not to contact

### ISSUE THREAD

**Issue by enoksaju** [adiwajshing/Baileys#1414]
When sending a template buttons in Android, a message is generated to myself and not to the contact, but the contact can see them in their chat, I think that the template button should be seen in the conversation with the contact and not in a chat with myself

**To Reproduce**
In the sample code run and send a template button responds when you receive a message from any other contact.

```
sock.ev.on('messages.upsert', async m => {
		console.log(JSON.stringify(m, undefined, 2))        
		const msg = m.messages[0]
		if(!msg.key.fromMe && m.type === 'notify') {
			console.log('replying to', m.messages[0].key.remoteJid)
			await sock!.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])		
			
			//send a template message!
			const templateButtons = [
				{index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
				{index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
				{index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
			]

			const templateMessage = {
				text: "Hi it's a template message",
				footer: 'Hello World',
				templateButtons: templateButtons
			}

			const sendMsg = await sock.sendMessage(msg.key.remoteJid, templateMessage)
			
			
		}
        
	})
```

**Expected behavior**

What was expected to be seen is that in the whatsapp that has the session and the bot does not generate a self-sent message when sending template buttons

**Comment by letsEdu** [comment]
for me this is happening only in mobile, in web version work normal

**Comment by vphelipe** [comment]
I'm having the exact same problem, I can't send non-contact templatebuttons

**Comment by ravindu01manoj** [comment]
@adiwajshing Its Send By Web Jid... (xxx:2@wha....., or xxx:3@wha... or ...)

**Comment by Inevitable-Dev** [comment]
Same problem here, when an msg Template is sent, it is also sent to the contact where baileys is being running

**Comment by ghifar1** [comment]
Same here

**Comment by enoksaju** [comment]
Closed, but not fixed

**Comment by Jorsis** [comment]
same

**Comment by Davidaprilio** [comment]
same here only type templateButtons message

**Comment by Francuchin** [comment]
Same

**Comment by mgulbazilyas** [comment]
same
