### ISSUE TITLE
[BUG] "Closing stale open session for new outgoing prekey bundle" 

### ISSUE THREAD

**Issue by manojsitapara** [adiwajshing/Baileys#1418]
Periodically I receive this message in error log, no other info. can anyone please suggest how to fix this?

**Comment by MacKey-255** [comment]
This error?
```
[20-marzo-2022 11:14:25 pm] Closing stale open session for new outgoing prekey bundle
[20-marzo-2022 11:14:25 pm] Closing session: SessionEntry {
  _chains: {
    'BZJQKcsQ1rQv+CKK9xNzHbkaDjkLHfS5EO0mdscoy6Im': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 1594465270,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 92 50 29 cb 10 d6 b4 2f f8 22 8a f7 13 73 1d b9 1a 0e 39 0b 1d f4 b9 10 ed 26 76 c7 28 cb a2 26>,
      privKey: <Buffer 68 66 36 7d 5a 73 e5 58 47 7c de a1 e9 92 fd 1c 2f 08 81 77 05 8c d5 1c a7 a8 05 5b f6 b6 c6 4e>
    },
    lastRemoteEphemeralKey: <Buffer 05 58 8a 29 c0 d0 12 01 8a 18 6b d2 22 73 57 5e d1 be 82 c6 cd 00 63 6b 42 6c 46 93 f5 c1 c2 4b 56>,
    previousCounter: 0,
    rootKey: <Buffer 49 c7 49 47 19 9f 53 8c eb f4 58 7e fa 34 f5 43 98 30 09 41 23 47 47 a1 21 b7 05 4f 3f 33 5b b1>
  },
  indexInfo: {
    baseKey: <Buffer 05 a1 99 af 09 66 70 ea 51 51 27 37 d5 8d 7c 31 d5 33 43 c5 47 2b af db 6d 82 2c 66 bb 77 fa 6f 7e>,
    baseKeyType: 1,
    closed: -1,
    used: 1647807642508,
    created: 1647807642508,
    remoteIdentityKey: <Buffer 05 48 8d 82 1b ac 43 1a c2 f8 5c 9c 36 e2 d4 0a df 59 72 54 aa d6 79 fd 12 f9 d8 ac 57 3c 6d 8d 6f>
  },
  pendingPreKey: {
    signedKeyId: 1,
    baseKey: <Buffer 05 a1 99 af 09 66 70 ea 51 51 27 37 d5 8d 7c 31 d5 33 43 c5 47 2b af db 6d 82 2c 66 bb 77 fa 6f 7e>,
    preKeyId: 14420667
  }
}
[20-marzo-2022 11:14:28 pm] Closing stale open session for new outgoing prekey bundle
[20-marzo-2022 11:14:28 pm] Closing session: SessionEntry {
  _chains: {
    'BcDSlqfTXcOVDEZkv+lhBgM2sFZiiY6tCPMMgB87AX0d': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 1852877201,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 c0 d2 96 a7 d3 5d c3 95 0c 46 64 bf e9 61 06 03 36 b0 56 62 89 8e ad 08 f3 0c 80 1f 3b 01 7d 1d>,
      privKey: <Buffer 10 c4 a7 42 a2 d9 09 a1 26 0d b7 4f 2d 34 af 39 fc 13 30 c0 c4 ca 00 32 ea 36 5b df 71 2f 7e 56>
    },
    lastRemoteEphemeralKey: <Buffer 05 e5 9b a8 6a f8 44 90 3e 06 27 c4 53 e8 b0 2b eb e1 9e 48 ed 49 0c f9 e4 48 86 95 46 15 25 e0 4c>,
    previousCounter: 0,
    rootKey: <Buffer 0e d1 68 5e d1 88 a0 33 a4 1d 87 8d a2 27 26 e5 77 82 ef 90 74 fe 8a a1 ec 01 ac d7 48 bb 90 0f>
  },
  indexInfo: {
    baseKey: <Buffer 05 d0 61 ca 39 98 99 ac 10 0a 30 7b b7 32 53 f0 95 89 d8 03 ca 17 5a 92 9b bf 99 d4 1b 30 f0 26 57>,
    baseKeyType: 1,
    closed: -1,
    used: 1647801609631,
    created: 1647801609631,
    remoteIdentityKey: <Buffer 05 a3 7b bc 4e e1 6c 07 ca 97 ea 6b 14 d7 b3 97 67 00 18 4b a3 c1 15 67 74 65 7e 2f b6 c4 74 39 6d>
  },
  pendingPreKey: {
    signedKeyId: 3,
    baseKey: <Buffer 05 d0 61 ca 39 98 99 ac 10 0a 30 7b b7 32 53 f0 95 89 d8 03 ca 17 5a 92 9b bf 99 d4 1b 30 f0 26 57>,
    preKeyId: 2101742
  }
}
```
I have the same problem, and `client.ev.on('messages.upsert')` don't receive messages :/

**Comment by manojsitapara** [comment]
> This error?
> ```
> [20-marzo-2022 11:14:25 pm] Closing stale open session for new outgoing prekey bundle
> [20-marzo-2022 11:14:25 pm] Closing session: SessionEntry {
>   _chains: {
>     'BZJQKcsQ1rQv+CKK9xNzHbkaDjkLHfS5EO0mdscoy6Im': { chainKey: [Object], chainType: 1, messageKeys: {} }
>   },
>   registrationId: 1594465270,
>   currentRatchet: {
>     ephemeralKeyPair: {
>       pubKey: <Buffer 05 92 50 29 cb 10 d6 b4 2f f8 22 8a f7 13 73 1d b9 1a 0e 39 0b 1d f4 b9 10 ed 26 76 c7 28 cb a2 26>,
>       privKey: <Buffer 68 66 36 7d 5a 73 e5 58 47 7c de a1 e9 92 fd 1c 2f 08 81 77 05 8c d5 1c a7 a8 05 5b f6 b6 c6 4e>
>     },
>     lastRemoteEphemeralKey: <Buffer 05 58 8a 29 c0 d0 12 01 8a 18 6b d2 22 73 57 5e d1 be 82 c6 cd 00 63 6b 42 6c 46 93 f5 c1 c2 4b 56>,
>     previousCounter: 0,
>     rootKey: <Buffer 49 c7 49 47 19 9f 53 8c eb f4 58 7e fa 34 f5 43 98 30 09 41 23 47 47 a1 21 b7 05 4f 3f 33 5b b1>
>   },
>   indexInfo: {
>     baseKey: <Buffer 05 a1 99 af 09 66 70 ea 51 51 27 37 d5 8d 7c 31 d5 33 43 c5 47 2b af db 6d 82 2c 66 bb 77 fa 6f 7e>,
>     baseKeyType: 1,
>     closed: -1,
>     used: 1647807642508,
>     created: 1647807642508,
>     remoteIdentityKey: <Buffer 05 48 8d 82 1b ac 43 1a c2 f8 5c 9c 36 e2 d4 0a df 59 72 54 aa d6 79 fd 12 f9 d8 ac 57 3c 6d 8d 6f>
>   },
>   pendingPreKey: {
>     signedKeyId: 1,
>     baseKey: <Buffer 05 a1 99 af 09 66 70 ea 51 51 27 37 d5 8d 7c 31 d5 33 43 c5 47 2b af db 6d 82 2c 66 bb 77 fa 6f 7e>,
>     preKeyId: 14420667
>   }
> }
> [20-marzo-2022 11:14:28 pm] Closing stale open session for new outgoing prekey bundle
> [20-marzo-2022 11:14:28 pm] Closing session: SessionEntry {
>   _chains: {
>     'BcDSlqfTXcOVDEZkv+lhBgM2sFZiiY6tCPMMgB87AX0d': { chainKey: [Object], chainType: 1, messageKeys: {} }
>   },
>   registrationId: 1852877201,
>   currentRatchet: {
>     ephemeralKeyPair: {
>       pubKey: <Buffer 05 c0 d2 96 a7 d3 5d c3 95 0c 46 64 bf e9 61 06 03 36 b0 56 62 89 8e ad 08 f3 0c 80 1f 3b 01 7d 1d>,
>       privKey: <Buffer 10 c4 a7 42 a2 d9 09 a1 26 0d b7 4f 2d 34 af 39 fc 13 30 c0 c4 ca 00 32 ea 36 5b df 71 2f 7e 56>
>     },
>     lastRemoteEphemeralKey: <Buffer 05 e5 9b a8 6a f8 44 90 3e 06 27 c4 53 e8 b0 2b eb e1 9e 48 ed 49 0c f9 e4 48 86 95 46 15 25 e0 4c>,
>     previousCounter: 0,
>     rootKey: <Buffer 0e d1 68 5e d1 88 a0 33 a4 1d 87 8d a2 27 26 e5 77 82 ef 90 74 fe 8a a1 ec 01 ac d7 48 bb 90 0f>
>   },
>   indexInfo: {
>     baseKey: <Buffer 05 d0 61 ca 39 98 99 ac 10 0a 30 7b b7 32 53 f0 95 89 d8 03 ca 17 5a 92 9b bf 99 d4 1b 30 f0 26 57>,
>     baseKeyType: 1,
>     closed: -1,
>     used: 1647801609631,
>     created: 1647801609631,
>     remoteIdentityKey: <Buffer 05 a3 7b bc 4e e1 6c 07 ca 97 ea 6b 14 d7 b3 97 67 00 18 4b a3 c1 15 67 74 65 7e 2f b6 c4 74 39 6d>
>   },
>   pendingPreKey: {
>     signedKeyId: 3,
>     baseKey: <Buffer 05 d0 61 ca 39 98 99 ac 10 0a 30 7b b7 32 53 f0 95 89 d8 03 ca 17 5a 92 9b bf 99 d4 1b 30 f0 26 57>,
>     preKeyId: 2101742
>   }
> }
> ```
> I have the same problem, and `client.ev.on('messages.upsert')` don't receive messages :/

Yes

**Comment by manojsitapara** [comment]
@adiwajshing  Can you please help?

**Comment by tiagoandrepro** [comment]
+1

**Comment by Bloxoid123** [comment]
+1

**Comment by manojsitapara** [comment]
@adiwajshing can you please give us some workaround to fix the issue?

**Comment by sabinocc** [comment]
+1

**Comment by manojsitapara** [comment]
@adiwajshing can you please help?

**Comment by paulocorcino** [comment]
+1

**Comment by jccalbuquerque** [comment]
+1

**Comment by manojsitapara** [comment]
@adiwajshing  can you please help?

**Comment by jccalbuquerque** [comment]
@adiwajshing can you please help?

**Comment by ibnumardini** [comment]
+1 any updates?

**Comment by manojsitapara** [comment]
@adiwajshing please help

**Comment by MacKey-255** [comment]
+1

**Comment by manojsitapara** [comment]
+1

**Comment by enoksaju** [comment]
same here, please help

**Comment by MacKey-255** [comment]
+1

**Comment by hassanfuad96** [comment]
+1

**Comment by enoksaju** [comment]
@adiwajshing  can you please help?

**Comment by enoksaju** [comment]
Is there an update?

**Comment by mrhb6006** [comment]
+1

**Comment by guilhermeromer** [comment]
Any updates?

**Comment by manojsitapara** [comment]
@adiwajshing any update?

**Comment by ReiDx** [comment]
any updates?

**Comment by manojsitapara** [comment]
You can ignore this warning

**Comment by arugaz** [comment]
[Libsignal](https://github.com/adiwajshing/libsignal-node/blob/master/src/session_builder.js#L46)
