### ISSUE TITLE
[BUG] groupMetadata - rate-overlimit

### ISSUE THREAD

**Issue by Iucasmaia** [adiwajshing/Baileys#1419]
Hi, groupMetadata (groupQuery) is showing this error when i execute.

`(node:35080) UnhandledPromiseRejectionWarning: Error: rate-overlimit
    at Object.assertNodeErrorFree (/root/mmm/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
    at query (/root/mmm/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:134:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.groupMetadata (/root/mmm/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
    at async principal (/root/mmm/src/principal.js:41:43)`

**Comment by Gimenz** [comment]
yah same

**Comment by MacKey-255** [comment]
Same error:
```
Error: rate-overlimit
    at Object.assertNodeErrorFree (/whatsapp/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
    at query (/whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:138:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async groupMetadata (/whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
    at async /whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41
    at async Promise.all (index 0)
    at async /whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51
    at async Object.transaction (/whatsapp/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:72:17)
    at async relayMessage (/whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9)
```
SAlu2s

**Comment by pe77** [comment]
same here

**Comment by zhinea** [comment]
same issue

**Comment by Bintang73** [comment]
> yah same

yeah same

**Comment by iluser** [comment]
> Same error:
> 
> ```
> Error: rate-overlimit
>     at Object.assertNodeErrorFree (/whatsapp/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)
>     at query (/whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:138:24)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async groupMetadata (/whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
>     at async /whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41
>     at async Promise.all (index 0)
>     at async /whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51
>     at async Object.transaction (/whatsapp/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:72:17)
>     at async relayMessage (/whatsapp/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9)
> ```
> 
> I think that happens when there are so many operations at the same time. SAlu2s

does anyone know how to get past that limit?

**Comment by aidulcandra** [comment]
I also have this issue, but I think after seeing the discussion it seems like it is caused by too many request for group metadata, let's try caching the group metadata, so that we don't over requesting it.

Also don't forget to update the metadata whenever any setting has changed

**Comment by Rasu-a** [comment]
> I also have this issue, but I think after seeing the discussion it seems like it is caused by too many request for group metadata, let's try caching the group metadata, so that we don't over requesting it.
> 
> Also don't forget to update the metadata whenever any setting has changed

How, to check metadata btw?

**Comment by aidulcandra** [comment]
@Rasu-a 
await sock.groupMetadata()

**Comment by shirser121** [comment]
Did you solve this?

**Comment by zhinea** [comment]
Yes, I've finished it. the main problem is when you have too many requests to the whatsapp server. examples are get group metadata, hit onWhatsApp number, etc.

**Comment by shirser121** [comment]
> Yes, I've finished it. the main problem is when you have too many requests to the whatsapp server. examples are get group metadata, hit onWhatsApp number, etc.

So if I want all the group metadata, how should I do it?

**Comment by zhinea** [comment]
> > Yes, I've finished it. the main problem is when you have too many requests to the whatsapp server. examples are get group metadata, hit onWhatsApp number, etc.
> 
> So if I want all the group metadata, how should I do it?

Use cache
