### ISSUE TITLE
image with template button 

### ISSUE THREAD

**Issue by Masterxv** [adiwajshing/Baileys#1424]
i want to send image with template button send

**Comment by DwiRizqiH** [comment]
```
//send a template message with an image **attached**!
const templateButtons = [
  {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
  {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
  {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const buttonMessage = {
    caption: "Hi it's a template message",
    footer: 'Hello World',
    templateButtons: templateButttons,
    image: { url: 'https://example.com/image.jpeg' } //it can be array { url: 'https://example.com/image.jpeg' } or buffer
}

const sendMsg = await sock.sendMessage(id, templateMessage)
```

**Comment by ngadimin51** [comment]
same here, image cannot sent

**Comment by xdavian** [comment]
same here too. image can't sent

**Comment by ngadimin51** [comment]
Work here

> ```
> //send a template message with an image **attached**!
> const templateButtons = [
>   {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
>   {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
>   {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
> ]
> 
> const buttonMessage = {
>     caption: "Hi it's a template message",
>     footer: 'Hello World',
>     templateButtons: templateButttons,
>     image: { url: 'https://example.com/image.jpeg' } //it can be array { url: 'https://example.com/image.jpeg' } or buffer
> }
> 
> const sendMsg = await sock.sendMessage(id, templateMessage)
> ```

Fixed, ushe like @DwiRizqiH 
Change the text to caption.
