### ISSUE TITLE
[BUG] The promise rejected with the reason "1006".     

### ISSUE THREAD

**Issue by zakirkun** [adiwajshing/Baileys#1425]
I have problem 

> [ERROR] 21:31:37 UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".

**Comment by burstfreeze** [comment]
You have to share more of the log, this single line is not enough for us to fix something.

Share the whole log but make sure to delete personal identifiers such as phone numbers before people start calling you 😅

**Comment by makanSukros** [comment]
Me too getting error like this

uncaughtException [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

I've wrapped all async await functions with try catch but the above error still appears I don't know where it came from 😅

**Comment by zakirkun** [comment]
> Me too getting error like this
> 
> uncaughtException [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".] { code: 'ERR_UNHANDLED_REJECTION' }
> 
> I've wrapped all async await functions with try catch but the above error still appears I don't know where it came from 😅

many socket connectin open i think

**Comment by aislanspeedio** [comment]
Same problem, here!!!
