### ISSUE TITLE
always online[BUG]

### ISSUE THREAD

**Issue by mosalmsoft** [adiwajshing/Baileys#1427]
**Describe the bug**
after scanning my WhatsApp .
my WhatsApp status appear online for all my contacts.
is it normal behavior to appear for all contact always online?
is this a bug or some code logic?

thanks in advance.

**To Reproduce**
1. Created a new connection
2. scan your whatsapp MD version
3. look from another whatsapp to your whatsapp no.

**Expected behavior**
the scanned WhatsApp status should not be always appears online .
like normal behavior (last seen ....) or no status like apple.

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Comment by mosalmsoft** [comment]
> It's normal, after all you are online.
> 
> You can change the status with:
> 
> ```js
> await sock.sendPresenceUpdate('unavailable', id)
> ```

thanks AkirahX,for reply
the issue is if 24H the status of my whatsapp is Online , i need it to be like normal whatsapp , if i send it get online then unavilable

**Comment by AkirahX** [comment]
> > É normal, afinal você está online.
> > Você pode alterar o status com:
> > ```js
> > aguardo  meia . sendPresenceUpdate ( 'indisponível' ,  id )
> > ```
> 
> obrigado AkirahX, para responder o problema é se 24H o status do meu whatsapp for Online, preciso que seja como o whatsapp normal, se eu enviar fique online então indisponível



> > It's normal, after all you are online.
> > You can change the status with:
> > ```js
> > await sock.sendPresenceUpdate('unavailable', id)
> > ```
> 
> thanks AkirahX,for reply the issue is if 24H the status of my whatsapp is Online , i need it to be like normal whatsapp , if i send it get online then unavilable

I don't see how, when you're connected to WhatsApp it's like you have a tab open in your browser forever.

**Comment by AkirahX** [comment]
> > It's normal, after all you are online.
> > You can change the status with:
> > ```js
> > await sock.sendPresenceUpdate('unavailable', id)
> > ```
> 
> thanks AkirahX,for reply the issue is if 24H the status of my whatsapp is Online , i need it to be like normal whatsapp , if i send it get online then unavilable

I don't see how, when you're connected to WhatsApp it's like you have a tab open in your browser forever.

**Comment by mosalmsoft** [comment]
yes i know same the whatsapp web .
as i have whatsapp web on my laptop always open .
but if i dont open its tab my status not be online ,On the contrary, the situation when using baileys ,just i scanned the qr code.
all my contacts see me always online all the time even i was shutting down my mobile and sleep.
