### ISSUE TITLE
Send presence update "recording" don't work [BUG]

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#1430]
Send presence update "recording" don't work.
Always stay online

**Comment by jeferssonlemes** [comment]
I made a correction of this, I will make a pr

**Comment by IanosJunior** [comment]
Are you to post here?

**Comment by jeferssonlemes** [comment]
@lanos

> Will you post here?

It's merged in master:
https://github.com/adiwajshing/Baileys/commit/ac9625adbb89609a2971106bdc68a59a79797d08
