### ISSUE TITLE
[MD] Check connection is ok?

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1432]
Is ther a way to check if connect is ok? 

sock.connectionIsOk() ?

Thanks

**Comment by Alhar6i** [comment]
I don't think so, but you can use the 'connection.update' event if you wouldn't like to add any implementation to the socket file.

You'll receive the 'connection.update' event whenever the connection state is changed (i.e open, close, and connecting)
```
sock.ev.on('connection.update', (update) => {
const { connection, lastDisconnect } = update;
//print the current connection  state 
console.log(connection);
})
```

Hope that helps.
