### ISSUE TITLE
how to get chats, contacts and messages v4

### ISSUE THREAD

**Issue by wagnerfillio** [adiwajshing/Baileys#1434]
how to get chats, contacts and messages?

the only time this information was obtained was when I read the qrcode!
via `chats.set`, `contacts.set` and `messages.set` events

I want to access this information to save to a database

**Comment by zakirkun** [comment]
im using webhooks

**Comment by salman0ansari** [comment]
```js
socket.ev.on('chats.set', async ({ chats }) => { `your code` })
```

**Comment by Pegorino82** [comment]
@zakirkun 
> im using webhooks

could you share, please

**Comment by Pegorino82** [comment]
@salman0ansari 
> ```js
> socket.ev.on('chats.set', async ({ chats }) => { `your code` })
> ```
i cannot catch this event. does it fires only once after qr scanned as @wagnerfillio says?

**Comment by salman0ansari** [comment]
> 

yes it only fires once you have to create data store to access event data later

**Comment by wagnerfillio** [comment]
> > 
> 
> yes it only fires once you have to create data store to access event data later

Well, what's the best way to store this data and get it anytime?
Any examples?

**Comment by salman0ansari** [comment]
> > > 
> > 
> > 
> > yes it only fires once you have to create data store to access event data later
> 
> Well, what's the best way to store this data and get it anytime? Any examples?

store data in db

**Comment by AxeemHaider** [comment]
If it fires only first time then how web.whatsapp.com handle this if you refresh browser page it fetch all messages and chats again. isn't it ?
