### ISSUE TITLE
connection not created on new whatsapp business

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#144]
on the day of today, all whatsapp business do not connect to the platform.

**Comment by sthales** [comment]
Works fine here

**Comment by algoz098** [comment]
It seems to be not all wp business, i have a couple and not all of them have a problem, but part of it

**Comment by adiwajshing** [comment]
@algoz098  It seems to be working fine, can you share an error log?

**Comment by algoz098** [comment]
The thing was the connection timeout, so there wasn't a log. The situation worked when i grab yestarday commits.
