### ISSUE TITLE
Send QR code to any other http Page / Server

### ISSUE THREAD

**Issue by kaniket7209** [adiwajshing/Baileys#1440]
Is there any way there to send the qr code to any other server address despite terminal.. Puppeteer is welcomed but thinking of just a way to scan it from a frontend page connected via server

**Comment by AiceGate** [comment]
socket.io

**Comment by kaniket7209** [comment]
But the qr code (url) is encoded and oy welcomed by whatsApp automatic decoder.. So how can i. Process the function to encode that url and sent over socket?

**Comment by Alhar6i** [comment]
> But the qr code (url) is encoded and oy welcomed by whatsApp automatic decoder.. So how can i. Process the function to encode that url and sent over socket?

The qr value that you receive on the update event is the value that you must use to generate the qr image.

**Comment by salman0ansari** [comment]
```js
const QRCode = require('qrcode')
let qrcode = ""
socket.ev.on('connection.update', async (update) => {
              const {  qr } = update
              if (qr) {
                QRCode.toDataURL(qr).then((url) => { qrcode = url }
```

**Comment by kaniket7209** [comment]
Thanks it worked..
