### ISSUE TITLE
[BUG] the message is still sent even though the number is not valid

### ISSUE THREAD

**Issue by aguskusmara** [adiwajshing/Baileys#1442]
all number is registered on whatsapp

![Screenshot_2022-04-01-14-52-09-58_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/71338260/161220531-1b3073ea-5c63-41cd-8c0b-5bbe1100ae72.jpg)

**Comment by FaizBastomi** [comment]
what do you mean?

**Comment by aguskusmara** [comment]
in bailey MD..
all number registered on whatsapp..

const id = '123456'
const [result] = await sock.onWhatsApp(id)
if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)

the result always exist
and the message is send

check this number

![IMG_20220401_234733](https://user-images.githubusercontent.com/71338260/161307263-b047883e-c265-4d79-93ec-f9891f1aafc8.jpg)

**Comment by aguskusmara** [comment]
![IMG_20220401_235026](https://user-images.githubusercontent.com/71338260/161307721-fcbdcddf-b56f-4378-9de4-fa7d154eb883.jpg)
