### ISSUE TITLE
[BUG] Cant link new devices at this time while trying to scan qr code.

### ISSUE THREAD

**Issue by sandro-salles** [adiwajshing/Baileys#1443]
**Describe the bug**
Hello.. every time i try to scan a QR Code in order to complete authentication flow, is shows a "**Cant link new devices at this time**" error on my device.

After that, i simply cannot scan even on web.whatsapp.com interface. Always the same error... 

Do you guys have any group on whatsapp or even discord where we can talk to other users, maybe having the same issue... ?

**To Reproduce**
1. Created a new connection
2. Wait for scan to show.
3. Scan on device (iPhone 7 with multi device enable by default)
4. See the error screen.

**Expected behavior**
To complete the QR Code scan succesully and be able to send/receive messages.

**Environment (please complete the following information):**
 - Is this on a server? 
 Nope... on my local machine.
 
 - What do your `connectOptions` look like? 
 `  const sock = makeWASocket({
    version,
    logger: logger.child({ level: "trace" }),
    printQRInTerminal: true,
    auth: state,
    // implement to handle retries
    getMessage: async (key) => {
      return {
        conversation: "hello",
      };
    },
  });`
 
The same as in the Example.

 - Do you have multiple clients on the same IP?
  No, but i must have in order to complete my project.
 
 - Are you using a proxy?
No.

**Additional context**

**Comment by HUGEIT** [comment]
https://github.com/adiwajshing/Baileys/issues?q=ghost+session

best you can do now is to wait and hope for the ghost sessions to be automatically wiped after a day maybe

**Comment by sandro-salles** [comment]
> https://github.com/adiwajshing/Baileys/issues?q=ghost+session
> 
> best you can do now is to wait and hope for the ghost sessions to be automatically wiped after a day maybe

@HUGEIT i found that by removing the app from my iPhone and reinstalling, the problem goes away (untill it comes back again... )

So it seems that the state in the mobile app itself, that probably controls the connected sessions , is getting dirty somehow.

**Comment by HUGEIT** [comment]
> @HUGEIT i found that by removing the app from my iPhone and reinstalling, the problem goes away (untill it comes back again... )

@sandro-salles that is very interesting. I thought the number is useless after you burned through 4 of these sessions. being able to re-install to see 4 new slots is a nice backup but it's still very bad for users

**Comment by sandro-salles** [comment]
@HUGEIT yep... very bad... :(

**Comment by code-by** [comment]
+1

**Comment by audiolomb** [comment]
+1
