### ISSUE TITLE
Restart Required Loop [BUG]

### ISSUE THREAD

**Issue by contateste584394857** [adiwajshing/Baileys#1448]
I'm in a "Restart Required" loop and it doesn't connect
I'm using the [example ](https://github.com/adiwajshing/Baileys#connecting)

I scan the QR
```
...,"msg":"registered connection, restart server...
...{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"}
connection closed due to  Error: Restart Required
```
It shows another QR, I scan it and the same error happens

**Comment by zakirkun** [comment]
same error

**Comment by contateste584394857** [comment]
[This code](https://pastebin.com/GEsk2w5i) is working normally for me

**Comment by m0nx73r** [comment]
same, any solution?

**Comment by contateste584394857** [comment]
> same, any solution?

@m0nx73r [yes](https://github.com/adiwajshing/Baileys/issues/1448#issuecomment-1093547983)

**Comment by contateste584394857** [comment]
https://github.com/adiwajshing/Baileys/issues/1448#issuecomment-1093547983

**Comment by mi-khatri** [comment]
Hi, i am facing same issue, but i able to connect when i completely restart my phone.
Please try to restart your phone, 
please delete your session file before connect

i hope this will help you

**Comment by asrofindo** [comment]
> [This code](https://pastebin.com/GEsk2w5i) is working normally for me

This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

Could you share the file?

Thank you very much.

**Comment by elie-atia** [comment]
> > [This code](https://pastebin.com/GEsk2w5i) is working normally for me
> 
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.
> 
> Could you share the file?
> 
> Thank you very much.

I'm facing the same problem, please provide an update of the code. Thanks you

**Comment by Shubhamrawat5** [comment]
Same error
