### ISSUE TITLE
[BUG] Closing stale open session for new outgoing prekey bundle

### ISSUE THREAD

**Issue by naylachan** [adiwajshing/Baileys#1449]
Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry {                                                           _chains: {
    'Be+KESjc7uroM1QBUgNdRqJHRVR0SJQIqbISUZYgj5h2': { chainKey: [Object], chainType: 2, messageKeys: {} },
    'BXFNco2uCwGTPDQoIJEJs8nNugrn4AfOEVph6YzTPlM+': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },                                                                                      registrationId: 61,
  currentRatchet: {                                                                         ephemeralKeyPair: {
      pubKey: <Buffer 05 71 4d 72 8d ae 0b 01 93 3c 34 28 20 91 09 b3 c9 cd ba 0a e7 e0 07 ce 11 5a 61 e9 8c d3 3e 53 3e>,
      privKey: <Buffer 28 9b 62 25 12 f9 86 65 78 11 13 92 fc 8e 37 c9 74 ce 28 c9 60 dd fe 94 c8 63 0e e7 e5 81 c5 59>
    },                                                                                      lastRemoteEphemeralKey: <Buffer 05 ef 8a 11 28 dc ee ea e8 33 54 01 52 03 5d 46 a2 47 45 54 74 48 94 08 a9 b2 12 51 96 20 8f 98 76>,                                            previousCounter: 0,
    rootKey: <Buffer dc 15 9b 67 76 77 7c 5a 6d 9d eb 31 7d f4 d7 4a f2 e0 7e 14 25 d1 39 6d ba 13 fa 95 ef 3d 53 88>
  },                                                                                      indexInfo: {
    baseKey: <Buffer 05 bc 2b 18 6c c7 44 7d f5 f3 fd 6f f7 f3 36 d1 1b cf 64 d9 9d f8 51 cd be 3f 59 07 f7 69 56 01 60>,
    baseKeyType: 2,                                                                         closed: -1,
    used: 1648982359314,                                                                    created: 1648982359314,
    remoteIdentityKey: <Buffer 05 fc 82 64 7b e4 bd 58 49 99 1e 16 a9 7f 7c d1 61 2c 92 d3 26 47 89 14 95 e6 ad 37 94 9d 06 96 18>
  }                                                                                     }
Solusi?

**Comment by tiagoandrepro** [comment]
+1

**Comment by sabinocc** [comment]
+1

**Comment by paulocorcino** [comment]
+1

**Comment by makanSukros** [comment]
+1

**Comment by lauriolasw** [comment]
Same here

**Comment by manojsitapara** [comment]
+1

**Comment by jccalbuquerque** [comment]
+1

**Comment by mateuscdor** [comment]
+1

**Comment by LightningNeko** [comment]
+1

**Comment by Fonnte** [comment]
+1

**Comment by salman0ansari** [comment]
+1

**Comment by Bloxoid123** [comment]
+1

**Comment by jccalbuquerque** [comment]
@adiwajshing can you please help?

**Comment by tyagolp** [comment]
+1

**Comment by lauriolasw** [comment]
+1

**Comment by 4relial** [comment]
+1

**Comment by manojsitapara** [comment]
@adiwajshing any update?

**Comment by paulocorcino** [comment]
Stranger nobody to talk about this issue. I believe explain something is a good start.

**Comment by aidulcandra** [comment]
I also have this issue when sending a message to a group, the bot also sends a "Waiting for this message" message.
However in local server it's working fine..

**Comment by enoksaju** [comment]
same here

**Comment by ricco-douro** [comment]
+1

**Comment by w3nder** [comment]
+1

**Comment by guilhermeromer** [comment]
+1

**Comment by bthomaz** [comment]
+1

**Comment by bigbangshop** [comment]
Same here.. help us

**Comment by bigbangshop** [comment]
First message sent to new id show a wait message in cell app and not show in web whatsapp.
other messages receive in cell app and still not show in web whatsapp until the id responds

**Comment by enoksaju** [comment]
describe same problem
Duplicate of #1603

**Comment by mrhb6006** [comment]
same problem

**Comment by jeffersonveloso** [comment]
Hello guys check this issue #1631.

**Comment by guilhermeromer** [comment]
Any updates?

**Comment by MacKey-255** [comment]
+1

**Comment by tiagomatrixd** [comment]
any solution?

**Comment by Heknon** [comment]
same here (on 4.3.0)

**Comment by aangindra** [comment]
same

**Comment by edwindefine** [comment]
any help?

**Comment by Xnuvers007** [comment]
Any help ?

**Comment by arifintajul4** [comment]
any help?

**Comment by JonazBR** [comment]
+1
