### ISSUE TITLE
[BUG] [ERROR] 02:44:38 Error: Timed Out  

### ISSUE THREAD

**Issue by zakirkun** [adiwajshing/Baileys#1459]
I have problem on wa md, trace error : 
``Error: Timed Out                                                                                                            at C:\Users\user\Workspace\backend-services-whatsapp\node_modules\@adiwajshing\baileys\lib\Utils\generics.js:178:32     at runNextTicks (node:internal/process/task_queues:61:5)                                                                at listOnTimeout (node:internal/timers:528:9)                                                                           at processTimers (node:internal/timers:502:7)                                                                       [ERROR] 02:44:38 Error: Timed Out

**Comment by zakirkun** [comment]
@adiwajshing

**Comment by ricco-douro** [comment]
Error: Timed Out
    at /srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32 {
  data: {
    stack: 'Error\n' +
      '    at Object.promiseTimeout (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:173:19)\n' +
      '    at waitForMessage (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:114:42)\n' +
      '    at query (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:137:22)\n' +
      '    at getUSyncDevices (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:172:30)\n' +
      '    at /srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:320:53\n' +
      '    at Object.transaction (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:78:27)\n' +
      '    at relayMessage (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:259:30)\n' +
      '    at Object.sendMessage (/srv/mware/gigatech/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:412:23)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

/*****************************************************************************
I had the same problem today and it all comes down to the something in the image that i was attaching. I have resolved the problema by opening and closing the picture in Paint.

two files are virtually identical in resolution and depth the ...1.jpg crashes and the ......2.jpg goes

[public.zip](https://github.com/adiwajshing/Baileys/files/8548264/public.zip)

Any ideas?
