### ISSUE TITLE
Include interactive Message Templetas

### ISSUE THREAD

**Issue by Fermich11** [adiwajshing/Baileys#146]
Would be nice to include the Interactive Message templates, as allow Us as dev's to create a better UX.

**Comment by adiwajshing** [comment]
I'm not sure what you're asking of, could you provide more details

**Comment by Fermich11** [comment]
it's a new feature that whatsapp is implementing: 
https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/
![image](https://user-images.githubusercontent.com/35929537/92940135-57560580-f414-11ea-955d-a29370edc450.png)

**Comment by adiwajshing** [comment]
I see, would be a cool feature to implement. However, it's hard to do as I don't have an example of what such a message looks like.

**Comment by adiwajshing** [comment]
So, I experimented with it with no success. Have commented the test in `Tests.Messages.ts` -- feel free to experiment further

**Comment by adiwajshing** [comment]
So, unfortunately, this does not seem possible right now. See [this](https://github.com/open-wa/wa-automate-nodejs/issues/98) & [this](https://github.com/Rhymen/go-whatsapp/issues/296)

Do let me know if you find something, closing for now.

**Comment by Fermich11** [comment]
ok, thanks! will let you know if I found how to make it work.

**Comment by BerTren-Nation** [comment]
> it's a new feature that whatsapp is implementing:
> https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/
> ![image](https://user-images.githubusercontent.com/35929537/92940135-57560580-f414-11ea-955d-a29370edc450.png)

@adiwajshing Is it possible now Can?

**Comment by PurpShell** [comment]
nope, read what he sent you

**Comment by RynKings** [comment]
#590 It now supported by using this protobuf

**Comment by RynKings** [comment]
> > it's a new feature that whatsapp is implementing:
> > https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/interactive-message-templates/
> > ![image](https://user-images.githubusercontent.com/35929537/92940135-57560580-f414-11ea-955d-a29370edc450.png)
> 
> @adiwajshing Is it possible now Can?

See this new protobuf #590 
You can just generate it using [pbjs](https://www.npmjs.com/package/protobufjs)
