### ISSUE TITLE
Can't Login After QR

### ISSUE THREAD

**Issue by minanseo** [adiwajshing/Baileys#1460]
I've scanned the QR, but still can't login. Since updating the WhatsApp application.
Like the image below
Can you help me?

![qr again](https://user-images.githubusercontent.com/59535259/161955773-9725f8f8-416d-40a3-a421-3561f7eccfc4.png)

**Comment by radhin123** [comment]
try deleting the session and re-scan.

**Comment by minanseo** [comment]
> 

which folder is the code in?
