### ISSUE TITLE
When Sending Pdf/ Excel File Preview is not as we get in phone [BUG]

### ISSUE THREAD

**Issue by kaniket7209** [adiwajshing/Baileys#1462]
While Sending the pdf/excel file I am not getting the preview as i need and in Message.ts file also there is no optoin/ add on to add anything .. Please help me out to find solution to this as I want to send the preview as we get in phone/Check this
Message.ts File/
 & WithDimensions) | ({
        document: WAMediaUpload
        mimetype: string
        fileName?: string

**Comment by RPT001** [comment]
> While Sending the pdf/excel file I am not getting the preview as i need and in Message.ts file also there is no optoin/ add on to add anything .. Please help me out to find solution to this as I want to send the preview as we get in phone/Check this Message.ts File/ & WithDimensions) | ({ document: WAMediaUpload mimetype: string fileName?: string

 ### ✔Solution:

> While sending the pdf file, please check the mimetype is correct or not, the correct mimetype for pdf is 'application/pdf' and for word document is 'application/doc'. In your case it must be 'application/undefined'

**Comment by kaniket7209** [comment]
Still unable to solve that and also it is not opening on Android .. Only opening on Windows
