### ISSUE TITLE
About migrate from v3 to v4

### ISSUE THREAD

**Issue by mi-khatri** [adiwajshing/Baileys#1467]
hello everyone,

i am working with bailey very well from long time.
but when Multi Device update received. i want to switch on Baileys-MD.
But the documentation for Baileys-MD is very difficult for me, because i work only in JavaScript not in typescript.

please any one provide code for switch from v3 to v4 in simple JavaScript code.

please help

-Thanks in advance

**Comment by HanzCEO** [comment]
Hello, i want to introduce you my Baileys multi-device library wrapper. Called `fabuya`.

It's new but i hope you can try it out,
more on that [here](https://github.com/HanzHaxors/fabuya)

Published as npm package too, also, Baileys version will always be followed when required
> Hanz
