### ISSUE TITLE
[BUG] - Get someone's presence always returning undefined

### ISSUE THREAD

**Issue by wagnerfillio** [adiwajshing/Baileys#1469]
**Describe the bug**
Get someone's presence always returning undefined

**To Reproduce**
1. Created a new connection
2. Log in to example.ts
3. Subscribe to the presence status update `await sock.presenceSubscribe("xyz@s.whatsapp.net") `

**Expected behavior**
To get someone's presence (if they're typing, online)

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? Example.ts
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by HanzCEO** [comment]
https://wabetainfo.com/whatsapp-is-enabling-new-privacy-measures-to-protect-users/
