### ISSUE TITLE
[BUG] QR code not showing

### ISSUE THREAD

**Issue by dcode-denpa** [adiwajshing/Baileys#1470]
![Screenshot_2022-04-09-17-59-05-103_com termux](https://user-images.githubusercontent.com/76629978/162575238-8ac9bb6c-8a90-4db3-aed9-406d0850fb6d.jpg)

**Comment by Fabrizz** [comment]
> Install qrcode-terminal using yarn add qrcode-terminal to auto-print the QR to the terminal.

**Comment by Kikii-XyZ** [comment]
> > Install qrcode-terminal using yarn add qrcode-terminal to auto-print the QR to the terminal.
> 
> also set `printQRInTerminal: true`
> 
> ```
> async function connectToWhatsApp () {
>     const sock = makeWASocket({
>         // can provide additional config here
>         printQRInTerminal: true
>     })
> ...
> ```
it's not working bro

**Comment by AkirahX** [comment]
Install this: https://www.npmjs.com/package/qrcode-terminal
