### ISSUE TITLE
[BUG] Getting this error

### ISSUE THREAD

**Issue by Cosmic-Bug** [adiwajshing/Baileys#1471]
(node:57) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 connection-phone-change listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit

**Comment by claudio-evocorp** [comment]
> (node:57) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 connection-phone-change listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit

**Comment by Cosmic-Bug** [comment]
> > (node:57) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 connection-phone-change listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit

Bro do you know how to resolve this error?
