### ISSUE TITLE
[BUG] Credential file grows up until to corrupt

### ISSUE THREAD

**Issue by paulocorcino** [adiwajshing/Baileys#1475]
**Describe the bug**
The file that storage credential corrupted after 1 week, it grows up until a file with 6 mb. 
How happened this?

```
======= 2022-04-10 17:30:08: SyntaxError: Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at useSingleFileAuthState (/home/openwa/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:125:29)
````

I don't know what I need to write why my instances work normally, but I'm very unconfident that this file return to grows up. This is normal? Or I should to do a workaround? How to save original file and replace after each reboot?

**Comment by diezeldev** [comment]
https://github.com/adiwajshing/Baileys/pull/1404

Hi use this. I don’t understand why he did not merge yet

**Comment by HanzCEO** [comment]
![image](https://user-images.githubusercontent.com/40712686/163084241-4e9f5fbc-8179-4813-8af6-69fe205dcc6b.png)

And this has been discussed on Discord too
