### ISSUE TITLE
[BUG] Send message to group error 500

### ISSUE THREAD

**Issue by bigbangshop** [adiwajshing/Baileys#1479]
I'm having problems sending group messages with the new jid format

Send error details

sendMessage {
  id: '120363023020874239@g.us',
  data: { text: '*Anna - Big Shop Moda:*\n54654654' }
}
Caught exception: Error: item-not-found
    at assertNodeErrorFree (/var/www/bll/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:294:15)
    at query (/var/www/bll/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:138:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async groupMetadata (/var/www/bll/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:24)
    at async /var/www/bll/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:250:41
    at async Promise.all (index 0)
    at async /var/www/bll/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:246:51
    at async Object.transaction (/var/www/bll/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:78:21)
    at async relayMessage (/var/www/bll/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:243:9)
    at async Object.sendMessage (/var/www/bll/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:395:17) {
  data: 404,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} unhandledRejection

**Comment by AkirahX** [comment]
This is your code?:
```javascript

sendMessage {
id: '120363023020874239@g.us',
data: { text: 'Anna - Big Shop Moda:\n54654654' }
}

```

**Comment by bigbangshop** [comment]
Yes... more correct example

WPP.sendMessage('120363023020874239@g.us', { text: 'Anna - Big Shop Moda:\n54654654' });

**Comment by bigbangshop** [comment]
Old group format and users are ok!

the function  WPP.onWhatsApp('120363023020874239@g.us') not work too. return []

**Comment by rafosolima** [comment]
I'm having the same problem onWhatsApp returns nothing when I enter a group id

**Comment by pandigresik** [comment]
> Yes... more correct example
> 
> WPP.sendMessage('[120363023020874239@g.us](mailto:120363023020874239@g.us)', { text: 'Anna - Big Shop Moda:\n54654654' });

try this solution

**Comment by igortrust** [comment]
same error here. If the idGroup doesn't have a "-", the lib keeps searching until it times out. This didn't happen before, I noticed the error this week

Error: Timed Out
    at /home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32 {
  data: {
    stack: 'Error: \n' +
      '    at Object.promiseTimeout (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:173:19)\n' +
      '    at waitForMessage (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:117:42)\n' +
      '    at query (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:140:22)\n' +
      '    at groupQuery (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:10:55)\n' +
      '    at groupMetadata (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:20:30)\n' +
      '    at /home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:267:47\n' +
      '    at /home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:270:23\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at Object.transaction (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:78:21)\n' +
      '    at relayMessage (/home/oem/Projetos/md/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:260:9)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

**Comment by igortrust** [comment]
> > Yes... more correct example
> > WPP.sendMessage('[120363023020874239@g.us](mailto:120363023020874239@g.us)', { text: 'Anna - Big Shop Moda:\n54654654' });
> 
> try this solution

it didn't work here :(

**Comment by ahmadkeren** [comment]
any solution?
sometime the message can send to the groups, but sometime that can't..

**Comment by paulohsilvestre** [comment]
did anyone manage to solve this problem? I'm having the same problem, some phones work normally others don't send

**Comment by paulohsilvestre** [comment]
> did anyone manage to solve this problem? I'm having the same problem, some phones work normally others don't send

I managed to solve my problem, when downloading the group id it downloaded and recorded the id only with numbers without the hyphen and some groups had the formatting or 554699999999-000000000 when sending a message it did not find the ID and gave time-out, then I corrected the groups and started sending correctly

**Comment by paulohsilvestre** [comment]
> > > did anyone manage to solve this problem? I'm having the same problem, some phones work normally others don't send
> > 
> > 
> > I managed to solve my problem, when downloading the group id it downloaded and recorded the id only with numbers without the hyphen and some groups had the formatting or 554699999999-000000000 when sending a message it did not find the ID and gave time-out, then I corrected the groups and started sending correctly
> 
> Do you have a example?

I imagine it's easier for me to help you in the process, because my structure differs from yours, what I did I debugged the process of receiving the message, and I validated the remoteJid and saw that it came with "-" in the remoteJid but it recorded erroneously in my database there at the time of sending the message did not have the "-" in the ID and it generated the error because sendMessage could not find the group ID
