### ISSUE TITLE
Empty buttons in iphone

### ISSUE THREAD

**Issue by cduarte** [adiwajshing/Baileys#1484]
Hi

I tested send buttons using the examples 
But I received in the iphone more buttons than specify in the json and that buttons is empty.

In whatsapp web is ok always.

The problem is only in the iphone:
- when send only buttons type "quickReplyButton" can send one or more and every time is OK!
- when send only buttons urlButton/callButton is Ok.

PROBLEM: 

- when use at same message type **quickReplyButton** and **urlButton/callButton**, so mix the type of buttons the problem occurs: show empty buttons

- For each button type urlButton/callButton is show one empty button when send at the same message the 

![a](https://user-images.githubusercontent.com/810062/163058959-40ebe441-02ad-4ce4-a4ec-915f2ade9d96.jpeg)
![b](https://user-images.githubusercontent.com/810062/163058962-58249f94-4bac-467f-b57e-c43259770487.jpeg)

**Comment by bayuterra** [comment]
same me to

**Comment by adinyahya** [comment]
what version of bailesy are you using?

**Comment by leenasn** [comment]
Any updates on this? I am also facing this issue.

**Comment by pedroherpeto** [comment]
same here!

**Comment by Fibonacci-Solucoes-Ageis** [comment]
same here!
