### ISSUE TITLE
Bailey Errors TypeError: Cannot read properties of undefined (reading 'toString')     at _0x4b7a50.base64EncodedAuthInfo

### ISSUE THREAD

**Issue by Nanatturnip** [adiwajshing/Baileys#1489]
![image](https://user-images.githubusercontent.com/80870215/163300673-f69a77df-cbdf-4a4b-abd1-5af596db1fe1.png)
Can you please help me, i dont know why this happened.

**Comment by ashish1500616** [comment]
Hi @Nanatturnip,

Please pass the **version** property to the makeWASocket and see if it works for you.

Version : 2, 2204, 13 is working for me.

```
const sock = makeWASocket({
		logger: P({ level: 'trace' }),
		printQRInTerminal: true,
		**version: [2, 2204, 13],**
		// implement to handle retries
		getMessage: async key => {
			return {
				conversation: 'hello'
			}
		}
	})
```
