### ISSUE TITLE
MD help me:/

### ISSUE THREAD

**Issue by KunzxD404** [adiwajshing/Baileys#1490]
Error get_result is not iterable

My code :
anu = await fetchJson(`tes`)
get_result = anu.result
let txt = `${q}\n\n`
for (var x of get_result){
txt += `*Testing* : ${x.title}\n`
}

**Comment by w3nder** [comment]
Your problem has nothing to do with the lib.
It's not a Baileys bug

Your problem is here.
`
anu = await fetchJson(tes)
get_result = anu.result
`

**Comment by KunzxD404** [comment]
> Your problem has nothing to do with the lib. It's not a Baileys bug
> 
> Your problem is here. `anu = await fetchJson(tes) get_result = anu.result`

what's the problem i use this as well in other parts but some don't get an error?

**Comment by AiceGate** [comment]
> 

why do you say this is a bug??
do you understand the code that you have typed?

You need help. but you said this is Bug.

**Comment by KunzxD404** [comment]
> > 
> 
> kenapa ane bilang ini bug?? Apakah Anda memahami kode yang Anda ketik?
> 
> Anda membutuhkan bantuan. tapi kamu bilang ini Bug.

Sorry😕

**Comment by AiceGate** [comment]
> > > 
> > 
> > 
> > kenapa ane bilang ini bug?? Apakah Anda memahami kode yang Anda ketik?
> > Anda membutuhkan bantuan. tapi kamu bilang ini Bug.
> 
> Sorry😕

if it's not related to bugs or requests. 
"Open a blank issue" not "Bug Issue"

**Comment by SheIITear** [comment]
This isn't related to baileys in anyway. The only reason why you're getting the error is because your code is wrong.
I'd suggest learning at least basics of javascript or typescript before hopping into some libraries.

**Comment by KunzxD404** [comment]
> Ini sama sekali tidak berhubungan dengan bailey. Satu-satunya alasan mengapa Anda mendapatkan kesalahan adalah karena kode Anda salah. Saya sarankan mempelajari setidaknya dasar-dasar javascript atau TypeScript sebelum melompat ke beberapa perpustakaan.

Ok:/
