### ISSUE TITLE
[BUG] Issue in sending message to multiple Participants 

### ISSUE THREAD

**Issue by adgamerx** [adiwajshing/Baileys#1491]
I'm getting this issue when I try to send message to multiple group

`trace":"Error: not-acceptable\n    at Object.assertNodeErrorFree (/app/node_modules/@adiwajshing/baileys/lib/WABinary/index.js:290:15)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:144:24)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async assertSessions (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:202:28)\n    at async sendMessagesAgain (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:229:9)\n    at async /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:295:25","msg":"error in sending message again"}`

**Environment (please complete the following information):**
 - Is this on a server? - On heroku
 - What do your `connectOptions` look like? 
`const { version } = await (0, baileys_1.fetchLatestBaileysVersion)();
    const sock = (0, baileys_1.default)({
        version,
        printQRInTerminal: true,
        auth: state,
        getMessage: async (key) => {
            return {
                conversation: 'hello'
            };
        }
    });`
 - Do you have multiple clients on the same IP? - No
 - Are you using a proxy? - No

**Comment by enoksaju** [comment]
+1
