### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by wahyuuhidayah** [adiwajshing/Baileys#1494]
what if I want to send a button and a pdf?

**Comment by AiceGate** [comment]
I've read.

**Comment by aidulcandra** [comment]
`// send a buttons message!
const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
  {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
]

const buttonMessage = {
    text: "Hi it's button message",
    footer: 'Hello World',
    buttons: buttons,
    headerType: 1
}

const sendMsg = await sock.sendMessage(id, buttonMessage)`
