### ISSUE TITLE
All accounts get banned after sending messages

### ISSUE THREAD

**Issue by khongten001** [adiwajshing/Baileys#1496]
Hi,

All my accounts get banned after sending messages from the code of this repository! 
@adiwajshing is there any way to log all income/outcome data then send you for narrowing the issue?

THanks

**Comment by LuanRT** [comment]
Not really a bug.
You'll eventually get banned if you send too many messages right after logging in or if you use a virtual number, it's inevitable. Try warming up the account first so only then you can use it.

**Comment by AiceGate** [comment]
this is not a bug, 
Your account was banned not because of this repository.
I'm using more than 5 numbers and it's been more than 3 months. no one got banned.

**Comment by Fabrizz** [comment]
Just don't spam people and only contact people that have already sent you a message or that you have on your contact list, also do as @LuanRT says, use the account for a bit, then connect the bot.

**Comment by khongten001** [comment]
Thank you for all information! I have some contacts in my accounts, they also sent some messages to my Whatsapp numbers but they still get banned. I'm trying to narrow down the issue so I can send information to @adiwajshing 

I updated the title to lower case!
