### ISSUE TITLE
[Feature][MD] loadMessage and mostRecentMessage without store

### ISSUE THREAD

**Issue by workgroupengineering** [adiwajshing/Baileys#1497]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

Allow using loadMessage and mostRecentMessage from socket without using store.

**Comment by ycarooliveira** [comment]
At the moment isnt possible, the whatsapp/facebook  designed MD so you SHOULD save everything from the moment you scan the QRcode till you logs out. The only way to get messages is to retrieve from where you saved them
