### ISSUE TITLE
Is it possible not to receive the new message event?

### ISSUE THREAD

**Issue by cassiano-guardianserver** [adiwajshing/Baileys#150]
I have a phone connected and I can usually receive messages from one phone, but when I send another phone, the messages do not arrive at the event, only on the cell phone.
This connected phone is a business account, I was unable to simulate it on other accounts.
I didn't catch any error or exception messages, I'm using the commit version ea36aabb6ca9c3abe47849a91421885f081ba339

**Comment by adiwajshing** [comment]
Could you try using the latest commit or `v3.1.0`?

**Comment by cassiano-guardianserver** [comment]
Problem solved, thank you!

**Comment by cassiano-guardianserver** [comment]
Close.
