### ISSUE TITLE
How to get contact profile name.

### ISSUE THREAD

**Issue by vishwajit76** [adiwajshing/Baileys#1500]
No option found to get profile name of contact number.

**Comment by pedroayres** [comment]
Up

**Comment by aidulcandra** [comment]
In what event do you want to get the profile name? Also do you mean the display name or the name that is saved in your contact?

**Comment by pedroayres** [comment]
On messages upsert

**Comment by aidulcandra** [comment]
> On messages upsert

You can use `pushName` to get the display name.

**Comment by hardianto-cpu** [comment]
> 

mybe get name by number
