### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#1503]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

Hello, I'm new to this library. I've been using whatsapp-web.js by pedrolopez and running it on Heroku, but it doesn't support Heroku anymore due to whatsapp multi-device. (all session data are saved in the filesystem and since Heroku's filesystem is ephemeral, the data is always deleted each time the dyno starts)

Does this library face the same issue? Does it still work fine? I'm planning to use it

**Comment by ashish1500616** [comment]
Hi @aidulcandra , I have tried Baileys with both legacy and multi-user support. 

Working good for me.

So I would suggest to play around and see if it fits your use case.

**Comment by adinyahya** [comment]
@ashish1500616 can you help me, i want to change my projecy from legacy to multidevice

**Comment by ashish1500616** [comment]
@adinyahya  Yeah Sure, Please raise your issues.
