### ISSUE TITLE
what is messageStubType: 39

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#151]
This strange message is getting received and i cannot discover what it represents.
```
WebMessageInfo {
  messageStubParameters: [],
  labels: [],
  key: MessageKey {
    remoteJid: 'OMITTED@s.whatsapp.net',
    fromMe: true,
    id: 'EE943F72B94F662D1EF33C2660A56270'
  },
  messageTimestamp: Long { low: 1599840659, high: 0, unsigned: true },
  messageStubType: 39
}
```

**Comment by sthales** [comment]
"Message you send to this chat and calls are now secured with end-to-end encryption. Tap for more info."

**Comment by algoz098** [comment]
I have saw the E2E_Encrypted message, do we have two events to it ?

**Comment by sthales** [comment]
Afaik there's only one

**Comment by algoz098** [comment]
I see, i was looking into a part of the message. I'm sorry.
