### ISSUE TITLE
Generate QR Super Laggy After 10 - 30 Minutes Running

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#1514]
Hello everyone, so I have a server with 4 cores and 8gb ram, I use this lib + fastify as a web service, the first time the service runs everything is fine qr appears quickly + fastify is very responsive, but after 30 connection numbers, the qr request process becomes sluggish + fastify becomes very laggy, after that not long an error appears like this.

{"level":30,"time":1650438680277,"pid":1355099,"hostname":"devserver.sg","reqId":"req-1t1","res":{"statusCode":400} ,"err":{"type":"Error","message":"aborted","stack":"Error: aborted\n at connResetException (node:internal/errors:691:14)\n at abortIncoming ( node:_http_server:596:17)\n at socketOnClose (node:_http_server:590:3)\n at Socket.emit (node:events:402:35)\n at TCP.<anonymous> (node:net:687 :12)","code":"ECONNRESET","statusCode":400},"msg":"aborted"}

is there a possibility that the whatsapp server rate-limit has been hit?

**Comment by ander890** [comment]
Same problem here, maybe bcs auth storage system using json file & causing i/o failure to read / write session data

alternatively you can try go version library using postgresql. Its very stable version i’ve tried rn for multiple session

**Comment by makanSukros** [comment]
> Same problem here, maybe bcs auth storage system using json file , its causing high cpu usage & i/o failure to read / write session data
> 
> alternatively you can try go version library using postgresql. Its very stable version i’ve tried rn for multiple session

did you experience socket hang up too when using this lib?

**Comment by ander890** [comment]
> > Same problem here, maybe bcs auth storage system using json file , its causing high cpu usage & i/o failure to read / write session data
> > alternatively you can try go version library using postgresql. Its very stable version i’ve tried rn for multiple session
> 
> did you experience socket hang up too when using this lib?

yes, already connected session getting many 1006 socket error and trap in recconect loop (close and start again every ~2 minutes)

**Comment by makanSukros** [comment]
Any suggestions @makanSukros

**Comment by makanSukros** [comment]
> > > Same problem here, maybe bcs auth storage system using json file , its causing high cpu usage & i/o failure to read / write session data
> > > alternatively you can try go version library using postgresql. Its very stable version i’ve tried rn for multiple session
> > 
> > 
> > did you experience socket hang up too when using this lib?
> 
> yes, already connected session getting many 1006 socket error and trap in reconect loop (close and start again every ~2 minutes)

I've tried to change using express js, it's the same, but if there's no number that connects to generate 100 qr at the same time, it's fine and smooth, I'm really confused

**Comment by ander890** [comment]
> > > > Same problem here, maybe bcs auth storage system using json file , its causing high cpu usage & i/o failure to read / write session data
> > > > alternatively you can try go version library using postgresql. Its very stable version i’ve tried rn for multiple session
> > > 
> > > 
> > > did you experience socket hang up too when using this lib?
> > 
> > 
> > yes, already connected session getting many 1006 socket error and trap in reconect loop (close and start again every ~2 minutes)
> 
> I've tried to change using express js, it's the same, but if there's no number that connects to generate 100 qr at the same time, it's fine and smooth, I'm really confused

Im using express too, it doesn't matter if you using fastify or express. The error happen if you connect many numbers (> 10), according to what i said earlier maybe bcs auth file system is using json, so maybe you can try dbms like postgresql instead singleFileAuthState

**Comment by ander890** [comment]
I've never implemented it with baileys before, alternatively you can try and/or learn from go implementation library (tulir/whatsmeow) which supports postgre natively

**Comment by makanSukros** [comment]
> I've never implemented it with baileys before, alternatively you can try and/or learn from go implementation library (tulir/whatsmeow) which supports postgre natively

Solved after im save credentials on db

**Comment by tmandinyenya** [comment]
@makanSukros Kindly share how you have solved it.

I have tried 

`export const useSingleAuthState = (instance: any, logger?: Logger): { state: AuthenticationState, saveState: () => void } => {
	let creds: AuthenticationCreds
	let keys: any = { }
	

	// save the authentication state to mongoDB
	const saveState = async () => {
		logger && logger.trace('saving auth state');

		await WhatsappInstance.findOneAndUpdate(
			{ _id: instance.id },
			{"authStateFull" : JSON.stringify({ creds, keys }, BufferJSON.replacer, 2)},
			{ new: true }
		);
	}

	if(instance && instance.authStateFull) {
		const result = JSON.parse(
			instance.authStateFull,
			BufferJSON.reviver
		)

		creds = result.creds
		keys = result.keys
	} else {
		creds = initAuthCreds()
		keys = { }
	}

	return {
		state: {
			creds,
			keys: {
				get: (type, ids) => {
					const key = KEY_MAP[type]
					return ids.reduce(
						(dict, id) => {
							let value = keys[key]?.[id]
							if(value) {
								if(type === 'app-state-sync-key') {
									value = proto.AppStateSyncKeyData.fromObject(value)
								}

								dict[id] = value
							}

							return dict
						}, { }
					)
				},
				set: (data) => {
					for(const _key in data) {
						const key = KEY_MAP[_key as keyof SignalDataTypeMap]
						keys[key] = keys[key] || { }
						Object.assign(keys[key], data[_key])
					}

					saveState()
				}
			}
		},
		saveState
	}
}` 

Using this is looping on Qr scan multiple times then fail with connection error.
