### ISSUE TITLE
Get Previously Unread Messages

### ISSUE THREAD

**Issue by j4v4soft** [adiwajshing/Baileys#1518]
how to load previously Unread Messages ?

**Comment by aidulcandra** [comment]
I think you should use the event `"messages.set"` to catch all the message history and store it somewhere. The documentation has a way to store data. Maybe you should check that out. That being said, you have to start a new empty state so that the `messages.set` event can fire again when it's syncing the message history.

**Comment by j4v4soft** [comment]
> 
no, I mean how to pull incoming and unread messages when the bot is offline

**Comment by burstfreeze** [comment]
There are `append` and `offline` types in the events. The latter is what you are looking for.

**Comment by j4v4soft** [comment]
> There are `append` and `offline` types in the events. The latter is what you are looking for.

i want to process offline messages when the bot is run. but don't know how
![unread_messsages_wa](https://user-images.githubusercontent.com/15384594/164915678-83053762-8c10-45d0-89f3-89ad7166fdcc.png)

**Comment by burstfreeze** [comment]
`if(m.type == 'offline')`

**Comment by aidulcandra** [comment]
```
sock.ev.on('messages.upsert', m => {
   if (m.type === 'append') {
       for (let i of m.messages) {
           // your code here. each message object is represented by i
       }
   }
})
```

**Comment by j4v4soft** [comment]
> ```
> sock.ev.on('messages.upsert', m => {
>    if (m.type === 'append') {
>        for (let i of m.messages) {
>            // your code here. each message object is represented by i
>        }
>    }
> })
> ```

in my case, unread messages (offline) are not shown in this event :'(

**Comment by gbenmelej** [comment]
Hi
This is how it works for me:
`
sock.ev.on('chats.set', async ({ chats }) => { 
		for(let key in chats){
			if(chats[key]['unreadCount'] > 0){
				await sock.sendMessage(chats[key]['id'],{text: "Replying unread messages  😃"});
				await delay(2000);
			}
		}
	})
`

**Comment by j4v4soft** [comment]
> Hi This is how it works for me:
> 
> ```
> sock.ev.on('chats.set', async ({ chats }) => { 
> 		for(let key in chats){
> 			if(chats[key]['unreadCount'] > 0){
> 				await sock.sendMessage(chats[key]['id'],{text: "Replying unread messages  😃"});
> 				await delay(2000);
> 			}
> 		}
> 	})
> ```
> 
> This event is executed by scanning the QR code

thank for y'r reply, but when executed scanning the QR its says 0 unread message :'(
