### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by hernanpatronc** [adiwajshing/Baileys#1521]
Upgrading from Baileys v.3.x to v.4.x I don't receive anymore push notifications on my phone, iPhone but also Android.
If I'm connected also on WhatsApp Desktop I can receive desktop notification, but never on the phone.

Same here...
@adiwajshing You can re-open this issue?

_Originally posted by @mtAlves in https://github.com/adiwajshing/Baileys/issues/1359#issuecomment-1082669867_

**Comment by PurpShell** [comment]
bump

**Comment by iM0hamed** [comment]
bump

**Comment by PurpShell** [comment]
Lol it got closed

**Comment by azudindaem** [comment]
We can markOnlineOnConnect = false. Only problem with business

```js
         const sock = makeWASocket({
            markOnlineOnConnect: false
        })
```
