### ISSUE TITLE
Identifying the recipient in messages.upsert

### ISSUE THREAD

**Issue by leenasn** [adiwajshing/Baileys#1522]
Hi,

I am connecting multiple WhatsApp numbers and I would like to know how can I identify the recipient in upsert i.e how to identify to which WhatsApp number the message was sent? 

I could see fromMe as true or false but couldn't find any recipient details in the upsert 

Thank you,
Leena

**Comment by aidulcandra** [comment]
It's in `remoteJid` property

**Comment by ravindu01manoj** [comment]
> Hi,
> 
> I am connecting multiple WhatsApp numbers and I would like to know how can I identify the recipient in upsert i.e how to identify to which WhatsApp number the message was sent?
> 
> I could see fromMe as true or false but couldn't find any recipient details in the upsert
> 
> Thank you, Leena

```js
 var sender_jid = m.messages[0].key.participant || m.messages[0].key.remoteJid
````
