### ISSUE TITLE
[BUG]Error after scan

### ISSUE THREAD

**Issue by faagas** [adiwajshing/Baileys#1524]
![Screenshot_2022-04-21-16-39-43-502_com termux](https://user-images.githubusercontent.com/80428711/164702311-342dc7e1-e6f0-46dc-80e9-0dd1e0aa1368.jpg)

Previously my bot had no problems like this, but recently this happened.  Please help me to solve this bug :')

**Comment by ashish1500616** [comment]
@faagas Update node to the latest version and retry.

**Comment by aidulcandra** [comment]
Legacy / Multi device?

**Comment by AkirahX** [comment]
Baileys doesn't work properly in Termux, this error is related to it.
