### ISSUE TITLE
Error upgrade v4 Baileys Multi Device [BUG]

### ISSUE THREAD

**Issue by adinyahya** [adiwajshing/Baileys#1525]
I'm having an error when upgrading from v3 baileys to v4 Multi device, does anyone know the solution?
<img width="700" alt="Screen Shot 2022-04-22 at 23 27 50" src="https://user-images.githubusercontent.com/29035241/164756283-97a4ad0a-5d34-4e26-8c00-76fb2e951571.png">

**Comment by binsarjr** [comment]
please check [here](https://github.com/adiwajshing/Baileys#notable-differences-between-baileys-v3--v4) its not bug from baileys.don't carelessly give bug labels.

codebase v3 and v4 has changed.read example code again for v4

**Comment by aidulcandra** [comment]
I think you should look into where the error raised, it's maybe from your code that needs to be updated to suit the new version of the library
