### ISSUE TITLE
[BUG][NORMAL] Buttons not working when clicked.

### ISSUE THREAD

**Issue by abhi-76** [adiwajshing/Baileys#1526]
I'm using normal baileys ( 3.5.3 ) and when I click buttons it won't work, But Button id is a command. That should be worked when clicked. Help me please.

**Comment by aidulcandra** [comment]
Maybe you should put the command not as the id, but the display text

**Comment by abhi-76** [comment]
> Maybe you should put the command not as the id, but the display text

I tried but not working

**Comment by AkirahX** [comment]
Create an algorithm to handle button responses, just setting "commands" will not work.

**Comment by Wkdiuzgahwoeidvxb1** [comment]
> Create an algorithm to handle button responses, just setting "commands" will not work.

How to create an algorithm can you give me example? I'm too facing this.

**Comment by LuanRT** [comment]
It is fairly simple to implement a button response handler. For those who are lost, you should probably start analyzing and paying more attention to the responses Baileys gives you when clicking a button, etc or anything. It's not rocket science.
