### ISSUE TITLE
How to change agent name?

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#1529]
I'm using Multi Device and sometimes I wanna log out from specific device but I get confused because the names are the same **(Google Chrome (Baileys)** and the last time active have only slight difference.

Is there any way to change how it is displayed?

**Comment by adinyahya** [comment]
const conn = makeWASocket({
            printQRInTerminal: true,
            logger: logg({ level: 'fatal' }),
            auth: state,
            browser: ["WhatsRice Multi Device", "MacOS", "3.0"]
        })
        
browser: ["WhatsRice Multi Device", "MacOS", "3.0"] -> change this


 you can start it by changing "browser" attribute in the connection
