### ISSUE TITLE
Weird bug while sending a group message 

### ISSUE THREAD

**Issue by talhabalaj** [adiwajshing/Baileys#153]
Hello, 
I hope you are doing well. I have discovered a weird bug while sending group messages using Baileys. The messages are sent but are not received on the other end. Super weird. If I see my phone with which I'm using Baileys, The messages are sent. But cannot be seen by any other participants of the group. 

I don't know what is going on tho. 
Can you help me out?

Thank you so much!

Side note: Didn't happen before, must be some update to WA Web.

**Comment by adiwajshing** [comment]
The entire group test suite is passing. If you show me some code, might be able to help

**Comment by talhabalaj** [comment]
Actually, I figured something out. This problem is not with baileys, I guess. It persists with using WhatsApp on the phone as well.
