### ISSUE TITLE
[BUG] [MD] Baileys very slow to receive and send message

### ISSUE THREAD

**Issue by paulocorcino** [adiwajshing/Baileys#1532]
I see Baileys MD work with slowly, if  you compare with v3 is strong diff between they. I have an account with more 3000 contacts and more than 500 sessions per day, the first problems are quantity message notification that service receive, are thousands notifications.

This is a sample.

```
{"level":20,"time":1650785809533,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579****@s.whatsapp.net","type":"picture","id":"1593211224","notify":"Ednilde","t":"1650785808"},"sent":{"id":"1593211224","to":"557921****@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
{"level":20,"time":1650785330876,"pid":1891,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579*******@s.whatsapp.net","type":"picture","id":"32421461","notify":"Edjina 🙏👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧🙌🙌","t":"1650785330"},"sent":{"id":"32421461","to":"5579*******@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
{"level":30,"time":1650785958671,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","msgAttrs":{"from":"status@broadcast","type":"text","edit":"7","id":"202894B622A4BAA087301BC91F234D2F","participant":"5579******@s.whatsapp.net","t":"1650785958","notify":"Thiagomergulhador🌊🏄🏽"},"retryCount":1,"msg":"sent retry receipt"}
```
I did an analysis and see that module consume much CPU saveState, and this file grows up, now my file has more 100mb.

![image](https://user-images.githubusercontent.com/7800501/164966873-24173d63-dfe8-4e5d-b681-e7d499911f4b.png)

CPU consumption
saveState 15% (accumulate after 3 times with 5%, so each time save consume 5%)
useSingleFileAuthState 13%
writevGeneric 6%

If you open the file with state, you will see much information with status@broadcast, I don't know if this information is important to persist on file, are thousands lines with this information.

```
 "status@broadcast::5579*********:0": [
        {
          "senderKeyId": 387750434,
          "senderChainKey": {
            "iteration": 0,
            "seed": "ui3qMfxWHAzM7rcLnJVpO7TEE+5FmKRkk7V4MWQAWrI="
          },
          "senderSigningKey": {
            "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
          },
          "senderMessageKeys": []
        },
        {
          "senderKeyId": 387750434,
          "senderChainKey": {
            "iteration": 2,
            "seed": "7veQ2w4T0c2tq9gGA2gSLxsBjASG/AudCuG+1dL6eQo="
          },
          "senderSigningKey": {
            "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
          },
          "senderMessageKeys": []
        },
        {
          "senderKeyId": 387750434,
          "senderChainKey": {
            "iteration": 3,
            "seed": "DPcRNX7aqmvnTSvDy9VE5t8J6d2Vh1iRhW3nutB8Dmk="
          },
          "senderSigningKey": {
            "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
          }
        }
      ],
```

@adiwajshing, I would like only to show a point I understand  need more attention, I don't know if I did something wrong, normally use default configuration and connect normally, however when an account has many contacts these difficulties happens.

You do a fantastic work and many people need to be grateful and send bless every day for you. 
Thank you, for all!

**Comment by makanSukros** [comment]
> I see Baileys MD work with slowly, if you compare with v3 is strong diff between they. I have an account with more 3000 contacts and more than 500 sessions per day, the first problems are quantity message notification that service receive, are thousands notifications.
> 
> This is a sample.
> 
> ```
> {"level":20,"time":1650785809533,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579****@s.whatsapp.net","type":"picture","id":"1593211224","notify":"Ednilde","t":"1650785808"},"sent":{"id":"1593211224","to":"557921****@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
> {"level":20,"time":1650785330876,"pid":1891,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579*******@s.whatsapp.net","type":"picture","id":"32421461","notify":"Edjina 🙏👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧🙌🙌","t":"1650785330"},"sent":{"id":"32421461","to":"5579*******@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
> {"level":30,"time":1650785958671,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","msgAttrs":{"from":"status@broadcast","type":"text","edit":"7","id":"202894B622A4BAA087301BC91F234D2F","participant":"5579******@s.whatsapp.net","t":"1650785958","notify":"Thiagomergulhador🌊🏄🏽"},"retryCount":1,"msg":"sent retry receipt"}
> ```
> 
> I did an analysis and see that module consume much CPU saveState, and this file grows up, now my file has more 100mb.
> 
> ![image](https://user-images.githubusercontent.com/7800501/164966873-24173d63-dfe8-4e5d-b681-e7d499911f4b.png)
> 
> CPU consumption saveState 15% (accumulate after 3 times with 5%, so each time save consume 5%) useSingleFileAuthState 13% writevGeneric 6%
> 
> If you open the file with state, you will see much information with status@broadcast, I don't know if this information is important to persist on file, are thousands lines with this information.
> 
> ```
>  "status@broadcast::5579*********:0": [
>         {
>           "senderKeyId": 387750434,
>           "senderChainKey": {
>             "iteration": 0,
>             "seed": "ui3qMfxWHAzM7rcLnJVpO7TEE+5FmKRkk7V4MWQAWrI="
>           },
>           "senderSigningKey": {
>             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
>           },
>           "senderMessageKeys": []
>         },
>         {
>           "senderKeyId": 387750434,
>           "senderChainKey": {
>             "iteration": 2,
>             "seed": "7veQ2w4T0c2tq9gGA2gSLxsBjASG/AudCuG+1dL6eQo="
>           },
>           "senderSigningKey": {
>             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
>           },
>           "senderMessageKeys": []
>         },
>         {
>           "senderKeyId": 387750434,
>           "senderChainKey": {
>             "iteration": 3,
>             "seed": "DPcRNX7aqmvnTSvDy9VE5t8J6d2Vh1iRhW3nutB8Dmk="
>           },
>           "senderSigningKey": {
>             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
>           }
>         }
>       ],
> ```
> 
> @adiwajshing, I would like only to show a point I understand need more attention, I don't know if I did something wrong, normally use default configuration and connect normally, however when an account has many contacts these difficulties happens.
> 
> You do a fantastic work and many people need to be grateful and send bless every day for you. Thank you, for all!

Solution: make your own database to manage state

**Comment by tmandinyenya** [comment]
> > I see Baileys MD work with slowly, if you compare with v3 is strong diff between they. I have an account with more 3000 contacts and more than 500 sessions per day, the first problems are quantity message notification that service receive, are thousands notifications.
> > This is a sample.
> > ```
> > {"level":20,"time":1650785809533,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579****@s.whatsapp.net","type":"picture","id":"1593211224","notify":"Ednilde","t":"1650785808"},"sent":{"id":"1593211224","to":"557921****@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
> > {"level":20,"time":1650785330876,"pid":1891,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579*******@s.whatsapp.net","type":"picture","id":"32421461","notify":"Edjina 🙏👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧🙌🙌","t":"1650785330"},"sent":{"id":"32421461","to":"5579*******@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
> > {"level":30,"time":1650785958671,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","msgAttrs":{"from":"status@broadcast","type":"text","edit":"7","id":"202894B622A4BAA087301BC91F234D2F","participant":"5579******@s.whatsapp.net","t":"1650785958","notify":"Thiagomergulhador🌊🏄🏽"},"retryCount":1,"msg":"sent retry receipt"}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I did an analysis and see that module consume much CPU saveState, and this file grows up, now my file has more 100mb.
> > ![image](https://user-images.githubusercontent.com/7800501/164966873-24173d63-dfe8-4e5d-b681-e7d499911f4b.png)
> > CPU consumption saveState 15% (accumulate after 3 times with 5%, so each time save consume 5%) useSingleFileAuthState 13% writevGeneric 6%
> > If you open the file with state, you will see much information with status@broadcast, I don't know if this information is important to persist on file, are thousands lines with this information.
> > ```
> >  "status@broadcast::5579*********:0": [
> >         {
> >           "senderKeyId": 387750434,
> >           "senderChainKey": {
> >             "iteration": 0,
> >             "seed": "ui3qMfxWHAzM7rcLnJVpO7TEE+5FmKRkk7V4MWQAWrI="
> >           },
> >           "senderSigningKey": {
> >             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
> >           },
> >           "senderMessageKeys": []
> >         },
> >         {
> >           "senderKeyId": 387750434,
> >           "senderChainKey": {
> >             "iteration": 2,
> >             "seed": "7veQ2w4T0c2tq9gGA2gSLxsBjASG/AudCuG+1dL6eQo="
> >           },
> >           "senderSigningKey": {
> >             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
> >           },
> >           "senderMessageKeys": []
> >         },
> >         {
> >           "senderKeyId": 387750434,
> >           "senderChainKey": {
> >             "iteration": 3,
> >             "seed": "DPcRNX7aqmvnTSvDy9VE5t8J6d2Vh1iRhW3nutB8Dmk="
> >           },
> >           "senderSigningKey": {
> >             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
> >           }
> >         }
> >       ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @adiwajshing, I would like only to show a point I understand need more attention, I don't know if I did something wrong, normally use default configuration and connect normally, however when an account has many contacts these difficulties happens.
> > You do a fantastic work and many people need to be grateful and send bless every day for you. Thank you, for all!
> 
> Solution: make your own database to manage state

I have tried

`export const useSingleAuthState = (instance: any, logger?: Logger): { state: AuthenticationState, saveState: () => void } => {
let creds: AuthenticationCreds
let keys: any = { }

// save the authentication state to mongoDB
const saveState = async () => {
	logger && logger.trace('saving auth state');

	await WhatsappInstance.findOneAndUpdate(
		{ _id: instance.id },
		{"authStateFull" : JSON.stringify({ creds, keys }, BufferJSON.replacer, 2)},
		{ new: true }
	);
}

if(instance && instance.authStateFull) {
	const result = JSON.parse(
		instance.authStateFull,
		BufferJSON.reviver
	)

	creds = result.creds
	keys = result.keys
} else {
	creds = initAuthCreds()
	keys = { }
}

return {
	state: {
		creds,
		keys: {
			get: (type, ids) => {
				const key = KEY_MAP[type]
				return ids.reduce(
					(dict, id) => {
						let value = keys[key]?.[id]
						if(value) {
							if(type === 'app-state-sync-key') {
								value = proto.AppStateSyncKeyData.fromObject(value)
							}

							dict[id] = value
						}

						return dict
					}, { }
				)
			},
			set: (data) => {
				for(const _key in data) {
					const key = KEY_MAP[_key as keyof SignalDataTypeMap]
					keys[key] = keys[key] || { }
					Object.assign(keys[key], data[_key])
				}

				saveState()
			}
		}
	},
	saveState
}
}`

Using this is looping on Qr scan multiple times then fail with connection error.

**Comment by makanSukros** [comment]
> > > I see Baileys MD work with slowly, if you compare with v3 is strong diff between they. I have an account with more 3000 contacts and more than 500 sessions per day, the first problems are quantity message notification that service receive, are thousands notifications.
> > > This is a sample.
> > > ```
> > > {"level":20,"time":1650785809533,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579****@s.whatsapp.net","type":"picture","id":"1593211224","notify":"Ednilde","t":"1650785808"},"sent":{"id":"1593211224","to":"557921****@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
> > > {"level":20,"time":1650785330876,"pid":1891,"hostname":"Paulos-MacBook-Pro.local","recv":{"from":"5579*******@s.whatsapp.net","type":"picture","id":"32421461","notify":"Edjina 🙏👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧👩‍👧‍👧🙌🙌","t":"1650785330"},"sent":{"id":"32421461","to":"5579*******@s.whatsapp.net","class":"notification","type":"picture"},"msg":"sent \"notification\" ack"}
> > > {"level":30,"time":1650785958671,"pid":5176,"hostname":"Paulos-MacBook-Pro.local","msgAttrs":{"from":"status@broadcast","type":"text","edit":"7","id":"202894B622A4BAA087301BC91F234D2F","participant":"5579******@s.whatsapp.net","t":"1650785958","notify":"Thiagomergulhador🌊🏄🏽"},"retryCount":1,"msg":"sent retry receipt"}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I did an analysis and see that module consume much CPU saveState, and this file grows up, now my file has more 100mb.
> > > ![image](https://user-images.githubusercontent.com/7800501/164966873-24173d63-dfe8-4e5d-b681-e7d499911f4b.png)
> > > CPU consumption saveState 15% (accumulate after 3 times with 5%, so each time save consume 5%) useSingleFileAuthState 13% writevGeneric 6%
> > > If you open the file with state, you will see much information with status@broadcast, I don't know if this information is important to persist on file, are thousands lines with this information.
> > > ```
> > >  "status@broadcast::5579*********:0": [
> > >         {
> > >           "senderKeyId": 387750434,
> > >           "senderChainKey": {
> > >             "iteration": 0,
> > >             "seed": "ui3qMfxWHAzM7rcLnJVpO7TEE+5FmKRkk7V4MWQAWrI="
> > >           },
> > >           "senderSigningKey": {
> > >             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
> > >           },
> > >           "senderMessageKeys": []
> > >         },
> > >         {
> > >           "senderKeyId": 387750434,
> > >           "senderChainKey": {
> > >             "iteration": 2,
> > >             "seed": "7veQ2w4T0c2tq9gGA2gSLxsBjASG/AudCuG+1dL6eQo="
> > >           },
> > >           "senderSigningKey": {
> > >             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
> > >           },
> > >           "senderMessageKeys": []
> > >         },
> > >         {
> > >           "senderKeyId": 387750434,
> > >           "senderChainKey": {
> > >             "iteration": 3,
> > >             "seed": "DPcRNX7aqmvnTSvDy9VE5t8J6d2Vh1iRhW3nutB8Dmk="
> > >           },
> > >           "senderSigningKey": {
> > >             "public": "BaP+ois9Bl7WwbmYN9zF4/9zW+mPsKVGbLeyNOMDMBt5"
> > >           }
> > >         }
> > >       ],
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @adiwajshing, I would like only to show a point I understand need more attention, I don't know if I did something wrong, normally use default configuration and connect normally, however when an account has many contacts these difficulties happens.
> > > You do a fantastic work and many people need to be grateful and send bless every day for you. Thank you, for all!
> > 
> > 
> > Solution: make your own database to manage state
> 
> I have tried
> 
> `export const useSingleAuthState = (instance: any, logger?: Logger): { state: AuthenticationState, saveState: () => void } => { let creds: AuthenticationCreds let keys: any = { }
> 
> // save the authentication state to mongoDB const saveState = async () => { logger && logger.trace('saving auth state');
> 
> ```
> await WhatsappInstance.findOneAndUpdate(
> 	{ _id: instance.id },
> 	{"authStateFull" : JSON.stringify({ creds, keys }, BufferJSON.replacer, 2)},
> 	{ new: true }
> );
> ```
> 
> }
> 
> if(instance && instance.authStateFull) { const result = JSON.parse( instance.authStateFull, BufferJSON.reviver )
> 
> ```
> creds = result.creds
> keys = result.keys
> ```
> 
> } else { creds = initAuthCreds() keys = { } }
> 
> return { state: { creds, keys: { get: (type, ids) => { const key = KEY_MAP[type] return ids.reduce( (dict, id) => { let value = keys[key]?.[id] if(value) { if(type === 'app-state-sync-key') { value = proto.AppStateSyncKeyData.fromObject(value) }
> 
> ```
> 						dict[id] = value
> 					}
> 
> 					return dict
> 				}, { }
> 			)
> 		},
> 		set: (data) => {
> 			for(const _key in data) {
> 				const key = KEY_MAP[_key as keyof SignalDataTypeMap]
> 				keys[key] = keys[key] || { }
> 				Object.assign(keys[key], data[_key])
> 			}
> 
> 			saveState()
> 		}
> 	}
> },
> saveState
> ```
> 
> } }`
> 
> Using this is looping on Qr scan multiple times then fail with connection error.

How to using flame like this bro?

**Comment by paulocorcino** [comment]
https://clinicjs.org/flame/

Em qui, 28 de abr de 2022 07:49, MakanSukro™ ***@***.***>
escreveu:

**Comment by tarikhagustia** [comment]
i'm facing this issue, i have manage 50 devices in 1 node instances and sometime when instance restarted, its become event loop latency issue. i'm going to profiling the issue its seem the bottle neck in saveState method.
