### ISSUE TITLE
Link preview dont work any url [BUG]

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#1536]
The link preview work with `https://www.youtube.com/watch?v=LV-nxDJdk88` but don't work with `https://youtu.be/LV-nxDJdk88` .

Why?

**Comment by manojsitapara** [comment]
> The link preview work with `https://www.youtube.com/watch?v=LV-nxDJdk88` but don't work with `https://youtu.be/LV-nxDJdk88` .
> 
> Why?

for me it is not working with 

> https://www.youtube.com/watch?v=LV-nxDJdk88

It send normal message without link preview

@IanosJunior did you do anything else apart from installing ?

> link-preview-js
