### ISSUE TITLE
[BUG] sendMessage is not working in groups

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#1538]
When I run a local server everything works fine, `sock.sendMessage` can send messages either in individual chats or in groups

But if I'm running the server on Heroku, I can still use `sendMessage` via private chat, but once I try it in a group, the bot only sends "Waiting for this message. This may take a while." and the console outputs this (`Closing stale open session for new outgoing prekey bundle`)
![image](https://user-images.githubusercontent.com/84653497/165185443-dea2bbdb-f8a9-4a5f-80f9-6a8429d72e62.png)

And any subsequent `sendMessage` will result in the same thing, even in private chats.. I have tried debugging it trying to find what the cause is but I couldn't. Please help me...

Here is my `message.upsert` event:
![image](https://user-images.githubusercontent.com/84653497/165185935-d661c7cc-c410-472f-9494-646cb6c43f20.png)

**Comment by aidulcandra** [comment]
UPDATE: Now local server also experiences the same issue

So basically this bug happens when sending a message to a group

**Comment by tiesco238** [comment]
same problem here. I cannot send messages to group with this (old) format "40799016510-1635263103".. It times out after 30 seconds. Group chats with 12345624234678@g.us format works just fine.

Somebody knows how to fix or work around this?

**Comment by LeonardoBein** [comment]
same problem here

**Comment by aidulcandra** [comment]
> same problem here. I cannot send messages to group with this (old) format "40799016510-1635263103".. It times out after 30 seconds. Group chats with [12345624234678@g.us](mailto:12345624234678@g.us) format works just fine.
> 
> Somebody knows how to fix or work around this?

So using the format without dash symbol works fine?
Let me try it then

**Comment by aidulcandra** [comment]
> same problem here. I cannot send messages to group with this (old) format "40799016510-1635263103".. It times out after 30 seconds. Group chats with [12345624234678@g.us](mailto:12345624234678@g.us) format works just fine.
> 
> Somebody knows how to fix or work around this?

Still doesn't work for me

**Comment by LeonardoBein** [comment]
I solved this by updating whatsapp app on mobile.

**Comment by aidulcandra** [comment]
> I solved this by updating whatsapp app on mobile.

My Whatsapp doesn't have any update available on Play Store. But it's working now. Closing the issue now.

**Comment by ahmadkeren** [comment]
Any solution, i got this problems too...

**Comment by manojsitapara** [comment]
@aidulcandra did you take any step to fix the issue?

**Comment by aidulcandra** [comment]
@manojsitapara I didnt.. the problem does occur when restarting the program buat it eventually be back to normal if you leave it for some time

**Comment by manojsitapara** [comment]
@aidulcandra Thank you for quick reply, let me try and update you.

**Comment by manojsitapara** [comment]
It send message to those groups which has less than 50 members, but it throw following error when trying to send message to those groups which has more than 250+ members 

> Closing stale open session for new outgoing prekey bundle
