### ISSUE TITLE
How to send & receive quoted messages? 

### ISSUE THREAD

**Issue by talhabalaj** [adiwajshing/Baileys#154]
Hello,

I have noticed that while receiving a quoted or replied message, there is an empty string in `proto.WebMessageInfo.messsage.conversation`. I think I don't know how to retrieve those messages. 

Can you help me out? 

Thank you.

**Comment by talhabalaj** [comment]
Tried `message.extendedTextMessage.text` as well

**Comment by adiwajshing** [comment]
Need some code, otherwise I can't tell what's going wrong

**Comment by talhabalaj** [comment]
```javascript
client.on('new-message', (conv) => {
 conv.message.conversation; // null for quoted messages
});
```

**Comment by adiwajshing** [comment]
``` ts

client.on('new-message', (conv) => {
 console.log(conv.message.extendedTextMessage.contextInfo) // contains all the info about the quoted message
})

```

**Comment by talhabalaj** [comment]
Thank you!

**Comment by Quiec** [comment]
How to send quoted message?
