### ISSUE TITLE
Saving Credentials Updates to MongoDB on creds.update event

### ISSUE THREAD

**Issue by tmandinyenya** [adiwajshing/Baileys#1541]
I have re-implemented useSingleFileAuthState as follows 

`
export const useSingleAuthState = (instance: any, logger?: Logger): { state: AuthenticationState, saveState: () => void } => {
	// require fs here so that in case "fs" is not available -- the app does not crash
	//const { readFileSync, writeFileSync, existsSync } = require('fs')
	let creds: AuthenticationCreds
	let keys: any = { }
	

	// save the authentication state to a file
	const saveState = async () => {
		logger && logger.trace('saving auth state');
		console.log("Saving state");
		await WhatsappInstance.findOneAndUpdate(
			{ _id: instance.id },
			{"authStateFull" : JSON.stringify({ creds, keys }, BufferJSON.replacer, 2)},
			{ new: true }
		);
	}

	if(instance && instance.authStateFull) {
		
		console.log(instance.authStateFull)
		
		const result = JSON.parse(
			instance.authStateFull,
			BufferJSON.reviver
		)

		console.log(result)
		creds = result.creds
		keys = result.keys
	} else {
		creds = initAuthCreds()
		keys = { }
	}

	return {
		state: {
			creds,
			keys: {
				get: (type, ids) => {
					const key = KEY_MAP[type]
					return ids.reduce(
						(dict, id) => {
							let value = keys[key]?.[id]
							if(value) {
								if(type === 'app-state-sync-key') {
									value = proto.AppStateSyncKeyData.fromObject(value)
								}

								dict[id] = value
							}

							return dict
						}, { }
					)
				},
				set: (data) => {
					for(const _key in data) {
						const key = KEY_MAP[_key as keyof SignalDataTypeMap]
						keys[key] = keys[key] || { }
						Object.assign(keys[key], data[_key])
					}

					saveState()
				}
			}
		},
		saveState
	}
}
` 
However it continues to request QR code and eventually fails.

Log Below

`
using WA v2.2212.7, isLatest: true
connection update {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
{"level":30,"time":1650983908022,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","browser":["Baileys","Chrome","4.0.0"],"helloMsg":{"clientHello":{"ephemeral":"FhdXUOuIIBQKtCO8jjmx8QYR39topAIY9oM6C8bqmlE="}},"msg":"connected to WA Web"}
{"level":10,"time":1650983908384,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","handshake":{"serverHello":{"ephemeral":"bn0Xs6rsaIyno+Z8683WiBleJsNwxZkXUEqPjR9Oa2E=","static":"0DCdg5x7jjTEMyMgtb5mOs4Ia19FUPIXlPkNGykOZCmNwLw0Dxd4D+prZSOIZOvO","payload":"m6DQkkmtWu0k2oGSb4njrXslj/4kdrkVFs/8HeXtE/Ht+mbYvjnfZP/B7fZ+bhT4m4NV5Zkdh4G/OnGNDWbBvTAplApkIm6zVh5wNihkFyliuXd0xNLlrRbBQSvdVQCdV6HUfRHFj8S9Gofbk7X9tWcoasCQgeXMSf2GipVo/ZgGYuh6m3LUjV3I5a5cW+9wV3nD5hSfi06BWqFOfYTAQtAXGQ=="}},"msg":"handshake recv from WA Web"}
{"level":30,"time":1650983908399,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","msg":"handshake complete"}
{"level":30,"time":1650983908402,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","node":{"passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2212,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","regData":{"eRegid":"AAAA9Q==","eKeytype":"BQ==","eIdent":"ii5ubFv0Rj5XzzYCuEzZageKWWF2+UMAVpH7u/jRdH8=","eSkeyId":"AAAB","eSkeyVal":"WfZT9dYVDxgSpvghgq0/EAdJQW8oJu+19rETi8YCjBE=","eSkeySig":"chpMB9/+21lZA//XeNEtXeRVVWZ5YoYlHEq68mWGardLSwzQ/eU4dldRD/ZV4xMzAWySOM/14o+KvJoB99jiig==","buildHash":"VHetvAwlE73ZZH7cT8WiuQ==","companionProps":"CgdCYWlsZXlzEgYIBBAAGAAYASAA"}},"msg":"not logged in, attempting registration..."}
{"level":10,"time":1650983908868,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","msgId":"1835496401","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"set","id":"1835496401","xmlns":"md"},"content":[{"tag":"pair-device","attrs":{},"content":[{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,106,99,108,88,76,109,121,57,86,57,51,98,112,104,107,101,51,78,74,106,90,112,100,115,52,107,47,102,78,82,53,102,54,102,50,98,108,55,119,102,98,110,114,100,103,85,101,48,86,50,77,105,117,87,100,118,48,66,43,56,80,107,52,87,90,43,116,102,99,110,52,111,103,57,82,116,72,119,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,87,116,52,117,43,99,83,101,106,53,104,111,100,106,89,80,79,53,84,78,120,81,49,120,113,70,57,101,49,99,55,81,70,97,121,54,53,51,88,54,75,83,117,110,77,73,51,98,120,51,49,97,115,113,90,116,66,87,69,122,89,75,98,53,70,85,100,101,72,79,122,83,111,110,105,122,102,119,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,88,52,90,119,115,122,47,67,99,116,116,73,114,85,88,71,122,86,119,55,107,49,55,110,70,84,80,88,117,43,48,111,74,89,53,114,54,101,108,87,77,57,108,68,109,105,48,111,71,110,110,101,84,69,118,67,43,119,87,107,98,72,57,103,100,72,54,43,99,71,116,108,98,47,48,68,84,81,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,51,108,116,81,83,56,115,101,119,109,69,68,107,47,86,101,53,57,52,114,73,116,108,75,119,67,52,43,52,54,118,68,73,118,119,65,81,49,76,53,107,54,57,108,69,119,102,99,104,110,115,47,82,112,98,103,85,108,78,115,74,71,111,55,122,119,75,55,121,122,43,87,57,85,69,104,113,81,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,57,80,53,78,49,99,113,108,74,49,106,48,69,98,114,104,73,69,105,86,105,48,108,81,85,101,112,57,75,112,50,52,90,110,66,88,85,120,48,115,115,100,90,122,53,50,54,87,88,115,75,72,54,66,75,122,110,65,48,98,104,48,57,83,109,104,114,105,116,53,108,67,47,106,54,48,53,103,61,61]}},{"tag":"ref","attrs":{},"content":{"type":"Buffer","data":[50,64,71,117,84,118,86,99,88,108,103,69,75,66,48,78,66,98,82,47,103,85,76,106,55,116,56,82,75,90,53,116,106,89,67,47,118,119,49,55,117,113,73,102,122,116,78,89,52,83,81,122,99,121,56,53,103,66,116,51,54,110,115,52,71,100,122,77,97,107,113,77,73,98,106,79,48,101,84,103,61,61]}}]}]},"msg":"communication"}

connection update {
  qr: '2@jclXLmy9V93bphke3NJjZpds4k/fNR5f6f2bl7wfbnrdgUe0V2MiuWdv0B+8Pk4WZ+tfcn4og9RtHw==,g0I/K3tOX1NIwtZIF97pnxgINOJFzMmvYCpng4guNWA=,ii5ubFv0Rj5XzzYCuEzZageKWWF2+UMAVpH7u/jRdH8=,1ht3T1yVYv5f/OPVtsqHFOY4u+NZxM+FfUanKAskvgs='
}
{"level":10,"time":1650983916956,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","msgId":"743873626","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"set","id":"743873626","xmlns":"md"},"content":[{"tag":"pair-success","attrs":{},"content":[{"tag":"platform","attrs":{"name":"smba"},"content":null},{"tag":"device-identity","attrs":{},"content":{"type":"Buffer","data":[10,116,10,14,8,133,177,173,143,6,16,234,135,160,147,6,24,1,18,32,38,14,41,101,22,142,211,84,190,128,87,5,18,233,52,191,53,21,221,104,240,246,215,38,0,216,188,82,115,23,28,99,26,64,121,2,183,215,71,24,235,34,62,208,232,130,170,121,106,92,1,241,209,157,225,197,89,203,50,55,35,151,230,110,140,131,65,221,217,193,201,205,47,48,86,192,29,153,153,106,7,124,30,41,243,186,24,173,186,44,48,8,98,246,58,39,112,11,18,32,217,44,255,188,21,200,0,130,73,127,84,24,161,9,179,124,55,131,212,219,188,159,19,125,119,113,201,73,101,87,108,30]}},{"tag":"biz","attrs":{"name":"Chitubu Provisional Licence Course"},"content":null},{"tag":"device","attrs":{"jid":"263747:59@s.whatsapp.net"},"content":null}]}]},"msg":"communication"}
{"level":20,"time":1650983916957,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","msg":"pair success recv"}
{"level":20,"time":1650983917051,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","msg":"pairing configured successfully"}
{"level":30,"time":1650983917052,"pid":530940,"hostname":"trust-mandinyenya-zbook-workstation","jid":"2634:59@s.whatsapp.net","msg":"registered connection, restart server"}

`

**Comment by Xrazik1** [comment]
`saveState` method calls independently from your code in the socket creation namespace. I can assume that your model doesn't have enough time to update creds before reconnecting happens. That's why the socket thinks creds are empty and reconnects again. 

Something you can try is to set your creds to model (without updating it and calling an async method) Then check if your model changed in your "connect" method and call saving to DB before your socket creates. But there you will have the problem that creds won't update during connection is online.

I'm still having the same case, trying to find a correct solution.

**Comment by Xrazik1** [comment]
Actually, the example case in the library perfectly works because it doesn't contain async operations inside. And It would be great if somebody add an example of interaction with a DB and async creds saving.

**Comment by growupmarketingdigital** [comment]
same problem here 
"not logged in, attempting registration..."
