### ISSUE TITLE
[BUG] Precondition Required Still Problem

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#1543]
After my bot running more than several hours im getting this error always:

Error: Connection Closed
    at sendRawMessage (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:56:19)
    at sendNode (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:67:16)
    at query (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:131:15)
    at interactiveQuery (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:23:30)
    at Object.onWhatsApp (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:61:31)
    at BWhatsAppCore.sendingMessage (/home/botwabaileys/bcore.js:1240:50)
    at resp.ack (/home/botwabaileys/server.js:424:26)
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/botwabaileys/server.js:423:13)
    at preHandlerCallback (/home/botwabaileys/node_modules/fastify/lib/handleRequest.js:126:28) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by makanSukros** [comment]
and this message also often comes out for some reason, I've tried to check the internet connection there is no problem, I've tried to change the provider also this problem still appears a few hours after the bot is running

Error: Timed Out
    at /home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:170:32 {
  data: {
    stack: 'Error\n' +
      '    at Object.promiseTimeout (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:165:19)\n' +
      '    at waitForMessage (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:107:42)\n' +
      '    at query (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:130:22)\n' +
      '    at /home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:240:38\n' +
      '    at runNextTicks (node:internal/process/task_queues:61:5)\n' +
      '    at processTimers (node:internal/timers:497:9)\n' +
      '    at async Object.transaction (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:78:21)\n' +
      '    at async resyncAppState (/home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:206:9)\n' +
      '    at async /home/botwabaileys/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:553:17'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

**Comment by Alhar6i** [comment]
Please check the connection.update event code 
in the `sock.ev.on('connection.update', (update) => {...}` you must check the `DisconnectReason` if it's not `loggedOut` then you **have to** call your function again to reconnect WA

**Comment by makanSukros** [comment]
> Please check the connection.update event code in the `sock.ev.on('connection.update', (update) => {...}` you must check the `DisconnectReason` if it's not `loggedOut` then you **have to** call your function again to reconnect WA

already using the reconnect method but it still appears

**Comment by Alhar6i** [comment]
> already using the reconnect method but it still appears
If you don't mind, please post your code (The initial call to the sock and the `sock.ev.on('connection.update', (update) => {...}`) here we might be able to help.

**Comment by makanSukros** [comment]
> > already using the reconnect method but it still appears
> 
> If you don't mind, please post your code (The initial call to the sock and the `sock.ev.on('connection.update', (update) => {...}`) here we might be able to help.

This is my code:

sock.ev.on('connection.update', async(update) => {
            
	const { connection, lastDisconnect } = update
	if(connection === 'close') {
		if(lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut){
			console.log('Retry Connect');
			this.startSock();
		}else{
			this.properlyDisconnect();
		}
	}
}

**Comment by rn2web** [comment]
> Não vejo nada de errado aqui. E também acredito que não há problema com Baileys Parece que você modificou o exemplo original colocando a função `startSocket `em sua própria classe (se não estiver errado).
> 
> Resolvi esse problema passando 'Normal' para a ` sock.end`função ou seja: `sock.end('Normal')`e no evento de atualização testei o motivo lastDisconnect se for 'Normal' então chamo o startSocket. Para mim, isso resolveu o problema.

can you provide a better example with that sock.end('Normal') ?
In my case, here i'm getting a error when trying use sock.end('Normal') ( can't use string )

**Comment by rn2web** [comment]
> I see nothing wrong here. And also I believe there is no issue with Baileys It seems you have modified the original example by placing the function `startSocket `in your own class (if I'm not wrong).
> 
> I solved this issue by passing 'Normal' to the` sock.end` function i.e: `sock.end('Normal')` and in the update event I tested the lastDisconnect reason if it is 'Normal' then I call the startSocket. For me, that solved the issue.

can you provide a better example with that sock.end('Normal') ?
In my case, here i'm getting a error when trying use sock.end('Normal') ( can't use string )

**Comment by makanSukros** [comment]
> I see nothing wrong here. And also I believe there is no issue with Baileys It seems you have modified the original example by placing the function `startSocket `in your own class (if I'm not wrong).
> 
> I solved this issue by passing 'Normal' to the` sock.end` function i.e: `sock.end('Normal')` and in the update event I tested the lastDisconnect reason if it is 'Normal' then I call the startSocket. For me, that solved the issue.

Still same error you can show example with this solution?

**Comment by muzafferkadir** [comment]
@makanSukros did you solve this problem?
