### ISSUE TITLE
[BUG] Error: Intentional Logout

### ISSUE THREAD

**Issue by zakirkun** [adiwajshing/Baileys#1546]
### I Have Problem 
`    at Object.logout (C:\Users\user\Workspace\backend-services-whatsapp\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:372:13)
    at C:\Users\user\Workspace\backend-services-whatsapp\src\utils\whatsapp.ts:148:40
    at Generator.next (<anonymous>)
    at C:\Users\user\Workspace\backend-services-whatsapp\src\utils\whatsapp.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\user\Workspace\backend-services-whatsapp\src\utils\whatsapp.ts:23:12)
    at logoutSession (C:\Users\user\Workspace\backend-services-whatsapp\src\utils\whatsapp.ts:147:56)
    at C:\Users\user\Workspace\backend-services-whatsapp\src\utils\whatsapp.ts:189:25
    at Generator.next (<anonymous>)
    at C:\Users\user\Workspace\backend-services-whatsapp\src\utils\whatsapp.ts:27:71 {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Intentional Logout'
    },
    headers: {}
  }
} , reconnecting  false`

**Comment by shoukosagiri-poi** [comment]
up

**Comment by diogo-smi** [comment]
up

**Comment by code-by** [comment]
how to establish new connection / session after doing logout() ?

**Comment by zakirkun** [comment]
> how to establish new connection / session after doing `logout()` ?

idk bro

**Comment by code-by** [comment]
up
