### ISSUE TITLE
[BUG] Error: TypeError: Cannot destructure property 'user' of 'exports.jidDecode(...)' as it is undefined.

### ISSUE THREAD

**Issue by aniq12** [adiwajshing/Baileys#1547]
TypeError: Cannot destructure property 'user' of 'exports.jidDecode(...)' as it is undefined.
at Object.jidNormalizedUser (/root/PatrickBot-MD/node_modules/@adiwajshing/baileys/lib/WABinary/jid-utils.js:49:13)
at /root/PatrickBot-MD/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:396:49
at Array.map (<anonymous>)
at /root/PatrickBot-MD/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:393:59
at /root/PatrickBot-MD/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:16:24
at async handleReceipt (/root/PatrickBot-MD/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:383:9)

**Comment by guilhermeromer** [comment]
Same here.

**Comment by joelvitorniino** [comment]
Same here

**Comment by erickythierry** [comment]
same here

**Comment by frmdeveloper** [comment]
same same

**Comment by aniq12** [comment]
> same same

:v

**Comment by erickythierry** [comment]
to work around this error temporarily, I indicate using a specific version of github baileys 
this error is specific to the most current version

in my project I made the change of package.json like so:
```
"dependencies": {
    "@adiwajshing/baileys": "git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b",
(...) 
```
this version does not cause this error

**Comment by SanzGantengz** [comment]
> > same same
> 
> :v

:v

**Comment by frmdeveloper** [comment]
Not same

**Comment by DentaCH** [comment]
same here

**Comment by rn2web** [comment]
same here :(

**Comment by jccalbuquerque** [comment]
I'm getting this error.
I'm installing Baileys from Git.
Does anybody know how to solve this?
I have already deleted all modules and installed again.
I already deleted the package-lock.json file.
This error happens when trying to reply to a message.
My source code with the NPM version runs without any errors, but with the Git version it gives this error.
Does anyone know how to solve?

The command I run to install from Git is: npm i github:adiwajshing/baileys
Any error with my command?

**Comment by erickythierry** [comment]
> I'm getting this error. I'm installing Baileys from Git. Does anybody know how to solve this? I have already deleted all modules and installed again. I already deleted the package-lock.json file. This error happens when trying to reply to a message. My source code with the NPM version runs without any errors, but with the Git version it gives this error. Does anyone know how to solve?
> 
> The command I run to install from Git is: npm i github:adiwajshing/baileys Any error with my command?

use the latest version available in Npm. Direct versions of github are updated more often but are less stable. I had this same problem and ended up migrating to the stable version of npm and did not get any more errors.

**Comment by ibnumardini** [comment]
i have some error
