### ISSUE TITLE
how to fix this error? timed out

### ISSUE THREAD

**Issue by triyatnaa29** [adiwajshing/Baileys#1549]
how to fix this error? 

node_modules\@adiwajshing\baileys\lib\Utils\generics.js:178
            .then(() => reject(new boom_1.Boom('Timed Out', {

**Comment by salykingleb** [comment]
Also interested in this

**Comment by HanzCEO** [comment]
Baileys timeout is not guaranteed having second chance, you should modify your config property of `connectTimeoutMs` to any number larger

**Comment by Gimenz** [comment]
yea im facing sme problem

**Comment by erickythierry** [comment]
to work around this error temporarily, I indicate using a specific version of github baileys
this error is specific to the most current version

in my project I made the change of package.json like so:
```
"dependencies": {
    "@adiwajshing/baileys": "git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b",
(...) 
```
this version does not cause this error

**Comment by DionlenoPiata** [comment]
> git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b

It didn't work for me. I'm using windows 11, node v17.9.0

**Comment by erickythierry** [comment]
> > git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b
> 
> It didn't work for me. I'm using windows 11, node v17.9.0

you deleted the node modules folder and redid the installation? you also need to delete the package-lock or yarn-lock.
(sorry to ask, but sometimes forget to do this)

**Comment by DionlenoPiata** [comment]
Yes, I did these procedures and the error continued

**Comment by DionlenoPiata** [comment]
> > > git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b
> > 
> > 
> > It didn't work for me. I'm using windows 11, node v17.9.0
> 
> you deleted the node modules folder and redid the installation? you also need to delete the package-lock or yarn-lock. (sorry to ask, but sometimes forget to do this)

Yes, I did these procedures and the error continued

**Comment by rn2web** [comment]
i'm getting the same problem

**Comment by DionlenoPiata** [comment]
> Set this on connection options:
> 
> `defaultQueryTimeoutMs: undefined`

Apparently this setup worked for me

**Comment by rn2web** [comment]
> > Set this on connection options:
> > `defaultQueryTimeoutMs: undefined`
> 
> Apparently this setup worked for me

Hi @DionlenoPiata  ,  where i put "defaultQueryTimeoutMs: undefined" ?
"connection options" ?

does it's inside of this?

const socket = makeWASocket({
    printQRInTerminal: true,
    auth: state,
  });

**Comment by AkirahX** [comment]
> > > Set this on connection options:
> > > `defaultQueryTimeoutMs: undefined`
> > 
> > 
> > Apparently this setup worked for me
> 
> Hi @DionlenoPiata , where i put "defaultQueryTimeoutMs: undefined" ? "connection options" ?
> 
> does it's inside of this?
> 
> const socket = makeWASocket({ printQRInTerminal: true, auth: state, });

Yes

```javascript

const socket = makeWASocket({ 
    printQRInTerminal: true, 
    auth: state, 
    defaultQueryTimeoutMs: undefined
});

```

**Comment by jacktheboss220** [comment]
> > Set this on connection options:
> > `defaultQueryTimeoutMs: undefined`
> 
> Apparently this setup worked for me

Thnx works for me.
