### ISSUE TITLE
Clear chat 

### ISSUE THREAD

**Issue by Ased2235** [adiwajshing/Baileys#1550]
Hello, Is it possible to add clear chat feature in MD?

**Comment by VEXG** [comment]
> Hello, Is it possible to add clear chat feature in MD?

No, but yes u can. But u have to store the chats/messages first into your custom db, there's a func built in to handle that. But for me its too heavy so i recommend you to use custom db

**Comment by Ased2235** [comment]
> > Hello, Is it possible to add clear chat feature in MD?
> 
> No, but yes u can. But u have to store the chats/messages first into your custom db, there's a func built in to handle that. But for me its too heavy so i recommend you to use custom db

Hello, Can you give me an example?
