### ISSUE TITLE
error sending messages, close connection [BUG]

### ISSUE THREAD

**Issue by erickythierry** [adiwajshing/Baileys#1552]
the script started to give an error when trying to send messages in specific groups, but it seems to be random.

even re-logging in or setting a specific version of the web

console output:
```
connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (xml-not-well-formed)
        at WebSocket.<anonymous> (C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:429:13)
        at WebSocket.emit (node:events:520:28)
        at C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:227:35
        at Object.decodeFrame (C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:142:17)
        at WebSocket.onMessageRecieved (C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:203:15)
        at WebSocket.emit (node:events:520:28)
        at Receiver.receiverOnMessage (C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\ws\lib\websocket.js:1137:20)
        at Receiver.emit (node:events:520:28)
        at Receiver.dataMessage (C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\ws\lib\receiver.js:513:14)
        at Receiver.getData (C:\Users\55919\Desktop\codigos\bots\botmd\node_modules\ws\lib\receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: true,
      output: [Object]
    },
    date: 2022-04-28T21:38:10.898Z
  }
}
{"level":30,"time":"2022-04-28T21:38:10.922Z","pid":3508,"hostname":"DESKTOP-9M2TP92","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
```
the error started today out of nowhere, without any modification of the code. I updated to the latest version of github and still the same problem

**Comment by LightningNeko** [comment]
the same error appears when I try to send a message to groups with more than 200 members

**Comment by erickythierry** [comment]
> the same error appears when I try to send a message to groups with more than 200 members

same here.
the temporary solution I found was to use a specific version of baileys.
replace baileys dependency with this one in package.json file
```
"dependencies": {
    "@adiwajshing/baileys": "git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b",
(...) 
```

**Comment by LightningNeko** [comment]
i wrote this temporary solution: https://github.com/LightningNeko/Baileys/commit/9ac1a059ef532233005e98c98a87da7362d0d546

**Comment by guiguicdd** [comment]
Same here

![image](https://user-images.githubusercontent.com/50055027/167274283-1a5efb8f-45d2-4b64-bd5f-da9c48ca56e4.png)

**Comment by guiguicdd** [comment]
Any update?

**Comment by hasanbasri1993** [comment]
> i wrote this temporary solution: [LightningNeko@9ac1a05](https://github.com/LightningNeko/Baileys/commit/9ac1a059ef532233005e98c98a87da7362d0d546)

How you now, still close connection ?

**Comment by guilhermeromer** [comment]
@LightningNeko The solution really helped me. I believe this is happening exactly on groups which have more than 200 people. Would be nice if you could make a pull request to Adi's repo with your solution! 😁

**Comment by viniciusgdr** [comment]
unstale

**Comment by SamPandey001** [comment]
Facing Same Error

**Comment by Shubhamrawat5** [comment]
Same issue

**Comment by russocorp** [comment]
i am having same error and dont send message to goups :/

**Comment by Borzalic** [comment]
same issue. even though i just sent a message to my own number.

**Comment by enoksaju** [comment]
same issue
