### ISSUE TITLE
"Waiting for this message. This may take a while" problem

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#1555]
**Describe the bug**
Sometimes when the bot sends a message, it only shows "Waiting for this message. This may take a while" on my phone, but apparently on the recipient's end it works just fine. When that happen there is also this log
![image](https://user-images.githubusercontent.com/84653497/166096453-dc238741-3e9c-4214-9d8c-ce5eadab2692.png)

EDIT: I noticed that this happens after relogging in (using saved authState)

**To Reproduce**
Log in.
Stop the connection. (Don't log out)
Log back in.
Send a message using bot as usual.

**Expected behavior**
The message content should be shown on my phone. But all I see is "Waiting for this message. This may take a while.". When I trigger it for several times... it's still showing the same result. But after a while it works fine, but those that are already sent still don't change.

**Environment (please complete the following information):**
 - Is this on a server? Both
 - What do your `connectOptions` look like? 
![image](https://user-images.githubusercontent.com/84653497/166096582-b399eca3-e27f-4d63-b534-2de33cd98268.png)
`authManager` is just an object returned from `useSingleFileAuthState`

 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
On the recipient's end it works just fine. But I want to see what it sends. (For debugging purposes)

**Comment by Gimenz** [comment]
yep, i facing same issue

**Comment by aidulcandra** [comment]
Could the problem be not closing the connection with `sock.end()` or something?

**Comment by makanSukros** [comment]
Same issue but not always happen for me

**Comment by aidulcandra** [comment]
> Same issue but not always happen for me

Does this happen after restarting the bot using a saved auth_state.json file ?

**Comment by ChCh27** [comment]
https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while

**Comment by aidulcandra** [comment]
> https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while

I've read that. I understand that happens at times but not so predictable like this. Everytime I restart the connection this will definetely happen.

**Comment by lyfe00011** [comment]
> > https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while
> 
> I've read that. I understand that happens at times but not so predictable like this. Everytime I restart the connection this will definetely happen.

How you managing auth state

**Comment by aidulcandra** [comment]
> > > https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while
> > 
> > 
> > I've read that. I understand that happens at times but not so predictable like this. Everytime I restart the connection this will definetely happen.
> 
> How you managing auth state

In production I use a site called Pantry to save my auth state there. It has an API that can be used with JavaScript.
In my `creds.update` event, I upload the auth state to Pantry

https://getpantry.cloud/

**Comment by lyfe00011** [comment]
> > > > https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-this-may-take-a-while
> > > 
> > > 
> > > I've read that. I understand that happens at times but not so predictable like this. Everytime I restart the connection this will definetely happen.
> > 
> > 
> > How you managing auth state
> 
> In production I use a site called Pantry to save my auth state there. It has an API that can be used with JavaScript. In my `creds.update` event, I upload the auth state to Pantry
> 
> https://getpantry.cloud/

For first msg can have waiting for... Which also solved by getMessage method
But happening after relogin can be bcz of faulty state

**Comment by adarsh-chakraborty** [comment]
im also facing this issue

**Comment by jasspro** [comment]
any update about this issue.

**Comment by makanSukros** [comment]
Still problem with me

**Comment by ibnumardini** [comment]
anyone updates?

**Comment by Heknon** [comment]
updates?

**Comment by imReCoder** [comment]
I am facing the same issue, I have been using one auth state file form many days.

**Comment by Kuroosh** [comment]
any updates ?

**Comment by imReCoder** [comment]
Deleting auth files and rescanning the new Qr code solved issues but still dont know why this occurred .

**Comment by adarsh-chakraborty** [comment]
Facing the same issue

**Comment by aidulcandra** [comment]
Here is something you can do:

When you create a socket, you should pass a getMessage function into the configuration. The getMessage function takes a message key as an argument, and it must return the message associated with that key.

So in your main file:
```
const baileys = require('@adiwajshing/baileys')

const tempStore = { } // This object will be used to store the bot's sent messages.  (MessageInfo object)

// Below's function is what solves the problem
const getMessage = async (key) => {
  const {id} = key
  console.log('Resending', id)
  return tempStore[id]?.message
}

async function start() {
  const { state, saveState } = baileys.useMultiFilesAuthState()
  client = baileys.default({
    auth: state
    getMessage,               // <--- Here, pass getMessage into the socket configuration
    printQRInTerminal: true
  })
}
```

And when you try to send a message, make sure you save the sent message in tempStore, with the message's key id as the key
```
const sent = await client.sendMessage( .... )
tempStore[sent.key.id] = sent
```
