### ISSUE TITLE
[BUG]Connection Closed

### ISSUE THREAD

**Issue by imamwasmawi03** [adiwajshing/Baileys#1556]
{
    "status": false,
    "response": {
        "data": null,
        "isBoom": true,
        "isServer": false,
        "output": {
            "statusCode": 428,
            "payload": {
                "statusCode": 428,
                "error": "Precondition Required",
                "message": "Connection Closed"
            },
            "headers": {}
        }
    }
}

**Comment by ekoprtok** [comment]
same problem

**Comment by makanSukros** [comment]
+1

**Comment by aidulcandra** [comment]
Can you show us your code?

**Comment by makanSukros** [comment]
> Can you show us your code?

sock.ev.on('connection.update', async(update) => {

const { connection, lastDisconnect } = update
if(connection === 'close') {
	if(lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut){
		console.log('Retry Connect');
		this.startSock();
	}else{
		this.properlyDisconnect();
	}
}
}
