### ISSUE TITLE
[BUG] error sending message in group

### ISSUE THREAD

**Issue by nyzfunbotz** [adiwajshing/Baileys#1558]
hello, why when I use the command in grub it can't? there is no error in the log, how do I deal with this problem

**Comment by aidulcandra** [comment]
Show your code

**Comment by ahmadkeren** [comment]
Same here.. any solution?

**Comment by ahmadkeren** [comment]
No error response..
![](https://user-images.githubusercontent.com/49072140/166431722-4d6ed366-d5e4-4be5-854f-7411df6090e6.png)

![](https://user-images.githubusercontent.com/49072140/166431645-d65fe679-9fc2-42d7-88c5-a83c274106c7.png)
