### ISSUE TITLE
"msg":"unprocessable update"}

### ISSUE THREAD

**Issue by OdinTm** [adiwajshing/Baileys#1559]
bug

**Comment by rn2web** [comment]
same here , when i scan qrcode  first time.

**Comment by wagnerfillio** [comment]
The same here
![image](https://user-images.githubusercontent.com/22008303/167233134-ac86b061-41d3-4112-a50c-8a0cd0126525.png)

**Comment by rn2web** [comment]
does anyone has a solution for this issue?
