### ISSUE TITLE
[BUG] BAGAI MANA SAYA MENGATASI HAL INI?

### ISSUE THREAD

**Issue by Bintangp02** [adiwajshing/Baileys#1565]
```
 connection: 'close',
  lastDisconnect: {
    error: Error: Restart Required
        at WebSocket.<anonymous> (/home/runner/Hisoka-Morou/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:433:17) {
      data: null,
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2022-05-04T08:03:26.320Z
  }
}
Connected... {
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
Connected... { connection: 'open' }
Connected... { receivedPendingNotifications: true }
```
inglish
HOW DO I RESOLVE THIS?

**Comment by FaizBastomi** [comment]
it's normal, every time it connects the server asks to restart the connection or sometimes the connection to the server drops and asks to reconnect

**Comment by ngadimin51** [comment]
Hapus creden

> ```
>  connection: 'close',
>   lastDisconnect: {
>     error: Error: Restart Required
>         at WebSocket.<anonymous> (/home/runner/Hisoka-Morou/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:433:17) {
>       data: null,
>       isBoom: true,
>       isServer: false,
>       output: [Object]
>     },
>     date: 2022-05-04T08:03:26.320Z
>   }
> }
> Connected... {
>   connection: 'connecting',
>   receivedPendingNotifications: false,
>   qr: undefined
> }
> Connected... { connection: 'open' }
> Connected... { receivedPendingNotifications: true }
> ```
> 
> inglish HOW DO I RESOLVE THIS?

Hapus credential aja Om.
