### ISSUE TITLE
Use old version with new Whatsapp Web Connection

### ISSUE THREAD

**Issue by xxxmike3** [adiwajshing/Baileys#1566]
Hi! i have a question: i use a old adiwajshing/Baileys base (v3), and my Bot have a lot of configurations and functions.
is possible to use my actual code and i update only connection section ? because whatspp web broken after the last update
i try to run update over my actual code, but don't work

**Comment by canove** [comment]
Unfortunately, you will have to rewrite most part of your code to work with the new v4.
