### ISSUE TITLE
makeInMemoryStore is to heavy?

### ISSUE THREAD

**Issue by ngadimin51** [adiwajshing/Baileys#1569]
I've been used makeInMemoryStore.

When i use 1 device to connect WA, I'ts looking good.
But when i used more than 4 device, my vps is overload.

It's small vps, just 1vCPU and 1Gig of RAM.

It's normal? Or my vps is needed to an upgrade?

**Comment by SheIITear** [comment]
Definitely too low power host.

**Comment by hasanbasri1993** [comment]
> I've been used makeInMemoryStore.
> 
> When i use 1 device to connect WA, I'ts looking good. But when i used more than 4 device, my vps is overload.
> 
> It's small vps, just 1vCPU and 1Gig of RAM.
> 
> It's normal? Or my vps is needed to an upgrade?

in Baileys version 3.x.x its is normal.
Any solution @adiwajshing ?

**Comment by ngadimin51** [comment]
I upgrade my vps using 2 gig ram.
It's fine now.

Thanks all
