### ISSUE TITLE
Product Catalog

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#157]
Is possible to get and send a product item from the catalog or even the entire catalog on whatsapp Business?

**Comment by algoz098** [comment]
The events on web whatsapp socket
`648.--33,,["action","presence","subscribe","SOMETHING@c.us"]`
`648.--34,,["query","bizCatalog",{"catalogWid":"SOMETHING@s.whatsapp.net","limit":10,"width":100,"height":100,"type":"get_product_catalog"}]`

**Comment by algoz098** [comment]
I have found how to query and send created products in a catalog:
```    conn.query({json: ["query","bizCatalog",{"catalogWid":"5516996114460@s.whatsapp.net","limit":999,"width":100,"height":100,"type":"get_product_catalog"}]})
    // conn.query({json: ["action","bizCatalog","get_product_catalog"]})
        .then(e => console.log('----\n', JSON.stringify(e, null, 2), '\n----'))
        .catch(e => console.error('----\n', e, '\n----'))````

Now, i did not found anything related to create a new product in a catalog. Is it even possible?

**Comment by adiwajshing** [comment]
If it can be created in WA Web, it can be done in Baileys

**Comment by algoz098** [comment]
Yes, it cant be handle by the default web client.

**Comment by athar21200** [comment]
Is there anyway to access already created products catalog and send it to chat?
