### ISSUE TITLE
[BUG] receivedPendingNotifications not working

### ISSUE THREAD

**Issue by luiscuriel** [adiwajshing/Baileys#1571]
All messages, chats, and updates that you get while offline are not received when connecting again the bot.

- Start baileys
- Store data to json file (works)
- Close Baileys
- Send messages to mobile device
- Start Baileys
- Read data from json file
- New received messages and updates never arrive...

**Comment by satriowicaksn** [comment]
has this issue been resolved? @luiscuriel
