### ISSUE TITLE
FATAL ERROR: JavaScript heap out of memory

### ISSUE THREAD

**Issue by Alhar6i** [adiwajshing/Baileys#1572]
**Describe the bug**
Please have a look at the JS stacktrace.

**To Reproduce**
1. Start the example.
2. Disable your connection to the internet so the example retries to reconnect while the internet is down!
3. Keep the example running so it tries to reconnect to the WA server several times.
4. wait for a while, the error 

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? Default as the example
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
<--- Last few GCs --->

[19844:000001CE79A3E910] 24068944 ms: Scavenge 3899.4 (4094.4) -> 3890.5 (4097.4) MB, 52.5 / 0.0 ms  (average mu = 0.283, current mu = 0.332) allocation failure
[19844:000001CE79A3E910] 24069067 ms: Scavenge 3902.1 (4097.4) -> 3892.9 (4101.4) MB, 99.0 / 0.0 ms  (average mu = 0.283, current mu = 0.332) allocation failure
[19844:000001CE79A3E910] 24069163 ms: Scavenge 3905.8 (4101.4) -> 3895.3 (4104.4) MB, 78.3 / 0.0 ms  (average mu = 0.283, current mu = 0.332) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF79EAB815F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114079
 2: 00007FF79EA454C6 DSA_meth_get_flags+65542
 3: 00007FF79EA4637D node::OnFatalError+301
 4: 00007FF79F37BA0E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF79F365FED v8::SharedArrayBuffer::Externalize+781
 6: 00007FF79F2093BC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF79F216069 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF79F21303A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF79F205C99 v8::internal::Heap::CollectGarbage+2137
10: 00007FF79F203E50 v8::internal::Heap::AllocateExternalBackingStore+2000
11: 00007FF79F221B60 v8::internal::FreeListManyCached::Reset+1408
12: 00007FF79F222215 v8::internal::Factory::AllocateRaw+37
13: 00007FF79F237ADF v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString+79
14: 00007FF79F01B1BD v8::internal::String::SlowFlatten+477
15: 00007FF79ED853CB v8::internal::WasmTableObject::Fill+603
16: 00007FF79F3857C6 v8::String::Utf8Length+22
17: 00007FF79EA65127 v8::internal::Malloced::operator delete+21383
18: 00007FF79F3363E6 v8::internal::Builtins::code_handle+172790
19: 00007FF79F335FD9 v8::internal::Builtins::code_handle+171753
20: 00007FF79F33629C v8::internal::Builtins::code_handle+172460
21: 00007FF79F336100 v8::internal::Builtins::code_handle+172048
22: 00007FF79F409801 v8::internal::SetupIsolateDelegate::SetupHeap+494673
23: 000001CE008361A0
error Command failed with exit code 134.

**Comment by VEXG** [comment]
try to increase the heap memory, u can search the tutorial in yt, these prob caused by session / ur storing a big object data to the memory storage

**Comment by ewar0401** [comment]
> > try to increase the heap memory, u can search the tutorial in yt, these prob caused by session / ur storing a big object data to the memory storage
> 
> I checked my store object size it was ~15 mb, thank you for your suggestion.

Hello, Can you share your solution? Best Regards.

**Comment by Rafaelknz** [comment]
Same here. I need a solution too

**Comment by VEXG** [comment]
> 

Note : if u use TS. Dont use ts-node for the production
