### ISSUE TITLE
adding built-in isOnline to avoid intensive tries to connect WhatsApp server

### ISSUE THREAD

**Issue by Alhar6i** [adiwajshing/Baileys#1574]
Hi,
When the internet connection becomes down. for any reason, Baileys tries to reconnect intensively.
The suggestion is that add a logic to test the internet status before trying to reconnect again.

**Comment by SheIITear** [comment]
Couldn't one implement it on their own code and kill the process if it keeps looping?

**Comment by Alhar6i** [comment]
> Couldn't one implement it on their own code and kill the process if it keeps looping?

Sure, everyone could.
The issue is expected to happen frequently so the suggested solution targets the issue's root.
