### ISSUE TITLE
[ASK] Mulitple Clients Simultaneously

### ISSUE THREAD

**Issue by imReCoder** [adiwajshing/Baileys#1576]
Can we run multiple whatsapp clients on same server, if yes how many clients can be run simultaneously? Can whatsapp ban for multiple clients from same ip address?

**Comment by tarikhagustia** [comment]
yes you can

**Comment by imReCoder** [comment]
> 

Thankyou you for reply.
Is there any problem if there will be like 100 clients login in same server?

**Comment by tarikhagustia** [comment]
> > 
> 
> Thankyou you for reply. Is there any problem if there will be like 100 clients login in same server?

Currently im running 50 instances in my server, the problem is huge memory usage

**Comment by marutichintan** [comment]
we are running 450 instance on a server. we are using pm2 to maintain all instance with memory limit to auto restart on high usage.

**Comment by imReCoder** [comment]
wow its cool.

**Comment by tarikhagustia** [comment]
> we are running 450 instance on a server. we are using pm2 to maintain all instance with memory limit to auto restart on high usage.

How much Ram usage for 450 Instance?

**Comment by marutichintan** [comment]
> 

Around 49 GB.

**Comment by AxeemHaider** [comment]
Isn't 49 GB is very expensive. If this is so expensive then why not Whatsapp Official Business API???

**Comment by ngadimin51** [comment]
> Isn't 49 GB is very expensive. If this is so expensive then why not Whatsapp Official Business API???

I think he selling service. 450 device with 49GB is usefull

**Comment by AxeemHaider** [comment]
> > Isn't 49 GB is very expensive. If this is so expensive then why not Whatsapp Official Business API???
> 
> I think he selling service. 450 device with 49GB is usefull

Still I think using WA API is less expensive than 49GB Memory, he can get more profit.
@marutichintan Can you please let us know where you hosted your application

**Comment by marutichintan** [comment]
> > > Isn't 49 GB is very expensive. If this is so expensive then why not Whatsapp Official Business API???
> > 
> > 
> > I think he selling service. 450 device with 49GB is usefull
> 
> Still I think using WA API is less expensive than 49GB Memory, he can get more profit. @marutichintan Can you please let us know where you hosted your application

WA API cost in India for sending message is 0.50 INR it too expensive. Dedicated Server from Hetzner

**Comment by binsarjr** [comment]
> we are running 450 instance on a server. we are using pm2 to maintain all instance with memory limit to auto restart on high usage.

are you using a proxy or not? did you not get banned for using multiple sessions (minimum 100 sessions) in 1 server?

**Comment by marutichintan** [comment]
1. I am using single proxy for user who want to send message to Unsaved Whatsapp no.
2. Other user are not allow to send message to new user or old chat is not available (without proxy).

**Comment by tarikhagustia** [comment]
> 1. I am using single proxy for user who want to send message to Unsaved Whatsapp no.
> 2. Other user are not allow to send message to new user or old chat is not available (without proxy).

is there any max connection from 1 server? currently i maintain 50 conn in 1 server

**Comment by zennn08** [comment]
> 1. I am using single proxy for user who want to send message to Unsaved Whatsapp no.
> 2. Other user are not allow to send message to new user or old chat is not available (without proxy).

Hi, I'm interested in your story and I want to ask you a few things. Can I have your email or discord for contact? Thankyou!

**Comment by AxeemHaider** [comment]
@marutichintan How you are managing node application in PM2 in cluster mode.
PM2 allow cluster mode for NodeJs application.
 If you are using cluster mode then how you are communicating between different cluster instance. Can you please let me know

**Comment by marutichintan** [comment]
> @marutichintan How you are managing node application in PM2 in cluster mode. PM2 allow cluster mode for NodeJs application. If you are using cluster mode then how you are communicating between different cluster instance. Can you please let me know

i am using folk mode. backend is on different server. backend will communicate with whatsapp instance using API and webhooks. whatsapp instance is identified using http port. Auth file and config file are store with port name. pm2 has API for start and manage process.

**Comment by AxeemHaider** [comment]
Thanks for your precious time.

**Comment by KILLYOUGUTSXXX** [comment]
hello bro, in here am using the baileys library, i don't know what is look normally sometime when my services is consuming memory until 700-900MB for 3-6 active user. maybe some people here had some an opinion for me. thank's  :v:

**Comment by AxeemHaider** [comment]
It's not normal, I don't think Baileys use such a huge memory.

**Comment by KILLYOUGUTSXXX** [comment]
> It's not normal, I don't think Baileys use such a huge memory.


emm am so confised now.
did you know bro, how to trace memory usage of every library running in service node js?

**Comment by AxeemHaider** [comment]
No, google it.

I think you are saving auth states in files and reading writing files is expansive tasks. Maybe you need to look at them

**Comment by KILLYOUGUTSXXX** [comment]
> No, google it.
> 
> I think you are saving auth states in files and reading writing files is expansive tasks. Maybe you need to look at them 

ya bro, true, i'm saving the auth to file, and when the state change it will rewrite to that's  file, does it gonna be a problem or maybe as a something bad ?

**Comment by AxeemHaider** [comment]
It can be, don't know how you are maintaining multiple clients by creating multiple Baileys instances or by creating multiple nodeJS instances?

**Comment by KILLYOUGUTSXXX** [comment]
i think am creating by Baileys instance, btw, this is my part of code, if u had a time to correct ma mistake :v:

**Create Folder /session & Define auth state into that's folder**
![image](https://user-images.githubusercontent.com/108051415/190297214-c3054e78-ffd6-4337-82c8-d849a2d20184.png)
![image](https://user-images.githubusercontent.com/108051415/190296126-e9476006-5174-4757-8090-f0efa0df4732.png)

**Write a session & some payload to folder that already created before**
![image](https://user-images.githubusercontent.com/108051415/190296371-e824ab86-09f5-4f83-92e5-9fa09c495796.png)

**The part of process which the connection is closed, it would be recursive the function, but if the status code reconnect from bailey send me as 401 will drop the session & completely remove the folder**
![image](https://user-images.githubusercontent.com/108051415/190296992-217403e8-a32b-4004-af93-c18b061f4b47.png)

**Comment by KILLYOUGUTSXXX** [comment]
for the additional informations, i'm using some of tech like : redis, socketio, postgres, mongoose.

and the features like : Auto reply, schedule message, blast message, etc.
