### ISSUE TITLE
[BUG] send location

### ISSUE THREAD

**Issue by erzacanz** [adiwajshing/Baileys#1578]
![Photo_1651873739398](https://user-images.githubusercontent.com/96880795/167220787-14a52ba1-9ecc-47ca-ae63-d5b3a9d7f8e0.png)

on normal Whatsapp the map image is not visible... but when on Whatsapp mod the map image is visible So how about?

**Comment by FatihArridho** [comment]
That's because WhatsApp has been updated so fake thumbnails can't be seen anymore except with a small resolution.
