### ISSUE TITLE
[BUG] BAGAIMANA CARA SAYA MENGATASINYA??

### ISSUE THREAD

**Issue by Bintangp02** [adiwajshing/Baileys#1579]
**Bagaimana cara saya mengatasinya??
Beri tahu saya**

**_#inglish_**
How do I solve it?? Let me know
```
=> In YUdiVA Al Faxxxxxxxxxxsel 120363xxxxx6260719@g.us
/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196
if (item.url.toString().startsWith('[http://'](http://%27/);) || item.url.toString().startsWith('[https://'](https://%27/);)) {
^
at Object.getStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18)
TypeError: Cannot read properties of undefined (reading 'toString')
at Object.encryptedStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44)
at Object.prepareWAMessageMedia (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132)
at Object.generateWAMessageContent (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:27)
at Object.generateWAMessage (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:68)
at Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:47)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at EventEmitter.<anonymous> (/index.js:157:32)
```
**Trimakasih**

**Comment by ravindu01manoj** [comment]
Use a direct link or a buffer to send media messages

**Comment by alanshalih** [comment]
ampung bang jago

**Comment by FatihArridho** [comment]
Hadeh

**Comment by Barqah-Xiex** [comment]
please send your script i will help you to fix it

tolong kirim naskah Anda, saya akan membantu Anda untuk memperbaikinya

**Comment by ngadimin51** [comment]
Pake direct link Pam Bro

> **Bagaimana cara saya mengatasinya?? Beri tahu saya**
> 
> **_#inglish_** How do I solve it?? Let me know
> 
> ```
> => In YUdiVA Al Faxxxxxxxxxxsel 120363xxxxx6260719@g.us
> /node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196
> if (item.url.toString().startsWith('[http://'](http://%27/);) || item.url.toString().startsWith('[https://'](https://%27/);)) {
> ^
> at Object.getStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18)
> TypeError: Cannot read properties of undefined (reading 'toString')
> at Object.encryptedStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44)
> at Object.prepareWAMessageMedia (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132)
> at Object.generateWAMessageContent (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:27)
> at Object.generateWAMessage (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:68)
> at Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:47)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at EventEmitter.<anonymous> (/index.js:157:32)
> ```
> 
> **Trimakasih**

Pake direct link Pak Bro. Kayanya itu localhost, jd ga bisa diakses dr luar linknya.
Kalau localhost pakai mediaStream ajah, di buffer.

**Comment by bkzutr90** [comment]
> please send your script i will help you to fix it
> 
> tolong kirim naskah Anda, saya akan membantu Anda untuk memperbaikinya

            } else if (txt == "mywaifu") {
                const hostt = "https://rest-beni.herokuapp.com"
                axios.get(hostt + "/api/randomimage/waifu").then(async function(response) {
                    const datas = await response.data;
                    const cok = datas.result
                    let dat = " Ini Waifu mu"
                        VHsendImageWithUrl(VHclient, from, cok, dat)
                }).catch(function(error) {
                    console.log(error);
                })
