### ISSUE TITLE
[ASK] How to test getMessage in MD

### ISSUE THREAD

**Issue by chimore** [adiwajshing/Baileys#1580]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues DONE ✅
2. Read through the readme at least once DONE ✅
3. Search the docs for the feature you're looking for DONE ✅

**Just describe the feature/question**

I've used my own implementation of Baileys Multidevice for over a month now, and I've seen the "Waiting for this message. This may take a while." appearing every now and then. Now that I'm trying to implement the `getMessage` method to resend messages from my "in memory store", I'm not able to trigger the bug.

Do you know a good way to trigger this bug, so I can get it fixed when it really happens?

In any case, if you do not know a way to do so, will you please tell if the parameter ´key´ that the `getMessage` method receives is an object containing something like the following?

```
"key": {
    "remoteJid": "12xxxxxxxxxxxxxxx8@g.us",
    "fromMe": true,
    "id": "BxxxxxxxxxxxxxxA"
}
```

I've included a log inside the ´getMessage´to see the content of the ´key´; however, as I cannot trigger this bug, this method is never called.

My socket declaration instance looks like this:

```
const sock = makeWASocket.default({
    ...(process.env.NODE_ENV === 'development' && { logger: logger }),
    printQRInTerminal: true,
    auth: state,
    version, 
    getMessage: async key => {
        console.log("-- RETYRING MESSAGE KEY --:")
        console.log(key);
        return {
            conversation: 'hello hello'
        }
    }
})
```

Any help would be really appreciated.

**Comment by picblog229** [comment]
I think this happens when you send first ever message to a number.

**Comment by picblog229** [comment]
This is the key format:
{
  remoteJid: 'xxxxx@s.whatsapp.net',
  id: 'BAE5692EA252DE23',
  fromMe: true,
  participant: 'xxxxx@s.whatsapp.net'
}

**Comment by chimore** [comment]
Thanks for sharing the key format @picblog229, that helps a lot!

On the other hand, this happens not only at sending first ever message to a number but also sporadically. However, if we are only sure that this happens when we first ever message to a number, would you recommend getting a new number and test this way or would this work if I delete all chat history on my phone and on the bot's store of an already known number?
