### ISSUE TITLE
Request send photo, video, gif, and text to status@broadcast

### ISSUE THREAD

**Issue by FatihArridho** [adiwajshing/Baileys#1583]
I just hope baileys can upload it to status, thank you.

**Comment by sorosons** [comment]
if there is a way i also want to know fellow it :)

**Comment by FaizBastomi** [comment]
ask WhatsApp, when will multi-device support upload to WhatsApp status

**Comment by FatihArridho** [comment]
> ask WhatsApp, when will multi-device support upload to WhatsApp status

Ya namanya juga beta bang jadi ada kekurangannya, mau nanya ke whatsapp pasti dia slowrespon:(
