### ISSUE TITLE
how to find out someone else's name by id in MD version?

### ISSUE THREAD

**Issue by Barqah-Xiex** [adiwajshing/Baileys#1584]
in the old version, namely version 3.5.3
the method
conn.contacts[iduser] != undefined ? conn.contacts[iduser].vname || conn.contacts[iduser].notify : "Anonymous"

then how to use it in the current version?

**Comment by zennn08** [comment]
```javascript
const { makeInMemoryStore } = require("@adiwajshing/baileys")
const store = makeInMemoryStore({ })
function getName(id) {
return store.contacts[id]?.notify || "Anonymous"
}
```
