### ISSUE TITLE
I try install from NPM or Yarn but nothing works

### ISSUE THREAD

**Issue by reinforcers** [adiwajshing/Baileys#1585]
I want to install on new server this what I got

$ yarn add @adiwajshing/baileys
yarn add v1.22.18
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

$ npm i @adiwajshing/baileys
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-09T03_16_04_859Z-debug-0.log

edit: these are using Rocky Linux 8. but in my own PC with Ubuntu 20.04 installed normally

edit:  I try `npm i @adiwajshing/baileys@3` it install v3.5.3 normally

**Comment by AkirahX** [comment]
Do you have git installed?

**Comment by reinforcers** [comment]
> Do you have git installed?

no I don't

**Comment by reinforcers** [comment]
I Install git and problem fixed. tks.
