### ISSUE TITLE
Closing session: SessionEntry Removing old closed session

### ISSUE THREAD

**Issue by phenriquec** [adiwajshing/Baileys#1589]
Hi,

I have a situation where this message appears after connect and doesn't disappear anymore, apparently in a loop!

does anyone know the reason?

09/05/2022 11:15:11 Closing session: SessionEntry {
  _chains: {
    BbHoTRLL0giFLDtD9egTL6VxQhCJBO13EfdjX8HOGTRk: { chainKey: [Object], chainType: 2, messageKeys: {} },
    'BZiCBY0E8LSXMvGdeeGT5hWLU5f3jVis35i/XPfWhTd2': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 589168037,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 98 82 05 8d 04 f0 b4 97 32 f1 9d 79 e1 93 e6 15 8b 53 97 f7 8d 58 ac df 98 bf 5c f7 d6 85 37 76>,
      privKey: <Buffer 98 20 32 b8 8e 18 a3 c4 87 b7 63 a4 5d e9 a9 c0 93 3b f5 50 cb 76 01 b9 dd a7 18 f6 6f dd ad 49>
    },
    lastRemoteEphemeralKey: <Buffer 05 b1 e8 4d 12 cb d2 08 85 2c 3b 43 f5 e8 13 2f a5 71 42 10 89 04 ed 77 11 f7 63 5f c1 ce 19 34 64>,
    previousCounter: 0,
    rootKey: <Buffer 52 57 6e 9f d0 a8 b5 3e 10 b0 29 cf dd 95 43 5a c8 50 8b 97 9f f1 24 50 1f 9f 19 7f 66 a5 cd d3>
  },
  indexInfo: {
    baseKey: <Buffer 05 74 18 94 c5 25 b3 4c 45 82 f7 48 2b 5d fb cc c4 1c 03 74 96 57 f6 b6 90 9b 23 e1 04 73 29 32 41>,
    baseKeyType: 2,
    closed: -1,
    used: 1652105710807,
    created: 1652105710807,
    remoteIdentityKey: <Buffer 05 b3 67 1b 3b df 22 9a f2 01 d1 1e f2 ef ff 43 f9 56 f4 57 36 13 da 34 d6 62 4d d9 68 94 1d 9b 50>
  }
}

09/05/2022 11:15:10 Removing old closed session: SessionEntry {
  _chains: {
    'BfTD9OQ9vBW+/AMsmGyk7EJ7yxrISEaJ4uocmCXD7WYM': { chainKey: [Object], chainType: 2, messageKeys: {} },
    'BV5S1BdcJiXVT7ykCpRqR79a/osASNABzdEQs94sB9ZN': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 589168037,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 5e 52 d4 17 5c 26 25 d5 4f bc a4 0a 94 6a 47 bf 5a fe 8b 00 48 d0 01 cd d1 10 b3 de 2c 07 d6 4d>,
      privKey: <Buffer e8 8c 79 6d 9a 47 67 72 88 76 76 be 14 69 bf 8d fc bc 14 7d cb e6 a5 1f 2e fa 46 8f 82 55 3b 45>
    },
    lastRemoteEphemeralKey: <Buffer 05 f4 c3 f4 e4 3d bc 15 be fc 03 2c 98 6c a4 ec 42 7b cb 1a c8 48 46 89 e2 ea 1c 98 25 c3 ed 66 0c>,
    previousCounter: 0,
    rootKey: <Buffer 3c 24 22 9b 20 de e7 50 1c b7 4b f0 3b c3 0e c0 a0 4d f5 81 0d 6a 1c db a6 51 0a 56 da 70 6f 6f>
  },
  indexInfo: {
    baseKey: <Buffer 05 93 e6 b1 24 f9 25 ba 1e 1f 53 e5 7c 08 06 77 48 84 2c 89 bd 4b e7 44 db 5a 24 42 7c d0 42 31 1c>,
    baseKeyType: 2,
    closed: 1652105703683,
    used: 1652105703470,
    created: 1652105703470,
    remoteIdentityKey: <Buffer 05 b3 67 1b 3b df 22 9a f2 01 d1 1e f2 ef ff 43 f9 56 f4 57 36 13 da 34 d6 62 4d d9 68 94 1d 9b 50>
  }
}

**Comment by tiesco238** [comment]
same here

**Comment by andreyrafah** [comment]
the same here

**Comment by enoksaju** [comment]
same here

**Comment by Zedmerlol** [comment]
same here, any solution?

**Comment by enoksaju** [comment]
+1

**Comment by enoksaju** [comment]
Not solved

**Comment by guilhermeromer** [comment]
Any updates?

**Comment by Hiarley** [comment]
+1
