### ISSUE TITLE
Always Online Presence

### ISSUE THREAD

**Issue by ngadimin51** [adiwajshing/Baileys#1591]
How to get ping pong from other whatsapp?

My account always showing "online" from other whatsapp.
I try to put in the script like this

sock.ev.on('messages.upsert', async m => {
     await sock.sendPresenceUpdate('unavailable', remoteJid) 
}

And my account presence set to unavailable, it's work, my account not showing online again.
But how to set this to unavailable from start connection?

I need this to avoid my girl says 'Why you always on and not replying my message'? 😅

**Comment by textarea** [comment]
> I need this to avoid my girl says 'Why you always on and not replying my message'? 😅

same here 😂

**Comment by ngadimin51** [comment]
> You can add `await sock.sendPresenceUpdate('unavailable', remoteJid)` into handler `'connection.update'` with `'connection' === 'open'`

remoteJid is target, isn't right?
Or remoteJid is our WA number?

**Comment by ngadimin51** [comment]
> > I need this to avoid my girl says 'Why you always on and not replying my message'? 😅
> 
> same here 😂

Cause it can messing our's relationship 🤣🤣🤣🤣

**Comment by ChCh27** [comment]
> remoteJid is target, isn't right?
Is optional, but .. it's not enought to add into `connection.update` because status is restored.
I've added also into `messages.upsert` handler and now it's ok.

**Comment by ngadimin51** [comment]
> > remoteJid is target, isn't right?
> 
> Is optional, but .. it's not enought to add into `connection.update` because status is restored. I've added also into `messages.upsert` handler and now it's ok.

if i want to set 'unavailable' to all of people who want to chat me, how to find remoteJid if I not save the number?
When use message.upsert we can find from key.

But how if before we get message.upsert to set 'unavailable'?

**Comment by yuvalwarsh** [comment]
> 

can you share the full code you added?

**Comment by yuvalwarsh** [comment]
> > remoteJid is target, isn't right?
> 
> Is optional, but .. it's not enought to add into `connection.update` because status is restored. I've added also into `messages.upsert` handler and now it's ok.

can you share the full code you added?
