### ISSUE TITLE
Link preview don't work

### ISSUE THREAD

**Issue by rajuaryan21** [adiwajshing/Baileys#1592]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
I have npm install link-preview-js but still link previews are not being generated for my text messages. Can you guide me why is it so? I am using MD.

**Comment by imReCoder** [comment]
same problem, did you able to solve it ?

**Comment by imReCoder** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature/question** I have npm install link-preview-js but still link previews are not being generated for my text messages. Can you guide me why is it so? I am using MD.

Hey did you solved the problem.If yes, please could you share ?

**Comment by manojsitapara** [comment]
+1

**Comment by itmor** [comment]
ты решил?
