### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by ninegrafh** [adiwajshing/Baileys#1595]
TypeError: Cannot read property 'toString' of undefined

please helpme solution
![image](https://user-images.githubusercontent.com/41564272/167542163-68d2dae3-ed99-4a05-96cf-5856efd1bdb1.png)

**Comment by AkirahX** [comment]
You probably tried to read the QRcode of Baileys version 3.5.3 with the beta version active in the app.

**Comment by ninegrafh** [comment]
> You probably tried to read the QRcode of Baileys version 3.5.3 with the beta version active in the app.

yess,,any solution?

**Comment by AkirahX** [comment]
> > You probably tried to read the QRcode of Baileys version 3.5.3 with the beta version active in the app.
> 
> yess,,any solution?

Exit beta or upgrade your system to Baileys version 4.0+.
