### ISSUE TITLE
[BUG] how to fix bad request 400?

### ISSUE THREAD

**Issue by re-Destro** [adiwajshing/Baileys#1596]
**Environment (please complete the following information):**
 - Is this on a server? Yes 
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No
 - -

```
const {
    makeWALegacySocket,
    useSingleFileAuthState,
    DisconnectReason,
} = require("@adiwajshing/baileys")
const { Boom } = require("@hapi/boom")
const {
    state,
    saveState
} = useSingleFileAuthState("./authInfo/session.json")


function webBot(args){
    const sock = makeWALegacySocket({
        auth: state,
        printQRInTerminal: true
    });

    sock.ev.on("creds.update", saveState);
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = new Boom(lastDisconnect?.error)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                webBot()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
}

webBot()

```

the problem is only happen when i use ``auth: state``

**Comment by re-Destro** [comment]
i got output like this in my terminal: 

``"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"Unexpected status in 'admin': Bad Request(400)"}``

**Comment by AkirahX** [comment]
CodePost your code, we can't help without knowing where you went wrong.

**Comment by re-Destro** [comment]
> Post your code, we can't help without knowing where you went wrong.

`const {
    makeWALegacySocket,
    useSingleFileAuthState,
    DisconnectReason,
    Browsers
} = require("@adiwajshing/baileys")
const { Boom } = require("@hapi/boom")
const {
    state,
    saveState
} = useSingleFileAuthState("./authInfo/session.json")


function webBot(args){
    const sock = makeWALegacySocket({
        auth: state,
        printQRInTerminal: true
    });
    
    sock.ev.on("creds.update", saveState);
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = new Boom(lastDisconnect?.error)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                webBot()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
}

webBot()
`

**Comment by re-Destro** [comment]
> Post your code, we can't help without knowing where you went wrong.

this problem is only happen when i use ``auth: state``

**Comment by ngadimin51** [comment]
May your connection is logged out from device.

**Comment by re-Destro** [comment]
> May your connection is logged out from device.

It's still not even logged in and scan QR code yet. The problem appear when i start the bot with 'node server.js'

**Comment by ngadimin51** [comment]
> > May your connection is logged out from device.
> 
> It's still not even logged in and scan QR code yet. The problem appear when i start the bot with `node server.js`

Delete credentials

**Comment by ikbalardiansah** [comment]
I just got new same error, how do you solving it?
