### ISSUE TITLE
[BUG] getaddrinfo ENOTFOUND web.whatsapp.net

### ISSUE THREAD

**Issue by ChCh27** [adiwajshing/Baileys#1597]
Sometimes I get `getaddrinfo ENOTFOUND web.whatsapp.net` error when downloading media.
As I can see I get stickerMessages with such content `"message":{"stickerMessage":{"url":"https://web.whatsapp.net",`.
Only some accounts are affected and only stickerMessages.

What can I do to be able to download this stickerMessages?

**Comment by jpamorimdev** [comment]
Same issue here, it's weird, sometimes it comes with the URL https://web.whatsapp.net and 
the `downloadContentFromMessage` function isn't able to download the file, I solved here overriding the URL key in `proto.Message.IStickerMessage` by the concat of "https://mmg.whatsapp.net" and `directPath` key in the object.

Example:
`
if (stickerMessage?.url === "https://web.whatsapp.net") stickerMessage.url = "https://mmg.whatsapp.net" + stickerMessage?.directPath;
`

I'm doing this and it's working for me now, hope it helps someone

**Comment by zhinea** [comment]
@ChCh27 you solved this?

**Comment by ChCh27** [comment]
> @ChCh27 you solved this?

No

**Comment by dsandrade** [comment]
I fixed with this code:

```
if (msgType === 'sticker') {
    msg.url = 'https://pps.whatsapp.net' + msg.directPath
}
```

**Comment by zhinea** [comment]
> I fixed with this code:
> 
> ```
> if (msgType === 'sticker') {
>     msg.url = 'https://pps.whatsapp.net' + msg.directPath
> }
> ```

Only wrong on web version sticker send, in mobile is fine

**Comment by jpamorimdev** [comment]
> > @ChCh27 you solved this?
> 
> No

May take a look at #2122

**Comment by zhinea** [comment]
> I fixed with this code:
> 
> ```
> if (msgType === 'sticker') {
>     msg.url = 'https://pps.whatsapp.net' + msg.directPath
> }
> ```

solved. Thank you
