### ISSUE TITLE
add contact

### ISSUE THREAD

**Issue by mrhb6006** [adiwajshing/Baileys#1599]
Hello
Thank you for your good project
Is there a way to add a contact with this code?
Or is there a way to find out  a phone number is a WhatsApp member?

**Comment by fadiinho** [comment]
You can use this:
```js
const id = '123456'
const [result] = await sock.onWhatsApp(id)
if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)
```
[See on the readme](https://github.com/adiwajshing/Baileys#misc)

**Comment by mrhb6006** [comment]
thanks a lot
