### ISSUE TITLE
Get the string that generate the QR code

### ISSUE THREAD

**Issue by brunon80** [adiwajshing/Baileys#16]
Hi,
Thanks again for this awesome project!

I'm creating this issue to ask you if you could make the string that generate the QR code avaiable on client instance or in other way (could be a function).

for example:
I would like to call the connect function, then the string that is used to generate the QR code stay in the client instance, so I can use like this:

`client.strConnection` // here is the string: ref + "," + publicKeyStr + "," + this.authInfo.clientID
or it could be on a function
`const strConnection = await client.getStrConnection()` 

So I can otherwise generate the qr code

**Comment by adiwajshing** [comment]
Has been added in the latest commit. Now you can bypass the default QR generation code using:

``` javascript
client.onReadyForPhoneAuthentication = ([ref, publicKey, clientID]) => {
    const str = ref + "," + publicKey + "," + clientID
    // generate QR with str
}
```

**Comment by brunon80** [comment]
Thanks!

**Comment by jzvi12** [comment]
Do you have the full snippet for generating and saving the QR code as a picture (png) locally?
