### ISSUE TITLE
user agent

### ISSUE THREAD

**Issue by mrhb6006** [adiwajshing/Baileys#1600]
Is there a way to change the user agent?
Currently in the Active Devices section, the phrase (Chrome
Baileys-) is observed. Is there a way to change that? For example (Chrome - linux) or (firefox-windows)

**Comment by catabozan** [comment]
```typescript
makeWASocket({
        browser: ['Linux', 'Chrome', '10.15.7'], // here
    })
```

**Comment by mrhb6006** [comment]
thanks a lot
