### ISSUE TITLE
How to resend a button message with the getMessage() function

### ISSUE THREAD

**Issue by textarea** [adiwajshing/Baileys#1601]
I'm already using the getMessage() [solves the "this message can take a while" issue]  function to resend text messages 
```
return {
  conversation: 'lorem ipsum...'
}
```
how to resend a button message?
thanks

**Comment by adarsh-chakraborty** [comment]
Can you share code how did you fix this message can take a while" issue please

**Comment by textarea** [comment]
I did not fix that issue.
With many devices connected I still have sometimes the message "can take a while".
Also I'm getting often the message "will not send message again, as sent too many times" after retring send the message with the getMessage() function and I don't really know how many messages get delivered with that function.

**Comment by textarea** [comment]
Leave here for future looks:

`return {
    buttonsMessage: {
        "to": "xxxxxxx",
        "message": {
            "text": "Lorem ipsum",
            "buttons": [
                {
                    "buttonId": "yes_button",
                    "buttonText": {
                        "displayText": "Yes"
                    },
                    "type": 1
                },
                {
                    "buttonId": "no_button",
                    "buttonText": {
                        "displayText": "No"
                    },
                    "type": 1
                }
            ],
            "headerType": 1
        }
    }
}`
