### ISSUE TITLE
[BUG] TOLONG SAYAAA !!!

### ISSUE THREAD

**Issue by Mmarjann** [adiwajshing/Baileys#1602]
D:\whabot\index.js:6
        const sock = makeWASocket({
              ^^^^

SyntaxError: Unexpected identifier
←[90m    at Object.compileFunction (node:vm:352:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1033:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1069:2
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[3
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:
←[90m    at Function.executeUserEntryPoint [as runMain] (node:intern
m
←[90m    at node:internal/main/run_main_module:17:47←[39m

My Code :
const { makeWASocket, useSingleFileAuthState, DisconnectReason  } = require('@adiwajshing/baileys');
const { Boom } = require('@hapi/boom');
const { state, saveState } = useSingleFileAuthState("./bot-session.json");

const startBot = {
	const sock = makeWASocket({
		printQRInTerminal: true,
		auth: state
	});	
	sock.ev.on("creds.update", saveState);
	sock.ev.on("connection.update", (up)=> {
		const {lastDisconnect, connection} = up;
		if(connection){
			console.log("connection status: "+connection);
		}
		if(connection =="close") {
			let reason = new Boom(lastDisconnect?.error)?.output?.statusCode;
			console.log(reason);
		}
	});
}

	

startBot();

**Comment by Barqah-Xiex** [comment]
ini yang di wa ?
jerrrr


ini gw ownr brainxiex cek
http://xiex.my.id

**Comment by BochilGaming** [comment]
That isn't bug from baileys but syntax from your code, pls learn javascript first
```js
function startBot() {
  const sock = makeWASocket({
printQRInTerminal: true,
auth: state
});
sock.ev.on("creds.update", saveState);
sock.ev.on("connection.update", (up)=> {
const {lastDisconnect, connection} = up;
if(connection){
console.log("connection status: "+connection);
}
if(connection =="close") {
let reason = new Boom(lastDisconnect?.error)?.output?.statusCode;
If (reason && reason != DisconnectReason.loggedOut) startBot()
console.log(reason);
}
})
}
startBot()
```

**Comment by Barqah-Xiex** [comment]
const startBot = () => {
const sock = makeWASocket({
printQRInTerminal: true,
auth: state
});
sock.ev.on("creds.update", saveState);
sock.ev.on("connection.update", (up)=> {
const {lastDisconnect, connection} = up;
if(connection){
console.log("connection status: "+connection);
}
if(connection =="close") {
let reason = new Boom(lastDisconnect?.error)?.output?.statusCode;
console.log(reason);
}
});
}

startBot();

**Comment by DwiRizqiH** [comment]
> ini yang di wa ? jerrrr
> 
> ini gw ownr brainxiex cek http://xiex.my.id

hello, do you have an Indonesian bot developer group? I want to join to ask questions
sorry off topic

**Comment by Mmarjann** [comment]
> ini yang di wa ? jerrrr
> 
> ini gw ownr brainxiex cek http://xiex.my.id
