### ISSUE TITLE
[BUG] Closing stale open session for new outgoing prekey bundle

### ISSUE THREAD

**Issue by guilhermeromer** [adiwajshing/Baileys#1603]
**Describe the bug**
I am receiving these **Closing stale open session for new outgoing prekey bundle**  followed by

```
Closing session: SessionEntry {
_chains: {
  'BU/xVLohjhTgeRXJCpoqI2cQquF833jzngPnV+PxOd0n': { chainKey: [Object], chainType: 1, messageKeys: {} }
},
registrationId: 89,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 4f f1 54 ba 21 8e 14 e0 79 15 c9 0a 9a 2a 23 67 10 aa e1 7c df 78 f3 9e 03 e7 57 e3 f1 39 dd 27>,
      privKey: <Buffer e0 9c 6a 74 72 6e f4 59 49 44 3a b2 78 4d 6f 84 2a 13 71 aa 52 63 6e af 22 57 2d 9a 2c 98 42 49>
    },
    lastRemoteEphemeralKey: <Buffer 05 8e 0f f5 31 0d 5d 8f 08 2f ee f3 2d e6 57 aa e5 ee f3 e7 6b 16 e4 2d c8 47 52 08 ef 45 60 33 07>,
    previousCounter: 0,
    rootKey: <Buffer cc 9e 0d f6 11 96 4f 24 ae 69 41 63 3b ae 30 21 3f d3 33 76 c8 be 01 ca ee 1d 4f d1 b1 f5 a8 b3>
  },
  indexInfo: {
    baseKey: <Buffer 05 0a 2b 39 41 d6 ae 00 6e e7 39 59 b6 2e 9d 6d d9 3a 0d 91 88 6c aa 0d ba 48 b5 7f 38 89 37 6b 3a>,
    baseKeyType: 1,
    closed: -1,
    used: 1652194935096,
    created: 1652194935096,
    remoteIdentityKey: <Buffer 05 05 db c1 d3 22 7e 59 71 36 32 86 a1 c3 29 4e a7 f9 0a 2f 67 43 8c a9 0a 7f 9a 49 50 58 f4 38 79>
  },
  pendingPreKey: {
    signedKeyId: 1,
    baseKey: <Buffer 05 0a 2b 39 41 d6 ae 00 6e e7 39 59 b6 2e 9d 6d d9 3a 0d 91 88 6c aa 0d ba 48 b5 7f 38 89 37 6b 3a>
  }
}
```

Is spamming on the console. I already tried to update Baileys.

I am also facing a problem sending messages in groups that have more than 100 people. I don't know if it is related, but started with this spamming. The error that I am receiving is: 

```
Error: Timed Out
    at /var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:170:32
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7) {
  data: {
    stack: 'Error\n' +
      '    at Object.promiseTimeout (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:165:19)\n' +
      '    at waitForMessage (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:108:42)\n' +
      '    at query (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:131:22)\n' +
      '    at assertSessions (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:203:34)\n' +
      '    at sendMessagesAgain (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:235:15)\n' +
      '    at async /var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:303:29'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
```

And sometimes followed by this

```
{
connection: 'close',
lastDisconnect: {
  error: Error: Stream Errored (xml-not-well-formed)
      at WebSocket.<anonymous> (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:430:13)
      at WebSocket.emit (node:events:527:28)
      at WebSocket.emit (node:domain:475:12)
      at /var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:228:35
      at Object.decodeFrame (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:142:17)
      at WebSocket.onMessageRecieved (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:204:15)
      at WebSocket.emit (node:events:527:28)
      at WebSocket.emit (node:domain:475:12)
      at Receiver.receiverOnMessage (/var/www/api-whatsapp-md/node_modules/ws/lib/websocket.js:1098:20)
      at Receiver.emit (node:events:527:28) {
    data: [Object],
    isBoom: true,
    isServer: true,
    output: [Object]
  },
  date: 2022-05-11T14:46:09.063Z
}
} {
  statusCode: 500,
  error: 'Internal Server Error',
  message: 'An internal server error occurred'
}
```

I really don't know is those are related to the **Closing stale open session for new outgoing prekey bundle**, but it started after I realized this.

My connection options looks like this:

```
    sock = makeWASocket({
              printQRInTerminal: false,
              browser: ['blablabla', 'Chrome', '3.0'],
              auth: await this.loadState(),
              logger: P({ level: 'error' }),
              defaultQueryTimeoutMs: undefined
          });
```

Could someone give me a light on this?

**Comment by Zedmerlol** [comment]
I have the same problem:

Closing open session in favor of incoming prekey bundle
 Closing session: SessionEntry {
   _chains: {
     'BRmM62Szyk+6Q6DBNEC7n7GPbDvW92dSUyPczLmXJrVm': { chainKey: [Object], chainType: 2, messageKeys: {} },
     Bd8FBGGXSPtkkZnU2He6RQTS2GVpQKCc6cV5xxjgQNRc: { chainKey: [Object], chainType: 1, messageKeys: {} }
   },
   registrationId: 1102308842,
   currentRatchet: {
     ephemeralKeyPair: {
       pubKey: <Buffer 05 df 05 04 61 97 48 fb 64 91 99 d4 d8 77 ba 45 04 d2 d8 65 69 40 a0 9c e9 c5 79 c7 18 e0 40 d4 5c>,
       privKey: <Buffer 30 61 1a 26 ec 86 85 f0 18 d4 f5 66 90 b7 ea 75 0e 9c e3 f2 c2 11 85 b1 f6 3a 94 93 55 fb 39 5a>
     },
     lastRemoteEphemeralKey: <Buffer 05 19 8c eb 64 b3 ca 4f ba 43 a0 c1 34 40 bb 9f b1 8f 6c 3b d6 f7 67 52 53 23 dc cc b9 97 26 b5 66>,
     previousCounter: 0,
     rootKey: <Buffer d8 ff 7c ff 43 8a dc 30 d3 27 31 af a1 ea 2a 61 a8 15 24 43 90 c0 82 2a 62 ab 9e a2 e8 4e 0c fe>
   },
   indexInfo: {
     baseKey: <Buffer 05 0d f3 9d 49 75 f4 e6 66 f8 43 cc 59 78 ec 39 ce 43 2f 8d 53 6e 1d 8b 50 c8 8e 34 45 1d 85 74 52>,
     baseKeyType: 2,
     closed: -1,
     used: 1652286470792,
     created: 1652286470792,
     remoteIdentityKey: <Buffer 05 e0 d5 89 7d 20 12 92 fe 04 21 05 cb 87 70 bd bd dc a5 25 3b a3 d7 c6 53 38 1b 28 49 79 44 79 09>
   }
 }
 Removing old closed session: SessionEntry {
   _chains: {
     'BfUyLC9ncKlG5l2p3MBsTHFu0s0ezZBbjRI7+5A1POU6': { chainKey: [Object], chainType: 2, messageKeys: {} },
     BYUXdWQe9m48j5G0jKZtekgJdrfXmeJPBn1eVO4p0aFj: { chainKey: [Object], chainType: 1, messageKeys: {} }
   },
   registrationId: 1102308842,
   currentRatchet: {
     ephemeralKeyPair: {
       pubKey: <Buffer 05 85 17 75 64 1e f6 6e 3c 8f 91 b4 8c a6 6d 7a 48 09 76 b7 d7 99 e2 4f 06 7d 5e 54 ee 29 d1 a1 63>,
       privKey: <Buffer 08 78 3a 96 c4 79 7f ad 2a 34 ac cb 08 b3 10 a0 a3 22 b9 bf a3 23 cb 28 8e 0f 8b 28 e3 50 75 6a>
     },
     lastRemoteEphemeralKey: <Buffer 05 f5 32 2c 2f 67 70 a9 46 e6 5d a9 dc c0 6c 4c 71 6e d2 cd 1e cd 90 5b 8d 12 3b fb 90 35 3c e5 3a>,
     previousCounter: 0,
     rootKey: <Buffer a5 01 eb 2d 96 a1 92 e3 55 e8 1f 82 04 66 77 95 6f 70 f5 06 bc 80 76 8b b7 49 95 1c 4d bb 9d 11>
   },
   indexInfo: {
     baseKey: <Buffer 05 1f 4a 1e f4 6f fc 6c 53 c2 cc 2b 36 c2 5c 84 8a 2a cb de 0c 6f fb 41 bc 74 23 af 71 a1 8c 91 50>,
     baseKeyType: 2,
     closed: 1652286458107,
     used: 1652286457944,
     created: 1652286457944,
     remoteIdentityKey: <Buffer 05 e0 d5 89 7d 20 12 92 fe 04 21 05 cb 87 70 bd bd dc a5 25 3b a3 d7 c6 53 38 1b 28 49 79 44 79 09>
   }
 }

**Comment by enoksaju** [comment]
+1

**Comment by tarikhagustia** [comment]
+1

**Comment by vishwajit76** [comment]
same problem

**Comment by 4relial** [comment]
+1

**Comment by enoksaju** [comment]
any update?

**Comment by Zedmerlol** [comment]
> any update?

Delete node_modules/@adowajshing
Then `npm install @adiwajshing/baileys`
This will make get baileys with the version 4.2.0 from npm (this works for me, 12 hours have passed without getting the error)

**Comment by bigbangshop** [comment]
doing the procedure of deleting the node_modules directory the error continues to occur when the first message is sent. in the others the error no longer occurs, but the messages sent by bayles still do not appear in the web version

**Comment by HoshenKadosh** [comment]
same issue with large groups

**Comment by bigbangshop** [comment]
I noticed that this message always appears before the error when I activate the log "fetching sessions"
I believe the key is not being updated

{"level":20,"time":1652467013200,"pid":18,"hostname":"api-163","jidsRequiringFetch":["553197171324:3@s.whatsapp.net"],"msg":"fetching sessions"}


Closing stale open session for new outgoing prekey bundle

**Comment by enoksaju** [comment]
> doing the procedure of deleting the node_modules directory the error continues to occur when the first message is sent. in the others the error no longer occurs, but the messages sent by bayles still do not appear in the web version

same here


i test with v4.0.0-md and only first message sent to unknown number is not shown

**Comment by enoksaju** [comment]
Any news?

**Comment by Jmallone** [comment]
> > any update?
> 
> Delete node_modules/@adiwajshing Then `npm install @adiwajshing/baileys` This will make get baileys with the version 4.1.0 from npm (this works for me, 12 hours have passed without getting the error)
> 
> Credits: Wender (Discord)

Works well for me

thanks

**Comment by rajuaryan21** [comment]
> doing the procedure of deleting the node_modules directory the error continues to occur when the first message is sent. in the others the error no longer occurs, but the messages sent by bayles still do not appear in the web version

Yes,this is happening to many of the users.

**Comment by adarsh-chakraborty** [comment]
any fixes?

**Comment by Zedmerlol** [comment]
> I've tried this and It works for a while, but after some time connected it starts all over again the spamming...

Me too but works anyway for me, I still don't find another solution

**Comment by guilhermeromer** [comment]
> Guys.. see example and implement yourself
> 
> https://github.com/adiwajshing/Baileys/blob/85a58fbc10caa92e726044336a7e6ff3f562fc62/Example/example.ts#L39
> 
> you need to implement makeInMemoryStore() which is all chats, contacts & message will be saved.. from there we can lookup message to resend back when this problem occurs

I have already tried to implement the makeInMemoryStore() method and to be honest it kinda helped a little because this method prevent the storage to be writed all the time, but still didn't fixed the spamming... I tried to use the example file only to check if I could had a bug in my custom code, but even in the example file I still have this issue. I still don't have any clue of why this is happening, I only know that it could be related to the libsignal library. 😞

**Comment by jeffersonveloso** [comment]
Hello guys check this issue #1631

**Comment by guilhermeromer** [comment]
> Hello guys check this issue #1631

I actually tried to do some tips that you guys mentioned in this topic, but still didn't helped much. You got any results?

**Comment by jeffersonveloso** [comment]
> > Hello guys check this issue #1631
> 
> I actually tried to do some tips that you guys mentioned in this topic, but still didn't helped much. You got any results?

Yes bro, this solution worked for me.

**Comment by guiguicdd** [comment]
Any update?

**Comment by SamPandey001** [comment]
> **Describe the bug** I am receiving these **Closing stale open session for new outgoing prekey bundle** followed by
> 
> ```
> Closing session: SessionEntry {
> _chains: {
>   'BU/xVLohjhTgeRXJCpoqI2cQquF833jzngPnV+PxOd0n': { chainKey: [Object], chainType: 1, messageKeys: {} }
> },
> registrationId: 89,
>   currentRatchet: {
>     ephemeralKeyPair: {
>       pubKey: <Buffer 05 4f f1 54 ba 21 8e 14 e0 79 15 c9 0a 9a 2a 23 67 10 aa e1 7c df 78 f3 9e 03 e7 57 e3 f1 39 dd 27>,
>       privKey: <Buffer e0 9c 6a 74 72 6e f4 59 49 44 3a b2 78 4d 6f 84 2a 13 71 aa 52 63 6e af 22 57 2d 9a 2c 98 42 49>
>     },
>     lastRemoteEphemeralKey: <Buffer 05 8e 0f f5 31 0d 5d 8f 08 2f ee f3 2d e6 57 aa e5 ee f3 e7 6b 16 e4 2d c8 47 52 08 ef 45 60 33 07>,
>     previousCounter: 0,
>     rootKey: <Buffer cc 9e 0d f6 11 96 4f 24 ae 69 41 63 3b ae 30 21 3f d3 33 76 c8 be 01 ca ee 1d 4f d1 b1 f5 a8 b3>
>   },
>   indexInfo: {
>     baseKey: <Buffer 05 0a 2b 39 41 d6 ae 00 6e e7 39 59 b6 2e 9d 6d d9 3a 0d 91 88 6c aa 0d ba 48 b5 7f 38 89 37 6b 3a>,
>     baseKeyType: 1,
>     closed: -1,
>     used: 1652194935096,
>     created: 1652194935096,
>     remoteIdentityKey: <Buffer 05 05 db c1 d3 22 7e 59 71 36 32 86 a1 c3 29 4e a7 f9 0a 2f 67 43 8c a9 0a 7f 9a 49 50 58 f4 38 79>
>   },
>   pendingPreKey: {
>     signedKeyId: 1,
>     baseKey: <Buffer 05 0a 2b 39 41 d6 ae 00 6e e7 39 59 b6 2e 9d 6d d9 3a 0d 91 88 6c aa 0d ba 48 b5 7f 38 89 37 6b 3a>
>   }
> }
> ```
> 
> Is spamming on the console. I already tried to update Baileys.
> 
> I am also facing a problem sending messages in groups that have more than 100 people. I don't know if it is related, but started with this spamming. The error that I am receiving is:
> 
> ```
> Error: Timed Out
>     at /var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:170:32
>     at runMicrotasks (<anonymous>)
>     at runNextTicks (node:internal/process/task_queues:61:5)
>     at listOnTimeout (node:internal/timers:528:9)
>     at processTimers (node:internal/timers:502:7) {
>   data: {
>     stack: 'Error\n' +
>       '    at Object.promiseTimeout (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:165:19)\n' +
>       '    at waitForMessage (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:108:42)\n' +
>       '    at query (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:131:22)\n' +
>       '    at assertSessions (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:203:34)\n' +
>       '    at sendMessagesAgain (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:235:15)\n' +
>       '    at async /var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:303:29'
>   },
>   isBoom: true,
>   isServer: false,
>   output: {
>     statusCode: 408,
>     payload: {
>       statusCode: 408,
>       error: 'Request Time-out',
>       message: 'Timed Out'
>     },
>     headers: {}
>   }
> }
> ```
> 
> And sometimes followed by this
> 
> ```
> {
> connection: 'close',
> lastDisconnect: {
>   error: Error: Stream Errored (xml-not-well-formed)
>       at WebSocket.<anonymous> (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:430:13)
>       at WebSocket.emit (node:events:527:28)
>       at WebSocket.emit (node:domain:475:12)
>       at /var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:228:35
>       at Object.decodeFrame (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:142:17)
>       at WebSocket.onMessageRecieved (/var/www/api-whatsapp-md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:204:15)
>       at WebSocket.emit (node:events:527:28)
>       at WebSocket.emit (node:domain:475:12)
>       at Receiver.receiverOnMessage (/var/www/api-whatsapp-md/node_modules/ws/lib/websocket.js:1098:20)
>       at Receiver.emit (node:events:527:28) {
>     data: [Object],
>     isBoom: true,
>     isServer: true,
>     output: [Object]
>   },
>   date: 2022-05-11T14:46:09.063Z
> }
> } {
>   statusCode: 500,
>   error: 'Internal Server Error',
>   message: 'An internal server error occurred'
> }
> ```
> 
> I really don't know is those are related to the **Closing stale open session for new outgoing prekey bundle**, but it started after I realized this.
> 
> My connection options looks like this:
> 
> ```
>     sock = makeWASocket({
>               printQRInTerminal: false,
>               browser: ['blablabla', 'Chrome', '3.0'],
>               auth: await this.loadState(),
>               logger: P({ level: 'error' }),
>               defaultQueryTimeoutMs: undefined
>           });
> ```
> 
> Could someone give me a light on this?

Facing Same problem.

**Comment by SamPandey001** [comment]
> 

did not work

**Comment by igortrust** [comment]
1 more here

**Comment by zellsito** [comment]
1 more here, help plz!!
Closing open session in favor of incoming prekey bundle
2022-06-28T02:35:47.029573+00:00 app[web.1]: Closing session: SessionEntry {
2022-06-28T02:35:47.029574+00:00 app[web.1]: _chains: {
2022-06-28T02:35:47.029574+00:00 app[web.1]: 'BU5Q3HSlUwWqm2JoRgRfj1ubU/jjqYgL8O8f/NJ83VtX': { chainKey: [Object], chainType: 2, messageKeys: {} 
},
2022-06-28T02:35:47.029574+00:00 app[web.1]: 'BRfG991+K2plRIKH8xuYVfQh63crwqeqjPlJsZ3bDWBv': { chainKey: [Object], chainType: 2, messageKeys: {} 
},
2022-06-28T02:35:47.029574+00:00 app[web.1]: 'BYE5H9Wf9PtN6qDGWyr2OoI/ypaG/SStzVz/Z/1YLCMZ': { chainKey: [Object], chainType: 1, messageKeys: {} 
}
2022-06-28T02:35:47.029575+00:00 app[web.1]: },
2022-06-28T02:35:47.029575+00:00 app[web.1]: registrationId: 1865,
2022-06-28T02:35:47.029575+00:00 app[web.1]: currentRatchet: {
2022-06-28T02:35:47.029575+00:00 app[web.1]: ephemeralKeyPair: {
2022-06-28T02:35:47.029586+00:00 app[web.1]: pubKey: <Buffer 05 81 39 1f d5 9f f4 fb 4d ea a0 c6 5b 2a f6 3a 82 3f ca 96 86 fd 24 ad cd 5c ff 67 
fd 58 2c 23 19>,
2022-06-28T02:35:47.029587+00:00 app[web.1]: privKey: <Buffer 70 ff 6a d6 5a 90 c2 52 da 66 3a 32 ad fd b3 59 2d 53 fd f4 d0 60 ec 2d 55 18 00 13 5f 4a ed 75>
2022-06-28T02:35:47.029587+00:00 app[web.1]: },
2022-06-28T02:35:47.029588+00:00 app[web.1]: lastRemoteEphemeralKey: <Buffer 05 17 c6 f7 dd 7e 2b 6a 65 44 82 87 f3 1b 98 55 f4 21 eb 77 2b c2 a7 aa 8c f9 49 b1 9d db 0d 60 6f>,
2022-06-28T02:35:47.029588+00:00 app[web.1]: previousCounter: 2,
2022-06-28T02:35:47.029588+00:00 app[web.1]: rootKey: <Buffer fb d3 e7 73 7d 6f a3 ab d5 77 39 e3 98 03 04 a8 35 41 8d c7 bd fa b1 32 b6 49 dd 98 15 f9 00 0a>
2022-06-28T02:35:47.029588+00:00 app[web.1]: },
2022-06-28T02:35:47.029588+00:00 app[web.1]: indexInfo: {
2022-06-28T02:35:47.029588+00:00 app[web.1]: baseKey: <Buffer 05 f0 f3 d1 3d 8a 2b 76 de ab 12 46 d3 a1 b4 4b 0f 91 cd 77 23 83 c2 03 67 6d b9 cb 5d 6e ac db 12>,
2022-06-28T02:35:47.029589+00:00 app[web.1]: baseKeyType: 2,
2022-06-28T02:35:47.029589+00:00 app[web.1]: closed: -1,
2022-06-28T02:35:47.029589+00:00 app[web.1]: used: 1656381098841,
2022-06-28T02:35:47.029589+00:00 app[web.1]: created: 1656380588470,
2022-06-28T02:35:47.029590+00:00 app[web.1]: remoteIdentityKey: <Buffer 05 a9 e4 1d d4 8a 70 82 d0 fb 80 b1 6c 80 28 e0 b2 0e 74 b9 39 01 43 5f 8a 94 cf 46 04 f3 50 f8 4f>
2022-06-28T02:35:47.029590+00:00 app[web.1]: }
2022-06-28T02:35:47.029590+00:00 app[web.1]: }

**Comment by ReiDx** [comment]
same error

**Comment by MuhammadKarzoun** [comment]
-1

**Comment by ViniciusZanetti** [comment]
any update?

**Comment by edwindefine** [comment]
any answer?

**Comment by Ningoje** [comment]
any fixes?

**Comment by zzAIMoo** [comment]
+1

**Comment by edwindefine** [comment]
> 

1 more here please help

**Comment by vaccarieli** [comment]
+1

**Comment by ubkh** [comment]
Same issue here. This only happens when I send a message into a chat. In the chat on mobile, an information icon appears next to this message stating 'This message will not disappear from the chat. The sender may be on an old version of WhatsApp'. 

I'm not sure if this is related, however I have tried to resolve this by querying the group metadata to get the message expiration time and adding it onto the ephemeralExpiration field of the message, to no avail.
