### ISSUE TITLE
[BUG] Conflict  Device Removed

### ISSUE THREAD

**Issue by imReCoder** [adiwajshing/Baileys#1605]
Sometimes when trying to authorize whatsapp by scanning qr code it shows this error

{"level":50,"time":1652296496298,"pid":22792,"hostname":"Recoders-Pc","error":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"msg":"stream errored out"}
{"level":30,"time":1652296496298,"pid":22792,"hostname":"Recoders-Pc","error":{"data":{"tag":"stream:error","attrs":{"code":"401"},"content":[{"tag":"conflict","attrs":{"type":"device_removed"},"content":null}]},"isBoom":true,"isServer":false,"output":{"statusCode":401,"payload":{"statusCode":401,"error":"Unauthorized","message":"Stream Errored"},"headers":{}}},"msg":"connection closed"}
{"level":30,"time":1652296496301,"pid":22792,"hostname":"Recoders-Pc","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}

Solution :
changing the network  works
and after successfull login if  i come back to same network and try to auth with saved auth files it works

**Comment by Zarinia** [comment]
Yeah, I have the same problem too.

**Comment by Zarinia** [comment]
Yeah, 😬

**Comment by buzziss** [comment]
I am having the same trouble

**Comment by imReCoder** [comment]
Any updates guys?

**Comment by kaniket7209** [comment]
> I am having the same trouble

I am also having the same issue but what is the solution ... And why this issue is staled. Does anyone have the solution

**Comment by mapsiva** [comment]
Any updates? The same problem here...
