### ISSUE TITLE
Get baileys.MessageType

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1607]
How get baileys.MessageType in new version?

**Comment by Zarinia** [comment]
let me test

**Comment by Zarinia** [comment]
thanks for your feedback
How can I implement this in v4
```
if (messageType === baileys.MessageType.image) {
			messageText = m.message.imageMessage.caption;
			typeId = MESSAGE_TYPE_ID_PICTURE;
		}
```

**Comment by ngadimin51** [comment]
> thanks for your feedback How can I implement this in v4
> 
> ```
> if (messageType === baileys.MessageType.image) {
> 			messageText = m.message.imageMessage.caption;
> 			typeId = MESSAGE_TYPE_ID_PICTURE;
> 		}
> ```

const message = m.messages[0].message // get message
if ( messageType === 'image' ) { // if image
     const messageText = message.imageMessage?.caption // if there is have some caption
const typeId = message.key.id // get the message id
}
