### ISSUE TITLE
[BUG] session authentication

### ISSUE THREAD

**Issue by FERDIZ-afk** [adiwajshing/Baileys#1610]
![Screenshot_2022-05-12-21-08-38-94](https://user-images.githubusercontent.com/69185890/168094572-043d8768-ac3a-40f8-a871-4b97a82207d4.png)

bug during session authentication how to fix it

![Screenshot_2022-05-12-21-18-37-04_a2cf8efcdd42a8e6f7906303f104fb67](https://user-images.githubusercontent.com/69185890/168096808-a0b24ef9-8d4e-4f18-b959-c6b17f35bcad.png)

on session bot authentication, on write json error occurs is this is limit of write json

**Comment by Mmarjann** [comment]
coba hapus file sesinya trus scan ulang qr codenya

**Comment by zennn08** [comment]
I think it was an error when writing session file. Maybe you can [read](https://github.com/adiwajshing/Baileys/pull/1404) this

**Comment by vishwajit76** [comment]
same issue

**Comment by FERDIZ-afk** [comment]
Thanks info
