### ISSUE TITLE
what mean the event `connection-phone-change`

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#162]
I have several events with these name been triggered with "true" and "false" all the time. What's?
Maybe is the connection was offline? If the case so, there's a way to previne the connection to became idle or disconnect?

the device is online with the app open receiving messages while this is happening.

**Comment by adiwajshing** [comment]
WhatsApp has a test for the phone connection -- it's a little unreliable. However, if you increase `conn.connectOptions.phoneResponseTime` to `10_000 ` or higher -- you should see fewer incorrect events

**Comment by algoz098** [comment]
Yea, the informeation from the conn are strange. Like, if a connection get online for too much time without information sending or receiving, if get a strange state
