### ISSUE TITLE
let's find a gap so button 5 can tag users on WhatsApp 

### ISSUE THREAD

**Issue by NzrlAfndi** [adiwajshing/Baileys#1621]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by AkirahX** [comment]
What?

**Comment by FaizBastomi** [comment]
This is a direct limitation of WhatsApp, it can't be changed
