### ISSUE TITLE
[BUG] Help sending a custom sticker

### ISSUE THREAD

**Issue by ThePinkLyna** [adiwajshing/Baileys#1624]
Im going nuts with this. The situation is this. I have a picture, I convert that picture into something else using fluentffmpeg and then I want to edit that image then send it. The problem here is that I the conversion stops the script from continuing after is done. And also, the edit part needs to wait until the conversion is done and I don't know how to do that, because it seems that with fluentffmpeg the order of the code doesn't matter.
Here is the script

```
                    
				case 'sticker':
					
					
						const encmedia = isQuotedImage ? JSON.parse(JSON.stringify(mek).replace('quotedM','m')).message.extendedTextMessage.contextInfo : mek
						const media = await Bether.downloadAndSaveMediaMessage(encmedia)
						
						await ffmpeg(`./${media}`)
							.input(media)
							
							.addOutputOptions([`-vcodec`,`libwebp`,`-vf`,`scale='min(320,iw)':min'(320,ih)':force_original_aspect_ratio=decrease,fps=15, pad=320:320:-1:-1:color=white@0.0, split [a][b]; [a] palettegen=reserve_transparent=on:transparency_color=ffffff [p]; [b][p] paletteuse`])
							.toFormat('webp')
							.save('./a.webp')
							.on('start', function (cmd) {
								console.log(`Started : ${cmd}`)
							})
							.on('error', function (err) {
								console.log(`Error : ${err}`)
								
								reply(mess.error.stick)
							}) 
							
							
					
exec(`webpmux -set exif ./BetherMultiMedia/Marca.exif ./a.webp -o ./a.webp`)
ran = fs.readFileSync(`./a.webp`)
Bether.sendMessage(from, ran, sticker, {quoted: freply})
break
 ```

On console I get the latter part first then the conversion, it doesn't make any sense. Help

**Comment by fadiinho** [comment]
I guess you need to send the message after the **end** event is fired.
```js
[...]
.on('end', function() {
  exec(`webpmux -set exif ./BetherMultiMedia/Marca.exif ./a.webp -o ./a.webp`)
  ran = fs.readFileSync(`./a.webp`)
  Bether.sendMessage(from, ran, sticker, {quoted: freply})
})
```
You can read about it [here](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#end-processing-finished)

**Comment by ThePinkLyna** [comment]
> I guess you need to send the message after the **end** event is fired.
> 
> ```js
> [...]
> .on('end', function() {
>   exec(`webpmux -set exif ./BetherMultiMedia/Marca.exif ./a.webp -o ./a.webp`)
>   ran = fs.readFileSync(`./a.webp`)
>   Bether.sendMessage(from, ran, sticker, {quoted: freply})
> })
> ```
> 
> You can read about it [here](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#end-processing-finished)

I tried that already, but the problem is that is like when ffmpeg ends, firing the end event, only executes one of what i put. I think i need an await in exec but i dont know where to put it, because the message needs to be sended after webpmux is done. Because i tried what you said, and the sticker gets send but without the edit. if i try to change the output of webpmux to b.webp then "ran" says "Cant find b.webp in ./", but the sticker is there, if i execute the sticker command again then it does send the image with the modification. Tell me how to do an await on "ran" so "ran" waits until webpmux is done editing the image... I think that is the solution

**Comment by SheIITear** [comment]
Use synchronous version of ```exec``` if you don't want to await. Also this is not a Baileys bug, so please refrain from creating issues like this and learn at least basics of the language a library uses before jumping straight into a complex one. Instead if you really need help with code of yours, you can join the discord server and ask in [#🤝-off-topic-help](https://discord.gg/DYgEu9EN).

**Comment by ThePinkLyna** [comment]
> synchronous version of `exec`

Thats the thing. I dont know how to do an await. Sorry for doing the issue in here, but stackoverflow didnt produced any result. Thank you, i will join your server and search for that exec version.

**Comment by ThePinkLyna** [comment]
Finally!
