### ISSUE TITLE
get message by messageID

### ISSUE THREAD

**Issue by mrhb6006** [adiwajshing/Baileys#1625]
is there any way to get message by messageID? i cant find specific function for that
(MD version)

**Comment by frmdeveloper** [comment]
https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts

Look at the link above. You will find makeInMemoryStore.

To get the message, use 
```js
store.loadMessage(jid, id, sock)
```

**Comment by muzafferkadir** [comment]
> https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts
> 
> Look at the link above. You will find makeInMemoryStore.
> 
> To get the message, use
> 
> ```js
> store.loadMessage(jid, id, sock)
> ```

i think it is for legacy version

**Comment by mrhb6006** [comment]
> https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts Look at the link above. You will find makeInMemoryStore.
> 
> To get the message, use
> 
> ```js
> store.loadMessage(jid, id, sock)
> ```

it is for legacy version

**Comment by frmdeveloper** [comment]
> it is for legacy version

https://github.com/adiwajshing/Baileys/blob/master/Example/example-legacy.ts
Look at the link above. You will find makeInMemoryStore.
To get the message, use 
```js
store.loadMessage(jid, id, sock)
```

**Comment by catabozan** [comment]
For MD version you can use the `inMemoryStore`'s [load messages](https://github.com/adiwajshing/Baileys/blob/master/src/Store/make-in-memory-store.ts#L261) function with a [cursor](https://github.com/adiwajshing/Baileys/blob/master/src/Types/Message.ts#L183).

**Comment by catabozan** [comment]
You can query all the messages before or after a certain messageID.

So if you want to get a message with a certain id:
let's say you want the message with `id=3`, and the message before has `id=2`
```typescript
const cursor = {
    before: {
                id: 2, // id of the message
                fromMe: true or false, // from my experience this property does not matter
                remoteJid: jidNormalizedUser(conversationId), // conversation ID (ex. 54234234324@s.whatsapp.net)
                participant: "" // you can leave it empty but it must be present
            }
}
```
and you specify the message count as `1` to fetch only one message.
