### ISSUE TITLE
I can't access by scanning the qr code

### ISSUE THREAD

**Issue by arvinmoj** [adiwajshing/Baileys#1626]
`connection closed due to  Error: Restart Required
    at WebSocket.<anonymous> (..../node_modules/@adiwajshing/baileys/lib/Socket/socket.js:433:17) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 410,
    payload: { statusCode: 410, error: 'Gone', message: 'Restart Required' },
    headers: {}
  }
} , reconnecting  true`

**Comment by DwiRizqiH** [comment]
normally appears after scan qr, can you read it?
"Restart Required"
Restart the bot

or you can look at 
https://github.com/adiwajshing/Baileys#connecting
for the reconnect mechanism
