### ISSUE TITLE
How can I get the read receipts of a specified chat message or the last message sent?

### ISSUE THREAD

**Issue by mhb96** [adiwajshing/Baileys#1627]
Hey guys,
I wanted to know if there is a way to get the read receipt (sent, delivered, read) for a specified chat message?
Eg. Get read receipt for chat message with Id: 123123. 

Side question, If there is a way, can you also guide me how to get this Id? 
Eg. Get the ids of the last X number of chats  OR  Get the Id of the last message sent.

Or the read receipt for the last chat sent?
Eg. Get read receipt of last chat message.

**Comment by burstfreeze** [comment]
You cannot fetch that from the server, you have to track those by yourself
