### ISSUE TITLE
[BUG] How to get the number of someone inside a group.

### ISSUE THREAD

**Issue by ThePinkLyna** [adiwajshing/Baileys#1629]
**Describe the bug**

**To Reproduce**
With your working bot, just add this case, im using the latest v3 Baileys, my mind is not ready to redo a 1year proyect by changing to baileys v4. And it will print the jid.

**Expected behavior**
Im trying to get the number of the person who does the command, because that way i can do a personalized way to respond commands based on who sended them. Besides the owner of the bot.

**Environment (please complete the following information):**
 - Is this on a server? I think it is.
 - What do your `connectOptions` look like? Those work fine
 - Do you have multiple clients on the same IP? Of course not.
 - Are you using a proxy? Nop.

**Additional context**
When i run it, it prints the group jid, i need the number, but the docs are.... confusing to understand.
Code:
```
case 'prueba60':
					lolip = mek.key.remoteJid
reply('*Veamos.*')
					reply(lolip)
break
```

**Comment by LightningNeko** [comment]
you can use
```js
    const senderId = mek.key.participant || mek.key.remoteJid
```

**Comment by ThePinkLyna** [comment]
> ```js
> const senderId = mek.key.participant || mek.key.remoteJid
> ```

Didnt worked. It returns the group id, not the number of the person. I guess the number will look like 12345678-456465@g.us or something. The think is that the returned value is 456465@g.us only, the group id, not the number

**Comment by zennn08** [comment]
Maybe you can try this.
```Typescript
const senderID = mek.key.fromMe ? conn.user.id : mek.participant ? mek.participant : mek.key.participant ? m.key.participant : mek.key.remoteJid
```

**Comment by ThePinkLyna** [comment]
> Maybe you can try this.
> 
> ```ts
> const senderID = mek.key.fromMe ? conn.user.id : mek.participant ? mek.participant : mek.key.participant ? mek.key.participant : mek.key.remoteJid
> ```

Didn't worked. 
"TypeError: Cannot use 'in' operator to search for 'text' in undefined"
