### ISSUE TITLE
onWhatsapp Timeout[BUG]

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#1633]
The function onWhatsapp return only timeout.

**Comment by ahmadkeren** [comment]
same too

**Comment by textarea** [comment]
Also for me

**Comment by jeferssonlemes** [comment]
for me it also started to occur in all sessions a little while ago

**Comment by hassanfuad96** [comment]
Up same

**Comment by cassiano-guardianserver** [comment]
same too

**Comment by ratnokustiawan** [comment]
same too

**Comment by ahmadkeren** [comment]
Its back work now...

**Comment by tarikhagustia** [comment]
same too

**Comment by ahmadkeren** [comment]
> Its back work now...

and going error back..

**Comment by aarvee022** [comment]
it works for a while then again stops working

**Comment by ahmadkeren** [comment]
> it works for a while then again stops working

T.T

**Comment by wskoderbr** [comment]
WhatsApp down....
https://downdetector.com/status/whatsapp/

**Comment by frmdeveloper** [comment]
![IMG-20220517-WA0084](https://user-images.githubusercontent.com/80396521/168821437-54707ad8-73aa-461b-ae44-affe3c11f487.jpg)

**Comment by shoukosagiri-poi** [comment]
same too

**Comment by Fokusdotid** [comment]
🗿

**Comment by frmdeveloper** [comment]
same same

**Comment by aarvee022** [comment]
seems like service restored now

**Comment by SanzGantengz** [comment]
> ![IMG-20220517-WA0084](https://user-images.githubusercontent.com/80396521/168821437-54707ad8-73aa-461b-ae44-affe3c11f487.jpg) _Don't make a bot_

🗿
