### ISSUE TITLE
How do I download the message history of a chat?

### ISSUE THREAD

**Issue by soengas73** [adiwajshing/Baileys#1637]
I've been researching and I don't see a way to download the message history of a chat, does anyone know?.
It is that I want to know how to get the chats to a document or view them outside the console, to know if it is possible to recover more than 3 months of chats

**Comment by reinforcers** [comment]
if the messages on that chat still available at your phone then the only way I know is using `makeInMemoryStore`, but first send new message to that chat then relogin to resync the data store
