### ISSUE TITLE
Dynamically set connection values on connection e.g. WAWeb version, Browser description and clientID

### ISSUE THREAD

**Issue by Gidraf** [adiwajshing/Baileys#164]
Hi @adiwajshing thanks for this great library, I was just wondering if there is way to dynamically set connection values when connecting this will give us the control to display the name we want on WA phones.
```
 const conn = new WAConnection() 
    await conn.connect (versionArray, LongBrowserDescription 
e.g 'windows', ShortBrowserDescription e.g 'firefox' or 'chrome', base64ClientId)
```
Thanks

**Comment by adiwajshing** [comment]
Yeah you can set it to anything you like:

`conn.browserDescription = Browsers.appropriate('Chrome')`

The above, for example, will make the appropriate chrome browser for your OS show up on your phone

`conn.browserDescription = Browsers.macOS('Safari')`

This'll make safari pop up

**Comment by Gidraf** [comment]
Okay thanks.
