### ISSUE TITLE
[BUG] Process Crashes while sending an image

### ISSUE THREAD

**Issue by AlenSaito1** [adiwajshing/Baileys#1642]
**Describe the bug**
The node process crashes while trying to send an image

**To Reproduce**

Example Code Snippet

```ts
x.sendMessage(jid, {
    image: { url: 'https://i.imgur.com/WQ3HpfI.jpeg' } 
})
```

Same issue while trying to send from a buffer

**Expected behavior**
 It should send the image or throw an error

**Environment (please complete the following information):**
 - Is this on a server? - No
 - What do your `connectOptions` look like? - Default
 - Do you have multiple clients on the same IP? - No
 - Are you using a proxy? - No

**Additional context**
It would have been better if it threw an error instead of straight up crashing

**Comment by SheIITear** [comment]
Can't reproduce, works fine for me and doesn't crash on invalid url.

**Comment by SheIITear** [comment]
I just tried it and no problems with local nor using url. Can you elaborate what happens when you try send an image? Send logs etc?

**Comment by AlenSaito1** [comment]
It just crashes, no errors, no logs related to this (even in debug mode), nothing.

**Comment by AlenSaito1** [comment]
https://github.com/adiwajshing/Baileys/issues/1260 Related issue

**Comment by SheIITear** [comment]
Interesting that does make it a bit hard to debug, especially as one can't reproduce it. I assume you're on linux environment, could you try attaching gdb or some debugger on the process and see it manages to get anything?

**Comment by AlenSaito1** [comment]
I'm on windows

**Comment by SheIITear** [comment]
It might help a bit trying to trace where it exists by checking if it i.e makes requests to the url.
Try looking if there is a debugger for windows that can tell you whats happening right before it dies.

**Comment by AlenSaito1** [comment]
I was able to fix it by adding a custom thumbnail each time

**Comment by Mihir1703** [comment]
Can anyone share working code?
I'm unable to connect to WhatsApp.

**Comment by makanSukros** [comment]
> Can anyone share working code? I'm unable to connect to WhatsApp.

Use example

**Comment by jeffersonveloso** [comment]
> Consegui corrigi-lo adicionando uma miniatura personalizada a cada vez

How you create custom thumbnails ? Show your code and lib please.

**Comment by AlenSaito1** [comment]
> > Consegui corrigi-lo adicionando uma miniatura personalizada a cada vez
> 
> How you create custom thumbnails ? Show your code and lib please.

Example

```ts
sock.sendMessage(jid, {
    image: buffer
    jpegThumbnail: buffer.toString('base64')
})
```

**Comment by zhinea** [comment]
same issue
