### ISSUE TITLE
Duplicates Instance on messages with Links Preview[BUG]

### ISSUE THREAD

**Issue by ChristianChs** [adiwajshing/Baileys#1646]
**Describe the bug**
Hi, I have a problem when I send Links
when I send a message (link) with preview

The Baileys Responds 2 times with the same instance
This doesn't always happen, but there may be situations that make it happen more often.

Ex:
User submits "https://youtu.be/8hIurGWZyXY"
// the image has a preview

baileys replies
pong
pong

**To Reproduce**
1. Created a new connection
2. Send a message(link) with preview

**Additional Information**
This error happens with any link that generates a preview

![WhatsApp Image 2022-05-20 at 10 12 29](https://user-images.githubusercontent.com/56552028/169560479-633ca4a2-16d8-4b53-823d-6869994dcecb.jpeg)
![WhatsApp Image 2022-05-20 at 10 12 55](https://user-images.githubusercontent.com/56552028/169560554-15c45d87-c65d-4340-92fd-48128324cef3.jpeg)

**Comment by Bloxoid123** [comment]
Same here :(
