### ISSUE TITLE
Every 50 minutes the connection closes [BUG]

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#1647]
Today the connection is closing every 50 minutes.

**Comment by afeno** [comment]
What do you mean by "Connection"? Do you need to scan the QR code again or is the socket closed?
quote from the readme:
`A baileys "socket" is meant to be a temporary & disposable object -- this is done to maintain simplicity & prevent bugs. I felt the entire Baileys object became too bloated as it supported too many configurations. You're encouraged to write your own implementation to handle missing functionality.`

So if the socket is closed, it is not an issue. Right?

**Comment by IanosJunior** [comment]
Look this log:

{"level":50,"time":"2022-05-26T18:36:26.693Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgId":"F370B7C5DB2ED5F67CAA8C3F13191490","params":["ENOENT: no such file or directory, open 'C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\auth_info_baileys\\sender-key-status@broadcast::553788513616::0.json'"],"msg":"failure in decrypting message"}
{"level":30,"time":"2022-05-26T18:36:26.694Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgAttrs":{"from":"status@broadcast","type":"media","id":"F370B7C5DB2ED5F67CAA8C3F13191490","participant":"553788513616@s.whatsapp.net","t":"1653590185","notify":"Zigg Cal├ºados"},"retryCount":4,"msg":"sent retry receipt"}
{"level":50,"time":"2022-05-26T18:36:27.615Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgId":"1C33B428F36B9CE498536D5D7361D886","params":["ENOENT: no such file or directory, open 'C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\auth_info_baileys\\sender-key-status@broadcast::553788513616::0.json'"],"msg":"failure in decrypting message"}
{"level":30,"time":"2022-05-26T18:36:27.617Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgAttrs":{"from":"status@broadcast","type":"media","id":"1C33B428F36B9CE498536D5D7361D886","participant":"553788513616@s.whatsapp.net","t":"1653590186","notify":"Zigg Cal├ºados"},"retryCount":4,"msg":"sent retry receipt"}
{"level":50,"time":"2022-05-26T18:36:29.108Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"msg":"stream errored out"}
{"level":30,"time":"2022-05-26T18:36:29.111Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"trace":"Error: Stream Errored (ack)\n    at WebSocket.<anonymous> (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:422:13)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit 
(node:domain:475:12)\n    at C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:219:35\n    at Object.decodeFrame (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:195:15)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    
at Receiver.emit (node:events:527:28)","msg":"connection errored"}
{"level":30,"time":"2022-05-26T18:36:29.115Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"trace":"Error: Connection Terminated by Server\n    at WebSocket.<anonymous> (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:352:13)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:219:35\n    at Object.decodeFrame (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:195:15)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    at Receiver.emit (node:events:527:28)","msg":"connection errored"}
connection closed: {"error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"date":"2022-05-26T18:36:29.113Z"}

**Comment by IanosJunior** [comment]
> What do you mean by "Connection"? Do you need to scan the QR code again or is the socket closed? quote from the readme: `A baileys "socket" is meant to be a temporary & disposable object -- this is done to maintain simplicity & prevent bugs. I felt the entire Baileys object became too bloated as it supported too many configurations. You're encouraged to write your own implementation to handle missing functionality.`
> 
> So if the socket is closed, it is not an issue. Right?
> 
> BTW, does anybody knows how to actively check if bailey's socket is open/closed?

Look this log:

{"level":50,"time":"2022-05-26T18:36:26.693Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgId":"F370B7C5DB2ED5F67CAA8C3F13191490","params":["ENOENT: no such file or directory, open 'C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\auth_info_baileys\\sender-key-status@broadcast::553788513616::0.json'"],"msg":"failure in decrypting message"}
{"level":30,"time":"2022-05-26T18:36:26.694Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgAttrs":{"from":"status@broadcast","type":"media","id":"F370B7C5DB2ED5F67CAA8C3F13191490","participant":"553788513616@s.whatsapp.net","t":"1653590185","notify":"Zigg Cal├ºados"},"retryCount":4,"msg":"sent retry receipt"}
{"level":50,"time":"2022-05-26T18:36:27.615Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgId":"1C33B428F36B9CE498536D5D7361D886","params":["ENOENT: no such file or directory, open 'C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\auth_info_baileys\\sender-key-status@broadcast::553788513616::0.json'"],"msg":"failure in decrypting message"}
{"level":30,"time":"2022-05-26T18:36:27.617Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgAttrs":{"from":"status@broadcast","type":"media","id":"1C33B428F36B9CE498536D5D7361D886","participant":"553788513616@s.whatsapp.net","t":"1653590186","notify":"Zigg Cal├ºados"},"retryCount":4,"msg":"sent retry receipt"}
{"level":50,"time":"2022-05-26T18:36:29.108Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"msg":"stream errored out"}
{"level":30,"time":"2022-05-26T18:36:29.111Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"trace":"Error: Stream Errored (ack)\n    at WebSocket.<anonymous> (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:422:13)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit 
(node:domain:475:12)\n    at C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:219:35\n    at Object.decodeFrame (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:195:15)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    
at Receiver.emit (node:events:527:28)","msg":"connection errored"}
{"level":30,"time":"2022-05-26T18:36:29.115Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"trace":"Error: Connection Terminated by Server\n    at WebSocket.<anonymous> (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:352:13)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:219:35\n    at Object.decodeFrame (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:195:15)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    at Receiver.emit (node:events:527:28)","msg":"connection errored"}
connection closed: {"error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"date":"2022-05-26T18:36:29.113Z"}

**Comment by Luxemburgo** [comment]
#1664 duplicated
