### ISSUE TITLE
[BUG] Template buttons does not send a message to the number informed, but to the number itself

### ISSUE THREAD

**Issue by RocketPainel** [adiwajshing/Baileys#1648]
**Describe the bug**
I found another bug, it is not possible to send a template message to a number, the message is sent to the same number connected to the application and not to the number informed

**To Reproduce**
1. Created a new connection
2. 
![image](https://user-images.githubusercontent.com/105253508/169601023-4ad806cf-c12f-46bf-afda-667b87417883.png)

3. run example code.

**Comment by Fredwuz** [comment]
In my experience, the message will be sent to yourself on the WhatsApp account of the bot but it also will be sent to the person on the other account
The first image is the account of the bot and the second is the account of myself
On the first image the bot is writing itself
<img src="https://user-images.githubusercontent.com/36505101/169623610-428d9e1c-4d8c-42ee-8127-636621565a77.jpeg" data-canonical-src="https://user-images.githubusercontent.com/36505101/169623610-428d9e1c-4d8c-42ee-8127-636621565a77.jpeg" width="200" />
<img src="https://user-images.githubusercontent.com/36505101/169623615-bf0aa52a-3ec6-4959-af23-3d2eabead2fd.jpeg" data-canonical-src="https://user-images.githubusercontent.com/36505101/169623615-bf0aa52a-3ec6-4959-af23-3d2eabead2fd.jpeg" width="200" />

PS you can create Code Blocks using three of these ` before and after your code, To enable the javascript highlighting write js behind the first ones
like this 
![image](https://user-images.githubusercontent.com/36505101/169623949-cf2a4cc3-6ba2-4c56-b7c7-7c0534539ff1.png)

**Comment by RocketPainel** [comment]
> Na minha experiência, a mensagem será enviada para você na conta do WhatsApp do bot, mas também será enviada para a pessoa da outra conta A primeira imagem é a conta do bot e a segunda é a minha conta . primeira imagem que o bot está escrevendo <img alt="" width="200" src="https://user-images.githubusercontent.com/36505101/169623610-428d9e1c-4d8c-42ee-8127-636621565a77.jpeg"> <img alt="" width="200" src="https://user-images.githubusercontent.com/36505101/169623615-bf0aa52a-3ec6-4959-af23-3d2eabead2fd.jpeg">
> 
> PS você pode criar blocos de código usando três desses ` antes e depois do seu código, para habilitar o javascript destacando escreva js atrás dos primeiros como este ![imagem](https://user-images.githubusercontent.com/36505101/169623949-cf2a4cc3-6ba2-4c56-b7c7-7c0534539ff1.png)

Hello, thanks, I didn't know how to create the code block. But I tested it here, and in my case it's only sent to my own number, so the person doesn't send it.

**Comment by ngadimin51** [comment]
Same case, it still send back to sender

**Comment by glauco-oliveira** [comment]
still having the same problem!

**Comment by SrFortes** [comment]
I also have this problem, it sends to the sender and also to my connected number !! 
![image](https://user-images.githubusercontent.com/41592754/174690024-cf3cba1a-9405-42fa-93d0-d4262bcd4d27.png)
![image](https://user-images.githubusercontent.com/41592754/174690085-545ebffc-291e-48cb-bc08-b7057bc5f69b.png)

**Comment by Jorsis** [comment]
same

**Comment by lopesclayton** [comment]
![image](https://user-images.githubusercontent.com/27986914/181870539-dea25b1c-345b-4078-a5d6-7ec5de64bc25.png)

I solved it with this adjustment in the code,
the mentioned line, sends it to my number, I put a conditional that will only be sent if it has buttons

**Comment by SrFortes** [comment]
> ![imagem](https://user-images.githubusercontent.com/27986914/181870539-dea25b1c-345b-4078-a5d6-7ec5de64bc25.png)
> 
> Resolvi com esse ajuste no código, a linha mencionada, envia para o meu número, coloco uma condicional que só será enviada se tiver botões

what would be the hydratedButtons ?
