### ISSUE TITLE
I am able to print QR on the terminal, but unable to find a way to Print QR code on the browser.

### ISSUE THREAD

**Issue by dotcomsolutionsAB** [adiwajshing/Baileys#1649]
I need help structuring my application, I want to build a simple interface which prints the QR code on the browser instead of the terminal.

I had implemented in successfully in the previous version as

`async function Connect(name){ const connection = new WAConnection() connection.loadAuthInfo(./${name}.json')
await connection.connect()
return connection
}

//Connecting New Mobile
app.get('/:name',async(req,res)=>{
console.log (Working uptil here!)
const conn = new WAConnection()
conn.on('qr',qr=>{
//res.send({'qr':qr})
const qrStream = new PassThrough();
const result = QRCode.toFileStream(qrStream, qr, {
type: 'png',
width: 500,
errorCorrectionLevel: 'H'
});
static_urlCode = ''

	qrStream.pipe(res);
})
conn.on('open', () => {
    const authInfo = conn.base64EncodedAuthInfo() // get all the auth info we need to restore this session
    fs.writeFileSync('./${req.params.name}.json', JSON.stringify(authInfo, null, '\t')) // save this info to a file
})
await conn.connect()

})`

But I cannot find a way to do so in the multi device version.

**Comment by salman0ansari** [comment]
check how did it
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/main/src/api/class/instance.js

**Comment by jasmanX** [comment]
> check how i did it https://github.com/salman0ansari/whatsapp-api-nodejs/blob/main/src/api/class/instance.js

how to get token (qr code key) before scanning ? how to generate wa token ?

**Comment by aislanspeedio** [comment]
> check how i did it https://github.com/salman0ansari/whatsapp-api-nodejs/blob/main/src/api/class/instance.js

The qr code generated into terminal by the baileys is not the same qr code data image generated by the qrcode lib package.
