### ISSUE TITLE
Getting contacts with names in MD

### ISSUE THREAD

**Issue by AxeemHaider** [adiwajshing/Baileys#1650]
MD version can't get names in contact there is only `notify` I want to get the names that are saved in my contacts. But I'm not able to see these names anywhere in the Baileys MD version. Is there any way I can get them?

**Comment by SrFortes** [comment]
Great, I'm also looking for the same solution!

**Comment by baagas0** [comment]
I need a same solution for this problem, anyone can help this problem?

**Comment by codevjs** [comment]
me too

**Comment by asabadyr** [comment]
Anybody? seems like it's not correctly mapped to the protobuf value

**Comment by HUGEIT** [comment]
@asabadyr what do you mean? contacts aren't pushed in form of protobuf data

**Comment by jrrcdev** [comment]
In MD you will receive the contact list after login(read qr code), but I discover an issue, after receiving the contact list(860 contacts), the system process the chat list and send a "contacts.set" event with the groups as contacts, but the store override the contacts list and I end up just with the groups(2 contacts)

How can we solve it @adiwajshing ?

**Comment by vlad-iliescu-tallarium** [comment]
Still relevant. Particularly the issue mentioned by @jrrcdev. I also ran into the issue where the group ids come after the user ids and overwrite them in the store. This looks like a bug to me at least.
Also, if the contacts we receive are the participants of the group, even though they left the group already, is that correct behavior? How can we get the contacts that are currently in the group?

**Comment by vlad-iliescu-tallarium** [comment]
Still relevant

**Comment by SrFortes** [comment]
Still relevant

**Comment by neves-gabriel** [comment]
Still relevant

**Comment by SrFortes** [comment]
Still relevant

**Comment by neves-gabriel** [comment]
Still relevant

**Comment by harshmakani1** [comment]
Still relevant

**Comment by vphelipe** [comment]
Still relevant
