### ISSUE TITLE
Is this package support commonJS Standards ?

### ISSUE THREAD

**Issue by Allu9221** [adiwajshing/Baileys#1653]
I wanted to implement this feature in my Node.js application, so I wanted to know whether this package support CommonJS standards. If this supports the CommonJS standards, is there any documentation on how to use this library.

**Comment by Zarinia** [comment]
Hi, Both CommonJS and ECMAScript supported by this library

**Comment by Allu9221** [comment]
Thank you @Zarinia, is there any documentation on how to use the functions?

**Comment by HanzCEO** [comment]
> Thank you @Zarinia, is there any documentation on how to use the functions?
> 
> Here, they have given the documentation for ECMAScript only.

![image](https://user-images.githubusercontent.com/40712686/170621883-242cdf40-b903-47ff-89fd-bb2ab03a91bb.png)
Everything documented under the red box is the main module. You can import anything listed there, simply by doing this:
```js
const { FunctionA, FunctionB } = require('./Baileys');
const { default: makeWASocket } = require('./Baileys');
```

Everything documented under the cyan box is the protobuf module. If you need something, do this:
```js
const { proto } = require('./Baileys');
const { somethingFromProto } = proto;
```

CMIIW
