### ISSUE TITLE
[BUG] Reaction messages not being displayed in receivers screen

### ISSUE THREAD

**Issue by danielcardeenas** [adiwajshing/Baileys#1654]
**Describe the bug**
Reaction messages not being displayed in receivers screen. Reaction messages are only showed in sender (baileys) whatsapp

**To Reproduce**
1. Created a new connection
2. Recieve message
3. Answer message with a reaction
4. Reaction only being showed in baileys user end (whatsapp andorid app)

**Expected behavior**
Show reaction in both ends

**Environment (please complete the following information):**
 - Is this on a server?
 No. Mac

 - What do your `connectOptions` look like?
```
    version: [2, 2214, 9],
    printQRInTerminal: true,
    auth: state,
    msgRetryCounterMap,
    // implement to handle retries
    getMessage: async (key) => {
      return {
        conversation: 'Reconectando...',
      };
    },
```
 - Do you have multiple clients on the same IP?
 No

 - Are you using a proxy?
 No

**Additional context**
```
if (isFromDaniel(message)) {
    const reactionMessage = {
      react: {
        text: '🙏',
        key: message.key,
      },
    };
    const client = WAClient.instance();
    await client.sendMessage(message.key.remoteJid!, reactionMessage);
}
```

**Comment by HanzCEO** [comment]
Does the receiver receive "Waiting for this message"?

**Comment by danielcardeenas** [comment]
> Does the receiver receive "Waiting for this message"?

He does not

**Comment by fadiinho** [comment]
I guess your case is the same as mine, if the message to react is from Whatsapp Web and from a group, you need to normalize the jid.
```js
import { jidNormalizedUser } from '@adiwajshing/baileys';

if (isFromDaniel(message)) {
    const key = {
      ...message.key,
      participant: jidNormalizedUser(message.key.participant)
    };
    const reactionMessage = {
      react: {
        key,
        text: '🙏'
      },
    };
    const client = WAClient.instance();
    await client.sendMessage(message.key.remoteJid!, reactionMessage);
}
```
``
Explanation:
The jid that comes from `message.key.participant` is in the format 
"xxxxxxxxxxxx:(some number, in my case was 7)@s.whatsapp.net" -> "xxxxxxxxxxxx:7@s.whatsapp.net".
After normalizing with `jidNormalizedUser` the middle number is removed ->  "xxxxxxxxxxxx@s.whatsapp.net".
I tried to fix that and make a PR but I failed.
