### ISSUE TITLE
Getting the last MD message ?

### ISSUE THREAD

**Issue by SrFortes** [adiwajshing/Baileys#1658]
How do I get the last chat message? with the multi device ?

**Comment by danielcardeenas** [comment]
Store messages in some way and ge the last one

**Comment by SrFortes** [comment]
ok, the solution I got was to use limit=1, so it gives me back the last message!

> add
> 
> ```
> store = makeInMemoryStore({
> 			logger: logger
> 		});
> ```
> 
> then get messages like:
> 
> ```
> jid:receiver_user
> limit=10;
> cursor.after = {
> id: last_id
> // fromMe: Boolean(cursor_fromMe && cursor_fromMe === 'true')
> };
> 
> store.loadMessages(jid, limit, useCursor)
> ```


**ok, the solution I got was to use limit=1, so it gives me back the last message!**

store.loadMessages(jid, limit=1)

**Comment by Zarinia** [comment]
How can I receive recent messages after a specific message ID?
