### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kiaonline** [adiwajshing/Baileys#1663]
Hi,
when is trigger 'messages.update' on sock event,
brings :8 as below:
it's normal?
{
  key: {
    remoteJid: '55111111111:8@s.whatsapp.net',
    id: 'BAE59CAD692C2583',
    fromMe: true,
    participant: undefined
  },
  update: { status: 3 }
}

I try to get the message from remoteJid and is  returned undefined because this variable is incorrect.

**Comment by BochilGaming** [comment]
Yes, it's normal. You can remove :8 using `jidNormalizedUser` function

**Comment by daniel672-boo** [comment]
Pode remover usando split(":")[0] e adcionar o @s.whatsapp.net depois

**Comment by kiaonline** [comment]
> Yes, it's normal. You can remove :8 using `jidNormalizedUser` function

Perfect. Works perfectly! 
tks
