### ISSUE TITLE
Connection closed each 50 minutes [BUG]

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#1664]
Log Debug:

26/05/2022 10:28:01-{"level":50,"time":1653571681517,"pid":10616,"hostname":"server","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"3A0AD791F485D88DEB53"}}]},"msg":"stream errored out"}
26/05/2022 10:28:01-{"level":30,"time":1653571681519,"pid":10616,"hostname":"server","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"3A0AD791F485D88DEB53"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"trace":"Error: Stream Errored (ack)\n    at WebSocket.<anonymous> (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:430:13)\n    at WebSocket.emit (node:events:390:28)\n    at E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:228:35\n    at Object.decodeFrame (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:204:15)\n    at WebSocket.emit (node:events:390:28)\n    at Receiver.receiverOnMessage (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    at Receiver.emit (node:events:390:28)\n    at Receiver.dataMessage (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\ws\\lib\\receiver.js:513:14)\n    at Receiver.getData (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\ws\\lib\\receiver.js:446:17)","msg":"connection errored"}
26/05/2022 10:28:01-{"level":30,"time":1653571681521,"pid":10616,"hostname":"server","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"trace":"Error: Connection Terminated by Server\n    at WebSocket.<anonymous> (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:361:13)\n    at WebSocket.emit (node:events:390:28)\n    at E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:228:35\n    at Object.decodeFrame (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:204:15)\n    at WebSocket.emit (node:events:390:28)\n    at Receiver.receiverOnMessage (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    at Receiver.emit (node:events:390:28)\n    at Receiver.dataMessage (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\ws\\lib\\receiver.js:513:14)\n    at Receiver.getData (E:\\Programas\\Comunica\\node_api\\baileys\\node_modules\\ws\\lib\\receiver.js:446:17)","msg":"connection errored"}
26/05/2022 10:28:01-connection closed: {"error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"3A0AD791F485D88DEB53"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"date":"2022-05-26T13:28:01.520Z"}

**Comment by Luxemburgo** [comment]
Same exact problem here. It's exactly every 50 minutes. Here's my connection closed log times:

    date: 2022-05-26T02:35:37.250Z
    date: 2022-05-26T03:25:44.712Z
    date: 2022-05-26T04:15:49.318Z
    date: 2022-05-26T05:05:53.443Z
    date: 2022-05-26T05:55:58.574Z
    date: 2022-05-26T06:46:02.970Z
    date: 2022-05-26T07:36:08.378Z
    date: 2022-05-26T08:26:13.329Z
    date: 2022-05-26T09:16:21.155Z
    date: 2022-05-26T10:06:26.389Z
    date: 2022-05-26T10:56:30.754Z
    date: 2022-05-26T11:46:34.176Z
    date: 2022-05-26T12:36:38.369Z
    date: 2022-05-26T13:26:41.312Z
    date: 2022-05-26T14:16:45.745Z
    date: 2022-05-26T15:06:49.735Z
    date: 2022-05-26T15:56:53.858Z
    date: 2022-05-26T16:46:58.095Z

Error: Stream Errored (ack) at WebSocket

**Comment by IanosJunior** [comment]
Last log

{"level":50,"time":"2022-05-26T18:36:26.693Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgId":"F370B7C5DB2ED5F67CAA8C3F13191490","params":["ENOENT: no such file or directory, open 'C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\auth_info_baileys\\sender-key-status@broadcast::553788513616::0.json'"],"msg":"failure in decrypting message"}
{"level":30,"time":"2022-05-26T18:36:26.694Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgAttrs":{"from":"status@broadcast","type":"media","id":"F370B7C5DB2ED5F67CAA8C3F13191490","participant":"553788513616@s.whatsapp.net","t":"1653590185","notify":"Zigg Cal├ºados"},"retryCount":4,"msg":"sent retry receipt"}
{"level":50,"time":"2022-05-26T18:36:27.615Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgId":"1C33B428F36B9CE498536D5D7361D886","params":["ENOENT: no such file or directory, open 'C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\auth_info_baileys\\sender-key-status@broadcast::553788513616::0.json'"],"msg":"failure in decrypting message"}
{"level":30,"time":"2022-05-26T18:36:27.617Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","msgAttrs":{"from":"status@broadcast","type":"media","id":"1C33B428F36B9CE498536D5D7361D886","participant":"553788513616@s.whatsapp.net","t":"1653590186","notify":"Zigg Cal├ºados"},"retryCount":4,"msg":"sent retry receipt"}
{"level":50,"time":"2022-05-26T18:36:29.108Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"msg":"stream errored out"}
{"level":30,"time":"2022-05-26T18:36:29.111Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"trace":"Error: Stream Errored (ack)\n    at WebSocket.<anonymous> (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:422:13)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit 
(node:domain:475:12)\n    at C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:219:35\n    at Object.decodeFrame (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:195:15)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    
at Receiver.emit (node:events:527:28)","msg":"connection errored"}
{"level":30,"time":"2022-05-26T18:36:29.115Z","pid":54208,"hostname":"Notebook-Ianos","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"trace":"Error: Connection Terminated by Server\n    at WebSocket.<anonymous> (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:352:13)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:219:35\n    at Object.decodeFrame (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:142:17)\n    at WebSocket.onMessageRecieved (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:195:15)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (C:\\ViaRapida\\Comunica\\Node Apis\\Baileys\\node_modules\\ws\\lib\\websocket.js:1160:20)\n    at Receiver.emit (node:events:527:28)","msg":"connection errored"}
connection closed: {"error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"0EC9CF1CFB22AD0A979F0A4220BDBFEC"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"date":"2022-05-26T18:36:29.113Z"}

**Comment by IanosJunior** [comment]
In another whatsapp number this does not happen. The amount of messages in which it gives error is much higher.

**Comment by IanosJunior** [comment]
> Same exact problem here. It's exactly every 50 minutes. Here's my connection closed log times:
> 
> ```
> date: 2022-05-26T02:35:37.250Z
> date: 2022-05-26T03:25:44.712Z
> date: 2022-05-26T04:15:49.318Z
> date: 2022-05-26T05:05:53.443Z
> date: 2022-05-26T05:55:58.574Z
> date: 2022-05-26T06:46:02.970Z
> date: 2022-05-26T07:36:08.378Z
> date: 2022-05-26T08:26:13.329Z
> date: 2022-05-26T09:16:21.155Z
> date: 2022-05-26T10:06:26.389Z
> date: 2022-05-26T10:56:30.754Z
> date: 2022-05-26T11:46:34.176Z
> date: 2022-05-26T12:36:38.369Z
> date: 2022-05-26T13:26:41.312Z
> date: 2022-05-26T14:16:45.745Z
> date: 2022-05-26T15:06:49.735Z
> date: 2022-05-26T15:56:53.858Z
> date: 2022-05-26T16:46:58.095Z
> ```
> 
> Error: Stream Errored (ack) at WebSocket

I saw that this problem only happens in the edge version. 
In the stable version do not disconnect after 50 minutes
What can it be @adiwajshing ?.

**Comment by adiwajshing** [comment]
Are you certain the issue doesn't exist on the NPM version? I'll have to investigate this then -- seems like a weird edge case

**Comment by IanosJunior** [comment]
> Are you certain the issue doesn't exist on the NPM version? I'll have to investigate this then -- seems like a weird edge case

Yes I have. I tested both in the same way and in the same number.

**Comment by makanSukros** [comment]
I also experienced a case like this, it's just that it's about 20-30 minutes faster, I've also made sure that my internet connection is normal and smooth, when I get a disconnected state from this lib, I check on the device the status is disconnected @adiwajshing

**Comment by makanSukros** [comment]
iam using edge version with node version v16.14.2

**Comment by mapacheverdugo** [comment]
Same here

**Comment by muzafferkadir** [comment]
same error

**Comment by riskihajar** [comment]
same error, on some number

**Comment by russocorp** [comment]
Here too, same error when sending messages

**Comment by muzafferkadir** [comment]
is anybody found any solution?

**Comment by dralucindaodonto** [comment]
> 2022-07-05 15:03:57.603 error: Erro inesperado ENOENT: no such file or directory, open 'D:\Whats\ClinicaOdontoJS\auth\creds.json' [Error: ENOENT: no such file or directory, open 'D:\Whats\ClinicaOdontoJS\auth\creds.json'] { errno: -4058, code: 'ENOENT', syscall: 'open', path: 'D:\Whats\ClinicaOdontoJS\auth\creds.json' }
> 
> it´s a weird behavior. after received this error, application continue sending messages but stop receive. Need clear auth folder and read qrcode again.

Hey ! qual sistema odontológico trabalha ? To no mesmo barco. chama no whats 12 992247834
