### ISSUE TITLE
[BUG] Different result between browser and phone for a message containing many buttons

### ISSUE THREAD

**Issue by Amineramadane** [adiwajshing/Baileys#1665]
### This is my code

![image](https://user-images.githubusercontent.com/68738340/170499793-94d1be24-4231-4db5-ab95-b6adf7df1844.png)

### Result on the web

![image](https://user-images.githubusercontent.com/68738340/170501175-f8fb1d3e-0587-4ade-83cf-f63c67b7551a.png)

### Result on the phone

![InkedWhatsApp Image 2022-05-26 at 14 54 00_LI](https://user-images.githubusercontent.com/68738340/170503520-cb9202db-f6b1-4dab-9f9d-6efcf1164803.jpg)

**Comment by viniciusgdr** [comment]
this is not a lib error, but a WhatsApp limitation in this regard

**Comment by marutichintan** [comment]
i have same issue, works ok on my mobile, not on other, I use section list.

**Comment by Amineramadane** [comment]
:(
