### ISSUE TITLE
Group Message Participant Receipt

### ISSUE THREAD

**Issue by ricco-douro** [adiwajshing/Baileys#1666]
Hello Everyone,

I am received Delivery and Read receipts for contact messages but Whatsapp also has the same feature in Group Messages. It Tell you whom was delivered to, and who has already read the message. 

Does anyone know how to get this read receipts from WA using Baileys?

![image](https://user-images.githubusercontent.com/46711848/170581927-ee87ff37-eb7d-4b7b-b250-20dcc6810d55.png)

**Comment by zennn08** [comment]
You can implement the data store
```Typescript
const msg = store.messages[jid].get(id)
console.log(msg.userReceipt)
```
The `jid` is id chats like `628xxx@s.whatsapp.net` or `1536xxx@g.us`
and the `id` is id messages, you can get this in the `message.key.id`

**Comment by zennn08** [comment]
You can implement the data store
```Typescript
const msg = store.messages[jid].get(id)
console.log(msg.userReceipt)
```
The `jid` is id chats like `628xxx@s.whatsapp.net` or `1536xxx@g.us`
and the `id` is id messages, you can get this in the `message.key.id`
