### ISSUE TITLE
[BUG] Edge Version Cannot be Installed due to Semver Conflict

### ISSUE THREAD

**Issue by HanzCEO** [adiwajshing/Baileys#1667]
**Describe the bug**
![image](https://user-images.githubusercontent.com/40712686/170619505-993619b8-4e62-4378-abf8-577e4674c3ed.png)

There seems to be a semver lock between the newest ts-jest and Baileys' @types/jest required version on 3eeded66b22c97e52398d1cafaf81bf185bf8cd5

**To Reproduce**
1. `git clone https://github.com/adiwajshing/Baileys`
2. `npm i -D`
3. Error

**Expected behavior**
`npm i -D` works successfully.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like?  Not related
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
[Pastebin to ERESOLVE](https://pastebin.com/KymrdtHt)

**Possible Fixes**
1. Installing the latest @types/jest solves the issue.
![image](https://user-images.githubusercontent.com/40712686/170620626-c38ce02b-8cdf-4274-87a0-4574c8880aa7.png)

**Comment by SheIITear** [comment]
Use ```yarn install```.

**Comment by HanzCEO** [comment]
> Use `yarn install`.

Oh, you're right. Maybe Baileys did not need npm users?

**Comment by SheIITear** [comment]
> > Use `yarn install`.
> 
> 
> 
> Oh, you're right. Maybe Baileys did not need npm users?

In the readme.md `yarn` is used instead of `npm`. Hence my comment.

**Comment by HanzCEO** [comment]
I will let adi decide on this. Will he supports npm users or otherwise.
Meanwhile, i will apply band-aid for my repository.
