### ISSUE TITLE
 how do i display QR code in html page?

### ISSUE THREAD

**Issue by Mmarjann** [adiwajshing/Baileys#1670]
how do i display QR code in html page?

**Comment by textarea** [comment]
Save QR code into a file
`import * as QRCode from 'qrcode';`
`QRCode.toFile(qrcodeImagePath, qrtext, {
            color: {
              dark: '#000000', // Black dots
              light: '#0000', // Transparent background
            },
          });`

**Comment by jasmanX** [comment]
how to get token (qr code key) before scanning ? how to generate wa token ?

**Comment by jasmanX** [comment]
> Save QR code into a file `import * as QRCode from 'qrcode';` `QRCode.toFile(qrcodeImagePath, qrtext, { color: { dark: '#000000', // Black dots light: '#0000', // Transparent background }, });`

how to get pre qr token ?
