### ISSUE TITLE
Explain query format to send Whatsapp server for contribution.

### ISSUE THREAD

**Issue by AxeemHaider** [adiwajshing/Baileys#1671]
Thanks for this great library I want to contribute in it. For this I want to know something. 
In most of the place we see you send queries to whatsapp server like this.
```js
{
        tag: 'iq',
	attrs: {
		to: 's.whatsapp.net',
		xmlns: 'w:biz',
		type: 'get'
	},
	content: [{
		tag: 'business_profile',
		attrs: { v: '244' },
		content: [{
			tag: 'profile',
			attrs: { jid }
		}]
	}]
}
```

I totally understand this format and encoding part, you encode it in binary and this send to server, I understand this part But I want to know how exactly you know **What to send** For example you added `xmlns: 'w:biz'` how you know you have to add it?

I think only why to know these things is to inspect the `web.whatsapp.net` socket communication but this is in Binary and I think in encoded form, how you are decoding and convert Binary to understand it. Are you doing this in the inspection tab or what other tools you are using. Can you please let us know so we can better contribute in it. 

@adiwajshing

**Comment by guilhermeromer** [comment]
You can check exactly what queries WhatsApp execute by pasting this on your console when you open your WhatsApp Web on the browser. It will automatically decode the binary to the tags that you are wanting to see. I use this to build custom functions using the query method.

Hope it helps!

```
if (!window.mR) {
    const moduleRaid = function () {
      moduleRaid.mID  = Math.random().toString(36).substring(7);
      moduleRaid.mObj = {};

      fillModuleArray = function() {
        (window.webpackChunkbuild || window.webpackChunkwhatsapp_web_client).push([
          [moduleRaid.mID], {}, function(e) {
            Object.keys(e.m).forEach(function(mod) {
              moduleRaid.mObj[mod] = e(mod);
            })
          }
        ]);
      }

      fillModuleArray();

      get = function get (id) {
        return moduleRaid.mObj[id]
      }

      findModule = function findModule (query) {
        results = [];
        modules = Object.keys(moduleRaid.mObj);

        modules.forEach(function(mKey) {
          mod = moduleRaid.mObj[mKey];

          if (typeof mod !== 'undefined') {
            if (typeof query === 'string') {
              if (typeof mod.default === 'object') {
                for (key in mod.default) {
                  if (key == query) results.push(mod);
                }
              }

              for (key in mod) {
                if (key == query) results.push(mod);
              }
            } else if (typeof query === 'function') { 
              if (query(mod)) {
                results.push(mod);
              }
            } else {
              throw new TypeError('findModule can only find via string and function, ' + (typeof query) + ' was passed');
            }

          }
        })

        return results;
      }

      return {
        modules: moduleRaid.mObj,
        constructors: moduleRaid.cArr,
        findModule: findModule,
        get: get
      }
    }

    window.mR = moduleRaid();   
}


if (!window.injected) {
    const decodeStanza = (window.mR.findModule('decodeStanza')[0]).decodeStanza;
    const encodeStanza = (window.mR.findModule('encodeStanza')[0]).encodeStanza;


    (window.mR.findModule('decodeStanza')[0]).decodeStanza = async (e, t) => {
        const result = await decodeStanza(e, t);

        console.log('FROM SERVER ->', result.toString());
        return result;
    }


    (window.mR.findModule('encodeStanza')[0]).encodeStanza = (e) => {
        const result = encodeStanza(e);

        console.log('TO SERVER ->', e.toString());
        return result;
    }

    window.injected = true;
}
```

**Comment by matheusb-comp** [comment]
Thanks, @guilhermeromer! Is this code based on [moduleRaid](https://github.com/pixeldesu/moduleRaid)?

I did not know about this module with the `decodeStanza` method in the [`bootstrap_qr`](https://web.whatsapp.com/bootstrap_qr.a93ca7c63be0f2cdef56.js)

**Comment by AxeemHaider** [comment]
The one I'm doing is
1. Login to WA Web on Chrome
2. Go to the inspector => sources
3. Adding log-points to the encodeStanza & decodeStanza method
4. Observe console for the requests sent

But nothing is printing on my console I don't know this is efficient way because every time you should not have paste the code on console and you can read all incoming and outgoing request from beginning
![unknown](https://user-images.githubusercontent.com/27768863/171556739-3dfa54a2-20fa-4670-ab33-58eff2dfeeba.png)

**Comment by guilhermeromer** [comment]
You should post this code on the Console tab on Chrome. Just paste it there and it will begin to show you the queries.

**Comment by AxeemHaider** [comment]
Which code the one you write ? 

The problem in pasting code everytime in console you loose some initial communication while opening console and pasting code there
