### ISSUE TITLE
WhatsApp dos not send message while using non resedentual ip address. 

### ISSUE THREAD

**Issue by beshoo** [adiwajshing/Baileys#1679]
Am testing the actual WhatsApp web service via the Chrome browser. 

If am using protonVpn on my pc, WhatsApp can receive messages, but it will not send. 

Once you send messages, waiting clock icon remains, ince disable the vpn. Message sent. 

Sometimes it works even with VPN. But most of the time it wasn't. 

I test bailey's, samething. 

What should we do?

**Comment by KevinEduardo** [comment]
Stop using VPN. Can't you? Try another VPN provider, such as Webscribe, NordVPN, or any other.

**Comment by marutichintan** [comment]
I am using proxy. you can try proxy its working fine for me.

**Comment by sultanlive** [comment]
> I am using proxy. you can try proxy its working fine for me.
Hello, what proxy are you using?
