### ISSUE TITLE
Cara kirim Katalog di bot Md gmna bwang ? (How to send catalog message)

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#1682]
How to send catalog message with bayles md, anyone can help me please ?

**Comment by zennn08** [comment]
English please!

**Comment by Kenzuya** [comment]
gatau, coba lu tanya pake bhs inggris

**Comment by Errs404** [comment]
gampang
reply("ini katalog banh)
wkwkw

**Comment by officialdittaz** [comment]
> gampang reply("ini katalog banh) wkwkw

Aduh... Si akang ini teh aya aya wae :v

**Comment by WahyuPR0** [comment]
Please say English

**Comment by officialdittaz** [comment]
> Please say English

Say English Gundul mu

**Comment by XiaFixy** [comment]
Bang

**Comment by WahyuPR0** [comment]
> > Please say English
> 
> Say English Gundul mu

Aowkwk bangsat

**Comment by officialdittaz** [comment]
> Bang

Iya beb ?
