### ISSUE TITLE
[REQ] Add response code into groupParticipantsUpdate

### ISSUE THREAD

**Issue by VEXG** [adiwajshing/Baileys#1683]
this is helpful when u want to handle some cases like ex. when the action is "add" and the user is private from being invited it will return a response code to mention that the user is private from inviting group

**Comment by Zobin33** [comment]
Yeah, Also sendMessage When Error Doesnt Send Error Or Status

**Comment by Zobin33** [comment]
> > Yeah, Also sendMessage When Error Doesnt Send Error Or Status
> 
> Off topic better to submit new issue tho

Sikontol Ngelunjak

**Comment by Zobin33** [comment]
> > Yeah, Also sendMessage When Error Doesnt Send Error Or Status
> 
> Off topic, better to submit new issue tho

But Relate, Some Methods Doesnt Send Some Response

**Comment by Zobin33** [comment]
> > Yeah, Also sendMessage When Error Doesnt Send Error Or Status
> 
> Off topic, better to submit new issue tho

But Relate, Some Functions Doesnt Send Error Response

**Comment by Zobin33** [comment]
> > > Yeah, Also sendMessage When Error Doesnt Send Error Or Status
> > 
> > 
> > Off topic, better to submit new issue tho
> 
> But Relate, Some Functions Doesnt Send Error Response

relayMessage Just Send MessageID.
