### ISSUE TITLE
[BUG] a hidden tag is send by bot to iphone users only

### ISSUE THREAD

**Issue by jacktheboss220** [adiwajshing/Baileys#1690]
I used this library and made a bot.
 while  sending a message sometime it tag random iphone user
without there tag id or name.
pls help

**Comment by erickythierry** [comment]
> I used this library and made a bot. while sending a message sometime it tag random iphone user without there tag id or name. pls help

now there is a new way of formatting jid.  with the multi device update, whatsapp identifies different sessions of the same number as follows:

112233445566:XX@s.whatsapp.net

notice it now has an increment ":XX" where "XX" is some number.

in this way, the same number can have different jid from this increment

although.  if you try to create a hide tag message using jid's with this ":XX" increment, you will only notify iPhone users.  
but. why?

well.  I don't know.  for some reason whatsapp understands that a hide tag with jid in this format notifies only iPhone users

if you test create a random jid like this: 

112233445566:@s.whatsapp.net 

and add it as a hide tag in a message, you will also be able to notify all iPhone users in a group.

I had this same problem using hide tag.  so I created a simple function that removes this number ":XX" from the jid before inserting it into the hide tag.  so I can notify all users of a group

**Comment by jacktheboss220** [comment]
> > I used this library and made a bot. while sending a message sometime it tag random iphone user without there tag id or name. pls help
> 
> now there is a new way of formatting jid. with the multi device update, whatsapp identifies different sessions of the same number as follows:
> 
> 112233445566:[XX@s.whatsapp.net](mailto:XX@s.whatsapp.net)
> 
> notice it now has an increment ":XX" where "XX" is some number.
> 
> in this way, the same number can have different jid from this increment
> 
> although. if you try to create a hide tag message using jid's with this ":XX" increment, you will only notify iPhone users. but. why?
> 
> well. I don't know. for some reason whatsapp understands that a hide tag with jid in this format notifies only iPhone users
> 
> if you test create a random jid like this:
> 
> 112233445566:@s.whatsapp.net
> 
> and add it as a hide tag in a message, you will also be able to notify all iPhone users in a group.
> 
> I had this same problem using hide tag. so I created a simple function that removes this number ":XX" from the jid before inserting it into the hide tag. so I can notify all users of a group

okay i will try.
thanx 😄
