### ISSUE TITLE
[Bug] Can't connect with brand new account

### ISSUE THREAD

**Issue by coolnickname** [adiwajshing/Baileys#17]
Error: https://pastebin.com/AhfgZBCr

This happens when connecting with a brand new whatsapp account with no chats or groups. After I started a conversation and sent a message it worked as expected.

**Comment by adiwajshing** [comment]
Not a major issue, but I'll look into it.

**Comment by adiwajshing** [comment]
Should be fixed in the latest version. Do test and lemme know.

**Comment by adiwajshing** [comment]
This is being handled in #34. Closing.
