### ISSUE TITLE
Load Messages

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1703]
How can I load messages newer than the last message time or last message id?

**Comment by Zarinia** [comment]
can I use cursor.after
```
const useCursor = "after" in cursor ? cursor : null;
messages = await this.store.loadMessages(jid, limit, useCursor);
```

**Comment by Zarinia** [comment]
According to this issue #1658 
How can I receive recent messages after a specific message ID?

**Comment by Zarinia** [comment]
When I use cursor.after returning an empty array

**Comment by Zarinia** [comment]
@barkerpedro 
@galiazzi 
@edgardmessias 
@Diden05 
No one can help?

**Comment by aislanspeedio** [comment]
For me the `load messages` method is returning empty array indendepently I use `before` ou `after` cursor.

My goal is to load new messages from the server to update my store.
