### ISSUE TITLE
Request Feature: Copy Button

### ISSUE THREAD

**Issue by MFarelS** [adiwajshing/Baileys#1704]
![Screenshot_20220606-150213_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/172127658-e7c8aabe-88be-4bb5-954b-3b53904b5740.jpg)

are this button is possible in baileys??

**Comment by erickythierry** [comment]
> ![Screenshot_20220606-150213_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/172127658-e7c8aabe-88be-4bb5-954b-3b53904b5740.jpg)
> 
> are this button is possible in baileys??

 can you get this message again? so you could run the baileys on your whatsapp number and analyze the logs when receiving this message. so you could see how json works and try to replicate

**Comment by MFarelS** [comment]
> > ![Screenshot_20220606-150213_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/172127658-e7c8aabe-88be-4bb5-954b-3b53904b5740.jpg)
> > are this button is possible in baileys??
> 
> can you get this message again? so you could run the baileys on your whatsapp number and analyze the logs when receiving this message. so you could see how json works and try to replicate

![Screenshot_20220609-001343_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/172677702-bb06e016-81f3-4909-9b71-f97d23da32bb.jpg)

**Comment by MFarelS** [comment]
case prefix+"copybutton":
    var captionnye = q.split('|')[0] || `By MFarelS ID`
var displaynye = q.split('|')[1] || `mfarels.id`
var copynye = q.split('|')[2] || `Parel Ganteng Banget`
const menuButa = [
    {index: 1, urlButton: {displayText: `${displaynye}`, url: 'https://www.whatsapp.com/otp/copy/'+copynye}},
]
    await ichi.sendMessage(from, { text: `${captionnye}`, templateButtons: menuButa, footer: `MFarelS ID` })
    break

**Comment by MFarelS** [comment]
solved

**Comment by frmdeveloper** [comment]
> @MFarelS
are this button is possible in baileys??

Yes, multi-device baileys supports all illegal messages
```js
sock.sendMessage(jid, {
  text: `Kode verifikasi Anda adalah 577345`,
  templateButtons: [{
    index: 1,
    urlButton: {
      displayText: `Salin kode`,
      url: 'https://www.whatsapp.com/otp/copy/577345'
    }
  }],
  footer: `FRM`
})
```

**Comment by azudindaem** [comment]
Its just normal template message with whatsapp special api link

https://www.whatsapp.com/otp/copy/<your code>

its appear Copy icon on device.. on web & desktop its still using link icon

**Comment by codevjs** [comment]
> > @MFarelS
> > are this button is possible in baileys??
> 
> Yes, multi-device baileys supports all illegal messages
> 
> ```js
> sock.sendMessage(jid, {
>   text: `Kode verifikasi Anda adalah 577345`,
>   templateButtons: [{
>     index: 1,
>     urlButton: {
>       displayText: `Salin kode`,
>       url: 'https://www.whatsapp.com/otp/copy/577345'
>     }
>   }],
>   footer: `FRM`
> })
> ```

can templateButtons request location?

**Comment by ahmedRSA** [comment]
> link

@MFarelS  what bot u use in screenshot?

**Comment by frmdeveloper** [comment]
OOO YA NDAK TAU

**Comment by ArdyBotzz** [comment]
> OOO YA NDAK TAU

[https://github.com/adiwajshing/Baileys/issues/1704#issuecomment-1150623146](url)
