### ISSUE TITLE
[BUG] TypeError: Cannot read property 'subject' of undefined

### ISSUE THREAD

**Issue by Tanaka9531** [adiwajshing/Baileys#1705]
TypeError: Cannot read property 'subject' of undefined
    at client (D:\New_folder\main.js:148:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
const groupName = m.isGroup ? groupMetadata.subject : ''

How To Fix This?

**Comment by Tanaka9531** [comment]
import { Contact } from './Contact';
export declare type GroupParticipant = (Contact & {
    isAdmin?: boolean;
    isSuperAdmin?: boolean;
    admin?: 'admin' | 'superadmin' | null;
});
export declare type ParticipantAction = 'add' | 'remove' | 'promote' | 'demote';
export interface GroupMetadata {
    id: string;
    owner: string | undefined;
    subject: string | undefined;
    creation: number;
    desc?: string;
    descOwner?: string;
    descId?: string;
    /** is set when the group only allows admins to change group settings */
    restrict?: boolean;
    /** is set when the group only allows admins to write messages */
    announce?: boolean;
    participants: GroupParticipant[];
    ephemeralDuration?: number;
}
export interface WAGroupCreateResponse {
    status: number;
    gid?: string;
    participants?: [{
        [key: string]: any;
    }];
}
export interface GroupModificationResponse {
    status: number;
    participants?: {
        [key: string]: any;
    };
}

i add | undefined in subject: string;
and i get new problem TypeError: Cannot read property 'caption' of undefined

**Comment by azudindaem** [comment]
Please show your code. Below is basic usage

```javascript
const metadata = await sock.groupMetadata("abcd-xyz@g.us") 
console.log(metadata.id + ", title: " + metadata.subject + ", description: " + metadata.desc)
```
