### ISSUE TITLE
[BUG] sending an empty reaction does not remove the previous one

### ISSUE THREAD

**Issue by erickythierry** [adiwajshing/Baileys#1707]
my last attempt was like this:

```
let reactResult = await sock.sendMessage(from, { react: { text: "⌛", key: msg.key } })
let keyResult = reactResult.message.ephemeralMessage.message.reactionMessage.key

await delay(2000)

let reactionMessage = {
        react: {
            text: "",
            key: keyResult
        }
}

await sock.sendMessage(from, reactionMessage)
```

but nothing happens

would anyone know a functional way to remove the reaction created earlier?

**Comment by fadiinho** [comment]
You need to send the empty reaction to the message you reacted.
```js
await sock.sendMessage(from, { 
  react: { 
    text: "⌛", 
    key: msg.key // use this in the empty reaction
  } 
})  

await delay(2000) 
let reactionMessage = { 
  react: { 
    text: "", 
    key: msg.key // here you use msg.key instead of keyResult
  } 
} 

await sock.sendMessage(from, reactionMessage)
```

**Comment by SheIITear** [comment]
This isn't a bug, as @fadiinho mentioned you're reacting to the reaction.

**Comment by erickythierry** [comment]
> This isn't a bug, as @fadiinho mentioned you're reacting to the reaction.

but this also occurs if I try to get the id of the message i reacted earlier. does not work send another reaction or even send an empty reaction.

**Comment by erickythierry** [comment]
> You need to send the empty reaction to the message you reacted.
> 
> ```js
> await sock.sendMessage(from, { 
>   react: { 
>     text: "⌛", 
>     key: msg.key // use this in the empty reaction
>   } 
> })  
> 
> await delay(2000) 
> let reactionMessage = { 
>   react: { 
>     text: "", 
>     key: msg.key // here you use msg.key instead of keyResult
>   } 
> } 
> 
> await sock.sendMessage(from, reactionMessage)
> ```

I did it. but I didn't get the expected result. i'm using the stavel version of npm (4.1.0).does this influence? or in this version already have this option to remove a reaction? because I've actually done it that you exemplified and i didn't have the expected result

**Comment by fadiinho** [comment]
> > You need to send the empty reaction to the message you reacted.
> > ```js
> > await sock.sendMessage(from, { 
> >   react: { 
> >     text: "⌛", 
> >     key: msg.key // use this in the empty reaction
> >   } 
> > })  
> > 
> > await delay(2000) 
> > let reactionMessage = { 
> >   react: { 
> >     text: "", 
> >     key: msg.key // here you use msg.key instead of keyResult
> >   } 
> > } 
> > 
> > await sock.sendMessage(from, reactionMessage)
> > ```
> 
> I did it. but I didn't get the expected result. i'm using the stable version of npm (4.1.0).does this influence? or in this version already have this option to remove a reaction? because I've actually done it that you exemplified and i didn't have the expected result

I just tested with the npm version and worked as expected, I guess you did something wrong in your code.
