### ISSUE TITLE
Error : Connection Terminated by Server [BUG]

### ISSUE THREAD

**Issue by caliphdev** [adiwajshing/Baileys#1708]
I tried bot command in group, then error like this

![IMG-20220607-WA0006](https://user-images.githubusercontent.com/92326690/172284926-0f5a8231-af37-4a1b-8665-46bf263c5295.jpg)

Please Help

**Comment by caliphdev** [comment]
> Hello, the error appears when your bot sends a message?

Yes, right

**Comment by MarvynSTAR** [comment]
> > Hello, the error appears when your bot sends a message?
> 
> Yes, right

That means your bot sends the message before the connection is open.

**Comment by caliphdev** [comment]
> > > Hello, the error appears when your bot sends a message?
> > 
> > 
> > Yes, right
> 
> That means your bot sends the message before the connection is open.

but it only happens in some groups

**Comment by muzafferkadir** [comment]
> > > Hello, the error appears when your bot sends a message?
> > 
> > 
> > Yes, right
> 
> That means your bot sends the message before the connection is open.

What should we do?

**Comment by MarvynSTAR** [comment]
> > > > Hello, the error appears when your bot sends a message?
> > > 
> > > 
> > > Yes, right
> > 
> > 
> > That means your bot sends the message before the connection is open.
> 
> but it only happens in some groups

Can you please show us the interested piece of code? We can't help you without it.
(@muzafferkadir)

**Comment by caliphdev** [comment]
solved

**Comment by aislanspeedio** [comment]
> solved

How did you solved it ???
