### ISSUE TITLE
Writing QR code to file

### ISSUE THREAD

**Issue by bhavya32** [adiwajshing/Baileys#171]
> conn.on('qr', qr => {
    // Now, use the 'qr' string to display in QR UI or send somewhere
}

Is QR here base64? I am unable to write it to file. I need to export qr to jpg image file.

**Comment by adiwajshing** [comment]
Yeah it's a string -- if you `console.log`, you'll find the same. It's kept as the raw string that needs to be converted to a QR so its more versatile & can be distributed faster.

**Comment by bhavya32** [comment]
OK. Now I got it. Actually I was trying it to directly write to file without converting to QR. It works fine after converting the string to QR and then writing to file.
