### ISSUE TITLE
TimeOut

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1711]
‍‍‍‍‍‍```
 [server] error: unhandledRejection: Timed Out
WhatsApp  | Error: Timed Out
WhatsApp  |     at /usr/src/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32 Error: Timed Out
WhatsApp  |     at /usr/src/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32
WhatsApp  | Jun-07-2022 11:11:59 [server] error: Error: Timed Out
```

**Comment by erickythierry** [comment]
> ‍‍‍‍‍‍``` [server] error: unhandledRejection: Timed Out WhatsApp | Error: Timed Out WhatsApp | at /usr/src/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32 Error: Timed Out WhatsApp | at /usr/src/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32 WhatsApp | Jun-07-2022 11:11:59 [server] error: Error: Timed Out

if you are using baileys directly from github, switch to the stable version available at npm (4.1.0). this 428 error is occurring a lot in the most current direct version of github.

**Comment by MarvynSTAR** [comment]
Hello, it's difficult to help you without a minimum of context.
Do you see this error when logging in or randomly while the bot is active?

**Comment by mrhb6006** [comment]
same issues

**Comment by Zarinia** [comment]
@MarvynSTAR 
Hi, I saw it randomly

**Comment by pe77** [comment]
same error

**Comment by phaticusthiccy** [comment]
#1736 Moreover, the link I sent contains this error. If it's useful, you guys can have a check it.
