### ISSUE TITLE
Portability Between Baileys and Venom/Sulla

### ISSUE THREAD

**Issue by bhavya32** [adiwajshing/Baileys#172]
I have made two backends from Venom and Baileys which can be switched at a single click without changing anything. But the problem is the tokens are still not portable. Although there is code which can read tokens from venom but it is giving the following error - 

```
[Baileys][9/28/2020, 11:32:11 AM] closed connection, reason invalid_session
(node:10812) UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'admin': Unauthorized(401)
    at WAConnection.query (C:\Users\bhavy\Desktop\Baileys\server\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:240:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\bhavy\Desktop\Baileys\server\node_modules\@adiwajshing\baileys\lib\WAConnection\1.Validation.js:68:32
    at async Promise.all (index 1)
    at async WAConnection.authenticate (C:\Users\bhavy\Desktop\Baileys\server\node_modules\@adiwajshing\baileys\lib\WAConnection\1.Validation.js:77:33)
    at async Promise.all (index 1)
    at async WebSocket.<anonymous> (C:\Users\bhavy\Desktop\Baileys\server\node_modules\@adiwajshing\baileys\lib\WAConnection\3.Connect.js:108:42)
(node:10812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
The token works fine in venom.

**Comment by adiwajshing** [comment]
Browser auth works correctly, the reason `401` pops up is if the session is logged out, that is the credentials are invalidated. Please just verify that that is not the case.

**Comment by bhavya32** [comment]
@adiwajshing Yeah. its not the case. Problem is something else.

**Comment by Manjit2003** [comment]
It seems like Venom depends upon a browser as compared to Baileys which does not requires one....

**Comment by bhavya32** [comment]
@Manjit2003 No. That is not case here. Baileys, instead of controlling browser, acts as a browser. Tokens are necessary. They are both used by Baileys and Venom just with some different token structure files. Baileys has the code to use tokens from venom/sulla by converting it to required format.

**Comment by adiwajshing** [comment]
@bhavya32 Can you share what the Venom tokens look like? Please do alter/remove the values before posting

**Comment by bhavya32** [comment]
Sorry, but now strangely it started to work. What I just did was created a new token in venom and imported it to baileys. Thank You. Maybe a corrupt token in Venom previous time(but I don't know how venom read that successfully) .
