### ISSUE TITLE
Closing open session

### ISSUE THREAD

**Issue by Zarinia** [adiwajshing/Baileys#1722]
```
WhatsApp  | Closing open session in favor of incoming prekey bundle
 Closing session: SessionEntry {
WhatsApp  |   _chains: {
.....
```

**Comment by phaticusthiccy** [comment]
I have not seen this error cause a general chaining problem. 
Could you explain a little more and write what kind of errors it caused? Also if it possible, the screenshot or code snippets may more explanatory.

**Comment by Zarinia** [comment]
@phaticusthiccy 
Please read this issue:
‍‍‍```https://github.com/adiwajshing/Baileys/issues/1757```
I still have a problem and I do not know the solution
