### ISSUE TITLE
How delete chats and messages??

### ISSUE THREAD

**Issue by biguitarman** [adiwajshing/Baileys#1723]
Hi, how i delete chats or messages?, i read the documentation and not work.
example:

`{
    "key": {
      "remoteJid": "57301984026@s.whatsapp.net",
      "fromMe": false,
      "id": "3EB099DA7EA98C489DBD"
    },
    "message": {
      "imageMessage": {
        "url": "https://mmg.whatsapp.net/d/f/AvG0DFjU3vUsjF9ogCmhiTy0ETX04YNkFKTvhAABZA47.enc",
        "mimetype": "image/jpeg",
        "fileSha256": "jYKEVCfUTU8+UgwNiAVUaQ/XxYuHta8mnuxTxLxwsEk=",
        "fileLength": "289807",
        "height": 578,
        "width": 1280,
        "mediaKey": "T8FpqTKb/pdATe2mwbWPGKeuIRr8DAlvitZ3r+er4XI=",
        "fileEncSha256": "vyZ5yf7wTTOP8nqeiryBNsc4yBg8GhC6lvuyN9/g3SU=",
        "directPath": "/v/t62.7118-24/26097893_2195645397280648_939321114478832633_n.enc?ccb=11-4&oh=01_AVy_AtZQaDR-k4klClpmKJk9nuBcxmxL8tNtINMju-vQRw&oe=62C67CBA",
        "mediaKeyTimestamp": "1654713254"
      }
    },
    "messageTimestamp": "1654713256",
    "ephemeralOutOfSync": false
  }`

then, not work

'messages.delete':  { jid: "57301984026@s.whatsapp.net", all: true }

**Comment by hassanfuad96** [comment]
Try see this 

https://github.com/adiwajshing/Baileys/pull/1718

**Comment by biguitarman** [comment]
Not show how!!

**Comment by DwiRizqiH** [comment]
if you want delete message for everyone
`await sock.sendMessage('123xxxx@s.whatsapp.net', { delete: message.key })`

if you want delete message for me
see this https://github.com/adiwajshing/Baileys/pull/1718
`await sock.chatModify({ clear: { messages: [{ id: 'ATWYHDNNWU81732J', fromMe: true, timestamp: "1654823909" }] } }, 
    '123xxxx@s.whatsapp.net', 
    []
)`

**Comment by yepestore** [comment]
> if you want delete message for everyone `await sock.sendMessage('123xxxx@s.whatsapp.net', { delete: message.key })`
> 
> if you want delete message for me see this #1718 `await sock.chatModify({ clear: { messages: [{ id: 'ATWYHDNNWU81732J', fromMe: true, timestamp: "1654823909" }] } }, '123xxxx@s.whatsapp.net', [] )`

how to delete for everyone quoted message?
