### ISSUE TITLE
How to figure connection is lost or QR attempts ended.

### ISSUE THREAD

**Issue by AxeemHaider** [adiwajshing/Baileys#1724]
If you check `connectionLost` and `timeout` both has same status code `408` so it's hard to figure out with the status that connection is lost or just qr ref attempts ended. Only way is to read the error message. But I think we should have to make it better by adding some kind of extra property to let know that connection was lost or qr attempts fail?

**Comment by azudindaem** [comment]
```json
{
	"error": {
		"data": null,
		"isBoom": true,
		"isServer": false,
		"output": {
			"statusCode": 408,
			"payload": {
				"statusCode": 408,
				"error": "Request Time-out",
				"message": "QR refs attempts ended"
			},
			"headers": {}
		}
	},
	"date": "2022-06-11T01:13:14.686Z"
}
```
