### ISSUE TITLE
Php Working with

### ISSUE THREAD

**Issue by mehmetsarr** [adiwajshing/Baileys#1729]
Hello, how can I run this repository in php?

**Comment by mehmetsarr** [comment]
> May AssemblyScript? I'm not so sure it will work, but porting this system to a web interface wouldn't make much sense.

I'm thinking of coding with Codeigniter 4.

**Comment by khoirulh1610** [comment]
provided hosting that supports nodejs then make it a rest api for Baileys. connect with restapi for the connection. if you need help, you can contact me.

**Comment by mehmetsarr** [comment]
> provided hosting that supports nodejs then make it a rest api for Baileys. connect with restapi for the connection. if you need help, you can contact me.

Thank you for your reply. Do I need to install this repository on the server now? How do I do it? I don't know how to do the rest api either.
