### ISSUE TITLE
Can It be converted to a rest-api with multiple whatsapp accounts?

### ISSUE THREAD

**Issue by Manjit2003** [adiwajshing/Baileys#173]
**@adiwajshing** thank you very much for this amazing library...
I just wanted to ask if I can make a rest-api out of this library?  If yes then can you please guide me?

**Comment by adiwajshing** [comment]
Glad you like the library. It can be made into a REST API fairly easily. However, I don't have enough free time to guide you.

**Comment by bhavya32** [comment]
@Manjit2003 If you are looking for some business, join with me. You can use express. I have a complete rest api with registration and Sending message including webhooks.

**Comment by Manjit2003** [comment]
@bhavya32 is it for free?

**Comment by Manjit2003** [comment]
@bhavya32 well i am not doing business actually i want to send payment receipt using this api also my hotel has several branches so i think that multiple instances will required. I have successfully made an rest-api but the problem is that the connection keeps closing after a few hours. Do you have any solution to prevent this?🤔

**Comment by dinnos** [comment]
@Manjit2003 if you prefer you can try our service: [Leadsales](https://leadsales.io/en/) the landing video is in Spanish but you can request information in English.

**Comment by bhavya32** [comment]
@dinnos what are you charging man. I am charging 5 usd a month for rest-api and you are charging 90 usd?

**Comment by dinnos** [comment]
@bhavya32 is for the infrastructure we divide the service between Firebase and AWS, the first for serverless and hosting (APP - CRM) and in AWS we have a container-based architecture to keep copies of the rest-api (Baileys) with a load balancer to redirect requests from clients to the container that has their API instance.

**Comment by Manjit2003** [comment]
@dinnos Whatever but still 90$ a month !!

**Comment by bhavya32** [comment]
@dinnos But what if baileys broke due to a change in whatsapp web?

**Comment by Gidraf** [comment]
@bhavya32 That's why we are here we should make this project to be live as long as possible.

**Comment by dinnos** [comment]
@bhavya32 baileys is momentary, right now we are working to receive the approval of FB but as you say it is a problem, that something could break although for now we have only had connection problems.

**Comment by itacirgabral** [comment]
> Can It be converted to a rest-api with multiple whatsapp accounts?

I'm working on this for an internal service of my company to replace chat-api in our products. You can have multiple connections:
```javascript
const conn1 = new WAConnection(credential1)
const conn2 = new WAConnection(credential2)
// (...)
const connN = new WAConnection(credentialN) 
```
expanded example:
https://gist.github.com/itacirgabral/98a6e70bba743a557d685296392810bd

> can you please guide me?

Make your repo public and show work. Probably you will make questions that I want to hear the answer from the others.

mini intro guide:
1. fix and run my example
2. learn https://expressjs.com/en/guide/routing.html
3. make the route `/instances/:id/sendmessage` that receive post with `{"jid":"deliveryto@s.whatsapp.net","text":"HelloWorld"}`
4. inside the router's handler find the instance and send the message

**Comment by hacen-ai** [comment]
@rawars I am really interested with your question... did you find a solution bro ?

**Comment by itacirgabral** [comment]
little demo
https://github.com/danarn17/baileys-whatsapp-api

**Comment by MuhammadKarzoun** [comment]
I am looking for multi agent platform to sell the service as saas

**Comment by itacirgabral** [comment]
@MuhammadKarzoun 
> I am looking for multi agent platform to sell the service as saas

a backup from my old job:
https://github.com/itacirgabral/GMAPI/tree/mdconnect/tsmotte

it is not updated.

be happy :)

**Comment by itacirgabral** [comment]
allah bless you @MuhammadKarzoun 

can you write code? Take a tour https://github.com/itacirgabral/GMAPI/tree/v2_main
