### ISSUE TITLE
Delivered message

### ISSUE THREAD

**Issue by Dguruz21** [adiwajshing/Baileys#1730]
Hello guys, I was trying to implement a funtion to know if a message is delivered or not, Anyone who can help please. Thanks in advance.

**Comment by azudindaem** [comment]
Check on this event listener so that you know how to do the rest 
```
sock.ev.on('messages.update', m => console.log(m))
sock.ev.on('message-receipt.update', m => console.log(m))
sock.ev.on('presence.update', m => console.log(m))
sock.ev.on('chats.update', m => console.log(m))
sock.ev.on('chats.delete', m => console.log(m))
sock.ev.on('contacts.upsert', m => console.log(m))
```

**Comment by russocorp** [comment]
i am using "messages.update" from this.
then, i use "msg.update.status" and update my database with this value.
https://adiwajshing.github.io/Baileys/enums/proto.WebMessageInfo.WebMessageInfoStatus.html#SERVER_ACK

**Comment by ANazih** [comment]
> i am using "messages.update" from this. then, i use "msg.update.status" and update my database with this value. https://adiwajshing.github.io/Baileys/enums/proto.WebMessageInfo.WebMessageInfoStatus.html#SERVER_ACK

Work fine thank you
