### ISSUE TITLE
[BUG] Link with preview is not working on android

### ISSUE THREAD

**Issue by hbinduni** [adiwajshing/Baileys#1735]
i try to send msg with link, and `add link-preview-js`, but it seem, link with preview only working on `desktop` and `ios`. link with preview is not working for `android`. is that correct?

**Comment by diazzaid** [comment]
> i try to send msg with link, and `add link-preview-js`, but it seem, link with preview only working on `desktop` and `ios`. link with preview is not working for `android`. is that correct?

same problem on github:adiwajshing/baileys version.
for stable version 4.1.0 works fine

**Comment by Islam-Mohammed-Younes** [comment]
#1719 related

**Comment by officialdittaz** [comment]
> > i try to send msg with link, and `add link-preview-js`, but it seem, link with preview only working on `desktop` and `ios`. link with preview is not working for `android`. is that correct?
> 
> * I know your problem. The error here is that the contextInfo on baileys github is not detected even though we write it. so I tried to make a new function. here is the code
> 
> ```js
>   /**
>    * sendMessage v2
>    * @param {String} chatId
>    * @param {import('@adiwajshing/baileys').AnyMessageContent} message
>    * @param {import('@adiwajshing/baileys').MiscMessageGenerationOptions} options
>    * @returns
>    */
>   xue.sendMessageV2 = async (chatId, message, options = {}) => {
>     let generate = await generateWAMessage(chatId, message, options)
>     const type = getContentType(generate.message)
>     if ('contextInfo' in options) generate.message[type].contextInfo = options?.contextInfo
>     if ('contextInfo' in message) generate.message[type].contextInfo = message?.contextInfo
>     return await xue.relayMessage(chatId, generate.message, { messageId: generate.key.id })
>   }
> ```

Yeah its work, but suddenly connection always closed when i try this function,

Error : stream errored (xml-not-well-formed)
Bad session file, please delete session and scan again

**Comment by whatsera** [comment]
hello @adiwajshing 
I'm Working on your repo from quite a while and just wanna to say amazing work done by you and other contributors, but I'm having issue with link preview on android devices.
I've updated the version to 4.2.0 & also installed "link-preview-js" but nothing seems to be working.
please guide us on this issue.
thanks for making this repo.

**Comment by jrrcdev** [comment]
Hello, @adiwajshing 

There are two problems with the implementation that I found when debugging the code, missing the followRedirects option on getLinkPreview function and the 'matched-url' is different from the link in the code, for exemple, if the link in text is https://google.com, the 'matched-url' need to be https://google.com, but the regex code is getting just 'google.com'.

I made a custom function as workaround and it worked, waiting for your fix.

**Comment by whatsera** [comment]
> Hello, @adiwajshing
> 
> There are two problems with the implementation that I found when debugging the code, missing the followRedirects option on getLinkPreview function and the 'matched-url' is different from the link in the text, for exemple, if the link in text is https://google.com, the 'matched-url' need to be https://google.com, but the regex code is getting just 'google.com'.
> 
> I made a custom function as workaround and it worked, waiting for your fix.

can we have that custom function??

**Comment by jrrcdev** [comment]
> > Hello, @adiwajshing
> > There are two problems with the implementation that I found when debugging the code, missing the followRedirects option on getLinkPreview function and the 'matched-url' is different from the link in the text, for exemple, if the link in text is https://google.com, the 'matched-url' need to be https://google.com, but the regex code is getting just 'google.com'.
> > I made a custom function as workaround and it worked, waiting for your fix.
> 
> can we have that custom function??

I just generate the link preview props outside Baileys code, so it do not use the code where it get the wrong link, it was based on Baileys code:

```
try {
	const info = await getLinkPreview(previewUrl, {
		timeout: 3000,
		followRedirects: true
	});

	if (info && "title" in info) {
		const [image] = info.images;
		let jpegThumbnail = undefined;

		if (image) {
			try {
				const stream = await getHttpStream(image, {
					timeout: 3000
				});
				jpegThumbnail = await extractImageThumb(stream, 192);
			} catch (error) {
				console.log(error);
			}
		}

		result = await client.sendMessage(jid, {
			text: message,
			linkPreview: {
				"canonical-url": info.url,
				"matched-text": previewUrl,
				title: info.title,
				description: info.description,
				jpegThumbnail
			}
		});
	}
} catch (error) {
	console.log(error);
}
```
I already have the previewUrl variable extracted on my code using the following code:

```
import getUrls from "get-urls";

let urls = getUrls(value, {
		exclude: ["wa.me", "whatsapp.com"],
		removeTrailingSlash: false,
		stripWWW: false
	});
```

**Comment by 239626** [comment]
@jrrcdev 
can you help me with a working code, I am struggling finding a working link preview message code

thank you in advance
