### ISSUE TITLE
[BUG] xml-not-well-formed

### ISSUE THREAD

**Issue by viniciusgdr** [adiwajshing/Baileys#1736]
**Describe the bug**
xml-not-well-formed

**To Reproduce**
1. Start a Connection
2. Send a Message on group with 200 peoples or more (Text, video, image, all)

Error:
{"level":50,"time":1655155812883,"pid":558,"hostname":"me","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"xml-not-well-formed","attrs":{}}]},"msg":"stream errored out"}
After that the code is closed automatically

**Comment by phaticusthiccy** [comment]
As an extra, the IDs of such large groups are corrupted. MD Baileys can't read this. When it receives a request to send a message, it cannot process it. A bug that needs to be fixed.

```graphql
{
  key: {
    remoteJid: 'xxxxxxx-xxxxx@g.us',
    fromMe: Boolean,
    id: String,
    participant: 'xxxxx@s.whatsapp.net'
  },
  messageTimestamp: Number,
  pushName: 'Atticus',
  status: 2,
  message: Message { 
    conversation: 'Primon'  
  }
}
```

The `key.remoteJid` must be include `-` inside. But in the large groups, this will return like that:
```graphql
{
  key: {
    remoteJid: 'xxxxxxxxxxxx@g.us',
    fromMe: Boolean,
    id: String,
    participant: 'xxxxx@s.whatsapp.net'
  },
  messageTimestamp: Number,
  pushName: 'Atticus',
  status: 2,
  message: Message { 
    conversation: 'Primon'  
  }
}
```
Seems like it needs attention. @adiwajshing

**Comment by BochilGaming** [comment]
> As an extra, the IDs of such large groups are corrupted. MD Baileys can't read this. When it receives a request to send a message, it cannot process it. A bug that needs to be fixed.
> 
> ```graphql
> {
>   key: {
>     remoteJid: 'xxxxxxx-xxxxx@g.us',
>     fromMe: Boolean,
>     id: String,
>     participant: 'xxxxx@s.whatsapp.net'
>   },
>   messageTimestamp: Number,
>   pushName: 'Atticus',
>   status: 2,
>   message: Message { 
>     conversation: 'Primon'  
>   }
> }
> ```
> 
> The `key.remoteJid` must be include `-` inside. But in the large groups, this will return like that:
> 
> ```graphql
> {
>   key: {
>     remoteJid: 'xxxxxxxxxxxx@g.us',
>     fromMe: Boolean,
>     id: String,
>     participant: 'xxxxx@s.whatsapp.net'
>   },
>   messageTimestamp: Number,
>   pushName: 'Atticus',
>   status: 2,
>   message: Message { 
>     conversation: 'Primon'  
>   }
> }
> ```
> 
> Seems like it needs attention. @adiwajshing

I guess, new whatsapp group, the id doesn't have '-'

**Comment by phaticusthiccy** [comment]
No, this is not about that. If you try it, you will see it will work. The problem here is that it dont works in such as large groups. 
I've seen a few other people raise this issue. Some say 100 people or more, some say 200 people or more.
I don't know how many people this error starts with, but what I do know is that it doesn't work in large groups.

Considering this, in the groups of 512 people that WhatsApp has tested, I think it is an issue that should be emphasized.

**Comment by Bloxoid123** [comment]
partial solution by @LightningNeko [Here](https://github.com/adiwajshing/Baileys/issues/1552#issuecomment-1114112643) #1552

**Comment by FatihArridho** [comment]
> > As an extra, the IDs of such large groups are corrupted. MD Baileys can't read this. When it receives a request to send a message, it cannot process it. A bug that needs to be fixed.
> > ```graphql
> > {
> >   key: {
> >     remoteJid: 'xxxxxxx-xxxxx@g.us',
> >     fromMe: Boolean,
> >     id: String,
> >     participant: 'xxxxx@s.whatsapp.net'
> >   },
> >   messageTimestamp: Number,
> >   pushName: 'Atticus',
> >   status: 2,
> >   message: Message { 
> >     conversation: 'Primon'  
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `key.remoteJid` must be include `-` inside. But in the large groups, this will return like that:
> > ```graphql
> > {
> >   key: {
> >     remoteJid: 'xxxxxxxxxxxx@g.us',
> >     fromMe: Boolean,
> >     id: String,
> >     participant: 'xxxxx@s.whatsapp.net'
> >   },
> >   messageTimestamp: Number,
> >   pushName: 'Atticus',
> >   status: 2,
> >   message: Message { 
> >     conversation: 'Primon'  
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Seems like it needs attention. @adiwajshing
> 
> I guess, new whatsapp group, the id doesn't have '-'

Betul, The old whatsapp group has a different id from the new group id. 

Old group id : xxxxx-xxx@g.us
New group id: xxxx@g.us

**Comment by viniciusgdr** [comment]
But this apparently has no explicit reasons, it is possible to send messages even with the new or the old jid. The reason is that when passing a certain number of people it causes the error (that apparently the error is unknown)

**Comment by Kryknz** [comment]
Well this error is persistent in the latest baileys version. 
Hope to see a fix soon.
Most bots are failing to work in larger groups.
🙏🏽‍🙏🏽‍

**Comment by viniciusgdr** [comment]
> error: Error: Stream Errored (xml-not-well-formed)
> 
> how to fix this

The problem still hasn't been solved, we'll have to wait @adiwajshing

**Comment by azudindaem** [comment]
atm didn't have any large group to replicate the issue.. please try this pr

#1762

**Comment by manojsitapara** [comment]
> atm didn't have any large group to replicate the issue.. please try this pr
> 
> #1762

Thanks I have tried this PR, seems working fine on WhatsApp group in which has more than 500+ members

**Comment by viniciusgdr** [comment]
Apparently Resolved
