### ISSUE TITLE
Baileys time out

### ISSUE THREAD

**Issue by bhavya32** [adiwajshing/Baileys#174]
The close connection event gives time out in 2 conditions.

1. QR code read fail/ not scanned by me.
2. The connected phone not available to internet. Baileys try 6 times before closing.

Now the problem is save event is triggered with same reaseon(timed out)  but I want to do different things in 2 scenarios.
I want to do - 
1. Destroy conn variable.
2. Try infinite times.

Is it possible directly by using baileys or some code change is required?

**Comment by adiwajshing** [comment]
1. Once you call `conn.close()`, everything is disposed. You can safely dereference `conn`
2. Just set `conn.connectOptions. maxRetries = Infinity`

**Comment by bhavya32** [comment]
@adiwajshing I very well know that. Problem is the same event is triggered both times, reason is the same, so how to differentiate between both conditions.

**Comment by adiwajshing** [comment]
Just check for `authInfo` after the fail, if there is no `authInfo.encKey`, that means you weren't logged in & can destroy the conn variable.

**Comment by bhavya32** [comment]
@adiwajshing Sorry I forgot to update but I kind of solved it. I instead of checking authInfo, checked if there is a token file for that username. Thanks by the way.
