### ISSUE TITLE
[BUG] error on call base64EncodedAuthInfo()

### ISSUE THREAD

**Issue by Pedro-Matias** [adiwajshing/Baileys#1740]
Hello, I'm trying to stablish a connection, but when I call "base64EncodedAuthInfo()" 

![image](https://user-images.githubusercontent.com/32912119/173703409-39df4ff0-78b6-431e-a21d-877d97a191a6.png)
![image](https://user-images.githubusercontent.com/32912119/173703455-98871d26-f383-43d1-bfaf-9d03ff849aa1.png)

It returns the following error:

![image](https://user-images.githubusercontent.com/32912119/173703476-78cb7af8-a0f2-4b8e-b705-034893f91bd5.png)

Can anyone help me? I'm kinda newbie btw, i've tried to search for similar errors but any of those helped.

**Comment by phaticusthiccy** [comment]
Which version of baileys are you using?

**Comment by phaticusthiccy** [comment]
I must have seen this years ago 🤭, Please update your baileys version.

**Comment by Pedro-Matias** [comment]
I'm currently using v3.5.2

**Comment by phaticusthiccy** [comment]
Please close the issue.
