### ISSUE TITLE
[BUG] Member limit

### ISSUE THREAD

**Issue by Descontinou** [adiwajshing/Baileys#1743]
Wanted to know how to resolve the issue of not working in groups with more than 239 members, in useMultiFileAuthState it gets messages on hold, already useSingleFileAuthState causes it to restart and does not perform any action.

**Comment by Zynfinity** [comment]
same problem

**Comment by manojsitapara** [comment]
same issue

**Comment by manojsitapara** [comment]
This issue has been fixed in recent commit

https://github.com/adiwajshing/Baileys/commit/27f53bfa5140081db818984d274190b4c394e98f
