### ISSUE TITLE
updateProfilePicture [BUG]

### ISSUE THREAD

**Issue by raphaelvserafim** [adiwajshing/Baileys#1744]
There was an error updating the group photo .

```js 
socket.updateProfilePicture(group_id, { url: picture });

```
ERROR:

```json 
"error":{"name":"Error","message":"No image processing library available","status":500,"errors":[],"stack":"Error: No image processing library available\n    at getImageProcessingLibrary (api/lib/Utils/messages-media.js:58:11) 

```

**Comment by barkerpedro** [comment]
Install the "jimp" or "sharp" lib that should work.

**Comment by raphaelvserafim** [comment]
Installed but the error still persists

**Comment by barkerpedro** [comment]
Tell how you installed the lib?

**Comment by raphaelvserafim** [comment]
Yea

**Comment by raphaelvserafim** [comment]
I see that the error has changed
```json 
"error":{"name":"Error","message":"Input file is missing: https://www.cachesistemas.com.br/assets/files/graphic3-min.png"
```

**Comment by FatihArridho** [comment]
As far as I know the photo should be buffered.

**Comment by FatihArridho** [comment]
Or if you want to read it from the file path, you can use

let fs = require('fs')
fa.readFileSync('image.jpg')

Example : sock.updateProfilePicture("abcd@g.us", { url: await fs.readFileSync('image.jpg') })

**Comment by FatihArridho** [comment]
Please, if you understand, please close the issue

**Comment by 4l3dx** [comment]
> I see that the error has changed
> 
> ```json
> "error":{"name":"Error","message":"Input file is missing: https://www.cachesistemas.com.br/assets/files/graphic3-min.png"
> ```

That error is because sharp does not provide any networking features by default.
You can use the axios module to make HTTP requests
Example:
```typescript
const img = await axios.get("https://www.cachesistemas.com.br/assets/files/graphic3-min.png", { responseType: 'arraybuffer' });
sock.updateProfilePicture(group_id, img.data );
```
