### ISSUE TITLE
[BUG] Tick ​​1

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#1749]
# this is a bug, but it's cool
Oops, apparently this is a new feature of multi-device baileys. I misunderstood
![Screenshot_20220616-055442](https://user-images.githubusercontent.com/80396521/173955577-06ae5681-43ee-4f5e-999c-582c5ec947e1.png)

**Comment by FatihArridho** [comment]
😱😱😱😱😱

**Comment by azudindaem** [comment]
this is because the sender have different version of whatsapp?

**Comment by mohamad-supangat** [comment]
you use whatsapp mod ? @frmdeveloper

**Comment by Fokusdotid** [comment]
That's is using whatsapp mod :'v

**Comment by FatihArridho** [comment]
> 

Ok tod:v

**Comment by mohamad-supangat** [comment]
> > 
> 
> Ok tod:v

koplak sis

**Comment by frmdeveloper** [comment]
eh kok undertood

**Comment by frmdeveloper** [comment]
kepencet
