### ISSUE TITLE
[BUG] esta bugado o Baileys seu corno

### ISSUE THREAD

**Issue by michaelsousa** [adiwajshing/Baileys#1750]
Tá bugado o Baileys seu viado

**Comment by azudindaem** [comment]
English please

**Comment by viniciusgdr** [comment]
What does that mean?

**Comment by Enige1337** [comment]
He is swearing in portuguese. Just close this...

**Comment by lindionez** [comment]
KKKKKKKKKKKKK

**Comment by Coelho7638** [comment]
Lindionez is laughing why?

**Comment by canove** [comment]
Peço licença para quebra de decoro e idioma padrão:

@michaelsousa , vai se foder!

O cara mantém uma LIB excelente como essa de graça, você deveria apenas agradecer ou contribuir corrigindo o bug.

I ask permission for breach of decorum and standard language:

@michaelsousa , fuck you!

The guy maintains an excellent LIB like this for free, you should just say thanks or contribute by fixing the bug.

Please, close!

**Comment by AkirahX** [comment]
Existe uma solução simples para isso, não use.

**Comment by SrFortes** [comment]
Peço desculpa pelo nosso colega mal-educado! Nem todos brasileiros ou não sei oque esse energúmeno seja, são assim ! o Baileys está funcionando normalmente atualmente! 

English version:
I apologize for our rude colleague! Not all Brazilians or I don't know what this nerd is, are like that! Baileys is currently running normally!

**Comment by edupoli** [comment]
Lamentavel..., acredito que a unica intencao em fazer esse post seja para chamar a atencao ,  atitudes como esta que separa profissionais de criancas ,  seja profissional, evolua 

English:
Unfortunately..., I believe that the only intention of this post is have attention, attitudes  this that separate professionals from children, be professional, progress

**Comment by Iucasmaia** [comment]
PT: criança que pegou script de bot no youtube e não sabe como funciona uma lib ainda...
EN: child who got bot script on youtube and doesn't know how a lib works yet...
