### ISSUE TITLE
[BUG] Can't generate QR code after deleting session on device

### ISSUE THREAD

**Issue by DanOliveira18** [adiwajshing/Baileys#1753]
**Describe the bug**
Hey guys, I managed to make a successful connection after scanning the QR code, after that I deleted the connection on my device, and then the application can no longer generate the QRcode for me to reconnect again, here's a print of how the "connection.update" looks like: 
![image](https://user-images.githubusercontent.com/39445623/174191237-696642e4-6030-44b9-87f2-5c6b926f934f.png)

My code: 

```
const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')
const { version, isLatest } = await fetchLatestBaileysVersion()
//console.log(version);
console.log(`using WA v${version.join('.')}, isLatest: ${isLatest}`)
//console.log('chat id', global.client[chat_id]);

   if (global.client[chat_id]){
      console.log('ja existe chatid');
      try {
         global.client[chat_id] = {};
         global.client.splice(global.client.indexOf(chat_id), 1);   
         
      } catch (error) {
         global.client[chat_id] = {};
         global.client.splice(global.client.indexOf(chat_id), 1);   
      }
   }

   console.log('criando conexao');

   const sock = makeWASocket({
		version: [2, 2119, 6],
		logger,
		printQRInTerminal: true,
		auth: state,
		msgRetryCounterMap,
		getMessage: async key => {
			return {
				conversation: 'hello'
			}
		}
	});

   global.client[chat_id] = sock;

   console.log('conexao criada');


global.client[chat_id].ev.on('call', item => console.log('recv call event', item))
global.client[chat_id].ev.on('chats.set', item => console.log(`recv ${item.chats.length} chats (is latest: ${item.isLatest})`))
global.client[chat_id].ev.on('messages.set', item => console.log(`recv ${item.messages.length} messages (is latest: ${item.isLatest})`))
global.client[chat_id].ev.on('contacts.set', item => console.log(`recv ${item.contacts.length} contacts`))
global.client[chat_id].ev.on('messages.update', m => console.log(m))
global.client[chat_id].ev.on('message-receipt.update', m => console.log(m))
global.client[chat_id].ev.on('presence.update', m => console.log(m))
global.client[chat_id].ev.on('chats.update', m => console.log(m))
global.client[chat_id].ev.on('chats.delete', m => console.log(m))
global.client[chat_id].ev.on('contacts.upsert', m => console.log(m))]
global.client[chat_id].ev.on('creds.update', saveCreds)

   global.client[chat_id].ev.on('connection.update', async (update) => {
      
      console.log('atualizou a sessao', update)
		const { connection, lastDisconnect, qr } = update
		if(connection === 'close') {
			if((lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut) {
				console.log((lastDisconnect.error)?.output?.statusCode)
            //inicializaSessao()
			} else {
            global.client[chat_id] = {};
				console.log('Connection closed. You are logged out.')
            
			}
		}
      if(qr) {
         console.log('gerou QR', qr)
         const base64Qr = await QrCode.toDataURL(qr)
         exportQR(base64Qr, 'public/'+chat_id+'.png');
         console.log('exportou o QR')
      }
})
```

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? I put it with the code
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**

Before I noticed that when I tried to generate the QR code, it came with information from my user who had been connected, I noticed that this information was coming from Creds, I cleaned the "baileys_auth_info" folder but still I still can't make the connection. Is there any way I can clear the sessions? And try to create a new one?

**Comment by AkirahX** [comment]
Delete the folder that Baileys generates for each session.

In your project it should be named `baileys_auth_info`, based on the code below.

```javascript
const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')
```

**Comment by DanOliveira18** [comment]
> 

Hey, I try to delete this folder as i mentioned in the ticket, it recreated the folder but it is empty, but I keep getting the same error, it tries to create the connection, then it gives the error "connection closed" with code 405, and it does not generate the QR code, this print is my console after the folder is deleted 
![image](https://user-images.githubusercontent.com/39445623/174348198-971be639-eefa-4a83-9b8e-7b13bcaeb95f.png)
![image](https://user-images.githubusercontent.com/39445623/174348225-87f917dd-b7da-4a43-a21e-2bf805d9a664.png)

**Comment by DanOliveira18** [comment]
I managed to solve it using the latest version of whatsapp on makeWASocket 

```
const sock = makeWASocket({
		version,
		logger,
		printQRInTerminal: true,
		auth: state,
		msgRetryCounterMap,
		getMessage: async key => {
			return {
				conversation: 'hello'
			}
		}
	});
```
