### ISSUE TITLE
How do I get the first message of the day?

### ISSUE THREAD

**Issue by SrFortes** [adiwajshing/Baileys#1755]
I'm wanting to create a greeting, when I get the first message of the day!! not the first message but the first of the day, anyone who has already done it?

thanks !

**Comment by AkirahX** [comment]
You can check if the date of the new message is after the last one, you can easily check this by looking at the "timestamp" parameter you get in the message object, save in your database or something related.

**Comment by SrFortes** [comment]
> You can check if the date of the new message is after the last one, you can easily check this by looking at the "timestamp" parameter you get in the message object, save in your database or something related.


The solution I found was to check if the user has had a message before, and compare the dates with moment.
