### ISSUE TITLE
[BUG] Observation:  Closing stale open session for new outgoing prekey bundle

### ISSUE THREAD

**Issue by Alhar6i** [adiwajshing/Baileys#1757]
**Describe the bug**
It's about the most annoying message

```
Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry {
  _chains: {
    BWe2f4JfVS8L9NBdUY32cm9HJeuD9MGbc7i7hD9RyaNC: { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
...
...
}
```

Here I'm placing the content of the related JSON files:

1- sender-key-status@broadcast--96650496XXXX--0.json

`[
{
"senderKeyId":1582493416,
"senderChainKey":{
"iteration":0,
"seed":"aKGIq99Ga6QfwDz/sRUqeT7DVq4fj/DmI7fWJp2kwnk="
},
"senderSigningKey":{
"public":"BWTvjAfSVzQVzPROvnjHh4J2eTnfXQOiqiiNSVdFoJwN"
}
}
]`

2- session-96650496XXXX.0.json
```
{
"_sessions":{
"BTN0zXZ8BNv1dNK1nacGpBYqJgkaAMrHh/NtETo+9+JP":{
"registrationId":1057692640,
"currentRatchet":{
"ephemeralKeyPair":{
"pubKey":"Be0Ts65N96ABIYItmdm5im8oTO2/k5U9SvxKd9gCUmgz",
"privKey":"WCiEelXyG/xjMcmRigPQAfV601GuxEkxBVYkjwgEZVk="
},
"lastRemoteEphemeralKey":"BQBIzRnMQaSnlgE+mxDu1Nz6xqOk2yqjHgi9kpkGMdRc",
"previousCounter":0,
"rootKey":"KRVtBAL6xeBBs67zwclOgY2+f+LZVLvFhOEyv+3wbQM="
},
"indexInfo":{
"baseKey":"BTN0zXZ8BNv1dNK1nacGpBYqJgkaAMrHh/NtETo+9+JP",
"baseKeyType":2,
"closed":-1,
"used":1655577356218,
"created":1655577356218,
"remoteIdentityKey":"Beil6PAVIPwCPqacarRgBvgDZwyUtM76Mse5vRUtf2QH"
},
"_chains":{
"BQBIzRnMQaSnlgE+mxDu1Nz6xqOk2yqjHgi9kpkGMdRc":{
"chainKey":{
"counter":0,
"key":"W1wcM/xEi78eGc2WdZixqosOaoHorlLlzfIvSEakzTQ="
},
"chainType":2,
"messageKeys":{
}
},
"Be0Ts65N96ABIYItmdm5im8oTO2/k5U9SvxKd9gCUmgz":{
"chainKey":{
"counter":-1,
"key":"QyDvvv/tXRiqjXZYo5xGOg8T6EyCBLGDe+KPun4dIko="
},
"chainType":1,
"messageKeys":{
}
}
}
}
},
"version":"v1"
}
```

**To Reproduce**

**Just run the original example and wait till someone who is NOT in your contact posts a state.**

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? as same as the original example
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
This issue is highly associated with the user's status especially if they save your contact while you are NOT storing him on your contacts.

**Comment by Alhar6i** [comment]
Hi @adiwajshing 
I have a question, its answer might lead to solving the above issue.

Here is a name of a JSON file
session-96656585XXXX:40.0.json ( I encoded the last digits of the mobile with XXXX)

It has three parts "session-", " 96656585XXXX", and ":40.0"
My question is about the last part ":40.0",  do you expect to see this part in the file name?
Thank you

**Comment by adiwajshing** [comment]
So, this isn't actually a bug, this message is printed out when a new session is overwriting the previous one (as the message suggests), this is expected to happen when a message decryption fails and is retried

**Comment by azudindaem** [comment]
> Hi @adiwajshing I have a question, its answer might lead to solving the above issue.
> 
> Here is a name of a JSON file session-96656585XXXX:40.0.json ( I encoded the last digits of the mobile with XXXX)
> 
> It has three parts "session-", " 96656585XXXX", and ":40.0" My question is about the last part ":40.0", do you expect to see this part in the file name? What does the digit mean? I see sometimes digits between 0 and 60 Thank you

device id for multi device connection.. this number will increased every time we scan the qr code.

**Comment by Alhar6i** [comment]
Ok, that is very clear.

**Comment by Zarinia** [comment]
I have the same issue,
How to fix it?

**Comment by ezequielsg** [comment]
That's not a problem man.
Just ignore this log.
