### ISSUE TITLE
[BUG]Closing stale open session for new outgoing prekey bundle

### ISSUE THREAD

**Issue by jeanscircuits** [adiwajshing/Baileys#1764]
**Closing stale open session for new outgoing prekey bundle**
Closing session: SessionEntry {
  _chains: {
    'BX5c9zQcm5uNAnDYe3c6+jH7UniAZsFPr29JUaZKkv9P': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 2064834028,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 7e 5c f7 34 1c 9b 9b 8d 02 70 d8 7b 77 3a fa 31 fb 52 78 80 66 c1 4f af 6f 49 51 a6 4a 92 ff 4f>,
      privKey: <Buffer 90 c9 14 22 51 f5 07 7f 58 69 88 46 8b 74 48 17 dd 2b b2 b5 23 39 03 df f8 cc cd cc 7a 58 ac 4b>
    },
    lastRemoteEphemeralKey: <Buffer 05 50 58 03 f6 0c 5c f9 b2 78 ef cf a2 5c 50 57 ac 8f fa e8 a2 15 6a ea 0b 93 9d f8 61 a5 ff f8 65>,
    previousCounter: 0,
    rootKey: <Buffer 60 64 f3 0d 31 10 db 14 26 3f 62 ea 7a 85 00 8f f7 c6 84 1b 64 ed ef 8a 62 a4 d5 b9 42 32 37 fe>
  },
  indexInfo: {
    baseKey: <Buffer 05 4a d5 8b e2 3b 33 23 d1 32 27 19 bb c3 76 68 ce dc b5 94 50 0d 61 ec 58 44 f2 3f ac ff c6 e5 73>,
    baseKeyType: 1,
    closed: -1,
    used: 1655710606889,
    created: 1655710606889,
    remoteIdentityKey: <Buffer 05 5d 9b a6 65 78 62 13 5f 3f 0b f1 9c 8f 93 0d ca db e1 83 8e ec 08 8a 2a ae 76 af 04 78 40 e8 56>
  },
  pendingPreKey: {
    signedKeyId: 1,
    baseKey: <Buffer 05 4a d5 8b e2 3b 33 23 d1 32 27 19 bb c3 76 68 ce dc b5 94 50 0d 61 ec 58 44 f2 3f ac ff c6 e5 73>,
    baseKey: <Buffer 05 3c 1c 08 fc 04 be c5 ff 70 eb cc 82 23 dd 1d 8e 09 45 ab 5b 64 52 5e 44 96 aa b7 1f 2e 09 66 5e>,
    baseKeyType: 1,
    closed: -1,
    used: 1655712821107,
    created: 1655712821107,
    remoteIdentityKey: <Buffer 05 5d 9b a6 65 78 62 13 5f 3f 0b f1 9c 8f 93 0d ca db e1 83 8e ec 08 8a 2a ae 76 af 04 78 40 e8 56>
  },
  pendingPreKey: {
    signedKeyId: 1,
    baseKey: <Buffer 05 3c 1c 08 fc 04 be c5 ff 70 eb cc 82 23 dd 1d 8e 09 45 ab 5b 64 52 5e 44 96 aa b7 1f 2e 09 66 5e>,
    preKeyId: 15715029
  }
}

**Comment by mrhb6006** [comment]
exactly same issue

**Comment by ezequielsg** [comment]
So, this isn't actually a bug, this message is printed out when a new session is overwriting the previous one (as the message suggests), this is expected to happen when a message decryption fails and is retried.
Just ignore this log.

**Comment by SamPandey001** [comment]
same issue
but you can add   "@adiwajshing/baileys": "git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b",

Works fine for me

**Comment by phaticusthiccy** [comment]
Not a big point, also I didnt see any problems with this.
Does it present any problem for you?

**Comment by huangzhong0406** [comment]
I also get this issue

**Comment by SamPandey001** [comment]
> Not a big point, also I didnt see any problems with this. Does it present any problem for you?

Yeah,I got an error when i use baileys 4.2.0 it sends msgs like 
Waiting for things message,btw your primon proto is going to be great

**Comment by SamPandey001** [comment]
> ![168733368-770f2fac-c54e-4d5f-8af4-a3478d22fde8](https://github.com/assets/11567062/18465391-d285-4405-bdfb-3bf901e76a8b)

Yeah,same error

Use this  "@adiwajshing/baileys": "git+ssh://git@github.com/adiwajshing/baileys.git#a98484c38bc92055e3c660a86687ee0425bc5c5b

**Comment by phaticusthiccy** [comment]
> > Not a big point, also I didnt see any problems with this. Does it present any problem for you?
> 
> Yeah,I got an error when i use baileys 4.2.0 it sends msgs like Waiting for things message,btw your primon proto is going to be great

If you are using 2 different devices (WhatsApp Web PC & Mobile), it may show this because maybe the version is different. There is a topic that explains this week very well. Please check out issue #1631
This will help you.

**Comment by chauhanshivam079** [comment]
> Not a big point, also I didnt see any problems with this. Does it present any problem for you?

it slows down the process of sending message to whatsapp
