### ISSUE TITLE
Duplicate message ACK

### ISSUE THREAD

**Issue by barkerpedro** [adiwajshing/Baileys#177]
Hello, I'm creating a response system for whatsapp using the excellent Baileys library.
Messages sent and received I direct to a webhook where they are handled.
The messages received are all right.
The messages sent I get the "ACK: 2 = sent, 3 = delivered and 4 = viewed". The first message sent is ok, but from the second it will be duplicated, sending the JSON of all previous messages.
Could you help me with this, follow the code below:

```node
const request = require('request');
const { WAConnection } = require("@adiwajshing/baileys");
const client = new WAConnection();
const urlWebhook = 'http://www.mywebhook.com';

client.on('message-new', async m => {
  if (m.key.fromMe == true) {
    client.on('message-status-update', async mAck => {
      var objSent = { messages: [] };
      objSent.messages.push({
        type: "chat",
        body: m.message.conversation,
        id: m.key.fromMe + '_' + m.key.remoteJid + '_' + mAck.ids[0],
        time: m.messageTimestamp.low,
        chatId: mAck.from,
        from: mAck.from,
        to: mAck.to,
        status: mAck.type == 2 ? "sent" : mAck.type == 3 ? "delivered" : "viewed",
      });
      await request({ url: urlWebhook, method: "POST", json: objSent, });
      await client.chatRead(m.key.remoteJid);
      console.log('Message sent succesfully!');
    });
  };
});
```

**Comment by adiwajshing** [comment]
The problem is that you're adding an `on` event every time a new message is received -- which means the second time you receive the message, the listener has been added twice & you get duplicate ACK

**Comment by barkerpedro** [comment]
Thanks for the reply, excellent work on that library.
Could you give me an idea of how I can make this request, without the loop occurring?

**Comment by adiwajshing** [comment]
You'll have to register the status-update event outside the message-new event. That'll work with no problems.

**Comment by barkerpedro** [comment]
Thank you so much for your attention.
I resolved using:

```Node
conn.registerCallback(["action", "add:relay", "message"], json => {}
+
conn.registerCallback(["Msg", "cmd"], json => {}
```
