### ISSUE TITLE
Response-based button sequence!

### ISSUE THREAD

**Issue by SrFortes** [adiwajshing/Baileys#1770]
Hello Baileys lovers, do any of you know a plugin based on this or similar to the image below, the idea is to create a sequence of buttons based on the answer!

![Screenshot_21](https://user-images.githubusercontent.com/41592754/174835775-9bf3c2e6-be61-4f87-a2cc-abe2ea2383e9.png)

**Comment by Iucasmaia** [comment]
did u tried using an object with data about user and responses?
