### ISSUE TITLE
root@xiex.my.id:~/kontol# Error: Closing stale open session for new outgoing prekey bundle

### ISSUE THREAD

**Issue by Barqah-Xiex** [adiwajshing/Baileys#1777]
*Closing stale open session for new outgoing prekey bundle*
in error logs

im using:
Ubuntu 20.04
8 CPU
64GB RAM

how to fix it or remove it from console ? please tell me!

**Comment by BochilGaming** [comment]
hi, I made a pull request to silence that log. adiwajshing/libsignal-node#1

**Comment by frmdeveloper** [comment]
Indonesia ?

**Comment by frmdeveloper** [comment]
how to fix it or remove it from console ?
You do not need to look at the console
:v
