### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by 44310010032** [adiwajshing/Baileys#1778]
Error: Timed Out
    at /home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:174:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:169:19)\n' +
      '    at waitForMessage (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:99:61)\n' +
      '    at query (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:122:22)\n' +
      '    at getUSyncDevices (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:174:30)\n' +
      '    at /home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:285:53\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Object.transaction (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:82:21)\n' +
      '    at async relayMessage (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:261:9)\n' +
      '    at async Object.sendMessage (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:478:17)\n' +
      '    at async EventEmitter.<anonymous> (/home/runner/BOT/index.js:1350:25)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}
/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48:19)
    at sendNode (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:16)
    at Object.sendPresenceUpdate (/home/runner/BOT/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:350:19)
    at global.reply (/home/runner/BOT/index.js:283:30)
    at EventEmitter.<anonymous> (/home/runner/BOT/index.js:1363:21) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by Fonnte** [comment]
+1 i can't find a way to solve this too

**Comment by tmandinyenya** [comment]
Did you manage to fix this error?

**Comment by Fonnte** [comment]
sadly the only solution work for me is by restarting the node process at the moment. i am looking for the solution though
