### ISSUE TITLE
the audio doens't work 

### ISSUE THREAD

**Issue by matibm** [adiwajshing/Baileys#178]
### Receives the correct size audio, but cannot play it

`
 if (videoId) {
                const video = youtubedl('https://www.youtube.com/watch?v=' + videoId, ['--format=18'], { start: downloaded, cwd: __dirname })
                // output = 'myvideo.mp4'

                video.pipe(fs.createWriteStream(output, { flags: 'a' }))
                video.on('end', async function() {

                    ffmpeg(output).toFormat('mp3').saveToFile('myaudio.mp3').on('end', () => {
                        let buffer = fs.readFileSync('myaudio.mp3')
                        const options = { mimetype: Mimetype.ogg }
                        await conn.sendMessage(id, buffer, MessageType.audio, options)

                        if (fs.existsSync(output)) {
                            fs.unlinkSync(output)
                        }
                    }).on('error', (err) => {
                        console.log("error", err);
                    })
                })

            }`

**Comment by adiwajshing** [comment]
You’re sending an mp3 but the mime type you’ve specified is ogg. Change mimetype to audio/mp4, it should work

**Comment by tcortega** [comment]
> You’re sending an mp3 but the mime type you’ve specified is ogg. Change mimetype to audio/mp4, it should work
> […](#)
> On 2 Oct 2020, at 8:50 PM, matibm ***@***.***> wrote: ﻿ Receives the correct size audio, but cannot play it ` if (videoId) { const video = youtubedl('https://www.youtube.com/watch?v=' + videoId, ['--format=18'], { start: downloaded, cwd: __dirname }) // output = 'myvideo.mp4' video.pipe(fs.createWriteStream(output, { flags: 'a' })) video.on('end', async function() { ffmpeg(output).toFormat('mp3').saveToFile('myaudio.mp3').on('end', () => { let buffer = fs.readFileSync('myaudio.mp3') const options = { mimetype: Mimetype.ogg } await conn.sendMessage(id, buffer, MessageType.audio, options) if (fs.existsSync(output)) { fs.unlinkSync(output) } }).on('error', (err) => { console.log("error", err); }) }) }` — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

You might want to edit your examples then, on sending messages example you give this example:
```javascript
// send an audio file
const buffer = fs.readFileSync("Media/audio.mp3") // can send mp3, mp4, & ogg -- but for mp3 files the mimetype must be set to ogg
const options: MessageOptions = {mimetype: Mimetype.mp4Audio} // some metadata (can't have caption in audio)
conn.sendMessage(id, buffer, MessageType.audio, options)
```
and claim that mp3 files need the ogg mimetype, I think this is misleading a lot of people into trying wrong mimetypes.
