### ISSUE TITLE
Not responding in some groups [BUG]

### ISSUE THREAD

**Issue by BrunoSobrino** [adiwajshing/Baileys#1784]
An error that I have been able to identify in my Bot is that in groups with more than 256 participants it does not respond and throws a baileys error

**Comment by manojsitapara** [comment]
It is fixed in recent commit 

https://github.com/adiwajshing/Baileys/pull/1762

**Comment by BrunoSobrino** [comment]
> Se corrigió en la confirmación reciente.
> 
> #1762

Thank you :)
