### ISSUE TITLE
Problem with waChatUniqueKey

### ISSUE THREAD

**Issue by thiagocardosoba** [adiwajshing/Baileys#179]
Hi,
When it reached 392 chats, it started giving a key duplication error in KeyedDB. To resolve it I had to change the value in line 53 of Utils.js:
from: `exports.waChatUniqueKey = (c) => ((c.t * 100000) + (hashCode(c.jid) % 100000)) * -1; // -1 to sort descending`
to:    `exports.waChatUniqueKey = (c) => ((c.t * 1000000) + (hashCode(c.jid) % 1000000)) * -1; // -1 to sort descending`

**Comment by adiwajshing** [comment]
I've fixed this up in the latest commit, this should no longer happen. Do let me know if fixed.
