### ISSUE TITLE
[BUG] Paralysing

### ISSUE THREAD

**Issue by Descontinou** [adiwajshing/Baileys#1793]
It does not receive or send the response to the commands performed, it was not my error, because it was not only with me, I am presenting the details about the error for you to solve, otherwise I am glad about the commitment of everyone who always provides a solution.

**Comment by phaticusthiccy** [comment]
It is very wrong of you to open a issue like this. 
Please edit by reviewing the pre-made issue template. Do not ask for help without giving any information such as what is the error is, how it occurred, where it occurred. In addition to this, you have not provided any examples or evidence of this error.
Please review the template or I will ask you to close your issue request.

**Comment by Descontinou** [comment]
> É muito errado de você abrir um assunto como este. Por favor, edite revisando o modelo de emissão pré-feito. Não peça ajuda sem dar nenhuma informação como qual é o erro, como ocorreu, onde ocorreu. Além disso, você não forneceu nenhum exemplo ou evidência deste erro. Por favor, revise o modelo ou pedirei que feche sua solicitação de emissão.

There is no way to give examples or cite without having what to show, it's like me saying I have a pain in my leg, but in this case the leg is not mine, so I have no way of knowing the real "Consequence" that occurs in the code, before coming with comments with critical analysis, come with a more logical answer, not with an answer structure.

What occurs? :

- It stops working and does not receive anything or send....

How do I solve it?

- By opening another session and closing it, then it recovers the previous delay and stops again, and I have to return to version 4.1.0 to not occur this problem...
