### ISSUE TITLE
Time Out[BUG]

### ISSUE THREAD

**Issue by KiZakiXD** [adiwajshing/Baileys#1794]
Closed Session
Session error:Error: Bad MAC Error: Bad MAC

**Comment by phaticusthiccy** [comment]
Try re-scanning the QR Code. Or this error can also occur in groups that are messaged for the first time.

**Comment by KiZakiXD** [comment]
> Try re-scan QR Code. Or this error can also occur in groups that are sending messages for the first time.

more than 10 times a day

**Comment by phaticusthiccy** [comment]
Sorry, the information you provided is too little. How do you make socket connections? What type of auth method are you using? You should share such things. 
Moreover, the code screenshot or content can help us.

**Comment by PhillRoyle** [comment]
I see these often too. A re-scan fixes it, but automatic restart using the same keys does not (probably to be expected).
I get `messages.upsert` events like this:
`{
  "messages": [
    {
      "key": {
        "remoteJid": "xxx@s.whatsapp.net",
        "fromMe": true,
        "id": "26B0C05430F8Dxxxxx"
      },
      "messageTimestamp": 1654072509,
      "pushName": "xxxxxx",
      "status": 2,
      "messageStubType": 2,
      "messageStubParameters": [
        "Bad MAC"
      ]
    }
  ],
  "type": "notify"
}`
`    "eventData.messages.messageStubParameters": [
      "Bad MAC"
    ],
    "eventData.messages.status": [
      2
    ],`

**Comment by xXDeonoXx** [comment]
how did you fixed that ? i'm having the same issue.

**Comment by Anezz12** [comment]
ow did you fixed that ? i'm having the same issue.
