### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Piyoxz** [adiwajshing/Baileys#1798]
why when the bot is turned on, previous messages that have not been replied to by the bot, will quote messages outside the group or outside?
I have an order if the sender sends a halo message it will be answered halo mazzeh
![error](https://user-images.githubusercontent.com/102013178/175544227-b7d87670-9afa-4a8e-be8c-0261300ef5d3.png)

**Comment by phaticusthiccy** [comment]
I don't think this is a problem caused by the bailyes. 
Check your code. You don't need to open a issue here for your own fault!

**Comment by Piyoxz** [comment]
> 

okeey
