### ISSUE TITLE
[Bug] Issue with json results for specific functions

### ISSUE THREAD

**Issue by coolnickname** [adiwajshing/Baileys#18]
The functions client.getStatus and client.getProfilePicture don't work as shown in the readme example.

For getStatus the example is as shown:
`client.getStatus ("xyz@c.us") // leave empty to get your own
.then (json => console.log("status: " + json.status))`
This doesn't work, it should be:
`client.getStatus ("xyz@c.us") // leave empty to get your own
.then (json => console.log("status: " + json[0].status))`

Similarly for the getProfilePicture result: `json.eurl` -> `json[0].eurl`

And on a sidenote, the example to get the profile picture uses getStatus() instead of getProfilePicture(). :wink:

**Comment by adiwajshing** [comment]
Ah, issue in my readme. I'll fix it up

**Comment by adiwajshing** [comment]
Updated the readme in the latest commit.
