### ISSUE TITLE
Error clearing the chat window

### ISSUE THREAD

**Issue by barkerpedro** [adiwajshing/Baileys#180]
![image](https://user-images.githubusercontent.com/737919/94985064-64ed3f80-0529-11eb-9c26-27d8a2c89141.png)

**Comment by adiwajshing** [comment]
You got this error while clearing a message right?

**Comment by barkerpedro** [comment]
This error occurred about 5 times, when I went to clear the entire conversation, but then the error stopped.
And I didn't change any version of the library.

**Comment by adiwajshing** [comment]
Should be fixed in the latest commit, please check

**Comment by barkerpedro** [comment]
I really tested it and it's not showing the error anymore, thanks for your great work.
