### ISSUE TITLE
Remove reaction from message

### ISSUE THREAD

**Issue by JonazBR** [adiwajshing/Baileys#1802]
option to remove reaction sent by bot

**Comment by phaticusthiccy** [comment]
```ts
await Proto.sendMessage(jid: number, "")
```
Did you try using this? (I don't know if it's works or not. This should be the logical method.)
Try it if you want..

**Comment by fadiinho** [comment]
You need to send a reaction message without an emoji.
```js
const reactionMessage = {
    react: {
        text: "",
        key: message.key
    }
}

const sendMsg = await sock.sendMessage(id, reactionMessage)
```

**Comment by phaticusthiccy** [comment]
> You need to send a reaction message without an emoji.
> 
> ```js
> const reactionMessage = {
>     react: {
>         text: "", // empty string instead of an emoji
>         key: message.key
>     }
> }
> 
> const sendMsg = await sock.sendMessage(id, reactionMessage)
> ```

Yooo, I forgot to put the object 😂
