### ISSUE TITLE
RejectCall

### ISSUE THREAD

**Issue by ThisMe124** [adiwajshing/Baileys#1806]
How to Reject Call On MD?

**Comment by KiZakiXD** [comment]
f

**Comment by phaticusthiccy** [comment]
https://github.com/adiwajshing/Baileys#writing-custom-functionality
Check this out

**Comment by ThisMe124** [comment]
Ok thx sir

**Comment by ThisMe124** [comment]
> https://github.com/adiwajshing/Baileys#writing-custom-functionality Check this out

Btw Why 404 *https://github.com/adiwajshing/Baileys/blob/master/src/WABinary/readme.md*
