### ISSUE TITLE
link thumbnail preview?

### ISSUE THREAD

**Issue by wulandrima1** [adiwajshing/Baileys#181]
i send message link "youtube.com"
but preview thumbnail not show..
how to show preview thumbnail  send link "youtube.com"
thanks.

**Comment by adiwajshing** [comment]
Can you just try `https://youtube.com`?

**Comment by wulandrima1** [comment]
> Can you just try `https://youtube.com`?

yes sir, i try https://www.youtube.com/ or https://www.wikipedia.org/, 
but not show preview thumbnail link

**Comment by adiwajshing** [comment]
Okay, what version are you using & show some code please?

**Comment by wulandrima1** [comment]
> Okay, what version are you using & show some code please?

thanks sir for help me..
my problem is version ( lol ), after update version.. work link preview..
sorry for your time sir..
