### ISSUE TITLE
[BUG] Cannot destructure property 'user' of '(0 , exports.jidDecode)(...)' as it is undefined.

### ISSUE THREAD

**Issue by itsMySky** [adiwajshing/Baileys#1810]
Console.log : TypeError: Cannot destructure property 'user' of '(0 , exports.jidDecode)(...)' as it is undefined.
    at jidNormalizedUser (C:\Users\NatalieHose\Documents\GitHub\botme-md\node_modules\@adiwajshing\baileys\lib\WABinary\jid-utils.js:49:13)
    at Object.generateWAMessageFromContent (C:\Users\NatalieHose\Documents\GitHub\botme-md\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:350:68)
    at Object.conn.sendMessage (C:\Users\NatalieHose\Documents\GitHub\botme-md\handler.js:191:39)
    at async Object.run (C:\Users\NatalieHose\Documents\GitHub\botme-md\command\info\owner.js:8:3)
    at async handler (C:\Users\NatalieHose\Documents\GitHub\botme-md\handler.js:463:4)

**Comment by Shubhamrawat5** [comment]
same issue

**Comment by FatihArridho** [comment]
Kok aku gak error bang arsky?

**Comment by FatihArridho** [comment]
Kok aku gak error bang arsky?

**Comment by Shubhamrawat5** [comment]
use this
npm i git://github.com/adiwajshing/Baileys.git#a75d9118bdc7829a12dcb5f758dc5f92528a272d

**Comment by SetyaStore** [comment]
> Console.log : TypeError: Cannot destructure property 'user' of '(0 , exports.jidDecode)(...)' as it is undefined. at jidNormalizedUser (C:\Users\NatalieHose\Documents\GitHub\botme-md\node_modules@adiwajshing\baileys\lib\WABinary\jid-utils.js:49:13) at Object.generateWAMessageFromContent (C:\Users\NatalieHose\Documents\GitHub\botme-md\node_modules@adiwajshing\baileys\lib\Utils\messages.js:350:68) at Object.conn.sendMessage (C:\Users\NatalieHose\Documents\GitHub\botme-md\handler.js:191:39) at async Object.run (C:\Users\NatalieHose\Documents\GitHub\botme-md\command\info\owner.js:8:3) at async handler (C:\Users\NatalieHose\Documents\GitHub\botme-md\handler.js:463:4)

Gw Ga Eror

**Comment by itsMySky** [comment]
> > Console.log : TypeError: Cannot destructure property 'user' of '(0 , exports.jidDecode)(...)' as it is undefined. at jidNormalizedUser (C:\Users\NatalieHose\Documents\GitHub\botme-md\node_modules@adiwajshing\baileys\lib\WABinary\jid-utils.js:49:13) at Object.generateWAMessageFromContent (C:\Users\NatalieHose\Documents\GitHub\botme-md\node_modules@adiwajshing\baileys\lib\Utils\messages.js:350:68) at Object.conn.sendMessage (C:\Users\NatalieHose\Documents\GitHub\botme-md\handler.js:191:39) at async Object.run (C:\Users\NatalieHose\Documents\GitHub\botme-md\command\info\owner.js:8:3) at async handler (C:\Users\NatalieHose\Documents\GitHub\botme-md\handler.js:463:4)
> 
> Gw Ga Eror

I didn't ask that

**Comment by itsMySky** [comment]
> 

> use this npm i git://github.com/adiwajshing/Baileys.git#a75d9118bdc7829a12dcb5f758dc5f92528a272d

This doesn't work

**Comment by zennn08** [comment]
use baileys version from github, this has already been fixed at [here](https://github.com/adiwajshing/Baileys/commit/a75d9118bdc7829a12dcb5f758dc5f92528a272d)

**Comment by RumTester** [comment]
Same issue anyone got a solution? Ime using latest build getting this error intermittently for the last couple of days

**Comment by aislanspeedio** [comment]
> use baileys version from github, this has already been fixed at [here](https://github.com/adiwajshing/Baileys/commit/a75d9118bdc7829a12dcb5f758dc5f92528a272d)

This isn't merged to the stable version yet ???
