### ISSUE TITLE
[BUG] Xml Not well formed, when bot is used in group which has 257+ members

### ISSUE THREAD

**Issue by DGXeon** [adiwajshing/Baileys#1811]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by manojsitapara** [comment]
It's fixed in recently, please use guy version not npm

**Comment by SetyaStore** [comment]
npm i github:adiwajshing/baileys
