### ISSUE TITLE
 [HELP] Hide message in console

### ISSUE THREAD

**Issue by BrunoSobrino** [adiwajshing/Baileys#1812]
Hello, could you help me with this?

I would like this message not to be displayed in my terminal / console, is there a way?

I have as base this:

else if (errorcode === DisconnectReason.connectionClosed) { console.log("[ ⚠ ] Connection lost, reconnecting...."); }

Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry {
  _chains: {
    'BUnuTua2kzwmZ0h0dUPdikDzV___________': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 1309______,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 49 ee 4e e6 b6 93 3c 26 67 48 74 75 ________________>,
      privKey: <Buffer 70 ac 7c c7 6d 45 1d 6e 2c 1b db 4c 04 c4 ____________>
    },
    lastRemoteEphemeralKey: <Buffer 05 c4 13 d5 54 9b 2b c2 19 7c da d6 66 61 ______________>,
    previousCounter: 0,
    rootKey: <Buffer 40 6b 7a ac 34 cb 5b db 83 e4 83 93 6f 30 _________________>
  },
  indexInfo: {
    baseKey: <Buffer 05 b5 f1 d9 29 01 cb 00 9b 12 2b 41 93 e______________>,
    baseKeyType: 1,
    closed: -1,
    used: 16561____,
    created: 165615_______,
    remoteIdentityKey: <Buffer 05 9a 5b ef 0b 82 83 79 7f b2 38 20 36 d4 ______________>
  },
  pendingPreKey: {
    signedKeyId: 1,
    baseKey: <Buffer 05 b5 f1 d9 29 01 cb 00 ______________>,
    preKeyId: 20______
  }
}

**Comment by BrunoSobrino** [comment]
> im using this inside my code `const kontol_info = console.info console.info = function() { if(!require("util").format(...arguments).includes("Closing session: SessionEntry")){ return kontol_info(...arguments) } }`

Thank you! I already managed to solve the problem

**Comment by joaopaulosobral** [comment]
> Thank you! I already managed to solve the problem

How did you get?
