### ISSUE TITLE
How to identify group ?

### ISSUE THREAD

**Issue by SrFortes** [adiwajshing/Baileys#1816]
**Is there any way to identify a group from chats.update?**

**Comment by 4l3dx** [comment]
```typescript
{
    id: 'xxxxxxxxxxxxxxxxx@g.us', //g.us is a group                                                  
    conversationTimestamp: 1656197586,
    unreadCount: 1
}
```

**Comment by SrFortes** [comment]
> ```ts
> {
>     id: 'xxxxxxxxxxxxxxxxx@g.us', //g.us is a group                                                  
>     conversationTimestamp: 1656197586,
>     unreadCount: 1
> }
> ```

I had noticed this! Thanks!
