### ISSUE TITLE
[BUG] dont add new features bro pls fix the bugs first🥺, the error xml not well formed in v4.2, it leads to bot crash 🤧

### ISSUE THREAD

**Issue by DGXeon** [adiwajshing/Baileys#1817]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by manojsitapara** [comment]
Please use git version, it is fixed in recent commit.

**Comment by azudindaem** [comment]
#1762
