### ISSUE TITLE
Auto Read [BUG]

### ISSUE THREAD

**Issue by KiZakiXD** [adiwajshing/Baileys#1818]
For [ conn.sendReadReceipt ] only applies to groups, is there a new auto read for private chat too, because when chats accumulate it creates a delay in the system.

How about the new code auto read?

**Comment by zennn08** [comment]
try this
https://github.com/adiwajshing/Baileys#reading-messages

**Comment by KiZakiXD** [comment]
oh iya, efek jarang baca docs
aqul kunz >\\<
