### ISSUE TITLE
Button or template messages to a group

### ISSUE THREAD

**Issue by aarvee022** [adiwajshing/Baileys#1819]
How can we send button or template message to a group?
I can send button or template message to a number but unable to send it to group.

Please help.

**Comment by phaticusthiccy** [comment]
https://github.com/adiwajshing/Baileys#non-media-messages

**Comment by aarvee022** [comment]
> https://github.com/adiwajshing/Baileys#non-media-messages

I have already tried it. i a, able to send button or template message to a number but not to group

I want to sned button or template message in the groups.

**Comment by phaticusthiccy** [comment]
Can you share us the code?

**Comment by Alhar6i** [comment]
> How can we send button or template message to a group? I can send button or template message to a number but unable to send it to group.
> 
> Please help.

You need the group id, Just use it as same as the jid

**Comment by tinyCoder32** [comment]
Same issue, it works for "some" groups and doesn't work for others. I couldn't find a pattern.
