### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by ekoeryanto** [adiwajshing/Baileys#182]
Add ability to set custom logger like `pino`, `winston`, etc.

**Comment by adiwajshing** [comment]
Sounds like a good idea. However, I don't have the bandwidth to do that right now. Please feel free to submit a PR!

**Comment by adiwajshing** [comment]
Well, I've implemented this in the latest commit.

**Comment by ekoeryanto** [comment]
Yes, I see but the pretty logger is not necessary put in here. let's user decide to use it or not
