### ISSUE TITLE
Not getting presence-update

### ISSUE THREAD

**Issue by vinayakvasu** [adiwajshing/Baileys#1820]
i have used the example code to get the presence, but its not working

**Comment by phaticusthiccy** [comment]
This module will expire after about 10 seconds. If you want it to work continuously, you must use `setInterval()`
If that's not your goal, can you post the code for the process you want to do?

**Comment by hossinasaadi** [comment]
> > I didn't set setInterval() only want it once when I execute subscribe presense but I'm not getting anything in the console
> > […](#)
> > On Mon, 27 Jun, 2022, 2:56 am Thiccy, _**@**_.***> wrote: This module will expire after about 10 seconds. If you want it to work continuously, you must use setInterval() If that's not your goal, can you post the code for the process you want to do?
> 
> // the presence update is fetched and called here sock.ev.on('presence-update', json => console.log(json)) // request updates for a chat setInterval(() => { sock.presenceSubscribe("[XXXXX@s.whatsapp.net](mailto:XXXXX@s.whatsapp.net)") }, 10_000)
> 
> i tried this but not updating

you should set your presence online:
`                                        await sock.sendPresenceUpdate('available')
`

**Comment by mgulbazilyas** [comment]
> > I didn't set setInterval() only want it once when I execute subscribe presense but I'm not getting anything in the console
> > […](#)
> > On Mon, 27 Jun, 2022, 2:56 am Thiccy, _**@**_.***> wrote: This module will expire after about 10 seconds. If you want it to work continuously, you must use setInterval() If that's not your goal, can you post the code for the process you want to do?
> 
> // the presence update is fetched and called here sock.ev.on('presence-update', json => console.log(json)) // request updates for a chat setInterval(() => { sock.presenceSubscribe("[XXXXX@s.whatsapp.net](mailto:XXXXX@s.whatsapp.net)") }, 10_000)
> 
> i tried this but not updating

it's `sock.ev.on('presence.update')` not `sock.ev.on('presence-update')`
