### ISSUE TITLE
[BUG] Message not decrypted

### ISSUE THREAD

**Issue by rafaelaraujobsb** [adiwajshing/Baileys#1821]
Guys, I'm using version 4.0.1 and I noticed that for some phones the message is not decrypted when it arrives on whatsapp, has anyone gone through this?
![WhatsApp Image 2022-06-26 at 17 24 36](https://user-images.githubusercontent.com/22384199/175832553-51df1a1f-e3eb-4666-873a-896a3ff9cf42.jpeg)

**Comment by phaticusthiccy** [comment]
#1631
Moreover, if the chat is not contained in the store and it is the first time to message, it can send it. Try saving your chats to the store before the main function starts.
