### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VanzGantengz** [adiwajshing/Baileys#1823]
error after scan 
Error: Stream Errored (restart required)

**Comment by phaticusthiccy** [comment]
If you are using the single-file auth method or the multi-file auth method, If you see the auth file after scanning the QR, ignore this error. Also, can you share your code?

**Comment by VanzGantengz** [comment]
const main = async(auth, memStr, multi, md) => {
  let store = memStr ? baileys.makeInMemoryStore({stream: "store" }) : undefined
  let { version, isLatest } = await baileys.fetchLatestBaileysVersion()
    store?.readFromFile("auth_store.json")
        var fileAuth = baileys.useSingleFileAuthState(auth)
        var sock = baileys.default({
            auth: fileAuth.state,
            printQRInTerminal: true,
            version: version,
            logger: P({level: "silent"}),
            getMessage: async key => {
              return {
                conversation: "p"
              }
            }
        })
        store?.bind(sock.ev)
        setInterval(() => {
            store?.writeToFile("auth_store.json")
        }, 10_000)
        sock.ev.on("creds.update", fileAuth.saveState)
        sock.ev.on("connection.update", update => {
            if (multi) {
              sock.ev.emit("multi.sessions", update)
            }
            if (update.connection == "close") {
              var code = update.lastDisconnect?.error?.output?.statusCode;
                console.log(update.lastDisconnect?.error)
                if (code != 401) {
                  main(setting.auth, true, false, true)
                }
                if (update.connection == "open") {
                    console.log("Connect to WA Web")
                }
            }
        })
}

**Comment by phaticusthiccy** [comment]
Can you try this.  moreover, i have never seen an event called multi.session before.


```ts
const main = async(auth, md) => {

  var store = baileys.makeInMemoryStore({ 
    logger: P().child( // import P from "pino";
      {                // const P = require("pino")
        level: 'silent', 
        stream: 'store' 
      }
    ) 
  })
  store.writeToFile("./auth_store.json")
  store?.readFromFile("auth_store.json")
  let { version, isLatest } = await baileys.fetchLatestBaileysVersion()

  var fileAuth = baileys.useSingleFileAuthState(auth)

  var sock = baileys.default({
    auth: fileAuth.state,
    printQRInTerminal: true,
    version: version,
    logger: P({level: "silent"}),
    getMessage: async key => {
      return {
        conversation: "p"
      }
    }
  })

  store?.bind(sock.ev)
  setInterval(() => {
    store?.writeToFile("auth_store.json")
    store?.readFromFile("auth_store.json")
  }, 10_000)

  sock.ev.on("creds.update", fileAuth.saveState)
  sock.ev.on("connection.update", update => {

    if (update.connection == "close") {
      var reason = new Boom(lastDisconnect?.error)?.output.statusCode 
      // const { Boom } = require("@hapi/boom");
      console.log(reason) 
      if (reason === DisconnectReason.loggedOut) {
        console.log("Logged Out");
        sock.logout();
      } else {
        if (update.connection == "open") {
          console.log("Connect to WA Web")
        } else {
          main(fileAuth.state, true)
        }
      }
    }
  })
  return sock;
}
```

**Comment by phaticusthiccy** [comment]
The useSingleFileAuthState method is very unstable and unstable. Please use ` await useMultiFileAuthState()` method instead of `useSingleFileAuthState()`.

**Comment by phaticusthiccy** [comment]
[Example](https://github.com/adiwajshing/Baileys#saving--restoring-sessions)
[Code](https://github.com/adiwajshing/Baileys/blob/f87f89329b467dca6472b5f24c505918bfcbdd01/src/Utils/use-multi-file-auth-state.ts)

**Comment by ibnumardini** [comment]
`useMultiFileAuthState()` is new method?

**Comment by criptopreto** [comment]
Same error:
Error: Stream Errored (restart required)
I'm using useMultiFileAuthState.

**Comment by criptopreto** [comment]
I found a solution.

**Comment by criptopreto** [comment]
In the event of disconnection `onDisconnect` I added a conditional `if` to detect the 515 status code, if it finds it then it must call a reconnect function, which basically what it does is call the connect function again with the same initial data and same qr code, then this time it does connect.

conditional in :
```
if (statusCode === 515) {
      return re_connect();
}
```

**Comment by morganzysman** [comment]
Hi,

Same here

**Comment by joaocib** [comment]
I was with the same error and resolved it by making the connection event asynchronous

**Comment by joaocib** [comment]
I was with the same error and resolved it by making the connection event asynchronous
`sock.ev.on("connection.update", **async** (update) => {`
