### ISSUE TITLE
Send pdf as bytes array

### ISSUE THREAD

**Issue by Dguruz21** [adiwajshing/Baileys#1825]
Hello everyone, I have pdf file in a bytes array, How could i send this file? Thanks in advance

**Comment by phaticusthiccy** [comment]
```mjs
var string_data = new Buffer.from(
  bytes_array
).toString()

(async () => {
  await sock.sendMessage(
    jid, 
    document: Buffer.from(string_data), { 
      mimetype: "application/pdf"
    }
  )
})

**Comment by Dguruz21** [comment]
For my example this works.

const sendFileAsBytesPdf = async (session, receiver, arraybytes, name) => {
    try {
        var string_data = Buffer.from(arraybytes,'base64')

        const payload = {
            document: string_data,
            mimetype: 'application/pdf',
            fileName: `${name}.pdf`,
        }
        var response = await session.sendMessage(receiver, payload)
        return response
    } catch {
        return Promise.reject(null) 
    }
}

**Comment by Dguruz21** [comment]
For my example, this works.
`const sendFileAsBytesPdf = async (session, receiver, arraybytes, name) => {
    try {
        await delay(1000)

        var string_data = Buffer.from(arraybytes,'base64')

        const payload = {
            document: string_data,
            mimetype: 'application/pdf',
            fileName: `${name}.pdf`,
        }
        var response = await session.sendMessage(receiver, payload)
        return response
    } catch {
        return Promise.reject(null) // eslint-disable-line prefer-promise-reject-errors
    }
}`

**Comment by SheIITear** [comment]
> ```js
> var string_data = new Buffer.from(
>   bytes_array
> ).toString()
> 
> (async () => {
>   await sock.sendMessage(
>     jid, 
>     document: Buffer.from(string_data), { 
>       mimetype: "application/pdf"
>     }
>   )
> })
> ```

Why's it necessary to convert to buffer 2x times and then wrap send into anonymous function?

**Comment by phaticusthiccy** [comment]
I don't know if it is sent as a bit array, so I converted it to ArrayBuffer as an alternative. Also function is just a roadmap for that that needed to be asynchronous.

**Comment by SheIITear** [comment]
> yeah it's possible, as i said. Mine is just an example, can be reproduced.

Yeah, I just think example code should be as simple as possible 👍🏼
