### ISSUE TITLE
[BUG] Invalid PreKey ID when sending new message

### ISSUE THREAD

**Issue by Xrazik1** [adiwajshing/Baileys#1827]
**Describe the bug**

If you send a message to a user you get "messages:upsert" event and a body which includes following: 
`{\"messages\":[{\"key\":{\"remoteJid\":\"phone@s.whatsapp.net\",\"fromMe\":true,\"id\":\"29463610\"},\"messageTimestamp\":1656343087,\"pushName\":\"Name\",\"status\":2,\"messageStubType\":2,\"messageStubParameters\":[\"Invalid PreKey ID\"]}],\"type\":\"notify\"}"}`
**To Reproduce**
1. Create connection and login via QR
2. Send a message to a user
3. Catch messages:upsert event

**Expected behavior**
I expect that upsert event will return an object with message body. On the other hand if you receive new message from a contact you get correct body without "Invalid PreKey ID" error.

**Comment by zellsito** [comment]
Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
Closing open session in favor of incoming prekey bundle
Closing session: SessionEntry {
 _chains: {

**Comment by ReiDx** [comment]
Closing open session in favor of incoming prekey bundle Closing session: SessionEntry
{ { _chains: { 'BfNrdrzx12Z73SQHJvLKkk7iD2eVahXhW8JWWKIsv/RO': { chainKey: [Object], chainType: 2, messageKeys: {} }, 'BQPoWFqteGpDVH8A1tJ/w/XiArGWFUdN/rLMGT0vb2Jo': { chainKey: [Object], chainType: 1, messageKeys: {} } }, registrationId: 818701705, currentRatchet: { ephemeralKeyPair: { pubKey: <Buffer 05 03 e8 58 5a ad 78 6a 43 54 7f 00 d6 d2 7f c3 f5 e2 02 b1 96 15 47 4d fe b2 cc 19 3d 2f 6f 62 68>, privKey: <Buffer f0 0c d3 48 74 a7 5d 61 57 ba 02 fb 83 7b b2 ac bb c4 a5 33 2e be ad 45 d3 17 50 b5 9b 20 93 5f> }, lastRemoteEphemeralKey: <Buffer 05 f3 6b 76 bc f1 d7 66 7b dd 24 07 26 f2 ca 92 4e e2 0f 67 95 6a 15 e1 5b c2 56 58 a2 2c bf f4 4e>, previousCounter: 0, rootKey: <Buffer 98 2e 40 af a6 25 5e a5 fc 3b cf 9f a3 87 90 43 bc f2 2f 15 27 f3 00 c3 9a 34 cc 8b 6e 78 19 1d> }, indexInfo: { baseKey: <Buffer 05 13 d5 b6 56 ec 49 64 11 70 aa 87 bb a8 c2 a9 f8 af b3 f4 a0 d0 d5 46 67 90 5b 64 e1 a6 35 17 33>, baseKeyType: 2, closed: -1, used: 1656798513643, created: 1656798513643, remoteIdentityKey: <Buffer 05 13 f5 8a 60 a2 3f 4a a5 c0 92 a0 16 24 9d d6 c5 77 ee 5a b3 c2 d9 47 c7 c7 e7 9a fb 1c a1 b5 69> } }

**Comment by makanSukros** [comment]
Bug still exist in the new latest edge version

**Comment by matheusf31** [comment]
Same here...
![image](https://user-images.githubusercontent.com/45342938/215855926-63334ee1-775a-407e-8e16-c2db6c9e622d.png)
