### ISSUE TITLE
Get Received/Read timestamp

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1828]
It's clear for me i can listen the 'messages.update' to know when a message is delivered or read by remote user.

But, if i lost connection, or Baileys is offline, i can retrieve received/read timestamp of certain message?

Thanks.

Like this..
![Exemplo](https://user-images.githubusercontent.com/4416953/176003314-12101851-fe5b-44be-8272-40a203a34ed1.png)

**Comment by fadiinho** [comment]
Yep, you can.

Asfaik you can get the message from store (if you're using the Baileys store) and get the timestamp there.
You have two "types" the group type and the private (chat) type.
The group type will be an array of `UserReceipt` (one object for each member), containing some info including `readTimestamp`:
```js
const message = await store.loadMessage(remoteJid, messageId, socket);
console.log(message.userReceipt);
// It will return:
[
  UserReceipt {
    pendingDeviceJid: [],
    deliveredDeviceJid: [],
    userJid: 'x@s.whatsapp.net',
    receiptTimestamp: Long { low: '<timestamp here>', high: 0, unsigned: false },
    readTimestamp: Long { low: '<timestamp here>', high: 0, unsigned: false }
  }
]
```
And the private will contain a property `status` that is a number.
If I remember well the numbers mean:
```
2: sent
3: received
4: read
```
I don't know if you can get the timestamp in a private chat.

**Comment by fadiinho** [comment]
Just realized that the store has the method `fetchMessageReceipts`.
So you can do:
```js
const receipts = await store.fetchMessageReceipts(messageId, socket);
```

**Comment by drauber** [comment]
Thanks for your response!
All you wrote is correct, but.. a private message haven't UserReceipt properties, and i can't find where is the timestamp if the message is delivered or read. Only can show the status of the message..
