### ISSUE TITLE
[BUG] UnhandledPromiseRejection [ERROR] The promise rejected with the reason "1006"

### ISSUE THREAD

**Issue by ghost** [adiwajshing/Baileys#1829]
sometimes it happens
I couldn't find the error, and I don't believe it's my code (because I've seen people with the same error)

Please help me

node: internal/process/promises: 288
triggerUncaughException(err, true /* fromPromise */);
[UnhandledPromiseRejection:** This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006"]

code: 'ERR_UNHANDLED_REJECTION'

This is someone else's log, similar to mine:

{"level":30,"time":1648645149673,"pid":18300,"hostname":"DESKTOP-HADL7CA","class":"baileys","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated"},"headers":{}}},"msg":"connection closed"} connection closed due to Error: Connection Terminated at WebSocket. (C:\Users\user\Workspace\whatsapp\node_modules@adiwajshing\baileys\lib\Socket\socket.js:358:30) at WebSocket.emit (node:events:532:35) at WebSocket.emitClose (C:\Users\user\Workspace\backend-services-whatsapp\node_modules\ws\lib\websocket.js:257:10) at TLSSocket.socketOnClose (C:\Users\user\Workspace\backend-services-whatsapp\node_modules\ws\lib\websocket.js:1217:15) at TLSSocket.emit (node:events:532:35) at node:net:687:12 at TCP.done (node:_tls_wrap:580:7) { data: null, isBoom: true, isServer: false, output: { statusCode: 428, payload: { statusCode: 428, error: 'Precondition Required', message: 'Connection Terminated' }, headers: {} } } , reconnecting true [ERROR] 19:59:09 UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006"

**Comment by phaticusthiccy** [comment]
Check the [example.ts](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts)

**Comment by maggionigab** [comment]
> Check the [example.ts](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts)

...I'm also not using Typescript

sock.ev.on('connection.update', (update) => {
    var _a, _b;
    const { connection, lastDisconnect } = update;
    if (connection === 'close') {
        // reconnect if not logged out
        if (((_b = (_a = lastDisconnect.error) === null || _a === void 0 ? void 0 : _a.output) === null || _b === void 0 ? void 0 : _b.statusCode) !== DisconnectReason.loggedOut) {
            startSock();
        }
        else {
            console.log('Connection closed. You are logged out.');
        }
    }
    console.log('connection update', update);
});

(typescript to javascript

**Comment by BochilGaming** [comment]
#1152
