### ISSUE TITLE
Faulty functions

### ISSUE THREAD

**Issue by barkerpedro** [adiwajshing/Baileys#183]
I'm calling the `conn.chatRead()` and `conn.chats.get()`, but they are giving an error in the return.

```Node
await conn.chatRead(m.key.remoteJid);

Error: chat 'xxxxxxx@s.whatsapp.net' not found //(xxxxxxx = phone number)
```
and
```Node
let senderName = await conn.chats.get(m.key.remoteJid).name;
console.log(senderName);

TypeError: Cannot read property 'name' of undefined
```

**Comment by adiwajshing** [comment]
Are you waiting for chats when connecting?

**Comment by barkerpedro** [comment]
I'm sorry for taking your time, but I didn't know I needed `waitForChats = true`.
Which one do I use is correct?

`conn.waitForChats = true;`
or
`conn.connectOptions.waitForChats = true;`

**Comment by adiwajshing** [comment]
`conn.connectOptions.waitForChats = true`, this one is correct & enabled by default

Without waiting for chats, there is no way to reliably access them in a future state.

**Comment by barkerpedro** [comment]
Thanks again for the help and congratulations on the excellent work with the library.
