### ISSUE TITLE
[BUG] Error: Timed Out

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#1836]
(node:460369) UnhandledPromiseRejectionWarning: Error: Timed Out
    at /home/botdev/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:174:32
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/home/botdev/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:169:19)\n' +
      '    at waitForMessage (/home/botdev/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:101:61)\n' +
      '    at query (/home/botdev/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:124:22)\n' +
      '    at /home/botdev/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:285:38\n' +
      '    at runNextTicks (node:internal/process/task_queues:61:5)\n' +
      '    at processTimers (node:internal/timers:497:9)\n' +
      '    at async Object.transaction (/home/botdev/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:86:21)\n' +
      '    at async resyncAppState (/home/botdev/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:251:9)\n' +
      '    at async resyncMainAppState (/home/botdev/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:441:9)\n' +
      '    at async Timeout.<anonymous> (/home/botdev/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:31:13)'

**Comment by makanSukros** [comment]
I very often experience Request Time-out errors like this, even though the internet connection is very stable, has anyone experienced the same thing as this?

**Comment by nastarrr** [comment]
> I very often experience Request Time-out errors like this, even though the internet connection is very stable, has anyone experienced the same thing as this?

I also experienced it, but haven't found a solution until now

**Comment by makanSukros** [comment]
Error appears from: const { onMutation } = newAppStateChunkHandler(recvChats);

**Comment by makanSukros** [comment]
Until now this error always appears every 10 minutes: 

UnhandledPromiseRejectionWarning: Error: Timed Out

**Comment by neves-gabriel** [comment]
Still relevant

**Comment by morganzysman** [comment]
I have the same issue

**Comment by 13banda** [comment]
+1

**Comment by diazzaid** [comment]
whatsapp server at certain times there is a restart session and it is done every day.
this is a sample log on the bailyes library and whatsapp-web.js
![image](https://user-images.githubusercontent.com/25816482/183560078-4b7055a9-47df-4a34-ad3e-e0f18a1193ad.png)
if you want to use the baileys library, look at this repo, there is already an auto restart when the whatsapp session is disconnected
https://github.com/ade566/wa-baileys
