### ISSUE TITLE
Get all groups that I am in

### ISSUE THREAD

**Issue by muhammad-bassiouni** [adiwajshing/Baileys#1846]
How can I get all groups with their details

**Comment by viniciusgdr** [comment]
Yes. socket.groupFetchAllParticipating()

Example to get all ids: 
socket.groupFetchAllParticipating().then((groups) => {
        let ids: groupMetadata[] = []
        for (let group in groups) {
            if (isJidGroup(groups[group].id)) ids.push(groups[group])
        }
       console.log(ids)
})

**Comment by phaticusthiccy** [comment]
> Yes. socket.groupFetchAllParticipating()
> 
> Example to get all ids: socket.groupFetchAllParticipating().then((groups) => { let ids: groupMetadata[] = [] for (let group in groups) { if (isJidGroup(groups[group].id)) ids.push(groups[group]) } console.log(ids) })

Correction;

```mjs
import {
  default: makeWASocket,
  isJidGroup
} from "@adiwajshing/baileys";

const socket = makeWASocket({ })

(function* () => {

  var groupData = socket.groupFetchAllParticipating()
  var groupIDs = []

  groupData.groups.map((Element) => {
    isJidGroup(Element.id) === true ? groupIDs.push(Element.id) : console.log(Element.id + " is not a group\n")
  })

  console.log("Groups :: \n")
  return console.log(groupIDs)
})
```

**Comment by Rippanteq7** [comment]
Just get all groups id
```js
Object.keys(await sock.groupFetchAllParticipating())
```

Get all groups with detail
```js
Object.values(await sock.groupFetchAllParticipating())
```

**Comment by muhammad-bassiouni** [comment]
thanks for the reply, I have tried the code above and it didn't work and just gave me this error " UnhandledPromiseRejectionWarning: Error: Connection Closed"
