### ISSUE TITLE
[BUG] failed to commit x mutations, tries left=

### ISSUE THREAD

**Issue by Krash0** [adiwajshing/Baileys#1847]
**Describe the bug**
![image](https://user-images.githubusercontent.com/23028535/176720641-a732acd0-23da-4deb-aab4-94a0d3e8c8fb.png)

im using ubuntu 18.04 lts

"failed to commit x mutations, tries left=x", every time,....

when a send a message the message is seended but the function response long time, +/- 30 seconds, because you need to wait for the counter to zero and the attempts to reach 0, I just deactivated it and put it in case it fails to give up, but this doesn't seem like the correct function, can anyone tell me what the code is trying to save and what it's for

code I'm using to """fix""" the problem
file: Utils/auth-utils.js

````

                        logger.trace('committing transaction');
                        // retry mechanism to ensure we've some recovery
                        // in case a transaction fails in the first attempt
                        let tries = 0;
                        //while (tries) {
                        //   tries -= 1;
                            try {
                                await state.set(mutations);
                                logger.trace({ dbQueriesInTransaction }, 'committed transaction');
                                ///break;
                            }
                            catch (error) {
                                logger.warn(`failed to commit ${Object.keys(mutations).length} mutations, tries left=${tries}`);
                               // await (0, generics_1.delay)(delayBetweenTriesMs);
                            }
                        //}

````

**Comment by Luxemburgo** [comment]
🤚 Same exact problem here! Starting in 4.2.0 version. Previous version doesn't have this problem

**Comment by ewwink** [comment]
same problem while sending message to group

**Comment by mynameisfiber** [comment]
This was happening to me while using a custom `SignalKeyStore` for authentication which was raising an exception on `SignalKeyStore.set`. Once I resolved the issue with my custom key store I no longer got the `failed to commit ${Object.keys(mutations).length} mutations, tries left=${tries}` messages.

**Comment by kevineduardo** [comment]
I'm having this issue.
