### ISSUE TITLE
how to get name

### ISSUE THREAD

**Issue by Bad-Boy-Codes** [adiwajshing/Baileys#1848]
question:
how can I get user names (account name the default one when we set)
in latest version

**Comment by Bad-Boy-Codes** [comment]
> sock.user To get the details of scanned whatsapp account

I mean other user's details
for eg: I have someone's id: xxxx@s.whatsapp.net
how can I get it's information

**Comment by ibnusyawall** [comment]
> > sock.user To get the details of scanned whatsapp account
> 
> I mean other user's details for eg: I have someone's id: [xxxx@s.whatsapp.net](mailto:xxxx@s.whatsapp.net) how can I get it's information

try this:

```ts
store.contacts[ids]?.name || store.contacts[ids].notify
```

**Comment by Bad-Boy-Codes** [comment]
> > > sock.user To get the details of scanned whatsapp account
> > 
> > 
> > I mean other user's details for eg: I have someone's id: [xxxx@s.whatsapp.net](mailto:xxxx@s.whatsapp.net) how can I get it's information
> 
> try this:
> 
> ```ts
> store.contacts[ids]?.name || store.contacts[ids].notify
> ```

no I didn't mean the name by which the user saved that number.

isn't there some way to get the global name that shows WhatsApp when the number isn't saved
![IMG_20220704_211801](https://user-images.githubusercontent.com/58816669/177187244-9d7b6bab-4e6c-4c0a-8732-86b36fa1a6c8.jpg)
look atat this image-

**Comment by enoksaju** [comment]
up
