### ISSUE TITLE
Notification (QR Callback) after create session

### ISSUE THREAD

**Issue by asyad85** [adiwajshing/Baileys#1849]
hi, how to send a notification (QR Callback) to the client using makeWASocket if the qr code scan is successful? tks

**Comment by salman0ansari** [comment]
create a bot on successful qr scan send a msg to client number

**Comment by ibnusyawall** [comment]
> hi, how to send a notification (QR Callback) to the client using makeWASocket if the qr code scan is successful? tks

```ts
ws.on('CB:iq,,pair-success', () => {
    console.log('success paired qr')
})
```
