### ISSUE TITLE
How can I send a message to broadcast list or bulk messages preventing ban from whatsapp?

### ISSUE THREAD

**Issue by iamjcharly** [adiwajshing/Baileys#185]
I'm trying to send a message to 2000 people for day, is this possible? Also whatsapp banned me a number after 1200 messages with a delay of 7500ms and other numbers after just 30 messages

**Comment by barkerpedro** [comment]
Spamming by whatsapp is tricky, as it can ban your number with 1000 messages, as well as it can ban with 10 messages.
The correct thing would be to wait for a number to contact your whatsapp, then send a message to this number.

**Comment by iamjcharly** [comment]
Oh I understand, is there a way to forward a message?

**Comment by adiwajshing** [comment]
Yes, it's also mentioned in the readme. Please refer to [this](https://github.com/adiwajshing/Baileys#forwarding-messages)

**Comment by iamjcharly** [comment]
Thanks I can forward the message
