### ISSUE TITLE
Button and Template Message Sending to Sender And Reciver Both

### ISSUE THREAD

**Issue by MyNavneet** [adiwajshing/Baileys#1850]
When I am sending a Template or Button Message Then 1 Message Send To the Receiver and the Same Message is received by Sender, Menace 1 Message Send to 2 Time if I am sending 100 Button messages then the same 100 messages are received on my sender's WhatsApp number.

Please provide me Solution For That Issue because Unsessery double message sending.

**Comment by maulalwi** [comment]
Same bug in template buttons

**Comment by MyNavneet** [comment]
Can anyone can Help me on This issue.

**Comment by rajeshkumarsir** [comment]
no solution found yet

**Comment by maulalwi** [comment]
Hm...

**Comment by MuhammadKarzoun** [comment]
have the same issue :(

**Comment by neocomun** [comment]
have the same issue. Is there no solution?

**Comment by Ajay-o-s** [comment]
🙂 same issue for me

**Comment by Ajay-o-s** [comment]
@adiwajshing

**Comment by xAuxin9** [comment]
Same issue!

**Comment by mariocarvalhope25** [comment]
have the same issue :(

**Comment by muazzissnajmi** [comment]
same issue

**Comment by PurpShell** [comment]
I don't think there is a solution since that is the way the template is processed on the phone

**Comment by MyNavneet** [comment]
Any Update On This Issue ..

[data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs=3D]

**Comment by aarvee022** [comment]
any solution?

**Comment by xAuxin9** [comment]
> any solution?

No!

**Comment by ANazih** [comment]
same issue
