### ISSUE TITLE
[BUG] ssh://git@github.com/adiwajshing/libsignal-node Permission denied (publickey)

### ISSUE THREAD

**Issue by zerosdev** [adiwajshing/Baileys#1853]
**Describe the bug**
I can't npm install

npm WARN config init.module Use `--init-module` instead.
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/adiwajshing/libsignal-node.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists

**Comment by mohamad-supangat** [comment]
set the ssh key in our github account if you use ssh 

https://docs.github.com/en/enterprise-server@3.1/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

or you can use https protocol 
https://github.com/adiwajshing/Baileys/blob/a2054d8efab0b659ad6bcecbe4e1c0cd2aeda3a4/package.json#L41

**Comment by phaticusthiccy** [comment]
Alternative;

```json
{
  "libsignal": "github:adiwajshing/libsignal-node"
}

**Comment by zerosdev** [comment]
> set the ssh key in our github account if you use ssh
> 
> https://docs.github.com/en/enterprise-server@3.1/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
> 
> or you can use https protocol
> 
> https://github.com/adiwajshing/Baileys/blob/a2054d8efab0b659ad6bcecbe4e1c0cd2aeda3a4/package.json#L41

But i don't set it manually, here is my project's package.json https://pastebin.com/TWVNJNJB
