### ISSUE TITLE
how to convert new example.ts code for node js

### ISSUE THREAD

**Issue by jasmanX** [adiwajshing/Baileys#1855]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

const { AnyMessageContent, delay, DisconnectReason, fetchLatestBaileysVersion, makeInMemoryStore, MessageRetryMap, useMultiFileAuthState } = require('./src');
const makeWASocket = require('./src');
const MAIN_LOGGER = require('./src/Utils/logger')
how to run in node js
👇

import { Boom } from '@hapi/boom'
import makeWASocket, { AnyMessageContent, delay, DisconnectReason, fetchLatestBaileysVersion, makeInMemoryStore, MessageRetryMap, useMultiFileAuthState } from '../src'
import MAIN_LOGGER from '../src/Utils/logger'

const logger = MAIN_LOGGER.child({ })
logger.level = 'trace'

const useStore = !process.argv.includes('--no-store')
const doReplies = !process.argv.includes('--no-reply')

// external map to store retry counts of messages when decryption/encryption fails
// keep this out of the socket itself, so as to prevent a message decryption/encryption loop across socket restarts
const msgRetryCounterMap: MessageRetryMap = { }

// the store maintains the data of the WA connection in memory
// can be written out to a file & read from it
const store = useStore ? makeInMemoryStore({ logger }) : undefined
store?.readFromFile('./baileys_store_multi.json')
// save every 10s
setInterval(() => {
	store?.writeToFile('./baileys_store_multi.json')
}, 10_000)

**Comment by jasmanX** [comment]
thanks for your kind response please little more :-

const logger = MAIN_LOGGER.child({ })
const msgRetryCounterMap: MessageRetryMap = { }
// the store maintains the data of the WA connection in memory
// can be written out to a file & read from it
const store = useStore ? makeInMemoryStore({ logger }) : undefined

**Comment by jasmanX** [comment]
> ```
> const { default: makeWASocket, useSingleFileAuthState, DisconnectReason, fetchLatestBaileysVersion, generateForwardMessageContent, prepareWAMessageMedia, generateWAMessageFromContent, generateMessageID, downloadContentFromMessage, makeInMemoryStore, jidDecode, proto } = require("@adiwajshing/baileys")
> const pino = require('pino')
> const { Boom } = require('@hapi/boom')
> ```



> ```
> const { default: makeWASocket, useSingleFileAuthState, DisconnectReason, fetchLatestBaileysVersion, generateForwardMessageContent, prepareWAMessageMedia, generateWAMessageFromContent, generateMessageID, downloadContentFromMessage, makeInMemoryStore, jidDecode, proto } = require("@adiwajshing/baileys")
> const pino = require('pino')
> const { Boom } = require('@hapi/boom')
> ```
for node js :-
const logger = MAIN_LOGGER.child({ })
logger.level = 'trace'

const msgRetryCounterMap: MessageRetryMap = { }
const store = useStore ? makeInMemoryStore({ logger }) : undefined
store?.readFromFile('./baileys_store_multi.json')

**Comment by jasmanX** [comment]
> ```
> const { default: makeWASocket, useSingleFileAuthState, DisconnectReason, fetchLatestBaileysVersion, generateForwardMessageContent, prepareWAMessageMedia, generateWAMessageFromContent, generateMessageID, downloadContentFromMessage, makeInMemoryStore, jidDecode, proto } = require("@adiwajshing/baileys")
> const pino = require('pino')
> const { Boom } = require('@hapi/boom')
> 
> const { state, saveState } = useSingleFileAuthState(SESSION_FILE_PATH)
> store.readFromFile(STORE_FILE_PATH)
> setInterval(() => {
>         store.writeToFile(STORE_FILE_PATH)
>     }, 10_000)
> 
>   const client = makeWASocket({
>     logger: pino({ level: 'silent' }),
>     printQRInTerminal: false,
>     browser: ['Ubuntu','Chrome','1.0.0'],
>     auth: state
>   });
> store.bind(client.ev);
> client.ev.on('creds.update', saveState)
> ```

function connectToWhatsApp (instancesid){
.... auth
.... test message
}
OK... connected with WA and sent a successfull welcome text message :)

Next step how to get session and send text via post method. Please guide Thanks a lot :)

**Comment by ndalu-id** [comment]
check my code

https://github.com/ndalu-id/baileys-api
