### ISSUE TITLE
Set my status as offline for all contacts

### ISSUE THREAD

**Issue by muhammad-bassiouni** [adiwajshing/Baileys#1857]
I want to set my status as "offline" for all contacts, so whenever any contact checks the chat it appears that I am offline. I know that there is similar functionality "sock.sendPresenceUpdate(state, id) ", but the problem here is that I have to set the state for every chat and by the way it will be "online" again after 10 seconds.

**Comment by fadiinho** [comment]
You can set `markOnlineOnConnect` to false in your socket options:
```js
const sock = makeWASocket({
    markOnlineOnConnect: false
});
```
If I remember well, it doesn't work in npm version.

**Comment by phaticusthiccy** [comment]
```es6
setInterval(async () => {
  await sock.sendPresenceUpdate(jid, "unavailable")
}, 10000)
```

**Comment by phaticusthiccy** [comment]
> ```js
> setInterval(async () => {
>   await sock.sendPresenceUpdate(jid, "unavailable")
> }, 10000)
> ```

The interval loop would repeat that every 10 seconds.

**Comment by muhammad-bassiouni** [comment]
> > ```js
> > setInterval(async () => {
> >   await sock.sendPresenceUpdate(jid, "unavailable")
> > }, 10000)
> > ```
> 
> The interval loop would repeat that every 10 seconds.

But here I have to select every chat id and set the status to offline and this is not effective

**Comment by phaticusthiccy** [comment]
Just set jid as your id. 

> > > ```js
> > > setInterval(async () => {
> > >   await sock.sendPresenceUpdate(jid, "unavailable")
> > > }, 10000)
> > > ```
> > 
> > 
> > The interval loop would repeat that every 10 seconds.
> 
> But here I have to select every chat id and set the status to offline and this is not effective

**Comment by muhammad-bassiouni** [comment]
thanks

> Just set jid as your id.
> 
> > > > ```js
> > > > setInterval(async () => {
> > > >   await sock.sendPresenceUpdate(jid, "unavailable")
> > > > }, 10000)
> > > > ```
> > > 
> > > 
> > > The interval loop would repeat that every 10 seconds.
> > 
> > 
> > But here I have to select every chat id and set the status to offline and this is not effective

thanks
