### ISSUE TITLE
URL links sending like normal text

### ISSUE THREAD

**Issue by iamjcharly** [adiwajshing/Baileys#186]
I'm seding a facebook link, but the link is viewed like plane text, just in iphone create the thumb and the link to click it, I'm doing something wrong?

 await conn.sendMessage('1231@s.whatsapp.net', 'https://facebook.com/SOME_VIDEO_URL', MessageType.text);

PD: If i use the same link in my phone the link is sent correctly

**Comment by barkerpedro** [comment]
Try:

```Nodejs
let generatedLink = await conn.generateLinkPreview('https://www.youtube.com/');
conn.sendMessage('xxxxxxxxxx@s.whatsapp.net', generatedLink, MessageType.extendedText);
```

**Comment by iamjcharly** [comment]
In Android still sending like normal text
let generatedLINK = await conn.generateLinkPreview(textMessage);
await conn.sendMessage(contacts[i], generatedLINK, MessageType.extendedText);

**Comment by barkerpedro** [comment]
Update to the last commit and see if it will work.
`npm install github:adiwajshing/baileys`

**Comment by iamjcharly** [comment]
Yes it works, just have to do a delay before send the message
