### ISSUE TITLE
store.contacts doesn't get all contacts

### ISSUE THREAD

**Issue by muhammad-bassiouni** [adiwajshing/Baileys#1860]
sotre.contacts doesn't show anything except two groups. in addition the name of each contact - group -  doesn't exist.

**Comment by vlad-iliescu-tallarium** [comment]
Related to https://github.com/adiwajshing/Baileys/issues/1650. This happens because group info is received on `contacts.set` either before or after the contacts. If the groups are received after, they will overwrite the contacts
