### ISSUE TITLE
[BUG] Errors during the first authentication

### ISSUE THREAD

**Issue by muhammad-bassiouni** [adiwajshing/Baileys#1861]
When I try to to authenticate for the first time, it gives this error
`connection closed due to  Error: Stream Errored (conflict)
    at WebSocket.<anonymous> (.\src\Socket\socket.ts:513:7)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emit (node:domain:475:12)
    at .\src\Socket\socket.ts:273:23
    at Object.decodeFrame (.\src\Utils\noise-handler.ts:164:5)
    at WebSocket.onMessageRecieved .\src\Socket\socket.ts:245:9)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emit (node:domain:475:12)
    at Receiver.receiverOnMessage (.\node_modules\ws\lib\websocket.js:1169:20)
    at Receiver.emit (node:events:527:28) {
  data: { tag: 'stream:error', attrs: {}, content: [ [Object] ] },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 440,
    payload: {
      statusCode: 440,
      error: 'Unknown',
      message: 'Stream Errored (conflict)'
    },
    headers: {}
  }
} , reconnecting  true`
and the store doesn't save either contacts nor chats

**Comment by Guilherme-j10** [comment]
the same with me

**Comment by renatomoitinho** [comment]
the same with me

**Comment by asabadyr** [comment]
Started to get this error today too. Any thoughts?

**Comment by Guilherme-j10** [comment]
I gonna try back some version

**Comment by tmd-billing** [comment]
The same with me ,, i use version ^4.3.0

**Comment by aislanspeedio** [comment]
I'm getting 440 status code but with the latest 5.x version

**Comment by aislanspeedio** [comment]
Would be great if we have a documentation with the description of those status codes

**Comment by satriowicaksn** [comment]
any solution for this issue ?
