### ISSUE TITLE
Why can't the fs/promises module be installed? 

### ISSUE THREAD

**Issue by radhin123** [adiwajshing/Baileys#1869]
- [`https://uploader.maxfile.repl.co/file/7zR7iOlCOCFQ.jpg `](url)
- MD version

**Comment by phaticusthiccy** [comment]
use this, instead of `fs/promises`
```js 
import * as fs from "fs"
// or
const fs = require("fs")
```

**Comment by moo-d** [comment]
Update node to >14.0.0. [``Source``](https://github.com/nodejs/node/issues/35740)

**Comment by radhin123** [comment]
thanks all
