### ISSUE TITLE
Problem login with WhatsApp bussines

### ISSUE THREAD

**Issue by rupas385** [adiwajshing/Baileys#187]
hi, I'm trying to connect this proyect with WhatsApp bussines but not works? 

i get this log:
validated connection successfully
sent init queries
connect attempt 1 failed: BaileysError: timed out... retrying...

Any idea?

**Comment by anaphalis777** [comment]
i got same response here, after load config session then trying to call connect function

**Comment by adiwajshing** [comment]
1. Please attach the entire log
2. Are you on a server?
3. Does your phone have a stable internet connection?
4. Try increasing the idle timeout via `conn.connectOptions.maxIdleTimeMs = 15_000`
