### ISSUE TITLE
[QUESTION] CPU 100% locking baileys

### ISSUE THREAD

**Issue by LeonardoBein** [adiwajshing/Baileys#1870]
I have the problem that I do not know the origin. When you send group messages, Baileys is 100% CPU even having more threads in server available.

![WhatsApp Image 2022-07-04 at 4 14 58 PM](https://user-images.githubusercontent.com/13971947/177351126-291f4915-3372-496d-b372-2616a6050d00.jpeg)

Most of the time, the last log presented is always "sending a new key" before the process crashes in 100% CPU

Is anyone having the same problem?

**Comment by LeonardoBein** [comment]
@LightningNeko Do you have this problem?

**Comment by paulosilvaae2** [comment]
@LightningNeko i see you are used to work groups, and you know a lot about big groups.
This happens mainly on big groups.
We have this problem too.
Could you help us in this issue, please?

**Comment by irham01** [comment]
same problem

**Comment by LightningNeko** [comment]
> @LightningNeko Do you have this problem?

I have a bot with about 30 groups of more than 300 people each and I have no problems sending messages, the cpu is blocked at 100% sending the first message to a chat for about 20 seconds, but then it works fine for me
