### ISSUE TITLE
how to add post method using this connectWa Function Please guide Thanks

### ISSUE THREAD

**Issue by jasmanX** [adiwajshing/Baileys#1872]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

function connectWA (instancesid) {
	sessionName = './auth_info/sessions/'+instancesid
    const { state, saveState } = useSingleFileAuthState(`${sessionName}.json`)
	
    const sock = makeWASocket.default({
		auth: state, 
		logger: pino({ level: 'silent' }),
		printQRInTerminal: true,
		getMessage: async key => {
			return {
				conversation: 'hello'
			}
		}
    })
	
    sock.ev.on('connection.update', async (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
		const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect);
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp(instancesid)
            }
        } else if(connection === 'open') {
})
			
        }
    });
	
	sock.ev.on('creds.update', saveState)

	const sendMessageWTyping = async(msg, jid) => {
		await sock.presenceSubscribe(jid)
		await delay(500)

		await sock.sendPresenceUpdate('composing', jid)
		await delay(2000)

		await sock.sendPresenceUpdate('paused', jid)

		await sock.sendMessage(jid, msg)
	}

	sock.ev.on('messages.upsert', async m => {

		const msg = m.messages[0]
		if(!msg.key.fromMe && m.type === 'notify' && doReplies) {
			await sock.sendReadReceipt(msg.key.remoteJid, msg.key.participant, [msg.key.id])
			await sendMessageWTyping({ text: 'Hello there! I m ' }, msg.key.remoteJid)
		}
	})

	return sock
}
after connection sent message successfully. checked !!

***************** want this type function 👇 Please guide Thanks 
app.post('/sendtext/:mobile/:textmessage', async (req, res) => {
     * how to use above defined sock for sending message ?
     * ?
     * ?
     const mob = formatmobile(req.params.mobile)
     const txt = req.params.textmessage
     const sentmsg = await sock.sendMessage(mob, txt, MessageType.text )
    res.sent(sentmsg)
}

**Comment by AkirahX** [comment]
It made me a little confused, are you having problems using the `sock` in the route?

**Comment by jasmanX** [comment]
thanks to all developed :)
