### ISSUE TITLE
[BUG] `quotedMessage` returning blank message

### ISSUE THREAD

**Issue by ponei** [adiwajshing/Baileys#1873]
**Describe the bug**
`quotedMessage` should have the content of the message, but this isn't always the case
Sometimes `quotedMessage` has `{ conversation: "" }`, which does not represent the real content of the message
The ID clearly exists as seen in picrel
![image](https://user-images.githubusercontent.com/28790957/177656649-2bbc790b-a0f1-4b6f-b16f-13ab8de23d3b.png)

**To Reproduce**
I'm not sure how to replicate since this problem is quite inconsistent, at least on my end
Some older messages have correct `quotedMessage` properties
However I've only encountered this behaviour on `buttonsResponseMessage`, which quotes `buttonsMessage`

**Expected behavior**
A correct `quotedMessage`

**Environment (please complete the following information):**
- OS: Windows 10
- Node version: 14.18.0
- Network: Localhost
- Baileys version: 4.2.0

**Comment by ponei** [comment]
still relevant :^)

**Comment by zennn08** [comment]
same isues
