### ISSUE TITLE
Can't send messages to large groups [BUG]

### ISSUE THREAD

**Issue by Schwartzblat** [adiwajshing/Baileys#1875]
**Describe the bug**
Sending a message to group that has more than 256 participants cause a timeout error
`Error: Timed Out
    at c:\Users\alonp\WebstormProjects\sockBot\node_modules\@adiwajshing\baileys\lib\Utils\generics.js:174:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\generics.js:169:19)\n' +
      '    at waitForMessage (botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:99:61)\n' +
      '    at query (botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:122:22)\n' +
      '    at getUSyncDevices (botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-send.js:174:30)\n' +
      '    at botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-send.js:285:53\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Object.transaction (botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\auth-utils.js:82:21)\n' +
      '    at async relayMessage (botPath\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-send.js:261:9)\n' +
      '    at async Object.sendMessage (botPath\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-send.js:478:17)
 },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

This is happened when I updated baileys version from 4.1.0 to 4.2.0.

**Comment by phaticusthiccy** [comment]
Use git version
```json
{
  "@adiwajshing/baileys": "github:adiwajshing/baileys"
}

**Comment by Schwartzblat** [comment]
Ok  that's solve the problem. Thanks.
