### ISSUE TITLE
[BUG] connection closed due to Error: Stream Errored (ack)

### ISSUE THREAD

**Issue by muhammad-bassiouni** [adiwajshing/Baileys#1876]
The script is working fine, but suddenly it crashes producing the following error
`{"level":50,"time":"2022-07-07T15:00:48.661Z","pid":xxxx,"hostname":"xxxx","class":"baileys","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"xxxxxxxxxxxxx"}}]},"msg":"stream errored out"}
{"level":30,"time":"2022-07-07T15:00:48.664Z","pid":xxxx,"hostname":"xxxx","class":"baileys","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"xxxxxxxxxxxxx"}}]},"isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}},"trace":"Error: Stream Errored (ack)\n  
  at WebSocket.<anonymous> (.\\src\\Socket\\socket.ts:513:7)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at .\baileys\\src\\Utils\\noise-handler.ts:164:5)\n    at WebSocket.onMessageRecieved (.\\baileys\\src\\Socket\\socket.ts:245:9)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emit (node:domain:475:12)\n    at Receiver.receiverOnMessage (.\\baileys\\node_modules\\ws\\lib\\websocket.js:1169:20)\n    at Receiver.emit (node:events:527:28)","msg":"connection errored"}
connection closed due to  Error: Stream Errored (ack)
    at WebSocket.<anonymous> (.\baileys\src\Socket\socket.ts:513:7)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emit (node:domain:475:12)
    at .\baileys\src\Socket\socket.ts:273:23
    at Object.decodeFrame (.\baileys\src\Utils\noise-handler.ts:164:5)
    at WebSocket.onMessageRecieved (.\baileys\src\Socket\socket.ts:245:9)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.emit (node:domain:475:12)
    at Receiver.receiverOnMessage (.\baileys\node_modules\ws\lib\websocket.js:1169:20)
    at Receiver.emit (node:events:527:28) {
  data: { tag: 'stream:error', attrs: {}, content: [ [Object] ] },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
} , reconnecting  true`

**Comment by CleberSilva93** [comment]
i have same problem.

**Comment by cassiano-guardianserver** [comment]
I'm having the same problem

**Comment by mrhb6006** [comment]
I'm having the same problem

**Comment by tiagoagenor** [comment]
I'm having the same problem

**Comment by Guilherme-j10** [comment]
someone solved it ?

**Comment by makanSukros** [comment]
I also experienced this, already using the latest version

**Comment by luispimenta** [comment]
I'm having the same problem

**Comment by OmarMYousef** [comment]
i'm experiencing this too
i hope someone do maintenance for this, kinda disappointing to see all the issues on this problem goes stale without a real solution

**Comment by makanSukros** [comment]
> i'm experiencing this too i hope someone do maintenance for this, kinda disappointing to see all the issues on this problem goes stale without a real solution

+1

**Comment by m4nzm333** [comment]
Up..
I'm using the latest version 4.3.0

**Comment by neves-gabriel** [comment]
Still relevant

**Comment by neves-gabriel** [comment]
Still relevant

**Comment by artmerlop** [comment]
Still relevant, same issue

**Comment by artmerlop** [comment]
> I'm having the same problem

@luispimenta did you solved it?

**Comment by luispimenta** [comment]
> > I'm having the same problem
> 
> @luispimenta did you solved it?

@artmerlop no :(

**Comment by h4775346** [comment]
Same Error Here

**Comment by ni3mumbaikar** [comment]
+1

**Comment by ni3mumbaikar** [comment]
solved added 

`sock.ev.on("creds.update", saveCreds);`

**Comment by Samcotech-ng** [comment]
> 

Where will I add the line?

**Comment by ni3mumbaikar** [comment]
*This is my connection code snippet*

```
async function connectToWhatsApp() {

  const { state, saveCreds } = await useMultiFileAuthState("auth_info_baileys");

  const sock = makeWASocket({
    printQRInTerminal: true,
    auth: state,
    logger: P({ level: "silent" }),
  });

  sock.ev.on("creds.update", saveCreds);

  sock.ev.on("connection.update", async (update) => {

    const { connection, lastDisconnect } = update;
    if (connection === "close") {

      let shouldReconnect = lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut;
      console.log("connection closed due to ", lastDisconnect.error, ", reconnecting ", shouldReconnect);

      if (shouldReconnect) {
        shouldReconnect = false;
        await connectToWhatsApp();
      }
    }

  });
```

> > 
> 
> Where will I add the line?

**Comment by Samcotech-ng** [comment]
> > Where will I add the line?
> 
> _This is my connection code snippet_
> 
> ```
> async function connectToWhatsApp() {
> 
>   const { state, saveCreds } = await useMultiFileAuthState("auth_info_baileys");
> 
>   const sock = makeWASocket({
>     printQRInTerminal: true,
>     auth: state,
>     logger: P({ level: "silent" }),
>   });
> 
>   sock.ev.on("creds.update", saveCreds);
> 
>   sock.ev.on("connection.update", async (update) => {
> 
>     const { connection, lastDisconnect } = update;
>     if (connection === "close") {
> 
>       let shouldReconnect = lastDisconnect.error.output.statusCode !== DisconnectReason.loggedOut;
>       console.log("connection closed due to ", lastDisconnect.error, ", reconnecting ", shouldReconnect);
> 
>       if (shouldReconnect) {
>         shouldReconnect = false;
>         await connectToWhatsApp();
>       }
>     }
> 
>   });
> ```

Which file will I put this.


Sorry, I'm a beginner.

The session doesn't end (It shows active when I check on my phone) but the chatbot stop responding

**Comment by ni3mumbaikar** [comment]
@Samcotech-ng I am not sure which file exactly but it has to be in the same file where you are creating socket.

**Comment by Samcotech-ng** [comment]
> @Samcotech-ng I am not sure which file exactly in your case but it has to be in the same file where you are creating socket.

Okay 
Thanks 

I'll try it 
Is my issue related to yours?

It just stop replying messages even though it's still connected
It doesn't happen on all whatsapps.

**Comment by Samcotech-ng** [comment]
> @Samcotech-ng I am not sure which file exactly in your case but it has to be in the same file where you are creating socket.

Sorry, I can't find the file.
I checked socket.js
