### ISSUE TITLE
[BUG] Unable to listen to audio on smartphone

### ISSUE THREAD

**Issue by jaovito** [adiwajshing/Baileys#1877]
## Description
When I send an audio with baileys, the audio only play on whatsapp web, in fisical device (iPhone) I can't play the audio.

### Steps to reproduce the behavior:
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Add a message upsert.
4. Into message upsert send an audio, like that:

```typescript
sock.ev.on('messages.upsert', async m => {
    const message = m.messages[0];
    if (message.message.conversation === "send") {
      await sock.sendPresenceUpdate('recording', message.key.remoteJid) 

      setTimeout(async () => {
        sock.sendMessage(
          message.key.remoteJid, 
          {
            audio: {
              url: resolve(__dirname, '..', 'files', 'audio.mp3'),
            },
            mimetype: 'audio/mp4',
          }, 
        )
        
        await sock.sendPresenceUpdate('available', message.key.remoteJid) 
      }, 2000)
    }
  })
```

**Expected behavior**
The audio will be sent normally, but I just can't hear it on whatsapp web, when it's on my iPhone. It's like there's no sound in it

**Environment (please complete the following information):**
 - Is this on a server?
   - No, is local
 - What do your `connectOptions` look like? 
   - I only connect with QR code and save my session
 - Do you have multiple clients on the same IP?
   - No
 - Are you using a proxy?
   - No

**Additional context**
My Full code:

```typescript
import makeWASocket, { DisconnectReason, BufferJSON, useMultiFileAuthState } from '@adiwajshing/baileys'
import { Boom } from '@hapi/boom'
import { resolve } from 'path'

const path = resolve(__dirname, '..', 'sessions', 'auth_info_baileys')


async function connectToWhatsApp () {
  const { state, saveCreds } = await useMultiFileAuthState(path)
  const sock = makeWASocket({
      // can provide additional config here
      auth: state,
      printQRInTerminal: true,
  })

  sock.ev.on('connection.update', (update) => {
      const { connection, lastDisconnect } = update
      if(connection === 'close') {
          const shouldReconnect = (lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
          console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
          // reconnect if not logged out
          if(shouldReconnect) {
              connectToWhatsApp()
          }
      } else if(connection === 'open') {
          console.log('opened connection')
      }
  })

  sock.ev.on('messages.upsert', async m => {
    const message = m.messages[0];
    if (message.message.conversation === "send") {
      await sock.sendPresenceUpdate('recording', message.key.remoteJid) 

      setTimeout(async () => {
        sock.sendMessage(
          message.key.remoteJid, 
          {
            audio: {
              url: resolve(__dirname, '..', 'files', 'audio.ogg'),
            },
            mimetype: 'audio/ogg',
          }, 
        )
        
        await sock.sendPresenceUpdate('available', message.key.remoteJid) 
      }, 2000)
    }
  })
  
  sock.ev.on("creds.update", saveCreds)
}
// run in main file
connectToWhatsApp()
```

**Comment by tiagomatrixd** [comment]
mimetype: "audio/mpeg"

**Comment by jaovito** [comment]
> mimetype: "audio/mpeg"

I tried this and it didn't work

**Comment by phaticusthiccy** [comment]
Classic IOS :)
Try this comment: https://github.com/adiwajshing/Baileys/issues/1243#issuecomment-1133061266

**Comment by jaovito** [comment]
> Classic IOS :) Try this comment: [#1243 (comment)](https://github.com/adiwajshing/Baileys/issues/1243#issuecomment-1133061266)

Same problem, now a message display on device.

![00029EB7-B333-4FC4-A9D2-A99D2A8ED20B_1_102_o](https://user-images.githubusercontent.com/61637710/178081479-daece35e-f0b4-4e6e-b0af-f4616615e3c5.jpeg)

If you see, when I send an audio with my voice, have a timeline voice on audio slider (last image)

![ScreenShot 20 24 53 em 08 07 2022](https://user-images.githubusercontent.com/61637710/178081589-a318ad65-5acf-434e-aa3c-4e24bd35c214.png)

**Comment by frmdeveloper** [comment]
please convert ogg to mp3, then send using mimetype audio/mp4

**Comment by frmdeveloper** [comment]
please convert ogg to mp3, then send using mimetype audio/mpeg. If there is an error try audio/mp4.

**Comment by frmdeveloper** [comment]
That's the reason I don't like iOS, because Android is more stable and affordable
