### ISSUE TITLE
 [BUG] tell me pls

### ISSUE THREAD

**Issue by SafwanGanz** [adiwajshing/Baileys#1886]
WhatsApp multi-device bot does not work in groups of more than 257+ people. But it works in groups with few members.. Why?

**Comment by nastarrrr** [comment]
It's fixed, have a look at this
#1762

**Comment by xxirfanx** [comment]
> WhatsApp multi-device bot does not work in groups of more than 257+ people. But it works in groups with few members.. Why?


Use git version

```json
{
  "@adiwajshing/baileys": "github:adiwajshing/baileys"
}
```
