### ISSUE TITLE
Let's build the calling functionality 🥳

### ISSUE THREAD

**Issue by RahulKasireddy** [adiwajshing/Baileys#1889]
### Goals

- Call to jid - [In Progress]
- Answer the call - [In Progress]
- Reject the call ✅

**Comment by SheIITear** [comment]
> ### Goals
> 
>     * Call to jid - [In Progress]
> 
>     * Answer the call - [In Progress]
> 
>     * Reject the call white_check_mark

Answering a call is possible already, but it'll die in few seconds because of no audio.

**Comment by frmdeveloper** [comment]
> **SheIITear**
> Answering a call is possible already, but it'll die in few seconds because of no audio.

How to use ?

**Comment by SheIITear** [comment]
> > **SheIITear**
> > Answering a call is possible already, but it'll die in few seconds because of no audio.
> 
> How to use ?

Join the discord server -> https://discord.com/channels/725839806084546610/843468649088155668/852110006735601674

**Comment by RahulKasireddy** [comment]
> > **SheIITear**
> > Answering a call is possible already, but it'll die in few seconds because of no audio.
> 
> How to use ?

We can use text to speech or like that to generate audio buffer

**Comment by SheIITear** [comment]
> > > **SheIITear**
> > > Answering a call is possible already, but it'll die in few seconds because of no audio.
> > 
> > 
> > How to use ?
> 
> We can use text to speech or like that to generate audio buffer

Thats not the current problem. First have to figure out how the encryption stuff works, implement it properly. Then figure out how the audio is passed and lastly figure out how to produce said audio.

**Comment by RahulKasireddy** [comment]
> > > > **SheIITear**
> > > > Answering a call is possible already, but it'll die in few seconds because of no audio.
> > > 
> > > 
> > > How to use ?
> > 
> > 
> > We can use text to speech or like that to generate audio buffer
> 
> Thats not the current problem. First have to figure out how the encryption/system stuff works, implement it properly. Then figure out how the audio is passed and lastly figure out how to produce said audio.

If you have the function to answer the call can you share me the script?

**Comment by frmdeveloper** [comment]
That is not what I mean. How to use it on multi-device
