### ISSUE TITLE
[BUG] Audio duration is 0:00

### ISSUE THREAD

**Issue by eabuslaiman** [adiwajshing/Baileys#189]
**Describe the bug**
The audio is being sent successfully. Anyway, it doesn't seems to have the duration label in a conversation.

**To Reproduce**
1. Created a new connection
2. Send an audio message using Baileys

**Expected behavior**
The user should receive the audio message, and it also needs to have the duration from the audio.

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**

We're trying to send an audio message using this API. The audio is sent successfully, anyway, it does not seems to have the duration label attached to the audio object. 

**Reproducible example**

Send an audio with the following audio URL: https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3

The code i'm using is the following:

```
const id = (to.indexOf('-') > -1 ? `${to}@g.us` : `${to}@s.whatsapp.net`) // the WhatsApp ID
let buffer = fs.readFileSync('test.mp3'); // This is the file I downloaded from https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_700KB.mp3

const message = await conn.sendMessage(id, buffer, MessageType.audio, {
  mimetype: Mimetype.ogg
});
```

Also, tested with **MessageType.audio** as messageType and **mimetype = Mimetype.mp4Audio**, with same results.

### Image capture

![IMG_4658](https://user-images.githubusercontent.com/10269573/95773606-2b3cd700-0c95-11eb-9874-8ac9ef7492a9.jpg)

Notice that the message is sucessfully sent, and it also is playable. It seems to work everything right. But the duration is 00:00 even when the user is playing the audio.

What am I doing wrong? Any ideas?

Thanks.

**Comment by adiwajshing** [comment]
Thank you for following the template. Your code is correct, WA requires that the audio duration is specified externally in the message body itself. I'll add in something to the options for this.

**Comment by eabuslaiman** [comment]
Thanks @adiwajshing. I tried to investigate in the issue by myself to add a pull request. Anyway, it's not so clear for me how you can view the websocket interaction using WhatsApp web. I tried to open developer tools then open the opened channel for ws (websocket). It contains some encoded messages but I'm unable to "debug" by myself.

Is there any easiest way to understanding the code by watching replies in the developer tools? I'd like to get some of your knowledge to collaborate with this repository.

Thanks again and congrats for awesome service you created.

**Comment by adiwajshing** [comment]
Glad you like the library. 

1. Open Chrome
2. You can open network inspector in chrome, open WA web, and then do whatever you're trying to replicate (say receive an audio message)
3. Export the network contents to a HAR file from Chrome (network panel has that option)
4. Setup a file called `browser-messages.json` in the Baileys root directory.
 - Enter the following contents:
  ``` js
  {
      "encKey": "327eybc871ey87ye87", // get from Chrome's local storage (WASecretBundle)
      "macKey": "238rc9ey9qwu98qw", // get from Chrome's local storage (WASecretBundle)
      "harFilePath": "/Users/abcd/Downloads/web.whatsapp.com.har"
  }
  ```
5. run `yarn browser-decode`. This will decrypt the HAR file and format it, so you can then view the contents & observe how WA communicates.

**Comment by jhonyfrozen** [comment]
I have the same problem.
I've been trying to solve it for two days, but without success yet.
I can play the audio through my web application, this audio is decoded by Baileys and the browser plays normally, but not on the phone.

**Comment by adiwajshing** [comment]
Baileys now automatically fetches the audio duration. These issues should be fixed now

**Comment by danielteodorodt** [comment]
@adiwajshing  Is not working. Even sending ogg, or mp3. I already updated the package. I also cloned the repository.

**Comment by jhonyfrozen** [comment]
> Baileys now automatically fetches the audio duration. These issues should be fixed now


it worked perfectly here.
Thank you

**Comment by danielteodorodt** [comment]
@jhonyfrozen  Can you send me a print of how you are sending the audio. And if you are using this github repository or if you are installing via npm.

**Comment by jhonyfrozen** [comment]
Are you trying to send a blob data from getusermedia?
Because my project receives a  blob data and then send using mp4Audio, but before yet on frontend, the blob need to be converted to mp3 and then sent to backend.

**On backend:**
 ```
  socket.on('sendaudio', async function (payload) {
                const chatId = payload.jid
                const buffer = await Buffer.from(payload.data)
                conn.sendMessage(chatId, buffer, MessageType.audio, { mimetype: Mimetype.mp4Audio, ptt: true })

            });
```
**On frondend:**

`import MicRecorder from "mic-recorder-to-mp3"`
   **...**

```
recorder
          .stop()
          .getMp3()
          .then(([buffer, blob]) => {
            // do what ever you want with buffer and blob
            // Example: Create a mp3 file and play
            self.$socket.client.emit("sendaudio", {
              jid: this.chatId,
              data: blob,
              buffer: buffer,
            });
          })
          .catch((e) => {
            alert("We could not retrieve your message");
            console.log(e);
          });
```

this is what i use.
