### ISSUE TITLE
Not working in 200+ groups[BUG]

### ISSUE THREAD

**Issue by pratyush4932** [adiwajshing/Baileys#1893]
Since past few days the bot is not working in 200+ grps it giving error.Can anyone help why it is happening? i am using baileys 4.2.0

**Comment by FatihArridho** [comment]
User version github

**Comment by xxirfanx** [comment]
Use git version
```
{
  "@adiwajshing/baileys": "github:adiwajshing/baileys"
}
```

**Comment by pratyush4932** [comment]
Thanks
