### ISSUE TITLE
Ca'nt get work sessions after scan qrcode

### ISSUE THREAD

**Issue by ZeniT21** [adiwajshing/Baileys#1894]
I scan my qr and get creds, after get it a removing file auth-info-multi.json. Please! Help
Session work about few seconds and drop:
![photo_2022-07-11_18-16-08](https://user-images.githubusercontent.com/37238491/178297951-0f384e43-080a-4928-a0c3-aca9660611ad.jpg)

**Comment by ZeniT21** [comment]
My code:
const express = require('express')
const qrImage = require('qr-image')
const socksProxyAgent = require('socks-proxy-agent').SocksProxyAgent
const { writeFileSync, createWriteStream, existsSync } = require('fs')
const { default: makeWASocket, BufferJSON} = require('@adiwajshing/baileys')
const fs = require("fs");



const app = express()
app.use(express.json())


app.post('/catch', async (req, res) => {
    res.status(202).send()

    const req_body = req.body
    // meta_id validation
    const metaId = req_body['meta_id']
    if (metaId === undefined) {
        return res.status(422).send('meta_id field is missing')
    }
    // making path to creds file
    const path = `somepath`

    // checking if file exists
   
    // socks field validation
    const proxy = req_body['socks']
    console.log('proxy: '+proxy)

    if (proxy === undefined) {
        return res.status(422).send('socks field is missing')
    }
    // creating proxy agent
    const proxyAgent = new socksProxyAgent(`socks://${proxy}`)
    // inform that request is processing
    res.status(202).send()
    // making socket
    const socket = makeWASocket({
        agent: proxyAgent,
        auth: state,
    })
    socket.ev.on('connection.update', async (update) => {
        // (re)write qr code if new one exists
        console.log(update)
        if (update.qr) {
            const qrSvg = qrImage.image(update.qr, {type: 'png'})
            await qrSvg.pipe(createWriteStream(`${path}/whatsapp_qr.png`))
        }

        // save creds if logged in
        if (update.connection === "close" && socket.authState.creds.account) {



            // baileys requires reconnecting after login (making new socket)
            const new_socket = makeWASocket({auth: socket.authState})
            new_socket.ev.on('connection.update', async (update) => {
                // save auth credentials
                if (update.connection === 'open') {

                    writeFileSync(
                        `${path}/creds.json`,
                        JSON.stringify(new_socket.authState, BufferJSON.replacer, 2)
                    )
                    // closing new socket
                    new_socket.end(undefined)

                    //delete account data for creating new qr
                    //if we are not remove this file - next account does not create
                   const path = '/usr/src/app/auth-info-multi.json'
                    try {
                      fs.unlinkSync(path)
                      //file removed
                    } catch(err) {
                      console.error(err)
                    }

                }
            })
        }
    })
    // closing socket
    socket.ev.on('creds.update', async (update) => {


        socket.end(undefined)



    })

})


const start = () => {
    const port = 3000
    try {
        app.listen(port, () => {
            console.log(`baileys listening`)

        })
    } catch (error) {
        console.log(error)
    }
}

start()

**Comment by ZeniT21** [comment]
`My code:
const express = require('express')
const qrImage = require('qr-image')
const socksProxyAgent = require('socks-proxy-agent').SocksProxyAgent
const { writeFileSync, createWriteStream, existsSync } = require('fs')
const { default: makeWASocket, BufferJSON} = require('@adiwajshing/baileys')
const fs = require("fs");



const app = express()
app.use(express.json())


app.post('/catch', async (req, res) => {
    res.status(202).send()

    const req_body = req.body
    // meta_id validation
    const metaId = req_body['meta_id']
    if (metaId === undefined) {
        return res.status(422).send('meta_id field is missing')
    }
    // making path to creds file
    const path = `somepath`

    // checking if file exists
   
    // socks field validation
    const proxy = req_body['socks']
    console.log('proxy: '+proxy)

    if (proxy === undefined) {
        return res.status(422).send('socks field is missing')
    }
    // creating proxy agent
    const proxyAgent = new socksProxyAgent(`socks://${proxy}`)
    // inform that request is processing
    res.status(202).send()
    // making socket
    const socket = makeWASocket({
        agent: proxyAgent,
        auth: state,
    })
    socket.ev.on('connection.update', async (update) => {
        // (re)write qr code if new one exists
        console.log(update)
        if (update.qr) {
            const qrSvg = qrImage.image(update.qr, {type: 'png'})
            await qrSvg.pipe(createWriteStream(`${path}/whatsapp_qr.png`))
        }

        // save creds if logged in
        if (update.connection === "close" && socket.authState.creds.account) {



            // baileys requires reconnecting after login (making new socket)
            const new_socket = makeWASocket({auth: socket.authState})
            new_socket.ev.on('connection.update', async (update) => {
                // save auth credentials
                if (update.connection === 'open') {

                    writeFileSync(
                        `${path}/creds.json`,
                        JSON.stringify(new_socket.authState, BufferJSON.replacer, 2)
                    )
                    // closing new socket
                    new_socket.end(undefined)

                    //delete account data for creating new qr
                    //if we are not remove this file - next account does not create
                   const path = '/usr/src/app/auth-info-multi.json'
                    try {
                      fs.unlinkSync(path)
                      //file removed
                    } catch(err) {
                      console.error(err)
                    }

                }
            })
        }
    })
    // closing socket
    socket.ev.on('creds.update', async (update) => {


        socket.end(undefined)



    })

})


const start = () => {
    const port = 3000
    try {
        app.listen(port, () => {
            console.log(`baileys listening`)

        })
    } catch (error) {
        console.log(error)
    }
}

start()
`

**Comment by Ajay-o-s** [comment]
try this method [`link`](https://github.com/Ajay-o-s/Keerthana.qr.md/blob/main/index.js)
