### ISSUE TITLE
[BUG] Read message

### ISSUE THREAD

**Issue by BallAmv** [adiwajshing/Baileys#1895]
Bug cannot receive and read messages after deleting All messages in whatsapp settings.  I don't think this is a bug because Baileys is still online, but I can see in the console that there is no indication that it's an error or not, but after I restart Baileys everything is back to normal and I can receive messages again, but over time I'm wasting my time because of small things  this... 

![Screenshot_2022-07-11-23-04-43-52_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/101131224/178308124-6a384656-48cf-47cb-9fdb-8cc1a7c79f8b.jpg)
![Screenshot_2022-07-11-23-04-57-76_6012fa4d4ddec268fc5c7112cbb265e7](https://user-images.githubusercontent.com/101131224/178308137-7fce475d-f43d-44b8-a6bb-342609c1dd8a.jpg)
please follow up

**Comment by FatihArridho** [comment]
Hah? Gua aman" aja hapus semua chat

**Comment by BallAmv** [comment]
> Hah? Gua aman" aja hapus semua chat

Detail bang

**Comment by FatihArridho** [comment]
> > Hah? Gua aman" aja hapus semua chat
> 
> Detail bang

Itu bugnya gmn

**Comment by frmdeveloper** [comment]
wow, they are indonesian
