### ISSUE TITLE
[BUG] Message delivery

### ISSUE THREAD

**Issue by bmbraga** [adiwajshing/Baileys#1899]
I believe that whatsapp changed some rule for the delivery of messages, it's been 3 days since most of the messages are sent, but they are not delivered to the contacts, has anyone gone through this?

**Comment by bagusrasuli** [comment]
Yes I do have same problem too. There are sent response but not delivered to recipient chat. Seems like a bug

**Comment by MuhammadKarzoun** [comment]
any fix ????
