### ISSUE TITLE
[Bug] Status query doesn't work for groups.

### ISSUE THREAD

**Issue by coolnickname** [adiwajshing/Baileys#19]
This is the result for the status query:
`[
            {
                "status": ""
            },
            [
                "query",
                "Status",
                "#####-1589815736@g.us"
            ]`

**Comment by coolnickname** [comment]
Sorry, it was my own fault. Kinda embarrassing.

**Comment by coolnickname** [comment]
Actually the status not working is an actual issue. I assume it should query the group description but it just returns an empty string.

**Comment by adiwajshing** [comment]
You're right, I assumed the same. However, it turns out you need a different query. This is the query you need to execute: 

``` javascript
client.query(["query", "GroupMetadata", "abcd-xyz@g.us"])
.then ( ([json, _]) => console.log("group desc: " + json.desc) )
```

This has been added into the latest commit. You can now execute the same query using ``` client.groupMetadata ("abcd-xyz@g.us") ```

This should resolve your issue.

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing.
