### ISSUE TITLE
Run websockets requests behind proxy ?

### ISSUE THREAD

**Issue by Forium777** [adiwajshing/Baileys#190]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
Hello,
I'd like to know if it's possible to run it behind a proxy ? Also, is it useful or not seen that WhatsApp already has our numbers so running a proxy would be useless ? I ask that because I sometimes get status_code 599 or 429 Too Many Requests so would using a proxy when I get this error fix the problem ?

Thanks!

**Comment by adiwajshing** [comment]
Well, if you followed 1. & 2. you would know that it is possible to run behind a proxy. It's useful if you want to manage a bunch of clients from a single device. The 599/429 is caused by you sending too many requests too quickly to WA, you should probably throttle your requests.

**Comment by Forium777** [comment]
Oh my bad, you were right I just found it thanks! Very last question : is it possible (if yes how?) to reconnect ```client.connect(auth)```  without re-running the script ? Thanks!

**Comment by ycarooliveira** [comment]
brother, do the 1. and 2. before asking... yes it is possible

**Comment by GodCode** [comment]
I think the issue is now solved so it must have been closed....
