### ISSUE TITLE
Cloud Platform to deploy Baileys

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#1901]
Hello any tips where I should deploy baileys to cloud for free? Seems like I can't use Heroku anymore because of the method of saving credential files in one folder. Heroku has an ephemeral file system so it will always delete the credential folder.

Any suggestion is much appreciated.

**Comment by Kenzuya** [comment]
nih bang gw saranin coba deploy di [https://app.jagoan.cloud/](url) lebih enak disitu bang, RAM nya juga gede dari heroku

**Comment by aidulcandra** [comment]
@Kenzuya Nggak ada yang free?

**Comment by Kenzuya** [comment]
pake temp mail mas

**Comment by aidulcandra** [comment]
@Kenzuya Nggak apa2... udah nemu yg free: Glitch namanya

**Comment by frmdeveloper** [comment]
> @aidulcandra
> @Kenzuya Nggak apa2... udah nemu yg free: Glitch namanya

Glitch bisa 24 jam ?

**Comment by frmdeveloper** [comment]
Pakai vps temen aja
