### ISSUE TITLE
[BUG] Messages are not delivered to whatsapp web but are received on devices !? Message absent from node 

### ISSUE THREAD

**Issue by MaznAbdullah** [adiwajshing/Baileys#1902]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - Yes
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - No
 - Are you using a proxy?
 - No

**Additional context**
```
{
  "key": {
    "remoteJid": "XXXXXXXXXX@s.whatsapp.net",
    "fromMe": false,
    "id": "3EB0AAFFACC7F98D821E"
  },
  "messageTimestamp": 1657672565,
  "pushName": "A.J",
  "messageStubType": 2,
  "messageStubParameters": [
    "Message absent from node"
  ]
}
```

**Comment by azudindaem** [comment]
This problem occurs when we send from web whatsapp to device

Sending from baileys to device is okay

Sending from device is okay

Its looks like failure in decrypting message

**Comment by Heknon** [comment]
Also getting this problem.
I am not receiving any of the message data.

This is what I'm getting from debug:
`{"level":20,"time":1657707739672,"pid":18372,"hostname":"DESKTOP-VRMRN0G","unhandled":true,"msgId":"3EB082DFADE54CBC70CC","fromMe":false,"frame":{"tag":"ack","attrs":{"from":"NUMBER","class":"receipt","type":"retry","id":"3EB082DFADE54CBC70CC"}},"msg":"communication recv"}
{"level":20,"time":1657707739803,"pid":18372,"hostname":"DESKTOP-VRMRN0G","recv":{"tag":"receipt","attrs":{"from":"NUMBER","id":"3EB082DFADE54CBC70CC","recipient":"NUMBER","t":"1657707741"}},"sent":{"id":"3EB082DFADE54CBC70CC","to":"NUMBER","class":"receipt"},"msg":"sent ack"}
{"level":20,"time":1657707741465,"pid":18372,"hostname":"DESKTOP-VRMRN0G","recv":{"tag":"message","attrs":{"from":"NUMBER","type":"text","id":"3EB00BDB53E0C4145B84","notify":"╫É╫ò╫¿╫Ö ╫ö╫¿╫É╫£","t":"1657707743"}},"sent":{"id":"3EB00BDB53E0C4145B84","to":"NUMBER","class":"message"},"msg":"sent ack"}
{"level":50,"time":1657707741466,"pid":18372,"hostname":"DESKTOP-VRMRN0G","key":{"remoteJid":"NUMBER","fromMe":false,"id":"3EB00BDB53E0C4145B84"},"params":["Message absent from node"],"msg":"failure in decrypting message"}
{"level":30,"time":1657707741467,"pid":18372,"hostname":"DESKTOP-VRMRN0G","msgAttrs":{"from":"NUMBER","type":"text","id":"3EB00BDB53E0C4145B84","notify":"╫É╫ò╫¿╫Ö ╫ö╫¿╫É╫£","t":"1657707743"},"retryCount":1,"msg":"sent retry receipt"}`

**Comment by Heknon** [comment]
[login log.txt](https://github.com/adiwajshing/Baileys/files/9101303/login.log.txt)
This is the log I get on debug level when logging in by scanning the QR code.
An error is thrown at the beginning:
```
conn close - Error: Stream Errored (restart required)
ERROR!
Error: Stream Errored (restart required)
    at WebSocket.<anonymous> (C:\Users\Administrator\Desktop\name-bot-2\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:408:13)
    at WebSocket.emit (node:events:527:28)
    at C:\Users\Administrator\Desktop\name-bot-2\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:219:35
    at Object.decodeFrame (C:\Users\Administrator\Desktop\name-bot-2\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:131:17)
    at WebSocket.onMessageRecieved (C:\Users\Administrator\Desktop\name-bot-2\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:195:15)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\Users\Administrator\Desktop\name-bot-2\node_modules\ws\lib\websocket.js:1169:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (C:\Users\Administrator\Desktop\name-bot-2\node_modules\ws\lib\receiver.js:513:14)
    at Receiver.getData (C:\Users\Administrator\Desktop\name-bot-2\node_modules\ws\lib\receiver.js:446:17) {
  data: { tag: 'stream:error', attrs: { code: '515' }, content: undefined },
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 515,
    payload: {
      statusCode: 515,
      error: 'Unknown',
      message: 'Stream Errored (restart required)'
    },
    headers: {}
  }
}
```

**Comment by MuhammadKarzoun** [comment]
yes this happens some times, any idea ?

**Comment by Leocardoso94** [comment]
remove `node_modules` folder and reconnect WhatsApp.

it worked for me.

**Comment by azudindaem** [comment]
> remove `node_modules` folder and reconnect WhatsApp.
> 
> it worked for me.

I can confirm this method will solve the problem

**Comment by MaznAbdullah** [comment]
Baileys needs ```node_modules``` to work !
I think you mean rm ```baileys_auth_info``` dir.
it worked for me
weird

**Comment by Leocardoso94** [comment]
remove node_modules and reinstall the deps

**Comment by MaznAbdullah** [comment]
WhatsApp may have removed the ability to see buttons which are sent by normal users : ( Although, I can see buttons sent by official Business APIs
