### ISSUE TITLE
[BUG] xml-not-well-formed on conn.copyNForward with mention

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#1906]
When i try to copyNForward text with Mention Suddenly Emror bro, xml not well formed

Anonymous chat:
const room = Object.values(anonChat).find(room => room.state == 'WAITING' && room.b == "")
if (roomChat && !isCmd && !isGroup && roomChat.b !=="") {
let other = [roomChat.a, roomChat.b].find(user => user !== m.sender)
m.copyNForward(other, true, m.quoted && m.quoted.fromMe ? {
contextInfo: {...m.msg.contextInfo,forwardingScore: 0,isForwarded: true,participant: other}} : {})
}

 m.copyNForward = (jid = m.chat, forceForward = true, options = {}) => conn.copyNForward(jid, m, forceForward, options)

**Comment by officialdittaz** [comment]
![Screenshot_2022-07-13-22-48-04-160_com whatsapp](https://user-images.githubusercontent.com/86673643/178777667-5f34ffe2-1050-4017-82f3-2acc6e8466b1.jpg)
![IMG-20220713-WA0301](https://user-images.githubusercontent.com/86673643/178777683-fd65806c-dd65-4944-85b1-745660a2637f.jpeg)

Okeh

**Comment by aidulcandra** [comment]
Use github version of baileys

npm i github:adiwajshing/baileys

**Comment by officialdittaz** [comment]
> Use github version of baileys
> 
> npm i github:adiwajshing/baileys

Yeah i'm using it
