### ISSUE TITLE
[BUG] message.upsert

### ISSUE THREAD

**Issue by im-shamil** [adiwajshing/Baileys#1907]
message.upsert not working on some chats 

is there any way to get updates except message.upsert ??

**Comment by makanSukros** [comment]
Yes, i have some issue like this, for some chat messages doesn't not appears

**Comment by im-shamil** [comment]
i fixed 

this is because in some chat to get the text will like msg.messages[0].message.conversation 

and

**Comment by makanSukros** [comment]
> message

not work for me, because on my problem, event message.upsert sometimes not triggered if exist new message

**Comment by IanosJunior** [comment]
> > message
> 
> not work for me, because on my problem, event message.upsert sometimes not triggered if exist new message

Same here
