### ISSUE TITLE
[BUG] QR CODE NOT SHOWING

### ISSUE THREAD

**Issue by liteblog** [adiwajshing/Baileys#1909]
I'm using Baileys v4.3.0, and after running the qr code doesn't show up, I have installed qrcode-teminal but it still doesn't appear,
and this my connection source :

```
const makeWASocket = require("@adiwajshing/baileys").default
const pino = require('pino')
const {
   delay,
   useSingleFileAuthState
} = require("@adiwajshing/baileys")
const sessionFile = 'session.json'
const {
   state,
   saveState
} = useSingleFileAuthState(`./${sessionFile}`)

const start = async () => {
   global.client = makeWASocket({
      logger: pino({
         level: 'silent'
      }),
      printQRInTerminal: true,
      browser: ['bot', 'Chrome', '1.0.0'],
      auth: state,
      version: [2, 2224, 8]
   })
   
   client.ev.on('connection.update', async (update) => {
      const {
         connection,
         lastDisconnect
      } = update
      if (connection === 'connecting') {}
      if (connection === 'open') {
         console.log(`Connected, you login as ${client.user.name}`)
      }
      if (connection === 'close') console.log(update)
   })
   
   return client
}

start()
```

**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by zennn08** [comment]
have you installed `qrcode-terminal`?  if you haven't installed it first

`yarn add qrcode-terminal`

**Comment by fazonetea** [comment]
try this
const makeWASocket = require("@adiwajshing/baileys").default
const pino = require('pino')
const {
   delay,
   useSingleFileAuthState
} = require("@adiwajshing/baileys")
const sessionFile = 'session.json'
const {
   state,
   saveState
} = useSingleFileAuthState(`./${sessionFile}`)

const start = async () => {
   global.client = makeWASocket({
      logger: pino({
         level: 'silent'
      }),
      printQRInTerminal: false,
      browser: ['bot', 'Chrome', '1.0.0'],
      auth: state,
      version: [2, 2224, 8]
   })
   
   client.ev.on('connection.update', async (update) => {
      const {
         connection,
         lastDisconnect
      } = update
if(lastDisconnect === undefined) {
		if (update.qr !== undefined){
			//printQRIfNecessaryListener
			const qrcode = require("qrcode-terminal")
			qrcode.generate(update.qr, { small: true })
			console.log('Scan this qr')
		}
	}
      if (connection === 'connecting') {}
      if (connection === 'open') {
         console.log(`Connected, you login as ${client.user.name}`)
      }
      if (connection === 'close') console.log(update)
   })
   
   return client
}

start()

**Comment by makanSukros** [comment]
This is not bug

**Comment by liteblog** [comment]
ok thanks

**Comment by sasmithasevidu** [comment]
> I'm using Baileys v4.3.0, and after running the qr code doesn't show up, I have installed qrcode-teminal but it still doesn't appear, and this my connection source :
> 
> ```
> const makeWASocket = require("@adiwajshing/baileys").default
> const pino = require('pino')
> const {
>    delay,
>    useSingleFileAuthState
> } = require("@adiwajshing/baileys")
> const sessionFile = 'session.json'
> const {
>    state,
>    saveState
> } = useSingleFileAuthState(`./${sessionFile}`)
> 
> const start = async () => {
>    global.client = makeWASocket({
>       logger: pino({
>          level: 'silent'
>       }),
>       printQRInTerminal: true,
>       browser: ['bot', 'Chrome', '1.0.0'],
>       auth: state,
>       version: [2, 2224, 8]
>    })
>    
>    client.ev.on('connection.update', async (update) => {
>       const {
>          connection,
>          lastDisconnect
>       } = update
>       if (connection === 'connecting') {}
>       if (connection === 'open') {
>          console.log(`Connected, you login as ${client.user.name}`)
>       }
>       if (connection === 'close') console.log(update)
>    })
>    
>    return client
> }
> 
> start()
> ```
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Created a new connection
> 2. Closed & used saved credentials to log back in
> 3. Etc.
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server?
> * What do your `connectOptions` look like?
> * Do you have multiple clients on the same IP?
> * Are you using a proxy?
> 
> **Additional context** Add any other context about the problem here.

you can help me?

**Comment by ChamodKeshan** [comment]
> 

pls enter sessoin code
