### ISSUE TITLE
The reconnecting functionality after a connection lost is not working properly

### ISSUE THREAD

**Issue by hexdump2002** [adiwajshing/Baileys#191]
I have been testing the library to see if it recovers correctly form disconnections. Unfortunately it seems it doesn't.

1. Created a new connection
2. Force a disconnection through your firewall, router, etc...
3. I keep getting this group of messages forever:

> closed connection, reason close, reconnecting in a few seconds...    class: "Baileys"
> oh no got disconnected: close, reconnecting: true
> WARN     [2020-10-14 10:12:15.952 +0000] (2207): connect attempt 1 failed, retrying...
>     class: "Baileys"
> WARN     [2020-10-14 10:12:18.958 +0000] (2207): connect attempt 2 failed, retrying...
>     class: "Baileys"
> INFO     [2020-10-14 10:12:22.091 +0000] (2207): connected to WhatsApp Web server, authenticating via reconnect
>     class: "Baileys"
> credentials updated
> INFO     [2020-10-14 10:12:22.563 +0000] (2207): validated connection successfully
>     class: "Baileys"
> WARN     [2020-10-14 10:12:38.579 +0000] (2207): connect attempt 3 failed, retrying...
>     class: "Baileys"
> INFO     [2020-10-14 10:12:41.762 +0000] (2207): connected to WhatsApp Web server, authenticating via reconnect
>     class: "Baileys"
> credentials updated
> INFO     [2020-10-14 10:12:42.807 +0000] (2207): validated connection successfully
>     class: "Baileys"
> WARN     [2020-10-14 10:12:59.121 +0000] (2207): connect attempt 4 failed, retrying...
>     class: "Baileys"
> INFO     [2020-10-14 10:13:02.282 +0000] (2207): connected to WhatsApp Web server, authenticating via reconnect
>     class: "Baileys"
> credentials updated
> INFO     [2020-10-14 10:13:02.854 +0000] (2207): validated connection successfully
>     class: "Baileys"
> WARN     [2020-10-14 10:13:18.914 +0000] (2207): connect attempt 5 failed, retrying...
>     class: "Baileys"
> INFO     [2020-10-14 10:13:22.064 +0000] (2207): connected to WhatsApp Web server, authenticating via reconnect
>     class: "Baileys"
> credentials updated
> INFO     [2020-10-14 10:13:22.656 +0000] (2207): validated connection successfully
...

**Expected behavior**
The connection should recover from the disconnection and keep receiving messages.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? 
```
    conn.connectOptions.regenerateQRIntervalMs = null;
    conn.connectOptions.maxRetries = 10 
```
 - Do you have multiple clients on the same IP?
No
 - Are you using a proxy?
No

**Comment by adiwajshing** [comment]
Can you use the latest commit & try with: `conn.connectOptions.alwaysUseTakeover = true`

Thanks for following template.

**Comment by hexdump2002** [comment]
That worked. Shouldn't this be the default behaviour? 

Thanks!
