### ISSUE TITLE
After this error appears, my bot is dead

### ISSUE THREAD

**Issue by sysnxr** [adiwajshing/Baileys#1918]
/app/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157
.then(() => reject(new boom_1.Boom('Timed Out', {                                           
^                     

Error: Timed Out

**Comment by officialdittaz** [comment]
Inalilahi wainailaihi rojiun botnya dead

**Comment by aidulcandra** [comment]
Use github version

npm install github:adiwajshing/baileys

**Comment by dnl4** [comment]
This issue happened to me when I tried to send message to an invalid number. Check if this is your case.

**Comment by frmdeveloper** [comment]
> @officialdittaz
> Inalilahi wainailaihi rojiun botnya dead

Gak gitu juga

**Comment by sysnxr** [comment]
> Use github version
> 
> npm install github:adiwajshing/baileys

solved \w this, thanks
