### ISSUE TITLE
connection-phone-change event is called with invalid phone state

### ISSUE THREAD

**Issue by hexdump2002** [adiwajshing/Baileys#192]
**Describe the bug**
After I subscribe to the connection-phone-change event, I enter plane mode in my device. Then the handler is alled with a connected state of false. This is correct, but right after that it is called with a connected state of true, which is not correct because my device is still in plane mode. Subsequents notifications are correct with a false value.

**To Reproduce**
1. Created a new connection
2. Subscribe to the connection-phone-change event
3. Sample code:
```
conn.on('connection-phone-change',async (result)=> 
{
        conn.logger.info(result.connected)
})
```
4. When the phone is online this prints:
- false
- true
- false (forever)

**Expected behavior**
As the device is in plane mode (disconnected from any network), the connection-phone-change handler should be called always with a false value but second time it is called with a true value for the phone state param.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like?
```
conn.connectOptions.regenerateQRIntervalMs = null;
conn.connectOptions.maxRetries = 10
conn.connectOptions.alwaysUseTakeover = true  
```
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by adiwajshing** [comment]
Thanks. This should be fixed in the latest commit.
