### ISSUE TITLE
send image is broken

### ISSUE THREAD

**Issue by mdaushi** [adiwajshing/Baileys#1920]
@adiwajshing i have a image base64 and im convert to buffer
then i send 
`const buffer = Buffer.from(message, 'base64')`
`return session.sendMessage(receiver, {image: buffer}, MessageType.image)`
the image was sent but its broken

Please Help Me

**Comment by frmdeveloper** [comment]
AH, broken heart

**Comment by zennn08** [comment]
you don't need `MessageType.image` for version 4.x. read the [docs](adiwajshing.github.io/baileys)

**Comment by mdaushi** [comment]
> AH, broken heart

Ah, galau galau

**Comment by frmdeveloper** [comment]
> @mdaushi 
> Ah, galau galau

Galau menunggu

**Comment by mdaushi** [comment]
> you don't need `MessageType.image` for version 4.x. read the [docs](adiwajshing.github.io/baileys) 

I remove MessageType.image but still not working

**Comment by neoxr** [comment]
> @adiwajshing i have a image base64 and im convert to buffer then i send `const buffer = Buffer.from(message, 'base64')` `return session.sendMessage(receiver, {image: buffer}, MessageType.image)` the image was sent but its broken
> 
> Please Help Me

try this
```
session.sendMessage(receiver, {
   image: {
      url: buffer
   },
   caption: 'pap lagi berak'
})
```

**Comment by mdaushi** [comment]
> > @adiwajshing i have a image base64 and im convert to buffer then i send `const buffer = Buffer.from(message, 'base64')` `return session.sendMessage(receiver, {image: buffer}, MessageType.image)` the image was sent but its broken
> > Please Help Me
> 
> try this
> 
> ```
> session.sendMessage(receiver, {
>    image: {
>       url: buffer
>    },
>    caption: 'pap lagi berak'
> })
> ```

Solve bro
im trying this

backend
```
const buffer = Buffer.from(message.image, 'base64')
session.sendMessage(receiver, {
    image: buffer, 
    caption: 'cebok cebok'
})
```
Handle image Vue
```
var reader = new FileReader();
reader.onload = (event) => {
  const myBuffer = event.target.result.replace('data:', '').replace(/^.+,/, '');
  this.input.image = myBuffer;
};
reader.readAsDataURL(file);
```
```
HTTP.post("chats/send?id=" + this.input.sender, {
  receiver: this.input.receiver,
  message: {
    image: this.input.image,
    caption: this.input.caption
  }
})
```

**Comment by mdaushi** [comment]
thanks for your help
