### ISSUE TITLE
Missing type for detectLinks?

### ISSUE THREAD

**Issue by fadiinho** [adiwajshing/Baileys#1921]
As said [here](https://github.com/adiwajshing/Baileys#notes), you can use `detectLinks: false` to not generate previews when sending a message with an url. I have searched in the code and I don't found anything about `detectLinks`.
```ts
...
   // will detect links & generate a link preview automatically (default true)
    detectLinks: true
...
```
![image](https://user-images.githubusercontent.com/94945604/179419246-d2cf0e28-173b-4b59-a5a9-dae2620db2b7.png)

**Comment by Ajay-o-s** [comment]
install ` link-preview-js`
