### ISSUE TITLE
Can anyone say how i can save the QR as an image file? I want to send it to web frontend.

### ISSUE THREAD

**Issue by akm-akm** [adiwajshing/Baileys#1923]

**Comment by Ajay-o-s** [comment]
i'am  using `qr-image`  to convert the qr code to image
my eg code in [here](https://github.com/Ajay-o-s/Keerthana.qr.md/blob/main/index.js)

**Comment by Ajay-o-s** [comment]
you can see my eg: code [`here`](https://github.com/Ajay-o-s/Keerthana.qr.md/blob/main/index.js)

**Comment by akm-akm** [comment]
thnks, btw can u help me in getting the current connection state. like connected, connecting, not connected.

**Comment by Ajay-o-s** [comment]
[`CODE`](https://github.com/Ajay-o-s/Keerthana.qr.md/blob/main/f.js#L102)

**Comment by Ajay-o-s** [comment]
> thnks, btw can u help me in getting the current connection state. like connected, connecting, not connected.
[`CODE`](https://github.com/Ajay-o-s/Keerthana.qr.md/blob/main/f.js#L102)

**Comment by Ajay-o-s** [comment]
🥰🥰

**Comment by AnonimoPro** [comment]
> você pode ver meu exemplo: código[`here`](https://github.com/Ajay-o-s/Keerthana.qr.md/blob/main/index.js)

Nao esta mais ativo

**Comment by Ajay-o-s** [comment]
> 

isso é um código antigo
