### ISSUE TITLE
whatsapp web is login problem. ' ;;; ' +

### ISSUE THREAD

**Issue by sasmithasevidu** [adiwajshing/Baileys#1926]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by sasmithasevidu** [comment]
login problem with whatsasena qr

**Comment by Guilherme-j10** [comment]
Same here

**Comment by sasmithasevidu** [comment]
> 

how to fix?

**Comment by SL-Alpha-X** [comment]
```js
'Asena;;;' + session
```

> login problem with whatsasena qr

**Comment by ChamodKeshan** [comment]
> ```js
> 'Asena;;;' + session
> ```
> 
> > login problem with whatsasena qr

this code not found

**Comment by PurpShell** [comment]
As you can clearly see, this is Baileys, and not WhatsAsena, talk about whatasena issues otherwhere (a github repo if that project has one)

close this issue afterwards

**Comment by ChamodKeshan** [comment]
> 

Although this is not whatsasena, wa web connection is related to this

**Comment by PurpShell** [comment]
> > 
> 
> Although this is not whatsasena, wa web connection is related to this

They should fix it

Baileys is functioning normally
