### ISSUE TITLE
[BUG] groupGetInviteInfo don't work correctly. [ MD - on Legacy this function don't exist! ]

### ISSUE THREAD

**Issue by Kuroosh** [adiwajshing/Baileys#1928]
**Describe the bug**
If you use `groupGetInviteInfo` on an invalid link / or if you got removed from this group with this link..
Your bot will crash.

**To Reproduce**
1. just use `socket.groupGetInviteInfo(YOUR_INVALID/KICKED GROUP LINK)` to get the error.
2. Error's will come like `Error: not-authorized` etc.

**Expected behavior**
`socket.groupGetInviteInfo(link)` should not crash & return maybe undefined ( or a status code why it can't get any information - like : 406, 401 etc. ) 

**Environment (please complete the following information):**
 - Is this on a server? - Yes
 - What do your `connectOptions` look like? - Standard
 - Do you have multiple clients on the same IP? - No
 - Are you using a proxy? - No

**Additional context**
Thank you for reading.. i hope it will get fixed soon, because we really need this function. 

Greets

- Kuroosh

**Comment by Kuroosh** [comment]
ahh and try catch will not prevent a crash.. because its an internal module error.

example error : 
```
Error: not-authorized
    at assertNodeErrorFree (C:\Users\Neu\node_modules\@adiwajshing\baileys\lib\WABinary\generic-utils.js:56:15)
    at query (C:\Users\Neu\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:126:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.groupGetInviteInfo (C:\Users\Neu\node_modules\@adiwajshing\baileys\lib\Socket\groups.js:122:29)
    at async Object.next (C:\Users\Neu\Documents\Baileys-Bot\src\bot.ts:49:47) {
  data: 401,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}
```

**Comment by fadiinho** [comment]
I guess try/catch doesn't works because `groupGetInviteInfo` is async. Try using `.catch()`.
```ts
socket.groupGetInviteInfo('group').catch((err) => {
  // Do something with the error
  console.log(err.message);
});
```

**Comment by Kuroosh** [comment]
> I guess try/catch doesn't works because `groupGetInviteInfo` is async. Try using `.catch()`.
> 
> ```ts
> const info = socket.groupGetInviteInfo('group').catch((err) => {
>   // Do something with the error
>   console.log(err.message);
> });
> ```

Well.. yes this is a work around.. but a return value would be still good ( like status code or smth ) 

but thx <3 ( this is how i made it actually ) :D
