### ISSUE TITLE
Is ther a way to "translate" singleFileState for useMultiFileAuthState

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#1933]
My clients don't like reconnect, and i need migrate the singleFileState working to more efficiente method useMultiFileAuthState.

I can do this? How?

Thanks

**Comment by Fonnte** [comment]
i create both method. when your device somehow logged out, your client will require to re-scan. the re-scan will using multiauth. if there is no old device using singleauth, you can safely remove the singleauth method

**Comment by drauber** [comment]
Bui i want to migrate to a multiauth without need to reconnect..
