### ISSUE TITLE
get group contacts

### ISSUE THREAD

**Issue by linkon1040z** [adiwajshing/Baileys#1937]
How to extract contacts from a specific group?

**Comment by ztfcode** [comment]
const groupMetadata = await sock.groupMetadata(groupJid: string)
const participants = groupMetadata.participants.map(u => id).map(id => id.replace(/@s.+/g, ''))

**Comment by linkon1040z** [comment]
how to get group participants?

**Comment by linkon1040z** [comment]
Can you help me ? I didn't understand how to apply this in my project

**Comment by ztfcode** [comment]
Where is part you still confused?
