### ISSUE TITLE
[BUG] Template message with buttons and list message not showing

### ISSUE THREAD

**Issue by AlejandroMHA** [adiwajshing/Baileys#1938]
Button type and list type messages are not shown for the one who receives the message, but the one who sends the message is shown

**Sender:**
![sender](https://user-images.githubusercontent.com/50057438/180167659-0c0982e3-a14e-4539-99b4-efb320f01733.jpg)

**Receiver:**
![receiver](https://user-images.githubusercontent.com/50057438/180167688-effa2733-b030-4832-b9e0-39355f36a4d7.jpg)

**Comment by AlejandroMHA** [comment]
The problem occurs with whatsapp in version 2.22.16.12 (beta), I have tried whatsapp version 2.22.15.75 and the web version of whatsapp and that problem does not occur

**Comment by souravkl11** [comment]
> The problem occurs with whatsapp in version 2.22.16.12 (beta), I have tried whatsapp version 2.22.15.75 and the web version of whatsapp and that problem does not occur

WhatsApp may have removed the ability to see buttons which are sent by normal users : ( Although, I can see buttons sent by official Business APIs

**Comment by guiguicdd** [comment]
Same here. Started 22/07. 
Buttons with image still working

**Comment by dralucindaodonto** [comment]
I am still able to send buttons 23/07

**Comment by tarikhagustia** [comment]
same here
