### ISSUE TITLE
Unable to Delete Chat

### ISSUE THREAD

**Issue by Gidraf** [adiwajshing/Baileys#194]
**Describe the bug**
I am trying to delete chat but it's throwing an error 

**To Reproduce**
Steps to reproduce the behaviour:
1. Created a new connection
2. Try deleting any chart 

**Expected behaviour**
It throws this error ```Unexpected status in 'action': Conflict(409)```

**Environment (please complete the following information):**
I am using a Windows machine

**Additional context**

**Comment by adiwajshing** [comment]
1. Is that happening for all chats? 
2. Is the chat you're trying to delete a group or single?

**Comment by Gidraf** [comment]
Currently is happening to the chats I am trying to delete, the chat isn't a group chat, kindly try and see if you can reproduce it on your end if you won't I will post my code so that you may have a look at it. Thanks.

**Comment by adiwajshing** [comment]
Can you post your code please? I can't reproduce on my end

**Comment by SuyKingsleigh** [comment]
I am having the same issue. 

Here's my code: 

    const chats = await conn.chats.all();
    for (const c of chats) {
        let jid = c.jid
        console.log("Deleting " + jid);
        const deleted = await conn.deleteChat(jid)
        console.log("Deleted: " + deleted)
    }
