### ISSUE TITLE
How to reject in coming call ?

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#1942]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by officialdittaz** [comment]
> Use event

Are you sure ?

**Comment by ztfcode** [comment]
`sock.ev.on('call', json => {
/*
  do awesome such block caller etc.
*/
})`

**Comment by ME1SEGAWON** [comment]
can you send anti call code

**Comment by salykingleb** [comment]
Good day to all! Is there any progress in your extremely interesting direction?

**Comment by ztfcode** [comment]
> can you send anti call code

sock.ev.on('call', json => { let { from } = json[2][0][1], action = json[2][0][0] switch (action) { case 'call': await itx.sendMessage(from, 'Anda diblock otomatis karena menelpon bot!', 'conversation') await sleep(500) await itx.blockUser(from, 'add') break default: break }})

**Comment by MaznAbdullah** [comment]
> `sock.ev.on('call', json => { let { from } = json[2][0][1], action = json[2][0][0] switch (action) { case 'call': await itx.sendMessage(from, 'Anda diblock otomatis karena menelpon bot!', 'conversation') await sleep(500) await itx.blockUser(from, 'add') break default: break }})`



> > can you send anti call code
> 
> sock.ev.on('call', json => { let { from } = json[2][0][1], action = json[2][0][0] switch (action) { case 'call': await itx.sendMessage(from, 'Anda diblock otomatis karena menelpon bot!', 'conversation') await sleep(500) await itx.blockUser(from, 'add') break default: break }})

it's will block calling user! not reject call (incoming call still ringing)

**Comment by ztfcode** [comment]
Let me explain you know baileys dont have ability to do that
baileys cant reject oncalling just handling oncalling present

**Comment by zennn08** [comment]
> Let me explain you know baileys dont have ability to do that baileys cant reject oncalling just handling oncalling present

your wrong, baileys can do that :\

**Comment by ztfcode** [comment]
> > Let me explain you know baileys dont have ability to do that baileys cant reject oncalling just handling oncalling present
> 
> your wrong, baileys can do that :\

How do that

**Comment by frmdeveloper** [comment]
> `sock.ev.on('call', json => { let { from } = json[2][0][1], action = json[2][0][0] switch (action) { case 'call': await itx.sendMessage(from, 'Anda diblock otomatis karena menelpon bot!', 'conversation') await sleep(500) await itx.blockUser(from, 'add') break default: break }})`

BAKAA

**Comment by ztfcode** [comment]
> 

So please show me your code to implement this

**Comment by RahulKasireddy** [comment]
Hey there! 👋 I've already implemented the code to reject the call today I'll request a PR (Pull Request) so that you can use that function to reject the call easily.

**Comment by ztfcode** [comment]
> Hei!👋Saya sudah menerapkan kode untuk menolak panggilan hari ini saya akan meminta PR (Tarik Permintaan) sehingga Anda dapat menggunakan fungsi itu untuk menolak panggilan dengan mudah.

Ok thanks a lot ^_^

**Comment by officialdittaz** [comment]
how to update profile status you can use this code

conn.setStatus = async (status) => {
        return await conn.query({
            tag: 'iq',
            attrs: {
                to: 's.whatsapp.net',
                type: 'set',
                xmlns: 'status',
            },
            content: [
                {
                    tag: 'status',
                    attrs: {},
                    content: Buffer.from(status, 'utf-8')
                }
            ]
        })
       
    }






if you want to reject call you can use this code, maybe :v

conn.ws.on('CB:call', async (json) => {
console.log(json)
const callerId = json.content[0].attrs['call-creator']
const idCall = json.content[0].attrs['call-id']
const Id = json.attrs.id
const T = json.attrs.t
conn.sendNode({
  tag: 'call',
    attrs: {
      from: '6289652938715@s.whatsapp.net',
      id: Id,
      t: T
    },
    content: [
      {
        tag: 'reject',
        attrs: {
          'call-creator': callerId,
          'call-id': idCall,
          count: '0'
        },
        content: null
      }
    ]
})

})

**Comment by ztfcode** [comment]
> how to update profile status you can use this code
> 
> conn.setStatus = async (status) => { return await conn.query({ tag: 'iq', attrs: { to: 's.whatsapp.net', type: 'set', xmlns: 'status', }, content: [ { tag: 'status', attrs: {}, content: Buffer.from(status, 'utf-8') } ] })
> 
> ```
> }
> ```
> 
> if you want to reject call you can use this code, maybe :v
> 
> conn.ws.on('CB:call', async (json) => { console.log(json) const callerId = json.content[0].attrs['call-creator'] const idCall = json.content[0].attrs['call-id'] const Id = json.attrs.id const T = json.attrs.t conn.sendNode({ tag: 'call', attrs: { from: '[6289652938715@s.whatsapp.net](mailto:6289652938715@s.whatsapp.net)', id: Id, t: T }, content: [ { tag: 'reject', attrs: { 'call-creator': callerId, 'call-id': idCall, count: '0' }, content: null } ] })
> 
> })

Thanks for the implement ^_^

**Comment by PurpShell** [comment]
close the issue as it is resolved, also regarding @officialdittaz 's code, you should not statically set the number the node is sent from. I'd say get the number dynamically either through (sock.user.id on MD)

```diff
conn.ws.on('CB:call', async (json) => {
    console.log(json)
    const callerId = json.content[0].attrs['call-creator']
    const idCall = json.content[0].attrs['call-id']
    const Id = json.attrs.id
    const T = json.attrs.t
    conn.sendNode({
        tag: 'call',
        attrs: {
-            from: '6289652938715@s.whatsapp.net',
+            from: conn.user.id,
            id: Id,
            t: T
        },
        content: [{
            tag: 'reject',
            attrs: {
                'call-creator': callerId,
                'call-id': idCall,
                count: '0'
            },
            content: null
        }]
    })

})
```

**Comment by frmdeveloper** [comment]
```js
conn.ws.on('CB:call', async (json) => {
    console.log(json)
    const callerId = json.content[0].attrs['call-creator']
    const idCall = json.content[0].attrs['call-id']
    const Id = json.attrs.id
    const T = json.attrs.t
    conn.sendNode({
        tag: 'call',
        attrs: {
-            from: '6289652938715@s.whatsapp.net',
+            from: conn.user.id,
            id: Id,
            t: T
        },
        content: [{
            tag: 'reject',
            attrs: {
                'call-creator': callerId,
                'call-id': idCall,
                count: '0'
            },
            content: null
        }]
    })

})
```
