### ISSUE TITLE
WhatsApp Messenger Not receiving list template message [BUG]

### ISSUE THREAD

**Issue by raphaelvserafim** [adiwajshing/Baileys#1948]
I recently did a test on version  WhatsApp Messenger 2.22.15.74 and it doesn't receive list type messages, messages only appear on the web

**Comment by MaznAbdullah** [comment]
#1902

**Comment by Heknon** [comment]
Can confirm this. I have had to revert to a giant ugly message since WhatsApp beta users can't see list messages (Section messages)
