### ISSUE TITLE
how to mentions in templateMessage ??

### ISSUE THREAD

**Issue by Barqah-Xiex** [adiwajshing/Baileys#1949]
How to mentions in templateMessage
My code:
```
const templateButtons = [
    {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
    {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
    {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const templateMessage = {
    text: "Hi @628979059392",
    footer: 'Hello World',
    templateButtons: templateButtons,
    mentions: ["628979059392@s.whatsapp.net"]
}

sock.sendMessage(id, templateMessage)
```

But unfortunately it still doesn't work the person mentioned there is not mentioned by templateMessage

**Comment by marru452** [comment]
con sender

**Comment by Barqah-Xiex** [comment]
> con sender

what does `con sender` mean?

**Comment by zennn08** [comment]
I think you can't mentions someone in templateMessages

**Comment by nastarrrr** [comment]
wht version of baileys are you using?

**Comment by undefined-60** [comment]
Já ocorreu isso comigo. Não consegui mencionar com templateMessage

**Comment by Barqah-Xiex** [comment]
> wht version of baileys are you using?

Github version:

`npm i https://github.com/adiwajshing/Baileys`

**Comment by Vynn-SOLO** [comment]
Based on what I've tested, you can't tag/mention and reply someone using templateMessages/

**Comment by PurpShell** [comment]
not possible, as the template message itself can't render it (as @Vynn-SOLO said)

i'd say close the issue
