### ISSUE TITLE
How to get all Contacts in MD version

### ISSUE THREAD

**Issue by mi-khatri** [adiwajshing/Baileys#1952]
Hi, 
i want to know How to get all my Contacts in MD version
Thanks

**Comment by ztfcode** [comment]
> Hi, i want to know How to get all my Contacts in MD version Thanks

Use event to update contacts upserted/updated then save it to baileys store is generated by makeInMemoryStore in baileys
As far i know bailey-md version not provide them as default
#CMIW

**Comment by mi-khatri** [comment]
> > Hi, i want to know How to get all my Contacts in MD version Thanks
> 
> Use event to update contacts upserted/updated then save it to baileys store is generated by makeInMemoryStore in baileys As far i know bailey-md version not provide them as default #CMIIW

Thanks a lot....

i tried it, but it not get all contacts. it is get only 20 cntantacs randomly.
Is there is another way to do it ?

Thanks
