### ISSUE TITLE
[BUG] waveform are comming in string format

### ISSUE THREAD

**Issue by Guilherme-j10** [adiwajshing/Baileys#1956]
when I receive an audio message, the waveform property according to the documentation should be an array of numbers, but what comes is a string in a format that appears to be a base64, I tried to decode it but without success. Anyone have an idea how to solve this?

**To Reproduce**
Just run the code example to see the same

**Environment (please complete the following information):**
localhost

![image](https://user-images.githubusercontent.com/55926786/181111431-713e1b82-b6d4-4b7b-887d-dbb360be1b25.png)

**Comment by SheIITear** [comment]
Not a bug.
