### ISSUE TITLE
Bateria

### ISSUE THREAD

**Issue by undefined-60** [adiwajshing/Baileys#1957]
Como ouvir eventos sobre à atualização no percentual da bateria do celular? Na versão legada existia um evento que mostrava isso. Na versão md esse recurso existe ou não?

**Comment by zakinshk** [comment]
Não pode medir o percentual de bateria sendo que a versão mult-device não depende mais de aparelho celular para ficar conectado.

Multi-device não utiliza aparelho para permenecer conectado a conexão é independente amigo.

**Comment by undefined-60** [comment]
Eu meio qur já tinha pensado nisso, isso foi mesmo só para confirmar a hipótese e eu acho que estava correto. Obrigado amigo.

**Comment by zakinshk** [comment]
fecha issue

**Comment by PurpShell** [comment]
please speak english on the issues page, thanks
