### ISSUE TITLE
[BUG] Messages not being received on WhatsApp Web, only in device (phone)

### ISSUE THREAD

**Issue by neves-gabriel** [adiwajshing/Baileys#1958]
**Describe the bug**
We are observing a new issue when sending messages. If the other side don’t have our contact saved, messages sent from Baileys are not being received on WhatsApp Web, only in the receiver's device (phone), after the receiver saves our contact on the device the next messages are delivered ok on WhatsApp Web/desktop. 

**To Reproduce**
1. Created a new connection
2. Choose a number that doesn't have your contact saved
3. Send a message from Baileys to that number,  like : `await sock.sendMessage(id, { text: 'oh hello there' })`
4. Check the receiver's device (phone) for the message
5. Check the receiver's WhatsApp Web for the message

**Expected behavior**
We expected the message to be received on both, WhatsApp Web AND the device (phone), the fact that it only shows on the device is the problem.

**Environment (please complete the following information):**
- Baileys v4.1.0 AND v4.3.0 (both versions have this problem)
- My socket options:
      `printQRInTerminal: true,
        auth: this.state,
        version,
        msgRetryCounterMap,
        browser: [VERSION, "Chrome", "4.0.0"],
        async getMessage(key) {
          return await retrieveMessageRtk(key);
        },`
- We are using useMultiFileAuthState
- Location: Brazil
- We are observing this issue in over 2000 instances of Baileys

**Comment by noiseXfragment** [comment]
Tried to solve it by removing the node_modules folder and reinstalling the library, problem solved for a while, but finally it happened again

**Comment by makanSukros** [comment]
Now im removing node_modules and re-scan number nothing work again, message always not appears on desktop or wa web, does this have something to do with the message failed to decrypt? @adiwajshing

**Comment by pedrosaddi** [comment]
> Now im removing node_modules and re-scan number nothing work again, message always not appears on desktop or wa web, does this have something to do with the message failed to decrypt? @adiwajshing

@makanSukros Did you try what are mentioned in this issue? To save the contact on device and trying receive on web/desktop?

**Comment by makanSukros** [comment]
> > Now im removing node_modules and re-scan number nothing work again, message always not appears on desktop or wa web, does this have something to do with the message failed to decrypt? @adiwajshing
> 
> @makanSukros Did you try what are mentioned in this issue? To save the contact on device and trying receive on web/desktop?

I've tried saving the contact as well but it's still not showing on the desktop/web

**Comment by neves-gabriel** [comment]
Still relevant

**Comment by noiseXfragment** [comment]
it's still happening today
