### ISSUE TITLE
[BUG] Message absent from node

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#1960]
**Describe the bug**
Today I encountered a strange bug, when someone sends a message to my number (as a bot) I don't receive the message content perfectly but I get a messageStubType 2 message with the content "Message absent from node", is anyone experiencing the same thing with me?

**Response from message.upsert**
{"key":{"remoteJid":"xxx@s.whatsapp.net","fromMe":false,"id":"3EB0EA33EA903CEE6C34"},"messageTimestamp":1658994332,"pushName":"Mas Prayogi","messageStubType":2,"messageStubParameters":["Message absent from node"]}

**Comment by noiseXfragment** [comment]
Same issue here, this bug appears when people send via wa desktop

**Comment by Fonnte** [comment]
me too, but it seems back to normal for now, it happend about 5 hours ago

**Comment by makanSukros** [comment]
> me too, but it seems back to normal for now, it happend about 5 hours ago

Until now I'm still experiencing this bug

**Comment by Fonnte** [comment]
> 

is your bot not replying due to absent from node? or your bot not getting the message?

**Comment by makanSukros** [comment]
> {"key":{"remoteJid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","fromMe":false,"id":"3EB0EA33EA903CEE6C34"},"messageTimestamp":1658994332,"pushName":"Mas Prayogi","messageStubType":2,"messageStubParameters":["Message absent from node"]}

bot only receiving like this from message upsert

{"key":{"remoteJid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","fromMe":false,"id":"3EB0EA33EA903CEE6C34"},"messageTimestamp":1658994332,"pushName":"Mas Prayogi","messageStubType":2,"messageStubParameters":["Message absent from node"]}

**Comment by Heknon** [comment]
What version of Baileys are you using?

**Comment by makanSukros** [comment]
this problem appears when the message is sent via whatsapp desktop, if the message is sent from the device everything is normal

**Comment by MaznAbdullah** [comment]
This problem occurs when we send from web whatsapp to device
Sending from baileys to device is okay (but not appear in web whatsapp)
Sending from device is okay
Its looks like failure in decrypting message


remove node_modules and reinstall the dependencies and reconnect

**Comment by makanSukros** [comment]
> This problem occurs when we send from web whatsapp to device Sending from baileys to device is okay (but not appear in web whatsapp) Sending from device is okay Its looks like failure in decrypting message
> 
> remove node_modules and reinstall the dependencies and reconnect

Tried before, for a while the message managed to get in, but in a few hours later the message from wa desktop didn't come back with the message absent from node

**Comment by textarea** [comment]
same here

**Comment by makanSukros** [comment]
It turns out that when I get an error message absent from node, I also get an error message "Closing stale open session for new outgoing prekey bundle" at the same time.

**Comment by riozec** [comment]
Same here. Any update?

**Comment by dnl4** [comment]
Just got this error right now.

**Comment by Alhar6i** [comment]
+1

**Comment by hbinduni** [comment]
i got this error too when i am sending message from new contact to my bot. i have testing it with several number and it always return the same `Message absent from node` error

**Comment by ripreal** [comment]
The problem relates to decoding frame. We do not receive 'enc'  single byte token and it's content from WA. This is how it looks like:
```
{
    "tag": "message",
    "attrs": {
        "from": "",
        "type": "",
        "id": "",
        "notify": "",
        "t": ""
    },
    "content": [
        {
            "tag": "url_text",
            "attrs": {}
        },
        {
            "tag": "url_number",
            "attrs": {}
        },
        {
            "tag": "unavailable",
            "attrs": {}
        }
    ]
}
```
And how normal message looks:
```
{
    "tag": "message",
    "attrs": {
        "from": "",
        "type": "",
        "id": "84839B8B27986549C4C4AD8C25B4C664",
        "recipient": "",
        "verified_level": "unknown",
        "notify": "",
        "verified_name": "",
        "t": ""
    },
    "content": [
        {
            "tag": "enc",
            "attrs": {
                "v": "2",
                "type": "pkmsg"
            },
            "content": {
                "type": "Buffer",
                "data": []
            }
        },
        {
            "tag": "url_text",
            "attrs": {}
        },
        {
            "tag": "url_number",
            "attrs": {}
        }
    ]
}
```

We see that there is no 'enc' tag in the first message. But occasionally it is normal since we do retry (and whatsapp web sure also does ). Baileys indeed after receiving corrupted message sends a retry request from here https://github.com/adiwajshing/Baileys/blob/master/src/Socket/messages-recv.ts#L141 but after 1 attempt it does not receive any response on this request from WA. I assume retry receipt request is somehow mailformed. Most likely tags keys

Or maybe we need to do more that 1retry request even if we do not receive anything from wa socket

**Comment by dnl4** [comment]
>  But occasionally it is normal since we do retry...

Does this mean that it will always work properly? In other words: Will we always be able to read the text even if we get the "failure in decrypting message" warning before the retry?

**Comment by ripreal** [comment]
> > But occasionally it is normal since we do retry...
> 
> Does this mean that it will always work properly? In other words: Will we always be able to read the text even if we get the "failure in decrypting message" warning before the retry?

No. Message from whatsapp does not contain any binary content. Only meta data (tag, attrs etc) There is nothing to decrypt.

**Comment by dnl4** [comment]
Still getting a lot of this error. Anyone found a solution?

**Comment by Capelinha** [comment]
hi, it happened to me today, this was the first message I received from a business account, I had this problem

`
{"key":{"remoteJid":"558799401241@s.whatsapp.net","fromMe":false,"id":"3EB066570E8CA61B294F"},"messageTimestamp":1674746551,"pushName":"Allanyo Santos","messageStubType":2,"messageStubParameters":["Message absent from node"]}

{"key":{"remoteJid":"558799401241@s.whatsapp.net","fromMe":false,"id":"3EB066570E8CA61B294F"},"messageTimestamp":1674746553,"pushName":"Allanyo Santos","messageStubType":2,"messageStubParameters":["Invalid PreKey ID"],"verifiedBizName":"Allanyo Santos"}
`

**Comment by marlonlimaserra** [comment]
up

**Comment by helmarluiz** [comment]
I am also encountering the "Invalid PreKey ID" error when receiving messages using the "@adiwajshing/baileys" library. In my case, this issue occurs only when receiving messages sent from an iPhone 11 Pro Max. However, when messages are sent from WhatsApp Web using Chrome 111.0.5563.146, everything works as expected.

Interestingly, after closing and reopening WhatsApp on my iPhone, I am able to receive messages correctly in Baileys.
