### ISSUE TITLE
[BUG] Problem using Dockerfile

### ISSUE THREAD

**Issue by mariocarvalhope25** [adiwajshing/Baileys#1961]
I'm using the available Dockerfile that uses the node:16-alpine image and when compiling with the docker build, it has the following problem:

![image](https://user-images.githubusercontent.com/35231262/181627681-c3edffd9-8c51-4d08-b854-d31f72b3fbcf.png)

**Comment by mariocarvalhope25** [comment]
Help

**Comment by Manjit2003** [comment]
It's not a Baileys issue but rather a type error in your program. If you update Baileys in your local environment too then you will have the same errors in your IDE

**Comment by mariocarvalhope25** [comment]
@Manjit2003 Do you use an API in a docker environment?
