### ISSUE TITLE
Input file contains unsupported image format

### ISSUE THREAD

**Issue by AxeemHaider** [adiwajshing/Baileys#1963]
**Describe the bug**
I'm getting this error when I try to send image with Buffer

> "class":"baileys","trace":"Error: Input file contains unsupported image format","msg":"failed to obtain extra info"}

**To Reproduce**
```ts
// mediaType = "image"
const mediaBuffer: Buffer = content[mediaType];
this.connection?.wa.sendMessage(
      jid,
      { [mediaType]: mediaBuffer }
);
```

**Comment by thisfardi** [comment]
ur problem solved bro ?

**Comment by AxeemHaider** [comment]
no, I think this error is from third party lib which create thumbnail.

**Comment by noxzym** [comment]
guys, how to solve this problem?
