### ISSUE TITLE
Feature : List of people who have seen the status/story we added

### ISSUE THREAD

**Issue by abinpaul1** [adiwajshing/Baileys#1968]
I was going through the docs and code, but couldnt find a way to get the list of people who have seen the status(story) we have posted. 

From what I know, we get a `reciept` tag with from set as `status@broadcast` when our contact sees the status for the first time. We have a timestamp of when they saw it as well. 

What if I want to get the seen list and timestamps later on. Is that possible? I would be happy to add the feature if I could get any pointers regarding how Whatsapp Web does this.

**Comment by PurpShell** [comment]
you should be able to implement your own store that listens to the receipt (probably on message.upsert), and then you would know who viewed it

**Comment by abinpaul1** [comment]
Yes that would work. So this view list is only stored client side just like messages? Now that you mention it, I think that's the case, just wanted to confirm

**Comment by abinpaul1** [comment]
One last thing. I know it might be too much to ask, but do you know of the table/db in the web.whatsapp site in which these status seen list is stored once it's received.
