### ISSUE TITLE
webhook configuration

### ISSUE THREAD

**Issue by mariocarvalhope25** [adiwajshing/Baileys#1970]
How do I configure the webhook in the API?  I'm using swagger

**Comment by PurpShell** [comment]
which api and which swagger and where are you from and what are the 3 digits on the back of your credit card? All things we don' know. this is not a place for questions and baileys doesn't have webhook functionality.

**Comment by thisfardi** [comment]
how to combine text and button in webhook ?
like this
![1653132415566](https://user-images.githubusercontent.com/38723240/182654715-b6f83638-bc37-457c-978a-9d464fcdafb7.png)
