### ISSUE TITLE
do we have an event for when to delete a group?

### ISSUE THREAD

**Issue by luispimenta** [adiwajshing/Baileys#1976]
I just found it when creating the group or updating the participants, but I don't see anything for when I delete the group

**Comment by fadiinho** [comment]
Asfaik `chats.delete` handles it.

**Comment by luispimenta** [comment]
> Asfaik `chats.delete` handles it.

Here it doesn't work, not even when I delete a normal chat, nor when I delete a group, it's not called 'chats.delete'
does it work there?
