### ISSUE TITLE
What makes it different from mgp25 or yowsup

### ISSUE THREAD

**Issue by bhavya32** [adiwajshing/Baileys#198]
WhatsApp changes its android app to prevent mgp25 and yowsup libraries.
WhatsApp changes button locations and div names or xpath to stop puppeteer based libraries.

=> **Then why not whatsapp changes its websocket system like change the format of data exchange to stop libraries like this.**

=> Why can't whatsapp distinguish between such websockets and real whatsapp web?

**Comment by adiwajshing** [comment]
As far as my understanding goes:
1. We're just using their system without the UI, so I don't see why they would actively try and block something like this
2. Including breaking changes frequently in the underlying code would break the apps for a lot of WA users
