### ISSUE TITLE
[BUG] Socket is not sending images.

### ISSUE THREAD

**Issue by Kuroosh** [adiwajshing/Baileys#1984]
**socket is not sending images.**
Hello
since 2 days i have a problem with socket.sendMessage
it randomly started act weird
if i try to send a image message, it will instantly crash.
it don't throw any kind of error.. and just crash.
i tried it with `Buffer, Base64, using try catch, using .catch().. & even fs.readFileSync`.

**To Reproduce**
```ts
            socket.sendMessage(msg.chatId, {
                image: fs.readFileSync('C:\\Users\\Administrator\\Desktop\\images\\background_join.jpg'),
            });
```
**Expected behavior**
It should send Pictures...

**Environment (please complete the following information):**
 - Is this on a server? - Yes
 - What do your `connectOptions` look like? - Good, everything else working.. only sending images is broken.
 - Do you have multiple clients on the same IP? - No.
 - Are you using a proxy? - No.

**Additional context**
even this simple pic won't being sended
i even tried to catch it with my Friend in these ways : 
```js
process.on('uncaughtException', function (err) {
    console.error(err.name + " | " + err.message);
})
process.on('unhandledRejection', function (err) {
    console.error(err);
})
process.on('exit', console.log);
process.on('SIGKILL', console.log);
process.on('SIGINT', console.log);
process.on('SIGUSR1', console.log);
process.on('SIGUSR2', console.log);
process.on('beforeExit', console.log);

socket.onUnexpectedError = (err, msg) => { 
        console.log(err);
        console.log(msg);
    }

socket.end = (err) => { 
        console.log(err);
    }

(socket.ws as unknown as WebSocket).addEventListener('error', (ev) => console.log(ev));
```

**Comment by Kuroosh** [comment]
And yes, it worked 2 days ago.

**Comment by Francuchin** [comment]
I use a url (https://.....) directly in the _image_ param and it works correctly.

**Comment by Kuroosh** [comment]
> I use a url (https://.....) directly in the _image_ param and it works correctly.

We even used that and it crashed too.

**Comment by SheIITear** [comment]
Possible duplicate of https://github.com/adiwajshing/Baileys/issues/1642#issuecomment-1131919256

**Comment by Kuroosh** [comment]
Switched to the Github Version today - bug still exists...

**Comment by Kuroosh** [comment]
Can't someone help? Since 7 days, we can't use most of our bot features...

**Comment by Kuroosh** [comment]
Ok after switching to the Github Version & implementing `jpegThumbnail` into the sendMessage function, it worked.
