### ISSUE TITLE
[BUG] Buttons not working!

### ISSUE THREAD

**Issue by mmhospedagem** [adiwajshing/Baileys#1985]
After today's whatsapp update, the Android and IOS APPs stopped receiving the templates buttons and buttons lists.

**Comment by mateuscdor** [comment]
same

**Comment by w3nder** [comment]
with version 2.22.16.75 I'm having the same problem, I don't get buttons and send list from lib.

**Comment by rafaeldalbosco** [comment]
Same bug

**Comment by igortrust** [comment]
+1

**Comment by makanSukros** [comment]
Same here

**Comment by zennn08** [comment]
+1

**Comment by makanSukros** [comment]
> Same here

result from message upsert:

{
  "key": {
    "remoteJid": "xxxx@s.whatsapp.net",
    "fromMe": true,
    "id": "BAE5DCD2CF0F06FF"
  },
  "message": {
    "buttonsMessage": {
      "contentText": "Content Test",
      "footerText": "Footer",
      "buttons": [
        {
          "buttonId": "id0",
          "buttonText": {
            "displayText": "Button A"
          },
          "type": "RESPONSE"
        },
        {
          "buttonId": "id1",
          "buttonText": {
            "displayText": "Button B"
          },
          "type": "RESPONSE"
        },
        {
          "buttonId": "id2",
          "buttonText": {
            "displayText": "Button C"
          },
          "type": "RESPONSE"
        }
      ],
      "headerType": "EMPTY"
    }
  },
  "messageTimestamp": "1659581541",
  "status": "PENDING"
}

**Comment by makanSukros** [comment]
> > Same here
> 
> result from message upsert:
> 
> { "key": { "remoteJid": "[xxxx@s.whatsapp.net](mailto:xxxx@s.whatsapp.net)", "fromMe": true, "id": "BAE5DCD2CF0F06FF" }, "message": { "buttonsMessage": { "contentText": "Content Test", "footerText": "Footer", "buttons": [ { "buttonId": "id0", "buttonText": { "displayText": "Button A" }, "type": "RESPONSE" }, { "buttonId": "id1", "buttonText": { "displayText": "Button B" }, "type": "RESPONSE" }, { "buttonId": "id2", "buttonText": { "displayText": "Button C" }, "type": "RESPONSE" } ], "headerType": "EMPTY" } }, "messageTimestamp": "1659581541", "status": "PENDING" }

Message always pending state

**Comment by CarlaFeldens** [comment]
Up de Herbert

**Comment by zakinshk** [comment]
+1 +1 up

**Comment by noiseXfragment** [comment]
Same here, I have downgraded the version also it doesn't work.

Then I get a message from a verified account and send a button message, I get this in the message object section, I don't know if this has an effect or not

![image](https://user-images.githubusercontent.com/110144588/182762158-356309f1-f0ac-4133-a9d9-5d09e03712e0.png)

**Comment by augusthofalqueto** [comment]
same issue

**Comment by Buzier** [comment]
same issue here

**Comment by adiwajshing** [comment]
Do try this: https://github.com/adiwajshing/Baileys/commit/9f3b00d58d4f6b1527db42069acafff01123cbf8

**Comment by makanSukros** [comment]
I have tested, now the button can be sent back, the issue can be closed @mmhospedagem 

Thanks @adiwajshing

**Comment by w3nder** [comment]
I just did the test, with buttons and list I received normally in app version 2.22.16.75

**Comment by maulalwi** [comment]
> Do try this: [9f3b00d](https://github.com/adiwajshing/Baileys/commit/9f3b00d58d4f6b1527db42069acafff01123cbf8)

Works for button only
Templates and list not work

**Comment by maulalwi** [comment]
> I just did the test, with buttons and list I received normally in app version 2.22.16.75

You use WA beta or WA version normally?

**Comment by maulalwi** [comment]
Try modif files https://github.com/adiwajshing/Baileys/pull/1990

And work normally again

**Comment by mmhospedagem** [comment]
templatesButtons in send only buttonMessage are sent!

**Comment by rafaeldalbosco** [comment]
> templatesButtons in send only buttonMessage are sent!

Here too, just buttonMessage and buttonList. templateMessage doesn't work.

**Comment by enoksaju** [comment]
> Try modif files #1990
> 
> And work normally again

this fix template message on Android, but on iPhone the app chash when receive buttons or templateButtons

**Comment by enoksaju** [comment]
any update for iPhones?

**Comment by enoksaju** [comment]
Not solved

**Comment by artmerlop** [comment]
Not solved

**Comment by andersling** [comment]
On iOS version app: 22.16.77 , it is not OK! maybe is relate the the meta data metioned by [noiseXfragment] 

![image](https://user-images.githubusercontent.com/3992929/185771394-abeaeeff-51aa-4c0d-ac43-838138b8ff8f.png)

**Comment by artmerlop** [comment]
It's working on iOS **ONLY** when the **recipient conversation is open**.

**Comment by andersling** [comment]
> 

hi,sir! how to do it in detail? thanks!!

Would you do me a favor to give a detail example message structure? 

have a nice day,sir!

**Comment by andersling** [comment]
> It's working on iOS **ONLY** when the **recipient conversation is open**.

hi,sir! how to do it in detail? thanks!!

Would you do me a favor to give a detail example message structure?

have a nice day,sir!

**Comment by artmerlop** [comment]
@andersling this is the message structure.

```
const options = JSON.parse(optionsJson).map((item, key) => {
        const object = {buttonId: `button${key}`, buttonText: {displayText: item}, type: 1}
        return object
})
const buttonMessage = {
        text: body.message,
        buttons: options,
        headerType: 1
}
await sendMessage('521' + phone + '@s.whatsapp.net', buttonMessage)
```

If you send the message with the recipient phone unlocked and the conversation open the message will arrive even on iOS, but if the app is in background or in another conversation the message won't arrive.

**Comment by andersling** [comment]
@artmerlop  thank you very much,sir!!

**Comment by FaizBastomi** [comment]
no stale

**Comment by lu4t** [comment]
Hi @adiwajshing and @artmerlop , is there something we could do to help solving this? 
Thanks!

**Comment by salsawij** [comment]
> Hi @adiwajshing and @artmerlop , is there something we could do to help solving this? Thanks!

I don't think so, probably Mark Zuckerberg could explain 💀
Latest whatsapp version doesn't really support button messages anymore ig

**Comment by lu4t** [comment]
> > Hi @adiwajshing and @artmerlop , is there something we could do to help solving this? Thanks!
> 
> I don't think so, probably Mark Zuckerberg could explain skull Latest whatsapp version doesn't really support button messages anymore ig

Thanks, I was not aware of that. So I guess we should just close this issue (and all related issues).
