### ISSUE TITLE
How to create fake reply in quoted message in MD? ( Baileys v 4.3.0)

### ISSUE THREAD

**Issue by Maarz-baar** [adiwajshing/Baileys#1986]
How do I create fakereply in quoted message with the remotejid set as 0@s.whatsapp.net. The method in #494 doesn't seems to work anymore. Thanks in advance!

**Comment by fadiinho** [comment]
You can do this way. 

```ts
const quotedMessage = {
  key: {
    id: 'inexistentId',
    remoteJid: '0@s.whatsapp.net',
    participant: '0@s.whatsapp.net',
   },
  message: { conversation: 'Fake Reply' }
}
socket.sendMessage(jid, { text: 'Hmm...' }, {
  quoted: quotedMessage
});
```

**Comment by Maarz-baar** [comment]
> You can do this way. But I guess it only works on Whatsapp Web. If I find another way to do it I'll comment again.
> 
> ```ts
> const quotedMessage = {
>   key: {
>     id: 'inexistentId',
>     remoteJid: '0@s.whatsapp.net',
>     participant: '0@s.whatsapp.net',
>    },
>   message: { conversation: 'Fake Reply' }
> }
> socket.sendMessage(jid, { text: 'Hmm...' }, {
>   quoted: quotedMessage
> });
> ```

Thank You so much <3. It worked flawlessly.
