### ISSUE TITLE
[BUG] Baileys not marking message as read

### ISSUE THREAD

**Issue by paulocorcino** [adiwajshing/Baileys#1987]
**Describe the bug**
I noticed after last update that Baileys not marking messages as read.

**Comment by maulalwi** [comment]
Change sendReadReceipt to readMessages

```
await sock.readMessages([msg.key])
```

**Comment by salykingleb** [comment]
> sendReadReceipt

Which library file is this in?Which library file is this in?

**Comment by maulalwi** [comment]
> > sendReadReceipt
> 
> Which library file is this in?


In the file you created

**Comment by salykingleb** [comment]
> > > sendReadReceipt
> > 
> > 
> > Which library file is this in?
> 
> In the file you created

Ok

**Comment by paulocorcino** [comment]
Yes! Thanks @maulalwi
