### ISSUE TITLE
[BUG] Template buttons not working

### ISSUE THREAD

**Issue by danielceogt** [adiwajshing/Baileys#1988]
**Describe the bug**
Hi, I just tried and the list buttons already work normally, only the template buttons still don't work, on the mobile it doesn't show up... greetings thanks for the support
![image](https://user-images.githubusercontent.com/110597212/182804121-dae75b76-daad-47b5-8a4e-41921a294a32.png)

**Comment by maulalwi** [comment]
Try modif files https://github.com/adiwajshing/Baileys/pull/1990

**Comment by PegeDev** [comment]
> Try modif files #1990

how to modif files ?
