### ISSUE TITLE
Custom path for downloading media

### ISSUE THREAD

**Issue by fdciabdul** [adiwajshing/Baileys#199]
```javascript
const savedFilename = await conn.downloadAndSaveMediaMessage (m)
 ```

there's no option for saving in custom path ?

**Comment by adiwajshing** [comment]
I see the readme may have mislead you, but the option is defined [here](https://github.com/adiwajshing/Baileys/blob/2ce9a1c28d341cd6602796343e93c4d4ccb5073e/src/WAConnection/6.MessagesSend.ts#L228)

**Comment by fdciabdul** [comment]
> I see the readme may have mislead you, but the option is defined [here](https://github.com/adiwajshing/Baileys/blob/2ce9a1c28d341cd6602796343e93c4d4ccb5073e/src/WAConnection/6.MessagesSend.ts#L228)

can you tell us how to send image from base64 image ?

**Comment by adiwajshing** [comment]
#165

**Comment by fdciabdul** [comment]
thank you @adiwajshing  you're awesome 💯
