### ISSUE TITLE
[BUG] Button message working in personal chat only .why?

### ISSUE THREAD

**Issue by SafwanGanz** [adiwajshing/Baileys#1991]
I can't see any buttons in groups
But that's still working in personal chat

Pls help me

**Comment by souravkl11** [comment]
+1

**Comment by LorranX** [comment]
list and button messages working normally after latest update, only template messages still not working correctly, do you have the latest version installed?

**Comment by BrunoSobrino** [comment]
> I can't see any buttons in groups But that's still working in personal chat
> 
> Pls help me

I made the modification in a fork and so far in my case the solution https://github.com/adiwajshing/Baileys/pull/1990/commits has worked for me using the baileys modification of my fork

"@adiwajshing/baileys": "github:BrunoSobrino/baileys"

In my case I left it as a temporary solution, in what they give an official solution

**Comment by SafwanGanz** [comment]
Thanks

**Comment by SafwanGanz** [comment]
> list and button messages working normally after latest update, only template messages still not working correctly, do you have the latest version installed?

No

**Comment by prototypeninja** [comment]
how to make the changeion in javascript version

**Comment by thisfardi** [comment]
please me too only button not work if not write manual.
