### ISSUE TITLE
Syncing Bailyes session with Selenium/Puppeteer

### ISSUE THREAD

**Issue by yuvalwarsh** [adiwajshing/Baileys#1992]
Hey, I'm trying to integrate Baileys with an already existing Chatbot to use the buttons functionality from here.

The other chatbot service uses Puppeteer/Selenium on chrome, so the problem is syncing both sessions so I don't need to connect twice. The session is stored by default in the browser's localstorage by Whatsapp Web itself and it gets loaded when the browser is booted.

So my question is the following: Is there anyway to use this data to authenticate?

**Comment by ahmedRSA** [comment]
Hi

**Comment by yuvalwarsh** [comment]
> Hi

Do you know how to pull that one off?
