### ISSUE TITLE
How to delete anyone's message? Can anyone show implementation?

### ISSUE THREAD

**Issue by akm-akm** [adiwajshing/Baileys#1998]

**Comment by fadiinho** [comment]
As described in the readme,  [https://github.com/adiwajshing/baileys#deleting-messages](here).

```ts
const jid = '123@g.us';

let key: WAMessageKey; // You can get this from the store

await sock.sendMessage(jid, { delete: key });
```

**Comment by akm-akm** [comment]
> As described in the readme, [here](https://github.com/adiwajshing/baileys#deleting-messages)
> 
> ```ts
> const jid = '123@g.us';
> 
> let key: WAMessageKey; // You can get this from the store
> 
> await sock.sendMessage(jid, { delete: key });
> ```

This is for deleting my own message, i want to delete other's message as an admin. How do i implement that?

**Comment by SamPandey001** [comment]
You can use this to delete anyone's message but this requires being admin + should be group.
`let { chat, fromMe, id } = m.quoted;
const key = {
    remoteJid: m.chat,
    fromMe: false,
    id: m.quoted.id,
    participant: m.quoted.sender
}
await sock.sendMessage(m.chat, { delete: key })`

Hope this helps.

**Comment by akm-akm** [comment]
> 

Is it tested?

**Comment by SamPandey001** [comment]
Yeah, I'm using it since week
