### ISSUE TITLE
how to make .jadibot feature?

### ISSUE THREAD

**Issue by ME1SEGAWON** [adiwajshing/Baileys#1999]
can someone give me this code for multidevice bot. i need .jadibot feature, i try to make but i cant, to many error i found

**Comment by FatihArridho** [comment]
Aowkwowk ngabrut

**Comment by Zynfinity** [comment]
:v:

**Comment by BlackAmda** [comment]
Not baileys related ???

**Comment by nastarrrr** [comment]
:v

**Comment by handoko19** [comment]
:v

**Comment by souravkl11** [comment]
> can someone give me this code for multidevice bot. i need .jadibot feature, i try to make but i cant, to many error i found

This isn't a Baileys related issue. Please close this issue

**Comment by ricocrivelli** [comment]
@adiwajshing this issue can be closed!

**Comment by AyGemuy** [comment]
jadiwibu saja

**Comment by aniq12** [comment]
kocak
