### ISSUE TITLE
Download media (base64)  (pictures/videos)

### ISSUE THREAD

**Issue by fidelinkbr** [adiwajshing/Baileys#2]
How to handle received messages that are media and download the complete base64?

**Comment by adiwajshing** [comment]
I haven't added explicit media handling in Baileys. However, Baileys does decode media messages into the media keys & URL you need to download & decrypt the media. Maybe try printing out a media message from the `onUnreadMessage ()` handler?

Also, I would recommend that you read this if you would like to handle [E2E media](https://github.com/sigalor/whatsapp-web-reveng#dealing-with-e2e-media).

**Comment by fidelinkbr** [comment]
It would be a great update of Baileys version. Displaying the base64 of the media in: onUnreadMessage (client.handlers.onUnreadMessage)

**Comment by adiwajshing** [comment]
This has been done. Check out the latest commit.
