### ISSUE TITLE
[BUG] Reconnection when phisycal device losts connection does not happen

### ISSUE THREAD

**Issue by hexdump2002** [adiwajshing/Baileys#200]
**Describe the bug**
At this time, when bayleys whatsapp looses connection it reconnects correctly but, when de physical device it is linked to looses the connection, for example because internet is off on the device or whatsapp closes, it does not reconnect. We are overcoming this by killing the old connection and building a new one that triggers the full the connection flow again.

Should Baileys whatsapp handle this and reconnect when the physical device is available again? Because we have noticed how information arrives to baileys when the device(and its whatsapp) is online again.

**To Reproduce**
1. Start whatsapp on the device
2. Execute this adb command to close whatsapp on the physical device ./adb -s 192.168.18.80 shell am force-stop com.whatsapp
3. Wait for the "asleep" response to arrive to baileys (log in debug mode is needed)
4. Relaunch whatsapp on the device
5. Beileys whatsapps receceives some messages but in the physical device whatsapp, the connection shows but it doesn't show as connected.

**Expected behavior**
When connection is lost in physical device, The baileys whatsapp instance linked to this phone should reconnect again.

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? 
    conn.autoReconnect = ReconnectMode.onConnectionLost
    conn.connectOptions.regenerateQRIntervalMs = null;
    conn.connectOptions.maxRetries = 10
    conn.connectOptions.alwaysUseTakeover = true
    conn.connectOptions.waitForChats = false
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**

**Comment by itacirgabral** [comment]
Hi @hexdump2002 

I'd like to have fine control over the connection too. Maybe a workaround should be pinging a trusted user to detect silent disconnection and try to reconnect lazy on system interaction. It's ugly.

I've found in `src/WAConnection/0.Base.ts`:
```typescript
    constructor () {
        super ()
        this.on ('CB:Cmd,type:disconnect', json => (
            this.state === 'open' && this.unexpectedDisconnect(json[1].kind || 'unknown')
        ))
    }
    /**
     * Connect to WhatsAppWeb
     * @param options the connect options
     */
    async connect() {
        return null
    }
    async unexpectedDisconnect (error: DisconnectReason) {
        const willReconnect = 
            (this.autoReconnect === ReconnectMode.onAllErrors || 
            (this.autoReconnect === ReconnectMode.onConnectionLost && error !== DisconnectReason.replaced)) &&
            error !== DisconnectReason.invalidSession // do not reconnect if credentials have been invalidated
        
        this.closeInternal(error, willReconnect)
        willReconnect && (
            this.connect ()
            .catch(err => {}) // prevent unhandled exeception
        ) 
    }
    /** continues **/
  }
```

And this [#issuecomment-658596680](https://github.com/adiwajshing/Baileys/issues/68#issuecomment-658596680) make think  we don't have a disconnection handler without the `CB:Cmd,type:disconnect` event and the queue prevents to throw.

Query to some cell info kind battery percentage maybe tracks the disconnection (I haven't tried it yet).

**Comment by adiwajshing** [comment]
When the physical device loses the internet connection, you don't need to reconnect WA web. It'll start working the moment the physical device comes back online
