### ISSUE TITLE
How can i delete chat ?

### ISSUE THREAD

**Issue by Borzalic** [adiwajshing/Baileys#2002]
I want to delete the chat record of number@s.whatsapp.net. I want to delete the entire chat, not the messages. How can I do that ?

**Comment by KENPRAEL** [comment]
I need to know too please

**Comment by AndyNotfound** [comment]
I Need info about this too please

**Comment by KENPRAEL** [comment]
Hi everybody, is there any info about this?

**Comment by zennn08** [comment]
You can try this: 
https://github.com/adiwajshing/Baileys#modifying-chats
```ts
const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
await sock.chatModify({
  delete: true,
  lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
},
'123456@s.whatsapp.net')
```

**Comment by mutumbutuku** [comment]
> You can try this: https://github.com/adiwajshing/Baileys#modifying-chats
> 
> ```ts
> const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
> await sock.chatModify({
>   delete: true,
>   lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
> },
> '123456@s.whatsapp.net')
> ```

ReferenceError: getLastMessageInChat is not defined

**Comment by utqinadhif** [comment]
> > You can try this: https://github.com/adiwajshing/Baileys#modifying-chats
> > ```ts
> > const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
> > await sock.chatModify({
> >   delete: true,
> >   lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
> > },
> > '123456@s.whatsapp.net')
> > ```
> 
> ReferenceError: getLastMessageInChat is not defined

not defined,
