### ISSUE TITLE
[BUG] productUpdate - Price Only (Product) error

### ISSUE THREAD

**Issue by user3470** [adiwajshing/Baileys#2003]
**Describe the bug**
I want to update product price only but leaving out images is causing undefined array errors and when using any url including imageUrls.original fro product fetch I get Timeout error

**To Reproduce**
1. fetch catalog and pick and product
2. productUpdate(product.id, {price: newPrice})
3. add urls ```images: [{ url: product.imageUrls.original }],```

**Expected behavior**
Update product price only without changing any image or product status

**Environment (please complete the following information):**
 - Is this on a server? Local Machine
 - What do your `connectOptions` look like?  Socket connection
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
Tried adding all other product info. Still not working
```js
.productUpdate(product.id, {
      ...product,
      images: [{ url: product.imageUrls.original }],
      price: text || product.price
    })
    .then((p) => {
      console.log(p);
    })
    .catch(e => {
      console.log(e);
    })
```

**Comment by Diden05** [comment]
Does productCreate work?
