### ISSUE TITLE
Memory usage is high when five whatsapp sessions are online for weeks for chatbots

### ISSUE THREAD

**Issue by vinayakvasu** [adiwajshing/Baileys#2004]
i have scanned 5 whatsapp instance and make that online for weeks,after 4-6 days memory of the system is increasing gradually(lots of messages are coming and its reply). im using `makeInMemoryStore({ })`  and using message retry. Is all incoming/outgoing messages are stored in memory??then is there any option to avoid that??

**Comment by fadiinho** [comment]
As said [here](https://github.com/adiwajshing/Baileys#implementing-a-data-store) at the end: 
`Note: I highly recommend building your own data store especially for MD connections, as storing someone's entire chat history in memory is a terrible waste of RAM.`
So, the solution is to implement your own store. I'm using MongoDB to make a store. You can see my example [here](https://github.com/fadiinho/MagicBot/blob/main/src/store/makeMongoStore.ts), I don't know if this is the best way, you can ask in the discord if you want, probably there is someone with more experience and maybe a better solution.

**Comment by fadiinho** [comment]
I don't know any mysql example, but you just need to see the `makeInMemoryStore` code and replace that code with your sql queries. You can see it [here](https://github.com/adiwajshing/Baileys/blob/master/src/Store/make-in-memory-store.ts#L30)
And if you implement your store you don't have to use it, `makeInMemoryStore()` is more like an example implementation that adiwajshing made, so you can implement your own store taking it as an example.

**Comment by Ammu164** [comment]
> As said [here](https://github.com/adiwajshing/Baileys#implementing-a-data-store) at the end: `Note: I highly recommend building your own data store especially for MD connections, as storing someone's entire chat history in memory is a terrible waste of RAM.` So, the solution is to implement your own store. I'm using MongoDB to make a store. You can see my example [here](https://github.com/fadiinho/MagicBot/blob/main/src/store/makeMongoStore.ts), I don't know if this is the best way, you can ask in the discord if you want, probably there is someone with more experience and maybe a better solution.

Can i get the discord id?

**Comment by fadiinho** [comment]
> > As said [here](https://github.com/adiwajshing/Baileys#implementing-a-data-store) at the end: `Note: I highly recommend building your own data store especially for MD connections, as storing someone's entire chat history in memory is a terrible waste of RAM.` So, the solution is to implement your own store. I'm using MongoDB to make a store. You can see my example [here](https://github.com/fadiinho/MagicBot/blob/main/src/store/makeMongoStore.ts), I don't know if this is the best way, you can ask in the discord if you want, probably there is someone with more experience and maybe a better solution.
> 
> Can i get the discord id?

Sure. https://discord.gg/XpTeQGDA

**Comment by Alhar6i** [comment]
> 

Dear @fadiinho do you advise us to use your implementation?

**Comment by fadiinho** [comment]
> > 
> 
> Dear @fadiinho do you advise us to use your implementation?

My implementation is not complete, so I recommend you to use [baileys-bottle](https://github.com/deadlinecode/baileys-bottle) (I'm planning to use it). It's a more complete implementation.

**Comment by Alhar6i** [comment]
Many thanks, it seems interesting
