### ISSUE TITLE
[BUG] Whatsapp Crash on IOS Devices After Sending Button Messages.

### ISSUE THREAD

**Issue by xAuxin9** [adiwajshing/Baileys#2009]
Hi, 

After sending a button template message . I tried to send a manual message to the user from my device , The Whatsapp app crashes as soon as I type something on the chat screen .

**Comment by PhantomD** [comment]
Same here, the issue only on ios

**Comment by lucianodltec** [comment]
+1

**Comment by ajeelias** [comment]
+1

**Comment by Samcotech-ng** [comment]
+1

**Comment by lucianodltec** [comment]
This issue still happening even updating this lib. Any work in progress on it?

**Comment by exallhost** [comment]
Any update?

**Comment by tinyCoder32** [comment]
+1

It happens with buttons only, lists work fine on iPhone (at least for me).

**Comment by lucianodltec** [comment]
Hey guys. Is there any workaround to fix this? Is it a Whatsapp bug or Baileys bug?

**Comment by xAuxin9** [comment]
> Hey guys. Is there any workaround to fix this? Is it a Whatsapp bug or Baileys bug?

It is disabled from whtsapp side only!

**Comment by lucianodltec** [comment]
I have changed templateMessage to buttonMessage since I need just reply buttons and everything works fine both on Android and iOS.

**Comment by xAuxin9** [comment]
> I have changed templateMessage to buttonMessage since I need just reply buttons and everything works fine both on Android and iOS.

Are you able to send whatsapp message after the new update?
