### ISSUE TITLE
[BUG]? downloadMediaMessage function doesn't work

### ISSUE THREAD

**Issue by HCAlco** [adiwajshing/Baileys#2015]
Function downloadMediaMessage doesn't work properly or i am so blind that i can't see obvious solution

`sock.ev.on('messages.upsert', async ({ messages }) => {
    const m = messages[0]

    if (!m.message) return // if there is no text or media message
    const messageType = Object.keys (m.message)[0]// get what type of message it is -- text, image, video
    // if the message is an image
    if (messageType === 'imageMessage') {
        // download the message
        const buffer = await downloadMediaMessage(
            m.message[messageType],
            'buffer',
            { },
            { 
                logger,
                // pass this so that baileys can request a reupload of media
                // that has been deleted
                reuploadRequest: sock.updateMediaMessage
            }
        )
        // save to file
        await writeFile('./my-download.jpeg', buffer)
    }`

Everything else works fine without that function and i have to admit that this part is from README so the problem is i get error when this part is not commented saying:

`"Argument of type 'IMessage' is not assignable to parameter of type 'IWebMessageInfo' . Property 'key' is missing in type 'IMessage' but required in type 'IWebMessageInfo'.`

Looks like in "Message Upsert" event anonymous function gets array of 'IMessage' type of objects instead of 'IWebMessageInfo' but i really don't know how to fix that and in discord people don't know what to do...
Don't throw rocks on me, i am not that experienced programmer. Please help :D

**Comment by AxeemHaider** [comment]
Did you able to solve that ???

**Comment by HCAlco** [comment]
Nope. Still no solution
