### ISSUE TITLE
Device Signature in WhatsApp App

### ISSUE THREAD

**Issue by mmmlves** [adiwajshing/Baileys#2016]
Hello,
  I noticed that the API signs "Baileys" on the connected devices screen in whatsapp app. This could be a problem due some reasons:
1. If someday whatsapp decides to ban Baileys users will be very easy - only see the device signature in connection and
2. This could be a vulnerability if a customer seems the signature - the API used to develop the product is exposed opening a backdoor for many problems and/or commercial issues.
 Is it possible to change it for "Google Chrome" or any usual connected device signature? I didn't find this possibility in the socket connections ops.

**Comment by mrfzvx12** [comment]
> Hello, I noticed that the API signs "Baileys" on the connected devices screen in whatsapp app. This could be a problem due some reasons:
> 
> 1. If someday whatsapp decides to ban Baileys users will be very easy - only see the device signature in connection and
> 2. This could be a vulnerability if a customer seems the signature - the API used to develop the product is exposed opening a backdoor for many problems and/or commercial issues.
>    Is it possible to change it for "Google Chrome" or any usual connected device signature? I didn't find this possibility in the socket connections ops.

try this.. to change it..
const client = WASocket({
        printQRInTerminal: true,
        auth: state,
        logger: Pino({ level: 'silent' }),
        browser: ['Example', 'Safari', '1.0'],
        version,
    })

**Comment by mmmlves** [comment]
Thanks! Worked !
