### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhaoying-zoe** [adiwajshing/Baileys#2017]
**Describe the bug**
When I scan the code to log in, the CPU of baileys server will rise very high. How can I solve the problem of soaring CPU?

**To Reproduce**
1. scan the code to log in

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?   yes
 - What do your `connectOptions` look like?    
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy?   no

**Comment by fadiinho** [comment]
This is probably because of the store provided by Baileys. If this is the problem, the only solution is to use a custom store.
[Here](https://github.com/deadlinecode/baileys-bottle) is a store made by a Baileys user, you can use any database you want with that.

**Comment by zhaojiankun6** [comment]
> This is probably because of the store provided by Baileys. If this is the problem, the only solution is to use a custom store. [Here](https://github.com/deadlinecode/baileys-bottle) is a store made by a Baileys user, you can use any database you want with that.

We now suspect that the decryption of the received message will cause the CPU to rise。
