### ISSUE TITLE
Can we change "Bailys" after whatsup scan QRcode 

### ISSUE THREAD

**Issue by Akash-Rathore** [adiwajshing/Baileys#2021]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by xxirfanx** [comment]
Chrome 

>```JS
> browser: ['Example','Chrome', '4.0.0']
>```
Safari 

>```JS
> browser: ['Example','Safari', '1.0.0']
>```

Example [check](https://github.com/adiwajshing/Baileys/blob/6fbca92c533f730b6af97f2c6c7a241e76d02e51/Example/example.ts#L24)

>```JS
> const sock = makeWASocket({
> 		version,
> 		logger,
> 		printQRInTerminal: true,
>                 browser: ['Example','Chrome', '4.0.0'],
> 		auth: state
>                 })

**Comment by BlackAmda** [comment]
> Chrome
> 
> > ```js
> > browser: ['Example','Chrome', '4.0.0']
> > ```
> 
> Safari
> 
> > ```js
> > browser: ['Example','Safari', '1.0.0']
> > ```
> 
> Example [check](https://github.com/adiwajshing/Baileys/blob/6fbca92c533f730b6af97f2c6c7a241e76d02e51/Example/example.ts#L24)
> 
> > ```js
> > const sock = makeWASocket({
> > 		version,
> > 		logger,
> > 		printQRInTerminal: true,
> >                 browser: ['Example','Chrome', '4.0.0'],
> > 		auth: state
> >                 })
> > ```
----
Firefox
> ```js
> browser: ['Example','firefox', '1.0.0']

Edge
> ```js
> browser: ['Example','edge', '1.0.0']

Opera
> ```js
> browser: ['Example','opera', '1.0.0']
