### ISSUE TITLE
Push notifications don't work

### ISSUE THREAD

**Issue by yuvalwarsh** [adiwajshing/Baileys#2023]
It seems I can not get push notifications on my phone, because bayIies keeps me online..

Is there a way to fix it, and set me as offline, so I can recieve notifications on my phone.

Thank you

**Comment by ajeelias** [comment]
const sock = makeWASocket({
		version,
		printQRInTerminal: true,
		auth: state,
		msgRetryCounterMap,
		markOnlineOnConnect:false,
....
