### ISSUE TITLE
Error: Unexpected server response: 400, retrying...

### ISSUE THREAD

**Issue by YanWrtama** [adiwajshing/Baileys#2024]
![Capturxxe](https://user-images.githubusercontent.com/31368776/184006017-07c3a23c-6a83-4adc-8446-0d1d21088ac4.PNG)
Anyone know this problem?
i have tried by changing,
================  
const conn = new WAConnection()
      conn.version = [2,2230,10];
================     
(new version 2,2230,10) :(

**Comment by xxirfanx** [comment]
> # ![Capturxxe](https://user-images.githubusercontent.com/31368776/184006017-07c3a23c-6a83-4adc-8446-0d1d21088ac4.PNG)
> Anyone know this problem?
> i have tried by changing,
> # const conn = new WAConnection()
> conn.version = [2,2230,10];
> (new version 2,2230,10) :(

 This check : [baileys version](https://github.com/adiwajshing/Baileys/blob/master/src/Defaults/baileys-version.json)

**Comment by YanWrtama** [comment]
> > # ![Capturxxe](https://user-images.githubusercontent.com/31368776/184006017-07c3a23c-6a83-4adc-8446-0d1d21088ac4.PNG)
> > Anyone know this problem?
> > i have tried by changing,
> > # const conn = new WAConnection()
> > conn.version = [2,2230,10];
> > (new version 2,2230,10) :(
> 
> This check : [baileys version](https://github.com/adiwajshing/Baileys/blob/master/src/Defaults/baileys-version.json)

Thank you for the response, earlier I had the time to change it according to  [baileys version](https://github.com/adiwajshing/Baileys/blob/master/src/Defaults/baileys-version.json) but I still can't

**Comment by YanWrtama** [comment]
![image](https://user-images.githubusercontent.com/31368776/184012528-9621b1f8-e82e-443a-9246-cdd8c05f4c3a.png)

**Comment by fadiinho** [comment]
Which version of baileys are you using?
