### ISSUE TITLE
[BUG] Button template no received in iphone / IOS

### ISSUE THREAD

**Issue by mmhospedagem** [adiwajshing/Baileys#2026]
Currently in the baileys version available on github, it is not possible to send messages from button templates for iphone IOS

Fix #1990  does not fix BUG on whatsapp iphone!

**Comment by ORMiK0** [comment]
duplicate #1985

**Comment by Himanshu1234556** [comment]
Also not working on Android

**Comment by alsak0de** [comment]
Fix didn't work for me either although it changed behaviour.
Now an empty type of message is received but then whatsapp app hangs and a 'clean chat' is needed to use whatsapp on the phone again :D 

I went back to the original messages.ts but no template messages are received on the phone. They do appear on heavy mac client, though.

**Comment by exallhost** [comment]
Face the same behavior. Any personal suggestions?

**Comment by vishwajit76** [comment]
Same here

**Comment by mzayn** [comment]
+1 same just waiting for the next patch update

**Comment by aarvee022** [comment]
Any update?

**Comment by exallhost** [comment]
No work in iOS. Any update?
