### ISSUE TITLE
makeInMemoryStore How to used

### ISSUE THREAD

**Issue by Akash-Rathore** [adiwajshing/Baileys#2029]
i am using makeInMemoryStore  in express Server . then showing 

Error: Cannot find module '@adiwajshing/keyed-db'
Require stack:
- C:\Users\akash\OneDrive\Desktop\adhiraj\Testing\node_modules\@adiwajshing\baileys\lib\Store\make-in-memory-store.js
- C:\Users\akash\OneDrive\Desktop\adhiraj\Testing\node_modules\@adiwajshing\baileys\lib\Store\index.js
- C:\Users\akash\OneDrive\Desktop\adhiraj\Testing\node_modules\@adiwajshing\baileys\lib\index.js
- C:\Users\akash\OneDrive\Desktop\adhiraj\Testing\src\app.js

**Comment by Laerthe-Souza** [comment]
This is simple, just install this module yarn install @adiwajshing/keyed-db. That should solve your problem

**Comment by makanSukros** [comment]
This is not a bug
