### ISSUE TITLE
[BUG] - Issue on Bailey - Kept Disconnected after 1-2 hour

### ISSUE THREAD

**Issue by mzayn** [adiwajshing/Baileys#2030]
**Describe the bug**

**To Reproduce**
1. Created a new connection via pm2
2. after 1 - 2 hour disconnected 
3. error log form node included : 

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 Yes Arm Ubuntu Server

 - What do your `connectOptions` look like? 
 using pm2

 - Do you have multiple clients on the same IP?
-

 - Are you using a proxy?
 - no

**Additional context**

==============

Hello 

i got this error and my connection always disconnected. 

```

2022-08-12T05:46:47: [31mERROR[39m [2022-08-12 05:46:46.514 +0800]: [36mstream errored out[39m
2022-08-12T05:46:47:     node: {
2022-08-12T05:46:47:       "tag": "stream:error",
2022-08-12T05:46:47:       "attrs": {
2022-08-12T05:46:47:         "code": "503"
2022-08-12T05:46:47:       }
2022-08-12T05:46:47:     }
2022-08-12T05:46:47: [32mINFO[39m [2022-08-12 05:46:46.514 +0800]: [36mconnection errored[39m

2022-08-12T05:46:47:     trace: "Error: Stream Errored (unknown)\n    at WebSocket.<anonymous> (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:414:13)\n    at WebSocket.emit (node:events:527:28)\n    at /www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:220:35\n    at Object.decodeFrame (/www/bailey/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)\n    at WebSocket.emit (node:events:527:28)\n    at Receiver.receiverOnMessage (/www/bailey/node_modules/ws/lib/websocket.js:1022:20)\n    at Receiver.emit (node:events:527:28)\n    at Receiver.dataMessage (/www/bailey/node_modules/ws/lib/receiver.js:507:14)\n    at Receiver.getData (/www/bailey/node_modules/ws/lib/receiver.js:440:17)"
```

how to fix this ?
Thanks

**Comment by atrikx** [comment]
I have a library and also got this issue, I guess its from whatsapp, it automatically closes connection with you because he thinks you "dead", to fix this I programmed an automatic send msg for my other number every 30min

**Comment by mzayn** [comment]
> 5

i see, so i need to reconfigure the code make some bot kept active for auto-reply every /30 min. 

hope bailey can fix this issue soon. 

thanks

**Comment by atrikx** [comment]
> > 5
> 
> i see, so i need to reconfigure the code make some bot kept active for auto-reply every /30 min.
> 
> hope bailey can fix this issue soon.
> 
> thanks

as I said, I have a library built on python, it's not using bailey's and i get the same issues... i don't think bailey can fix this....

btw, the bug of send buttons its killing me... it's only showing on whatsapp web, dont show on android or ios anymore :(
do u know anything about it?

**Comment by mmmlves** [comment]
to fix the buttons bug: https://github.com/adiwajshing/Baileys/pull/1996/files
this is already committed in the newest Baileys version (not stable)

**Comment by mzayn** [comment]
how to check if bailey make auto update for WA version on web cause in my node log say this version 

` using WA v2.2228.8, isLatest: true`

and the code configure like this 

```
    // fetch latest version of WA Web
    const { version, isLatest } = await fetchLatestBaileysVersion()
    console.log(`using WA web v${version.join('.')}, isLatest: ${isLatest}`)

```

do bailey have update for this ?

**Comment by Alhar6i** [comment]
I don't think it was Bailey's issue!
You need to write your own reconnecting logic.

I use this solution


```
sock.ev.on('connection.update', (update) => {
		const { connection, lastDisconnect } = update

		console.log(`CONNECTION STATE ${connection}`)

		if (connection === 'close') {
			// reconnect if not logged out
			if ((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {

				if (lastDisconnect.error.message === 'Normal Disconnect') {
					console.log('Close connection normally')
					return;
				}

				if ((lastDisconnect.error as Boom)?.data?.code === "ENOTFOUND") {
					setTimeout(function () {
						controllerSocket(Controller)
					}, 21000)
				}
				else {
					controllerSocket(Controller)
				}
			} else {
				controllerEvent.emit('close');
				console.log(`${Controller} Connection closed. You are logged out.`)
			}
		}
		else if (connection === 'connecting') {
			controllerEvent.emit('connecting', sock);
		}
	})

```

You might be wondering about 'Normal Disconnect', I pass this parameter, whenever I want, to inform Baileys that the connection was closed normally. 

`	sock.end(new Error('Normal Disconnect'));
`

**Comment by mzayn** [comment]
> I don't think it was Bailey's issue! You need to write your own reconnecting logic.
> 
> I use this solution
> 
> ```
> sock.ev.on('connection.update', (update) => {
> 		const { connection, lastDisconnect } = update
> 
> 		console.log(`CONNECTION STATE ${connection}`)
> 
> 		if (connection === 'close') {
> 			// reconnect if not logged out
> 			if ((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {
> 
> 				if (lastDisconnect.error.message === 'Normal Disconnect') {
> 					console.log('Close connection normally')
> 					return;
> 				}
> 
> 				if ((lastDisconnect.error as Boom)?.data?.code === "ENOTFOUND") {
> 					setTimeout(function () {
> 						controllerSocket(Controller)
> 					}, 21000)
> 				}
> 				else {
> 					controllerSocket(Controller)
> 				}
> 			} else {
> 				controllerEvent.emit('close');
> 				console.log(`${Controller} Connection closed. You are logged out.`)
> 			}
> 		}
> 		else if (connection === 'connecting') {
> 			controllerEvent.emit('connecting', sock);
> 		}
> 	})
> ```
> 
> You might be wondering about 'Normal Disconnect', I pass this parameter, whenever I want, to inform Baileys that the connection is closed normally.
> 
> ` sock.end(new Error('Normal Disconnect')); `

hi, thanks for the code and reply.. but for my code configure like this 

```
    sock[token].ev.on('connection.update', async (update) => {
        const { connection, qr, lastDisconnect } = update
        if (connection === 'close') {
            // reconnect if not logged out
            if ((lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut) {
               
                if ((lastDisconnect.error)?.output?.payload?.message === 'Stream Errored (restart required)') {
                    delete qrcode[token]
                    connectToWhatsApp(token, io)
                    if (io != null) io.emit('message', { token: token, message: "Reconnecting" })
                } else if ((lastDisconnect.error)?.output?.payload?.message === 'QR refs attempts ended') {
                    delete qrcode[token]
                    if (io != null) io.emit('message', { token: token, message: lastDisconnect.error.output.payload.message, error: lastDisconnect.error.output.payload.error })
                }
            } else if ((lastDisconnect.error)?.output?.statusCode === 401) {
                setStatus(token, 'Disconnect')
                console.log('Connection closed. You are logged out.')
                if (io !== null) {
                    io.emit('message', { token, message: 'Connection closed. You are logged out.' })
                }
                clearConnection(token)
            }
        }

        if (qr) {
            // SEND TO YOUR CLIENT SIDE
            QRCode.toDataURL(qr, function (err, url) {
                if (err) {
                    console.log(err);
                }
                qrcode[token] = url
                if (io !== null) {
                    io.emit('qrcode', { token, data: url, message: 'Qrcode updated, please scan with your Whatsapp Device' })
                }
            })
        }

        if (connection === 'open') {
            
            setStatus(token, 'Connected')
            let number = sock[token].user.id.split(':')
            number = number[0] + '@s.whatsapp.net'

            const ppUrl = await getPpUrl(token, number)
            if (io !== null) {

                io.emit('connection-open', { token, user: sock[token].user, ppUrl })
            }
            delete qrcode[token]
        }
```

need to change ? 

thanks

**Comment by mzayn** [comment]
> I don't think it was Bailey's issue! You need to write your own reconnecting logic.
> 
> I use this solution
> 
> ```
> sock.ev.on('connection.update', (update) => {
> 		const { connection, lastDisconnect } = update
> 
> 		console.log(`CONNECTION STATE ${connection}`)
> 
> 		if (connection === 'close') {
> 			// reconnect if not logged out
> 			if ((lastDisconnect.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut) {
> 
> 				if (lastDisconnect.error.message === 'Normal Disconnect') {
> 					console.log('Close connection normally')
> 					return;
> 				}
> 
> 				if ((lastDisconnect.error as Boom)?.data?.code === "ENOTFOUND") {
> 					setTimeout(function () {
> 						controllerSocket(Controller)
> 					}, 21000)
> 				}
> 				else {
> 					controllerSocket(Controller)
> 				}
> 			} else {
> 				controllerEvent.emit('close');
> 				console.log(`${Controller} Connection closed. You are logged out.`)
> 			}
> 		}
> 		else if (connection === 'connecting') {
> 			controllerEvent.emit('connecting', sock);
> 		}
> 	})
> ```
> 
> You might be wondering about 'Normal Disconnect', I pass this parameter, whenever I want, to inform Baileys that the connection is closed normally.
> 
> ` sock.end(new Error('Normal Disconnect')); `

- your code that can make the auto reconnecting when close ?

**Comment by Alhar6i** [comment]
here you go
the setTimeout function is used just in case your internet was down so it tries to reconnect every 21 seconds instead of connecting aggressively


```
if ((lastDisconnect.error as Boom)?.data?.code === "ENOTFOUND") {
	setTimeout(function () {
		controllerSocket(Controller)
	}, 21000)
}
else {
	controllerSocket(Controller)
}
```

**Comment by Alhar6i** [comment]
> 
> * your code that can make the auto reconnecting when close ?

The bot listens to the user encoded input if it's for example 'Pleas_Close_Me' then the connection is ended normally.
That allows the user to stop the bot without logged it out

**Comment by mzayn** [comment]
> here you go the setTimeout function is used just in case your internet was down so it tries to reconnect every 21 seconds instead of connecting aggressively
> 
> ```
> if ((lastDisconnect.error as Boom)?.data?.code === "ENOTFOUND") {
> 	setTimeout(function () {
> 		controllerSocket(Controller)
> 	}, 21000)
> }
> else {
> 	controllerSocket(Controller)
> }
> ```

hi,

already use your code but, my Bot WA still DC

here the log node :

```
2022-08-16T10:12:09: [32mINFO[39m [2022-08-16 10:12:08.416 +0800]: [36mconnection errored[39m
2022-08-16T10:12:09:     trace: "Error: Connection Terminated\n    at WebSocket.<anonymous> (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:351:30)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emitClose (/www/bailey/node_modules/ws/lib/websocket.js:247:10)\n    at TLSSocket.socketOnClose (/www/bailey/node_modules/ws/lib/websocket.js:1102:15)\n    at TLSSocket.emit (node:events:539:35)\n    at node:net:709:12\n    at TCP.done (node:_tls_wrap:582:7)"
```

**Comment by mzayn** [comment]
> > here you go the setTimeout function is used just in case your internet was down so it tries to reconnect every 21 seconds instead of connecting aggressively
> > ```
> > if ((lastDisconnect.error as Boom)?.data?.code === "ENOTFOUND") {
> > 	setTimeout(function () {
> > 		controllerSocket(Controller)
> > 	}, 21000)
> > }
> > else {
> > 	controllerSocket(Controller)
> > }
> > ```
> 
> hi,
> 
> already use your code but, my Bot WA still DC
> 
> here the log node :
> 
> ```
> 2022-08-16T10:12:09: �[32mINFO�[39m [2022-08-16 10:12:08.416 +0800]: �[36mconnection errored�[39m
> 2022-08-16T10:12:09:     trace: "Error: Connection Terminated\n    at WebSocket.<anonymous> (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:351:30)\n    at WebSocket.emit (node:events:527:28)\n    at WebSocket.emitClose (/www/bailey/node_modules/ws/lib/websocket.js:247:10)\n    at TLSSocket.socketOnClose (/www/bailey/node_modules/ws/lib/websocket.js:1102:15)\n    at TLSSocket.emit (node:events:539:35)\n    at node:net:709:12\n    at TCP.done (node:_tls_wrap:582:7)"
> ```

i configure code like this 

```
    sock[token].ev.on('connection.update', async (update) => {
        const { connection, qr, lastDisconnect } = update
        if (connection === 'close') {
            // reconnect if not logged out
            if ((lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut) {
               
                if ((lastDisconnect.error)?.output?.payload?.message === 'Stream Errored (restart required)') {
                    delete qrcode[token]
                    connectToWhatsApp(token, io)
                    if (io != null) io.emit('message', { token: token, message: "Reconnecting" })
                } else if ((lastDisconnect.error)?.output?.payload?.message === 'QR refs attempts ended') {
                    delete qrcode[token]
                    if (io != null) io.emit('message', { token: token, message: lastDisconnect.error.output.payload.message, error: lastDisconnect.error.output.payload.error })
                }
            } else if ((lastDisconnect.error)?.output?.statusCode === 401) {
                setStatus(token, 'Disconnect')
                console.log('Connection closed. You are logged out.')
                if (io !== null) {
                    io.emit('message', { token, message: 'Connection closed. You are logged out.' })
                }
                clearConnection(token)
            }
            
           else if ((lastDisconnect.error)?.output?.statusCode === "ENOTFOUND") {
            	setTimeout(function () {
            		controllerSocket(Controller)
            	}, 21000)
            }
            else {
            	controllerSocket(Controller)
            }            
            
        }
```

**Comment by Alhar6i** [comment]
you still need to implement and define the main function **controllerSocket** I guess

**Comment by mzayn** [comment]
> **controllerSocket**

hmm need to configure in server.js where controller 

`var controller = require('./mycontroller');`

**Comment by undefined-60** [comment]
> Eu tenho uma biblioteca e também recebi esse problema, acho que é do whatsapp, ele fecha automaticamente a conexão com você porque ele pensa que você está "morto", para corrigir isso programei um envio automático de msg para meu outro número a cada 30mi

Será que emitir algum evento qualquer também funcione como um sinal para dizer que o usuário está ativo? Ou obrigatoriamente tem que ser uma mensagem?

**Comment by mzayn** [comment]
hi, today i got new type of connection closed. 428 ? 

possible to fix ? 

```
2022-08-19T07:17:31: Error: Connection Closed
2022-08-19T07:17:31:     at sendRawMessage (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:49:19)
2022-08-19T07:17:31:     at sendNode (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:60:16)
2022-08-19T07:17:31:     at query (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:124:15)
2022-08-19T07:17:31:     at groupQuery (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:12:55)
2022-08-19T07:17:31:     at groupMetadata (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/groups.js:22:30)
2022-08-19T07:17:31:     at /www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:274:47
2022-08-19T07:17:31:     at /www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:277:23
2022-08-19T07:17:31:     at async Object.transaction (/www/bailey/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:85:21)
2022-08-19T07:17:31:     at async relayMessage (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:264:9)
2022-08-19T07:17:31:     at async Object.sendMessage (/www/bailey/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:523:17) {
2022-08-19T07:17:31:   data: null,
2022-08-19T07:17:31:   isBoom: true,
2022-08-19T07:17:31:   isServer: false,
2022-08-19T07:17:31:   output: {
2022-08-19T07:17:31:     statusCode: 428,
2022-08-19T07:17:31:     payload: {
2022-08-19T07:17:31:       statusCode: 428,
2022-08-19T07:17:31:       error: 'Precondition Required',
2022-08-19T07:17:31:       message: 'Connection Closed'
2022-08-19T07:17:31:     },
2022-08-19T07:17:31:     headers: {}
2022-08-19T07:17:31:   }
2022-08-19T07:17:31: }
2022-08-19T07:17:31: [33mWARN[39m [2022-08-19 07:17:31.151 +0800]: [36murl generation failed[39m
2022-08-19T07:17:31:     trace: "FetchError: uri requested responds with a redirect, redirect mode is set to error: https://whatsapp.com/dl\n    at ClientRequest.<anonymous> (/www/bailey/node_modules/node-fetch/lib/index.js:1523:14)\n    at ClientRequest.emit (node:events:513:28)\n    at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)\n    at TLSSocket.socketOnData (node:_http_client:521:22)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)"
```

**Comment by prcode** [comment]
@atrikx Hi, can you share the python scrip with me - mencti @ gmail.com? thanks

**Comment by ibnumardini** [comment]
I have an error too, I have implemented to send a message to another number every 30 minutes, but I still have the error
