### ISSUE TITLE
[BUG] Double receive message with thumbnail

### ISSUE THREAD

**Issue by zennn08** [adiwajshing/Baileys#2031]
**Describe the bug**
This bug doesn't always happen.
This bug occurs when someone sends a message with a thumbnail and the message is receive 2x at the same time.
![image](https://user-images.githubusercontent.com/75623219/184320409-a429a417-0773-4a0d-be07-167ab2f1621c.png)

**To Reproduce**
1. Created a new connection
2. Send A messages with thumbnail

**Expected behavior**
Only receive one time

**Environment (please complete the following information):**
 - Is this on a server? `Yes`
 - What do your `connectOptions` look like? 
 ```ts
 {
        printQRInTerminal: false,
        auth: state,
        logger: P({ level: "silent" })
        getMessage: messageRetryHandler
}
 ```
 - Do you have multiple clients on the same IP? `Yes`
 - Are you using a proxy? `No`

**Comment by zennn08** [comment]
any solution?

**Comment by itmor** [comment]
I'm not much off topic, but how did you manage to display link thumbnails in the first place? They do not work for me, can you help, how do you send a message?

**Comment by zennn08** [comment]
.

**Comment by zennn08** [comment]
.

**Comment by zhinea** [comment]
any solutions?

**Comment by zennn08** [comment]
.

**Comment by undefined-60** [comment]
> .

Eu acho que sei qual o problema com essa mensagem dupla, na verdade ela não está duplicada, tem ids diferentes oque leva a crer que ao invés de enviar mensagem dupla ele recebeu duas mensagens iguais no messages.upsert

**Comment by undefined-60** [comment]
> > .
> 
> Eu acho que sei qual o problema com essa mensagem dupla, na verdade ela não está duplicada, tem ids diferentes oque leva a crer que ao invés de enviar mensagem dupla ele recebeu duas mensagens iguais no messages.upsert

Uma implementação simples acaba com este problema. Salve o id das mensagens recebidas em alguma variável etc... E sempre verifique se você já tem este id salvo, se tiver a mensagem veio duplicada, funcionou bem no meu caso. Não obtive mais esse problema.
