### ISSUE TITLE
User secret

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#2036]
Please add a feature to pass in some secret string so that the credentials generated in one environment cannot be used in another.

The secret for example can be stored in the .env variable.

When another person copies our code including the credential folder, they should not be able to authenticate using any other secret string.

**Comment by HUGEIT** [comment]
simply don't commit your credentials, the issue is on your end because sharing credentials is a very bad design choice

**Comment by aidulcandra** [comment]
> simply don't commit your credentials, the issue is on your end because sharing credentials is a very bad design choice

It's the environment that does not allow setting folders private. Well then I guess I have to move somewhere else.

**Comment by aidulcandra** [comment]
I have implemented my own auth state manager. This way I can make the credentials be saved in a database instead
#2040
