### ISSUE TITLE
[BUG] Always got error "closed connection, reason intentional"

### ISSUE THREAD

**Issue by anaphalis777** [adiwajshing/Baileys#204]
**Describe the bug**

**To Reproduce**
1. Generate qrcode
2. Fetch session connection
3. Load session file & Created a new connection
4. Got error "closed connection, reason intentional"

**Expected behavior**
Should got connected status

**Environment (please complete the following information):**
 - Is this on a server?  :x:
 - What do your `connectOptions` look like? 
{
        regenerateQRIntervalMs: 30_000,
        maxIdleTimeMs: 15_000,
        waitOnlyForLastMessage: false,
        waitForChats: false,
        maxRetries: 10,
        connectCooldownMs: 4000,
        phoneResponseTime: 10_000,
        alwaysUseTakeover: true
}

 - Do you have multiple clients on the same IP? :x:
 - Are you using a proxy?  :x:

**Additional context**
After load session files and connect, always got message "closed connection, reason intentional"

**Comment by adiwajshing** [comment]
I think there’s something up with your code. Can you show it please?

**Comment by anaphalis777** [comment]
hmm am sorry, i think i got race condition in my code :(
