### ISSUE TITLE
[BUG] Buttons Not Working Today

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#2045]
Today I tried to send the button but it didn't work, the button appears on my cellphone but in the recipient the button doesn't appear at all, I tried to run from the example the result is still the same

**Comment by as-shiddiq** [comment]
yes, I also get the same bug

**Comment by jayfortune03** [comment]
same also, with version 2.22.16.75 of WA on android

**Comment by BlackAmda** [comment]
Using 9f3b00d58d4f6b1527db42069acafff01123cbf8 commit will fix your button issue + list message except template button messages.

**Comment by Heknon** [comment]
> Using [9f3b00d](https://github.com/adiwajshing/Baileys/commit/9f3b00d58d4f6b1527db42069acafff01123cbf8) commit will fix your button issue + list message except template button messages.

You can also just set `viewOnce` to true

**Comment by makanSukros** [comment]
> Using [9f3b00d](https://github.com/adiwajshing/Baileys/commit/9f3b00d58d4f6b1527db42069acafff01123cbf8) commit will fix your button issue + list message except template button messages.

Worked with this
