### ISSUE TITLE
How to send base64 file in whatsup

### ISSUE THREAD

**Issue by Akash-Rathore** [adiwajshing/Baileys#2046]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by SamPandey001** [comment]
First of all this is not a bug

**Comment by AxeemHaider** [comment]
Convert base64 data into buffer and send media message

```js
const buffer = Buffer.from(base64Data, "base64");

await sock.sendMessage(
    id, 
    { 
        image: buffer, 
    }
)
```
