### ISSUE TITLE
[BUG] Cannot send document via stream

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#2047]
When I try to send a pdf by stream, the pdf cannot be opened. But when I send it by url, it opens.

Note: I already specify the mimetype to 'application/pdf'

**Comment by 100n0m3** [comment]
you must specify the content-type to application/pdf

**Comment by aidulcandra** [comment]
> you must specify the content-type to application/pdf

@100n0m3 I did for both cases.

**Comment by aidulcandra** [comment]
> you must specify the content-type to application/pdf

@100n0m3 Wait, you mean in the http request ?

**Comment by aidulcandra** [comment]
> you must specify the content-type to application/pdf

@100n0m3 I tried. It doesn't work, man..
