### ISSUE TITLE
[BUG] Template buttons with image not working

### ISSUE THREAD

**Issue by deri387** [adiwajshing/Baileys#2049]
Hi, help me to solve template buttons with thumbnail image, until now it's didn't working..
<img width="422" alt="Screen Shot 2022-08-17 at 07 56 37" src="https://user-images.githubusercontent.com/37043134/185010476-2ec5147e-2cd3-4f2e-b396-f4e90f950390.png">

What's wrong?

**Comment by LorranX** [comment]
no kind of template message is being received using baileys, in new versions of whatsapp the message just does not appear, apparently there is still no complete solution to the problem

**Comment by deri387** [comment]
i just found an solution, i will close this issue

**Comment by DineshValor** [comment]
> no kind of template message is being received using baileys, in new versions of whatsapp the message just does not appear, apparently there is still no complete solution to the problem

Is there any solution found?
