### ISSUE TITLE
Whatsapp do not recognize QR

### ISSUE THREAD

**Issue by aldoglez24** [adiwajshing/Baileys#205]
I can't login using the QR since the Whatsapp App does not recognize de QR code printed in the terminal

I'm using a Galaxy Note 10+ and a Mackbook Pro

I have tried reading the QR with the camera and no issues found

**Comment by adiwajshing** [comment]
Can you make sure that your terminal has a
black background?

**Comment by aldoglez24** [comment]
That fix my problem, thank you for your response
