### ISSUE TITLE
Invite Group Message for private contact in Create Group or Adding participants in groupParticipantsUpdate.

### ISSUE THREAD

**Issue by mustafamasvi** [adiwajshing/Baileys#2051]
There are couple of PR's/implementations, but they are either stale or closed.
@adiwajshing Please could you add the implementation.
Thanks

**Comment by mustafamasvi** [comment]
Any update ??

**Comment by BlackAmda** [comment]
??

**Comment by maleeqB** [comment]
Any update please?
