### ISSUE TITLE
How to get the same name as in the phone address book

### ISSUE THREAD

**Issue by huangzhong0406** [adiwajshing/Baileys#2052]
I would like to know how to get the same name as in the phone address book

**Comment by huangzhong0406** [comment]
I see this **[MD Contact names? #873](https://github.com/adiwajshing/Baileys/issues/873)**，but I don't have or get the name in the address book

**Comment by AxeemHaider** [comment]
Names are saved in `contacts` you can get it from there. 

First when you scan qr code might you will not get names in contact just a `notify` but after few moments you will get the address book names in contact. This is happen because it require to sync with mobile.

**Comment by huangzhong0406** [comment]
Hi my friend，I checked notify. It's not exactly the name of my address book

**Comment by AxeemHaider** [comment]
yes, notify is something else, isn't there a `name` property in your contact?

**Comment by huangzhong0406** [comment]
The notify and name fields  are not the name of the phone address book

**Comment by AxeemHaider** [comment]
Hmmm... `name` field should be. Are these same?
