### ISSUE TITLE
How to end connection 

### ISSUE THREAD

**Issue by Fernando-Lupa** [adiwajshing/Baileys#2056]
All right, guys? I wanted to know how close connection, I couldn't find it in the documentation. I use "sock.end", but "error: time out" appears after a while.

**Comment by Alhar6i** [comment]
simply call end()

`sock.end();`

you can pass a parameter to tell the reason
`sock.end('Normal close');`
More description found here https://github.com/adiwajshing/Baileys/issues/2030#issuecomment-1214294352

**Comment by atrikx** [comment]
try also end on your phone

**Comment by salman0ansari** [comment]
sock.ws.close()
sock.ev.removeAllListeners()

**Comment by Fernando-Lupa** [comment]
Thanks 🙏
