### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chandika7d** [adiwajshing/Baileys#2058]
0|app    | Error: Unsupported state or unable to authenticate data
0|app    |     at CipherBase.final (<anonymous>)
0|app    |     at Decipheriv.final (node:internal/crypto/cipher:193:29)
0|app    |     at aesDecryptGCM (/var/www/core/node_modules/@adiwajshing/baileys/lib/Utils/crypto.js:93:58)
0|app    |     at decrypt (/var/www/core/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:31:51)
0|app    |     at Object.decodeFrame (/var/www/core/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:127:36)
0|app    |     at WebSocket.onMessageRecieved (/var/www/core/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)
0|app    |     at WebSocket.emit (node:events:527:28)
0|app    |     at Receiver.receiverOnMessage (/var/www/core/node_modules/ws/lib/websocket.js:1178:20)
0|app    |     at Receiver.emit (node:events:527:28)
0|app    |     at Receiver.dataMessage (/var/www/core/node_modules/ws/lib/receiver.js:513:14)
0|app    | Error: Unsupported state or unable to authenticate data
0|app    |     at CipherBase.final (<anonymous>)
0|app    |     at Decipheriv.final (node:internal/crypto/cipher:193:29)
0|app    |     at aesDecryptGCM (/var/www/core/node_modules/@adiwajshing/baileys/lib/Utils/crypto.js:93:58)
0|app    |     at decrypt (/var/www/core/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:31:51)
0|app    |     at Object.decodeFrame (/var/www/core/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:127:36)
0|app    |     at WebSocket.onMessageRecieved (/var/www/core/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:196:15)
0|app    |     at WebSocket.emit (node:events:527:28)
0|app    |     at Receiver.receiverOnMessage (/var/www/core/node_modules/ws/lib/websocket.js:1178:20)
0|app    |     at Receiver.emit (node:events:527:28)
0|app    |     at Receiver.dataMessage (/var/www/core/node_modules/ws/lib/receiver.js:513:14)

**Comment by salykingleb** [comment]
+

**Comment by sultanlive** [comment]
+++
