### ISSUE TITLE
[BUG] Audio Playback Error

### ISSUE THREAD

**Issue by danielteodorodt** [adiwajshing/Baileys#206]
@adiwajshing  Hello, after modifications, the audio is sending with the seconds, but does not play on the cell phone, only on WhatsApp Web.

Even if it is, mp3, ogg, opus. I used your own updated repository with your audio "sonata.mp3" in the "Media" folder, so I believe that it is not a problem in my code, because I used yours.

**Comment by adiwajshing** [comment]
Code?

**Comment by danielteodorodt** [comment]
@adiwajshing your project that has a problem with the audio. I didn't program anything wrong. I thought it was a problem with my algorithms. The audio still has a problem.

**Comment by jhonyfrozen** [comment]
> @adiwajshing Hello, after modifications, the audio is sending with the seconds, but does not play on the cell phone, only on WhatsApp Web.
> 
> Even if it is, mp3, ogg, opus. I used your own updated repository with your audio "sonata.mp3" in the "Media" folder, so I believe that it is not a problem in my code, because I used yours.

Can you paste your code here?
You need to set Mimetype to mp4Audio too:
conn.sendMessage(chatId, buffer, MessageType.audio, { mimetype: Mimetype.mp4Audio, ptt: true })

**Comment by danielteodorodt** [comment]
@jhonyfrozen  I'm using his own example from the repository to upload.

Can you put it like you did here?

**Comment by adiwajshing** [comment]
@danielteodorodt Can you please just post the exact script you're using?

**Comment by danielteodorodt** [comment]
![image](https://user-images.githubusercontent.com/64978981/97439215-a690c080-1904-11eb-9f67-2b885be348bb.png)

I am using your own example.

Sending an .mp3 file, whatever.

And the audio does not play. It only shows the seconds.

**Comment by itacirgabral** [comment]
Hi @danielteodorodt, I've put some minimal code here:
https://github.com/itacirgabral/baileysissues206demo

It's working for me like this:
![print](https://user-images.githubusercontent.com/6052177/97477764-69d5c100-1926-11eb-85c0-bf7ac142073c.jpeg)

```javascript
const fs = require('fs')
const { WAConnection, MessageType, Mimetype } = require('@adiwajshing/baileys')

const someone = '554433221100@s.whatsapp.net'
const audio = fs.readFileSync(require('path').join(__dirname, 'audio.ogg'))
const options = {
  mimetype: Mimetype.ogg
}

;(async () => {
    const conn = new WAConnection() 

    await conn.connect()

    setTimeout(() => {
        console.log('bep')
        conn.sendMessage (someone, audio, MessageType.audio, options)
    }, 5012)
})()
```

The `audio.ogg` was recorded by whatapp. I'm only using opus container.

**Comment by danielteodorodt** [comment]
Hello, @itacirgabral  thank you for your help with the problem.

Another audio already recorded from whatsapp and try to send, yes it works.

The point is to send an audio file, be it .mp3, .ogg or .opus. As a file or as a "voice" it doesn't work.

Take an .mp3 file and try to upload it as an audio file.

If you can help me with that.

**Comment by danielteodorodt** [comment]
Muito obrigado. pela ajuda @itacirgabral
