### ISSUE TITLE
[BUG] make-in-memory-store

### ISSUE THREAD

**Issue by Ajay-o-s** [adiwajshing/Baileys#2063]
```
async function connectToWhatsApp() {
    const db = makeInMemoryStore({ })
    const { version, isLatest } = await fetchLatestBaileysVersion();
    const { state, saveState } = useSingleFileAuthState ('./Auth/auth.json');
    const Ammu = makeWASocket({ 
        auth: state, 
        logger: Pino({ level: "silent" }), 
        version: version,
        browser: ['KEERTHANA:bot', 'Safari','3.0'],
        syncFullHistory: true
    });
    if(fs.existsSync('./Auth/auth.json')) return db.readFromFile('./Auth/auth.json')
    if(fs.existsSync('./Auth/auth.json')) return setInterval(() => {db.writeToFile('./Auth/auth.json')}, 10000)
   // db.bind(Ammu.ev);
    Ammu.ev.on("creds.update", saveState);
    //Ammu.ev.on('chats.set', () => {console.log('got chats', db.chats.all())})
    //Ammu.ev.on('contacts.set', () => {console.log('got contacts', Object.values(store.contacts))})
    Ammu.ev.on("connection.update", async(up) => {require('./connection.update')(Ammu, up)});
    Ammu.ev.on("group-participants.update", async(gpu) => {require('./group-participants.update')(Ammu, ...gpu)});
    Ammu.ev.on("groups.update", async(gu) => {require('./groups.update')(Ammu, gu)});
    Ammu.ev.on("messages.upsert", async(mu) => {require('./message.upsert')(Ammu, mu)});
}
```

/workspaces/Ajay-o-s/App/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:220
        chats.upsert(...json.chats);
                                           ^

TypeError: json.chats is not iterable (cannot read property undefined)
    at fromJSON (/workspaces/Ajay-o-s/App/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:220:15)
    at Object.readFromFile (/workspaces/Ajay-o-s/App/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:347:17)
    at Object.connectToWhatsApp (/workspaces/Ajay-o-s/App/connection/Keerthana.js:23:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async KEERTHANA (/workspaces/Ajay-o-s/App/index.js:14:9)
Program node index.js exited with code 1

**Comment by souravkl11** [comment]
You are using the same auth state file for message store. Use another location for store

**Comment by Ajay-o-s** [comment]
❤💕
