### ISSUE TITLE
[Questions] How to remove specific event listener

### ISSUE THREAD

**Issue by anaphalis777** [adiwajshing/Baileys#207]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues :heavy_check_mark:
2. Read through the readme at least once :heavy_check_mark:
3. Search the docs for the feature you're looking for :heavy_check_mark:

**Just describe the feature/question**
Hello, can i remove all event or spesific event after run function connect?
So, i have problem with event qr, after calling connect function and success scan the qrcode, then am trying to call close function, but this session still generate new qrcode, and am trying with removeAllListeners() and assign connection variable with null value, but in my terminal still generate qrcode :disappointed:

**Comment by jhonyfrozen** [comment]
Hi!
So, i believe that your implementation is wrong.

Can you post your code here, how you manage your session?

**Comment by adiwajshing** [comment]
+1 please show your code

**Comment by anaphalis777** [comment]
sorry" am mistake in use call function, nvm am solved now bruhh
