### ISSUE TITLE
How to run qr code on vs code terminal and how into convert png formate. Then after scaning qr code how tk get session code. Please say any one step by step iam bigner🥺

### ISSUE THREAD

**Issue by HMser** [adiwajshing/Baileys#2076]

**Comment by kauanzito** [comment]
based on what i understand its not showing qr code right?
have you already installed qrcode-terminal?

**Comment by VanzGantengz** [comment]
```js
/* code by ivanz.xyz */


//common
const qrcode = require("qrcode")
const { writeFileSync } = require("fs")
//esm
import qrcode from "qrcode"
import { writeFileSync } from "fs"

//put in events connection.update
sock.ev.on("connection.update", async update => {
    console.log(update)
       var buffer = await qrcode.toBuffer(update.qr)
        setInterval(() => {
       writeFileSync("qr.png", buffer)
  }, 60000*3)
})

**Comment by SanzGanzs** [comment]
> ```js
> /* code by ivanz.xyz */
> 
> 
> //common
> const qrcode = require("qrcode")
> const { writeFileSync } = require("fs")
> //esm
> import qrcode from "qrcode"
> import { writeFileSync } from "fs"
> 
> //put in events connection.update
> sock.ev.on("connection.update", async update => {
>     console.log(update)
>        var buffer = await qrcode.toBuffer(update.qr)
>         setInterval(() => {
>        writeFileSync("qr.png", buffer)
>   }, 60000*3)
> })
> ```

🗿

**Comment by SKDRAGON1** [comment]
How to do code in watsapp Send?

**Comment by frmdeveloper** [comment]
Anda berasal dari negara apa ?
