### ISSUE TITLE
[BUG] button not visible

### ISSUE THREAD

**Issue by vikodk67** [adiwajshing/Baileys#2077]
why i bring up the button, it can't be seen. only appears on self

**Comment by salykingleb** [comment]
IOS?

**Comment by ernestoyoofi** [comment]
> why i bring up the button, it can't be seen. only appears on self

same dude, but can be seen on whatsapp version 2.22.15

**Comment by ernestoyoofi** [comment]
> IOS?

I'm on android

**Comment by salykingleb** [comment]
> > IOS?
> 
> I'm on android

On android, everything is easier - go to Baileys/src/Utils/messages.ts / and at the very bottom in 751 lines uncomment // || message.templateMessage, restart the system and everything will be ok

**Comment by salykingleb** [comment]
> > IOS?
> 
> Я на Android

It should be like this:
export const patchMessageForMdIfRequired = (message: proto.IMessage) => {
	const requiresPatch = !!(
		message.buttonsMessage
		 || message.templateMessage
		|| message.listMessage
	)
	if(requiresPatch) {
		message = {
			viewOnceMessage: {
				message: {
					messageContextInfo: generateContextInfo(),
					...message
				}
			}
		}
	}

	return message

**Comment by ernestoyoofi** [comment]
> > > IOS?
> > 
> > 
> > I'm on android
> 
> On android, everything is easier - go to Baileys/src/Utils/messages.ts / and at the very bottom in 751 lines uncomment // || message.templateMessage, restart the system and everything will be ok

it works, sometimes when pressing the button often force close, but it's okay still can run well, thanks you @salykingleb !

**Comment by exallhost** [comment]
No work in iOS.

**Comment by thiagomagamoc** [comment]
> > > IOS?
> > 
> > 
> > I'm on android
> 
> On android, everything is easier - go to Baileys/src/Utils/messages.ts / and at the very bottom in 751 lines uncomment // || message.templateMessage, restart the system and everything will be ok

This solution does not work on iOS.
Has anyone found a permanent solution?

**Comment by salykingleb** [comment]
> > > > IOS?
> > > 
> > > 
> > > Я на Android
> > 
> > 
> > На Android все проще - перейдите в Baileys/src/Utils/messages.ts / и в самом низу в 751 строке раскомментируйте // || message.templateMessage, перезапустите систему, и все будет в порядке
> 
> Это решение не работает на iOS.Кто-нибудь нашел постоянное решение?

There is a problem with the display on iOS as far as I know global. I see how the sms arrives on ios and immediately disappears - does anyone have any thoughts about what this problem is related to?

**Comment by andersling** [comment]
> > > > > IOS?
> > > > 
> > > > 
> > > > Я на Android
> > > 
> > > 
> > > На Android все проще - перейдите в Baileys/src/Utils/messages.ts / и в самом низу в 751 строке раскомментируйте // || message.templateMessage, перезапустите систему, и все будет в порядке
> > 
> > 
> > Это решение не работает на iOS.Кто-нибудь нашел постоянное решение?
> 
> There is a problem with the display on iOS as far as I know global. I see how the sms arrives on ios and immediately disappears - does anyone have any thoughts about what this problem is related to?

@salykingleb  we are trying on this issue that occurs on iOS ,but We don't have the bussiness API ,do you have it?

**Comment by salykingleb** [comment]
> > > > > > IOS?
> > > > > 
> > > > > 
> > > > > Я на Android
> > > > 
> > > > 
> > > > На Android все проще - перейдите в Baileys/src/Utils/messages.ts / и в самом низу в 751 строке раскомментируйте // || message.templateMessage, перезапустите систему, и все будет в порядке
> > > 
> > > 
> > > Это решение не работает на iOS.Кто-нибудь нашел постоянное решение?
> > 
> > 
> > There is a problem with the display on iOS as far as I know global. I see how the sms arrives on ios and immediately disappears - does anyone have any thoughts about what this problem is related to?
> 
> @salykingleb we are trying on this issue that occurs on iOS ,but We don't have the bussiness API ,do you have it?

I don't have a business IP, but I know that the buttons in iOS come from it because I recently received advertising from them myself

**Comment by salykingleb** [comment]
> > > > > > IOS?
> > > > > 
> > > > > 
> > > > > Я на Android
> > > > 
> > > > 
> > > > На Android все проще - перейдите в Baileys/src/Utils/messages.ts / и в самом низу в 751 строке раскомментируйте // || message.templateMessage, перезапустите систему, и все будет в порядке
> > > 
> > > 
> > > Это решение не работает на iOS.Кто-нибудь нашел постоянное решение?
> > 
> > 
> > There is a problem with the display on iOS as far as I know global. I see how the sms arrives on ios and immediately disappears - does anyone have any thoughts about what this problem is related to?
> 
> @salykingleb we are trying on this issue that occurs on iOS ,but We don't have the bussiness API ,do you have it?

We are also trying to solve this problem, but it is not very clear where to dig. We found a couple of oddities and that's all for now

**Comment by salykingleb** [comment]
> > > > > > > IOS?
> > > > > > 
> > > > > > 
> > > > > > Я на Android
> > > > > 
> > > > > 
> > > > > На Android все проще - перейдите в Baileys/src/Utils/messages.ts / и в самом низу в 751 строке раскомментируйте // || message.templateMessage, перезапустите систему, и все будет в порядке
> > > > 
> > > > 
> > > > Это решение не работает на iOS.Кто-нибудь нашел постоянное решение?
> > > 
> > > 
> > > There is a problem with the display on iOS as far as I know global. I see how the sms arrives on ios and immediately disappears - does anyone have any thoughts about what this problem is related to?
> > 
> > 
> > @salykingleb we are trying on this issue that occurs on iOS ,but We don't have the bussiness API ,do you have it?
> 
> We are also trying to solve this problem, but it is not very clear where to dig. We found a couple of oddities and that's all for now

We can join forces if you are interested, write in a telegram https://t.me/Premium_SMS_Messenger

**Comment by andersling** [comment]
> > > > > > > > IOS?
> > > > > > > 
> > > > > > > 
> > > > > > > Я на Android
> > > > > > 
> > > > > > 
> > > > > > На Android все проще - перейдите в Baileys/src/Utils/messages.ts / и в самом низу в 751 строке раскомментируйте // || message.templateMessage, перезапустите систему, и все будет в порядке
> > > > > 
> > > > > 
> > > > > Это решение не работает на iOS.Кто-нибудь нашел постоянное решение?
> > > > 
> > > > 
> > > > There is a problem with the display on iOS as far as I know global. I see how the sms arrives on ios and immediately disappears - does anyone have any thoughts about what this problem is related to?
> > > 
> > > 
> > > @salykingleb we are trying on this issue that occurs on iOS ,but We don't have the bussiness API ,do you have it?
> > 
> > 
> > We are also trying to solve this problem, but it is not very clear where to dig. We found a couple of oddities and that's all for now
> 
> We can join forces if you are interested, write in a telegram https://t.me/Premium_SMS_Messenger

Nice ,sir! Let's try to do it!  I try to join your TG now!
