### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CarlosTwT** [adiwajshing/Baileys#2087]
**the buttons do not come out **

Hello, I need help with the buttons in my Bot

I use the client conn.sendMessage  In commands like the menu and even using the latest version I can't see the buttons 

An example of how I have configured the buttons:

const buttons = [
           { buttonId: `.owner`,buttonText:{displayText: 'Owner'}, type : 1},
           { buttonId: `.ping`,buttonText:{displayText: 'Speed'}, type : 1}
           ]
        const buttonMessage = {
           image: {url: "https://telegra.ph/file/88d3843440331b5cd1970.jpg"},
           caption: menu,
           footer: "Bot aún en etapa de desarrollo",
           buttons: buttons,
           headerType: 1,
           withTag: true
         }
       conn.sendMessage(msg.from, buttonMessage, {quoted : msg})

**Comment by ricocrivelli** [comment]
duplicated from #2077 #2026 #2006 and #1985
