### ISSUE TITLE
[BUG] "Only admin can send message" notification problem when muting a group

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#2089]
**Describe the bug**
When I mute a group, someone receives a lot of "Only admin can send messages to this group" notification

**To Reproduce**
1. Invite the bot in a group
2. Mute the group

**Expected behavior**
Somebody sent me a screenshot of what happened. I don't see this in my phone,, though. Other people received this as well but the number varies. This one got the most notifications.
![IMG-20220824-WA0014.jpg](https://user-images.githubusercontent.com/84653497/186275744-184498e1-ad0f-49a7-9564-c68144f26075.jpg)

**Environment (please complete the following information):**
 - Is this on a server?
   Yes, running on Replit
 - What do your `connectOptions` look like? 
   ![20220824_061948.jpg](https://user-images.githubusercontent.com/84653497/186276248-c347cd55-f769-4cef-baac-d9408c38f829.jpg)
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**

**Comment by AzRyCb** [comment]
+1

**Comment by fadiinho** [comment]
Can you show the code that you used to mute?

**Comment by aidulcandra** [comment]
> Can you show the code that you used to mute?

No code for that. I mute the group manually.
