### ISSUE TITLE
Clear all group and private chat history

### ISSUE THREAD

**Issue by salsawij** [adiwajshing/Baileys#2090]
Is there any news regarding this feature? I've looked up in the issues section but no updates yet

**Comment by amiruldev20** [comment]
use chatModify

**Comment by salsawij** [comment]
> use chatModify

I've tried using this, but it didn't work. Only clearing one message, not all chat history

**Comment by fadiinho** [comment]
This will delete the entire chat:
```js
const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
await sock.chatModify({
  delete: true,
  lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
},
'123456@s.whatsapp.net')
```

**Comment by FERDIZ-afk** [comment]
> This will delete the entire chat:
> 
> ```js
> const lastMsgInChat = await getLastMessageInChat('123456@s.whatsapp.net') // implement this on your end
> await sock.chatModify({
>   delete: true,
>   lastMessages: [{ key: lastMsgInChat.key, messageTimestamp: lastMsgInChat.messageTimestamp }]
> },
> '123456@s.whatsapp.net')
> ```


how do i get the function getLastMessageInChat

**Comment by fadiinho** [comment]
> how do i get the function getLastMessageInChat

If you're using the store provided by Baileys you can use:
```ts
const lastMsg  = store.mostRecentMessage('123456@s.whatsapp.net');
```
Otherwise, you'll have to implement it by your own.

**Comment by salsawij** [comment]
> ```ts
> const lastMsg  = store.mostRecentMessage('123456@s.whatsapp.net');
> ```

```const lastMsg  = store.mostRecentMessage('123456@s.whatsapp.net');
await sock.chatModify({
  delete: true,
  lastMessages: [{ key: lastMsg.key, messageTimestamp: lastMsg.messageTimestamp }]
},
'123456@s.whatsapp.net')```

is it like this?

**Comment by FERDIZ-afk** [comment]
> > how do i get the function getLastMessageInChat
> 
> If you're using the store provided by Baileys you can use:
> 
> ```ts
> const lastMsg  = store.mostRecentMessage('123456@s.whatsapp.net');
> ```
> 
> Otherwise, you'll have to implement it by your own.

Thanks for your information

**Comment by fadiinho** [comment]
> is it like this?
Yep. I guess you can close this issue now

**Comment by salsawij** [comment]
> > is it like this?
> 
> Yep. I guess you can close this issue now

it says incomplete key, I'm-

**Comment by Ningoje** [comment]
> ```ts
> const lastMsg  = store.mostRecentMessage('123456@s.whatsapp.net');
> ```



> > > is it like this?
> > 
> > 
> > Yep. I guess you can close this issue now
> 
> it says incomplete key, I'm-

const lastMsg  = await store.mostRecentMessage('123456@s.whatsapp.net');
