### ISSUE TITLE
[BUG] Error after updating promises:288

### ISSUE THREAD

**Issue by salykingleb** [adiwajshing/Baileys#2095]
Good afternoon to all!
After upgrading to version 4.4.0, I started seeing a critical error very often: node: internal/process/promises: 288
causes an uncaught exception (error, true/* from promise*/);
            ^

[[Raw Promise: This error occurred either because of a call inside an asynchronous function without a catch block, or because of a rejection of a promise that was not processed using .catch(). The promise is rejected because of "1006".] {
code: ERROR 'UNHANDLED NEGATION_
}

My attempts to get rid of it were unsuccessful, .catch(err => console.error(error)) can't determine what the problem is. Previously, this was also observed, but extremely rarely

**Comment by Shubhamrawat5** [comment]
Hi did you find the issue and solution?
