### ISSUE TITLE
setOnPresenceUpdate doesnt work on new contact

### ISSUE THREAD

**Issue by metinkun** [adiwajshing/Baileys#21]
setOnPresenceUpdate does not trigs for new contacts(new contacts that i did not chat before on whatsapp) with empty chat. when i open whatsapp chat from phone , setOnPresenceUpdate  starts to send contacts presence but after i close empty chat screen on phone , setOnPresenceUpdate  stops sending presence. and this situation always repeats when i open and close new contacts empty chats on phone. 

`const oldContact = "90xxxxxxxxx@c.us";`
`const brandNewContact= "90yyyyyyyyy@c.us";`

`setInterval(async () => {`
` await client.requestPresenceUpdate(oldContact );`
` await client.requestPresenceUpdate(brandNewContact);`
`  }, 1000);`

` client.setOnPresenceUpdate((json) => {`
`  console.log(json);`
`});`

in this stuation oldcontacts presence info comes on every change. 
on the other hand brandnewcontacts presence info only comes when i opened empty chat window of brandnewcontacts from whatsapp mobile app.

**Comment by adiwajshing** [comment]
Yes it does not, it's a limitation by WhatsApp. You can query their presence though, if you're one of their contacts. However, If the person does not have you in their contacts, you can't query their presence either.

**Comment by adiwajshing** [comment]
Since this won’t be worked on, closing.
