### ISSUE TITLE
[BUG] Button msg & Lists msg not respond in group

### ISSUE THREAD

**Issue by thisfardi** [adiwajshing/Baileys#2100]
anyone help how to solve Button msg & Lists msg if click not respond in group?
i write manual work, if click button not work/button not respond
![image](https://user-images.githubusercontent.com/38723240/187024670-c33853e4-4e37-4830-84c4-c8c0fd636d11.png)

**Comment by FatihArridho** [comment]
Hadeh

**Comment by AzRyCb** [comment]
> Hadeh

Ada ada aja y bg

**Comment by KiZakiXD** [comment]
> > Hadeh
> 
> Ada ada aja y bg

versi brp emg ngab?

**Comment by thisfardi** [comment]
gmn jadi ngab solusinya ?

**Comment by Raf1401** [comment]
Are the button functions working normally for whoever is using it? Does it work for both Android and iOS?

**Comment by thisfardi** [comment]
> Are the button functions working normally for whoever is using it? Does it work for both Android and iOS?

true all work
but not to group

**Comment by Raf1401** [comment]
> > Are the button functions working normally for whoever is using it? Does it work for both Android and iOS?
> 
> true all work but not to group

Seriously?

Here the recipient does not receive on the device. Only on whatsapp web...
Neither Android nor iOS.
Can you confirm?

**Comment by allefrodrigo** [comment]
> 
Here too, i'm using android & ios and the buttons only appears only on whatsapp web

**Comment by thisfardi** [comment]
> > > Are the button functions working normally for whoever is using it? Does it work for both Android and iOS?
> > 
> > 
> > true all work but not to group
> 
> Seriously?
> 
> Here the recipient does not receive on the device. Only on whatsapp web... Neither Android nor iOS. Can you confirm?

true work on android and ios.
i just use this resources latest. but  Button msg & Lists msg if click not respond in group.
i write manual work, if click button not work/button not respond

**Comment by thisfardi** [comment]
u can try this
`New template buttons message json

{
"key": {
"remoteJid": "[917300073000@s.whatsapp.net](mailto:917300073000@s.whatsapp.net)",
"fromMe": false,
"id": "D56EB8F5D7880C8135"
},
"messageTimestamp": 1661843976,
"pushName": "917300073000",
"message": {
"templateMessage": {
"fourRowTemplate": {
"content": {
"namespace": "e17a8855_a6b6_0ead_996e_d4beb0076001|en",
"elementName": "cred2199_button",
"fallbackLg": "en",
"localizableParams": [
{
"default": "Γé╣100.00"
},
{
"default": "your XXX Bank"
},
{
"default": "XXXX-XXXX"
},
{
"default": "30-Aug-2022"
},
{
"default": "100"
},
{
"default": "D6PJQ8PJE4V"
},
{
"default": "within the next 14 minutes"
},
{
"default": "https://app.cred.club/k63y/transactiondetails"
}
],
"hydratedHsm": {
"hydratedTemplate": {}
}
},
"buttons": [
{
"urlButton": {
"url": {
"namespace": "e17a8855_a6b6_0ead_996e_d4beb0076001|en",
"elementName": "cred2199_button",
"fallbackLg": "en",
"localizableParams": [
{
"default": "k63y/7b4ff3b2"
}
],
"hydratedHsm": {
"hydratedTemplate": {}
}
}
},
"index": 0
}
]
},
"hydratedTemplate": {
"hydratedContentText": "Payment of Γé╣100.00 was received for your XXX Bank credit card XXXX-XXXX on 30-Aug-2022 and you have earned 100 CRED coins.\n\nYour order id is XXX. Payment will be credited to credit card account within the next 14 minutes.\n\nView transaction details here: https://app.cred.club/k63y/transactiondetails",
"hydratedButtons": [
{
"urlButton": {
"displayText": "Explore rewards",
"url": "https://app.cred.club/XXX"
}
}
],
"templateId": "52472492230XXXX"
}
},
"messageContextInfo": {
"deviceListMetadata": {
"recipientKeyHash": "pmWMhc1QYtOYXXXX",
"recipientTimestamp": "166184XXXX"
},
"deviceListMetadataVersion": 2
}
},
"verifiedBizName": "CRED"
}

Note: I replaced some text to xxx.`
