### ISSUE TITLE
[MD] Get events in messages

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2103]
How should I proceed to get the following events in the messages:

Sent
Received
Reading

**Comment by salykingleb** [comment]
+

**Comment by salykingleb** [comment]
+1

**Comment by salykingleb** [comment]
> ```js
> sock.ev.on('messages.update', (m) => {
>   // logic of your application...
>   for (var k in m) {
>     console.log(m[k]);
>   }
> });
> ```
> 
> ```json
> "status": 2 // sent
> "status": 3 // delivered
> "status": 4 // viewed
> ```

Cool!
