### ISSUE TITLE
[BUG] Failed to scan qrcode Stream Errored (restart required)

### ISSUE THREAD

**Issue by allanlisboa** [adiwajshing/Baileys#2111]
![Captura de Tela 2022-09-01 às 14 39 28](https://user-images.githubusercontent.com/37181884/187978096-8bad732e-6e7b-4d94-94f1-82f8accf3315.png)

My code : 
![Captura de Tela 2022-09-01 às 14 39 58](https://user-images.githubusercontent.com/37181884/187978189-afbd18e9-b029-4408-9b2a-9b0db55e15bb.png)

**Comment by joaocib** [comment]
same

**Comment by gabrieldiaspereira** [comment]
@allanlisboa Could you tell us how you solved the problem?

**Comment by JonhnyDev** [comment]
Has anyone managed to solve this problem?

**Comment by OMartinez-NeT** [comment]
+1

**Comment by yusufneeson** [comment]
Same. I still haven't found the solution

**Comment by zLucasKk** [comment]
Its probably your environment, your code is good to go and should restart by itself... That's strange 🤔, make sure you're using the latest version of everything, including your IDE.
