### ISSUE TITLE
How to convert qrcode to base64?

### ISSUE THREAD

**Issue by allanlisboa** [adiwajshing/Baileys#2113]
The connection update returns a string from the qr but it doesn't seem to be a base64 but it doesn't work when we try to view it in the browser

![Captura de Tela 2022-09-02 às 00 55 50](https://user-images.githubusercontent.com/37181884/188055972-9800972a-d84c-4083-be13-abc60b776821.png)

Output in browser: 
![Captura de Tela 2022-09-02 às 00 58 14](https://user-images.githubusercontent.com/37181884/188056199-c7068a74-7bfd-4b7c-ad67-8dd931dd4eab.png)

**Comment by allanlisboa** [comment]
![Captura de Tela 2022-09-02 às 00 57 31](https://user-images.githubusercontent.com/37181884/188056118-78cd40f8-2076-4d56-9caa-ffaba5c15c71.png)

**Comment by apicesistemas** [comment]
@allanlisboa @TanKucukhas 
I'm creating an api to contain several whatsapp bots and I need to retrieve the qrcode to write to a database to be sent to clients to read how do I retrieve the base64 of the qr property?
