### ISSUE TITLE
Deletion of chat by admin

### ISSUE THREAD

**Issue by henceutbeey** [adiwajshing/Baileys#2114]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**
hello bro, may I ask that bots can delete other people's chats as admins

**Comment by DwiRizqiH** [comment]
yes, just delete it like you delete it before

**Comment by officialdittaz** [comment]
Komtol

**Comment by henceutbeey** [comment]
ya, hapus saja seperti Anda menghapusnya sebelumnya

> Komtol

Lah ? Knpa si monyet ini

**Comment by AzRyCb** [comment]
> ya, hapus saja seperti Anda menghapusnya sebelumnya
> 
> > Komtol
> 
> Lah ? Knpa si monyet ini

Biasalah gabut

**Comment by henceutbeey** [comment]
> > ya, hapus saja seperti Anda menghapusnya sebelumnya
> > > Komtol
> > 
> > 
> > Lah ? Knpa si monyet ini
> 
> Biasalah gabut

itu gman bg, kan skrng ada yang baru, bisa delete pesan member itu gmna

**Comment by nadiadev7** [comment]
sock.sendMessage(jid, {
        delete: key
    })

**Comment by SanzGanzs** [comment]
> Komtol

🗿

**Comment by undefined-60** [comment]
> > sock.sendMessage(jid, { delete: key })
> 
> Não funciona,
> 
> por exemplo, grupo de administradores de bot, quero excluir as mensagens de outras pessoas por esse bot, porque agora os administradores do grupo podem excluir mensagens de membros

Consigo excluir a mensagem de outros participantes usando um bot
