### ISSUE TITLE
[BUG] image thumbnail not working

### ISSUE THREAD

**Issue by arthur-es** [adiwajshing/Baileys#2116]
**Describe the bug**
When I send a image, it always shows with a black background, like this:
![image](https://user-images.githubusercontent.com/37699234/188237201-110be8c3-7fe6-49a2-b1c1-c1676907213d.png)

**To Reproduce**
1. Send a image

**Expected behavior**
I expected to see a thumnail, and not a black background. 
Or, you auto-download the file.

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/37699234/188237344-f013537c-3a0c-4015-b9f1-f8e999ea1a64.png)

**Comment by ZeniT21** [comment]
When i send video, I have a some problem - video without preview on Android, in iphone video with preview.

**Comment by artmerlop** [comment]
Test

**Comment by artmerlop** [comment]
Not stale and not completed
