### ISSUE TITLE
[BUG] 408 Request Time-out && 500 Internal Server Error

### ISSUE THREAD

**Issue by hassanfuad96** [adiwajshing/Baileys#2118]
**Describe the bug**
 Error: Connection was lost
6|api  |     at Timeout.<anonymous> (/var/www/node_modules/@adiwajshing/baileys/lib/LegacySocket/socket.js:287:17)
6|api  |     at listOnTimeout (node:internal/timers:559:17)
6|api  |     at processTimers (node:internal/timers:502:7) {
6|api  |   data: null,
6|api  |   isBoom: true,
6|api  |   isServer: false,
6|api  |   output: {
6|api  |     statusCode: 408,
6|api  |     payload: {
6|api  |       statusCode: 408,
6|api  |       error: 'Request Time-out',
6|api  |       message: 'Connection was lost'
6|api  |     },
6|api  |     headers: {}
6|api  |   }
6|api  | }
6|api  | Error: Connection was lost
6|api  |     at Timeout.<anonymous> (/var/www/node_modules/@adiwajshing/baileys/lib/LegacySocket/socket.js:287:17)
6|api  |     at listOnTimeout (node:internal/timers:559:17)
6|api  |     at processTimers (node:internal/timers:502:7) {
6|api  |   data: null,
6|api  |   isBoom: true,
6|api  |   isServer: false,
6|api  |   output: {
6|api  |     statusCode: 408,
6|api  |     payload: {
6|api  |       statusCode: 408,
6|api  |       error: 'Request Time-out',
6|api  |       message: 'Connection was lost'
6|api  |     },
6|api  |     headers: {}
6|api  |   }
6|api  | }
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3178)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3180)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3181)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3177)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3179)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3182)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3183)
6|api  | (node:903580) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3184)
6|api  | 1006
6|api  | 1006
6|api  | 1006
6|api  | 1006
6|api  | 1006
6|api  | 1006
6|api  | 1006
6|api  | Error: bad-request
6|api  |     at assertNodeErrorFree (/var/www/node_modules/@adiwajshing/baileys/lib/WABinary/generic-utils.js:56:15)
6|api  |     at query (/var/www/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:127:48)
6|api  |     at runMicrotasks (<anonymous>)
6|api  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
6|api  |     at async Object.profilePictureUrl (/var/www/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:377:24)
6|api  |     at async getLocalProfilePic (/var/www/app.js:337:21)
6|api  |     at async /var/www/multi.js:263:23 {
6|api  |   data: 400,
6|api  |   isBoom: true,
6|api  |   isServer: true,
6|api  |   output: {
6|api  |     statusCode: 500,
6|api  |     payload: {
6|api  |       statusCode: 500,
6|api  |       error: 'Internal Server Error',
6|api  |       message: 'An internal server error occurred'
6|api  |     },
6|api  |     headers: {}
6|api  |   }
6|api  | }
6|api  | Error: Timed Out
6|api  |     at /var/www/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:157:32
6|api  |     at runMicrotasks (<anonymous>)
6|api  |     at runNextTicks (node:internal/process/task_queues:61:5)
6|api  |     at listOnTimeout (node:internal/timers:528:9)
6|api  |     at processTimers (node:internal/timers:502:7) {
6|api  |   data: {
6|api  |     stack: 'Error\n' +
6|api  |       '    at promiseTimeout (/var/www/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:152:19)\n' +
6|api  |       '    at waitForMessage (/var/www/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:100:61)\n' +
6|api  |       '    at query (/var/www/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:22)\n' +
6|api  |       '    at /var/www/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:28:38\n' +
6|api  |       '    at refreshMediaConn (/var/www/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:46:15)\n' +
6|api  |       '    at runMicrotasks (<anonymous>)\n' +
6|api  |       '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
6|api  |       '    at async Object.upload (/var/www/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:440:26)\n' +
6|api  |       '    at async

**To Reproduce**
1. Send a message

**Expected behavior**
Server is turn to bad 502 gateway, sometime loading to much

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? yes

**Comment by AzRyCb** [comment]
+1

**Comment by salykingleb** [comment]
+1

**Comment by SamPandey001** [comment]
+1

**Comment by alexdsgmoura** [comment]
+1

**Comment by deriknyvo** [comment]
i have same problem

**Comment by dsandrade** [comment]
+1

**Comment by xXDeonoXx** [comment]
+1
