### ISSUE TITLE
[MD] Pdf file preview not work 

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2126]
I am sending a pdf file but the preview is not generated.

![image](https://user-images.githubusercontent.com/10979090/188732941-2bfde06d-8d2e-4499-be57-43248c488d81.png)

How should I proceed to generate this view?

**Comment by thisfardi** [comment]
me too

**Comment by Francuchin** [comment]
same happens to me

**Comment by SafwanGanz** [comment]
> I am sending a pdf file but the preview is not generated.
> 
> ![image](https://user-images.githubusercontent.com/10979090/188732941-2bfde06d-8d2e-4499-be57-43248c488d81.png)
> 
> How should I proceed to generate this view?

Resize image to 360p

**Comment by nadiadev7** [comment]
use baileys [Amirul Dev](https://github.com/amiruldev20/Baileys) or [this package](https://npmjs.com/package/baileys)
