### ISSUE TITLE
[BUG] Missing conversations when extracting

### ISSUE THREAD

**Issue by tiagoandrepro** [adiwajshing/Baileys#213]
When using the sample code to extract WhatsApp conversations I realized that it does not extract all chat conversations, just a few. Is there any way to extract all conversations?

**Comment by adiwajshing** [comment]
See [here](https://github.com/adiwajshing/Baileys/blob/69da12c33c784893427a0b116c1c3f656f6fa43b/src/WAConnection/7.MessagesExtra.ts#L146)
