### ISSUE TITLE
[BUG] Send message to logged number

### ISSUE THREAD

**Issue by cornertotal** [adiwajshing/Baileys#2131]
**Describe the bug**
When I try to send a message to my jid, that is the same as number that run my bot, the message remains in pending status and it’s not delivered to my chat.

**To Reproduce**
Just send a message to your bot jid

**Expected behavior**
The expected behavior is that I can send message to my personal chat

**Comment by LorranX** [comment]
Everything looks like normal here
![Captura de tela 2022-09-08 115311](https://user-imag
![Screenshot_2022 09 08_11 51 21 547](https://user-images.githubusercontent.com/89737304/189155129-a3e29acd-c640-4e1c-87d6-16142269db90.png)
es.githubusercontent.com/89737304/189155086-c1ce0921-57fd-409e-bd59-a01776ca7478.png)

**Comment by cornertotal** [comment]
> Everything looks like normal here
> 
> ![Captura de tela 2022-09-08 115311](https://user-images.githubusercontent.com/89737304/189155802-61f80a10-c994-4fd4-942d-d324a052a8e0.png) ![Screenshot_2022 09 08_11 51 21 547](https://user-images.githubusercontent.com/89737304/189155811-0904c16d-c8e6-4431-bb07-a0118e3211c1.png)

I use Baileys with saved credentials from multi device qrcode. 
When I send a message from bot to itself, in my iPhone with whatsapp configured with the bot number I can’t see the sent message. 
Have you tried your code with this environment?

**Comment by LorranX** [comment]
Do u use MultiFileAuthState? in my tests, I had a considerable worsening in baileys performance, in some cases it seemed to be slower, and many of the messages sent from the connection, arrived at the receiver as "waiting for message", I just wouldn't have the iPhone to do other tests, but here it works fine

**Comment by cornertotal** [comment]
I think that the problem is whatsapp.
I tried to connect with whatsapp web to my numeber, send message to myself and I see only the sent message, not the received like your screenshot.
And if I open this chat from my smartphone I can’t see the sent message.

Can you test with your number please?
