### ISSUE TITLE
[BUG] Template Button Solution

### ISSUE THREAD

**Issue by Laxeder** [adiwajshing/Baileys#2132]
I found a possible solution for Template Buttons using hydratedTemplate:

![template-vs](https://user-images.githubusercontent.com/63991021/188924262-2e9fea36-ec36-4fff-a642-b652be1fc8f2.png)
Working perfectly on Android:

![template-wa](https://user-images.githubusercontent.com/63991021/188924336-2bb27ac1-9d1c-4bf4-af20-8f3e5fe26f03.png)

I had to use relayMessage because sendMessage doesn't handle hydratedTemplate type messages correctly. A viable solution is to better handle the message of type hydratedTemplate in sendMessage or convert templateMessage to hydratedTemplate

**Comment by salykingleb** [comment]
does not work in ios

**Comment by undefined-60** [comment]
> does not work in ios

Tentou mudar o viewOnceMessage tipo para o tipo mensagens temporárias? Eu mudei aqui, e está funcionando não sei se isso resolverá para dispositivos IOS

**Comment by Laxeder** [comment]
> does not work in ios

Hm... Did you find any solution for IOS? It definitely looks like TemplateButtons is disabled for IOS

**Comment by jeans0cotton** [comment]
> I found a possible solution for Template Buttons using hydratedTemplate:
> 
> ![template-vs](https://user-images.githubusercontent.com/63991021/188924262-2e9fea36-ec36-4fff-a642-b652be1fc8f2.png) Working perfectly on Android:
> 
> ![template-wa](https://user-images.githubusercontent.com/63991021/188924336-2bb27ac1-9d1c-4bf4-af20-8f3e5fe26f03.png)
> 
> I had to use relayMessage because sendMessage doesn't handle hydratedTemplate type messages correctly. A viable solution is to better handle the message of type hydratedTemplate in sendMessage or convert templateMessage to hydratedTemplate

Perfect!!..Thanks

**Comment by salykingleb** [comment]
> > does not work in ios
> 
> Hm... Did you find any solution for IOS? It definitely looks like TemplateButtons is disabled for IOS

All right

**Comment by salykingleb** [comment]
> > does not work in ios
> 
> Tentou mudar o viewOnceMessage tipo para o tipo mensagens temporárias? Eu mudei aqui, e está funcionando não sei se isso resolverá para dispositivos IOS

No mister

**Comment by undefined-60** [comment]
> > > does not work in ios
> > 
> > 
> > Tentou mudar o viewOnceMessage tipo para o tipo mensagens temporárias? Eu mudei aqui, e está funcionando não sei se isso resolverá para dispositivos IOS
> 
> No mister

Mais fato é que pelo menos em Android funciona

**Comment by makanSukros** [comment]
Button doesn't appear on IOS

**Comment by salsawij** [comment]
> I found a possible solution for Template Buttons using hydratedTemplate:
> 
> ![template-vs](https://user-images.githubusercontent.com/63991021/188924262-2e9fea36-ec36-4fff-a642-b652be1fc8f2.png) Working perfectly on Android:
> 
> ![template-wa](https://user-images.githubusercontent.com/63991021/188924336-2bb27ac1-9d1c-4bf4-af20-8f3e5fe26f03.png)
> 
> I had to use relayMessage because sendMessage doesn't handle hydratedTemplate type messages correctly. A viable solution is to better handle the message of type hydratedTemplate in sendMessage or convert templateMessage to hydratedTemplate

hello, how about list message?
