### ISSUE TITLE
[BUG] Single tick on Receiver side

### ISSUE THREAD

**Issue by xAuxin9** [adiwajshing/Baileys#2133]
Has anyone facing this issue of single tick on Whatsapp's receiver side.

**Comment by jeans0cotton** [comment]
Yes...Me Too..

**Comment by LorranX** [comment]
Everything normal here, have u used some Presence Update recently? Anyways try sock.sendPresenceUpdate('available') and see what happens

**Comment by tarikhagustia** [comment]
> Everything normal here, have u used some Presence Update recently? Anyways try sock.sendPresenceUpdate('available') and see what happens

@LorranX have you try sent to new and non contact number? this is happend to me when sending to non contact user

**Comment by hartadi** [comment]
> > Everything normal here, have u used some Presence Update recently? Anyways try sock.sendPresenceUpdate('available') and see what happens
> 
> @LorranX have you try sent to new and non contact number? this is happend to me when sending to non contact user

me too,
if the recipient reply, then all working fine,
message is sent (double tick)

for new (first) chat, the message is only one tick (waiting for message on receiver side)
