### ISSUE TITLE
Error: Timed Out[BUG]

### ISSUE THREAD

**Issue by GeovannyMB** [adiwajshing/Baileys#2135]
*when trying to perform the connection update the application gives this error after some time

Error: Timed Out
    at C:\src\Utils\generics.ts:150:5
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:499:9) {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (C:\src\\Utils\\generics.ts:144:16)\n' +
      '    at waitForMessage (C:\src\\Socket\\socket.ts:126:39)\n' +
      '    at query (C:\src\\Socket\\socket.ts:153:16)\n' +
      '    at sendPassiveIq (C:\src\\Socket\\socket.ts:385:3)\n' +
      '    at WebSocket.<anonymous> (C:\src\\Socket\\socket.ts:501:9)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

**Comment by salykingleb** [comment]
1

**Comment by salykingleb** [comment]
Changing **defaultQueryTimeoutMs: undefined,** did not bring results

**Comment by cassiano-guardianserver** [comment]
+1

**Comment by canove** [comment]
What do you mean by "perform connection update"?

**Comment by GeovannyMB** [comment]
> What do you mean by "perform connection update"?

automatically start or restart the connection update trigger event..
example: if a recipient number is incorrect then the connection update event will restart and Baileys will get back up and running

(sorry for my english)

**Comment by DionlenoPiata** [comment]
+1
