### ISSUE TITLE
Template Buttons Not Displaying on IOS

### ISSUE THREAD

**Issue by xAuxin9** [adiwajshing/Baileys#2136]
After installing the new update, the  buttons are not visible on IOS receiver side, What can be the possible solution?

**Comment by makanSukros** [comment]
+1

**Comment by allegrun** [comment]
+1

**Comment by kanha1995** [comment]
For me, whatsapp is crashing until I delete that message from non-ios device.

**Comment by xxirfanx** [comment]
+1

**Comment by xAuxin9** [comment]
I Checked in the discord server of the repo, the template buttons are disabled for IOS!
