### ISSUE TITLE
Logged out (401) every 15 days

### ISSUE THREAD

**Issue by Macarthurval** [adiwajshing/Baileys#2139]
My Baileys instances are being logged out from WhatsApp approximately every 15 days, having to log in again by scanning the QR.

Is anyone else having this problem? In WhatsApp Web sessions this does not happen.

Thanks, regards.

**Comment by Fonnte** [comment]
you should keep opening your whatsapp app once before 14 days, else you will be logged out on the 15th days

ref : https://faq.whatsapp.com/579413796526134/

**Comment by Macarthurval** [comment]
@Fonnte I thought it was a bug.

Thank you very much for the info, really appreciated!
