### ISSUE TITLE
[BUG] Connection lost after 2 segs and then 10 segs after

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#214]
**Describe the bug**
After the connections is created, two segs and is "lost" it will recover, but then, after 10 segs will be "lost" and recover, and so on

**To Reproduce**
1. Created a new connection
2. wait

**Expected behavior**
The connection would not be lost after 10 segs

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like?  nothing seted
 - Do you have multiple clients on the same IP? yes (happens locally too)
 - Are you using a proxy? no

**Additional context**

**Comment by algoz098** [comment]
After some dig, i found out the "startKeepAliveRequest" function on file 3.connect is the origin of the problem, i tried to increase the timeout to see if that helps, and did, but, that should not be necessary right?

Can i help with this in any way? This has been a pain for me for a while and i do not know hot to help. If so, please, just tell me.

thx

**Comment by adiwajshing** [comment]
There's probably something up with your network config. Can you put up a debug log?

**Comment by algoz098** [comment]
When i rollback a couple commits it works.

I cant right now i do not have it running anymore
