### ISSUE TITLE
[BUG] how to get the Baileys module to be installed 

### ISSUE THREAD

**Issue by FERDIZ-afk** [adiwajshing/Baileys#2140]
![Screenshot_2022-09-10-09-17-04-15_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/69185890/189465104-d36cf400-e629-4fa9-aea6-7905194a0eca.png)

Please help me 🙏🙏🙏🙏🙏🙏

**Comment by Kenzuya** [comment]
jangan install sharp bang, jadi tabrakan sama module baileysnya
