### ISSUE TITLE
[BUG] failure in decrypting message

### ISSUE THREAD

**Issue by jurajmatus** [adiwajshing/Baileys#2150]
**Describe the bug**
Sometimes the message fails to be decrypted and is then represented as an empty stub

**Related issues**
* #1590
* #1721 

**To Reproduce**
* I don't see any rule when it happens

**Expected behavior**
Message is decrypted or at least there is a method to retry decryption in case keys are updated later

**Environment (please complete the following information):**
 - Is this on a server? YES (node version 14)
 - What do your `connectOptions` look like?
```
{
    version,// fetchLatestBaileysVersion()
    logger: state.logger, // error level
    markOnlineOnConnect: false,
    auth: state.authState, // custom DynamoDB based implementation
    syncFullHistory: true,
    msgRetryCounterMap: state.msgRetryCounterMap,
    connectTimeoutMs: 5 * 60 * 1000,
    defaultQueryTimeoutMs: undefined,
    keepAliveIntervalMs: 10000,
    browser: Browsers.macOS('Desktop'),
  }
```
 - Do you have multiple clients on the same IP? NO
 - Are you using a proxy? NO

**Additional context**
A message like this is produced in `messages.upsert`:
```json
{
  "key": {
    "remoteJid": "xx-xx@g.us",
    "fromMe": true,
    "id": "xx",
    "participant": "xx@s.whatsapp.net"
  },
  "messageTimestamp": 1663009678,
  "pushName": "___",
  "status": 2,
  "messageStubType": 2,
  "messageStubParameters": [
    "No sender key for: xx-xx@g.us::xx::0"
  ]
}
```

**Comment by undefined-60** [comment]
Isso ocorre comigo também.

**Comment by jhenterprise** [comment]
To Reproduce:
Happen only on groups or statues message.upsert when trying to send a message through a real device. Through Whatsapp web working fine. (In my case)

**Comment by jurajmatus** [comment]
Still an issue

**Comment by lRafaelOliveira** [comment]
Tambem estou com o mesmo problema

**Comment by 1337-sys** [comment]
I still have the same problem.  https://github.com/tulir/whatsmeow/issues/251

**Comment by jurajmatus** [comment]
Still an issue

**Comment by jurajmatus** [comment]
Still an issue

**Comment by jurajmatus** [comment]
Still an issue

**Comment by textarea** [comment]
Still an issue

**Comment by jurajmatus** [comment]
Still an issue

**Comment by lauriolasw** [comment]
+1

**Comment by Waxaranai** [comment]
+1

**Comment by dnl4** [comment]
+1

**Comment by clairton** [comment]
+1

**Comment by marcusrfaust** [comment]
+1

Ainda é um problema.

**Comment by vidimeylan** [comment]
> To Reproduce: Happen only on groups or statues message.upsert when trying to send a message through a real device. Through Whatsapp web working fine. (In my case)

+1
me too

**Comment by helmarluiz** [comment]
+1
