### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by NicolasCaous** [adiwajshing/Baileys#2152]
Hey, @adiwajshing 

You don't know how many times this library has helped me in my personal life. I organize an NGO and have you made my life so much easier to get in touch with multiple people. :)

I just wanted to let you know that your library is doing good work. Thank you for your free work here!

Ps.: I promise to start contributing when I have more time to do so. But that is not possible today. 😄

**Comment by SafwanGanz** [comment]
😂
