### ISSUE TITLE
Poll message

### ISSUE THREAD

**Issue by salsawij** [adiwajshing/Baileys#2154]
I've seen someone doing this, but I don't know how to do it. Anyone got idea?

**Comment by undefined-60** [comment]
conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: "4" }, { optionName: "5" }] } }, {});

Isso funciona para min.

**Comment by salsawij** [comment]
> conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: "4" }, { optionName: "5" }] } }, {});
> 
> Isso funciona para min.

![image](https://user-images.githubusercontent.com/106524854/190150829-b7b3c3ec-d9e8-45b4-996d-2a1439af1161.png)
didn't work, it tells me to update whatsapp and crashes my phone (with bot number)

**Comment by undefined-60** [comment]
> > > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: " 4" }, { optionName: "5" }] } }, {}); 
> > > Isso funciona para min.
> > 
> > 
> > ![imagem](https://user-images.githubusercontent.com/106524854/190150829-b7b3c3ec-d9e8-45b4-996d-2a1439af1161.png) não funcionou, ele me diz para atualizar o whatsapp e trava meu whatsapp (com número do bot)
> 
> Se você usa Whatsapp desatualizado seria meio difícil de ver mesmo não é?

conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: "4" }, { optionName: "5" }], selectableOptionsCount: 1 } }, {});
tente este, aqui funcionou.

**Comment by undefined-60** [comment]
![Screenshot_2022-09-14-09-22-12-1](https://user-images.githubusercontent.com/108310586/190152722-22cd6e5c-446c-4339-9d62-91b76ffcc4d3.png)

**Comment by salsawij** [comment]
> > > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: " 4" }, { optionName: "5" }] } }, {});
> > > Isso funciona para min.
> > 
> > 
> > ![Image](https://user-images.githubusercontent.com/106524854/190150829-b7b3c3ec-d9e8-45b4-996d-2a1439af1161.png)did not work, it tells me to update whatsapp and crashes my whatsapp (with bot number)
> 
> If you use outdated Whatsapp it would be kind of hard to see, right?

ohh, alright. I'll try it out, thanks!

**Comment by salsawij** [comment]
@undefined-60, may I know what whatsapp version you are using?

**Comment by undefined-60** [comment]
> 

Estou usando Whatsapp Mod, com o Whatsapp da play store não é possível ver

**Comment by salsawij** [comment]
> > 
> 
> I am using Whatsapp Mod, with Whatsapp from play store it is not possible to see

I also use a modded version on my other phone, it still didn't show

**Comment by KaZenn-7** [comment]
> 



> > > > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: " 4" }, { optionName: "5" }] } }, {});
> > > > Isso funciona para min.
> > > 
> > > 
> > > ![imagem](https://user-images.githubusercontent.com/106524854/190150829-b7b3c3ec-d9e8-45b4-996d-2a1439af1161.png) não funcionou, ele me diz para atualizar o whatsapp e trava meu whatsapp (com número do bot)
> > 
> > 
> > Se você usa Whatsapp desatualizado seria meio difícil de ver mesmo não é?
> 
> conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: "4" }, { optionName: "5" }], selectableOptionsCount: 1 } }, {}); tente este, aqui funcionou.

@undefined-60 funcionou pra enviar a enquete, mas sabe se tem alguma opção para contabilizar? Estou usando whats beta e pra mim não aparece o voto dos outros, apenas o meu

**Comment by undefined-60** [comment]
> > 
> 
> > > > > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: " 4" }, { optionName: "5" }] } }, {});
> > > > > Isso funciona para min.
> > > > 
> > > > 
> > > > ![imagem](https://user-images.githubusercontent.com/106524854/190150829-b7b3c3ec-d9e8-45b4-996d-2a1439af1161.png) não funcionou, ele me diz para atualizar o whatsapp e trava meu whatsapp (com número do bot)
> > > 
> > > 
> > > Se você usa Whatsapp desatualizado seria meio difícil de ver mesmo não é?
> > 
> > 
> > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: "4" }, { optionName: "5" }], selectableOptionsCount: 1 } }, {}); tente este, aqui funcionou.
> 
> @undefined-60 funcionou pra enviar a enquete, mas sabe se tem alguma opção para contabilizar? Estou usando whats beta e pra mim não aparece o voto dos outros, apenas o meu

Eu acho que tem que gerar a mensagem antes e depois enviar com relay para sair uma coisa mais completa, qualquer coisa eu escrevo um comentario.

**Comment by KaZenn-7** [comment]
@undefined-60 pode me mostrar como fazer por favor?

**Comment by amiruldev20** [comment]
lol. your whatsapp not support

**Comment by FERDIZ-afk** [comment]
only visible in the WhatsApp mod app

**Comment by clicknetcafe** [comment]
> 

And beta

**Comment by nadiadev7** [comment]
close this issue. that's because send polls is currently only visible to wa beta and mods

**Comment by BlackAmda** [comment]
Update: WhatsApp Android 2.22.20.73 now support to vote poll messages.

**Comment by 239626** [comment]
> Update: WhatsApp Android 2.22.20.73 now support to vote poll messages.

latest v2.22.22.80 is not showing it

**Comment by KaZenn-7** [comment]
> > > 
> > 
> > > > > > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: " 4" }, { optionName: "5" }] } }, {});
> > > > > > Isso funciona para min.
> > > > > 
> > > > > 
> > > > > ![imagem](https://user-images.githubusercontent.com/106524854/190150829-b7b3c3ec-d9e8-45b4-996d-2a1439af1161.png) não funcionou, ele me diz para atualizar o whatsapp e trava meu whatsapp (com número do bot)
> > > > 
> > > > 
> > > > Se você usa Whatsapp desatualizado seria meio difícil de ver mesmo não é?
> > > 
> > > 
> > > conn.relayMessage(from, { pollCreationMessage: { name: "@adiwajshing/baileys", options: [{ optionName: "1" }, { optionName: "2" }, { optionName: "3" }, { optionName: "4" }, { optionName: "5" }], selectableOptionsCount: 1 } }, {}); tente este, aqui funcionou.
> > 
> > @undefined-60 funcionou pra enviar a enquete, mas sabe se tem alguma opção para contabilizar? Estou usando whats beta e pra mim não aparece o voto dos outros, apenas o meu
> 
> Eu acho que tem que gerar a mensagem antes e depois enviar com relay para sair uma coisa mais completa, qualquer coisa eu escrevo um comentario.

pode escrever o comentário? @undefined-60
