### ISSUE TITLE
Vue3 framework support

### ISSUE THREAD

**Issue by hartum** [adiwajshing/Baileys#2155]
Hi there
I just downloaded the repo, installed everything needed and ran the example......
.....it worked like a charm

But when I created my project in vue 3, and installed the library (from https://www.npmjs.com/package/@adiwajshing/baileys), the problems started.

Buffer not found -> I could get more technical here but I don't think it's worth it, )in short I'm missing a lot of things).

So, are there any plans to support the Vue3 framework?
can someone give me some indication to be able to use this fantastic code from Vue3?

**Comment by Manjit2003** [comment]
You cant use this in frontend

**Comment by hartum** [comment]
Oh I see, I completely misunderstood the concept.

Thanks for the answer!!
