### ISSUE TITLE
how to get function of groupInviteMessage

### ISSUE THREAD

**Issue by bennysolo** [adiwajshing/Baileys#2159]
How??? I Dont Know!
Please tell me

**Comment by KaZenn-7** [comment]
I'm stuck on this too.

I made this:

_var linkgc = await conn.groupInviteCode(from)
dest ='xxxxx@s.whatsapp.net'
const invit = generateWAMessageFromContent(dest, proto.Message.fromObject({
groupInviteMessage: {
groupJid: 'xxxxx@g.us',
inviteCode: linkgc,
inviteExpiration: "1663436013",
groupName: `${groupName}`,
caption: 'Get in'
}
}), { userJid: dest })
await conn.relayMessage(dest, invit.message, { messageId: invit.key.dest})_

but the inviteCode doesn't work, and IDK how to generate a valid one :/

**Comment by nadiadev7** [comment]
async value(jid, participant, inviteCode, inviteExpiration, groupName = 'unknown subject', caption = 'Invitation to join my WhatsApp group', jpegThumbnail, options = {}) {
const msg = proto.Message.fromObject({
groupInviteMessage: proto.GroupInviteMessage.fromObject({
inviteCode,
inviteExpiration: parseInt(inviteExpiration) || + new Date(new Date + (3 * 8600000)),
groupJid: jid,
groupName: (groupName ? groupName : await conn.getName(jid)) || null,
jpegThumbnail: Buffer.isBuffer(jpegThumbnail) ? jpegThumbnail.toString('base64') : null,
caption
})
})
const message = generateWAMessageFromContent(participant, msg, options)
await conn.relayMessage(participant, message.message, { messageId: message.key.id, additionalAttributes: { ...options } })
return message
}

**Comment by ferhacks** [comment]
> I'm stuck on this too.
> 
> I made this:
> 
> _var linkgc = await conn.groupInviteCode(from) dest ='[xxxxx@s.whatsapp.net](mailto:xxxxx@s.whatsapp.net)' const invit = generateWAMessageFromContent(dest, proto.Message.fromObject({ groupInviteMessage: { groupJid: '[xxxxx@g.us](mailto:xxxxx@g.us)', inviteCode: linkgc, inviteExpiration: "1663436013", groupName: `${groupName}`, caption: 'Get in' } }), { userJid: dest }) await conn.relayMessage(dest, invit.message, { messageId: invit.key.dest})_
> 
> but the inviteCode doesn't work, and IDK how to generate a valid one :/

a valid invitation code is generated when trying to add a person and that person has the option of being added to a group deactivated, you can extract the option to add from the baileys code, since that is where the valid code comes from, I don't know if I make myself understood

**Comment by KaZenn-7** [comment]
> > I'm stuck on this too.
> > 
> > I made this:
> > 
> > _var linkgc = await conn.groupInviteCode(from) dest ='[xxxxx@s.whatsapp.net](mailto:xxxxx@s.whatsapp.net)' const invit = generateWAMessageFromContent(dest, proto.Message.fromObject({ groupInviteMessage: { groupJid: '[xxxxx@g.us](mailto:xxxxx@g.us)', inviteCode: linkgc, inviteExpiration: "1663436013", groupName: `${groupName}`, caption: 'Get in' } }), { userJid: dest }) await conn.relayMessage(dest, invit.message, { messageId: invit.key.dest})_
> > 
> > but the inviteCode doesn't work, and IDK how to generate a valid one :/
> 
> a valid invitation code is generated when trying to add a person and that person has the option of being added to a group deactivated, you can extract the option to add from the baileys code, since that is where the valid code comes from, I don't know if I make myself understood

Hmm, ok I got it. I'll try, thx.
