### ISSUE TITLE
[BUG] Messages not triggering "message-new"event

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#216]
**Describe the bug**
The last commit sometimes do not trigger the 'message-new' event

**To Reproduce**
1. Created a new connection
2. receive some messages from some number

**Expected behavior**
would trigger the event every time a new message is received

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? the default
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? no

**Comment by adiwajshing** [comment]
It should always receive. Do you have some logs? Preferably on DEBUG level

**Comment by itacirgabral** [comment]
I can't reproduce it too.

I put it in a demo on gitpod: [
![Screenshot from 2020-11-03 12-52-21](https://user-images.githubusercontent.com/6052177/98016265-2242af80-1dd4-11eb-88c0-3a09e060ac11.png)
](https://gitpod.io/#https://github.com/itacirgabral/baileysissues216Reproduce)
[https://gitpod.io/#https://github.com/itacirgabral/baileysissues216Reproduce](https://gitpod.io/#https://github.com/itacirgabral/baileysissues216Reproduce)

**Comment by algoz098** [comment]
The problem is not happening for all and everytime. I had to rollback it, i will try to replicate again in dev env.

**Comment by adiwajshing** [comment]
If I could see a debug log, that would be great
