### ISSUE TITLE
[BUG] externalAdReply does not appear in text messages

### ISSUE THREAD

**Issue by SafwanGanz** [adiwajshing/Baileys#2161]
conn.sendMessage(m.chat, {text: 'hai', contextInfo: {"externalAdReply": {title: titlink, mediaType: 3, renderLargerThumbnail: false, showAdAttribution: true, body: deslink, thumbnail: image, sourceUrl: `${args[0]}`}}}, {quoted: m})

its not working

**Comment by amiruldev20** [comment]
use  [this baileys](https://github.com/amiruldev20/Baileys)

**Comment by IqbalzzX** [comment]
use relayMessage work

**Comment by nadiadev7** [comment]
use baileys [https://github.com/amiruldev20/Baileys](Amirul Dev)  or [https://npmjs.com/package/baileys](this package) its work

**Comment by SafwanGanz** [comment]
> use relayMessage work

Ok..

**Comment by SafwanGanz** [comment]
> use [this baileys](https://github.com/amiruldev20/Baileys)

Its baileys bro

**Comment by amiruldev20** [comment]
> > use [this baileys](https://github.com/amiruldev20/Baileys)
> 
> Its baileys bro

my baileys has been fixed about that bug

**Comment by amiruldev20** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/73012169/190886730-dc3938d9-f5fa-43eb-bfaf-609a57576b97.png)

**Comment by souravkl11** [comment]
> > > use [this baileys](https://github.com/amiruldev20/Baileys)
> > 
> > 
> > Its baileys bro
> 
> my baileys has been fixed about that bug

Why don't you make a fix pr on this repo? Make it!
