### ISSUE TITLE
[BUG] Template-Buttons are broken on IOS & Android.

### ISSUE THREAD

**Issue by Kuroosh** [adiwajshing/Baileys#2163]
**Describe the bug**

**To Reproduce**
1. Use this code : 
```ts
const groupHelpButtons = [
    { index: 1, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 🤍💙', url: 'https://chat.whatsapp.com/KCZMVKfwgUm31pclF30fw4' } },
    { index: 2, urlButton: { displayText: '🤍❤️ VenoX Dating 🤍❤️ ', url: 'https://chat.whatsapp.com/FO7JV5n5ksR5fAgBn99P6A' } },
    { index: 3, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 2 🤍💙', url: 'https://chat.whatsapp.com/Fzs9OjPeDlI81dtBKSMA2P' } },
    { index: 4, urlButton: { displayText: '🤍🌈 VenoX LGBTQ 🤍🌈', url: 'https://chat.whatsapp.com/J0UtFR0l61O3hgtguPXhzT' } },
    { index: 5, urlButton: { displayText: '🤍💦 VenoX Nudes 🤍💦', url: 'https://chat.whatsapp.com/BoGQCVRPTC1B5fxfND2PAX' } },
    { index: 6, urlButton: { displayText: '👮🏼‍♀️🗒️ VenoX Admin Apply 🗒️👮🏼‍♀️', url: 'https://chat.whatsapp.com/KCfW5oBbhC4Kv7g2ToGQil' } },
    { index: 7, urlButton: { displayText: '🚫⚠️ VenoX Unban Apply ⚠️🚫', url: 'https://chat.whatsapp.com/EdpufHmYGj0FdHmg5UdqIZ' } },
    { index: 8, urlButton: { displayText: '🧪👨🏼‍🔬 VenoX Test Bot 👨🏼‍🔬🧪', url: 'https://chat.whatsapp.com/CmvBnhy0RBdFk5y4BeQm2v' } },
]

```

**Expected behavior**
Should show Template Buttons on IOS & Android. 

**Environment (please complete the following information):**
 - Is this on a server? Yes.
 - What do your `connectOptions` look like? Good.
 - Do you have multiple clients on the same IP? Yes.
 - Are you using a proxy? No.

**Additional context**
It worked before.
Now its only visible on WA Web.
Normal Buttons working fine.
Button Sections working fine too.

Only Template Buttons with URL are broken ( newest WA Version on both plattforms ).

**Comment by undefined-60** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use this code :
> 
> ```ts
> const groupHelpButtons = [
>     { index: 1, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 🤍💙', url: 'https://chat.whatsapp.com/KCZMVKfwgUm31pclF30fw4' } },
>     { index: 2, urlButton: { displayText: '🤍❤️ VenoX Dating 🤍❤️ ', url: 'https://chat.whatsapp.com/FO7JV5n5ksR5fAgBn99P6A' } },
>     { index: 3, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 2 🤍💙', url: 'https://chat.whatsapp.com/Fzs9OjPeDlI81dtBKSMA2P' } },
>     { index: 4, urlButton: { displayText: '🤍🌈 VenoX LGBTQ 🤍🌈', url: 'https://chat.whatsapp.com/J0UtFR0l61O3hgtguPXhzT' } },
>     { index: 5, urlButton: { displayText: '🤍💦 VenoX Nudes 🤍💦', url: 'https://chat.whatsapp.com/BoGQCVRPTC1B5fxfND2PAX' } },
>     { index: 6, urlButton: { displayText: '👮🏼‍♀️🗒️ VenoX Admin Apply 🗒️👮🏼‍♀️', url: 'https://chat.whatsapp.com/KCfW5oBbhC4Kv7g2ToGQil' } },
>     { index: 7, urlButton: { displayText: '🚫⚠️ VenoX Unban Apply ⚠️🚫', url: 'https://chat.whatsapp.com/EdpufHmYGj0FdHmg5UdqIZ' } },
>     { index: 8, urlButton: { displayText: '🧪👨🏼‍🔬 VenoX Test Bot 👨🏼‍🔬🧪', url: 'https://chat.whatsapp.com/CmvBnhy0RBdFk5y4BeQm2v' } },
> ]
> ```
> 
> **Expected behavior** Should show Template Buttons on IOS & Android.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server? Yes.
> * What do your `connectOptions` look like? Good.
> * Do you have multiple clients on the same IP? Yes.
> * Are you using a proxy? No.
> 
> **Additional context** It worked before. Now its only visible on WA Web. Normal Buttons working fine. Button Sections working fine too.
> 
> Only Template Buttons with URL are broken ( newest WA Version on both plattforms ).

Acho que o máximo é 3 botões de url, call etc...

**Comment by Darker935** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Use this code :
> 
> ```ts
> const groupHelpButtons = [
>     { index: 1, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 🤍💙', url: 'https://chat.whatsapp.com/KCZMVKfwgUm31pclF30fw4' } },
>     { index: 2, urlButton: { displayText: '🤍❤️ VenoX Dating 🤍❤️ ', url: 'https://chat.whatsapp.com/FO7JV5n5ksR5fAgBn99P6A' } },
>     { index: 3, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 2 🤍💙', url: 'https://chat.whatsapp.com/Fzs9OjPeDlI81dtBKSMA2P' } },
>     { index: 4, urlButton: { displayText: '🤍🌈 VenoX LGBTQ 🤍🌈', url: 'https://chat.whatsapp.com/J0UtFR0l61O3hgtguPXhzT' } },
>     { index: 5, urlButton: { displayText: '🤍💦 VenoX Nudes 🤍💦', url: 'https://chat.whatsapp.com/BoGQCVRPTC1B5fxfND2PAX' } },
>     { index: 6, urlButton: { displayText: '👮🏼‍♀️🗒️ VenoX Admin Apply 🗒️👮🏼‍♀️', url: 'https://chat.whatsapp.com/KCfW5oBbhC4Kv7g2ToGQil' } },
>     { index: 7, urlButton: { displayText: '🚫⚠️ VenoX Unban Apply ⚠️🚫', url: 'https://chat.whatsapp.com/EdpufHmYGj0FdHmg5UdqIZ' } },
>     { index: 8, urlButton: { displayText: '🧪👨🏼‍🔬 VenoX Test Bot 👨🏼‍🔬🧪', url: 'https://chat.whatsapp.com/CmvBnhy0RBdFk5y4BeQm2v' } },
> ]
> ```
> 
> **Expected behavior** Should show Template Buttons on IOS & Android.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server? Yes.
> * What do your `connectOptions` look like? Good.
> * Do you have multiple clients on the same IP? Yes.
> * Are you using a proxy? No.
> 
> **Additional context** It worked before. Now its only visible on WA Web. Normal Buttons working fine. Button Sections working fine too.
> 
> Only Template Buttons with URL are broken ( newest WA Version on both plattforms ).

Only 2 url buttons are supported

**Comment by Inevitable-Dev** [comment]
> > > **Describe the bug** A clear and concise description of what the bug is.
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. Use this code :
> > > 
> > > ```ts
> > > const groupHelpButtons = [
> > >     { index: 1, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 🤍💙', url: 'https://chat.whatsapp.com/KCZMVKfwgUm31pclF30fw4' } },
> > >     { index: 2, urlButton: { displayText: '🤍❤️ VenoX Dating 🤍❤️ ', url: 'https://chat.whatsapp.com/FO7JV5n5ksR5fAgBn99P6A' } },
> > >     { index: 3, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 2 🤍💙', url: 'https://chat.whatsapp.com/Fzs9OjPeDlI81dtBKSMA2P' } },
> > >     { index: 4, urlButton: { displayText: '🤍🌈 VenoX LGBTQ 🤍🌈', url: 'https://chat.whatsapp.com/J0UtFR0l61O3hgtguPXhzT' } },
> > >     { index: 5, urlButton: { displayText: '🤍💦 VenoX Nudes 🤍💦', url: 'https://chat.whatsapp.com/BoGQCVRPTC1B5fxfND2PAX' } },
> > >     { index: 6, urlButton: { displayText: '👮🏼‍♀️🗒️ VenoX Admin Apply 🗒️👮🏼‍♀️', url: 'https://chat.whatsapp.com/KCfW5oBbhC4Kv7g2ToGQil' } },
> > >     { index: 7, urlButton: { displayText: '🚫⚠️ VenoX Unban Apply ⚠️🚫', url: 'https://chat.whatsapp.com/EdpufHmYGj0FdHmg5UdqIZ' } },
> > >     { index: 8, urlButton: { displayText: '🧪👨🏼‍🔬 VenoX Test Bot 👨🏼‍🔬🧪', url: 'https://chat.whatsapp.com/CmvBnhy0RBdFk5y4BeQm2v' } },
> > > ]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **Expected behavior** Should show Template Buttons on IOS & Android.
> > > **Environment (please complete the following information):**
> > > 
> > > * Is this on a server? Yes.
> > > * What do your `connectOptions` look like? Good.
> > > * Do you have multiple clients on the same IP? Yes.
> > > * Are you using a proxy? No.
> > > 
> > > **Additional context** It worked before. Now its only visible on WA Web. Normal Buttons working fine. Button Sections working fine too.
> > > Only Template Buttons with URL are broken ( newest WA Version on both plattforms ).
> > 
> > 
> > Only 2 url buttons are supported
> 
> no they are not wtf. it worked with 5 url buttons too before.

Yes, on IOS devices up to 5 buttons are visible and on Whatsapp Web they are practically infinite, on Android only 3, which is the default

**Comment by enoksaju** [comment]
> > > > **Describe the bug** A clear and concise description of what the bug is.
> > > > **To Reproduce** Steps to reproduce the behavior:
> > > > 
> > > > 1. Use this code :
> > > > 
> > > > ```ts
> > > > const groupHelpButtons = [
> > > >     { index: 1, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 🤍💙', url: 'https://chat.whatsapp.com/KCZMVKfwgUm31pclF30fw4' } },
> > > >     { index: 2, urlButton: { displayText: '🤍❤️ VenoX Dating 🤍❤️ ', url: 'https://chat.whatsapp.com/FO7JV5n5ksR5fAgBn99P6A' } },
> > > >     { index: 3, urlButton: { displayText: '🤍💙 VenoX Chill Gruppe 2 🤍💙', url: 'https://chat.whatsapp.com/Fzs9OjPeDlI81dtBKSMA2P' } },
> > > >     { index: 4, urlButton: { displayText: '🤍🌈 VenoX LGBTQ 🤍🌈', url: 'https://chat.whatsapp.com/J0UtFR0l61O3hgtguPXhzT' } },
> > > >     { index: 5, urlButton: { displayText: '🤍💦 VenoX Nudes 🤍💦', url: 'https://chat.whatsapp.com/BoGQCVRPTC1B5fxfND2PAX' } },
> > > >     { index: 6, urlButton: { displayText: '👮🏼‍♀️🗒️ VenoX Admin Apply 🗒️👮🏼‍♀️', url: 'https://chat.whatsapp.com/KCfW5oBbhC4Kv7g2ToGQil' } },
> > > >     { index: 7, urlButton: { displayText: '🚫⚠️ VenoX Unban Apply ⚠️🚫', url: 'https://chat.whatsapp.com/EdpufHmYGj0FdHmg5UdqIZ' } },
> > > >     { index: 8, urlButton: { displayText: '🧪👨🏼‍🔬 VenoX Test Bot 👨🏼‍🔬🧪', url: 'https://chat.whatsapp.com/CmvBnhy0RBdFk5y4BeQm2v' } },
> > > > ]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > **Expected behavior** Should show Template Buttons on IOS & Android.
> > > > **Environment (please complete the following information):**
> > > > 
> > > > * Is this on a server? Yes.
> > > > * What do your `connectOptions` look like? Good.
> > > > * Do you have multiple clients on the same IP? Yes.
> > > > * Are you using a proxy? No.
> > > > 
> > > > **Additional context** It worked before. Now its only visible on WA Web. Normal Buttons working fine. Button Sections working fine too.
> > > > Only Template Buttons with URL are broken ( newest WA Version on both plattforms ).
> > > 
> > > 
> > > Only 2 url buttons are supported
> > 
> > 
> > no they are not wtf. it worked with 5 url buttons too before.
> 
> Yes, on IOS devices up to 5 buttons are visible and on Whatsapp Web they are practically infinite, on Android only 3, which is the default






you have working templates on ios?
