### ISSUE TITLE
Add delete by admin feature please Example : This message was deleted by admin

### ISSUE THREAD

**Issue by dcode-denpa** [adiwajshing/Baileys#2164]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**

**Comment by zennn08** [comment]
https://github.com/adiwajshing/Baileys#deleting-messages

**Comment by dcode-denpa** [comment]
Thx bang aqul

**Comment by dcode-denpa** [comment]
> https://github.com/adiwajshing/Baileys#deleting-messages

Ada examplenya ga bang?

**Comment by AzRyCb** [comment]
> > https://github.com/adiwajshing/Baileys#deleting-messages
> 
> Ada examplenya ga bang?

Di sc aine

**Comment by zennn08** [comment]
> > https://github.com/adiwajshing/Baileys#deleting-messages
> 
> Ada examplenya ga bang?

seperti fitur #delete biasa, hanya perlu update baileys dan botnya admin

**Comment by zennn08** [comment]
:/

**Comment by amiruldev20** [comment]
readme.md

**Comment by amiruldev20** [comment]
help. if you ask, don't issue it, but on the discussion page or discord
