### ISSUE TITLE
[BUG] unknown level unhandled

### ISSUE THREAD

**Issue by itacirgabral** [adiwajshing/Baileys#217]
**Describe the bug**
The log level `unhandled` is no longer known.
> (node:51027) UnhandledPromiseRejectionWarning: Error: unknown level unhandled
    at Pino.setLevel (/home/itacirgabral/source/motte/node_modules/pino/lib/levels.js:90:42)
    at Pino.set level [as level] (/home/itacirgabral/source/motte/node_modules/pino/lib/proto.js:56:38)

**To Reproduce**
```javascript
const { WAConnection } = require('@adiwajshing/baileys')

;(async () => {
  const conn = new WAConnection()
  conn.logger.level = 'unhandled'
  await conn.connect()
})()
```
Version 3.2.2

**Expected behavior**
Logs everything that was not handled. The documentations define this behavior https://github.com/adiwajshing/Baileys#writing-custom-functionality

**Environment (please complete the following information):**
 - Is this on a server?
It's on my notebook
 - What do your `connectOptions` look like? 
It's the default + level unhandled
 - Do you have multiple clients on the same IP?
no
 - Are you using a proxy?
no

**Additional context**
Last Friday it was working.

 `debug` and `info` level does not throws

Could be interesting the logger be an injected dependency that could be replaced by us to bradcasts into another pubsub system.

**Comment by adiwajshing** [comment]
Yeah my bad, I forgot to update the readme. It's level = 'debug' now
