### ISSUE TITLE
Simple quick reply button error [BUG]

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#2173]
Now a simple button message don't work.
Only WhatsApp Web.
![image](https://user-images.githubusercontent.com/34457222/191262811-c27792d7-9aad-4762-b23d-16d99dc423d9.png)
```
const buttons = [
{buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
{buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
{buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
	]
	
	const buttonMessage = {
		text: "Hi it's button message",
		footer: 'Hello World',
		buttons: buttons,
		headerType: 1
	}
	
	const sendMsg = await sock.sendMessage(msg.key.remoteJid!, buttonMessage)
```
@adiwajshing

**Comment by ricocrivelli** [comment]
This way works on IOS but don't work on web

**Comment by enoksaju** [comment]
try remove footer

**Comment by ricocrivelli** [comment]
![image](https://user-images.githubusercontent.com/2865753/191366100-0974f1e7-9c3c-4eda-acf9-4ff81a0430da.png)
It returns an empty string... I'm away from my computer now to test on web.

**Comment by enoksaju** [comment]
try send this object

```
{
    "text": "Hi it's button message",

    "buttons": [
        {"buttonId": "id1", "buttonText": {"displayText": "Button 1"}},
        {"buttonId": "id2", "buttonText": {"displayText": "Button 2"}},
        {"buttonId": "id3", "buttonText": {"displayText": "Button 3"}}
    ]
}
```

**Comment by IanosJunior** [comment]
> try remove footer
> 
> ```
> const buttons = [
> {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
> {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
> {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
> 	]
> 	
> 	const buttonMessage = {
> 		text: "Hi it's button message",
> 		// footer: 'Hello World',
> 		buttons: buttons,
> 		headerType: 1
> 	}
> 	
> 	const sendMsg = await sock.sendMessage(msg.key.remoteJid!, buttonMessage)
> ```

Work fine!!!
What's happening? Before it worked with the footer.

**Comment by morganzysman** [comment]
I also have this issue removing footer works.
