### ISSUE TITLE
Fix adreply

### ISSUE THREAD

**Issue by SafwanGanz** [adiwajshing/Baileys#2174]
**pleas Fix adreply in text msg**

**Comment by A-d-i-t-h-y-a-n** [comment]
Oru proto update il, ath poyatha,
Ini nokanda,
Ath kittuilla 😂

**Comment by raselcomel** [comment]
Use versi "github:amiruldev20/baileys"

**Comment by amiruldev20** [comment]
gush spam issue yg sama. kalau dikasi solusi org tidak dipraktekan

**Comment by raselcomel** [comment]
Awikwok:v
