### ISSUE TITLE
[BUG] Connection Terminated

### ISSUE THREAD

**Issue by GeovannyMB** [adiwajshing/Baileys#2175]
* The error happens when the application is running for a long time. After some period of working, the connection closes and this message is displayed in the terminal:

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "1006".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

* The last time this error happened, the application ran normally for 12 hours straight, after which it lost the connection

**Comment by DionlenoPiata** [comment]
+1

**Comment by salykingleb** [comment]
+1

**Comment by salykingleb** [comment]
I'm also looking for a solution and I don't see it yet
