### ISSUE TITLE
ERRO AO ENVIAR BOTAO COM URL E CALL AJUDEM!!

### ISSUE THREAD

**Issue by guigavbs** [adiwajshing/Baileys#2176]
// botao url inicio
app.post('/zdg-urlbtn', [
      body('jid').notEmpty()
   ], async (req, res) => {
      const errors = validationResult(req).formatWith(({
      msg
      }) => {
      return msg;
      });
      if (!errors.isEmpty()) {
      return res.status(422).json({
         status: false,
         message: errors.mapped()
		 
		 
      });
	  
      }
	  
	  

        const templateButtons = [
    {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
    {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
    {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]
   

      const jid = req.body.jid;
      const title = req.body.title;
	  const caption = req.body.caption;
      const footer = req.body.footer;
	  const description = req.body.description;
	  const sendMsg = await sock.sendMessage(id, templateMessage)
	  
      const ZDGLayoutPost = {
          image: {
                  url: './assets/card.jpg',
               },
		  
		  templateButtons: templateButtons
          
        
		 
      }

         ZDGsock.sendMessage(jid, ZDGLayoutPost).then(response => {
            res.status(200).json({
               status: true,
               response: response
            });
            }).catch(err => {
            res.status(500).json({
               status: false,
               response: err
            });
         });
   });
// botao url fim

AO ENVIAR O POST, ELE ENVIA PARA O MESMO NUMERO DE SAÍDA PODE AJUDAR?

**Comment by gerenciadores** [comment]
Not working
