### ISSUE TITLE
 ERROR SENDING BUTTON WITH URL AND CALLING HELP!! to disturb

### ISSUE THREAD

**Issue by guigavbs** [adiwajshing/Baileys#2177]
WHEN SENDING THE POST, IT SENDS TO THE SAME OUTPUT NUMBER CAN IT HELP?

SEGUE O CODIGO ABAIXO
FOLLOW THE CODE BELOW!!

// btn url

app.post('/zdg-urlbtn', [
      body('jid').notEmpty()
   ], async (req, res) => {
      const errors = validationResult(req).formatWith(({
      msg
      }) => {
      return msg;
      });
      if (!errors.isEmpty()) {
      return res.status(422).json({
         status: false,
         message: errors.mapped()
		 
		 
      });
	  
      }
	  
	  

        const templateButtons = [
    {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
    {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
    {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]
   

      const jid = req.body.jid;
      const title = req.body.title;
	  const caption = req.body.caption;
      const footer = req.body.footer;
	  const description = req.body.description;
	  const sendMsg = await sock.sendMessage(id, templateMessage)
	  
      const ZDGLayoutPost = {
          image: {
                  url: './assets/card.jpg',
               },
		  
		  templateButtons: templateButtons
          
        
		 
      }

         ZDGsock.sendMessage(jid, ZDGLayoutPost).then(response => {
            res.status(200).json({
               status: true,
               response: response
            });
            }).catch(err => {
            res.status(500).json({
               status: false,
               response: err
            });
         });
   });
// btnurl fim

**Comment by randiramli** [comment]
have you found a solution?, I've also been like that since WhatsApp update

**Comment by guigavbs** [comment]
I'm still not waiting to see if someone comments!

**Comment by FERDIZ-afk** [comment]
> WHEN SENDING THE POST, IT SENDS TO THE SAME OUTPUT NUMBER CAN IT HELP?
> 
> SEGUE O CODIGO ABAIXO FOLLOW THE CODE BELOW!!
> 
> // btn url
> 
> app.post('/zdg-urlbtn', [ body('jid').notEmpty() ], async (req, res) => { const errors = validationResult(req).formatWith(({ msg }) => { return msg; }); if (!errors.isEmpty()) { return res.status(422).json({ status: false, message: errors.mapped()
> 
> ```
>   });
>   
>   }
>   
>   
> 
>     const templateButtons = [
> {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
> {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
> {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
> ```
> 
> ]
> 
> ```
>   const jid = req.body.jid;
>   const title = req.body.title;
>   const caption = req.body.caption;
>   const footer = req.body.footer;
>   const description = req.body.description;
>   const sendMsg = await sock.sendMessage(id, templateMessage)
>   
>   const ZDGLayoutPost = {
>       image: {
>               url: './assets/card.jpg',
>            },
> 	  
> 	  templateButtons: templateButtons
>       
>     
> 	 
>   }
> 
>      ZDGsock.sendMessage(jid, ZDGLayoutPost).then(response => {
>         res.status(200).json({
>            status: true,
>            response: response
>         });
>         }).catch(err => {
>         res.status(500).json({
>            status: false,
>            response: err
>         });
>      });
> ```
> 
> }); // btnurl fim



Maybe this can help 



app.post('/zdg-urlbtn', [
body('jid').notEmpty()
], async (req, res) => {
const errors = validationResult(req).formatWith(({
msg
}) => {
return msg;
});
if (!errors.isEmpty()) {
return res.status(422).json({
status: false,
message: errors.mapped()

  });
  
  }
  
  

    const templateButtons = [
{index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
{index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
{index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

  const jid = req.body.jid;
  const title = req.body.title;
  const caption = req.body.caption;
  const footer = req.body.footer;
  const description = req.body.description;
  const sendMsg = await sock.sendMessage(id, templateMessage)
  
  const ZDGLayoutPost = {
      image: fs.readFileSync('./assets/card.jpg'), // if it's an image file, you can use fs if the image is from the url then use { url : "http://yegeheh.jpg" }
	  	footer: `helo world`,
	  templateButtons: templateButtons
      
    
	 
  }

     ZDGsock.sendMessage(jid, ZDGLayoutPost).then(response => {
        res.status(200).json({
           status: true,
           response: response
        });
        }).catch(err => {
        res.status(500).json({
           status: false,
           response: err
        });
     });
});

**Comment by FERDIZ-afk** [comment]
@guigavbs

**Comment by mohamad-supangat** [comment]
i has some error maybe haha 🤣🤣🤣🤣

**Comment by FERDIZ-afk** [comment]
> saya memiliki beberapa kesalahan mungkin haha🤣🤣🤣🤣

😂😂 Looks like you still don't understand about using functions, improve your learning, friends.
