### ISSUE TITLE
[MD] New example.ts error in node js

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2180]
I'm having an error with the ' makeCacheableSignalKeyStore' function, I'm following the model of [example.ts](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts)

![image](https://user-images.githubusercontent.com/10979090/191611383-c2823399-6c3d-4930-ab0c-c211fc2296bd.png)

![image](https://user-images.githubusercontent.com/10979090/191611180-ba8dd1f2-a93f-45f9-a751-8600e1348824.png)

![image](https://user-images.githubusercontent.com/10979090/191611272-4e4ef1c7-a32b-47e2-9660-3f9b04ea9da9.png)

But in node JS, would anyone have this new example in js?

**Comment by ibnusyawall** [comment]
please update your Baileys module to latest version

**Comment by AlanMartines** [comment]
Okay, I'll update and test.

**Comment by AlanMartines** [comment]
It worked, thank you.
