### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bigbdigital** [adiwajshing/Baileys#2181]
useSingleFileAuthState is not funcition.

Please not remove this function in stable version

**Comment by zennn08** [comment]
it's not bug
useSingleFileAuthState has been remove in last [commit](https://github.com/adiwajshing/Baileys/commit/5aaefa94d6dda04da68e8394ac4b2c858d19ae18)

You can use `useMultiFileAuthState`

**Comment by AyGemuy** [comment]
how to convert useSingleFileAuthState to useMultiFileAuthState
using simple method

**Comment by undefined-60** [comment]
> useSingleFileAuthState não é função.
> 
> Por favor, não remova esta função na versão estável

Use uma versão mais antiga que tenha a função ou use a nova
