### ISSUE TITLE
How to close Qr code ?

### ISSUE THREAD

**Issue by adinyahya** [adiwajshing/Baileys#2183]
hello guys, how to stop qr code, i have looping qr code

**Comment by DwiRizqiH** [comment]
client.end()
or
client.ws.close()

**and this is not BUG**

**Comment by alatwa** [comment]
Use this function
`client.logout().then(()=>{
  console.log('ok')
})`

**Comment by AlanMartines** [comment]
> Use this function `client.logout().then(()=>{ console.log('ok') })`

Is not working #2207

**Comment by AlanMartines** [comment]
> client.ws.close()

client.ws.close() it works for me.
