### ISSUE TITLE
[BUG] risk of app crash: deleting messages from other group members causes crash

### ISSUE THREAD

**Issue by erickythierry** [adiwajshing/Baileys#2189]
**Describe the bug**
I tried to use the function to delete messages from other people in the group but it didn't work

the bot being the admin of the group, when trying to delete any message from any user, ends up running some bug that causes all (or almost all) of the participants' apps to crash

in my tests I was unable to open my app for almost 2 hours after my bot (in another number) tried to delete a message from me in the group

**Comment by zLucasKk** [comment]
Same issue with me...
