### ISSUE TITLE
empty contacts if not waitForChats

### ISSUE THREAD

**Issue by itacirgabral** [adiwajshing/Baileys#219]
Hi 

The `WAConnection` have the contacts property:
https://adiwajshing.github.io/Baileys/classes/_src_waconnection_0_base_.waconnection.html#contacts

There is an example of its uses:
https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#L37

But if you setup like that the contacts aren't lazy populated:
```javascript
conn.connectOptions.waitForChats = false
```

Maybe it's the cause of https://github.com/adiwajshing/Baileys/issues/126

**Comment by itacirgabral** [comment]
I made a demo:
https://gitpod.io/#https://github.com/itacirgabral/baileysissues219

https://adiwajshing.github.io/Baileys/classes/_src_waconnection_3_connect_.waconnection.html#receivechatsandcontacts
Is that method enough to populate contacts?

**Comment by adiwajshing** [comment]
This isn't exactly supported. However, you can accommodate for this pretty easily using:
``` js
this.once('CB:response,type:contacts', json => {
  // json[2] is the array of contacts
  json[2].forEach(([type, contact]: ['user', WAContact]) => {
    console.log (`contact: ${contact}`)
  })
})
conn.connectOptions.waitForChats = false
await conn.connect()
```
