### ISSUE TITLE
Template message sending issue.

### ISSUE THREAD

**Issue by sachindadhaniya** [adiwajshing/Baileys#2199]
When template message sending it's send to sender number instead of recipient number.

**Comment by LorranX** [comment]
Visual...

**Comment by FERDIZ-afk** [comment]
> Saat mengirim pesan template, itu dikirim ke nomor pengirim, bukan nomor penerima.

you are using android or ios device

**Comment by sachindadhaniya** [comment]
Android device

**Comment by FERDIZ-afk** [comment]
> Android device

It's like that on Android, because it's said that people using iOS devices are visible, but on Android it's visible

**Comment by FERDIZ-afk** [comment]
Try checking this comment https://github.com/adiwajshing/Baileys/issues/2006#issuecomment-1208769408

**Comment by sachindadhaniya** [comment]
In my case all functions work but when I send template message it's automatically send to sender number.

**Comment by SamPandey001** [comment]
> In my case all functions work but when I send template message it's automatically send to sender number. So there is some bug i think...

Well,try defining target correctly.
I never faced such issues.

**Comment by hassanfuad96** [comment]
> In my case all functions work but when I send template message it's automatically send to sender number. So there is some bug i think...

This happen only on android, the receiver is gettng the message. here are no issue. Btw, the template for url & call is not available to be seen in whatsapp app latest version.

**Comment by Enoch240824** [comment]
Please what version are you using

**Comment by sachindadhaniya** [comment]
i am a beta tester. with latest version daily update.
