### ISSUE TITLE
Missing audio type on MessageType

### ISSUE THREAD

**Issue by brunon80** [adiwajshing/Baileys#22]
Hey! I found a problem while sending audio, there is no `audio` type
`WhatsAppWeb.MessageType.audio` is `undefined`

Looking on your code I found this:
```javascript
// WhatsAppWeb.js line 25
/** 
 * set of message types that are supported by the library
	 */
	static MessageType = {
		text: "conversation",
		image: "imageMessage",
		video: "videoMessage",
		sticker: "stickerMessage",
		document: "documentMessage",
		extendedText: "extendedTextMessage"
        }
```

there is no `audio` key on `MessageType`, to by pass this I just passed `audioMessage` when sending a audio file.

**Comment by adiwajshing** [comment]
Must've slipped by me. I'll add it in.

**Comment by adiwajshing** [comment]
Fixed in the latest commit.
