### ISSUE TITLE
conn.isOnWhatsApp() more complete

### ISSUE THREAD

**Issue by barkerpedro** [adiwajshing/Baileys#220]
Hello, would there be any way to use `conn.isOnWhatsApp('551198765432@s.whatsapp.net')` and it will return a more complete JSON?

For example, in another lib that I used, when making `conn.checkNumber('5511998765432@c.us')` it returned:

```json
{
   "exists": true,
   "correctJid": "551198765432@c.us"
}

```
I removed the "9" more than I had in the number.

**Comment by GodCode** [comment]
It would be more easy if you could specify the name of the lib which you have been using...

**Comment by adiwajshing** [comment]
I'm not sure why one would want this

**Comment by barkerpedro** [comment]
2 Examples of numbers here in my region:
1) 55 11 9 1234-5678
2) 55 11 1234-5678

When I use conn.isOnWhatsapp, it informs that the 2 are true, but what works for Whatsapp is the "1" only.
In open-wa / wa-automate-nodejs he used the search in 2 numbers and he returned that only "1" was the correct one.

**Comment by itacirgabral** [comment]
E ai @barkerpedro, beleza mano?!?!!

I have some friends saved without the prefix 9. When a message is sent to the correct number with the prefix 9 a new contact is created and the message wont go to my old prefixless contact. So I use the `conn.contacts` numbers only.

Restrict the destination to knowed contacts will help you to not be set as spammer.

```javascript
const knowedNumbers = Object.keys(conn.contacts).map(jid => jid.slice(0, jid.indexOf('@')))
if(!!knowedNumbers.find(el => el === '5511988776655')) {
  // (...)
}
```

**Comment by barkerpedro** [comment]
It is because we use a system that receives calls by telephone, goes through a PABX and in this case comes with "9". We return messages to the number you called via Whatsapp, however some customers have Whatsapp with "9" and others do not have "9".

It is sad to say that, but I believe that I will have to return to the other Lib, just because of this functionality.

**Comment by barkerpedro** [comment]
> E ai @barkerpedro, beleza mano?!?!!
> 
> I have some friends saved without the prefix 9. When a message is sent to the correct number with the prefix 9 a new contact is created and the message wont go to my old prefixless contact. So I use the `conn.contacts` numbers only.
> 
> Restrict the destination to knowed contacts will help you to not be set as spammer.
> 
> ```js
> const knowedNumbers = Object.keys(conn.contacts).map(jid => jid.slice(0, jid.indexOf('@')))
> if(!!knowedNumbers.find(el => el === '5511988776655')) {
>   // (...)
> }
> ```

Would you have any discord to clear up any doubts with you?

**Comment by Manjit2003** [comment]
https://discord.gg/7FYURJyqng

**Comment by itacirgabral** [comment]
> Would you have any discord to clear up any doubts with you?

Opa, é itacirgabral em tudo.

I'm just enter the @Manjit2003's  server, see you.

**Comment by adiwajshing** [comment]
@barkerpedro I just inspected the code to determine whether its possible to return what you're asking for, it is. I'll send over a commit in a while -- you can check it out

**Comment by adiwajshing** [comment]
@barkerpedro The latest commit has the functionality that you're looking for

**Comment by barkerpedro** [comment]
It worked perfect, I am very grateful for the effort.
Thanks.
