### ISSUE TITLE
[BUG] Baileys version.json

### ISSUE THREAD

**Issue by FERDIZ-afk** [adiwajshing/Baileys#2202]
![Screenshot_2022-09-28-11-30-20-24](https://user-images.githubusercontent.com/69185890/192720213-542370ae-2ddd-4cd7-a1b0-532449b4094c.png)

Pliss help me every time I install the Baileys module via github (yarn add github:adiwajshing/baileys) it turns out like this. The problem is there is a Baileys version 

Inside the node_modules/@adiwajshing/baileys/lib/Defaults directory there is no file named baileys-version.json Meanwhile in the node_modules/@adiwajshing/baileys/src/Defaults directory there is a baileys-version.json json file 

Please tell me how to install yarn add github:adiwajshing/baileys baileys version already in the lib directory without having to move files

**Comment by amiruldev20** [comment]
change "@adiwajshing/baileys": "github:amiruldev20/Baileys"
remove node modules & npm i

**Comment by FERDIZ-afk** [comment]
> change "@adiwajshing/baileys": "github:amiruldev20/Baileys" remove node modules & npm i

just the same
