### ISSUE TITLE
Decrypted message with closed session.

### ISSUE THREAD

**Issue by Ajay-o-s** [adiwajshing/Baileys#2203]
Decrypted message with closed session.
Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry

**Comment by amiruldev20** [comment]
use [baileys amirul dev](https://github.com/amiruldev20/Baileys)

**Comment by BlackAmda** [comment]
> use [baileys amirul dev](https://github.com/amiruldev20/Baileys)

Why?
