### ISSUE TITLE
Convert a whatsapp id to phone number

### ISSUE THREAD

**Issue by IanosJunior** [adiwajshing/Baileys#2204]
Does anyone know how to convert a whatsapp id to phone number?
It can be TypeScript or JavaScript.
Considering the separate DDI.

**Comment by Gimenz** [comment]
maybe, you can use this module ~> [awesome-phonenumber](https://github.com/grantila/awesome-phonenumber)

**Comment by hansputera** [comment]
> Does anyone know how to convert a whatsapp id to phone number? It can be TypeScript or JavaScript. Considering the separate DDI.

Did you mean whatsapp id like this? (`123456789012:12@whatsapp.net` or `123456789012@whatsapp.net`) ?
If you just want to get the phone number, I think you can use a simple regex to extract it (I'm not a regexr expert btw)

Example:
```ts
const whatsappId: string = '123456789012:12@whatsapp.net';

whatsappId.replace(/(:[0-9]+)?@.+/g, ''); // output: '123456789012'
```

**Comment by SheIITear** [comment]
Thats an oddly unnecessary complex regex. You can just use `/:.*/`.

**Comment by SheIITear** [comment]
> > Does anyone know how to convert a whatsapp id to phone number? It can be TypeScript or JavaScript. Considering the separate DDI.
> 
> Did you mean whatsapp id like this? (`123456789012:12@whatsapp.net` or `123456789012@whatsapp.net`) ? If you just want to get the phone number, I think you can use a simple regex to extract it (I'm not a regexr expert btw)
> 
> Example:
> 
> ```ts
> const whatsappId: string = '123456789012:12@whatsapp.net';
> 
> whatsappId.replace(/(:[0-9]+)?@.+/g, ''); // output: '123456789012'
> ```


Thats an oddly unnecessary complex regex. You can just use /:.*/.
