### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'addSenderKeyState')

### ISSUE THREAD

**Issue by Francuchin** [adiwajshing/Baileys#2205]
When receiving or sending messages to a group, the "messages.upsert" event is fired with this content:

    "messages": [
      {
        "key": {
          "remoteJid": "XXXXX@g.us",
          "fromMe": false,
          "id": "XXXXXX",
          "participant": "XXXXX@s.whatsapp.net"
        },
        "messageTimestamp": XXXXX,
        "pushName": "Francuchin",
        "messageStubType": 2,
        "messageStubParameters": [
          "Cannot read properties of undefined (reading 'addSenderKeyState')"
        ]
      }
    ],

**Comment by JoaoArtur** [comment]
up

**Comment by AlvaroBrasilia** [comment]
Same issue!

**Comment by AlvaroBrasilia** [comment]
...

**Comment by Francuchin** [comment]
No changes...

**Comment by Francuchin** [comment]
Still an issue

**Comment by AlvaroBrasilia** [comment]
Same issue here when I send a list message template. 
When a user select an option the returns is like the reported in this topic.

My question is... This is a expected result or a bug? Does return List messege selected working on a group?
