### ISSUE TITLE
getStatus() in MD

### ISSUE THREAD

**Issue by Miku21750** [adiwajshing/Baileys#2206]
I don't know, i search in Docs and readme.md, i can't search `getStatus()`. I see in the issues section, the way to get 'about' contact is `getStatus()`. But when i try `conn.getStatus(jid.sender)` it's said `TypeError: conn.getStatus is not a function`

**Comment by TOXIC-DEVIL** [comment]
> I don't know, i search in Docs and readme.md, i can't search `getStatus()`. I see in the issues section, the way to get 'about' contact is `getStatus()`. But when i try `conn.getStatus(jid.sender)` it's said `TypeError: conn.getStatus is not a function`

Use **conn.fetchStatus(jid.sender)**

**Comment by Miku21750** [comment]
> 
> Use `conn.fetchStatus(jid.sender)`

Okay thanks, it's work. But i have another question. I use conn.fetchStatus and the result is as i expected. 
`{
    status : (status)
    setAt : (time set)
 }`
Let say i get the status. And the result is like this
`{
    status : 'hey there, i'm using whatsapp'
    setAt : 2022-06-24T11:46:45.000Z
 }`

So, how do i call the setAt value to string, so i can display it as original time we can read?
Thanks

**Comment by Miku21750** [comment]
Sorry, i mean how to make that setAt value to a original date and time we can read

**Comment by Miku21750** [comment]
Oh sorry, i don't know that is the original format date from javascript.
Then i only use `const date = new Date(status.setAt)` to get the original date.
The issue is closed

**Comment by TOXIC-DEVIL** [comment]
> Oh sorry, i don't know that is the original format date from javascript. Then i only use : `let anu = await conn.fetchStatus(jid.Sender)` `const date = new Date(anu.setAt)` to get the original date. The issue is closed

Yeh
