### ISSUE TITLE
[MD] Logout not work

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2207]
Using the logoff function returns the error below.

![image](https://user-images.githubusercontent.com/10979090/193166552-e1b9f2c3-096c-426a-8584-13d122f2ff7b.png)

Baileys is in the package version: 4.4.0

**Comment by umair6372** [comment]
> Using the logoff function returns the error below.
> 
> ![image](https://user-images.githubusercontent.com/10979090/193166552-e1b9f2c3-096c-426a-8584-13d122f2ff7b.png)
> 
> Baileys is in the package version: 4.4.0

did you find the solution ?????

**Comment by AlanMartines** [comment]
> > Using the logoff function returns the error below.
> > ![image](https://user-images.githubusercontent.com/10979090/193166552-e1b9f2c3-096c-426a-8584-13d122f2ff7b.png)
> > Baileys is in the package version: 4.4.0
> 
> did you find the solution ?????

I haven't found it yet...
