### ISSUE TITLE
[BUG] Not responding in group

### ISSUE THREAD

**Issue by naylachan** [adiwajshing/Baileys#2208]
sometimes my bot doesn't answer in the group, I checked the logs, no errors occur, here I'm using the latest version of Baileys 4.4.0, does anyone know a solution for this?

**Comment by Francuchin** [comment]
I hav a simillar case reported in [This Issue](https://github.com/adiwajshing/Baileys/issues/2205#issue-1389643158) maybe is the same problem... 🤷

**Comment by naylachan** [comment]
> I don't agree with this opinion, I'm trying to share the results of the bot script with others, and that person also has the same problem when using my script, is there any other solution for this?

**Comment by naylachan** [comment]
Ooo

> maybe it's a problem in your network

I don't agree with this opinion, I'm trying to share the results of the bot script with others, and that person also has the same problem when using my script, is there any other solution for this?

**Comment by naylachan** [comment]
> I hav a simillar case reported in [This Issue](https://github.com/adiwajshing/Baileys/issues/2205#issue-1389643158) maybe is the same problem... 🤷

Have you found a way to solve this problem?

**Comment by AlvaroBrasilia** [comment]
Same issue :(

**Comment by AlvaroBrasilia** [comment]
Up
