### ISSUE TITLE
How to decrypt vote poll encPlayload ?

### ISSUE THREAD

**Issue by VanzGantengz** [adiwajshing/Baileys#2215]
```json
      {
        "message": {
        "pollUpdateMessage": {
          "pollCreationMessageKey": {
            "remoteJid": "xxx@g.us",
            "fromMe": false,
            "id": "xxx",
            "participant": "xxx@s.whatsapp.net"
          },
          "vote": {
        =>  "encPayload": "xNIZl7q9IP7ucJ94S9NO4lZKFta+c8xM3WzsQdYJNHaZyDPeyGVvubBVXjFwVIje5UU=",
        =>   "encIv": "5yg3Hw+xehIw76Bi"
          },
          "senderTimestampMs": "xxx"
        }
      }
    }

**Comment by SanzGanzs** [comment]
> ```json
>       {
>         "message": {
>         "pollUpdateMessage": {
>           "pollCreationMessageKey": {
>             "remoteJid": "xxx@g.us",
>             "fromMe": false,
>             "id": "xxx",
>             "participant": "xxx@s.whatsapp.net"
>           },
>           "vote": {
>         =>  "encPayload": "xNIZl7q9IP7ucJ94S9NO4lZKFta+c8xM3WzsQdYJNHaZyDPeyGVvubBVXjFwVIje5UU=",
>         =>   "encIv": "5yg3Hw+xehIw76Bi"
>           },
>           "senderTimestampMs": "xxx"
>         }
>       }
>     }
> ```

🗿

**Comment by SheIITear** [comment]
Its encrypted using AES-GCM. I did a quick test on decrypting it and managed to figure out a bit of how it works and how it can be done.

1. You need the enc_key from the creation of poll.
2. You take the enc_payload and env_iv
3. Create the additional data needed using ````console.log(enc.encode('pollmsg_id\u0000jid_here'))````
4. Use those to decrypt the data by aes-gcm: 
````js
const decryptMessage = async () => {
    const encoded = new Uint8Array([enc_payload])
    return crypto.subtle.decrypt({name: "AES-GCM",iv: new Uint8Array([enc_iv]),additionalData: new Uint8Array([additional_data]),tagLength: 128},(await crypto.subtle.importKey("raw",new Uint8Array([enc_key]),"AES-GCM",false,["encrypt","decrypt"])),encoded)
}
````
5. Then we decode the result using:
```js
const decrypted = new Uint8Array(await decryptMessage()).slice(2)

const decode = decrypted => {
    const n = [48,49,50,51,52,53,54,55,56,57,65,66,67,68,69,70],r = [48,49,50,51,52,53,54,55,56,57,97,98,99,100,101,102];
0,11,151,91,234,155,173,98,186,224,98,84,20,87,19,225,124,112,144,150,69,253,236,28,187,185,175,191,226,162,121,166,178,178,140,141,74,10,226,111,251,49,226,18,241,39,17,51,63,185
    const outarr = [];
    for (let i = 0; i < decrypted.length; i++) {
        const val = decrypted[i];
        outarr.push(n[val >> 4],n[15 & val])
    }
    return String.fromCharCode.apply(String,outarr)
}
````
6. You should be left with sha-256 hash of the poll option. This can be confirmed with, for example, ````Buffer.from(await crypto.subtle.digest("SHA-256",(new TextEncoder).encode('ShellTear'))).toString('hex')````

Example photos:

Received pollupdate
![image](https://user-images.githubusercontent.com/62976449/198176655-e80b29db-0390-490e-b421-ac0783491417.png)

Decrypting the update
![image](https://user-images.githubusercontent.com/62976449/198176427-3a4feb3b-5ba1-445f-9133-8abb41ea75b0.png)

**Comment by azudindaem** [comment]
nice work!

**Comment by hansputera** [comment]
:+1:

**Comment by SheIITear** [comment]
For encryption its simple:
1. Generate the enc_key (creation message) which is 32 bytes and the iv which is 12 bytes.
2. Then do the steps using it till you get decryption key & additional data.
3. Then take the sha 256 hash of the poll option. 
````js
const pollOptionHash = new Uint8Array(await crypto.subtle.digest("SHA-256", (new TextEncoder).encode('ShellTear')))
````
4. Encrypt pollOptionHash using the decryptionKey, iv and additionalData from above steps.
````js
const encryptMessage = async (hash) => {
    const tagSize_multiplier = 16
    const encoded = new Uint8Array([enc_payload])
    const key = await crypto.subtle.importKey('raw', new Uint8Array([decryptionKey]), 'AES-GCM', false, ['encrypt' ,'decrypt'])
    return crypto.subtle.encrypt({name: 'AES-GCM', iv: new Uint8Array([enc_iv]), additionalData: additional_data, tagLength: 8 * tagSize_multiplier}, key, hash)
}
````

Lastly the output of step 4 is enc_payload and iv is same as used for encryption. 
The decryptionKey is not part of the creation message! Use the bytes generated in step 1.

**Comment by hansputera** [comment]
> 

What data should we fill in `modificationSender` ?

**Comment by SheIITear** [comment]
> > 
> 
> 
> 
> What data should we fill in `modificationSender` ?

Vote sender jid.

**Comment by hansputera** [comment]
Hm, I'm still confused by `enc_key`, you said `enc_key` it's from `messageSecret`, right?

In your code for decrypting polls, there is a use of `enc_key` in the process. And, `enc_key` or `messageSecret` is only available from when `pollCreationMessage` appears isn't it?

**Comment by SheIITear** [comment]
> Hm, I'm still confused by `enc_key`, you said `enc_key` it's from `messageSecret`, right?
> 
> 
> 
> In your code for decrypting polls, there is a use of `enc_key` in the process. And, `enc_key` or `messageSecret` is only available from when `pollCreationMessage` appears isn't it?

Yes

**Comment by PurpShell** [comment]
https://gist.github.com/PurpShell/44433d21631ff0aefbea57f7b5e31139 @hansputera I have implemented this in a gist

**Comment by SheIITear** [comment]
After doing some more investigation after @PurpShell found out that the payload size can change which obviously affects the output. 
Keep in mind that you might have to keep track of user's votes to determine poll updates.

1. If the user has only voted once and then unvotes: payload is 16 bytes and the decryption result will be empty. 

2. If the user votes second time, the payload will be 84 bytes. (single vote payload is 50 bytes, so there is +34 bytes per voted option. ie 3 voted options would be 118, 4 would be 152 and so on). 
The payload will contain hashes of **ALL** options voted on. The hashes are in the order the user voted.
The hashes are decrypted to a single string, but I found that there is a **hash seperator mark:** ````0A20```` 

3. If a person has voted on more than one options and unvotes one: you'll receive the hashes of the voted options and the unvoted hash is removed. 

Images:

Step 2:
![image](https://user-images.githubusercontent.com/62976449/198745847-f94346c4-cace-4541-93eb-9501aab84619.png)

Step 3:
![image](https://user-images.githubusercontent.com/62976449/198745936-7456bd8c-cc4f-4bd4-9838-1be2ec7cc088.png)

The hashes in image are already seperated. The output from decryption on second image would be (I added dashes around the seperation mark to make it noticeable):
````0E07CF830957701D43C183F1515F63E6B68027E528F43EF52B1527A520DDEC82-0A20-C5282FC767CABF0C7794DA23B5FEB85659668614691DBC89A0B96E3F7C314202````

**Comment by Auties00** [comment]
> 

I've been researching the same for my library WhatsappWeb4J. I reversed the decryption without any problems, though the messageSecret looks to be null in the protobuf. While debugging the same process on Whatsapp Web's client, I noticed that that field is indeed null when the proto arrives, but later gets somehow filled. I've tried to understand how that works, but I had no luck today. Do you know by any chance?

**Comment by Auties00** [comment]
> I did some more investigating after @PurpShell noticed that the payload size can change which obviously affects the output. Keep in mind that you might have to keep track of user's votes to determine poll updates.
> 
> 1. If the user has only voted once and then unvotes: payload is 16 bytes and the decryption result will be empty.
> 2. If the user votes second time, the payload will be 84 bytes. (single vote payload is 50 bytes, so there is +34 bytes per voted option. ie 3 voted options would be 118, 4 would be 152 and so on).
>    The payload will contain hashes of **ALL** options voted on. The hashes are in the order the user voted.
>    The decrypted payload is a single string and the hashes are separated from each other by **hash end mark:** `0A20`  <-- (0A = newline and 20 = space)
> 3. If a person has voted on more than one option and unvotes one: you'll receive the hashes of the voted options and the unvoted hash is removed.
> 
> Images:
> 
> ![image](https://user-images.githubusercontent.com/62976449/198745847-f94346c4-cace-4541-93eb-9501aab84619.png)
> 
> ![image](https://user-images.githubusercontent.com/62976449/198745936-7456bd8c-cc4f-4bd4-9838-1be2ec7cc088.png)
> 
> The hashes in the images are already seperated. The output from decryption on second image would be (I added dashes around the separation mark to make it noticeable): `0E07CF830957701D43C183F1515F63E6B68027E528F43EF52B1527A520DDEC82-0A20-C5282FC767CABF0C7794DA23B5FEB85659668614691DBC89A0B96E3F7C314202`

I've been researching the same for my library WhatsappWeb4J. I reversed the decryption without any problems, though the messageSecret looks to be null in the protobuf. While debugging the same process on Whatsapp Web's client, I noticed that that field is indeed null when the proto arrives, but later gets somehow filled. I've tried to understand how that works, but I had no luck today. Do you know by any chance?
