### ISSUE TITLE
[BUG] github actions to work when installing this lib

### ISSUE THREAD

**Issue by JonhnyDev** [adiwajshing/Baileys#2216]
tests and eslint error in yarn.

```
 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/adiwajshing/libsignal-node.git
Directory: /home/runner/work/WP.COM/WP.COM
Output:
Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
when I remove the lib with "yarn remove @adiwajshing/baileys", github actions works normally again

**Comment by robvanderleek** [comment]
I also bumped into this.
The dependency in `package.json` is `git+https://github.com/adiwajshing/libsignal-node` but builds in GH Actions use `ssh://git@github.com/adiwajshing/libsignal-node.git` and fail.

A solution that worked for me is to run the following command in your GH Actions workflow before running `yarn install`:
`git config --global url."https://github".insteadOf ssh://git@github`
