### ISSUE TITLE
I need to know each message, when and who read it #418

### ISSUE THREAD

**Issue by mygethu** [adiwajshing/Baileys#222]
hi bro
I need to know each message, when and who read it

There are detailed information in the information card of the whatsup app, showing the details of the reader, can it be easily obtained in large quantities?
![截圖 2020-11-07 上午2 35 35](https://user-images.githubusercontent.com/30842496/98396953-ed6b7c80-20a1-11eb-9a30-f6a2ad09ccac.png)

**Comment by adiwajshing** [comment]
See [here](https://github.com/adiwajshing/Baileys/blob/75aa1f9d81f248e10a3eed102cfcb2a682374235/src/WAConnection/7.MessagesExtra.ts#L20)

**Comment by mygethu** [comment]
Hi
 Dear bro
I want open what`sup  app and “baileys”  at same time?can do it?

**Comment by mygethu** [comment]
Dear bro
And thank you for your answer
