### ISSUE TITLE
[BUG] TypeError: makeWASocket is not a function (Node ESM + Typescript)

### ISSUE THREAD

**Issue by rodrigosuelli** [adiwajshing/Baileys#2223]
I'm using typescript and nodejs with ES modules (`"type": "module"` in `package.json`). I need es modules because im using top-level await in the project.

import makeWASocket from '@adiwajshing/baileys';
 
const sock = makeWASocket()
^
TypeError: makeWASocket is not a function

Please help, how can I fix this?

**Comment by clicknetcafe** [comment]
https://github.com/adiwajshing/Baileys/issues/1092#issuecomment-1030268968

**Comment by rodrigosuelli** [comment]
> [#1092 (comment)](https://github.com/adiwajshing/Baileys/issues/1092#issuecomment-1030268968)

I need a solution that uses `import`

**Comment by VanzGantengz** [comment]
it should be this way 

```js
import baileys from "@adiwajshing/baileys";
const sock = baileys.defaulf({})
```
or 
```js
import default: makeWASocket from "@adiwajshing/baileys";
const sock = makeWASocket({})

**Comment by rodrigosuelli** [comment]
> it should be this way
> 
> ```js
> import baileys from "@adiwajshing/baileys";
> const sock = baileys.defaulf({})
> ```
> 
> or
> 
> ```js
> import default: makeWASocket from "@adiwajshing/baileys";
> const sock = makeWASocket({})
> ```
Don't worked for me.
import baileys from "@adiwajshing/baileys";
const sock = baileys.default({})
^
TS2339: Property 'default' does not exist on type '(config: UserFacingSocketConfig) => { getOrderDetails: (orderId: string, tokenBase64: string) => Promise<OrderDetails>; getCatalog: (jid?: string | undefined, limit?: number | undefined) => Promise<...>; ... 63 more ...; waitForConnectionUpdate: (check: (u: Partial<...>) => boolean | undefined, timeoutMs?: number | ...'.

**Comment by VanzGantengz** [comment]
but i worked in javascript esm

**Comment by rodrigosuelli** [comment]
> but i worked in javascript esm

Can I make this work with typescript esm?

**Comment by undefined-60** [comment]
> deveria ser assim
> 
> ```js
> import baileys from "@adiwajshing/baileys";
> const sock = baileys.defaulf({})
> ```
> 
> ou
> 
> ```js
> import default: makeWASocket from "@adiwajshing/baileys";
> const sock = makeWASocket({})
> ```

Usar import { default: makeWASocket } from "@adiwajshing/baileys"; talvez funcionária não?

**Comment by Waxaranai** [comment]
unstale, need an update on this.

**Comment by aksh-git** [comment]
Try this

```js
import * as baileys from '@adiwajshing/baileys';
const makeWASocket  = baileys.default.default;
```
import all as baileys then ..

**Comment by abdurahmanshiine** [comment]
> Try this
> 
> ```js
> import * as baileys from '@adiwajshing/baileys';
> const makeWASocket  = baileys.default.default;
> ```
> 
> import all as baileys then ..

This didn't work for me as well, this is the output i'm getting:

```
.../node_modules/.pnpm/@adiwajshing+baileys@5.0.0_qrcode-terminal@0.12.0/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:36
    const { creds } = authState;
            ^

TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.

at makeSocket (.../node_modules/.pnpm/@adiwajshing+baileys@5.0.0_qrcode-terminal@0.12.0/
node_modules/@adiwajshing/baileys/lib/Socket/socket.js:36:13)
```

**Comment by aksh-git** [comment]
try defining `auth: state` in connection options..
```js
import { useMultiFileAuthState } from '@adiwajshing/baileys'

const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys');

const conn = makeWASocket({ auth: state }) 
```

**Comment by abdurahmanshiine** [comment]
> try defining `auth: state` in connection options..
> 
> ```js
> import { useMultiFileAuthState } from '@adiwajshing/baileys'
> 
> const { state, saveCreds } = await useMultiFileAuthState('auth_info_baileys');
> 
> const conn = makeWASocket({ auth: state }) 
> ```

Thanks, that helped. I got another issue though, which forcefully terminates the process:

```
{..., "trace":"Error: Stream Errored (restart required)\n    at WebSocket.<anonymous>(/home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/@adiwajshing+baileys@5.0.0_qrcode-terminal@0.12.0/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:424:13)\n    at WebSocket.emit (node:events:513:28)\n    at /home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/@adiwajshing+baileys@5.0.0_qrcode-terminal@0.12.0/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/@adiwajshing+baileys@5.0.0_qrcode-terminal@0.12.0/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/@adiwajshing+baileys@5.0.0_qrcode-terminal@0.12.0/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at Receiver.receiverOnMessage (/home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/ws@8.12.0/node_modules/ws/lib/websocket.js:1180:20)\n    at Receiver.emit (node:events:513:28)\n    at Receiver.dataMessage (/home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/ws@8.12.0/node_modules/ws/lib/receiver.js:526:14)\n    at Receiver.getData (/home/abdurahman/Programming/JS/NodeJS/WhatsApp/baileys-whatsapp/node_modules/.pnpm/ws@8.12.0/node_modules/ws/lib/receiver.js:459:17)","msg":"connection errored"}
```

Any idea what could be the cause?

**Comment by mzcoder-hub** [comment]
is there any solutin about this ? im using `type : module` too
