### ISSUE TITLE
Logout session issue 

### ISSUE THREAD

**Issue by umair6372** [adiwajshing/Baileys#2224]
hey ! we are facing one of the issue which is logout from WhatsApp through this library when we try logout function its not working properly means session is still active and we can still send sms....
so please add this logout feature properly into the library and guide us about it...
thank you!

here is the error screenshot
![193166552-e1b9f2c3-096c-426a-8584-13d122f2ff7b](https://user-images.githubusercontent.com/30259305/194062875-1f853d37-85a5-40bc-8122-3129823e5b21.png)
here is the code for logout....
![index](https://user-images.githubusercontent.com/30259305/194063249-2ba8dde9-ffae-4983-8b83-9af9206282fd.jpg)

**Comment by fares-coder** [comment]
Same Issue

**Comment by undefined-60** [comment]
> Ei ! estamos enfrentando um dos problemas que é sair do WhatsApp através desta biblioteca quando tentamos a função de logout, não está funcionando corretamente significa que a sessão ainda está ativa e ainda podemos enviar sms .... nos oriente sobre isso... obrigado!
> 
> aqui está a captura de tela do erro aqui está o código para logout .... ![193166552-e1b9f2c3-096c-426a-8584-13d122f2ff7b](https://user-images.githubusercontent.com/30259305/194062875-1f853d37-85a5-40bc-8122-3129823e5b21.png) ![índice](https://user-images.githubusercontent.com/30259305/194063249-2ba8dde9-ffae-4983-8b83-9af9206282fd.jpg)

Tente colocar o número de celular dentro da função logout
