### ISSUE TITLE
ImageMessage and VideoMessage not working.

### ISSUE THREAD

**Issue by joelvitorniino** [adiwajshing/Baileys#2225]
Recently, imagemessage and videomessage is not working, how to solve?

```
if(events['messages.upsert']) {
            const upsert = events['messages.upsert']
            if(upsert.type !== 'notify') {
                return;
            }

            for(const msg of upsert.messages) {
                if(isCmd(msg)) {
                    await msgHandler(sock, msg);
                }
            };
```

**Comment by guiireal** [comment]
There's no way to know if it's a bug or not, since your "msgHandler" function is a wrapper, we have no way of knowing what's inside it.

You should run examples with Baileys' own functions, to make sure the problem is in Baileys, otherwise the problem is in your code.
