### ISSUE TITLE
An enhancement suggestion to handle connection close issue, related to (428 Precondition Required)

### ISSUE THREAD

**Issue by Alhar6i** [adiwajshing/Baileys#2226]
Hi,

I'm wondering if you could improve the way that Baileys handles the 'connection close' issue.

In the socket.ts file, there are four places where you throw the error without emitting the connection update event  (refer to the below lines)
Lines 65, 93, 133, and 332
I guess it would be useful if you could add the connection update event if that is possible.
That will help clean up the socket before reconnecting it.
 
Edit
------
@adiwajshing 
I traced the Precondition Required error, the strange thing is that the connection was closed when baileys received the server response "Precondition Required"!
Can someone explain how that comes?
Do you think that was a socket bug?

 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428

Cheers

**Comment by Alhar6i** [comment]
I think this issue might be a bug.
My account is able to receive messages of all types while it can not send any messages of any type.
The function **sendRawMessage**  throws an error when validate the connection state (ws.readyState !== ws.OPEN).
How that comes?
Do we have two connections simultaneously?

**Comment by dsandrade** [comment]
same issue

**Comment by satriowicaksn** [comment]
+1
