### ISSUE TITLE
[BUG] Error trying to react to a message

### ISSUE THREAD

**Issue by K3inn** [adiwajshing/Baileys#2228]
**Describe the bug**
Good evening everyone, I have a problem. I'm trying to react to a message when a command is executed, but I'm getting this error:
```
  output: {
    statusCode: 400,
    payload: {
      statusCode: 400,
      error: 'Bad Request',
      message: 'Invalid media type'
    }
```

**Expected behavior**
I need it to react to the user who execute the command

**Additional context**
```
async replyReact(){
    await sock.sendMessage(from, { reaction: { text: "💖", key: mei.key }})
}
```
I think the problem is in the way I'm passing the emoji, but I don't know how to solve it...

**Comment by Akkun3704** [comment]
Try this
```js
async replyReact() {
  await sock.sendMessage(from, { react: { text: "💖", key: mei.key }})
}
```
