### ISSUE TITLE
Skip QR Code logging in terminal

### ISSUE THREAD

**Issue by sandro-salles** [adiwajshing/Baileys#223]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

Hey man, first of all, what a GREAT WORK! Really, impressive!

I just want to suggest the possibility to avoid logging the QRCode to terminal, maybe using a flag (skipQrTerminal or something)... the terminal logging is useful for troubleshooting purposes, but ends up polluting the server logs!

Thanks again!

**Comment by adiwajshing** [comment]
Glad you like the library. Have you tried `conn.removeAllListeners('qr')`?

**Comment by sandro-salles** [comment]
Yep... it works perfectly! Thanks again man!
