### ISSUE TITLE
[BUG] Reupload request always fails for older files

### ISSUE THREAD

**Issue by jurajmatus** [adiwajshing/Baileys#2230]
**Describe the bug**
Whenever a media that is older than some threshold (around 20 days), it fails to get downloaded.
Retry mechanism is activated and mobile device is online and it still happens.

**To Reproduce**
1. Call 
  ```ts
  downloadMediaMessage(
    message, // older message
    'buffer',
    {},
    {
      logger: waState.logger,
      reuploadRequest: async msg => {
        return sock.updateMediaMessage(msg);
      },
    }
  )
  ```
2. Error is thrown
  ```
    ERROR Failed to re-upload media (3)
      at decodeMediaRetryNode
      ...
      data: { code: '3' },
      isBoom: true,
      isServer: false,
      output: {
        statusCode: 412,
        payload: {
          statusCode: 412,
          error: 'Precondition Failed',
          message: 'Failed to re-upload media (3)'
        },
        headers: {}
      }
    }
  ```

**Expected behavior**
It should succeed at least sometimes, especially when the device is connected to the internet.

**Environment (please complete the following information):**
 - Is this on a server? YES (node version 14)
 - What do your `connectOptions` look like?
```
{
    version,// fetchLatestBaileysVersion()
    logger: state.logger, // error level
    markOnlineOnConnect: false,
    auth: state.authState, // custom DynamoDB based implementation
    syncFullHistory: true,
    msgRetryCounterMap: state.msgRetryCounterMap,
    connectTimeoutMs: 5 * 60 * 1000,
    defaultQueryTimeoutMs: undefined,
    keepAliveIntervalMs: 10000,
    browser: Browsers.macOS('Desktop'),
  }
```
 - Do you have multiple clients on the same IP? NO
 - Are you using a proxy? NO

**Comment by jurajmatus** [comment]
Still an issue

**Comment by jurajmatus** [comment]
Still an issue

**Comment by jurajmatus** [comment]
Still an issue

**Comment by LZNOXP** [comment]
maybe the sender doesn't have the file, the sender need to have the file in order for whatsapp to reupload it (i think) or they already deleted the message.
this is just what i think
