### ISSUE TITLE
[BUG] Buttons & ListMessage Not Coming

### ISSUE THREAD

**Issue by dcode-denpa** [adiwajshing/Baileys#2233]
![Screenshot_2022-10-08-16-20-35-397_com CyberWhatsapp](https://user-images.githubusercontent.com/76629978/194700216-84067820-21ad-4bda-9642-b9848e271f81.jpg)

**Comment by Vynn-SOLO** [comment]
> ![Screenshot_2022-10-08-16-20-35-397_com CyberWhatsapp](https://user-images.githubusercontent.com/76629978/194700216-84067820-21ad-4bda-9642-b9848e271f81.jpg)

bagian listMessage, taro viewOnce: true bawah buttonText

**Comment by RIKASHIKI** [comment]
> 

is there anything other than that

**Comment by dcode-denpa** [comment]
> > ![Screenshot_2022-10-08-16-20-35-397_com CyberWhatsapp](https://user-images.githubusercontent.com/76629978/194700216-84067820-21ad-4bda-9642-b9848e271f81.jpg)
> 
> bagian listMessage, taro viewOnce: true bawah buttonText

Sama aja

**Comment by salsawij** [comment]
> > > ![Screenshot_2022-10-08-16-20-35-397_com CyberWhatsapp](https://user-images.githubusercontent.com/76629978/194700216-84067820-21ad-4bda-9642-b9848e271f81.jpg)
> > 
> > 
> > bagian listMessage, taro viewOnce: true bawah buttonText
> 
> Sama aja

```const sections = [
    {
    title: "Section 1",
    rows: [
        {title: "Option 1", rowId: "option1"},
        {title: "Option 2", rowId: "option2", description: "This is a description"}
    ]
    },
   {
    title: "Section 2",
    rows: [
        {title: "Option 3", rowId: "option3"},
        {title: "Option 4", rowId: "option4", description: "This is a description V2"}
    ]
    },
]

const listMessage = {
  text: "This is a list",
  footer: "nice footer, link: https://google.com",
  title: "Amazing boldfaced list title",
  buttonText: "Required, text on the button to view the list",
  viewOnce: true,
  sections
}

await sock.sendMessage(from, listMessage)```
bisa kok ini
