### ISSUE TITLE
[BUG] duplicate message with previous link

### ISSUE THREAD

**Issue by undefined-60** [adiwajshing/Baileys#2235]
*the message becomes duplicated when replying to a message with a previous link, this does not always happen, but it happens a lot.*

**Comment by undefined-60** [comment]
> _the message becomes duplicated when replying to a message with a previous link, this does not always happen, but it happens a lot._

![Screenshot_2022-10-08-10-42-28-1](https://user-images.githubusercontent.com/108310586/194710841-b17ad444-6afc-4a6c-974f-86af6d8297f9.png)

Exemplo:

**Comment by undefined-60** [comment]
This error doesn't actually duplicate the message itself, baileys drops the messages.upsert 2 times because the id of each message is different

**Comment by zennn08** [comment]
![Screenshot_20221009_074233](https://user-images.githubusercontent.com/75623219/194732390-5d69b182-41a9-4bd3-aebf-73d92cec45ca.JPG)
The id of each messages is same

**Comment by BlackAmda** [comment]
It happened to me also. Try close the link preview and send, then it will not reply twice. Still I don't know how to fix that.

**Comment by undefined-60** [comment]
> ![Captura de tela_20221009_074233](https://user-images.githubusercontent.com/75623219/194732390-5d69b182-41a9-4bd3-aebf-73d92cec45ca.JPG) O id de cada mensagem é o mesmo

O id da mensagem recebida é o mesmo, mais o da mensagem enviada pelo baileys não, pelo menos aqui.

**Comment by undefined-60** [comment]
> Aconteceu comigo também. Tente fechar a visualização do link e enviar, então ele não responderá duas vezes. Ainda não sei como consertar isso.

Eu editei uma pequena parte do código baileys, por aqui resolveu perfeitamente o erro.

caminho: baileys/lib/Socket/messages-recv.js linha 515+- //uso JavaScript.
edição:
    // recv a message
    const keys = {};
    ws.on('CB:message', (node) => {
        Object.keys(keys).length && Object.keys(keys).map((i) => {
            if (Date.now() >= keys[i]) {
                delete keys[i];
            };
        });
        if (node.attrs && node.content[0] && node.content[0].attrs && node.content[0].attrs.mediatype == 'url') {
            if (keys[node.attrs.id]) {
                logger.debug(node.attrs, 'duplicate message, ignoring...');
                return delete keys[node.attrs.id];
            } else {
                keys[node.attrs.id] = Date.now() + 60000;
            }
        }
        flushBufferIfLastOfflineNode(node, 'processing message', handleMessage);
    });

**Comment by undefined-60** [comment]
> > Aconteceu comigo também. Tente fechar a visualização do link e enviar, então ele não responderá duas vezes. Ainda não sei como consertar isso.
> 
> Eu editei uma pequena parte do código baileys, por aqui resolveu perfeitamente o erro.
> 
> caminho: baileys/lib/Socket/messages-recv.js linha 515+- //uso JavaScript. edição: // recv a message const keys = {}; ws.on('CB:message', (node) => { Object.keys(keys).length && Object.keys(keys).map((i) => { if (Date.now() >= keys[i]) { delete keys[i]; }; }); if (node.attrs && node.content[0] && node.content[0].attrs && node.content[0].attrs.mediatype == 'url') { if (keys[node.attrs.id]) { logger.debug(node.attrs, 'duplicate message, ignoring...'); return delete keys[node.attrs.id]; } else { keys[node.attrs.id] = Date.now() + 60000; } } flushBufferIfLastOfflineNode(node, 'processing message', handleMessage); });

Pode não ser a melhor solução mais funciona perfeitamente.

**Comment by zennn08** [comment]
> Pode não ser a melhor solução mais funciona perfeitamente.

thanks! i will try ur code

**Comment by undefined-60** [comment]
> > Pode não ser a melhor solução mais funciona perfeitamente.
> 
> thanks! i will try ur code

Ok, comente novamente se funcionar ou não...
