### ISSUE TITLE
how to interact with stories

### ISSUE THREAD

**Issue by asifdzaki93** [adiwajshing/Baileys#2237]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**
how to interact with stories?
send, view?

**Comment by Verzach3** [comment]
When a message is received that has the remoteJid of status@broadcast is a story, you can reply to it as a normal message i think
