### ISSUE TITLE
[BUG] Connection closed with message "stream errored out" and node tag "stream:error" with code 503

### ISSUE THREAD

**Issue by ibnumardini** [adiwajshing/Baileys#2238]
**Describe the bug**
Idk what happened, but the connection closed after being online for a few hours.

**To Reproduce**
1. Created a new connection
2. Very randomly, I have multiple connections for one IP, and a close connection just happened with one of an instance

**Expected behavior**
How to fix it? or why that condition can happen?

**Environment (please complete the following information):**
 - Is this on a server? `YES`
 - What do your `connectOptions` look like? 
 ```
const sock = makeWASocket({
  version: version,
  logger: this._log(deviceId),
  printQRInTerminal: this.logQR,
  auth: state,
  browser: osName,
  defaultQueryTimeoutMs: undefined
})
```
 - Do you have multiple clients on the same IP? `YES`
 - Are you using a proxy? `NO`

**Additional context**
**# This the log before I get the error**
`{"level":30,"time":1665266729109,"pid":3313,"hostname":"wa.server","APP-DEV":"Ibnu Mardini","deviceId":123,"0":{"key":{"remoteJid":"status@broadcast","fromMe":false,"id":"74F43DB67DCBED99B2CC7DD6F885C682","participant":"601983236**@s.whatsapp.net"},"messageTimestamp":1665266727,"pushName":"***","message":{"senderKeyDistributionMessage":{"groupId":"status@broadcast","axolotlSenderKeyDistributionMessage":"MwjZptnQBxAWGiCXChI1u9w7YhIDccM7ZKzLW759/LXeQvgxsj8O44eociIhBVb3gIcqkGFil5CO1I3k/b9HRp+awOQyMrjEIyMcLN99"},"messageContextInfo":{"deviceListMetadata":{"senderKeyHash":"MbOGoLNtpkeyNA==","senderTimestamp":"1664755382","recipientKeyHash":"7wi6KK7vLUFyUg==","recipientTimestamp":"1665188267"},"deviceListMetadataVersion":2}},"verifiedBizName":"***"},"caller":"EventEmitter.<anonymous> (/***/providers/App-Bailyes-Md/src/WASocket.js:105:43)","msg":"messages.upsert"}`

**# This the log error of what I get**
`{"level":50,"time":1665266742368,"pid":3313,"hostname":"wa.server","APP-DEV":"Ibnu Mardini","deviceId":123,"node":{"tag":"stream:error","attrs":{"code":"503"}},"caller":"WebSocket.<anonymous> (/***/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:413:16)","msg":"stream errored out"}`

`{"level":30,"time":1665266742371,"pid":3313,"hostname":"wa.server","APP-DEV":"Ibnu Mardini","deviceId":123,"trace":"Error: Stream Errored (unknown)\n    at WebSocket.<anonymous> (/***/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:415:13)\n    at WebSocket.emit (events.js:400:28)\n    at /***/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:221:35\n    at Object.decodeFrame (/***/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/***/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:197:15)\n    at WebSocket.emit (events.js:400:28)\n    at Receiver.receiverOnMessage (/***/node_modules/ws/lib/websocket.js:1178:20)\n    at Receiver.emit (events.js:400:28)\n    at Receiver.dataMessage (/***/node_modules/ws/lib/receiver.js:513:14)\n    at Receiver.getData (/***/node_modules/ws/lib/receiver.js:446:17)\n    at Receiver.startLoop (/***/node_modules/ws/lib/receiver.js:148:22)\n    at Receiver._write (/***/node_modules/ws/lib/receiver.js:83:10)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at Receiver.Writable.write (internal/streams/writable.js:303:10)\n    at TLSSocket.socketOnData (/***/node_modules/ws/lib/websocket.js:1272:35)\n    at TLSSocket.emit (events.js:400:28)","caller":"end (/***/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:234:16)","msg":"connection errored"}`

`{"level":30,"time":1665266742373,"pid":3313,"hostname":"wa.server","APP-DEV":"Ibnu Mardini","deviceId":123,"connection":"close","lastDisconnect":{"error":{"data":{"tag":"stream:error","attrs":{"code":"503"}},"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"Stream Errored (unknown)"},"headers":{}}},"date":"2022-10-08T22:05:42.372Z"},"caller":"EventEmitter.<anonymous> (/***/providers/App-Baileys-Md/src/WASocket.js:53:41)","msg":"connection.update"}`

**Comment by ibnumardini** [comment]
after that error, the auto-reconnect mechanism is if the connection is closed, but this error log happens

`{"level":30,"time":1665266742373,"pid":3313,"hostname":"wa.server","APP-DEV":"Ibnu Mardini","deviceId":123,"connection":"close","lastDisconnect":{"error":{"data":{"tag":"stream:error","attrs":{"code":"503"}},"isBoom":true,"isServer":true,"output":{"statusCode":503,"payload":{"statusCode":503,"error":"Service Unavailable","message":"Stream Errored (unknown)"},"headers":{}}},"date":"2022-10-08T22:05:42.372Z"},"caller":"EventEmitter.<anonymous> (/***/providers/App-Baileys-Md/src/WASocket.js:53:41)","msg":"connection.update"}`

and login failed with the message `not logged in, attempting registration...` and baileys generate a new QR code

**Comment by ibnumardini** [comment]
anyone helps?

**Comment by jurajmatus** [comment]
I think it's expected to happen from time to time and if restarting works, there should be no problem

**Comment by diegodorgam** [comment]
+1

**Comment by huangzhong0406** [comment]
+1

**Comment by stlsw** [comment]
+1
