### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by vihangayt0** [adiwajshing/Baileys#2247]
I want to know that the admin can delete the messages of other people who are new to whatsapp, where is the feature that can be done by bailyes. I read the readme.md but I did not find this feature.

**Comment by undefined-60** [comment]
> I want to know that the admin can delete the messages of other people who are new to whatsapp, where is the feature that can be done by bailyes. I read the readme.md but I did not find this feature.

const jid = '1234@s.whatsapp.net' // can also be a group
const response = await sock.sendMessage(jid, { text: 'hello!' }) // send a message
// sends a message to delete the given message
// this deletes the message for everyone
await sock.sendMessage(jid, { delete: response.key })
?????

**Comment by vihangayt0** [comment]
> > I want to know that the admin can delete the messages of other people who are new to whatsapp, where is the feature that can be done by bailyes. I read the readme.md but I did not find this feature.
> 
> const jid = '[1234@s.whatsapp.net](mailto:1234@s.whatsapp.net)' // can also be a group const response = await sock.sendMessage(jid, { text: 'hello!' }) // send a message // sends a message to delete the given message // this deletes the message for everyone await sock.sendMessage(jid, { delete: response.key }) ?????

![Screenshot_2022-10-10-14-31-31-030_com whatsapp](https://user-images.githubusercontent.com/96816258/194831629-f012824a-537b-4b2a-909b-8e0999c58580.jpg)
how to delete others msg from everyone like this.

**Comment by undefined-60** [comment]
> 

"this deletes the message for everyone" read again

**Comment by SamPandey001** [comment]
> > 
> 
> "this deletes the message for everyone" read again

Yeah,that question made me 👀 trice. 😂
I gave him codes even new issue,duh

**Comment by SamPandey001** [comment]
```js
const key = {
    remoteJid: m.msg.contextInfo.remoteJid,
    fromMe: false,
    id: m.msg.contextInfo.stanzaId,
    participant: sock.decodeJid(m.msg.contextInfo.participant)
}
await sock.sendMessage(jid, { delete: key })
```
