### ISSUE TITLE
Template Message is sent to myself

### ISSUE THREAD

**Issue by imReCoder** [adiwajshing/Baileys#2248]
Template Message is sent to myself and not to remoteJid
Message is visible as received message on my side and message is not visible on remote side
**Message body :**
 ```
 const templateButtons = [
                {index: 1, urlButton: {displayText: "⭐ Star Baileys on GitHub!", url: "https://github.com/adiwajshing/Baileys"}},
                {index: 2, callButton: {displayText: "Call me!", phoneNumber: "+1 (234) 5678-901"}},
                {index: 3, quickReplyButton: {displayText: "This is a reply, just like normal buttons!", id: "id-like-buttons-message"}},
            ];
            
 const templateMessage:IWhatsappTemplateMessage = {
                text: "Hi it's a template message",
                footer: "",
                templateButtons: templateButtons
            };
```

**Message sent response :** 

_` {"key":{"remoteJid":"919099858434@s.whatsapp.net","fromMe":true,"id":"BAE55AD154B05D1E"},"message":{"templateMessage":{"fourRowTemplate":{},"hydratedTemplate":{"hydratedContentText":"Hi it's a template message","hydratedButtons":[{"urlButton":{"displayText":"⭐ Star Baileys on GitHub!","url":"https://github.com/adiwajshing/Baileys"},"index":1},{"callButton":{"displayText":"Call me!","phoneNumber":
"+1 (234) 5678-901"},"index":2},{"quickReplyButton":{"displayText":"This is a reply, just like normal buttons!","id":"id-like-buttons-message"},"index":3}]}}},"messageTimestamp":"1665403237","status":"PENDING"}`_

Button Message ,List Message works fine only Template Message problem

**Comment by jasspro** [comment]
same here. any solution?

**Comment by makanSukros** [comment]
> same here. any solution?

Yes same here

**Comment by lcsouzamenezes** [comment]
Yes same here

**Comment by hmcorpltd** [comment]
solution for template message not going to receiver:

you need to remove only // the cause of the problem to make the template message start displaying on receiver side. This small change worked for me.

go to : src/Utils/messages.ts

go to line number 784:

// || message.templateMessage

remove extra // and change it to :

|| message.templateMessage


save it.

you are done 💯  now the template messages will start going to display on receiver side.

**Comment by imReCoder** [comment]
> message.templateMessage

I tried but its not working.

**Comment by hassanfuad96** [comment]
Its being blocked by whatsapp.

**Comment by imReCoder** [comment]
> Its being blocked by whatsapp.

then how its working for android ?
its not working in only ios

**Comment by hassanfuad96** [comment]
> > Its being blocked by whatsapp.
> 
> then how its working for android ? its not working in only ios

On my android is not working, i think u using old WhatsApp version. Latest WhatsApp version is unable to view those.

**Comment by erickmanovei** [comment]
same here. any solution?

**Comment by Cosm1cBug** [comment]
Any solution for this yet?

**Comment by keyurboss** [comment]
It is showing on the receiver's side But On our side it shows that it is been sent by the receiver.

**Comment by gadhiamitul41** [comment]
> It is showing on the receiver's side But On our side, it shows that the receiver has sent it.

+1

**Comment by keyurboss** [comment]
Any Solutions??

**Comment by erickmanovei** [comment]
> Any Solutions??

**Comment by rlucredio** [comment]
+1

**Comment by Ningoje** [comment]
any solution?

**Comment by Francuchin** [comment]
+1

**Comment by KevinEduardo** [comment]
+1

**Comment by mohammadelarief** [comment]
same here. any solution?

**Comment by juaose** [comment]
Same here.

I've tried sending _button, template and list_ messages (IOS & Android)

Messages bounce back with a "status": "PENDING" and end up being displayed baileys' side.

The template messages DO work when chatting WA web to baileys, used Chrome.

(Using WA business, BTW)

**Comment by aloisoinac** [comment]
Here!!
[https://github.com/adiwajshing/Baileys/issues/2328#issuecomment-1316161411](https://github.com/adiwajshing/Baileys/issues/2328#issuecomment-1316161411)

**Comment by juaose** [comment]
> Here!! [#2328 (comment)](https://github.com/adiwajshing/Baileys/issues/2328#issuecomment-1316161411)

It worked.
I can now use  _button, and list_  messages on both IOS and Android devices.
Thank you very much!

**Comment by rlucredio** [comment]
+1

**Comment by rlucredio** [comment]
+1

**Comment by gerenciadores** [comment]
+1

**Comment by rizalb7** [comment]
+1

**Comment by wendibarmara** [comment]
cannot receive template message from smartphone / handphone Whatsapp but in web whatsapp can receive

**Comment by rlucredio** [comment]
+1

**Comment by rlucredio** [comment]
+1

**Comment by aarzaary** [comment]
+1

**Comment by rlucredio** [comment]
1
