### ISSUE TITLE
[BUG] conn.groupMetadata(jid) doesn't work

### ISSUE THREAD

**Issue by theSoberSobber** [adiwajshing/Baileys#2250]
It always says precondition required and gives a 408 error.

**Comment by jurajmatus** [comment]
Can you post an example how you call it? I have a suspicion you use it for all chats without checking whether it's a group or not

**Comment by theSoberSobber** [comment]
I am sorry, actually it was an async await error in my app leading to the method being called before the connection was even established. Sorry for the inconvineance caused.
