### ISSUE TITLE
How to tag 5 members random in the group?

### ISSUE THREAD

**Issue by joelvitorniino** [adiwajshing/Baileys#2255]
```
public top5() {
        const arrayMemberOne = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
        const arrayMemberTwo = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
        const arrayMemberThree = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
        const arrayMemberFour = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
        const arrayMemberFive = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];

        const arrayMembers = [arrayMemberOne, arrayMemberTwo, arrayMemberThree, arrayMemberFour, arrayMemberFive];
        let members = "";
        arrayMembers.forEach((p, i) => members += `@${arrayMembers[i].replace('@s.whatsapp.net', '')}\n`)

        return { arrayMember: arrayMembers, stringMembers: members };
    };
    
    await conn.sendMessage(jid, { text: `Top 5: ${utils.commandSlice(msg.message.conversation, 5)}\n${groupLib.top5().stringMembers}`, mentions: groupLib.top5().arrayMember });
```

I tried this, but isn't work. How to tag 5 members random?

**Comment by undefined-60** [comment]
> ```
> public top5() {
>         const arrayMemberOne = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
>         const arrayMemberTwo = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
>         const arrayMemberThree = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
>         const arrayMemberFour = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
>         const arrayMemberFive = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
> 
>         const arrayMembers = [arrayMemberOne, arrayMemberTwo, arrayMemberThree, arrayMemberFour, arrayMemberFive];
>         let members = "";
>         arrayMembers.forEach((p, i) => members += `@${arrayMembers[i].replace('@s.whatsapp.net', '')}\n`)
> 
>         return { arrayMember: arrayMembers, stringMembers: members };
>     };
>     
>     await conn.sendMessage(jid, { text: `Top 5: ${utils.commandSlice(msg.message.conversation, 5)}\n${groupLib.top5().stringMembers}`, mentions: groupLib.top5().arrayMember });
> ```
> 
> Eu tentei isso, mas não é trabalho. Como marcar 5 membros aleatoriamente?

Usa um for que repete 5 vezes o código de pegar 1 membro aleatório e jogue em uma array

**Comment by joelvitorniino** [comment]
> > ```
> > public top5() {
> >         const arrayMemberOne = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
> >         const arrayMemberTwo = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
> >         const arrayMemberThree = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
> >         const arrayMemberFour = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
> >         const arrayMemberFive = this.arrayMembers[Math.round(Math.random() * this.arrayMembers.length)];
> > 
> >         const arrayMembers = [arrayMemberOne, arrayMemberTwo, arrayMemberThree, arrayMemberFour, arrayMemberFive];
> >         let members = "";
> >         arrayMembers.forEach((p, i) => members += `@${arrayMembers[i].replace('@s.whatsapp.net', '')}\n`)
> > 
> >         return { arrayMember: arrayMembers, stringMembers: members };
> >     };
> >     
> >     await conn.sendMessage(jid, { text: `Top 5: ${utils.commandSlice(msg.message.conversation, 5)}\n${groupLib.top5().stringMembers}`, mentions: groupLib.top5().arrayMember });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Eu tentei isso, mas não é trabalho. Como marcar 5 membros aleatoriamente?
> 
> Usa um for que repete 5 vezes o código de pegar 1 membro aleatório e jogue em uma array

**Comment by joelvitorniino** [comment]
Obrigado!
