### ISSUE TITLE
[BUG]Login fail with “Multi-device beta not joined ”

### ISSUE THREAD

**Issue by is99zsq** [adiwajshing/Baileys#2256]
**Describe the bug**
QR Scan Login return "Multi-device beta not joined" and Fail 

But cannot find any MD beta option from UI

seem like the  PROTOCOL is updated?

**To Reproduce**
1. new register number on Android
2. baileys start to QR Scan

**Expected behavior**
Android Scan  Login

**Environment (please complete the following information):**
 - Is this on a server? NO
 - What do your `connectOptions` look like?  NORMAL
 - Do you have multiple clients on the same IP?  NO
 - Are you using a proxy? NO

**Additional context**
Android Version 2.22.14.71

**Comment by jurajmatus** [comment]
You need to do this in WhatsApp, go to linked devices and somewhere there is an option to join Multidevice program
