### ISSUE TITLE
If there is someone who can fix the .update command, please give me a massage on this number.

### ISSUE THREAD

**Issue by vihangayt0** [adiwajshing/Baileys#2257]
If there is someone who can fix the .update command, please give me a massage on this number.
wa.me/94762898541

**Comment by SheIITear** [comment]
bruh

**Comment by BlackAmda** [comment]
BRUH!! Please don't use issues to ask your stupid questions. (Sorry but have to say it)

You can use : 
Discussions - https://github.com/adiwajshing/Baileys/discussions
Join Discord - https://discord.gg/WeJM5FP9GG

**Comment by vihangayt0** [comment]
> BRUH!! Please don't use issues to ask your stupid questions. (Sorry but have to say it)
> 
> You can use : Discussions - https://github.com/adiwajshing/Baileys/discussions Join Discord - https://discord.gg/WeJM5FP9GG
> 
> AND, PLEASE CLOSE YOUR PREVIOUS ISSUES.
> 
> ![close-issue-select-reason](https://user-images.githubusercontent.com/83172207/195756435-edc83954-22e2-40b5-a754-14a71868cc86.png)

okay

**Comment by vihangayt0** [comment]
closed
