### ISSUE TITLE
[BUG] sometimes stop alone

### ISSUE THREAD

**Issue by naylachan** [adiwajshing/Baileys#2260]
I turn on the bot, but a few minutes later the bot stops and displays a log like this, anyone know a solution for this?
Open image :
https://i.ibb.co/ZxHhZd3/Screenshot-2022-10-14-12-30-48-34-3796354b0bd5993045f3f41216646e5c.jpg

**Comment by MaznAbdullah** [comment]
i think whatsapp server ban your ip .

**Comment by FERDIZ-afk** [comment]
> I turn on the bot, but a few minutes later the bot stops and displays a log like this, anyone know a solution for this? Open image : https://i.ibb.co/ZxHhZd3/Screenshot-2022-10-14-12-30-48-34-3796354b0bd5993045f3f41216646e5c.jpg

is it when the bot leaves the group

**Comment by naylachan** [comment]
> saya pikir server whatsapp melarang ip Anda.

Tidak, Saya mencoba run bot kembali dan berhasil, tetapi beberapa saat kemudian ini kembali seperti ini

> i think whatsapp server ban your ip .

No, I tried to run the bot again and it worked, but a while later this

**Comment by naylachan** [comment]
> > I turn on the bot, but a few minutes later the bot stops and displays a log like this, anyone know a solution for this? Open image : https://i.ibb.co/ZxHhZd3/Screenshot-2022-10-14-12-30-48-34-3796354b0bd5993045f3f41216646e5c.jpg
> 
> is it when the bot leaves the group

No

**Comment by FERDIZ-afk** [comment]
> > > I turn on the bot, but a few minutes later the bot stops and displays a log like this, anyone know a solution for this? Open image : https://i.ibb.co/ZxHhZd3/Screenshot-2022-10-14-12-30-48-34-3796354b0bd5993045f3f41216646e5c.jpg
> > 
> > 
> > is it when the bot leaves the group
> 
> No

in bot base hisoka and ichigo-kurosaki that rarely happens

**Comment by Cosm1cBug** [comment]
I'm also getting this same error.

Any help appreciated.

Tnx

**Comment by naylachan** [comment]
> 

Any suggestions for this?
