### ISSUE TITLE
[BUG] useSingleFileAuthState error

### ISSUE THREAD

**Issue by Eximinati** [adiwajshing/Baileys#2261]
**Describe the bug**
sometimes its say useSingleFileAuth is not a function

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**
![image](https://user-images.githubusercontent.com/72595444/195771969-d8bb2d6f-0df3-4ca4-8b96-28cf8b359b80.png)
![image](https://user-images.githubusercontent.com/72595444/195772219-84995669-d575-4645-9b00-d10e126fafe6.png)

**Comment by phenriquec** [comment]
hi,

how to convert to javascript?

import MAIN_LOGGER from '../src/Utils/logger'

const logger = MAIN_LOGGER.child({ })
logger.level = 'trace'

tks

**Comment by fazonetea** [comment]
useSingleFileAuthState is the best for session according to me

**Comment by Eximinati** [comment]
Already figured out the problem unlike some nerds who just came to thumb down my issue

**Comment by Eximinati** [comment]
🐦

**Comment by laudsonfelipe** [comment]
> autor

And how did you solve your problem?
