### ISSUE TITLE
setstatus error

### ISSUE THREAD

**Issue by vihangayt0** [adiwajshing/Baileys#2263]
![Screenshot_2022-10-14-15-23-54-305_com android chrome](https://user-images.githubusercontent.com/96816258/195819778-69d89668-86de-4004-b7cf-840742c16c3b.jpg)
I set the time to auto bio. After about a minute I got this error.

**Comment by guiireal** [comment]
This doesn't seem like a bug in Baileys, but in the environment where you're running it.

**Comment by FERDIZ-afk** [comment]
> ![Screenshot_2022-10-14-15-23-54-305_com android chrome](https://user-images.githubusercontent.com/96816258/195819778-69d89668-86de-4004-b7cf-840742c16c3b.jpg) I set the time to auto bio. After about a minute I got this error.

Be careful if your whatsapp account is blocked

**Comment by FERDIZ-afk** [comment]
> This doesn't seem like a bug in Baileys, but in the environment where you're running it.

True
