### ISSUE TITLE
[BUG] Key argument must be one of type

### ISSUE THREAD

**Issue by X-KERING** [adiwajshing/Baileys#2268]
(node:3259) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:3259) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined

**Comment by SamPandey001** [comment]
Seems like mistake in defining path.
If you send your code, would be better.

Type received "undefined".
