### ISSUE TITLE
GroupMetadata

### ISSUE THREAD

**Issue by bakhti31** [adiwajshing/Baileys#227]
List all participant on group

**Comment by itacirgabral** [comment]
You can use `conn.groupMetadata("123-432@g.us")`
```javascript
{
  id: '123-432@g.us',
  owner: '432@c.us',
  subject: 'TEST GROUP 07',
  creation: 1605021081,
  participants: [
    { id: '213212312@c.us', isAdmin: false, isSuperAdmin: false },
    { id: '432@c.us', isAdmin: true, isSuperAdmin: true }
  ],
  subjectTime: 1605021081,
  subjectOwner: '432@c.us'
}
```

**Comment by arl03** [comment]
Then, how to get all participants id on group?

**Comment by bakhti31** [comment]
Okey, thanks that helpfull

**Comment by bakhti31** [comment]
I have result like this
undefined, title: undefined, description: undefined
Object [JSON] {}
628xxxxxxxxx-16xxxxxxx@g.us

From this code
const metadata = await conn.groupMetadata(id)
console.log(JSON.id + ", title: " + JSON.subject + ", description: " + JSON.desc)                   console.log(JSON)                                 console.log(id)

How to get return as well?

**Comment by arl03** [comment]
Try
const metaData = await conn.groupMetaData(id)
console.log(metaData.id, ", title: " + metaData.subject + ",description: " + metaData.desc)

**Comment by bakhti31** [comment]
> Try
> const metaData = await conn.groupMetaData(id)
> console.log(metaData.id + ", title: " + metaData.subject + ",description: " + metaData.desc)

okay thanks, i think it's cause variable name, cause when i change to metaData the result is avaible, and when i follow your script conn.groupMetaData it's getting error says it not function, but thanks. that worked
