### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jayant-080** [adiwajshing/Baileys#2272]
Stream Errored (restart required)
statuscode : 515

**Comment by VEXG** [comment]
Basicly you didnt read the documentaion correctly..

here is a section that handling the status code
https://github.com/adiwajshing/Baileys#connecting

**Comment by jayant-080** [comment]
yeah my bad its running fine now ,, its because i am not good at programming ,,can u tell me can we send message without recieving message with baileys ,, because i am getting precondition required message when i try to send message
