### ISSUE TITLE
Possible Request option for - Mention Group user as silent  

### ISSUE THREAD

**Issue by mzayn** [adiwajshing/Baileys#2273]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**

---------------

possible baileys - do like this > can mention groups as silently > Silently mention all group members in the message  ?

like this sample. > can do for mention group as silent.

![image](https://user-images.githubusercontent.com/15009301/196905995-e0a0fc8e-8149-4c68-a11f-d17d65ae0973.png)

if can le me know. 

Thanks

**Comment by aidulcandra** [comment]
client.sendMessage(
  jid,
  {
    text: "Silently mention",
    mentions: [/*list all the ids to mention*/],
  }
)

**Comment by Akkun3704** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature**
> 
> possible baileys - do like this > can mention groups as silently > Silently mention all group members in the message ?
> 
> like this sample. > can do for mention group as silent.
> 
> ![image](https://user-images.githubusercontent.com/15009301/196905995-e0a0fc8e-8149-4c68-a11f-d17d65ae0973.png)
> 
> if can le me know.
> 
> Thanks

Try this
```javascript
const { participants } = await sock.groupMetadata(jid)

sock.sendMessage(jid, { text: 'your text', mentions: participants.map(x => x.id) })
```

**Comment by mzayn** [comment]
> > **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> > 
> > 1. Search through the repo's previous issues
> > 2. Read through the readme at least once
> > 3. Search the docs for the feature you're looking for
> > 
> > **Just describe the feature**
> > possible baileys - do like this > can mention groups as silently > Silently mention all group members in the message ?
> > like this sample. > can do for mention group as silent.
> > ![image](https://user-images.githubusercontent.com/15009301/196905995-e0a0fc8e-8149-4c68-a11f-d17d65ae0973.png)
> > if can le me know.
> > Thanks
> 
> Try this
> 
> ```js
> const { participants } = await sock.groupMetadata(jid)
> 
> sock.sendMessage(jid, { text: 'your text', mentions: participants.map(x => x.id) })
> ```

got error when use 

`ypeError: sock.groupMetadata is not a function`

**Comment by aidulcandra** [comment]
@mzayn sock is the object you create with baileys' makeSocket function

some people may use "client" as the name.

If you use "sock", then maybe you placed the code in the wrong place.

It has to have access to the sock/client object
