### ISSUE TITLE
[BUG] Take Too Long Generate QR

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#2274]
the last few hours get qr code is very long and often timeout ends with error, uncaughtException [UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch() . The promise rejected with the reason "1006".] {
   code: 'ERR_UNHANDLED_REJECTION'
}

has anyone experienced the same thing?

**Comment by ahmedRSA** [comment]
did you find solution?
