### ISSUE TITLE
[BUG] event promote and demote

### ISSUE THREAD

**Issue by areltiyan** [adiwajshing/Baileys#228]
**To Reproduce**
1. make event promote and demote
2. Not showing log in command prompt

code : 
`conn.on ('group-participants-promote', async(msg) => console.log(msg))  `

conn option : 
```
        const conn = new WAConnection();
        conn.connectOptions = {
            regenerateQRIntervalMs: 15_000,
            maxIdleTimeMs: 45_000,
            waitOnlyForLastMessage: false,
            waitForChats: true,
            maxRetries: Infinity,
            connectCooldownMs: 3_000,
            phoneResponseTime: 10_000,
            alwaysUseTakeover: true,
        }

        conn.autoReconnect = ReconnectMode.onConnectionLost;
```

not showing ss : 
![image](https://user-images.githubusercontent.com/54056041/98833533-bb2a9800-2470-11eb-9148-d139148933ef.png)

**Comment by areltiyan** [comment]
```
conn.on ('CB:Chat', json => { 
            console.log (json)
        })
```

show 
![image](https://user-images.githubusercontent.com/54056041/98837531-a56ba180-2475-11eb-9944-a6b3454591f8.png)
`["Chat",{"id":"xxxxxx31-xxxxxx5401@g.us","cmd":"action","data":["demote","xxxxxx097@c.us",{"participants":["xxxxxx320@c.us"]}]}]`

**Comment by itacirgabral** [comment]
I can confirm the bug

On my logs:
```
 s12,["Chat",{"id":"55xxxxxxxxxx-yyyyyyyyyy@g.us","cmd":"action","data":["promote","55xxxxxxxxxx@c.us",{"participants":["55xxxxxxxXXX@c.us"]}]}]
    unhandled: true
    class: "Baileys"

(...)

s14,["Chat",{"id":"55xxxxxxxxxx-yyyyyyyyyy@g.us","cmd":"action","data":["demote","55xxxxxxxxxx@c.us",{"participants":["55xxxxxxxXXX@c.us"]}]}]
    unhandled: true
    class: "Baileys"
```

`unhandled: true` means Baileys didn't get the callback

**Comment by adiwajshing** [comment]
Thanks for pointing this out. The latest commit fixes this issue with some changes to the way group events work. Please check the readme for reference

**Comment by areltiyan** [comment]
@adiwajshing  can you make event if User added into new group?

**Comment by areltiyan** [comment]
oh i see event 'chat-new' working now. Thanks.

**Comment by areltiyan** [comment]
@adiwajshing you maybe forget to add this.
![image](https://user-images.githubusercontent.com/54056041/99005645-be5a7c80-2573-11eb-9ddb-0177025e7b63.png)

just a suggestion maybe change this event name because this is will make 2 output log in event 
![image](https://user-images.githubusercontent.com/54056041/99005735-e9dd6700-2573-11eb-8c1b-463b5451df19.png)

log
![image](https://user-images.githubusercontent.com/54056041/99006020-653f1880-2574-11eb-839e-b34273c8005c.png)

**Comment by areltiyan** [comment]
and now if i put 'message-new' event

event 'group-participants-promote' not triggered
