### ISSUE TITLE
precondition required

### ISSUE THREAD

**Issue by jayant-080** [adiwajshing/Baileys#2280]
when i am trying to send a message  outside any event i am getting precondition required error

**Comment by zhinea** [comment]
same issue

**Comment by serra9311** [comment]
same issue

**Comment by serra9311** [comment]
```
12-09 13:49:20.174: Error: Connection Closed
12-09 13:49:20.174:     at sendRawMessage (/home/ubuntu/whatsapp-mergedb/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:49:19)
12-09 13:49:20.174:     at sendNode (/home/ubuntu/whatsapp-mergedb/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:60:16)
12-09 13:49:20.174:     at query (/home/ubuntu/whatsapp-mergedb/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:124:15)
12-09 13:49:20.174:     at Object.profilePictureUrl (/home/ubuntu/whatsapp-mergedb/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:375:30)
12-09 13:49:20.174:     at Timeout._onTimeout (/home/ubuntu/whatsapp-mergedb/model/WASocket_model.js:299:37)
12-09 13:49:20.174:     at listOnTimeout (node:internal/timers:559:17)
12-09 13:49:20.174:     at processTimers (node:internal/timers:502:7) {
12-09 13:49:20.174:   data: null,
12-09 13:49:20.174:   isBoom: true,
12-09 13:49:20.174:   isServer: false,
12-09 13:49:20.174:   output: {
12-09 13:49:20.174:     statusCode: 428,
12-09 13:49:20.174:     payload: {
12-09 13:49:20.174:       statusCode: 428,
12-09 13:49:20.174:       error: 'Precondition Required',
12-09 13:49:20.174:       message: 'Connection Closed'
12-09 13:49:20.174:     },
12-09 13:49:20.174:     headers: {}
12-09 13:49:20.174:   }
12-09 13:49:20.174: }
always have this problem

```

**Comment by Arthur-bl-dev** [comment]
Same problem here.

**Comment by moskoweb** [comment]
Same problem here.

**Comment by dsandrade** [comment]
Same problem here

**Comment by jludere** [comment]
same problem

**Comment by zLucasKk** [comment]
It's probably a performance issue that causes a WhatsApp request block.
This error affects probably everyone, a thing you can do to minimize it is optimize your code and logic to make less load between client and server, this works fine for me, rarely this error appear after a optimization.

**Comment by zhinea** [comment]
> It's probably a performance issue that causes a WhatsApp request block. This error affects probably everyone, a thing you can do to minimize it is optimize your code and logic to make less load between client and server, this works fine for me, rarely this error appear after a optimization.

can you tell what you optimized

**Comment by zLucasKk** [comment]
> > It's probably a performance issue that causes a WhatsApp request block. This error affects probably everyone, a thing you can do to minimize it is optimize your code and logic to make less load between client and server, this works fine for me, rarely this error appear after a optimization.
> 
> can you tell what you optimized

I optimized all my code and some functions to make it more accurate.
I switched `if` to `switch`, discarded some lines, request informations just when is really needed like ```typescript sock.groupMetadata(jid)```.

**Comment by zLucasKk** [comment]
Anyway, another bug is related about WebSocket connection break, it happens always a response don't get a good reply, for example, when you breakpoint in debugging, that's really annoying, I can't even debug for search the problem. 😒

**Comment by zhinea** [comment]
> > > It's probably a performance issue that causes a WhatsApp request block. This error affects probably everyone, a thing you can do to minimize it is optimize your code and logic to make less load between client and server, this works fine for me, rarely this error appear after a optimization.
> > 
> > 
> > can you tell what you optimized
> 
> I optimized all my code and some functions to make it more accurate. I switched `if` to `switch`, discarded some lines, request informations just when is really needed like `sock.groupMetadata(jid)`.

but my app only sends messages, set seen message and set typing message

**Comment by zhinea** [comment]
how i can optimize it?

**Comment by zLucasKk** [comment]
> > > > It's probably a performance issue that causes a WhatsApp request block. This error affects probably everyone, a thing you can do to minimize it is optimize your code and logic to make less load between client and server, this works fine for me, rarely this error appear after a optimization.
> > > 
> > > 
> > > can you tell what you optimized
> > 
> > 
> > I optimized all my code and some functions to make it more accurate. I switched `if` to `switch`, discarded some lines, request informations just when is really needed like `sock.groupMetadata(jid)`.
> 
> but my app only sends messages, set seen message and set typing message



> how i can optimize it?

Probably you're trying to bypass WhatsApp spam detection with "set seen" and "set typing", but for real, its not needed (self assuming, my bot is working for about 2 months of intense development, anything happens to my bot's WhatsApp account.), try to remove all of them and just send messages.

By the way, review your entire code and search for manners to make it easier for your server/host at first.

Baileys is a unstable library, sadly.

**Comment by naufkia** [comment]
same here, any solution right now?

**Comment by dsandrade** [comment]
there is any solution?

**Comment by serra9311** [comment]
??

**Comment by enmanuelmag** [comment]
I thinks that the lib is outdated for the current WhatsApp API and is imposible to use it

**Comment by arugaz** [comment]
> when i am trying to send a message outside any event i am getting precondition required error

you just need to check if the socket is connected or not, it works fine for me
![image](https://user-images.githubusercontent.com/53950128/205043343-216c171f-81ac-4a4f-b5ff-abeb150c5cde.png)

**Comment by juaose** [comment]
Since I  started checking if an ID exists on WA, I haven't got any more 428 errors.

Such as...

`const [result] = await whatsApp.onWhatsApp(jid);

    if (!result || !result.exists) {
      //handle this
      // return, throw, etc
     return;
    }

    //id does exist on WA
    await whatsApp.sendMessage(
      result.jid,
      {
        text: "hi cutie pie",
      }
    );

`
