### ISSUE TITLE
Possible Bailey .sendMessage() > do Push Name (name /username wa) in variable $name ? let me know

### ISSUE THREAD

**Issue by mzayn** [adiwajshing/Baileys#2282]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**

Hello,

want ask, can i know the code for > sendMessage > push sender name with some with using variable {name} 

if Bailey possible to do that, let me know by ping to me  ?

thanks

**Comment by undefined-60** [comment]
> **Antes de adicionar este problema, certifique-se de fazer o seguinte para garantir que não seja uma duplicata:**
> 
> 1. Pesquise nas edições anteriores do repositório
> 2. Leia o leia-me pelo menos uma vez
> 3. Pesquise nos documentos o recurso que você está procurando
> 
> **Apenas descreva o recurso**
> 
> Olá,
> 
> quero perguntar, posso saber o código para > sendMessage > enviar o nome do remetente com alguns usando a variável {name}
> 
> se Bailey possível fazer isso, deixe-me saber por ping para mim?
> 
> obrigado

Quando uma mensagem é recebida ele provavelmente vem com o nome do remetente, agora se você quizer enviar para alguém sem ter recebido uma mensagem, não sei o código
