### ISSUE TITLE
Pin Contact

### ISSUE THREAD

**Issue by Valentine-Mario** [adiwajshing/Baileys#229]
Is there a method to pin a user whatsapp contact? 
I'm not referring to the pin chat method which I'm aware of.

**Comment by itacirgabral** [comment]
https://github.com/adiwajshing/Baileys#modifying-chats


```javascript
const response = await conn.modifyChat (jid, ChatModification.pin) // pin the chat
```

Please test if it really works and report it to us.

**Comment by Valentine-Mario** [comment]
I tried this method. But it seems this only works for when pinning chat and not pinning contact. eg if I write
`
await conn.modifyChat("2349033720345@s.whatsapp.net", ChatModification.pin)
`

I would get an error of "2349033720345@s.whatsapp.net not found in the chat.

**Comment by adiwajshing** [comment]
You can't pin contacts

**Comment by ekucet** [comment]
> Is there a method to pin a user whatsapp contact?
> I'm not referring to the pin chat method which I'm aware of.

did you find any solution?

**Comment by Valentine-Mario** [comment]
> > Is there a method to pin a user whatsapp contact?
> > I'm not referring to the pin chat method which I'm aware of.
> 
> did you find any solution?

Unfortunately not
