### ISSUE TITLE
Suspicious Link Detector

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#2292]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**

So I just noticed that Whatsapp can now detect suspicpicious link..

How to find that out in baileys?

**Comment by undefined-60** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature**
> 
> So I just noticed that Whatsapp can now detect suspicpicious link..
> 
> How to find that out in baileys?

Acho que você pôde usar algo semelhante ao Whatsapp para detectar links suspeitos por conta própria, normalmente links suspeitos são aqueles com algum caractere estranho como î, ó por exemplo... Um regex para encontar caracteres fora do normal deve bastar.
