### ISSUE TITLE
[BUG] I can't send gif with button

### ISSUE THREAD

**Issue by Salientekill** [adiwajshing/Baileys#2294]
Every time I try to send a gif with a button it is not sent as a gif but as a video

**Comment by Vynn-SOLO** [comment]
> Every time I try to send a gif with a button it is not sent as a gif but as a video

Try this

const buttonGIF = { 
        video: ./Media/ma_gif.mp4, 
        caption: "hello!",
        gifPlayback: true,
        buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
  {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
    },
]

const buttonMessage = {
    text: "Hi it's button message",
    footer: 'Hello World',
    buttons: buttons,
    headerType: 1
}

const sendMsg = await sock.sendMessage(id, buttonMessage)
