### ISSUE TITLE
No Words now👀

### ISSUE THREAD

**Issue by SamPandey001** [adiwajshing/Baileys#2295]
WhatsApp down!!
Not a issue at Baileys. Just an information.
I rechecked code almost 7 times where's mistake,No qr is coming.

Lately i saw this.
If u r facing same. Keep patience.😂
![Screenshot_2022-10-25-13-58-07-81_680d03679600f7af0b4c700c6b270fe7](https://user-images.githubusercontent.com/104565822/197724219-d11b2040-2543-4bcc-92bb-09765b5e2b5b.jpg)

**Comment by makanSukros** [comment]
Its not bug from this library please close your issue

**Comment by Mandy-Kunh** [comment]
> Its not bug from this library please close your issue

Yeah bro,ik that. It was just a information for others.
