### ISSUE TITLE
[BUG] Message Upsert Cannot Fire After Scan QR Code

### ISSUE THREAD

**Issue by makanSukros** [adiwajshing/Baileys#2296]
After QR Code appears and scanning, event messages upsert cannot fire, but if im stop and start again from exist session, messages upsert fire again

**Comment by makanSukros** [comment]
ws.on('CB:message', (node) => {
        console.log('Receiving New Message');
        processNodeWithBuffer(node, 'processing message', handleMessage);
    });

I've tried to check this function but it doesn't trigger when there's a new message

**Comment by irham01** [comment]
same issue

**Comment by nogats07** [comment]
are you using the master branch?

**Comment by makanSukros** [comment]
> are you using the master branch?

Yes im using master branch

**Comment by bentacos** [comment]
> > are you using the master branch?
> 
> Yes im using master branch

it's still working on 4.4.0

**Comment by rizrmd** [comment]
> > > are you using the master branch?
> > 
> > 
> > Yes im using master branch
> 
> it's still working on 4.4.0

Where do I get 4.4.0 ? in npm ?

**Comment by bentacos** [comment]
> > > > are you using the master branch?
> > > 
> > > 
> > > Yes im using master branch
> > 
> > 
> > it's still working on 4.4.0
> 
> Where do I get 4.4.0 ? in npm ?

yes, the last stable release

**Comment by MaznAbdullah** [comment]
any update ?

**Comment by irham01** [comment]
@adiwajshing

**Comment by DionlenoPiata** [comment]
+1

**Comment by undefined-60** [comment]
Não vi este problema por aqui ainda, está normal para min (uso versão de borda)

**Comment by bigbdigital** [comment]
Same problem here. the problem occurs only after read qr code. chat history not too. if reset node js, message.upsert back to work, but history not sync, only new messages

**Comment by bigbdigital** [comment]
the last release 4.4.0 not have makeCacheableSignalKeyStore function

**Comment by makanSukros** [comment]
> Same problem here. the problem occurs only after read qr code. chat history not too. if reset node js, message.upsert back to work, but history not sync, only new messages

Did you have the previous library backup before the update? I went back to using the backup library

**Comment by bigbdigital** [comment]
> 

No, I do not have. can you send it to me please?

**Comment by MaznAbdullah** [comment]
wrap code
```
if( events['connection.update']?.isNewLogin == true ){
	await delay(1000);
	sock.ws.close(undefined);
	sock.ev.removeAllListeners();
	startSock()
}
```

**Comment by makanSukros** [comment]
Still not work

**Comment by makanSukros** [comment]
> await delay(1000);
> 	sock.ws.close(undefined);
> 	sock.ev.removeAllListeners();
> 	startSock()

after implementation this, im get infinity loop on connection update

**Comment by makanSukros** [comment]
Solved with latest version commit

**Comment by irham01** [comment]
> Solved with latest version commit

I use latest version commit but there is no change
