### ISSUE TITLE
[Enhancement] Private reply to group messages

### ISSUE THREAD

**Issue by coolnickname** [adiwajshing/Baileys#23]
I have done some testing on this topic and figured I'd share the results with you in case you want to add support for this feature. I would make a PR myself but I'm new to javascript so I don't think that's a good idea (you should see my code :stuck_out_tongue:)

The layout for the message object should be the following:
```JSON
"extendedTextMessage": {
	"text": "test",
	"contextInfo": {
		"stanzaId": "3AEQZF32B6040467A109",
		"participant": "xxx@s.whatsapp.net",
		"remoteJid": "xxx-xxx@g.us",
		"quotedMessage": {
			"conversation": ""
		}
	}
}
```
"text" is pretty self explanatory, but the contextInfo works a bit different than with a normal quoted message. The stanzaId has to be an actual id of a message sent in the group. As you probably know you can spoof the text in a quoted message by just putting any text you want in the "conversation" element, that doesn't work (reliably) here.

The client of the recipient pulls the actual message text from the group using the stanza id, so as long as the recipient is the group and stanzaId is a valid message id the text you put under "quotedMessage" is overwritten by the actual message. 

There is some funkyness to it, though. For example, if you do add some text under "quotedMessage" the sender will see the spoofed text, but the recipient will have the spoofed text overwritten by the actual text pulled from the stanzaId.

I have done a lot of testing with this and found a lot of interesting results. But without going into the details this is how to safely implement this feature: 
If you don't want any glitchyness for the recipient, stanzaId should always be a valid message id in the group of "remoteJid" and the recipient must have been in the group when the message was sent so it can query the stanzaId. The participant you're quoting does not have to be the person you send the message to. If you also don't want any glitches on the sender's end you need to fill in the message text in quotedMessage with the text from the original message.

Sorry for the wall of text, I hope you can make something of it. If you need me to explain something or need more info/an example I'd be happy to help.

**Comment by coolnickname** [comment]
Obviously this is another low priority enhancement as it's not really a useful feature and it's pretty easy to just make your own message object using the info above and send it using client.sendMessage.

**Comment by adiwajshing** [comment]
Thanks lot for this! This really is quite interesting. I wouldn't have figured this out on my own. Don't worry about the quality of your code too much, nobody's here to judge you for it.

So, the only was to verify if the message is valid is by fetching the message from the group & then cross-checking it. I think this'll be too cumbersome for most cases. However, you could add a specialized case for the send message function for exactly this purpose. I'll make some minor changes in the code to allow that. You could submit a PR after that?

**Comment by coolnickname** [comment]
> So, the only was to verify if the message is valid is by fetching the message from the group & then cross-checking it.

Yes, but in my eyes the burden of making sure the message is valid is the user's responsibility, not the API's.

After looking at the code for sendTextMessage I think it wouldn't be too difficult to support this feature by just adding a couple of extra lines around [here](https://github.com/adiwajshing/Baileys/blob/master/WhatsAppWeb.Send.js#L48).

While coming up with an idea of how to implement this I noticed a bug too: when making the contextInfo you set "participant" to the "remoteJid" of the quoted message, which works for private messages but not for groups. 

To fix the bug we'd have to do something like this:
```
if quoted.key.remoteJid is a group jid then:
     'participant' is set to 'quoted.participant'. 
else:
    'participant' is set to 'quoted.key.remoteJid'. 
endif
```
Because it's a group 'quoted.participant' is the jid of the actual sender, in private messages it's still 'quoted.key.remoteJid'.

After this we can add the functionality of the private replies to group messages:
```
if the jid of the person we're sending the message to is private chat AND if quoted.key.remoteJid is a group jid then:
//this means it's a private reply from a group
     add the element 'remoteJid' to 'contextInfo' and set it to 'quoted.key.remoteJid'
else:
//this means it's either a private reply to a private chat or a group reply to a group chat. So no extra action is required.

endif
```

While I could definitely add this in a PR as it's just a couple of lines of if/else statements, I don't think I will be able to test it as I have no experience with npm and node so I don't know how to use my local version of the baileys package instead of the npm installed one :V

**Comment by adiwajshing** [comment]
Oh, I just added this entire fix in the latest commit. You can quote other messages when sending all kinds of (including media) messages.

I thought you were interested in adding an automated check to validate the message being quoted?

**Comment by coolnickname** [comment]
How do you mean validate?

And looking at the code it does seem like what you changed would work, if that's the case feel free to close this issue.

**Comment by adiwajshing** [comment]
By validate, I mean actually fetch the message corresponding to the stanzaId being quoted & verify the text before sending.

The changes do work, tested it out. Also, the spoofing messages loophole you gave is quite cool.

**Comment by coolnickname** [comment]
Oh no, sorry for the misunderstanding.

While I can see it being a logical addition, I think it's the responsibility of the person using this API to keep track of the message text in the same way they kept track of the message id, should they want to do so. Not to mention the only side effect of not passing the correct text is a visual glitch on the sender's end, so I don't think it's worth querying the message text.

**Comment by adiwajshing** [comment]
Oh, no worries. Glad it’s resolved, I’m closing now.
