### ISSUE TITLE
 BaileysError: Unexpected status in 'action': Conflict(409)

### ISSUE THREAD

**Issue by SuyKingsleigh** [adiwajshing/Baileys#230]
Every time I try to delete a chat I got this error: 

Unexpected status in 'action': Conflict(409)

    const chats = await conn.chats.all();
    for (const c of chats) {
        let jid = c.jid
        console.log("Deleting " + jid);
        conn.deleteChat(jid)
            .then(d => console.log("Chat deleted successfully"))
            .catch(err => console.log("Failed to delete: " + err));
    }

**Comment by adiwajshing** [comment]
WA has been introducing these lately, will look into it

**Comment by itacirgabral** [comment]
just to poke, what if you serialize the deletion batch?

```javascript
const delay = t => x => new Promise((res, rej) => {
  setTimeout(() => {
    res(x)
  }, t)
})

const mkAsyncSerial = f => async function* (arr) {
  for (const el of arr) {
    yield f(el)
  }
}

const asyncSerial300 = mkAsyncSerial(delay(300))
;(async () => {
  for await (chat of asyncSerial300(chats)) {
    // delete chat here, one at a time.
  }
})()
```

**Comment by adiwajshing** [comment]
@itacirgabral this is a genuine bug on Android, I believe. Haven't had the chance to debug

**Comment by pokearaujo** [comment]
same here

**Comment by adiwajshing** [comment]
@pokearaujo @itacirgabral @SuyKingsleigh this should be fixed in the latest commit

**Comment by caiquejjx** [comment]
Im in the latest version but I keep gettin this error when I delete chats... it still deletes but throws the error
