### ISSUE TITLE
can't create TypeScript Compiling

### ISSUE THREAD

**Issue by hardianto-cpu** [adiwajshing/Baileys#2302]
**Describe the bug**
i want to install the latest baileys in my project but get error when using "npm install" command. and then i searched for it in issue but it didn't solve my [issues](https://github.com/adiwajshing/Baileys/issues/1790) (
![Screenshot (5)](https://user-images.githubusercontent.com/74147602/198441893-ee502925-c402-46b3-bd56-0db29e36591e.png)

**Comment by FERDIZ-afk** [comment]
> **Describe the bug** i want to install the latest baileys in my project but get error when using "npm install" command. and then i searched for it in issue but it didn't solve my [issues](https://github.com/adiwajshing/Baileys/issues/1790) ( ![Screenshot (5)](https://user-images.githubusercontent.com/74147602/198441893-ee502925-c402-46b3-bd56-0db29e36591e.png)

Can't your install module Sharp

**Comment by MaznAbdullah** [comment]
edit  src/Utils/messages-media.ts
- const jimp = _jimp?.default || _jimp
+ const jimp = _jimp["default"] || _jimp
