### ISSUE TITLE
300+ Participants

### ISSUE THREAD

**Issue by Piyoxz** [adiwajshing/Baileys#2304]
how come when the bot command is sent to a group of 300+ participants, the message is not sent, but in a group of -200 participants it is sent but it's really slow

**Comment by Piyoxz** [comment]
![image](https://user-images.githubusercontent.com/102013178/198861071-93439040-2139-4327-9294-a4e7c358c477.png)
sometimes like this

**Comment by amiruldev20** [comment]
getmsg

**Comment by BrunoSobrino** [comment]
> getmsg

Bisakah Anda membantu saya mengimplementasikannya di repositori saya?
[https://github.com/BrunoSobrino/TheMystic-Bot-MD](https://github.com/BrunoSobrino/TheMystic-Bot-MD)

**Comment by LZNOXP** [comment]
It is in the example
https://github.com/adiwajshing/Baileys/blob/5e28d2346078cf7d101e5ce1792589d3b90ccb6d/Example/example.ts#L43

**Comment by BrunoSobrino** [comment]
> It is in the example
> 
> https://github.com/adiwajshing/Baileys/blob/5e28d2346078cf7d101e5ce1792589d3b90ccb6d/Example/example.ts#L43

I have tried based on this example but I can not do it successfully. I keep getting messages on hold

Could you help me to implement it in my WhatsApp Bot please? [Contact me in TheShadowBrokers-TEAM@outlook.com](TheShadowBrokers-TEAM@outlook.com)

**Comment by xAbdaziz** [comment]
Did you manage to fix it?

**Comment by xAbdaziz** [comment]
> Did you manage to fix it?

@Piyoxz

**Comment by Piyoxz** [comment]
> > Did you manage to fix it?
> 
> @Piyoxz

nope
