### ISSUE TITLE
send vcard from a chat with vcard stored in json

### ISSUE THREAD

**Issue by wesuRage** [adiwajshing/Baileys#2305]
I need to send a vcard, but its insanely big to put in the code, so i tried to store it with `makeInMemoryStore({})`. Now its stored as json with all the information of it. But i wonder how i could send a vcard with all that same information as in the json file.

Is there any way possible of doing it or just another way of storing a vcard to send for anyone? (and again, its TOO BIG to put directly in the code)

**Comment by Alhar6i** [comment]
> I need to send a vcard, but its insanely big to put in the code, so i tried to store it with `makeInMemoryStore({})`. Now its stored as json with all the information of it. But i wonder how i could send a vcard with all that same information as in the json file.
> 
> Is there any way possible of doing it or just another way of storing a vcard to send for anyone? (and again, its TOO BIG to put directly in the code)

You could save the vCard as a text in a text file and then read it from the text file as a string.
