### ISSUE TITLE
Template message , Button Messages Still not working on iOS? Anyone solve this problem? thanks

### ISSUE THREAD

**Issue by andersling** [adiwajshing/Baileys#2306]
Hi, everyone:
    since august , the Template message , Button Messages are not working on iOS, how is going now? anyone have solved it? big thanks!

**Comment by caiogrigoleto** [comment]
Hi guys, I'm still having the same problem on iOS, did anyone manage to solve it?

**Comment by raphaelvserafim** [comment]
IOS não funciona

**Comment by enoksaju** [comment]
I think now it doesn't work on android either

**Comment by caiogrigoleto** [comment]
Has anyone found a solution to the iOS button or list options issue?
