### ISSUE TITLE
How can i get disconnect reason?

### ISSUE THREAD

**Issue by zskini** [adiwajshing/Baileys#2308]
When the connection is closed I just want to know the reason but baileys gives me a json version of all the data.
How can I find out only the reason from this data?
For example
I only need to separate the reason from the json data I get below, how can I do that?
like: reason = 403
Thanks everyone.

`{"level":30,"time":"2022-11-01T17:27:51.804Z","pid":13248,"hostname":"DESKTOP","class":"baileys","error":{"data":{"reason":"403","location":"odn"},"isBoom":true,"isServer":false,"output":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Connection Failure"},"headers":{}}},"msg":"connection closed"}`

**Comment by burstfreeze** [comment]
```
let err = `{"level":30,"time":"2022-11-01T17:27:51.804Z","pid":13248,"hostname":"DESKTOP","class":"baileys","error":{"data":{"reason":"403","location":"odn"},"isBoom":true,"isServer":false,"output":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Connection Failure"},"headers":{}}},"msg":"connection closed"}`

let obj = JSON.parse(err)

console.log(obj.msg)
```

**Comment by zskini** [comment]
> ```
> let err = `{"level":30,"time":"2022-11-01T17:27:51.804Z","pid":13248,"hostname":"DESKTOP","class":"baileys","error":{"data":{"reason":"403","location":"odn"},"isBoom":true,"isServer":false,"output":{"statusCode":403,"payload":{"statusCode":403,"error":"Forbidden","message":"Connection Failure"},"headers":{}}},"msg":"connection closed"}`
> 
> let obj = JSON.parse(err)
> 
> console.log(obj.msg)
> ```

Thanks

**Comment by frmdeveloper** [comment]
Kamu nanya itu kenapa.
Yaudah biar aku kasih tau ya
