### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nielzie7** [adiwajshing/Baileys#2311]
C:\wp\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:35
    const { creds } = authState;
            ^

TypeError: Cannot destructure property 'creds' of 'authState' as it is undefined.
    at makeSocket (C:\wp\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:35:13)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

iam using @adiwajsing/baileys 4.4.0

**Comment by ju-li** [comment]
I'm running into this issue too. The example in https://github.com/adiwajshing/Baileys#connecting just plain doesn't work

This is the code I'm trying to run:
```import makeWASocket, { DisconnectReason } from '@adiwajshing/baileys'

async function connectToWhatsApp () {
    const sock = makeWASocket.default({
        // can provide additional config here
        printQRInTerminal: true
    })
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                connectToWhatsApp()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
}
// run in main file
connectToWhatsApp()```

**Comment by ju-li** [comment]
The only code I've got to work is the example.ts file: https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts

But that code doesn't work with the current release (v4.4) so you gotta install the edge version `yarn add github:adiwajshing/baileys`

**Comment by LorranX** [comment]
Use baileys Edge version

**Comment by nielzie7** [comment]
> Use baileys Edge version

thanks

**Comment by titiloxx** [comment]
You have to add creds to makeWASocket, Baileys has solve it with its useMultiFileAuthState module
Try this:
```
import { useMultiFileAuthState } from '@adiwajshing/baileys'
...
 const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')

    const sock = makeWASocket({
        auth: {
			creds: state.creds,
			keys: state.keys,
		},
...
```
