### ISSUE TITLE
[BUG] clear chats

### ISSUE THREAD

**Issue by amiruldev20** [adiwajshing/Baileys#2312]
clear chats no work
my code
sock.chatModify({
  delete: true,
  lastMessages: [{ key: m.key, messageTimestamp: m.messageTimestamp }]
},
jid)

**Comment by amiruldev20** [comment]
solved. work in my repo github.com/amiruldev20/Baileys

**Comment by AliAryanTech** [comment]
> solved. work in my repo github.com/amiruldev20/Baileys

Really??
