### ISSUE TITLE
[BUG] It is not possible to update the profile name.

### ISSUE THREAD

**Issue by andresayac** [adiwajshing/Baileys#2317]
It is not possible to update the profile name using the updateProfileName method
```
const updateProfileName = async (session, name) => {
    try {
        return await session.updateProfileName(name)
    } catch {
        return Promise.reject(null) 
    }
}
```

**return** 

`{"level":40,"time":1667996718541,"pid":9088,"hostname":"LAPTOP-SV50PQ66","syncAction":{"syncAction":{"index":"WyJzZW50aW5lbCIsImNyaXRpY2FsX2Jsb2NrIl0=","padding":"","version":3},"index":["sentinel","critical_block"]},"id":"critical_block","msg":"unprocessable update"}`

**Comment by salykingleb** [comment]
+1
