### ISSUE TITLE
[BUG] "messages.upsert" event stopping working

### ISSUE THREAD

**Issue by deriknyvo** [adiwajshing/Baileys#2318]
**Describe the bug**
After disconnecting the device and re-authenticating the QR Code the "messages.upsert" event is no longer triggered

**To Reproduce**
1. Read the QR code
2. On device, on connected devices log out manually (this will make the qrCode print to the screen again)
3. And send a message to the device connected to baileys

**Expected behavior**
Every time the QR code is read it should receive all messages in the "messages.upsert" event

**Environment (please complete the following information):**
 - Is this on a server? 
 -- localhost

 - What do your `connectOptions` look like? 
 -- `printQRInTerminal: true,
		auth: {
			creds: state.creds,
			keys: makeCacheableSignalKeyStore(state.keys, logger),
		},
		msgRetryCounterMap,
		generateHighQualityLinkPreview: true,
		getMessage: async (key) => {
			if (store) {
				const msg = await store.loadMessage(key.remoteJid!, key.id!)
				return msg?.message || undefined
			}

			return {
				conversation: 'hello'
			}
		},
		keepAliveIntervalMs: 20000,
		defaultQueryTimeoutMs: 20000,
		connectTimeoutMs: 30000`

 - Do you have multiple clients on the same IP?
 -- no

 - Are you using a proxy?
-- no

**Additional context**
after inserting some console logs I noticed that the code snippet in the image is executed, but no new event arrives in "messages.upsert"

![image](https://user-images.githubusercontent.com/33598231/200834364-8efb6674-b427-4068-9505-a3381bc674f8.png)

**Comment by makanSukros** [comment]
If you using edge version, try update this lib and try re-scan again

**Comment by zennn08** [comment]
2

**Comment by vishwajit76** [comment]
Sometimes it's not working, but after reinitialize its works.

**Comment by vishwajit76** [comment]
When we link a new device like login into web.whatsapp.com, suddenly "message.upsert" event is stopped, but sending a message is working.

If you have many unread messages, you face this issue.

**Comment by brunovribeiro** [comment]
I have same problem. Did anyone get anything?

**Comment by jtourisNS** [comment]
same problem, no solution yet

**Comment by vishwajit76** [comment]
any update?

**Comment by adiwajshing** [comment]
I believe the latest commit should've resolved this issue. If updating to the latest GH version doesn't resolve -- do comment back

https://github.com/adiwajshing/Baileys/commit/a589e881366eb6110ddbb0a3c2533d48a9e59202

**Comment by zennn08** [comment]
nice, works perfectly for now

**Comment by deriknyvo** [comment]
> I believe the latest commit should've resolved this issue. If updating to the latest GH version doesn't resolve -- do comment back
> 
> [a589e88](https://github.com/adiwajshing/Baileys/commit/a589e881366eb6110ddbb0a3c2533d48a9e59202)

it worked, thanks
