### ISSUE TITLE
Connection change listener

### ISSUE THREAD

**Issue by MuratKaragozgil** [adiwajshing/Baileys#232]
Hi,

I couldn't find custom connection change listener. Can you help to me ? 

```
 const conn = new WAConnection() // instantiate
 conn.autoReconnect = ReconnectMode.onConnectionLost // only automatically reconnect when the connection breaks
```

when connection lost, i need to run some custom functions. 

Thanks,
Best regards

**Comment by adiwajshing** [comment]
Read the [readme](https://github.com/adiwajshing/Baileys#handling-events).

**Comment by MuratKaragozgil** [comment]
Thanks
