### ISSUE TITLE
whatsapp communities message is not going

### ISSUE THREAD

**Issue by rsaisankalp** [adiwajshing/Baileys#2324]
whatsapp communities message is not going

**Comment by rsaisankalp** [comment]
Anytime this feature is coming

**Comment by kaiquebarreto** [comment]
Is it already possible to create communities or notice groups?

**Comment by rsaisankalp1** [comment]
I mean , communities, which is combinations of multiple gruops.
Feature to send in those communities is missing. anyways community creation is secondary
