### ISSUE TITLE
[BUG] button/list button not work.

### ISSUE THREAD

**Issue by Switzg** [adiwajshing/Baileys#2328]
**Describe bug:**

The buttons are not working in the new version, is there any viable solution?

**Comment by MaznAbdullah** [comment]
me 2

**Comment by LZNOXP** [comment]
patching the message is now optional. to patch the message add this to your connectionOption

```js
            patchMessageBeforeSending: (message) => {
                const requiresPatch = !!(
                    message.buttonsMessage ||
                    // || message.templateMessage
                    message.listMessage
                );
                if (requiresPatch) {
                    message = {
                        viewOnceMessage: {
                            message: {
                                messageContextInfo: {
                                    deviceListMetadataVersion: 2,
                                    deviceListMetadata: {},
                                },
                                ...message,
                            },
                        },
                    };
                }

                return message;
            },
```

code from [here](https://github.com/adiwajshing/Baileys/blob/190e6d6bd6c201b7c6787c1e37732ea2bee25d21/src/Utils/messages.ts#L781)

**Comment by 55lindo55** [comment]
> patching the message is now optional. to patch the message add this to your connectionOption
> 
> ```js
>             patchMessageBeforeSending: (message) => {
>                 const requiresPatch = !!(
>                     message.buttonsMessage ||
>                     // || message.templateMessage
>                     message.listMessage
>                 );
>                 if (requiresPatch) {
>                     message = {
>                         viewOnceMessage: {
>                             message: {
>                                 messageContextInfo: {
>                                     deviceListMetadataVersion: 2,
>                                     deviceListMetadata: {},
>                                 },
>                                 ...message,
>                             },
>                         },
>                     };
>                 }
> 
>                 return message;
>             },
> ```
> 
> code from [here](https://github.com/adiwajshing/Baileys/blob/190e6d6bd6c201b7c6787c1e37732ea2bee25d21/src/Utils/messages.ts#L781)

Do we always have to do this procedure? If so, it will be complicated...

**Comment by LZNOXP** [comment]
> Do we always have to do this procedure? If so, it will be complicated...

Why or how is it complicated?

**Comment by 55lindo55** [comment]
> > Do we always have to do this procedure? If so, it will be complicated...
> 
> Why or how is it complicated?

because now we have to add this code every time before transitioning from typesctipt to JavaScript, correct? Or is it just playing this on the connection?

**Comment by LZNOXP** [comment]
> > > Do we always have to do this procedure? If so, it will be complicated...
> > 
> > 
> > Why or how is it complicated?
> 
> because now we have to add this code every time before transitioning from typesctipt to JavaScript, correct? Or is it just playing this on the connection?

What do you mean?

**Comment by 55lindo55** [comment]
> 

toda vez que sai uma atualização da baileys, eu converto ele de typesctipt para JavaScript, certo?! Então... antes da conversão de linguagem, precisaria modificar isso toda vez, ao invés de já vim padrão na baileys

**Comment by 55lindo55** [comment]
> > > > Do we always have to do this procedure? If so, it will be complicated...
> > > 
> > > 
> > > Why or how is it complicated?
> > 
> > 
> > because now we have to add this code every time before transitioning from typesctipt to JavaScript, correct? Or is it just playing this on the connection?
> 
> What do you mean?

every time a baileys update comes out, I convert it from typesctipt to JavaScript, right?! So... before language conversion, I would need to modify this every time, instead of already vim pad

**Comment by 55lindo55** [comment]
> you dont have to modify Baileys directly, (if that's what you mean) you just need to add this to your makeWASocket options
> 
> ```js
> const sock = makeWASocket({
>             // can provide additional config here
>             ...
>             printQRInTerminal: true,
>             patchMessageBeforeSending: (message) => {
>                 const requiresPatch = !!(
>                     message.buttonsMessage ||
>                     // || message.templateMessage
>                     message.listMessage
>                 );
>                 if (requiresPatch) {
>                     message = {
>                         viewOnceMessage: {
>                             message: {
>                                 messageContextInfo: {
>                                     deviceListMetadataVersion: 2,
>                                     deviceListMetadata: {},
>                                 },
>                                 ...message,
>                             },
>                         },
>                     };
>                 }
> 
>                 return message;
>             },
>     })
> ```

oh yes, now i understand

**Comment by erickmanovei** [comment]
> ```js
> patchMessageBeforeSending: (message) => {
>                 const requiresPatch = !!(
>                     message.buttonsMessage ||
>                     // || message.templateMessage
>                     message.listMessage
>                 );
>                 if (requiresPatch) {
>                     message = {
>                         viewOnceMessage: {
>                             message: {
>                                 messageContextInfo: {
>                                     deviceListMetadataVersion: 2,
>                                     deviceListMetadata: {},
>                                 },
>                                 ...message,
>                             },
>                         },
>                     };
>                 }
> 
>                 return message;
>             },
> ```

Using typescript, it is showing this error: Argument of type '{ printQRInTerminal: true; auth: AuthenticationState; patchMessageBeforeSending: (message: any) => any; }' is not assignable to parameter of type 'UserFacingSocketConfig'.

**Comment by LZNOXP** [comment]
> > ```js
> > patchMessageBeforeSending: (message) => {
> >                 const requiresPatch = !!(
> >                     message.buttonsMessage ||
> >                     // || message.templateMessage
> >                     message.listMessage
> >                 );
> >                 if (requiresPatch) {
> >                     message = {
> >                         viewOnceMessage: {
> >                             message: {
> >                                 messageContextInfo: {
> >                                     deviceListMetadataVersion: 2,
> >                                     deviceListMetadata: {},
> >                                 },
> >                                 ...message,
> >                             },
> >                         },
> >                     };
> >                 }
> > 
> >                 return message;
> >             },
> > ```
> 
> Using typescript, it is showing this error: Object literal may only specify known properties, and 'patchMessageBeforeSending' does not exist in type 'UserFacingSocketConfig'.

Use edge version

**Comment by erickmanovei** [comment]
> > > ```js
> > > patchMessageBeforeSending: (message) => {
> > >                 const requiresPatch = !!(
> > >                     message.buttonsMessage ||
> > >                     // || message.templateMessage
> > >                     message.listMessage
> > >                 );
> > >                 if (requiresPatch) {
> > >                     message = {
> > >                         viewOnceMessage: {
> > >                             message: {
> > >                                 messageContextInfo: {
> > >                                     deviceListMetadataVersion: 2,
> > >                                     deviceListMetadata: {},
> > >                                 },
> > >                                 ...message,
> > >                             },
> > >                         },
> > >                     };
> > >                 }
> > > 
> > >                 return message;
> > >             },
> > > ```
> > 
> > 
> > Using typescript, it is showing this error: Object literal may only specify known properties, and 'patchMessageBeforeSending' does not exist in type 'UserFacingSocketConfig'.
> 
> Use edge version

Thanks for your answer!
When I add edge version with the "yarn add github:adiwajshing/baileys" command, my TypeScript project shows this error: "Cannot find module '@adiwajshing/baileys' or its corresponding type declarations."
My code to import is:
import makeWASocket, {
DisconnectReason,
useMultiFileAuthState,
AnyWASocket,
} from '@adiwajshing/baileys';

What I need to do to use edge version in TypeScript project?

**Comment by erickmanovei** [comment]
> 

wow, thanks! Works for me!
For this, I added "@adiwajshing/baileys": "https://github.com/adiwajshing/Baileys.git" in may package.json dependencies, and I needed to update my Whatsapp app.

**Comment by devmitesh** [comment]
@erickmanovei did it fix button and template message issue for ios?

**Comment by erickmanovei** [comment]
> @erickmanovei did it fix button and template message issue for ios?

@devmitesh after change my Baileys version to Edge version and add the code specified in this issue, works in IOS, but, only when I send messages to myself. When I send it to another number, doesnt work.
Is there any solution for this, @LZNOXP ?

**Comment by LZNOXP** [comment]
Maybe you can try [this](https://github.com/adiwajshing/Baileys/issues/2376#issuecomment-1333834487)

**Comment by mzayn** [comment]
> you dont have to modify Baileys directly, (if that's what you mean) you just need to add this to your makeWASocket options
> 
> ```js
> const sock = makeWASocket({
>             // can provide additional config here
>             ...
>             printQRInTerminal: true,
>             patchMessageBeforeSending: (message) => {
>                 const requiresPatch = !!(
>                     message.buttonsMessage ||
>                     // || message.templateMessage
>                     message.listMessage
>                 );
>                 if (requiresPatch) {
>                     message = {
>                         viewOnceMessage: {
>                             message: {
>                                 messageContextInfo: {
>                                     deviceListMetadataVersion: 2,
>                                     deviceListMetadata: {},
>                                 },
>                                 ...message,
>                             },
>                         },
>                     };
>                 }
> 
>                 return message;
>             },
>     })
> ```

i was trying this code but still error on template, button and list message for me 

here my code hope can fix button, template, and list message. also i was trying `viewOnce: true`  still error on > iOS 

```
const client = MytoolBot({
      /** provide an auth state object to maintain the auth state */
      auth: state,
      /** version to connect with */
      version,
      setMaxListeners: 0,
      retryRequestDelayMs: 0,
      /** the WS url to connect to WA */
      waWebSocketUrl: 'wss://web.whatsapp.com/ws/chat',
      /** pino logger */
      logger: pino({
        level: 'silent'
      }),
      /** should the QR be printed in the terminal */
      printQRInTerminal: true,
      
    //   for fix button, template list message 
            patchMessageBeforeSending: (message) => {
                const requiresPatch = !!(
                    message.buttonsMessage ||
                    // || message.templateMessage
                    message.listMessage
                );
                if (requiresPatch) {
                    message = {
                        viewOnceMessage: {
                            message: {
                                messageContextInfo: {
                                    deviceListMetadataVersion: 2,
                                    deviceListMetadata: {},
                                },
                                ...message,
                            },
                        },
                    };
                }

                return message;
            },      
      //
      emitOwnEvents: true,
      treatCiphertextMessagesAsReal: true,
      /** Default timeout for queries, undefined for no timeout */
      defaultQueryTimeoutMs: undefined,
      /** proxy agent */
      agent: undefined,
      /** agent used for fetch requests -- uploading/downloading media */
      fetchAgent: undefined,
      /** 
       * fetch a message from your store 
       * implement this so that messages failed to send (solves the "this message can take a while" issue) can be retried
       * */
      getMessage: undefined
      //
    });
    ```

**Comment by danzok** [comment]
were you able to send the list button?

**Comment by leonetosoft** [comment]
same issue here.
Thanks @mIsPtr. Works for me
