### ISSUE TITLE
How to block or unblock a user?

### ISSUE THREAD

**Issue by Quiec** [adiwajshing/Baileys#233]
Hi,

I looked doc, code and whatsapp-web-reg but i didn't find anything.
How to block or unblock a user?

**Comment by adiwajshing** [comment]
Haven’t added that functionality yet

**Comment by Quiec** [comment]
@adiwajshing, Can you at least find a query? I can write function.

**Comment by Quiec** [comment]
@adiwajshing Any news?

**Comment by adiwajshing** [comment]
@Quiec not yet, you can try observing the traffic yourself and help via a PR?
Read this for a [start](https://github.com/adiwajshing/Baileys/issues/67#issuecomment-658042249)

**Comment by Quiec** [comment]
> @Quiec not yet, you can try observing the traffic yourself and help via a PR?

I did not understand. If we connect with the same information, will two devices accept it at the same time?

**Comment by adiwajshing** [comment]
Not sure what you're asking here

**Comment by itacirgabral** [comment]
## block logs:
```
DEBUG    [2020-11-16 19:49:07.036 +0000] (269399): s12,["Blocklist",{"id":1,"blocklist":["5565VVVVVV95@c.us","55659XXXXXX1@c.us","55XXXXXXXX96@c.us","556XXXXXX707@c.us"]}]
    unhandled: true
    class: "Baileys"
```

## unblock logs:
```
DEBUG    [2020-11-16 19:50:10.607 +0000] (269399): s15,["Blocklist",{"id":1,"blocklist":["55659VVVVV31@c.us","559CCCCCCC96@c.us","556ZZZZZZ707@c.us"]}]
    unhandled: true
    class: "Baileys"
```

https://github.com/adiwajshing/Baileys#writing-custom-functionality

**Comment by adiwajshing** [comment]
@itacirgabral I believe these logs are exactly the same. One can't unambiguously tell what they're doing

**Comment by Quiec** [comment]
@adiwajshing I guess its just adding the blocked list. User is not blocking it.

**Comment by itacirgabral** [comment]
> @itacirgabral I believe these logs are exactly the same. One can't unambiguously tell what they're doing

The first query blocklist length is 4. The second query blocklist length is 3.

I can listen to its events:
```javascript
  conn.on('CB:Blocklist', json => {
    console.log('CB:Blocklist')
    console.log(JSON.stringify(json, null, 2))
  })
```

`CB:Blocklist` happens after `credentials-updated` and before `s1,{"status":200}`.
`CB:Blocklist` happens every time someone is (un)blocked too.

## How to write custom queries?
How do I list the Blocklist? How do I set the Blocklist?

```javascript
// bad code
conn.query({ json: [ 'query', 'Blocklist' ] })

// returns { status: 400 }
```

**Comment by adiwajshing** [comment]
@itacirgabral  Try blocking someone via WA Web & see the query?

**Comment by Quiec** [comment]
> @itacirgabral Try blocking someone via WA Web & see the query?

Sending binary. I tried decode but I can't...

**Comment by itacirgabral** [comment]
> @itacirgabral Try blocking someone via WA Web & see the query?

![Screenshot from 2020-11-29 17-40-03](https://user-images.githubusercontent.com/6052177/100554307-38744c00-326a-11eb-8585-ef0c3c67a954.png)

**Comment by Quiec** [comment]
@adiwajshing Any news? Do you decoded it?

**Comment by Quiec** [comment]
don't close

**Comment by edgardmessias** [comment]
```js
// Block
[
  "action",
  {
    "type": "set",
    "epoch": "2"
  },
  [
    [
      "block",
      {
        "type": "add"
      },
      [
        [
          "user",
          {
            "jid": "<number>@c.us"
          },
          null
        ]
      ]
    ]
  ]
]

//Unblock
[
  "action",
  {
    "type": "set",
    "epoch": "8"
  },
  [
    [
      "block",
      {
        "type": "remove"
      },
      [
        [
          "user",
          {
            "jid": "<number>@c.us"
          },
          null
        ]
      ]
    ]
  ]
]
```
