### ISSUE TITLE
Always got forbidden when using groupParticipantsUpdate [BUG]

### ISSUE THREAD

**Issue by soby-bolu** [adiwajshing/Baileys#2334]
**Describe the bug**
Always got forbidden when using function groupParticipantsUpdate to invite someone join group

**To Reproduce**
1. Using groupParticipantsUpdate

**Environment (please complete the following information):**
 - Is this on a server? local and server
 - What do your `connectOptions` look like? default options
 - Do you have multiple clients on the same IP? different
 - Are you using a proxy? not

**Comment by maleeqB** [comment]
Same here, whenever a user has group privacy turned on, it says forbidden and then I get banned 

Have you found any solution or workaround?

**Comment by kamikazechaser** [comment]
I was able to add multiple people with status 403. The ban came naturally after like 150 people, but not immediately I got 403. I tested with a single user per array.

**Comment by maleeqB** [comment]
Hi @kamikazechaser, did you implement any delay in doing so?

I also tried single user per array, but I still get Forbidden error, followed by ban


Any workaround to add multiple users to a group? Is 150 the highest you've ever managed?

**Comment by kamikazechaser** [comment]
150 was my first try, got banned at exactly 150. Yes I have a function to randomize delays, but I don't think that helps that much. I believe the ban was because all the random numbers reported the group before leaving. I used an old non voip account btw.

**Comment by BimaPangestu28** [comment]
> Don't think this is a bug. I was able to add multiple people with status 403. The ban came naturally after like 150 people, but not immediately I got 403. I tested with a single user per array.

I got error at first time invite someone to group
Already test using new Whatsapp and old Whatsapp account but it's still same got forbidden error

**Comment by maleeqB** [comment]
Exactly @BimaPangestu28, even sometimes when it's my first time adding a single user to a group / creating a group with a user, I still face this forbidden error

**Comment by kamikazechaser** [comment]
A status 403 is the privacy setting of that user, as long as you are not logged out after that it is all good.

**Comment by maleeqB** [comment]
It's an error not just a status code or sth, It returns the Forbidden error and it's immediately followed by temporary ban (logged out due to spam)

**Comment by kamikazechaser** [comment]
Oh ok, yeah that is a ban. Could be your IP is banned, try using a HTTP proxy with Baileys or VPN and see if you still face the same issue.

**Comment by BimaPangestu28** [comment]
> Oh ok, yeah that is a ban. Could be your IP is banned, try using a HTTP proxy with Baileys or VPN and see if you still face the same issue.

Already check with another vm and still got banned, can you give example for using http proxy with baileys?

**Comment by kamikazechaser** [comment]
```js
// https://www.npmjs.com/package/http-proxy-agent
agent: new HttpProxyAgent(proxy);
```
