### ISSUE TITLE
add the new poll feature

### ISSUE THREAD

**Issue by lietd** [adiwajshing/Baileys#2335]
recently WhatsApp added the new poll feature, it would be awesome to use that.

![IMG_20221117_092414](https://user-images.githubusercontent.com/114436025/202445649-e91cc9ca-5ae9-4d6c-aac1-b74add9ced9a.jpg)

**Comment by undefined-60** [comment]
> recently WhatsApp added the new poll feature, it would be awesome to use that.
> 
> ![IMG_20221117_092414](https://user-images.githubusercontent.com/114436025/202445649-e91cc9ca-5ae9-4d6c-aac1-b74add9ced9a.jpg)

Go to pull requests and read the topic poll request...

**Comment by andresayac** [comment]
It is already available as I saw in another issue
https://github.com/adiwajshing/Baileys/pull/2290

**Comment by rsaisankalp** [comment]
It is much required please add it
