### ISSUE TITLE
[BUG] Connection Closed - statusCode: 428

### ISSUE THREAD

**Issue by dionesdf** [adiwajshing/Baileys#2336]
Hello guys.

I realized that if I don`t send messages for a while the connection closes by itself.

(C:\baileys\node_modules\express\lib\router\layer.js:95:5)
    at C:\baileys\node_modules\express\lib\router\index.js:284:15 {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}

**To Reproduce**
Don`t send messages for a while, 20 minutes for example.

This is the set of my connection.

const config = {
      auth: state,
      logger: P({ level: 'error' }),
      printQRInTerminal: true,
      version,
      connectTimeoutMs: 90_000,
      //connectTimeoutMs:undefined,
      async getMessage(key) {
         return { conversation: '' };
      },
   }

Is there something that I`m missing to do?

Thanks in advance.

**Comment by jludere** [comment]
same issue

**Comment by dsandrade** [comment]
same issue

**Comment by serra9311** [comment]
up

**Comment by serra9311** [comment]
no one solves the problem?

**Comment by xXDeonoXx** [comment]
i have the same issue

**Comment by truemoroz** [comment]
i have the same issue

**Comment by arelial838** [comment]
+1
