### ISSUE TITLE
[BUG] Error: Stream Errored (restart required)

### ISSUE THREAD

**Issue by nyongrand** [adiwajshing/Baileys#2341]
**Describe the bug**

**To Reproduce**
1. Start Baileys thror error after scan QR

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

`
connection update {
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored (restart required)
        at WebSocket.<anonymous> (C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:424:13)
        at WebSocket.emit (node:events:520:28)
        at C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:222:35
        at Object.decodeFrame (C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\@adiwajshing\baileys\lib\Utils\noise-handler.js:131:17)
        at WebSocket.onMessageRecieved (C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:198:15)
        at WebSocket.emit (node:events:520:28)
        at Receiver.receiverOnMessage (C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\ws\lib\websocket.js:1178:20)
        at Receiver.emit (node:events:520:28)
        at Receiver.dataMessage (C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\ws\lib\receiver.js:513:14)
        at Receiver.getData (C:\Users\SIRS\source\repos\whatsapp-bot\node_modules\ws\lib\receiver.js:446:17) {
      data: [Object],
      isBoom: true,
      isServer: true,
      output: [Object]
    },
    date: 2022-11-18T05:56:46.113Z
  }
}
using WA v2.2243.7, isLatest: true
`

**Comment by zLucasKk** [comment]
It's not a BUG. You just need to restart the connection with WhatsApp to sync your auth between WhatsApp Web and your environment.

**Comment by zLucasKk** [comment]
Here the solution for you in TypeScript:
```
bot.ev.on('connection.update', async (update) => {
		const { connection, lastDisconnect } = update

		switch (connection) {
			case 'close':
				const shouldReconnect = (lastDisconnect?.error as Boom)?.output?.statusCode !== DisconnectReason.loggedOut
				console.log('🔴 Conexão perdida: ', lastDisconnect?.error)
				if (shouldReconnect) {
					init() // YOUR INIT FUNCTION
				}
				console.log(seconds.ToDHMS(process.uptime()))
				break;

			case 'connecting':
				console.log('🟡 Aguardando Conexão...')
				break;

			case 'open':
				console.log('🟢 Conectado.')
				await bot.sendPresenceUpdate("available")
				await bot.updateProfileStatus("🟢 Online")
				break;

			default:
				break;
		}
	})
```
This code handle all connection updates,  fell free to play with. Obviously, ignore the imports that is not built-in, good luck! 👋

**Comment by nyongrand** [comment]
> It's not a BUG. You just need to restart the connection with WhatsApp to sync your auth between WhatsApp Web and your environment, just call a Connection Close event, calling your Init function if there is a connection close, so it can restart everytime WhatsApp breaks your bot connection.

Thanks for your reply, actually I already do that, the code you mentioned actually pretty much the same as mine, but your reply pointed me to the right path.

The real problem is, I run block of code (starting Fastify server) on init, Baileys run perfectly after I remove the code.

Looks like I have to move my code to another place, maybe you know where is the best place to start Fastify?
If you ask why I started Fastify in Baileys init, I need access to socks instance when the Fastify route is called.

**Comment by zLucasKk** [comment]
I'm sorry for late reply, i never used Fastify to tell you more about again, i'm sorry...
I run my BOT in a primitive dedicated server using just SSH/SFTP and pure NodeJS Framework hahaha 🤣
Well that is all me and my clients need at moment...
Wish you well and good luck!
