### ISSUE TITLE
[BUG] presenceSubscribe does not work [Paid Support]

### ISSUE THREAD

**Issue by muratpolat** [adiwajshing/Baileys#2342]
**Describe the bug**

I did all my tests via whatsapp business. I tried 3 different phone numbers.

Despite messaging with the user, I cannot get the user's online information. The phone I want to get online information from is my own phone. The target phone's online information is on

At first I thought if whatsapp is blocking me. Then I tried with web whatsapp. When I tried with web whatsapp, I was able to access online information.

This issue persists in old and new versions.

I need paid support to fix this issue.

**Comment by resatkrlc** [comment]
I am having same issue. Hopefully there will be any answers.

**Comment by muratpolat** [comment]
i solved this problem: kutsalpolat@gmail.com

**Comment by resatkrlc** [comment]
Could you share the solition here? and it would be great if @adiwajshing add to this library.
