### ISSUE TITLE
Why all the messages sent out are PENDING ,

### ISSUE THREAD

**Issue by huangzhong0406** [adiwajshing/Baileys#2348]
Why all the messages sent out are PENDING , messages.upsert received status:1 , Cannot be delivered to recipient

**Comment by AlvaroBrasilia** [comment]
+1

**Comment by 4relial** [comment]
+1

**Comment by rsaisankalp** [comment]
Implement using the example
getMessage is the solution

**Comment by moskoweb** [comment]
It works for contacts, but not for groups.

**Comment by rsaisankalp** [comment]
Yeah same issue happened to me
Only in groups

Fixed with the example
getMessage when you create wasocket as listed in the example.
It will retry the message untill decryption passes.tjos should fix your issue
