### ISSUE TITLE
To check if it's possible to add contact?

### ISSUE THREAD

**Issue by kbwong-cti** [adiwajshing/Baileys#235]
Hi, thanks you sharing your whatsapp API, I have been trying to check through your readme & codes, but not able to find any method/routine to add a contact... is it possible?

**Comment by adiwajshing** [comment]
Unfortunately it isn’t possible

**Comment by kbwong-cti** [comment]
ok, understood, thanks for your response anyway.

**Comment by itacirgabral** [comment]
It is not possible to add a contact to the phone contact list.

But Baileys have `conn.contacts` built at boot time reading from mobile messages. If you sent a message to a new one then the next boot will grab it to the bailey's contact object.
