### ISSUE TITLE
[BUG] Button with images don't working

### ISSUE THREAD

**Issue by gabrielayer** [adiwajshing/Baileys#2351]
using actual version 4.4.0, when i send the button with type header 4 (image), the console just stops.

using the example:

					// send a buttons message with image header!
				const buttons = [
					{buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
					{buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
					{buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
				]
				
				const buttonMessage = {
					image: {url: 'media/imagem.jpg'},
					caption: "Hi it's button message",
					footer: 'Hello World',
					buttons: buttons,
					headerType: 4
				}
				
				const sendMsg = await conn.sendMessage(from, buttonMessage)

**Comment by Aiinne** [comment]
Button fake location not work too

**Comment by gabrielayer** [comment]
> Button fake location not work too

Do you have any idea how to resolve? here location is also not working.

**Comment by gabrielayer** [comment]
@adiwajshing
