### ISSUE TITLE
[BUG] URL generation failed with valid title and url.. but invalid image link/format

### ISSUE THREAD

**Issue by azudindaem** [adiwajshing/Baileys#2368]
**Describe the bug**
URL generation failed when there is invalid url or invalid format

**To Reproduce**
1. Send simple message text with url + invalid link/image

**Expected behavior**
```json
{"level":40,"time":1669523590543,"pid":10043,"hostname":"localhost","msgId":"XXXXX","trace":"url generation failed"}
48|master-8000  | [Error: ENOENT: no such file or directory, open 'data:image/svg+xml,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20viewBox=%270%200%20768%20768%27%3E%3C/svg%3E'] {
48|master-8000  |   errno: -2,
48|master-8000  |   code: 'ENOENT',
48|master-8000  |   syscall: 'open',
48|master-8000  |   path: 'data:image/svg+xml,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20viewBox=%270%200%20768%20768%27%3E%3C/svg%3E'
48|master-8000  | }
```

Previous update does not fixed the problem and when error occurs message will failed

https://github.com/adiwajshing/Baileys/commit/26828d3dea46d78397a77f667b2f4f3f34db5de6

**Comment by textarea** [comment]
Sometimes url preview generation throws this error, if you want to disable url preview generation add linkPreview: WAUrlInfo empty param to your message:
`message.linkPreview = {
          'canonical-url': '',
          'matched-text': '',
          title: '',
        }`
