### ISSUE TITLE
[BUG] Error: mutex start

### ISSUE THREAD

**Issue by zennn08** [adiwajshing/Baileys#2369]
**Describe the bug**
Spamming log error mutex start

`{"level":40,"time":"2022-11-27T06:47:18.034Z","pid":3132077,"hostname":"xxxx","stack":"Error: mutex start\n    at /root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleReceipt (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:348:29)\n    at execTask (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:549:20)\n    at processNodeWithBuffer (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:539:19)\n    at WebSocket.<anonymous> (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:569:9)\n    at WebSocket.emit (node:events:513:28)\n    at /root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/root/xxx/bot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}`

**Comment by makanSukros** [comment]
+1

**Comment by MaznAbdullah** [comment]
+1

**Comment by azudindaem** [comment]
Is this occur after updating to the latest commit?

**Comment by zennn08** [comment]
yes

**Comment by Fonnte** [comment]
+1

**Comment by azudindaem** [comment]
can you explain on house to reproduce this error.

**Comment by erickythierry** [comment]
+1

but the bot does not stop responding
it just fills the logs with this error

**Comment by zennn08** [comment]
> can you explain on how to reproduce this error.

You just need to update to the latest commit version and run the bot. after a few minutes, spam logs occur as above

**Comment by zennn08** [comment]
I think its because [this commit](https://github.com/adiwajshing/Baileys/commit/bcf33d786ca2c5518d0504e8034c0dba30705170)

**Comment by jccalbuquerque** [comment]
+1

**Comment by rafaeldalbosco** [comment]
+1

**Comment by handoko19** [comment]
+1

**Comment by GabrielBragaGit** [comment]
+1

**Comment by IanosJunior** [comment]
> I think its because [this commit](https://github.com/adiwajshing/Baileys/commit/bcf33d786ca2c5518d0504e8034c0dba30705170)

Yup. I removed it and it fixed it.

**Comment by azudindaem** [comment]
from my observation, this mutex error happen when i react to message

Since this is non critical error, we still can use latest commit and ignore this error

**Comment by frmdeveloper** [comment]
forgot

**Comment by frmdeveloper** [comment]
for now the programmers do not want to fix it.

**Comment by LZNOXP** [comment]
Latest commit fix this

**Comment by erickythierry** [comment]
> Latest commit fix this

has not been fixed

**Comment by allegrun** [comment]
+1

**Comment by w3nder** [comment]
+1

**Comment by AlvaroBrasilia** [comment]
+1

**Comment by gbenmelej** [comment]
+1

**Comment by arthur-es** [comment]
+1

**Comment by zennn08** [comment]
.

**Comment by JuniYadi** [comment]
+1

**Comment by allegrun** [comment]
+1

**Comment by zennn08** [comment]
.

**Comment by timosur** [comment]
+1

**Comment by Shubhamrawat5** [comment]
.

**Comment by clicknetcafe** [comment]
> > I think its because [this commit](https://github.com/adiwajshing/Baileys/commit/bcf33d786ca2c5518d0504e8034c0dba30705170)
> 
> Yup. I removed it and it fixed it.

what part did you remove

**Comment by panalgin** [comment]
You can temporarily fix the issue by importing Baileys into your application

```
"dependencies": {
    "@adiwajshing/baileys": "panalgin/Baileys", 
```

Until the pull request at https://github.com/adiwajshing/Baileys/pull/2453

closes #2453

**Comment by erickythierry** [comment]
now this bug is present in npm version too

**Comment by zennn08** [comment]
fix with new [commit](https://github.com/adiwajshing/Baileys/commit/5efb0ebbea19b7f3d783fbc1589fa0e9c1386ff5)

**Comment by Losangelo** [comment]
How to solve the mutex error that still persists in baileys 5.0.0?

{"level":40,"time":"2023-01-20T12:45:44.745Z","pid":140087,"hostname":"dev","stack":"Error: mutex start\n    at <anonymous> (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31)\n    at Object.mutex (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:13)\n    at handleMessage (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n    at execTask (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at <anonymous> (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35)\n    at Object.decodeFrame (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)","waitOver":false,"msg":"possible mutex deadlock"}

**Comment by hansputera** [comment]
> How to solve the mutex error that still persists in baileys 5.0.0?
> 
> {"level":40,"time":"2023-01-20T12:45:44.745Z","pid":140087,"hostname":"dev","stack":"Error: mutex start\n at (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31)\n at Object.mutex (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:13)\n at handleMessage (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n at execTask (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n at processNodeWithBuffer (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n at WebSocket. (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n at WebSocket.emit (node:events:513:28)\n at WebSocket.emit (node:domain:489:12)\n at (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35)\n at Object.decodeFrame (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)","waitOver":false,"msg":"possible mutex deadlock"}

up

**Comment by ekucet** [comment]
> > How to solve the mutex error that still persists in baileys 5.0.0?
> > {"level":40,"time":"2023-01-20T12:45:44.745Z","pid":140087,"hostname":"dev","stack":"Error: mutex start\n at (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31)\n at Object.mutex (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:13)\n at handleMessage (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:451:29)\n at execTask (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n at processNodeWithBuffer (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n at WebSocket. (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:560:9)\n at WebSocket.emit (node:events:513:28)\n at WebSocket.emit (node:domain:489:12)\n at (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35)\n at Object.decodeFrame (/home/godev/Downloads/projects/pessoais/ProjetoLu/b5Baileys/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)","waitOver":false,"msg":"possible mutex deadlock"}
> 
> up

up

**Comment by zennn08** [comment]
you can install baileys github version

```cli
yarn add github:adiwajshing/baileys
```

or maybe we need release new version to fix this promblem @adiwajshing

**Comment by matheusf31** [comment]
+1

**Comment by drizion** [comment]
+1

**Comment by arthur-es** [comment]
+1

**Comment by danLDev** [comment]
+1

**Comment by Paguiar735** [comment]
Given that there are four comments on this thread, I assume the problem still persists in some way or another.

If this alleged error/warning comes up and you're a new user of this library, I suggest trying [this](https://github.com/Paguiar735/baileys-quickstart).

So if you're not a newcomer, provide us with a minimal reproducible example, because personally I'm not getting any of this on my end (I'm running v5.0.0).

**Comment by DeveloperNewton** [comment]
+1

**Comment by DeveloperNewton** [comment]
To prevent messages like "possible mutex deadlock" from appearing during code execution, you can go to node_modules/@adiwajshing/baileys, access the "utils" directory, open the make_mutex file and comment or delete line 18 (here it appears on line 18, if it doesn't appear, look for logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'))

In short: delete/comment out the line containing logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'); in the make_mutex file inside the "Utils" directory in node_modules

**Comment by zennn08** [comment]
.

**Comment by Victor-FT** [comment]
+1

**Comment by lanaparadinha** [comment]
up

**Comment by creative-ae** [comment]
still not fixed in the latest version

**Comment by lanaparadinha** [comment]
and fixed when? Project is stoped?

**Comment by erickythierry** [comment]
> still not fixed in the latest version

install directly from github, the npm version is taking too long to receive updates.
I'm using it directly from github and this error has been fixed

**Comment by erickythierry** [comment]
> and fixed when? Project is stoped?

install directly from github, the npm version is taking too long to receive updates.
I'm using it directly from github and this error has been fixed

**Comment by hansputera** [comment]
I've created the npm version [here](https://www.npmjs.com/package/@gampang-pkg/baileys-edge), and this package automatically updates every new commit from GitHub (source: https://github.com/hansputera/Baileys-edge)

Hope it helps 😅

**Comment by lanaparadinha** [comment]
how make that?

**Comment by erickythierry** [comment]
> how make that?

remove npm's baileys from your project:
`npm uninstall @adiwajshing/baileys`

now install version from github:
`npm install github:adiwajshing/baileys`
