### ISSUE TITLE
[BUG] Message to Groups

### ISSUE THREAD

**Issue by vinder11** [adiwajshing/Baileys#237]
Good morning, I have a problem, I have tried to send messages to groups but in the console after connecting the instance it stays loading and never sends, while when it sends to a specific number, the message is sent correctly.

`const clientConnect = await client.connectSlim (ban);`

`const options = {quoted: null, autoReconnect: false, timestamp: new Date () };`
`// group= EEEOaAp2aPq235nKOynJJL`
`const MessageSend = await client.sendTextMessage (group+'@g.us', message, options);  //Fail`
`//5917........`
`const MessageSend = await client.sendTextMessage (number+'@s.whatsapp.net', message, options);  //Done`

I appreciate your help.

**Comment by itacirgabral** [comment]
I have working code using this feature. Had your user already joined the group?

group jid example:
- `"5521988776644-1234567890@g.us"`

try to send a message to `EEEOaAp2aPq235nKOynJJL@g.us` makes my whatsapp crash. It is not a valid jid
```
DEBUG	 [2020-11-19 14:35:32.185 +0000] (73688): s9,["Stream","asleep"]
    unhandled: true
    class: "Baileys"
```

**Comment by adiwajshing** [comment]
@itacirgabral is right, your group ID is likely malformed causing the connection to get stuck

**Comment by vinder11** [comment]
@adiwajshing sorry, but how can I get the correct id of the group, I don't understand, please could you explain.
I am attached to the group to which I am trying to send the message.
This is the ID that the group takes when it generates an invitation link for the group.

**Comment by itacirgabral** [comment]
`conn.contacts` have the JIDs.

You will need:
```javascript
conn.connectOptions.waitForChats = true
await conn.connect()
console.dir(conn.contacts)
```

From README.md
> To note:
> - id is the WhatsApp ID of the person or group you're sending the message to.
> It must be in the format [country code][phone number]@s.whatsapp.net, for example +19999999999@s.whatsapp.net for people. For groups, it must be in the format 123456789-123345@g.us.

**Comment by barkerpedro** [comment]
Try:

```Node
const getGroups = await conn.chats;
let objGroup = { groups: [] };
let members = getGroups.array;
for (var key in members) {
  if (members[key].jid.indexOf('@g.us') != -1) {
    objGroup.groups.push({
      id: members[key].jid,
      name: members[key].name
    });
   }
}
console.log(objGroup);
```

**Comment by vinder11** [comment]
@itacirgabral and @barkerpedro thank you very much for your help.
