### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by Ningoje** [adiwajshing/Baileys#2373]
##I get this error after bot runs for about 2 hours. 

_

> 0|index  | SyntaxError: Unexpected end of JSON input
> 0|index  |     at JSON.parse (<anonymous>)
> 0|index  |     at Object.readFromFile (/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:308:35)
> 0|index  |     at Object.<anonymous> (/index.js:40:7)
> 0|index  |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
> 0|index  |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
> 0|index  |     at Module.load (node:internal/modules/cjs/loader:1037:32)
> 0|index  |     at Module._load (node:internal/modules/cjs/loader:878:12)
> 0|index  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
> 0|index  |     at Module._compile (node:internal/modules/cjs/loader:1159:14)
> 0|index  |     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)

_

When this happens, i have to delete  **baileys_store.json** file.

```
const store = makeInMemoryStore({ logger2 })
// can be read from a file
store.readFromFile('./database/baileys_store.json')
// saves the state to a file every 10s
setInterval(() => {
    store.writeToFile('./database/baileys_store.json')
},10 * 1000)
```

Im using edge version

**Comment by erickythierry** [comment]
I had some problems with this Baileys default store function. I ended up not using it. I made a similar one that suits me
