### ISSUE TITLE
how to make anti delete status ?

### ISSUE THREAD

**Issue by officialdittaz** [adiwajshing/Baileys#2375]
When user delete their status broadcast, the bot is auto copyAndForward their status and send to me, can anyone help ?

**Comment by officialdittaz** [comment]
Anying 🗿

**Comment by SanzGanzs** [comment]
> Anying 🗿

🗿

**Comment by officialdittaz** [comment]
kaga ada yang komen tpi pada dislike anying emang :v

**Comment by RavensVenix** [comment]
bisanya cuman ngedeteksi status di add, dihapus, pake caption, gambar/video
ntar tinggal kembangin aja supaya bisa ngirim video
lagian gua ga butuh video sw orang :v

taruh dibagian connecting nya (default: index.js)
buat xylaa.autosw = true/false ( ganti xylaa ke nama yang dipakai di bot sendiri, taruh dibawah xylaa.public )
kalau mau dibuat fitur on off buat case seperti ini

case 'autosw': {
if (!isCreator) return replay(mess.owner)
if (xylaa.autosw) {
xylaa.autosw = false
reply('auto sw is now disabled')
} else if (!xylaa.autosw) {
xylaa.autosw = true
reply('auto sw is now active')
}
} 
break

( itu xylaa.autosw nya jgn lupa diganti juga sesuai nama yang diberikan di connecting tdi )

lalu pergi lagi ke connecting nya
kita buat dulu nomor yang mau dikasih teks nya
xylaa.sendsw = '6281xxxxx@s.whatsapp.net'

cari ev.on('messages.upsert', async chatUpdate => {
taruh dibawah if (!mek.message) return
if (mek.key.remoteJid === 'status@broadcast') {
let bot = xylaa.decodeJid(xylaa.user.id)
if (!xylaa.autosw) return
setTimeout(() => {
xylaa.readMessages([mek.key])
let mt = getContentType(mek.message)
console.log((/protocolMessage/i.test(mt)) ? `${mek.key.participant.split('@')[0]} Telah menghapus Story nya` : 'Melihat story user : '+mek.key.participant.split('@')[0]);
if (/protocolMessage/i.test(mt)) xylaa.sendMessage(xylaa.sendsw, {text:'Status dari @'+mek.key.participant.split('@')[0]+' Telah dihapus', mentions: [mek.key.participant]})
if (/(imageMessage|videoMessage|extendedTextMessage)/i.test(mt)) {
let keke = (mt == 'extendedTextMessage') ? `\nStory Teks Berisi : ${mek.message.extendedTextMessage.text}` : (mt == 'imageMessage') ? `\nStory Gambar dengan Caption : ${mek.message.imageMessage.caption}` : (mt == 'videoMessage') ? `\nStory Video dengan Caption : ${mek.message.videoMessage.caption}` : '\nTidak diketahui cek saja langsung!!!'
xylaa.sendMessage(xylaa.sendsw, {text: 'Melihat story dari @'+mek.key.participant.split('@')[0] + keke, mentions: [mek.key.participant]});
}
}, 0);
}

otomatis kalau ada yang upload sw ntar dibaca ama bot nya trus di send message di nomor yang ditaruh di sendsw td

ga berlaku buat orang yang suka nonton sw :v

**Comment by SanzGanzs** [comment]
> bisanya cuman ngedeteksi status di add, dihapus, pake caption, gambar/video ntar tinggal kembangin aja supaya bisa ngirim video lagian gua ga butuh video sw orang :v
> 
> taruh dibagian connecting nya (default: index.js) buat xylaa.autosw = true/false ( ganti xylaa ke nama yang dipakai di bot sendiri, taruh dibawah xylaa.public ) kalau mau dibuat fitur on off buat case seperti ini
> 
> case 'autosw': { if (!isCreator) return replay(mess.owner) if (xylaa.autosw) { xylaa.autosw = false reply('auto sw is now disabled') } else if (!xylaa.autosw) { xylaa.autosw = true reply('auto sw is now active') } } break
> 
> ( itu xylaa.autosw nya jgn lupa diganti juga sesuai nama yang diberikan di connecting tdi )
> 
> lalu pergi lagi ke connecting nya kita buat dulu nomor yang mau dikasih teks nya xylaa.sendsw = '[6281xxxxx@s.whatsapp.net](mailto:6281xxxxx@s.whatsapp.net)'
> 
> cari ev.on('messages.upsert', async chatUpdate => { taruh dibawah if (!mek.message) return
> 
> if (mek.key.remoteJid === 'status@broadcast') { let bot = xylaa.decodeJid(xylaa.user.id) if (!xylaa.autosw) return setTimeout(() => { xylaa.readMessages([mek.key]) let mt = getContentType(mek.message) console.log((/protocolMessage/i.test(mt)) ? `${mek.key.participant.split('@')[0]} Telah menghapus Story nya` : 'Melihat story user : '+mek.key.participant.split('@')[0]); if (/protocolMessage/i.test(mt)) xylaa.sendMessage(xylaa.sendsw, {text:'Status dari @'+mek.key.participant.split('@')[0]+' Telah dihapus', mentions: [mek.key.participant]}) if (/(imageMessage|videoMessage|extendedTextMessage)/i.test(mt)) { let keke = (mt == 'extendedTextMessage') ? `\nStory Teks Berisi : ${mek.message.extendedTextMessage.text}` : (mt == 'imageMessage') ? `\nStory Gambar dengan Caption : ${mek.message.imageMessage.caption}` : (mt == 'videoMessage') ? `\nStory Video dengan Caption : ${mek.message.videoMessage.caption}` : '\nTidak diketahui cek saja langsung!!!' xylaa.sendMessage(xylaa.sendsw, {text: 'Melihat story dari @'+mek.key.participant.split('@')[0] + keke, mentions: [mek.key.participant]}); } }, 0); }
> 
> ( sebelumnya cek dulu disitu ada ga yang status@broadcast, kalo ada hapus dlu baru ganti ke itu ) otomatis kalau ada yang upload sw ntar dibaca ama bot nya trus di send message di nomor yang ditaruh di sendsw td + console
> 
> ga berlaku buat orang yang suka nonton sw :v

mantap🗿

**Comment by RavensVenix** [comment]
> > bisanya cuman ngedeteksi status di add, dihapus, pake caption, gambar/video ntar tinggal kembangin aja supaya bisa ngirim video lagian gua ga butuh video sw orang :v
> > taruh dibagian connecting nya (default: index.js) buat xylaa.autosw = true/false ( ganti xylaa ke nama yang dipakai di bot sendiri, taruh dibawah xylaa.public ) kalau mau dibuat fitur on off buat case seperti ini
> > case 'autosw': { if (!isCreator) return replay(mess.owner) if (xylaa.autosw) { xylaa.autosw = false reply('auto sw is now disabled') } else if (!xylaa.autosw) { xylaa.autosw = true reply('auto sw is now active') } } break
> > ( itu xylaa.autosw nya jgn lupa diganti juga sesuai nama yang diberikan di connecting tdi )
> > lalu pergi lagi ke connecting nya kita buat dulu nomor yang mau dikasih teks nya xylaa.sendsw = '[6281xxxxx@s.whatsapp.net](mailto:6281xxxxx@s.whatsapp.net)'
> > cari ev.on('messages.upsert', async chatUpdate => { taruh dibawah if (!mek.message) return
> > if (mek.key.remoteJid === 'status@broadcast') { let bot = xylaa.decodeJid(xylaa.user.id) if (!xylaa.autosw) return setTimeout(() => { xylaa.readMessages([mek.key]) let mt = getContentType(mek.message) console.log((/protocolMessage/i.test(mt)) ? `${mek.key.participant.split('@')[0]} Telah menghapus Story nya` : 'Melihat story user : '+mek.key.participant.split('@')[0]); if (/protocolMessage/i.test(mt)) xylaa.sendMessage(xylaa.sendsw, {text:'Status dari @'+mek.key.participant.split('@')[0]+' Telah dihapus', mentions: [mek.key.participant]}) if (/(imageMessage|videoMessage|extendedTextMessage)/i.test(mt)) { let keke = (mt == 'extendedTextMessage') ? `\nStory Teks Berisi : ${mek.message.extendedTextMessage.text}` : (mt == 'imageMessage') ? `\nStory Gambar dengan Caption : ${mek.message.imageMessage.caption}` : (mt == 'videoMessage') ? `\nStory Video dengan Caption : ${mek.message.videoMessage.caption}` : '\nTidak diketahui cek saja langsung!!!' xylaa.sendMessage(xylaa.sendsw, {text: 'Melihat story dari @'+mek.key.participant.split('@')[0] + keke, mentions: [mek.key.participant]}); } }, 0); }
> > ( sebelumnya cek dulu disitu ada ga yang status@broadcast, kalo ada hapus dlu baru ganti ke itu ) otomatis kalau ada yang upload sw ntar dibaca ama bot nya trus di send message di nomor yang ditaruh di sendsw td + console
> > ga berlaku buat orang yang suka nonton sw :v
> 
> mantapmoyai

okeii thank youu

**Comment by xbnfz01** [comment]
hadeh di prettier dong , codingannya berantakan bener wkwk
