### ISSUE TITLE
Feature Request: Change Groups's Title and Description

### ISSUE THREAD

**Issue by shubham0804** [adiwajshing/Baileys#238]
It would be great if a group's title and description can be changed!

**Comment by adiwajshing** [comment]
You can, it’s mentioned in the readme

**Comment by shubham0804** [comment]
I'm unable to find it over there. I found the method to query the group's meta data but no way to modify it. Kindly guide.

**Comment by adiwajshing** [comment]
I apologise, I missed documenting that. Updated, read [here](https://github.com/adiwajshing/Baileys#groups)

**Comment by shubham0804** [comment]
Thanks man! I appreciate the effort you have put into this library. Also is there a way to revoke the invite link of a group?

**Comment by areltiyan** [comment]
> Thanks man! I appreciate the effort you have put into this library. Also is there a way to revoke the invite link of a group?

```
const json = ["action","inviteReset", remoteJid] 
await conn.query({json, expect200: true, requiresPhoneConnection: false})
```
