### ISSUE TITLE
send message to status@broadcast

### ISSUE THREAD

**Issue by calix666** [adiwajshing/Baileys#2382]
hello 
how can i send a message to status@broadcast 
in the last version 3.1 i use conn.sendMessage('status@broadcast', "hi this is a status")
but now   i use sock.sendMessage('status@broadcast', {text: "hi this is a status"}) its time out

**Comment by frmdeveloper** [comment]
for now the programmers do not want to fix it.

**Comment by VanzGantengz** [comment]
You can send status manually

**Comment by mateusmirandaalmeida** [comment]
> Você pode enviar o status manualmente

text message can also be sent manually hahahaha
