### ISSUE TITLE
possible mutex deadlock IOS [BUG]

### ISSUE THREAD

**Issue by rawars** [adiwajshing/Baileys#2386]
**Describe the bug**
When an IOS device is scanned, <messaging-history.set"> <contacts.upsert> events are not executed, messages regarding <possible mutex deadlock> are reflected in the terminal.

**To Reproduce**
1. start qr
2. Scan IOS
3. does not sync

![Captura_de_pantalla_de_2022-12-05_16-09-21](https://user-images.githubusercontent.com/3655598/205744876-fb10df1d-70a8-4378-afff-2c00a96ae7ee.png)

**Comment by zennn08** [comment]
#2369

**Comment by adarsh-chakraborty** [comment]
Still facing with android, just the log is filled with this error and nothing else

**Comment by DeveloperNewton** [comment]
+1

**Comment by bobbysites** [comment]
+1
