### ISSUE TITLE
[BUG] Whatsaapp Crashed

### ISSUE THREAD

**Issue by VanzGantengz** [adiwajshing/Baileys#2387]
please fix bug sending messages with quoted and remoteJid: " " (null)
```js
const quoted = { key: { id, participant, remoteJid: " " } }
sock.sendMessage(msg.key.remoteJid, { text: "Hello World" }, { quoted })
```
the bug is very detrimental, whatsapp crashes continuously and can't be opened.
please help to fix the bug, because many people abuse it

**Comment by pe77** [comment]
same problema here

**Comment by SanzGanzs** [comment]
> please fix bug sending messages with quoted and remoteJid: " " (null)
> 
> ```js
> const quoted = { key: { id, participant, remoteJid: " " } }
> sock.sendMessage(msg.key.remoteJid, { text: "Hello World" }, { quoted })
> ```
> 
> the bug is very detrimental, whatsapp crashes continuously and can't be opened. please help to fix the bug, because many people abuse it

bilek🗿

**Comment by dinataaaa** [comment]
😏

**Comment by SanzGanzs** [comment]
> 😏

🗿

**Comment by ffauzan** [comment]
The bug is on the WhatsApp side, so I don't think he needs to fix it. And people can just use another library to send the same kind of bugged message.

**Comment by salsawij** [comment]
I tried the code, and nothing happened

**Comment by Kuroosh** [comment]
cant reproduce.
