### ISSUE TITLE
[BUG] Problem in recive message

### ISSUE THREAD

**Issue by Guilherme-j10** [adiwajshing/Baileys#2389]
does anyone know why when sometimes i connect my device i get the message meta data normally in my terminal but i don't get anything if someone who is not saved in my contacts sends me the same message over the web ?

**Comment by vishwajit76** [comment]
The same problem from the past few days, "messages.upsert" event stopped working.

**Comment by NavpreetDevpuri** [comment]
Same, It does not work even with contacts

**Comment by NavpreetDevpuri** [comment]
@adiwajshing Do have any Idea? 

Whenever we receive any message we get `"type":"pkmsg"` logs but not `messages.upsert`
