### ISSUE TITLE
[BUG] Url generation failed

### ISSUE THREAD

**Issue by DeveloperNewton** [adiwajshing/Baileys#2390]
I have error to generate url with link preview

Return of logger pino:

"msg":"url generation failed"
FetchError: uri requested responds with a redirect, redirect mode is set to error

**Comment by azudindaem** [comment]
does this error break your message?

**Comment by arthur-es** [comment]
![image](https://user-images.githubusercontent.com/37699234/206794744-164e9f37-dfeb-4ae4-878d-82f1df362b0f.png)

I'm having a similar issue that whenever I send a WhatsApp Business Short Link it throws this error.

**Comment by LZNOXP** [comment]
> ![image](https://user-images.githubusercontent.com/37699234/206794744-164e9f37-dfeb-4ae4-878d-82f1df362b0f.png)
> 
> I'm having a similar issue that whenever I send a WhatsApp Business Short Link it throws this error.
> 
> Does anyone know how to fix this?

get the redirected url

```ts
// example using fetch
const response = await fetch(url, { redirect: "follow" });
const newUrl = response.url;
```

i think there's an option you can pass to your sock connection, but idk

**Comment by DeveloperNewton** [comment]
The error I'm getting is in link-preview-js using Baileys (latest)The error I'm getting is in link-preview-js using Baileys (latest)

In the older version, I could send it with sock.sendMessage() using link-preview-js, but in the latest versions I can't!

**Comment by arthur-es** [comment]
> > ![image](https://user-images.githubusercontent.com/37699234/206794744-164e9f37-dfeb-4ae4-878d-82f1df362b0f.png)
> > I'm having a similar issue that whenever I send a WhatsApp Business Short Link it throws this error.
> > Does anyone know how to fix this?
> 
> get the redirected url
> 
> ```ts
> // example using fetch
> const response = await fetch(url, { redirect: "follow" });
> const newUrl = response.url;
> ```
> 
> i think there's an option you can pass to your sock connection, but idk

@adiwajshing is there a way to pass to the sock connection (when creating one) that it needs to follow the redirect so it does not throw an error? or just a way for this error not to appear.

**Comment by textarea** [comment]
+1

**Comment by arthur-es** [comment]
+1
