### ISSUE TITLE
[BUG] Error receiving messages on some whatsapp numbers

### ISSUE THREAD

**Issue by DavidsonGomes** [adiwajshing/Baileys#2394]
Some connections I make cannot receive messages, the following error appears in the console:

`"Error: Value not found\n at KeyedDB.deleteById (/www/wwwroot/vilavelutti/backend/node_modules/@adiwajshing/keyed-db/lib/KeyedDB.js:90:23)\n at EventEmitter.<anonymous> ( /www/wwwroot/vilavelutti/backend/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:114:23)\n at EventEmitter.emit (node:events:513:28)\ n at EventEmitter.emit (node:domain:552:15)\n at EventEmitter.<anonymous> (/www/wwwroot/vilavelutti/backend/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:38 :16)\n at EventEmitter.emit (node:events:513:28)\n at EventEmitter.emit (node:domain:552:15)\n at flush (/www/wwwroot/vilavelutti/backend/node_modules/@ adiwajshing/baileys/lib/Utils/event-buffer.js:58:16)\n at async /www/wwwroot/vilavelutti/backend/node_modules/@adiwajshing/baileys/lib/Utils/event-buffer.js:96: 25\n at async /www/wwwroot/vilavelutti/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:401:17\n at async Promise.all (index 0)\n at async handleMessage (/www/wwwroot/vilavelutti/backend/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:356:9)","msg":"unexpected error in 'processing message'"`

**Comment by Ajaykks** [comment]
Yeh

**Comment by Ajaykks** [comment]
Yeh

**Comment by DavidsonGomes** [comment]
Can you tell the reason for the error? my client does not receive messages

**Comment by allegrun** [comment]
how can i solve this problem?

**Comment by xXDeonoXx** [comment]
same error
