### ISSUE TITLE
[BUG] Buttons are not received if whatsapp is closed (IOS)

### ISSUE THREAD

**Issue by automation-experiences** [adiwajshing/Baileys#2398]
**Describe the bug**
If the receiver's whatsapp application is closed, the message with buttons is not received.
In whatsapp web it is received normally.

**To Reproduce**
1. Created a new connection
2. Authenticated
3. Close the application (destination's whatsapp)
4. Send button list
5. Wait a few seconds and open the app again. The message did not arrive.

**Expected behavior**
I hired a paid service to test if their button push was working. And it is sending successfully.

I noticed a difference in the message data structure.

This image contains the structure that successfully sent the buttons:
https://ibb.co/37gbZS0

This second image is our message structure using Baileys:
https://ibb.co/dBVyh29

Does it have a possible solution looking at the different structures?

I saw that something similar was already reported, but it was closed and marked as resolved.

I've tried using the viewOnce attribute, without success. I also tested it in the edge version and I was not successful.

**Comment by Zedmerlol** [comment]
+1 same with normal buttons

**Comment by FERDIZ-afk** [comment]
it was like that of his Baileys. somehow

**Comment by icsocoid** [comment]
Same problem on iOS..button not receive when app closed..

**Comment by jrCleber** [comment]
+1

**Comment by automation-experiences** [comment]
> +1
> 
> Not only the buttons, the lists are also not received if the app is closed.

it is true.

**Comment by giuseppecastaldo** [comment]
Also for me, how can I solve?
