### ISSUE TITLE
Cannot read "unread message" when Baileys not running when messaget sent

### ISSUE THREAD

**Issue by achmadlutfi** [adiwajshing/Baileys#24]
example.js cannot read "unread message" when baileys not running when messages sent.

[Baileys] connected to WhatsApp Web
[Baileys] resolving login challenge
[Baileys] validated connection successfully
[Baileys] waiting for chats & contacts
[Baileys] connected successfully
oh hello xxxx (xxxxx@s.whatsapp.net)
you have 1 unread messages
you have 33 chats & 250 contacts

**Comment by adiwajshing** [comment]
I think there is a misunderstanding. You can view all prior unread messages using:

``` javascript
    client.connect()
    .then (([user, chats, contacts, unread]) => {
        console.log ("oh hello " + user.name + " (" + user.id + ")")
        console.log ("you have " + unread.length + " unread messages")
        console.log ("you have " + chats.length + " chats")

        console.log (unread) // see what this prints, this contains all the unread message data
    })

```

**Comment by adiwajshing** [comment]
Assuming you've figured it out, closing.
