### ISSUE TITLE
2 types of audio messages

### ISSUE THREAD

**Issue by NicolasCaous** [adiwajshing/Baileys#241]
There are 2 different types of audio messages on Whatsapp.

  * Audio files that are shared;
  * Microphone recordings;

The first one has an audio icon when displayed.
The second one uses the sender's profile picture.

![Sem título](https://user-images.githubusercontent.com/24411365/100020975-79c6b080-2dbf-11eb-93b1-61b38cb74800.png)

It seems to me that, currently, you can only send the first type of audio messages. I tried adding a thumbnail to the audio message to no avail:

```
Error: audio messages cannot have thumbnails
```

Could you implement the second type of audio messages?

**Comment by adiwajshing** [comment]
It’s already implemented. You have to use the ptt flag, see the sending message section of the readme

**Comment by NicolasCaous** [comment]
Got it. It worked, thank you! :)
