### ISSUE TITLE
[BUG]Lost upsert events

### ISSUE THREAD

**Issue by dotKa** [adiwajshing/Baileys#2416]
**Describe the bug**
When connecting multiple baileys apps with same whatsapp account, first connected doesn't continue listen upsert events.

**To Reproduce**
1. Connect baileys app named A
2. Connect same whatsapp account another baileys app named B
3. A app stop contacts, messages... upsert events

**Comment by vishwajit76** [comment]
same

**Comment by dotKa** [comment]
waiting for activity :D

**Comment by 4relial** [comment]
+1

**Comment by dotKa** [comment]
sad story :( no comment, no idea

**Comment by satriowicaksn** [comment]
+1
