### ISSUE TITLE
[BUG] (?) Unable to send images through buffer/link

### ISSUE THREAD

**Issue by salsawij** [adiwajshing/Baileys#2419]
3221226505

the code above appears on console whenever I send images. Images aren't sent, instead the whole console froze and bot stops reading messages.

**Comment by tarikhagustia** [comment]
+1 yes, i have same issue

**Comment by Fonnte** [comment]
It's working fine sending message with buffer/url on my app. I am using edge version. What baileys version you are using? What are your socket config?

**Comment by zahmadz** [comment]
it's working fine here on my app, can we see your code and image link sample?

**Comment by salsawij** [comment]
> It's working fine sending message with buffer/url on my app. I am using edge version. What baileys version you are using? What are your socket config?

latest version, as for my code @zahmadz 
```await conn.sendMessage(from, { image: url })```

**Comment by Fonnte** [comment]
> > It's working fine sending message with buffer/url on my app. I am using edge version. What baileys version you are using? What are your socket config?
> 
> latest version, as for my code @zahmadz `await conn.sendMessage(from, { image: url })`

i think the correct code is `{image: {url: 'https://example.com/image.jpeg'}},` as stated in [docs ](https://github.com/adiwajshing/Baileys#media-messages)

**Comment by salsawij** [comment]
> > > It's working fine sending message with buffer/url on my app. I am using edge version. What baileys version you are using? What are your socket config?
> > 
> > 
> > latest version, as for my code @zahmadz `await conn.sendMessage(from, { image: url })`
> 
> i think the correct code is `{image: {url: 'https://example.com/image.jpeg'}},` as stated in [docs ](https://github.com/adiwajshing/Baileys#media-messages)

sorry, i meant image: buffer
