### ISSUE TITLE
[QUESTION] Can't streaming

### ISSUE THREAD

**Issue by areltiyan** [adiwajshing/Baileys#242]
If I send a video why do [receiver] have to **download** it first then can see it?

**The point is it can't streaming videos**

> Screenshot
![image](https://user-images.githubusercontent.com/54056041/100393577-bbc84e80-306c-11eb-97e3-a8b52d94dc2e.png)

**Comment by adiwajshing** [comment]
It is possible, you'll have to decrypt while downloading the video. I haven't needed it yet, so haven't implemented
