### ISSUE TITLE
[BUG] ev.on 'messages.delete' tidak berfungsi 

### ISSUE THREAD

**Issue by DEFF-Y** [adiwajshing/Baileys#2420]
client.ev.on("messages.delete", async (m) => {
	console.log(m)
	console.log('test')
	})

Saya membuat code seperti ini yang saya kira ini adalah untuk mendeteksi pesan yang telah dihapus

Tetapi saat dijalankan tidak terjadi apa apa pada log cmd saya

Tolong jelaskan apa kesalahanya

**Comment by FERDIZ-afk** [comment]
Harus bikin database chat nya dulu

**Comment by SanzGanzs** [comment]
> Harus bikin database chat nya dulu
🗿

**Comment by FERDIZ-afk** [comment]
> > Harus bikin database chat nya dulu
> > 🗿

Cek base bot punya saya

**Comment by banguncode** [comment]
Have U tried deleting messages for everyone? does the log appear?

**Comment by FERDIZ-afk** [comment]
> Have U tried deleting messages for everyone? does the log appear?

Yes, I've tried the logs to appear and it succeeded in forwarding the message again

**Comment by guiireal** [comment]
English please!

**Comment by FERDIZ-afk** [comment]
> English please!
it's also english

**Comment by FERDIZ-afk** [comment]
You can check the anti-delete code for messages on my base

https://github.com/FERDIZ-afk/bot-oni-chan
