### ISSUE TITLE
[BUG] Some options not working in templateButtons

### ISSUE THREAD

**Issue by DeveloperNewton** [adiwajshing/Baileys#2421]
- mentions not working
- ephemeralExpiration not working
- bug with quoted message
- even defining ephemeralExpiration, it appears as if it had not been defined
- and others bugs in templateButtons...

Code:

```
const isGroup = key.remoteJid.endsWith('g.us')
const groupMetadata = isGroup ? await sock.groupMetadata(key.remoteJid) : {}
await sock.sendMessage(key.remoteJid, {
	image: {
		url: 'testImg.jpeg'
	}, //or image: fs.readFileSync('testeImg.jpeg') // this a buffer
	footer: 'Test footer.',
	caption: 'Hello!\n\nThis a test caption with image atached.',
	mentions: isGroup ? groupMetadata.participants.map(membro => membro.id) : [key.remoteJid],
	templateButtons: [
		{
			index: 1,
			urlButton: {
				displayText: 'Test button.',
				url: 'https://www.google.com'
			}
		}
	]
}, {
	quoted: m,
	ephemeralExpiration: 604800 //this a one week
})
```

**Comment by FaizBastomi** [comment]
mentions and quoting message is not supported in templateButtons by default in WhatsApp

**Comment by AzRyCb** [comment]
> * mentions not working
> * ephemeralExpiration not working
> * bug with quoted message
> * even defining ephemeralExpiration, it appears as if it had not been defined
> * and others bugs in templateButtons...
> 
> Code:
> 
> ```
> const isGroup = key.remoteJid.endsWith('g.us')
> const groupMetadata = isGroup ? await sock.groupMetadata(key.remoteJid) : {}
> await sock.sendMessage(key.remoteJid, {
> 	image: {
> 		url: 'testImg.jpeg'
> 	}, //or image: fs.readFileSync('testeImg.jpeg') // this a buffer
> 	footer: 'Test footer.',
> 	caption: 'Hello!\n\nThis a test caption with image atached.',
> 	mentions: isGroup ? groupMetadata.participants.map(membro => membro.id) : [key.remoteJid],
> 	templateButtons: [
> 		{
> 			index: 1,
> 			urlButton: {
> 				displayText: 'Test button.',
> 				url: 'https://www.google.com'
> 			}
> 		}
> 	]
> }, {
> 	quoted: m,
> 	ephemeralExpiration: 604800 //this a one week
> })
> ```

Ephemeeal expiration use "7" or "14" and more
Not use 604800 for now

**Comment by DeveloperNewton** [comment]
A temporary solution for the button to be sent normally with an attached image:

`{
	quoted: null,
	ephemeralExpiration: 1
}`

!!! Using the variable m in quoted does not work, however, after testing, I saw that by setting quoted to null and setting ephemeralExpiration to 1, it sends normally, but does not send as temporary messages, it sends as if it were not going to disappear !!!

Another thing: a friend from discord support informed me that mentions only works on a normal button or a list button, it doesn't work on a templateButton. He said it's whatsapp standard (but I don't know if it's true)
