### ISSUE TITLE
[BUG] message.conversation is undefined for some message

### ISSUE THREAD

**Issue by nyongrand** [adiwajshing/Baileys#2426]
**Describe the bug**
When reading a text message, sometimes `msg.message.conversation` is undefined, so I need to handle it and instead read the message from `msg.message.extendedTextMessage.text`, but sometimes otherwise `msg.message.extendedTextMessage.text` is undefined and message goes on `msg.message.conversation`.

Actually what is the proper way to read chat message?

**To Reproduce**
1. Created a new connection
2. Wait until bot got chat message

**Comment by Alhar6i** [comment]
Good question, I hope one of the experts here can help! for me, I would test both against falsy until some one provides a better solution.

**Comment by ffauzan** [comment]
That is just how text message work.  It can be a conversation or extended text message. Handle it by checking conversation first, since text is here for majority of the time.
What I have found so far is:
Conversation: Simple text
Extended text message: Super long text that trigger "read more" button, Text with tag/mention

**Comment by nyongrand** [comment]
> That is just how text message work. It can be a conversation or extended text message. Handle it by checking conversation first, since the text is here for majority of the time. What I have found so far is: Conversation: Simple text Extended text message: Super long text that triggers "read more" button, Text with tag/mention

I think that is not true, I try sending 2 same message from 2 different number, surprisingly, one goes conversation, and the other goes to extendedTextMessage

**Comment by ffauzan** [comment]
> > That is just how text message work. It can be a conversation or extended text message. Handle it by checking conversation first, since the text is here for majority of the time. What I have found so far is: Conversation: Simple text Extended text message: Super long text that triggers "read more" button, Text with tag/mention
> 
> I think that is not true, I try sending 2 same message from 2 different number, surprisingly, one goes to conversation, and the other goes to extendedTextMessage

Is that reproducible?

I use message.conversation for getting command (command & its args < 150 characters) for my bot, and it never fails. Tested on multiple number & platform as well.

**Comment by Fonnte** [comment]
> > That is just how text message work. It can be a conversation or extended text message. Handle it by checking conversation first, since the text is here for majority of the time. What I have found so far is: Conversation: Simple text Extended text message: Super long text that triggers "read more" button, Text with tag/mention
> 
> I think that is not true, I try sending 2 same message from 2 different number, surprisingly, one goes to conversation, and the other goes to extendedTextMessage

Why is it be an issue? You can just look the at the response. If it's conversation, get the value, if it's extendedTextMessage, get the value.

**Comment by nyongrand** [comment]
> Is that reproducible?
> 
> I use message.conversation for getting command (command & its args < 150 characters) for my bot, and it never fails. Tested on multiple number & platform as well.

I spent a few days looking at incoming messages, and unfortunately, I can't determine which messages went to conversations or which went to messages.



> Why is it be an issue? You can just look the at the response. If it's conversation, get the value, if it's extendedTextMessage, get the value.

I'm reporting this problem at least, if someone has this problem, he shouldn't waste his time, looking for bugs, because I can't find any documentation that points here.

**Comment by Alhar6i** [comment]
> > That is just how text message work. It can be a conversation or extended text message. Handle it by checking conversation first, since the text is here for majority of the time. What I have found so far is: Conversation: Simple text Extended text message: Super long text that triggers "read more" button, Text with tag/mention
> 
> I think that is not true, I try sending 2 same message from 2 different number, surprisingly, one goes to conversation, and the other goes to extendedTextMessage

Did you send the messages from the same mobile? or you used different mobiles? e.g iPhone, Androed etc

**Comment by nyongrand** [comment]
> Did you send the messages from the same mobile? or you used different mobiles? e.g iPhone, Androed etc

Testing on 2 different Android phone, Group and Private, one number always goes to conversation the other always goes to Extended Message

**Comment by arugaz** [comment]
> **Describe the bug** When reading a text message, sometimes `msg.message.conversation` is undefined, so I need to handle it and instead read the message from `msg.message.extendedTextMessage.text`, but sometimes otherwise `msg.message.extendedTextMessage.text` is undefined and message goes on `msg.message.conversation`.
> 
> Actually what is the proper way to read chat message?
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Created a new connection
> 
>     2. Wait until bot got chat message

Maybe this can help you [look at the parsing body (message text)](https://github.com/arugaz/whatsapp-bot/blob/master/src/utils/whatsapp.utils/serialize/message.ts#L31)
