### ISSUE TITLE
[BUG] Waiting for message or uncompatible version of whatsapp when sending message to groups

### ISSUE THREAD

**Issue by andresavila1982** [adiwajshing/Baileys#2429]
**Describe the bug**

When sending message to groups, the messages doesn't appear. Instead it shows randomly one of those 2 legends. Incompatible version or waiting for message. 
if you try to send again the same message, the message arrives perfectly. It happens every 1 of 2 messages sent to the group.

**To Reproduce**
1. Send a message to the group.
2. incompatible version or waiting for message legend
3. re-send the message, message arrives perfectly.

**Expected behavior**
Message used to arrive perfectly fine on the first try.

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**

It starts to fail 2 weeks ago.

**Comment by andresavila1982** [comment]
This still happens with 5.0.0 version

**Comment by reneroth** [comment]
Try reauthenticating with the baileys client, it should work then.
