### ISSUE TITLE
[BUG] Some of Wa tracking apps do not show "Active" after user scans qr code but still can track while not showing active. How it is possible.

### ISSUE THREAD

**Issue by waaplog** [adiwajshing/Baileys#2431]
**Please Help**
if you use "sendPresenceUpdate("unavailable") " you can not use or get any data from "presenceSubscribe(jid)" but somehow some of the apps can still track and stays unactive at he same time.
Please we need help.
Best regards.

**Comment by Fonnte** [comment]
you cannot see the other presence when you are not let them see yours. read this : https://faq.whatsapp.com/419827870318306

**Comment by waaplog** [comment]
English:
-----------------------------------
Hello,
Due to new Whatsapp update right now no app can track the numbers. We are on to a new solution we will fix it in one or two days. Thank you for your patience.
Best regards.

عربي:
-----------------------------------
مرحبًا،
نظرًا لتحديث Whatsapp الجديد في الوقت الحالي ، لا يمكن لأي تطبيق تتبع الأرقام. نحن بصدد حل جديد وسنصلحه خلال يوم أو يومين. شكرا لك على صبرك.
مع أطيب التحيات.

Español:
--------------------------------------------------
Hola,
Debido a la nueva actualización de Whatsapp en este momento, ninguna aplicación puede rastrear los números. Estamos en una nueva solución, la arreglaremos en uno o dos días. Gracias por su paciencia.
Saludos.


Türkçe:
----------------------------------
Merhaba,
Yeni Whatsapp güncellemesi nedeniyle şu anda hiçbir uygulama numaraları izleyemiyor. Yeni bir çözüm peşindeyiz, bir veya iki gün içinde düzelteceğiz. Sabrınız için teşekkürler.
Saygılarımla.

**Comment by waaplog** [comment]
Thank you for your response. @Fonnte
