### ISSUE TITLE
[BUG] Blank Sticker

### ISSUE THREAD

**Issue by feri-irawan** [adiwajshing/Baileys#2432]
**Describe the bug**
I sent the sticker, I received the sticker, but the sticker is blank

**To Reproduce**
```js
const url = "https://thestikerurl.com"; // <-- return content of type `image/png`
await sock.sendMessage(id, {
  sticker: { url },
});
```

![49205930-7f03e700-f3c1-11e8-9e61-bc698e238226](https://user-images.githubusercontent.com/57158078/209977176-5da15b45-53b8-4d1e-ac37-e8d50c49b913.png)

**Comment by undefined-60** [comment]
> **Descreva o bug** Enviei o adesivo, recebi o adesivo, mas o adesivo está em branco
> 
> **Para reproduzir** Etapas para reproduzir o comportamento:
> 
> ```js
> const url = "https://thestikerurl.com"; // <-- return content of type `image/png`
> await sock.sendMessage(id, {
>   sticker: { url },
> });
> ```
> 
> ![49205930-7f03e700-f3c1-11e8-9e61-bc698e238226](https://user-images.githubusercontent.com/57158078/209977176-5da15b45-53b8-4d1e-ac37-e8d50c49b913.png)

Você está mandando no formato "image/png" uma sticker deve estar em "image/webp" use algum programa (ffmpeg etc...) para mudar o mimetype da imagem

**Comment by Piyoxz** [comment]
const url = "https://thestikerurl.com"; // <-- return content of type `image/png`
await sock.sendMessage(id, { sticker: {url : url} });

**Comment by pandigresik** [comment]
use image with format webp not png or jpg

**Comment by feri-irawan** [comment]
> use image with format webp not png or jpg

it worked, thanks a lot
