### ISSUE TITLE
error in sending keep alive [BUG]

### ISSUE THREAD

**Issue by ngadimin51** [adiwajshing/Baileys#2435]
I got this on connection error.
Any body got same issues?

INFO [2022-12-30 18:29:12.371 +0700]: connection errored
    trace: "Error: Connection was lost\n    at Timeout._onTimeout (...\\lib\\Socket\\socket.js:289:17)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)"
ERROR [2022-12-30 18:29:57.381 +0700]: error in sending keep alive
    trace: "Error: Timed Out\n    at ...\\lib\\Utils\\generics.js:157:32"

**Comment by ngadimin51** [comment]
So, nobody got error like me?

**Comment by danishb01** [comment]
I am getting the same issue!
