### ISSUE TITLE
Using lib in a webextension

### ISSUE THREAD

**Issue by zoutepopcorn** [adiwajshing/Baileys#244]
This lib looks great, and works fine in node.js

The connection:
```
import WS from 'ws'
```
is working fine in nodejs, but now it's impossible to run in a chrome extension. Maybe it's possible to connect from the extension even without visiting web.whatsapp.com

Hopefully we can also use the browser websocket to connect..

**Comment by itacirgabral** [comment]
I would suggest something like [isomorphic-ws](https://www.npmjs.com/package/isomorphic-ws)

From [ws](https://github.com/websockets/ws) readme:
> Note: This module does not work in the browser. (...). To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like isomorphic-ws.

**Comment by zoutepopcorn** [comment]
Ah thanks, that would be great.

I'm sure we need to set the origin header from the websocket now. Tested it without, and failed. The browser is not able to do that. I'm not sure if the chrome extension can do it...

https://stackoverflow.com/questions/22868897/access-websocket-traffic-from-chrome-extension

Or we need to inject it to web.whatsapp.com or just injecting a favicon to connect. I don't know whats possible. If the 'fs' is kept outside the lib, we could save login info in localstorage or something..

**Comment by itacirgabral** [comment]
https://github.com/sigalor/whatsapp-web-reveng#javascript
> just needed because browsers don't allow changing HTTP headers for WebSockets
> (...)
> Also make sure that, when establishing the connection, the HTTP header `Origin: https://web.whatsapp.com` is set, otherwise the connection will be rejected.

https://github.com/sigalor/whatsapp-web-reveng/blob/db7e54755d3fe08f6f34d1d71e42fedbee2c8fd1/index_jsdemo.js#L12
```javascript
new WebSocket("wss://web.whatsapp.com/ws", { headers: { "Origin": "https://web.whatsapp.com" } })
```

**Comment by zoutepopcorn** [comment]
Yes, but this is nodejs I think... In a chrome extension, we have to do a other trick I think
