### ISSUE TITLE
Better ESM Support

### ISSUE THREAD

**Issue by Waxaranai** [adiwajshing/Baileys#2452]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**
I'm trying to use this lib with esm and typescript but i couldn't get it working,

e.g: `got` require the `moduleResolution` to be either Node16 or NodeNext, but when i changed it to those. baileys import throwed error. 

see the image below
![Screenshot_2023-01-04-18-44-17-185_com android chrome](https://user-images.githubusercontent.com/32866617/210549581-d02eaaa5-095a-494b-bcb0-62a18919cfe1.png)

**Comment by Verzach3** [comment]
Let me see how you are importing the library, i'm using typescript with esm modules without trouble

**Comment by renatokeys** [comment]
import { makeWASocket } from "@adiwajshing/baileys"
should work,
