### ISSUE TITLE
[BUG] Weird log's 

### ISSUE THREAD

**Issue by AliAryanTech** [adiwajshing/Baileys#2455]
**Describe the bug**
It's giving weird log's - [Check](https://pastebin.com/raw/YubcFnZE)

**To Reproduce**
Skip 

**Expected behavior**
Skip

**Environment (please complete the following information):**
Railway server, it was working fine but after I updated to 5.0 it start giving those log's 

**Additional context**
Add buttons support, it's not visible 🥺

**Comment by arugaz** [comment]
It looks like #2369

**Comment by AliAryanTech** [comment]
> It looks like #2369

excectly, so I need to close this? Coz this issue already exist.

**Comment by kamuridesu** [comment]
yeah just close it and wait for the fix to be merged
