### ISSUE TITLE
Tag all the members of group

### ISSUE THREAD

**Issue by re-Destro** [adiwajshing/Baileys#246]
How i can tag all the member of groups, or how i can get the nickname of the members of groups?

**Comment by Quiec** [comment]
Example code I wrote: https://github.com/Quiec/WhatsAsena/blob/master/plugins/tagall.js

**Comment by re-Destro** [comment]
> Example code I wrote: https://github.com/Quiec/WhatsAsena/blob/master/plugins/tagall.js

Thanks bruh...
