### ISSUE TITLE
send a template message not working[BUG]

### ISSUE THREAD

**Issue by baljeetachra** [adiwajshing/Baileys#2461]
send a template message Not working. it recive on same number which we use to send.
//send a template message!
const templateButtons = [
    {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
    {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
    {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const templateMessage = {
    text: "Hi it's a template message",
    footer: 'Hello World',
    templateButtons: templateButtons
}

**Comment by manojsitapara** [comment]
Add viewonce:true in templateMessage

**Comment by FERDIZ-afk** [comment]
> send a template message Not working. it recive on same number which we use to send. //send a template message! const templateButtons = [ {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}}, {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}}, {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}}, ]
> 
> const templateMessage = { text: "Hi it's a template message", footer: 'Hello World', templateButtons: templateButtons }

Add this code below printQRTerminal 


		patchMessageBeforeSending: (message) => {
                const requiresPatch = !!(
                  message.buttonsMessage
              	  || message.templateMessage
              		|| message.listMessage
                );
                if (requiresPatch) {
                    message = {
                        viewOnceMessage: {
                            message: {
                                messageContextInfo: {
                                    deviceListMetadataVersion: 2,
                                    deviceListMetadata: {},
                                },
                                ...message,
                            },
                        },
                    };
                }
                return message;
    },

**Comment by aarzaary** [comment]
@manojsitapara @FERDIZ-afk have u try send to IOS?

**Comment by manojsitapara** [comment]
> @manojsitapara @FERDIZ-afk have u try send to IOS?

Yes

**Comment by TaufikR30** [comment]
> > @manojsitapara @FERDIZ-afk have u try send to IOS?
> 
> Yes

After re-scanning was your button somehow sent by the receiver?

**Comment by aarzaary** [comment]
@manojsitapara buttons template work in IOS?

**Comment by ralfiannor** [comment]
Button template still not work in ios but working well in android and web

**Comment by unilogica** [comment]
Same problem here. With `patchMessageBeforeSending` solves list buttons, but not working with template buttons.

What happens is in the number that sends the message I can see the `urlButton` and the `callButton`, but not the `quickReplyButton`.

On the side of the person who receives the message, he doesn't see anything, neither the text message nor any of the 3 types of buttons.
