### ISSUE TITLE
428 Precondition Required

### ISSUE THREAD

**Issue by xXDeonoXx** [adiwajshing/Baileys#2465]
**Describe the bug**
A Connected account/number stops sending and receiving messages after some random time and i keep receiving 428 status code when sock.sendMessage is called.

**To Reproduce**
I don't know how to reproduce this issue, it usually happens after some time (a few hours) and i't only get back to normal
when i fully reconnect the number trough qr code.

**Expected behavior**
The socket don't return 428 when trying to send a message.

**Environment (please complete the following information):**
 - Is this on a server? 
 Yes, but the issue happens locally too.
 
 - What do your `connectOptions` look like? 
 
    const { version } = await fetchLatestBaileysVersion();
    const { state, saveCreds } = await useMultiFileAuthState(
      `./auth/${instance_id}`,
    );

    const sock: WASocket = makeWASocket({
      version,
      printQRInTerminal: false,
      auth: state,
      browser: ['Browser Name', 'Firefox', '106.0.5'],
      connectTimeoutMs: 60_000,
      keepAliveIntervalMs: 60_000,
      defaultQueryTimeoutMs: 60_000,
    });
 
 
 - Do you have multiple clients on the same IP?
   Yes.
   
 - Are you using a proxy?
   No.

**Additional context**

![image](https://user-images.githubusercontent.com/45169227/211398651-fda8851b-10de-4d46-bb11-6d810b4f821b.png)

**Comment by salykingleb** [comment]
Process the error 428 and after receiving it, send the account to the reconnect

**Comment by xXDeonoXx** [comment]
> Process the error 428 and after receiving it, send the account to the reconnect

There is a correct way to reconnect a WA socket ? Our current method calls our connect function again and make the connection process as it do when is starting.

**Comment by andrody** [comment]
Same error with me

**Comment by growupmarketingdigital** [comment]
same here! I did same as described above, tryed to reconnect after the error, but no success... please help

**Comment by salykingleb** [comment]
> * instance_id

It should look something like the code below.



recon = [428, 408, 500] 
h = instance_id


if (recon.includes(lastDisconnect.error.output.statusCode)) {
					if (!noCount.includes(lastDisconnect.error.output.statusCode))
						recon_wa[h].recon += 5;
					setTimeout(() => {
						WA.session(
							h,
							async(X) => {
								sessions[h] = X
							},
							false
						)
					}, 10000)
					return;

**Comment by xXDeonoXx** [comment]
i implemented the setTimeout here as well and nothing changed...
