### ISSUE TITLE
[BUG] qr taking 20-25s to generate

### ISSUE THREAD

**Issue by ahmedRSA** [adiwajshing/Baileys#2467]
**Describe the bug**
- **qr is taking 20-25second to generate tried everything  but same problem** 

**To Reproduce**
1. **use default example code**

**Expected behavior**
- **qr to generate fast**

**Environment (please complete the following information):**
 - Is this on a server? **NO**
 - What do your `connectOptions` look like?  **default**
 - Do you have multiple clients on the same IP? **NO**
 - Are you using a proxy? **NO**

**Comment by ahmedRSA** [comment]
qr event fires after 20-25s what could be reason of this?

**Comment by ahmedRSA** [comment]
this function is on loop till 20-25s 
then qr generated
![image](https://user-images.githubusercontent.com/77731877/211550605-95cc1e65-5895-4788-a6ea-130cfe4fface.png)

**Comment by ahmedRSA** [comment]
@adiwajshing can you help?

**Comment by panalgin** [comment]
I have run the example project and it immediately generates the QR, then it gets refreshed every 20 or 30 seconds for like 7-8 times. I can't see an issue, what is it you're trying to do?

**Comment by ahmedRSA** [comment]
is there any way i can debug events?
