### ISSUE TITLE
[BUG] Cannot read property 'lastKnownPresence' of undefined

### ISSUE THREAD

**Issue by dinnos** [adiwajshing/Baileys#247]
**Describe the bug**
When it's the first contact with a contact (sending or receiving) the message is not delivered/handled and the lib throws the error: 

<img width="763" alt="Captura de Pantalla 2020-11-28 a la(s) 14 02 18" src="https://user-images.githubusercontent.com/25092933/100524956-55355480-3182-11eb-9836-202188a60109.png">

**To Reproduce**
1. Created a new connection
2. Send/Receive message from unknown number (contact)  

**Expected behavior**
Omit the validation of presence and receive the message.

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like?  
<img width="460" alt="Captura de Pantalla 2020-11-28 a la(s) 14 04 23" src="https://user-images.githubusercontent.com/25092933/100524988-a04f6780-3182-11eb-896f-ad3dec3bd012.png">

 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**

**Comment by adiwajshing** [comment]
Can you try the latest commit & see if that fixes the problem? Thanks for following the template

**Comment by dinnos** [comment]
Thanks @adiwajshing I see that is already working.

**Comment by dinnos** [comment]
Thanks @adiwajshing I see that is already working.
