### ISSUE TITLE
node:internal/process/promises:288

### ISSUE THREAD

**Issue by Shubhamrawat5** [adiwajshing/Baileys#2470]
My bot is crashing randomly every like 1 hour and getting this error. Any idea why this is happening

node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
<ref *1> Error: connect ETIMEDOUT 2a03:2880:f22d:c5:face:b00c:0:167:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
errno: -110,
code: 'ETIMEDOUT',
syscall: 'connect',

**Comment by Shubhamrawat5** [comment]
Also this

node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
<ref *1> Error: getaddrinfo ENOTFOUND web.whatsapp.net
at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:84:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',

**Comment by salykingleb** [comment]
+1

**Comment by Shubhamrawat5** [comment]
one more

node:internal/errors:704
const ex = new Error(msg);
^
Error: socket hang up
at connResetException (node:internal/errors:704:14)
at TLSSocket.socketOnEnd (node:_http_client:489:23)
at TLSSocket.emit (node:events:549:35)
at endReadableNT (node:internal/streams/readable:1359:12)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
code: 'ECONNRESET',

**Comment by Shubhamrawat5** [comment]
Another

node:internal/process/promises:288
triggerUncaughtException(err, true /* fromPromise */);
^
<ref *1> Error: read ECONNRESET
at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
errno: -104,
code: 'ECONNRESET',
syscall: 'read',
config: {

**Comment by Shubhamrawat5** [comment]
Found the problem.

Coming because of sending message from bot.sendMessage() and I didn't use proper try catch for await async function

**Comment by SarkarJobs** [comment]
+1

**Comment by vfa-tanna** [comment]
+1

**Comment by anand-netzoptimize** [comment]
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);

**Comment by alizaib0573** [comment]
> Found the problem.
> 
> Coming because of sending message from bot.sendMessage() and I didn't use proper try catch for await async function

Can you hlp how could you solve this problm

**Comment by coycoylaniba** [comment]
is there any fix for this?

**Comment by GuidoPisarra** [comment]
Hi, the solution I found so far is to put the code inside a try catch block.
