### ISSUE TITLE
[MD] Change online or offline after synchronizing

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2471]
Good night,

It is currently configured in the connection settings whether WhatsApp will be online or offline after synchronizing the session, is it possible to change between online and offline using some function after synchronizing WhatsApp?

**Comment by DikaArdnt** [comment]
> Good night,
> 
> It is currently configured in the connection settings whether WhatsApp will be online or offline after synchronizing the session, is it possible to change between online and offline using some function after synchronizing WhatsApp?

[read documentation](https://github.com/adiwajshing/Baileys/blob/master/README.md#configuring-the-connection)

**Comment by AlanMartines** [comment]
The "markOnlineOnConnect" parameter, as far as I know, is used to leave the status always online or offline, I would like to know if there is a way for me to switch between online and offline at any time after the WhatsApp sync.
