### ISSUE TITLE
 Ban 

### ISSUE THREAD

**Issue by Ningoje** [adiwajshing/Baileys#2473]
sometimes using` groupParticipantsUpdate` leads to immediate ban

**Comment by calix666** [comment]
if you add or delete user to a group you will be suspend your number

**Comment by Ningoje** [comment]
![Screenshot_20230113-000434](https://user-images.githubusercontent.com/93015830/212309523-bb36b1e1-d565-46ba-b791-a413a2b76802.png)

The ban happens when adding user with this enabled

**Comment by gqlxj1987** [comment]
Yes, add user would be ban, but promote not. Other people can join group with group invite links

**Comment by fnevesgx** [comment]
Same to me, but give error on create group with my contact, could be something exclusive from wa bussiness?

**Comment by fnevesgx** [comment]
Update: ban occurs with regular wa too when creating group too
