### ISSUE TITLE
[BUG] Cannot use import statement outside a module.

### ISSUE THREAD

**Issue by TheRadioDept** [adiwajshing/Baileys#2475]
Hello. 

I've faced an error while trying to execute `node example.ts`. 
I've cloned the repo, made connection to my WhatsApp account, and executed `yarn add @hapi/boom.` But after running mentioned command, I am facing the following error: 
`import { Boom } from '@hapi/boom'`
`SyntaxError: Cannot use import statement outside a module`

Any help would be appreciated!

**Comment by hansputera** [comment]
Have you tried `yarn example` or `node --inspect -r ts-node/register example.ts` ?

**Comment by TheRadioDept** [comment]
Yes. `yarn example` is working fine for me. But I was wondering why can't I run 'node example.ts'.
Sorry if I'm asking smth weird, I'm pretty new to this all.

**Comment by SheIITear** [comment]
Not baileys error, learn js/ts.
