### ISSUE TITLE
[BUG] cannot read type message of viewOnce

### ISSUE THREAD

**Issue by affisjunianto** [adiwajshing/Baileys#2480]
why my bot can't read viewOnce message. before he could. but now it can't even though I didn't change anything from before

**Comment by AzRyCb** [comment]
Use viewoncev2

**Comment by affisjunianto** [comment]
> Use viewoncev2

how to use that

i use getContentType but can read view once

**Comment by AliAryanTech** [comment]
> why my bot can't read viewOnce message. before he could. but now it can't even though I didn't change anything from before

**Use this**
```js
const buffer = await downloadMediaMessage(sock.message.viewOnceMessageV2.message)
```
thank me later, also close this issue then.

**Comment by affisjunianto** [comment]
> > why my bot can't read viewOnce message. before he could. but now it can't even though I didn't change anything from before
> 
> **Use this**
> 
> ```js
> const buffer = await downloadMediaMessage(sock.message.viewOnceMessageV2.message)
> ```
> 
> thank me later, also close this issue then.

thanks dude
