### ISSUE TITLE
[BUG] - Checking Number for onWhatsApp - nothing happen when use 

### ISSUE THREAD

**Issue by mzayn** [adiwajshing/Baileys#2485]
**Describe the bug**

Bug for onWhatsApp For checking number where are used this option 

```
const id = '123456'
const [result] = await sock.onWhatsApp(id)
if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)
```

get nothing result for latest bailey 

Hope have an update for this! or alternative. 

Thanks 

**Additional context**

**Comment by DikaArdnt** [comment]
> **Jelaskan bugnya**
> 
> Bug untuk onWhatsApp Untuk memeriksa nomor di mana opsi ini digunakan
> 
> ```
> const id = '123456'
> const [result] = await sock.onWhatsApp(id)
> if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)
> ```
> 
> mendapatkan hasil apa-apa untuk bailey terbaru
> 
> Semoga ada pembaruan untuk ini! atau alternatif.
> 
> terima kasih
> 
> **Konteks tambahan** Tambahkan konteks lain tentang masalah di sini.

![IMG_20230116_033937](https://user-images.githubusercontent.com/88322331/212566035-b255251b-1e18-4665-a10d-04f5fdd99c54.jpg)

the function works, They will have results if the number you entered is correct and they will not have results alias blank if they enter a wrong number/invalid number

**Comment by mzayn** [comment]
> ```
> const [result] = await sock.onWhatsApp(id)
> if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)
> ```

hmm i was write code like this but nothing happen 

```
return await client.onWhatsApp(number).then(([result]) => {
        //console.log('Result:\n', result); //return object success
        //
        if (result.exists) {
          return {
            "erro": false,
            "status": 200,
            "number": result.jid,
            "message": "registered"
          };
          //
        } else if (!result.exists) {
          //
          return {
            "erro": true,
            "status": 404,
            "number": result.jid,
            "message": "not register"
          };
          //
        } else {
          //
          return {
            "erro": true,
            "status": 404,
            "message": "wrong num > "+ number
          };
          //
        }
      }).catch((erro) => {
        console.error('Error when sending:\n', erro); //return object error
        //
        return {
          "erro": true,
          "status": 404,
          "message": "wrong num > " + number
        };
        //
      });

**Comment by BlackAmda** [comment]
> > ```
> > const [result] = await sock.onWhatsApp(id)
> > if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)
> > ```
> 
> hmm i was write code like this but nothing happen
> 
> ```
> return await client.onWhatsApp(number).then(([result]) => {
>         //console.log('Result:\n', result); //return object success
>         //
>         if (result.exists) {
>           return {
>             "erro": false,
>             "status": 200,
>             "number": result.jid,
>             "message": "registered"
>           };
>           //
>         } else if (!result.exists) {
>           //
>           return {
>             "erro": true,
>             "status": 404,
>             "number": result.jid,
>             "message": "not register"
>           };
>           //
>         } else {
>           //
>           return {
>             "erro": true,
>             "status": 404,
>             "message": "wrong num > "+ number
>           };
>           //
>         }
>       }).catch((erro) => {
>         console.error('Error when sending:\n', erro); //return object error
>         //
>         return {
>           "erro": true,
>           "status": 404,
>           "message": "wrong num > " + number
>         };
>         //
>       });
> ```

Your code is working fine. And example code given by Baileys documentation also working fine. But the problem is if someone's number doesn't exists on WhatsApp, it doesn't give the result you expect.

- Example:
```js
const id = '123'
const [result] = await sock.onWhatsApp(id)
console.log(result)

/*
Expected result:
 * Since you cannot register only three numbers, the result should be as follows,
    { exists: false, jid: '123@s.whatsapp.net' }

But actual result:
    undefined
*/
```
So, you can't get `if (!result.exists)` to check the unregistered status. Instead, use `if (!result)`. 🙂

**Comment by AliAryanTech** [comment]
> > > ```
> > > const [result] = await sock.onWhatsApp(id)
> > > if (result.exists) console.log (`${id} exists on WhatsApp, as jid: ${result.jid}`)
> > > ```
> > 
> > 
> > hmm i was write code like this but nothing happen
> > ```
> > return await client.onWhatsApp(number).then(([result]) => {
> >         //console.log('Result:\n', result); //return object success
> >         //
> >         if (result.exists) {
> >           return {
> >             "erro": false,
> >             "status": 200,
> >             "number": result.jid,
> >             "message": "registered"
> >           };
> >           //
> >         } else if (!result.exists) {
> >           //
> >           return {
> >             "erro": true,
> >             "status": 404,
> >             "number": result.jid,
> >             "message": "not register"
> >           };
> >           //
> >         } else {
> >           //
> >           return {
> >             "erro": true,
> >             "status": 404,
> >             "message": "wrong num > "+ number
> >           };
> >           //
> >         }
> >       }).catch((erro) => {
> >         console.error('Error when sending:\n', erro); //return object error
> >         //
> >         return {
> >           "erro": true,
> >           "status": 404,
> >           "message": "wrong num > " + number
> >         };
> >         //
> >       });
> > ```
> 
> Your code is working fine. And example code given by Baileys documentation also working fine. But the problem is if someone's number doesn't exists on WhatsApp, it doesn't give the result you expect.
> 
> * Example:
> 
> ```js
> const id = '123'
> const [result] = await sock.onWhatsApp(id)
> console.log(result)
> 
> /*
> Expected result:
>  * Since you cannot register only three numbers, the result should be as follows,
>     { exists: false, jid: '123@s.whatsapp.net' }
> 
> But actual result:
>     undefined
> */
> ```
> 
> So, you can't get `if (!result.exists)` to check the unregistered status. Instead, use `if (!result)`. 🙂

🤔 Well, why it use Array? [result] I mean can we check multiple numbers at a time?? 
If (yes) return how? 
else return "they should make Array Object to Object only"

**Comment by BlackAmda** [comment]
No, you can't

**Comment by AliAryanTech** [comment]
> No, you can't

Then don't you think they should change Array to single Object:
```js
const id = '123@s.whatsapp.net'
const result = await sock.onWhatsApp(id)
if (result) console.log(result)
// [{ exists: false, jid: '123@s.whatsapp.net' }] to 
// { exists: false, jid: '123@s.whatsapp.net' }
```

**Comment by BlackAmda** [comment]
> > No, you can't
> 
> Then don't you think they should change Array to single Object:
> 
> ```js
> const id = '123@s.whatsapp.net'
> const result = await sock.onWhatsApp(id)
> if (result) console.log(result)
> // [{ exists: false, jid: '123@s.whatsapp.net' }] to 
> // { exists: false, jid: '123@s.whatsapp.net' }
> ```
> 
> I checked the [code](https://github.com/adiwajshing/Baileys/blob/master/src/Socket/chats.ts#L106) even it accept the `string[]` still give no result when `array > 0`

I also checked giving multiple numbers like below,
```js
const [result] = await sock.onWhatsApp('123456', '12345', '456789')``

After running the code, it shows an error and closes the connection. If they coded it as an array for the purpose of providing an option to check multiple numbers, they should fix that.

**Comment by AliAryanTech** [comment]
> > > No, you can't
> > 
> > 
> > Then don't you think they should change Array to single Object:
> > ```js
> > const id = '123@s.whatsapp.net'
> > const result = await sock.onWhatsApp(id)
> > if (result) console.log(result)
> > // [{ exists: false, jid: '123@s.whatsapp.net' }] to 
> > // { exists: false, jid: '123@s.whatsapp.net' }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I checked the [code](https://github.com/adiwajshing/Baileys/blob/master/src/Socket/chats.ts#L106) even it accept the `string[]` still give no result when `array > 0`
> 
> I also checked giving multiple numbers like below,
> 
> ```js
> const [result] = await sock.onWhatsApp('123456', '12345', '456789')
> ```
> 
> After running the code, it shows an error and closes the connection. If they coded it as an array for the purpose of providing an option to check multiple numbers, they should fix that.

**Indeed**

**Comment by AliAryanTech** [comment]
> In what format should I enter the number to the id value?

I guess, you mean what typo 🗿
It's string "123@s.whatsapp.net"

**Comment by theCoderrrr** [comment]
data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
} 
I get an error like this. I enter the id variable as country code + number

**Comment by AliAryanTech** [comment]
> data: null, isBoom: true, isServer: false, output: { statusCode: 428, payload: { statusCode: 428, error: 'Precondition Required', message: 'Connection Closed' }, headers: {} } } I get an error like this. I enter the id variable as country code + number

Sometimes, this error occurred..
 just write your number without + symbol as "123@s.whatsapp.net"
