### ISSUE TITLE
Don't respond when the client is not running

### ISSUE THREAD

**Issue by pa7rickr** [adiwajshing/Baileys#2487]
Hello, 

How to make the bot not respond when the client is not running. 

If the client is turned on, the bot will start in a new chat (does not load old chats when the client is not running).

**Comment by DikaArdnt** [comment]
> Hello,
> 
> How to make the bot not respond when the client is not running.
> 
> If the client is turned on, the bot will start in a new chat (does not load old chats when the client is not running).

[understand this](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#L115)

**Comment by pa7rickr** [comment]
> > Hello,
> > How to make the bot not respond when the client is not running.
> > If the client is turned on, the bot will start in a new chat (does not load old chats when the client is not running).
> 
> [understand this](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#L115)

thanks for information.
