### ISSUE TITLE
Whatsapp add to cart 

### ISSUE THREAD

**Issue by Valentine-Mario** [adiwajshing/Baileys#249]
Whatsapp recently added a new features for whatsapp business accounts where clients can add items to cart and reply business owners as a quoted message of the items they've added to their cart. 

But whenever I receive a new cart quoted message from client, I can't seem to be able to get  the quoted message or conversation from the reply. The payload I receive is: 
`
WebMessageInfo {
  messageStubParameters: [],
  labels: [],
  key:
   MessageKey {
     remoteJid: '2349033720347@s.whatsapp.net',
     fromMe: false,
     id: '6E4E5DB8EBE0920BCC574BF27BFA912F' },
  message: Message {},
  messageTimestamp: Long { low: 1606728277, high: 0, unsigned: true },
  status: 0,
  ephemeralOutOfSync: false,
  epoch: 101 }
`
As you can see the message payload is empty. Is there any way to decode this cart item information received from my clients?

**Comment by adiwajshing** [comment]
Might have to update the protobuf for that
