### ISSUE TITLE
[BUG] Messages with button send but not arrived

### ISSUE THREAD

**Issue by nagatowell** [adiwajshing/Baileys#2499]
I use for one month all the api and everything works fine, but today, when I try to send, I do not receive error, in the whatsapp the message is sent, but does not arrive to destination phone.

Messages without buttons, is working normal.

Someone know how I can try to resolve that?

<img width="564" alt="Captura de Tela 2023-01-18 às 19 59 23" src="https://user-images.githubusercontent.com/13136456/213315293-253a366f-a9e3-4567-bb84-19b0cc281124.png">

<img width="588" alt="Captura de Tela 2023-01-18 às 19 59 36" src="https://user-images.githubusercontent.com/13136456/213315302-d64dc492-809e-49d9-a0c1-71fc139c3c05.png">

<img width="813" alt="Captura de Tela 2023-01-18 às 20 00 48" src="https://user-images.githubusercontent.com/13136456/213315309-7bda45bd-50e7-4254-a19d-236ef0862a81.png">

**Environment (please complete the following information):**
 - Is this on a server? Yes, running in docker on aws
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by Falkon1610** [comment]
Maybe you can add this to your makeWASocket options

`const sock = makeWASocket({
            // can provide additional config here
            ...
            printQRInTerminal: true,
            patchMessageBeforeSending: (message) => {
                const requiresPatch = !!(
                    message.buttonsMessage ||
                    // || message.templateMessage
                    message.listMessage
                );
                if (requiresPatch) {
                    message = {
                        viewOnceMessage: {
                            message: {
                                messageContextInfo: {
                                    deviceListMetadataVersion: 2,
                                    deviceListMetadata: {},
                                },
                                ...message,
                            },
                        },
                    };
                }

                return message;
            },
    })`
    
    [2328#issuecomment](https://github.com/adiwajshing/Baileys/issues/2328#issuecomment-1351048162)

**Comment by nagatowell** [comment]
Cool, that's it, it works.


Thanks a lot for that.
