### ISSUE TITLE
Problem running oficial package: SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by eduardobento** [adiwajshing/Baileys#25]
The problem dont run, except in line above:

```
2020-05-28T00:15:51.751600+00:00 app[web.1]: /app/node_modules/baileys/WhatsAppWeb.js:116
2020-05-28T00:15:51.751642+00:00 app[web.1]:                 type: ackTypes[json.ack-1] ?? "unknown (" + json.ack + ")"
```

In localhost I just changed to ```type: ackTypes[json.ack-1] ? "unknown (" + json.ack + ")" : ""``` but in cloud I dont can change.

**Comment by adiwajshing** [comment]
Oh this is an issue with older versions of node. The ?? operator isn’t available on older versions of node, I’ll fix it up.

**Comment by adiwajshing** [comment]
This is fixed in the latest commit.

**Comment by eduardobento** [comment]
Great ! It works, thanks.
