### ISSUE TITLE
[BUG] listReply is not recognized in sendMessage's content

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#2501]
**Describe the bug**
In lib/Utils/messages.js there is a missing `else if` block, that is to check if the message has "`listReply`". I checked the Typescript one it is there but, in the Javascript one it's missing

**messages.js:**
![image](https://user-images.githubusercontent.com/84653497/213383212-c9f4fbb6-84ad-459d-a010-fe23b62e89a7.png)

**messages.ts:**
![image](https://user-images.githubusercontent.com/84653497/213383346-b98adf89-70d2-48ba-ae56-1cae3e2dfe39.png)

And so trying to send a listReply (using Javascript) results in an error because "listReply" is considered invalid media

**To Reproduce**
const listReply = {
  listType: 1,
  title: 'Example title from list option',
  description: 'Example description',
  singleSelectReply: {
    { selectedRowId: 'exampleRowId' }
  }
}
sock.sendMessage(jid, { listReply: {listType:1, title, desctiption, singleSelectReply: {selectedRowId}} })

**Expected behavior**
It should send a message like when you click on an option in a list message

**Comment by calix666** [comment]
sock.sendMessage(msg.from,{
    text: 'Lista de seleccion',
    footer: "_🤖SkyBot_",
    title: `*encuesta❔*`,
    buttonText: '🔘Seleccione',
    sections:[{title: '🤖Sky❗', rows: [{title: "titulo1",  rowId:"id1"},{title: "titulo2",  rowId:"id2"}]}]
    })

**Comment by aidulcandra** [comment]
@calix666 I am trying to send a listReply, not listMessage
