### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sendchampltd** [adiwajshing/Baileys#2506]
Below is the event data for listening to a connection instance. The participant is undefined which makes it difficult to identify the owner of the message in a multiple connection environment.

message:  {
  key: {
    remoteJid: '2348034210294@s.whatsapp.net',
    fromMe: false,
    id: '3A950836239ACDDD33D2',
    participant: undefined
  },
  messageTimestamp: 1674138943,
  pushName: 'Dammy',
  message: Message {
    conversation: 'Webhook notification',
    messageContextInfo: MessageContextInfo {
      deviceListMetadata: [DeviceListMetadata],
      deviceListMetadataVersion: 2
    }
  }
}

Thanks

**Comment by olotudammy** [comment]
Hello, any update on this please?
