### ISSUE TITLE
[BUG] downloadMediaMessage not handling 'documentWithCaptionMessage'

### ISSUE THREAD

**Issue by arthur-es** [adiwajshing/Baileys#2507]
**Describe the bug**
Say someone sent a PDF with a caption (possible in WhatsApp web)...

This 'downloadMediaMessage' function is giving off this error: 
![image](https://user-images.githubusercontent.com/37699234/213690322-73eb84cf-e826-4de3-b8e8-77d0f1838f55.png)
![image](https://user-images.githubusercontent.com/37699234/213690307-8728c86b-d8c0-4ef6-afc6-3de24e324a39.png)

**To Reproduce**
1. Send a pdf with a caption in WhatsApp Web
2. Expect the error in the terminal

**Expected behavior**
To be able to get the file buffer by sending the 'msg' object to the downloadMediaMessage

**Environment (please complete the following information):**
 - Local machine
 - What do your `connectOptions` look like? 
![image](https://user-images.githubusercontent.com/37699234/213690648-2f1b1b18-bf25-48d8-b2d8-04844d4851ae.png)
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Comment by arugaz** [comment]
It works flawlessly, you just need to parse the message

![Screenshot_2023-01-20-22-47-12_1440x900](https://user-images.githubusercontent.com/53950128/213743393-fe9650b7-e88f-4a8a-9f1a-6c60dd592d48.png)

**Comment by AliAryanTech** [comment]
**I guess, do this 🤔**
```js 
const buffer = await downloadMediaMessage(sock.message.documentWithCaptionMessage.message)
```

**Comment by realmarcos** [comment]
I had the same error and updated to version 5.0.0 it solved.

`npm i @adiwajshing/baileys@5.0.0`
