### ISSUE TITLE
[BUG] something weird in quoted message

### ISSUE THREAD

**Issue by FIlham** [adiwajshing/Baileys#2509]
So Here I Want To Make A WhatsApp Bot, But I Found Something Something Weird In Quoted Messages
![Screenshot_20230115_202822](https://user-images.githubusercontent.com/109337705/213867213-37530a7a-6829-4850-8d20-5180a9ec9cb0.jpg)

So My WhatsApp Bot Doesn't Reply/quote Messages That Should Be Quoted (bots should have quoted my message containing "#fb ....")

**Comment by AliAryanTech** [comment]
Comedy?
It's clearly mentioned. 
```js
await sock.sendMessage('1234@s.whatsapp.net', { quoted: msg })
```

Have not you read docs? - [Here](https://github.com/adiwajshing/Baileys#Notes)

**Comment by FIlham** [comment]
> Comedy? It's clearly mentioned.
> 
> ```js
> await sock.sendMessage('1234@s.whatsapp.net', { quoted: msg })
> ```
> 
> Have not you read docs? - [Here](https://github.com/adiwajshing/Baileys#Notes)

Granted He Quoted My Message, But What I Wanted

What I Do:
- Send a #hello Message and Continue With a #ping

What Bots Do:
- Reply/quote the #hello Command With "Hello, World" text and Continue By Replying/quoting the #ping Command With "Pong!"

But What Happened
- The bot only quotes 1 command (the #ping command) and sends "Hello, World" and "Pong!" In 1 Quote Message

**Comment by Piyoxz** [comment]
> ```js
> ```js
> 
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

change quoted to 

case 'fb':
const messagefb = msg
//this code api facebook 
conn.sendMessage(from, {video: {url: ""}}, {quoted: messagefb}  
break;

**Comment by FIlham** [comment]
> change quoted to
> 
> ```
> case "fb":
> const messagefb = msg
> //this code api facebook 
> await conn.sendMessage(from, {video: {url: ""}}, {quoted: messagefb}  
> break;
> ```

Alright, Thanks
