### ISSUE TITLE
[BUG] Since 3.3.0 release connectOpions.waitForChats is not working

### ISSUE THREAD

**Issue by BrianStefanovich** [adiwajshing/Baileys#251]
**Describe the bug**
`connectOptions.waitForChats = false` isn't working. Still waiting for chats to be loaded to start the connection.

**To Reproduce**
1. Created a new connection
2. Set connectOptions.waitForChats = false
3. Run the app, and still waiting for chats to be loaded until connection is opened.

**Expected behavior**
As previous releases, app must open the connection without waiting for chats to be loaded.

**Environment (please complete the following information):**
 - This is on a server with Node 12
- This is my connectOptions: 
```
connectOptions = {
  waitForChats: false
}
```
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**
I'm running this app on Google Cloud Functions

**Comment by dinnos** [comment]
@BrianStefanovich since v3.3.0 that options is deprecated

**Comment by BrianStefanovich** [comment]
Thanks for the quick response. This library is amazing, I'm really thankful for what you've done. My node skills aren't so sharp but I hope that i can help with something easy to fix someday. Thank you again :D
