### ISSUE TITLE
[BUG] in the message viewone section 

### ISSUE THREAD

**Issue by FERDIZ-afk** [adiwajshing/Baileys#2511]
When I send a picture or video with view once turned on. That in my console log doesn't output any data .

**Comment by AliAryanTech** [comment]
**Well**
```js
const buffer = await downloadMediaMessage(sock.message.viewOnceMessageV2.message)
```
thank me later, also close this issue then.

**Comment by FERDIZ-afk** [comment]
> **Well**
> 
> ```js
> const buffer = await downloadMediaMessage(sock.message.viewOnceMessageV2.message)
> ```
> 
> thank me later, also close this issue then.

why does it have to be closed in my console.log there is nothing when I send a picture or video that uses view once

**Comment by AliAryanTech** [comment]
> > **Well**
> > ```js
> > const buffer = await downloadMediaMessage(sock.message.viewOnceMessageV2.message)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > thank me later, also close this issue then.
> 
> why does it have to be closed in my console.log there is nothing when I send a picture or video that uses view once

Show your code
