### ISSUE TITLE
Publish package to npm instead of direct github

### ISSUE THREAD

**Issue by ekoeryanto** [adiwajshing/Baileys#2516]
I am experimenting bun.js but blocked by this type of package
https://github.com/adiwajshing/Baileys/blob/41851d9e34e43029134a89ceabce528422d1faff/package.json#L39
https://github.com/adiwajshing/Baileys/blob/41851d9e34e43029134a89ceabce528422d1faff/package.json#L76

**Comment by Verzach3** [comment]
Yo should make your own fork an edit those entries

**Comment by ekoeryanto** [comment]
@Verzach3 I did but i want this package better

**Comment by Verzach3** [comment]
Better?

**Comment by Verzach3** [comment]
If you want the latest version i have a package in npm `@verzach3/baileys-edge` is in sync with the latest commit
