### ISSUE TITLE
[BUG] How to stop default log messages thrown by whatsapp in terminal

### ISSUE THREAD

**Issue by raweee** [adiwajshing/Baileys#2518]
Hi,
I try many things, but didnt find any option to prevent logging of these type of message shown below. 

{"level":30,"time":"2023-01-25T20:03:31.731Z","pid":5225,"hostname":"Rawee-PC","class":"baileys","msg":"resyncing regular from v0"}
{"level":30,"time":"2023-01-25T20:03:32.078Z","pid":5225,"hostname":"Rawee-PC","class":"baileys","msg":"synced regular to v1"}
{"level":30,"time":"2023-01-25T20:03:32.272Z","pid":5225,"hostname":"Rawee-PC","class":"baileys","msg":"resyncing regular from v1"}
{"level":30,"time":"2023-01-25T20:03:32.746Z","pid":5225,"hostname":"Rawee-PC","class":"baileys","msg":"synced regular to v2"}

**Comment by salykingleb** [comment]
logger = pino({
level: 'fatal'
});

**Comment by salykingleb** [comment]
You should change the level trace to fatal
