### ISSUE TITLE
[BUG] regenerateQRIntervalMs No longer working &(how to set max  regenerating QR count) ?

### ISSUE THREAD

**Issue by MaznAbdullah** [adiwajshing/Baileys#252]
Hello,
    conn.connectOptions.alwaysUseTakeover = true
    conn.connectOptions.regenerateQRIntervalMs = null // no QR regen
    conn.connectOptions.maxRetries = 1  // attempt to reconnect at most 10 times in a row

the connection still regenerating QR every 20 sec,
or are there any way to set max  regenerating QR count ?
any help please.

**Comment by adiwajshing** [comment]
Why exactly do you want to stop QR generation?

**Comment by MaznAbdullah** [comment]
@adiwajshing 
hi dear friend. I've been using "regenerateQRIntervalMs" but In general it has no effect anymore and still regenerating QR every 20 sec, even if I set
conn.connectOptions.regenerateQRIntervalMs=30000

**Comment by adiwajshing** [comment]
I understand, but what is your use case?

**Comment by NicolasCaous** [comment]
@adiwajshing I have a similar problem. The use case in question is that I want to have more time to scan the QR code. Do you know what is the maximum limit imposed by the WhatsApp web server?

**Comment by adiwajshing** [comment]
@NicolasCaous You can't have more time to scan it, WA expires the QR after 20s

**Comment by hamzasgd1** [comment]
> Why exactly do you want to stop QR generation?

how to stop qr generation?

**Comment by fiantinangon** [comment]
@adiwajshing Reffer to this part of doc, we can disable the QR regeneration 
```conn.regenerateQRIntervalMs = null // no QR regen```

But it seems not working now, if that's option is no longer available maybe the documentation need to update

<img width="870" alt="Screen Shot 2020-12-18 at 6 49 40 PM" src="https://user-images.githubusercontent.com/9161278/102611599-cce31780-4161-11eb-8130-556c2d17e814.png">
