### ISSUE TITLE
Detect Receiver Already Read, Delivered, Sent or Pending

### ISSUE THREAD

**Issue by kevinhimawan** [adiwajshing/Baileys#2522]
Hi there!

Is there any possibility that we can detect or have a callback whether message that we already broadcast is read, delivered, sent or pending?? So we can notice which message is still sent or pending due receiver inactive phone number

**Comment by giuseppecastaldo** [comment]
> Hi there!
> 
> Is there any possibility that we can detect or have a callback whether message that we already broadcast is read, delivered, sent or pending?? So we can notice which message is still sent or pending due receiver inactive phone number

check 'messages.update' event
