### ISSUE TITLE
[BUG] Cannot install or update library via npm

### ISSUE THREAD

**Issue by dhirennjaypal** [adiwajshing/Baileys#2524]
**Describe the bug**
i am trying to update library from 4.4.0 to 5.0.0 from npm but cannot do it, i tried to delete node_module and reinstall library but still showing same error.

**To Reproduce**
Run command in Command Window
`npm i @adiwajshing/baileys`

Gettings Error
`npm ERR! code ERESOLVE`
`npm ERR! ERESOLVE could not resolve`
`npm ERR!`
`npm ERR! While resolving: @adiwajshing/baileys@5.0.0`
`npm ERR! Found: link-preview-js@2.1.19`
`npm ERR! node_modules/link-preview-js`
`npm ERR!   link-preview-js@"^2.1.19" from the root project`
`npm ERR!`
`npm ERR! Could not resolve dependency:`
`npm ERR! peerOptional link-preview-js@"^3.0.0" from @adiwajshing/baileys@5.0.0`
`npm ERR! node_modules/@adiwajshing/baileys`
`npm ERR!   @adiwajshing/baileys@"*" from the root project`
`npm ERR!`
`npm ERR! Conflicting peer dependency: link-preview-js@3.0.4`
`npm ERR! node_modules/link-preview-js`
`npm ERR!   peerOptional link-preview-js@"^3.0.0" from @adiwajshing/baileys@5.0.0`
`npm ERR!   node_modules/@adiwajshing/baileys`
`npm ERR!     @adiwajshing/baileys@"*" from the root project`
`npm ERR!`
`npm ERR! Fix the upstream dependency conflict, or retry`
`npm ERR! this command with --force, or --legacy-peer-deps`
`npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Expected behavior**
it should install library as in other libraries.

**Environment**
OS: Windows 10 Pro 21H2
NodeJS Version: v18.6.0

**Comment by pst4r8** [comment]
npm i @adiwajshing/baileys --force

**Comment by dhirennjaypal** [comment]
> npm i @adiwajshing/baileys --force

but, what are the side effects of doing this ?

**Comment by hansputera** [comment]
> > npm i @adiwajshing/baileys --force
> 
> but, what are the side effects of doing this ?

See https://stackoverflow.com/questions/52001771/npm-install-force-flag

**Comment by marru452** [comment]
npm i @adiwajshing/baileys@5.0.0
