### ISSUE TITLE
TypeError: WAConnection is not a constructor

### ISSUE THREAD

**Issue by khairul-amin** [adiwajshing/Baileys#2526]
helo, can anyone help me to solve a problem like this?

![wabot](https://user-images.githubusercontent.com/22488571/215392797-95680b21-6e2b-4e99-a852-4578456a6a43.png)

**Comment by gqlxj1987** [comment]
use npm i @adiwajshing/baileys@5.0.0

**Comment by khairul-amin** [comment]
> use npm i @adiwajshing/baileys@5.0.0

I've updated the Baileys, but it's causing a new problem, can anyone help to fix it?
![image](https://user-images.githubusercontent.com/22488571/215634943-919e55a4-fff0-4ff0-b7b6-d72865a863d8.png)
