### ISSUE TITLE
[BUG] The link in the message is not active on iPhone

### ISSUE THREAD

**Issue by Arphimed** [adiwajshing/Baileys#2527]
After the last update of the WhatsApp, the link in the message in the iPhone is not active.
What needs to be done to make the link active (you can’t add a phone number to contacts) ?

**Comment by isychev93** [comment]
Have the same problem.

**Comment by Paguiar735** [comment]
What do you guys mean by "link in the message in the iPhone"?

Are you saying that links are displayed in chat as plain text instead of clickable hyperlinks?

**Comment by Arphimed** [comment]
> 
Yes.

**Comment by Arphimed** [comment]
> What do you guys mean by "link in the message in the iPhone"?
> 
> Are you saying that links are displayed in chat as plain text instead of clickable hyperlinks?

Yes.

**Comment by Arphimed** [comment]
> What do you guys mean by "link in the message in the iPhone"?
> 
> Are you saying that links are displayed in chat as plain text instead of clickable hyperlinks?

Do you have the same problem?

**Comment by empresarrollo** [comment]
I'm seing the same thing. Links are not clickable.

**Comment by deriknyvo** [comment]
I have same problem.

Apparently the problem is with the IOS, I tested the sending by accounts without bayles and it only receives the clickable link if the contact is saved in the recipient's address book.

**Comment by textarea** [comment]
same problem

**Comment by Paguiar735** [comment]
> same problem

As the user above said, the problem is unrelated to Baileys, so it's pretty much a dead end here unless WhatsApp itself decides to change the way it operates on iOS.
