### ISSUE TITLE
[BUG] Sending login request loop after logout on device

### ISSUE THREAD

**Issue by dimailn** [adiwajshing/Baileys#253]
Baileys enters loop "sending login request" after logout on device in version 3.3.1 and master. 

**To Reproduce**
1. Created a new connection with infinity retries and scan qr code
2. Logout on device

**Expected behavior**
In version 3.2.1 event 'close' emitted with reason 'invalid_session'. 

**Environment:**
 - Is this on a server? yes
 - What do your `connectOptions` look like?     maxRetries = Infinity, connectCooldownMs = 3000
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? yes

**Comment by adiwajshing** [comment]
Thanks for reporting this, will fix ASAP

**Comment by adiwajshing** [comment]
Fixed [here](https://github.com/adiwajshing/Baileys/commit/4a6c72c36c228552bbf30f697923f61c743d1246)

**Comment by dimailn** [comment]
Thank you
