### ISSUE TITLE
Buttons on iOS

### ISSUE THREAD

**Issue by yuvalwarsh** [adiwajshing/Baileys#2531]
Hi

I’m working with the 4.4.0 version, and I noticed buttons/list messages are not sent to an iOS device if its app is closed.

What can I do to solve it?

**Comment by yuvalwarsh** [comment]
Up

**Comment by Paguiar735** [comment]
What do you mean by "if its app is closed"?

**Comment by Paguiar735** [comment]
@yuvalwarsh I suggest closing this issue and staying tuned to #2442
