### ISSUE TITLE
How to send ephemeral message according to the chat's disappearing message setting?

### ISSUE THREAD

**Issue by aidulcandra** [adiwajshing/Baileys#2534]
In Readme, it is mentioned that by default a message's ephemeralExpiration is set to 'chat' to follow the chat's ephemeral expiration setting. But it doesn't seem to work.

The workaround for groups is to query the metadata and get the ephemeralexpiration setting but how about private chats?

**Comment by BlackAmda** [comment]
You can use **extendedTextMessage.contextInfo.expiration**

Example:
```JS
sock.ev.process(async (events) => {
    if(events['messages.upsert']) {
        const upsert = events['messages.upsert']
        const ephemeralexpiration = upsert.message.extendedTextMessage.contextInfo.expiration
    }
})
```
