### ISSUE TITLE
[BUG] - enabling temporary messages by yourself - solved

### ISSUE THREAD

**Issue by luix-guxto** [adiwajshing/Baileys#2538]
In a WPP Bot function, he needs to forward some messages to a specific number, however, every time he goes to forward, he turns on the temporary messages mode

![Trecho do Codigo](https://user-images.githubusercontent.com/77067320/216978199-d8dd9620-ae93-4861-9348-3ca44304d6a7.png)

![Ativação](https://user-images.githubusercontent.com/77067320/216978534-dc7d85ea-29f8-440f-8456-d3f83a06aab4.png)

**Comment by realmarcos** [comment]
This is whatsapp setting itself. To prevent it from being activated automatically you need to access the settings (settings->privacy) of temporary messages and deactivate.

**Comment by luix-guxto** [comment]
No, I found out what it was, for this not to happen, when forwarding a message, you need to check its type, if it is protocolMessage, you block the forwarding, as it will forward the protocolMessage, thus connecting the temporary messages.
