### ISSUE TITLE
[BUG] Template messages are getting send to self by Bot

### ISSUE THREAD

**Issue by ANUR46** [adiwajshing/Baileys#2539]
**Describe the bug**
I have tried to send a template message but the bot is sending the template message to itself in place of sending to the other person.
Template, Lists and Buttons messages are not getting send on the group and to the single user.
Button and Lists messages are showing sent from the device but not showing into receiver device.

Here is my code
```
import makeWAconnet, { DisconnectReason, BufferJSON, useMultiFileAuthState } from '@adiwajshing/baileys'
import { Boom } from '@hapi/boom'
import pino from 'pino'

import * as fs from 'fs'

const session_dir = "./session_auth"

const { state, saveCreds } = await useMultiFileAuthState(session_dir)

async function connectToWhatsApp() {
  const conn = makeWAconnet.default({

    logger: pino({ level: 'silent' }),
    // browser: ['AnuBot', 'Safari', '1.0.0'],
    printQRInTerminal: true,
    syncFullHistory: true,
    auth: state
  })
  conn.ev.on('connection.update', async (update) => {
    const { connection, lastDisconnect } = update
    if (connection === 'close') {

      const shouldReconnect = new Boom(lastDisconnect).error?.output?.statusCode !== DisconnectReason.loggedOut

      if (shouldReconnect) {
        connectToWhatsApp();
      }
      else {
        connectToWhatsApp();
      }
    }
    else if (connection === 'open') {
      console.log('opened connection')
    }
  })

  const getGroupAdmins = (member) => {
    const admins = []
    for (let i of member) {
      if (i.admin === "admin" || i.admin === "superadmin")
        admins.push(i.id)
    }
    return admins
  }
  conn.ev.on('messages.upsert', async chatMsg => {

    var m = chatMsg.messages[0]
    if (!m.message) return;
    if (m.key && m.key.remoteJid == 'status@broadcast') return;
    m.message = (Object.keys(m.message)[0] === 'ephemeralMessage') ? m.message.ephemeralMessage.message : m.message
    // let type = Object.keys(m.message)
    const from = m.key.remoteJid
    let type = Object.keys(m.message)
    // console.log("Type :>  ", type)

    const isGroup = from.endsWith('@g.us')
    const content = JSON.stringify(m.message)
    type = (!['senderKeyDistributionMessage', 'messageContextInfo'].includes(type[0]) && type[0]) || (type.length >= 3 && type[1] !== 'messageContextInfo' && type[1]) || type[type.length - 1]
    const body = (type === 'conversation') ? m.message.conversation : (type == 'imageMessage') ? m.message.imageMessage.caption : (type == 'videoMessage') ? m.message.videoMessage.caption : (type == 'extendedTextMessage') ? m.message.extendedTextMessage.text : (type == 'buttonsResponseMessage') ? m.message.buttonsResponseMessage.selectedButtonId : (type == 'listResponseMessage') ? m.message.listResponseMessage.singleSelectReply.selectedRowId : (type == 'templateButtonReplyMessage') ? m.message.templateButtonReplyMessage.selectedId : (type === 'messageContextInfo') ? (m.message.buttonsResponseMessage?.selectedButtonId || m.message.listResponseMessage?.title || m.text) : ''
    const budo = (type === 'conversation' && m.message.conversation.startsWith('.')) ? m.message.conversation : (type == 'imageMessage') ? m.message.imageMessage.caption : (type == 'videoMessage') ? m.message.videoMessage.caption : (type == 'extendedTextMessage') ? m.message.extendedTextMessage.text : (type == 'buttonsResponseMessage') ? m.message.buttonsResponseMessage.selectedButtonId : (type == 'listResponseMessage') ? m.message.listResponseMessage.singleSelectReply.selectedRowId : (type == 'templateButtonReplyMessage') ? m.message.templateButtonReplyMessage.selectedId : (type === 'messageContextInfo') ? (m.message.buttonsResponseMessage?.selectedButtonId || m.message.listResponseMessage?.title || m.text) : ''
    const command = budo.slice(1).trim().split(/ +/).shift().toLowerCase()
    const args = body.trim().split(/ +/).slice(1)
    const q = args.join(' ')
    const groupMetadata = isGroup ? await conn.groupMetadata(from) : ''
    const groupMembers = isGroup ? await groupMetadata.participants : ''
    const groupName = isGroup ? groupMetadata.subject : ''
    const bot_Number = conn.user.id ? conn.user.id.split(":")[0] : conn.user.id
    const groupAdmins = isGroup ? await getGroupAdmins(groupMembers) : ''
    const participants = isGroup ? await groupMetadata.participants : ''
    const sender = isGroup ? m.key.participant : m.key.remoteJid
    const isGroupAdmins = isGroup ? groupAdmins.includes(sender) : false
    const isQuotedImage = type === 'extendedTextMessage' && content.includes('imageMessage')
    const isQuotedVideo = type === 'extendedTextMessage' && content.includes('videoMessage')

    const rec_num = (from.split("@"))[0]
    console.log("Bot Num : ", bot_Number)
    console.log("Rec Num : ", (from.split("@"))[0])

    const botNumber = conn.user.id ? conn.user.id.split(":")[0] + "@s.whatsapp.net" : conn.user.id
    console.log("Bot Number :>  ", botNumber)
    console.log("Sender Number : ", from)
    var id = 'abcd@s.whatsapp.net' // the WhatsApp ID 
    id = from

    if (botNumber != from && body != undefined) {

      if (body == 'Hi') {

        // send a buttons message!
        const buttons = [
          { buttonId: 'id1', buttonText: { displayText: 'Button 1' }, type: 1 },
          { buttonId: 'id2', buttonText: { displayText: 'Button 2' }, type: 1 },
          { buttonId: 'id3', buttonText: { displayText: 'Button 3' }, type: 1 }
        ]

        const buttonMessage = {
          text: "Hi it's button message",
          footer: 'Hello World',
          buttons: buttons,
          headerType: 1
        }

        const sendMsg1 = await conn.sendMessage(id, buttonMessage)

        //send a template message!
        const templateButtons = [
          { index: 1, urlButton: { displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys' } },
          { index: 2, callButton: { displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901' } },
          { index: 3, quickReplyButton: { displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message' } },
        ]

        const templateMessage = {
          text: "Hi it's a template message",
          footer: 'Hello World',
          templateButtons: templateButtons
        }

        const sendMsg2 = await conn.sendMessage(id, templateMessage)

        conn.sendMessage(m.key.remoteJid, templateMessage)
      }
    }
  })

  conn.ev.on('creds.update', saveCreds)
}
// run in main file
connectToWhatsApp()
```

**To Reproduce**
Please review the code and suggest to me where I am doing any mistake in sending message.
I am only able to send simple message after login but Template, Button and List messages are not sending properly.

**Comment by nifist99** [comment]
same issue need hlp

**Comment by DeveloperNewton** [comment]
Temporary solution for the same.

There is a bug (or WhatsApp itself error) that does not allow sending to some devices without setting the "ephemeralExpiration" option, try:

```
const templateButtons = [
{ index: 1, urlButton: { displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys' } },
{ index: 2, callButton: { displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901' } },
{ index: 3, quickReplyButton: { displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message' } },
]

const templateMessage = {
text: "Hi it's a template message",
footer: 'Hello World',
templateButtons: templateButtons
}

const sendMsg2 = await conn.sendMessage(id, templateMessage, {
ephemeral Expiration: 604800
})
```


Note: in "ephemeralExpiration" it is defined as 604800 (7 days), the button template appears normally, however, it will not expire, regardless of the value that is set (possible bug in baileys or in whatsapp itself).

In short: it is necessary to define something in "ephemeralExpiration".


Link: https://github.com/adiwajshing/Baileys/issues/2421#issuecomment-1374386899

**Comment by rawars** [comment]
> Temporary solution for the same.
> 
> There is a bug (or WhatsApp itself error) that does not allow sending to some devices without setting the "ephemeralExpiration" option, try:
> 
> ```
> const templateButtons = [
>     { index: 1, urlButton: { displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys' } },
>     { index: 2, callButton: { displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901' } },
>     { index: 3, quickReplyButton: { displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message' } },
> ]
> 
> const templateMessage = {
>     text: "Hi it's a template message",
>     footer: 'Hello World',
>     templateButtons: templateButtons
> }
> 
> const sendMsg2 = await conn.sendMessage(id, templateMessage, {
>     ephemeralExpiration: 604800
> })
> ```
> 
> Note: in "ephemeralExpiration" it is defined as 604800 (7 days), the button template appears normally, however, it will not expire, regardless of the value that is set (possible bug in baileys or in whatsapp itself).
> 
> In short: it is necessary to define something in "ephemeralExpiration".
> 
> Link: [#2421 (comment)](https://github.com/adiwajshing/Baileys/issues/2421#issuecomment-1374386899)

With this, it works but for old IOS devices the OS version is 11

**Comment by ANUR46** [comment]
> Temporary solution for the same.
> 
> There is a bug (or WhatsApp itself error) that does not allow sending to some devices without setting the "ephemeralExpiration" option, try:
> 
> ```
> const templateButtons = [
>     { index: 1, urlButton: { displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys' } },
>     { index: 2, callButton: { displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901' } },
>     { index: 3, quickReplyButton: { displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message' } },
> ]
> 
> const templateMessage = {
>     text: "Hi it's a template message",
>     footer: 'Hello World',
>     templateButtons: templateButtons
> }
> 
> const sendMsg2 = await conn.sendMessage(id, templateMessage, {
>     ephemeralExpiration: 604800
> })
> ```
> 
> Note: in "ephemeralExpiration" it is defined as 604800 (7 days), the button template appears normally, however, it will not expire, regardless of the value that is set (possible bug in baileys or in whatsapp itself).
> 
> In short: it is necessary to define something in "ephemeralExpiration".
> 
> Link: [#2421 (comment)](https://github.com/adiwajshing/Baileys/issues/2421#issuecomment-1374386899)

It working for me.
But I have find one more solution for this.
We can add viewOnce into the template message as follows.

```
const templateMessage = {
    text: "Hi it's a template message",
    footer: 'Hello World',
    templateButtons: templateButtons,
   viewOnce: true
}
```

**Comment by AxeemHaider** [comment]
Whatever you add **viewOnce** or **ephemeralExpiration** it work but if you logout device and re scan QR code you will see template, list and button messages **key** changed, It change `key.fromMe` to **false** always even you have send it. Problem only occur when you re scan QR code otherwise it show `key.fromMe = true` when you send.
