### ISSUE TITLE
[MD] Link preview is not working

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2541]
I'm sending this message with a link:

```js
client.sendMessage(from, {
        text: 'https://www.youtube.com/watch?v=V1bFr2SWP1I',
        caption: 'Kamakawiwo ole',
        detectLinks: true
});
```

It sends as a link, but it doesn't generate the preview.

![image](https://user-images.githubusercontent.com/10979090/217576922-07280ce4-7230-4477-bd76-651de3ee1d99.png)

**Comment by realmarcos** [comment]
To enable this function's usage, add link-preview-js as a dependency to your project with `yarn add link-preview-js`. 

The last time I used the link preview it worked on the web version but not on the device. I don't know how it is now

**Comment by AlanMartines** [comment]
> To enable this function's usage, add link-preview-js as a dependency to your project with `yarn add link-preview-js`.
> 
> The last time I used the link preview it worked on the web version but not on the device. I don't know how it is now

I already added the dependency but it had no effect, is there anything else I need to do in the code?

**Comment by realmarcos** [comment]
try looking for something on discord [aqui](https://discord.com/invite/WeJM5FP9GG)

**Comment by DeveloperNewton** [comment]
If you added baileys through npm (instead of yarn), use `npm i link-preview-js`

**Comment by moskoweb** [comment]
Set the ```linkPreview``` property to ```undefined``` and install the ```link-preview-js``` package that works.

Example:
```js
client.sendMessage(from, {
        text: 'https://www.youtube.com/watch?v=V1bFr2SWP1I',
        caption: 'Kamakawiwo ole',
        linkPreview: undefined,
});
```

**Comment by AlanMartines** [comment]
Did not work.

![image](https://user-images.githubusercontent.com/10979090/218554258-22a6c43a-1e6f-42d2-9150-c90e39b3d5f3.png)

Is there any other step to be performed?

**Comment by jeffersonveloso** [comment]
> Set the `linkPreview` property to `undefined` and install the `link-preview-js` package that works.
> 
> Example:
> 
> ```js
> client.sendMessage(from, {
>         text: 'https://www.youtube.com/watch?v=V1bFr2SWP1I',
>         caption: 'Kamakawiwo ole',
>         linkPreview: undefined,
> });
> ```


linkPreview: undefined,
This solution not work for me.
