### ISSUE TITLE
[BUG] Button message visible only on WhatsApp Web

### ISSUE THREAD

**Issue by luix-guxto** [adiwajshing/Baileys#2544]
The template and button messages are only visible on the recipient's whatsapp web, on the cell phone it is not visible.

![Celular](https://user-images.githubusercontent.com/77067320/217844457-356dd543-5d6d-4780-854f-f9cfb3d7c4fb.jpg)
![Web](https://user-images.githubusercontent.com/77067320/217844569-28006f15-11cd-4866-965f-abb93ee9ae55.jpg)

**Comment by ANUR46** [comment]
Same issue with Lists messages too and in my case buttons messages are not visible to the receiver/user's phone, just showing in sender's/bot device. Can you tell me what code you have used for sending template messages. Because in my case bot is sending template messages to self. [Here's my code](https://github.com/adiwajshing/Baileys/issues/2539#issue-1576102694)

**Comment by ecatugy** [comment]
Downgrade to release **v4.4.0** that will work.

**Comment by DeveloperNewton** [comment]
See this solution: https://github.com/adiwajshing/Baileys/issues/2539#issuecomment-1427424586

**Comment by robinhodemorais** [comment]
> Faça o downgrade para a versão **v4.4.0** que funcionará.

does it work that way for IOS?

**Comment by luix-guxto** [comment]
> Same issue with Lists messages too and in my case buttons messages are not visible to the receiver/user's phone, just showing in sender's/bot device. Can you tell me what code you have used for sending template messages. Because in my case bot is sending template messages to self.

For me to, bot send messages to self

**Comment by luix-guxto** [comment]
> Downgrade to release **v4.4.0** that will work.

downgrade would be a temporary solution, in this case, this base is sending list messages and buttons to itself.

**Comment by jeffersonveloso** [comment]
> Faça o downgrade para a versão **v4.4.0** que funcionará.

Você fez o downgrade pelo npm ?

**Comment by ANUR46** [comment]
> The template and button messages are only visible on the recipient's whatsapp web, on the cell phone it is not visible.
> 
> ![Celular](https://user-images.githubusercontent.com/77067320/217844457-356dd543-5d6d-4780-854f-f9cfb3d7c4fb.jpg) ![Web](https://user-images.githubusercontent.com/77067320/217844569-28006f15-11cd-4866-965f-abb93ee9ae55.jpg)


Try to add **viewOnce: true**  into your button messages. [See this Answer](https://github.com/adiwajshing/Baileys/issues/2539#issuecomment-1436329734)
