### ISSUE TITLE
Message History not requested by phone [BUG]

### ISSUE THREAD

**Issue by TentacleSama4254** [adiwajshing/Baileys#2550]
I recently updated Bailey's and I noticed that it no longer requests the connected device for old messages. I have the `syncFullHistory` setting set to `true` but listening to the `'messaging-history.set'` event does not catch any events.

## Steps to Reproduce:
1. Update Bailey's to the latest version
2. Check the value of the `syncFullHistory` setting, it should be set to `true`
3. Observe the behavior of the `'messaging-history.set'` event

## Expected Behavior:
- Bailey's should request the connected device for old messages and trigger the `'messaging-history.set'` event.

## Actual Behavior:
- Bailey's does not request the connected device for old messages and the `'messaging-history.set'` event is not caught.

**Comment by robvanderleek** [comment]
I experience the same behaviour.

(BTW the stale bot on this repository is quite assertive in closing issues that are not resolved, perhaps the threshold can be increased a bit or triage is taking too long)
