### ISSUE TITLE
[BUG] possible mutex deadlock

### ISSUE THREAD

**Issue by wesuRage** [adiwajshing/Baileys#2553]
```
{"level":40,"time":"2023-02-12T19:17:18.315Z","pid":5788,"hostname":"User","stack":"Error: mutex start\n    at C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:15:31\n    at Object.mutex (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:35:15)\n    at handleReceipt (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:361:29)\n    at execTask (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:554:20)\n    at processNodeWithBuffer (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:551:15)\n    at WebSocket.<anonymous> (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:566:9)\n    at WebSocket.emit (node:events:513:28)\n    at C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:222:35\n    at Object.decodeFrame (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (C:\\Users\\userr\\Documentos\\botzap\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}
```

this error haunts me and my friends for a long time... This thing blocks baileys from detecting messages

**Comment by Ahosall** [comment]
+1

**Comment by DeveloperNewton** [comment]
up

**Comment by DeveloperNewton** [comment]
To prevent messages like "possible mutex deadlock" from appearing during code execution, you can go to node_modules/@adiwajshing/baileys, access the "utils" directory, open the make_mutex file and comment or delete line 18 (here it appears on line 18, if it doesn't appear, look for logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'))

In short: delete/comment out the line containing logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'); in the make_mutex file inside the "Utils" directory in node_modules

**Comment by wesuRage** [comment]
> To prevent messages like "possible mutex deadlock" from appearing during code execution, you can go to node_modules/@adiwajshing/baileys, access the "utils" directory, open the make_mutex file and comment or delete line 18 (here it appears on line 18, if it doesn't appear, look for logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'))
> 
> In short: delete/comment out the line containing logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'); in the make_mutex file inside the "Utils" directory in node_modules

hello @DeveloperNewton i've already tried to do that before, it really stops the "mutex" thing, but then it starts to spam infinitely buffers on my terminal, that also blocks baileys from detecting new messages

**Comment by Ahosall** [comment]
> To prevent messages like "possible mutex deadlock" from appearing during code execution, you can go to node_modules/@adiwajshing/baileys, access the "utils" directory, open the make_mutex file and comment or delete line 18 (here it appears on line 18, if it doesn't appear, look for logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'))
> 
> In short: delete/comment out the line containing logger_1.default.warn({ stack, waitOver }, 'possible mutex deadlock'); in the make_mutex file inside the "Utils" directory in node_modules

Hello @DeveloperNewton i removed some lines from my make-mutex following this [commit](https://github.com/adiwajshing/Baileys/commit/5efb0ebbea19b7f3d783fbc1589fa0e9c1386ff5). The make-mutex warning messages disappear, however the buffers appear, but very little. What is happening now is that messages are no longer being received. With some treatments in the message sending function, I was able to get a reply back, but sometimes it doesn't get sent.

```js
await sock.sendMessage(jid, message).then(msg => console.log(msg));
```

**Comment by sultanlive** [comment]
+1
