### ISSUE TITLE
Sending location works?

### ISSUE THREAD

**Issue by alexduca** [adiwajshing/Baileys#2555]
Hello everyone! I have a curiosity regarding location sendings via the library. Since they disabled this feature on Whatsapp Web I wanted to know if it worked (I'm using another library and it doesn't work, before changing all the code I wanted to be sure). Thanks!

```
const sentMsg  = await sock.sendMessage(
    id, 
    { location: { degreesLatitude: 24.121231, degreesLongitude: 55.1121221 } }
)
```

**Comment by RavensVenix** [comment]
![image](https://user-images.githubusercontent.com/100336044/221019747-b009b3e2-478c-4c55-b1b1-2cebb4a3c0fa.png)
