### ISSUE TITLE
[BUG] groupMetadata.inviteCode is always undefined

### ISSUE THREAD

**Issue by Helvio88** [adiwajshing/Baileys#2556]
**Describe the bug**
`inviteCode` is always `undefined` in `groupMetadata.inviteCode`, where `group = sock.groupMetadata(message.key.remoteJid)`

**To Reproduce**
1. Receive a Group Message
2. Get the Group Metadata object with `sock.groupMetadata(message.key.remoteJid)`
3. print `group.inviteCode`

**Expected behavior**
`group.inviteCode` should contain the same `inviteCode` found in `sock.groupInviteCode(group.id)`

**Environment (please complete the following information):**
 - Is this on a server?
`Yes`
 - What do your `connectOptions` look like? 
```typescript
const { state, saveCreds } = await useMultiFileAuthState(`/data/${sessionId}`)
  client = <baileysClient>makeWASocket({
    auth: state,
    printQRInTerminal: true,
    logger: pino({ level: 'silent' })
  })
```
 - Do you have multiple clients on the same IP?
`No`
 - Are you using a proxy?
`No`

**Additional context**
No additional information.

**Comment by moskoweb** [comment]
It only works if you are an administrator of the group in question, otherwise it returns an error.

**Comment by Helvio88** [comment]
I am an admin

**Comment by zennn08** [comment]
you can get inviteCode using this function

```ts
const code = await sock.groupInviteCode(msg.key.remoteJid)
console.log(code)
```
