### ISSUE TITLE
presenceSubscribe not working on some numbers

### ISSUE THREAD

**Issue by theCoderrrr** [adiwajshing/Baileys#2558]
Although I subscribe to numbers with the presence subscribe code, I cannot receive presence data even if I subscribe to a number that has not been messaging before, the socket does not start, how can I start it?

**Comment by luix-guxto** [comment]
You can explain better?
I Don't understand.

**Comment by theCoderrrr** [comment]
Although I subscribe to some numbers with presence subscribe, the presence data does not appear when updated

**Comment by Verzach3** [comment]
You want to listen to others presences?

**Comment by theCoderrrr** [comment]
> You want to listen to others presences?

yes

**Comment by Verzach3** [comment]
You are using the presenceSubscribe function wrong, the function is to send presences to contacts, not to receive, to listen to others presences you need to listen for the event in the Baileys event emitter

**Comment by theCoderrrr** [comment]
> You are using the presenceSubscribe function wrong, the function is to send presences to contacts, not to receive, to listen to others presences you need to listen for the event in the Baileys event emitter

Can you share a sample code?

**Comment by Verzach3** [comment]
```JS
if(events["presence.update"], () => {
	const { id, presences } = events["presence.update"]!
	if (presences[id].lastKnownPresence === "composing"){
		console.log("User is typing...")
	}
	if (presences[id].lastKnownPresence === "available"){
		console.log("User is online...")
	}
})
```
I hope this works for you

**Comment by theCoderrrr** [comment]
> ```js
> if(events["presence.update"], () => {
> 	const { id, presences } = events["presence.update"]!
> 	if (presences[id].lastKnownPresence === "composing"){
> 		console.log("User is typing...")
> 	}
> 	if (presences[id].lastKnownPresence === "available"){
> 		console.log("User is online...")
> 	}
> })
> ```
> 
> I hope this works for you, keep in mind that there are other types of presences, let me know if you have any other problems.

Thank you, can you give me a contact address where I can reach you?

**Comment by theCoderrrr** [comment]
> ```js
> if(events["presence.update"], () => {
> 	const { id, presences } = events["presence.update"]!
> 	if (presences[id].lastKnownPresence === "composing"){
> 		console.log("User is typing...")
> 	}
> 	if (presences[id].lastKnownPresence === "available"){
> 		console.log("User is online...")
> 	}
> })
> ```
> 
> I hope this works for you, keep in mind that there are other types of presences, let me know if you have any other problems.

I tested the code there is a problem it does not detect the user is logged in

**Comment by Paguiar735** [comment]
First you have to make sure those "some numbers" are not from contacts that hire their presence, or which presence just doesn't appear to the account logged into Baileys because they don't have that WhatsApp account saved as a constant on their device.

**Comment by theCoderrrr** [comment]
> First you have to make sure those "some numbers" are not from contacts that hid their presence status, or which presence status just isn't visible to the account logged into Baileys because they don't have that WhatsApp account saved as a contact on their device.

the presence status of some numbers is not private
