### ISSUE TITLE
[BUG] Cannot install library by npm or yarn

### ISSUE THREAD

**Issue by HRRabee** [adiwajshing/Baileys#2559]
**Describe the bug**
I try to download the library through npm and yarn and it doesn't and it gives me an error.

**To Reproduce**
1. yarn add @adiwajshing/baileys
2. npm i @adiwajshing/baileys

**Expected behavior**
C:\Users\Administrator\Desktop\Folder>yarn add @adiwajshing/baileys
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

C:\Users\Administrator\Desktop\Folder>npm i @adiwajshing/baileys
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-02-13T19_59_16_734Z-debug-0.log

**Environment:**
windows server 2019
node v18.13.0
yarn v1.22.19

**Comment by hansputera** [comment]
Please install the git

**Comment by HRRabee** [comment]
> Please install the git
Thank you
It worked

**Comment by HRRabee** [comment]
> Please install the git

Thank you
It worked
