### ISSUE TITLE
[MD] Store does not work whatsapp business

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#2564]
The store is not populated with whatsapp business, only with regular whatsapp.

Any suggestions?

**Comment by luix-guxto** [comment]
I tried to use the api in whatsapp business too, but I couldn't even stay connected, I suggest using only the regular whatsapp.

**Comment by asenawritescode** [comment]
I am using this library with BotWhatsapp works like a charm https://github.com/codigoencasa/bot-whatsapp
