### ISSUE TITLE
[BUG] makeWASocket is not defined

### ISSUE THREAD

**Issue by fsteamID** [adiwajshing/Baileys#2565]
**this my code**
```
const {
    default: makeWasocket,
    MessageOptions,
    isJidgroup,
    useMultiFileAuthState,
    BufferJSON,
    delay,
    AnyMessageContent,
    makeInMemoryStore,
    msgRetryCounterMap,
    DisconnectReason,
    MimeType,
    fetchLatestBaileysVersion,
    makeCacheableSignalKeyStore,
    makeBusinessSocket
} = require("@adiwajshing/baileys");
const {Boom} = require('@hapi/boom');
const fs = require('fs');
const path =require('path');


async function sambungkanBot() {
    const { state, saveCreds } = await useMultiFileAuthState('daus_bot')
    let { version, isLatest } = await fetchLatestBaileysVersion();
    const sock = makeWASocket({
        printQRInTerminal: true,
        browser: ['fsteamID Bot Whatsapp Project','Kiwi','1.0.0'],
        auth: state,
    });
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error = Boom)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            // reconnect if not logged out
            if(shouldReconnect) {
                sambungkanBot()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    });
   conn.ev.on ('creds.update', saveCreds);
}
// run in main file
sambungkanBot()
```

**console log**
const sock = makeWASocket({
                 ^

ReferenceError: makeWASocket is not defined
    at sambungkanBot (/home/firdaus/Documents/Script/Project BoT WHATSAPPKU/coba.js:29:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by henriquesouza141** [comment]
const {
  default: makeWASocket,
  MessageOptions,
  isJidgroup,
  useMultiFileAuthState,
  BufferJSON,
  delay,
  AnyMessageContent,
  makeInMemoryStore,
  msgRetryCounterMap,
  DisconnectReason,
  MimeType,
  fetchLatestBaileysVersion,
  makeCacheableSignalKeyStore,
  makeBusinessSocket
} = require("@adiwajshing/baileys");

const {Boom} = require('@hapi/boom');
const fs = require('fs');
const path =require('path');


async function sambungkanBot() {
  const { state, saveCreds } = await useMultiFileAuthState('daus_bot')
  //let { version, isLatest } = await fetchLatestBaileysVersion();
  const sock = makeWASocket({
      printQRInTerminal: true,
      browser: ['fsteamID Bot Whatsapp Project','Kiwi','1.0.0'],
      auth: state,
  });
  sock.ev.on('connection.update', (update) => {
      const { connection, lastDisconnect } = update
      if(connection === 'close') {
          const shouldReconnect = (lastDisconnect.error = Boom)?.output?.statusCode !== DisconnectReason.loggedOut
          console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
          // reconnect if not logged out
          if(shouldReconnect) {
              sambungkanBot()
          }
      } else if(connection === 'open') {
          console.log('opened connection')
      }
  });
 sock.ev.on ('creds.update', saveCreds);
}
// run in main file
sambungkanBot()

**Comment by fsteamID** [comment]
thx this working
