### ISSUE TITLE
How to Tag all user?

### ISSUE THREAD

**Issue by widhisec** [adiwajshing/Baileys#257]
hello, I want to ask about whatsapp, how to get lots of tags for all users, what kind of example? 
Thanks

**Comment by Quiec** [comment]
Example code I wrote: https://github.com/Quiec/WhatsAsena/blob/master/plugins/tagall.js

**Comment by widhisec** [comment]
> Example code I wrote: https://github.com/Quiec/WhatsAsena/blob/master/plugins/tagall.js

file folders have been separated a lot, bro

**Comment by Quiec** [comment]
what?

**Comment by widhisec** [comment]
> what?
yes if there is no plugins file it will not work thanks

**Comment by arisawali2014** [comment]
thats literally how to tag all people using this lib

**Comment by widhisec** [comment]
> thats literally how to tag all people using this lib

Okay thanks ma brooo

**Comment by Quiec** [comment]
> > what?
> > yes if there is no plugins file it will not work thanks

you should port as your code
