### ISSUE TITLE
Presence Update - Ban Problem [BUG]

### ISSUE THREAD

**Issue by MuratKaragozgil** [adiwajshing/Baileys#2573]
**Description**
Hello, i try to get presence update of many numbers. Because of this, I send a message to the numbers one time then Baileys will provide presence updates for this number. But if I send 2 or 3 messages to numbers, WhatsApp bans my number.

**To Reproduce**
1. Connect to baileys
2. Send message to 2 or 3 numbers
3. Get presence updates
4. Got ban :(

**Expected behavior**
How can i get presence updates of many numbers ? I can add them as contact on the phone, no problem. But i need to get presence updates constantly.

**Environment (please complete the following information):**
 - Is this on a server? - Yes
 - What do your `connectOptions` look like? - Same as Example code on baileys repository
 - Do you have multiple clients on the same IP? - Same ip
 - Are you using a proxy? - No

**Comment by Paguiar735** [comment]
This is definitely not a bug with Baileys as the tag suggests, since WhatsApp's averse to any type of automation that it considers to be "Harm[ful] to WhatsApp or [their] Users" on its platform, unless it's coming from an official WhatsApp Businesses API partner.

You have to at least wait a few seconds before checking the presence of another user, instead of checking all of them at once, which I believe is what you're doing.

In either case, it'll be best to explain what you're trying to accomplish instead of asking for help getting your implementation to work, since there might be a better way to do so without making that requests to the WhatsApp servers.

**Comment by ANUR46** [comment]
> **Description** Hello, i try to get presence update of many numbers. Because of this, I send a message to the numbers one time then Baileys will provide presence updates for this number. But if I send 2 or 3 messages to numbers, WhatsApp bans my number.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Connect to baileys
> 2. Send message to 2 or 3 numbers
> 3. Get presence updates
> 4. Got ban :(
> 
> **Expected behavior** How can i get presence updates of many numbers ? I can add them as contact on the phone, no problem. But i need to get presence updates constantly.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server? - Yes
> * What do your `connectOptions` look like? - Same as Example code on baileys repository
> * Do you have multiple clients on the same IP? - Same ip
> * Are you using a proxy? - No


Please review this [responce](https://github.com/adiwajshing/Baileys/issues/2572#issuecomment-1436346783)

**Comment by MuratKaragozgil** [comment]
Thank you for your response guys, actually, my purpose is to track users' online/offline statuses. The user count can be 10. Do you know any solution without banned?

**Comment by MuratKaragozgil** [comment]
Thank you for your responses, actually main problem is wanting to get presence updates from 10 phone numbers. It shouldn't be real-time but I don't want to be banned from Whatsapp. 

My steps are below. Do you know a solution for this use case?

**Comment by Fonnte** [comment]
sorry for OOT, but why do many people need to see the recipients presence? is there any benefit or anything with it?

**Comment by MuratKaragozgil** [comment]
Actually, I'm trying to create a chatbot and the bot should know user presences to understand when to write

**Comment by dinlazyazilim** [comment]
Ya

> Actually, I'm trying to create a chatbot and the bot should know user presences to understand when to write

yapacağın işlem basit kardeşim tabi anladığım kadarı ile , whatsapp kullanıcı mesajlarını kendi veritbanına kaydettirip sonra , kendi veritbanında sorgu yaptırmandır. En azından yazından anladığım konunun çözümü budur.
Esenlikler dilerim.

**Comment by MuratKaragozgil** [comment]
Yorum için teşekkürler ama çözüm bu değil maalesef. Esenlikler.

**Comment by jeffersonveloso** [comment]
We will try to keep the issue in English only so that everyone understands what is being discussed.
