### ISSUE TITLE
Baileys Overload 

### ISSUE THREAD

**Issue by Goldn7799** [adiwajshing/Baileys#2579]
Baileys overload if on ```Closing stale open session for new outgoing prekey bundle``` , nodejs eating > 5GB on loading chat, and stopped with code ```Exited with code: SIGKILL```

**Comment by AxeemHaider** [comment]
Same issue here

**Comment by caiogrigoleto** [comment]
In my case, this message occurs followed by this code snippet...
It usually gives this message and then stops sending messages.


![image](https://user-images.githubusercontent.com/62262505/221863157-0a30af7f-3371-4c9b-a6da-e6888e6308fa.png)
