### ISSUE TITLE
How to get name?

### ISSUE THREAD

**Issue by asmin-dev** [adiwajshing/Baileys#258]
How to get name from user?

**Comment by Al2VyN** [comment]
conn.on('message-new', async(m) =>
{
   const name_sender_or_group = conn.chats.get(m.key.remoteJid).name
   const name_sender_from_member_group = conn.chats.get(m.participant).name
});

**Comment by BerTren-Nation** [comment]
> conn.on('message-new', async(m) =>
> {
> const name_sender_or_group = conn.chats.get(m.key.remoteJid).name
> const name_sender_from_member_group = conn.chats.get(m.participant).name
> });

![Screenshot_2020-12-10-07-18-39-67_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/72166971/101768268-f07de080-3b17-11eb-9ef3-1c287a3a7566.png)

conn.chats.get(m.participant).name
I don't know why error

**Comment by asmin-dev** [comment]
if the contact is not saved on the phone, the result is undefined

**Comment by Nurutomo** [comment]
```js
let user = conn.contacts[m.key.remoteJid]
/*
{
 vname: 'Business Name',
 name: 'Contact Name',
 short: 'Contact Name in Short',
 notify: 'Pushname'
}
*/
```

**Comment by asmin-dev** [comment]
Thanks, it's work

Pada tanggal Kam, 24 Des 2020 19.23, Nurutomo <notifications@github.com>
menulis:
