### ISSUE TITLE
sendmessage not work out the events[BUG]

### ISSUE THREAD

**Issue by HoSheiMa** [adiwajshing/Baileys#2583]
sendmessage function works fine into event like message.upsert but when using it out of the event functions works but not sent the message give me a pending status but nothing send in whatsapp
iam sure that connection are ready and everything is fine before use sendmessage function but i don't know why its trouble in this points
part of the code:
CoreApp is the sock after login
```js
CoreApp.event("messages.upsert", async (m) => {
    console.log(JSON.stringify(m));
    console.log("333replying to", m.messages[0].key.remoteJid!);
    // works fine
    await CoreApp.sendMessage(m.messages[0].key.remoteJid!, {
      text: "Hello from bahaa!",
    });
  });

  console.log("coreApp opened : " + CoreApp.ready);
  // not works
  const wres = await CoreApp.sendMessage(to, {
    text: "Hello from bahaa1!",
  });
  console.log("wres", wres);
```
wres response:
```json
{"messages":[{"key":{"remoteJid":"201207425745@s.whatsapp.net","fromMe":true,"id":"BAE578A806DA775A"},"message":{"extendedTextMessage":{"text":"Hello from bahaa1!"}},"messageTimestamp":"1677562929","status":"PENDING"}],"type":"append"}
```

**Comment by arthur-es** [comment]
same problem here

**Comment by arthur-es** [comment]
@HoSheiMa did you solve your problem?

**Comment by vishwajit76** [comment]
"messages.upsert" event has stopped working for some time. when we link more than 1 device then this issue is faced. I already tried to restart the event but had no success.

Any update?

**Comment by MaznAbdullah** [comment]
same problem.
