### ISSUE TITLE
[BUG] the application stops by itself

### ISSUE THREAD

**Issue by fsteamID** [adiwajshing/Baileys#2584]
i'm having a problem,
when my application is run successfully but after a long run the application error and have to re-run the application ,,

i am using "baileys 5.0.0" useMultiFileAuthState.

but when I use baileys version 440 the application runs smoothly, useSingleFileAuthState

how to deal with applications that stop by themselves?

i use "screen" and run the bot using nodemon index.

thx

**Comment by RavensVenix** [comment]
It could be because your script takes up a lot of RAM to run it so that your script is killed by the RAM itself
To temporarily solve this problem, try using PM2 or Forever.
