### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by denz-aja** [adiwajshing/Baileys#2586]
bang cara buat bot auto mengetik gimana ya🗿🗿

**Comment by TOXIC-DEVIL** [comment]
> bang cara buat bot auto mengetik gimana ya🗿🗿

**Read: [readme](https://github.com/adiwajshing/Baileys#update-presence) before opening an issue.**
```js
// composing - typing...
// recording - recording audio...
// available - online
// unavailable - offline

// Example:
await sock.sendPresenceUpdate('composing', id) // for typing..

await sock.sendPresenceUpdate('available', id) // for online..

await sock.sendPresenceUpdate('unavailable', id) // for offline..

await sock.sendPresenceUpdate('recording', id) // for recording..
```

**Comment by yannngithub** [comment]
Kalo ada yang pake bot terus mengetik gitu? pakai aja yang "composing"

**Comment by yannngithub** [comment]
> bang cara buat bot auto mengetik gimana ya🗿🗿

Kalo ada yang pake bot terus mengetik gitu? pakai aja yang "composing"

**Comment by denz-aja** [comment]
Ok dah bisa Tq

**Comment by RavensVenix** [comment]
//Auto-Typing
await sock.sendPresenceUpdate('composing', id)

//Auto-RecordVoiceNote
await sock.sendPresenceUpdate('recording', id)
