### ISSUE TITLE
[BUG] - Wrong mimetype. Gif message comes with image/jpeg

### ISSUE THREAD

**Issue by charlscript** [adiwajshing/Baileys#2589]
**Describe the bug**
When a gif message is received, it comes with image/jpeg mimetype

**To Reproduce**
1. Get a gif message and console.log it
2. Is received a wrong mimetype

**Expected behavior**
It is expected to return  image/gif.

**Environment (please complete the following information):**
 - Is this on a server? 
 No
 - What do your `connectOptions` look like? 
 - ` const socket = makeWaSocket ({
            version: version,
            printQRInTerminal: true,
            auth: state,
            logger: logger,
            msgRetryCounterCache,
            generateHighQualityLinkPreview: true
        });`
 - Do you have multiple clients on the same IP?
 - No
 - Are you using a proxy?
 - No

**Additional context**
--

**Comment by RavensVenix** [comment]
Try this

import { MessageType, MessageOptions, Mimetype } from '@adiwajshing/baileys'
// Sending gifs
await sock.sendMessage(
    id, 
    { 
        video: fs.readFileSync("Media/ma_gif.mp4"), 
        caption: "hello!",
        gifPlayback: true
    }
)
