### ISSUE TITLE
Authenticating failed to web server

### ISSUE THREAD

**Issue by xxxLord99** [adiwajshing/Baileys#259]
Hello sir, @adiwajshing  
when i try your libs, i've got some trouble and the qrcode doesn't generated, pict below
any solutions for me please :(

![Screenshot_20201209_161503](https://user-images.githubusercontent.com/56199096/101609597-b9390200-3a39-11eb-97ab-75d26163fede.png)

**Comment by adiwajshing** [comment]
I think if you update to the latest commit, this will be resolved

**Comment by xxxLord99** [comment]
> I think if you update to the latest commit, this will be resolved
still can't work for me sir.

**Comment by xxxLord99** [comment]
pict below for my full code

![image](https://user-images.githubusercontent.com/56199096/101630065-ec3cbf00-3a54-11eb-9b40-4cac063d4684.png)

**Comment by ekoeryanto** [comment]
can it be because of the newest update of whatsapp web?
