### ISSUE TITLE
[BUG] - issue  websocket and etc after scan QR and Logout

### ISSUE THREAD

**Issue by mzayn** [adiwajshing/Baileys#2591]
this issue don't solved. when i use logout & disconnect the QR / Connection

i was use latest version Github Bailey not v5

```
INFO [2023-03-02 09:06:32.085 +0800]: connection errored
    trace: "Error: Intentional Logout\n    at Object.logout (/mybot/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:355:13))"
```
   
   here my code :
   
![image](https://user-images.githubusercontent.com/15009301/222306759-dba94e75-e453-4ed4-8188-5704996f02de.png)

   
---------

this issue was found on WA Business - when not completely logout at the linked device and appear (Logged Out sign) > here the picture 
![image](https://user-images.githubusercontent.com/15009301/222307194-8495318f-1917-4808-966f-1c74687773e7.png)

and When in try WS Personal > the logout fully logout the device with No Sign (Logged Out) at my phone > Linked Device

hope can fix this.

Thanks

**Comment by ikbalardiansah** [comment]
Same error here. Do you solving it yet?

**Comment by mzayn** [comment]
still no idea to fix..
