### ISSUE TITLE
[ Error ] : while sending messages.

### ISSUE THREAD

**Issue by AbhiDevOfficial** [adiwajshing/Baileys#2594]
Hey,
While sending messages, bot throwing an error. And I've found that line where the bot throws Error. The error is **Error: NoSessionException**

https://github.com/adiwajshing/Baileys/blob/74bd2f57a266542ef405fb9077fda86c7a7984d7/WASignalGroup/group_cipher.js#L33

**Some times while sending messages to group, it shows WAITING FOR THIS MESSAGE too.**

Please fix these asap.

**Thank You!**

**Comment by RavensVenix** [comment]
Waiting for message is normal when using a new session, usually this process takes about 10 minutes, also if someone adds your bot to the group sometimes the message will be waiting for message. If you wait, this problem will resolve itself or if it's still not resolved, try restarting the script or try scanning a new session.

**Comment by AbhiDevOfficial** [comment]
> Waiting for message is normal when using a new session, usually this process takes about 10 minutes, also if someone adds your bot to the group sometimes the message will be waiting for message. If you wait, this problem will resolve itself or if it's still not resolved, try restarting the script or try scanning a new session.

Thank You
