### ISSUE TITLE
[BUG] why sending video/photo massages two times? 

### ISSUE THREAD

**Issue by HEXA-GAN** [adiwajshing/Baileys#2595]

**Comment by RfadnjdExt** [comment]
Can yoy show your code and the version you using?

**Comment by SafwanGanz** [comment]
> Can you show your code and the Baileys version that you use?

Which part?

**Comment by SafwanGanz** [comment]
> Can you show your code and the Baileys version that you use?

Using baileys latest version 5.0.0

**Comment by HEXA-GAN** [comment]
> _No description provided._

Which part?

**Comment by HEXA-GAN** [comment]
Using baileys latest version 5.0.0

**Comment by Shubhamrawat5** [comment]
I've face same problem sometimes randomly

**Comment by jacktheboss220** [comment]
same
