### ISSUE TITLE
[HELP] While sending audio

### ISSUE THREAD

**Issue by Maaz4f** [adiwajshing/Baileys#2597]
I want to reply an audio in that is in same directory named audiocomb.mp3 in javascript file.

**Comment by hansputera** [comment]
just read the `audiocomb.mp3` file contents with `node:fs`, and take the Buffer.

After that, send the buffer using `.sendMessage({ audio: <buffer> })`

**Comment by zLucasKk** [comment]
It's **not a BUG**.
You need to transform your _./audiocomb.mp3_ file into a _Buffer_.
To do this, read the file using _FileSystem Library (fs)_, store the result value to any variable you want, place it inside _.sendMessage({ audio: **audioBuffer** });_ then everything should work great, remember, your audio need to be uploaded everytime to WhatsApp servers, it always demand some time so don't worry or, consider using a already uploaded file.

**Comment by zLucasKk** [comment]
You can also resquest audios from web using _.sendMessage({ audio: { url: **'https://.../audiocomb.mp3'** });_.
