### ISSUE TITLE
generateQRCode 

### ISSUE THREAD

**Issue by JuniorRibas** [adiwajshing/Baileys#26]
Good Morning

I'm having trouble making an implementation using your lib

How can I send the qr code key to my API?

how I could use the generateQRCode method inside my controller.

`const WhatsAppWeb = require('baileys') 

class WhatsappController {

    async getQrCode({repsonse}){

        const client = new WhatsAppWeb()
        

        const oi = await  client.generateQRCode()

        console.log(oi)
    }

}

module.exports = WhatsappController`

**Comment by adiwajshing** [comment]
This was resolved a couple days back. Take a look at issue #16.

**Comment by JuniorRibas** [comment]
The big difficulty is sending the str with the token to generate the QR Code for my front

Me doing so does not report the token to me


`
const client = new WhatsAppWeb()
const token = await client.onReadyForPhoneAuthentication()

response.send(token)
`


I want to authenticate, save
 `const authJSON = client.base64EncodedAuthInfo ()`
in the database and then give a client.close ()

**Comment by adiwajshing** [comment]
I'm glad you find the library useful. However, you're using the function incorrectly, `onReadyForPhoneAuthentication ` is a callback, it should be:

``` javascript
const client = new WhatsAppWeb()
client.onReadyForPhoneAuthentication = ([ref, publicKey, clientID]) => {
    const str = ref + "," + publicKey + "," + clientID
    // generate QR with str
    // QR.generate(str, {small: true})
}
```

**Comment by JuniorRibas** [comment]
I'm sorry to bother you again.

But I did what you asked and it worked
But I came across another little problem kkkk

`const client = new WhatsAppWeb ()`
`client.connect ()`
`client.onReadyForPhoneAuthentication = ([ref, publicKey, clientID]) => {`
      ` const str = ref + "," + publicKey + "," + clientID`
      
         `this.socket.emitTo ('message', {authenticated: false, str}, [this.socket.id])`
    ` }`

Put the code above inside a web socket, but I wanted to send a confirmation message as soon as the QrCode scan was done

And send feedback from that
`client.base64EncodedAuthInfo ()`

**Comment by adiwajshing** [comment]
Sure. The connect function is a promise, so you could know when you're authenticated successfully when:

``` javascript

client.connect ()
.then (() => {
    console.log ("connected")
    const authInfo = client.base64EncodedAuthInfo () // send this over or do something with it
})

```

Do read the readme, it explains all of this.

**Comment by JuniorRibas** [comment]
Got it partner

I had done just that, but I couldn't do `then`

`const client = new WhatsAppWeb ()`
`client.connect ()`
`.the (() => {`
`console.log ('Done')`
`})`
`client.onReadyForPhoneAuthentication = ([ref, publicKey, clientID]) => {`
        `const str = ref + "," + publicKey + "," + clientID`
      
          `this.socket.emitTo ('message', {authenticated: false, str}, [this.socket.id])`
     ` }`

I think that when calling client.onReadyForPhoneAuthentication `then` is not executed

**Comment by JuniorRibas** [comment]
Got it partner

I had done just that, but I couldn't do `then`

`const client = new WhatsAppWeb ()`
`client.connect ()`
`.the (() => {`
`console.log ('Done')`
`})`
`client.onReadyForPhoneAuthentication = ([ref, publicKey, clientID]) => {`
        `const str = ref + "," + publicKey + "," + clientID`
      
          `this.socket.emitTo ('message', {authenticated: false, str}, [this.socket.id])`
     ` }`

I think that when calling `client.onReadyForPhoneAuthentication` `then` is not executed

**Comment by JuniorRibas** [comment]
![qr](https://user-images.githubusercontent.com/34239187/83255522-fa954e80-a186-11ea-8ab2-dbf2367e905c.png)

I found the problem

Function action does not end authentication

she stays: `waiting for chats & contacts`

Forever

**Comment by JuniorRibas** [comment]
Started working again! hehe


I believe that there must be a limit that a cell phone can connect and disconnect from whatsapp web
I took the test again and now reconnected.

**Comment by adiwajshing** [comment]
Great. Since your issue seems to be resolved, I'm closing the issue.
