### ISSUE TITLE
[BUG] Problem to send group Messages -> sendMessages() method 

### ISSUE THREAD

**Issue by SalazarF92** [adiwajshing/Baileys#2600]
Hi there! We're currently experiencing issues when trying to send content to all groups using Bailleys. The problem is happening randomly, where sometimes the content is sent to all groups, sometimes only to a few groups. We don't receive any error messages when the content is not sent to some groups.

The current problem started when we update to Bailleys version in which the method changed from relayMessage() to sendMessage().

We've already checked the following:

The device is connected properly through the QR code.
We tried changing the device hardware model to test if that was the issue for certain cases, but we still experienced the same problem.

**Comment by zLucasKk** [comment]
Consider use the older version of Baileys, if you fell confortable and secured with.

**Comment by SalazarF92** [comment]
> Consider use the older version of Baileys, if you fell confortable and secured with.

Actually I need the current version that we are running considering the functions and methods we are using to perform the best result with the clients we have..

**Comment by zLucasKk** [comment]
> > Consider use the older version of Baileys, if you fell confortable and secured with.
> 
> Actually I need the current version that we are running considering the functions and methods we are using to perform the best result with the clients we have..

I really can't realize what exactly is your problem, i'm sorry.

**Comment by zLucasKk** [comment]
> 



> @zLucasKk The thing is, we had a microservice that generates the message object for baileys based on our object, it is basically the same what Baileys do with "sendMessage" under the hood, but it broke about a month ago in a way that people couldn't download any type of media generated by it. That's the context behind changing from "relayMessage" to baileys's "sendMessage". And well, using an older version isn't a good practice security-wise, and there is no guarantee that it will work forever, but I appreciate your help anyways.

I understand you, hope you guys find a solution for that.

**Comment by SalazarF92** [comment]
Hello. About the current situation, we solve it rolling back the version from 5.0.0 to 4.4.0. Thanks!
