### ISSUE TITLE
Product message sending

### ISSUE THREAD

**Issue by Inevitable-Dev** [adiwajshing/Baileys#2601]
Is it possible to send product messages in Baileys?

Like these:
![image](https://user-images.githubusercontent.com/73140494/222921153-954233d6-b9d5-4832-af93-ba151f0b8adf.png)

![image](https://user-images.githubusercontent.com/73140494/222921197-5d34e232-2262-4f12-bccc-dc097c0168ca.png)

Looking at the documentation, it seems to me that there are only interactions related to the catalog

**Comment by Inevitable-Dev** [comment]
@adiwajshing Is there any work in progress to add this type of message?

**Comment by IgorDePaula** [comment]
any update?
