### ISSUE TITLE
Messages are sent to the authenticated number instead of the assigned one [BUG]

### ISSUE THREAD

**Issue by angelLain** [adiwajshing/Baileys#2606]
Hello, I have this problem very rare, when you sent messages on my cell phone it comes out that it has been sent to my cell phone number, which is wrong because I sent it to another number but in whatsapp web I get that if it was sent correctly to another number but when I ask the contact who supposedly received the message I never received anything,  nothing appears, try to close all sessions and change the browser authentication to Desktop but I still have the error

capture of the cell phone that shows that the message is coming to me instead of the other number
![cappp](https://user-images.githubusercontent.com/115596248/223002828-69619ef1-e4bd-42d7-8b26-c222827aee23.PNG)

capture of the web where it is seen that if it arrives but only I can see it, the contact tells me that he does not see it
![looo](https://user-images.githubusercontent.com/115596248/223002907-cecb83d1-71a6-475a-b76b-40564242cb23.PNG)

**Comment by Epayq** [comment]
Same

**Comment by ANUR46** [comment]
I think you are having same issue which I were getting before.
Please review my [solution](https://github.com/adiwajshing/Baileys/issues/2539#issuecomment-1436329734). It will work for you if you have the same problem.
