### ISSUE TITLE
[BUG] isAdmin and isSuperAdmin booleans returns undefined: undefined.

### ISSUE THREAD

**Issue by zLucasKk** [adiwajshing/Baileys#2607]
_contact.isSuperAdmin_ and _contact.isAdmin_ is returning _undefined: undefined_ expected: _'admin': string | 'superadmin':string | null: null._

see #2602 for more information.

**Comment by hansputera** [comment]
maybe you can use `Participant.admin === 'admin'` or `Participant.admin === 'superadmin'` instead to identify the participant is admin or superadmin

**Comment by zLucasKk** [comment]
> maybe you can use `Participant.admin === 'admin'` or `Participant.admin === 'superadmin'` instead to identify the participant is admin or superadmin

**Comment by zLucasKk** [comment]
> maybe you can use `Participant.admin === 'admin'` or `Participant.admin === 'superadmin'` instead to identify the participant is admin or superadmin

Thanks for you reply, i've already mentioned the participant object method in #2602 as a solution.

**Comment by AzRyCb** [comment]
Close this issue

**Comment by Littlerock505** [comment]
No comment i new don't want to step on toes

**Comment by zLucasKk** [comment]
> Close this issue

It's a BUG. Need to be solved.
