### ISSUE TITLE
Add list users (like list groups) functionality?

### ISSUE THREAD

**Issue by lightaffaire** [adiwajshing/Baileys#2608]
Is it planned to add list users functionality?

1. list active chats
or
2. list all users with whatsapp on phone

return  phonenum/id, username/chatname

**Comment by unilogica** [comment]
Is there a way to list the groups my number is an admin or participant?

**Comment by AliAryanTech** [comment]
> Is there a way to list the groups my number is an admin or participant?

Indeed, 
```js 
await client.groupFetchAllParticipating()
```

**Comment by robvanderleek** [comment]
`groupFetchAllParticipating()` lists all the groups a user is a member of, it does not list users.
AFAIK there is currently no way to list users.

**Comment by AliAryanTech** [comment]
> `groupFetchAllParticipating()` lists all the groups a user is a member of, it does not list users. AFAIK there is currently no way to list users.

Noobs thesedays

**Comment by unilogica** [comment]
> > `groupFetchAllParticipating()` lists all the groups a user is a member of, it does not list users. AFAIK there is currently no way to list users.
> 
> Noobs thesedays

Lol. Combining 2 pieces he assembles the puzzle

**Comment by lightaffaire** [comment]
Instead of posting a snarky comment how about just answering the question or thread with useful info?

ie.

1. there is no known way todo it
2. it is an interesting suggestion and will be added to the todo list

or 

3. here is a potential way to implement what you require using 2 pieces

That way everyone benefits. Leave such comments at the door @unilogica as it helps no-one.

**Comment by unilogica** [comment]
> Instead of posting a snarky comment how about just answering the question or thread with useful info?
> 
> ie.
> 
> 1. there is no known way todo it
> 2. it is an interesting suggestion and will be added to the todo list
> 
> or
> 
> 3. here is a potential way to implement what you require using 2 pieces
> 
> That way everyone benefits. Leave such comments at the door @unilogica as it helps no-one.

I usually wouldn't waste time on this kind of discussion. But I'll take the opportunity to leave something really useful in the repository: You didn't ask any questions. The other user didn't ask any questions either, he stated that there was no way.

Many people don't know how to ask questions on the internet. They don't know how to formulate a simple question, for example, I tried this and that, but that didn't work. So what could I do with that?

You didn't ask for my opinion, so I throw you a question back: Why don't you take one of your suggestions that you gave and implement it here? Rephrase it with a question and you'll probably always get an answer.

Didn't realize that @AliAryanTech  gave a precious pearl here? And a wise man once said "Cast not pearls before swine".

**Comment by AliAryanTech** [comment]
> > Instead of posting a snarky comment how about just answering the question or thread with useful info?
> > ie.
> > 
> > 1. there is no known way todo it
> > 2. it is an interesting suggestion and will be added to the todo list
> > 
> > or
> > 
> > 3. here is a potential way to implement what you require using 2 pieces
> > 
> > That way everyone benefits. Leave such comments at the door @unilogica as it helps no-one.
> 
> I usually wouldn't waste time on this kind of discussion. But I'll take the opportunity to leave something really useful in the repository: You didn't ask any questions. The other user didn't ask any questions either, he stated that there was no way.
> 
> Many people don't know how to ask questions on the internet. They don't know how to formulate a simple question, for example, I tried this and that, but that didn't work. So what could I do with that?
> 
> You didn't ask for my opinion, so I throw you a question back: Why don't you take one of your suggestions that you gave and implement it here? Rephrase it with a question and you'll probably always get an answer.
> 
> Didn't realize that @AliAryanTech gave a precious pearl here? And a wise man once said "Cast not pearls before swine".

Wow, that's such a nice quotes, well I shouldn't give that a perfect solution which they can't even use.

**Comment by lightaffaire** [comment]
@unilogica instead of waffling on about how to ask questions on the internet how about dragging your eyes to the beginning of this thread (at the top of this page...) but to save overloading your meagre cognitive abilities I will copy it here for you:

"Is it planned to add list users functionality?

    list active chats
    or
    list all users with whatsapp on phone

return phonenum/id, username/chatname"

A simple question asking if list users like the list groups functionality is available in the library.

Would be great to have that available so that apps built using baileys could offer that functionality ie. mudslide.

**Comment by AliAryanTech** [comment]
> @unilogica instead of waffling on about how to ask questions on the internet how about dragging your eyes to the beginning of this thread (at the top of this page...) but to save overloading your meagre cognitive abilities I will copy it here for you:
> 
> "Is it planned to add list users functionality?
> 
> ```
> list active chats
> or
> list all users with whatsapp on phone
> ```
> 
> return phonenum/id, username/chatname"
> 
> A simple question asking if list users like the list groups functionality is available in the library.
> 
> Would be great to have that available so that apps built using baileys could offer that functionality ie. mudslide.

Let's, me end this topic, "Is it planned to add list users functionality" already did long ago as if you read documentation.

Next to "list all users with whatsapp on phone"
By phone you mean to client, so I give you the answer already, otherwise you can store all the users id on a DB and then get the list mostly ppl use mongoose you can see the code on anyone bot.
