### ISSUE TITLE
user-presence-update deprecated.

### ISSUE THREAD

**Issue by ekucet** [adiwajshing/Baileys#261]
'**user-presence-update**' deprecated. It is recommended '**chat-update**' But '**chat-update**' is work only if you have a chat with that your contact. if you haven't a chat, 'chat-update' doesn't work. is there any other solution this case? Because I want to presence for **my contact list of all**.

**Comment by adiwajshing** [comment]
As far as I know, if you don't have a chat with a person -- you won't get presence updates

**Comment by ekucet** [comment]
Yes I know, 'user-presence-update' method is working but deprecated. 'user-presence-update' method was giving presence of contact if you don't have a chat.

**Comment by vjyanand** [comment]
Please let me know how this is resolved.

**Comment by ekucet** [comment]
> Please let me know how this is resolved.

i didn’t find any solution. I lost my hope. ☹️

**Comment by ekucet** [comment]
> Please let me know how this is resolved.

hi bro, if you want to search with together, you can add my whatsapp number: 

+905307036483

We can share our experiences.
