### ISSUE TITLE
Exemple of README is outdated

### ISSUE THREAD

**Issue by DelvesPlunger** [adiwajshing/Baileys#2619]
The example on the main readme file is outdated; The socket must be created with an auth object but if you are using the npm version and not the git version comment some options from the examples:

Working example for the release version from npm (version 5.0.0):

```
const sock = makeWASocket({
		//version,
		// logger,
		printQRInTerminal: true,
		auth: {
			creds: state.creds,
			/** caching makes the store faster to send/recv messages */
			//keys: makeCacheableSignalKeyStore(state.keys, logger),
		},
		// msgRetryCounterCache,
		// generateHighQualityLinkPreview: true,
		// ignore all broadcast messages -- to receive the same
		// comment the line below out
		// shouldIgnoreJid: jid => isJidBroadcast(jid),
		// implement to handle retries & poll updates
		// getMessage,
	})

```

**Comment by DelvesPlunger** [comment]
The example on the main readme file is outdated; The socket must be created with an auth object but if you are using the npm version and not the git version comment some options from the examples:

Working example for the release version from npm (version 5.0.0):

```
const sock = makeWASocket({
		//version,
		// logger,
		printQRInTerminal: true,
		auth: {
			creds: state.creds,
			/** caching makes the store faster to send/recv messages */
			//keys: makeCacheableSignalKeyStore(state.keys, logger),
		},
		// msgRetryCounterCache,
		// generateHighQualityLinkPreview: true,
		// ignore all broadcast messages -- to receive the same
		// comment the line below out
		// shouldIgnoreJid: jid => isJidBroadcast(jid),
		// implement to handle retries & poll updates
		// getMessage,
	})

```

**Comment by beshoo** [comment]
I can not run any examples. 
what is the correct way to install it?

and what is the correct npm installation command?

**Comment by ANUR46** [comment]
> 

Did you mean to install baileys installation using npm? if yes then you can use the following command.

```
npm install @adiwajshing/baileys

**Comment by ANUR46** [comment]
> I can not run any examples. what is the correct way to install it?
> 
> and what is the correct npm installation command?

Did you mean to install baileys installation using npm? if yes then you can use the following command.
```
npm install @adiwajshing/baileys
```
