### ISSUE TITLE
[BUG] makeWASocket is not a function

### ISSUE THREAD

**Issue by IgorDePaula** [adiwajshing/Baileys#2624]
**Describe the bug**
makeWASocket is not a function

**To Reproduce**
 I used the script from README file

![Captura de tela de 2023-03-12 13-33-53](https://user-images.githubusercontent.com/2833993/224558626-c752cf5b-4b31-4414-80db-ee2d45e18534.png)

**Expected behavior**
not have error

**Environment (please complete the following information):**
 - Is this on a server? not, is a local test
 - What do your `connectOptions` look like?  is default
 - Do you have multiple clients on the same IP? not
 - Are you using a proxy? not

**Comment by barkerpedro** [comment]
Try:


```node
import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'

const config = {
  printQRInTerminal: true,
// ...
};

const sock = makeWASocket(config);
```

**Comment by IgorDePaula** [comment]
> Try:
> 
> ```js
> import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> 
> const config = {
>   printQRInTerminal: true,
> // ...
> };
> 
> const sock = makeWASocket(config);
> ```

is equals my code above.

**Comment by zennn08** [comment]
try this:

```js
const {
    DisconnectReason,
    default: makeWASocket,
    // useSingleFileAuthState
} = (await import('@adiwajshing/baileys')).default

const config = {
  printQRInTerminal: true,
// ...
};

const sock = makeWASocket(config);
```

**Comment by barkerpedro** [comment]
> > Try:
> > ```js
> > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > 
> > const config = {
> >   printQRInTerminal: true,
> > // ...
> > };
> > 
> > const sock = makeWASocket(config);
> > ```
> 
> is equals my code above.

it's different, check it correctly and test it as I gave you to check if it will work

**Comment by ANUR46** [comment]
Just add .default with the makeWASocket function
Example-

```
import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'

const conn = makeWASocket.default({
        printQRInTerminal: true,
    })
```

**Comment by IgorDePaula** [comment]
> Just add .default with the makeWASocket function Example-
> 
> ```js
> import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> 
> const conn = makeWASocket.default({
>         printQRInTerminal: true,
>     })
> ```

![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)

**Comment by IgorDePaula** [comment]
> try this:
> 
> ```js
> const {
>     DisconnectReason,
>     default: makeWASocket,
>     // useSingleFileAuthState
> } = (await import('@adiwajshing/baileys')).default
> 
> const config = {
>   printQRInTerminal: true,
> // ...
> };
> 
> const sock = makeWASocket(config);
> ```

![image](https://user-images.githubusercontent.com/2833993/224700470-5da23c67-f721-4b2a-bf1c-b440c2091c2b.png)

**Comment by ANUR46** [comment]
> > Just add .default with the makeWASocket function Example-
> > ```js
> > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > 
> > const conn = makeWASocket.default({
> >         printQRInTerminal: true,
> >     })
> > ```
> 
> ![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)

Try to show the code to get correct help in place of showing screenshot. Because by seeing screenshot can not get what code you are using and how.

**Comment by IgorDePaula** [comment]
> > > Just add .default with the makeWASocket function Example-
> > > ```js
> > > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > > 
> > > const conn = makeWASocket.default({
> > >         printQRInTerminal: true,
> > >     })
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)
> 
> Try to show the code to get correct help in place of showing screenshot. Because by seeing screenshot can not get what code you are using and how.

this simple code https://adiwajshing.github.io/Baileys/#connecting

**Comment by ANUR46** [comment]
> > > > Just add .default with the makeWASocket function Example-
> > > > ```js
> > > > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > > > 
> > > > const conn = makeWASocket.default({
> > > >         printQRInTerminal: true,
> > > >     })
> > > > ```
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)
> > 
> > 
> > Try to show the code to get correct help in place of showing screenshot. Because by seeing screenshot can not get what code you are using and how.
> 
> this simple code https://adiwajshing.github.io/Baileys/#connecting

Make sure that the code you have written is into JS not into TS. Read the docs carefully that code is into the TS. First convert it into js and then follow my above solution which is for using .default with makeWASocket function.

You can take reference of connection code from my this code [Check Code](https://github.com/adiwajshing/Baileys/issues/2539#issue-1576102694)

**Comment by IgorDePaula** [comment]
> > > > > Just add .default with the makeWASocket function Example-
> > > > > ```js
> > > > > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > > > > 
> > > > > const conn = makeWASocket.default({
> > > > >         printQRInTerminal: true,
> > > > >     })
> > > > > ```
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)
> > > 
> > > 
> > > Try to show the code to get correct help in place of showing screenshot. Because by seeing screenshot can not get what code you are using and how.
> > 
> > 
> > this simple code https://adiwajshing.github.io/Baileys/#connecting
> 
> Make sure that the code you have written is into JS not into TS. Read the docs carefully that code is into the TS. First convert it into js and then follow my above solution which is for using .default with makeWASocket function.

I just copy and paste the code, is all in js.

**Comment by ANUR46** [comment]
> > > > > > Just add .default with the makeWASocket function Example-
> > > > > > ```js
> > > > > > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > > > > > 
> > > > > > const conn = makeWASocket.default({
> > > > > >         printQRInTerminal: true,
> > > > > >     })
> > > > > > ```
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)
> > > > 
> > > > 
> > > > Try to show the code to get correct help in place of showing screenshot. Because by seeing screenshot can not get what code you are using and how.
> > > 
> > > 
> > > this simple code https://adiwajshing.github.io/Baileys/#connecting
> > 
> > 
> > Make sure that the code you have written is into JS not into TS. Read the docs carefully that code is into the TS. First convert it into js and then follow my above solution which is for using .default with makeWASocket function.
> 
> I just copy and paste the code, is all in js.

Read the given document carefully then proceed.

**Comment by IgorDePaula** [comment]
> > > > > > > Just add .default with the makeWASocket function Example-
> > > > > > > ```js
> > > > > > > import makeWASocket, { DisconnectReason } from '@adiwajshing/Baileys'
> > > > > > > 
> > > > > > > const conn = makeWASocket.default({
> > > > > > >         printQRInTerminal: true,
> > > > > > >     })
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > ![image](https://user-images.githubusercontent.com/2833993/224700110-a3954c23-a502-4468-b108-93f0731c64a9.png)
> > > > > 
> > > > > 
> > > > > Try to show the code to get correct help in place of showing screenshot. Because by seeing screenshot can not get what code you are using and how.
> > > > 
> > > > 
> > > > this simple code https://adiwajshing.github.io/Baileys/#connecting
> > > 
> > > 
> > > Make sure that the code you have written is into JS not into TS. Read the docs carefully that code is into the TS. First convert it into js and then follow my above solution which is for using .default with makeWASocket function.
> > 
> > 
> > I just copy and paste the code, is all in js.
> 
> Read the given document carefully then proceed.

where I wrong?

**Comment by ANUR46** [comment]
> 

Again copy the code given in the docs and then use
**makeWASocket.default** in place of makeWASocket

**Comment by IgorDePaula** [comment]
> > 
> 
> Again copy the code given in the docs and then use **makeWASocket.default** in place of makeWASocket

I already make this, and I got this same result

**Comment by ANUR46** [comment]
> > > 
> > 
> > 
> > Again copy the code given in the docs and then use **makeWASocket.default** in place of makeWASocket
> 
> I already make this, and I got this same result

Have you tried with new code? And have you convert the code into the JS?

**Comment by ANUR46** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Again copy the code given in the docs and then use **makeWASocket.default** in place of makeWASocket
> > > 
> > > 
> > > I already make this, and I got this same result
> > 
> > 
> > Have you again write new code as I said? And have you convert the code into the JS?
> 
> Yes, new code, no, I'm coding in js, not ts.

The code you have copy and past is into TS not fully JS. So first convert it then use.
Copy your code and paste into the [Playgroung](https://www.typescriptlang.org/play#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBBCcQQ0MwAUVWDEQC0gADVHBQGNJ3KAALygABEAAkYNAMOB4GRonzFBTBPB3AERcwABS0+mM9ysygc9wASmCKhwzQ8ZC8iHFzmB7BoXzcZmY7AYzEg-Fg0HUiQ58D0Ii8fLpDKZgj5SWxfPADlQAHJhAA5SASPlBFQAeS+ZHegmdWkgR1QjgUrmkeFATjNOmGWH0KAQiGhwkuNok4uiIgMHGxCyYrA4PCCJSAA) and then copy the converted JS code and then run.

**Comment by safwanolaimat** [comment]
Hello 

You can bypass this like
**note:the code uses typescript import so you should add in the package.json "type":"module"**

by using the "useSingleFileAuthState"
```
import makeWASocket, {useSingleFileAuthState} from '@adiwajshing/Baileys'

const conn = makeWASocket.default({
        printQRInTerminal: true,
        auth:useSingleFileAuthState("test.json").state
})
```
also you can use the "useMultiFileAuthState" which is the recommended way
```
import makeWASocket, { useMultiFileAuthState } from '@adiwajshing/Baileys'
const startSock = async () => {
    const conn = makeWASocket.default({
        printQRInTerminal: true,
        auth: (await useMultiFileAuthState("auth_folder")).state
    })
}

startSock();
```

**Comment by IgorDePaula** [comment]
> Hello
> 
> You can bypass the issue like this **note: the code uses typescript import so you should add in the package.json "type":"module"**
> 
> by using the "useSingleFileAuthState"
> 
> ```
> import makeWASocket, {useSingleFileAuthState} from '@adiwajshing/Baileys'
> 
> const conn = makeWASocket.default({
>         printQRInTerminal: true,
>         auth:useSingleFileAuthState("test.json").state
> })
> ```
> 
> also you can use the "useMultiFileAuthState" which is the recommended way
> 
> ```
> import makeWASocket, { useMultiFileAuthState } from '@adiwajshing/Baileys'
> const startSock = async () => {
>     const conn = makeWASocket.default({
>         printQRInTerminal: true,
>         auth: (await useMultiFileAuthState("auth_folder")).state
>     })
> }
> 
> startSock();
> ```
> 
> **Update: if you don't got the qrCode in the terminal you should the add the "qrcode-terminal" package in the dependancy** `npm i qrcode-terminal`

I already try this

**Comment by safwanolaimat** [comment]
can you put your code and package.json here not screenshot

**Comment by safwanolaimat** [comment]
your screenshot is not same as what I provided

**Comment by safwanolaimat** [comment]
If you got connection close after scanning the QRCode 

try this code 
```
const { Boom } = require('@hapi/boom')
const { default: makeWASocket, DisconnectReason, useMultiFileAuthState } = require('@adiwajshing/baileys')

const startSock = async() => {
	const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')
	const sock = makeWASocket({
		printQRInTerminal: true,
		auth: {
			creds: state.creds,
		},
	})

	sock.ev.process(
		async(events) => {
			if(events['connection.update']) {
				const update = events['connection.update']
				const { connection, lastDisconnect } = update

				if(connection === 'close') {
					// reconnect if not logged out
					if (new Boom(lastDisconnect?.error)?.output.statusCode !== DisconnectReason.loggedOut) {
						startSock()
					} else {
						console.log('Connection closed. You are logged out.')
					}
				}
				console.log('connection update', update)
			}
			// credentials updated -- save them
			if(events['creds.update']) {
				await saveCreds()
			}
		}
	)
	return sock;
}

startSock();
```

**Comment by IgorDePaula** [comment]
Thank you very much @safwanolaimat , your code help me a lot. Know you anything about this https://github.com/adiwajshing/Baileys/issues/2626?
