### ISSUE TITLE
Unable to send media

### ISSUE THREAD

**Issue by Nurutomo** [adiwajshing/Baileys#263]
From the error, we can see the problem is might be the **Jimp** module when generating the thumbnail

My code to send the image
```js
/**
  * Variable description
  * @param {ChatId} id Chat ID
  * @param {Buffer} img My Image Buffer
  * @param {MessageType} type message type
  */
conn.sendMessage(id, img, MessageType.image)
```
![IMG-20201209-WA0037](https://user-images.githubusercontent.com/18616827/101639633-1c3e8f00-3a62-11eb-83a3-9726f1ee3ea6.jpg)

```
Platform: Android 5.1
Baileys: latest version in npm (during 9 Dec 2020)
NodeJS: v13.0.0
App: Termux
```

**Comment by adiwajshing** [comment]
Well, the error says it couldn't find MIMETYPE for a `null` buffer. That's probably the issue -- the image is corrupt or incorrectly retrieved?

**Comment by Nurutomo** [comment]
My image was incorrectly retreived, because im using API to get the (png) image
Here it is the image that doesn't work
![canvas](https://user-images.githubusercontent.com/18616827/101850241-f9a89500-3b8b-11eb-90f3-c0a0cf9d123b.png)
