### ISSUE TITLE
[BUG] ListMessage, doesn't arrive on whatsapp mobile (lates v.2.23.5.78) but goes to desktop

### ISSUE THREAD

**Issue by syifarahmat** [adiwajshing/Baileys#2645]
This just happened, even though this morning it still could. Looks like WhatsApp has disabled this feature. same as button message

![image](https://user-images.githubusercontent.com/11779955/226544532-a1d7cde2-8116-49e0-97e8-94e5f84536e6.png)

Desktop : ![image](https://user-images.githubusercontent.com/11779955/226544723-ae0a82a3-ac76-4214-bb8a-5c0578d08ce2.png)

🤔🤔🤔

**Comment by makanSukros** [comment]
#2631

**Comment by enoksaju** [comment]
+1
