### ISSUE TITLE
Buttons are not showing after the new whatsapp update. [BUG]

### ISSUE THREAD

**Issue by vihangayt0** [adiwajshing/Baileys#2646]
Buttons are not showing after the new whatsapp update.

**Comment by allanlisboa** [comment]
I have the same problem

**Comment by Abrazax56** [comment]
> struktur pesan tombol yang dikirim oleh whatsapp api official, dikirim variabel recipientKeyHash, mungkin nilai dari variabel recipientKeyHash adalah validasi apakah tombol muncul atau tidak di aplikasi Ini sangat tricky. Sayangnya, tidak mungkin mengirim tombol || daftar melalui Baileys lagi :(

we can only wait how adiwajshing handles this matter

**Comment by alessandroanalistati** [comment]
+1

**Comment by deriknyvo** [comment]
same problem :c

**Comment by surajmahajan2012** [comment]
@adiwajshing it's time to came in to picture now

**Comment by Inevitable-Dev** [comment]
> 

Could you share the value of this variable so we know how it is?

**Comment by Inevitable-Dev** [comment]
> the structure of the button message sent by whatsapp api official, sent the recipientKeyHash variable, maybe the value of the recipientKeyHash variable is a validation for whether the button appears or not in the application It's very tricky. Unfortunately, it was not possible to send button || list through Baileys anymore :(

Could you share the value of this variable so we know how it is?

**Comment by msakiya** [comment]
Same problem :(

**Comment by gigantiumweb** [comment]
@adiwajshing Buttons are not showing on android mobile

**Comment by makanSukros** [comment]
> variable

Maybe @adiwajshing  is working hard to solve this problem, it would be better if we both experiment and try various things to solve this problem

**Comment by emacielxp** [comment]
> > the structure of the button message sent by whatsapp api official, sent the recipientKeyHash variable, maybe the value of the recipientKeyHash variable is a validation for whether the button appears or not in the application It's very tricky. Unfortunately, it was not possible to send button || list through Baileys anymore :(
> 
> @MaznAbdullah Could you share the value of this variable so we know how it is?

something like this:

`"recipientKeyHash": "nopVs9S5HXw9mg=="`

**Comment by JefIra24** [comment]
Same problem :(

**Comment by enoksaju** [comment]
+1

**Comment by manoeuvrelawliet** [comment]
@MaznAbdullah 
Same with #1936 
Right ?

**Comment by marcelomedina22** [comment]
I got this issue for android users, iOS are ok

**Comment by hackersepulveda** [comment]
Any news about this? I tried a few minutes ago and the error continues, the problem is in Android

**Comment by microband-sa** [comment]
Any news ?

**Comment by aniakg** [comment]
We are facing the problem for buttons and list not showing in Phone, web WhatsApp it is showing

**Comment by lucazin** [comment]
IOS device works  but android device no.

**Comment by vikodk67** [comment]
time to switch, to the stone age😔☝️ temporarily

**Comment by inrl-md** [comment]
> Buttons are not showing after the new whatsapp update.
Youse inrl bot md now😂
