### ISSUE TITLE
[NEED HELP]

### ISSUE THREAD

**Issue by BerTren-Nation** [adiwajshing/Baileys#265]
![Screenshot_2020-12-10-07-18-39-67_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/72166971/101705129-e1b41100-3ab8-11eb-80fc-ffb1b86a3910.png)
![Screenshot_2020-12-10-07-18-45-74_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/72166971/101705134-e678c500-3ab8-11eb-9b11-0552df4f1bf0.png)
![Screenshot_2020-12-10-07-19-03-86_7352322957d4404136654ef4adb64504](https://user-images.githubusercontent.com/72166971/101705142-ea0c4c00-3ab8-11eb-898b-ba7afb611890.png)
[NEED HELP]
This is an error
const nameuser = conn.chats.get(m.participant).name
And I tried to delete .name
const nameuser = conn.chats.get(m.participant)

The results undefined

**Comment by adiwajshing** [comment]
This is unrelated to the library. You need to verify the chat/contact exists before accessing it. Try using the optional `?` operator
