### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AakashCoolx** [adiwajshing/Baileys#2650]
system can not filter and start the message sending process

error showing "file already exists" when I click to generate QR code.

 public function stopinit() {
            $ids = explode(",",$this->request->getPost('ids'));
            $file = fopen("/var/www/writable/tmp/whatsapp/lock.txt","w+");
            log_message('error', "HERE stopinit acquiring lock");
            if(flock($file,LOCK_EX)) {
            log_message('error', "HERE stopinit acquiring lock succeeded");
                    if(file_exists("/var/www/writable/tmp/whatsapp/commands.txt") || file_exists("/var/www/writable/tmp/whatsapp/out.txt")) {
                            flock($file,LOCK_UN);
                            fclose($file);
                            return json_encode(array("status"=>"danger","msg"=>"File already exists"));
                    }
                    file_put_contents("/var/www/writable/tmp/whatsapp/commands.txt","stopinit ".implode(" ",$ids));
                    while(!file_exists("/var/www/writable/tmp/whatsapp/out.txt")) {
                            sleep(1);
                    }
                    $response = file_get_contents("/var/www/writable/tmp/whatsapp/out.txt");
                    unlink("/var/www/writable/tmp/whatsapp/out.txt");
            log_message('error', "HERE stopinit relinquishing lock");
                    flock($file,LOCK_UN);
                    fclose($file);
                    return $response;
            } else {
                    fclose($file);
                    return json_encode(array("status"=>"danger","msg"=>"Failed to lock file"));
            }
    }

**Comment by marcelomedina22** [comment]
This is your code bug.
Try use unlink on your code bro

**Comment by AakashCoolx** [comment]
can you please help me out by using any desk? request
