### ISSUE TITLE
useSingleFileAuthState is not a function [BUG]

### ISSUE THREAD

**Issue by Abrazax56** [adiwajshing/Baileys#2654]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by xbnfz01** [comment]
The latest version of Baileys deprecated useSingleFileAuthState , now uses useMultiFileAuthState

**Comment by Abrazax56** [comment]
> The latest version of Baileys deprecated useSingleFileAuthState , now uses useMultiFileAuthState

how to use it?

**Comment by ernestoyoofi** [comment]
useSingleFileAuthState can no longer be used, now can only use useMultiFileAuthState like this

```js
const CreateSocket = require("@adiwajshing/baileys").default
const {
  DisconnectReason,
  useMultiFileAuthState,
} = require("@adiwajshing/baileys")
const P = require("pino")

async function WhatsApp() {
  const { state, saveCreds } = await useMultiFileAuthState(
    __dirname+"/auth" // path folder for save credentials
  )

  const socket = CreateSocket({
    logger: P({ level: "silent" }),
    generateHighQualityLinkPreview: true,
    auth: state,
    printQRInTerminal: true,
  })

  socket.ev.on("creds.update", saveCreds)
  socket.ev.on("connection.update", (status) => {
    const { connection, lastDisconnect } = status
    if(connection === "close") {
      console.log("Error Connection:", lastDisconnect.error)
      const tryConnect = lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut
      if(tryConnect) {
        WhatsApp()
      }
    }
    if(connection === "open") {
      console.log("✅ Success !")
    }
  })
}
```
