### ISSUE TITLE
[BUG] can't send a list message

### ISSUE THREAD

**Issue by afifslonongboy** [adiwajshing/Baileys#2659]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by mmmlves** [comment]
The list and button messages aren't working anymore. There are a lot of reports about this. We are working hard to fix it, but it looks like it is something intentionally built at WhatsApp Server to restrict these types os messages to the official API. Sad. I don't know if people will be able to workaround this problem.

**Comment by gigantiumweb** [comment]
the problem is in Android phone... but still working on WA Web and IPhone

**Comment by bucaramarketing** [comment]
si revisando no funcionan esta caido
