### ISSUE TITLE
[Feature] Connection Retry Event with optional cancellation

### ISSUE THREAD

**Issue by workgroupengineering** [adiwajshing/Baileys#266]
Hi,
thanks for the great library. To improve interactivity I would like to suggest adding an event indicating the number of connection attempts and possibly canceling the connection.

**Comment by adiwajshing** [comment]
Glad you like the library.

1. You can set the max number of attempts via `conn.connectOptions.maxRetries = X`
2. If you want to listen for intermediate closes of the WS
```
conn.on('ws-close', () => {
 // do something here
})
```

Both of these methods are covered in the readme

**Comment by workgroupengineering** [comment]
Thanks for the reply,


>     1. You can set the max number of attempts via `conn.connectOptions.maxRetries = X`
Yes I knew him




>     2\. If you want to listen for intermediate closes of the WS
> 
> 
> ```
> conn.on('ws-close', () => {
>  // do something here
> })
> ```

This event escaped me thanks.

The ws-close event is raised whenever the websocket is closed, right? If for a reason x when I create the connection, the connection to the websocket fails, will I never get a ws-close?
