### ISSUE TITLE
Any bot base that is not encrypted?

### ISSUE THREAD

**Issue by DavidModzz** [adiwajshing/Baileys#2660]

**Comment by DavidModzz** [comment]
:)

**Comment by ridah23** [comment]
Sini bang buat dri 0

**Comment by ridah23** [comment]
https://wa.me/6281572885606

**Comment by guiireal** [comment]
This issue doesn't make much sense, you should open a discussion instead of an issue.

**Comment by inrl-md** [comment]
Chcek x-asena :- https://github.com/inrl-official/inrl-bot-md

Decrypted :- https://github.com/X-Electra/X-Asena

**Comment by dhyZx** [comment]
cringe
