### ISSUE TITLE
[BUG] Failure in decrypting message at event on messages.upsert

### ISSUE THREAD

**Issue by BoboiAzumi** [adiwajshing/Baileys#2662]
```
{"level":50,"time":"2023-03-25T06:14:15.885Z","pid":6187,"hostname":"N-Konpyuta","key":
{"remoteJid":"xxxxxxxxxxxxx@s.whatsapp.net","fromMe":false,
"id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
"params":["Cannot read properties of undefined (reading 'get')"],"msg":"failure in decrypting message"}
```

Here is My Code

```js
const makeWASocket = require("@adiwajshing/baileys")
const  { DisconnectReason, fetchLatestBaileysVersion, proto, useMultiFileAuthState, Browsers, makeCacheableSignalKeyStore }  = makeWASocket

const MAIN_LOGGER = require( '@adiwajshing/baileys/lib/Utils/logger.js' )

const logger = MAIN_LOGGER.default.child({})
logger.level = 'error'

const startSock = async()=>{
    const { state, saveCreds } = await useMultiFileAuthState('baileys_auth_info')
	// fetch latest version of WA Web
	const { version, isLatest } = await fetchLatestBaileysVersion()
	console.log(`using WA v${version.join('.')}, isLatest: ${isLatest}`)

	const sock = makeWASocket.default({
        browser: Browsers.ubuntu("chrome"),
		version,
        markOnlineConnect: true,
		printQRInTerminal: true,
		auth: {
			creds: state.creds
		},
        logger: logger,
        getMessage: () => {return proto.Message.fromObject({})}
	})

    sock.ev.on ('creds.update', saveCreds)

    sock.ev.on("connection.update", (update)=>{
        const {connection, lastDisconnect} = update
        if(connection === 'close'){
            let shouldReconnect = lastDisconnect.error.output.payload.statusCode !== DisconnectReason.loggedOut
            if(shouldReconnect){
                startSock()
            }
        }
    })

    sock.ev.on('messages.upsert', async m => {
        console.log(JSON.stringify(m))
    })

}


startSock()
```

**Comment by MeLoseAgain** [comment]
Work?

**Comment by BoboiAzumi** [comment]
> Work?

doesn't work

**Comment by Fonnte** [comment]
Using latest baileys version? Or npm version?

**Comment by BoboiAzumi** [comment]
> Using latest baileys version? Or npm version?

both are the latest versions

**Comment by Fonnte** [comment]
> > Using latest baileys version? Or npm version?
> 
> both are the latest versions

Try using npm version, is it solved?

**Comment by BoboiAzumi** [comment]
> > > Using latest baileys version? Or npm version?
> > 
> > 
> > both are the latest versions
> 
> Try using npm version, is it solved?

No, it still doesn't work.
I also try using yarn, but it doesn't work either

**Comment by makanSukros** [comment]
No issue for me, everything ok except button or list

**Comment by BoboiAzumi** [comment]
> No issue for me, everything ok except button or list

wow,
is there something wrong with my code?.
the messages.upsert event is absolutely not working in my code

**Comment by makanSukros** [comment]
> > No issue for me, everything ok except button or list
> 
> wow, is there something wrong with my code?. the messages.upsert event is absolutely not working in my code

IDK For now messages.upsert is fine here

**Comment by BoboiAzumi** [comment]
> > > No issue for me, everything ok except button or list
> > 
> > 
> > wow, is there something wrong with my code?. the messages.upsert event is absolutely not working in my code
> 
> IDK For now messages.upsert is fine here

do you use typescript or javascript?

**Comment by chiraglodariya** [comment]
> > > > No issue for me, everything ok except button or list
> > > 
> > > 
> > > wow, is there something wrong with my code?. the messages.upsert event is absolutely not working in my code
> > 
> > 
> > IDK For now messages.upsert is fine here
> 
> do you use typescript or javascript?

I am used javascript and getting same error.

**Comment by BoboiAzumi** [comment]
> > > > > No issue for me, everything ok except button or list
> > > > 
> > > > 
> > > > wow, is there something wrong with my code?. the messages.upsert event is absolutely not working in my code
> > > 
> > > 
> > > IDK For now messages.upsert is fine here
> > 
> > 
> > do you use typescript or javascript?
> 
> I am used javascript and getting same error.

is it working now ?.
I think, maybe there a code mistake in our code

**Comment by chiraglodariya** [comment]
> > > > > > No issue for me, everything ok except button or list
> > > > > 
> > > > > 
> > > > > wow, is there something wrong with my code?. the messages.upsert event is absolutely not working in my code
> > > > 
> > > > 
> > > > IDK For now messages.upsert is fine here
> > > 
> > > 
> > > do you use typescript or javascript?
> > 
> > 
> > I am used javascript and getting same error.
> 
> is it working now ?. I think, maybe there a code mistake in our code

Still not worked
