### ISSUE TITLE
A new type group invite url

### ISSUE THREAD

**Issue by zennn08** [adiwajshing/Baileys#2664]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature**
A new type of group invite url, "requests to join"
![Screenshot_2023_0326_090212](https://user-images.githubusercontent.com/75623219/227751292-49bcb319-8c64-4a3c-902b-c1efca8baee6.png)

I have tried using the `groupAcceptInvite`, but it returns error `upgrade-required`

![Screenshot_2023_0326_090935](https://user-images.githubusercontent.com/75623219/227751477-85d1d9cd-adab-4e99-8857-3815f3e1bcba.png)

**Comment by FaizBastomi** [comment]
At mine there was no error trying this function today,
try updating your baileys

<details open>
<summary><h3>Screenshot</h3></summary>
<p>

- Send query
![image](https://user-images.githubusercontent.com/64179402/228601068-fa4a175a-2ddc-4697-9f6b-1d8820fd11e3.png)
> the content is the same as in `groupAcceptInvite`, I rewrote it to be sure of the result

- Query result
![image](https://user-images.githubusercontent.com/64179402/228599701-0e28c388-8085-4db9-b54c-a79002033a52.png)

- Group event
![image](https://user-images.githubusercontent.com/64179402/228600488-860aa44d-66ba-469a-98ec-31b82c85b79d.jpg)
> The bot has automatically request to join the group

</p>
</details>

**Comment by zennn08** [comment]
this issue is solved after update WA version
