### ISSUE TITLE
How to identify the device of the person sending the massage

### ISSUE THREAD

**Issue by vihangayt0** [adiwajshing/Baileys#2665]
How to identify the device of the person sending the massage

**Comment by RavinduManoj** [comment]
```ts
var id = msg.key.id
var device = id.length > 21 ? "android" : id.substring(0, 2) === "3A"  ? "ios" : "web"

```

## msg identify from [here](https://github.com/adiwajshing/Baileys/blob/aef45e6755a78524aedf01868789feaf8853d912/Example/example.ts#L107)

**Comment by aidulcandra** [comment]
`import {getDevice} from "@adiwajshing/baileys"

// Input the message id
const device = getDevice(messageId)`

**Comment by vihangayt0** [comment]
> 

thanks bro ❤️

**Comment by vihangayt0** [comment]
thanks bro
