### ISSUE TITLE
[BUG]los botones no funcionan

### ISSUE THREAD

**Issue by bucaramarketing** [adiwajshing/Baileys#2666]
los botones aun no funcionan se arreglara o sera mejor no usarlos?

**Comment by justinrd** [comment]
Aparentemente ha sido intencional de parte de WhatsApp, no permiten su envío por el API, de momento la recomendación el usar texto plano, ya que ni botones ni listas

**Comment by makanSukros** [comment]
There are too many duplicate issues regarding this button, please read the issue thread regarding this button on a pre-existing issue

**Comment by alessandroanalistati** [comment]
> Aparentemente foi intencional por parte do WhatsApp, eles não permitem o envio pela API, no momento a recomendação é usar texto simples, pois nem botões nem listas

I DON'T THINK IT IS NOT BECAUSE IT WORKS ON SOME DEVICES

**Comment by igortrust** [comment]
#2615

**Comment by justinrd** [comment]
> > Aparentemente foi intencional por parte do WhatsApp, eles não permitem o envio pela API, no momento a recomendação é usar texto simples, pois nem botões nem listas
> 
> I DON'T THINK IT IS NOT BECAUSE IT WORKS ON SOME DEVICES

The reason for the failure is not on a specific device, it is on the versions of the application package. Example iPhone XR, whatsapp version 22.2.3.x does not work, but on the same iPhone we change the version and iPhone XR remains, whatsapp version 22.1.2.x on that one works.
We have carried out the tests on different brands, models and versions

**Comment by NowDev** [comment]
@bucaramarketing please close this issue, the community is already working on it on this issue:
- https://github.com/adiwajshing/Baileys/issues/2631

**Comment by bucaramarketing** [comment]
cerrado
