### ISSUE TITLE
How to catch this exception invalid_session and perform action 

### ISSUE THREAD

**Issue by hamzasgd1** [adiwajshing/Baileys#267]
UnhandledPromiseRejectionWarning: BaileysError: Unexpected error in login

**Comment by MaznAbdullah** [comment]
@hamzasgd1 
al-salam 3likom bro,

conn.on("close", async ({ reason, isReconnecting }) => {
    console.log(  "Disconnected because " + reason + ", reconnecting: " + isReconnecting );
    if (!isReconnecting && reason == "invalid_session") {
      if (fs.existsSync("./auth_info.json")) {
        fs.unlinkSync("./auth_info.json");
      }
      conn.clearAuthInfo();
    }
  });

**Comment by hamzasgd** [comment]
Wa elikum asslam @MaznAbdullah 

Your solution is only valid of connection is already made and then closed but what if I make a connections from existing auth info then hoe should I tackle this?

**Comment by itacirgabral** [comment]
catch is trick

![mateo](https://user-images.githubusercontent.com/6052177/101910465-59f00480-3b95-11eb-9ae6-0222b597e0ba.jpeg)
[Does the above code cause an unhandledRejection?](https://twitter.com/matteocollina/status/1266049120361381888)

Promises should be catched as soon as possible. 
```javascript
let err

const conn = await conn.connect().catch(e => {
  err = e
  return false
})

if (!conn) {
  console.error(err)
}
```
