### ISSUE TITLE
[BUG] Latest Update Whatsapp make message doesnt appear in mobile.

### ISSUE THREAD

**Issue by luthfifadle** [adiwajshing/Baileys#2670]
**Describe the bug**
Whatsapp not show the message when whatsapp latest update and just show on whatsapp web/desktop only.

**To Reproduce**
1.  Update the latest whatsapp

**Expected behavior**
Message doesnt appear in mobile, except Desktop and Web

**Environment (please complete the following information):**
 - Is this on a server? Yes
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
-

**Comment by makanSukros** [comment]
How come text and media messages appear, except for buttons and list messages

**Comment by makanSukros** [comment]
> How come text and media messages appear, except for buttons and list messages

and before creating a new thread, please read the previous thread regarding the button / list message issue

**Comment by vousmeevoyez** [comment]
@luthfifadle Try adding `markOnlineOnConnect `.

```
const sock = makeWASocket({
	version,
	printQRInTerminal: true,
	auth: state,
	msgRetryCounterMap,
	markOnlineOnConnect:false,
```

`Note: In the multi-device version of WhatsApp -- if a desktop client is active, WA doesn't send push notifications to the device. If you would like to receive said notifications -- mark your Baileys client offline using sock.sendPresenceUpdate('unavailable')`

**Comment by imReCoder** [comment]
anyone tried this ?

**Comment by hamidsaifi77** [comment]
> > anyone tried this ?
> 
> Yes, I did. It works correctly.

can you show an example of which code is working for you?
Thanks in advance

**Comment by hamidsaifi77** [comment]
> > > > anyone tried this ?
> > > 
> > > 
> > > Yes, I did. It works correctly.
> > 
> > 
> > can you show an example of which code is working for you? Thanks in advance
> 
> ```
> this.sock = makeWASocket({
>             version,
>             logger,
>             printQRInTerminal: true,
>             auth: {
>                 creds: state.creds,
>                 /** caching makes the store faster to send/recv messages */
>                 keys: makeCacheableSignalKeyStore(state.keys, logger),
>             },
>             // msgRetryCounterCache,
>             msgRetryCounterMap,
>             markOnlineOnConnect:false,
>             generateHighQualityLinkPreview: true,
>             // ignore all broadcast messages -- to receive the same
>             // comment the line below out
>             shouldIgnoreJid: jid => isJidBroadcast(jid),
>             // implement to handle retries & poll updates
>             getMessage,
>         })
> ```
> 
> I'm using **markOnlineOnConnect:false** in the makeWASocket declaration.

Thank you for your quick response.
check mine and correct if its wrong:-

 const sock = makeWASocket({
        auth: state,
        logger: pino({ level: "fatal" }),
        printQRInTerminal: true,
        // auth: {
        //     creds: state.creds,
        //     /** caching makes the store faster to send/recv messages */
        //     keys: makeCacheableSignalKeyStore(state.keys, logger),
        // },
        // msgRetryCounterCache,
        // msgRetryCounterMap,
        markOnlineOnConnect: false,
        generateHighQualityLinkPreview: true,
        // ignore all broadcast messages -- to receive the same
        // comment the line below out
        // shouldIgnoreJid: jid => isJidBroadcast(jid),
        // implement to handle retries & poll updates
        // getMessage,
    })


// sending message here
await sock.sendMessage(onwhatsapp[0]?.jid, buttonMessage)
await sock.sendPresenceUpdate('unavailable')

**Comment by makanSukros** [comment]
> 

button / message sending list appears with this parameter? I have tried and the button still does not appear

**Comment by ijerez2001** [comment]
> > > > > anyone tried this ?
> > > > 
> > > > 
> > > > Yes, I did. It works correctly.
> > > 
> > > 
> > > can you show an example of which code is working for you? Thanks in advance
> 
> ```
> const sock = makeWASocket({
>         auth: state,
>         logger: pino({ level: "fatal" }),
>         printQRInTerminal: true,
>         // auth: {
>         //     creds: state.creds,
>         //     /** caching makes the store faster to send/recv messages */
>         //     keys: makeCacheableSignalKeyStore(state.keys, logger),
>         // },
>         // msgRetryCounterCache,
>         // msgRetryCounterMap,
>         markOnlineOnConnect: false,
>         generateHighQualityLinkPreview: true,
>         // ignore all broadcast messages -- to receive the same
>         // comment the line below out
>         // shouldIgnoreJid: jid => isJidBroadcast(jid),
>         // implement to handle retries & poll updates
>         // getMessage,
>     })
> ```
> 
> > I'm using **markOnlineOnConnect:false** in the makeWASocket declaration.
> 
> Thank you for your quick response. check mine and correct if its wrong:-
> 
> ```
> const sock = makeWASocket({
>         auth: state,
>         logger: pino({ level: "fatal" }),
>         printQRInTerminal: true,
>         // auth: {
>         //     creds: state.creds,
>         //     /** caching makes the store faster to send/recv messages */
>         //     keys: makeCacheableSignalKeyStore(state.keys, logger),
>         // },
>         // msgRetryCounterCache,
>         // msgRetryCounterMap,
>         markOnlineOnConnect: false,
>         generateHighQualityLinkPreview: true,
>         // ignore all broadcast messages -- to receive the same
>         // comment the line below out
>         // shouldIgnoreJid: jid => isJidBroadcast(jid),
>         // implement to handle retries & poll updates
>         // getMessage,
>     })
> ```
> 
> ```
> 
> // sending message here
> await sock.sendMessage(onwhatsapp[0]?.jid, buttonMessage)
> await sock.sendPresenceUpdate('unavailable')
> ```

I don't use sendPresenceUpdate. Check if you call sendPresenceUpdate before sendMessage.
I've tried with text message.

**Comment by hamidsaifi77** [comment]
> 

Oh, the text message is working absolutely fine however I was talking about the button and list message.

**Comment by manoeuvrelawliet** [comment]
Me neither
