### ISSUE TITLE
MESSAGES WITH BUTTONS AND LISTS DON'T APPEAR? APPEARANCE ONLY WORKS ON OLDER MOBILE PHONES AND WHATSAPP WEB.

### ISSUE THREAD

**Issue by alessandroanalistati** [adiwajshing/Baileys#2671]
MESSAGES WITH BUTTONS AND LISTS DON'T APPEAR? APPEARANCE ONLY WORKS ON OLDER MOBILE PHONES AND WHATSAPP WEB.

WHEN THE PERSON ACCESS WHATSAP WEB THE BUTTONS AND LISTS APPEAR.

**Comment by makanSukros** [comment]
> MESSAGES WITH BUTTONS AND LISTS DON'T APPEAR? APPEARANCE ONLY WORKS ON OLDER MOBILE PHONES AND WHATSAPP WEB.
> 
> WHEN THE PERSON ACCESS WHATSAP WEB THE BUTTONS AND LISTS APPEAR.

Don't open the latest issue regarding this button / list message, please monitor the progress regarding this button / list message in the previous issue threads

**Comment by makanSukros** [comment]
See this #2631

**Comment by vikodk67** [comment]
> MESSAGES WITH BUTTONS AND LISTS DON'T APPEAR? APPEARANCE ONLY WORKS ON OLDER MOBILE PHONES AND WHATSAPP WEB.
> 
> WHEN THE PERSON ACCESS WHATSAP WEB THE BUTTONS AND LISTS APPEAR.

Maybe we should unite, tackle this problem, try experimenting. Don't be afraid of errors😭😔

**Comment by makanSukros** [comment]
> Maybe we should unite, tackle this problem, try experimenting. Don't be afraid of errors😭😔

That's right, don't just get angry, let's experiment with each other so that this problem has a bright spot

**Comment by sostenesapollo** [comment]
Any update ?

**Comment by alessandroanalistati** [comment]
> AS MENSAGENS COM BOTÕES E LISTAS NÃO APARECEM? APARÊNCIA SÓ FUNCIONA EM CELULARES MAIS ANTIGOS E WHATSAPP WEB.
> 
> QUANDO A PESSOA ACESSA O WHATSAP WEB APARECEM OS BOTÕES E AS LISTAS.

**Comment by alessandroanalistati** [comment]
there is another speech in another tick

**Comment by gigantiumweb** [comment]
Working buttons messages
https://wa.me/6285811500888

**Comment by manoeuvrelawliet** [comment]
#2670

**Comment by IanosJunior** [comment]
+1

**Comment by guiireal** [comment]
Guys, stop opening the same types of issues. There are already plenty of similar issues, so please be more careful and attentive to this. Monitor the open issues when the subject is the same!

**Comment by ReyEndymion** [comment]
A solution is proposed in the https://github.com/BrunoSobrino/Baileys... repository to see if adiwajshing and his team take it into account to correct it in recent versions of WhatsApp

**Comment by alessandroanalistati** [comment]
Resolvendo em outra edição.
