### ISSUE TITLE
How i can fix this in terminal

### ISSUE THREAD

**Issue by codemakesense07** [adiwajshing/Baileys#2676]
`{"level":40,"time":"2023-03-31T01:02:50.728Z","pid":7324,"hostname":"LAPTOP-71IK`
25K5","stack":"Error: mutex start\n    at C:\\Users\\Acer\\Desktop\\KODING WASEN
DER 2\\Baileys\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:1
5:31\n    at Object.mutex (C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\
\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:35:15)\n    at h
andleMessage (C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules
\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:451:29)\n    at execTask
(C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules\\@adiwajshin
g\\baileys\\lib\\Socket\\messages-recv.js:554:20)\n    at processNodeWithBuffer
(C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules\\@adiwajshin
g\\baileys\\lib\\Socket\\messages-recv.js:551:15)\n    at WebSocket.<anonymous>
(C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules\\@adiwajshin
g\\baileys\\lib\\Socket\\messages-recv.js:560:9)\n    at WebSocket.emit (node:ev
ents:527:28)\n    at C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_
modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:222:35\n    at Object.dec
odeFrame (C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules\\@a
diwajshing\\baileys\\lib\\Utils\\noise-handler.js:131:17)\n    at WebSocket.onMe
ssageRecieved (C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_module
s\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:198:15)\n    at WebSocket.emit
(node:events:527:28)\n    at Receiver.receiverOnMessage (C:\\Users\\Acer\\Deskto
p\\KODING WASENDER 2\\Baileys\\node_modules\\ws\\lib\\websocket.js:1184:20)\n
 at Receiver.emit (node:events:527:28)\n    at Receiver.dataMessage (C:\\Users\\
Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules\\ws\\lib\\receiver.js:52
6:14)\n    at Receiver.getData (C:\\Users\\Acer\\Desktop\\KODING WASENDER 2\\Bai
leys\\node_modules\\ws\\lib\\receiver.js:459:17)\n    at Receiver.startLoop (C:\
\Users\\Acer\\Desktop\\KODING WASENDER 2\\Baileys\\node_modules\\ws\\lib\\receiv
er.js:158:22)","waitOver":true,"msg":"possible mutex deadlock"}``

**Comment by FaizBastomi** [comment]
Previously it was a hardcoded logger that adiwajshing added, but due to too much spam it was finally removed in the following commit https://github.com/adiwajshing/Baileys/commit/0d53fbe7fae5164f8bf90b9ede2dc08724898d7c. If you are using the npm version, it is recommended to install this baileys github version

**Comment by Aidils60** [comment]
![IMG-20230331-WA0636](https://user-images.githubusercontent.com/38816724/229100528-0d6792c3-cef2-4427-ba1c-4c934e584086.jpeg)
how to fix this 🥺

**Comment by altemirjosecoelho** [comment]
+1
