### ISSUE TITLE
[BUG]  throw new Constants_1.BaileysError(Constants_1.DisconnectReason.close

### ISSUE THREAD

**Issue by hasanbasri1993** [adiwajshing/Baileys#268]
**Describe the bug**
 throw new Constants_1.BaileysError(Constants_1.DisconnectReason.close

**To Reproduce**
1. scan qrcode if there a chat list, if i remove remove chat working
**Expected behavior**

**Environment (please complete the following information):**
- mac
- node -v v15.3.0

**Additional context**

![Image of Yaktocat](https://i.ibb.co/crWwmW3/Screenshot-at-Dec-11-23-36-45.png)

**Comment by ycarooliveira** [comment]
Show your code pls

**Comment by hasanbasri1993** [comment]
import { WAConnection} from '@adiwajshing/baileys'
import * as fs from "fs";
import terminal from "qrcode-terminal";

async function connectToWhatsApp() {
    const conn = new WAConnection()


    conn.on('qr', qr => {
        terminal.generate(qr, {small: true});
        console.log(qr);
        // Now, use the 'qr' string to display in QR UI or send somewhere
    })

    conn.on ('credentials-updated', () => {
        // save credentials whenever updated
        console.log (`credentials updated!`)
        const authInfo = conn.base64EncodedAuthInfo() // get all the auth info we need to restore this session
        fs.writeFileSync('./auth_info.json', JSON.stringify(authInfo, null, '\t')) // save this info to a file
    })

    conn.loadAuthInfo ('./auth_info.json') // will load JSON credentials from file
    // called when WA sends chats
    // this can take up to a few minutes if you have thousands of chats!
    conn.on('chats-received', async ({hasNewChats}) => {
        console.log(`you have ${conn.chats.length} chats, new chats available: ${hasNewChats}`)

        const unread = await conn.loadAllUnreadMessages()
        console.log("you have " + unread.length + " unread messages")
    })
    // called when WA sends chats
    // this can take up to a few minutes if you have thousands of contacts!
    conn.on('contacts-received', () => {
        console.log('you have ' + Object.keys(conn.contacts).length + ' contacts')
    })

    // loads the auth file credentials if present
    await conn.connect()
    conn.on('chat-update', chatUpdate => {
        // `chatUpdate` is a partial object, containing the updated properties of the chat
        // received a new message
        if (chatUpdate.messages && chatUpdate.count) {
            const message = chatUpdate.messages.all()[0]
            console.log(message)
        } else console.log(chatUpdate) // see updates (can be archived, pinned etc.)
    })
}

// run in main file
connectToWhatsApp()
    .catch(err => console.log("unexpected error: " + err)) // catch any errors

**Comment by ycarooliveira** [comment]
you dont need to do this => `terminal.generate(qr, {small: true});` Baileys already do for you. I can't see where you error comes from, can you show your entire code? put your code on git so I can run over here and see what could have happen. You could join Discord [here](https://discord.gg/7FYURJyqng) as well.

**Comment by hasanbasri1993** [comment]
ok thanks.. solve d
