### ISSUE TITLE
SessionError: No sessions [BUG]

### ISSUE THREAD

**Issue by SafwanGanz** [adiwajshing/Baileys#2688]
SessionError: No sessions                                                       at Object.91701xxxxxxx:39.0 [as awaitable] (/root/bot_v2/node_modules/libsignal/src/session_cipher.js:69:15)                                     at _asyncQueueExecutor (/root/bot_v2/node_modules/libsignal/src/queue_job.js:19:21)

How to fix

**Comment by BrunoSobrino** [comment]
+1

**Comment by 4relial** [comment]
+1

**Comment by marcelcamargo** [comment]
+1

**Comment by SafwanGanz** [comment]
> +1

Fixed bro. Use Latest version baileys
Update package like:
"adiwajshing/baileys": "github:adiwajshing/baileys"
