### ISSUE TITLE
How to get message ID after SendMessage

### ISSUE THREAD

**Issue by dammah** [adiwajshing/Baileys#2692]
Hello, can I get the message ID after sending the message with the SendMeesage function??

**Comment by ravindu01manoj** [comment]
```ts
const msg  = await sock.sendMessage(jid, { text: 'oh hello there' })
console.log(msg.key.id)
```

**Comment by codemakesense07** [comment]
Anyone can fix this ? : C:\Users\Acer\Desktop\KODING WASENDER 2\Baileys\app.js:169
                const pesan = messages[0].message.conversation;
                                                  ^

TypeError: Cannot read properties of undefined (reading 'convers
ation')

**Comment by aidulcandra** [comment]
@codemakesense07 
const pesan = messages[0]?.message.conversation

Isi variabel "pesan" bisa saja undefined. Perlu dicek dengan if (pesan)

**Comment by ravindu01manoj** [comment]
> Anyone can fix this ? : C:\Users\Acer\Desktop\KODING WASENDER 2\Baileys\app.js:169 const pesan = messages[0].message.conversation; ^
> 
> TypeError: Cannot read properties of undefined (reading 'convers ation')

```ts
   if(upsert.type === 'notify') {
         const pesan = messages[0]?.message?.conversation
        // continue code...
    }
```
