### ISSUE TITLE
Ternyata penerusku banyak ya. Semoga kalian sukses menjadi programer.

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#2702]
kata orang sebelah, saya itu tolol (goblog).

<details>
 <summary>Klik disini</summary>

 ![IMG-20230407-WA0578](https://user-images.githubusercontent.com/80396521/230504284-187830f1-03e3-432a-814f-b21a5114ee02.jpg)

</details>

**Comment by wiraardy** [comment]
hadeh

**Comment by nugraizy** [comment]
this is beyond useless.

**Comment by TobyG74** [comment]
??? what does it mean.

**Comment by dhyZx** [comment]
why¿

**Comment by bolaxd** [comment]
> kata orang sebelah, saya itu tolol.

apa yng di harapkan di issue ini

**Comment by xfar05** [comment]
???

**Comment by Zobin33** [comment]
Frmdev Siapa Dah ngeselin

**Comment by WahyuPR0** [comment]
Bjir bat

**Comment by Ichizza** [comment]
????

**Comment by WahyuPR0** [comment]
Lmao

**Comment by ImYanXiao** [comment]
> kata orang sebelah, saya itu tolol.

Bang Udah Bang🗿

**Comment by edot92** [comment]
lanjut brok

**Comment by manoeuvrelawliet** [comment]
Here again someone from wkwkwk land

**Comment by frmdeveloper** [comment]
> **bolaxd**
> apa yng di harapkan di issue ini

Saya berharap, semua orang bisa menjadi yang terbaik

**Comment by frmdeveloper** [comment]
> @TobyG74
> ??? what does it mean.

the person next door said I was stupid

**Comment by frmdeveloper** [comment]
> @Zobin33
> Frmdev Siapa Dah ngeselin

Maaf deh

**Comment by frmdeveloper** [comment]
> @ImYanXiao
> Bang Udah Bang🗿

😭

**Comment by SanzGanzs** [comment]
why bro🗿

**Comment by fdvky1** [comment]
?

**Comment by SkylarKaf** [comment]
Jan disini napa

**Comment by natxdixie** [comment]
apcb??

**Comment by SayuLont** [comment]
> kata orang sebelah, saya itu tolol (goblog).
> 
> Klik disini
> ![IMG-20230407-WA0578](https://user-images.githubusercontent.com/80396521/230504284-187830f1-03e3-432a-814f-b21a5114ee02.jpg)

Luwh sp?

**Comment by banguncode** [comment]
> kata orang sebelah, saya itu tolol (goblog).
> 
> Klik disini

want to look pro, right? ohhh man...

**Comment by 4relial** [comment]
malu sendiri ane liatnya

**Comment by aidulcandra** [comment]
bruh masalah pribadi di bawa2

**Comment by amiruldev20** [comment]
hdeh

**Comment by Aidils60** [comment]
memalukan..
who do you think you are?

**Comment by WahyuPR0** [comment]
Wareg drama

**Comment by banguncode** [comment]
> kata orang sebelah, saya itu tolol (goblog).
> 
> Klik disini
> ![IMG-20230407-WA0578](https://user-images.githubusercontent.com/80396521/230504284-187830f1-03e3-432a-814f-b21a5114ee02.jpg)

Tolong issue ini dihapus (bukan di-close). Memalukan, norak, kampungan. Pro boleh, goblok jangan... jgn malu2in org Indo lah. Masa kalah sama prindavan?!

**Comment by banguncode** [comment]
> kata orang sebelah, saya itu tolol (goblog).
> 
> Klik disini

Tolong issue ini dihapus (bukan di-close). Memalukan, norak, kampungan. Pro boleh, goblok jangan... jgn malu2in org Indo lah. Masa kalah sama prindavan?!

**Comment by TobyG74** [comment]
> > @TobyG74
> > ??? what does it mean.
> 
> the person next door said I was stupid

Cringe. Useless.

**Comment by dio-azhrii** [comment]
norak

**Comment by wiraardy** [comment]
> > > @TobyG74
> > > ??? what does it mean.
> > 
> > 
> > the person next door said I was stupid
> 
> Cringe. Useless.

looks like he needs more attention

**Comment by frmdeveloper** [comment]
Alhamdulillah
