### ISSUE TITLE
BUG OWNER on the iphone forclose

### ISSUE THREAD

**Issue by fahmiarisma** [adiwajshing/Baileys#2707]
// send a contact!
const vcard = 'BEGIN:VCARD\n' // metadata of the contact card
            + 'VERSION:3.0\n' 
            + 'FN:Jeff Singh\n' // full name
            + 'ORG:Ashoka Uni;\n' // the organization of the contact
            + 'TEL;type=CELL;type=VOICE;waid=911234567890:+91 12345 67890\n' // WhatsApp ID + phone number
            + 'END:VCARD'
const sentMsg  = await sock.sendMessage(
    id,
    { 
        contacts: { 
            displayName: 'Jeff', 
            contacts: [{ vcard }] 
        }
    }
)

on the iphone forclose

**Comment by Gimenz** [comment]
yep, i have facing same issue too :(
