### ISSUE TITLE
Externaladreply not adding.

### ISSUE THREAD

**Issue by vihangayt0** [adiwajshing/Baileys#2708]
Externaladreply not adding.

please help me for fix that...

code :

conn.sendMessage(from, {text: 'teks', contextInfo:{"externalAdReply": {"title": 'rr', "body": 'f', "mediaType": 3,"thumbnail": fs.readFileSync('./media/astro.jpg')}}}, {sendEphemeral: true, quoted: mek })

**Comment by Ajayos** [comment]
use @amiruldev20 s baileys

sock.sendMessage(jid, {
text: hellow,
contextInfo: {
externalAdReply: {
title: 'hello',
body: 'body',
thumbnailUrl: 'url.com',
sourceUrl:'google.com'
}}}
