### ISSUE TITLE
Error in uploading to media-lax3-1.cdn.whatsapp.net, 

### ISSUE THREAD

**Issue by lvvy** [adiwajshing/Baileys#275]
ERROR    [2020-12-14 07:41:14.449 +0000] (13812): Error in uploading to media-lax3-1.cdn.whatsapp.net, retrying...
    class: "Baileys"
ERROR    [2020-12-14 07:41:35.481 +0000] (13812): Error in uploading to mmg.whatsapp.net
    class: "Baileys"

**Comment by lvvy** [comment]
uploadAgent ...

**Comment by textarea** [comment]
I have this error too, what does it mean "uploadAgent..." ?

**Comment by lvvy** [comment]
> 我也有这个错误，“uploadAgent...”是什么意思？@lvvy

	client.connectOptions.agent = ProxyAgent ('http://127.0.0.1:10809')
	
![Uploading QQ截图20210805163220.png…]()
client.connectOptions.fetchAgent = ProxyAgent ('http://127.0.0.1:10809')

**Comment by textarea** [comment]
thank you, does "ProxyAgent" is this https://www.npmjs.com/package/proxy-agent ?

**Comment by lvvy** [comment]
> 谢谢，“ProxyAgent”是这个https://www.npmjs.com/package/proxy-agent吗？
直接从@adiwajshing/baileys引入的：

import {ProxyAgent} from '@adiwajshing/baileys

**Comment by textarea** [comment]
Hero

**Comment by lvvy** [comment]
> But it doesn't works for me: connect ECONNREFUSED 127.0.0.1:10809

127.0.0.1:10809  Change to your agent address

**Comment by textarea** [comment]
I never had an agent address, can you suggest any documentation how to build one?
