### ISSUE TITLE
loop in waiting for chats & contacts

### ISSUE THREAD

**Issue by JuniorRibas** [adiwajshing/Baileys#28]
![image](https://user-images.githubusercontent.com/34239187/83357307-05481300-a342-11ea-8eb1-973ca8806797.png)

Apparently it is happening directly.

Every connection does not end authentication, and stays in that loop and never ends the connection.

Is there a cache that I should clear?

**Comment by adiwajshing** [comment]
No, there is no cache to clear. Are you using a fresh account? An account with no chats?

**Comment by JuniorRibas** [comment]
The account exists conversations.

What happens that sometimes it doesn’t connect, then out of nowhere it works again
Very strange.

Does this just happen to me? hahahaha

**Comment by adiwajshing** [comment]
Try removing the timeout and see what happens?

**Comment by JuniorRibas** [comment]
![image](https://user-images.githubusercontent.com/34239187/83462148-d6fd2d00-a440-11ea-8956-4d14201b2fae.png)


I commented all the part of the code that sought the contacts

There it worked .....

**Comment by adiwajshing** [comment]
This should not happen. However, this issue should be fixed in the latest version. Do check it out and lemme know.

**Comment by adiwajshing** [comment]
Assuming the issue is resolved, closing.
