### ISSUE TITLE
How a client can download media/zip/pdf/video/ without saving on Server?

### ISSUE THREAD

**Issue by athar21200** [adiwajshing/Baileys#280]
Is it possible play or download video without saving on server? I mean peer to peer play?

Similarly download zip/pdf directly without saving on server?

My current approach is first file will be saved on server and then it will generate a download link but i want to make it direct buffer download instead of saving on server first.

Thank you!

**Comment by adiwajshing** [comment]
You'll have to implement the decryption on the client side, you can stream it directly then.

**Comment by athar21200** [comment]
> You'll have to implement the decryption on the client side, you can stream it directly then.

How to do that?
