### ISSUE TITLE
How to send extendedTextMessage or Quoted Message or Reply?

### ISSUE THREAD

**Issue by hamzasgd1** [adiwajshing/Baileys#283]
I can see message type extendedTextMessage with these option
quoted: quotedMessage, // the message you want to quote
contextInfo: { forwardingScore: 2, isForwarded: true }

but how to send sent it what's this quotedMessage object?

**Comment by adiwajshing** [comment]
Have you seen the [example script](https://github.com/adiwajshing/Baileys/blob/523f0341ed9b4958fd06a604075f2fe754942386/Example/example.ts#L114) linked in the readme?

**Comment by hamzasgd1** [comment]
Yes thanks.
