### ISSUE TITLE
[HELP] can you explain what is waitForMessage function?

### ISSUE THREAD

**Issue by ItzNgga** [adiwajshing/Baileys#287]
Im interested with this and i think its similar with discordjs wait message

https://adiwajshing.github.io/Baileys/classes/_src_waconnection_0_base_.waconnection.html#waitformessage

**Comment by fdciabdul** [comment]
it's like when somene typing or recording the message , have you read the readme ?

**Comment by ItzNgga** [comment]
> it's like when somene typing or recording the message , have you read the readme ?

there's no documentaion about that

**Comment by adiwajshing** [comment]
@ItzNgga it's an internal function to wait for a message with a specific tag. It is used for queries from the WA server very often. If you search for its usage throughout the library  -- in the base & validation especially -- I believe the function will be clearer.

**Comment by ItzNgga** [comment]
@adiwajshing thanks for your help,
