### ISSUE TITLE
 how to make a custom reply

### ISSUE THREAD

**Issue by irf5455** [adiwajshing/Baileys#288]
like we replied to him but he didn't type anything

**Comment by fdciabdul** [comment]
```javascript

conn.sendMessage("62896xxxxx@s.whatsapp.net", " this is message" , "MessageType.text")
```

you can use schedule message for it

**Comment by fdciabdul** [comment]
> ```js
> conn.sendMessage("62896xxxxx@s.whatsapp.net", " this is message" , MessageType.text)
> ```
> 
> you can use schedule message for it

**Comment by kikiixyz** [comment]
Dah jadi ngab:v
Gw Buat sendiri

**Comment by MFarelS** [comment]
> Dah jadi ngab:v
> Gw Buat sendiri

Bagi stahhh

**Comment by EmanSaputra** [comment]
> Dah jadi ngab:v
> Gw Buat sendiri

Buktinya Mana?, Tanpa Bukti = gak percaya:v

**Comment by ItzNgga** [comment]
custom reply easy, reply nya gambar bkp aja an

**Comment by Nurutomo** [comment]
```js
function fakeReply(jid, text = '', fakeJid = this.user.jid, fakeText = '', fakeGroupJid) {
   return conn.sendMessage(jid, text, MessageType.extendedText, { key: { fromMe: fakeJid == this.user.jid, participant: fakeJid, ...(fakeGroupJid ? { remoteJid: fakeGroupJid } : {}) }, message: { conversation: fakeText }})
}
```

https://github.com/Nurutomo/wabot-aq/blob/bdeeaa834b3da6b47e768d522647405d2a311fd2/lib/simple.js#L38

**Comment by kikiixyz** [comment]
> Buktinya Mana?, Tanpa Bukti = gak percaya:v
Yaelah ngab
