### ISSUE TITLE
how block calling contact

### ISSUE THREAD

**Issue by justinthoms** [adiwajshing/Baileys#289]
Too many users are calling need to block after miss call
WhatsApp can get miss call history

**Comment by adiwajshing** [comment]
[Here](https://github.com/adiwajshing/Baileys/blob/bc3cb6c178211988c74f5b3203504d0c4c074c32/src/WAConnection/5.User.ts#L174) you go

**Comment by hasanbasri1993** [comment]
how to get id who is calling ?
