### ISSUE TITLE
[BUG] New number timed out

### ISSUE THREAD

**Issue by randhipp** [adiwajshing/Baileys#290]
**Describe the bug**

![image](https://user-images.githubusercontent.com/25372728/103011616-ce02b300-456c-11eb-94b8-fbfa00e6f003.png)

**Right Image** 
new number -> succesfully scan, but failed to connect, always timed out. Receive working. Send not working.
old number -> scan success, can send and receive message.

**Left Image**
this issue not happen in old commit github:adiwajshing/baileys#ba8b8c693a712be962d5e5a760ddd5cf42a57d30 

**To Reproduce**
1. using "github:adiwajshing/baileys" at package.json
2. use brand new number

**Expected behavior**
New number can send and receive message like in the old commit.

**Environment (please complete the following information):**
 - Is this on a server? yes
 - What do your `connectOptions` look like? 
```
conn.connectOptions = {
        /** New QR generation interval, set to null if you don't want to regenerate */
        regenerateQRIntervalMs: 10000,
        /** fails the connection if no data is received for X seconds */
        maxIdleTimeMs: 60000,
        /** maximum attempts to connect */
        maxRetries: 10,
        /** should the chats be waited for;
         * should generally keep this as true, unless you only care about sending & receiving new messages
         * & don't care about chat history
         * */
        waitForChats: true,
        /** if set to true, the connect only waits for the last message of the chat
         * setting to false, generally yields a faster connect
         */
        waitOnlyForLastMessage: false,
        /** max time for the phone to respond to a connectivity test */
        phoneResponseTime: 10000,
        /** minimum time between new connections */
        connectCooldownMs: 5000,
        /** agent used for WS connections (could be a proxy agent) */
        agent: undefined,
        /** agent used for fetch requests -- uploading/downloading media */
        fetchAgent: undefined,
        /** always uses takeover for connecting */
        alwaysUseTakeover: true
    }
``` 
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? no

**Additional context**
Already tried new device, new number, LTE and WIFI connection. but still same issue happen in latest commit.

**Comment by adiwajshing** [comment]
Can you attach the full logs please?
Also, try setting waitForChats to false
