### ISSUE TITLE
ffmpeg: command not found on sending video

### ISSUE THREAD

**Issue by hamzasgd1** [adiwajshing/Baileys#291]
could not generate video thumb: Error: Command failed: ffmpeg -ss 00:00:00 -i ./7facef2438.mp4 -y -s 48x48 -vframes 1 -f image2 ./7facef2438.mp4.jpg
/bin/sh: ffmpeg: command not found

**Comment by fdciabdul** [comment]
this is not feom baileys itself , show your code 

maybe you tried to call ffmpeg without exec right ?

**Comment by Nurutomo** [comment]
Try installing ffmpeg on your device
`apt install ffmpeg`

**Comment by hasanbasri1993** [comment]
if use heroku add this package https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
