### ISSUE TITLE
this.isZero is not a fucntion

### ISSUE THREAD

**Issue by hamzasgd1** [adiwajshing/Baileys#293]
While sending all the document messages receiving this error but messages are sending fine.
using this code

 const mediaBlob = fs.readFileSync(`./tmp/uploads/code.pdf`)
conn.sendMessage(jid, mediaBlob, MessageType.document, {
            filename: code.zip,
            mimetype: Mimetype.zip,
})

output after sending

{
  url: 'https://mmg.whatsapp.net/d/f/ArpfXf0jjgLi9aigJM6555VY48SYFMC14ssdUyWYY2bNdmEMQDdk.enc',
  mimetype: 'application/zip',
  title: 'code.zip',
  fileSha256: 'TFV3DzMcpLiQsdHD/jogHouqs9dsdsbksfXGGKSVDQ4lO8DM=',
  fileLength: '31385',
  pageCount: 0,
  mediaKey: 'SuyFRRsgU/mRIpjP9whresdsdJgqc/Jamu9aogcHD9ZiRIU=',
  fileName: 'code.zip',
  fileEncSha256: 'QWeSNS+u/hPf/sJ5C+Luu/6QaErS7Ajdsds5xB+mXUUT/x0=',
  directPath: '/v/t62.7119-24/40892sdsds746_3d374172739346727_5662870094236613793_n.enc?oh=b98ccd0d6bf792a3d4dsdscd9939ca9b5352e&oe=601146AD',
  mediaKeyTimestamp: '1609070418'
}
(node:7090) UnhandledPromiseRejectionWarning: TypeError: this.isZero is not a function
    at String.toString (/www/wwwroot/ab/node_modules/long/src/long.js:474:14)
    at Function.toObject (/www/wwwroot/ab/node_modules/@adiwajshing/baileys/WAMessage/WAMessage.js:11771:98)

**Comment by adiwajshing** [comment]
Updating to v3.4.1 should fix this

**Comment by hamzasgd1** [comment]
> Updating to v3.4.1 should fix this

Error is still the same after updating.

**Comment by adiwajshing** [comment]
1. Delete node_modules
2. Delete yarn lock

Check after that, if doesn't work then show your full code.

**Comment by hamzasgd1** [comment]
Okay
