### ISSUE TITLE
How To Access Whatsapp Web

### ISSUE THREAD

**Issue by albertstyles312** [adiwajshing/Baileys#296]
if i run bot, i can open whatsapp web

**Comment by adiwajshing** [comment]
Yes

**Comment by Quiec** [comment]
> Yes
> […](#)
> On 28-Dec-2020, at 8:06 PM, albertstyles312 ***@***.***> wrote: ﻿ if i run bot, i can open whatsapp web — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

How?

**Comment by adiwajshing** [comment]
By disconnecting the bot

**Comment by UnKnoWn-Consortium** [comment]
This library is leveraging the private WebSocket interfaces for Whatsapp Web. So restrictions for WhatsApp Web (e.g. only one client allowed at the same time) also apply to this library.
