### ISSUE TITLE
İphone Users

### ISSUE THREAD

**Issue by omerbeylife** [adiwajshing/Baileys#297]
Hello, audio files, google voices do not work on iphone users

**Comment by adiwajshing** [comment]
Need more info than this.

**Comment by omerbeylife** [comment]
There is such a plug-in but iPhone users cannot play bot sounds. The problem is caused by bailley. 
https://www.github.com/Quiec/WhatsAsena/tree/master/plugins/scrapers.js

**Comment by Quiec** [comment]
The sounds sent by Baileys are not listen on the iPhone.

Any suggestions?

**Comment by edgardmessias** [comment]
Try this: `ffmpeg -i audio.mp3 -vn -ar 44100 -ac 2 -b:a 192k audio-fixed.mp3 -y`

**Comment by Quiec** [comment]
> Try this: `ffmpeg -i audio.mp3 -vn -ar 44100 -ac 2 -b:a 192k audio-fixed.mp3 -y`

Thanks!

**Comment by Romerio** [comment]
For me it only worked after adding "-f ipod"
`ffmpeg -i audio.mp3 -vn -ab 128k -ar 44100 -f ipod audio-fixed.mp3 -y`
