### ISSUE TITLE
Which event is fired when we send a message?

### ISSUE THREAD

**Issue by cryptosalomao** [adiwajshing/Baileys#30]
Hi, nice library!

I'm using this library on a personal project, and i would like to know which event is fired when we send a message to someone or to a group from the cellphone, not from the library itself. Thanks.

**Comment by adiwajshing** [comment]
Glad you like it. You can register a custom callback to get notified of when new messages are sent:

``` javascript
// receive all new messages
client.registerCallback (["action", "add:relay", "message"], json => {
    const message = json[2][0][2]
    console.log (`Message sent by me: ${message.key.fromMe}`)
    // do something here
})

```

This replaces the `setOnUnreadMessage` callback, so you'll have to handle incoming unread messages here too.

**Comment by adiwajshing** [comment]
Since it seems to be resolved, closing.
