### ISSUE TITLE
how to make watermark on sticker

### ISSUE THREAD

**Issue by BerTren-Nation** [adiwajshing/Baileys#301]
`this is an example of how to make it?`
![IMG_20210103_173034](https://user-images.githubusercontent.com/72166971/103476717-c05df080-4dea-11eb-8cc8-09ae61086abe.jpg)

**Comment by Alphakingg-ai** [comment]
masih menunggu:v

**Comment by MRHRTZ** [comment]
![Screenshot_2021-01-07-08-57-55-291_com gbwhatsapp](https://user-images.githubusercontent.com/52845610/103841624-93e5f500-50c6-11eb-847d-2ac6e1db10de.jpg)

Its using exif file and libwebp

**Comment by lxndr-rl** [comment]
> ![Screenshot_2021-01-07-08-57-55-291_com gbwhatsapp](https://user-images.githubusercontent.com/52845610/103841624-93e5f500-50c6-11eb-847d-2ac6e1db10de.jpg)
> 
> Its using exif file and libwebp

can you provide an example?

**Comment by BerTren-Nation** [comment]
> > Its using exif file and libwebp
> 
> can you provide an example?

webpmux -set exif file.exif inputfile.webp -o outfile.webp
`You Need Create Exif File first`
