### ISSUE TITLE
[BUG] When sending a media message with buffer the RSS memory grows a lot and after the message is sent it doesn't give back all of the memory used

### ISSUE THREAD

**Issue by caiquejjx** [adiwajshing/Baileys#302]
**Describe the bug**
While trying to send video messages the bigger the video more memory is used to send it, but after the message is sent only a small part of the memory is given back, a lot still retained.

**To Reproduce**
use the conn.sendMessage method to send a media message, the bigger the buffer more noticeable it is.

**Expected behavior**
Expected the memory to grow while sending the message but returning to normal after sending it.

**Additional context**
 In my case I tried to send an 89MB video, at first the memory went from 62MB to 403MB after sending the video it decreased to 371MB

**Comment by caiquejjx** [comment]
@adiwajshing anything on this topic?

**Comment by adiwajshing** [comment]
Haven't had a chance to debug this yet @caiquejjx. My guess is that it might have to do with fetch, is it possible for you to write a test for this?

**Comment by caiquejjx** [comment]
I tried but unsucessfull, gonna wait someone or you to debug it

**Comment by adiwajshing** [comment]
@caiquejjx @luisxciv I've switched the http library from `node-fetch` to `got` & added the ability to use streams for sending media. See [here](https://github.com/adiwajshing/Baileys#media-messages) for docs. Let me know if that works for you.

Right now, these features are only available on the master branch.

**Comment by canove** [comment]
I noticed the same using `downloadMediaMessage`, the memory used by my node app grows the size of downloaded media and is not garbage collected.

I'll give a try to master branch version and post the results here.

**Comment by canove** [comment]
Same occur with stabl-ish version. Opened a new issue https://github.com/adiwajshing/Baileys/issues/343
