### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ASLKiRa** [adiwajshing/Baileys#306]
Oops, I have a question what would be the parameter to automatically know the id of a person marked in a group?

![images.jpg](https://user-images.githubusercontent.com/63880084/103778417-fa104080-5010-11eb-9ada-47959757f071.jpg)

**Comment by adiwajshing** [comment]
Not sure what you mean

**Comment by ASLKiRa** [comment]
@adiwajshing



For example, to know the id of the person who sent a message, use the parameter (m.key.remoteJid), now in a group for example, how do I get the id of a person I mentioned using @ ?, For example to add a command to give to an administrator person, I would give a specific command by (m.message.conversation.startsWith ("/ adm"), and soon after I would mark the person I want to give administrator in the group,

In an example in the "/ adm @example " group

**Comment by itacirgabral** [comment]
event = chat-update
message:
```json
{
  "jid":"grupoxyz@g.us",
  "messages":[
    {
      "key": {
        "remoteJid":"grupoxyz@g.us",
      },
      "message": {
        "extendedTextMessage": {
          "text":"@556500000000 oi você",
          "previewType":"NONE",
          "contextInfo": {
            "mentionedJid": ["556500000000@s.whatsapp.net"]
          }
        }
      }
    }
  ]
}
```

you can setup the log level to `trace`, everything you do on mobile will be logged on terminal to you learn what is going on.

**Comment by itacirgabral** [comment]
I would like to suggest you use the reply pattern. You can reply to someone's message with `🔝` to make him an admin.

**Comment by ASLKiRa** [comment]
@itacirgabral
@adiwajshing

Got it, I was thinking of using (conn.groupMakeAdmin), wouldn't it work with it?

![Screenshot_20210107-225023.png](https://user-images.githubusercontent.com/63880084/103964697-d1846580-513a-11eb-9be4-6918f751d761.png)

**Comment by ASLKiRa** [comment]
```
} else if ( m.message.conversation &&
m.message.conversation.startsWith("/adm")) 

{ conn.groupMakeAdmin(m.key.mentionedJid, ' you are admin', MessageType.text } 
```_

**Comment by ASLKiRa** [comment]
@itacirgabral @adiwajshing


In theory it would be like this, but it didn’t work that way, I’m programming by cell phone (termux), it’s kind of hard to make it work, but with a help I can certainly

**Comment by ASLKiRa** [comment]
@itacirgabral

Vi q vc mora no Brasil, vc fala português?


Do you speak portuguese?

**Comment by adiwajshing** [comment]
@ASLKiRa you can use `groupMakeAdmin` -- it should work fine. You can use some test vectors to make sure you're retrieving the right values from the message.

**Comment by ASLKiRa** [comment]
@adiwajshing


I understand, but how exactly can I do it, I still don't understand much about programming, if you can make me available some study material it would be good

**Comment by ASLKiRa** [comment]
@itacirgabral @adiwajshing
