### ISSUE TITLE
Messages are sent many times when the phone is reconnected

### ISSUE THREAD

**Issue by ajeelias** [adiwajshing/Baileys#307]
Hi!

If I send a message or many messages, and the phone (connected to whatsapp) is turned off, Baley's library tries to send repeatedly, and when the phone turned on and it connects to whatsapp again, many of the same messages are sent. How can I control it?

Thanks!

**Comment by adiwajshing** [comment]
Please show your code

**Comment by ajeelias** [comment]
![imagen](https://user-images.githubusercontent.com/15612750/104111281-f86ba480-52be-11eb-98c0-4ca85b73e8e4.png)
![imagen](https://user-images.githubusercontent.com/15612750/104111419-59e04300-52c0-11eb-8914-d022829c54e0.png)

After send the message with the phone turned off, it try to send many times, and when the phone is turned on again, it send all of these messages ...

**Comment by adiwajshing** [comment]
It looks like you're calling the function multiple times -- which is why it's being sent multiple times

**Comment by ajeelias** [comment]
I will take a look. Thanks!
