### ISSUE TITLE
[BUG] Unexpected status in 'query': Not Found(404)

### ISSUE THREAD

**Issue by mtAlves** [adiwajshing/Baileys#309]
**Describe the bug**
I have an express server inside a docker container, on route requests a new WhatsApp connection is open and works fine, but a few moments later an error occurs.
```/agent/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:231
            throw new Constants_1.BaileysError(`Unexpected status in '${json[0] || 'generic query'}': ${http_1.STATUS_CODES[response.status]}(${response.status})`, { query: json, message, status: response.status });
                  ^
BaileysError: Unexpected status in 'query': Not Found(404)
    at WAConnection.query (/agent/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:231:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at WAConnection.getProfilePicture (/agent/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:427:26)
    at /agent/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:32
 ```
On `WAConnection.query` called with `q.json = [ 'query', 'ProfilePicThumb', 'JID HERE ex: 5521999999999@s.whatsapp.net' ]` the lib crashes. This same query occurs many times without problems, but whenever that crashes this is the query.

**To Reproduce**
1. Create an express server
2. Create a new connection on request
3. Wait for the crash

**Expected behavior**
Keep alive connections

**Environment (please complete the following information):**
 - Is this on a server? **YES**
 - What do your `connectOptions` look like? `{ maxRetries: 10 }`
 - Do you have multiple clients on the same IP? **NO**
 - Are you using a proxy? **NO**

**Comment by mtAlves** [comment]
Update:
The error occurs every I sent a message to a group.

`q.json [ 'query', 'ProfilePicThumb', '552140422409-1581469096@g.us' ]` group jids ends with `@g.us` instead `@s.whatsapp.net`

**Comment by adiwajshing** [comment]
@mtAlves this is intended behaviour. The error code tells you about the nature of denial -- If it's 404, then there is no profit picture. However, if it's 401 -- then it means you don't have permission to view the picture.

You can work around this very easily if you don't care about the error code, `url = conn.getProfilePicture(jid).catch(err => '')`

**Comment by mtAlves** [comment]
I think that this is not an error on Baileys side, even though the server returns a 404 the method `getProfilePicture` should returns the profile pic url or null value.
`getProfilePicture` throws an error if picture has not found, but the lib has not crashed.

Thank you for all your hard work on this!
