### ISSUE TITLE
Possibly not compatible with whatsapp beta.

### ISSUE THREAD

**Issue by gsbenevides2** [adiwajshing/Baileys#31]
Hello, I'm testing your library at the moment I'm a beta user of whatsapp for android.  And I can't send messages, the connection with qr code works, but it doesn't send a message.  And the whatsapp app just stops working.
 Some details:
 - Android: 9
 - Whatsapp Android Version: 2.20.188

 I am downgrading out of the beta to see if that's right.

**Comment by gsbenevides2** [comment]
I just left the beta program but I still can't send messages.

**Comment by gsbenevides2** [comment]
I found the problem, the constant number was wrong
```js
const number = '55119553011@s.whatsapp.net'
```
Above is correct, I recommend adding something to the readme to help a user get started.I will close this issue.

**Comment by adiwajshing** [comment]
You're right, for individual numbers, you need to have `@s.whatsapp.net` as the suffix. I'll add this into the readme.

**Comment by gsbenevides2** [comment]
And me thinking it was because I was beta on Android. But a question hit me now, what's the use of: `@c.us`

**Comment by adiwajshing** [comment]
It’s just a way WhatsApp uses to identify people — I’m not really sure why it has two types of IDs though
