### ISSUE TITLE
how to upload stories?

### ISSUE THREAD

**Issue by kikiixyz** [adiwajshing/Baileys#312]
hello friends :), I want to ask, how do we upload stories on whatsapp.
thanks for the help :)

**Comment by itacirgabral** [comment]
https://github.com/adiwajshing/Baileys#sending-messages

> For broadcast lists it's [timestamp of creation]@broadcast.
> For stories, the ID is status@broadcast.

**Comment by kikiixyz** [comment]
> https://github.com/adiwajshing/Baileys#sending-messages
> 
> > For broadcast lists it's [timestamp of creation]@broadcast.
> > For stories, the ID is status@broadcast.

uploading to whatsapp story?

**Comment by FERDIZ-afk** [comment]
> hello friends :), I want to ask, how do we upload stories on whatsapp. thanks for the help :)

I can't either
