### ISSUE TITLE
How do we get another person's "about" info?

### ISSUE THREAD

**Issue by Okcor** [adiwajshing/Baileys#313]
I have:

1. Searched through the repo's previous issues
2. Read through the readme at least once
3. Searched the docs for the feature you're looking for

----------------------------------------------------

I know how to get my own about information and I know how to get other people's information such as the status, but I don't see a function for getting info like their about message. I think we would do something similar to [this](https://github.com/adiwajshing/Baileys/blob/2b50e4e6cc2827f32ed5ee1b6abdc1a04baf5334/src/WAConnection/5.User.ts#L66) except replace the `'status'` with something else, however I've looked at the readme for the reverse engineering project and I don't see a key word for about.

Is there a proper list of the kinds of queries we can do, or better yet a function that returns a WAUser with all the details of one of our contacts/group members?

**Comment by adiwajshing** [comment]
What kind of `about` are you expecting?

**Comment by Okcor** [comment]
> What kind of `about` are you expecting?

When normally using WhatsApp, you can click on a person's profile and there is an "About and phone number" section. the first thing there is a custom message the user set and when it was set (The `about` information)

**Comment by adiwajshing** [comment]
The only things WA serves:
1. Status (likely the about you’re talking about). Can get using conn.getStatus
2. Name. Can get using conn.contacts
3. Phone. Can get from the jid

**Comment by Okcor** [comment]
I believe status is a seperate thing, basically the "Stories" from some other messaging service, I forget. But I'll try it anyways just to be sure.

I'll run my program in debug mode and see if I notice any queries that look like what I want. I'll report back with my findings

**Comment by Okcor** [comment]
Ok, so `conn.getStatus` does indeed get the "about" information I'm looking for. That's odd though because WhatsApp has its own seperate "Status" thing like I mentioned before. Maybe about was always internally referred to as "Status" and then later they added the seperate "Status" feature?

In that case, the readme and function name should be updated to make it clear we are getting the about section rather than the status.

**Comment by adiwajshing** [comment]
@Okcor WhatsApp used to call it status in the old days -- so I just kept it that way. Could rename to about actually, it's a clearer distinction

**Comment by Okcor** [comment]
> @Okcor WhatsApp used to call it status in the old days -- so I just kept it that way. Could rename to about actually, it's a clearer distinction

Yeah, either renaming it or adding a comment above the function would be good
