### ISSUE TITLE
Readme's instructions for getting a user's presence doesn't work

### ISSUE THREAD

**Issue by Okcor** [adiwajshing/Baileys#314]
**Describe the bug**
The readme's instructions for getting the "presence" of a user doesn't work. "on" event function doesn't detect traffic even though I can see it with logger level set to trace.

**To Reproduce**
Steps to reproduce the behaviour:
1. Created a new connection
2. Choose a phone number to get presence of
3. Add this code
```typescript
// the presence update is fetched and called here
conn.on ('user-presence-update', json => console.log(json.id + " presence is " + json.type))
await conn.requestPresenceUpdate (phoneNumbersJid) // request the update
```
4. Run

**Expected behaviour**
This will get us a subscription for the presence

**Environment**
- No strange environment stuff, just running my program locally

**Additional context**
It seems there isn't a listener for `user-presence-update` since its not present [here](https://github.com/adiwajshing/Baileys/blob/500805236abfb5a60609865b7cc19687157f05d5/src/WAConnection/4.Events.ts#L612), so I have a temporary fix where I use this custom listener, however it detects presences for all groups/users.

```typescript
conn.on('CB:Presence', async json => {
    console.log(json[1].id + " presence is " + json[1].type)
})
await conn.requestPresenceUpdate(phoneNumbersJid)
```

**Comment by Okcor** [comment]
Looking through older commits, it seems the `requestPresenceUpdate` event was deprecated and eventually removed in revision ac4b4c7 . 

I'm not sure why we now have to use a chat to get the presence? I see there used to be an update listener for about/status that was also deprecated, but that got its own function `getStatus()` so its not a problem.

IMO having a dedicated function `getPresence()` to get the current presence is useful since sometimes we don't want to bother setting up a listener and only want to query once.

I noticed the readme says to set logger level to debug to help implement new queries/stuff, but I don't see any useful information in the debug output for presences so I don't know how to make my own `getPresence()` function. Any help would be much appreciated.

**Comment by adiwajshing** [comment]
I apologise for the stale data in the readme. There are a few reasons why I've chosen to keep presence as a part of the `Chat` object.
1. An individual contact does not have presence updates. Only participants in chats do. Thus, the presence of a contact is always in respect to a specific chat. Even for chats with individuals, the presence is in respect to this independent chat.
2. Having presence be a dictionary mapping participant jid to presence (i.e. `presences: {[jid: string]: WAPresence}`) let's us handle individual and group chats in the exact same manner -- by referencing the `presences` property -- reducing code overhead
3. Handling raw presence data is a bit of a pain. I mapped the raw presence updates into solid state based changes on the `chat-update` event to make this data easier to work with.

[Here](https://github.com/adiwajshing/Baileys/blob/e1952ff349ef11e4240624bd05c03dfeac521017/Example/example.ts#L51) is an example showing the working.

**Comment by Okcor** [comment]
Thanks for the response. Yeah, for an event/emitter based system the chat version makes more sense.

But is it still possible to make a one-time function like `getStatus()` is? I'd just prefer to not have to setup an event/emitter system if I just want to check the presence once, so I don't have to worry about waiting for the event (Since I don't think you can use `await` on that) and then ending the event/emitter after the first presence check. Even if this still accesses it in that dictionary format, that's still good.

**Comment by Okcor** [comment]
Maybe the function could request a subscription and return a `promise`. When we get the first presence update we ignore the rest of the subscription info and prepare the information to be resolved through the promise.

**Comment by Okcor** [comment]
This is what I have so far for a one-time function. It would go in `5.User.ts`
```javascript
    /** Requests the current presence */
    async requestCurrentPresence(jid: string) {
        const presenceSubscribe = await this.query({ json: ['action', 'presence', 'subscribe', jid] })
        if (presenceSubscribe.status != 200) { 
            return
        }

        // Detect a "presence" event that matches our jid and store it
        var presence = ???

        await this.query({ json: ['action', 'presence', 'unsubscribe', jid]})

        return presence
    }
```
I don't know how to do 2 things:
- The previous ways of getting the actual presence data was by setting up an `on` event callback. So at the moment any subscriptions made with this function would be caught [here](https://github.com/adiwajshing/Baileys/blob/500805236abfb5a60609865b7cc19687157f05d5/src/WAConnection/4.Events.ts#L214). I'm still new to Javascript, so I don't know if we can have multiple callback functions for the one event, but if we can it would be good to catch the first presence update that matches our `jid`. But without an `on` event, I have no idea how I'd await and store these things.
- The unsubscribe query I made always returns a 400. Seems its the wrong thing to do. Should we worry about unsubscribing from a presence?

Also to be clear, the function would return the first presence update received, not a continued update since the existing `on` methods already do that. Also it would have the ability to get the presence of people you don't have a chat with. For example, group members with no direct DMs.

**Comment by Tvillonce** [comment]
>     1. An individual contact does not have presence updates. Only participants in chats do. Thus, the presence of a contact is always in respect to a specific chat. Even for chats with individuals, the presence is in respect to this independent chat.

I'm not sure i understand this. I have been using the latest release (3.4.1) and from what I can see, individual contacts _do_ have presence updates.
Has there been a change in WhatsApp web which removes or deprecates this?

**Comment by adiwajshing** [comment]
> > ```
> > 1. An individual contact does not have presence updates. Only participants in chats do. Thus, the presence of a contact is always in respect to a specific chat. Even for chats with individuals, the presence is in respect to this independent chat.
> > ```
> 
> 
> I'm not sure i understand this. I have been using the latest release (3.4.1) and from what I can see, individual contacts _do_ have presence updates.
> 
> Has there been a change in WhatsApp web which removes or deprecates this?

@Tvillonce that is because those contacts are also "chats" in and of themselves.

**Comment by adiwajshing** [comment]
@Okcor you don't have to unsubscribe for presences.

You can try this as a function (not tested or production ready)
``` ts
const waitForPresence = async(chatJid: string, contactJid: string) => {
  await conn.requestPresenceUpdate(chatJid)
  return new Promise(resolve => (
    conn.on('chat-update', update => {
      if(update.jid === chatJid && update.presences && update.presences[contactJid]) {
        resolve(update.presences[contactJid].lastKnownPresence)
      }
    })
  ))
}

```

**Comment by Okcor** [comment]
> @Okcor you don't have to unsubscribe for presences.
> 
> You can try this as a function (not tested or production ready)
> 
> ```ts
> const waitForPresence = async(chatJid: string, contactJid: string) => {
>   await conn.requestPresenceUpdate(chatJid)
>   return new Promise(resolve => (
>     conn.on('chat-update', update => {
>       if(update.jid === chatJid && update.presences && update.presences[contactJid]) {
>         resolve(update.presences[contactJid].lastKnownPresence)
>       }
>     })
>   ))
> }
> ```

I modified it to pass in `conn`. It does work for some people, but fails for others. For example if I give it my own jid then it hangs (But I kind of expected that). However it also hangs for jids not in my contacts which is a problem because there are some people I share groups with who aren't in my contacts. Whereas the `on` event that was deprecated and removed was able to get the presence of those people.

**Comment by Okcor** [comment]
Issue isn't resolved. Don't close
