### ISSUE TITLE
Is it possible to decode media on frontend?

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#315]
I want do smth like this. WhatsApp send me link with .enc file. I send this link to React app. This file is decoded and then displayed on the page. Has anyone done something like this?

**Comment by adiwajshing** [comment]
You can run the decryption code pretty easily on the frontend — just have to remove the dependency on FS and work in pure memory

**Comment by ilyaborodin** [comment]
> You can run the decryption code pretty easily on the frontend — just have to remove the dependency on FS and work in pure memory
> 
> > On 16-Jan-2021, at 2:01 AM, Ilya Borodin <notifications@github.com> wrote:
> > 
> > ﻿
> > I want do smth like this. WhatsApp send me link with .enc file. I send this link to React app. This file is decoded and then displayed on the page. Has anyone done something like this?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Thx
