### ISSUE TITLE
add pushName

### ISSUE THREAD

**Issue by Kry9toN** [adiwajshing/Baileys#316]
@adiwajshing Please add return pushname, id, and etc on method `getContact`
example :
`getContact('12345@s.whatsapp.net')`

**Comment by ajeelias** [comment]
Hi, you can do it..

**Comment by ajeelias** [comment]
async getContact(pId) {
  return conn.contacts[pId].notify
}

**Comment by Kry9toN** [comment]
> async getContact(pId) {
> return conn.contacts[pId].notify
> }

Not work for me

`(node:29162) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'notify' of undefined`

**Comment by ajeelias** [comment]
async getContactName(pFindValue) {
        console.log('getName findValue='+pFindValue);

        if(pFindValue.includes('g.us')){
            // console.log('getName by name='+conn.contacts[pFindValue].name+ ' findValue='+pFindValue);
            return conn.contacts[pFindValue].name    
        }else if(pFindValue.includes('.net')){
            // console.log('getName by notify='+conn.contacts[pFindValue].notify);
            return conn.contacts[pFindValue].notify    
        }else {
            return ''
        }

    }

**Comment by Okcor** [comment]
What exactly is a pId? I'm using jids instead and `conn.contacts` is fine with that

**Comment by Kry9toN** [comment]
`conn.contacts` that method for search your saved contacts, i need detect contacts like from sender id or id on greeting detections

**Comment by Okcor** [comment]
> `conn.contacts` that method for search your saved contacts, i need detect contacts like from sender id or id on greeting detections

Yeah, that's a good point. For example if you're in a group then there may be people who aren't in your contacts list, but you might want to get their display/push names to make custom messages using it.

**Comment by Kry9toN** [comment]
> > `conn.contacts` that method for search your saved contacts, i need detect contacts like from sender id or id on greeting detections
> 
> Yeah, that's a good point. For example if you're in a group then there may be people who aren't in your contacts list, but you might want to get their display/push names to make custom messages using it.

I need push name for welcome image, i dont have idea for take their pushname

**Comment by BerTren-Nation** [comment]
I use this is to take the name
conn.contacts["62xxxx@s.whatsapp.net"] != undefined ? conn.contacts["62xxxx@s.whatsapp.net"].vname || conn.contacts["62xxxx@s.whatsapp.net"].notify : undefined

**Comment by Kry9toN** [comment]
> I use this is to take the name
> conn.contacts["[62xxxx@s.whatsapp.net](mailto:62xxxx@s.whatsapp.net)"] != undefined ? conn.contacts["[62xxxx@s.whatsapp.net](mailto:62xxxx@s.whatsapp.net)"].vname || conn.contacts["[62xxxx@s.whatsapp.net](mailto:62xxxx@s.whatsapp.net)"].notify : undefined

This can take name, other than the people in your contacts?

**Comment by BerTren-Nation** [comment]
> > I use this is to take the name
> > conn.contacts["[62xxxx@s.whatsapp.net](mailto:62xxxx@s.whatsapp.net)"] != undefined ? conn.contacts["[62xxxx@s.whatsapp.net](mailto:62xxxx@s.whatsapp.net)"].vname || conn.contacts["[62xxxx@s.whatsapp.net](mailto:62xxxx@s.whatsapp.net)"].notify : undefined
> 
> This can take name, other than the people in your contacts?

> let user = conn.contacts["62xxxx@s.whatsapp.net"]
/*
{
 vname: 'Business Name',
 name: 'Contact Name',
 short: 'Contact Name in Short',
 notify: 'Pushname'
}
*/
get names from contacts 

conn.chats.get("62xxxx@s.whatsapp.net").name

**Comment by Kry9toN** [comment]
Oke solved

**Comment by Okcor** [comment]
> Oke solved

But that won't get the name of people outside your contacts. It can get the names of any chats you're in (1-on-1 and group names). There still doesn't seem to be a way to get the display name for someone not in your contacts/chats.
