### ISSUE TITLE
How do we get the about/status timestamp?

### ISSUE THREAD

**Issue by Okcor** [adiwajshing/Baileys#319]
`getStatus()` returns just the about/status, but I don't see any way to get the timestamp from when it was set.

**Comment by adiwajshing** [comment]
Yeah, I haven't looked into fetching that. You can inspect WA Web traffic to find out If such a method exists

**Comment by Okcor** [comment]
I'm not familiar with watching web traffic, so I don't really know how to navigate Chrome's network tab's packets.

Although, now that I've double checked. I can't even see the about time in the actual Web/Desktop programs, so maybe its just not accessible what-so-ever? That's weird, I could have sworn I saw it before.

If I'm wrong and the about time is visible, do let me know. Otherwise I'll close this issue in a few days.

**Comment by Okcor** [comment]
Yeah, "about's time" definitely isn't available on WhatsApp Web at this time
