### ISSUE TITLE
How to save a new authInfo after whatsapp updates it?

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#320]
It is your text in readme: 

> Note: Upon every successive connection, WA can update part of the stored credentials. Whenever that happens, the credentials-updated event is triggered, and you should probably update your saved credentials upon receiving that event. Not doing so may lead WA to log you out after a few weeks with a 419 error code.

But a few commits ago event "credentials-updated" was removed. What happens now when whatsapp updates authInfo?
How to save a new authInfo after whatsapp updates it?

**Comment by Okcor** [comment]
The readme is a little outdated, it mentions a few things that have been removed. However what I believe it means is that you should save the authentication data back into a `json` file after connecting so next time you run, you load the credentials and log in with that. We can see this in the example from lines [32 to 38](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#L32).

**Comment by ilyaborodin** [comment]
> The readme is a little outdated, it mentions a few things that have been removed. However what I believe it means is that you should save the authentication data back into a `json` file after connecting so next time you run, you load the credentials and log in with that. We can see this in the example from lines [32 to 38](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts#L32).

I understand this and have already done it. The library has changed,but I think whatsapp api has not changed.  So I wonder what will happen in the key if wa changes authinfo for example one week.

I have only one idea, that wa will reconnect after getting new aithonfo, and I can get authinfo from "open" event.

**Comment by adiwajshing** [comment]
Apologies for the stale pieces of information in the readme. 

You can save the authInfo again after the open event. 

credentials-updated was removed because open would inevitably be called immediately after credentials-updated, making the event redundant.

**Comment by ilyaborodin** [comment]
> Apologies for the stale pieces of information in the readme.
> 
> You can save the authInfo again after the open event.
> 
> credentials-updated was removed because open would inevitably be called immediately after credentials-updated, making the event redundant.

Thank you. I thought it worked that way.
