### ISSUE TITLE
[BUG]  Sometimes the application freezes

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#323]
**Description**
Hello, everyone. When I switched from my old version to the latest changes in the master branch, from time to time everything began to freeze. It feels like the connection with the phone is lost and not restored. 
Tried everything:
- I entered the application on my phone several times
- turned off and on the Internet on my phone

But I did not find the reason and how it can be reproduced. It happens to me randomly.
Phone: iphone xr, internet working good(i can load websites and use other apps)
The last message that i see is:

> DEBUG    [2021-01-20 17:12:07.171 +0000] (13708): s13,["Stream","asleep"]
>     unhandled: true
>     class: "Baileys"

**Environment:
 - on local machine
 - connectOptions:
```
   connWA.connectOptions = {
    maxIdleTimeMs: 60_000,
    maxRetries: Infinity,
    phoneResponseTime: 15_000,
    connectCooldownMs: 4000,
    alwaysUseTakeover: true
  }
```
 - One connection - 1 ip
 - Don't use proxy
 -   connWA.autoReconnect = ReconnectMode.onAllErrors;

**Comment by keef3ar** [comment]
> **Description**
> Hello, everyone. When I switched from my old version to the latest changes in the master branch, from time to time everything began to freeze. It feels like the connection with the phone is lost and not restored.
> Tried everything:
> 
> * I entered the application on my phone several times
> * turned off and on the Internet on my phone
> 
> But I did not find the reason and how it can be reproduced. It happens to me randomly.
> Phone: iphone xr, internet working good(i can load websites and use other apps)
> The last message that i see is:
> 
> > DEBUG    [2021-01-20 17:12:07.171 +0000] (13708): s13,["Stream","asleep"]
> > unhandled: true
> > class: "Baileys"
> 
> **Environment:
> 
> * on local machine
> * connectOptions:
> 
> ```
>    connWA.connectOptions = {
>     maxIdleTimeMs: 60_000,
>     maxRetries: Infinity,
>     phoneResponseTime: 15_000,
>     connectCooldownMs: 4000,
>     alwaysUseTakeover: true
>   }
> ```
> 
> * One connection - 1 ip
> * Don't use proxy
> * connWA.autoReconnect = ReconnectMode.onAllErrors;

did you found a reason or solution?

**Comment by ilyaborodin** [comment]
> > **Description**
> > Hello, everyone. When I switched from my old version to the latest changes in the master branch, from time to time everything began to freeze. It feels like the connection with the phone is lost and not restored.
> > Tried everything:
> > 
> > * I entered the application on my phone several times
> > * turned off and on the Internet on my phone
> > 
> > But I did not find the reason and how it can be reproduced. It happens to me randomly.
> > Phone: iphone xr, internet working good(i can load websites and use other apps)
> > The last message that i see is:
> > > DEBUG    [2021-01-20 17:12:07.171 +0000] (13708): s13,["Stream","asleep"]
> > > unhandled: true
> > > class: "Baileys"
> > 
> > 
> > **Environment:
> > 
> > * on local machine
> > * connectOptions:
> > 
> > ```
> >    connWA.connectOptions = {
> >     maxIdleTimeMs: 60_000,
> >     maxRetries: Infinity,
> >     phoneResponseTime: 15_000,
> >     connectCooldownMs: 4000,
> >     alwaysUseTakeover: true
> >   }
> > ```
> > 
> > 
> > 
> > * One connection - 1 ip
> > * Don't use proxy
> > * connWA.autoReconnect = ReconnectMode.onAllErrors;
> 
> did you found a reason or solution?

No, maybe u found?

**Comment by zhengshengjie666** [comment]
您解决了吗？是怎么解决的呢？

**Comment by leenasn** [comment]
Any updates on this? I am also facing this issue.

**Comment by leenasn** [comment]
I found that this issue happens when I use quickReplyButton. If am sending plain messages or messages with buttons, the issue doesn't happen. Hope that helps.

**Comment by Jorsis** [comment]
same here
