### ISSUE TITLE
Is it possible to not automatically load messages when connecting

### ISSUE THREAD

**Issue by Okcor** [adiwajshing/Baileys#324]
I could be completely wrong, but it seems when we login and start a connection with the WA servers, under the hood, it sends us all our contacts and chats to us. This includes every message in those chats.

I was wondering if the WhatsApp Web AI allows us to get *some* chats at a time, or at least only get the messages from a specific few chats when requested? I believe this is important because if we are in multiple chats with long histories, startup will take a fair bit of time and a bit more data in RAM than needed.

Here's an example use case: I make a program that only checks new messages in a select few chats. I only care about reading the new messages and don't care about old messages or any messages from the other chats.

**Comment by Okcor** [comment]
To be clear, I know we have the function `loadMessages()` which implies that the messages aren't initially local, but even before calling it I can see that the messages are present in `conn.chats.get(jid)`. So really. `loadMessages()` is a getter of local data.

**Comment by adiwajshing** [comment]
I completely understand your concern, and really wish there was a way -- but WA just forces this info onto us

**Comment by Okcor** [comment]
> I completely understand your concern, and really wish there was a way -- but WA just forces this info onto us

Ah well. Thanks for clarifying this

**Comment by morganzysman** [comment]
Hi, is it still the case ?

Regards
