### ISSUE TITLE
How do I know QR code is scanned by mobile app

### ISSUE THREAD

**Issue by hvupadhye** [adiwajshing/Baileys#325]
How to handle QR code scanned event? Browser keeps on showing QR even after it scanned successfully.

**Comment by Okcor** [comment]
Were you running `example.ts`? When I ran it, initially my phone was vertical and the camera wouldn't scan the code. I had to rotate my phone landscape for it to actually work. After that the QR code disappeared and the rest of the example worked. Maybe you are having the same issue?

There is also a way to override the QR callback so you can see if its actually triggering or not
```javascript
conn.on('qr', qr => {
    // Now, use the 'qr' string to display in QR UI or send somewhere
}
await conn.connect ()
```
