### ISSUE TITLE
please help, sir 

### ISSUE THREAD

**Issue by kikiixyz** [adiwajshing/Baileys#326]
How do I save music, photos, videos to localdisk?

**Comment by itacirgabral** [comment]
https://github.com/adiwajshing/Baileys#downloading-media-messages

https://adiwajshing.github.io/Baileys/classes/waconnection.html#downloadandsavemediamessage

**Comment by ibnusyawall** [comment]
```js
client.downloadAndSaveMediaMessage(m, 'filename')
```

**Comment by kikiixyz** [comment]
thanks for all:)
