### ISSUE TITLE
Can I get only the contact list in my phone book?

### ISSUE THREAD

**Issue by welcome14** [adiwajshing/Baileys#328]
I would like to be able to have the list of contacts in my phone book, currently with the "conn.contacts" command all the contacts are listed, even those no longer present in my phone book.
How can I do ?

Thank you!

**Comment by itacirgabral** [comment]
They came from the groups participants too.

You don't have access to the phone book. You can get all the whatsapp chats and filter it only who isn't a group.

- chat-new
- chats-received
