### ISSUE TITLE
help me, sir

### ISSUE THREAD

**Issue by kikiixyz** [adiwajshing/Baileys#329]
how to leave all group?

**Comment by Okcor** [comment]
The hardest part about this is getting the jids of the groups you are in. The jids for all chats can be found in `conn.chats`, but the data is private so normally you can't check. However I discovered you can bypass the private by doing
```javascript
for (const [key, value] of Object.entries(conn.contacts)) {
   if(/[0-9]+-[0-9]+@g.us/.test(value.jid)){   // Checks if its a group jid using regex
      try{
         await conn.groupLeave(value.jid);
      }
      catch (excption) {
         // Do stuff when it throws an error
      }
   }
}
```
If there's a proper way to get the chat jids, let me know.

**Comment by kikiixyz** [comment]
> The hardest part about this is getting the jids of the groups you are in. The jids for all chats can be found in `conn.chats`, but the data is private so normally you can't check. However I discovered you can bypass the private by doing
> 
> ```js
> for (const [key, value] of Object.entries(conn.contacts)) {
>    if(/[0-9]+-[0-9]+@g.us/.test(value.jid)){   // Checks if its a group jid using regex
>       try{
>          await conn.groupLeave(value.jid);
>       }
>       catch (excption) {
>          // Do stuff when it throws an error
>       }
>    }
> }
> ```
> 
> If there's a proper way to get the chat jids, let me know.
> 
> Also FYI @kikiixyz, when making issues on places like GitHub, don't title the issue "help me, sir". Instead it should be a tl;dr of the issue. E.g. "How do I leave all groups?"


heemm sorry i don't know,
By the way, thank you for your help
