### ISSUE TITLE
retrieving data on login

### ISSUE THREAD

**Issue by keef3ar** [adiwajshing/Baileys#33]
Is there any way to not request chats and contacts? Account with 12000+ chats, i don't need to get it on start. I found only event on contact recive, but can't find where Baileys makes request. Is whatsapp sending it forced?

**Comment by adiwajshing** [comment]
WhatsApp sends it forced :/
However, I'll implement a workaround.

**Comment by adiwajshing** [comment]
@keef3ar I've written a workaround in the library, instead of waiting for the chats when connecting, you can opt to do so in the background now. This is available in the latest commit, here is an example:

``` javascript
    client.connectSlim() // does not wait for chats & contacts
    .then (user => {
        console.log ("oh hello " + user.name + " (" + user.id + ")")
        
        client.receiveChatsAndContacts () // optionally, wait for chats & contacts in the background
        .then (([chats, contacts, unread]) => {
            console.log ("you have " + unread.length + " unread messages")
            console.log ("you have " + chats.length + " chats")
        })
    })
```
