### ISSUE TITLE
Add a warning about WhatsApp ban in Readme

### ISSUE THREAD

**Issue by rchuluc** [adiwajshing/Baileys#331]
I was developing a simple API to interact with WhatsApp with this lib, so far from spamming ... just because the two phone numbers involved in the tests are mine, and was banned from WA. So, I think that you should put a warning at the top of the readme file. My advice to anyone using WA automations, use another phone number (not your personal) and be careful.

**Comment by gfarias** [comment]
Hi, can you provide more details on what you did that got you banned? And how are you sure that WA banned you?

**Comment by rchuluc** [comment]
Hi @gfarias, I've got banned by creating a group and deleting the members, but, in the method i've removed myself by mistake insted leaved the group, so Whatsapp banned me for the abnormal behaviour ... When you are banned, the Whatsapp app in the phone is loged out and you receive a message when you try to login again, informing that the number is banned. So, you know when you are banned.

I did a search in Google about how to retrieve my number back, and fortunatelly I got him back. If you have got banned, just send an apologize email to WA support, the email is in the banned message in your phone that will open when you try to login. Some people say that the first time that you got banned you can back with this method, if it's not your first time, it may be permanent.

My advice, use another number to test and develop, not your personal, before start using the new account use this account normally, sending and receiving messages mannually ... it's called "warm up the account".

And, the most important, don't send spam.

**Comment by gfarias** [comment]
@rchuluc great explanation and advice, thanks!
