### ISSUE TITLE
The user is shown as online at all times

### ISSUE THREAD

**Issue by NilsIrl** [adiwajshing/Baileys#332]
I have a script that connects and then listens on some events. However, the user that it is connected to is shown as online at all times even though nothing is happening. Is there a way to disable the online presence?

**Comment by adiwajshing** [comment]
What events are you listening for?

**Comment by NilsIrl** [comment]
I'm listening for `credentials-updated`, `contacts-received` and `chat-update`.

**Comment by mtAlves** [comment]
Is there a way to disable the online presence?
I have tried to use `conn.updatePresence(conn.user.jid, Presence.unavailable)` after `conn.connect()` but was unsuccessful.
