### ISSUE TITLE
Unsure how to paginate conn.chats.get(jid).messages

### ISSUE THREAD

**Issue by Okcor** [adiwajshing/Baileys#334]
I wish to paginate my messages I'm not using `loadMessages()` because that makes API calls, instead I'll use the chat messages we already have. I can do `conn.chats.get(jid).messages.paginated(null, 5, undefined, 'before')` to get the 5 latest messages, but in order to get the next messages, I need a cursor. I don't really get what it expects the cursor to be since everything I try either complains its the wrong type, or it says `Cannot read property 'epoch' of undefined`. The KeyedDB repo's readme showed an example giving the current time, but when I tried that it gave the wrong type error.

**Comment by adiwajshing** [comment]
`loadMessages()` automatically uses the cache when available

**Comment by Okcor** [comment]
> `loadMessages()` automatically uses the cache when available

I looked at the implementation of that function and I saw that it always sent off a query at the beginning, even before checking the cached messages. Shouldn't it first check the cache then fetch from WA if it isn't there?

**Comment by Okcor** [comment]
Oh right, that's a function _definition_, not a function _call_. got it.
