### ISSUE TITLE
[BUG] Send media from URL

### ISSUE THREAD

**Issue by ikheetjeff** [adiwajshing/Baileys#336]
**Describe the bug**
When i send a message with media url, i get the error:

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object

My code:
await client.sendMessage(
    '<mynumber>@s.whatsapp.net', 
    { url: 'https://giphy.com/gifs/11JTxkrmq4bGE0/html5' }, // send directly from remote url!
    MessageType.video, 
    { mimetype: Mimetype.gif, caption: "hello!" }
);

What is the fix for this?

**Comment by itacirgabral** [comment]
hi!

Are you using the npm @adiwajshing/baileys package? Its version 1.4.1 have not this function, It is only in github yet.
http://localhost:8080/classes/waconnection.html#sendmessage

**Comment by piyush-multiplexer** [comment]
> hi!
> 
> Are you using the npm @adiwajshing/baileys package? Its version 1.4.1 have not this function, It is only in GitHub yet.
> http://localhost:8080/classes/waconnection.html#sendmessage

Hello,
Regarding version of the package, the latest version on GitHub is currently **v3.4.1** and after that no releases made but latest code is in master branch with version **4.0.0** is there yet to release. Can you do a release of that so one can download it from direct npm/specific version for further package updates?

**Comment by adiwajshing** [comment]
4.0.0 hasn’t been released since it’s not complete yet
