### ISSUE TITLE
error at installation

### ISSUE THREAD

**Issue by goreorto** [adiwajshing/Baileys#337]
`npm install @adiwajshing/baileys` or `npm install github:adiwajshing/baileys` produces

```
npm ERR! prepareGitDep > @adiwajshing/baileys@4.0.0 prepare /mine/.npm/_cacache/tmp/git-clone-9f06747d
npm ERR! prepareGitDep > tsc
npm ERR! prepareGitDep
npm ERR! prepareGitDep src/WAConnection/Utils.ts(16,32): error TS2307: Cannot find module 'music-metadata' or its corresponding type declarations.
npm ERR! prepareGitDep src/WAConnection/Utils.ts(250,41): error TS2307: Cannot find module 'music-metadata' or its corresponding type declarations.

```

```
> node --version
v14.6.0
```

**Comment by gfarias** [comment]
+1

**Comment by mtAlves** [comment]
Same here.

**Comment by gfarias** [comment]
@adiwajshing have you had a chance to look at this? thanks.

**Comment by adiwajshing** [comment]
Haven't had a chance. It works fine for me on node 12 & 14.
I don't think this issue is for Baileys per se, but something in the `music-metadata` repo. 

However, if I could have more environment specific information -- this could be debugged. Also, does it work fine on `yarn`?

@gfarias @goreorto

**Comment by goreorto** [comment]
Switching to yarn fixed it, @adiwajshing 

I got `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined` right after but `npm audit fix` got rid of that.
