### ISSUE TITLE
GIFs Doesn't play in WA [BUG]

### ISSUE THREAD

**Issue by AlenSaito1** [adiwajshing/Baileys#340]
**Description**
The GIF files and Video (sent with `Mimetype.gif`) doesn't play on Whatsapp

**Code**

```TS 

//Modules used
import { WAConnection, MessageType, Mimetype } from '@adiwajshing/baileys'
import get from 'axios'
import * as fs from 'fs-extra'
import * as ffmepg from 'fluent-ffmpeg'
import { execSync } from 'child_process'

const url = `https://cdn.nekos.life/hug/hug_042.gif` //example url
const res = await get(url, { responseType: 'arraybuffer'})
client.sendMessage(jid, res.data, MessageType.video, { mimetype: Mimetype.gif, caption: 'cool caption' })

//Also tried sending from a video file

const res = await get(url, { responseType: 'arraybuffer'})
await fs.writeFile('well.gif', res.data)
execSync(`ffmpeg -f gif -i well.gif well.mp4`)
const buff = await fs.readFile('well.mp4')
client.sendMessage(jid, buff, MessageType.video, { mimetype: Mimetype.gif, caption: 'cool caption' })

```

**Expected Behaviour**
It was supposed to play the GIF after downloading

**Environmen**

 - Is this on a server?
 +No

 -  What do your `connectOptions` look like? 
 ```JS\
{
  maxIdleTimeMs: 60000,
  maxRetries: 10,
  connectCooldownMs: 4000,
  phoneResponseTime: 15000,
  alwaysUseTakeover: true
}
```
 - Do you have multiple clients on the same IP?
 + No

 - Are you using a proxy?
 + No

**Additional context**

*** Screenshots

- On Phone
![WhatsApp Image 2021-01-30 at 16 55 34](https://user-images.githubusercontent.com/66544823/106355567-d80f9280-631e-11eb-9d15-d2f38a944d39.jpeg)
Clicking on the `GIF` Button (in the middle of the container) does nothing

-On Web

![Screenshot_2021-01-30 (92) WhatsApp](https://user-images.githubusercontent.com/66544823/106355582-f2497080-631e-11eb-9746-eac705cef948.png)

Clicking on the Download Button does nothing

I hope this gets fixed soon, Thanks

**Comment by adiwajshing** [comment]
@AlenSaito1 works fine on the latest commit. Can you try that and let me know if that works?
