### ISSUE TITLE
[BUG] Possible memory leak on "downloadMediaMessage"

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#343]
**Describe the bug**
After getting media buffer from "downloadMediaMessage", the memory usage grows the size of downloaded media and are not garbage collected.

**To Reproduce**
Steps to reproduce the behavior, using `downloadMediaMessage` on your code:
1. Start your application with --inspect: `node --inspect myapp.js`.
2. On chrome, go to `chrome://inspect` and connect to your app.
3. Take a snapshot of heap memory.
4. Ask someone to send you a big media (I've tested with a 19MB zip file).
5. Take another snapshot and compare heap memory usage.

**Expected behavior**
The used memory should be garbage collected, freeing up memory.

**Additional context**
![image](https://user-images.githubusercontent.com/24817866/106388317-b1a03480-63bc-11eb-82bf-f8d99d48ade4.png)

**Comment by canove** [comment]
Update: Using the "stream" type of `downloadMediaMessage` works great! Memory was used for a while but get garbage collected after som seconds:

![image](https://user-images.githubusercontent.com/24817866/106393009-40b84700-63d3-11eb-8ee4-3ad8a95be5c6.png)

**Comment by adiwajshing** [comment]
Should this be closed then @canove ?

**Comment by canove** [comment]
I don't know. It's ok to "buffer type" keep the media size in memory?
