### ISSUE TITLE
[BUG] Can't get message status DELIVERY_ACK and READ

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#344]
**Describe the bug**
I'm only receiving status 1 and 2 with the master branch version.

**To Reproduce**
1. Created a new connection
2. Register a listener to chat-update and logs message status:
```
   conn.on("chat-update", async chat => {
      if (chat.messages) {
        const msg = chat.messages.all()[0];
        console.log(msg.status);
    });

```

**Expected behavior**
Get a status 3 and eventually 4. But it stops on 2.

**Comment by adiwajshing** [comment]
Was an issue on android phones. have fixed in latest commit on GH @canove

**Comment by canove** [comment]
@adiwajshing, just tested it today, and now i'm receiving 2 and 3, but not 4 (read). Do you have any clue why?
