### ISSUE TITLE
How to page messages with a predicate

### ISSUE THREAD

**Issue by Okcor** [adiwajshing/Baileys#345]
I would like to load some of my messages that match a condition in a paged format. The `conn.loadMessages()` method doesn't have an option for predicates, however the lower-level KeyedDB does have a few methods.

1. Calling `.filter().all()` on the messages db will get all the messages you want, but its not that great if you want to page it since it makes a copy of the whole section
2. `.paginatedByValue()` allows for pagination with a WebMessageInfo object for `cursor`, but you'd need to pass around a WebMessageInfo which is a bit bulky. Also, internally it just calls the method below anyways.
3. `.paginated()` is probably the right option and the one I'm currently trying to use, however I can't figure out the format it expects for `cursor`. Everything I try to use throws an error.

Here is my code so far
```javascript
export function a(conn: WAConnection, jid: string, rangeLower: number, rangeUpper: number, cursor, amount: number) {
    const predicate = (item => item.messageTimestamp >= rangeLower && item.messageTimestamp <= rangeUpper)
    const messages = conn.chats.get(jid).messages.paginated(cursor, amount, predicate, 'after')

    // Get the new cursor if we can
    if (messages.length > 0) {
        cursor = {id: messages[messages.length - 1].key.id, fromMe: messages[messages.length - 1].key.fromMe}
        // cursor = messages[messages.length - 1].key
        // cursor = GET_MESSAGE_ID(messages[messages.length - 1].key)
    } else {
        cursor = null
    }

    return [messages, cursor]
}

main() {
   // Initialisation stuff first
   
   // Paginated loading
   var result = a(conn, jid, timeA, timeB, null, 3)
   result = a(conn, jid, timeA, timeB, result[1], 3)
}
```
The first call works fine (since cursor is null), but the second call throws an error for all of the options I have in the `if` block.

I've looked through the code and documentation for both Baileys and KeyedDB, but I still can't figure out what it wants other than "type `K`"

**Comment by adiwajshing** [comment]
Try this perhaps:
``` ts

let msg: WAMessage
await findMessage(jid, message => {
  if(myConditionMatches(message)) {
    msg = message
    return msg
  }
})
```

**Comment by Okcor** [comment]
> Try this perhaps:
> 
> ```ts
> let msg: WAMessage
> await findMessage(jid, message => {
>   if(myConditionMatches(message)) {
>     msg = message
>     return msg
>   }
> })
> ```

I'm not too sure how that would be used. Are you suggesting looping over all the messages and calling `findMessage` on all of them to find which ones meet my condition or not? I think that would work, but it seems inefficient.

I'm fairly sure the messages are already sorted by timestamp which means for my particular condition (Messages between two timestamps) I should be able to paginate over a block with no problem. If I get a cursor to the first message that meets the predicate/condition, then I should just be able to paginate normally. The problem is that I don't what it expects the cursor to be.

**Comment by adiwajshing** [comment]
No, the findMessage function internally loops over an array and loads more messages if necessary from WA. Moreover, the messages are not sorted by timestamp — they’re sorted by some other mechanism that I don’t understand (in order of when the messages were received by the phone).

**Comment by Okcor** [comment]
Oh, right. I didn't realise `findMessage()` was an existing function. It looks almost perfect, but it doesn't look page-able since I don't think it returns anything. In that case I'll just go back to one of the previous methods. Thanks for the help though.
