### ISSUE TITLE
[BUG] url bug termux

### ISSUE THREAD

**Issue by LaShreka** [adiwajshing/Baileys#348]
![Screenshot_20210203-011145](https://user-images.githubusercontent.com/74848093/106697249-217d0d80-65bd-11eb-92d9-a74c441a3bcb.png)
**Describe the bug**
This error whenever the program tries to download an image / video / gif
    Error : TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

my code:

	case 'randomcat':
try {
					if (isBanned) return reply(mess.only.benned)    
				
				if (!isUser) return reply(mess.only.userB)					
						res = await fetchJson(`https://nekos.life/api/v2/img/meow`, {method: 'get'})
						bufferxx = await getBuffer(res.result)
						client.sendMessage(from, bufferxx, image, {quoted: mek, caption: 'neko neko'})
					} catch (e) {
						console.log(`Error :`, color(e,'red'))
						reply('❌ *ERROR* ❌')
					}
					break

**Comment by BerTren-Nation** [comment]
> ![Screenshot_20210203-011145](https://user-images.githubusercontent.com/74848093/106697249-217d0d80-65bd-11eb-92d9-a74c441a3bcb.png)
> **Describe the bug**
> This error whenever the program tries to download an image / video / gif
> Error : TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
> 
> my code:
> 
> ```
> if (args.length < 1) return reply('Onde está o url, hum?')
> if (!isUrl(args[0]) && !args[0].includes('tiktok.com')) return reply(mess.error.Iv)
> 	reply(mess.wait)
> 	anu = await fetchJson(`https://docs-jojo.herokuapp.com/api/tiktok_nowm?url=`, {method: 'get'})
> 				if (anu.error) return reply(anu.error)
> 				buffer = await getBuffer(anu.result)
> 				client.sendMessage(from, buffer, video, {quoted: mek})
> 				break
> ```
look at the web results first before asking
