### ISSUE TITLE
Check Number Validity on Whatsapp

### ISSUE THREAD

**Issue by piyush-multiplexer** [adiwajshing/Baileys#349]
Hello,
I need to check mobile number exists on WhatsApp or not. I tried in v3.4.1 version which accepts all integer values and gives a positive response, and if I check to current v4.0.0 then it shows an error, How can I achieve this in any of this version?**
Tried Using isOnWhatsApp and isOnWhatsAppNoConn both.

In v3.4.1
![image](https://user-images.githubusercontent.com/18528418/106993460-c441b180-67a0-11eb-9c1f-4e046626af76.png)
In v4.0.0
![image](https://user-images.githubusercontent.com/18528418/106993508-db809f00-67a0-11eb-9a3f-f365a6eadbaf.png)

**Comment by adiwajshing** [comment]
Is fixed now, was an issue with headers being used to determine status of the number. @piyush-multiplexer

**Comment by piyush-multiplexer** [comment]
@adiwajshing  Yes, that issue is resolved(regarding response), but validating mobile numbers gives still wrong results with all integer values.

```
{ exists: true, jid: '766666@s.whatsapp.net' }
766666 exists on WhatsApp, as jid: 766666@s.whatsapp.net

{ exists: true, jid: '910123456789@s.whatsapp.net' }
910123456789 exists on WhatsApp, as jid: 910123456789@s.whatsapp.net

{ exists: true, jid: '9427905422@s.whatsapp.net' }
9427905422 exists on WhatsApp, as jid: 9427905422@s.whatsapp.net
```

**Comment by NicolasCaous** [comment]
@piyush-multiplexer Whatsapp actually allows you to send messages to those numbers. I don't know why, but it works. So I don't think that the validation is wrong at all

**Comment by piyush-multiplexer** [comment]
Yes got it.
