### ISSUE TITLE
how to Reject call?

### ISSUE THREAD

**Issue by kikiixyz** [adiwajshing/Baileys#350]
how do i reject a call,
and if the feature doesn't exist, may I request that feature?: D

**Comment by adiwajshing** [comment]
I believe you cannot do that on WA Web as of now

**Comment by kikiixyz** [comment]
Alright, by the way, I want to ask one more question, yes: D
How to Detect message readers?
confused sir

**Comment by kikiixyz** [comment]
@adiwajshing

**Comment by adiwajshing** [comment]
Listen for the `chat-update` event, whenever a message is read -- it is updated here

**Comment by kikiixyz** [comment]
> Listen for the `chat-update` event, whenever a message is read -- it is updated here

thx, semoga berhasil ajg

**Comment by adiwajshing** [comment]
No worries. Kaka chinta na kari
