### ISSUE TITLE
[BUG] `loadChats` not loading anything at all

### ISSUE THREAD

**Issue by NicolasCaous** [adiwajshing/Baileys#351]
**Describe the bug**
`loadChats` isn't loading anything, even if `getChats` works

**To Reproduce**
1. Created a new connection
2. Call `loadChats`
```javascript
console.log(await conn.loadChats(1));
console.log(conn.chats);
```
Output:
```javascript
{ chats: [], cursor: undefined }
KeyedDB {
  key: { key: [Function: key], compare: [Function: compare] },
  idGetter: [Function (anonymous)],
  dict: {},
  array: []
}
```
3. Compare with `getChats`
```javascript
console.log(await conn.getChats());
console.log(conn.chats);
```
Output:
```javascript
[ 'response', { type: 'chat', duplicate: 'true' }, null ]
KeyedDB {
  key: { key: [Function: key], compare: [Function: compare] },
  idGetter: [Function (anonymous)],
  dict: {/* gigantic list of chats from my personal whatsapp*/},
  array: [/* gigantic list of chats from my personal whatsapp*/]
}
```

**Expected behavior**
`loadChats` should be a paginated version of `getChats`, however, nothing is being returned

**Environment (please complete the following information):**
 - Is this on a server? No, it's from my personal computer
 - What do your `connectOptions` look like?
```javascript
{
  maxIdleTimeMs: 60000,
  maxRetries: 10,
  connectCooldownMs: 4000,
  phoneResponseTime: 15000,
  alwaysUseTakeover: true
}
```
 - Do you have multiple clients on the same IP? Nope, just 1.
 - Are you using a proxy? No

**Additional context**
`conn.on("open"`:
```javascript
{
  user: {
    jid: 'redacted',
    name: 'redacted',
    phone: {
      wa_version: '2.21.2.18', // Also tested with 2.21.1.16 before updating to the latest (2.21.2.18) version
      mcc: '724',
      mnc: '010',
      os_version: '10',
      device_manufacturer: 'samsung',
      device_model: 'j8y18lte',
      os_build_number: 'QP1A.190711.020.J810MUBU2CTJ3'
    },
    imgUrl: 'redacted'
  },
  newConnection: false,
  isNewUser: true
}
```

package.json:
```javascript
"@adiwajshing/baileys": "^3.4.1"
```

**Comment by adiwajshing** [comment]
Can you check it out on the latest commit and see if works?

**Comment by NicolasCaous** [comment]
@adiwajshing Just tested it, same thing:

```javascript
Connected
{ chats: [], cursor: undefined }
KeyedDB {
  key: { key: [Function: key], compare: [Function: compare] },
  idGetter: [Function (anonymous)],
  dict: {},
  array: []
}
```

Just for you to be sure that I have actually checked out the latest commit:

The latest change on master was the isOnWhatsAppNoConn location header fix, this is what my compiled node_modules looks like:
```javascript
       /**
         * Query whether a given number is registered on WhatsApp, without needing to open a WS connection
         * @param str phone number/jid you want to check for
         * @returns undefined if the number doesn't exists, otherwise the correctly formatted jid
         */
        this.isOnWhatsAppNoConn = async (str) => {
            let phone = str.split('@')[0];
            const url = `https://wa.me/${phone}`;
            const response = await this.fetchRequest(url, 'GET', undefined, undefined, undefined, false);
            const loc = response.headers.location; // <- Fix is here
...
```

**Comment by NicolasCaous** [comment]
# Unrelated:

Also, I have noticed that the latest commit on master adds an `auth` property to the `open` handler. That is really nice, but I think that `encKey` and `macKey` should be converted to base64 to maintain consistency.

```javascript
auth: {
    clientID: 'redacted base64',
    serverToken: 'redacted base64',
    clientToken: 'redacted base64',
    encKey: <Buffer redacted buffer>,
    macKey: <Buffer redacted buffer>
  }
```

**Comment by Okcor** [comment]
If you aren't already, make sure you check the chats after the `received-initial-data` event https://github.com/adiwajshing/Baileys/issues/333

**Comment by NicolasCaous** [comment]
is `received-initial-data always` fired?

**Comment by NicolasCaous** [comment]
The `received-initial-data` event and `initial-data-received` (don't know which is  the correct one) isn't being fired. I have tested both.

**Comment by NicolasCaous** [comment]
On the latest version (9edef50), `initial-data-received` is being fired but with an empty payload:
```javascript
{ chatsWithMissingMessages: [] }
```

**Comment by NicolasCaous** [comment]
Update:

It works after a few tries:

```javascript
Connected
Attempt 1 { chats: [], cursor: undefined }
Attempt 2 { chats: [], cursor: undefined }
Attempt 3 {
  chats: [
    {
// REDACTED
    }
  ],
  cursor: '160207cca5511997365087@s.whatsapp.net'
}
Attempt 4 {
  chats: [
    {
// REDACTED
    }
  ],
  cursor: '160207cca5511997365087@s.whatsapp.net'
}
Attempt 5 {
  chats: [
    {
// REDACTED
    }
  ],
  cursor: '160207cca5511997365087@s.whatsapp.net'
}
```

**Comment by Okcor** [comment]
Sorry, I made a typo. It is `initial-data-received`, the other one doesn't exist.

The latest build recently changed stuff (Since the main android app also changed), so maybe stuff is still broken.

**Comment by adiwajshing** [comment]
@NicolasCaous The connection does not wait for chats to be received. 
@Okcor is right, you need to listen for this event and only then go ahead with the chat loading.

Eg. code:
``` ts
conn.on('initial-data-received', () => {
   console.log(await conn.loadChats(1))
})
```

**Comment by NicolasCaous** [comment]
After adapting my script to wait for the initial data, it works perfectly

```javascript
Connecting...  
{
  user: {
    ...
  },
  auth: {
    ...
  },
  isNewUser: true
}
Connected
Waiting initial data...
{ chatsWithMissingMessages: [] }
Initial data received
{
  chats: [
    {
      jid: '...',
      count: 2,
      name: 'Família Silvestre Nasci',
      t: 1612786180,
      mute: '1634475323',
      message: 'true',
      modify_tag: '790668',
      spam: 'false',
      messages: [KeyedDB]
    }
  ],
  cursor: '160212a045511973438356-1490203977@g.us'
}
The end!
Closing connection
Connection closed
Done in 11.22s.
```

@adiwajshing So is this intended behavior? Maybe it should be better documented.

**Comment by adiwajshing** [comment]
@NicolasCaous the chats-received event and general connection logic is covered [here](https://github.com/adiwajshing/Baileys#connecting)

**Comment by NicolasCaous** [comment]
@adiwajshing thank you for your quick support. This is a wonderful library! :)
