### ISSUE TITLE
[BUG] On credentials-updated dosen't fire. 

### ISSUE THREAD

**Issue by AlenSaito1** [adiwajshing/Baileys#353]
**Description**
On credentials-updated dosen't fire. 

**To Reproduce**

Create code

```TS

import { WAConnection, MessageType, ReconnectMode } from '@adiwajshing/baileys';
import * as fs from 'fs-extra'

...
    let id = 'test'
    const client = new WAConnection()
    client.autoReconnect = ReconnectMode.onConnectionLost
    client.logger.level = 'fatal'; 
    client.connectOptions.maxRetries = 10;
    client.on('qr', (qr) => console.log(qr))
    client.on('credentials-updated', () => {
        console.log(chalk.green('CREDENTIALS UPDATED'))
        const authInfo = client.base64EncodedAuthInfo()
        fs.writeFileSync(`${id}.json`, JSON.stringify(authInfo, null, '\t'))
    })
    fs.existsSync(`${id}.json`) && client.loadAuthInfo(`${id}.json`)
    await client.connect()

```

**Expected behavior**
It was supposed to log and save the auth info after scanning the QR Code

**Environment**
 - Is this on a server? -Yes
 - What do your `connectOptions` look like?  
 ```JS
{
  maxIdleTimeMs: 60000,
  maxRetries: 10,
  connectCooldownMs: 4000,
  phoneResponseTime: 15000,
  alwaysUseTakeover: true
}
```
 - Do you have multiple clients on the same IP? -No
 - Are you using a proxy? -No

**Additional context**
***Screenshot***
![1612321264549 remmina-2021-2-9-11_48_38 762869](https://user-images.githubusercontent.com/66544823/107360299-bb801100-6afb-11eb-9bed-e5ca52c30729.jpg)
SS Context: it didn't log 'CREDENTIALS UPDATED'

-It used to log credentials updated from time to time till a few days ago
-It started happening like 2-3 days ago

**Comment by AlenSaito1** [comment]
Sorry, Should have read the paid attentions to the commits.

**Comment by sidvenu** [comment]
@AlenSaito1 I'm having the same problem, what resolved your issue?

**Comment by AlenSaito1** [comment]
> @AlenSaito1 I'm having the same problem, what resolved your issue?
When its connected it fires `open`

**Comment by felangga** [comment]
Having the same problem too

**Comment by waghcwb** [comment]
I'm having the same issue `credentials-updated` is not firing. But `conn.on('open')` seems to work.
