### ISSUE TITLE
Is it possible to cancel sending a message after timeout?

### ISSUE THREAD

**Issue by olezhko9** [adiwajshing/Baileys#355]
Hello! Can you help me with one problem?

If the phone has connection problems while sending a message, the message cannot be delivered right now. However, when the connection is restored, the message will be delivered. Is it possible to completely cancel sending a message if it was not sent, for example, in the first 10 seconds?

I am using a HTTP-request to send a message, and it is important for me to get the result of sending in ~15 seconds. Now I am running:
```javascript
await Promise.race([
  WAClient.sendMessage(jid, text, MessageType.text),
  new Promise((resolve, reject) => { setTimeout(reject, config.sendTimeoutMs, new Error('Timeout')) })
])
```
But even if this code returns an Timeout error, then when the connection is restored on the phone, the message will still be sent.

**Comment by keef3ar** [comment]
is anyone knows a solution? i have the same situation

**Comment by olezhko9** [comment]
> is anyone knows a solution? i have the same situation

I am happy to announce that I have found a possible solution. Here it is:
The connection instance has a field __event_. This field stores the request callbacks. When you make send message request, a new callback is created, and the key of this starts with "TAG". To prevent delivery of this message when the connection is restored, you must remove this key from the __event_ object.
**Warning!** It is possible to remove callbacks for other requests that would like to be done.

Here's how I do it
```JavaScript
for (let key of Object.keys(WAClient._events)) {
  if (key.indexOf('TAG') !== -1) {
    delete WAClient._events[key]
  }
}
```
