### ISSUE TITLE
Stories Privacy

### ISSUE THREAD

**Issue by jovazxc** [adiwajshing/Baileys#356]
Hi, im trying to set status privacy but im unable to get it working

Im trying with this piece of code
`
 await conn.query({
                json: ['StatusV3', { type: 'privacy', whitelist: ['phonenumber@c.us'] }]
            })
`

Any help will be appreciated

Based on whatsapp debugging it says this

`s18,["StatusV3",{"type":"privacy","whitelist":["52xxxxxxxxxxx@c.us"]}]`

**Comment by fdciabdul** [comment]
can you attach the error to here ?

**Comment by jovazxc** [comment]
Nothing appears on the console, it just return an object, 

`{status:400}`

**Comment by jovazxc** [comment]
@adiwajshing can you help me?
