### ISSUE TITLE
How to send description or caption on location message

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#357]
I was using {caption: 'message'} but not sending the description in the location message

**Comment by lxndr-rl** [comment]
this type of message doesnt support caption

**Comment by ianmsfvenom** [comment]
![Screenshot_11](https://user-images.githubusercontent.com/57237342/107858179-a237d700-6e11-11eb-8187-5649a75338a6.png)

**Comment by ianmsfvenom** [comment]
I want the bot to send a message like this
