### ISSUE TITLE
Bug to gif not play

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#360]
I'm using this code 
`client.sendMessage(from, buffer, MessageType.video, {mimetype: Mimetype.gif})`
but even so when the bot sends gif it doesn't start

**Comment by phaticusthiccy** [comment]
> I'm using this code
> `client.sendMessage(from, buffer, MessageType.video, {mimetype: Mimetype.gif})`
> but even so when the bot sends gif it doesn't start

Hey, can you send whole code. Cauze there is no problem with mimetype. Its working perfectly.
