### ISSUE TITLE
How To Detect Deleted Message? 

### ISSUE THREAD

**Issue by tegzxy** [adiwajshing/Baileys#363]
Send Message On Deleted Message From User.
Message deletion detection currently appears only in the console.log. I want that message send to conversation
For Example :

```[ ⚠️ DELETED MESSAGE INFO ⚠️ ]

Name : ${pushname}
Tipe : MessageType
Time :  Time
Message : ${text}

Please Help Me.

**Comment by lxndr-rl** [comment]
If you want a logger you need save all new messages and when a message is revoke compare ID



I have no idea if it can be done in another simpler way but this would work.

![image](https://user-images.githubusercontent.com/47733425/108548550-fc291880-72b9-11eb-9e3a-84e0a1c3c66c.png)
![image](https://user-images.githubusercontent.com/47733425/108548556-00553600-72ba-11eb-8a3a-ee330d9576c0.png)


Code:
```javascript
let messageLogger = []  //declare a variable to save message

client.on('chat-update', async (message) => { 

if (!message.hasNewMessage) {
   try {
	if (JSON.parse(JSON.stringify(message)).messages[0].messageStubType == 'REVOKE') {
		for (let i = 0; i <= messageLogger.length; i++) {
			if (JSON.parse(JSON.stringify(message)).messages[0].key.id == messageLogger[i].messages[0].key.id) {
				messagedeleted = messageLogger[i].messages[0].message.conversation
				console.log('A message has been deleted: ', messagedeleted)
			}
		}

	}
   } catch { }
} else {
	messageLogger.push(JSON.parse(JSON.stringify(message)))
}

...
})
```
If you optimize it please share your code ;)

**Comment by MRHRTZ** [comment]
@tegzxy 

![Screenshot_2021-02-24-00-20-41-499_com whatsapp w4b](https://user-images.githubusercontent.com/52845610/108881789-4998e300-7636-11eb-8bf0-01ed542f5a3c.jpg)


Like this?

**Comment by lxndr-rl** [comment]
> Like this?

I think that's what he wants

**Comment by bilal-08** [comment]
> If you want a logger you need save all new messages and when a message is revoke compare ID
> 
> I have no idea if it can be done in another simpler way but this would work.
> 
> ![image](https://user-images.githubusercontent.com/47733425/108548550-fc291880-72b9-11eb-9e3a-84e0a1c3c66c.png) ![image](https://user-images.githubusercontent.com/47733425/108548556-00553600-72ba-11eb-8a3a-ee330d9576c0.png)
> 
> Code:
> 
> ```js
> let messageLogger = []  //declare a variable to save message
> 
> client.on('chat-update', async (message) => { 
> 
> if (!message.hasNewMessage) {
>    try {
> 	if (JSON.parse(JSON.stringify(message)).messages[0].messageStubType == 'REVOKE') {
> 		for (let i = 0; i <= messageLogger.length; i++) {
> 			if (JSON.parse(JSON.stringify(message)).messages[0].key.id == messageLogger[i].messages[0].key.id) {
> 				messagedeleted = messageLogger[i].messages[0].message.conversation
> 				console.log('A message has been deleted: ', messagedeleted)
> 			}
> 		}
> 
> 	}
>    } catch { }
>    return
> } else {
> 	messageLogger.push(JSON.parse(JSON.stringify(message)))
> }
> 
> ...
> })
> ```
> 
> If you optimize it please share your code ;)

I couldn't find the messageStubType any  updates?
