### ISSUE TITLE
Clearing Log INFO

### ISSUE THREAD

**Issue by sProDev** [adiwajshing/Baileys#365]
Hi there, can I hide the INFO log as below? because I want to customize console.log which will appear in my own format, hehe
```
INFO [2021-02-20 03:44:47.143 +0000] (15036): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
```

**Comment by LuanLRT** [comment]
Just add this to your code and they'll be hidden.
`conn.logger.level = 'warn';`

**Comment by sProDev** [comment]
> Just add this to your code and they'll be hidden.
> `conn.logger.level = 'warn';`

Wow this is working, thank you very much for your help
