### ISSUE TITLE
Event close show warning memory leak

### ISSUE THREAD

**Issue by anaphalis777** [adiwajshing/Baileys#366]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues ✔️
2. Read through the readme at least once ✔️
3. Search the docs for the feature you're looking for ✔️

**Just describe the question**
Hello when am listen event close, then i awalys got warning about memory leak
`(node:26017) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 ws-close listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)`

Is the warning message alright? in my condition i have listened 10+ instance WAConnection, then after several minutes my node instace got crashed, and the reason node crashed because memory leak issues

**Comment by adiwajshing** [comment]
It's likely that you may not be releasing the events. If you show your code, I could possibly help.

**Comment by anaphalis777** [comment]
sure @adiwajshing 

`const {
  WAConnection,
  ReconnectMode,
  waChatKey,
} = require("@adiwajshing/baileys");
const fs = require("fs");

(async () => {
  global.instances = new WAConnection();
  global.instances.autoReconnect = ReconnectMode.onConnectionLost;
  global.instances.logger.level = "info";

  global.instances.regenerateQRIntervalMs = null;
  global.instances.connectOptions.maxRetries = 2;
  global.instances.chatOrderingKey = waChatKey(true);

  global.instances.on("close", () => {
    // TODO: handling close
  });

  global.instances.on("chats-received", async ({ hasNewChats }) => {
    if (hasNewChats) {
      let unreadMessages = await global.instances.loadAllUnreadMessages();
      console.log(
        `chats-received (loadUnreadMessages) : ${unreadMessages.length}`
      );
    }
  });

  global.instances.on("qr", (datas) => {
    console.log(datas);
  });

  global.instances.on("credentials-updated", () => {
    console.log("save sessions !!");
    fs.writeFileSync(
      "./creds.json",
      JSON.stringify(global.instances.base64EncodedAuthInfo(), null, "\t")
    );
  });

  fs.existsSync("./creds.json") &&
    global.instances.loadAuthInfo("./creds.json");

  await global.instances.connect().catch((err) => {
    if (err.status > 400) {
      console.log(`remove devices from database !!`);
      fs.unlinkSync("./creds.json");
    }
  });
})();
`

**Comment by anaphalis777** [comment]
any update sir @adiwajshing ?
