### ISSUE TITLE
How to send message upon start?

### ISSUE THREAD

**Issue by LilSadPanda** [adiwajshing/Baileys#367]
Hello I'd like to send a message upon bot start

**Comment by zorox-1** [comment]
you can check [https://adiwajshing.github.io/Baileys/#handling-events ](https://adiwajshing.github.io/Baileys/#handling-events). there are list of events that can trigger any action.

**Comment by LilSadPanda** [comment]
> 
> 
> you can check [https://adiwajshing.github.io/Baileys/#handling-events ](https://adiwajshing.github.io/Baileys/#handling-events). there are list of events that can trigger any action.

Thanks. Yeah I made a simple problem and couldnt fugure out why its not working
