### ISSUE TITLE
[problem or bug?] GroupSettingChange.settingChange not working

### ISSUE THREAD

**Issue by karmaisgreat** [adiwajshing/Baileys#368]
// allow everyone to modify the group's settings -- like display picture etc.
await conn.groupSettingChange ("abcd-xyz@g.us", GroupSettingChange.settingChange, false)
// only allow admins to modify the group's settings
await conn.groupSettingChange ("abcd-xyz@g.us", GroupSettingChange.settingChange, true)

When ever i try to use GroupSettingChange.settingChange i get:

UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'action': Unauthorized(401)

is it only mine issue or bug? Please help...

**Comment by adiwajshing** [comment]
The error is telling you the problem -- you don't have access to change the settings on the group you're trying to modify
