### ISSUE TITLE
Timeout on restore session.

### ISSUE THREAD

**Issue by ev4ndropc** [adiwajshing/Baileys#37]
Dude, the api is good, but when restoring the session or even opening a new session, there is a very long timeout error, every 10 times I try to connect, 1 connects and the other 9 times out (not necessarily that value, is an estimate).

**Comment by ev4ndropc** [comment]
I checked, the following message appears in the application.

`"Couldn't connect, make sure you're on web.whatsapp.com"`

**Comment by adiwajshing** [comment]
I’m glad you like the API, but I think that’s an internet connectivity issue.

**Comment by adiwajshing** [comment]
Assuming its resolved, closing.
