### ISSUE TITLE
[BUG] loadAllMessages doesn't load all messages

### ISSUE THREAD

**Issue by NilsIrl** [adiwajshing/Baileys#372]
**Describe the bug**

`loadAllMessages`, doesn't all messages. I have a conversation with about 60k messages and only around 23k are loaded.

**To Reproduce**

1. Created a new connection

```ts
        let count = 0;
        await conn.loadAllMessages(jid, async message => {
          count += 1;
          if (count % 100 == 0)
            console.log(count)
        });
```

Even though there are about 60k messages, this will only output up to around 23k. I tried increasing and decreasing the chunkSize and it did help. What seems to happen is that it will not accept any additional chunk over 23k. Which means that if the chunk size is 10k, we can load 30k messages and if the chunk size is 20k we can load 40k. In my case, I set the chunk size to 100k which allowed me to load all 60k messages.

**Expected behavior**

Regardless of the `chunkSize`, all 60k messages are returned.

**Comment by adiwajshing** [comment]
Interesting. Can you log the message counts for the last few chunks you receive before it halts at 23K?

**Comment by NilsIrl** [comment]
with a `chunkSize` of 1: 4281, 22609
with a `chunkSize` of 25: 24148, 22225
with a `chunkSize` of 100: 24198
with a `chunkSize` of 1000: 24998
with a `chunkSize` of 10000: 29996, 29996
with a `chunkSize` of 70000: 61911
with a `chunkSize` of 100000: 61911

Note on large chunkSizes (over 10000?) I get the following message:

```
INFO     [2021-02-27 13:12:22.181 +0000] (27406): checking phone connection...
    class: "Baileys"
```

But it doesn't seem to affect anything.

conclusion: I have no clue what is going on, it seems somewhat random.
