### ISSUE TITLE
[BUG] - Sender Definition

### ISSUE THREAD

**Issue by JoseCarlos056** [adiwajshing/Baileys#375]
**Describe the bug**

In the example.ts file there is the definition of sender in the event "chat-update" but this definition seeks a non-existent data.

` let sender = m.key.remoteJid
        if (m.key.participant) {
            // participant exists if the message is in a group
            sender += ' (' + m.key.participant + ')'
        }`
replace to:
`      let sender = m.key.remoteJid
        if (m.participant) {
            // participant exists if the message is in a group
            sender += ' (' + m.participant + ')'
        }`

**Comment by adiwajshing** [comment]
Weirdly enough -- both these properties can be present in a message

**Comment by JoseCarlos056** [comment]
Tks!
