### ISSUE TITLE
unable to run example.js

### ISSUE THREAD

**Issue by alucionet** [adiwajshing/Baileys#376]
Hello, 

Can anybody help me with new install issue as follows?
Platform: Linux CentOS 7

[mauah@xena Baileys-master]$ node --version
v6.17.1

[mauah@xena Baileys-master]$ npm test

> @adiwajshing/baileys@4.0.0 test /home/mauah/Downloads/baileys/Baileys-master
> mocha --timeout 240000 -r ts-node/register src/Tests/Tests.*.ts

/home/mauah/Downloads/baileys/Baileys-master/node_modules/mocha/lib/errors.js:173
const MOCHA_ERRORS = new Set(Object.values(constants));
                                    ^

TypeError: Object.values is not a function
    at Object.<anonymous> (/home/mauah/Downloads/baileys/Baileys-master/node_modules/mocha/lib/errors.js:173:37)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mauah/Downloads/baileys/Baileys-master/node_modules/mocha/lib/utils.js:16:16)
    at Module._compile (module.js:577:32)
npm ERR! Test failed.  See above for more details.

npm run example

> @adiwajshing/baileys@4.0.0 example /home/mauah/Downloads/baileys/Baileys-master
> node --inspect -r ts-node/register Example/example.ts

Debugger listening on 127.0.0.1:9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/d4f1364f-9fb9-4e44-be7e-31cee6e91317
/home/mauah/Downloads/baileys/Baileys-master/Example/example.ts:24
async function example() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Module.m._compile (/home/mauah/Downloads/baileys/Baileys-master/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (module.js:586:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/mauah/Downloads/baileys/Baileys-master/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)

npm ERR! Linux 3.10.0-1160.6.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "example"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @adiwajshing/baileys@4.0.0 example: `node --inspect -r ts-node/register Example/example.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @adiwajshing/baileys@4.0.0 example script 'node --inspect -r ts-node/register Example/example.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @adiwajshing/baileys package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --inspect -r ts-node/register Example/example.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @adiwajshing/baileys
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @adiwajshing/baileys
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mauah/Downloads/baileys/Baileys-master/npm-debug.log

[mauah@xena Baileys-master]$ more npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'example' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'preexample', 'example', 'postexample' ]
5 info lifecycle @adiwajshing/baileys@4.0.0~preexample: @adiwajshing/baileys@4.0.0
6 silly lifecycle @adiwajshing/baileys@4.0.0~preexample: no script for preexample, continuing
7 info lifecycle @adiwajshing/baileys@4.0.0~example: @adiwajshing/baileys@4.0.0
8 verbose lifecycle @adiwajshing/baileys@4.0.0~example: unsafe-perm in lifecycle true
9 verbose lifecycle @adiwajshing/baileys@4.0.0~example: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mauah/Downloads
/baileys/Baileys-master/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/mauah/.local/bin:/home/mauah
/bin
10 verbose lifecycle @adiwajshing/baileys@4.0.0~example: CWD: /home/mauah/Downloads/baileys/Baileys-master
11 silly lifecycle @adiwajshing/baileys@4.0.0~example: Args: [ '-c',
11 silly lifecycle   'node --inspect -r ts-node/register Example/example.ts' ]
12 silly lifecycle @adiwajshing/baileys@4.0.0~example: Returned: code: 1  signal: null
13 info lifecycle @adiwajshing/baileys@4.0.0~example: Failed to exec example script
14 verbose stack Error: @adiwajshing/baileys@4.0.0 example: `node --inspect -r ts-node/register Example/example.ts`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid @adiwajshing/baileys@4.0.0
16 verbose cwd /home/mauah/Downloads/baileys/Baileys-master
17 error Linux 3.10.0-1160.6.1.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "example"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @adiwajshing/baileys@4.0.0 example: `node --inspect -r ts-node/register Example/example.ts`
22 error Exit status 1
23 error Failed at the @adiwajshing/baileys@4.0.0 example script 'node --inspect -r ts-node/register Example/example.ts'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the @adiwajshing/baileys package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node --inspect -r ts-node/register Example/example.ts
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs @adiwajshing/baileys
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls @adiwajshing/baileys
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by barkerpedro** [comment]
Apparently your version of the "node/npm" is old.
Update the node and then update the npm: 
```bash
npm i npm -g
```

**Comment by alucionet** [comment]
Just update node, and now it has different error:

[mauah@xena Baileys-master]$ node run example
node:internal/modules/cjs/loader:926
  throw err;
  ^

Error: Cannot find module '/home/mauah/Downloads/baileys/Baileys-master/run'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[mauah@xena Baileys-master]$ node --version
v15.10.0

**Comment by alucionet** [comment]
works like a charm. thanks
