### ISSUE TITLE
Event "new-message" deprecated.

### ISSUE THREAD

**Issue by JoseCarlos056** [adiwajshing/Baileys#377]
What reason to mark the event "new message" as deprecated ?

**Comment by adiwajshing** [comment]
Because `chat-update` takes care of all kinds of updates to a chat -- including `new message`

**Comment by JoseCarlos056** [comment]
Ok, sorry.

**Comment by dcdunkan** [comment]
@adiwajshing  You should update README's [this part](https://github.com/adiwajshing/Baileys#downloading-media-messages). This contains a code block which uses "message-new" update event.
