### ISSUE TITLE
Would it be possible to test the connection with the cell phone?

### ISSUE THREAD

**Issue by cassiano-guardianserver** [adiwajshing/Baileys#378]
Sometimes the "close" or "connection-phone-change" event does not arrive and in fact the connection is no longer active.

I know this because when I try to send a message it gives an error and the "close" event arrives but if a message arrives before that, the "message-new" event does not arrive.

**Comment by adiwajshing** [comment]
You can run a poll to ping the phone every few seconds -- this will ensure you don't miss any messages.
Eg.
``` ts
// this is a protected property as of now
setInterval(() => conn.sendAdminTest(), 30_000) // poll every 30s
```

**Comment by barkerpedro** [comment]
In conn.sendMessage it has a behavior that verifies the phoneConnected = true. Would there be any way to force this phoneConnected into my application, for example to use with conn.isOnWhatsApp?

**Comment by cassiano-guardianserver** [comment]
I will do these tests in my application. Thanks!

**Comment by barkerpedro** [comment]
> ```ts
> setInterval(() => conn.sendAdminTest(), 30_000)
> ```

How can I get the return of this function?

**Comment by barkerpedro** [comment]
I achieved:

```node
setInterval(() => conn.query({ json: ['admin', 'test'] })
  .then((response) => {
    console.log(response);
  }), 5_000);
```
