### ISSUE TITLE
[BUG] GIFs Doesn't play in WA

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#383]
GIFs are sent but not played.
`            
await connWA.sendMessage(
    jid,
    fs.readFileSync(data.path),
    MessageType.video,
    {mimetype: Mimetype.gif}
)
`
![photo_2021-03-01_20-54-44](https://user-images.githubusercontent.com/48887908/109537928-88b0b380-7ad0-11eb-9b52-a35cc0cd1287.jpg)

**Comment by ilyaborodin** [comment]
Gifts should be send only in .mp4 format. For convert .gif to .mp4 user:
ffmpeg -i animated.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" video.mp4

**Comment by Pegorino82** [comment]
> Gifts should be send only in .mp4 format. For convert .gif to .mp4 user: ffmpeg -i animated.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" video.mp4

Hi, could you show how to use it with remote url gif?
