### ISSUE TITLE
[BUG] RequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by Claver888** [adiwajshing/Baileys#385]
**Describe the bug**
downloadAndSaveMediaMessage does not work in docker, I get the error indicated below, I haven’t tried it without docker, I’m sure it’s business, but docker is needed

**To Reproduce**
1) I used express zhs and docker,
2) tried to download media from post

**Expected behavior**
I'm waiting for the file to download from the message, but I get an error

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**
backend_nodejs       | RequestError: connect ECONNREFUSED 127.0.0.1:443
backend_nodejs       |     at ClientRequest.<anonymous> (/backend_nodejs/node_modules/got/dist/source/core/index.js:953:111)
backend_nodejs       |     at Object.onceWrapper (events.js:422:26)
backend_nodejs       |     at ClientRequest.emit (events.js:327:22)
backend_nodejs       |     at ClientRequest.EventEmitter.emit (domain.js:467:12)
backend_nodejs       |     at ClientRequest.origin.emit (/backend_nodejs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
backend_nodejs       |     at TLSSocket.socketErrorListener (_http_client.js:469:9)
backend_nodejs       |     at TLSSocket.emit (events.js:315:20)
backend_nodejs       |     at TLSSocket.EventEmitter.emit (domain.js:467:12)
backend_nodejs       |     at emitErrorNT (internal/streams/destroy.js:106:8)
backend_nodejs       |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
backend_nodejs       |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

**Comment by adiwajshing** [comment]
This isn't a bug with Baileys but likely an issue with your docker environment

**Comment by Claver888** [comment]
> This isn't a bug with Baileys but likely an issue with your docker environment

Then please explain why it is trying to connect to 127.0.0.1:443, what should work on this port?

**Comment by Claver888** [comment]
![image](https://user-images.githubusercontent.com/77071445/110347433-ad150e80-8041-11eb-9980-6632334bd8d9.png)
Without a docker, the same problem (

**Comment by Claver1000** [comment]
> This isn't a bug with Baileys but likely an issue with your docker environment

On my server port 443 is occupied by another site, how can I get around this?

**Comment by Claver1000** [comment]
> Это не ошибка Baileys, а скорее всего проблема в вашей среде докеров.

Help? please

**Comment by Cosangeles22** [comment]
I have the same problem, no docker, please tell me where to dig ...
