### ISSUE TITLE
Problems establishing a connection

### ISSUE THREAD

**Issue by SuyKingsleigh** [adiwajshing/Baileys#388]
Hello, sometimes, when I try to connect, it got stuck at 

"connect attempt 3 failed, retrying…"
"connected to WhatsApp Web server, authenticating via takeover" 

the phone is connected and I can send and receive messages on it. 

I have the following configs: 

    conn.connectOptions.alwaysUseTakeover = true;
    conn.connectOptions.phoneResponseTime = 30_000;
    conn.connectOptions.maxIdleTimeMs = 45_000; 
    
 What should I do? 

 Thanks in advance.

**Comment by adiwajshing** [comment]
Can you show the full logs?

**Comment by SuyKingsleigh** [comment]
INFO	 [2021-03-08 11:04:01.858 +0000] (13996): loading authentication credentials from /usr/local/profiles/auth_info.json
    class: "Baileys"
INFO	 [2021-03-08 11:04:02.147 +0000] (13996): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
WARN	 [2021-03-08 11:04:17.330 +0000] (13996): connect attempt 1 failed, retrying...
    class: "Baileys"
INFO	 [2021-03-08 11:04:20.565 +0000] (13996): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
WARN	 [2021-03-08 11:04:35.720 +0000] (13996): connect attempt 2 failed, retrying...
    class: "Baileys"
INFO	 [2021-03-08 11:04:38.963 +0000] (13996): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
WARN	 [2021-03-08 11:04:54.113 +0000] (13996): connect attempt 3 failed, retrying...

I believe this is not exactly a problem, but something related to phone's bad connection, although I'd like to know if there's anything I could do.
