### ISSUE TITLE
[BUG] Sending Image (marker not found)

### ISSUE THREAD

**Issue by ikheetjeff** [adiwajshing/Baileys#389]
I got a error when i send a Whatsapp message with a media URL:

`Error: marker was not found at decodeScan (/projects/whatsapp/complimaatje/node_modules/jpeg-js/lib/decoder.js:344:15) at constructor.parse (/projects/whatsapp/complimaatje/node_modules/jpeg-js/lib/decoder.js:804:29) at Object.decode [as image/jpeg] (/projects/whatsapp/complimaatje/node_modules/jpeg-js/lib/decoder.js:1096:11) at Jimp.parseBitmap (/projects/whatsapp/complimaatje/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53) at Jimp.parseBitmap (/projects/whatsapp/complimaatje/node_modules/@jimp/core/dist/index.js:431:32) at /projects/whatsapp/complimaatje/node_modules/@jimp/core/dist/index.js:373:15 at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:75:3) { methodName: 'constructor' }`

Code:
`await client.sendMessage('<number>@s.whatsapp.net', { url: 'https://i.imgur.com/m9VKjJf.jpg' }, MessageType.image,{ mimetype: Mimetype.png, caption: "hello!" });`

If i add "thumbnail: null" to options, i don't get the error. But i want a tumbmail, is there a fix?

**Comment by barkerpedro** [comment]
I had the same problem in #358 and it was not solved, I am using version 3.4.1.

**Comment by ianmsfvenom** [comment]
`const download = require('image-downloader')

const options = {
  url: 'http://someurl.com/image.jpg',
  dest: '/path/to/dest'               
}

download.image(options)
  .then(({ filename }) => {
    await client.sendMessage('<number>@s.whatsapp.net', filename, MessageType.image,{ caption: "hello!" });
  })
  .catch((err) => console.error(err))
`

try download image or use local image

**Comment by ikheetjeff** [comment]
> `const download = require('image-downloader')
> 
> const options = {
> url: 'http://someurl.com/image.jpg',
> dest: '/path/to/dest'
> }
> 
> download.image(options)
> .then(({ filename }) => {
> await client.sendMessage('@s.whatsapp.net', filename, MessageType.image,{ caption: "hello!" });
> })
> .catch((err) => console.error(err))
> `
> 
> try download image or use local image

Don’t work, get the same error.

**Comment by auyeung112002** [comment]
Same here. There are some issues related.
https://github.com/adiwajshing/Baileys/issues/438
https://github.com/adiwajshing/Baileys/issues/358

The problem seems to be reading incomplete image file(written by encryptedStream() ) from /tmp when generating thumbnail. Don't why the image written to /tmp is sometimes broken. I tried sending the same image(jpg) multiple times and this issue happened randomly.

https://github.com/adiwajshing/Baileys/blob/5dfeaf75b0ae474ab11d9632f2695a7de5e0ce76/src/WAConnection/Utils.ts#L331

https://github.com/adiwajshing/Baileys/blob/5dfeaf75b0ae474ab11d9632f2695a7de5e0ce76/src/WAConnection/Utils.ts#L247

**Comment by mi-khatri** [comment]
here is solution for me

#install request
----------------------
npm install request --save

#define funcion
----------------------

var download = function(uri, filename, callback) {
  var request = require('request');
  request.head(uri, function(err, res, body) {
      console.log('content-type:', res.headers['content-type']);
      console.log('content-length:', res.headers['content-length']);

      request(uri).pipe(fs.createWriteStream(filename)).on('close', callback);
  });
};

# and use it
-------------------

  var dFile = 'file.png';
  download(fileUrl, dFile, function() {
  
  conn.sendMessage(
      id, 
      { url: dFile }, // send from local url!
      MessageType.image, 
      {  mimetype: Mimetype.png, caption: 'caption'  }
  )

Thats it !!!
