### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by matibm** [adiwajshing/Baileys#390]
**Describe the bug**
Sticker of gif not works
**To Reproduce**
I send the sticker webp of gif but it looks like an img sticker
  
![image](https://user-images.githubusercontent.com/50302609/110407162-2cb2d580-8062-11eb-8da7-304fe81c3dc3.png)

**Additional context**
the wepb file works fine, but in chat it looks like a sticker without movement

**Comment by mqad21** [comment]
Does the gif file have square dimension?  Try to make it square and it's work fine.
