### ISSUE TITLE
HOW TO DETECT CALL?

### ISSUE THREAD

**Issue by kikiixyz** [adiwajshing/Baileys#392]

**Comment by kikiixyz** [comment]
thanks

**Comment by kikiixyz** [comment]
> Try this:
> 
> ```js
> conn.on('CB:action,,call', async json => {
>         const callerId = json[2][0][1].from;
>         console.log(`[WARN] ${callerId.split('@')[0]} is calling!`);
> });
> ```

may I ask one more question ?,
how do you detect our message readers in the group?

**Comment by ibnusyawall** [comment]
> > Try this:
> > ```js
> > conn.on('CB:action,,call', async json => {
> >         const callerId = json[2][0][1].from;
> >         console.log(`[WARN] ${callerId.split('@')[0]} is calling!`);
> > });
> > ```
> 
> may I ask one more question ?,
> how do you detect our message readers in the group?

https://github.com/adiwajshing/Baileys/issues/393#issuecomment-797871973
