### ISSUE TITLE
connect attempt 1 failed: Error: connect ETIMEDOUT 157.240.7.54:443

### ISSUE THREAD

**Issue by appocalyp** [adiwajshing/Baileys#396]
I just run npm start, but how can that be

How to Solve it?

**Comment by adiwajshing** [comment]
![学习某课程必读的](https://user-images.githubusercontent.com/8328864/111807802-5c32cf00-88f9-11eb-8693-160630aa0c7a.JPG)

**Comment by MFarelS** [comment]
WKWKWKWKWK

**Comment by Zalleya** [comment]
ajg wkwkwk
