### ISSUE TITLE
How to send archive .apk

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#399]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by FaizBastomi** [comment]
`client.sendMessage(jid, buffer, MessageType.document, { mimetype: "application/vnd.android.package-archive" })`

i hope it works

**Comment by ianmsfvenom** [comment]
thxxx

**Comment by creuza** [comment]
And a PDF??

**Comment by FaizBastomi** [comment]
> And a PDF??

for pdf is
```js
client.sendMessage(jid, buffer, document, { mimetype: "application/pdf" })
```
