### ISSUE TITLE
Check if number has WhatsApp

### ISSUE THREAD

**Issue by cadu3011** [adiwajshing/Baileys#4]
Hi,
is it possible to check whether number has WhatsApp or not?
Thanks a lot!

**Comment by adiwajshing** [comment]
You can write such a query. I haven't implemented this explicitly in the library yet, but would be a cool feature.

**Comment by adiwajshing** [comment]
https://github.com/Rhymen/go-whatsapp

**Comment by adiwajshing** [comment]
This feature has now been implemented. See the readme for an example.
