### ISSUE TITLE
Create a Quick Survey to Remove Participant from Group?

### ISSUE THREAD

**Issue by jzvi12** [adiwajshing/Baileys#40]
I would like to know if it's possible to create a 'Yes' or 'No' question that's triggered by a keyword (when there's a troublemaker in a group) and send it in to ask all participants to vote for the removal of of a particular participant within a group. For example:

BOT says: "How many of you guys want +9100000000 to be removed from group? Please send 'yes' if you agree, or send 'no' if you don't agree."

Then logic would be:

If the 'Yes" voting is greater than 3, then remove '9100000000@c.us' number from group chat...

Is this possible?

Thanks in advance!

**Comment by adiwajshing** [comment]
Yeah, its 100% doable.
