### ISSUE TITLE
Error when trying to log in with saved credentials.

### ISSUE THREAD

**Issue by maxymoo22** [adiwajshing/Baileys#400]
If I don't use `loadAuthInfo`, I can scan the QR code, the app logs in and everything is all good. However, as soon as I save the auth info to a file then use `loadAuthInfo` so I don't have to scan the QR code every time I get some problems. Connect attempt 1 failed, invalid sesion and a `BaileysError`. Log output below:

```
INFO     [2021-03-14 02:32:21.075 +0000] (9916): loading authentication credentials from ./auth_info.json
    class: "Baileys"
INFO     [2021-03-14 02:32:21.439 +0000] (9916): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
WARN     [2021-03-14 02:32:22.008 +0000] (9916): connect attempt 1 failed
    error: {
      "name": "BaileysError",
      "status": 401,
      "context": {
        "query": [
          "admin",
          "login",
          "3 other base64_looking fields here - didn't know if they should be kept private"
          "takeover"
        ],
        "message": "Unauthorized",
        "status": 401
      }
    }
    class: "Baileys"
INFO     [2021-03-14 02:32:22.010 +0000] (9916): closed connection, reason invalid_session
    class: "Baileys"
Unexpected error: BaileysError: Unexpected status in 'admin': Unauthorized(401)
```

It's strange how it works normally but only fails when I use the saved auth info. Shouldn't they just be the same anyway? Saving it like this btw:
```javascript
conn.connect().then(_ => {
    console.log("Started!");

    const authInfo = conn.base64EncodedAuthInfo();
    writeFileSync("./auth_info.json", JSON.stringify(authInfo, null, "\t"));
    console.log("Credentials updated!");
});
```

Maybe I'm saving it incorrectly?

**Comment by adiwajshing** [comment]
@maxymoo22 are you logging out from your phone? Also are you sure you're loading the correct file back in?

**Comment by maxymoo22** [comment]
By "logging out of my phone", do you mean closing the whatsapp application or removing baileys from the list of logged in web devices? I'm not doing either of them, and I believe I'm loading the correct file - I always save to `auth_info` and I always read from `auth_info`.
