### ISSUE TITLE
Full of imageMessageXXXXXXXXX files on /tmp folder

### ISSUE THREAD

**Issue by textarea** [adiwajshing/Baileys#401]
**Describe the bug**
Each time is sent an image message it creates 2 files in /tmp folder, the second one has .enc extension

**To Reproduce**
1. send an image message

**Expected behavior**
Any temporary files should get deleted after message sent

**Environment (please complete the following information):**
 - Is this on a server? Yes, Debian 10
 - What do your `connectOptions` look like? default
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Comment by textarea** [comment]
@adiwajshing why anyone should choose to keep them?

**Comment by adiwajshing** [comment]
I mean them being in the `tmp` folder isn't really an issue

**Comment by textarea** [comment]
Server disk space is not infinite, even if is not a big issue is relevant for me. But I agree with you we, the community, have to contribute to the project. Unfortunately I don't have skills for propose a PR for this issue, hope some other one can take a look.

**Comment by barkerpedro** [comment]
Try:

```shell
npm install shelljs --save-dev
```
```node
(async () => {

    const shell = require("shelljs");

    async function sleep(time) {
        return new Promise(resolve => setTimeout(resolve, time));
    }

    await conn.sendMessage(jid, buffer, MessageType.image, options);
    await sleep(5000);
    await shell.exec("rm -f /tmp/*.enc");

})();
```

**Comment by KeruMx** [comment]
Re-open Issue.
[Error: ENOENT: no such file or directory, open 'C:\Temp\imageMessage3EB0B816FA2D'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\Temp\imageMessage3EB0B816FA2D',
  methodName: 'constructor'
i got this when send20 imageMessage
after 11 then dont send
