### ISSUE TITLE
BaileysError: Not expecting a response

### ISSUE THREAD

**Issue by textarea** [adiwajshing/Baileys#402]
**Describe the bug**
Sometimes, not always, I get this error:
```
BaileysError: Not expecting a response
    at onErr (/var/www/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:188:56)
    at /var/www/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:183:82
    at Timeout.<anonymous> (/var/www/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:270:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  status: 422,
  context: { status: 422 }
}
```

**To Reproduce**
1. send text message, not always 

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? Yes, Debian 10
 - What do your `connectOptions` look like? default
 - Do you have multiple clients on the same IP? Yes
 - Are you using a proxy? No

**Additional context**
Send with success a most of messages, I don't know why some of them fail

**Comment by textarea** [comment]
I suppose this error come out when client is not connected

**Comment by ViniciusCoelhoDeAbreu** [comment]
I'm getting this error when I try to use groupCreate method.

Probably WhatsApp Web updated something.

Anyone has any solution?

**Comment by adiwajshing** [comment]
Hi @textarea can you please mention your WA version? And can you create a message to consistently reproduce the issue?

**Comment by textarea** [comment]
Hi @adiwajshing,
I'm not connected with my device, I see this error for some connected clients in error logs.
One of them, for example, has 2.21.5.17 WA version.
It happens when client has simultaneously: **client.state** = 'open' and **client.phoneConnected** = false

**Comment by guiromer** [comment]
Hi guys! I am with the same issue when I use groupCreate method.

Anyone has come with a solution?

**Comment by luiscuriel** [comment]
Same problem here... random same error when sending messages :(
