### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xolo1** [adiwajshing/Baileys#403]
hi everyone, please fix a bug toggleDisappearingMessages, before people misuse it

Sorry if my English is bad

**Comment by ekoeryanto** [comment]
screenshot or more detail 🥺

**Comment by xolo1** [comment]
If someone uses the command in the group, everyone in the group will crash if they tap the chat

> screenshot or more detail 🥺

If someone uses the command in the group, everyone in the group will crash if they tap the chat, this has no effect on the bot.

**Comment by xolo1** [comment]
![screenshot](https://user-images.githubusercontent.com/80741078/111584990-3a4e2500-87f1-11eb-93a7-23547756f5ef.jpg)

**Comment by xolo1** [comment]
When viewed from whatsapp-web
