### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by LuizTokuhara** [adiwajshing/Baileys#404]
Is it possible to connect multiple whatsapp accounts using a single Bailey's instance?
Is there any example or tutorial on how to do it?

Thanks!

**Comment by ibnusyawall** [comment]
try https://github.com/adiwajshing/Baileys/issues/173#issuecomment-702434638 or https://github.com/adiwajshing/Baileys/issues/292#issuecomment-750858204

**Comment by LuizTokuhara** [comment]
Thanks @ibnusyawall
