### ISSUE TITLE
groupCreate  - Not expecting a response

### ISSUE THREAD

**Issue by ViniciusCoelhoDeAbreu** [adiwajshing/Baileys#406]
**Describe the bug**
When I use conn.groupCreate(groupName, participants) it gives that error: 

> INFO [2021-03-19 16:20:28.134 +0000] (5692): cancelling wait for message as a response is no longer expected from the phone
    tag: "759.--7"
    class: "Baileys"
(node:5692) UnhandledPromiseRejectionWarning: BaileysError: Not expecting a response
    at onErr (C:\Users\kickp\Desktop\lead-whatsapp-node\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:188:56)
    at C:\Users\kickp\Desktop\lead-whatsapp-node\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:183:82
    at Timeout.<anonymous> (C:\Users\kickp\Desktop\lead-whatsapp-node\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:270:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**To Reproduce**
1. Connect the application with a phone
2. Use WAConnection groupCreate method.

**Expected behavior**
It should create a new group.

**Environment (please complete the following information):**
 - Is this on a server? Yes, and at my PC too.
 - What do your `connectOptions` look like? default
 - Do you have multiple clients on the same IP? No.
 - Are you using a proxy? No.

**Additional context**

**Comment by barkerpedro** [comment]
I solved my problem by changing "tyoe" to "type" in the 6.MessagesSend.ts file. #408

**Comment by ViniciusCoelhoDeAbreu** [comment]
> I solved my problem by changing "tyoe" to "type" in the 6.MessagesSend.ts file. #408

Fixed. Thank you so much!
