### ISSUE TITLE
When a new whatsapp account scan qrcode, throw error.

### ISSUE THREAD

**Issue by nswbmw** [adiwajshing/Baileys#41]
TypeError: Cannot read property 'forEach' of null
    at /xxx/node_modules/baileys/WhatsAppWeb.Session.js:133:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async /xxx/script/sendMessge.js:30:18

when i use another account send one message to this new account, it work ok(scan qrcode).

**Comment by adiwajshing** [comment]
I've updated the NPM module. Please try it out now.
