### ISSUE TITLE
Title group return undefined [BUG]

### ISSUE THREAD

**Issue by MRHRTZ** [adiwajshing/Baileys#418]
**Describe the bug**
Subject group metadata return undefined

**To Reproduce**
1. Created new group using conn.groupCreate('title', [conn.user.jid]
2. Join to group
3. Check metadata, and subject of metadata is undefined

**Environment (please complete the following information):**
 - Is this on a server? Yes server and locally was same
 - What do your `connectOptions` look like? I don't using that options
 - Do you have multiple clients on the same IP? Nope just one
 - Are you using a proxy? No, i'm not

Pic:
![Screenshot_2021-03-26-05-54-38-010_com whatsapp](https://user-images.githubusercontent.com/52845610/112554529-0e3a3180-8df9-11eb-884a-6c7fdc769515.jpg)

Also have error if using conn.groupUpdateSubject()
![image](https://user-images.githubusercontent.com/52845610/112555035-f616e200-8df9-11eb-95f4-febd5a8e2bfd.png)

**Comment by FaizBastomi** [comment]
up

**Comment by AlenSaito1** [comment]
up (2)

**Comment by pokearaujo** [comment]
I try make a "workaround" with new groups created by phone, but maybe work

`this.client.on('CB:Chat,cmd:action', (json) => {
      const jid = json[1].id;
      const subject = json[1]?.data[2]?.subject ?? null;
      const action = json[1]?.data[0];
      if (!action || !jid || !subject) {
        return;
      }

      if (action != 'create') {
        return;
      }

      const chat = this.client.chats.get(jid);
      if (!chat) {
        return;
      }

      setTimeout(() => {
        this.client.chats.update(jid, (chat) => {
          chat.name = subject;
        });
        console.log('created', chat);
      }, 500);
    });`

**Comment by ferhacks** [comment]
up (3)

**Comment by guiromer** [comment]
up(4)

**Comment by adiwajshing** [comment]
@MRHRTZ you might want to try `conn.fetchGroupMetadataFromWA` to always fetch the latest metadata from the phone

**Comment by MRHRTZ** [comment]
> @MRHRTZ you might want to try `conn.fetchGroupMetadataFromWA` to always fetch the latest metadata from the phone

It's working

here the screenshot log of `conn.fetchGroupMetadataFromWA`

![image](https://user-images.githubusercontent.com/52845610/116783496-316f9500-aab9-11eb-8f51-dc9e469be17e.png)


and for `conn.groupMetadata` is

![image](https://user-images.githubusercontent.com/52845610/116783524-595ef880-aab9-11eb-889a-3a6000c20c57.png)


I will change it to fetchGroupMetadataFromWA instead thanks.
