### ISSUE TITLE
[BUG] image dont buffer

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#423]
I was using the new update made three days ago, however, when I went to apply the new commands on my bot, there were two errors in the whatssap bot that I use, the first is when I will link an image with a jpeg or jpg format, this error appears
![WhatsApp Image 2021-03-27 at 15 11 49](https://user-images.githubusercontent.com/57237342/112730168-d7563f80-8f0e-11eb-9da4-cfe7abfb42b2.jpeg)

and the second is that when I send a sticker, this error appears as well, but send the sticker normally, but I want to know just out of curiosity
![WhatsApp Image 2021-03-27 at 15 14 31](https://user-images.githubusercontent.com/57237342/112730255-52b7f100-8f0f-11eb-87a4-e4cc62f8c1c4.jpeg)

**Comment by canove** [comment]
@ianmsfvenom, I have the second error occurring here too after update.  

Btw, when you want to post a error or a code, use the `Insert Code Option`. It helps readability a lot
