### ISSUE TITLE
How to get quoted message sender id

### ISSUE THREAD

**Issue by ferhacks** [adiwajshing/Baileys#424]
I was doing a warning system, however, I would like to know how to obtain the sender id of a quoted message to facilitate this system, I do not know if I explain myself

**Comment by Nurutomo** [comment]
m.message.extendedTextMessage.contextInfo.participant
m.message.imageMessage.contextInfo.participant
m.message.videoMessage.contextInfo.participant
m.message.audioMessage.contextInfo.participant

**Comment by ferhacks** [comment]
> m.message.extendedTextMessage.contextInfo.participant
> m.message.imageMessage.contextInfo.participant
> m.message.videoMessage.contextInfo.participant
> m.message.audioMessage.contextInfo.participant

Thanks, but there is no way to make all the messages in one Code?

**Comment by Nurutomo** [comment]
https://github.com/Nurutomo/wabot-aq/blob/master/lib/simple.js#L345-L347

**Comment by ferhacks** [comment]
Thanks

**Comment by ferhacks** [comment]
> m.message.extendedTextMessage.contextInfo.participant
> m.message.imageMessage.contextInfo.participant
> m.message.videoMessage.contextInfo.participant
> m.message.audioMessage.contextInfo.participant

Can you send an example ?, I tried to use the code and I did not understand it well
