### ISSUE TITLE
How to send Pdf file preview thumbnail?

### ISSUE THREAD

**Issue by Kikii-XyZ** [adiwajshing/Baileys#429]

**Comment by FaizBastomi** [comment]
```js
conn.sendMessage(jid, buffer, MessageType.document, { mimetype: Mimetype.gif, thumbnail: buffer })
```

**Comment by RizqiTatsumaki** [comment]
> ```js
> conn.sendMessage(jid, buffer, MessageType.document, { mimetype: Mimetype.gif, thumbnail: jpegBuffer })
> ```

why is the mimetype gif ??

**Comment by FaizBastomi** [comment]
> > ```js
> > conn.sendMessage(jid, buffer, MessageType.document, { mimetype: Mimetype.gif, thumbnail: jpegBuffer })
> > ```
> 
> why is the mimetype gif ??

sorry, typo😅

**Comment by Kikii-XyZ** [comment]
the result is mp4

**Comment by FaizBastomi** [comment]
> the result is mp4

- if you want to send it as a document
```js
conn.sendMessage(jid, videoBuffer, MessageType.document, { filename: "video.mp4", mimetype: "video/mp4" })
```
- video as document with thumbnail preview
```js
conn.sendMessage(jid, videoBuffer, MessageType.document, { filename: "video.mp4", mimetype: "video/mp4", thumbnail: jpegBase64 })
```

- if you want to be sent like a normal video
```js
conn.sendMessage(jid, videoBuffer, MessageType.video)
```
- normal video with caption
```js
conn.sendMessage(jid, videoBuffer, MessageType.video, { caption: "Caption Here" })
```
**i am not sure exactly what you are talking about so i am as helpful as i can, sorry again if it doesn't go your way🙏**

**Comment by Kikii-XyZ** [comment]
> > the result is mp4
> 
> * if you want to send it as a document
> 
> ```js
> conn.sendMessage(jid, videoBuffer, MessageType.document, { filename: "video.mp4", mimetype: "video/mp4" })
> ```
> 
> * video as document with thumbnail preview
> 
> ```js
> conn.sendMessage(jid, videoBuffer, MessageType.document, { filename: "video.mp4", mimetype: "video/mp4", thumbnail: jpegBase64 })
> ```
> 
> * if you want to be sent like a normal video
> 
> ```js
> conn.sendMessage(jid, videoBuffer, MessageType.video)
> ```
> 
> * normal video with caption
> 
> ```js
> conn.sendMessage(jid, videoBuffer, MessageType.video, { caption: "Caption Here" })
> ```
> 
> **i am not sure exactly what you are talking about so i am as helpful as i can, sorry again if it doesn't go your waypray**
> 
> > The document thumbnail can't be a Base64 video, it might just grab the first frame of the base64 video or it might even get an error

Yaallah gw nanya gmn cara ngirim file pdf dan menampilkan thumbnailnya:v

**Comment by FaizBastomi** [comment]
@Kikii-XyZ 
```js
conn.sendMessage(jid, pdfBuffer, MessageType.document, { mimetype: Mimetype.pdf, thumbnail: jpegBase64, filename: "name" })
```
**please try first**

- With thumbnail
![Screenshot_2021_0404_000429](https://user-images.githubusercontent.com/64179402/113485946-7b755300-94da-11eb-8dfb-e9e683c4dfa7.png)

- Without thumbnail
![Screenshot_2021_0404_000459](https://user-images.githubusercontent.com/64179402/113485951-7f08da00-94da-11eb-85db-545956adb2c5.png)

**Comment by Kikii-XyZ** [comment]
> @Kikii-XyZ
> 
> ```js
> conn.sendMessage(jid, pdfBuffer, MessageType.document, { mimetype: Mimetype.pdf, thumbnail: jpegBase64, filename: "name" })
> ```
> 
> **please try first**
> 
> > OK, if this can answer your question
> > You can close these issues, thanks from me
> 
> * With thumbnail
>   ![Screenshot_2021_0404_000429](https://user-images.githubusercontent.com/64179402/113485946-7b755300-94da-11eb-8dfb-e9e683c4dfa7.png)
> * Without thumbnail
>   ![Screenshot_2021_0404_000459](https://user-images.githubusercontent.com/64179402/113485951-7f08da00-94da-11eb-85db-545956adb2c5.png)

Okay, I understand
```
Close issuw now
```
