### ISSUE TITLE
How to get the information that an unexpected disconnect has happened

### ISSUE THREAD

**Issue by AdllerSimas** [adiwajshing/Baileys#431]
When an unexpected disconnect occurs, I need to obtain this information. How can I keep monitoring this condition? In lib baileys, I get this information when the unexpectedDisconnect method happens, ok, but how do I get this information and take it to my application backend. Does anyone have any ideas?

**Comment by pcsfilho** [comment]
I have a similar problem, disconnection occurs from time to time and I still don't understand the reason. I created a method to check from time to time if it is connected, but I still don't know what may be happening for the connection to be very bad.
```
this.client.autoReconnect = ReconnectMode.onAllErrors
        this.client.browserDescription = ['CZ', "Chrome", '3.0'] as [string, string, string]
        this.client.chatOrderingKey = waChatKey(true)
        this.client.connectOptions.maxRetries = Infinity
        this.client.logger.level = 'debug'
        this.client.connectOptions.alwaysUseTakeover = true
        this.client.connectOptions.phoneResponseTime = 10_000
        // this.client.connectOptions.regenerateQRIntervalMs = 20000
        this.connectCallbacks()
        await this.connect(authInfo, callback)
        try {
            setInterval(
                () => this.client.query({
                    json: ['admin', 'test']
                }).then(
                    response => {}
                ), 15_000)
        } catch(e) {
            logger.debug(e)
        }
```
However, the cell phone is connected to the internet.
Does anyone have any ideas?
