### ISSUE TITLE
Set QR Code generating limitation 

### ISSUE THREAD

**Issue by jasspro** [adiwajshing/Baileys#434]
"close reason : Unexpected status in 'admin': Too Many Requests(429)"

How can I set qr code limitation and set interval between generating two qr code ?

**Comment by ziadAwfarDev** [comment]
@jasspro  i faced the same issue and a work around to is to count qr codes whenever it created and set a limit to it like if it hits this limit call connaction.close()

**Comment by MuhShalah007** [comment]
> "close reason : Unexpected status in 'admin': Too Many Requests(429)"
> 
> How can I set qr code limitation and set interval between generating two qr code ?

how to prevent it?

**Comment by jasspro** [comment]
Hello,

In which version do you get this solution?
MD or regular?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by thiagomagamoc** [comment]
Any solution for this?
