### ISSUE TITLE
Reemit chat-update event

### ISSUE THREAD

**Issue by viniciusll** [adiwajshing/Baileys#435]
I'd like to reemit the chat-update event with the same message it was emitted, i'm trying to use conn.once('chat-update'), but I'm not being able to

make it work. Can you help me to achieve this?

`
conn.on('chat-update', async chatUpdate => {
      conn.once('chat-update', {???})
})
`

**Comment by itacirgabral** [comment]
save the data somewhere and call the event handler again

```javascript
conn.on('chat-update', d => {
  saveDataSomewhere(d)
  chatUpdateHandler(d)
 })
 ```

```javascript
const d2 = getDataSomewhere()
chatUpdateHandler(d2)
```

**Comment by viniciusll** [comment]
I'm trying to call `conn.once()` like this:

`
conn.on('chat-update', async chatUpdate => {
   const { jid, count, t, hasNewMessage, messages } = chatUpdate
   conn.once('chat-update', { jid, count, t, hasNewMessage, messages })
})
`

but I'm getting this error: 

`
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type object
    at checkListener (events.js:64:11)
    at WAConnection.once (events.js:313:3)
    at Object.saveMessage (C:\Users\vinic\Desktop\omnipipe\src\service\message.service.js:103:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
`
Do you know how to correctly call `conn.once()`?
