### ISSUE TITLE
some time image msg failed

### ISSUE THREAD

**Issue by jasspro** [adiwajshing/Baileys#438]
I got this error "marker was not found" in image msg, same image sent already . what happen in here? I am using url for sending image

**Comment by Manjit2003** [comment]
**@jasspro** it would be helpful if you could send a comprehensive screenshot as well as a log of the error. Also, can you send a piece of your code?

**Comment by jasspro** [comment]
yes, thanks for replying,
my code is 
await conn.sendMessage(phone, { url: "Live Image URL Path" }, MessageType.image, { mimetype: Mimetype.png, caption: message})
             .catch((erro) => {  console.log("erro.text : " + erro.text);   });

currently, I have no any error's screenshot b'coz it is not coming every time.

**Comment by jasspro** [comment]
Error ScreenShot is here.  
![Error](https://user-images.githubusercontent.com/25892615/113590458-4c80ed80-9650-11eb-905f-cdd8aa0c6833.jpg)

**Comment by 13banda** [comment]
+1

**Comment by canove** [comment]
Same here. Disabling thumbnails seems to resolve it.

**Comment by pokearaujo** [comment]
+1
