### ISSUE TITLE
Stop getting presence

### ISSUE THREAD

**Issue by shubham0804** [adiwajshing/Baileys#442]
I can get the realtime presence update of a number using `conn.requestPresenceUpdate()` but am unable to find a way to stop getting the presence update. There must be some way to achieve this. Any help is appreciated.

Thanks for the excellent library @adiwajshing

**Comment by shubham0804** [comment]
Commenting to keep this open

**Comment by Macarthurval** [comment]
I would like to know how to cancel the presence subscription too.
