### ISSUE TITLE
How to set author name and package name in sticker

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#443]
I'm trying different ways on how to put the name of the author and the package when sending a sticker on whatsapp just to make it look better can someone help me how to put this blessed name of the author and the package on the sticker, if you don't know the that I'm talking about follows the line below:

![WhatsApp Image 2021-04-06 at 22 17 22](https://user-images.githubusercontent.com/57237342/113863060-91f00880-977f-11eb-8178-6154ee08794f.jpeg)

**Comment by AlenSaito1** [comment]
@ianmsfvenom You can add the pack/author name in the sticker editing the EXIF metadata in a `WebP file` to add the author and pack name.

You can use `webpmux` to set the metadata in a `WebP file` like [this](https://github.com/AlenSaito1/wa-sticker-formatter/blob/85c60c5fcb11be9f85a387d7a486fa9a694e7277/src/Sticker.ts#L246)
and the code in [this method](https://github.com/AlenSaito1/wa-sticker-formatter/blob/85c60c5fcb11be9f85a387d7a486fa9a694e7277/src/Sticker.ts#L255) will create a valid .exif file with the pack/author name

I would have created a PR, but `webpmux` requires a lot of dependencies  and I don't think it's practical to have many dependencies in a lightweight implementation of WA-Web-API

In the meantime, You can use [Wa-Sticker-Formatter](https://www.npmjs.com/package/wa-sticker-formatter) to add metadata to images and send them as stickers.

Thanks.
