### ISSUE TITLE
How can we stop QR code generating?

### ISSUE THREAD

**Issue by jasspro** [adiwajshing/Baileys#446]
once we call "conn.on("qr", (qr) => {});" method, it generate QR code, but how can we stop generating after some time? it is continuously generating QR code.

**Comment by jessekalil** [comment]
I have the same doubt

**Comment by daffigusti** [comment]
same with me...

**Comment by Manjit2003** [comment]
use ```conn.removeAllListeners("qr");``` after which you can register your own qrcode listener...

**Comment by MaznAbdullah** [comment]
when use conn.removeAllListeners("qr");
i get loop msg
error in QR gen

**Comment by guiromer** [comment]
> error in QR gen

Me too, I am having the same loop message.

**Comment by ziadAwfarDev** [comment]
you can use connection.disconnect() and then connect again when you need to

**Comment by ziadAwfarDev** [comment]
@Manjit2003 this method won't stop qr generate but it will stop you listen to the events 
better way is to stop the connection by calling connection.close()

**Comment by PurpShell** [comment]
open

**Comment by bramaudi** [comment]
Cannot stop event by closing connection, the QR generation keep running until **Too Many Request**
![image](https://user-images.githubusercontent.com/14371119/123601068-71d16200-d821-11eb-80bc-1d165d2ec0ef.png)

**Comment by yateeshr** [comment]
Currently the QR generation stops only when the QR code has been scanned and not when connection is closed. 
The default connection state is  `connecting`. When `conn.close()` is called, the state is set to `close`.
So another check needs to be added in `/WAConnection/1.Validation.ts`
```
if (this.state === 'open' || this.state === 'close')
    return;
```

**Comment by bramaudi** [comment]
Thanks for your insight, i should try.
Currently I'm using different approach by automatically stop node process after successfully get QR code using `setTimeout`, then do repetition to fetch API in client-side with 20sec interval which is basically the QR code expiration time.

**Comment by thiagomagamoc** [comment]
Any soltuion for this?

**Comment by WevertonCouto** [comment]
you can use .logout() to stop qr code generate
