### ISSUE TITLE
[BUG] Failed to Send Media message

### ISSUE THREAD

**Issue by 13banda** [adiwajshing/Baileys#447]
**Describe the bug**
Failed to upload images & video. got this error
i hope media url change (whatsapp update)

```ERROR [2021-04-10 14:52:36.853 +0000] (10912): Error in uploading to media-del1-1.cdn.whatsapp.net (RequestError: connect ECONNREFUSED 127.0.0.1:443) , retrying...
    class: "Baileys"
ERROR [2021-04-10 14:52:36.857 +0000] (10912): Error in uploading to media.fdel7-1.fna.whatsapp.net (RequestError: connect ECONNREFUSED 127.0.0.1:443) , retrying...
    class: "Baileys"
ERROR [2021-04-10 14:52:36.859 +0000] (10912): Error in uploading to mmg.whatsapp.net (RequestError: connect ECONNREFUSED 127.0.0.1:443) 
    class: "Baileys"
Error: Media upload failed on all hosts
    at WAConnection.prepareMessageMedia (/mnt/311042F23AE20872/workspace/flychatbot/app/server/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:173:19)
 ```

**To Reproduce**
1. Send any image or video file

**Expected behavior**
File need to send successfully

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like?  normal 
 - Do you have multiple clients on the same IP?no
 - Are you using a proxy?no

**Comment by canove** [comment]
How often it occurs? After last update, sometimes my installation stops sending media, restarting the server makes all work again. 

Here, it occurs randomly

**Comment by pokearaujo** [comment]
Here occurs after send to 10 groups, i need restart to send again.

**Comment by 13banda** [comment]
nothing send in our case not after restarting process
look like whatsapp update his backend

**Comment by hasanbasri1993** [comment]
i still worked with this commit build https://github.com/adiwajshing/Baileys/commit/05bae6b1e72351696eb8da451c68fae092b55577

**Comment by hamzasgd** [comment]
same error here 
Error: Media upload failed on all hosts....

**Comment by hasanbasri1993** [comment]
any solution ?

**Comment by pokearaujo** [comment]
here seems working good after not send the media buffer direct, now im sending using from a url like:

`
await conn.sendMessage(
    id, 
    { url: 'https://giphy.com/gifs/11JTxkrmq4bGE0/html5' }, // send directly from remote url!
    MessageType.video, 
    { mimetype: Mimetype.gif, caption: "hello!" }
)
`

**Comment by 13banda** [comment]
+1

**Comment by canove** [comment]
@pokearaujo, here it occurs even with URL.
@adiwajshing, any clue on how we can get more information about it?

**Comment by hamzasgd** [comment]
> @pokearaujo, here it occurs even with URL.
> @adiwajshing, any clue on how we can get more information about it

use proxy and the problem will be solved.

**Comment by canove** [comment]
@hamzasgd, thanks for this. I never tried a proxy before, can you point me the directions? 
`conn.connectOptions.agent = ProxyAgent ('http://1.0.180.120:8080')`
Using a single proxy (a paid one) like this example will do the trick, or I have to change it time by time?

**Comment by SlimGee** [comment]
I know this issue has been closed for a long time, I'm having the same issue in MD after updating to the latest version. I get this error when I try to upload an image with ` .sendMessage(id, { image: remote_url }` . The error: ` uploadResult: "Bad Request to URI: https://mmg.whatsapp.net/mms/image` `Error: Media upload failed on all hosts` how do I solve this, I don't know where to start
