### ISSUE TITLE
Help to send audio

### ISSUE THREAD

**Issue by ferhacks** [adiwajshing/Baileys#450]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
I have tried you use baileys to send a local audio, but this one does not play on phones, only on whatsapp web, how do I fix it?
![Screenshot_20210413-165408_WhatsApp](https://user-images.githubusercontent.com/63879582/114620177-51115b80-9c79-11eb-8748-f391cd1338b8.png)

**Comment by ferhacks** [comment]
and my code is:
``			case 'randomusic':
				let rndrl = fs.readFileSync('./getrandom.txt').toString().split('\n')
				let chfuck2 = rndrl[Math.floor(Math.random() * rndrl.length)]
				const bufferm = fs.readFileSync(`audio/${chfuck2}`)
				await xinz.sendMessage(from, bufferm, MessageType.audio, {quoted : qul, mimetype: "audio/mp4", ptt : true})
				break
``

**Comment by ferhacks** [comment]
I fixed this using ffmpeg command, close

**Comment by AlenSaito1** [comment]
It'd be helpful for anyone who comes across this issue if you share the command which fixed it for you.

**Comment by ferhacks** [comment]
``ffmpeg -i voltageost.mp3 -vn -ar 44100 -ac 2 -b:a 192k voltageost2.mp3
-y``

**Comment by TentacleSama4254** [comment]
Thd

**Comment by codermert** [comment]
hi, i still have the problem. how can we solve this?
