### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by frmjajal1** [adiwajshing/Baileys#453]
why can't save session.
Earlier I scanned the qr code successfully connected, but the .json session was not saved.
My friend also experienced the same thing. please reply via whatsapp (if possible)
wa.me/62895803265350

**Comment by ibnusyawall** [comment]
```js
conn.on('open', () => {
    fs.writeFileSync('./session.json', JSON.stringify(conn.base64EncodedAuthInfo()))
})
```

open instead of credentials-updated

if your problem has been solved, pliese close this issues!

**Comment by frmjajal1** [comment]
Okay
