### ISSUE TITLE
disappearing messages new feature

### ISSUE THREAD

**Issue by rthelolchex** [adiwajshing/Baileys#454]
baileys error : cannot convert undefined or null to object (after i'm change disappearing messages settings)

**Comment by ferhacks** [comment]
up

**Comment by adiwajshing** [comment]
@rthelolchex need more info/code than this to help you

**Comment by Pokoke-01** [comment]
> baileys error : cannot convert undefined or null to object (after i'm change disappearing messages settings)

try this


`if (!m.message) return`

put this code on top of yours

**Comment by AlenSaito1** [comment]
You need access this `WAMessage.message.ephemeralMessage.message` from the Message Object while Disappearing messages are on

**Comment by ferhacks** [comment]
> You need access this `WAMessage.message.ephemeralMessage.message` from the Message Object while Disappearing messages are on

How?

**Comment by ferhacks** [comment]
I found the fix

Add this code in this line

mek.message = (Object.keys(mek.message)[0] === 'ephemeralMessage') ? mek.message.ephemeralMessage.message : mek.message

![Screenshot_20210512-152708_Termux](https://user-images.githubusercontent.com/63879582/118033317-aa32e480-b336-11eb-9f72-11a218bfcd59.png)

**Comment by rthelolchex** [comment]
> I found the fix
> 
> Add this code in this line
> 
> `mek.message = (Object.keys(mek.message)[0] === 'ephemeralMessage') ? mek.message.ephemeralMessage.message : mek.message`
> 
> ![Screenshot_20210512-152708_Termux](https://user-images.githubusercontent.com/63879582/118033317-aa32e480-b336-11eb-9f72-11a218bfcd59.png)

Thanks dude, i mean this problem before xD, my bot isn't working
