### ISSUE TITLE
Getting No Message Present On Download Media Message...

### ISSUE THREAD

**Issue by hamzasgd** [adiwajshing/Baileys#460]
BaileysError: No message present
4|websocket  |     at WAConnection.downloadMediaMessage (/www/wwwroot/app.abandonedguru.com/nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:316:19)
4|websocket  |     at /www/wwwroot/app.abandonedguru.com/nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/Mutex.js:20:53
4|websocket  |     at runMicrotasks (<anonymous>)
4|websocket  |     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
4|websocket  |   status: 400,
4|websocket  |   context: { status: 400 }
4|websocket  | }

**Comment by AlenSaito1** [comment]
Show your code, Please.

**Comment by hamzasgd** [comment]
Simply loading message
const message = await conn.loadMessages(jid, 20, cursor)

**Comment by hamzasgd** [comment]
also sometimes getting this
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
4|websocket  |     at Decipheriv.final (internal/crypto/cipher.js:174:29)
4|websocket  |     at Transform.final [as _final] (/www/wwwroot/app.abandonedguru.com/nodejs/node_modules/@adiwajshing/baileys/lib/WAConnection/Utils.js:487:31)
4|websocket  |     at callFinal (internal/streams/writable.js:610:10)
4|websocket  |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
4|websocket  |   library: 'digital envelope routines',
4|websocket  |   function: 'EVP_DecryptFinal_ex',
4|websocket  |   reason: 'bad decrypt',
4|websocket  |   code: 'ERR_OSSL_EVP_BAD_DECRYPT'
4|websocket  | }

**Comment by danielteodorodt** [comment]
Same Here
