### ISSUE TITLE
How to qouted msg with specify message

### ISSUE THREAD

**Issue by asmin-dev** [adiwajshing/Baileys#462]
I replied to someone else's message and the bot also replied to the message, how to do it?

**Comment by ZefianAlfian** [comment]
itu function nya tambahin quote nya, jangan langsung ambil msg, jadinya ginj

```js
function reply(from, teks, quote){
conn.sendMessage(from, teks, MessageType.text, { quoted: quote } );
}
reply(from, "tes", msg); 
```

work for me

I can't speak English, so I use Indonesian

**Comment by asmin-dev** [comment]
> itu function nya tambahin quote nya, jangan langsung ambil msg, jadinya ginj
> 
> ```js
> function reply(from, teks, quote){
> conn.sendMessage(from, teks, MessageType.text, { quoted: quote } );
> }
> reply(from, "tes", msg); 
> ```
> 
> work for me
> 
> I can't speak English, so I use Indonesian

> Kalau itu saya tau, yang saya maksud itu misalkan di dalam grub ada 3 orang, katakanlah A,B dan C, misalkan C ini botnya
> Nah ketika si A membalas pesan si B maka si C juga ikut membalas pesan si B, mengerti yang saya maksud?
