### ISSUE TITLE
Can not receive presence messages

### ISSUE THREAD

**Issue by sorosons** [adiwajshing/Baileys#463]
I could receive presence messages after subscribing a number until this morning. Now, I am able to subscribe a number but I can not receive online/offline information from the connection. I can only receive online/offline messages if I open the conversation with that number on my phone.

**Comment by kavehshahedi** [comment]
I've got this problem too. Looking forward to its solution!

**Comment by 07h** [comment]
is there a solution?

**Comment by AlenSaito1** [comment]
Looks like WhatsApp removed the ability to look-up the presence of non-contacts in the last update.

**Comment by lonelypx** [comment]
I think WhatsApp removed this. There are so many WhatsApp status trackers in google appsotre that all have the same issue.

**Comment by adiwajshing** [comment]
This was likely caused by a security vulnerability in WhatsApp that they've now, thankfully, fixed. 
Please do not use this library or any other library to track people's presence without their consent.
