### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ferhacks** [adiwajshing/Baileys#467]
**Describe the bug**
Today I wanted to use this library, but I was surprised that the library does not receive any messages, and I am not the only one affected, some friends also have the same problem as me

**To Reproduce**
1. Update library
2. Start script
3. starts without problems but does not do or receive anything

**Expected behavior**
in theory my script sends and receives messages, but does neither of the two

**Environment (please complete the following information):**
 - Is this on a server?
 - yes
 - What do your `connectOptions` look like? 
 - default
 - Do you have multiple clients on the same IP?
 - yep
 - Are you using a proxy?
 - no

**Comment by ziadAwfarDev** [comment]
@ferhacks are you sure it works before and if so are you sure you have not get blocked by whatsapp 
try to scan another phone and test it again on your local env maybe
