### ISSUE TITLE
Problem starting the server. Unexpected token =

### ISSUE THREAD

**Issue by VallejoJuanPablo** [adiwajshing/Baileys#468]
Hi I have a problem starting the server.

TERMINAL:

[nodemon] starting `node src/server.js`
/var/www/api_whatsapp/node_modules/baileys/WhatsAppWeb.js:21
        static Presence = {
                        ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/api_whatsapp/src/controllers/wpp.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ziadAwfarDev** [comment]
@VallejoJuanPablo can you share this snippet of your code

**Comment by VallejoJuanPablo** [comment]
Yes, sure, and if you want to take a look, I'll leave you the link to the repository too.

Git : https://github.com/VallejoJuanPablo/ApiWW.git

Code :server.js
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const app = express();
require("dotenv").config();



//body parse(para leer atributos en el body)
app.use(bodyParser.urlencoded({ extended: true }));

app.use(bodyParser.json());

//cors 
app.use(cors());

//Ruta de inicio
app.get('/', (req, res) => res.send("Esta es mi raiz de api"));

//rutas wpp (trae las rutas de otro archivo para que no se junten todas)
app.use('/wpp', require('./router/wpp'));


app.listen(3001, () => {
 console.log("El servidor está inicializado en el puerto 3001");
});


routes/wpp.js
const express = require("express");
const router = express.Router();
const wpp_controller = require("../controllers/wpp");
const mid_auth = require("../middleware/auth");

//Principal de Facturas no hace nada 
router.get("/", (req, res) => res.send("Principal de WPP"));

router.get("/asd", (req, res) => res.send("Principal de WPP"));

//POST: endpoint para consultar las facturas relacionadas con un cliente, en un periodo de tiempo. Requiere token para autenticar el logueo.
router.post("/conectar", function (req, res) {
wpp_controller.conectApi(req, res)
})


router.post("/enviar",function (req, res) {
    wpp_controller.sendMessage(req, res)
})
    

/* router.post("/conectar",  mid_auth, function (req, res) {
    wpp_controller.conectApi(req, res)
    })
    
    
    router.post("/enviar",  mid_auth, function (req, res) {
        wpp_controller.sendMessage(req, res)
    }) */
    
    
module.exports = router;

controller/wpp,js

const WhatsAppWeb = require('baileys')

const client = new WhatsAppWeb() 


// CONECTA WHATS - SERVIDOR
module.exports.conectApi = async (req, res) => {
    client.connect()
    .then (([user, chats, contacts, unread]) => {
        res.jsonp({mensaje: 'Autenticación exitosa'});
    })
    .catch (err => console.log(err) )
}


// ENVIAR MENSAJES

module.exports.sendMessage = async (req, res) => {
options = {
    quoted: null,
    timestamp: new Date()
}
client.sendTextMessage(`${req.body.phone}@s.whatsapp.net`, req.body.body, options)
.then( res.jsonp({mensaje:'Notificación enviada'}))
.catch (err => console.log(req.body) )
}

**Comment by ziadAwfarDev** [comment]
@VallejoJuanPablo  change you importing to be like this 
const {
    WAConnection,
} = require('@adiwajshing/baileys')
and then you can create and object from it like this 

let connection = new WAConnection()
and then connection.connect() whenever you want

**Comment by VallejoJuanPablo** [comment]
Excellent, problem solved when starting the server, now, I have a problem sending the message, it is pending. Could you help me with that?

Promise { <pending> }

Code of sendMessage:

module.exports.sendMessage = async (req, res) => {
options = {
    quoted: null,
    timestamp: new Date()
}
const id = `${req.body.phone}@s.whatsapp.net`
const exists = await client.isOnWhatsApp (id)
if (exists) console.log (`${id} exists on WhatsApp, as jid: ${exists.jid}`)
const sentMsg  =  await client.sendMessage(`${req.body.phone}@s.whatsapp.net`, req.body.body, MessageType.text)
console.log(sentMsg)
}

**Comment by ziadAwfarDev** [comment]
@VallejoJuanPablo nice congratulation and keep it up my friend 👍
