### ISSUE TITLE
How can i check if whatsapp is connected before send a message?

### ISSUE THREAD

**Issue by gabrielroubiera** [adiwajshing/Baileys#469]
I would like to know if there is any method to verify if baileys is connected to a number.

**Comment by AlenSaito1** [comment]
`conn.state === 'open'`

**Comment by gabrielroubiera** [comment]
@AlenSaito1 I've tried but it dosen't works, i made a method to get it and it still works.

**Comment by ziadAwfarDev** [comment]
@gabrielroubiera  you can't even whatsapp doesn't know until it send a message or after sometime when timeout triggered 
a work around is to make a status for you session to track it and listen .on('connection-phone-change', (state))
when you send a message and it takes time this listener will be triggered if the connection lost

**Comment by gabrielroubiera** [comment]
@ziadAwfarDev Thank you so much!
