### ISSUE TITLE
Missing unread messages

### ISSUE THREAD

**Issue by CheloXL** [adiwajshing/Baileys#47]
While trying the library, I've found that I were missing some unread messages. After enabling logs, I found that WS is sending two messages with add:before/last:true. So, after the first one, you remove the handlers and the second message is "unhandled".
I'm not sure how to fix that, since you use the last:true to signal the completion of the promise...

**Comment by adiwajshing** [comment]
That's an interesting observation. Will incorporate in the next release. Thanks.

**Comment by adiwajshing** [comment]
I'm trying a few things but I am unable to get two `last:true` messages. Could you possibly send the tags & headers of the messages received?

**Comment by CheloXL** [comment]
f607b4eb6ca79cdf.--1b,["action",,["contacts",{"type":"frequent"}]]
...
f607b4eb6ca79cdf.--1d,["action",{"add":"last"}]
f607b4eb6ca79cdf.--1e,["action",{"add":"before","last":"true"}]
f607b4eb6ca79cdf.--1f,["action",{"add":"before","last":"true"}]

then comes
preempt-f607b4eb6ca79cdf.--20,["response",{"type":"contacts"}]

**Comment by adiwajshing** [comment]
Thanks a lot. What version of WhatsApp are you using on your phone?

**Comment by CheloXL** [comment]
2.20.193.9

**Comment by adiwajshing** [comment]
It should be fixed now. Could you try the latest version of Baileys (2.0.0)? You can install it using `npm i github:adiwajshing/baileys`

**Comment by CheloXL** [comment]
Perfect!, will try and let you know. Thanks!

**Comment by CheloXL** [comment]
I can confirm that now it seems to be working perfect. Thank you!

**Comment by adiwajshing** [comment]
Awesome. Closing.
