### ISSUE TITLE
Multi sessions

### ISSUE THREAD

**Issue by filipeborelli** [adiwajshing/Baileys#470]
Hello, how i open multi sessions?

**Comment by ziadAwfarDev** [comment]
i think you can wrap you code in a class and create multi objects and assign a worker threads to handle them

**Comment by ferhacks** [comment]
try [This](https://github.com/adiwajshing/Baileys/issues/292#issuecomment-750858204) or [This](https://github.com/adiwajshing/Baileys/issues/173#issuecomment-702434638)
