### ISSUE TITLE
[BUG] bro, how to troubleshoot unexpected end of files

### ISSUE THREAD

**Issue by Fadli2249** [adiwajshing/Baileys#472]
case prefix+ 'ktp':
if (args.length == 0) return reply(`Usage: ${prefix}ktp nik|provinsi|kabupaten|nama|tempat, tanggal lahir|jenis kelamin|jalan|rt/rw|kelurahan|kecamatan|agama|status nikah|pekerjaan|warga negara|berlaku sampai|url_image\n\nExample: ${prefix}ktp 456127893132123|bumipertiwi|fatamorgana|LoL Human|mars, 99-99-9999|belum ditemukan|jl wardoyo|999/999|turese|imtuni|alhamdulillah islam|jomblo kack|mikirin dia|indo ori no kw|hari kiamat|https://i.ibb.co/Xb2pZ88/test.jpg`)
get_args = args.join(" ").split("|")
nik = get_args[0]
prov = get_args[1]
kabu = get_args[2]
name = get_args[3]
ttl = get_args[4]
jk = get_args[5]
jl = get_args[6]
rtrw = get_args[7]
lurah = get_args[8]
camat = get_args[9]
agama = get_args[10]
nikah = get_args[11]
kerja = get_args[12]
warga = get_args[13]
until = get_args[14]
img = get_args[15]
ini_buffer = await getBuffer(`https://api.lolhuman.xyz/api/ktpmaker?apikey=${apikey}&nik=${nik}&prov=${prov}&kabu=${kabu}&name=${name}&ttl=${ttl}&jk=${jk}&jl=${jl}&rtrw=${rtrw}&lurah=${lurah}&camat=${camat}&agama=${agama}&nikah=${nikah}&kerja=${kerja}&warga=${warga}&until=${until}&img=${img}`)
await hexa.sendMessage(from, ini_buffer, image, { quoted: mek, caption: 'nih ktp mu' })
break

**Comment by zennn08** [comment]
stress

**Comment by rayyreall** [comment]
Malu maluin Negara  bug datang dari mana stress

**Comment by riznih** [comment]
Stress

**Comment by MrG3P5** [comment]
tlulnya murni

**Comment by HAFizh-15** [comment]
Akalnya masih murni ya bund

**Comment by hardiantojek93** [comment]
Sial Ku tertawa

**Comment by Hexagonz** [comment]
Panggilin emaknya woi

**Comment by meowcraftY** [comment]
Hadeh

**Comment by shansekai** [comment]
Memalukan

**Comment by dhyZx** [comment]
Woe hekajon murid lu ngebug

**Comment by ZefianAlfian** [comment]
wOw

**Comment by Nurutomo** [comment]
close close!

**Comment by AlenSaito1** [comment]
What did I just witness
