### ISSUE TITLE
Request of the function that makes the listen when the user enters and leaves the group

### ISSUE THREAD

**Issue by ikarofsouza** [adiwajshing/Baileys#475]
- Solicitação da função que faz o listen quando o usuário entra e sai do grupo, assim como a onMessage e onAnyMessage.

- Request of the function that makes the listen when the user enters and leaves the group, as well as onMessage and onAnyMessage.

![Screenshot1](https://user-images.githubusercontent.com/48399495/116793399-7944eb00-aabe-11eb-8d74-6ed3836fee65.png)

![Screenshot2](https://user-images.githubusercontent.com/48399495/116793398-78ac5480-aabe-11eb-9daa-c6bd55309839.png)

**Comment by AlenSaito1** [comment]
[`conn.on('group-participants-update', (event) => {})`](https://adiwajshing.github.io/Baileys/classes/waconnection.html#on)

**Comment by tiagoandrepro** [comment]
does not work

conn.on('group-participants-update', (event) => {})
