### ISSUE TITLE
Added options to edit group description, subject and properties 

### ISSUE THREAD

**Issue by ikarofsouza** [adiwajshing/Baileys#477]
- Added options to edit group description, subject and properties.

![Screenshot3](https://user-images.githubusercontent.com/48399495/116793456-c0cb7700-aabe-11eb-8b73-1beeaaa3b48d.jpg)
![Screenshot4](https://user-images.githubusercontent.com/48399495/116793458-c1640d80-aabe-11eb-9d03-cbd266a9f155.jpg)
![Screenshot](https://user-images.githubusercontent.com/48399495/116793459-c1fca400-aabe-11eb-9f05-32c83c3e7c05.png)
![Screenshot2](https://user-images.githubusercontent.com/48399495/116793460-c1fca400-aabe-11eb-9ca5-6bbaa5687a94.png)

**Comment by AlenSaito1** [comment]
https://adiwajshing.github.io/Baileys/classes/waconnection.html#groupsettingchange
