### ISSUE TITLE
[BUG] How can I update the name value of conn.contactAddOrGet when the bot number is just entered into the group?

### ISSUE THREAD

**Issue by QUERY-GANI** [adiwajshing/Baileys#478]
**Describe the bug**
I tried to list whatsapp groups but got a little problem, when adding my bot number to whatsapp groups, and I tried console.log (conn.contactAddOrGet(jid)) the value of name is undefined

**To Reproduce**
1. Created a new connection
2. Create a new method on WAConnection
```javascript
getName(jid) {
      let v = jid === '0@s.whatsapp.net' ? {
        jid,
        vname: 'WhatsApp'
      } : jid === this.user.jid ?
          this.user : this.contactAddOrGet(jid)
      return  v.name || v.vname || v.notify || PhoneNumber('+' + v.jid.replace('@s.whatsapp.net', '')).getNumber('international')
    }
```
3. Then call conn.getName on chat-update:
```javascript
let handler = async (m, { conn, command }) => {
console.log(conn.getName(m.chat)); // returns undefined value if bot was recently added to whatsapp group
let txt = conn.chats.array.filter((v) => v.jid.endsWith("g.us")).map((v) => `${conn.getName(v.jid)}\n${v.jid} [${v.read_only ? "Left" : "Joined"}]`).join`\n\n`
    conn.reply(m.chat, "List Groups:\n" + txt, m)
})

handler.help = ["groups", "grouplist"]
handler.tags = ["info"]
handler.command = /^(groups?list)$/i
handler.owner = true
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler
```

**[Full source code is available on nurutomo's github](https://github.com/Nurutomo/wabot-aq)**

**Expected behavior**
I hope the name value of conn.contactAddOrGet isn't undefined when the bot enters a new group in whatsapp

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like?  I didn't use any options
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

because conn.contactAddOrGet always returns undefined value if bot was recently added to whatsapp group, so I try to use conn.fetchGroupMetadataFromWA if jid ends g.us:
```javascript
async getName(jid) {
      let v = jid === '0@s.whatsapp.net' ? {
        jid,
        vname: 'WhatsApp'
      } : jid === this.user.jid ?
          this.user : jid.endsWith("g.us") ? await this.fetchGroupMetadataFromWA(jid) : this.contactAddOrGet(jid)
      return jid.endsWith("g.us") ? v.subject : v.name || v.vname || v.notify || PhoneNumber('+' + v.jid.replace('@s.whatsapp.net', '')).getNumber('international')
    }
```

then use async / await on array.map:
```javascript
console.log(await conn.getName(m.chat)); // return the name of group :)
let txt = await conn.chats.array.filter((v) => v.jid.endsWith("g.us")).map(async (v) => `${await conn.getName(v.jid)}\n${v.jid} [${v.read_only ? "Left" : "Joined"}]`).join`\n\n`
    conn.reply(m.chat, "List Groups:\n" + txt, m) // but the problem, txt return [promise object] :(
```

i dont know why txt is return [promise object], [i tried visiting stackoverflow about async await inside array.map and tried it but it didn't help](https://stackoverflow.com/questions/42489918)

**Comment by Nurutomo** [comment]
you must use
```js
await Promise.all([Array that contain Promises])
```
before joining them

> then use async / await on array.map:
> 
> ```js
> console.log(await conn.getName(m.chat)); // return the name of group :)
> let txt = await conn.chats.array.filter((v) => v.jid.endsWith("g.us")).map(async (v) => `${await conn.getName(v.jid)}\n${v.jid} [${v.read_only ? "Left" : "Joined"}]`).join`\n\n`
>     conn.reply(m.chat, "List Groups:\n" + txt, m) // but the problem, txt return [promise object] :(
> ```
> 
> i dont know why txt is return [promise object], [i tried visiting stackoverflow about async await inside array.map and tried it but it didn't help](https://stackoverflow.com/questions/42489918)

**Comment by QUERY-GANI** [comment]
Thanks nurutomo san >_<
