### ISSUE TITLE
QR to Web

### ISSUE THREAD

**Issue by VallejoJuanPablo** [adiwajshing/Baileys#479]
Hello people, I would like to know if it is possible to send the qr code to a web page to make the connection.

this is the code to connect:

const {
    WAConnection,MessageType
    } = require('@adiwajshing/baileys')

    let client = new WAConnection()

// CONECTA WHATS - SERVIDOR
module.exports.conectApi = async (req, res) => {
  client.connect()
    .then (([user, chats, contacts, unread]) => {
        res.jsonp({mensaje: 'Autenticación exitosa'});
    })
    .catch (err => console.log(err) )
}

**Comment by ibnusyawall** [comment]
maybe you can combine it with express js and ws modules

**Comment by AlenSaito1** [comment]
This is how we do it 

- [Storing the QR](https://github.com/Synthesized-Infinity/Whatsapp-Botto-Xre/blob/09580a845c63cc8c1ccc4c035bf7cf27bbf9887a/src/Main.ts#L65)
- [Displaying it a Webpage](https://github.com/Synthesized-Infinity/Whatsapp-Botto-Xre/blob/09580a845c63cc8c1ccc4c035bf7cf27bbf9887a/src/Web/Routes/Base.ts#L45)

**Comment by dacaruso** [comment]
Hi, me too I'm in trouble in visualizing the qr code in a web page. Since I'm a complete novice to javascript development, can anyone point me to an easy to understand example ?
TIA

**Comment by VallejoJuanPablo** [comment]
Yes, the @AlenSaito1 example is quite complicated, I am working in this way, integrating it with a laravel project, maybe it will help you to start.

Api Connect:
module.exports.conectApi = async (req, res) => {
    client.connect()
    client.on('qr', (QR) => {
        res.jsonp({qr: QR});
    })
    .then (([user, chats, contacts, unread]) => {
        res.jsonp({mensaje: 'Autenticación exitosa'});
    })
    .catch (err => console.log(err) )
}

Return once in the body the qr in string format

Laravel :
public function index(Request $request){
$resposne = Http:post('route of api wpp connect');
$response = $response->json();

return view('qrCode')->with('response'.$response['qr']);
}

and in the view convert 'string qr' in qr formart

**Comment by viniciusll** [comment]
var conn;

const Connect = async (conn) => {
  await conn.connect()
}

`if (conn.state !== 'close') { res.send({ message: 'A conexão já encontra-se aberta.' }); return }`

**Comment by dacaruso** [comment]
Thank you, I don't know Laravel and I'm quite new to those modern web application framework,  I was wondering what could be the easiest tech stack to build my mvp based on this library...

**Comment by aislanspeedio** [comment]
It seems in the v5.x we don't have anymore this 'QR' event on the socket client.
