### ISSUE TITLE
Error installing a whatsapp bot with termux

### ISSUE THREAD

**Issue by shanduy** [adiwajshing/Baileys#484]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.
![Screenshot_2021-05-09-08-57-19-870_com termux](https://user-images.githubusercontent.com/79606488/117574828-953f2280-b0a4-11eb-9680-9ddd9e05fd19.jpg)

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by AlenSaito1** [comment]
It looks like you don't have the `index.js` file you're trying to run. Please close the issue as it is not related to the library.

**Comment by shanduy** [comment]
And where do I put these commands? Before it worked normally

**Comment by dcdunkan** [comment]
From termux! And remember, *This is not an issue with this library*. And you have opened, 2 same issues (#486). You should close at least one. Your problem is because, you haven't installed this library which is required to run your bot.

**Comment by shanduy** [comment]
If it was an error with your library, it was only updating something and it was fixed, and if it is in termux, I have a video on YouTube of how to install the bot, Greetings 🤫

**Comment by Unknownhacker0000** [comment]
> If it was an error with your library, it was only updating something and it was fixed, and if it is in termux, I have a video on YouTube of how to install the bot, Greetings 🤫

Video link??
