### ISSUE TITLE
Get Status

### ISSUE THREAD

**Issue by VallejoJuanPablo** [adiwajshing/Baileys#485]
Hello people, I would like to know how to determine if the server is connected or not, because when it is connected the getStatus () method responds correctly but if it is not connected it does not respond at all.

const {
    WAConnection,MessageType
    } = require('@adiwajshing/baileys')

    let client = new WAConnection()

module.exports.status = async (req, res) => {
    const resp = await client.getStatus()
        res.jsonp(resp); 
}

**Comment by Nurutomo** [comment]
use `client.status`

**Comment by VallejoJuanPablo** [comment]
Thank you
