### ISSUE TITLE
[BUG]NOW MY BOT DOES NOT WORK

### ISSUE THREAD

**Issue by shanduy** [adiwajshing/Baileys#486]
Good night
My bot worked correctly before and it was installed very easily, it did not have any errors, every time I installed it I get this error
![Screenshot_2021-05-09-08-57-19-870_com termux](https://user-images.githubusercontent.com/79606488/117591471-47eda000-b0fa-11eb-834c-a6f2b5afbb27.jpg)
The direct of the bot is all correct, it had already been a month without any error but for 5 days this error has occurred, this is the directory is well written and with that function correctly
![IMG_20210509_180636](https://user-images.githubusercontent.com/79606488/117591505-74092100-b0fa-11eb-9b13-517a9d41e025.jpg)
I do not know if maybe the direct is off or in maintenance. I hope someone helps me, thanks in advance

**Comment by angga759** [comment]
> Good night
> My bot worked correctly before and it was installed very easily, it did not have any errors, every time I installed it I get this error
> ![Screenshot_2021-05-09-08-57-19-870_com termux](https://user-images.githubusercontent.com/79606488/117591471-47eda000-b0fa-11eb-834c-a6f2b5afbb27.jpg)
> The direct of the bot is all correct, it had already been a month without any error but for 5 days this error has occurred, this is the directory is well written and with that function correctly
> ![IMG_20210509_180636](https://user-images.githubusercontent.com/79606488/117591505-74092100-b0fa-11eb-9b13-517a9d41e025.jpg)
> I do not know if maybe the direct is off or in maintenance. I hope someone helps me, thanks in advance

[Follow this](https://github.com/adiwajshing/Baileys#install)

**Comment by shanduy** [comment]
It continues with the same problem, before it worked correctly I do not know what happened, the QR did give it, now I do not know why this happened

- In termux it is very easy to install

**Comment by AlenSaito1** [comment]
@shanduy  This issue is not related to this library. Please Close this issue. 

PS: Check if your `node_modules` folder has been deleted, If that's the case, run `npm i` or `npm ci` if you have a `package.lock.json`
