### ISSUE TITLE
How to get whatsapp sender id in group?

### ISSUE THREAD

**Issue by IDIka31** [adiwajshing/Baileys#487]
How to get whatsapp sender id in group?

**Comment by AlenSaito1** [comment]
`message.participant` (`message` refers to the [WAMessage/proto.WebMessageInfo](https://adiwajshing.github.io/Baileys/classes/proto.webmessageinfo-1.html) here)

**Comment by Nurutomo** [comment]
```js
m.key.fromMe ? conn.user.jid : m.participant ? m.participant : m.key.participant ? m.key.participant : m.key.remoteJid
```
`m` refer to message
