### ISSUE TITLE
Typing status does not continue when you send the first message

### ISSUE THREAD

**Issue by danielteodorodt** [adiwajshing/Baileys#49]
Hello, I thank you for the very well structured project.

I have a difficulty, put it to appear typing, when going to the next message sent the typing does not work anymore.

    async function sendMessage(number, name) {

    client.updatePresence(number + "@s.whatsapp.net", WhatsAppWeb.Presence.available)
    client.updatePresence(number + "@s.whatsapp.net", WhatsAppWeb.Presence.composing)

    setTimeout(() => {

        client.sendTextMessage(number + "@s.whatsapp.net", "Hi *" + name + "*, how are you?")

        client.updatePresence(number + "@s.whatsapp.net", WhatsAppWeb.Presence.composing)

        setTimeout(() => {
          
            client.sendTextMessage(number + "@s.whatsapp.net", "Hi *" + name + "*, how are you?")
    
        }, 5 * 1000)

    }, 5 * 1000)

    return "true";
    }

**Comment by adiwajshing** [comment]
Glad you like the project. Yes, you'll have to update the presence again after every message. It's just the way WhatsApp works :/

**Comment by danielteodorodt** [comment]
But it's not working.  when i try to update presence the second time it doesn't work.

**Comment by adiwajshing** [comment]
I believe the problem is that you're not waiting for send message to complete. Try this:

``` javascript
async function sendMessage(number, name) {
  await client.updatePresence(number + "@s.whatsapp.net", WhatsAppWeb.Presence.available)
  await client.updatePresence(number + "@s.whatsapp.net", WhatsAppWeb.Presence.composing)

  setTimeout(async () => {

    await client.sendTextMessage(number + "@s.whatsapp.net", "Hi *" + name + "*, how are you?")
    await client.updatePresence(number + "@s.whatsapp.net", WhatsAppWeb.Presence.composing)

    setTimeout(() => {
        client.sendTextMessage(number + "@s.whatsapp.net", "Hi *" + name + "*, how are you?")
    }, 5 * 1000)

}, 5 * 1000)

return "true";
}
```

**Comment by danielteodorodt** [comment]
It worked thanks so much for the help
