### ISSUE TITLE
[ASK] Need Help! SendMessage with document (pdf)

### ISSUE THREAD

**Issue by bulongx** [adiwajshing/Baileys#490]
//content = fs.readFileSync('./uploads/file.pdf')
content = { url: './uploads/file.pdf' }
options.mimetype = Mimetype.pdf
type = MessageType.text
const response = await conn.sendMessage('62******', content, type, options)

i don't know, how to send file docx, pdf, etc... i use above source code n' always fail... plz help me...

type = MessageType.text <<< i think the problem is here, but idk whats it's must be... i tried extended text, bu same error...

**Comment by AlenSaito1** [comment]
type should be `MessageType.document`

**Comment by bulongx** [comment]
thx, it's done... you saved me...

btw how to send document if document format (zip, rar,7z, docx,xlxs, pptx)
i tried below, but undefined Mimetype...

//options.mimetype = Mimetype.zip
//options.mimetype = Mimetype.docx
//options.mimetype = Mimetype.pptx
//options.mimetype = Mimetype.xlsx

any suggest??

**Comment by LuanRT** [comment]
> thx, it's done... you saved me...
> 
> btw how to send document if document format (zip, rar,7z, docx,xlxs, pptx)
> i tried below, but undefined Mimetype...
> 
> //options.mimetype = Mimetype.zip
> //options.mimetype = Mimetype.docx
> //options.mimetype = Mimetype.pptx
> //options.mimetype = Mimetype.xlsx
> 
> [ERROR]
> TSError: ? Unable to compile TypeScript:
> app.ts:196:30 - error TS2339: Property 'zip' does not exist on type 'typeof Mime
> type'.
> 196 ext_file = Mimetype.zip;
> ~~~
> app.ts:198:30 - error TS2339: Property 'docx' does not exist on type 'typeof Mim
> etype'.
> 198 ext_file = Mimetype.docx;
> ~~~~
> app.ts:200:30 - error TS2339: Property 'pptx' does not exist on type 'typeof Mim
> etype'.
> 200 ext_file = Mimetype.pptx;
> ~~~~
> app.ts:202:30 - error TS2339: Property 'xlsx' does not exist on type 'typeof Mim
> etype'.
> 202 ext_file = Mimetype.xlsx;
> ~~~~
> 
> any suggest??

Simply pass the mimetype manually as a string:

```js
// zip
options.mimetype = "application/zip";

// docx
options.mimetype = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

// pptx
options.mimetype = "application/vnd.openxmlformats-officedocument.presentationml.presentation";

// xlsx
options.mimetype = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
```

Refer to this list for more information:
https://www.sitepoint.com/mime-types-complete-list/

**Comment by angga759** [comment]
`const Mimetype = require('mime.json');`

`client.sendMessage('xxx@s.whatsapp.net', { url:  './uploads/file.pdf' }, MessageType.document, { mimetype: Mimetype['pdf'] })`

**Comment by angga759** [comment]
> @angga759 what's the `mime.json` you're referring to?

Module npmjs

**Comment by bennysolo** [comment]
mimetype: 'application/pdf'

**Comment by it03sca** [comment]
I need to send file with mode SEND image/video OR document/send file mode:
how to detect automatic, mimetype & message type? depend on filename

here is my code:
===================================
const UPLOAD_FILE_PATH = './uploads/';
const options: MessageOptions = { };
let type: MessageType;
let content;
var file_name = 'document.jpeg';
//var file_name = 'video.mp4';
//var file_name = 'document.pdf';

phone_number = '628564*******@s.whatsapp.net';
content = await fs.readFileSync(UPLOAD_FILE_PATH + file_name)

type = MessageType.image;
//type = MessageType.video;
//type = MessageType.document;

options.mimetype = Mimetype.jpeg;
//options.mimetype = Mimetype.mp4;
//options.mimetype = Mimetype.pdf;

const response = await conn.sendMessage(phone_number , content, type, options);
console.log(response);
