### ISSUE TITLE
[ASK] Need Help! SendMessage with Attachment (MessageType & mimetype automaticly detection depend on filename)

### ISSUE THREAD

**Issue by bulongx** [adiwajshing/Baileys#492]
I need to send file with mode SEND image/video OR document/send file mode:
how to detect automatic, mimetype & message type? depend on filename

here is my code:

const UPLOAD_FILE_PATH = './uploads/';
const options: MessageOptions = { };
let type: MessageType;
let content;
var file_name = 'document.jpeg';
//var file_name = 'video.mp4';
//var file_name = 'document.pdf';

phone_number = '628564*******@s.whatsapp.net';
content = await fs.readFileSync(UPLOAD_FILE_PATH + file_name)

////////////////////////// this is need to be automaticly detection by filename////////////////////////////////////
type = MessageType.image;
//type = MessageType.video;
//type = MessageType.document;

options.mimetype = Mimetype.jpeg;
//options.mimetype = Mimetype.mp4;
//options.mimetype = Mimetype.pdf;
////////////////////////// this is need to be automaticly detection by filename////////////////////////////////////

const response = await conn.sendMessage(phone_number , content, type, options);
console.log(response);

**Comment by barkerpedro** [comment]
```node
const mime = require("mime-types");

let file_name = 'document.jpeg';
let typeFile = mime.lookup(file_name);
let mimeFile = mime.extension(typeFile);
...
console.log(typeFile);      // mime format
console.log(mimeFile );   // extension file
```

**Comment by PurpShell** [comment]
you know you don't need to provide the mime

**Comment by LuanRT** [comment]
> you know you don't need to provide the mime

The documentation says:
`“Optional for all media types except documents”`

So if he wants to send pdf files or any other kind of document then he's got to provide the correct mimetype.
