### ISSUE TITLE
Divide Baileys to run as multiple microservices

### ISSUE THREAD

**Issue by devheitor** [adiwajshing/Baileys#493]
Hi, anyone here have ever thought about decoupling Baileys to have, for instance, a microservice dedicated only to receive and send messages to whatsapp web web server like a socket, while having another microservice just to decrypt and parse the messages received, and another microservice just to encrypt the messages to send?

This way, one could have on a k8's cluster, for example, with just one pod connected and communicating to WhatsAppWeb Web Socekt while having multiple pods to decrypt and parse messages received, and multiple pods to encrypt messages to send, aiming to have the necessary parallelism to process a Whatsapp account with a lot messages coming in and out.

The idea is also about decouple business logic of Baileys. Another pods responsible to have business logic would be in between the pods responsible to decrypt and parse the messages received and the pods responsible to encrypt and send the messages after the business logic processing

Any help in this task? How to start?  How we project Baileys and its classes to have something like this, running for example on a k8s?

**Comment by PurpShell** [comment]
this is so hard to implement, yet you will only gain so little performance boosts

**Comment by Velezer** [comment]
you can use message queue or something behave like that
