### ISSUE TITLE
How to make a fakereply

### ISSUE THREAD

**Issue by yogipw** [adiwajshing/Baileys#494]
Hm

**Comment by FaizBastomi** [comment]
```js
conn.sendMessage(jid, 'hm', MessageType.text, { contextInfo: { participant: '0@s.whatsapp.net', quotedMessage: { conversation: 'this is fake reply'} } } )
````

**Comment by yogipw** [comment]
Thx sir

**Comment by MaznAbdullah** [comment]
how to do it in MD ?

**Comment by Maarz-baar** [comment]
> ```js
> conn.sendMessage(jid, 'hm', MessageType.text, { contextInfo: { participant: '0@s.whatsapp.net', quotedMessage: { conversation: 'this is fake reply'} } } )
> ```

Could you please tell how to do it in latest MD version of baileys. I want the sender as Whatsapp (0@s.whatsapp.net)
