### ISSUE TITLE
[BUG] Uploading Audio Media

### ISSUE THREAD

**Issue by mzz14** [adiwajshing/Baileys#496]
I am getting below error log while sending Audio file (.ogg) format

 Error in uploading to media-dub4-1.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...

The file is actually getting sent and being played but somehow my logs are looking like above.

Any help needed

**Comment by canove** [comment]
Sam here.. the media is indeed sent, but it sometimes logs an error. 

Is there a way to enrich this error, so we can get more info about the media that causes it, like its name or type?
