### ISSUE TITLE
[BUG] Duplicate ID inserted

### ISSUE THREAD

**Issue by dinnos** [adiwajshing/Baileys#497]
**Describe the bug**
When the connections it's open some connections throw the the following error: 

<img width="893" alt="Captura de Pantalla 2021-05-24 a la(s) 17 21 46" src="https://user-images.githubusercontent.com/25092933/119414095-85cef480-bcb4-11eb-97d7-b625600e8006.png">

and the connection enters on a crashing loop

**To Reproduce**
1. Created a new connection
2. Scan the QR

**Expected behavior**

Omit chats duplication

**Environment (please complete the following information):**
 - Is this on a server? Yes on a Kubernetes cluster
 - What do your `connectOptions` look like? Default options
 - Do you have multiple clients on the same IP? Yes, over a Kubernetes cluster
 - Are you using a proxy? No

**Additional context**

**Comment by canove** [comment]
same here

**Comment by adiwajshing** [comment]
What version are y’all running?

**Comment by canove** [comment]
I'm on 3.5.0 stable. I've inserted some checks to ignore group messages on my code, and it seems to resolved it. But I'm not sure its related, because the erros appears to be on keyed DB, so I should throw even with my "if isGroup return" code.

**Comment by danielteodorodt** [comment]
same here

**Comment by sostenesapollo** [comment]
I'm also getting this error . Is there any solution ?

**Comment by JeanJunior18** [comment]
> I'm on 3.5.0 stable. I've inserted some checks to ignore group messages on my code, and it seems to resolved it. But I'm not sure its related, because the erros appears to be on keyed DB, so It should throw even with my "if isGroup return" code.
> 
> ![image](https://user-images.githubusercontent.com/24817866/119505787-b14cf000-bd43-11eb-8459-fec396ff4244.png)
> 
> It was occurring on every instance, causing the server to reboot and occurring again, on an infinite loop. After ignoring groups, its working about 20 minutes without errors.

Where you ignore the groups? Can you show a example?

**Comment by canove** [comment]
@sostenesapollo, nothing yet.

I noticed that it only occur with a single whatsapp, that has a lot of groups.

@JeanJunior18
My solution didn't work, since I was ignoring groups on my app, and not on Baileys itself.

**Comment by sostenesapollo** [comment]
How to ignore group messages ?

**Comment by sostenesapollo** [comment]
Okay. So we need to look at the keyddb error handling... Bcs it's breaking the entire running app

**Comment by canove** [comment]
> Okay. So we need to look at the keyddb error handling... Bcs it's breaking the entire running app
Yeah, I think this is the only way....

**Comment by JeanJunior18** [comment]
> @sostenesapollo, nothing yet.
> 
> I noticed that it only occur with a single whatsapp, that has a lot of groups.
> 
> @JeanJunior18
> My solution didn't work, since I was ignoring groups on my app, and not on Baileys itself.
> 
> 

Hmmm, so you left from all groups?

**Comment by canove** [comment]
@JeanJunior18, no. Just disconnected the affected whatsapp 😟

**Comment by ilyaborodin** [comment]
This has already been fixed. As I see u use release 3.5.0, that doesn't have commits of april, may, june. Just update library to the last commit.

https://github.com/adiwajshing/Baileys/commit/5dfeaf75b0ae474ab11d9632f2695a7de5e0ce76

**Comment by sostenesapollo** [comment]
Not fixed ! I've updated the lib but the error persists .

**Comment by canove** [comment]
@sostenesapollo , did you confirm that the "insertIfAbsent" is present on yours 4.Events.ts ?
It looks like should do the trick, But I don't have an affected account to test right now.

**Comment by sostenesapollo** [comment]
I'm using the last baileys version, idk if it's present at there. 
canove mano passa teu whats kkk

**Comment by canove** [comment]
> I'm using the last baileys version, idk if it's present at there.
> canove mano passa teu whats kkk

Sent to your email ;)
