### ISSUE TITLE
Is get presence possible?

### ISSUE THREAD

**Issue by ozoktay** [adiwajshing/Baileys#5]
Hello,

Thanks for this repo. There is something i want to ask. Can I get online/offline status my contacts?

Like this?

`this.query(["action","presence","subscribe","905527222606@c.us"]);`

I tried but I didn't get a result.

**Comment by adiwajshing** [comment]
I had some code in place that prevented custom queries like this from being executed. I've updated that, now this query should work.

However, when I tried this query I got a status 200 JSON back & then another seemingly unrelated JSON with the presence update. So, I've added the following callback for all presence updates:

``` javascript
client.query(["action","presence","subscribe","905527222606@c.us"])
client.handlers.presenceUpdated = (id, presence) => {
    console.log(id + " is " + presence)
}

```

This is included in the latest commit.

**Comment by ozoktay** [comment]
It's work. Thanks for quick reply.
