### ISSUE TITLE
Add "Report Contact"

### ISSUE THREAD

**Issue by Hainjku** [adiwajshing/Baileys#500]
Can you add that a user can be reported? 

Just as you can block with a command I want it to also be reported

**Comment by Hainjku** [comment]
"Report contact"

**Comment by Hainjku** [comment]
Please add in Baileys "Report Contact" 
![image](https://user-images.githubusercontent.com/79340315/119762238-b31dcd00-be83-11eb-88cd-9af6ba56eb3e.png)

**Comment by PurpShell** [comment]
hard to add

**Comment by Hainjku** [comment]
Why is it difficult?  Please I need it, could I donate to them

**Comment by Hainjku** [comment]
@adiwajshing

**Comment by AlenSaito1** [comment]
I personally think this shouldn't be added as people can use it to spam reports against other people

**Comment by Hainjku** [comment]
> I personally think this shouldn't be added as people can use it to spam reports against other people

I want to test if that works

**Comment by PurpShell** [comment]
I found a way, though as @AlenSaito1 said, it is mostly going to be negative false reports, but I could see people using it to report against spammers in their bots and apps

**Comment by Hainjku** [comment]
> I found a way, though as @AlenSaito1 said, it is mostly going to be negative false reports, but I could see people using it to report against spammers in their bots and apps

Hast du den Weg gefunden? Können Sie mir bitte helfen?

**Comment by Hainjku** [comment]
> I found a way, though as @AlenSaito1 said, it is mostly going to be negative false reports, but I could see people using it to report against spammers in their bots and apps

@PurpShell Hey, can you tell me how can I report spammers with the bot?
