### ISSUE TITLE
How to delete all group and personal chat messages 

### ISSUE THREAD

**Issue by Suryapardana** [adiwajshing/Baileys#501]
TypeError: conn.deleteChat

**Comment by Nurutomo** [comment]
```js
for (let { jid } of conn.chats.all()) {

  // delete chat
  await conn.modifyChat(jid, 'delete')
  
  
  // clear chat
  await conn.modifyChat(jid, 'clear', {
    includeStarred: false // default to true
  })
}
```

**Comment by kurnianetwork** [comment]
> ```js
> for (let { jid } of conn.chats.all()) {
> 
>   // delete chat
>   await conn.modifyChat(jid, 'delete')
>   
>   
>   // clear chat
>   await conn.modifyChat(jid, 'clear', {
>     includeStarred: false // default to true
>   })
> }
> ```

kalo cara auto archive chat yang sudah di read/ udah di buka dalam waktu 24 jam gimana mas?
