### ISSUE TITLE
How to auto remove the .enc generated files inside the /tmp folder ?

### ISSUE THREAD

**Issue by sostenesapollo** [adiwajshing/Baileys#502]
![image](https://user-images.githubusercontent.com/35838667/120054675-a6c27d00-c007-11eb-9387-78c73d3a8b64.png)

The server /tmp folder be full of these files, how can we keep the folder always free ?

**Comment by sostenesapollo** [comment]
I'm doing this manually today, but there is some function in baileys to auto-remove these files ?

**Comment by Nurutomo** [comment]
```bash
# All
rm *Message3EB0*

# Only .enc
rm *Message3EB0*.enc
```

**Comment by sostenesapollo** [comment]
thanks @Nurutomo
