### ISSUE TITLE
[BUG] 'downloadAndSaveMediaMessage' Does not work on Ephermal messages (dissappearing messages) 

### ISSUE THREAD

**Issue by TentacleSama4254** [adiwajshing/Baileys#506]
Please look into this

**Comment by Nurutomo** [comment]
It doesn't even go through ephemeralMessage type
https://github.com/adiwajshing/Baileys/blob/eb55760eace888a5f63f64a66899ffb79a840f50/src/WAConnection/Utils.ts#L454-L469
