### ISSUE TITLE
[BUG] 404 Not found while getBroadcastListInfo

### ISSUE THREAD

**Issue by ahgsql** [adiwajshing/Baileys#509]
### Describe the bug
I have 3 broadcast lists. I can get jids of them. But only one of them response with status 200 and recipents' numbers.

### Steps to reproduce the behavior:

**Create minimal example with default config.
Create couple of broadcast lists with 2-3 person added.
use following code to get all of broadcast lists's jids.**
```
 conn.on("chats-received", async () => {
    let chats = await conn.chats;
    chats.array.forEach(async (chat) => {
      if (chat.jid.includes("broadcast")) {
        console.log(chat.jid)
      }
    });
  });

```
After that, try following:

```
let info = await conn.getBroadcastListInfo(JID OF ONE BROADCAST);
console.log(info);
```

### **Expected behavior**

Get information about broadcast lists. But it success for one of them, and fails for others.

### 
Environment (please complete the following information):
Running on Centos 7.
conn.connectOptions = {
/** fails the connection if no data is received for X seconds /
maxIdleTimeMs: 25000,
/* maximum attempts to connect /
maxRetries: 5,
/* max time for the phone to respond to a connectivity test /
phoneResponseTime: 10000,
/* minimum time between new connections */
connectCooldownMs: 3000,

/** always uses takeover for connecting */
alwaysUseTakeover: true,
queryChatsTillReceived: true,
};

Do you have multiple clients on the same IP? NO
Are you using a proxy? NO

**Comment by vasani-arpit** [comment]
+1 

@adiwajshing I can reproduce this.

**Comment by vasani-arpit** [comment]
not stale
