### ISSUE TITLE
how to send catalog in baileys

### ISSUE THREAD

**Issue by DielGanz** [adiwajshing/Baileys#511]
I hope in response

**Comment by hardiantojek93** [comment]
😅

**Comment by bhavya32** [comment]
@DielGanz Why Open a second issue. Please close it. Or @hardiantojek93 You close yours.

**Comment by yogipw** [comment]
try this
case 'catalog':
res = await conn.prepareMessageFromContent(from,{
"productMessage": {
				"product": {
					"productImage":{
						"mimetype": "image/jpeg",
						"jpegThumbnail": fs.readFileSync(`./stik/thumb.jpeg`) //Gambarnye
					},
					"title": fake, 
					"description": "YogiPw", 
					"currencyCode": "USD",
					"priceAmount1000": "2000",
					"retailerId": "entahlah",
					"productImageCount": 1
				},
				    "businessOwnerJid": `0@s.whatsapp.net`
		}
}, 
 {quoted:mek, contextInfo:{}}) 

conn.relayWAMessage(res)
break
