### ISSUE TITLE
[BUG] Sending Media failing due to some reason And Can't we catch errors..

### ISSUE THREAD

**Issue by bhavya32** [adiwajshing/Baileys#513]
I have been trying to sending Docs but get the following error - 

```
const options = {
                    mimetype: "application/pdf",
                    caption: "Document",
                    filename: "Doc"
                }
conn.sendMessage(id, Buffer, MessageType.document, options)
                .then((result) => {
                    console.log(result)
                })
                .catch((err) => console.log(err))
```

Errors - 
```
ERROR    [2021-06-03 17:36:58.182 +0000] (14780): Error in uploading to media.fdel27-3.fna.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...
    class: "Baileys"
ERROR    [2021-06-03 17:37:05.160 +0000] (14780): Error in uploading to media.fdel27-3.fna.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying...
    class: "Baileys"
```

My Issues - 
I can not catch the error? Its baileys logging directly to the console. Baileys does not throw error at all? 

Context - It generally happens when  sending to multiple people.  

As  different issues  are being create such as  for audio, and images, and docs as well, we should use this as a common link.
@13banda @mzz14 @hamzasgd @pokearaujo @hasanbasri1993 @canove

@adiwajshing I know I might be disturbing you but can you please check this for once?

**Comment by canove** [comment]
Hi @bhavya32. Thanks for sharing

I started to use a proxy on connection to solve this, but it didn't work. 

Even with proxy, I still get this problem after a few hours and needs to restart the server to get send media working again.

I have around 20 instances of Baileys running on same server, and when the bug occurs, none of them can send media's.

In my case I don't get even the "Error in uploading to media" error.. it just don't send the media, nothing is throwed on console. 

Any help about this will be extremely appreciated.

**Comment by bhavya32** [comment]
@canove For me, I am currently not facing the issue since 30 min. It might be early but these things I did to troubleshoot - 

1. I had implemented some code that calls baileys  after some delay.  In that code - 1 or 2 messages were dropping. I fixed it. So make sure all your request is reaching baileys LIB.

2. This is important - 
Open the file -``` \node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js```
You will find - ```async refreshMediaConn(forceGet = false)```
Change it to - ```async refreshMediaConn(forceGet = true)```

Do reply me the update worked or not. It will be helpful for both of us if we solve this issue somehow.

**Comment by canove** [comment]
@bhavya32, I already tried something similar, but I pass this option on "sendMessage" method. You changed the lib itself, but sending this as an option seems to do the same effect.

![image](https://user-images.githubusercontent.com/24817866/120803955-7c4a5580-c51a-11eb-83d4-6b5e6c3de5df.png)

Unfortunately, it didn't work

**Comment by canove** [comment]
Update: I put some code after and before the "sendMessage" call. When its working properly, I get the both "Before" and "After" logged. 

When the bug occurs, the "after" log never cames. 

My code: 
![image](https://user-images.githubusercontent.com/24817866/120806366-26c37800-c51d-11eb-82ab-c04ffd2b1e0f.png)


The result on console when working fine:
![image](https://user-images.githubusercontent.com/24817866/120806464-4490dd00-c51d-11eb-846d-b3b347e43296.png)


The result on console when bugged:
![image](https://user-images.githubusercontent.com/24817866/120806525-570b1680-c51d-11eb-8fa5-5215bc0b9df0.png)

Seems like the promise of sendMessage is neither resolved or rejected. It keeps waiting forever...

**Comment by bhavya32** [comment]
@canove  In the same MessageSend File, Baileys uploads the Media and gets mediaUrl. 
You will find - 
```
 if (!mediaUrl)
            throw new Error('Media upload failed on all hosts');
```
Add an else function where it logs the ```mediaUrl``` if it is not blank. If it is blank, we are sure it is uploading error.

**Comment by adiwajshing** [comment]
@canove 
> Seems like the promise of sendMessage is neither resolved or rejected. It keeps waiting forever...

This is likely a connection issue where the connection between the server & phone becomes stale, and the phone does not respond to the send request. Have to reconnect here.

@bhavya32 the message only goes on to send if mediaUrl is truthy -- it won't cause the async function to hang.

**Comment by adiwajshing** [comment]
@bhavya32 
> My Issues -
I can not catch the error? Its baileys logging directly to the console. Baileys does not throw error at all?

Context - It generally happens when sending to multiple people.


If you're sending the message to multiple people, it might be best to upload & compile the content and then send the same content to multiple people instead of using the `sendMessage` function in a loop

**Comment by LuanRT** [comment]
This problem doesn't seem to happen in the previous version of Baileys.

**Comment by canove** [comment]
> @canove 
> > Seems like the promise of sendMessage is neither resolved or rejected. It keeps waiting forever...
> 
> This is likely a connection issue where the connection between the server & phone becomes stale, and the phone does not respond to the send request. Have to reconnect here.
> 

But I can send text messages normally when it occurs, It's make sense?

**Comment by bhavya32** [comment]
@canove I would still recommend to know if mediaUrl is generated or not. It will be like a break point. You will know the problem is before that code or after that.

**Comment by canove** [comment]
@bhavya32, unfortunately I couldn't do the test.

Like @LuanRT suggested, the previous version doesn't seem to have this. I just downgrade back to 3.4.1 and it's working fine for days. 

I did a lot of change on this version (using patch-package) to handle medias with got streams, like the new one. Its working fine, but I wan't to upgrade back to 3.5.1 as soon as it becomes fixed, so I will keep following this issue.

@adiwajshing, I suggest you to disable the stale bot on this one, since it was reported for many people after 3.5.1 release. Keeping it open will help us all to get further information about this bug. 

Thanks :)

**Comment by ariffb25** [comment]
> @canove For me, I am currently not facing the issue since 30 min. It might be early but these things I did to troubleshoot -
> 
> 1. I had implemented some code that calls baileys  after some delay.  In that code - 1 or 2 messages were dropping. I fixed it. So make sure all your request is reaching baileys LIB.
> 2. This is important -
>    Open the file -` \node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js`
>    You will find - `async refreshMediaConn(forceGet = false)`
>    Change it to - `async refreshMediaConn(forceGet = true)`
> 
> Do reply me the update worked or not. It will be helpful for both of us if we solve this issue somehow.

thank you very much, this is very helpful

**Comment by syahrularranger** [comment]
> @canove Bagi saya, saat ini saya tidak menghadapi masalah sejak 30 menit. Mungkin masih awal, tetapi hal-hal ini saya lakukan untuk memecahkan masalah -
> 
> 1. Saya telah menerapkan beberapa kode yang memanggil bailey setelah beberapa penundaan. Dalam kode itu - 1 atau 2 pesan jatuh. Aku telah memperbaikinya. Jadi pastikan semua permintaan Anda mencapai LIB bailey.
> 2. Ini penting - 
>    Buka file - ` \node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js`
>    Anda akan menemukan - `async refreshMediaConn(forceGet = false)`
>    Ubah ke -`async refreshMediaConn(forceGet = true)`
> 
> Balas saya pembaruan berfungsi atau tidak. Akan sangat membantu bagi kita berdua jika kita memecahkan masalah ini entah bagaimana.

Thx too.. from @ariffb25 I know this.. my issue has benn solved :D

**Comment by ilyaborodin** [comment]
> ale bot on this one, since it was report

Hey! Did u find solution for this bug?
