### ISSUE TITLE
[BUG] .on('CB:Pong') and on('CB:Cmd,type:disconnect') listeners not working.

### ISSUE THREAD

**Issue by sostenesapollo** [adiwajshing/Baileys#514]
These listeners not working for me. and I dont know how to know if the phone is disconnected.

`
this.on('CB:Cmd,type:disconnect', json => { 
 console.log('disconnected', json)
})
`

`
this.on('CB:Pong', json => {
   console.log('pong', json)
})
`

**Comment by bhavya32** [comment]
What I do - 
```
conn.on('connection-phone-change', data => {console.log(data)})
```
Now disconnect your mobile from internet.

Finally send a message to someone or try to read a chat ( I read chat from a person not on WA.) This way, WA will try to reach out to you mobile, and when it is not able to, the above event will be triggered.

**Comment by sostenesapollo** [comment]
I wanted to be in realtime, I got it
