### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Krazy-Projects** [adiwajshing/Baileys#517]
Hi,

Getting error while fetching all contacts and chats

**(node:11852) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 ws-close listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit**

Any way to increase the limit?

**Comment by sostenesapollo** [comment]
```conn.setMaxListeners(0);```

**Comment by sostenesapollo** [comment]
@Krazy-Projects  doe this worked ?

**Comment by PfizerDev** [comment]
> @Krazy-Projects doe this worked ?

Yeah! It worked.

Thanks

**Comment by yogipw** [comment]
> `conn.setMaxListeners(0);`

Thxx

**Comment by sostenesapollo** [comment]
You can disable the logs using `conn.logger.level = 'silent';`

**Comment by PfizerDev** [comment]
okk. Got it.

**Comment by PfizerDev** [comment]
> You can disable the logs using `conn.logger.level = 'silent'` to stop seeing these annoying logs

okk. Got it.

**Comment by sostenesapollo** [comment]
Solved ? Close the  issue

**Comment by PfizerDev** [comment]
> Solved ? Close the issue

Yeah

**Comment by kharaone** [comment]
> You can disable the logs using `conn.logger.level = 'silent'` to stop seeing these annoying logs

that will not solve the root issue though, only stop showing the log lines.

**Comment by PfizerDev** [comment]
> > You can disable the logs using `conn.logger.level = 'silent'` to stop seeing these annoying logs
> 
> that will not solve the root issue though, only stop showing the log lines.

You know any permanent solution? or any hack?

**Comment by sostenesapollo** [comment]
I know that bailyes keep ping into whatsapp server, so that makes sense this log ` checking phone connection...`
