### ISSUE TITLE
[BUG] can't get message status DELIVERY_ACK READ (4)

### ISSUE THREAD

**Issue by MaznAbdullah** [adiwajshing/Baileys#518]
**Describe the bug**

can't get message status DELIVERY_ACK READ (4) when receiver(jid) red it.
I'm only receiving status 2 and 3.
I can't get status 4. but it stops on 3
but it work if receiver(jid) opening whatsapp app during while sending the message !?

```
conn.on("chat-update", (chat) => {
if (chat.messages?.first?.status){
   console.log(`${chat.messages.first.key.id} ${chat.messages.first.status}`)
});
```

**Comment by PurpShell** [comment]
@adiwajshing, I talked to @MaznAbdullah, and the same happens for conn.messageInfo, no reads just deliveries. and on mobile the tick seems fine

**Comment by sostenesapollo** [comment]
You should use this two listeners, one just one of those detects sent, and just other detects delivered and read
`this.conn.on('CB:Msg', async (data) => {`

`this.conn.on('CB:Msg,cmd:ack', async (data) => {`

**Comment by soncemvo** [comment]
bug stil present, when message readed its return 3 instead of 4. And if you send audio message its return 4(not 5) when listened
