### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PfizerDev** [adiwajshing/Baileys#520]
**(node:8971) UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'query': Too Many Requests(429)
    at WAConnection.query**

Getting above error while fetching profile picture of mine.

module - **await conn.getProfilePicture()**

Need help.

**Comment by tobizinho** [comment]
Opa, boa tarde! Algumas pessoas "Devs" estão falando que a possibilidade do baileys cair por conta do multi device, O quê vocês tem a dizer ?!

**Comment by MuhShalah007** [comment]
Me too
