### ISSUE TITLE
[BUG] TypeError: Cannot read property 'url' of undefined 

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#525]
This error has been happening for 2 days, when I send some media files, this error occurs and the bot stops, since it was working a few days ago

```
if (item.url.toString().startsWith('http://') || item.url.toString().startsWith('https://')) {
             ^
TypeError: Cannot read property 'url' of undefined
```

**Comment by rayyreall** [comment]
lanjutkan prestasi anda

**Comment by ryuux** [comment]
Gege lu bang

**Comment by diosamuel** [comment]
This is your code issue, not from Baileys bug, so I thought please don't ask here because it's from your wrong code😁

**Comment by Hexagonz** [comment]
awikwok
