### ISSUE TITLE
[BUG] connect attempt x failed: Error: close

### ISSUE THREAD

**Issue by nugraizy** [adiwajshing/Baileys#526]
Is the server down? i got this error recently. any information will be good.

**Comment by guiireal** [comment]
Here too... Wait for more information.

**Comment by pedroanalista** [comment]
Here too!

**Comment by DielGanz** [comment]
I hope it will be fixed soon

**Comment by DielGanz** [comment]
I hope it will be fixed soon

**Comment by Zalleya** [comment]
tidur kawan

**Comment by pedroanalista** [comment]
The error happens in the file "WhatsAppWeb.Session.js" when trying to open connection with the line below:

this.conn = new WebSocket("wss://web.whatsapp.com/ws", {origin: "https://web.whatsapp.com"})

**Comment by andrody** [comment]
Here too

**Comment by TxC-Toxic** [comment]
I hope this can be fixed soon

**Comment by Zobin33** [comment]
Waiting For Solution....

**Comment by Nurutomo** [comment]
![image](https://user-images.githubusercontent.com/18616827/122095584-c7783880-ce37-11eb-8d0e-90bbefe87f79.png)

**Comment by sidvenu** [comment]
Same error here.

**Comment by BlackAmda** [comment]
Same error. Hope adiwajshing will fix soon.

**Comment by SheIITear** [comment]
Change the client version to like [2, 2119, 6] and you can connect again.

**Comment by sidvenu** [comment]
@SheIITear how to do that?

**Comment by yogipw** [comment]
Tidur bang udah malam bang
Udah malem

**Comment by AdlyAlimin** [comment]
> Change the wa web version to like [2, 2119, 6] and you can connect again.

perfect working...

**Comment by TxC-Toxic** [comment]
> > Change the wa web version to like [2, 2119, 6] and you can connect again.
> 
> perfect working...

its workink?

**Comment by SheIITear** [comment]
> @SheIITear how to do that?

Add `conn.version = [2, 2119, 6]` to your file or edit the file `src/WAConnection/0.Base.ts` on line 35.

**Comment by AdlyAlimin** [comment]
> > > Change the wa web version to like [2, 2119, 6] and you can connect again.
> > 
> > 
> > perfect working...
> 
> its workink?

yes. 
![image](https://user-images.githubusercontent.com/31163650/122096834-8e44c600-ce41-11eb-96a6-cd114c612e65.png)

**Comment by TOXIC-DEVIL** [comment]
> Is the server down? i got this error recently. any information will be good.

Yes 💔😂

**Comment by Nurutomo** [comment]
![image](https://user-images.githubusercontent.com/18616827/122097096-7d905200-ce39-11eb-8262-eaeeb052adfd.png)
worked!

**Comment by guiireal** [comment]
Worked !

![image](https://user-images.githubusercontent.com/13739343/122097199-c9b1a700-cde5-11eb-8c2d-bec8d9f97191.png)

**Comment by TxC-Toxic** [comment]
Working!!!

**Comment by Zobin33** [comment]
Thanks ShellTear Worked Great Solution!

**Comment by nugraizy** [comment]
okay 100% works. case closed. thanks to @SheIITear

**Comment by sidvenu** [comment]
For the time being, those who have CI/CD and can't change `node_modules`, just change the version property:
```
const conn = new WAConnection();
conn.version = [2, 2119, 6]
```

**Comment by phaticusthiccy** [comment]
Thanks for precious solution @SheIITear 
Perfect debugging :)

**Comment by TOXIC-DEVIL** [comment]
> > @SheIITear how to do that?
> 
> Add `conn.version = [2, 2119, 6]` to your file or edit the file `src/WAConnection/0.Base.ts` on line 35.

Thanks for fixing @SheIITear ❤

**Comment by canove** [comment]
@SheIITear , do you mind sharing how do you figured it out? 

Thanks 😊

**Comment by eduardohf14** [comment]
Changing the version seems to work the conection, but now whatsapp isn't reading the qrcodes

**Comment by ngadimin51** [comment]
![image](https://user-images.githubusercontent.com/72244361/122149168-d8e83180-ce85-11eb-807e-2fce8c3fe442.png)
This morning t to modified like @SheIITear say.
But i'm using npm to install baileys.
it's usefull and connected.
Thanks @SheIITear 

A lot of chat form my user in my inbox &128513;

**Comment by JuanDelValle18** [comment]
@SheIITear Could you make a video (on Youtube or another platform) to show us step by step the whole process? 😟

**Comment by SheIITear** [comment]
> @SheIITear , do you mind sharing how do you figured it out?
> 
> Thanks 😊

The response gotten from trying to connect was `["cmd", {"type": "update"}]`, which told me that it most likely had something to do with the version.
I then proceeded to edit the version to newer after realizing that it is pretty old.

**Comment by SheIITear** [comment]
> @SheIITear Could you make a video (on Youtube or another platform) to show us step by step the whole process? 😟

There's no need. It is already fixed on the newest version so you don't need to edit it anymore.

**Comment by josco007** [comment]
it works with client.version = [2, 2119, 6]; thanks 


`

               const client = new WhatsAppWeb(); 
                client.version = [2, 2119, 6];
                client.connectSlim() // does not wait for chats & contacts
                .then (user => {
                        console.log ("oh hello " + user.name + " (" + user.id + ")")
                        
                        client.receiveChatsAndContacts () // wait for chats & contacts in the background
                        .then (([chats, contacts, unread]) => {
                                console.log ("you have " + unread.length + " unread messages")
                                console.log ("you have " + chats.length + " chats")
                         
                        })
                })
                .catch (err => {
                        console.log("unexpected error: " + err); 
                
                });

`

**Comment by chuchiss** [comment]
ERROR TO -> 2, 2119, 6 ??

NEW VERSION ???

**Comment by alann-maulana** [comment]
> ERROR TO -> 2, 2119, 6 ??
> 
> NEW VERSION ???

```js
version: [number, number, number] = [2, 2140, 12]
```
https://github.com/adiwajshing/Baileys/blob/master/src/WAConnection/0.Base.ts#L35

**Comment by cakracomp** [comment]
work like a charm

maturnuwun @alann-maulana

**Comment by c7nasr** [comment]
Still Got this error

**Comment by aldimufti12** [comment]
still error ? pls help me
