### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#529]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by ferhacks** [comment]
Add this
``
conn.version = [2, 2119, 6]
``

**Comment by ldmuniz** [comment]
Exactly how @ferhacks comment, I changed on

node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js line 41

**Comment by ferhacks** [comment]
> Exactly how @ferhacks commented, I changed on
> 
> node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js line 41

Search your ``new WAConnection`` My case ``const Lxa = new WAConnection()``

const Lxa = new WAConnection()
Lxa.version = [2, 2119, 6]

Ready, Fixed! (Sorry for bad English)

**Comment by JoseCarlos056** [comment]
> Add this
> `conn.version = [2, 2119, 6]`

thanks, it works.

**Comment by drauber** [comment]
Very nice!
Thanks, i post the issue accidentaly, and not write the correct question.

**Comment by eduardohf14** [comment]
> Add this
> `conn.version = [2, 2119, 6]`

Changing the version seems to work the conection, but now whatsapp isn't reading the qrcodes
