### ISSUE TITLE
[BUG] WhatsApp not reading qrcode

### ISSUE THREAD

**Issue by eduardohf14** [adiwajshing/Baileys#530]
**Describe the bug**
I'm trying to read the qrcode generated by the lib in the console, but it doesn't work and gives me a message:

"Can't scan the code? Exit and relaunch the app"

When I try to read the qrcode direct from web.whatsapp.com in the browser, it works.

**To Reproduce**
1. Created a new connection
2. Try to read the qrcode from console

**Expected behavior**
Nothing happens, whatsapp doesn't recognize the qrcode

**Comment by JoseCarlos056** [comment]
Solved in #529

**Comment by eduardohf14** [comment]
> Solved in #529

nope, changing the version only worked to reconnect the existing sessions, but when you try to read the qrcode again, nothing happens

**Comment by JoseCarlos056** [comment]
In my case, it returned with its proper functioning when changing:
`const conn = new WAConnection()
conn .version = [2, 2119, 6]`

**Comment by eduardohf14** [comment]
> In my case, it returned with its proper functioning when changing:
> `const conn = new WAConnection() conn .version = [2, 2119, 6]`

I discovered the problem, I was using a new conn in a different place, so changing version in all places worked, thanks dude
