### ISSUE TITLE
loadAllMessages does not work

### ISSUE THREAD

**Issue by alucionet** [adiwajshing/Baileys#533]
Hello,

I've been trying to write a simple script to get ALL chats including its contents   and save them to database.
I tried the sample provided, modified it based on postings on discord, etc, and it still does not work. 
Found this loadAllMessages function , and it also does not spit out anything.

Here's the script:
import {
    WAConnection,
    MessageType,
    Presence,
    MessageOptions,
    Mimetype,
    WALocationMessage,
    WA_MESSAGE_STUB_TYPES,
    ReconnectMode,
    ProxyAgent,
    waChatKey,
} from '../src/WAConnection'

const fs = require("fs")
var chats
var client,rows,offset,encounteredOffset
var count = 0;
var msg = [];

/** 
 * Extract all your WhatsApp conversations & save them to a file
 * produceAnonData => should the Id of the chat be recorded
 * */ 
function extract (outputFile,offset) {
    // internal extract function
        rows = 0
        if (offset) {
            encounteredOffset = false
        } else {
            encounteredOffset = true
            fs.writeFileSync(outputFile, "chat,input,output\n") // write header to file
        }
}

async function extractChat (index) {
            const id = chats[index]
            if (id.includes("g.us") || !encounteredOffset) { // skip groups
                if (id === offset) {
                    encounteredOffset = true
                }
                if (index+1 < chats.length) {
                    return extractChat(index+1)
                }
                return
            }
            console.log("extracting for " + id + "...")

            var curInput = ""
            var curOutput = ""
            var lastMessage

            await client.loadAllMessages (id, async message => {
      msg.push(message);
      count += 1;
} , 5, false)
            .then (() => console.log("finished extraction for " + id))
            .then (() => {
                //if (index+1 < chats.length) {
                if (index+1 < 3) {
                    return extractChat(index+1)
                }
            })
}

async function connectWA (authCreds, outputFile, produceAnonData=false, offset=null) {
    client = new WAConnection() // instantiate

    client.autoReconnect = ReconnectMode.onConnectionLost // only automatically reconnect when the connection breaks
    client.connectOptions.maxRetries = 10

    // loads the auth file credentials if present
    fs.existsSync('./auth_info.json') && client.loadAuthInfo ('./auth_info.json')
    await client.connect()

    // credentials are updated on every connect
    const authInfo = client.base64EncodedAuthInfo() // get all the auth info we need to restore this session
    fs.writeFileSync('./auth_info.json', JSON.stringify(authInfo, null, '\t')) // save this info to a file

    client.on('chats-received', ({ hasNewChats }) => {
       console.log('oh hello ' + client.user.name + ' (' + client.user.jid + ')')

       chats = Object.keys(client.chats.dict)
       extract("output.csv")
       console.log("Begin extracting Messages")
       extractChat(0)
    })
}

let creds = JSON.parse(fs.readFileSync("./auth_info.json"))
connectWA(creds, "output.csv")

The versions of the software that I use:
-bash-4.2$ npm -v
7.7.6

  "name": "@adiwajshing/baileys",
  "version": "4.0.0",

I am not sure where to start debugging. I placed a few of console logs in the src files, to the point of retrieve variable in the loadMessage function in 7.MessagesExtra.ts , and it shows nothing.

Can someone please help point me to the right direction?

Thanks

**Comment by Santy-Gz** [comment]
i also have this problem ,someone know the porblem or solution??

**Comment by alucionet** [comment]
bumping up. please help?

**Comment by Jefry-nolastname** [comment]
leaving a (dot) .

**Comment by Jefry-nolastname** [comment]
is there another ways to load messages?

**Comment by alucionet** [comment]
anyone? any leads?

**Comment by bhavya32** [comment]
@Jefry-nolastname You are being rate limited. You are querying too much in too little time.

**Comment by bhavya32** [comment]
@alucionet loadAllMessages works perfectly fine. Its your code that has flaws. You can run it standalone and see. We can not help in your code.

**Comment by Jefry-nolastname** [comment]
thanks anyway for the reply, but i ended up using other plugin. Best of luck
