### ISSUE TITLE
[FEATURE] Make QR Terminal optional

### ISSUE THREAD

**Issue by banyu-wigara** [adiwajshing/Baileys#534]
Hi, firstly thank you for this wonderful package, love it.

Now, to the main topic, wouldn't it be good to make qr terminal as optional?
Why? because maybe some of us doesn't need it, maybe we can add another option at initialization?

**Comment by PurpShell** [comment]
conn.logger.level = "silent"

**Comment by ilyaborodin** [comment]
```
connWA.removeAllListeners('qr')
```
With this u will remove all listeners of qr event, including event that outputs qr to the terminal. After this you just need to add your custom qr listener with your logic(sending qr or smth else)

**Comment by banyu-wigara** [comment]
> ```
> connWA.removeAllListeners('qr')
> ```
> 
> With this u will remove all listeners of qr event, including event that outputs qr to the terminal. After this you just need to add your custom qr listener with your logic(sending qr or smth else)

This seems good for now, thank you for the answer.

**Comment by banyu-wigara** [comment]
Added here #552
