### ISSUE TITLE
error on startup, apparently a bug

### ISSUE THREAD

**Issue by fabriciocotag** [adiwajshing/Baileys#540]
I try install the latest version of baileys api on my machine, on new project directory and when i run "node index.js", i get the following error: 'unknown error', [ 'Cmd', { type: 'update' } ]

my console log:

E:\files\newproject>node index.js
[Baileys] connected to WhatsApp Web"
Got error:  [ undefined, 'unknown error', [ 'Cmd', { type: 'update' } ] ]

my index.js:
const WhatsAppWeb = require('baileys');
const client = new WhatsAppWeb();
client.connect()
.then (([user, chats, contacts, unread]) => {
  console.log ("oh hello " + user.name + " (" + user.id + ")")
  console.log ("you have " + unread.length + " unread messages")
  console.log ("you have " + chats.length + " chats")
})
.catch (err => console.log("Got error: " + err) )

**Comment by SheIITear** [comment]
Duplicate of #526.
