### ISSUE TITLE
REST API Question

### ISSUE THREAD

**Issue by guerrerog-git** [adiwajshing/Baileys#541]
If i need to create a REST API for multidevice using your library, do i need to connect for each request to the API or is not neccesary ? Thanks for your help

**Comment by sostenesapollo** [comment]
Hello @guerrerog-git you can use express to create a rest api

**Comment by guerrerog-git** [comment]
Hi thanks for your help, I have a problem, when i add the first express endpoint but the QR code is waiting for scan and blocks the request, but i dont need the QR code in this moment, i want to get the QR code in other endpoint.

The code:

`app.get('/crear-token', async (req: express.Request, res: express.Response) => {
    const conn = new WAConnection() // instantiate
    conn.autoReconnect = ReconnectMode.onConnectionLost // only automatically reconnect when the connection breaks
    conn.logger.level = 'debug' // set to 'debug' to see what kind of stuff you can implement
    // attempt to reconnect at most 10 times in a row
    conn.connectOptions.maxRetries = 10
    conn.chatOrderingKey = waChatKey(true) // order chats such that pinned chats are on top

    // uncomment the following line to proxy the connection; some random proxy I got off of: https://proxyscrape.com/free-proxy-list
    //conn.connectOptions.agent = ProxyAgent ('http://1.0.180.120:8080')
    await conn.connect()
    // credentials are updated on every connect
    const authInfo = conn.base64EncodedAuthInfo() // get all the auth info we need to restore this session
    fs.writeFileSync('./auth_info.json', JSON.stringify(authInfo, null, '\t')) // save this info to a file

    res.status(200).send(req.query.token)
});`

Thanks

**Comment by guerrerog-git** [comment]
Yes it is an REST API, there are more similars like REST API

**Comment by sostenesapollo** [comment]
you need to create an array of clients, or an object
```clients = []```
after this, each new client you push to the array
```
   const conn = new WAConnection() 
   clients.push(conn)
```

so you can access the client by the endpoint

```
app.get((req, res)=>{
    // Here you get the passed tokey via body or query
    // So you can find this especific token in your array list and do what yo want
    // In my case I use an object is quite easy to find... just using clients[req.body.token] I have access to the client
})
```

**Comment by guerrerog-git** [comment]
Thanks @sostenesapollo but the main problem is at the moment of invoke the await conn.connect(); the QR is showed on console (server) and the process is blocked until the user scan on console (server).

I think can be 2 endpoints different moments: 1) create new connection (with a identifier) 2) get QR code image    the main doubt is in what part must i invoke connect() method ?

**Comment by sostenesapollo** [comment]
If you do like I said in previous answer there's no any block. beacause the there's a event listner `conn.on('qr')` that you can have the qrcode asyncronously

**Comment by banyu-wigara** [comment]
> Thanks @sostenesapollo but the main problem is at the moment of invoke the await conn.connect(); the QR is showed on console (server) and the process is blocked until the user scan on console (server).
> 
> I think can be 2 endpoints different moments: 1) create new connection (with a identifier) 2) get QR code image the main doubt is in what part must i invoke connect() method ?

As @sostenesapollo answer, the qr code is not blocking

**Comment by bhavya32** [comment]
@guerrerog-git can you close the issue if its solved?

**Comment by guerrerog-git** [comment]
Thanks @sostenesapollo but when in My first endpoint when i invoke the method connect to create the instance and listen for QR code ... The method connect is waitting and not pass, the method blocks the API endpoint response and the QR Code is showed on server console waitting for scan ... I need connect and give the QR Code in other endpoint or what is the correct process ? Thanks

**Comment by guerrerog-git** [comment]
> you need to create an array of clients, or an object
> 
> ```
>    var  clients = []
> ```
> 
> after this, each new client you push to the array
> 
> ```
>    const conn = new WAConnection() 
>    clients.push(conn)
> ```
> 
> so you can access the client by the endpoint
> 
> ```
> app.get((req, res)=>{
>     // Here you get the passed token via body or query
>     // So you can find this especific token in your array list and do what yo want
>     // In my case I use an object is quite easy to find... just using clients[req.body.token] I have access to the client
> })
> ```

In this example in what part should i invoke the method connect ? I don't understand thanks

**Comment by bhavya32** [comment]
@guerrerog-git I don't see you have much experience on Rest API's and express. It will be better to learn first as that example by sostenesapollo is very much complete. Connect can be invoked whatever place you want after new WAConnection(). Please close the issue and continue to discord here - https://discord.gg/XF6XGrMe

**Comment by guerrerog-git** [comment]
Yes @bhavya32 i know express but i have the problem with the first endpoint /create-instance, when i invoke the first URL from a browser the request is loading the QR Code on the server console in a loop and the endpoint doesnt ends the response.

I need get the QR Code with the second endpoint for the instance created /qr  this is my code:

`var tokens = [];
var qrcode;

// this is a simple route to make sure everything is working properly
const runningMessage = `Server running at http://localhost:${port}`;
app.get('/create-instance', async (req: express.Request, res: express.Response) => {
    const conn = new WAConnection() // instantiate

    conn.autoReconnect = ReconnectMode.onConnectionLost // only automatically reconnect when the connection breaks
    conn.logger.level = 'debug' // set to 'debug' to see what kind of stuff you can implement
    // attempt to reconnect at most 10 times in a row
    conn.connectOptions.maxRetries = 10
    conn.chatOrderingKey = waChatKey(true) // order chats such that pinned chats are on top
    const token = crypto.randomBytes(10).toString('hex');
    tokens[token] = conn;
    
    fs.existsSync('./'+ req.query.token.toString() +'.json') && conn.loadAuthInfo ('./'+ req.query.token.toString() +'.json')
    // uncomment the following line to proxy the connection; some random proxy I got off of: https://proxyscrape.com/free-proxy-list
    //conn.connectOptions.agent = ProxyAgent ('http://103.198.126.237:8888')
    conn.on('qr', qr => {
        // Now, use the 'qr' string to display in QR UI or send somewhere
        qrcode = qr;
    });
    conn.connect();
    // credentials are updated on every connect
    const authInfo = conn.base64EncodedAuthInfo() // get all the auth info we need to restore this session
    fs.writeFileSync('./'+ req.query.token.toString() +'.json', JSON.stringify(authInfo, null, '\t')) // save this info to a file

   
    res.status(200).send(token);
});

app.get('/qr', async (req: express.Request, res: express.Response) => {
    const conn = tokens[req.query.token.toString()];
    res.status(200).send(qrcode);
});`

**Comment by bhavya32** [comment]
@guerrerog-git `conn.connectOptions.logQR=false` to avoid printing to console. You can generate token at the very beginning and send that. The rest of the code will run until it reaches end or return statement.

**Comment by guerrerog-git** [comment]
Many thanks the QR Code on console confuse me but with the option in false all is better thanks a lot
