### ISSUE TITLE
Any One?! 😄

### ISSUE THREAD

**Issue by TOXIC-DEVIL** [adiwajshing/Baileys#542]

**Comment by AlenSaito1** [comment]
First of all. You shouldn't promote your repos on other repos' issues. Plus this doesn't have anything to do with Baileys

Second, All you did was clone https://github.com/phaticusthiccy/WhatsAsenaDuplicated, removed the actual credits from the `README`, deleted all language JSON files except English. and finally made some changes to the code... I don't there's any effectual changes you made which makes it promotable as it's own repository. Even if you make good changes to the code, the right thing to do is contribute to the original repo.

Thank you and Please close this issue.
