### ISSUE TITLE
How can i download/save stories?

### ISSUE THREAD

**Issue by brkphp** [adiwajshing/Baileys#545]
Hello to everyone,

Is there a way to download the stories?

**Comment by AlenSaito1** [comment]
https://adiwajshing.github.io/Baileys/classes/waconnection.html#getstories

**Comment by brkphp** [comment]
this method returns stories, I am asking to download photos and videos.

**Comment by AlenSaito1** [comment]
The object it returns has an array of `WAMessage`. You can use `downloadMediaMessage` method in `WAConnection` to download them if they have media

**Comment by PurpShell** [comment]
^
