### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by Pegorino82** [adiwajshing/Baileys#548]
How to log in file via WAConnection.logger?

**Comment by Pegorino82** [comment]
?

**Comment by Pegorino82** [comment]
`conn.logger.child({filename: pino.destination('./filename.log')});` creates log file, but it still logging into console, not in file

**Comment by Tkd-Alex** [comment]
Folliwing ...

**Comment by bhavya32** [comment]
@Pegorino82 
```
conn.logger = pino(
  pino.destination("./pino-logger.log")
);
```
Works fine for me.
