### ISSUE TITLE
Error, any ideas?

### ISSUE THREAD

**Issue by ThePinkLyna** [adiwajshing/Baileys#549]
So I'm kinda new on this of making a whatsapp bot... I'm trying to do a simple but while I'm adding functions and everything, I started with baileys with a sample script, but I can't make it to work, it prints the qr but it doesn't let me to scan it (Pass like 2 seconds before it prints another) because it shows an error, then it prints another, after 10 attemps a crash appear and then it gets stuck.  (Sorry for my english, I don't know... please help? c:  )
![IMG-20210623-WA0238](https://user-images.githubusercontent.com/86382340/123168158-973b2600-d445-11eb-8b03-c043461d9932.jpg)

**Comment by SowTag** [comment]
Try increasing maxIdleTimeMs and maxRetries.

```js
// Example

const conn; // your WAConnection object

conn.connectOptions = {
maxIdleTimeMs: 60000,
maxRetries: 25
};
```

**Comment by AlenSaito1** [comment]
@ThePinkLyna are you on the latest version of Baileys?
\
