### ISSUE TITLE
Validation layer for target id on `sendMessage`

### ISSUE THREAD

**Issue by NicolasCaous** [adiwajshing/Baileys#55]
Sending messages to '+number@s.whatsapp.net' instead of 'number@s.whatsapp.net' crashes WhatsApp.

This isn't an issue per se, since this has nothing to do with an error that happens on the code using Baileys. However, since this is the direct culprit of the crashes, I think that it would be prudent to have some sort of validation layer before trying to send messages. This will avoid some headaches, as I have experienced while trying to understand what was going on, if incorrect ids are used.

Since you already mention how ids should be structured in the README, why not enforce it?

**Comment by adiwajshing** [comment]
Sure, makes sense. Maybe submit a PR for validation?

**Comment by CheloXL** [comment]
Just to comment in, I believe this is the same error I'm experiencing in #48.

**Comment by adiwajshing** [comment]
I've added an explicit validation layer while sending messages. It's enabled by default, check it out and lemme know if it works fine

**Comment by adiwajshing** [comment]
Assuming it's fixed now. Closing.
