### ISSUE TITLE
[BUG]connect attempt timed out

### ISSUE THREAD

**Issue by pinhaosama** [adiwajshing/Baileys#550]
**Describe the bug**
it just wont connect, no matter how much time i set it to try

**To Reproduce**
WARN [2021-06-23 21:41:12.729 +0000] (10908): connect attempt 1 failed: Error: timed out, retrying...
    class: "Baileys"

**Expected behavior**
it would connect quickly

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like? 
            maxIdleTimeMs: 60000,
            maxRetries: 10,
            connectCooldownMs: 4000,
            phoneResponseTime: 15000,
            maxQueryResponseTime: 10000,
            alwaysUseTakeover: true,
            queryChatsTillReceived: true
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

it worked in my first several attempts, but it does not work anymore, can someone help me?

**Comment by FaizBastomi** [comment]
@pinhaosama are you on the latest version of Baileys?

**Comment by pinhaosama** [comment]
yes

**Comment by bhavya32** [comment]
Did you delete old token and scan again? Faced similar situation and solved by doing that.

**Comment by pinhaosama** [comment]
how do i do that?

**Comment by bhavya32** [comment]
> how do i do that?

Share your code. Also tell Baileys version, that version is not of baileys.
