### ISSUE TITLE
Kick all anti banned members? 

### ISSUE THREAD

**Issue by RidwanXyZ** [adiwajshing/Baileys#553]
want to get all the group members out with this code.

`
y = []
for(let i of groupMembers){
y.push(i.jid)
}

conn.groupRemove(from, y)

`

N, damn, I'm blocked by Mark zuckerberg

**Comment by Nurutomo** [comment]
```js
conn.groupRemove(m.key.remoteJid, (await ccnn.groupMetadata(m.key.remoteJid)).participants.map(member => member.jid))
```

**Comment by Nurutomo** [comment]
> want to get all the group members out with this code.
> 
> `
> y = []
> for(let i of groupMembers){
> y.push(i.jid)
> }
> 
> conn.groupRemove(from, y)
> 
> `
> 
> N, damn, I'm blocked by Mark zuckerberg

because you're kicking multiple user at once

**Comment by RynKings** [comment]
You can't kick multiple members at once

you need to loop it
```
for(let i of groupMembers){
    conn.groupRemove(from, i.jid)
}
```

**Comment by AlenSaito1** [comment]
The 2nd argument should be an array

```TS
for(let i of groupMembers){
    conn.groupRemove(from, [i.jid])
}

// Using Array.map
// I highly recommend `awaiting` the promise that `groupRemove` returns  
(await conn.groupMetadata(jid)).participants.forEach(async (user) => await conn.groupRemove(jid, [user.jid]))
```

**Comment by Nurutomo** [comment]
for safety, use `@c.us` instead of `@s.whatsapp.net`

**Comment by ghostvar** [comment]
there is no groupRemove in documented 😂
