### ISSUE TITLE
[BUG] loadAllMessage throw "Not expecting response";

### ISSUE THREAD

**Issue by Jefry-nolastname** [adiwajshing/Baileys#555]
[the code.txt](https://github.com/adiwajshing/Baileys/files/6723324/the.code.txt)
**Describe the bug**
tried calling conn.loadAllMessages after the client opened and received a throw on the method.
**To Reproduce**
** I attached a file so it's easier to look at the code
1. Creating a connection and using loadAllMessages
class Bailey {
    constructor() {
        this.client = new WAConnection();
        this.client.logger.level = "silent";
        this.client.connectOptions = {
            regenerateQRIntervalMs: 6_000,
            maxIdleTimeMs: 45_000,
            // waitOnlyForLastMessage: false,
            // waitForChats: true,
            // maxRetries: Infinity,
            // connectCooldownMs: 3_000,
            // phoneResponseTime: 10_000,
            alwaysUseTakeover: true,
        };
    }
    async createNewClient(callback) {
        try {
            callbacks(this.client, callback); //this is for registering all the callback {on-chat-update, etc} and return them 
            console.log("initialize");
            await this.client.connect();
            // this is what i did when the callback on "opened" triggered
            // client.initialize();
            //var clientInfo = await getClientInfo();
            //save it on database
        } catch (e) {
            console.log(e.message);
            return;
            // return callback({ STATUS: 0, TYPE: "CLOSED", DATA: e.message });
        }
    }
}
//using the bailey class
var newclient = new Bailey();
newClient.createNewClient(async function (data) {
   if (data["STATUS"] == 1 && data["TYPE"] == "READY") {
   // saving authinfo and stuff
    await strapi.services["session-data"].createClient(
	    data,
	    newClient
    );
   //trying the loadAllmessages to add message history
    try{
      newClient.client.loadAllMessages("something@s.whatsapp.net", (message) =>
        console.log("Loaded message with ID: " + message.key.id)
      );
    }
      catch(e){console.log(e.message);//keep getting here and throwing}
  
  }
});

**Expected behavior**
A results of an array of messages.

**Environment (please complete the following information):**
 - Is this on a server? 
 =>yes, local strapi server 
 - What do your `connectOptions` look like? 
 => mostly default settings
 this.client.connectOptions = {
            regenerateQRIntervalMs: 6_000,
            maxIdleTimeMs: 45_000,
            // waitOnlyForLastMessage: false,
            // waitForChats: true,
            // maxRetries: Infinity,
            // connectCooldownMs: 3_000,
            // phoneResponseTime: 10_000,
            alwaysUseTakeover: true,
        };  
 - Do you have multiple clients on the same IP?
 => same IP as in same network? yes but different devices and still throw on single device use 
 - Are you using a proxy?
 => nope

**Additional context**
=> i want to use this plugin to create multi-client WA from  multiple devices cause this is by far the lightest WA api i had  found for now. and i created a class to handle each Instances called Bailey(); so it's easier to manage callback from each conn instance. Thanks in advance for creating this plugin.

**Comment by bhavya32** [comment]
@Jefry-nolastname So you get some messages logged before being thrown the error or not? Also please use ``` to format the code as otherwise it becomes unreadable.
