### ISSUE TITLE
isOnWhatsAppNoConn still works? Android app crashing!

### ISSUE THREAD

**Issue by canove** [adiwajshing/Baileys#559]
I have a number that once I send a message to it, it crashes de Android app
The number is 000000000006, you can give a try (be careful, it will crash the mobile app)

I'm working in a way to check if the number exists on my contact creation logic. Since I don't always have a connection available, I tried to use isOnWhatsAppNoConn, but it always return `{ exists: true, jid: '000000000006@s.whatsapp.net' }`

- This method still works for someone else? If it's not, I suggest to remove it from the isOnWhatsApp fallback, since it can lead to errors.
- Is there a way to check if a number exists without a connection?

**Comment by khoirulh1610** [comment]
I've experienced something similar, it happened because of my mistake in the script.

**Comment by gunslingerOP** [comment]
> I've experienced something similar, it happened because of my mistake in the script.

@khoirulh1610 Could you say what the mistake was? I'm facing a similar issue when trying to send a message!

**Comment by bhavya32** [comment]
@gunslingerOP I can confirm its broken now.

**Comment by bhavya32** [comment]
@canove I can confirm `isOnWhatsAppNoConn` is broken and I proposed to remove it as a fallback. Currently there is no other method. There is no need for connection between phone and baileys for `isOnWhatsApp` . You just have to connect once and it should then work even if phone is not connected to internet. (Not Sure about it. Tested for like 30 min)
