### ISSUE TITLE
How to send HydratedURLButton

### ISSUE THREAD

**Issue by RidwanXyZ** [adiwajshing/Baileys#560]

**Comment by FaizBastomi** [comment]
Until now no one has been able to make a replica of it.
there may be, but the message is not visible on other people, only visible on your own number.
I've tried it and it's only visible on your own number, not visible on others.

or, can wait for someone to explain it to you.

**Comment by bhavya32** [comment]
@RidwanXyZ Please close the issue? As Faiz explained, its available only to Official API. Sending through Baileys requires modifying WhatsApp's sqlite database.
