### ISSUE TITLE
RequestError: connect ECONNREFUSED 443

### ISSUE THREAD

**Issue by Cosangeles22** [adiwajshing/Baileys#561]
``Describe the bug
downloadAndSaveMediaMessage does not work, I get the error indicated below,

To Reproduce

I used express zhs and docker,
tried to download media from post
Expected behavior
I'm waiting for the file to download from the message, but I get an error

Environment (please complete the following information):

Additional context

`backend_nodejs | RequestError: connect ECONNREFUSED 127.0.0.1:443
backend_nodejs | at ClientRequest. (/backend_nodejs/node_modules/got/dist/source/core/index.js:953:111)
backend_nodejs | at Object.onceWrapper (events.js:422:26)
backend_nodejs | at ClientRequest.emit (events.js:327:22)
backend_nodejs | at ClientRequest.EventEmitter.emit (domain.js:467:12)
backend_nodejs | at ClientRequest.origin.emit (/backend_nodejs/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
backend_nodejs | at TLSSocket.socketErrorListener (_http_client.js:469:9)
backend_nodejs | at TLSSocket.emit (events.js:315:20)
backend_nodejs | at TLSSocket.EventEmitter.emit (domain.js:467:12)
backend_nodejs | at emitErrorNT (internal/streams/destroy.js:106:8)
backend_nodejs | at emitErrorCloseNT (internal/streams/destroy.js:74:3)
backend_nodejs | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)`

Code:

`    attachmentRender(v: WebMessageInfo, message: any = {}){
        const attachment = v.message;
 if(attachment[MessageType.sticker]) {
     try {
         const savedFile = this.conn.downloadAndSaveMediaMessage(v, './Media/media_in_' + 'lol')
         console.log(' sent media, saved at: ' + savedFile)
     } catch (err) {
         console.log('error in decoding message: ' + err)
     }
 }`

**Comment by bhavya32** [comment]
@Cosangeles22 
1. Remove the questions you have not answered and format log as code with ```
2. This looks problem in your code.
3. It is must to share your code(Not Full, only the part where you download).

**Comment by Cosangeles22** [comment]
> @Cosangeles22
> 
> 1. Remove the questions you have not answered and format log as code with ```
> 2. This looks problem in your code.
> 3. It is must to share your code(Not Full, only the part where you download).

Corrected, thanks. I was looking for information by mistake, I think this might be related to got and https-proxy-agent itself, https://github.com/sindresorhus/got/issues/951 was discussed here

**Comment by Cosangeles22** [comment]
Please help @bhavya32 @barkerpedro @galiazzi @edgardmessias

**Comment by bhavya32** [comment]
@Cosangeles22 I don't see any baileys error. It says connection refused on 127.0.0.1:443.
