### ISSUE TITLE
Load message with MessageID

### ISSUE THREAD

**Issue by ni3mumbaikar** [adiwajshing/Baileys#563]
I am having a messageID where Image is attached. I want to download media when someone reply to that Image message i.e. When the new message [MessageType-ExtendedMessage] is extended to the previous messageID [MessageType-ImageMessage]  

Now I can fetch last n messages from the user and check each with loops that it matches with the messageID or not   

`const messages = await conn.loadMessages ("xyz-abc@g.us", n)`  

Also I can fetch the entire history with loadAllMessages, is there any better way to load that single specific message using message id directly so that I can download the media attached to it.

**Comment by ibnusyawall** [comment]
```js
let message = conn.loadMessage(jid, id)
```

**Comment by alucionet** [comment]
how did you get loadAllMessages to work? care to share a snippet of your code? Some of us have been having trouble to make it work.

**Comment by bhavya32** [comment]
@ni3mumbaikar Please close the issue if its solved.

**Comment by ni3mumbaikar** [comment]
> how did you get loadAllMessages to work? care to share a snippet of your code? Some of us have been having trouble to make it work.

`const messages = await conn.loadAllMessages ("xyz@c.us", message => console.log("Loaded message with ID: " + message.key.id))`

this loads entire conversation history in messages variable

**Comment by ni3mumbaikar** [comment]
> @ni3mumbaikar Please close the issue if its solved.

Yes solved, Thank you all the contributors and developers 👍
