### ISSUE TITLE
[BUG] Application crashes due to incorrect ID format when sending messages (Request to update documentation)

### ISSUE THREAD

**Issue by gunslingerOP** [adiwajshing/Baileys#564]
**Describe the bug**
sendMessage method crashes WhatsApp application and causes weird behavior, I found out the hard way that one should not enter a "+" before the number they're sending it to

This way made the app crash and messed up everything : ["+" then country code][Phone number]

The correct way of making an ID is : [country code WITHOUT a +][Phone number you're sending to]@s.whatsapp.net

**To Reproduce**
1. Created a new connection and authenticated it
2. try to send a normal text message
3. Provide the ID parameter in this format :  ["+" then country code][Phone number]
4. Whatsapp app on your phone crashes and your node app will keep trying to find a phone connection

**FIX**
Simply **do not** add a + before the country code when creating an ID, it should be created in this format:

[country code WITHOUT a +][Phone number you're sending to]@s.whatsapp.net

Maintainers, please update the documentation as you explicitly show a + before the country code!

**Comment by bhavya32** [comment]
@gunslingerOP You are absolutely right. I will make PR.
