### ISSUE TITLE
[FEATURE] Check WA Version

### ISSUE THREAD

**Issue by banyu-wigara** [adiwajshing/Baileys#566]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
A: Done
2. Read through the readme at least once
A: Done
3. Search the docs for the feature you're looking for
A. Done

**Just describe the feature/question**
Is there any way to check WA Web version? Sometimes the connection is refused (Not always) because the version sent during initialization (?) is different, maybe it's good to have a function for checking before init and listener to listen for a new version change (IDK if this one is possible since I don't have much understanding about this package yet)

**Comment by bhavya32** [comment]
@banyu-wigara Use this - 
```
https://web.whatsapp.com/check-update?version=2.2123.8&platform=web
```
You can use this api and tell baileys which version to use - 
```
conn.version = [2, 2123, 8]
```

**Comment by banyu-wigara** [comment]
> https://web.whatsapp.com/check-update?version=2.2123.8&platform=web

@bhavya32 Thank you for the reply, and before I close this issue, I want ask one more thing, how can I check if my account got banned when using this package?

**Comment by bhavya32** [comment]
@banyu-wigara Don't have experience with number bans. I don't think whatsapp will tell whatsapp web  if number is blocked. You can join out discord and ask there - https://discord.gg/7FYURJyqng

**Comment by banyu-wigara** [comment]
@bhavya32 Oke, thank you for the reply
