### ISSUE TITLE
[BUG] Sending Messages to Groups - { status: "ERROR" }

### ISSUE THREAD

**Issue by phaticusthiccy** [adiwajshing/Baileys#567]
I'm using Baileys@3.4.1 Version. When I try to trigger command above 2.21.12.17 WhatApp version, the data turns like that:
```json
{
  "id": "msg_id",
  "jid": "jid@g.us",
  "fromMe": true,
  "message": ".alive",
  "timestamp": time,
  "data": {
    "key": {
      "remoteJid": "jid@g.us",
      "fromMe": true,
      "id": "msg_id"
    },
    "message": {
      "conversation": ".alive"
    },
    "messageTimestamp": "time",
    "status": "ERROR"
  },
  "reply_message": false,
  "mention": false
}
```

But above the 2.21.12.17 version it turns like that:
```json
{
  "id": "msg_id",
  "jid": "jid@g.us",
  "fromMe": true,
  "message": ".alive",
  "timestamp": time,
  "data": {
    "key": {
      "remoteJid": "jid@g.us",
      "fromMe": true,
      "id": "msg_id"
    },
    "message": {
      "conversation": ".alive"
    },
    "messageTimestamp": "time",
    "status": "SERVER_ACK"
  },
  "reply_message": false,
  "mention": false
}
```
While it works on data with **SERVER_ACK**, it does not work on data with **ERROR**. This error only happens in groups.
Is there any solutions for this?

**Comment by bhavya32** [comment]
@phaticusthiccy Why not jump on to Baileys v3.5.1? or try using - 
```
conn.version=[2, 2121, 7]
```

**Comment by phaticusthiccy** [comment]
> @phaticusthiccy Why not jump on to Baileys v3.5.1? or try using -
> 
> ```
> conn.version=[2, 2121, 7]
> ```
> 
> I can not recreate the problem. I am on android v2.21.12.21

After 3.4.1 bailyes version, ı am facing "marker was not found", "not expected response", and many issues. That's why, ı prefer to stay 3.4.1 
Also ı tired `conn.version` previously. It doesn't effect.
