### ISSUE TITLE
List Message

### ISSUE THREAD

**Issue by mrfzvx12** [adiwajshing/Baileys#568]
How to use & send list message

**Comment by mrfzvx12** [comment]
![IMG-20210704-WA0111](https://user-images.githubusercontent.com/72728486/124379537-e99c0280-dce1-11eb-82a8-27a0d200fd6d.jpg)

**Comment by mrfzvx12** [comment]
![Uploading IMG-20210704-WA0110.jpg…]()

**Comment by mrfzvx12** [comment]
![IMG-20210704-WA0110](https://user-images.githubusercontent.com/72728486/124379566-03d5e080-dce2-11eb-833b-4371013599f8.jpg)

**Comment by FaizBastomi** [comment]
maybe you want to play with WAMessageProto if you want.

**Comment by mrfzvx12** [comment]
> maybe you want to play with WAMessageProto if you want.

![IMG-20210704-WA0001](https://user-images.githubusercontent.com/72728486/124379926-1a7d3700-dce4-11eb-9e63-39bc1fb7bc02.jpg)

Udah jadi harus pake WhatsApp biasa.. tadi pake WhatsApp bisnis..

**Comment by FaizBastomi** [comment]
if it is solved, please close this issue. Thank you.
