### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pegorino82** [adiwajshing/Baileys#569]
**Describe the bug**
Calling method `loadAllUnreadMessages()` returns 0 when there is chat with unread messages

**To Reproduce**
1. Write into chat
2. Start app

**Expected behavior**
Log with unread messages presented

from example:
```
const unread = await conn.loadAllUnreadMessages();
console.log ('you have ' + unread.length + ' unread messages');
```
in log
`you have 0 unread messages`
data got from `chats-received`:
```
 {
        "jid": "70123456789@s.whatsapp.net",
        "count": 2,
        "name": "Name",
        "t": 1625401525,
        "mute": "0",
        "message": "true",
        "spam": "false",
        "messages": []
    },
```
and whatsapp looks like:
![image](https://user-images.githubusercontent.com/25233395/124385818-0a635880-dce0-11eb-8daf-3dc4586f0f39.png)

**Comment by bhavya32** [comment]
@Pegorino82 Lets solve it step by step.  Run this - 

```
const unread= await conn.chats.all().filter(chat => chat.count > 0)
console.log(JSON.stringify(unread))
```
It should return the chats where count is above 0.  Share its output.

**Comment by Pegorino82** [comment]
@bhavya32 yes, i did the same) i filtered all chats and load messages from unread. and i saw your pr, waiting it be merged.

**Comment by bhavya32** [comment]
@Pegorino82 I don't think my PR will do any good to you. My PR removed extra unread count. I did not get 0 unread even before.
