### ISSUE TITLE
Extract Chat List + Last Conversation + Chat name and Picture

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#57]
Hello!

There are a simple way to get chat list with the last message, unread messages, chat picture and chat name?

I tried like this:

```javascript
const [chats, contacts, unread] = await client.receiveChatsAndContacts()
        
chats.map((chat) => {
   const { t: timestamp, jid } = chat
   client.loadConversation(jid, 1)
})
```

But the problem is: I am not able to capture all last messages from all my chats.

Looks like `receiveChatsAndContacts()` stops after ~80 requests.

**Comment by adiwajshing** [comment]
Hi, do you mean `receiveChatsAndContacts()` stops after 80 chats?

**Comment by kaykyr** [comment]
> Hi, do you mean `receiveChatsAndContacts()` stops after 80 chats?

Example:

```javascript
const [chats, contacts, unread] = await client.receiveChatsAndContacts()

let count = 0

chats.map((chat) => {
   const { t: timestamp, jid } = chat
   count++
   client.loadConversation(jid, 1)
   console.log(`Total ${count}`) //about ~80 it stops... (remaining about 500 chats)
})
```

**Comment by kaykyr** [comment]
> Hi, do you mean `receiveChatsAndContacts()` stops after 80 chats?

Oh, you updated the ``receiveChatsAndContacts()``. Thanks a lot!
