### ISSUE TITLE
connection-phone-change event

### ISSUE THREAD

**Issue by Pegorino82** [adiwajshing/Baileys#570]
**How `'connection-phone-change'` works?**

from example:
  ```
conn.on('connection-phone-change', (update) => {
      console.log('[connection-phone-change]', update)
  });
```
i turn off connection on device and see in logs:

> INFO [2021-07-04 12:58:02.235 +0000] (11060): connected to WhatsApp Web server, authenticating via takeover
>     class: "Baileys"
> WARN [2021-07-04 12:59:02.363 +0000] (11060): connect attempt 3 failed: Error: timed out, retrying
>     class: "Baileys"
>     error: {}
> INFO [2021-07-04 12:59:06.558 +0000] (11060): connected to WhatsApp Web server, authenticating via takeover
>     class: "Baileys"
> WARN [2021-07-04 13:00:06.692 +0000] (11060): connect attempt 4 failed: Error: timed out, retrying
>     class: "Baileys"
>     error: {}
> INFO [2021-07-04 13:00:10.891 +0000] (11060): connected to WhatsApp Web server, authenticating via takeover
>     class: "Baileys"
> WARN [2021-07-04 13:01:11.042 +0000] (11060): connect attempt 5 failed: Error: timed out, retrying
>     class: "Baileys"
>     error: {}
> INFO [2021-07-04 13:01:15.212 +0000] (11060): connected to WhatsApp Web server, authenticating via takeover
>     class: "Baileys"
> WARN [2021-07-04 13:02:15.336 +0000] (11060): connect attempt 6 failed: Error: timed out, retrying
>     class: "Baileys"
>     error: {}

but no `[connection-phone-change]` with `update` object

**Comment by banyu-wigara** [comment]
@Pegorino82
From your logs, it's seems like you try to login but your phone is doesn't have any internet connection (Sorry if I'm wrong).
Last time I tried, phone connection related event is only triggered when you have successfully logged in and you want to do some action(s) like sending message (Correct me if I'm wrong here).

**Comment by Pegorino82** [comment]
@banyu-wigara yes, you are right. it's not good logs.
![image](https://user-images.githubusercontent.com/25233395/124395649-e880ca80-dd0d-11eb-8758-0e23366b4877.png)
here turn off internet on device, but nothing in console. Also i sent messege to device and nothing happened.
But if i turn internet on messages are delivered.
I expect to get message if my device loose connection - is `'[connection-phone-change]' `ritgh event for this?

**Comment by bhavya32** [comment]
@Pegorino82 I will explain. WA does not always send data to phone. It sends ping to phone and phone returns pong request at fixed intervals say 15 min. Now when you disconnect your phone, Baileys or WA-Web does not know it. 

Sending Message was supposed be sending from Baileys using `sendMessage()`. It will surely trigger your event in case phone is not connected. I would recommend sending ping instead of message - 
```
conn.query({ json: ['admin', 'test'] }
```
You can send this at whatever interval you want to.

**Comment by banyu-wigara** [comment]
@Pegorino82 
Sorry for not being clear, what I mean is when you try to send message from your "bot" then it will first check for phone connection, I don't know if the phone connection is checked elsewhere but that's what I've tested

**Comment by banyu-wigara** [comment]
@bhavya32 Ah ... so that's how it works, thanks for the explanation, anyways I want ask something, how can I know if my WA account got banned when using this package? And if there is method to get WA web version?

**Comment by banyu-wigara** [comment]
@bhavya32 Ah ... so that's how it works, thanks for the explanation, anyways I want ask something, how can I know if my WA account got banned when using this package? And if there is method to get WA web version?

**Comment by Pegorino82** [comment]
@bhavya32 ok, thx)
