### ISSUE TITLE
[BUG] Send Message to group make WhatsApp app error

### ISSUE THREAD

**Issue by hasbimsdd27** [adiwajshing/Baileys#571]
**Describe the bug**
When I want to send message to group, whatsapp app on my android phone (as sender) became force close

**To Reproduce**
1. Send Message to group
2. Check whatsapp on android phone and it became crash
3. Baileys Log became checking phone connection

**Expected behavior**
it should be not error, because when I send message to other person contact is normal but when i send message to group its became error on my whatsapp app

**Environment (please complete the following information):**
 - Is this on a server? No, Still in Local
 - What do your `connectOptions` look like? default
 - Do you have multiple clients on the same IP? yes
 - Are you using a proxy? no

**Additional context**
- whatsapp version 2.21.12.21 (Android)
- Baileys version  3.5.1

![image](https://user-images.githubusercontent.com/58213577/124414135-45b36500-dd7c-11eb-81a7-248ff6595e0c.png)

**Comment by bhavya32** [comment]
@hasbimsdd27 You forgot to share your code. Especially the format of your group ID. WhatsApp is crashing as most probably your group id is wrong.

**Comment by hasbimsdd27** [comment]
oh yap, I forgot to share my code

this is my group id `6282371396603-1601467283@g.us`

this is my code 

```
exports.bulkSendMessage = async (session, to, message, userUnique, io) => {
  let success = 0;

  const handleSend = async (number) => {
    console.log(
      number.includes("-") ? `${number}@g.us` : `${number}@s.whatsapp.net`
    );
    await this.sendMessage(
      session,
      number.includes("-") ? `${number}@g.us` : `${number}@s.whatsapp.net`,
      message,
      userUnique
    );
    success++;
    if (success < to.length - 1) {
      setTimeout(async () => {
        await handleSend(to[success]);
      }, 500);
    }
  };
  await handleSend(to[success]);
};
```


this is the screenshot
![image](https://user-images.githubusercontent.com/58213577/124421956-b498ba00-dd8c-11eb-8267-d2d341329755.png)

**Comment by hasbimsdd27** [comment]
that was my mistake, it's already solved. thanks
