### ISSUE TITLE
[BUG] updateProfileName

### ISSUE THREAD

**Issue by NurFy** [adiwajshing/Baileys#575]
Why, when i try conn.updateProfileName , it send "Bad Request(400)"

**Comment by banyu-wigara** [comment]
@NurFy Can you provide some SS for logs? And maybe some step to reproduce, like is it fresh install or on some conditions maybe?

**Comment by bhavya32** [comment]
@NurFy this must be the case for WhatsApp Business. I tested and it works only on standard.

**Comment by NurFy** [comment]
> @NurFy this must be the case for WhatsApp Business. I tested and it works only on standard. This is because even WA-web does not allow you to change profile name for WA-Business

Okay Thanks For Your Information

**Comment by sandro-salles** [comment]
Up... guys, does anyone knows how to change profile name on MD version?

Thanks in advance!
