### ISSUE TITLE
[BUG] Freeze when using getProfilePicture after 1 to 2 days.

### ISSUE THREAD

**Issue by kingsocialvn** [adiwajshing/Baileys#576]
Hello there

Everything works great and no problem when we use it on v3.5.1

But recently we discovered that when we use getProfilePicture for about 1 to 2 days, everything becomes frozen.

And can't do anything after that. The problem only resolved when we restarted the server

`avatar = await conn.getProfilePicture(jid).catch(() => '');`

Thanks

**Comment by bhavya32** [comment]
It will be better to add console.log() in catch and provide us some logs if any.

**Comment by kingsocialvn** [comment]
I was going to send logs before but unfortunately, I checked and didn't see any logs.

It closes with and does not save any logs.

**Comment by bhavya32** [comment]
> It closes with and does not save any logs. 
It only logs to terminal and does not save it anywhere. Are you saying that your terminal closed and you missed the log? Or there was no log on terminal itself?

**Comment by kingsocialvn** [comment]
Hello there

I'm using PM2 to run Baileys

But It only shows logs about connection information. But it doesn't show any logs related to the error or anything that I can send.

This is source code for it

![image](https://user-images.githubusercontent.com/87051663/124734785-a9d25680-df3f-11eb-8e22-ed91e792cd21.png)

I want to get user data with avatar

Everything worked great for about 1 day. But then it froze.

I deleted the line

`client.user.avatar = await client.getProfilePicture(client.user.jid).catch(() => "");`

And everything works fine and doesn't freeze anymore.

**Comment by kingsocialvn** [comment]
Any guys can help for this?
