### ISSUE TITLE
Too Many Request [BUG]

### ISSUE THREAD

**Issue by guerrerog-git** [adiwajshing/Baileys#577]
**Describe the bug**
I get this message:
(10016): connect attempt 1 failed: Error: Unexpected status in 'admin': Too Many Requests(429), retrying...

**To Reproduce**
1. conn.connect()

**Expected behavior**
I think retry the connection and show the QR Code

**Comment by LuanRT** [comment]
This is not a bug, it happens if you request too many QR codes without scanning. I suggest you to close the issue.

**Comment by guerrerog-git** [comment]
Ok thanks, can i indicaste the time between each request of QR Code ?
