### ISSUE TITLE
How can i convert the qr string (qr code) into image?

### ISSUE THREAD

**Issue by guerrerog-git** [adiwajshing/Baileys#578]
I'm getting a string similar to this: 1@sXDVmVRiHqrZpWZBETRCShe4/J8sVhFdyNYVF1x4gQo2O9tJQmFNGcxQdjZjRZ/O73NIet3Ofy4Dew==,PT8YgVPVqZSwkFdNnvb7NX69niYl5zuMevLV/2nH9jg=,avFEPaV8wvN104UD3uTwAA==

how can i convert into image ?

**Comment by LuanRT** [comment]
You can use `qr-image` for that.
```js
const qr = require("qr-image");

//...

conn.on("qr", (qr_data) => {
    let qr_img_buffer = qr.imageSync(qr_data);
});

```

**Comment by bhavya32** [comment]
@guerrerog-git I highly recommend joining discord server for help related to your project as its not a baileys issue.

**Comment by guerrerog-git** [comment]
Ok, is not a issue is a question, thanks.
