### ISSUE TITLE
Memory needed

### ISSUE THREAD

**Issue by guerrerog-git** [adiwajshing/Baileys#579]
Hoy much RAM (MB or GB) do i need for have 10 instances at same time ?

**Comment by PurpShell** [comment]
100mb?

**Comment by mSharif10** [comment]
I think more than 100mb.

**Comment by banyu-wigara** [comment]
> Hoy much RAM (MB or GB) do i need for have 10 instances at same time ?

@guerrerog-git It depends, if you code correctly (no memory leaks) then it's not that much, I have around 20 active instance now and its not taking that much ram (stable in 100 ~ 120mb), but it's different when you have memory leak, even 1 instance can get your memory up to the sky (no kidding here ...)

**Comment by banyu-wigara** [comment]
> Hoy much RAM (MB or GB) do i need for have 10 instances at same time ?

@guerrerog-git It depends, if you code correctly (no memory leaks) then it's not that much, I have around 20 active instance now and its not taking that much ram (stable in 100 ~ 120mb), but it's different when you have memory leak, even 1 instance can get your memory up to the sky (no kidding here ...)

**Comment by Pegorino82** [comment]
> > Hoy much RAM (MB or GB) do i need for have 10 instances at same time ?
> 
> @guerrerog-git It depends, if you code correctly (no memory leaks) then it's not that much, I have around 20 active instance now and its not taking that much ram (stable in 100 ~ 120mb), but it's different when you have memory leak, even 1 instance can get your memory up to the sky (no kidding here ...)

i have got 160mb when running example script
