### ISSUE TITLE
Freezes when getProfilePicure

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#58]
Code:
```js
async getChatsAndConversations() {
   const client = await this.getClient()
   const [chats, contacts, unread] = await client.receiveChatsAndContacts()
   
   let _chats = chats.slice(0)
   _chats.sort((a, b) => {
      return b.t - a.t
   })

   await Promise.all(
      _chats.map(async (chat, index) => {
         const profilePicture = await client.getProfilePicture(chat.jid) //After some requests it freezes

         const phoneNumber = formatPhoneNumber(
            `+${chat.jid.split('@')[0]}`
         )

         _chats[index] = {
            id: chat.jid,
            timestamp: chat.t,
            name: chat.name ? chat.name : phoneNumber,
            phoneNumber,
            unread: chat.count,
            msgs: chat.messages,
            profilePicture: profilePicture,
            chat,
         }
      })
   )
}
```

Looks like theres something wrong with `getProfilePicture()`, like `loadConversation()` after executing these functions some times it just stops...

I'll try to find the problem, but I am opening this issue to inform you about it, and ask for any help.

**Comment by kaykyr** [comment]
This is the way WhatsApp send requests:
![Screen Shot 2020-07-08 at 21 04 32](https://user-images.githubusercontent.com/30188217/86982180-04837780-c15f-11ea-9733-ab4bd0057a9f.png)

This is what this Lib is sending:
![Screen Shot 2020-07-08 at 21 04 23](https://user-images.githubusercontent.com/30188217/86982191-0cdbb280-c15f-11ea-9bdf-2359f690a838.png)

Looks like this model of using timestamp isn't reliable, because I can send many requests in the same second. Maybe a index model will work better.

**Comment by kaykyr** [comment]
Yeaaah! That's it!

This kind of tagging isn't reliable, try something like this:

```javascript
export var tagCounter = {
    count: 0,
}

// whatsapp requires a message tag for every message, we just use the timestamp as one
export function generateMessageTag() {
    tagCounter.count++
    return tagCounter.count.toString()
}
```

This is just an example I used to test it. Problem solved with this.

Could you please solve that using a better way? <3

**Comment by adiwajshing** [comment]
This was quite interesting. Never had this problem before, but it's a good idea to make the library more reliable with a fix like this. Since you've opened a PR #59 for this, I'm closing this issue.

Thanks.
