### ISSUE TITLE
unexpected error: ,unknown error,Cmd,[object Object]

### ISSUE THREAD

**Issue by mSharif10** [adiwajshing/Baileys#580]
**When I run the script below I am getting the following:**

`[Baileys] connected to WhatsApp Web`

`unexpected error: ,unknown error,Cmd,[object Object]`

Here is the script I ran:

```
const WhatsAppWeb = require('baileys') 

const client = new WhatsAppWeb() 
    client.connectSlim() // does not wait for chats & contacts
    
    .then (user => {
        console.log("the error is not here")
        console.log ("oh hello " + user.name + " (" + user.id + ")")
        
        client.receiveChatsAndContacts () // wait for chats & contacts in the background
        .then (([chats, contacts, unread]) => {
            console.log ("you have " + unread.length + " unread messages")
            console.log ("you have " + chats.length + " chats")
        })
    })
    .catch (err => console.log("unexpected error: " + err))

```

**what is the solution of this issue please?**

**Comment by mSharif10** [comment]
I have **traced** that the `WhatsAppWeb.Session.js` in `beginAuthentication` function, the **json.status** is returning **`undefined`**

**Comment by cacalderonc** [comment]
any solution?

**Comment by cacalderonc** [comment]
up

**Comment by cacalderonc** [comment]
up

**Comment by cacalderonc** [comment]
up

**Comment by cacalderonc** [comment]
any solution?

**Comment by EricAlvarez292** [comment]
any solution on this?

**Comment by PurpShell** [comment]
> **When I run the script below I am getting the following:**
> 
> `[Baileys] connected to WhatsApp Web`
> 
> `unexpected error: ,unknown error,Cmd,[object Object]`
> 
> Here is the script I ran:
> 
> ```
> const WhatsAppWeb = require('baileys') 
> 
> const client = new WhatsAppWeb() 
>     client.connectSlim() // does not wait for chats & contacts
>     
>     .then (user => {
>         console.log("the error is not here")
>         console.log ("oh hello " + user.name + " (" + user.id + ")")
>         
>         client.receiveChatsAndContacts () // wait for chats & contacts in the background
>         .then (([chats, contacts, unread]) => {
>             console.log ("you have " + unread.length + " unread messages")
>             console.log ("you have " + chats.length + " chats")
>         })
>     })
>     .catch (err => console.log("unexpected error: " + err))
> ```
> 
> **what is the solution of this issue please?**

`baileys` is no longer maintained, please use `@adiwajshing/baileys` instead.

**Comment by mSharif10** [comment]
@PurpShell yeah I got it and now I am using @adiwajshing/baileys this issue gone. but what about this https://github.com/adiwajshing/Baileys/issues/585? what you can say about it?
thanks
