### ISSUE TITLE
[BUG] MaxListenersExceedWarning on connection-phone-change

### ISSUE THREAD

**Issue by luiscuriel** [adiwajshing/Baileys#581]
**Describe the bug**
When connecting with a phone account with hundreds of whatsapp groups and contacts I get this warning:
MaxListenersExceedWarning. 31 connection-phone-change listeners added to [WAConnection]

Then when trying to send messages I get:
UnhandledPromiseRejectionWarning: BaileysError: Not expecting a response

And the message is not delivered.

**To Reproduce**
1. Created a new connection
2. Received groups and chats
3. Send a message to one group

**Expected behavior**
Message sent and everything ok

**Environment (please complete the following information):**
 - Running on local machine, tried windows and mac
 - Empty Message Options
 - No proxy

**Additional context**

**Comment by bhavya32** [comment]
@luiscuriel Try this for MaxListenersExceedWarning - 
```
conn.setMaxListeners(0);
``` 
Share your code for the other error.

**Comment by luiscuriel** [comment]
Thanks, no warning when using that solution. The other error does not happen since I put that line :S
