### ISSUE TITLE
Sticker cmd

### ISSUE THREAD

**Issue by Mve-Dec** [adiwajshing/Baileys#582]
Bang izin nanya bang cara bikin comand pake stiker gmn ya

**Comment by ibnusyawall** [comment]
mohon untuk menggunakan bahasa Inggris dalam bertanya dalam proyek terbuka, jelaskan secara rinci masalah kamu, bukan hanya sekedar bertanya tanpa konteks yang jelas, biasakan buka dokumentasi terlebih dahulu, ikutin bagaimana submit issues dengan benar, tidak seperti ini. tolong tutup issues ini jika berkenan.


please use English when asking questions in open projects, explain in detail your problem, not just asking without a clear context, make it a habit to open the documentation first, follow how to submit issues correctly, not like this. please close this issue if you like.

**Comment by Nafiz0110** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

hadeh

**Comment by rayyreall** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

Gg lu bro tingkatkan prestasi mu

**Comment by Zobin33** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

Gini Gan Baileys Cuma Nyediain Wa Web Api, Bukan Nyediain Script Bot, Kalo Lu bikin Issue gajelas sama aja kek lu bilang 1+1=3 alias bego, kalo mau nanya beginian ke yang bikincommand sticker

Baileys only provide wa web api, not a script bot, if you make some issue but nothing to do you are idiot.

**Comment by Zobin33** [comment]
Please close the issue:)

> Bang izin nanya bang cara bikin comand pake stiker gmn ya

Tolong tutup issue nya anjing

Please close the issue

**Comment by FadliDarmawan** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya 

Tutup issues nya jika berkenan

**Comment by VEXG** [comment]
Clown moment 🤡

**Comment by VEXG** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya 

Please use english, baileys just a web api dont ask for a feature like sticker cmd.. its out of topic

**Comment by PurpShell** [comment]
Issues are not meant for questions, I am not going to answer people with this attude, please join the discord for questions, this place is intended for bug reports (with the library itself), and feature requests to add. Issues are not for questions please understand where I'm coming from.

- Invite: https://discord.gg/7FYURJyqng

**Comment by PurpShell** [comment]
ALSO PLEASE TALK ENGLISH!

**Comment by mann-x** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

Close issue nya ajg

**Comment by NurFy** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

Menggokil

**Comment by nugraizy** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

here's the logic:
first, store the filesha256 to database with the cmd value whatever you want.
second, if the sticker is found with exact same filesha256 then return whatever you want and whatever you want to do with them.

**Comment by PurpShell** [comment]
@adiwajshing close please :|

**Comment by pukimaq** [comment]
> Bang izin nanya bang cara bikin comand pake stiker gmn ya

Aowkwowkwkk
