### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cyssxt** [adiwajshing/Baileys#587]
**Describe the bug**
After a while, It will throw an exception and restart。
[Error: ENOENT: no such file or directory, open '/tmp/audioMessage3EB042855A52'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/audioMessage3EB042855A52'
}
**To Reproduce**
Steps to reproduce the behavior: I can’ t reproduce!

**Expected behavior**
How to solute it or catch the exception

**Comment by bhavya32** [comment]
@cyssxt New to coding?

1. Your issue does not has your code or info what you are trying to do?
2. Error is written crystal clear that the file does not exist.
3. If it can't be reproduced, how are we supposed to solve it?

**Comment by cyssxt** [comment]
> @cyssxt Please note these points -
> 
> 1. Your issue does not has your code or info what you are trying to do?
> 2. Error is written crystal clear that the file does not exist.
> 3. If it can't be reproduced, how are we supposed to solve it?
Ok.And can you tell me where will this logic be handled，I want know the reference code in which file！Thanks。

**Comment by maleeqB** [comment]
> > @cyssxt Please note these points -
> > 
> > 1. Your issue does not has your code or info what you are trying to do?
> > 2. Error is written crystal clear that the file does not exist.
> > 3. If it can't be reproduced, how are we supposed to solve it?
> >    Ok.And can you tell me where will this logic be handled，I want know the reference code in which file！Thanks。

Any response? ```sock.sendMessage(chat.key.remoteJid, image:{url})```
where file doesn't exist in the url throws the error
