### ISSUE TITLE
[BUG] groupSettingChange Unexpected status in 'action': Unauthorized(401)

### ISSUE THREAD

**Issue by Notsfsssf** [adiwajshing/Baileys#588]
**Describe the bug**
`groupSettingChange` got `Unexpected status in 'action': Unauthorized(401)`
I'm sure I have right to change the settings on the group    
Do I need to perform other additional operations?
**To Reproduce**
```javascript
            const group = await conn.groupCreate(groupName + index, memberGroup)
            if (group.gid) {
                console.log("created group with id: " + group.gid) //work
                await conn.groupUpdateDescription(group.gid, descr) //work
                await conn.groupMakeAdmin(group.gid, memberGroup) //work
                await conn.updateProfilePicture(group.gid, img) //work
                await conn.groupSettingChange(a, GroupSettingChange.settingChange, true) //401
            }
```

**Expected behavior**
`groupSettingChange` sucess

**Environment (please complete the following information):**
 - Is this on a server? Nope
 - What do your `connectOptions` look like? default
 - Do you have multiple clients on the same IP? nope
 - Are you using a proxy? yes

**Comment by lyfe00011** [comment]
admin ?

**Comment by Notsfsssf** [comment]
> admin ?

Of course, the group was created by me

**Comment by Notsfsssf** [comment]
I found the problem, I need to set myself as an administrator after creation(`    await conn.groupMakeAdmin(myJid, ["8617680348161@c.us"])`), even if it has been shown that I am an administrator in whatsapp
