### ISSUE TITLE
error when trying to send buttons [BUG]

### ISSUE THREAD

**Issue by creuza** [adiwajshing/Baileys#597]
```
const id = message.key.remoteJid // the WhatsApp ID 
const buttons = [
    {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
    {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1}
]
const buttonMessage = {
    contentText: "Hi it's button message",
    footerText: 'Hello World',
    buttons: buttons,
    headerType: 1
}
          
const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
```

          
          
**When trying to send buttons with this code following the readme, I get the following error:**

_(node:11040) UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'action': Bad Request(400)_

links:
[non-media-messages](https://github.com/adiwajshing/Baileys#non-media-messages)

**Comment by PurpShell** [comment]
bro you are not allowed yo send the message, are you on WA Business?

**Comment by creuza** [comment]
yes


> mano você não tem permissão para enviar a mensagem, você está no WA Business?

**Comment by pipaliyachirag** [comment]
getting the same error any help?

**Comment by usoajwj** [comment]
> ```
> const id = message.key.remoteJid // the WhatsApp ID 
> const buttons = [
>     {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
>     {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1}
> ]
> const buttonMessage = {
>     contentText: "Hi it's button message",
>     footerText: 'Hello World',
>     buttons: buttons,
>     headerType: 1
> }
>           
> const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
> ```
> 
> **When trying to send buttons with this code following the readme, I get the following error:**
> 
> _(node:11040) UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'action': Bad Request(400)_
> 
> links:
> [non-media-messages](https://github.com/adiwajshing/Baileys#non-media-messages)

you cannot send button message if you are on whatsapp business

**Comment by creuza** [comment]
I managed to solve it, just install it with this command:

`npm install github:adiwajshing/baileys`

I'm using WhatApp Bussiness on Android, and I can send the buttons, I just can't send lists.

![button](https://user-images.githubusercontent.com/61638869/126074541-754d1e4c-7890-481b-8d2a-d8777b5ef180.PNG)
