### ISSUE TITLE
Prensece

### ISSUE THREAD

**Issue by ozoktay** [adiwajshing/Baileys#6]
The number is stored in my contact list but this feature does not work when there is no converstaion. Is there a solution for this?

**Comment by ozoktay** [comment]
I am trying to start a conversation without sending any messages. It works this way for this session.

**Comment by adiwajshing** [comment]
It works just fine. Do ensure that the id you're trying to send it to is in the format: ```91999999999@s.whatsapp.net```. 

If it is, then how exactly are you sending this message? Can you send some code?

**Comment by ozoktay** [comment]
I also tried this option.

`client.handlers.onConnected = () => {
	client.requestPresenceUpdate('905524801267@s.whatsapp.net')
}

client.handlers.presenceUpdated = (id, presence) => {
	console.log(id + ' ' + presence)
}`


OR

`client.handlers.onConnected = () => {
	client.query(["action","presence","subscribe","905527222606@c.us"]).then(function(result) {
           console.log(result) // return status 200 but it should be available, unavilable or composin
         })
}

client.handlers.presenceUpdated = (id, presence) => {
	console.log(id + ' ' + presence)
}`

**Comment by adiwajshing** [comment]
The latter option will work. You will get a status 200 in the promise, but the presenceUpdated callback will be called with the presence update.

**Comment by ozoktay** [comment]
I know but if when i send a request with a number i contacted before return presense status.

Anyway if a number has not been contacted before, this method does not work. If you have two numbers, you can test it. These two numbers should not have been in contact with each other before.

**Comment by adiwajshing** [comment]
You're right, WhatsApp does not allow for the functionality if the person does not have you in their contacts. I am not interesting in developing a workaround for this right now. I'm also closing this issue as it is beyond the scope of this API for the foreseeable future. However, please do contribute a workaround, if you find one.
