### ISSUE TITLE
[BUG] No URL protocol specified when downloadMediaMessage

### ISSUE THREAD

**Issue by workgroupengineering** [adiwajshing/Baileys#601]
**Describe the bug**
throw No URL protocol specified when downloadMediaMessage

**To Reproduce**
1. run example
2. receive immage
3. the exception will throw.

**Expected behavior**
Download media.

**Environment (please complete the following information):**
 - Is this on a server? Windows
 - What do your `connectOptions` look like? standard
 - Do you have multiple clients on the same IP? no
 - Are you using a proxy? no

**Additional context**
none

**Comment by rawars** [comment]
> **Describe the bug**
> throw No URL protocol specified when downloadMediaMessage
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. run example
> 2. receive immage
> 3. the exception will throw.
> 
> **Expected behavior**
> Download media.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server? Windows
> * What do your `connectOptions` look like? standard
> * Do you have multiple clients on the same IP? no
> * Are you using a proxy? no
> 
> **Additional context**
> none

It also happened to me, to solve I realized that Baileys executes the chatupdate function several times already in the second execution you can see the buffer to be able to download, it only happens when an image is sent through the cell phone that I scan the code when it has the fromMe property****

**Comment by rasyidrafi** [comment]
`(node:6492) UnhandledPromiseRejectionWarning: TypeError: No URL protocol specified
    at Object.exports.default (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\got@11.8.2\node_modules\got\dist\source\core\utils\options-to-url.js:31:19)
    at normalizeArguments (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\got@11.8.2\node_modules\got\dist\source\core\index.js:480:51)
    at got (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\got@11.8.2\node_modules\got\dist\source\create.js:112:39)
    at Function.got.stream (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\got@11.8.2\node_modules\got\dist\source\create.js:221:37)
    at Object.getGotStream (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\@adiwajshing+baileys@3.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:363:35)
    at Object.decryptMediaMessageBuffer (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\@adiwajshing+baileys@3.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:465:35)
    at downloadMediaMessage (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\@adiwajshing+baileys@3.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:321:42)
    at WAConnection.downloadMediaMessage (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\@adiwajshing+baileys@3.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\6.MessagesSend.js:332:32)
    at C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\@adiwajshing+baileys@3.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\Mutex.js:20:53  
    at WAConnection.descriptor.value (C:\Users\Rasyid Rafi\Documents\Development\nodeApp\wa_baileys\node_modules\.pnpm\@adiwajshing+baileys@3.5.1\node_modules\@adiwajshing\baileys\lib\WAConnection\Mutex.js:22:15)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with 
a non-zero exit code.`

this is my sample code
`conn.on('chat-update', async cht => {
     if (!cht.hasNewMessage) return;
     let theKeys = Object.keys(cht.messages.dict)[0];
     const mediaMsg = cht.messages.dict[theKeys];
     conn.downloadMediaMessage(mediaMsg, { type: "buffer" })
}`

Same error happening on me, pleae fix it :(

**Comment by mtoloon** [comment]
The same problem on Ubuntu 20.04 and node 14.17.2. 
There was no problem about 3 months before and all media were downloaded without any problem.

**Comment by rasyidrafi** [comment]
After searching for the answer, and do so many test, im just realized that,
`conn.downloadMediaMessage()` doesnt work when we try to download our chat to other contacts,
do u know what i mean?
im trying to download my sended image and it doesnt work. **FAIL**
But if i try to download image from other contacts that sended to me it works fine **SUCCESS**

Sorry bad in english.

**Comment by bluesky322** [comment]
I have this error too

**Comment by workgroupengineering** [comment]
The issue persist,  it only happens when an image is sent through the cell phone that I scan the code when it has the fromMe property****

**Comment by spacysky322** [comment]
has this been fixed?

**Comment by spacysky322** [comment]
Hi, does this example still work? https://github.com/adiwajshing/Baileys#downloading-media-messages

I tried and no result

**Comment by ngekoding** [comment]
Okay, finally I got the solution after exploring the documentation.
The idea is, we fetch the message from WA first, then download the media from that fetched message.

Here is the example:

```js
// Get the newest message from WA, so get all the info
const messages = await conn.fetchMessagesFromWA(m.key.remoteJid, 1, { id: m.key.id });
const mTmp = messages[0];

const savedFile = await conn.downloadAndSaveMediaMessage(mTmp, './media/media_in_' + m.key.id);
console.log(savedFile);
```

Hope this can help anyone who have the same issue.

**Comment by mtoloon** [comment]
> Okay, finally I got the solution after exploring the documentation.
> The idea is, we fetch the message from WA first, then download the media from that fetched message.
> 
> Here is the example:
> 
> ```js
> // Get the newest message from WA, so get all the info
> const messages = await conn.fetchMessagesFromWA(m.key.remoteJid, 1, { id: m.key.id });
> const mTmp = messages[0];
> 
> const savedFile = await conn.downloadAndSaveMediaMessage(mTmp, './media/media_in_' + m.key.id);
> console.log(savedFile);
> ```
> 
> Hope this can help anyone who have the same issue.

The `fetchMessagesFromWA` returns another message in this way!  
Here `m.key.id` is `FDB56A4B807AB5ED86D9D1AB28C2B85A`, but the returned messages[0].id is: `9B46B8F403A066C89DB201DBD86DA5E1`

**Comment by Krakinz** [comment]
This Error Needs A Permanent Fix Devs.

**Comment by paulohsilvestre** [comment]
someone managed to solve this problem, if not, someone managed to get the exact message by its ID, because the tests I did always bring a before or after and never the desired message, then I already got the previous one and tried to get the next one, but if it happens that the whats user types too fast other messages come in first and he gets lost, this only happens when the message is sent by the phone that the qrcode was read, and fromMe = true comes, sorry for my english, Google Translator
