### ISSUE TITLE
How send arrayContacts?

### ISSUE THREAD

**Issue by mann-x** [adiwajshing/Baileys#603]
How send a contactArray?

**Comment by PurpShell** [comment]
Issues are not meant for questions, I am not going to answer people with this attude, please join the discord for questions, this place is intended for bug reports (with the library itself), and feature requests to add. Issues are not for questions please understand where I'm coming from.

- Invite: https://discord.gg/7FYURJyqng

**Comment by mann-x** [comment]
> Issues are not meant for questions, I am not going to answer people with this attude, please join the discord for questions, this place is intended for bug reports (with the library itself), and feature requests to add. Issues are not for questions please understand where I'm coming from.
> 
> * Invite: https://discord.gg/7FYURJyqng

Oke
