### ISSUE TITLE
User Status Online/Offline

### ISSUE THREAD

**Issue by krmzgn** [adiwajshing/Baileys#607]
Hi. Online / Offline status is not displayed without starting chat. Is there no solution to this?

**Comment by ibnusyawall** [comment]
Can you describe in detail your problem? along with screenshots if needed

**Comment by krmzgn** [comment]
As an example, our number is not registered in the contact list of the person we want to look at the online / offline status.
Don't we see that person's online / offline status?

**Comment by Manjit2003** [comment]
There's no way to check the status of a user without starting a chat. These limitations are imposed by WhatsApp so anything in Baileys won't work...
