### ISSUE TITLE
When Connecting with android whats app it's crash and IOS it running with error

### ISSUE THREAD

**Issue by jayanisanjay** [adiwajshing/Baileys#61]
Once i Scan QR code below are detail once i scan QR code

1) Messages
       "before all" hook for "should send a text message":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Presence
       "before all" hook for "should update presence":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Misc
       "before all" hook for "should tell if someone has an account on WhatsApp":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) Groups
       "before all" hook for "should create a group":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) Events
       "before all" hook for "should deliver a message":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  6) Test Connect
       should connect:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\Projects\NodeJS\WA2\src\WAConnection\Tests.ts)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  7) Test Connect
       should reconnect:
     Error: the string "Timed out" was thrown, throw an Error :)

npm ERR! Test failed.  See above for more details.

**Comment by adiwajshing** [comment]
It seems like you logged out from your phone, or you called `client.logout()`. Is that the case?

**Comment by jayanisanjay** [comment]
Below are step that we are testing 
we use below code

npm test

After using this command we have QR Code in command line
We Scan from my android phone web WhatsApp it's scan successfully and android app of what's app crash

[Baileys][7/10/2020, 1:41:10 PM] validated connection successfully
    √ should connect (7060ms)
[Baileys][7/10/2020, 1:41:11 PM] connected to WhatsApp Web, authenticating...
[Baileys][7/10/2020, 1:41:17 PM] validated connection successfully
[Baileys][7/10/2020, 1:41:17 PM] waiting for chats & contacts
    6) should reconnect


  4 passing (34s)
  6 failing


  1) Messages
       "before all" hook for "should send a text message":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Presence
       "before all" hook for "should update presence":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Misc
       "before all" hook for "should tell if someone has an account on WhatsApp":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) Groups
       "before all" hook for "should create a group":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) Events
       "before all" hook for "should deliver a message":
     Error: the array [
  401
  "unpaired from phone"
  {
    "status": 401
  }
] was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  6) Test Connect
       should reconnect:
     AssertionError [ERR_ASSERTION]: 0 == true
      at D:\Projects\NodeJS\WA2\src\WAConnection\Tests.ts:42:20
      at step (src\WAConnection\Tests.ts:52:23)
      at Object.next (src\WAConnection\Tests.ts:33:53)
      at fulfilled (src\WAConnection\Tests.ts:24:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by adiwajshing** [comment]
Delete the `auth_info.json` file and then, in the Baileys directory can you try executing the following command: 

`mocha --timeout 60000 -r ts-node/register src/WAClient/Tests.ts`

**Comment by adiwajshing** [comment]
Assuming you've managed to test successfully, closing.

**Comment by ABEBAAPHUMEIN** [comment]
same issue with me...

how to fix??

**Comment by ABEBAAPHUMEIN** [comment]
> Delete the `auth_info.json` file and then, in the Baileys directory can you try executing the following command:
> 
> `mocha --timeout 60000 -r ts-node/register src/WAClient/Tests.ts`

i can run but failed to create group,same issue happen again
