### ISSUE TITLE
PROTOBUF ERROR

### ISSUE THREAD

**Issue by Nafiz01** [adiwajshing/Baileys#611]
How to fix this error protobuff?

npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > protobufjs@6.11.2 postinstall /home/nafiz919/.npm/_cacache/tmp/git-clone-e745549c/node_modules/protobufjs
npm ERR! prepareGitDep > node scripts/postinstall
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 
npm ERR! prepareGitDep > @adiwajshing/baileys@3.5.1 prepare /home/nafiz919/.npm/_cacache/tmp/git-clone-e745549c
npm ERR! prepareGitDep > tsc
npm ERR! prepareGitDep 
npm ERR! prepareGitDep node_modules/token-types/lib/index.d.ts(123,44): error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).
npm ERR! prepareGitDep node_modules/token-types/lib/index.d.ts(131,44): error TS2314: Generic type 'IGetToken<T>' requires 1 type argument(s).
npm ERR! prepareGitDep 
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! @adiwajshing/baileys@3.5.1 prepare: `tsc`
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR! 
npm ERR! prepareGitDep npm ERR! Failed at the @adiwajshing/baileys@3.5.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/nafiz919/.npm/_logs/2021-07-24T09_26_55_042Z-debug.log

**Comment by danielteodorodt** [comment]
same here

**Comment by Nafiz0110** [comment]
> same here

But I've found a way to make it work and not error

**Comment by danielteodorodt** [comment]
> > same here
> 
> But I've found a way to make it work and not error

Removed node_modules, and had to install npm version and not github.

**Comment by ariffb25** [comment]
I also experienced the same thing, I just updated the nodejs version and it worked

**Comment by RynKings** [comment]
try to use 

`yarn add https://github.com/adiwajshing/Baileys.git`

**Comment by Farhan687636** [comment]
@RynKings thanks

**Comment by Adiixyz** [comment]
> try to use
> 
> `yarn add https://github.com/adiwajshing/Baileys.git`

need to install yarn?

**Comment by RynKings** [comment]
> > try to use
> > `yarn add https://github.com/adiwajshing/Baileys.git`
> 
> need to install yarn?

yea

**Comment by Adiixyz** [comment]
> > > try to use
> > > `yarn add https://github.com/adiwajshing/Baileys.git`
> > 
> > 
> > need to install yarn?
> 
> yea

ok thanks... it work
