### ISSUE TITLE
[BUG] Protobufjs Error

### ISSUE THREAD

**Issue by Rizky878** [adiwajshing/Baileys#612]
how to fix it??

npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > protobufjs@6.11.2 postinstall /home/nafiz919/.npm/_cacache/tmp/git-clone-e745549c/node_modules/protobufjs
npm ERR! prepareGitDep > node scripts/postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > @adiwajshing/baileys@3.5.1 prepare /home/nafiz919/.npm/_cacache/tmp/git-clone-e745549c
npm ERR! prepareGitDep > tsc
npm ERR! prepareGitDep
npm ERR! prepareGitDep node_modules/token-types/lib/index.d.ts(123,44): error TS2314: Generic type 'IGetToken' requires 1 type argument(s).
npm ERR! prepareGitDep node_modules/token-types/lib/index.d.ts(131,44): error TS2314: Generic type 'IGetToken' requires 1 type argument(s).
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the --dev option is deprecated. Use --only=dev instead.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 2
npm ERR! prepareGitDep npm ERR! @adiwajshing/baileys@3.5.1 prepare: tsc
npm ERR! prepareGitDep npm ERR! Exit status 2
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the @adiwajshing/baileys@3.5.1 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR! /home/rzky/.npm/_logs/2021-07-24T09_26_55_042Z-debug.log

**Comment by FaizBastomi** [comment]
clone of #611
