### ISSUE TITLE
[BUG] Whatsapp app crash on sendMessage

### ISSUE THREAD

**Issue by bramaudi** [adiwajshing/Baileys#613]
**Describe the bug**
Whatsapp keep stopped when using sendMessage API and in terminal showing `checking phone connection...`.

**To Reproduce**
I have created a [repo](https://github.com/bramaudi/baileys-reproduce)

**Expected behavior**
Message sent and app doesn't crash.

**Environment (please complete the following information):**
 - Is this on a server? **No**
 - What do your `connectOptions` look like? **Default**
 - Do you have multiple clients on the same IP? **No**
 - Are you using a proxy? **No**

**Additional context**
Before it was okay but this happened after several days i'm leaving the project.

**Comment by Manjit2003** [comment]
Thats because you are using `1234@s.whatsapp.net` as phone number. Which is invalid for sending messages. To avoid such errors in future, check if the number exists by `conn.isOnWhatsApp(id)`

**Comment by bramaudi** [comment]
Thanks for the reply, it's work again without touching my code so i guess the problem goes to WhatsApp side.

I know exactly how the WhatsApp ID format, by the way before reporting this issue i have try sending messages to valid number but getting this error.

FYI, I can confirm that you can send message even on wrong/unregistered phone number and you should try too if you want, but still the invalid number make WhatsApp app crash as you have say.
