### ISSUE TITLE
[BUG] While send buttons message

### ISSUE THREAD

**Issue by WhatTheSemvak** [adiwajshing/Baileys#614]
Error While I Send Buttons Message. 
Iam already follow code in readme.md but its not work, i have to update new version of Baileys
When me running the command Error Log Be Like This :

> > `(node:32507)` UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'action': Bad Request(400)
> 
>     at WAConnection.query (/storage/emulated/0/Download/SelfRev/SelfRev/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:236:27)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async WAConnection.relayWAMessage (/storage/emulated/0/Download/SelfRev/SelfRev/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:279:13)
>     at async WAConnection.sendMessage (/storage/emulated/0/Download/SelfRev/SelfRev/node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js:25:9)
> (Use `node --trace-warnings ...` to show where the warning was created)

Please Help me how to fix this thx

**Comment by RynKings** [comment]
Are you using whatsapp business ?

**Comment by RynKings** [comment]
Can I see your code ?

**Comment by Nafiz0110** [comment]
wkwk gua bisa aja

**Comment by Gidraf** [comment]
Hey, install directly from the Github repository.

**Comment by PurpShell** [comment]
This is why we should put a disclaimer that things you see on the repo are not 1:1 on NPM, or to be fair just release it as a feature update to NPM

**Comment by rthelolchex** [comment]
sama bang w begitu juga, errornya dimana dah
