### ISSUE TITLE
[BUG] Media upload failed on all hosts + some other errors 

### ISSUE THREAD

**Issue by TentacleSama4254** [adiwajshing/Baileys#615]
I updated to the last github version and my app is also in the latest version. ![IMG_20210725_143613.jpg](https://user-images.githubusercontent.com/74726248/126913502-d58dfd45-e276-4e5c-a5c3-1d0a67b433aa.jpg)![IMG_20210725_104432.jpg](https://user-images.githubusercontent.com/74726248/126913504-7adb809d-1a6e-4af0-98ed-5ed2023ce4d6.jpg)![IMG_20210725_103939.jpg](https://user-images.githubusercontent.com/74726248/126913506-61a8b54c-bd52-4b17-b5a0-df0920a93175.jpg)

I don't know what is causing this for me

**Comment by ariffb25** [comment]
I also experienced the same thing about it

### Media upload failed on all hosts

check this issue https://github.com/adiwajshing/Baileys/issues/513

### Marker was not found

add thumbnail on options, I don't know what it should look like but it's worked for me
as an example
```js
conn.sendMessage(jid, content, mimetype, { thumbnail: Buffer.alloc(0) })
```

**Comment by TentacleSama4254** [comment]
What's buffer.alloc(0)
