### ISSUE TITLE
[BUG]how to remove buttonMessage and listMessages ?

### ISSUE THREAD

**Issue by syifarahmat** [adiwajshing/Baileys#616]
how to remove buttonMessage and listMessages ?
Use : await conn.clearMessage (jid, {id: response.messageID, remoteJid: jid, fromMe: true})
still don't want to delete

I want to delete just for me

**Comment by Zobin33** [comment]
> how to remove buttonMessage and listMessages ?
> Use : await conn.clearMessage (jid, {id: response.messageID, remoteJid: jid, fromMe: true})
> still don't want to delete
> 
> I want to delete just for me

If You Want Delete For All Use client.deleteMessage(jid,message.key)

Clear only delete message for us not all so use deleteMessage instead
