### ISSUE TITLE
ButtonMessage

### ISSUE THREAD

**Issue by AlvioAdjiJanuar** [adiwajshing/Baileys#619]
I tried new things using the baileys module, I've read readme.md and I tried the button message, but why when I test it on my PC it appears like this "Message : BaileysError: Unexpected status in 'action': Bad Request(400)" i already fetch the repo on github , not on npm

**Comment by Nafiz01** [comment]
Aahhaa ternyata buttonMessage

**Comment by AlvioAdjiJanuar** [comment]
Kek menarik aja diliatnya

**Comment by Nafiz01** [comment]
Typescript lu eror

**Comment by AlvioAdjiJanuar** [comment]
iya kah ?

**Comment by LuanRT** [comment]
You shouldn't be asking questions here, do that in the Discord server instead. And to y'all in the replies: **SPEAK ENGLISH**.
