### ISSUE TITLE
Create transmission list 

### ISSUE THREAD

**Issue by tiagoandrepro** [adiwajshing/Baileys#62]
Is it possible to create a transmission list from the library?

**Comment by adiwajshing** [comment]
A broadcast list is not possible right now. But it can be added soon, I'll try and add it in by tomorrow.

**Comment by adiwajshing** [comment]
So you cannot create a broadcast list in WhatsApp Web currently and so, the library cannot support it :/

However, the library supports sending messages to broadcast lists & receiving messages from them as well -- just like a regular message. You can also query the metadata of a broadcast list using `client.getBroadcastInfo('xxxxxx@broadcast')`

Hope this helps

**Comment by tiagoandrepro** [comment]
I understand, thank you very much for your effort.
