### ISSUE TITLE
can't scan for whatsapp beta version 

### ISSUE THREAD

**Issue by Rianfirnanda** [adiwajshing/Baileys#625]
In WhatsApp beta version, you can still use WhatsApp on other devices even if you are offline .So, the primary device for the bot account does not need to be connected to the internet all the time. It's very useful for bots

**Comment by LuanRT** [comment]
Duplicate of https://github.com/adiwajshing/Baileys/issues/605

There's no need to open a new issue regarding that, everyone is already aware of it and there are already some people reverse engineering the new protocol.

**Comment by Rianfirnanda** [comment]
> Duplikat #605
> 
> Tidak perlu membuka isu baru tentang itu, semua orang sudah mengetahuinya dan sudah ada beberapa orang yang merekayasa balik protokol baru.

Thank you for the information
