### ISSUE TITLE
File name null

### ISSUE THREAD

**Issue by tiagoandrepro** [adiwajshing/Baileys#63]
When sending a document, the name is not being sent.
How to pass the name?

![Image](https://i.ibb.co/TBHdWhd/Captura-de-Tela-2020-07-12-a-s-03-52-55.png)

**Comment by adiwajshing** [comment]
The option to add the filename has been added. It's in the latest commit, which you can install using: `npm i github:adiwajshing/baileys`

When sending a media message, just add the filename to the options:
``` ts
client.sendMessage ('1234@s.whatsapp.net', fileBuffer, MessageType.pdf, {filename: 'my-doc.pdf'})
```

**Comment by tiagoandrepro** [comment]
Thank you
