### ISSUE TITLE
i found a bug marker was not found on jpeg-js or png-js, is there any solution? and how to solve it?[BUG]

### ISSUE THREAD

**Issue by Ivan-MLN** [adiwajshing/Baileys#638]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by akm-akm** [comment]
![image](https://user-images.githubusercontent.com/67242659/129041461-4f18d980-8465-4eda-bfe8-9dcf42ef45e2.png)
Got similar error when trying to send images.

  client.sendMessage(from,
                fs.readFileSync(path.join(__dirname, "../readme/images/logo.jpeg")
                ), image, {
                quoted: xxx,
                detectLinks: false,
                caption: msg,
                mimetype: Mimetype.jpeg
            })

**Comment by phaticusthiccy** [comment]
#488
