### ISSUE TITLE
[BUG] Error when getting group metadata with 'fetchGroupMetadataFromWA'

### ISSUE THREAD

**Issue by ngekoding** [adiwajshing/Baileys#641]
**Describe the bug**
I try to use `fetchGroupMetadataFromWA` and the group metadata returned but also got the error below: 
`BaileysError: Unexpected status in 'query': Bad Request(400)`

**To Reproduce**
1. Created a new connection
2. Just try to get group metadata with `fetchGroupMetadataFromWA`

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - Is this on a server? **No, still on local development. macOS Big Sur**
 - What do your `connectOptions` look like? **Just use the default**
 - Do you have multiple clients on the same IP? **No**
 - Are you using a proxy? **No**

**Additional context**
Here is my code looks like, just a simple copied from the example.

```js
const { 
  WAConnection, 
  MessageType, 
  Presence 
} = require('@adiwajshing/baileys');
const fs = require('fs');

(async() => {
  const whatsapp = new WAConnection();
  
  // Try to use saved session
  try {
    whatsapp.loadAuthInfo ('./session.json')
  } catch (err) {
    console.log('No session saved before!');
  }

  whatsapp.on('open', () => {
    const authInfo = whatsapp.base64EncodedAuthInfo();
    fs.writeFileSync('./session.json', JSON.stringify(authInfo, null, '\t'));
  });

  whatsapp.on('chat-update', async chat => {
    // Only do something when a new message is received
    if (!chat.hasNewMessage) return;

    const m = chat.messages.all()[0];
    const messageContent = m.message;
    
    // If it is not a regular text or media message
    if (!messageContent) return;

    // Relayed my own message
    if (m.key.fromMe) return;

    let sender = m.key.remoteJid;

    // This is a group message
    if (m.key.participant) {
      sender += ' (' + m.key.participant + ')';
      try {
        const groupInfo = await whatsapp.fetchGroupMetadataFromWA(m.key.remoteJid);
        console.log('Message from group:');
        console.log(groupInfo); 
      } catch (err) {
        console.log('Error getting group info:', err);
      }
    }

    const messageType = Object.keys(messageContent)[0];

    if (messageType === MessageType.text) {
        const text = m.message.conversation
        console.log(sender + ' sent: ' + text)
    } else if (messageType === MessageType.extendedText) {
        const text = m.message.extendedTextMessage.text
        console.log(sender + ' sent: ' + text + ' and quoted message: ' + JSON.stringify(m.message))
    } else {
      console.log(`No action defined for message type: ${messageType}`);
    }
    
  });

  await whatsapp.connect();
})();
```

And here the error logs from Terminal.

<img width="868" alt="Error Log" src="https://user-images.githubusercontent.com/11625690/129155946-2d645006-cad0-4f76-95f4-18019ce8e4b0.png">

Thanks in advance

**Comment by Pegorino82** [comment]
not sure this is the answer, but it works for me `whatsapp.groupMetadata(m.key.remoteJid)`

**Comment by ngekoding** [comment]
> not sure this is the answer, but it works for me `whatsapp.groupMetadata(m.key.remoteJid)`

Yes, but I need to fetch the latest metadate as mentioned here https://github.com/adiwajshing/Baileys/issues/418#issuecomment-830615558

**Comment by ngekoding** [comment]
> looks like you forgot to provide a filter if the id is from WhatsApp Status.
> 
> > ![IMG_20210813_114406](https://user-images.githubusercontent.com/64179402/129305939-fad7c949-540b-41bb-b428-247a47427a17.png)

Thank you.
Okay get the point, but it is very confusing. From the example, I was add the validation for the group only as the example code mentioned (ref: https://github.com/adiwajshing/Baileys/blob/e3e521b3850979f3bf081082bc8a80a05694070c/Example/example.ts#L83).

```js
    // This is a group message
    if (m.key.participant) {
      sender += ' (' + m.key.participant + ')';
      try {
        const groupInfo = await whatsapp.fetchGroupMetadataFromWA(m.key.remoteJid);
        console.log('Message from group:');
        console.log(groupInfo); 
      } catch (err) {
        console.log('Error getting group info:', err);
      }
    }
```

I think I will follow this part of the readme, the group id ended with `@g.us`. (ref: https://github.com/adiwajshing/Baileys#notes)
