### ISSUE TITLE
[BUG] unexpected end of file - Send image/png

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#643]
**Describe the bug**
When trying to send an image message, some files have "unexpected end of file"

**To Reproduce**
Try to send te attached file whit this code:
`          const filepath = '/home/douglas/tmp/uploads/25d3853808dfdc659b34-Arrecadacoes.png'
          wa.conn.sendMessage(
            whatsapp,
            fs.readFileSync(filepath),
            whatsappMessageType,
            {
              mimetype: whatsappFileMimeType,
              filename: message,
              forceNewMediaOptions: true,
            }
          );
`
![25d3853808dfdc659b34-Arrecadacoes](https://user-images.githubusercontent.com/4416953/129350018-0efa953b-83b5-4c86-93e8-b8c06e86c160.png)

**Expected behavior**
The message whas delivered.

**Environment (please complete the following information):**
 - Is this on a server?
 No, my developer machine

 - What do your `connectOptions` look like? 
I Only change maxRetries to conn.connectOptions.maxRetries = 99999;

 - Do you have multiple clients on the same IP?
 No

 - Are you using a proxy?
No

**Additional context**
Many files work correctly, but many other throw the same error.

**Comment by PurpShell** [comment]
> **Describe the bug**
> When trying to send an image message, some files have "unexpected end of file"
> 
> **To Reproduce**
> Try to send te attached file whit this code:
> ` const filepath = '/home/douglas/tmp/uploads/25d3853808dfdc659b34-Arrecadacoes.png' wa.conn.sendMessage( whatsapp, fs.readFileSync(filepath), whatsappMessageType, { mimetype: whatsappFileMimeType, filename: message, forceNewMediaOptions: true, } );`
> ![25d3853808dfdc659b34-Arrecadacoes](https://user-images.githubusercontent.com/4416953/129350018-0efa953b-83b5-4c86-93e8-b8c06e86c160.png)
> 
> **Expected behavior**
> The message whas delivered.
> 
> **Environment (please complete the following information):**
> 
> * Is this on a server?
>   No, my developer machine
> * What do your `connectOptions` look like?
>   I Only change maxRetries to conn.connectOptions.maxRetries = 99999;
> * Do you have multiple clients on the same IP?
>   No
> * Are you using a proxy?
>   No
> 
> **Additional context**
> Many files work correctly, but many other throw the same error.

they have their header corrupt. basically the header says there is for example 2000 bytes, and there turns out to be less than that. Either files are getting cut of because of some copy problem or if you are uploading a upload problem
