### ISSUE TITLE
I have a problem with a termux bot

### ISSUE THREAD

**Issue by shanduy** [adiwajshing/Baileys#645]
How are you, greetings.
I have an error, for days my bot does not work and it does not send me the QR in termux, before it did but now I get this error that is in the image
![Screenshot_2021-08-13-23-17-07-958_com.termux.jpg](https://user-images.githubusercontent.com/79606488/129434070-8a2d854f-7e76-4eb7-a65c-d6439ebb2fae.jpg)

Does anyone know why this happens??
If you could help me I would appreciate it.

**Comment by barkerpedro** [comment]
Pasos para instalar el bot en termux

> pkg install git
> pkg install ffmpeg
> pkg install nodejs
> pkg install wget
> git clone https://github.com/shanduy/ShanBot
> cd ShanBot
> bash install.sh
> npm start
> Y escaneas el QR con tu Whatsapp

**Comment by shanduy** [comment]
> Pasos para instalar el bot en termux
> 
> > pkg install git
> > pkg install ffmpeg
> > pkg install nodejs
> > pkg install wget
> > git clone https://github.com/shanduy/ShanBot
> > cd ShanBot
> > bash install.sh
> > npm start
> > Y escaneas el QR con tu Whatsapp

Gracias bro.
Pero a hizo un problema de los paquetes de termux ahora lo acaban de soluciónar, gracias por tu ayuda.

**Comment by DikaArdnt** [comment]
pkg install nodejs
npm install @adiwajsing/baileys 
Or
pkg install git
npm install github:adiwajshing/baileys

**Comment by PurpShell** [comment]
you don't fking npm i 

> How are you, greetings.
> I have an error, for days my bot does not work and it does not send me the QR in termux, before it did but now I get this error that is in the image
> ![Screenshot_2021-08-13-23-17-07-958_com.termux.jpg](https://user-images.githubusercontent.com/79606488/129434070-8a2d854f-7e76-4eb7-a65c-d6439ebb2fae.jpg)
> 
> Does anyone know why this happens??
> If you could help me I would appreciate it.

**Comment by Rubiuswtf** [comment]
tengo el mismo problema ayuda
