### ISSUE TITLE
How to use groupInviteMessage

### ISSUE THREAD

**Issue by FazrilDev** [adiwajshing/Baileys#646]
@adiwajshing

**Comment by rayyreall** [comment]
Stress

**Comment by Zobin33** [comment]
Open Docs Of Baileys Bro

Bukan dokumentasi Baileys Mek

> @adiwajshing

**Comment by rayyreall** [comment]
you can read the documentation https://adiwajshing.github.io

> @adiwajshing

**Comment by dhyZx** [comment]
AWOAKWOAKWOWK BUTA KONTOL

**Comment by davandri** [comment]
Stress

**Comment by noizydev** [comment]
stress

**Comment by DikaArdnt** [comment]
Psarkas handal

**Comment by FaizBastomi** [comment]
- Code :

```js
const { MessageType } = require("@adiwajshing/baileys")
/* Using sendMessage */
sendMessage(jid, { groupJid: 'abc-xyz@g.us', groupName: 'something cool', inviteCode: string, inviteExpiration: number, caption: string, jpegThumbnail: Uint8array }, MessageType.groupInviteMessage)
```
> - jid = the number of the person to be invited.
> - groupJid = id of the group.
> - groupName = group subject.
> - inviteCode = invite codes.
>   - (gets from the groupAdd() response, if the target number activates group privacy. usually the response code of it is 403)
> - inviteExpiration = invitation expires. (Same as above)
> - jpegThumbnail = group icon. (optional)
> - caption = caption. (optional)
---
> sample response for people turning on group privacy.
> ![ex](https://user-images.githubusercontent.com/64179402/119530191-fc4f1d80-bdac-11eb-9a65-714769299a1e.png)

**I hope it's clear😄**

**Comment by hardianto-cpu** [comment]
> 

how in multi device

**Comment by hardianto-cpu** [comment]
```const respon = await sock.groupParticipantsUpdate(jid, [participants], "add")```
this respon a sender
