### ISSUE TITLE
[BUG] ERROR SyntaxError: Unexpected end of JSON input    at JSON.parse (<anonymous>)    at WAConnection.loadAuthInfo (/storage/emulated/0/.bot/frnbot/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:150:29)    at Object.<anonymous> (/storage/emulated/0/.bot/frnbot/main.js:42:35)    at Module._compile (internal/modules/cjs/loader.js:1063:30)    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)    at Module.load (internal/modules/cjs/loader.js:928:32)    at Function.Module._load (internal/modules/cjs/loader.js:769:14)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)    at internal/main/run_main_module.js:17:47Exited with code: 1

### ISSUE THREAD

**Issue by FranChouG** [adiwajshing/Baileys#648]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by ibnusyawall** [comment]
lol

**Comment by LuanRT** [comment]
WTF

**Comment by ngekoding** [comment]
@FranChouG Please describe you problem clearly, fill the data as the Bug Template given.

**Comment by vlamizzz02** [comment]
Lol

**Comment by mateusmirandaalmeida** [comment]
Authentication issues happen when your whatsapp version is updating to multi device beta version

**Comment by pasya1912** [comment]
> Authentication issues happen when your whatsapp version is updating to multi device beta version

that's mean it doesnt support it yet huh ?

**Comment by FaizBastomi** [comment]
> that's mean it doesnt support it yet huh ?
@pasya1912 not yet.

**Comment by rayyreall** [comment]
good job mate
