### ISSUE TITLE
ignore stories updates

### ISSUE THREAD

**Issue by tiagoandrepro** [adiwajshing/Baileys#65]
I need to monitor the messages sent by the cell phone and for that I am using the registerCallback () function.
It is possible to ignore the updates of stories or to classify if it is a call of stories or message.

**Comment by adiwajshing** [comment]
You can simply use the following function. If the first parameter is true, messages sent by you from your phone will also get relayed. 

``` ts
client.setOnUnreadMessage (true, message => console.log('got new message'))

```

**Comment by tiagoandrepro** [comment]
It worked!

When I send by the device I am receiving the complete log in my API, but when I do the sending with the sendMessage () function I only receive the status and the message id.

What is the best option to receive the complete log of the message sent?

**Comment by adiwajshing** [comment]
Ideally, you should do the following:
``` ts
const response = await client.sendMessage('1234@s.whatsapp.net', 'hi there', MessageType.text)
const messages = await client.loadConversation('1234@s.whatsapp.net', 1) // load the latest message

const sentMessage = message[0]
```

`sentMessage` will be the full message object retrieved from WhatsApp. Alternatively, if you want the exact sent message object, in the latest commit, you can also:

``` ts
const response = await client.sendMessage('1234@s.whatsapp.net', 'hi there', MessageType.text)
const message = response.message
```

**Comment by tiagoandrepro** [comment]
I'm still getting the story updates. What can I be doing wrong? messageStubType only returns zero for any type of message? Am I using it correctly?

```javascript
client.setOnUnreadMessage(true, message => {
    console.log(message.messageStubType))
    sendApi({ message: message})
})`

**Comment by adiwajshing** [comment]
I think you can check if its a story using the following:
``` ts
client.setOnUnreadMessage(true, message => {
    if (message.key.remoteJid === 'status@broadcast') {
        return // it is a story update!
    }
    console.log(message.messageStubType))
    sendApi({ message: message})
})
```

**Comment by adiwajshing** [comment]
Assuming it's resolved -- closing.
