### ISSUE TITLE
Sending List Message thru WA Business doesnt work

### ISSUE THREAD

**Issue by cryptoAlgorithm** [adiwajshing/Baileys#654]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
When a list message is sent thru a WA business account, it doesn't get sent. It is shown in the chat view with a error icon, and pressing resend does not do anything.

The error looks something like the image below (taken from another issue)
<img src="https://user-images.githubusercontent.com/72728486/124379537-e99c0280-dce1-11eb-82a8-27a0d200fd6d.jpg">

Although there is one closed issue (#568) very similar to this, neither a solution was provided nor were the replies in English. I hope somebody can help fix my issue or tell me if its impossible to do so, since it would be a great addition to my bot.

**Comment by syifarahmat** [comment]
You can See : 
https://discord.com/channels/725839806084546610/855153774841298994/872148736866934825

**Comment by ibnusyawall** [comment]
list messages require standard (no business)

**Comment by PurpShell** [comment]
this is a limitation in whatsapp, not baileys. Close this issue please lol
