### ISSUE TITLE
[FRM]  I can't send Media if the message is temporarily active

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#657]
I used the method from issue #602 
But i can't send if the message is temporarily active.

if message is temporarily off => https://i.ibb.co/0CbWJW0/Screenshot-20210820-205443.png

if message is temporarily active => https://i.ibb.co/51hKZH8/Screenshot-20210820-205526.png

How to handle that problem ?

**Comment by FaizBastomi** [comment]
you mean "disappearing messages" is on?

**Comment by FaizBastomi** [comment]
please, show your code.

**Comment by frmdeveloper** [comment]
> please, show your code.

I have included the code

**Comment by frmdeveloper** [comment]
I have fixed the bug. Now I will pull the code above
