### ISSUE TITLE
Multi-device Support

### ISSUE THREAD

**Issue by YehudaEi** [adiwajshing/Baileys#663]
Hi,
Is there a chance to work soon with a beta of multi-devices?

**Comment by ferhacks** [comment]
It's easy to say, but doing it is something else.

**Comment by FaizBastomi** [comment]
please, stop asking "multi-device". we are all working here. Can't tell when it will be finished. Because we want to guarantee everything is working before it is released publicly.

**Comment by YehudaEi** [comment]
Sorry, I'm really sorry. I just wanted to ask if it's really at work. It's clear to me that it's complicated to program it.

**Comment by FaizBastomi** [comment]
Don't feel guilty, I know you all want to quickly support the "multi-device" and always check on the progress.
the key is patience.

**Comment by PurpShell** [comment]
Really, Multi-device is a huge topic to discuss..

Duplicate of #605 (@adiwajshing please close this and open that one)

see you guys there
