### ISSUE TITLE
how to add label to chat or contacts?

### ISSUE THREAD

**Issue by harshmakani1** [adiwajshing/Baileys#667]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

pls add support for label chat or messages.

**Comment by harshmakani1** [comment]
Pls reply me.

**Comment by Ergo-proxy9847** [comment]
> Pls reply me.

Hi

**Comment by azudindaem** [comment]
No you can't

WhatsApp Business users can’t edit their business name or labels from WhatsApp Web or Desktop.
