### ISSUE TITLE
How to get the credentials from the browser???

### ISSUE THREAD

**Issue by Manjit2003** [adiwajshing/Baileys#67]

**Comment by adiwajshing** [comment]
Do see the [browser credentials type](https://github.com/adiwajshing/Baileys/blob/8ce1e2da0831e5603a7086bf84ea846f85eba488/src/WAConnection/Constants.ts#L23) 

Then:
1. Open WhatsApp Web and then Chrome developer tools (CMD + ctrl + I)
2. Open the Application section
3. In the application section, open local storage
4. Find the corresponding keys i.e.  `WASecretBundle`, `WAToken1`, `WABrowserId`, `WAToken2`
5. Create a JSON file with the above mentioned keys & their values
6. Use that JSON file for your credentials as mentioned in the readme.

Hope this helps.

**Comment by adiwajshing** [comment]
Assuming it's resolved -- closing.
