### ISSUE TITLE
[BUG] Media upload failed on all hosts 

### ISSUE THREAD

**Issue by TentacleSama4254** [adiwajshing/Baileys#670]
Will comment till one of you fix this issue

![IMG_20210828_044717](https://user-images.githubusercontent.com/74726248/131197417-1621b5f9-58cb-4e62-a982-b29441426bd9.jpg)

**Comment by ekoeryanto** [comment]
welcome to github 🤣 

post the code to reproduce the issue, please

**Comment by TentacleSama4254** [comment]
Happens whenever I try to send any media (imageMessage/videoMessage/audioMessage/document/Message)

**Comment by TentacleSama4254** [comment]
.

**Comment by TentacleSama4254** [comment]
> welcome to github 🤣 
> 
> post the code to reproduce the issue, please.
> 
> you can read it from here https://github.com/adiwajshing/Baileys/blob/8ce486d2a50d6aafc728728ead5b8dfe1d3b4ac3/src/WAConnection/6.MessagesSend.ts#L224


Try

```
wait nrc.run(youtube-dl https://youtu.be/_PPUSOy_1GM --output ./temp.mp4) 
   var fDl = await fs.readFile(./temp.mp4)
   await client.sendMessage(from,fDl, MessageType.video ,{ caption : '',quoted: m})
```
