### ISSUE TITLE
can somebody port this project to c#.net

### ISSUE THREAD

**Issue by asushil** [adiwajshing/Baileys#676]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by asushil** [comment]
i did not find how it can be done in .net

**Comment by ekoeryanto** [comment]
create a websocket server and connect to it
