### ISSUE TITLE
How to send location with caption?

### ISSUE THREAD

**Issue by RidwanXyZ** [adiwajshing/Baileys#677]

**Comment by FaizBastomi** [comment]
Code :
```js
conn.sendMessage(jid, { degressLongitude: 0, degressLatitude: 1, comment: "caption" }, MessageType.location)
```

Docs: [here](https://adiwajshing.github.io/Baileys/interfaces/proto.ilocationmessage.html)

***
If you just want to ask something, please join our discord server. [click me](https://discord.gg/7FYURJyqng)
