### ISSUE TITLE
How To Send An Image Using relayMessage?

### ISSUE THREAD

**Issue by WhatTheSemvak** [adiwajshing/Baileys#678]
How To Send An Image Using relayMessage?
I so confused with this problem. Every i try with json code it must be error, I already to try Eval the Image. I want to relay because i want the fileLength and imagesize is not changed, Different for sendMessage, tell me how to fix this

**Comment by FaizBastomi** [comment]
do you have a sample code?
If so, please include it in your comments.
We can't help without the code snipset you used.
***
To discuss further, please join our discord server. [click me](https://discord.gg/7FYURJyqng)
