### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SaiSridhar783** [adiwajshing/Baileys#679]
**Describe the bug**
Sending image/video as sticker does not work. It shows properly on Whatsapp Web but not on Phone.

**To Reproduce**
1. Created a new connection
2. conn.sendMessage(id, {url: "./sticker.png"}, MessageType.sticker}

**Expected behavior**
Message should be sent as a sticker but the message is empty.

**Environment (please complete the following information):**
 - Is this on a server? Local
 - What do your `connectOptions` look like?  Default as in example.ts (no proxies)
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by SaiSridhar783** [comment]
On further inspection, found that these keys are missing in the data:

Original sticker message:
![image](https://user-images.githubusercontent.com/58875230/131985054-47fad8e1-e6dc-451c-9cfd-0422c379616e.png)

Sticker message sent by Baileys:
![image](https://user-images.githubusercontent.com/58875230/131985198-caa9b118-06b0-4d3c-a430-6554974b4875.png)

**Comment by FaizBastomi** [comment]
Sending stickers using Baileys, make sure beforehand that the format to be sent is in webp format.  Baileys doesn't include convert to webp by default.  So you are required to convert yourself to webp format.

**Comment by SaiSridhar783** [comment]
Yes, Converting to webp explicitly works like a charm.
