### ISSUE TITLE
Do not reconnect automatically after loosing network connection

### ISSUE THREAD

**Issue by diegogazzolo** [adiwajshing/Baileys#68]
Steps:
1) Connect whith client.autoReconnect = true;
2) Try to receive some messages, OK
3) Manually desconnect my network adapter.
4) setOnUnexpectedDisconnect is fired: closed
5) Manually reconnect my network adapter.
6) Wait 30 secconds
7) Try to receive another messages, but I stop receiving, 
8) Tray to send message throw http://localhost:3000/sebd?texto=text. Error is fired (error stack at the end of this text)

Log:
====================================

C:\data\labs\wa1>node index
[Baileys][14/7/2020 12:28:33] loading authentication credentials from ./auth_info.json
[Baileys][14/7/2020 12:28:33] connected to WhatsApp Web, authenticating...
[Baileys][14/7/2020 12:28:34] resolving login challenge
[Baileys][14/7/2020 12:28:34] validated connection successfully
oh hello Facundo Gazzolo (5493541686538@s.whatsapp.net)
got notification of type: message
message type: conversation
mensaje: {"key":{"remoteJid":"5493541622098@s.whatsapp.net","fromMe":false,"id":"3EB058DC258D7865EF17"},"message":{"conversation":"parafacu8"},"messageTimestamp":"1594740526","status":"ERROR"}
disconnected unexpectedly:  "closed"

Code (index.js):
====================================
const {
    WAClient,
    MessageType,
    getNotificationType,
    Mimetype,
    MessageLogLevel,
  } = require("@adiwajshing/baileys");

const fs = require("fs");

const express = require('express');
const http = require('http');
const qrcode = require('qrcode-terminal');

const client = new WAClient();
client.autoReconnect = true;
//client.logLevel = MessageLogLevel.all;

client.setOnUnreadMessage(true, async (m) => {

    const [notificationType, messageType] = getNotificationType(m)

    console.log("got notification of type: " + notificationType) // message, groupAdd, groupLeave
    console.log("message type: " + messageType) // conversation, imageMessage, videoMessage, contactMessage etc.
    
    console.log("mensaje: " + JSON.stringify(m));

  });
  
  client.setOnUnexpectedDisconnect((err) => {
    
    console.log(
      "disconnected unexpectedly: ",
      JSON.stringify(err, null, 2)
    );
    
	/*
	AFTER DISCONNECTION, Do Not Reconnects.
	*/
	
  });

if (fs.existsSync("./auth_info.json"))
{

    client.connectSlim('./auth_info.json').then (user => {
        console.log ("oh hello " + user.name + " (" + user.id + ")")
       
    })
    .catch (err => console.log("unexpected error: " + err));

}
else

client.onReadyForPhoneAuthentication = ([ref, publicKey, clientID]) => {

    const str = ref + ',' + publicKey + ',' + clientID; // the QR string
    // Now, use 'str' to display in QR UI or send somewhere
    console.log("QR SEND: " + str);

    // se envia al otro servidor

    http.get('http://localhost:3001/qr?qr=' + encodeURIComponent(str), (resp) => {
        let data = '';

        // A chunk of data has been recieved.
        resp.on('data', (chunk) => {
            data += chunk;
    });

    // The whole response has been received. Print out the result.
    resp.on('end', () => {
        console.log("QR RECEIVED: " + data);
    });

    }).on("error", (err) => {
        console.log("Error: " + err.message);
    });

}

const app = express();

app.get('/send', (req, res) => {
    
    let texto = req.query.texto;

    const id = '5493541111111@s.whatsapp.net' // the WhatsApp ID 
    
    client.sendMessage(id, texto, MessageType.text);
    
    res.end('OK');

})

app.get('/connect', (req, res) => {
    
    client.connectSlim() // genera que se genere el QR y se envie para escanear
    .then (user => {
        const creds = client.base64EncodedAuthInfo () // contains all the keys you need to restore a session
        fs.writeFileSync('./auth_info.json', JSON.stringify(creds, null, '\t')) // save JSON to file
    });

});

app.get('/reconnect', (req, res) => {
    
    client.connectSlim('./auth_info.json').then (user => {
        console.log ("reconectado " + user.name + " (" + user.id + ")")
    })
    .catch (err => console.log("unexpected error: " + err));

    

});

app.get('/*', (req, res) => {

    res.end('Not Found');

});

app.listen(3000, () =>{

    console.log('Web on port 3000');

});

const app2 = express();

app2.get('/qr', (req, res) => {
    
    let qr = req.query.qr;

    qrcode.generate(qr, {small: true});

    res.end('QR RECEIVED: ' + qr);

})

app2.listen(3001, () =>{

    console.log('Web on port 3001');

});

ERROR After trying to send message:
========================

(node:21024) UnhandledPromiseRejectionWarning: Error: cannot send message, disconnected from WhatsApp
    at WhatsAppWebMessages.WAConnectionBase.send (C:\datos\fuentes\FlexiMarketing\labs\wa1\node_modules\@adiwajshing\baileys\lib\WAConnection\Base.js:332:19)
    at WhatsAppWebMessages.WAConnectionBase.sendBinary (C:\datos\fuentes\FlexiMarketing\labs\wa1\node_modules\@adiwajshing\baileys\lib\WAConnection\Base.js:313:14)
    at WhatsAppWebMessages.<anonymous> (C:\datos\fuentes\FlexiMarketing\labs\wa1\node_modules\@adiwajshing\baileys\lib\WAConnection\Base.js:286:32)
    at step (C:\datos\fuentes\FlexiMarketing\labs\wa1\node_modules\@adiwajshing\baileys\lib\WAConnection\Base.js:52:23)
    at Object.next (C:\datos\fuentes\FlexiMarketing\labs\wa1\node_modules\@adiwajshing\baileys\lib\WAConnection\Base.js:33:53)

**Comment by adiwajshing** [comment]
Hi,

I've implemented a feature that queues requests when the connection is closed. This will prevent an error from being thrown when in-between reconnects. 

This is implemented in the latest commit, which you can install using: `npm install github:adiwajshing/baileys`. 
You don't have to change any code in your app -- it will just work.

**Comment by diegogazzolo** [comment]
Hi, thanks again for your response.
 
I update the package and tested again.

The result was:
================

1) After loosing network connection it tried to reconet several times
2) When networt connection was ok it tried to login
3) Here I don't undestand the sequence:
[Baileys][15/7/2020 19:16:03] validated connection successfully (OK)
oh no got disconnected: closed (CLOSED)
4) But then i tried to receive a message and was ok.

I think this message must not be printed: "oh no got disconnected: closed (CLOSED)", no?

LOG:
================
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:15:56] network is down, reconnecting...
[Baileys][15/7/2020 19:16:00] connected to WhatsApp Web, authenticating...
[Baileys][15/7/2020 19:16:02] resolving login challenge
[Baileys][15/7/2020 19:16:03] validated connection successfully
oh no got disconnected: closed
got notification of type: message
message type: conversation
mensaje: {"key":{"remoteJid":"5493541622098@s.whatsapp.net","fromMe":false,"id":"3EB01A23A86D7EF76629"},"message":{"conversation":"prueba4"},"messageTimestamp":"1594851417","status":"ERROR"}

**Comment by adiwajshing** [comment]
You're right -- `onUnexpectedDisconnect` should not be called with `autoReconnect`. Have fixed in the latest commit.

**Comment by diegogazzolo** [comment]
Now it's ok !

Thanks
