### ISSUE TITLE
WhatsApp Web Multi Device Login and without Phone Internet Connection

### ISSUE THREAD

**Issue by Nazzid** [adiwajshing/Baileys#680]
![WhatsApp-multi-device-support](https://user-images.githubusercontent.com/68158086/131896868-77424863-a19c-43fc-95d5-694787435271.jpg)

**Comment by LuanRT** [comment]
Baileys does not support multi-device yet, please close this issue.

**Comment by salman0ansari** [comment]
Duplicate of #605

**Comment by SLdevilX** [comment]
yes need it
