### ISSUE TITLE
How to run as a daemon?

### ISSUE THREAD

**Issue by alex3o0** [adiwajshing/Baileys#684]
I have been using [venom-bot](https://github.com/orkestral/venom/) for a year with no much troubles but now I want to check this repo. The problem is, when I stop the execution I lost the session, so the second time I run the script I need to capture the QR code again. In docker this is not biggie, I can just press `ctrl + p`, `ctrl+q` to liberate my terminal without stoping the process. But now I'm trying to run it with systemctl wich forces to run it in background so I can't capture the QR code.

In venom-bot I have no problem since the session's cache is saved in a token file so I can run it normaly once, capture the QR code, stop it, an then run it as service. How is Baileys way to do this?

**Comment by UnKnoWn-Consortium** [comment]
Read the doc
https://github.com/adiwajshing/Baileys#saving--restoring-sessions
