### ISSUE TITLE
Possible memory leak in event listeners registration

### ISSUE THREAD

**Issue by bfbechlin-axur** [adiwajshing/Baileys#687]
I got the Baileys library working on production with a shitty phone that disconnects all the time, there are plans to change it but now we need the root setup on it. Thus, inside the close listener, I have been calling again to connect after a fixed delay to keep the connection alive. After some hours, I find out some node warnings in the logs:

```
(node:17) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 ws-close listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit
```
```
(node:17) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 31 connection-phone-change listeners added to [WAConnection]. Use emitter.setMaxListeners() to increase limit
```

After that my Winston logger is killed and I have to look in the container output.

Events that I'm being listening to:
* open
*  close
*  chat-update
*  chats-update

My reconnection routine does not try to bind any of these events again. I suspect that calling connect several times without success may lead to this scenario. I had not seen any advice for not calling connect more than once, but in any case, I will ask is there a cleanup that I have to call before I try to connect again (like close)?

**Comment by ekoeryanto** [comment]
that is not a bug, but you are 😂
just set wa.setMaxListeners(0)

**Comment by bfbechlin-axur** [comment]
Seems nice, then I set that max listener to infinity, and the code keep creating listeners until I got an out of memory. Good advice @ekoeryanto , in the same line as don't mind about freeing your pointers, you do have lots of memory nowadays.

**Comment by elbiozard** [comment]
> wa.setMaxListeners(0)

Hello! Sorry for the bad translation and ignorance, but I have the same problem and I don't know where to add the line "wa.setMaxListeners(0)". I would appreciate it if you could help me where I should go. Thanks
