### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ftwrr** [adiwajshing/Baileys#689]
INFO [2021-09-09 23:38:54.112 +0000] (7252): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
WARN [2021-09-09 23:39:54.146 +0000] (7252): connect attempt 1 failed: Error: timed out, retrying...
    class: "Baileys"
    error: {}
INFO [2021-09-09 23:39:58.256 +0000] (7252): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"
WARN [2021-09-09 23:40:58.315 +0000] (7252): connect attempt 2 failed: Error: timed out, retrying...
    class: "Baileys"
    error: {}
INFO [2021-09-09 23:41:02.418 +0000] (7252): connected to WhatsApp Web server, authenticating via takeover
    class: "Baileys"

**Comment by FaizBastomi** [comment]
check your internet connection. And I beg you not to make an issue like this again, very much begging you to please close this issue because it is not related to Baileys.
