### ISSUE TITLE
Missing setOnTakenOver

### ISSUE THREAD

**Issue by diegogazzolo** [adiwajshing/Baileys#69]
Hi, I tried to take an action when the user close the session from WhatsApp in the phone.

a)
I tried to use "client.setOnTakenOver" but the compiler throw an error:
TypeError: client.setOnTakenOver is not a function,

I searched in code but I could not find it.

(I edited the issue, i'll divide it in 2 issues. thanks)

**Comment by adiwajshing** [comment]
I think [this](https://github.com/adiwajshing/Baileys/blob/5a39683c02fc18628a76700dad589de1e5c05e95/Example/example.ts#L116) is the function you're looking for.

**Comment by diegogazzolo** [comment]
I foud this in the Readme but i could not use it:

Called when you log into WhatsApp Web somewhere else
client.setOnTakenOver (async () => {
    // reconnect to gain connection back here
    await client.connect ()
})

**Comment by adiwajshing** [comment]
You're right -- left it there by mistake. Have removed from the readme now. Please do see the link I sent to respond to the taken over event

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing.
