### ISSUE TITLE
iam requesr fitur end group

### ISSUE THREAD

**Issue by Ivan-MLN** [adiwajshing/Baileys#690]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by noizydev** [comment]
Lol

**Comment by xfar05** [comment]
Stres

**Comment by juwenaja** [comment]
gimana cara ngasih tau ke dia ya bro

**Comment by MrG3P5** [comment]
lmao

**Comment by ekoeryanto** [comment]
malu-maluin. tutup!

**Comment by dhyZx** [comment]
Bocah gobloggggg

**Comment by EhanGanss** [comment]
blok goblok

**Comment by sansekai** [comment]
Lawak

**Comment by Zalleya** [comment]
akwkw stres

**Comment by DielGanz** [comment]
bgaimana kita kasih tau ke dia

**Comment by meowcraftY** [comment]
Stress, ngetik aja masih typo

**Comment by ultimareall** [comment]
Pansos

**Comment by bennysolo** [comment]
akun dana dek

**Comment by Errs404** [comment]
wtf

**Comment by AlvioAdjiJanuar** [comment]
ada apa ini

**Comment by frmdeveloper** [comment]
Wah, anda harus menggunakan whatsapp mod yang ada fitur end group
Terus, anda harus membuat fitur leavegrup di script anda
SELESAI

**Comment by ZuxyGanz** [comment]
Anda tau janda?

**Comment by frmdeveloper** [comment]
> gimana cara ngasih tau ke dia ya bro

Caranya gini bang

**Comment by frmdeveloper** [comment]
> wah
.

**Comment by ZuxyGanz** [comment]
> > gimana cara ngasih tau ke dia ya bro
> 
> Caranya gini bang

/> Mangkannya terkenal tolol:v

**Comment by ZuxyGanz** [comment]
> Wah, anda harus menggunakan whatsapp mod yang ada fitur end group
> Terus, anda harus membuat fitur leavegrup di script anda
> SELESAI

Sangat pintar awokawokawokawoka tapi kalo ngga jadi admin ya ngga ke end:v

**Comment by shinainaru** [comment]
Njerr ko iso

**Comment by BochilGaming** [comment]
GG gemink :v

**Comment by ozoktay** [comment]
17 Eyl 2021 Cum, saat 02:20 tarihinde BochilGaming ***@***.***>
şunu yazdı:

**Comment by frmdeveloper** [comment]
Ternyata bukan saya doang yang gini.
Giliran saya yang gitu, dibuli di semua sosmed seperti whatsapp DLL

**Comment by frmdeveloper** [comment]
> > Wah, anda harus menggunakan whatsapp mod yang ada fitur end group
> > Terus, anda harus membuat fitur leavegrup di script anda
> > SELESAI
> 
> Sangat pintar awokawokawokawoka tapi kalo ngga jadi admin ya ngga ke end:v

kasih if (!isBotAdmin) return reply('Gue bukan admin !!!')

**Comment by juwenaja** [comment]
> > > Wah, anda harus menggunakan whatsapp mod yang ada fitur end group
> > > Terus, anda harus membuat fitur leavegrup di script anda
> > > SELESAI
> > 
> > 
> > Sangat pintar awokawokawokawoka tapi kalo ngga jadi admin ya ngga ke end:v
> 
> kasih `if (!isBotAdmin) return reply('Gue bukan admin !!!')`

aowkaowk

**Comment by Ivan-MLN** [comment]
Y

**Comment by noizydev** [comment]
mastah jadi2an berulah kembali & buat malu gob-

**Comment by rtwone** [comment]
Blok!!!

**Comment by Manxtodd** [comment]
Ipan ipan

**Comment by ArdyBotzz** [comment]
njir mastah lol

**Comment by ArdyBotzz** [comment]
ipanz"😱

**Comment by DepinKunn** [comment]
Bang Ivan😍🥰🥴🥴

**Comment by SanzGantengz** [comment]
Mastah kita komen😱

**Comment by ArdyBotzz** [comment]
apasih

Pada tanggal Kam, 23 Sep 2021 10.50 AM, SanzGantengz <
***@***.***> menulis:

**Comment by VEXG** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature/question**

STRESSS

**Comment by frmdeveloper** [comment]
Udah ditutup masih rame

**Comment by shinz-404** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. Search through the repo's previous issues
> 2. Read through the readme at least once
> 3. Search the docs for the feature you're looking for
> 
> **Just describe the feature/question**

Wkwkwkw bocil termux tolol²

**Comment by MuhammadRestu999** [comment]
Awokawokawok :v
