### ISSUE TITLE
Bug on Updating Profile Name

### ISSUE THREAD

**Issue by phaticusthiccy** [adiwajshing/Baileys#691]
https://github.com/adiwajshing/Baileys/blob/8ce486d2a50d6aafc728728ead5b8dfe1d3b4ac3/src/WAConnection/5.User.ts#L80

Changed name overwrites existing name. Before these functions, you can add `.replace(conn.user.jid, name)`
I don't need to open a pr for this. If so, I'm sure there won't be any problems.

**Comment by sandro-salles** [comment]
Hey @[phaticusthiccy](https://github.com/phaticusthiccy)

Do you have ny hint on how to change the profile name on MD version?

Thanks in advance!

**Comment by phaticusthiccy** [comment]
I haven't seen a function for this yet. I think you should do this with custom actions. I haven't used this module for a long time. A lot has changed. Sooo may you can open a new topic or issue for this ı donna know yet 🤔
