### ISSUE TITLE
Support for Beta Version of Whatsapp

### ISSUE THREAD

**Issue by dotcomsolutionsAB** [adiwajshing/Baileys#692]
Is this library compatible with the new Beta version of Whatsapp.

**Comment by khoirulh1610** [comment]
not yet

**Comment by alsa-kode** [comment]
are there any next future roadmap plans?
thanks!

**Comment by adiwajshing** [comment]
Ya'll can try it out [here](https://github.com/adiwajshing/Baileys/tree/multi-device)

**Comment by alsa-kode** [comment]
Brilliant. Great work, thanks for sharing!

**Comment by alsa-kode** [comment]
Hiya, I've been playing around with new multi-device beta. I've created a MQTT2Whatsapp bridge that uses Baileys to receive and send MQTT messages. All good except that whatsapps are sent twice with no reason. This is the log that happens after I call sendMessageWTyping({ text: message }, id): 

{"level":10,"time":1632735855641,"pid":29,"hostname":"2197f524bead","msgId":"d.3-60","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"d.3-60"},"content":[{"tag":"usync","attrs":{"sid":"d.3-59","mode":"query","last":"true","index":"0","context":"message"},"content":[{"tag":"result","attrs":{},"content":[{"tag":"devices","attrs":{},"content":null}]},{"tag":"list","attrs":{},"content":[{"tag":"user","attrs":{"jid":"34696419289@s.whatsapp.net"},"content":[{"tag":"devices","attrs":{},"content":[{"tag":"device-list","attrs":{},"content":[{"tag":"device","attrs":{"id":"0"},"content":null},{"tag":"device","attrs":{"id":"2","key-index":"3"},"content":null},{"tag":"device","attrs":{"id":"31","key-index":"61"},"content":null}]},{"tag":"key-index-list","attrs":{"ts":"1632734154"},"content":{"type":"Buffer","data":[10,19,8,138,216,205,252,4,16,202,151,198,138,6,24,61,34,3,0,3,61,18,64,109,29,71,134,39,69,159,88,36,20,129,201,77,251,197,62,9,117,57,161,72,163,226,176,122,183,37,162,0,143,158,34,125,201,225,240,143,8,116,142,230,199,3,50,185,114,54,166,28,29,185,205,247,4,77,240,1,115,130,29,46,178,201,132]}}]}]}]}]}]},"msg":"communication"}
{"level":20,"time":1632735855641,"pid":29,"hostname":"2197f524bead","msg":"got 2 additional devices"}
{"level":20,"time":1632735855645,"pid":29,"hostname":"2197f524bead","msgId":"BAE5DCF5F5B7239A","msg":"sending message"}
{"level":10,"time":1632735855761,"pid":29,"hostname":"2197f524bead","msgId":"BAE5DCF5F5B7239A","fromMe":false,"frame":{"tag":"ack","attrs":{"from":"34696419289@s.whatsapp.net","class":"message","id":"BAE5DCF5F5B7239A","t":"1632735855"},"content":null},"msg":"communication"}
{"level":20,"time":1632735855762,"pid":29,"hostname":"2197f524bead","attrs":{"from":"34696419289@s.whatsapp.net","class":"message","id":"BAE5DCF5F5B7239A","t":"1632735855"},"msg":"sending receipt for ack"}
{"level":10,"time":1632735856181,"pid":29,"hostname":"2197f524bead","msgId":"BAE5DCF5F5B7239A","fromMe":false,"frame":{"tag":"receipt","attrs":{"from":"34696419289:2@s.whatsapp.net","type":"inactive","id":"BAE5DCF5F5B7239A","t":"1632735856"},"content":null},"msg":"communication"}
{"level":10,"time":1632735856579,"pid":29,"hostname":"2197f524bead","msgId":"d.3-58","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"d.3-58"},"content":[{"tag":"usync","attrs":{"sid":"d.3-57","mode":"query","last":"true","index":"0","context":"message"},"content":[{"tag":"result","attrs":{},"content":[{"tag":"devices","attrs":{},"content":null}]},{"tag":"list","attrs":{},"content":[{"tag":"user","attrs":{"jid":"34696419289@s.whatsapp.net"},"content":[{"tag":"devices","attrs":{},"content":[{"tag":"device-list","attrs":{},"content":[{"tag":"device","attrs":{"id":"0"},"content":null},{"tag":"device","attrs":{"id":"2","key-index":"3"},"content":null},{"tag":"device","attrs":{"id":"31","key-index":"61"},"content":null}]},{"tag":"key-index-list","attrs":{"ts":"1632734154"},"content":{"type":"Buffer","data":[10,19,8,138,216,205,252,4,16,202,151,198,138,6,24,61,34,3,0,3,61,18,64,109,29,71,134,39,69,159,88,36,20,129,201,77,251,197,62,9,117,57,161,72,163,226,176,122,183,37,162,0,143,158,34,125,201,225,240,143,8,116,142,230,199,3,50,185,114,54,166,28,29,185,205,247,4,77,240,1,115,130,29,46,178,201,132]}}]}]}]}]}]},"msg":"communication"}
{"level":20,"time":1632735856580,"pid":29,"hostname":"2197f524bead","msg":"got 2 additional devices"}
{"level":20,"time":1632735856584,"pid":29,"hostname":"2197f524bead","msgId":"BAE5DF6D39F71558","msg":"sending message"}
{"level":10,"time":1632735856701,"pid":29,"hostname":"2197f524bead","msgId":"BAE5DF6D39F71558","fromMe":false,"frame":{"tag":"ack","attrs":{"from":"34696419289@s.whatsapp.net","class":"message","id":"BAE5DF6D39F71558","t":"1632735856"},"content":null},"msg":"communication"}

I hope you can track this to understand why two messages are going out.

In case it helps, this is what triggers the 'sending out':

        mqclient.on('message', function (topic, message) {
            const id=topic.split("/")[1]+"@s.whatsapp.net";
            sendMessageWTyping({ text: message }, id)
          })

**Comment by burstfreeze** [comment]
@alsa-kode you should create a new issue for a new problem. However, for these kinds of issues that can very well be implementation-issues on your side, please join https://discord.gg/gZmbTE4ERN - we have these chat servers to keep the Baileys issue section a bit more clean and discuss at a faster pace. The maintainer is also there but we want him to be able to work without distraction so we try to help and solve everyone's problems to let the maintainers focus on their incredible work on this.

**Comment by alsa-kode** [comment]
> @alsa-kode you should create a new issue for a new problem. However, for these kinds of issues that can very well be implementation-issues on your side, please join https://discord.gg/gZmbTE4ERN - we have these chat servers to keep the Baileys issue section a bit more clean and discuss at a faster pace. The maintainer is also there but we want him to be able to work without distraction so we try to help and solve everyone's problems to let the maintainers focus on their incredible work on this.

Understood and agreed. Thanks.

**Comment by jefripunza** [comment]
i have unique error
```
D:\Project App\adaundanganonline.com>node md
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'D:\Project App\adaundanganonline.com\md'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
help me please :')

**Comment by jhowbhz** [comment]
npm install cjs --unsafe-perm

> i have unique error
> 
> ```
> D:\Project App\site.com>node md
> internal/modules/cjs/loader.js:892
>   throw err;
>   ^
> 
> Error: Cannot find module 'D:\Project App\site.com\md'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```
> 
> `md.ts` file :
> 
> ```
> import makeWASocket, { BufferJSON } from '@adiwajshing/baileys-md'
> import * as fs from 'fs'
> 
> // will initialize a default in-memory auth session
> const conn = makeSocket()
>     // this will be called as soon as the credentials are updated
> conn.ev.on('auth-state.update', () => {
>     // save credentials whenever updated
>     console.log(`credentials updated!`)
>     const authInfo = conn.authState // get all the auth info we need to restore this session
>         // save this info to a file
>     fs.writeFileSync(
>         './auth_info.json',
>         JSON.stringify(authInfo, BufferJSON.replacer, 2)
>     )
> })
> ```
> 
> help me please :')

**Comment by jefripunza** [comment]
> npm install cjs --unsafe-perm

i still have the same problem

**Comment by jefripunza** [comment]
after I changed to the .mjs extension then a new error occurred :
```
D:\Project App\site.com>node md.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'D:\Project App\site.com\node_modules\@adiwajshing\baileys-md\' imported from D:\Project App\site.com\md.mjs     
    at legacyMainResolve (internal/modules/esm/resolve.js:222:9)
    at packageResolve (internal/modules/esm/resolve.js:657:14)
    at moduleResolve (internal/modules/esm/resolve.js:705:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
