### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by rtwone** [adiwajshing/Baileys#693]
Hello bro Adi, I want to request a feature getSnapchat like Sha's Open WhatsApp library, I'm waiting bro, good luck

**Comment by FaizBastomi** [comment]
duplication of #681 

Please before creating an issue, search and read the existing issues to avoid duplication of issues.

**Comment by rtwone** [comment]
> duplication of #681 
> 
> Please before creating an issue, search and read the existing issues to avoid duplication of issues.

eumm oke

**Comment by FaizBastomi** [comment]
@rtwone Please close this issue.  Thank you.
> eumm oke
