### ISSUE TITLE
@adiwajshing @ibnusyawall Has anyone tested this in a WA Business app? I am getting error while sending a message. **This works completely fine in normal WA.**

### ISSUE THREAD

**Issue by Goomer2** [adiwajshing/Baileys#694]
@adiwajshing @ibnusyawall Has anyone tested this in a WA Business app? I am getting error while sending a message. **This works completely fine in normal WA.**

![image](https://user-images.githubusercontent.com/6497827/124917800-e3739200-e011-11eb-98b9-e254d4323f3f.png)

_Originally posted by @vasani-arpit in https://github.com/adiwajshing/Baileys/pull/574#issuecomment-876378662_

**Comment by FaizBastomi** [comment]
that's a limitation of WhatsApp itself.  Not a problem with Baileys.

**Comment by FaizBastomi** [comment]
You can read the comments on this issue. #686
