### ISSUE TITLE
ERROR WHEN DELETING PEOPLE

### ISSUE THREAD

**Issue by shanduy** [adiwajshing/Baileys#695]
Hello how are you.
I have an error with a command to remove people from WhatsApp groups. Well when I place the command over to the person I want to delete, I get this error in termux.
![IMG_20210918_233329.jpg](https://user-images.githubusercontent.com/79606488/133915630-654bd3fa-79e7-4a3c-9552-7de95e111caf.jpg)
Before the command worked normally and now I don't know what is happening. If it is my mistake I apologize.
I hope you can help me with this problem

**Comment by FaizBastomi** [comment]
Send us your code so we can find out what went wrong.

**Comment by shanduy** [comment]
It is not a problem with my code, why before it worked fine, now I do not know what is happening, the error is in Baileys there in the image it says it

**Comment by SheIITear** [comment]
Bruh

**Comment by shanduy** [comment]
¿?

**Comment by LuanRT** [comment]
:-; oof

**Comment by PurpShell** [comment]
> ¿?

SEND YOUR CODE!
 please, jid.replace is not a function means you are passing something else...

**Comment by shanduy** [comment]
Do not you know that the error is here ???

**Comment by SheIITear** [comment]
This indeed is a bruh moment.

**Comment by SheIITear** [comment]
Just a tip, if you want people to help you provide them what they ask for.

Me myself lose the interest to help when my questions to figure out what's wrong are declared to be either unnecessary or "my code definitely can't be wrong".

I do assume that's for most others as well, but you do you.

**Comment by PurpShell** [comment]
> Do not you know that the error is here ???

send me your code or get lost

**Comment by shanduy** [comment]
> > ¿No sabes que el error está aquí ???
> 
> envíame tu código o piérdete

jjajajaajaja cerra el culo flaco

**Comment by shanduy** [comment]
> Solo un consejo, si quieres que las personas te ayuden a proporcionarles lo que piden.
> 
> Yo mismo pierdo el interés en ayudar cuando mis preguntas para averiguar qué está mal se declaran innecesarias o "mi código definitivamente no puede estar mal".
> 
> Supongo que eso también es para la mayoría de los demás, pero tú lo haces.

Dou?

**Comment by PurpShell** [comment]
btw you can't delete people, you can only remove participants

**Comment by shanduy** [comment]
> por cierto, no puedes eliminar personas, solo puedes eliminar participantes

Lol it's the same lol

**Comment by VEXG** [comment]
> It is not a problem with my code, why before it worked fine, now I do not know what is happening, the error is in Baileys there in the image it says it

this is the one of the most dumbest issues ever..

well we cant see the actual problems when u not give us the code/case..
if u just scared ur code got leaked just close this issue and get lost

**Comment by SheIITear** [comment]
> > It is not a problem with my code, why before it worked fine, now I do not know what is happening, the error is in Baileys there in the image it says it
> 
> this is the one of the most dumbest issues ever..
> 
> well we cant see the actual problems when u not give us the code/case..
> if u just scared ur code got leaked just close this issue and get lost

It's like I said, he's code must be perfect and never possible for it to break.

**Comment by shanduy** [comment]
> > No es un problema con mi codigo, porque antes funcionaba bien, ahora no se que esta pasando, el error esta en Baileys ahí en la imagen lo dice
> 
> este es uno de los temas más tontos de todos los tiempos.
> 
> Bueno, no podemos ver los problemas reales cuando no nos das el código / caso ...
> si estás asustado, tu código se ha filtrado, cierra este problema y piérdete.

MOMENTO DOU

**Comment by VEXG** [comment]
someone close this issue

**Comment by shanduy** [comment]
> alguien cierre este problema

TENEMO UN MOMENTO NASHEEE

**Comment by Ergo-proxy9847** [comment]
Even if this was a valid issue I doubt anyone here would actually help, all they do is find reasons not to

**Comment by SheIITear** [comment]
> Even if this was a valid issue I doubt anyone here would actually help, all they do is find reasons not to

Ah yes, the dude who made this issue just straight up denies people asking for info about the issue so obviously no one is interested in helping.

Unfortunately my crystal ball can't help with only having a screenshot of some js error.

**Comment by shanduy** [comment]
> > Incluso si este fuera un problema válido, dudo que alguien aquí realmente ayude, todo lo que hacen es encontrar razones para no
> 
> Ah, sí, el tipo que hizo este problema simplemente niega que las personas soliciten información sobre el problema, por lo que obviamente nadie está interesado en ayudar.
> 
> Desafortunadamente, mi bola de cristal no puede ayudar con solo tener una captura de pantalla de algún error de js.

LOl you did not read that now it works with the new version of WhatsApp, so if it was the problem here.

**Comment by LuanRT** [comment]
Dude...🤦‍♂️🤦‍♂️

**Comment by shanduy** [comment]
Momento DOUUUUUUU ✋🤓🤚

**Comment by PurpShell** [comment]
> Even if this was a valid issue I doubt anyone here would actually help, all they do is find reasons not to

I will help, I've been asking for some code to fix his damn issue, but this incompetent bitch decided that he likes a little trolling

@adiwajshing, please close this issue, thanks.

**Comment by shanduy** [comment]
> > Incluso si este fuera un problema válido, dudo que alguien aquí realmente ayude, todo lo que hacen es encontrar razones para no
> 
> Te ayudaré, he estado pidiendo un código para solucionar su maldito problema, pero esta perra incompetente decidió que le gusta un poco de trolling.
> 
> @adiwajshing , cierre este problema, gracias.

MOMENtO BUeNsDO
