### ISSUE TITLE
Can't Recconect after Closing Session in WhatsApp Phone App

### ISSUE THREAD

**Issue by diegogazzolo** [adiwajshing/Baileys#70]
Hi,
Steps:
==========

1) run node index.js (ok)
2) Scan QR from console (ok)
3) In the phone, close the session.
4) Error when try to reconnect. Does not show the new QR.

If I run node index again it works OK.

Console:
==========
C:\watest>node index
[Baileys][17/7/2020 09:58:03] connected to WhatsApp Web, authenticating...
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▄▄  ▀█▀▀▀▀▄▀▀▄▄▄▀██▀▄ ▄█▄█▀▄█ ▄▄▄▄▄ █
█ █   █ █ ▄▀▀█ ▄▀▄  ▄ ▀ ▀█████▄█ █▀█ ▀█ █   █ █
█ █▄▄▄█ █▄▄ █▄█  █▀ ▀ ▄▄▄  ▄ ▀▀▀▀▄ ▄▄▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄█▄█▄▀▄▀▄▀▄▀ █▄█ █ █▄▀▄▀▄█▄▀▄█▄▄▄▄▄▄▄█
█ ▄▄ █▀▄█ █▄▀▄▀█▄█ █▀    ▄▀▄ ▄▄ ▄▀█▄   █▀  ▄█▄█
█▀▀▄▀▄▄▄   █▄█▄█▀▄▀▀███▀ ▀▀█▄▀█▄█ █▀█▄ ▄▀███  █
███  ▀ ▄▄▀█▀ █ ▀█▄ ▄▀▀▀ ▀ ▀ ██▄█▀█▀█▄█▄  █ ▀▀██
█▄███▄█▄█▀█▀▀▀▀█ ▀██ ▄█▄▄▀ ████▀▄▀▀  ▄█ ▄ ▀  ▀█
█▄▀▀▄█▀▄ ▄ ▀▄▄  ▀▀ ▀▄▀▀▀▀▀▄▄ ▀ █     ▄██ ▀ ▀ ▄█
███ ▀▄▀▄▄   ▄▀▀▀▄▀ ▀  ▀█ ▄▀  █▀▄ ▄█▄ ▀▄    ▄▄▀█
█▄ ▄  ▄▄▄ ▄█▀█▀███ █  ▄▄▄ ▄▄▄   ██▀█▀ ▄▄▄ ▀ ▄▀█
███▀  █▄█ ▄▄▀█▄▀█  █  █▄█ ▄█ █▀▄▀█▄ ▄ █▄█ ▀▄  █
█▄▀ ▄▄ ▄ ▄█▄ ▄▄▀█▄▄▄█▄    ▄▀▀███ ▀▀▄  ▄▄ ▄█▀▄▀█
██▀▀▄█▀▄▀██ ▄▀▄    █  █▄ ▀█ █▄█▄▀ ▀▄▀▀▄▀▀▀▀▀▀██
██▀  ▀▄▄ ██  ▄▄ ▀  ▀▄▀▄█▄▄█▄▄█ ▄▀  ▀ ▀▀▄▄   █▄█
█  █  ▄▄▀█▄█▄ ▀▀  ▀██▀▄▀█▄▄  ▀  ▄▀█▄██ ▀▄▀██ ██
█▀█▀▀▀▀▄█▄█▀▀█ ▀▄█▀█ █▄▄▄ ▄▄█▄ ▀▀▀▄▄█ ▀ ███▄▀▀█
██▀▀▀ █▄▄▄ ▀   ▄█ ▀█▀█▄▄▀█▄█ █▀▄█▄ ▀▀ ▄▄ ▀█▄▀▄█
█▄██▄▄█▄█ ▄ █▄▄▀ ▄ ▄▀ ▄▄▄ ▄ ▄▀▄▄ ▀ ██ ▄▄▄ ▄█▀ █
█ ▄▄▄▄▄ ████ █▀▄█ ▀▀▀ █▄█ ▀▄▀▄██ █ ▄▀ █▄█   ███
█ █   █ █▀▀█▄██ ▀▀▀██▄▄  ▄█▄ █▄█▄ ▀ ▄▄ ▄▄▄▄▀▄▄█
█ █▄▄▄█ █  ▀▄  ▄▀█▄██▄▀▄█▀▄▀ ▀▄▀▀▀█ ▄▄▀ ▀▀█▄█ █
█▄▄▄▄▄▄▄█▄▄▄█████▄▄███▄█▄██▄█▄█████▄▄██▄███████

[Baileys][17/7/2020 09:58:13] validated connection successfully
CONNECT OK
oh no got disconnected: undefined
[Baileys][17/7/2020 09:58:26] connected to WhatsApp Web, authenticating...
RECONNECT ERROR: Error: unexpected status: 401 on JSON: {"status":401}

Code:
=========

const {
    WAClient,
    MessageType,
    getNotificationType,
    Mimetype,
    MessageLogLevel,
} = require("@adiwajshing/baileys");

const fs = require("fs");

const client = new WAClient();
client.autoReconnect = true;
//client.logLevel = MessageLogLevel.all;

  
client.setOnUnexpectedDisconnect(reason => {
    console.log ('oh no got disconnected: ' + reason);

    // reconnect

    client.connectSlim().then(user => {
        
        console.log("RECONNECT OK");
        

    })
    .catch (err => {
        console.log("RECONNECT ERROR: " + err);
    });

});

client.connectSlim().then(user => {
        
    console.log("CONNECT OK");
    

})
.catch (err => {
    console.log("CONNECT ERROR: " + err);
});

**Comment by adiwajshing** [comment]
If you log out from the phone -- WhatsApp invalidates your credentials & you get a 401 error.

**Comment by diegogazzolo** [comment]
Yes but it raises after trying to reconnect:

// reconnect

client.connectSlim().then(user => {
    
    console.log("RECONNECT OK");
    

})

**Comment by adiwajshing** [comment]
Yes, if you log out after it is connected -- then try and reconnect -- it will error out.

**Comment by adiwajshing** [comment]
Closing as this isn't really an issue with Baileys
