### ISSUE TITLE
add the verified green check feature in the profile name

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#700]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. find the problem first
2. then fight
3. then close this issue

**Just describe the feature/question**

**Comment by PurpShell** [comment]
> **Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
> 
> 1. find the problem first
> 2. then fight
> 3. then close this issue
> 
> **Just describe the feature/question**

what?

**Comment by FaizBastomi** [comment]
> what? elaborate, the entire issue template is there to tell you, ELABORATE
> wait, i think your feature is already added buddy, wake up..
> https://adiwajshing.github.io/Baileys/interfaces/wacontact.html#verify

Maybe he means something like the picture below, BUT this can only be obtained by accounts that have been verified by WhatsApp directly (to my knowledge)

![IMG_20210925_051647](https://user-images.githubusercontent.com/64179402/134745321-e176b465-a9ba-4866-abd5-d2799098ad57.png)

**Comment by frmdeveloper** [comment]
> > tunggu, sepertinya fiturmu sudah ditambahkan sobat, bangun.. 
> > https://adiwajshing.github.io/Baileys/interfaces/wacontact.html#verify
> 
> Mungkin maksudnya seperti gambar di bawah ini, TAPI ini hanya bisa didapatkan oleh akun yang sudah diverifikasi langsung oleh WhatsApp (setahu saya)
> 
> ![IMG_20210925_051647](https://user-images.githubusercontent.com/64179402/134745321-e176b465-a9ba-4866-abd5-d2799098ad57.png)

the price of whatsapp api is expensive

**Comment by PurpShell** [comment]
> > wait, i think your feature is already added buddy, wake up..
> > https://adiwajshing.github.io/Baileys/interfaces/wacontact.html#verify
> 
> Maybe he means something like the picture below, BUT this can only be obtained by accounts that have been verified by WhatsApp directly (to my knowledge)
> 
> ![IMG_20210925_051647](https://user-images.githubusercontent.com/64179402/134745321-e176b465-a9ba-4866-abd5-d2799098ad57.png)

so he wants one for himself? not possible
