### ISSUE TITLE
[BUG] Cannot read duration on videoMessage.seconds from sendMessage

### ISSUE THREAD

**Issue by VEXG** [adiwajshing/Baileys#703]
**Describe the bug**
Every time i send video from baileys it just show 00:00 but when i play the video the duration work normally ex:
- in quoted / display (sended from sendMessage)
![image](https://user-images.githubusercontent.com/83714022/134757608-1680ba31-3f3e-417e-bd53-0f5246e5bbe0.png)
![image](https://user-images.githubusercontent.com/83714022/134757407-ef422175-4719-4d51-9b4d-3abef3b38002.png)

- when i play it (sended from sendMessage)
![image](https://user-images.githubusercontent.com/83714022/134757426-1d919557-7da7-42ba-b1b5-28985ee6aae6.png)

- in normal video (sended from human/user)
![image](https://user-images.githubusercontent.com/83714022/134757760-93e1cc60-faf3-4af6-9331-d793c63381ef.png)

well my friend fixed it with ffprobe but i seems kinda complicated and heavy cuz it need a tmp
![image](https://user-images.githubusercontent.com/83714022/134757798-27d7f74e-596f-4cd5-9f01-7b42f183d66d.png)

semilar issue #189

**Comment by fazonetea** [comment]
hmm si cilok awokwowk

**Comment by SheIITear** [comment]
So whats happening is that you're not setting the video duration.
What your friend did wasn't a fix, he just downloaded the video and checked the duration using `ffprobe`.

Add duration when sending the file and it should work normally.

More info in [documentation.](url)
