### ISSUE TITLE
[BUG] Restoring Sessions Multi-Device  Failed to decrypt message with any known session

### ISSUE THREAD

**Issue by aguskusmara** [adiwajshing/Baileys#704]
When i try Restoring Sessions
i get errors

![image](https://user-images.githubusercontent.com/71338260/134765523-dac816ea-539a-40fe-b0ea-054cdadb1a15.png)

**Comment by lonelypx** [comment]
I think device MAC address change

**Comment by aguskusmara** [comment]
> I think device MAC address change

how should i do?

**Comment by adiwajshing** [comment]
Ya'll need to save/restore your auth state correctly. Look at the example script

**Comment by aguskusmara** [comment]
> Ya'll need to save/restore your auth state correctly. Look at the example script

this is my code

`const authJSON = JSON.parse(
    fs.readFileSync(
        './auth_info.json',
        { encoding: 'utf-8' }
    ),
    BufferJSON.reviver
)
const auth = { 
    creds: authJSON.creds, 
    // stores pre-keys, session & other keys in a JSON object
    // we deserialize it here
    keys: initInMemoryKeyStore(authJSON.keys) 
}
const conn = makeWASocket(auth)`

i try to create API,,
this work =>await conn.sendMessage(to, {text : msg});

but if i got new message ,,
error = >
`Failed to decrypt message with any known session...
Session error:Error: Bad MAC Error: Bad MAC
    at Object.verifyMAC (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/crypto.js:87:15)
    at SessionCipher.doDecryptWhisperMessage (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/session_cipher.js:248:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SessionCipher.decryptWithSessions (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/session_cipher.js:145:29)
    at async Object.6282111200672.0 [as awaitable] (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/session_cipher.js:169:28)
    at async _asyncQueueExecutor (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/queue_job.js:20:29)`

**Comment by hbinduni** [comment]
i also testing multi device beta but when i restore connection from save session, i got this error: `"msg":"failure in decrypting message"`. i am using `Example/example.ts` from repo.

**Comment by aguskusmara** [comment]
Key used already or never filled

`{"level":50,"time":1632907550278,"pid":17460,"hostname":"e57245183ab7","class":"baileys","msgId":"5A322EE04489ED8DFF56F3E0214DC654","trace":"MessageCounterError: Key used already or never filled\n    at SessionCipher.doDecryptWhisperMessage (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/session_cipher.js:234:19)\n    at Object.6285883424822.0 [as awaitable] (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/session_cipher.js:205:42)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async _asyncQueueExecutor (/rbd/pnpm-volume/4c679e23-8d18-45f8-a99e-d061fe567226/node_modules/libsignal/src/queue_job.js:20:29)","data":"APgQCwb6/4dihYg0JIIvAwQmCPsQWjIu4ESJ7Y3/VvPgIU3GVBKkHf8FFjKQZpeN/ARwZWVyDfwEQWJhefgB+AYWNjMEYPyTMxIhBWpZQo7iMWn3zcWssEu89IIzAlLzhC/1y98jWaMLlqAVGiEFkJi00AL5FKR1Wk50n561KY/hvAJM3rkjoO4CAteS0GQiQjMKIQWO4WogvE0NxECe2wi3VKGLsTaj1/Qp7fHik6lu2vHWQhAAGAAiED8BteS5nRMV1ktAbszcq79h0J3gD9FMKSie/r3+AzAB","msg":"failure in decrypting message"}`

**Comment by diveshahuja** [comment]
I still have this issue, do u got any solution?
