### ISSUE TITLE
How much Share Hosting Resource Require?

### ISSUE THREAD

**Issue by dsuinfo** [adiwajshing/Baileys#707]
Hello @adiwajshing  thanks for script am using this but i want to know how much Resources required to run this smoothly on shared hosting? (because this will not work on VPS i seen)
Ex. If i scan the 100+ Numbers than how much resource it will consume like Ram, Cpu, IOPS, etc of cpanel

Thank you

**Comment by nekiak** [comment]
Why don't you just try and measure it yourself? it depends on your code.

**Comment by dsuinfo** [comment]
okay will share stats if i successfully analyse

**Comment by TentacleSama4254** [comment]
This is generally my resource usage


 ![ee86c00e-5db0-43ae-a90e-c6ed527d5a4c.png](https://user-images.githubusercontent.com/74726248/135226413-d26ca800-2cc1-428d-99a8-437a794063f6.png)

And yes it does depend on what you write in the code. If you just want to check for the numbers it would take waay les
