### ISSUE TITLE
Failed to create group. How to create group on whatsapp?

### ISSUE THREAD

**Issue by ABEBAAPHUMEIN** [adiwajshing/Baileys#71]
**Error**
[Baileys][7/18/2020, 7:48:47 PM] validated connection successfully
[Baileys][7/18/2020, 7:48:51 PM] connected to WhatsApp Web, authenticating...
[Baileys][7/18/2020, 7:48:52 PM] validated connection successfully
    √ should queue requests when closed (9827ms)

  5 passing (3m)
  2 failing

  1) Groups
       should create a group:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\dd\Downloads\Baileys-master\Baileys-master\src\WAClient\Tests.ts)

      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  2) Test Connect

       should connect:

     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\dd\Downloads\Baileys-master\Baileys-master\src\WAConnection\Tests.ts)

      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

### _.env file_

> set TEST_JID=+919323163364@s.whatsapp.net

**_Tests.ts_**

> import { WAClient } from './WAClient'
> import { MessageType, MessageOptions, Mimetype, Presence, ChatModification } from './Constants'
> import * as fs from 'fs'
> import * as assert from 'assert'
> 
> import { decodeMediaMessage, validateJIDForSending } from './Utils'
> import { promiseTimeout, createTimeout } from '../WAConnection/Utils'
> 
> require ('dotenv').config () // dotenv to load test jid
> const testJid = process.env.TEST_JID || '1234@s.whatsapp.net' // set TEST_JID=xyz@s.whatsapp.net in a .env file in the root directory
> 
> async function sendAndRetreiveMessage(client: WAClient, content, type: MessageType, options: MessageOptions = {}) {
>     const response = await client.sendMessage(testJid, content, type, options)
>     assert.strictEqual(response.status, 200)
>     const messages = await client.loadConversation(testJid, 1, null, true)
>     assert.strictEqual(messages[0].key.id, response.messageID)
>     return messages[0]
> }
> function WAClientTest(name: string, func: (client: WAClient) => void) {
>     describe(name, () => {
>         const client = new WAClient()
>         before(async () => {
>             const file = './auth_info.json'
>             await client.connectSlim(file)
>             fs.writeFileSync(file, JSON.stringify(client.base64EncodedAuthInfo(), null, '\t'))
>         })
>         after(() => client.close())
>         func(client)
>     })
> }
> WAClientTest('Messages', (client) => {
>     it('should send a text message', async () => {
>         const message = await sendAndRetreiveMessage(client, 'hello fren', MessageType.text)
>         assert.strictEqual(message.message.conversation, 'hello fren')
>     })
> })
> 
> WAClientTest('Groups', (client) => {
>     let gid: string
>     it('should create a group', async () => {
>         const response = await client.groupCreate('Cool Test Group', [testJid])
>         gid = response.gid
>         console.log('created group: ' + JSON.stringify(response))
>     })
>     
> })

**### I want to create group but error occured. Please Share the script after fixing above error.**

**Comment by adiwajshing** [comment]
Not to worry -- it's only a timeout error. Please read this [section](https://github.com/adiwajshing/Baileys#groups) to understand how to create & modify groups. The `Tests.ts` file should also be of great help. 

This sample script should work well too:
``` ts
import { WAClient } from '@adiwajshing/baileys'

const client = new WAClient() 
client.connectSlim() 
.then (async user => {
    const response = await client.groupCreate('Cool Test Group', ['919999999999@c.us', '1234@c.us'])
    console.log ('created group with id: ' + response.gid)
})
.catch (err => console.log("unexpected error: " + err))
```

**Comment by ABEBAAPHUMEIN** [comment]
Error:

  5 passing (37s)
  1 failing

  1) Pending Requests
       should queue requests when closed:
     Uncaught Error: recieved encrypted buffer when auth creds unavailable
      at Object.decryptWA (src\WAConnection\Utils.ts:113:19)
      at WAConnectionConnector.onMessageRecieved (src\WAConnection\Connect.ts:144:37)
      at WebSocket.<anonymous> (src\WAConnection\Connect.ts:50:47)
      at Receiver.receiverOnMessage (node_modules\ws\lib\websocket.js:797:20)
      at Receiver.dataMessage (node_modules\ws\lib\receiver.js:428:14)
      at Receiver.getData (node_modules\ws\lib\receiver.js:367:17)
      at Receiver.startLoop (node_modules\ws\lib\receiver.js:143:22)
      at Receiver._write (node_modules\ws\lib\receiver.js:78:10)
      at doWrite (_stream_writable.js:403:12)
      at writeOrBuffer (_stream_writable.js:387:5)
      at Receiver.Writable.write (_stream_writable.js:318:11)
      at TLSSocket.socketOnData (node_modules\ws\lib\websocket.js:872:35)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at TLSSocket.Readable.push (_stream_readable.js:212:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)



[Baileys][7/19/2020, 12:51:44 PM] connected to WhatsApp Web, authenticating...
[Baileys][7/19/2020, 12:51:45 PM] validated connection successfully
(node:12108) UnhandledPromiseRejectionWarning: Error: done() called multiple times in test <Pending Requests should queue requests when closed> of file C:\Users\dd\Downloads\Baileys-master\Baileys-master\src\WAConnection\Tests.ts
    at createMultipleDoneError (C:\Users\dd\Downloads\Baileys-master\Baileys-master\node_modules\mocha\lib\errors.js:294:13)
    at multiple (C:\Users\dd\Downloads\Baileys-master\Baileys-master\node_modules\mocha\lib\runnable.js:281:24)
    at done (C:\Users\dd\Downloads\Baileys-master\Baileys-master\node_modules\mocha\lib\runnable.js:292:14)
    at C:\Users\dd\Downloads\Baileys-master\Baileys-master\node_modules\mocha\lib\runnable.js:362:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:12108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! Test failed.  See above for more details.

**Test.ts**

import { WAClient } from './WAClient'
import { MessageType, MessageOptions, Mimetype, Presence, ChatModification } from './Constants'
import * as fs from 'fs'
import * as assert from 'assert'

import { decodeMediaMessage, validateJIDForSending } from './Utils'
import { promiseTimeout, createTimeout } from '../WAConnection/Utils'

const client = new WAClient() 
client.connectSlim() 
.then (async user => {
    const response = await client.groupCreate('Cool Test Group', ['919323105831@c.us', '919323163364@s.whatsapp.net'])
    console.log ('created group with id: ' + response.gid)
})
.catch (err => console.log("unexpected error: " + err))

**Running script in powershell + Windows 10**
