### ISSUE TITLE
Send Image as Document So Whatsapp Didn't Compress The Image

### ISSUE THREAD

**Issue by RiyanRIS** [adiwajshing/Baileys#710]
[QUESTION]
It is possible to send images as documents so that the image quality is not reduced..

**Comment by SheIITear** [comment]
Yes, also aren't the images compressed on the web version only?

**Comment by RiyanRIS** [comment]
> Yes, also aren't the images compressed on the web version only?

how to? or can you give me the reference..

**Comment by SheIITear** [comment]
More info in [documentation](https://adiwajshing.github.io/Baileys/classes/waconnection.html#sendmessage).

**Comment by RiyanRIS** [comment]
this method compresed the image.. but thanks for answer..

**Comment by SheIITear** [comment]
Documents aren't compressed.

**Comment by codevjs** [comment]
how to Send Image as Document?
