### ISSUE TITLE
[BUG] multi-device branch cannot send message to broadcast list

### ISSUE THREAD

**Issue by ander890** [adiwajshing/Baileys#713]
**Describe the bug**
cannot send message to broadcast list, message instead sent to regular number

**To Reproduce**
1. Send message to broadcast list (timestamp@broadcast)

**Comment by ander890** [comment]
@scoder37 pm ngab, wa ada di https://ander890.github.io/

**Comment by frmdeveloper** [comment]
Javascript atau Typescript ?

**Comment by adiwajshing** [comment]
Cannot be sent to broadcast list from MD as of now.
