### ISSUE TITLE
Please give example for button mg reply text i mean Click menu button it send This is a menu Use this commands like this please give example

### ISSUE THREAD

**Issue by DARKCRIME1** [adiwajshing/Baileys#717]
PLEASE **PLEASE**
Please give example for button mg reply text i mean Click menu button it send This is a menu Use this commands like this please give example

Please give example for button mg reply text i mean Click menu button it send This is a menu Use this commands like this please give example

**Comment by maxbgg** [comment]
I want 😝🙏😐

**Comment by viniciusgdr** [comment]
> PLEASE **PLEASE** Please give example for button mg reply text i mean Click menu button it send This is a menu Use this commands like this please give example
> 
> Please give example for button mg reply text i mean Click menu button it send This is a menu Use this commands like this please give example

bro, before opening an Issue, ask first in Server Discord...


but answering, here is a prototype of sending buttons using Baileys MD.

`
let buttons = [
       { buttonId: 'ID1', 
       buttonText: { 
             displayText: 'Button' }, 
             type: 1 
       }
]`
`conn.sendMessage(id, { text: 'Text Here", buttons: buttons })`

**Comment by ravindu01manoj** [comment]
it's magic 😌

**Comment by Hisham-Muhammed** [comment]
> > It's not magic, you have to look at the documentation carefully.
> > You will get a "buttonsResponseMessage" in message.message, look at https://adiwajshing.github.io/Baileys/classes/proto.message.html
> > please look at the docs and ask questions in the [discord](https://discord.gg/7FYURJyqng) for fast response, instead of opening issues (they are meant for bug reports IN BAILEY's CODE, not yours).
> > Thank you.
> 
> gringringrin nice wink

😍✅️👍
