### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by Manjit2003** [adiwajshing/Baileys#72]
I am experiencing the following error just after scanning the qrcode:

`        return new TextDecoder().decode(value)
        ^
ReferenceError: TextDecoder is not defined
`

@adiwajshing any solutions??

**Comment by adiwajshing** [comment]
So, `TextDecoder` is not supported on all platforms. Now that I think about it, I should not have used that in the first place. 

The latest commit does not depend on `TextEncoder` & `TextDecoder`. So, that should work for you. 

You can install it using `npm i github:adiwajshing/baileys`
