### ISSUE TITLE
How to send image or video as document

### ISSUE THREAD

**Issue by codevjs** [adiwajshing/Baileys#722]
How to send image or video as document? I tried using messageType document but it doesn't work

**Comment by TentacleSama4254** [comment]
when you send documets Mimetype is a required parameter

for video try
```client.sendMessage(jid, Buffer, 'documentMessage', {mimetype:'video/mp4', filename: `coolName.mp4` } )```

and images
```client.sendMessage(jid, Buffer, 'documentMessage', {mimetype:'image/jpeg', filename: `coolName.jpeg` } )```
```client.sendMessage(jid, Buffer, 'documentMessage', {mimetype:'image/png', filename: `coolName.png` } )```

..should work

**Comment by codevjs** [comment]
> metype:

Thank u its work
