### ISSUE TITLE
[BUG] npm ERR! > @adiwajshing/baileys-md@4.0.0 prepare

### ISSUE THREAD

**Issue by ianmsfvenom** [adiwajshing/Baileys#727]
i'm writing ` npm i github:adiwajshing/baileys#multi-device` to install the package but it's now returning this error, only when i install without github it works normally, only when down in github it gives the error

```
npm ERR! > @adiwajshing/baileys-md@4.0.0 prepare
npm ERR! > tsc
npm ERR! 
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(10,22): error TS2304: Cannot find name 'CanvasImageSource'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(11,22): error TS2304: Cannot find name 'CanvasImageSource'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(12,22): error TS2304: Cannot find name 'CanvasImageSource'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(17,43): error TS2304: Cannot find name 'ImageBitmapSource'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(18,43): error TS2304: Cannot find name 'ImageBitmapSource'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(22,37): error TS2304: Cannot find name 'HTMLElement'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(27,53): error TS2304: Cannot find name 'CanvasState'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(27,66): error TS2304: Cannot find name 'CanvasTransform'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(27,83): error TS2304: Cannot find name 'CanvasCompositing'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,9): error TS2304: Cannot find name 'CanvasImageSmoothing'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,31): error TS2304: Cannot find name 'CanvasFillStrokeStyles'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,55): error TS2304: Cannot find name 'CanvasShadowStyles'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,75): error TS2304: Cannot find name 'CanvasFilters'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,90): error TS2304: Cannot find name 'CanvasRect'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,9): error TS2304: Cannot find name 'CanvasDrawPath'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,25): error TS2304: Cannot find name 'CanvasText'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,54): error TS2304: Cannot find name 'CanvasImageData'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,71): error TS2304: Cannot find name 'CanvasPathDrawingStyles'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(30,9): error TS2304: Cannot find name 'CanvasTextDrawingStyles'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(30,34): error TS2304: Cannot find name 'CanvasPath'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(39,35): error TS2304: Cannot find name 'EventTarget'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(42,53): error TS2304: Cannot find name 'CanvasRenderingContext2DSettings'.    
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(44,56): error TS2304: Cannot find name 'WebGLContextAttributes'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(44,81): error TS2304: Cannot find name 'WebGLRenderingContext'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(46,11): error TS2304: Cannot find name 'WebGLRenderingContext'.
npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(48,75): error TS2304: Cannot find name 'Blob'.
npm ERR! ../../../../../../node_modules/@types/superagent/index.d.ts(31,29): error TS2304: Cannot find name 'Blob'.
npm ERR! ../../../../../../node_modules/@types/superagent/index.d.ts(119,14): error TS2304: Cannot find name 'XMLHttpRequest'.
npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(11,76): error TS2304: Cannot find name 'WebGLContextAttributes'.
npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(11,102): error TS2304: Cannot find name 'WebGLRenderingContext'.
npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(22,63): error TS2304: Cannot find name 'EXT_texture_filter_anisotropic'.
npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(25,62): error TS2304: Cannot find name 'WEBGL_compressed_texture_s3tc'.
npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(26,52): error TS2304: Cannot find name 'WEBGL_depth_texture'.
npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(27,51): error TS2304: Cannot find name 'WEBGL_lose_context'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(7,37): error TS2304: Cannot find name 'HTMLElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(8,81): error TS2304: Cannot find name 'WebGLContextAttributes'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(17,42): error TS2304: Cannot find name 'WebGLRenderingContext'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(337,47): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(337,59): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(337,98): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(339,61): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(339,73): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(339,112): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(345,47): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(345,59): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(345,98): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(347,61): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(347,73): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(347,112): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(354,31): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(354,43): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(354,82): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(363,31): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(363,43): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(363,82): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(374,31): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(374,43): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(374,82): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(384,31): error TS2304: Cannot find name 'ImageData'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(384,43): error TS2304: Cannot find name 'HTMLImageElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(384,82): error TS2304: Cannot find name 'HTMLVideoElement'.
npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(560,72): error TS2304: Cannot find name 'WebGLActiveInfo'.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 2
npm ERR! npm ERR! path C:\Users\ianga\AppData\Local\npm-cache\_cacache\tmp\git-cloneNLBfQZ
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc
npm ERR!```

**Comment by Gimenz** [comment]
> i'm writing ` npm i github:adiwajshing/baileys#multi-device` to install the package but it's now returning this error, only when i install without github it works normally, only when down in github it gives the error
> 
> ```
> npm ERR! > @adiwajshing/baileys-md@4.0.0 prepare
> npm ERR! > tsc
> npm ERR! 
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(10,22): error TS2304: Cannot find name 'CanvasImageSource'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(11,22): error TS2304: Cannot find name 'CanvasImageSource'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(12,22): error TS2304: Cannot find name 'CanvasImageSource'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(17,43): error TS2304: Cannot find name 'ImageBitmapSource'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(18,43): error TS2304: Cannot find name 'ImageBitmapSource'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(22,37): error TS2304: Cannot find name 'HTMLElement'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(27,53): error TS2304: Cannot find name 'CanvasState'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(27,66): error TS2304: Cannot find name 'CanvasTransform'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(27,83): error TS2304: Cannot find name 'CanvasCompositing'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,9): error TS2304: Cannot find name 'CanvasImageSmoothing'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,31): error TS2304: Cannot find name 'CanvasFillStrokeStyles'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,55): error TS2304: Cannot find name 'CanvasShadowStyles'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,75): error TS2304: Cannot find name 'CanvasFilters'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(28,90): error TS2304: Cannot find name 'CanvasRect'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,9): error TS2304: Cannot find name 'CanvasDrawPath'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,25): error TS2304: Cannot find name 'CanvasText'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,54): error TS2304: Cannot find name 'CanvasImageData'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(29,71): error TS2304: Cannot find name 'CanvasPathDrawingStyles'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(30,9): error TS2304: Cannot find name 'CanvasTextDrawingStyles'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(30,34): error TS2304: Cannot find name 'CanvasPath'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(39,35): error TS2304: Cannot find name 'EventTarget'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(42,53): error TS2304: Cannot find name 'CanvasRenderingContext2DSettings'.    
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(44,56): error TS2304: Cannot find name 'WebGLContextAttributes'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(44,81): error TS2304: Cannot find name 'WebGLRenderingContext'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(46,11): error TS2304: Cannot find name 'WebGLRenderingContext'.
> npm ERR! ../../../../../../node_modules/@types/offscreencanvas/index.d.ts(48,75): error TS2304: Cannot find name 'Blob'.
> npm ERR! ../../../../../../node_modules/@types/superagent/index.d.ts(31,29): error TS2304: Cannot find name 'Blob'.
> npm ERR! ../../../../../../node_modules/@types/superagent/index.d.ts(119,14): error TS2304: Cannot find name 'XMLHttpRequest'.
> npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(11,76): error TS2304: Cannot find name 'WebGLContextAttributes'.
> npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(11,102): error TS2304: Cannot find name 'WebGLRenderingContext'.
> npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(22,63): error TS2304: Cannot find name 'EXT_texture_filter_anisotropic'.
> npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(25,62): error TS2304: Cannot find name 'WEBGL_compressed_texture_s3tc'.
> npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(26,52): error TS2304: Cannot find name 'WEBGL_depth_texture'.
> npm ERR! ../../../../../../node_modules/@types/webgl-ext/index.d.ts(27,51): error TS2304: Cannot find name 'WEBGL_lose_context'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(7,37): error TS2304: Cannot find name 'HTMLElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(8,81): error TS2304: Cannot find name 'WebGLContextAttributes'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(17,42): error TS2304: Cannot find name 'WebGLRenderingContext'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(337,47): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(337,59): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(337,98): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(339,61): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(339,73): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(339,112): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(345,47): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(345,59): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(345,98): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(347,61): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(347,73): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(347,112): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(354,31): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(354,43): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(354,82): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(363,31): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(363,43): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(363,82): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(374,31): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(374,43): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(374,82): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(384,31): error TS2304: Cannot find name 'ImageData'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(384,43): error TS2304: Cannot find name 'HTMLImageElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(384,82): error TS2304: Cannot find name 'HTMLVideoElement'.
> npm ERR! ../../../../../../node_modules/@types/webgl2/index.d.ts(560,72): error TS2304: Cannot find name 'WebGLActiveInfo'.
> npm ERR! npm WARN using --force Recommended protections disabled.
> npm ERR! npm ERR! code 2
> npm ERR! npm ERR! path C:\Users\ianga\AppData\Local\npm-cache\_cacache\tmp\git-cloneNLBfQZ
> npm ERR! npm ERR! command failed
> npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc
> npm ERR!```
> ```

have you resolved this problem?
