### ISSUE TITLE
Create Whatsapp Group With Only Admin Access

### ISSUE THREAD

**Issue by ABEBAAPHUMEIN** [adiwajshing/Baileys#73]
I want to **create a whatsapp group** in which only admin can send message.

**i also want to fetch the invite link of all Joined whatsapp group**

Failed to create whatsapp group of 100 people

Script Crash On trying to add like **100 people** in whatsapp group.

**Comment by adiwajshing** [comment]
Have added this functionality in the latest commit. Do see [here](https://github.com/adiwajshing/Baileys#groups) for usage & install the latest version using: `npm install github:adiwajshing/baileys`

**Comment by ABEBAAPHUMEIN** [comment]
Thank you very much for your quick reply.

I really liked your project very much

### Can you make the working of script like below

****Validate if user is on whatsapp or not

if user is on whatsapp then add the user to particular group**

Can you please drop the script below.

Awaiting for reply

**Comment by adiwajshing** [comment]
That should be fairly straightforward to do after reading the readme. I encourage you to do so & write the script yourself.
