### ISSUE TITLE
[BUG] After yesterday's baileys update, I can't receive messages

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#735]
{"level":50,"time":1634167052535,"pid":18,"hostname":"railway","msgId":"E5BBDA83FCEE574CB6C54ABC67AA02A9","trace":"Error: No sender key for: 6283169480682-1633389755@g.us::994402482908::0\n    at GroupCipher.decrypt (/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/WASignalGroup/group_cipher.js:39:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.decodeMessageStanza (/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/lib/Utils/decode-wa-message.js:70:37)\n    at async WebSocket.<anonymous> (/home/frmdev/frmdev/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:294:21)","data":"APgOCwb6/wxigxaUgGgqFjM4l1UTBCYI+xDlu9qD/O5XTLbFSrxnqgKpBfr/BplEAkgpCAMd/wUWNBZwUg38FUZSTSBEZXZlbG9wZXIg8J+WkO+4j/gB+AYWNjMEF/xcMwiso4yxAxC4ARoQJKu8Udl+9zYGDDphev5yYGCUAikYKvQysxf7bp7oTg/pfJ66ZVVUtRorugOeM3OZVmGVBIMTJklduqw00l6R3tnkELCU3weo4iWTjhBQxAE=","msg":"failure in decrypting message"}

**Comment by frmdeveloper** [comment]
gak jadi

**Comment by ghostvar** [comment]
> gak jadi

so solution is?
