### ISSUE TITLE
Pl provide use cases on the home pages

### ISSUE THREAD

**Issue by vishalparkar** [adiwajshing/Baileys#74]
Thank you very much for creating such a good api.
Pl provide use cases on the home pages so that newbies like me can understand what purposes it can be used for. e.g. I specifically wish to know whether I can use it in my Django project for sending notifications to users' whatsapp numbers based on an event.

Pl guide me. Sorry if I've misused the issue feature to raise this issue !

**Comment by adiwajshing** [comment]
So, this is a Node API -- Django is for Python only I believe. You cannot use this with Django directly. 
You may want to see [this](https://github.com/sigalor/whatsapp-web-reveng) implementation.

Regarding examples -- I believe there are plenty. The readme provides quite a few usage examples, [example.ts](https://github.com/adiwajshing/Baileys/blob/master/Example/example.ts) should be very helpful. Moreover, you should take a look at the `Tests.ts` files in every folder.

**Comment by vishalparkar** [comment]
Thanks for the guidance !
