### ISSUE TITLE
[Multi Device] makeWASocket is not a function (javascript)

### ISSUE THREAD

**Issue by AkirahX** [adiwajshing/Baileys#755]
Hi, I'm trying to use MD for the first time, but this error doesn't let me be happy

Error: `TypeError: makeWASocket is not a function`

Line: ` const conn = makeWASocket({printQRInTerminal: true})`

Full code: 

```javascript
const makeWASocket = require('@adiwajshing/baileys-md')

async function connectWpp(){
    const conn = makeWASocket({
        printQRInTerminal: true
    })
    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect } = update
        if(connection === 'close') {
            const shouldReconnect = (lastDisconnect.error)?.output?.statusCode !== DisconnectReason.loggedOut
            console.log('connection closed due to ', lastDisconnect.error, ', reconnecting ', shouldReconnect)
            if(shouldReconnect) {
                sock = startSock()
            }
        } else if(connection === 'open') {
            console.log('opened connection')
        }
    })
    sock.ev.on('messages.upsert', m => {
        console.log(JSON.stringify(m, undefined, 2))

        console.log('replying to', m.messages[0].key.remoteJid)
        sendMessageWTyping({ text: 'Hello there!' }, m.messages[0].key.remoteJid)
    })
}
connectWpp()
```

I've tried several changes known to me, but nothing resolved (sorry, i'am really noob)

`const { makeWASocket }  = require('@adiwajshing/baileys-md')` 

`const conn = new makeWASocket({
        printQRInTerminal: true
    })`

**Comment by AkirahX** [comment]
> Hello,
> 
> That is because you have to require it like this:
> 
> ```js
> const makeWASocket = require('@adiwajshing/baileys-md').default;
> ```

Thank you very much!!! That solved

**Comment by kamuridesu** [comment]
> Hello,
> 
> That is because you have to require it like this:
> 
> ```js
> const makeWASocket = require('@adiwajshing/baileys-md').default;
> ```

Any way to adapt this using `import` instead of `require`?
