### ISSUE TITLE
Fetch all whatsapp contact?

### ISSUE THREAD

**Issue by ABEBAAPHUMEIN** [adiwajshing/Baileys#76]
How to fetch all whatsapp contact list?

**Comment by adiwajshing** [comment]
Please see [here](https://github.com/adiwajshing/Baileys#connecting)

**Comment by ABEBAAPHUMEIN** [comment]
i have already checked the this guide file. It allows me to fetch the conversation list [i.e chat list]. I want the whole whatsapp contact list with name and number.

**Comment by adiwajshing** [comment]
The `contacts` variable contains all your contacts fren. This will help.

``` ts
client.connect() 
.then (([user, chats, contacts, unread]) => {
    contacts.forEach (contact => {
        const name = contact.name || contact.notify
         console.log ('Hi I am your contact ' + name  + ', my id is ' +  contact.jid)
    })
})
.catch (err => console.log("unexpected error: " + err) )
```
