### ISSUE TITLE
Pdf file preview thumbnail

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#762]
Good afternoon,

Questioning regarding [#429](https://github.com/adiwajshing/Baileys/issues/429)

With the code at the bottom of the file,
```js
conn.sendMessage(jid, pdfBuffer, MessageType.document, { mimetype: Mimetype.pdf, thumbnail: jpegBase64, filename: "name" });
```
But how to get the jpegBase64 from the pdf, how should I proceed, if I don't inform the base64, the thumbnail is not shown, the problem is how to generate the jpegBase64 of the pdf file I'm sending?

Could someone help me in this impasse?

**Comment by mi-khatri** [comment]
hello everyone,
when i try to send pdf file in msg then there is not generate pdf preview on receiver side.
I try all of the code above but no result

My code is
"con.sendMessage(mobile_id, { url: urls }, MessageType.document, { caption: "", mimetype: Mimetype.pdf, filename: "File.pdf", thumbnail: jpegBase64 })"

but no luck

Please help
