### ISSUE TITLE
Decoding Media Error

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#77]
Related to the issue #29 I am facing same error here:

```bash
(node:9356) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/node_modules/node-fetch/lib/index.js:1299:9)
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at Function.fetch [as default] (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/node_modules/node-fetch/lib/index.js:1401:9)
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:237:62
    at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
    at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:23:12)
```

I think this isn't solved. =/

**Comment by kaykyr** [comment]
There are another error also:

```bash
(node:9356) UnhandledPromiseRejectionWarning: Error: Empty buffer returned. File has possibly been deleted from WA servers. Run `client.updateMediaMessage()` to refresh the url
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:244:31
    at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
    at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
    at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:9356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

This happens even after restarting script.

**Comment by kaykyr** [comment]
I am trying to solve this, but if someone know how to fix it, please comment below.

**Comment by kaykyr** [comment]
> Related to the issue #29 I am facing same error here:
> 
> ```shell
> (node:9356) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
>     at getNodeRequestOptions (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/node_modules/node-fetch/lib/index.js:1299:9)
>     at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/node_modules/node-fetch/lib/index.js:1404:19
>     at new Promise (<anonymous>)
>     at Function.fetch [as default] (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/node_modules/node-fetch/lib/index.js:1401:9)
>     at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:237:62
>     at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
>     at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
>     at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:27:71
>     at new Promise (<anonymous>)
>     at __awaiter (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:23:12)
> ```
> 
> I think this isn't solved. =/

Looks like this is related to contact sharing message. My bad, sorry.

**Comment by kaykyr** [comment]
> There are another error also:
> 
> ```shell
> (node:9356) UnhandledPromiseRejectionWarning: Error: Empty buffer returned. File has possibly been deleted from WA servers. Run `client.updateMediaMessage()` to refresh the url
>     at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:244:31
>     at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
>     at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
>     at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:9356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
> ```
> 
> This happens even after restarting script.

Related to this:

```bash
Error: Empty buffer returned. File has possibly been deleted from WA servers. Run `client.updateMediaMessage()` to refresh the url
    at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:244:31
    at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
    at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
    at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Message {
  stickerMessage: StickerMessage {
    url: 'https://mmg.whatsapp.net/d/f/AidxYUQ-GGp37J9lB-_BoVzT5t-g4VVUm0UBPiW73A1p.enc',
    fileSha256: <Buffer e9 fa 1c 4e fb 93 a1 13 2b db 1f c6 db 55 64 37 ea 44 0f 51 eb b0 61 8a 87 f1 3a 07 ed 02 1d 1d>,
    fileEncSha256: <Buffer 1a 79 a7 7c 32 92 2f bc 42 b9 86 22 ce 21 f2 cb 92 5e 0c 0c dd dd ef 53 41 1e a2 5c 3c 5b e9 7f>,
    mediaKey: <Buffer c7 32 7c 04 fe 4c 2a 8f 3f f1 df 7b 1f a6 24 d3 25 9d 73 a1 b3 6d db 92 74 84 a8 da c3 28 63 20>,
    mimetype: 'image/webp',
    height: 512,
    width: 512,
    directPath: '/v/t62.15575-24/28910913_2686578494950979_4730591050054990471_n.enc?oh=b897601607819928bf87e562e62d463a&oe=BF27B26F',
    fileLength: Long { low: 72480, high: 0, unsigned: true },
    mediaKeyTimestamp: Long { low: 1593389308, high: 0, unsigned: false }
  }
}
```

**Comment by kaykyr** [comment]
Looks like we're unable to decode sticker messages.

**Comment by kaykyr** [comment]
> > There are another error also:
> > ```shell
> > (node:9356) UnhandledPromiseRejectionWarning: Error: Empty buffer returned. File has possibly been deleted from WA servers. Run `client.updateMediaMessage()` to refresh the url
> >     at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:244:31
> >     at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
> >     at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
> >     at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
> >     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > (node:9356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
> > ```
> > 
> > 
> > This happens even after restarting script.
> 
> Related to this:
> 
> ```shell
> Error: Empty buffer returned. File has possibly been deleted from WA servers. Run `client.updateMediaMessage()` to refresh the url
>     at /Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:244:31
>     at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:52:23)
>     at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:33:53)
>     at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/Baileys/lib/WAClient/Utils.js:24:58)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> Message {
>   stickerMessage: StickerMessage {
>     url: 'https://mmg.whatsapp.net/d/f/AidxYUQ-GGp37J9lB-_BoVzT5t-g4VVUm0UBPiW73A1p.enc',
>     fileSha256: <Buffer e9 fa 1c 4e fb 93 a1 13 2b db 1f c6 db 55 64 37 ea 44 0f 51 eb b0 61 8a 87 f1 3a 07 ed 02 1d 1d>,
>     fileEncSha256: <Buffer 1a 79 a7 7c 32 92 2f bc 42 b9 86 22 ce 21 f2 cb 92 5e 0c 0c dd dd ef 53 41 1e a2 5c 3c 5b e9 7f>,
>     mediaKey: <Buffer c7 32 7c 04 fe 4c 2a 8f 3f f1 df 7b 1f a6 24 d3 25 9d 73 a1 b3 6d db 92 74 84 a8 da c3 28 63 20>,
>     mimetype: 'image/webp',
>     height: 512,
>     width: 512,
>     directPath: '/v/t62.15575-24/28910913_2686578494950979_4730591050054990471_n.enc?oh=b897601607819928bf87e562e62d463a&oe=BF27B26F',
>     fileLength: Long { low: 72480, high: 0, unsigned: true },
>     mediaKeyTimestamp: Long { low: 1593389308, high: 0, unsigned: false }
>   }
> }
> ```

About this issue:
![Screen Shot 2020-07-20 at 22 08 23](https://user-images.githubusercontent.com/30188217/88001061-92ebe780-cad5-11ea-8054-0f2322ea432d.png)

Looks like this happens when WhatsApp Web shows a download button. There are a way to force this download through WhatsApp Web Socket?

It could be like this:
1 - Try download file
2 - Catch Fails:
3 - Force download

**Comment by adiwajshing** [comment]
Well, the error is exactly what it says it is. The file gets deleted from the WA servers after a while. You'll have to refresh the media url. You can do that using:

``` ts

const myMessage: WAMessage = // your media message
try {
  await decodeMediaMessage (myMessage, 'downloaded_file')
} catch (err) {
  if (err.toString().includes('deleted')) {
    await client.updateMediaMessage (myMessage) // will refresh the media url
    await decodeMediaMessage (myMessage,  'downloaded_file') // decode now
  } 
}

```

**Comment by kaykyr** [comment]
> Well, the error is exactly what it says it is. The file gets deleted from the WA servers after a while. You'll have to refresh the media url. You can do that using:
> 
> ```ts
> const myMessage: WAMessage = // your media message
> try {
>   await decodeMediaMessage (myMessage, 'downloaded_file')
> } catch (err) {
>   if (err.toString().includes('deleted')) {
>     await client.updateMediaMessage (myMessage) // will refresh the media url
>     await decodeMediaMessage (myMessage,  'downloaded_file') // decode now
>   } 
> }
> ```

Thanks! This worked!

**Comment by felangga** [comment]
I'm getting this error also when sending image / video

> TypeError: Only absolute URLs are supported 

After checking up, there is no url key on event chat-update
