### ISSUE TITLE
[MD] Crash in chat-utils.ts -> computeLtHash() . Results in no more messages being received

### ISSUE THREAD

**Issue by burstfreeze** [adiwajshing/Baileys#776]
One session just broke down on me, seconds after connecting.

`{"level":10,"time":1635691518436,"pid":1747,"hostname":"-","msgId":"d.e-3","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"d.e-3"},"content":[{"tag":"sync","attrs":{},"content":[{"tag":"collection","attrs":{"name":"critical_unblock_low"},"content":[{"tag":"patches","attrs":{},"content":[{"tag":"patch","attrs":{},"content":{"type":"Buffer","data":[-LIKE 1000 BYTES-]}}]}]}]}]},"msg":"communication"}`

```
/Users/B/Documents/Baileys/src/Utils/chat-utils.ts:61
                throw new Boom('')
                      ^
Boom [Error]
    at computeLtHash (/Users/B/Documents/Baileys/src/Utils/chat-utils.ts:61:23)
    at Object.decodePatches (/Users/B/Documents/Baileys/src/Utils/chat-utils.ts:278:19)
    at resyncState (/Users/B/Documents/Baileys/src/Socket/chats.ts:453:57)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  output: {}
}
```

This does not seem to be the same behavior as #744. It may be linked to #751 since after that occurred, restarting did not cause any more messages to be received.

**Comment by TentacleSama4254** [comment]
may i cask how to catch this error

**Comment by adiwajshing** [comment]
I can confirm that sometimes the connection gets broken, however, I'm not a 100% certain that the LT hash error is the cause. Still debugging tho

**Comment by burstfreeze** [comment]
I only had this occur 2 times now, cannot say for sure the session wasn't broken bfore or a bit after.

Thank you for your recent commit on this so we can see more context. Will report back

**Comment by canove** [comment]
@adiwajshing , I don't know if it helps, but after updating with new LT hash logs:

```
[1636302096636] ERROR: failed to sync state
    trace: "Error: failed to verify LTHash at 1\n    at Object.decodePatches (/wpp-md-microservice/dist/libs/baileys-md/lib/Utils/chat-utils.js:261:23)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async resyncState (/wpp-md-microservice/dist/libs/baileys-md/lib/Socket/chats.js:364:51)"
    node: {
      "tag": "notification",
      "attrs": {
        "from": "@s.whatsapp.net",
        "type": "server_sync",
        "id": "607553149",
        "t": "1636302095"
      },
      "content": [
        {
          "tag": "collection",
          "attrs": {
            "name": "critical_unblock_low",
            "version": "3"
          },
          "content": null
        }
      ]
    }
```

I've noticed that the received message that throws this erro wasn't acked (sender phone didn't get the blue checks)

My session keeps working fine after this, and subsequente messages ware acked correctly 
![image](https://user-images.githubusercontent.com/24817866/140653404-8e87aa42-4a85-4520-8ec6-c26243fb7989.png)

**Comment by adiwajshing** [comment]
So the LT hash issue does not lead to no more messages being received. However, the issue itself should be resolved [here](https://github.com/adiwajshing/Baileys/pull/696/commits/ba453a588be05825b76d90632e8876ad43d7c8c9)

Feel free to reopen if not fixed.
