### ISSUE TITLE
How to create QR code in website

### ISSUE THREAD

**Issue by Xmell91** [adiwajshing/Baileys#777]
i hope baileys can help me

**Comment by erickythierry** [comment]
you need to create a basic script just to generate a qr and save the auth.json file. then you can integrate this code into some web app (like a simple app in express.js)

**Comment by diosamuel** [comment]
please don't open issues that are not specifically related to Baileys. if you want to create qrcode, try to search qrcode library in npm and learn abt nodejs framework like Express.js or Adonis.js
