### ISSUE TITLE
[Multi-device] Whatsapp bans numbers

### ISSUE THREAD

**Issue by Sserpske** [adiwajshing/Baileys#779]
**Describe the bug**
I have been developing an App using this library for about 2 weeks. But since Friday, WhatsApp started banning my test numbers that I was connecting. I tried different devices, different networks and about 5-6 numbers. All of them are banned after the first message written from my app.  
I also checked it with the example from the library, the number is also banned.

**To Reproduce**
1. Just run example.ts
2. Scan the qr-code
3. Write a message to WhatsApp, which was connected
4. In response should come the message 'Hello there!'
5. After that the number is banned

**Expected behavior**  
Until Friday (October 29) I had not been banned for 2 weeks. Expect no ban.  

**Environment (please complete the following information):**
Running locally, not on the server.  
I tried different options to connect, for example this  
```
{
    logger: logger({ level: 'trace' }),
    auth: loadState(),
}

```   
or this  

```
{
    logger: P({ level: 'trace' }), 
    auth: authState,
    browser: ['Windows', 'Google Chrome', '90'],
    version: [2, 2142, 12],
}
```

I have one client per IP  
I don't use proxies

**Comment by erickythierry** [comment]
occurred to me once when using a newly registered virtual number. however when using a personal secondary number, I didn't have this problem

**Comment by Kauefranca** [comment]
Try to wait 2-3 days after you register the number for starting, It worked for me.

**Comment by Sserpske** [comment]
Thanks for the tips. They partially solved my problem
