### ISSUE TITLE
[BUG] connect attempt 2 failed: Error: close, retrying...   

### ISSUE THREAD

**Issue by Caliph91** [adiwajshing/Baileys#781]
![Screenshot_20211102-070608_Termius](https://user-images.githubusercontent.com/92326690/139758527-ef9056dd-07f3-4fa8-ab12-fc7e6169ebdd.jpg)

**Comment by xxxmike3** [comment]
whatsapp changed again the qrcode generator, need change some variable to run again, but i don't know, waiting for help also kkakkkk

**Comment by rafaeljustinox** [comment]
@Caliph91 , did you solve the problem? I'm facing the same here

**Comment by arisawali2014** [comment]
change connection version

**Comment by muhammadsaddamnur** [comment]
how to solve this case?

**Comment by xxxmike3** [comment]
Solution: 

access the file in
./node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js and edit the contents and search for
this.version = [X, XXXX, XX];

change for version to

 const conn = new WAConnection();
conn.version = [3, 3234, 9];              <<<  here

**Comment by JuniorRibas** [comment]
here the same problem.

I changed the version to [3, 3234, 9]
But the problem persists!
:-(

> Solution:
> 
> access the file in ./node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js and edit the contents and search for this.version = [X, XXXX, XX];
> 
> change for version to
> 
> const conn = new WAConnection(); conn.version = [3, 3234, 9]; <<< here

here the same problem.

I changed the version to [3, 3234, 9]
But the problem persists!
:-(
