### ISSUE TITLE
[BUG] error qr

### ISSUE THREAD

**Issue by amiruldev20** [adiwajshing/Baileys#782]
error scan qr & run session

**Comment by amiruldev20** [comment]
****WARN [2021-11-02 01:40:21.749 +0000] (9632): connect attempt 2 failed: Error: close, retrying...
    class: "Baileys"
    error: {}

**Comment by rafaeljustinox** [comment]
I'm facing this same issue. I was testing another lib (https://www.npmjs.com/package/whatsapp-web.js) and this another one is working. I saw that it's QR Code now has more information then the one from this project.

**whatsapp-web.js** is something like:
1@TvIujina/7mNopcZVDBycJNr7gGU+Dk+uLBjGekXhq5IETSM4D+XxFel+DS7LbFoCnvYqc4QIPm7wg==,ljQ6PH9EEgaulWzfrsiTwFjZTTPm7ur/mtIndmlVozU=, uP8PwxU7abNAbtagZs/qbg==

and **this project** is something like:
,7b2pSGmR7UkC7Wv2sIpkpQNU7emjpptDPLPN3IOUW0g=,UPnh//F2EXEO6sH+msQIQQ==

**Comment by SrFortes** [comment]
probably whatsapp is updating their server with multi device, because the symptom the same like that

**Comment by rafaeljustinox** [comment]
I have solved. Just define the [3, 3234, 9] version for the instance.
I solved with this:

const conn = new WAConnection();
conn.version = [3, 3234, 9];

PS: I'm on the Discord server that I found on the documentation in README.md and founded this solution there. It works!

**Comment by SrFortes** [comment]
> I have solved. Just define the [3, 3234, 9] version for the instance. I solved with this:
> 
> const conn = new WAConnection(); conn.version = [3, 3234, 9];
> 
> PS: I'm on the Discord server that I found on the documentation in README.md and founded this solution there. It works!

ok, here it works too!! nice!! Brazil

**Comment by frmdeveloper** [comment]
Thanks

**Comment by Mr7Gabriel** [comment]
For this Problem can be changed to Higher Version located at: ./node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js and edit the contents and search for `this.version = [X, XXXX, XX];`  replace with
`"2, 2142, 12"` or higher

**Comment by diveshahuja** [comment]
Its not scanning even after changing the version code and even i tried changing the browsers(in Utils files), its not scanning

**Comment by SrFortes** [comment]
> Its not scanning even after changing the version code and even i tried changing the browsers(in Utils files), its not scanning

restart your server node ? 

tried to change this version?
const conn = new WAConnection();
conn.version = [3, 3234, 9];

**Comment by diveshahuja** [comment]
yes i restarted several times and even rebooted the server and tried the version you have mentioned , its not scannig

**Comment by SrFortes** [comment]
> yes i restarted several times and even rebooted the server and tried the version you have mentioned , its not scannig

try to exit whatsapp beta if using, mine wouldn't scan because it was in whatsapp beta!

**Comment by diveshahuja** [comment]
No, its not on beta, i tried changing the server but it didn't worked

**Comment by diveshahuja** [comment]
Issue solved after downgrading node js version to 14

**Comment by amiruldev20** [comment]
const conn = new WAConnection();
conn.version = [3, 3234, 9];

its work

**Comment by PurpShell** [comment]
> For this Problem can be changed to Higher Version located at: ./node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js and edit the contents and search for 
> `this.version = [X, XXXX, XX];`  replace with
> `"2, 2142, 12"` or higher
> 
> Note: It is possible that something else will go wrong if it is replaced

I highly highly discourage this

**Comment by PurpShell** [comment]
> 
> 
> > yes i restarted several times and even rebooted the server and tried the version you have mentioned , its not scannig
> 
> try to exit whatsapp beta if using, mine wouldn't scan because it was in whatsapp beta!

Use baileys-md

**Comment by JoseCarlos056** [comment]
> > > yes i restarted several times and even rebooted the server and tried the version you have mentioned , its not scannig
> > 
> > 
> > try to exit whatsapp beta if using, mine wouldn't scan because it was in whatsapp beta!
> 
> Use baileys-md


you can explain better?

**Comment by JuniorRibas** [comment]
here the same problem.

I changed the version to [3, 3234, 9]
But the problem persists!
:-(

**Comment by Mr7Gabriel** [comment]
> here the same problem.
> 
> I changed the version to [3, 3234, 9] But the problem persists! :-(

What version did you use before?

**Comment by JuniorRibas** [comment]
> > here the same problem.
> > I changed the version to [3, 3234, 9] But the problem persists! :-(
> 
> What version did you use before?

this [2, 2142, 12]

**Comment by Mr7Gabriel** [comment]
> > > here the same problem.
> > > I changed the version to [3, 3234, 9] But the problem persists! :-(
> > 
> > 
> > What version did you use before?
> 
> this [2, 2142, 12]

Hmm, the version you were using before doesn't need to be changed, but seeing that versions `[3, 3234, 9]` don't work either, you should create a new report that opens so that can help.
