### ISSUE TITLE
[BUG] Send List Message

### ISSUE THREAD

**Issue by deri387** [adiwajshing/Baileys#786]
I get the error when i tried to send list message.
(node:24645) UnhandledPromiseRejectionWarning: BaileysError: Unexpected status in 'action': Bad Request(400)

Thanks.

**Comment by FaizBastomi** [comment]
Are you using WhatsApp business or normal?
Have you checked in your code there is an error?

if you believe this is completely an error from the Baileys lib, please send us the full debugging log.
