### ISSUE TITLE
Is Baileys able to send songs with a message button?

### ISSUE THREAD

**Issue by Rizxyu** [adiwajshing/Baileys#787]

**Comment by adiwajshing** [comment]
Use discord for questions. Do not open an issue

**Comment by Rizxyu** [comment]
> Use discord for questions. Do not open an issue

Link server discord for questions

**Comment by burstfreeze** [comment]
You really cannot miss it, it's literally in the first paragraph of the readme.

![image](https://user-images.githubusercontent.com/87532537/141680615-739bf2ea-f124-47ed-a405-3ea27cccb664.png)
