### ISSUE TITLE
Change group picture

### ISSUE THREAD

**Issue by moskoweb** [adiwajshing/Baileys#788]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
Feature that allows you to update the image of a group, as well as it is possible to change the description and settings, it would be interesting to be able to change the image of the group through the URL of an image.

**Comment by adiwajshing** [comment]
You've obviously not read the readme, closing.
