### ISSUE TITLE
[BUG] Lost all connections and cant reconnect

### ISSUE THREAD

**Issue by drauber** [adiwajshing/Baileys#789]
Yesterday all my number connected with Baileys lost the connection. 
And i can't reconnect anyone. 

**To Reproduce**
Try read a qrcode generated by baileys server, whatsapp on phone ignoring it.

**Expected behavior**
Make a new connection and create auth_info.json

**Comment by drauber** [comment]
I have changed the conneciton "conn.version = [2, 2140, 12];" and it works again.

Is there a way to not need change this and automatic always use the last version?

**Comment by ineward** [comment]
I have the same problem but I don't have a solution for it yet

**Comment by drauber** [comment]
@ineward you need to change the conn.version in connection options.
`
    const conn = new WAConnection(); // instantiate
    conn.version = [2, 2140, 12];

    conn.autoReconnect = ReconnectMode.onConnectionLost; // only automatically reconnect when the connection breaks
`
But i seems this is not the best solution.

**Comment by jefaokpta** [comment]
> @ineward you need to change the conn.version in connection options.
> 
> ```
> const conn = new WAConnection();
> conn.version = [2, 2140, 12];
> conn.autoReconnect = ReconnectMode.onConnectionLost;
> ```
> 
> But i seems this is not the best solution.

This solved to me too buddy thanks for share.

**Comment by josco007** [comment]
Thanks I had the same problem but with this fix now is working.

I have a question. how do you know the correct version?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by harshmakani1** [comment]
Try to get new 0.base file from wa.connection

**Comment by harshmakani1** [comment]
https://github.com/adiwajshing/Baileys/blob/master/src/WAConnection/0.Base.ts

**Comment by jefaokpta** [comment]
> Thanks I had the same problem but with this fix now is working. I have a question. how do you know the correct version? Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)

Load some WhatsApp Web -> Settings -> Help.
Then you'll get something like this:
<img width="425" alt="Screen Shot 2021-11-03 at 18 20 39" src="https://user-images.githubusercontent.com/10830832/140194634-fd916412-2113-46c3-ac47-bbb8750716d5.png">

**Comment by halowahyudi** [comment]
Than

> I have changed the conneciton "conn.version = [2, 2140, 12];" and it works again.
> 
> Is there a way to not need change this and automatic always use the last version?

Thanksss

> @ineward you need to change the conn.version in connection options.
> 
> ```
> const conn = new WAConnection();
> conn.version = [2, 2140, 12];
> conn.autoReconnect = ReconnectMode.onConnectionLost;
> ```
> 
> But i seems this is not the best solution.

Its Work. Thanks
