### ISSUE TITLE
How to get contact presence update of unsaved contacts like WhatsLog app.

### ISSUE THREAD

**Issue by ManjitPardeshi** [adiwajshing/Baileys#79]
Hello guys can you help me to get the online presence of unsaved contacts just like the app WhatsLog does. I have tried to reverse-engineer that app and I came to know that it uses a rest api. Can anyone of you please suggest me what is the underlying technology behind that rest-api?? I want this for my data-science project..
Someone please help me...
@adiwajshing

**Comment by adiwajshing** [comment]
Veere, eh try kari:

``` ts
const client = new WAClient ()
await client.connectSlim ()

const interval = setInterval(() => client.updatePresence(null, Presence.available), 10000) // say you're available
// is called whenever someone you have a chat with comes online, goes offline or is typing
client.setOnPresenceUpdate ((json: PresenceUpdate) => console.log(json.id + " presence is " + json.type)) 
```

Lemme know if this works, might require some adjustments.

**Comment by Manjit2003** [comment]
But how can I get the presence of unsaved or non-chat accounts? @adiwajshing

**Comment by adiwajshing** [comment]
This will do unsaved contacts -- but non-chat accounts is not possible.

**Comment by Manjit2003** [comment]
@adiwajshing So any guess on how that service must be working? It gives accurate timing of online and offline status...

**Comment by adiwajshing** [comment]
Nope, I haven't looked into it

**Comment by Manjit2003** [comment]
How does the Rhymen/go-whatsapp library is able to get presence of other contacts

answer : https://github.com/Rhymen/go-whatsapp/issues/416#issuecomment-663802433

**Comment by adiwajshing** [comment]
Both libraries use the same API -- there isn't going to be much of a difference. They've given you the same code I sent you. However, in my experience it doesn't work with unknown contacts.
