### ISSUE TITLE
Enable Discussion Tab

### ISSUE THREAD

**Issue by ekoeryanto** [adiwajshing/Baileys#791]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**
Hello, @adiwajshing I think it's better to enable discussion in this repo, thanks.

**Comment by azudindaem** [comment]
Please join [discord](https://discord.gg/7FYURJyqng)
