### ISSUE TITLE
[Multi-device] Waiting for this message. Check your phone.

### ISSUE THREAD

**Issue by xbassols** [adiwajshing/Baileys#793]
Whenever I send a message via this library I receive the message on my regular phone just fine but on my computer client using the official client and my regular phone connected also with multi device enabled I receive:

Waiting for this message. Check your phone. [Learn more](https://faq.whatsapp.com/general/security-and-privacy/seeing-waiting-for-this-message-check-your-phone?lang=en)

Is this considered normal behaviour and I need to implement some kind of resend for the web client version or is it an issue with the library?

If I send a message directly from the "API phone" to my regular phone it does work.

**Comment by Luxemburgo** [comment]
Same here ☝️

**Comment by adiwajshing** [comment]
This is some bug on WA's side -- I've reproduced it too, cannot do much about it. This happens when using official clients as well
