### ISSUE TITLE
[Multi Device] Get all Chats Jids

### ISSUE THREAD

**Issue by Luxemburgo** [adiwajshing/Baileys#794]
Hi! Anyone figured out how to get the Jids of the started chats in Baileys-Md?

Thanks!

**Comment by PurpShell** [comment]
socket.chats?

**Comment by PurpShell** [comment]
you should have your own handlers, in my case I save to the same json and then laod

**Comment by Luxemburgo** [comment]
Can you give me an example? I'm having difficulties to understand what messages I had to handle to achive this goal. 

Thank you

**Comment by Luxemburgo** [comment]
My ultimate goal is to know what chats are already active to avoid  to check every time for the WhatsApp Id (onWhatsApp function) before send a new message
