### ISSUE TITLE
Question about ButtonMessage

### ISSUE THREAD

**Issue by SL-Alpha-X** [adiwajshing/Baileys#795]
How to send buttonMessage with image 😐

**Comment by Zobin33** [comment]
> **How to send buttonMessage with image 😐**

Seed documentation, why u dont read it?

**Comment by SL-Alpha-X** [comment]
Please send me link

**Comment by SL-Alpha-X** [comment]
Plzzzzzzzzzzzzzzzz😿

**Comment by azudindaem** [comment]
// send a buttons message!
const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1}
]

const buttonMessage = {
    contentText: "Hi it's button message",
    footerText: 'Hello World',
    buttons: buttons,
    headerType: 1
}

const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)

**Comment by SL-Alpha-X** [comment]
Thanks, i know that but i want to know how to send it with icture

**Comment by SL-Alpha-X** [comment]
> // send a buttons message! const buttons = [ {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1}, {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1} ]
> 
> const buttonMessage = { contentText: "Hi it's button message", footerText: 'Hello World', buttons: buttons, headerType: 1 }
> 
> const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)

Thanks, i know that but i want to know how to send it with picture 😣

**Comment by azudindaem** [comment]
```
var content = fs.readFileSync(localfile-path-here);
var description = params.description;
var media = await conn.prepareMessageMedia(content, MessageType.image); // change for file type
var type = 4;
var buttonMessage = { 
    contentText: description, 
    footerText: params.footer, 
    buttons: params.buttons, 
    headerType: type, 
    ...media
    }
await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage);
```

**Comment by SL-Alpha-X** [comment]
> ```
> var content = fs.readFileSync(localfile-path-here);
> var description = params.description;
> var media = await conn.prepareMessageMedia(content, MessageType.image); // change for file type
> var type = 4;
> var buttonMessage = { 
>     contentText: description, 
>     footerText: params.footer, 
>     buttons: params.buttons, 
>     headerType: type, 
>     ...media
>     }
> await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage);
> ```

Thanks a lot bro 😭😋

**Comment by SL-Alpha-X** [comment]
🙂 tnx

**Comment by KAWITHMA** [comment]
> > // send a buttons message! const buttons = [ {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1}, {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1} ]
> > const buttonMessage = { contentText: "Hi it's button message", footerText: 'Hello World', buttons: buttons, headerType: 1 }
> > const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
> 
> Thanks, i know that but i want to know how to send it with picture 😣

Ado bn උබ හදගත්තද බටන් බොට්

**Comment by SL-Alpha-X** [comment]
> > > // send a buttons message! const buttons = [ {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1}, {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1} ]
> > > const buttonMessage = { contentText: "Hi it's button message", footerText: 'Hello World', buttons: buttons, headerType: 1 }
> > > const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
> > 
> > 
> > Thanks, i know that but i want to know how to send it with picture 😣
> 
> Ado bn උබ හදගත්තද බටන් බොට්

Ooo 🙂

**Comment by KAWITHMA** [comment]
> > > > // send a buttons message! const buttons = [ {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1}, {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1} ]
> > > > const buttonMessage = { contentText: "Hi it's button message", footerText: 'Hello World', buttons: buttons, headerType: 1 }
> > > > const sendMsg = await conn.sendMessage(id, buttonMessage, MessageType.buttonsMessage)
> > > 
> > > 
> > > Thanks, i know that but i want to know how to send it with picture 😣
> > 
> > 
> > Ado bn උබ හදගත්තද බටන් බොට්
> 
> Ooo 🙂

Mata udauwak diyam.
Mama button ගැහුවා ඒ වුනාට commond වැඩ නෑ
