### ISSUE TITLE
[BUG] Cannot Receive Message

### ISSUE THREAD

**Issue by AF1298** [adiwajshing/Baileys#796]
Hello sir, @adiwajshing can you help me pls

i had some trouble, when i send message from another contact, in my service didn't get anything, here my part of code : 
![image](https://user-images.githubusercontent.com/48938319/140448097-4bab6338-74d1-4db2-aa33-23d1c0ad2be8.png)

it doesn't print the console log,

beforem i say thank u sir

**Comment by AF1298** [comment]
done

**Comment by TentacleSama4254** [comment]
> done

What was the solution if I may ask
