### ISSUE TITLE
eror scan qr wa busniss v 2.21.21.19 [BUG]

### ISSUE THREAD

**Issue by thaziz** [adiwajshing/Baileys#797]
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined

**Comment by thaziz** [comment]
I did the WhatsApp busnis version 2.21.21.19 update, then I did a scan but there was an error, I'm not using the beta version

**Comment by vicfelipe** [comment]
Same here

**Comment by athasamid** [comment]
same here, any update?

**Comment by akm-akm** [comment]
same here, nothing happening.

**Comment by thaziz** [comment]
> Solved by install stabl-ish `npm install github:adiwajshing/baileys`

still an error, this error if you use the latest whatsapp business

**Comment by athasamid** [comment]
@thaziz i used latest whatsapp business (v2.21.21.19) and it work.

**Comment by thaziz** [comment]
Thanks
