### ISSUE TITLE
[BUG] Baileys Error in Heroku

### ISSUE THREAD

**Issue by MohammedRoshanT** [adiwajshing/Baileys#798]
I have  deployed whatsapp bot to Heroku. It was fine until October 31. 
Now it is showing Error. Please fix this, this bug made the all bots stop
>
![Screenshot_20211105-093908](https://user-images.githubusercontent.com/70361124/140463793-b5959c54-d025-4b64-b9f6-cee44bb58c7f.png)

**Comment by MohammedRoshanT** [comment]
Or please tell th solution

**Comment by lyfe00011** [comment]
> Or please tell the solution

#792

**Comment by MohammedRoshanT** [comment]
PLEASE  REPLY ASAP!

**Comment by frmdeveloper** [comment]
> PLEASE REPLY ASAP!

See #792
