### ISSUE TITLE
sendTextMessage returns promise resolve after 10-20 seconds

### ISSUE THREAD

**Issue by keef3ar** [adiwajshing/Baileys#8]
sendTextMessage returns promise resolve after 10-20 seconds
Message goes almost instantly(saw it in app on phone), but promise resolves very slow.
Any ideas?

**Comment by adiwajshing** [comment]
That's really odd. It returns it instantaneously on my phone. I'll test it out again. 

However, can you write a small script to test this bug out? That'll be a help in debugging it

**Comment by keef3ar** [comment]
Message comes instantaneously, only promise resolving is slowly. I will check it and send sample of code
`   static async sendText(msg) {
    console.time("sending");
    const response = await client.sendTextMessage(msg.wh_id, msg.body);
    console.timeEnd("sending");
    return response;
  }
`
Checked it right now, and get 17 seconds.

**Comment by adiwajshing** [comment]
This should be fixed in the latest version, do check it out.
