### ISSUE TITLE
[MD] QR code update only fires once

### ISSUE THREAD

**Issue by burstfreeze** [adiwajshing/Baileys#800]
The website refreshes the code every 25 seconds.

Can we make the same happen in Baileys?

**Comment by AF1298** [comment]
it should be setup on this part
![image](https://user-images.githubusercontent.com/48938319/140488882-6c644729-a9f3-4fca-ae5e-f7b85ca7bb1d.png)

but, idk when customize this part, there is nothing happened

**Comment by dinnos** [comment]
Some updates on this issue?

**Comment by burstfreeze** [comment]
The following will help you but it's a bit ugly, hoping for adi to make it clean some time.

```
const postQR = async(qr) => {
...
        (async() => {
            for (const index in refs) {
        
                const qr = [refs[index], noiseKeyB64, identityKeyB64, advB64].join(',');

                ev.emit('connection.update', { qr })
                await postQR(qr)
            
                await new Promise (resolve => setTimeout(resolve, connectTimeoutMs))
            }
        })()
```

**Comment by adiwajshing** [comment]
Was added in: https://github.com/adiwajshing/Baileys/pull/696/commits/bbf5bc96cca79bc31f8dd1aac4a5d54f49225e07
