### ISSUE TITLE
Error after scan qrcode on iPhone

### ISSUE THREAD

**Issue by ahmadun** [adiwajshing/Baileys#802]
After scan qrcode from iPhone, the error occurred.

But on android its run smothly.

**Comment by iM0hamed** [comment]
INFO [2021-11-05 15:12:56.088 +0000] (942414): validated connection successfully
    class: "Baileys"
(node:942414) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined

**Comment by ahmadun** [comment]
> INFO [2021-11-05 15:12:56.088 +0000] (942414): validated connection successfully class: "Baileys" (node:942414) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined

Yess, the detail error like this

**Comment by azudindaem** [comment]
Please your iphone make sure its not MD

**Comment by poseidonwood** [comment]
im same with it , not join in MD , but can scan qrcode , i dont know what happen
