### ISSUE TITLE
[BUG] received odd group ID

### ISSUE THREAD

**Issue by AkirahX** [adiwajshing/Baileys#805]
Hi, I'm getting this error only in newly created groups, in old groups no error happens.

`WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID
    gid: "120363039905510325@g.us"
    class: "Baileys"`

The ID's of the new groups are different from the old ones

New: 120363039905510325@g.us

Old: 15753320750-1633539600@g.us

baileys does not accept this ID, so no scripts work on it.

**Comment by viniciusgdr** [comment]
Yes, it was happening to me. In my pull I sent the correction, look there > [Click here](https://github.com/adiwajshing/Baileys/pull/804)

**Comment by AkirahX** [comment]
> Yes, it was happening to me. In my pull I sent the correction, look there > [Click here](https://github.com/adiwajshing/Baileys/pull/804)
https://chat.whatsapp.com/EM7Ne5Cpjru0yX6DcoduRM

**Comment by azudindaem** [comment]
Adi has merged last night.. check this out

https://github.com/adiwajshing/Baileys/pull/804

**Comment by viniciusgdr** [comment]
> Adi has merged last night.. check this out
> 
> #804
Not yet, approval is missing.

**Comment by azudindaem** [comment]
he remove the checking

**Comment by Millena543** [comment]
> Olá, estou recebendo este erro apenas em grupos recém-criados, em grupos antigos nenhum erro acontece.
> 
> `WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID gid: "120363039905510325@g.us" class: "Baileys"`
> 
> Os IDs dos novos grupos são diferentes dos antigos
> 
> Novo: [120363039905510325@g.us](mailto:120363039905510325@g.us)
> 
> Antigo: [15753320750-1633539600@g.us](mailto:15753320750-1633539600@g.us)
> 
> baileys não aceita este ID, então nenhum script funciona nele.

Conseguiu resolver?

**Comment by Millena543** [comment]
> Hi, I'm getting this error only in newly created groups, in old groups no error happens.
> 
> `WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID gid: "120363039905510325@g.us" class: "Baileys"`
> 
> The ID's of the new groups are different from the old ones
> 
> New: [120363039905510325@g.us](mailto:120363039905510325@g.us)
> 
> Old: [15753320750-1633539600@g.us](mailto:15753320750-1633539600@g.us)
> 
> baileys does not accept this ID, so no scripts work on it.

Managed to solve?

**Comment by AkirahX** [comment]
> > Hi, I'm getting this error only in newly created groups, in old groups no error happens.
> > `WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID gid: "120363039905510325@g.us" class: "Baileys"`
> > The ID's of the new groups are different from the old ones
> > New: [120363039905510325@g.us](mailto:120363039905510325@g.us)
> > Old: [15753320750-1633539600@g.us](mailto:15753320750-1633539600@g.us)
> > baileys does not accept this ID, so no scripts work on it.
> 
> Managed to solve?

Yes (temporary), modify this on WAconnection/4.events.js


Original: 

```javascript
if(isGroupID(jid) && !jid.includes('-'))
```

Modifield: 

```javascript
if(isGroupID(jid) && !jid.includes('@g.us' || '-'))
```
temporary solution until merge the pull request

**Comment by Millena543** [comment]
> > > Hi, I'm getting this error only in newly created groups, in old groups no error happens.
> > > `WARN [2021-11-07 14:32:55.910 +0000] (4150): recieved odd group ID gid: "120363039905510325@g.us" class: "Baileys"`
> > > The ID's of the new groups are different from the old ones
> > > New: [120363039905510325@g.us](mailto:120363039905510325@g.us)
> > > Old: [15753320750-1633539600@g.us](mailto:15753320750-1633539600@g.us)
> > > baileys does not accept this ID, so no scripts work on it.
> > 
> > 
> > Managed to solve?
> 
> Yes (temporary), modify this on WAconnection/4.events.js
> 
> Original:
> 
> ```js
> if(isGroupID(jid) && !jid.includes('-'))
> ```
> 
> Modifield:
> 
> ```js
> if(isGroupID(jid) && !jid.includes('@g.us' || '-'))
> ```
> 
> temporary solution until merge the pull request

Thanks

**Comment by AkirahX** [comment]
Solved!
