### ISSUE TITLE
BUG in QRCode [BUG]

### ISSUE THREAD

**Issue by jeanccoelho** [adiwajshing/Baileys#806]
Solution

update Version and browser Details In "WAConnection \ Validation" func authenticate

`           const { ref, ttl } = await this.query({
                json: ['admin', 'init', [2,2142,12],["Mac OS","Chrome","10.15.7"], (_a = this.authInfo) === null || _a === void 0 ? void 0 : _a.clientID, true],
                expect200: true,
                waitForOpen: false,
                longTag: true,
                requiresPhoneConnection: false,
                startDebouncedTimeout: true
            });
 `

**Comment by ngadimin51** [comment]
still cannot connected
