### ISSUE TITLE
[MD] Issue after recent commits: Error: failed to find key "AAAAAB2j" to decode mutation

### ISSUE THREAD

**Issue by azudindaem** [adiwajshing/Baileys#808]
New error after using latest commit

{"level":30,"time":1636368107963,"pid":7532,"hostname":"localhost","class":"baileys","msg":"recv all pending notifications"}
============================Connection Update============================
Connection Update { receivedPendingNotifications: true } 26
Error: failed to find key "AAAAAB2j" to decode mutation
    at decodePatches (/home/webapps/md/node_modules/@adiwajshing/baileys-md/lib/Utils/chat-utils.js:275:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resyncAppState (/home/webapps/md/node_modules/@adiwajshing/baileys-md/lib/Socket/chats.js:180:59) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by burstfreeze** [comment]
I also had that with an older commit, may not be entirely related to the most recent commits. For me it was a chat being pinned but I lost the session before I could open an issue.

If this only happens with pins, I would suggest not breaking the connection based on that

**Comment by azudindaem** [comment]
i see. it just happen when i update to the latest commit just now..

**Comment by burstfreeze** [comment]
Ok update - it just happened to me after scanning the code. Will try again with a clean fork but indeed appears to be an issue.

**Comment by burstfreeze** [comment]
Also happens with a clean fork. @azudindaem please change the empty title of the issue to something like

`Issue after recent commits: Error: failed to find key "AAAAAB2j" to decode mutation`

**Comment by canove** [comment]
Same here.

It just occur on first connection (right after reading QR). 

``` 
[1636372000947] INFO: requesting account sync
    fromTimestamp: "1636372000"
(node:69858) UnhandledPromiseRejectionWarning: Error: failed to find key "AAAAAA8U" to decode mutation
    at Object.decodePatches (/home/cassio/code_learn/whaticket-closed/wpp-md-microservice/src/libs/baileys-md/lib/Utils/chat-utils.js:275:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at resyncAppState (/home/cassio/code_learn/whaticket-closed/wpp-md-microservice/src/libs/baileys-md/lib/Socket/chats.js:180:59)
```

**Comment by burstfreeze** [comment]
Commit 3c6edde1d61af6619dd0eedefd8e286de4ab0d4d does not have that issue - first log in did not work straight away, second login attempt worked. So it looks like it's only the last commit causing the issue.

**Comment by azudindaem** [comment]
i notice after last commit [5120f1d
](https://github.com/adiwajshing/Baileys/commit/5120f1d1e419c7fadef7b35a04974dbd7c3bb4d8) no error

Testing on
1. clean fork
2. 1 session
3. multiple session

**Comment by keef3ar** [comment]
> i notice after last commit [5120f1d ](https://github.com/adiwajshing/Baileys/commit/5120f1d1e419c7fadef7b35a04974dbd7c3bb4d8) no error
> 
> Testing on
> 
> 1. clean fork
> 2. 1 session
> 3. multiple session

still have the same issue even with latest version

**Comment by ilyaborodin** [comment]
I have the same issue with latest commit too

**Comment by burstfreeze** [comment]
I can confirm it does not break the connection anymore when pinning.

It does give `"msg":"unprocessable update"` however does not break connection and reaches `chats.update` event.

**Comment by adiwajshing** [comment]
The key not found is not an issue to be concerned about. It's alright if the key isn't found on the first or second connection attempt

**Comment by voltYazilim** [comment]
I don't quite understand what the solution is, can you explain? @burstfreeze

**Comment by burstfreeze** [comment]
@voltYazilim 

Since the latest commits I do not see this error anymore. If you see this coming up in a crucial situation (e.g. receiving messages) you can open another issue describing your situation.
