### ISSUE TITLE
[BUG]  button

### ISSUE THREAD

**Issue by cantiir2** [adiwajshing/Baileys#817]
me when adding buttons example 
                    case 'buttons':
                        const buttons = [
                            {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
                            {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
                            {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
                          ]
                          const buttonMessage = {
                              image: {url: 'https://i.ibb.co/JdfQ73m/photo-2021-02-05-10-13-39.jpg'},
                              caption: "Hi it's button message",
                              footerText: 'Hello World',
                              buttons: buttons,
                              headerType: 4
                          }
                        await conn.sendMessage(from, buttonMessage)
                    break

and than got error with

21:27:23 [  ERROR  ] BaileysError: Unexpected status in 'action': Bad Request(400)

what a problem this ?

**Comment by azudindaem** [comment]
are you using MD?

**Comment by cantiir2** [comment]
yeah
