### ISSUE TITLE
[BUG] TS build fails

### ISSUE THREAD

**Issue by SaiSridhar783** [adiwajshing/Baileys#818]
Wrote a project in Typescript. The build fails due to reference error as shown:

![image](https://user-images.githubusercontent.com/58875230/140940821-ce744a93-f834-438b-8992-d30dca4f5545.png)

Using npm and not yarn

**Comment by AlenSaito1** [comment]
set `skipLibCheck` to true in `conmpilerOptions` in your `tsconfig.json`

Reference https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by SaiSridhar783** [comment]
Thanks! It works.
