### ISSUE TITLE
[ MD ] Issue to send OGG files

### ISSUE THREAD

**Issue by frmontini** [adiwajshing/Baileys#819]
I sent this example file:

https://file-examples-com.github.io/uploads/2017/11/file_example_OOG_1MG.ogg

```
let params = {}
params.mimetype = 'audio/ogg'
params.audio = { url: 'https://file-examples-com.github.io/uploads/2017/11/file_example_OOG_1MG.ogg' }
params.ptt = true
await socket.sendMessage('***@s.whatsapp.net', params)
```

Returned data from sendMessage function:

```
{
   "key":{
      "remoteJid":"*****@s.whatsapp.net",
      "fromMe":true,
      "id":"BAE*****"
   },
   "message":{
      "audioMessage":{
         "url":"https://mmg.whatsapp.net/d/f/*****.enc",
         "mimetype":"audio/ogg",
         "fileSha256":"aTky41*****",
         "fileLength":"1089524",
         "seconds":74,
         "ptt":true,
         "mediaKey":"jXa7*****",
         "fileEncSha256":"oJxYA*****"
      }
   },
   "messageTimestamp":"1636486550",
   "status":"PENDING"
}
```

But, when i open my WhatsApp on Android, the audio message is not on chat.
Also, i can download the audio message using Baileys-MD too.

**UPDATE**

The audio message sent from Baileys-MD appears on official WhatsApp Web chat.
Is missing only on WhatsApp for Android.

**Comment by hansputera** [comment]
Same

**Comment by leenasn** [comment]
I am also facing similar issues with messages with buttons. They are missing in the Android Phone, but visible in WhatsApp Web. Any way to fix this?

**Comment by ez-br** [comment]
> let params = {}
> params.mimetype = 'audio/ogg'
> params.audio = { url: 'https://file-examples-com.github.io/uploads/2017/11/file_example_OOG_1MG.ogg' }
> params.ptt = true
> await socket.sendMessage('***@s.whatsapp.net', params)

Use 
params.mimetype = 'audio/ogg; codecs=opus'
it works for me

**Comment by kiaonline** [comment]
> I sent this example file:
> 
> https://file-examples-com.github.io/uploads/2017/11/file_example_OOG_1MG.ogg
> 
> ```
> let params = {}
> params.mimetype = 'audio/ogg'
> params.audio = { url: 'https://file-examples-com.github.io/uploads/2017/11/file_example_OOG_1MG.ogg' }
> params.ptt = true
> await socket.sendMessage('***@s.whatsapp.net', params)
> ```
> 
> Returned data from sendMessage function:
> 
> ```
> {
>    "key":{
>       "remoteJid":"*****@s.whatsapp.net",
>       "fromMe":true,
>       "id":"BAE*****"
>    },
>    "message":{
>       "audioMessage":{
>          "url":"https://mmg.whatsapp.net/d/f/*****.enc",
>          "mimetype":"audio/ogg",
>          "fileSha256":"aTky41*****",
>          "fileLength":"1089524",
>          "seconds":74,
>          "ptt":true,
>          "mediaKey":"jXa7*****",
>          "fileEncSha256":"oJxYA*****"
>       }
>    },
>    "messageTimestamp":"1636486550",
>    "status":"PENDING"
> }
> ```
> 
> But, when i open my WhatsApp on Android, the audio message is not on chat. Also, i can download the audio message using Baileys-MD too.
> 
> **UPDATE**
> 
> The audio message sent from Baileys-MD appears on official WhatsApp Web chat. Is missing only on WhatsApp for Android.

Use
params.mimetype = 'audio/ogg; codecs=opus'
it works for me
