### ISSUE TITLE
[BUG] oadd group id

### ISSUE THREAD

**Issue by amiruldev20** [adiwajshing/Baileys#820]
how to fix WARN [2021-11-07 01:41:59.019 +0000] (2780): recieved read update for unknown chat 120363039091387898@g.us
class: "Baileys"

**Comment by Millena543** [comment]
> how to fix WARN [2021-11-07 01:41:59.019 +0000] (2780): recieved read update for unknown chat [120363039091387898@g.us](mailto:120363039091387898@g.us) class: "Baileys"

Managed to solve?

**Comment by amiruldev20** [comment]
I'm getting this error only in newly created groups, in old groups no error happens.

**Comment by amiruldev20** [comment]
original
if(isGroupID(jid) && !jid.includes('-'))

modified
if(isGroupID(jid) && !jid.includes('@g.us' || '-'))

**Comment by Millena543** [comment]
> original if(isGroupID(jid) && !jid.includes('-'))
> 
> modified if(isGroupID(jid) && !jid.includes('@g.us' || '-'))

Thanks

**Comment by amiruldev20** [comment]
ok
