### ISSUE TITLE
[BUG] MD problem restarting

### ISSUE THREAD

**Issue by voltYazilim** [adiwajshing/Baileys#821]
![image](https://user-images.githubusercontent.com/73412953/141032528-2045d0bc-f82b-4c21-bac4-b0cf2e3c9d63.png)

**I'm facing this problem when I run it again after connecting without making any changes. Can you help me?**
@adiwajshing

**Comment by burstfreeze** [comment]
Use the search feature if your issue has already been posted which indeed it has been.

**Comment by voltYazilim** [comment]
this problem is new for md i guess no source found for solution @burstfreeze
