### ISSUE TITLE
Baileys MD connection error

### ISSUE THREAD

**Issue by AkirahX** [adiwajshing/Baileys#823]
Hi, I get this error every time I scan the QR Code, I've tried several codes, including example.ts, help ;-;

```
{"level":10,"time":1636516673088,"pid":83549,"hostname":"Sapphire","msgId":"3060980563","fromMe":false,"frame":{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"set","id":"3060980563","xmlns":"md"},"content":[{"tag":"pair-success","attrs":{},"content":[{"tag":"platform","attrs":{"name":"android"},"content":null},{"tag":"device-identity","attrs":{},"content":{"type":"Buffer","data":[10,116,10,14,8,160,173,166,172,4,16,191,134,173,140,6,24,1,18,32,123,23,147,232,240,220,173,176,55,181,81,162,158,141,251,144,1,118,122,81,30,19,17,183,144,63,222,60,60,221,99,2,26,64,83,234,220,23,238,77,66,247,90,58,199,52,181,142,47,239,169,221,105,185,123,220,154,36,149,3,212,217,84,251,147,201,87,222,111,46,173,76,172,60,63,36,250,115,80,170,90,118,186,181,43,22,144,230,226,227,156,203,79,205,73,188,91,3,18,32,213,92,194,91,213,171,170,242,15,211,138,142,12,66,35,184,211,24,191,93,85,40,51,145,210,239,103,108,103,253,85,161]}},{"tag":"device","attrs":{"jid":"5511963923790:17@s.whatsapp.net"},"content":null}]}]},"msg":"communication"}
{"level":20,"time":1636516673089,"pid":83549,"hostname":"Sapphire","msg":"pair success recv"}
{"level":20,"time":1636516673178,"pid":83549,"hostname":"Sapphire","msg":"pairing configured successfully"}
{"level":30,"time":1636516673183,"pid":83549,"hostname":"Sapphire","jid":"5511963923790:17@s.whatsapp.net","msg":"registered connection, restart server"}
{"level":30,"time":1636516673187,"pid":83549,"hostname":"Sapphire","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}

```

**Comment by bahtiarp** [comment]
i'm facing the same issue, but as soon the connection close, ctrl+c then restart. this works for me.
but, still waiting the proper solutions.

**Comment by adiwajshing** [comment]
Issue is your connection isn't auto restarting automatically. Please see the code in the example script.

**Comment by bahtiarp** [comment]
> Issue is your connection isn't auto restarting automatically. Please see the code in the example script.

Aha, it works. I didn't see update in the example.ts
thanks @adiwajshing 🙏

**Comment by user3470** [comment]
> Issue is your connection isn't auto restarting automatically. Please see the code in the example script.

After a Few hours I realized the restart function should be awaited. That worked for me

**Comment by Millena543** [comment]
> 

how did you solve the problem? I'm also not able to connect the qr

**Comment by AkirahX** [comment]
> > 
> 
> how did you solve the problem? I'm also not able to connect the qr

See this code: https://github.com/adiwajshing/Baileys/blob/3b756787d498e21cfa0ec4d74ea189fda1e3d8bc/Example/example.ts#L67

If your problem is the same as the one I had, this will solve it.
