### ISSUE TITLE
[BUG] MD won't receive a event on group creation exit or removal

### ISSUE THREAD

**Issue by algoz098** [adiwajshing/Baileys#825]
**Describe the bug**
Create a group on whatsapp web while connected to the same account in baileys MD and it won't throw any message of it while logging every event and in debug mode

**To Reproduce**
1. Create connection with debug
2. Create a group in the phone with same number

**Expected behavior**
Someevent to handle in baileys

**Environment (please complete the following information):**
 - Is this on a server? no
 - What do your `connectOptions` look like?  Example
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Comment by JoseCarlos056** [comment]
What is 'MD'?

**Comment by adiwajshing** [comment]
Should be resolved [here](https://github.com/adiwajshing/Baileys/pull/696/commits/469f3451d266464c85c2ff025a57c64dc6d5998e)

Feel free to reopen if issue persists.
