### ISSUE TITLE
[BUG] Update your library with WhatsApp.

### ISSUE THREAD

**Issue by Harshil-d** [adiwajshing/Baileys#826]
First Update version code in your library from 2 21__ 8 to 2 2141 12
without an updated version, WhatsApp sends some static QRcode and refuses to connect, and after doing that WhatsApp QRcode arrives and the web connection closes. 
then if I scan QRcode its refuse to connect 

Note*
while finding the error I put some debug points that time I made the connection for little time 
maybe it's some extra argument you send after the connection just remember this thing does not take seriously maybe there have some other reasons to not connect.

**Comment by burstfreeze** [comment]
Do not use the master branch anymore. Master is gone.

**Comment by Harshil-d** [comment]
Which branch I can use and
FYI I am used with _**npm I @adiwajshing/baileys**_

**Comment by Harshil-d** [comment]
Well, what branch can I use (there are a lot of branches) and
FYI I installed the library with 'npm I @ adiwajshing / baileys' command.

>

**Comment by Harshil-d** [comment]
Well, which branch can I use (there are a lot of branches) and
FYI I installed the library with 'npm I @ adiwajshing / baileys'.

>

**Comment by BochilGaming** [comment]
> First Update version code in your library from 2 21__ 8 to 2 2141 12 without an updated version, WhatsApp sends some static QRcode and refuses to connect, and after doing that WhatsApp QRcode arrives and the web connection closes. then if I scan QRcode its refuse to connect
> 
> Note* while finding the error I put some debug points that time I made the connection for little time maybe it's some extra argument you send after the connection just remember this thing does not take seriously maybe there have some other reasons to not connect.

*npm install github:adiwajshing/baileys*

**Comment by Harshil-d** [comment]
I get unavailable all the time in the Presence Update event. ( when login number not saved on a phone which online-offline updates I am seeing )
And the listener is available when the user is online but the type in the data is **unavailable** every time.

In short, I am not getting reliable data.

**Comment by Harshil-d** [comment]
thanks

but I get unavailable all the time in the Presence Update event. ( when
login number not saved on a phone which online-offline updates I am seeing )
And the listener is available when the user is online but the type in the
data is **unavailable** every time.

In short, I am not getting reliable data.

**Comment by adiwajshing** [comment]
WA does not give reliable presence updates for people:
1. not in your contacts
2. no chat with them

Moreover, this is unrelated to the original issue which is also fairly vague.

**Comment by Harshil-d** [comment]
It's not your problem WhatsApp updates its data security.
