### ISSUE TITLE
[BUG] [MD] DetectLink is not working.

### ISSUE THREAD

**Issue by alexandrepossebom** [adiwajshing/Baileys#827]
If I send a message with a group link:

```
const from = chat.key.remoteJid;
const link = await client.groupInviteCode(from);

client.sendMessage(from, {
        text: 'https://chat.whatsapp.com/' + link,
        quoted: chat,
        detectLinks: true,
});
```

It's send as txt not as link.

**Comment by adiwajshing** [comment]
This isn't supported on MD yet. WA hasn't added support mate.

**Comment by alexandrepossebom** [comment]
> This isn't supported on MD yet. WA hasn't added support mate.

Thank you for answering!

**Comment by moskoweb** [comment]
Hi, still not possible?

**Comment by textarea** [comment]
@moskoweb for me it is working

`const sentMsg = await sock.sendMessage(
      to,
      { text: message },
      { detectLinks: true }
    );`
