### ISSUE TITLE
Login connecting eror

### ISSUE THREAD

**Issue by raselcomel** [adiwajshing/Baileys#828]
https://github.com/adiwajshing/Baileys/blob/b616cf5aca487ec80d068beedbe3e4d14f0eafca/src/WAConnection/3.Connect.ts#L107

**Comment by shinz-404** [comment]
> https://github.com/adiwajshing/Baileys/blob/b616cf5aca487ec80d068beedbe3e4d14f0eafca/src/WAConnection/3.Connect.ts#L107

![IMG_20211111_070504](https://user-images.githubusercontent.com/83520747/141214073-bcaa61f3-2e33-47d8-a00b-fc37f0cfcc44.jpg)
