### ISSUE TITLE
When is new npm update comming

### ISSUE THREAD

**Issue by SL-Alpha-X** [adiwajshing/Baileys#830]
😦

**Comment by SL-Alpha-X** [comment]
😦

**Comment by AkirahX** [comment]
Once it's stable, use the versions directly from github if you want the latest updates.

Baileys:
`npm install github:adiwajshing/baileys`

Baileys MD:
`npm install github:adiwajshing/baileys#multi-device`

**Comment by SL-Alpha-X** [comment]
Thanks 🙂
