### ISSUE TITLE
WhatsApp Web Forcing Use MD

### ISSUE THREAD

**Issue by FaizBastomi** [adiwajshing/Baileys#831]
Looks like WhatsApp Web has pushed to use MD, Legacy Connection won't be able to connect. Try using the "multi-device" branch or wait until it is merged to the "master" branch.
```bash
npm install github:adiwajshing/baileys#multi-device
# or
yarn add github:adiwajshing/baileys#multi-device
```

**Comment by adiwajshing** [comment]
What's the point of this issue exactly ?

**Comment by FaizBastomi** [comment]
never mind, sorry about that

>
