### ISSUE TITLE
[BUG] How ? Group jid

### ISSUE THREAD

**Issue by mrfzvx12** [adiwajshing/Baileys#835]
WARN [2021-11-11 05:52:15.251 +0000] (5991): recieved odd group ID
    gid: "120363021255346001@g.us"
    class: "Baileys"

**Comment by akm-akm** [comment]
same issue

**Comment by guiguicdd** [comment]
This is a new group id. Just update your Baileys module, it was fixed

**Comment by mrfzvx12** [comment]
> This is a new group id. Just update your Baileys module, it was fixed

I've updated it but it keeps showing up
