### ISSUE TITLE
[MD] How to disconnect and reconnect (refresh) to socket?

### ISSUE THREAD

**Issue by resatkrlc** [adiwajshing/Baileys#840]
Hi, i didn't find any source for to do this. How to disconnect from sock and reconnect?

Maybe like sock.disconnect() ?

**Comment by BochilGaming** [comment]
> Hi, i didn't find any source for to do this. How to disconnect from sock and reconnect?
> 
> Maybe like sock.disconnect() ?

look example.ts

**Comment by sekooo** [comment]
+1 please help

**Comment by resatkrlc** [comment]
> +1 please help

i guess its sock.end()

**Comment by sekooo** [comment]
> > +1 please help
> 
> i guess its sock.end()

No, sock.end not working.. 

![baii](https://user-images.githubusercontent.com/8312608/230222635-f0beb5ed-2bb0-44ef-93ac-d159cc2c1e1b.png)
