### ISSUE TITLE
how to solve "received odd group id" on whatsapp bot script

### ISSUE THREAD

**Issue by KunzxD404** [adiwajshing/Baileys#844]
Please help me

how to solve "received odd group id" on whatsapp bot script

**Comment by tiesco238** [comment]
Whatsapp changed the formatting of group ids.

Comment following lines in file: node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js

        // if (Utils_1.isGroupID(jid) && !jid.includes('-')) {
        //     this.logger.warn({ gid: jid }, 'recieved odd group ID');
        //     return;
        // }

This worked for me as a temporary solution.
Matt

**Comment by guiireal** [comment]
> Whatsapp changed the formatting of group ids.
> 
> Comment following lines in file: node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js
> 
> ```
>     // if (Utils_1.isGroupID(jid) && !jid.includes('-')) {
>     //     this.logger.warn({ gid: jid }, 'recieved odd group ID');
>     //     return;
>     // }
> ```
> 
> This worked for me as a temporary solution. Matt

Amazing !

**Comment by AkirahX** [comment]
Update your Baileys, the solution has already been merged.

Close this.

**Comment by KunzxD404** [comment]
Ok thanks
