### ISSUE TITLE
[Request] - Interface defaults for message

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#85]
Hello!

Everything going good with this API, but I'd like to purpose a change, look:

When we receive a message using `client.setOnUnreadMessage()` we have a message interface like this:

```javascript
WebMessageInfo {
   messageStubParameters: [],
   labels: [],
   key: MessageKey {
      remoteJid: 'xxxxxx@s.whatsapp.net',
      fromMe: false,
      id: 'xxxxxx'
   },
   message: Message { conversation: 'Received Message' },
   messageTimestamp: Long { low: 1595898597, high: 0, unsigned: true }
}
```

But when we send messages using `client.sendMessage` the response is something like this:
```javascript
{
   status: 200,
   messageID: 'xxxxxxxxxx',
   message: {
       key: {
         remoteJid: 'xxxxxxxxx@s.whatsapp.net',
         fromMe: true,
         id: 'E310FA9A0BD4F8286D07'
       },
       message: { extendedTextMessage: [Object] },
       messageTimestamp: 1595898926.829,
       messageStubParameters: [],
       participant: null,
       status: 1
  }
}
```

Can we apply the same interface pattern to the response of sending messages?

Thank you!

**Comment by adiwajshing** [comment]
No, I don't see a lot of good in adding such a breaking change. Moreover, the reason I've kept it this way is to ensure users get back the status code & messageID first -- because that is crucial. The message is merely the message object sent.

**Comment by kaykyr** [comment]
> No, I don't see a lot of good in adding such a breaking change. Moreover, the reason I've kept it this way is to ensure users get back the status code & messageID first -- because that is crucial. The message is merely the message object sent.

Ok! I got it! But the structure is very similar, the only thing needed will be status code but you can handle this like this:

Throw error in case of `status !=== 200` return message in interface format in case of `status === 200`

But ok! This is just a suggestion, I'll implement a parser to solve this for me.
