### ISSUE TITLE
WhatsApp does not read the QR code

### ISSUE THREAD

**Issue by avrcoelho** [adiwajshing/Baileys#850]
WhatsApp does not read the QR code. What?

**Comment by Fadhlursz** [comment]
me too

**Comment by erickythierry** [comment]
if you're using regular baileys, then it won't work anymore, whatsapp is sending the new multi device update to all users and this new update is not compatible with regular baileys (look in the project readme about baileys MD) the one that works with the new update (but it's still unstable)
