### ISSUE TITLE
[BUG] Image Fetching issue.

### ISSUE THREAD

**Issue by ShinNouzen** [adiwajshing/Baileys#853]
Ahh.... I've been having trouble in processing the images. It sometimes work but it mostly gives the error(Error Marker was not Found) from  [jimp](https://github.com/oliver-moran/jimp). It happens most of the time. And most of that files are of jpg  format, but png file works but it also gives the error sometimes.

**Comment by phaticusthiccy** [comment]
#488

**Comment by ShinNouzen** [comment]
@phaticusthiccy will this work? I mean I'll be using url for the thumbnail so...

**Comment by phaticusthiccy** [comment]
Thumbs must be base64 string. Not a link or something else. You can follow the steps what ı wrote :) 
Please check #488. If everything is ok, you will able to pass "marker wasnt found" error.
