### ISSUE TITLE
Scan Barcode

### ISSUE THREAD

**Issue by thisfardi** [adiwajshing/Baileys#855]
how to set time to scan bacrode?

**Comment by thisfardi** [comment]
this my code :
var alreadyConnected = false;

client.on('qr', (qr) => console.log('Scan Qr Di Atas'));


client.on('connecting', (anu,ena) => { 
if (alreadyConnected) {
functions.animate.add('Connecting',{text:'Menghubungkan Ulang Ke Koneksi '+client.user.name});
await postQR(qr)
} else {
functions.animate.add('Connecting',{text:'Menghubungkan Ke Koneksi....'});
}
});

client.on('open', () => {
alreadyConnected = true
functions.animate.succeed('Connecting',{text: 'Sukses Terhubung Ke '+client.user.name});
botinfo.session = client.base64EncodedAuthInfo();
functions.fs.writeFileSync('./src/json/botInfo.json',JSON.stringify(botinfo,null,2));
});

client.on('close',({isReconnecting,reason}) => {
isReconnecting?console.log(functions.logColor(`✖ Koneksi Terputus, Mencoba Mengubungkan Ulang Ke `+client.user.name,'red')):console.log(functions.logColor(`✖ Koneksi Terputus, Menutup Koneksi`,'red')) && process.send('close')
})

very fast i cant scan barcode. please help. thanks

**Comment by mrfzvx12** [comment]
> this my code : var alreadyConnected = false;
> 
> client.on('qr', (qr) => console.log('Scan Qr Di Atas'));
> 
> client.on('connecting', (anu,ena) => { if (alreadyConnected) { functions.animate.add('Connecting',{text:'Menghubungkan Ulang Ke Koneksi '+client.user.name}); await postQR(qr) } else { functions.animate.add('Connecting',{text:'Menghubungkan Ke Koneksi....'}); } });
> 
> client.on('open', () => { alreadyConnected = true functions.animate.succeed('Connecting',{text: 'Sukses Terhubung Ke '+client.user.name}); botinfo.session = client.base64EncodedAuthInfo(); functions.fs.writeFileSync('./src/json/botInfo.json',JSON.stringify(botinfo,null,2)); });
> 
> client.on('close',({isReconnecting,reason}) => { isReconnecting?console.log(functions.logColor(`✖ Koneksi Terputus, Mencoba Mengubungkan Ulang Ke `+client.user.name,'red')):console.log(functions.logColor(`✖ Koneksi Terputus, Menutup Koneksi`,'red')) && process.send('close') })
> 
> very fast i cant scan barcode. please help. thanks

Set timeout saat connect.. buat mengatur qr agar tidak muncul dengan cepat.. bisa cek di repo saya...
