### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nexusNw** [adiwajshing/Baileys#856]
please solve the "marker not found" eror😭

**Comment by LuanRT** [comment]
Bruh

**Comment by SheIITear** [comment]
Bruh

**Comment by Zobin33** [comment]
Hi There, The Marker Not Found Bug Isnt On Baileys, The Bug In Jimp, So Close The Issue

**Comment by phaticusthiccy** [comment]
> please solve the "marker not found" eror😭

#488
