### ISSUE TITLE
[BUG] onErr = ({ reason, status }) => reject(new Constants_1.BaileysError(reason, { status }));

### ISSUE THREAD

**Issue by Barqah-Xiex** [adiwajshing/Baileys#857]
/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:190
                onErr = ({ reason, status }) => reject(new Constants_1.BaileysError(reason, { status }));
                                                       ^

BaileysError: Not expecting a response

**Comment by thaziz** [comment]
This case same with me
