### ISSUE TITLE
[BUG] How auto reconnect on close?

### ISSUE THREAD

**Issue by deri387** [adiwajshing/Baileys#858]
conn.on("close", async (reason) => {
      console.log("Disconnected because " + reason.reason);

      if (reason.reason === "lost") {
        conn.close();
        conn.loadAuthInfo(conn.base64EncodedAuthInfo());
        conn.connect();
        return {};
      }
      if (reason.reason != "intentional") {
        console.log("Unable to reconnect");
      }
    });
    
    
how can i auto reconnect when the reason of close is not intentional?

**Comment by jrvidotti** [comment]
Set this param:
`conn.autoReconnect = ReconnectMode.onAllErrors`
