### ISSUE TITLE
[BUG] undefined in the request url when sending message

### ISSUE THREAD

**Issue by WhitespaceQ** [adiwajshing/Baileys#86]
I'm new to nodejs and JS in general so pardon my ugly script.

I'm trying to build a script to send messages for a group project, here's the snippet

```
import WAClient from '@adiwajshing/baileys'
import MessageType from '@adiwajshing/baileys'

async function blast() {
	const blastClient = new WAClient.WAClient()
	blastClient.autoReconnect = true

	await blastClient.connectSlim('./auth_info.json')
	.then (async user => {
		const id = '000@s.whatsapp.net'
		await blastClient.sendMessage(id, 'SomeMessages', MessageType.text)
	})
}

blast().catch((err) => console.log(encountered error: ${err}))
```

Here's what I got
```
[Baileys][7/28/2020, 6:11:10 PM] loading authentication credentials from ./auth_info.json
[Baileys][7/28/2020, 6:11:10 PM] connected to WhatsApp Web, authenticating...
[Baileys][7/28/2020, 6:11:11 PM] resolving login challenge
[Baileys][7/28/2020, 6:11:12 PM] validated connection successfully
encountered error: FetchError: request to https://mmg-fna.whatsapp.netundefined/[redacted]?auth=[redacted]&token=[redacted] failed, reason: getaddrinfo ENOTFOUND mmg-fna.whatsapp.netundefined
```

Notice the italic undefined in the url, that shouldn't be there if I'm not mistaken.

I'm using Baileys 2.2.0 and nodejs 14.6.0

**Comment by adiwajshing** [comment]
Are you sure this is the script you're using? This seems like you may have accidentally set `MessageType.image` or something on a text message.

**Comment by WhitespaceQ** [comment]
> Are you sure this is the script you're using? This seems like you may have accidentally set `MessageType.image` or something on a text message.

Yeah, that's my script that throws the error. I haven't found any obvious error on my part that's why I'm asking here. May I know why you think that this  is related to `MessageType.image`, that may help on troubleshooting

**Comment by adiwajshing** [comment]
Ah found the issue, it's this line:
``` ts
import MessageType from '@adiwajshing/baileys' // this line is the problem
import { MessageType } from '@adiwajshing/baileys' // change to this
```

You see, without the curly brackets, you basically import the entire module but with the curly brackets -- you specify exactly which object you want.

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing

**Comment by WhitespaceQ** [comment]
Sorry for the late response, I'm mingling with the code trying to pinpoint the culprit myself. Pardon my ignorance as I'm not as knowledgeable with Nodejs but with your suggestion, I'm getting this

If this is wholly on my lack of understanding, do ignore my question.

```
import { MessageType } from '@adiwajshing/baileys'
         ^^^^^^^^^^^
SyntaxError: The requested module '@adiwajshing/baileys' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```

Thanks!
