### ISSUE TITLE
[BUG] after update baileys-md, i cannot scan

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#861]
[BUG] after update baileys-md, i cannot scan

**Comment by SilentX26** [comment]
same with me, cannot scan qrcode. I get message "please scan qrcode again"

**Comment by itacirgabral** [comment]
baileys multi device is https://github.com/adiwajshing/Baileys/tree/multi-device.
you need baileys and mobile in multidevice mode.

**Comment by frmdeveloper** [comment]
> baileys multi device is https://github.com/adiwajshing/Baileys/tree/multi-device. you need baileys and mobile in multidevice mode.

Now, i can connect to baileys-md.
accidentally
