### ISSUE TITLE
[BUG] WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by ilyaborodin** [adiwajshing/Baileys#864]
After several hours of work, this error started spamming.

<img width="854" alt="Снимок экрана 2021-11-15 в 11 36 54" src="https://user-images.githubusercontent.com/48887908/141749456-b5a28391-d2ba-4fa5-801e-71c34336f2f3.png">

**Comment by ilyaborodin** [comment]
This time I turned on the trace logging mode. And that I noticed that a minute before this error, other errors began to spam
`{"level":50,"time":1636974711892,"pid":3023,"hostname":"stage-api-1","error":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"BAE51353E52A8A00"},"content":null}]},"msg":"stream errored out"}`

`{"level":30,"time":1636974711892,"pid":3023,"hostname":"stage-api-1","error":{"data":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"BAE51353E52A8A00"},"content":null}]},"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Stream Errored"},"headers":{}}},"msg":"connection closed"}`

And right behind this error, this one:
`{"level":10,"time":1636974711894,"pid":3023,"hostname":"stage-api-1","fromMe":false,"frame":{"tag":"xmlstreamend","attrs":{},"content":null},"msg":"communication"}
`

` {"level":30,"time":1636974711894,"pid":3023,"hostname":"stage-api-1","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Terminated by Server"},"headers":{}}},"msg":"connection closed"}
`

I also attach logs so that you can view. I scanned the qr code at 9:34 am and cut the logs to 11:13± am.

[index-error.log](https://github.com/adiwajshing/Baileys/files/7538977/index-error.log)
[index-out.log](https://github.com/adiwajshing/Baileys/files/7538959/index-out.log)

no private data in the logs

**Comment by ilyaborodin** [comment]
#810

**Comment by burstfreeze** [comment]
The provided example.ts has an issue with triggering the reconnect on error more than once. Do you use the normal example.ts?

**Comment by ilyaborodin** [comment]
> The provided example.ts has an issue with triggering the reconnect on error more than once. Do you use the normal example.ts?

I think so. Everything looks the same like in new example.ts.

init wa connection:
<img width="924" alt="Снимок экрана 2021-11-15 в 16 44 24" src="https://user-images.githubusercontent.com/48887908/141792353-23839b97-9f55-4b08-a882-6d3be080964c.png">

connection.update:

<img width="820" alt="Снимок экрана 2021-11-15 в 16 44 59" src="https://user-images.githubusercontent.com/48887908/141792492-2cddcebb-9a1c-4f8f-92b1-9ba412068c28.png">

**Comment by rawars** [comment]
Good friends, I picked up a connection at two in the afternoon, but at five it got lost and I stopped listening, this is the exit through the terminal, I had it running on my local computer and on a server in aws at two it broke .

Also noteworthy that I have the last commit made.
![error50](https://user-images.githubusercontent.com/3655598/141792770-89dd291c-b831-4cdd-bfe6-f1b398da45c2.png)

I republish it here because I had posted it in a different thread.

**Comment by ilyaborodin** [comment]
I also saw that several people reported this issue in discord

**Comment by burstfreeze** [comment]
Does this happen to you shortly after reconnects? This is based on topkek's suggestion:

```
const startSock = () => {
	
	var relaunchSemaphore = 0

	// !== DisconnectReason.loggedOut) {
		sock.ev.removeAllListeners('connection.update')

		relaunchSemaphore++

		if(relaunchSemaphore == 1) {
			console.log('Restarting conn.');
				setTimeout(function(){ 
				sock = startSock() 
			}, 100);
		}

```

Although an actual thread lock may be cleaner this could work well. The only issue I could see with this idea is when there are 2 events coming in VERY shortly after each other that both more or less simultaneously raise the semaphore. Then nothing will happen at all instead. We could add another lock bool to check for that as well but at this point the thread lock really would be the better solution or maybe a bit deeper in baileys disable follow-up events. For me it was when numerous errors triggered at once, causing the reconnect to be triggered numerous times.

**Comment by ilyaborodin** [comment]
I saw this messages and implemented smth like this, but I had the same issue after this I think. I will make tests, check logs again and respond

**Comment by burstfreeze** [comment]
Send us the logs again if it happens again

**Comment by ilyaborodin** [comment]
> Send us the logs again if it happens again

I just checked logs. Stream Errored happened few times yesterday, but thing with delay helped. It did not start spamming like before. Just close and open with delay. I will scan now and will test again. If it will work I close the issue. 

is 100 ms enough? I tested 2 secs delay. But as I see in logs 100 ms should be enough

**Comment by burstfreeze** [comment]
The delay does not have a meaning I think.

**Comment by ilyaborodin** [comment]
@burstfreeze 

Again logger spam to me stream error, but now without "WebSocket is not open: readyState 2 (CLOSING)".

Logs:
[index-error.log](https://github.com/adiwajshing/Baileys/files/7556960/index-error.log)
[index-out.log](https://github.com/adiwajshing/Baileys/files/7556961/index-out.log)


At the same time as first this error appeared I received this error: 

`
TypeError: Cannot read property 'key' of undefined
at EventEmitter.<anonymous> (/home/ubuntu/whatsapp_api_md/node_modules/@adiwajshing/baileys-at EventEmitter.emit (events.js:412:35)
at WebSocket.<anonymous> (/home/ubuntu/whatsapp_api_md/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:383:12)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

In my opinion this error appears when I am trying to connect to wa.

And I'm pretty sure I'm not trying to open 2 times the connection when 2 close events arrive. I logged this.

After few hours this started I restarted server and it connected successfully 

Connected issue: #874

**Comment by burstfreeze** [comment]
Ok, at least it is not spawning duplicate instances anymore. Unfortunately I have no idea what's going on with your logs. Is this on VPN, server or on your personal device?

**Comment by ilyaborodin** [comment]
Aws, EC2, São Paulo

**Comment by guiromer** [comment]
I am also having the same problem when the socket have been instantiated for a while (usually one hour)

```
{"level":50,"time":1637176166196,"pid":1442,"hostname":"iMac-de-Guil.local","error":{"tag":"stream:error","attrs":{},"content":[{"tag":"ack","attrs":{"id":"69525B21AFE0B10B672A1E94D46FA295"},"content":null}]},"msg":"stream errored out"}

loading state  5522997692579:82@s.whatsapp.net
loading state  5522997692579:82@s.whatsapp.net

{
  connection: 'close',
  lastDisconnect: {
    error: Error: Stream Errored
        at WebSocket.<anonymous> (/Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:458:13)
        at WebSocket.emit (events.js:400:28)
        at WebSocket.emit (domain.js:475:12)
        at /Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:230:35
        at Object.decodeFrame (/Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Utils/noise-handler.js:141:17)
        at WebSocket.onMessageRecieved (/Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:208:15)
        at WebSocket.emit (events.js:400:28)
        at WebSocket.emit (domain.js:475:12)
        at Receiver.receiverOnMessage (/Users/guilherme/Sites/api-whatsapp-md/node_modules/ws/lib/websocket.js:983:20)
        at Receiver.emit (events.js:400:28) {
      data: [Object],
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2021-11-17T19:09:26.198Z
  }
} 
Then, followed by this one: 

{
  connection: 'close',
  lastDisconnect: {
    error: Error: Connection Terminated by Server
        at WebSocket.<anonymous> (/Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:372:13)
        at WebSocket.emit (events.js:400:28)
        at WebSocket.emit (domain.js:475:12)
        at /Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:230:35
        at Object.decodeFrame (/Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Utils/noise-handler.js:141:17)
        at WebSocket.onMessageRecieved (/Users/guilherme/Sites/api-whatsapp-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:208:15)
        at WebSocket.emit (events.js:400:28)
        at WebSocket.emit (domain.js:475:12)
        at Receiver.receiverOnMessage (/Users/guilherme/Sites/api-whatsapp-md/node_modules/ws/lib/websocket.js:983:20)
        at Receiver.emit (events.js:400:28) {
      data: null,
      isBoom: true,
      isServer: false,
      output: [Object]
    },
    date: 2021-11-17T19:09:26.247Z
  }
}
{
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}
{
  connection: 'connecting',
  receivedPendingNotifications: false,
  qr: undefined
}

{"level":50,"time":1637176167463,"pid":1442,"hostname":"iMac-de-Guil.local","error":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"},"content":null}]},"msg":"stream errored out"}
```

**Comment by adiwajshing** [comment]
@guiromer mate you literally opened two sockets for the same instance -- issue is in your reconnect script

**Comment by burstfreeze** [comment]
@adiwajshing this can happen with Baileys example too. It puts duplicate events within a very short time on some errors sometimes.
