### ISSUE TITLE
[BUG] Multi-Device : groupParticipantsUpdate doesn't return status code

### ISSUE THREAD

**Issue by akhilnarayanan1** [adiwajshing/Baileys#865]
**Describe the bug**
`groupParticipantsUpdate` only returns list of participants (no status code present)

**To Reproduce**
1. `let response = await socket.groupParticipantsUpdate(
        m.messages[0].key.remoteJid,
        ["9179XXXXXX20@s.whatsapp.net",],
        'add'
    )
console.log(JSON.stringify(response, undefined, 2))`
2. The response is a list of participantsAffected

**Expected behavior**
`groupParticipantsUpdate` should return list of participantsAffected along with **status code**

**Comment by akhilnarayanan1** [comment]
Open

**Comment by guiguicdd** [comment]
Same here
