### ISSUE TITLE
[BUG] Empty messages for history notification

### ISSUE THREAD

**Issue by Pegorino82** [adiwajshing/Baileys#867]
got this error

{..."msg":"got history notification"}
{
  "messages": [
    {
      "key": {
        "remoteJid": "@s.whatsapp.net",
        "fromMe": true,
        "id": ""
      },
      "message": {
        "protocolMessage": {
          "type": "HISTORY_SYNC_NOTIFICATION",
          "historySyncNotification": {
            "fileSha256": "=",
            "fileLength": "",
            "mediaKey": "=",
            "fileEncSha256": "i=",
            "directPath": "/=61B8FD04",
            "syncType": "RECENT",
            "chunkOrder": 2
          }
        }
      },
      "messageTimestamp": "1636990901",
      "status": "SERVER_ACK",
      "pushName": ""
    }
  ],
  "type": "notify"
}
{
  "messages": [],
  "type": "prepend"
}
/Baileys/src/Socket/messages-recv.ts:505
        const chat: Partial<Chat> = { id: messages[0].key.remoteJid }
                                                      ^
TypeError: Cannot read properties of undefined (reading 'key')
    at EventEmitter.<anonymous> (/Baileys/src/Socket/messages-recv.ts:505:55)
    at EventEmitter.emit (node:events:402:35)
    at EventEmitter.emit (node:domain:475:12)
    at processHistoryMessage (/Baileys/src/Socket/messages-recv.ts:256:20)
    at processMessage (/Baileys/src/Socket/messages-recv.ts:121:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EventEmitter.<anonymous> (/Baileys/src/Socket/messages-recv.ts:518:13)
error Command failed with exit code 1.

**Comment by keef3ar** [comment]
U can use this fix before it not fixed in library
`const replaceBugEvent = client => {
  const func: Function = client.ev.listeners("messages.upsert")[0];
  client.ev.removeAllListeners("messages.upsert");
  client.ev.on("messages.upsert", ({ messages }) => {
    if (messages[0]?.key?.remoteJid) {
      return func({ messages });
    }
  });
};`

**Comment by adiwajshing** [comment]
Resolved in latest commit
