### ISSUE TITLE
Unknown status code: 419

### ISSUE THREAD

**Issue by CheloXL** [adiwajshing/Baileys#87]
I'm getting a 419 when trying to initialize the app. I already paired the phone and everything was working fine. Since I'm just playing around, I didn't use the app for a couple of weeks.

Now I'm getting a 419 status error. Since it is not a standard code, I'm not quite sure what that could mean. I'm pretty sure that if I re-pair the phone, everything will start to work again, but maybe this is something that can be handled automatically, since  WSWeb doesn't force me to re-pair the phone.

**Comment by adiwajshing** [comment]
Yeah, I have no idea either. Did you try connecting more than once?

**Comment by CheloXL** [comment]
Yes... always getting the same error code....

**Comment by adiwajshing** [comment]
I don't think this issue is fixable, probably something to do with WA itself or some protocol not yet explored. I'm closing this for now.
