### ISSUE TITLE
[BUG] "Waiting for this message. This may take a while." in both directions

### ISSUE THREAD

**Issue by jackcokk** [adiwajshing/Baileys#870]
Amazing work adiwajshing and pokearaujo and all contributors, we all have to thank you so much!

I am experiencing an issue with messages sent with Baileys that in the message frame it says 

_Waiting for this message. This may take a while._ on a recipients' device.

My sql also sometimes does not have all the messages sent in a chat.

On the other hand in some of these cases, other group participants, my WhatsApp Web desktop app and even another Baileys instance did receive and decrypt that message. Just not the phone itself or sometimes it is available on the phone but not in Baileys.

I suppose it is not an issue with the sending of messages but rather with the key back-and-forth. I can only assume that WAWeb writes these missing messages to a queue and regularly checks whether both the devices in question are online at the same time in order to trigger a new key synchronization.*

To summarize in a user story:

Baileys sends message, someone's device (iPhone or linked device) is offline. The device in question is not in sync with the signal keys (?) and when it goes online, power at the Baileys computer cuts off and is unavailable for a few hours. All devices are online again after a while but the messages from and to each other may be missing.

I have even seen the same among the actual apps but usually within seconds the issue has resolved itself when both went online. So I guess there must be a way to do it in the same manner the website app does it.

Is there something we can do with the website app to e.g. log incoming and outgoing traffic in order that may help you analyze and implement the missing functionality? It is astonishing at what pace this project has become relatively stable so I am sure there will be a way to also fix that somehow.

 

@PurpShell I remember you went a lot through IndexedDB for wwebjs when md has launched. Have you see any kind of stack for the to-be-resynced messages or similar?

**Comment by adiwajshing** [comment]
The issue is likely in the way you're storing your keys, if you're using SQL or some other DB where there is a delay in storing/retreiving data -- there is a chance you use an incorrect signal session to encrypt/decrypt a message -- causing the issue you're seeing. 

This is very likely not an issue with the library

**Comment by jackcokk** [comment]
There indeed is a delay. Do the auth state updates get ACK'd by Baileys? Could there be a way to make them wait for an event (db notifies successful save)?

I am asking because what may be possible is that Baileys during reconnecting loads an older set of auth whilst the current one is still being saved to the db. This would mean that Baileys has ACK'd the new set but launched the session with an incomplete set.

Would having the auth-state.update re-done to something like a promise-based handler work so it blocks further execution until the save event has finished? We are probably talking about milliseconds there so it wouldn't affect performance at all but I suppose this may ensure that we at any given time always only ACK the latest set of data and if the save failed (no memory, db not available etc.) or did not complete in time Baileys simply will not ACK, maybe causing the server to re-send the keys?

**Comment by jackcokk** [comment]
Does this commit https://github.com/adiwajshing/Baileys/commit/78fd72c8e509198aba73c509a990699de4fb57be relate to this issue? Is there a way to test this for you to confirm?
