### ISSUE TITLE
[BUG]  TypeError: Cannot read properties of undefined (reading 'key')

### ISSUE THREAD

**Issue by lyfe00011** [adiwajshing/Baileys#874]
Nov 16 23:02:23 Connecting...
Nov 16 23:02:23 {
Nov 16 23:02:23   connection: 'connecting',
Nov 16 23:02:23   receivedPendingNotifications: false,
Nov 16 23:02:23   qr: undefined
Nov 16 23:02:23 }
Nov 16 23:02:24 Connecting...
Nov 16 23:02:24 { connection: 'open' }
Nov 16 23:02:24 Connected
Nov 16 23:02:24 /root/LyFE/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:447
Nov 16 23:02:24         const chat = { id: messages[0].key.remoteJid };
Nov 16 23:02:24                                        ^
Nov 16 23:02:24 TypeError: Cannot read properties of undefined (reading 'key')
Nov 16 23:02:24     at EventEmitter.<anonymous> (/root/LyFE/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:447:40)
Nov 16 23:02:24     at EventEmitter.emit (node:events:402:35)
Nov 16 23:02:24     at WebSocket.<anonymous> (/root/LyFE/node_modules/@adiwajshing/baileys-md/lib/Socket/messages-recv.js:383:12)
Nov 16 23:02:24     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Nov 16 23:02:24 Tue Nov 16 2021 23:02:24 GMT+0530 (India Standard Time)
Nov 16 23:02:24 Program node test.js exited with code 1
Nov 16 23:02:24 Starting child process with 'node test.js'
after some hours(5+) this error came 
also it run without any restart or connection issues upto this.
yup latest commit.

**Comment by canove** [comment]
Same here. How did you solve it?

**Comment by ilyaborodin** [comment]
Same

**Comment by ilyaborodin** [comment]
At the same time with "Cannot read properties of undefined" I received this errors:
<img width="1440" alt="Снимок экрана 2021-11-17 в 19 34 32" src="https://user-images.githubusercontent.com/48887908/142242606-db959165-f99a-4ff5-b9b2-c0f8dd2729c3.png">

**Comment by lyfe00011** [comment]
> Same

?.key?.remoteJID
im trying this, i thinks happen just after received notification true

**Comment by ilyaborodin** [comment]
> > Same
> 
> ?.key?.remoteJID im trying this, i thinks happen just after received pending notification true
> 
> Nov 17 08:49:10 { Nov 17 08:49:10 connection: 'connecting', Nov 17 08:49:10 receivedPendingNotifications: false, Nov 17 08:49:10 qr: undefined Nov 17 08:49:10 } Nov 17 08:49:10 undefined // maybe this too Nov 17 08:49:10 { connection: 'open' } Nov 17 08:49:10 undefined // maybe this too Nov 17 08:49:10 Connected Nov 17 08:49:11 { receivedPendingNotifications: true } Nov 17 08:49:11 undefined // this is error case Nov 17 08:49:20 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) Nov 17 08:49:56 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) Nov 17 08:49:59 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) Nov 17 08:50:01 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) ![Screenshot_20211117_222524](https://user-images.githubusercontent.com/76509367/142246247-c2acaa86-bc03-4626-9529-d604f327f9dd.png)

do u have stream error in this case or no?

**Comment by lyfe00011** [comment]
> > > Same
> > 
> > 
> > ?.key?.remoteJID im trying this, i thinks happen just after received pending notification true
> > Nov 17 08:49:10 { Nov 17 08:49:10 connection: 'connecting', Nov 17 08:49:10 receivedPendingNotifications: false, Nov 17 08:49:10 qr: undefined Nov 17 08:49:10 } Nov 17 08:49:10 undefined // maybe this too Nov 17 08:49:10 { connection: 'open' } Nov 17 08:49:10 undefined // maybe this too Nov 17 08:49:10 Connected Nov 17 08:49:11 { receivedPendingNotifications: true } Nov 17 08:49:11 undefined // this is error case Nov 17 08:49:20 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) Nov 17 08:49:56 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) Nov 17 08:49:59 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) Nov 17 08:50:01 [xxx-xxx@g.us](mailto:xxx-xxx@g.us) ![Screenshot_20211117_222524](https://user-images.githubusercontent.com/76509367/142246247-c2acaa86-bc03-4626-9529-d604f327f9dd.png)
> 
> do u have stream error in this case or no?

I think it's happened with this error when reconnecting

**Comment by ilyaborodin** [comment]
I think so too, I am adding logger to this place and will push to stage.

**Comment by lyfe00011** [comment]
> I think so too, I am adding logger to this place and will push to stage.

This undefined is not related to this issue
