### ISSUE TITLE
[BUG] Closed connection still tries to regenerate QR

### ISSUE THREAD

**Issue by jrvidotti** [adiwajshing/Baileys#876]
**Describe the bug**

**To Reproduce**
1. Try to initiate a WAConnection, not scanning QR Code
2. At some time, try to close and dispose WAConnection with a function like this:
```
  public async dispose(): Promise<void> {
    console.log('WAService.dispose()')
    try {
      this.conn.removeAllListeners()
      if (this.conn.state !== 'close') this.conn.close()
    } catch (error) {
      console.log('error disposing:', error)
    }
  }
```
3. Got this output:
```
closing, countQr >= 3
WAService.dispose()
INFO [2021-11-16 21:45:23.823 +0000] (72659): closed connection, reason intentional
    class: "Baileys"
DEBUG [2021-11-16 21:45:43.826 +0000] (72659): regenerating QR
    class: "Baileys"
TRACE [2021-11-16 21:45:43.836 +0000] (72659): 1637099083.--0,["admin","Conn","reref"]
    fromMe: true
    class: "Baileys"
WARN [2021-11-16 21:45:43.840 +0000] (72659): error in QR gen
    class: "Baileys"
    error: {}
DEBUG [2021-11-16 21:46:03.844 +0000] (72659): regenerating QR
    class: "Baileys"
TRACE [2021-11-16 21:46:03.845 +0000] (72659): 1637099083.--1,["admin","Conn","reref"]
    fromMe: true
    class: "Baileys"
WARN [2021-11-16 21:46:03.845 +0000] (72659): error in QR gen
    class: "Baileys"
    error: {}
```

**Expected behavior**
I want to cease all activity within that instance of WAConnection in order to start a fresh connection without restart application.

**Comment by PokeGuys** [comment]
Are you calling the `dispose` function inside `qr` event handler?

**Comment by ThePinkLyna** [comment]
Can't you just do a close and then a restart? I mean, using async? Something like "Bot.close()" and then "start()" again?

**Comment by PokeGuys** [comment]
> Can't you just do a close and then a restart? I mean, using async? Something like "Bot.close()" and then "start()" again?

No, you can't if you call `close()` inside `qr` event.

This PR #897 can fix this bug.

**Comment by jrvidotti** [comment]
> Are you calling the `dispose` function inside `qr` event handler?

Yes, after a few retries. But nevermind, I moved on to multidevice and solved my problem!

I think that this version is becoming obsolete as Whatsapp pushes current beta to everyone, right?
