### ISSUE TITLE
[BUG]Cannot read properties of undefined (reading 'clientID')

### ISSUE THREAD

**Issue by manishkumar1601** [adiwajshing/Baileys#881]
I am gettting this error please help me with this

![image](https://user-images.githubusercontent.com/76832269/142136897-0dc09f64-7f81-4a4f-9df0-348cac6eb9bb.png)

**Comment by DentaStudio** [comment]
your WhatsApp client is using Multi Device Web WhatsApp
and baileys have a new version for this

try this a new baileys for multi device
https://github.com/adiwajshing/baileys/tree/multi-device

for now, the documentation it doesn't exist, learn this by yourself

(sorry for my bad english)
