### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by orderku** [adiwajshing/Baileys#882]
im add clearall chat on whtsapp bot

error code 
Error : TypeError: botku.deleteChat is not a function

my code 

case 'clearall':
if (!isOwner) return reply('Kamu siapa?')
                                        anu = await botku.chats.all()
                                        botku.setMaxListeners(25)
                                        for (let _ of anu) {
                                                botku.deleteChat(_.jid)
                                        }
                                        reply(`Sukses delete all chat`)
                                        break

**Comment by BochilGaming** [comment]
> im add clearall chat on whtsapp bot
> 
> error code Error : TypeError: botku.deleteChat is not a function
> 
> my code
> 
> case 'clearall': if (!isOwner) return reply('Kamu siapa?') anu = await botku.chats.all() botku.setMaxListeners(25) for (let _ of anu) { botku.deleteChat(_.jid) } reply(`Sukses delete all chat`) break

```js
await botku.clearMessage
```

**Comment by frmdeveloper** [comment]
> im add clearall chat on whtsapp bot
> 
> error code Error : TypeError: botku.deleteChat is not a function
> 
> my code
> 
> case 'clearall': if (!isOwner) return reply('Kamu siapa?') anu = await botku.chats.all() botku.setMaxListeners(25) for (let _ of anu) { botku.deleteChat(_.jid) } reply(`Sukses delete all chat`) break

```js
for (let _ of anu) {
     await client.modifyChat(_.jid, 'clear')
}
reply(`Sukses delete all chat`)
```
