### ISSUE TITLE
Key used already or never filled [BUG]

### ISSUE THREAD

**Issue by rawars** [adiwajshing/Baileys#884]
**Describe the bug**
After having almost an hour working without problems, suddenly it throws an error and stops listening, the error itself <MessageCounterError: Key used already or never filled \ n at SessionCipher.doDecryptWhisperMessage> and at the end there is another message that says <" msg ":" failure in decrypting message ">

**To Reproduce**
1. Created a new connection
2. Run for an hour
3. Stops and does not keep listening, displays the message that the message cannot be decrypted

![photo_2021-11-17_19-35-39](https://user-images.githubusercontent.com/3655598/142322263-54234b89-ed5d-4c39-b570-e91575e8e069.jpg)

![photo_2021-11-17_19-38-48](https://user-images.githubusercontent.com/3655598/142322274-07113448-1d27-455a-a4d0-7af1f5f0bb09.jpg)

**Comment by enoksaju** [comment]
same here
