### ISSUE TITLE
[BUG] Cannot send sticker from buffer in Baileys-md

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#889]
## cannot send sticker from buffer in baileys-md
![Screenshot_20211118-224019](https://user-images.githubusercontent.com/80396521/142447462-2fc1d507-79bf-43fc-8d89-a094781f86ff.png)

**Comment by lyfe00011** [comment]
{sticker:buffer}

**Comment by frmdeveloper** [comment]
> {sticker:buffer}

![Screenshot_20211119-051608](https://user-images.githubusercontent.com/80396521/142505595-bffacab7-f37a-468a-b485-5af7d5f5f49a.png)

**Comment by frmdeveloper** [comment]
Please fix

**Comment by frmdeveloper** [comment]
@adiwajshing how to fix ?

**Comment by DentaStudio** [comment]
you forget a mimetype

try this
```javascript
sock.sendMessage(jid, { sticker: (buffer), mimetype: 'image/webp' }, { quoted: mek })
```

it's working 
![Screenshot_2021-11-22-10-39-26-11_7352322957d4404136654ef4adb64504.jpg](https://user-images.githubusercontent.com/69065410/142793256-f324eb33-e877-457d-ba59-f647519908e8.jpg)

**Comment by frmdeveloper** [comment]
> this is not bug, you forget a mimetype
> 
> try this
> 
> ```js
> sock.sendMessage(jid, { sticker: (buffer), mimetype: 'image/webp' }, { quoted: mek })
> ```
> 
> it's working ![Screenshot_2021-11-22-10-39-26-11_7352322957d4404136654ef4adb64504.jpg](https://user-images.githubusercontent.com/69065410/142793256-f324eb33-e877-457d-ba59-f647519908e8.jpg)

only 1 time
