### ISSUE TITLE
[MD BUG] failure in decrypting message

### ISSUE THREAD

**Issue by Dakauann** [adiwajshing/Baileys#891]
**Describe the bug**

**To Reproduce**
1: Start the client
2: Use and start restarting the process
3: starts getting some error logs
4: wait/continue using

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? I do not changed It or added anything
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**
After some time using the api, it starts showing me some errors inside baileys, and after some time it also shows that the message id/number has already been used in the session

If u need i can send u a screen shot of my code.

![Screenshot_20211118-182639](https://user-images.githubusercontent.com/74578069/142499471-bd6fb342-db25-4148-9315-3e8154bcda4c.png)

**Comment by frmdeveloper** [comment]
## try this

```js
sock.ev.on("messages.upsert", async(meek) => {
  try {
	if (!meek.messages) return
	const mek = meek.messages[0]
	const chat = { id: mek.key.remoteJid }
```

**Comment by Dakauann** [comment]
> ## try this
> ```js
> sock.ev.on("messages.upsert", async(meek) => {
>   try {
> 	if (!meek.messages) return
> 	const mek = meek.messages[0]
> 	const chat = { id: mek.key.remoteJid }
> ```

what is defined by "meek"

**Comment by Dakauann** [comment]
> ## try this
> ```js
> sock.ev.on("messages.upsert", async(meek) => {
>   try {
> 	if (!meek.messages) return
> 	const mek = meek.messages[0]
> 	const chat = { id: mek.key.remoteJid }
> ```

I'll test it

**Comment by nazaltk** [comment]
@Dakauann  Were you able to fix this? If yes, can you please post your method here.

**Comment by Dakauann** [comment]
> ## try this
> ```js
> sock.ev.on("messages.upsert", async(meek) => {
>   try {
> 	if (!meek.messages) return
> 	const mek = meek.messages[0]
> 	const chat = { id: mek.key.remoteJid }
> ```

This didn't work, I don't think it's an error with an indefinite message, I feel it's an error inside the message decryptor
![Screenshot_20211119-110138](https://user-images.githubusercontent.com/74578069/142634913-a36b4871-1629-47bc-bce5-c190c566ad0b.png)

**Comment by DentaStudio** [comment]
**Try this**

```javascript
sock.ev.on('messages.upsert', async (mek) => {
    mek = JSON.parse(JSON.stringify(mek.messages[0]))
    if (!mek.message) return
    chat = { id: mek.key.remoteJid }
})
```

**Comment by nazaltk** [comment]
Still, it is an error for me while running. If it is working for you can you please post the full method, please?

**Comment by lyfe00011** [comment]
use latest commit

**Comment by nazaltk** [comment]
`{
  "messages": [
    {
      "key": {
        "remoteJid": "917560829311@s.whatsapp.net",
        "fromMe": false,
        "id": "3EB0257FE4F32F810F92"
      },
      "messageStubType": "CIPHERTEXT",
      "messageStubParameters": [
        "nodeCrypto.diffieHellman is not a function"
      ]
    }
  ],
  "type": "notify"
}`

Still I could see following error in console.

**Comment by adiwajshing** [comment]
You need to update your node version, use at least v14

**Comment by Dakauann** [comment]
> You need to update your node version, use at least v14

is version 1.17 bad?

**Comment by Dakauann** [comment]
> > You need to update your node version, use at least v14
> 
> is version 17 bad for baileys md?

**Comment by Dakauann** [comment]
Is the node 17 version bad for baileys md?

**Comment by Dakauann** [comment]
Fixed on recent version
