### ISSUE TITLE
[BUG] Connection Closed Automatically (BAILEYS-MD)

### ISSUE THREAD

**Issue by DentaStudio** [adiwajshing/Baileys#893]
after turning on the script, and running it for 5 minutes, for some reason the script stops itself and outputs like this

```JSON
{
	"level": 30,
	"time": 1637316977270,
	"pid": 22044,
	"hostname": "localhost",
	"class": "baileys",
	"error": {
		"data": null,
		"isBoom": true,
		"isServer": false,
		"output": {
			"statusCode": 408,
			"payload": {
				"statusCode": 408,
				"error": "Request Time-out",
				"message": "Connection was lost"
			},
			"headers": {}
		}
	},
	"msg": "connection closed"
}
```
```javascript
connection update {
    connection: 'close',
    lastDisconnect: {
        error: Error: Connection was lost
               at Timeout.<anonymous> (/storage/emulated/0/bot/wa/node_module/@adiwajshing/baileys-md/lib/Socket/socket.js:290:17)
               at listOnTimeout (node:internal/timers:557:17)
               at processTimers (node:internal/timers:500:7) {
                   data: null,
                   isBoom: true,
                   isServer: false,
                   output: [Object]
        },
        date: 2021-11-19T10:16:17.370Z
    }
}
```

and this has happened so many times, it's very annoying

who says this is my network, NO! my network is working fine

**Comment by frmontini** [comment]
@DentaStudio Try to delete your node_modules folder and package-lock.json file.
After that, use npm install to update to the latest version of Baileys.

**Comment by canove** [comment]
It also happens to me sometimes, after a few (6~10 hours) connected.

**Comment by frmontini** [comment]
> It also happens to me sometimes, after a few (6~10 hours) connected.

@canove Use the socket.end() function when your WhatsApp is not receiving or sending messages. I check every 10 minutes. If nothing happens in that interval, you can call the function and restart the persisted session. With that, you can stay connected for days, because the socket will always be open.
