### ISSUE TITLE
whattsapp group problem

### ISSUE THREAD

**Issue by Piyushdas1624** [adiwajshing/Baileys#894]
whenever i am adding my bot in some groups and using command like "/help" its not working . But when ever i am texting the bot privately its working fine and i have faced some glitch i thing whenever there is only my whattsapp account and my bot account on the group only (2) person on the group no one else added to the group then the commands are working just fine

**Comment by binsarjr** [comment]
it's because the group id has changed. I don't know the solution either

**Comment by Piyushdas1624** [comment]
What can I do now ?

**Comment by viniciusgdr** [comment]
> whenever i am adding my bot in some groups and using command like "/help" its not working . But when ever i am texting the bot privately its working fine and i have faced some glitch i thing whenever there is only my whattsapp account and my bot account on the group only (2) person on the group no one else added to the group then the commands are working just fine

Update your baileys...
npm install github:adiwajshing/baileys

**Comment by Piyushdas1624** [comment]
I am using it on heroku so how can I update it
