### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by ThePinkLyna** [adiwajshing/Baileys#895]
Hello, it's me again. Its there any way that the QR code can be outputted to an image file? Because I need to send the code to another device (My console doesn't show it correctly. So I was thinking about an image file) so I think that's the only solution. Its there any way to do so? Thank you in advice.

**Comment by DentaStudio** [comment]
you using a baileys or baileys-multi_device?

**Comment by ThePinkLyna** [comment]
Normal Baileys! Not Multi device!

**Comment by DentaStudio** [comment]
using module qrcode and fs for save qr in to image

try this

```javascript
const qrcode = require('qrcode')
const fs = require('fs')

const generate = async function (input) {
    rawData = await qrcode.toDataURL(input, { scale: 8 })
    dataBase64 = rawData.replace(/^data:image\/png;base64,/, "")
    fs.writeFileSync('qrcode.png', dataBase64, 'base64')
    console.log("Success generate image qr")
}

conn.qr('qr', qr => {
    generate(qr)
})
```

**Comment by ThePinkLyna** [comment]
After some work on my script I managed it to work like a sharm, thank you!
