### ISSUE TITLE
[BUG] [Multi-Device] Audio Error

### ISSUE THREAD

**Issue by ferhacks** [adiwajshing/Baileys#896]
**Describe the bug**
When trying to upload an audio to the WhatsApp servers, it is sent but there is a problem, certain audios do not play, I download the audios in a buffer and then send them, with some it works and with others it does not

**To Reproduce**
1: Request Music
2: Bot send Music
3: Try yo play, but notting play

**Expected behavior**
that the audio plays normally

**Environment (please complete the following information):**
 - Is this on a server? 
 - yes
 - What do your `connectOptions` look like? 
 - Normal
 - Do you have multiple clients on the same IP?
 - yes
 - Are you using a proxy?
 - no

**Additional context**
Nothing

**Comment by DentaStudio** [comment]
i think your option in sock.sendMessage() is wrong

try this mimetype
mp3 = "audio/mpeg"
example:

```javascript
sock.sendMessage(jid, { audio: (buffer) }, { mimetype: "audio/mpeg", mp3: true })
```


if you want send this in format voice note
opus = true (bolean)
example:

```javascript
sock.sendMessage(jid, { audio: (buffer) }, { mimetype: "audio/mpeg", opus: true })
```

cmiiw

**Comment by ferhacks** [comment]
> 

I am using typescript, it tells me that option does not exist

**Comment by hardianto-cpu** [comment]
> i think your option in sock.sendMessage() is wrong
> 
> try this mimetype mp3 = "audio/mpeg" example:
> 
> ```js
> sock.sendMessage(jid, { audio: (buffer) }, { mimetype: "audio/mpeg", mp3: true })
> ```
> 
> if you want send this in format voice note opus = true (bolean) example:
> 
> ```js
> sock.sendMessage(jid, { audio: (buffer) }, { mimetype: "audio/mpeg", opus: true })
> ```
> 
> cmiiw

dont work🙃

**Comment by DentaStudio** [comment]
sorry, maybe try this

```javascript
sock.sendMessage(jid, { audio: (buffer), mimetype: "audio/mpeg", mp3: true})
```

it works for me

**Comment by nuraziz0404** [comment]
`sock.sendMessage(jid, { audio: (buffer), pttAudio: true, mimetype: "audio/mpeg"})`

it works for me
