### ISSUE TITLE
[BUG] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received Undefined

### ISSUE THREAD

**Issue by ravindu01manoj** [adiwajshing/Baileys#898]
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received Undefined

How do i fix this error

![IMG_20211120_235850](https://user-images.githubusercontent.com/88134633/142737270-f706624a-bc1b-4dd1-9084-5ccd496445bc.jpg)

**Comment by VEXG** [comment]
its ur feature problem, not the baileys. the buffer cannot get the buffer from the link. it can be forbidden or something

**Comment by phaticusthiccy** [comment]
If you want to send media messages, then u must use Arraybuffer. Either way firstly you should take buffer data via cheerio, axios, got or another module. 
Finally, u must able to get `< Buffer 00 22 33 11 55 ...>` or `< ArrayBuffer 00 22 33 11 55 ...>`

This is the eventual solution of this error.
