### ISSUE TITLE
[BUG] Device error sending button list

### ISSUE THREAD

**Issue by tiagoandrepro** [adiwajshing/Baileys#899]
List type message is not being sent according to the attached print.

Even if it is required to resend on the device itself, it does not send. Does anyone know why?

![image](https://user-images.githubusercontent.com/4328046/142740307-5c927397-421d-45eb-b24e-bd67752e77a6.png)

`[
            {
                "jid": "mynumber@s.whatsapp.net",
                "t": 1637440844,
                "hasNewMessage": true,
                "messages": [
                    {
                        "key": {
                            "remoteJid": "mynumber@s.whatsapp.net",
                            "fromMe": true,
                            "id": "3EB02331EC35"
                        },
                        "message": {
                            "listMessage": {
                                "description": "Hello it's list message",
                                "buttonText": "Click Me!",
                                "listType": "SINGLE_SELECT",
                                "sections": [
                                    {
                                        "title": "Selecione",
                                        "rows": [
                                            {
                                                "title": "id1",
                                                "description": "Descrição 1",
                                                "rowId": "1"
                                            },
                                            {
                                                "title": "id2",
                                                "description": "Descrição 2",
                                                "rowId": "2"
                                            },
                                            {
                                                "title": "id3",
                                                "description": "Descrição 3",
                                                "rowId": "3"
                                            }
                                        ]
                                    }
                                ]
                            }
                        },
                        "messageTimestamp": "1637440844",
                        "status": "SERVER_ACK"
                    }
                ]`

**Comment by ferhacks** [comment]
Not work on WhatsApp Bussines, install whatsapp normal
