### ISSUE TITLE
Deploy in Heroku and other servers

### ISSUE THREAD

**Issue by eduardobento** [adiwajshing/Baileys#9]
Hi !

I tried to deploy a simple project with Baileys in Heroku, but it seems that module Baileys cannot be installed. The build log is:

```
-----> Pruning devDependencies
       yarn install v1.22.4
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       info fsevents@2.1.2: The platform "linux" is incompatible with this module.
       info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       warning Ignored scripts due to flag.
       Done in 2.28s.
```

But in execution he throws error code: 'MODULE_NOT_FOUND' in files that import Baileys.

Do you know a server that we can deploy ?

Thanks

**Comment by adiwajshing** [comment]
I've used Baileys for a project deployed on AWS Free Tier -- an Ubuntu 18.04 system. Works perfectly. Can you send the execution error log?

**Comment by adiwajshing** [comment]
I'm assuming you've figured the issue out. Closing.

**Comment by eduardobento** [comment]
Sorry this late message. It works perfectly in heroku !

My problem is that I declare ```require("Baileys")``` with B in uppercase. Just change to lower and it works fine.

Stay here the solution.
Thanks

**Comment by eduardobento** [comment]
@adiwajshing , my sugestion is change the ```require('Baileys')``` in readme to ```require('baileys')```.

**Comment by adiwajshing** [comment]
Sure, makes sense.
