### ISSUE TITLE
[MD BUG] QR code appearing even after scanning

### ISSUE THREAD

**Issue by Dakauann** [adiwajshing/Baileys#900]
**Describe the bug**
Im trying to connect using the auth example in example.ts using: useSingleFileAuthState, but when o try to Scan the qrcode, this happens.
![Screenshot_20211120-174841](https://user-images.githubusercontent.com/74578069/142740554-bfdf9d05-8500-4c0b-89be-20b24dd9253c.png)

**To Reproduce**
Explaned How gotten on the discribing 
**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server? No
 - What do your `connectOptions` look like? Do not changed anything
 - Do you have multiple clients on the same IP? No
 - Are you using a proxy? No

**Additional context**

**Comment by burstfreeze** [comment]
Your issue description is incomplete. 

In your case, "To Reproduce" and "Expected behavior" should not be ignored I guess

**Comment by Dakauann** [comment]
> Your issue description is incomplete.
> 
> In your case, "To Reproduce" and "Expected behavior" should not be ignored I guess

I explaned How i got this error when describing It.

**Comment by burstfreeze** [comment]
No, you say the QR code is appearing but all we can see from your screenshot is that the QR code was once printed to the console as it should be. Once you scroll down you will not see the QR code anymore.

**Comment by Dakauann** [comment]
> No, you say the QR code is appearing but all we can see from your screenshot is that the QR code was once printed to the console as it should be. Once you scroll down you will not see the QR code anymore.

I don't think you've seen the full print, if you pay attention to the part that appears 'close' means that I scanned the qr, but it still didn't connect, and on top of that it generated another one.
![Uploading Screenshot_20211120-175801.png…]()

**Comment by burstfreeze** [comment]
Check the error codes, 410 is a baileys internal error code triggering the reconnect after a successful scan, expected behavior.

Copy the full log instead of a partial screenshot

**Comment by Dakauann** [comment]
> Check the error codes, 410 is a baileys internal error code triggering the reconnect after a successful scan, expected behavior.
> 
> Copy the full log instead of a partial screenshot

Where can i fins the error codes?

**Comment by burstfreeze** [comment]
CTRL+Click `loggedOut` in the example.ts or CTRL+F for it.

**Comment by Dakauann** [comment]
> CTRL+Click `loggedOut` in the example.ts or CTRL+F for it.

I tried to scan the qr code again and this was the result of the logs:






{"level":20,"time":1637443541302,"pid":2933,"hostname":"localhost","msg":"pair success recv"}                                                                                     {"level":20,"time":1637443541435,"pid":2933,"hostname":"localhost","msg":"pairing configured successfully"}                                                                       {"level":30,"time":1637443541442,"pid":2933,"hostname":"localhost","jid":"558494740630:52@s.whatsapp.net","msg":"registered connection, restart server"}                          ATUALIZAÇÃO DE CONEXÃO! :  { isNewLogin: true, qr: undefined }                           {"level":30,"time":1637443541448,"pid":2933,"hostname":"localhost","error":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":410,"payload":{"statusCode":410,"error":"Gone","message":"Restart Required"},"headers":{}}},"msg":"connection closed"}       {"level":40,"time":1637443541602,"pid":2933,"hostname":"localhost","msg":"\n            Baileys just created a single file state for your credentials. \n            This will not be supported soon.\n            Please pass the credentials in the config itself\n        "}                                                                                     ATUALIZAÇÃO DE CONEXÃO! :  {                                                               connection: 'close',                                                                     lastDisconnect: {                                                                          error: Error: Restart Required                                                               at WebSocket.<anonymous> (/storage/emulated/0/trash-ts/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:448:17) {                                                      data: null,                                                                              isBoom: true,                                                                            isServer: false,                                                                         output: [Object]                                                                       },                                                                                       date: 2021-11-20T21:25:41.458Z                                                         }                                                                                      }                                                                                        {"level":30,"time":1637443542579,"pid":2933,"hostname":"localhost","msg":"connected to WA Web"}                                                                                   {"level":20,"time":1637443543945,"pid":2933,"hostname":"localhost","msg":"handshake recv from WA Web"}                                                                            {"level":30,"time":1637443543965,"pid":2933,"hostname":"localhost","msg":"handshake complete"}                                                                                    {"level":30,"time":1637443543967,"pid":2933,"hostname":"localhost","msg":"not logged in, attempting registration..."}

**Comment by burstfreeze** [comment]
Either your terminal resets `fs` status after running or the single file state in baileys is temporary.

Check if you can find a `auth_info_multi.json` in your Baileys or working directory

**Comment by Dakauann** [comment]
> Either your terminal resets `fs` status after running or the single file state in baileys is temporary.
> 
> Check if you can find a `auth_info_multi.json` in your Baileys or working directory

I'll test it

**Comment by Dakauann** [comment]
> Either your terminal resets `fs` status after running or the single file state in baileys is temporary.
> 
> Check if you can find a `auth_info_multi.json` in your Baileys or working directory

redid the entire system of connection of baileys md, and managed to fix this error.

**Comment by kythepublic** [comment]
> redid the entire system of connection of baileys md, and managed to fix this error.

How bro? I found the same error.
