### ISSUE TITLE
[MD BUG] Error: forbidden

### ISSUE THREAD

**Issue by Dakauann** [adiwajshing/Baileys#901]
**Describe the bug**
While the process os running, the process stops due to the error: forbidden

**To Reproduce**
1. Make a connection 
2. Start it
3. Wait a little bit

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?no
 - What do your `connectOptions` look like? Dont changed
 - Do you have multiple clients on the same IP?no
 - Are you using a proxy?no

**Additional context**
Log error:

/storage/emulated/0/teste-md/node_modules/@adiwajshing/baileys-md/lib/WABinary/index.js:289                                                                                               throw new boom_1.Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code });                                                                                            ^                                                                          Error: forbidden                                                                             at assertNodeErrorFree (/storage/emulated/0/teste-md/node_modules/@adiwajshing/baileys-md/lib/WABinary/index.js:289:15)                                                           at query (/storage/emulated/0/teste-md/node_modules/@adiwajshing/baileys-md/lib/Socket/socket.js:147:48)                                                                          at runMicrotasks (<anonymous>)                                                           at processTicksAndRejections (node:internal/process/task_queues:96:5)                    at async Object.groupMetadata (/storage/emulated/0/teste-md/node_modules/@adiwajshing/baileys-md/lib/Socket/groups.js:20:24) {                                                  data: 403,                                                                               isBoom: true,                                                                            isServer: true,                                                                          output: {                                                                                  statusCode: 500,                                                                         payload: {                                                                                 statusCode: 500,                                                                         error: 'Internal Server Error',                                                          message: 'An internal server error occurred'                                           },                                                                                       headers: {}                                                                            }                                                                                      }                                                                                        npm ERR! code ELIFECYCLE                                                                 npm ERR! errno 1                                                                         npm ERR! trash-md@1.0.0 start: `ts-node main.ts`                                         npm ERR! Exit status 1                                                                   npm ERR!                                                                                 npm ERR! Failed at the trash-md@1.0.0 start script.                                      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                                                         npm ERR! A complete log of this run can be found in:                                     npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2021-11-20T22_10_46_546Z-debug.log

**Comment by burstfreeze** [comment]
Again, please post the log as text. Your uploads do not work and it is harder for us to read logs from images than via text.

**Comment by Dakauann** [comment]
> Again, please post the log as text. Your uploads do not work and it is harder for us to read logs from images than via text.

Ok, I didn't know it was worse for you to read.

**Comment by DentaStudio** [comment]
oh man, can you send this log in to image? picture of your terminal?

this is really so hard for read this log

**Comment by Dakauann** [comment]
> oh man, can you send this log in to image? picture of your terminal?
> 
> this is really so hard for read this log

The onde guy behind said the opposite
