### ISSUE TITLE
Devices out of sync. There may be a problem with your phone clock.

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#902]
### Devices out of sync. There may be a problem with your phone clock.
- On my smartphone it shows 10 am
- On my hosting (replit) it shows 3 am
```js
console.log(new Date().getHours())
// 3
```
Any ideas to work around it ?
Like adding a module

![IMG-20211121-WA0048](https://user-images.githubusercontent.com/80396521/142749047-3e966636-52ad-412b-abb9-4d53ddefda0d.jpg)

**Comment by DentaStudio** [comment]
repl.it servers are overseas, and follow UTC hours
while you are in Indonesia (maybe WIB/WITA/WIT)
and the time zone is very different

maybe that's the reason why the clock is not in sync

**Comment by frmdeveloper** [comment]
> repl.it servers are overseas, and follow UTC hours. you are in Indonesia (maybe WIB/WITA/WIT) and the time zone is very different. maybe that's the reason why the clock is not in sync
> 
> the solution is to just change the place to host your script which is near your country such as hosting in Singapore, etc
> 
> if you just let it go, the chances of getting banned will be high because you suspect that a device has access to your WhatsApp and it's far from your phone

If left alone, the session will exit automatically. 
I have read the information
