### ISSUE TITLE
Issue in the new auth system?

### ISSUE THREAD

**Issue by jackcokk** [adiwajshing/Baileys#907]
Either the new auth system needs a small example or there is some error in it.

Right now, if I pass a function to save to my database, the `save` event only writes the `creds` part of the state to the db, resulting in `Cannot read property 'me' of undefined` at `/socket.ts`.

Are we supposed to have 2 different entries now, one for `creds` and one for `keys`? If so, in what way does the event tell us which kind of entry is to be updated?

Instead of doing `state = state || sock?.authState` just doing `state = sock?.authState` made the scan work but is that how we are supposed to handle that? Or is there some other way to know what kind of update is taking place?

**Comment by azudindaem** [comment]
use latest commit and refer to example.ts for new implementation

**Comment by jackcokk** [comment]
That is the point, the example does not showcase the new system

**Comment by Dakauann** [comment]
> That is the point, the example does not showcase the new system

It does

**Comment by itacirgabral** [comment]
little demo: https://github.com/itacirgabral/baileysVanilla
- signup read the qrcode and stay connected
- start read creds file and stay connected

https://github.com/adiwajshing/Baileys/blob/multi-device/src/Utils/auth-utils.ts#L98-L133

caution. shared state in recursive loop may cause memory leak.

**Comment by jackcokk** [comment]
@Dakauann 
> It does

No, what you see in the example is the single-file auth state that re-saves the whole file every time something changes. The idea of the new system is that it only updates the parts that are required to update, saving costly disk writes

**Comment by muzafferkadir** [comment]
> little demo: https://github.com/itacirgabral/baileysVanilla
> 
> * signup read the qrcode and stay connected
> * start read creds file and stay connected
> 
> https://github.com/adiwajshing/Baileys/blob/multi-device/src/Utils/auth-utils.ts#L98-L133
> 
> caution. shared state in recursive loop may cause memory leak.

Hi i want to save my creds not into `auth_info_multi` file, into database (mongodb) how can i save this any suggestion?
