### ISSUE TITLE
generateWAMessage

### ISSUE THREAD

**Issue by hardianto-cpu** [adiwajshing/Baileys#908]
How Generate video, image message use function `prepareMessageMedia`

i try dont work
![Screenshot_2021-11-22-07-57-10-284_com microsoft rdc android](https://user-images.githubusercontent.com/74147602/142786713-cd0e991b-6824-48d3-9544-b4142f8d128d.jpg)

**Comment by BochilGaming** [comment]
add option ```js { upload: waUploadToServer } ```

**Comment by hardianto-cpu** [comment]
> 

value isBuffer?

**Comment by BochilGaming** [comment]
> > 
> 
> value isBuffer?

value for what?

**Comment by rashidsiregar28** [comment]
Add options { upload }

Example:

`let prepare = await generateWAMessage(id, content, {upload: chika.waUploadToServer})`

Its work for me

**Comment by hardianto-cpu** [comment]
> Add options { upload }
> 
> Example:
> 
> `let prepare = await generateWAMessage(id, content, {upload: chika.waUploadToServer})`
> 
> Its work for me

ok thanks
