### ISSUE TITLE
[BUG] Error when downloading content from message (BAILEYS MD)

### ISSUE THREAD

**Issue by DentaStudio** [adiwajshing/Baileys#909]
when i start this code 

```javascript
baileys.downloadContentFromMessage('./image.jpeg', (JSON.parse(JSON.stringify(data.chat.message.extendedTextMessage.contextInfo).replace('quotedM', 'm'))), 'image')
```

i get this error
![Screenshot_2021-11-22-12-20-09-05.jpg](https://user-images.githubusercontent.com/69065410/142801169-9e0a7586-0e19-433e-9d26-27f19d3cf629.jpg)

how to download content from message?

**Comment by BochilGaming** [comment]
> when i start this code
> 
> ```js
> baileys.downloadContentFromMessage('./image.jpeg', (JSON.parse(JSON.stringify(data.chat.message.extendedTextMessage.contextInfo).replace('quotedM', 'm'))), 'image')
> ```
> 
> i get this error ![Screenshot_2021-11-22-12-20-09-05.jpg](https://user-images.githubusercontent.com/69065410/142801169-9e0a7586-0e19-433e-9d26-27f19d3cf629.jpg)
> 
> how to download content from message?
```js
const fs = require('fs')
const { downloadContentFromMessage } = require('@adiwajshing/baileys-md') 
const stream = await downloadContentFromMessage(m.message.imageMessage, 'image')
        let buffer = Buffer.from([])
        for await(const chunk of stream) {
            buffer = Buffer.concat([buffer, chunk])
        }
        // save to file
        await fs.writeFileSync('./my-download.jpeg', buffer)
```

**Comment by DentaStudio** [comment]
thx, this work
