### ISSUE TITLE
how to make button

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#911]
how to make this button loc
![IMG_20211122_154229_724](https://user-images.githubusercontent.com/90820338/142830719-143f34d7-d0da-410e-b511-743e9fd6d040.jpg)

**Comment by ekoeryanto** [comment]
search it before, kak.
https://github.com/adiwajshing/Baileys/pull/584

**Comment by scoder37** [comment]
aku bsa bkin button loc,doc,video,image nah aku lgi cari pencerahan soal itu.
itu yg bagian klik website itu kayak hydrate template. tp msh bingung satuinnya dengan fakeloc dan button

**Comment by hardianto-cpu** [comment]
> aku bsa bkin button loc,doc,video,image nah aku lgi cari pencerahan soal itu. itu yg bagian klik website itu kayak hydrate template. tp msh bingung satuinnya dengan fakeloc dan button

> i made with proto

**Comment by scoder37** [comment]
example pls

**Comment by rashidsiregar28** [comment]
> example pls

Open on [this](https://adiwajshing.github.io/Baileys/classes/proto.templatebutton.html)

**Comment by scoder37** [comment]
oke thanks you
