### ISSUE TITLE
[BUG] send a sticker via buffer only one time

### ISSUE THREAD

**Issue by rashidsiregar28** [adiwajshing/Baileys#914]
Try send sticker from buffer but only send for one time after run a script

`conn.sendMessage(id, { sticker: fs.readFileSync('./sticker.webp')})`

Log eror 

`{"level":20,"time":1637639231696,"pid":3096,"hostname":"CPC-xfar-HBH-IN","msg":"Error in uploading to media-ort2-2.cdn.whatsapp.net (HTTPError: Response code 415 (Unsupported Media Type)) , retrying..."}`

But i try send sticker from url, its work any time

`conn.sendMessage(id, { sticker: { url: https://web.id/sticker.webp' } })`

**Comment by azudindaem** [comment]
Yes. At this momment use only url for all media messages
