### ISSUE TITLE
How to upload authState

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#921]
How do I save the authState then upload it to my website? 
```js 
sock.ev.on('creds.update', saveState) 
``` 
So what? 
___
I used to use this, now this feature has been removed 
```js
sock.ev.on('auth-state.update', async() => {
     await uploadFile(JSON.stringify(sock.authState), 'session.json')
     saveState(sock.authState)
})
```

uploadFile(JSON.stringify(sock.authState), 'session.json')

**Comment by frmdeveloper** [comment]
Hooooooooooooww

**Comment by burstfreeze** [comment]
I don't know how the rest of your code looks like but sock should have an auth property that you can save in full.

**Comment by itacirgabral** [comment]
https://github.com/adiwajshing/Baileys/issues/907#issuecomment-977181179

**Comment by frmdeveloper** [comment]
```js
fs.watchFile('ses.json', async() => {
	await uploadFilee(JSON.stringify(state, BufferJSON.replacer, 2), 'ses.json')
})
```
