### ISSUE TITLE
add fitur call

### ISSUE THREAD

**Issue by affisjunianto** [adiwajshing/Baileys#924]
try adding the call feature to the whatsapp web. so that everyone can add the call music feature. like discord

**Comment by Zobin33** [comment]
This Lib Is Not A Whatsapp Web, But Whatsapp Web Api, Idiots

**Comment by DentaStudio** [comment]
bruh, baileys using a WebSocket, not API

**Comment by Zobin33** [comment]
> bruh, baileys using a WebSocket, not API

Is A Whatsapp Web Api, But Using WebSocket Lol

**Comment by Zobin33** [comment]
![Screenshot_2021-11-27-18-38-31-211_com android chrome](https://user-images.githubusercontent.com/48700650/143679623-800f6988-4be1-4496-8975-cbb417c9cb23.jpg)

**Comment by kbiits** [comment]
> ![Screenshot_2021-11-27-18-38-31-211_com android chrome](https://user-images.githubusercontent.com/48700650/143679623-800f6988-4be1-4496-8975-cbb417c9cb23.jpg)
> 

Read more about API idiots

**Comment by Zobin33** [comment]
basically baileys can't add a phone because on the whatsapp web itself there is no call feature

**Comment by VEXG** [comment]
> bruh, baileys using a WebSocket, not API

![image](https://user-images.githubusercontent.com/83714022/143680172-41b3bb10-5470-4326-b4a1-20f72a27168f.png)

dumb.

**Comment by kbiits** [comment]
> > bruh, baileys using a WebSocket, not API
> 
> ![image](https://user-images.githubusercontent.com/83714022/143680172-41b3bb10-5470-4326-b4a1-20f72a27168f.png)
> 
> dumb.

Yo idiots, learn more what is API before talking about it

**Comment by VEXG** [comment]
> > > bruh, baileys using a WebSocket, not API
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/83714022/143680172-41b3bb10-5470-4326-b4a1-20f72a27168f.png)
> > dumb.
> 
> Yo idiots, learn more what is API before talking about it

chill ;/

**Comment by DentaStudio** [comment]
hhhh chill, chill

sorry if wrong

**Comment by SanzGantengz** [comment]
> hhhh chill, chill
> 
> sorry if wrong

WOW

**Comment by DentaStudio** [comment]
anjir lu @SanzGantengz ada dimana mana

**Comment by frmdeveloper** [comment]
> basically baileys can't add a call feature because on the whatsapp web itself there is no call feature

I once made a call using WhatsApp on my computer

**Comment by frmdeveloper** [comment]
> bruh, baileys using a WebSocket, not API

wss://web.whatsapp.com

**Comment by frmdeveloper** [comment]
> anjir lu @SanzGantengz ada dimana mana

ya iya lah
Gue sering liat dia di whatsapp

**Comment by Fau-Zan** [comment]
> anjir lu @SanzGantengz ada dimana mana

Ngapain den?

**Comment by ThisMe124** [comment]
Waw

**Comment by WahyuPR0** [comment]
Bjir aowkwkwk Kon** emg

**Comment by DentaStudio** [comment]
> > anjir lu @SanzGantengz ada dimana mana
> 
> Ngapain den?

lagi ngoding

**Comment by SanzGantengz** [comment]
> anjir lu @SanzGantengz ada dimana mana

Awoakwoakawoakwo

**Comment by SanzGantengz** [comment]
> > anjir lu @SanzGantengz ada dimana mana
> 
> ya iya lah Gue sering liat dia di whatsapp

Woah

**Comment by scoder37** [comment]
ada yg tau doc baileys md

**Comment by ikbal-hanafi** [comment]
> 

setau w belum di buatjn docsnya soalnya masih mode pengembangan, lagian kalau udah kelas bakalan langsung di pindahkan ke branch utama

**Comment by BranGamer145** [comment]
OMGH

**Comment by DentaStudio** [comment]
> ada yg tau doc baileys md

[](https://discord.com/channels/725839806084546610/891299313932722247/914851409856446525)

**Comment by DentaStudio** [comment]
> ada yg tau doc baileys md

join discord nya baileys, cek channel #baileys-md terus liat pin. disitu ada di pin docs nya

**Comment by frmdeveloper** [comment]
> join discord nya baileys, cek channel #baileys-md terus liat pin. disitu ada di pin docs nya

Mana link discrod nya ?
