### ISSUE TITLE
[BUG] Message : TypeError: Cannot read property 'stanzaId' of null

### ISSUE THREAD

**Issue by Adiixyz** [adiwajshing/Baileys#927]
**Describe the bug**

**To Reproduce**
1. Created a new connection
2. Closed & used saved credentials to log back in
3. Etc.

**Expected behavior**

**Environment (please complete the following information):**
 - Is this on a server?
 - What do your `connectOptions` look like? 
 - Do you have multiple clients on the same IP?
 - Are you using a proxy?

**Additional context**

**Comment by phaticusthiccy** [comment]
Can you share whole code?

**Comment by Adiixyz** [comment]
> Can you share whole code?

bot code?

**Comment by phaticusthiccy** [comment]
Yeah, can you post the code of the part where you got the error.
