### ISSUE TITLE
help

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#929]
example hydrated message pls

**Comment by frmdeveloper** [comment]
> example hydrated message pls

Only whatsapp multi device

**Comment by scoder37** [comment]
yes im build md

**Comment by scoder37** [comment]
i need example

**Comment by BochilGaming** [comment]
> i need example

#931

**Comment by frmdeveloper** [comment]
> example hydrated message pls

https://github.com/adiwajshing/Baileys/issues/931#issuecomment-980812232

Use that

**Comment by Zobin33** [comment]
> example hydrated message pls

Pls close the issue
