### ISSUE TITLE
How to properly use client.loadConversation()

### ISSUE THREAD

**Issue by kaykyr** [adiwajshing/Baileys#93]
Hello!

In some chats, when I try to load conversation from a index I get this error:

```bash
Quering from message ID 3AB411D3EDBB6638140D
(node:32438) UnhandledPromiseRejectionWarning: Error: error in query, got status: 404
    at WhatsAppWebMessages.<anonymous> (/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/baileys/lib/WAClient/Base.js:278:35)
    at step (/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/baileys/lib/WAClient/Base.js:46:23)
    at Object.next (/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/baileys/lib/WAClient/Base.js:27:53)
    at fulfilled (/Users/kaykyramos/Desktop/WhatsApp-Socket/node_modules/@adiwajshing/baileys/lib/WAClient/Base.js:18:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:32438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is my code:

```javascript
async getEarlier(thread, data) {
		const { parentPort, event } = thread
		const { session, chat, id, decrypt, includeMe } = data

		State.currentChat = chat

		const client = await this.getClient(session)

		console.log(`Quering from ID ${id}`)

		const _conversation = await client.loadConversation(chat, 25, {
			id,
			fromMe: includeMe,
		})

		const conversation = await MessageController.formatConversation(
			_conversation,
			client,
			decrypt
		)

		parentPort.postMessage({
			event,
			response: {
				conversation,
			},
		})
	}
```

I am using this function incorrectly?

This works fine for some messages, but not for some others.

**Comment by adiwajshing** [comment]
I'm also debugging the same issue right now. Can you reproduce the issue? Or is it random

**Comment by kaykyr** [comment]
> I'm also debugging the same issue right now. Can you reproduce the issue? Or is it random

It's isn't random, this always happens with the same message ID code. In my example I tried with this message ID: `3AB411D3EDBB6638140D`

**Comment by kaykyr** [comment]
Hello!

Looks like this always happens with some chats, independent of message ID.

For example:
John Appleseed (1404400004@c.us) <== this will aways happens with this chat.

**Comment by adiwajshing** [comment]
Very interesting, I’m looking into it. This happens when you provide a cursor or without a cursor as well?

**Comment by kaykyr** [comment]
> Very interesting, I’m looking into it. This happens when you provide a cursor or without a cursor as well?
> […](#)
> On Aug 7, 2020, at 12:29 AM, Kayky Ramos ***@***.***> wrote: ﻿ Hello! Looks like this always happens with some chats, independent of message ID. For example: John Appleseed ***@***.***) <== this will aways happens with this chat. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

This happens only when I provide a cursor.

**Comment by adiwajshing** [comment]
Okay -- have you tried switching the `fromMe` field? Set it to `true` and `false` and see if it works

**Comment by kaykyr** [comment]
> Okay -- have you tried switching the `fromMe` field? Set it to `true` and `false` and see if it works

I'll try it, but I am requesting with `fromMe: true`, it's important in this case.

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing.
