### ISSUE TITLE
[BUG] no respon

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#930]
how to solve the message sometimes not detected in console log? I run the bot, then I try to type the sticker command and it works, now I try again typing the sticker command in the group or in private messages but the bot doesn't respond, the console log terminal also doesn't detect any incoming messages

**Comment by DentaStudio** [comment]
![Screenshot_2021-11-27-23-26-37-74_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/69065410/143688121-273ffdc5-809b-4088-8eff-c9e6659f32d1.jpg)

i get this error after use command sticker

maybe this is the cause of the message not being detected
