### ISSUE TITLE
[MD] Req

### ISSUE THREAD

**Issue by amiruldev20** [adiwajshing/Baileys#931]
example button hydrated pls

**Comment by BochilGaming** [comment]
> example button hydrated pls

```js
const { generateWAMessageFromContent, proto } = require('@adiwajshing/baileys-md')
    const template = generateWAMessageFromContent(m.key.remoteJid, proto.Message.fromObject({
        templateMessage: {
            hydratedTemplate: {
                hydratedContentText: 'Testing',
                hydratedButtons: [{
                    urlButton: {
                        displayText: 'test',
                        url: 'whatsapp://send?text=HI'
                    }
                }, {
                    callButton: {
                        displayText: 'call ...',
                        phoneNumber: '+62 8733'
                    }
                },
                {
                    quickReplyButton: {
                        displayText: 'Hii',
                        id: 'id1'
                    }
                }
                ]
            }
        }
    }), { userJid: m.participant || m.key.remoteJid, quoted: m });
    return await conn.relayMessage(
        m.key.remoteJid,
        template.message,
        { messageId: template.key.id }
    )
```

**Comment by scoder37** [comment]
uh tq

**Comment by Denver1997** [comment]
> > example button hydrated pls
> 
> ```js
> const { generateWAMessageFromContent, proto } = require('@adiwajshing/baileys-md')
>     const template = generateWAMessageFromContent(m.key.remoteJid, proto.Message.fromObject({
>         templateMessage: {
>             hydratedTemplate: {
>                 hydratedContentText: 'Testing',
>                 hydratedButtons: [{
>                     urlButton: {
>                         displayText: 'test',
>                         url: 'whatsapp://send?text=HI'
>                     }
>                 }, {
>                     callButton: {
>                         displayText: 'call ...',
>                         phoneNumber: '+62 8733'
>                     }
>                 },
>                 {
>                     quickReplyButton: {
>                         displayText: 'Hii',
>                         id: 'id1'
>                     }
>                 }]
>             }
>         }
>     }), { userJid: m.participant || m.key.remoteJid, quoted: m });
>     return await conn.relayMessage(
>         m.key.remoteJid,
>         template.message,
>         { messageId: template.key.id }
>     )
> ```

its working on normal whatsapp login or beta mode?
