### ISSUE TITLE
How to send catalogue

### ISSUE THREAD

**Issue by SL-Alpha-X** [adiwajshing/Baileys#939]
`▫️️How to send catalogue using baileys. `

**Comment by phaticusthiccy** [comment]
I couldn't see any document for catalog messages. If you arent using MD, there is the supported message types:

**string | WATextMessage | WALocationMessage | WAContactMessage | WAContactsArrayMessage | WAGroupInviteMessage | WAMediaUpload | WAListMessage | WAButtonsMessage** 

Just recode these for your source.

**Comment by SL-Alpha-X** [comment]
Ok thanks
