### ISSUE TITLE
[ MD ] HOW TO TAG FROM generateWAMessageFromContent()

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#944]
how to tag in hydrate button location
![Screenshot_20211130-065302](https://user-images.githubusercontent.com/90820338/143961223-2900af92-d7e2-4140-9a50-eb5346682564.png)

**Comment by Zobin33** [comment]
{quoted: WAMessage{}}

**Comment by scoder37** [comment]
quoted from

generateWAMessageFromContent()
