### ISSUE TITLE
[ MD ] [Question] Docs Of Multi Device

### ISSUE THREAD

**Issue by Zobin33** [adiwajshing/Baileys#945]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

Hi There, My Question Is "Where The Docs Of Baileys Multi Device", 

Sometime I Find Something Harder Like "this.loadMessage", i was read the readme.md, to get message using "getMessageFromStore", but it wont work, cause in "Baileys" or "makeWASocket" Is "Undefined", 

i find how to get all messages but not found it, "So I Hope Adiwajshing Create Some Docs For Baileys MD"

:)

**Comment by azudindaem** [comment]
Do not ask for Docs right now.. and never use md for production yet.. it is not ready .. take your time to read instruction and use example.ts then you will be good..  as per loadMessage, its only valid for legacy (non-md)

**Comment by Zobin33** [comment]
> Do not ask for Docs right now.. and never use md for production yet.. it is not ready .. take your time to read instruction and use example.ts then you will be good.. as per loadMessage, its only valid for legacy (non-md)

Ok Thanks
