### ISSUE TITLE
Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#948]
npm install
![Screenshot_20211201-155229](https://user-images.githubusercontent.com/80396521/144202522-0396c6dd-0886-4a2b-89ff-5cef14be8882.png)
___
node index.js
![Screenshot_20211201-155241](https://user-images.githubusercontent.com/80396521/144202544-c35a6a88-fb6a-4cf6-8f54-0248bdca19a7.png)

___
my device
![Screenshot_20211201-155704](https://user-images.githubusercontent.com/80396521/144203125-57f8d034-282c-47b5-92b7-d6c0065b499d.png)

**Comment by DentaStudio** [comment]
first, build this module with tsc

```bash
$ npm install typescript typedoc -g
$ cd ./node_modules/@adiwajshing/baileys-md
$ npm run build:all
```

**Comment by frmdeveloper** [comment]
![Screenshot_20211201-185525](https://user-images.githubusercontent.com/80396521/144230285-03d54733-10dd-4e8b-91ed-4e70064ccd23.png)

![Screenshot_20211201-185544](https://user-images.githubusercontent.com/80396521/144230280-7bb7f90a-2834-4de4-8d8a-ee82c8694b54.png)

**Comment by JimmyBastos** [comment]
Add this to your script session in `package.json`

`"postinstall": "cd ./node_modules/@adiwajshing/baileys-md && npm install &> /dev/null"`

**Comment by zennn08** [comment]
Maybe this can help:
first you have to install yarn
`$ npm install yarn -g`
Then,
`$ yarn add github:adiwajshing/baileys#multi-device
$ cd node_modules/@adiwajshing/baileys-md
$ yarn`

Then you can go back to the root folder and run your script as usual

**Comment by frmdeveloper** [comment]
> Maybe this can help: first you have to install yarn
> 
> > $ npm install yarn -g
> > Then,
> > $ yarn add github:adiwajshing/baileys#multi-device
> > $ cd node_modules/@adiwajshing/baileys-md
> > $ yarn
> 
> Then you can go back to the root folder and run your script as usual

Sama aja bos

**Comment by zennn08** [comment]
> > Then you can go back to the root folder and run your script as usual
> 
> Sama aja bos

It worked for me and I'm just sharing my way to solve this problem

**Comment by frmdeveloper** [comment]
github-action ugly
