### ISSUE TITLE
BUG ?

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#949]
is this a bug? sometimes after many console logs save auth state in cmd sometimes it lags (must be entered) to console the latest messages

![Screenshot_20211201-183552](https://user-images.githubusercontent.com/90820338/144228426-961b3207-6d1c-41a8-b760-285f8d24f5f0.png)

**Comment by itacirgabral** [comment]
every message update your creds keys increasing the .json size.
the blocking saveState will take longer may cause console hanging.

**Comment by scoder37** [comment]
do you have a solution? sometimes if it doesn't lag in console.log auth stated yes closed option (must be rerun)

**Comment by itacirgabral** [comment]
> every message (...) increase the .json size.
NO! I'm wrong. It was fixed https://github.com/adiwajshing/Baileys/commit/efc7dffbebcfaa6b2eef2e1fa9035715c2f53f48

I'm not sure if I understand your question correctly.

saving auth state on every message is normal. It is not a problem.

Saving the full creds.json will stun you by (json size) / (hd speed):
- json = 0.1 mb
- hd = 100 mb/s
- stun = 0.001 seconds

if you have several connections in one process, each one will add stun.

you can write your own saveState to do not log it
- https://github.com/adiwajshing/Baileys/blob/multi-device/src/Utils/auth-utils.ts#L99-L133
- https://github.com/itacirgabral/baileysVanilla/blob/master/src/saveSignup.ts

**Comment by scoder37** [comment]
thank you for the answer, I have found a solution so that the bot continues to run even though the process of saving old json

**Comment by scoder37** [comment]
can you help me in this issue
https://github.com/adiwajshing/Baileys/issues/944
