### ISSUE TITLE
Small bug with downloadMediaMessage for productMessage

### ISSUE THREAD

**Issue by Nobilitate** [adiwajshing/Baileys#95]
First, thanks for making such a great library. It's incredibly cool and useful, and I'm having a lot of fun using it.
You seem to be contributing to and improving it quite often, which is very much noticed and appreciated.

---

I ran into a bit of a snag when attempting to download media for a `productMessage`.

In `decodeMediaMessageBuffer` there is some extra logic around `productMessage` to correctly set `messageContent` to its `productImage` property:
https://github.com/adiwajshing/Baileys/blob/master/src/WAClient/Utils.ts#L120-L126

This seems to work quite well.

After that, we then attempt to get the extension in `extensionForMediaMessage`:
https://github.com/adiwajshing/Baileys/blob/master/src/WAClient/Utils.ts#L172-L177

And we encounter the same scenario, where it needs the same special treatment when it's a `productMessage`.

However, it is missing that part in `extensionForMediaMessage` and only attempts `message[type]`.. which becomes `message[productMessage]`, which does not have the needed`mimetype` property for `getExtension`:

```
        const messageContent = message[type] as
                                | proto.VideoMessage
                                | proto.ImageMessage
                                | proto.AudioMessage
                                | proto.DocumentMessage
        extension = getExtension (messageContent.mimetype)
```

Hence, we get a Type Error at 
```
TypeError: Cannot read property 'split' of undefined
    at getExtension (/app/node_modules/@adiwajshing/baileys/lib/WAClient/Utils.js:198:49)
    at Object.extensionForMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/WAClient/Utils.js:209:21)
    at WhatsAppWebMessages.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/WAClient/Messages.js:376:35)
```

---

Hope this is helpful. Happy to provide more info if need be.

**Comment by adiwajshing** [comment]
Ah thanks so much for bringing this to notice. If you're up for it, you could submit a PR?

**Comment by adiwajshing** [comment]
Has been taken care of in the latest commit. Closing.

**Comment by Nobilitate** [comment]
Hey sorry I've only been working on these things on the weekends. Thanks for taking care of it!
