### ISSUE TITLE
Blocking the sending of images 

### ISSUE THREAD

**Issue by neocomun** [adiwajshing/Baileys#950]
Não consigo mais enviar mensagens com mídias (fotos/vídeos).
Fiquei sabendo que o whatsapp está bloqueando quando o envio é feito em massa.

Alguem sabe de alguma solução para resolver isso? Meu sistema envia a mensagem utilizando um temporizador, mas mesmo assim não estão sendo enviadas. Poderiam me ajudar?

I can no longer send messages with media (photos/videos).
I learned that whatsapp is blocking when sending in bulk.

Does anyone know of any solution to resolve this? My system sends the message using a timer, but it's still not being sent. can you help me?

**Comment by itacirgabral** [comment]
mano, escreve em inglês... Mesmo se vc copiar do tradutor do google já tá bom

![gretchen](https://user-images.githubusercontent.com/6052177/144251204-b8f1cc60-40cd-4284-bda4-4deed147a9a9.jpeg)

do you send the same image to everyone?
are you using `forward message`? 
how many messages are you sending? how much time is the interval?
how many messages were sent to block your images? Are there any errors?
can you send text message after the block?

**Comment by neocomun** [comment]
Thanks for replying friend!

**Do you send the same image to everyone?**
Yes, I send the same message to all customers.

**Are you using forward message?**
No, I'm using it as a new image submission

**how many messages are you sending? how much time is the interval?**
Usually 100 messages, but I always put a 20 second timeout for each post

**how many messages were sent to block your images? Are there any errors?**
In fact, regardless of the amount of submissions made to the whatsapp account, it is blocking. There are no errors, it just doesn't send.

**can you send text message after the block?**
Text messages are going smoothly, only messages with media like, image, video and pdf are not being sent.

**Comment by itacirgabral** [comment]
is the first image blocked too?

you can try prototype a demo:
```typescript
const fs = require('fs')
const { WAConnection, MessageType, Mimetype } = require('@adiwajshing/baileys')

const someone = '554433221100@s.whatsapp.net'
const image = fs.readFileSync(require('path').join(__dirname, 'gretchen.jpeg'))
const messageType = MessageType.image
const options = {
  mimetype: Mimetype.image,
  filename: 'gretchen.jpeg'
}

;(async () => {
    const conn = new WAConnection()

    await conn.connect()

    setTimeout(() => {
        console.log('bep')
        conn
          .sendMessage (someone, image, messageType, options)
          .then(console.dir)
          .catch(console.erro)
    }, 1_000)
})()
```
https://github.com/itacirgabral/baileysissues950

**Comment by neocomun** [comment]
Strange, I use the same method. Could you check? Can I hire him to do this maintenance?

**Comment by neocomun** [comment]
wa.me/5531995914109

**Comment by itacirgabral** [comment]
thanks so much but my boss will kill me 😵

you can find bailyes genius here:
https://discord.gg/fsPEer3g

if you publish your code we can work for free(dom)

**Comment by neocomun** [comment]
Thank you for your help

**Comment by Ethernit** [comment]
Tenho um grupo de dev me chama no WhatsApp  73 91776616

**Comment by LightningNeko** [comment]
I had the same problem, I solved it by changing 
"let uploadInfo = await refreshMediaConn(false);" 
to
"let uploadInfo = await refreshMediaConn(true);"
in lib/Socket/message-send.js:318

**Comment by neocomun** [comment]
Strange, which way would this be?
node_modules/@adiwajshing/baileys/lib/WAConnection/6.MessagesSend.js
On line 192 I have
`try {
                const { body: responseText } = await this.fetchRequest(url, 'POST', fs_1.createReadStream(encBodyPath), options.uploadAgent, { 'Content-Type': 'application/octet-stream' });
                const result = JSON.parse(responseText);
                mediaUrl = result === null || result === void 0 ? void 0 : result.url;
                if (mediaUrl)
                    break;
                else {
                    json = await this.refreshMediaConn(true);
                    throw new Error(`upload failed, reason: ${JSON.stringify(result)}`);
                }
            }
            catch (error) {
                const isLast = host.hostname === json.hosts[json.hosts.length - 1].hostname;
                this.logger.error(`Error in uploading to ${host.hostname} (${error}) ${isLast ? '' : ', retrying...'}`);
            }`
 

I didn't find lib/Socket/
