### ISSUE TITLE
When i am trying to send any Gif or Mp4 video then whatsapp is not rendering it.

### ISSUE THREAD

**Issue by Krakinz** [adiwajshing/Baileys#953]
Once i sent the file (gif,mp4) via the api, the video doesnt render aka run.
It is just a static video.
Video doesnt even run but the size of the video file is perfect.
Any help would be useful.
Thanks

**Comment by phaticusthiccy** [comment]
Hi
Can you send the code? Also if you want to send gifs, u must use `mimetype: Mimetype.gif` to .mp4 files.

**Comment by Krakinz** [comment]
> Hi Can you send the code? Also if you want to send gifs, u must use `mimetype: Mimetype.gif` to .mp4 files.


```
EXAMPLE WITH GIF LINK:

const { MessageType, Mimetype } = require(`@adiwajshing/baileys`);
module.exports = {
  name: `ultron`,
  description: `test ultron`,
  υℓтяσηʍօʀɛ: `test ultron`,
  async handle(υℓтяσηℓιєηт, chat, ᴜʟᴛʀᴏɴ, args) {
    await υℓтяσηℓιєηт.sendMessage(
      ᴜʟᴛʀᴏɴ.chatId,
      { url: "https://i.postimg.cc/G2SZsJ7Z/image.gif" },
      MessageType.video,
      { mimetype: Mimetype.gif, caption: `Test GIF Command` }
    );
  },
};


```

**Comment by Krakinz** [comment]
Sorry for mistake....

EXAMPLE WITH GIF LINK:

const { MessageType, Mimetype } = require(`@adiwajshing/baileys`);
module.exports = {
  name: `ultron`,
  description: `test ultron`,
  υℓтяσηʍօʀɛ: `test ultron`,
  async handle(υℓтяσηℓιєηт, chat, ᴜʟᴛʀᴏɴ, args) {
    await υℓтяσηℓιєηт.sendMessage(
      ᴜʟᴛʀᴏɴ.chatId,
      { url: "https://i.postimg.cc/G2SZsJ7Z/image.gif" },
      MessageType.video,
      { mimetype: Mimetype.gif, caption: `Test GIF Command` }
    );
  },
};

**Comment by phaticusthiccy** [comment]
You can use axios to get arraybuffer. Then you can send it using this example:

```js
axios.get("url").then(async (buff) => { await conn.sendMessage(id, Buffer.from(buff.data), MessageType.video, { mimetype: Mimetype.gif}) })
```

**Comment by Krakinz** [comment]
Damn ...
Thank You So Much Sir..

**Comment by Krakinz** [comment]
> You can use axios to get arraybuffer. Then you can send it using this example:
> 
> ```js
> axios.get("url").then(async (buff) => { await conn.sendMessage(id, Buffer.from(buff.data), MessageType.video, { mimetype: Mimetype.gif}) })
> ```

Even After i am habing ffmpeg and also inside linux
Bot Shows *ENOENT: no such file or directory, open '/tmp/3EB09FD310E4.jpg'*
Any Further Help Would be great

**Comment by Krakinz** [comment]
> You can use axios to get arraybuffer. Then you can send it using this example:
> 
> ```js
> axios.get("url").then(async (buff) => { await conn.sendMessage(id, Buffer.from(buff.data), MessageType.video, { mimetype: Mimetype.gif}) })
> ```

Even After i am habing ffmpeg and also inside linux
Bot Shows *ENOENT: no such file or directory, open '/tmp/3EB09FD310E4.jpg'*
Any Further Help Would be great
