### ISSUE TITLE
how to send PDF ?  In multidevice 

### ISSUE THREAD

**Issue by mateuscdor** [adiwajshing/Baileys#954]
how to send PDF documments?
In multidevice

Does anyone have a code and have already tested it?

**Comment by phaticusthiccy** [comment]
`mimetype: Mimetype.pdf`

**Comment by mateuscdor** [comment]
there is a way to post the complete script

I don't know how to call the function that sends document.

Could you post a shipping example?

**Comment by phaticusthiccy** [comment]
Yeah sure.

# ES6
`js
import { MessageType, MessageOptions, Mimetype } from '@adiwajshing/baileys'

async function sendpdf () {
  return await conn.sendMessage(id, fs.readFileSync('patch/to/pdf'), MessageType.document, { mimetype: Mimetype.pdf })
}
await sendpdf()
`

### or

`js
import { MessageType, MessageOptions, Mimetype } from '@adiwajshing/baileys'

async function sendpdf (patchtopdf) {
  return await conn.sendMessage(id, fs.readFileSync(patchtopdf), MessageType.document, { mimetype: Mimetype.pdf })
}
await sendpdf('patch/to/pdf')
`

##

# ES5
`js
const { MessageType, MessageOptions, Mimetype } = require('@adiwajshing/baileys');

async function sendpdf () {
  return await conn.sendMessage(id, fs.readFileSync('patch/to/pdf'), MessageType.document, { mimetype: Mimetype.pdf })
}
await sendpdf()
`

### or

`js
const { MessageType, MessageOptions, Mimetype } = require('@adiwajshing/baileys');

async function sendpdf (patchtopdf) {
  return await conn.sendMessage(id, fs.readFileSync(patchtopdf), MessageType.document, { mimetype: Mimetype.pdf })
}
await sendpdf('patch/to/pdf')
`

##

You must use `await senddpf` functions inside a async function.

**Comment by mateuscdor** [comment]
thank you very much

you are genius.

**Comment by phaticusthiccy** [comment]
Yeah you can use same mimetype on MD.

```js
// ES6
import { MessageType, MessageOptions, Mimetype } from '@adiwajshing/baileys-md'

// ES5
const { MessageType, MessageOptions, Mimetype } = require('@adiwajshing/baileys-md')
```

https://github.com/adiwajshing/Baileys/tree/multi-device#media-messages
https://github.com/adiwajshing/Baileys/tree/multi-device#notes

**Comment by mateuscdor** [comment]
Very veey mutch 
Thanks

**Comment by phaticusthiccy** [comment]
You can close the issue :)

**Comment by Ethernit** [comment]
> You can close the issue :)
