### ISSUE TITLE
[BUG] Sending messages blocked with error code 406 / 500 when Baileys queries for bad device

### ISSUE THREAD

**Issue by jackcokk** [adiwajshing/Baileys#955]
I have just restarted my bot and it's unable to send messages any longer.

Once `example.ts` tries to send a message it says 
`"got 11 additional devices"`
`saving auth state`
`"fetching session"`
`saving auth state`

and everything goes back to the beginning. This loops 8 times until it says 

`"error","id":"e.f-16"},"content":[{"tag":"error","attrs":{"code":"406","text":"not-acceptable"},"content":null}]},"msg":"communication"}`

```
WABinary/index.ts:307
		throw new Boom(errNode.attrs.text || 'Unknown error', { data: +errNode.attrs.code })
```

Anyone else experiencing something similar? Happened yesterday for the first time so I started from scratch and now running into the same issue. Receiving messages and getting profile pictures works fine but sending is broken for some reason

**Comment by jackcokk** [comment]
I cannot find any direct references to null-checks in the web code but if anyone wants to dig deeper, there are a few occurrences on this. In any case, web is able to send messages to groups with bad group devices so they do handle this in _some_ way but I think with the added statement we can make Baileys behave :)

![image](https://user-images.githubusercontent.com/91759091/144471244-a343c12c-2986-4cbf-aa1a-612ee2527ed7.png)

**Comment by adiwajshing** [comment]
@jackcokk thanks for the debugging. Could you please send an example of a usync query which has a bad device (of course, censor the phone number)

**Comment by jackcokk** [comment]
@adiwajshing of course

So first we receive the group metadata

`{"level":10,"time":1638...,"attrs":{"from":"group@g.us","type":"result","id":"6.7-12"},"content":[{"tag":"group","attrs":{"subject":"XX","creator":"...@s.whatsapp.net","s_o":"...@s.whatsapp.net","id":"...","creation":"...","s_t":"...","p_v_id":"."},"content":[{"tag":"participant","attrs":{"jid":",,,@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"mmm@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"nnn@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"bbb@s.whatsapp.net","type":"superadmin"},"content":null},{"tag":"participant","attrs":{"jid":"vvv@s.whatsapp.net"},"content":null},{"tag":"description","attrs":{},"content":null}]}]},"msg":"communication"}`

which mentions each phone participant.

The usync that we get is when we receive

`{"level":10,"time":16384...{"tag":"iq","attrs":{"from":"@s.whatsapp.net","type":"result","id":"6.7-14"},"content":[{"tag":"usync","attrs":{"sid":"6.7-13","mode":"query","last":"true","index":"0","context":"message"},"content":[{"tag":"result","attrs":{},"content":[{"tag":"devices","attrs":{},"content":null}]},{"tag":"list","attrs":{},"content":[{"tag":"user","attrs":{"jid":"123........]}}]}]}]}]}]},"msg":"communication"}`

to see the device list for each participant.

I am not going to bother you with the full list but here is one example each for a valid and an invalid number within the `........` block above:

`{"tag":"user","attrs":{"jid":"invalid@s.whatsapp.net"},"content":[{"tag":"devices","attrs":{},"content":[{"tag":"device-list","attrs":{},"content":[{"tag":"device","attrs":{"id":"0"},"content":null},{"tag":"device","attrs":{"id":"1","key-index":"11"},"content":null},{"tag":"device","attrs":{"id":"2"},"content":null},{"tag":"device","attrs":{"id":"3","key-index":"13"},"content":null}]},{"tag":"key-index-list","attrs":{"ts":"123"},"content":{"type":"Buffer","data":[10,..]}}]}]}]}]}]}`

`{"tag":"user","attrs":{"jid":"valid@s.whatsapp.net"},"content":[{"tag":"devices","attrs":{},"content":[{"tag":"device-list","attrs":{},"content":[{"tag":"device","attrs":{"id":"0"},"content":null},{"tag":"device","attrs":{"id":"1","key-index":"4 "},"content":null},{"tag":"device","attrs":{"id":"2","key-index":"5"},"content":null}]},{"tag":"key-index-list","attrs":{"ts":"1234"},"content":{"type":"Buffer","data":[10..]}}]}]},`

Mind how in the `invalid` block id0 and id2 do not have a `key-index`. I think it's expected for id0 (the actual phone) to not have one, but every `non-0` ID should have one. If there is none at a `non-0` id, we have to skip to avoid the bad query that breaks the connection and prevents sending.

**Comment by adiwajshing** [comment]
I see -- thanks a ton for the info, I've implement a fix https://github.com/adiwajshing/Baileys/commit/d9cfed64ff668426e8419a3dc565c51747422a79

If the issue persists, please feel free to reopen

**Comment by jackcokk** [comment]
It seems to be fixed fixed, thank you! Also, the if statement looks a lot cleaner now.
