### ISSUE TITLE
[BUG] Session can't be reconnected automatically, after disconnected

### ISSUE THREAD

**Issue by AF1298** [adiwajshing/Baileys#957]
hellow,
i want to as some question,

i have case like this : 

- session always close or lost in a few time, and when it want to connected again as automatically, i must open my Whatsapp application on my phone to pair it again.

any solution for me sir, please @adiwajshing 

beforem thank's a lot sir

**Comment by camagenta** [comment]
same here,
currently finding solution to solve this problem
but in my case, the session still there but after about 15 times the log say time out
