### ISSUE TITLE
[BUG] MD BUG ADD TO GROUP

### ISSUE THREAD

**Issue by ThisMe124** [adiwajshing/Baileys#958]
How To Fix This? 
This Happens When I Add A Bot To A New Group And I Test The Command...

This Image:
![IMG_20211202_171243](https://user-images.githubusercontent.com/88891071/144553416-4256da50-2035-4e05-a413-d77adbb9bd54.jpg)

**Comment by Zobin33** [comment]
> How To Fix This? This Happens When I Add A Bot To A New Group And I Test The Command...
> 
> This Image: ![IMG_20211202_171243](https://user-images.githubusercontent.com/88891071/144553416-4256da50-2035-4e05-a413-d77adbb9bd54.jpg)

I've Experienced That, What I Do Is Tag The Last Message Later The Session Will Be Normal, Usually That's If The Device Is Not In Sync

**Comment by Zobin33** [comment]
Is Woking Good Only Tag Last Message On Me:)

**Comment by ThisMe124** [comment]
Hmm
