### ISSUE TITLE
[BUG] MD

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#960]
Error: Timed Out
    at C:\Users\rdp\Desktop\mywamd2\node_modules\@adiwajshing\baileys-md\lib\Utils\generics.js:151:32 {
  data: {
    stack: 'Error\n' +
      '    at Object.promiseTimeout (C:\\Users\\rdp\\Desktop\\mywamd2\\node_modules\\@adiwajshing\\baileys-md\\lib\\Utils\\generics.js:146:19)\n' +
      '    at waitForMessage (C:\\Users\\rdp\\Desktop\\mywamd2\\node_modules\\@adiwajshing\\baileys-md\\lib\\Socket\\socket.js:123:42)\n' +
      '    at query (C:\\Users\\rdp\\Desktop\\mywamd2\\node_modules\\@adiwajshing\\baileys-md\\lib\\Socket\\socket.js:145:22)\n' +
      '    at getUSyncDevices (C:\\Users\\rdp\\Desktop\\mywamd2\\node_modules\\@adiwajshing\\baileys-md\\lib\\Socket\\messages-send.js:161:30)\n' +
      '    at relayMessage (C:\\Users\\rdp\\Desktop\\mywamd2\\node_modules\\@adiwajshing\\baileys-md\\lib\\Socket\\messages-send.js:281:35)\n' +
      '    at async Object.sendMessage (C:\\Users\\rdp\\Desktop\\mywamd2\\node_modules\\@adiwajshing\\baileys-md\\lib\\Socket\\messages-send.js:391:17)\n' +
      '    
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
} unhandledRejection

**Comment by Ethernit** [comment]
your posts don't make sense.

no one can help without seeing the code. avoid incomplete posts when opening the issue

**Comment by SheIITear** [comment]
Get downvoted for saying what should be obvious, lol. 

People do like skipping the issue template.

**Comment by SheIITear** [comment]
> your posts don't make sense.
> 
> no one can help without seeing the code. avoid incomplete posts when opening the issue

Get down voted for saying what should be obvious, lol.

People do like skipping the issue template.
