### ISSUE TITLE
[MD]  Validate the phone numbe

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#961]
The command below does not work on MD.
```js
const id = '123456';
const exists = await conn.isOnWhatsApp (id);
if (exists) console.log (`${id} exists on WhatsApp, as jid: ${exists.jid}`);
```
How to validate the phone number on the MD?

**Comment by viniciusgdr** [comment]
in the example is wrong

the right one is conn.onWhatsApp(id)

**Comment by scoder37** [comment]
![Screenshot_20211204-075358](https://user-images.githubusercontent.com/90820338/144690268-df9cbc0a-9f30-4312-9844-c9ed73cdb450.png)

conn.onWhatsApp(id)

**Comment by scoder37** [comment]
i'am md users, id 62851xx@s.whatsapp.net

**Comment by AlanMartines** [comment]
It worked, thanks for the help.
