### ISSUE TITLE
[MD] Ask

### ISSUE THREAD

**Issue by scoder37** [adiwajshing/Baileys#962]
is this a bug? a response like this when viewed from wa busines, but seen in ordinary wa is safe
![Screenshot_20211204-074701](https://user-images.githubusercontent.com/90820338/144690174-99cf5786-6996-43b7-8638-1f9266a3bd11.png)

**Comment by scoder37** [comment]
![Screenshot_20211204-074813](https://user-images.githubusercontent.com/90820338/144690215-e622a814-985a-4307-beb2-04cd3a30992a.png)
wa non bussines

**Comment by Zobin33** [comment]
> is this a bug? a response like this when viewed from wa busines, but seen in ordinary wa is safe ![Screenshot_20211204-074701](https://user-images.githubusercontent.com/90820338/144690174-99cf5786-6996-43b7-8638-1f9266a3bd11.png)

That Is Template Message Where Is A Button Message With Url Button? You Need To add templateId On There, Btw Can I Get Link Of That Group?
