### ISSUE TITLE
add template buttons without md

### ISSUE THREAD

**Issue by Adiixyz** [adiwajshing/Baileys#963]
**Before adding this issue, make sure you do the following to make sure this is not a duplicate:**
1. Search through the repo's previous issues
2. Read through the readme at least once
3. Search the docs for the feature you're looking for

**Just describe the feature/question**

**Comment by ferhacks** [comment]
you Can't, lol

**Comment by Adiixyz** [comment]
> you Can't, lol

uh
i want to use md but scared if banned

**Comment by Zobin33** [comment]
> > you Can't, lol
> 
> uh i want to use md but scared if banned

Bruh You Never Gonna Be Banned If You Use Carefully

**Comment by Adiixyz** [comment]
> > > you Can't, lol
> > 
> > 
> > uh i want to use md but scared if banned
> 
> Bruh You Never Gonna Be Banned If You Use Carefully

ok fine

**Comment by fazonetea** [comment]
> > > > you Can't, lol
> > > 
> > > 
> > > uh i want to use md but scared if banned
> > 
> > 
> > Bruh You Never Gonna Be Banned If You Use Carefully
> 
> ok fine

heh adi sok inggris lu wkwk

**Comment by frmdeveloper** [comment]
Jangan malu-maluin negara anda

**Comment by frmdeveloper** [comment]
Closed #963.
