### ISSUE TITLE
[ MD ] Request Search Message

### ISSUE THREAD

**Issue by itsMySky** [adiwajshing/Baileys#965]
request that multi-device baileys update Search Messages like regular baileys

**Comment by Ased2235** [comment]
Ye, I'm looking for that too.

**Comment by mateuscdor** [comment]
Yes true

**Comment by BochilGaming** [comment]
I guess, WhatsApp doesn't use queries to search for messages. so you have to save every incoming message in database and you can search it in database if needed

**Comment by adiwajshing** [comment]
Yeah, ya'll have to implement it on your own, there is no "WhatsApp query" for search messages -- have to store the history on your own in a DB and then search it

**Comment by rawars** [comment]
> Yeah, ya'll have to implement it on your own, there is no "WhatsApp query" for search messages -- have to store the history on your own in a DB and then search it

Is there a way to subscribe when WhatsApp MD sends the history?  To be able to store them in the database?
