### ISSUE TITLE
is the feature of searching for messages by ID already available?

### ISSUE THREAD

**Issue by frmdeveloper** [adiwajshing/Baileys#967]
is the feature of searching for messages by ID already available?
```js
const msg = getMessageFromStore('455@s.whatsapp.net', 'HSJHJWH7323HSJSJ') // implement this on your end
await sock.sendMessage('1234@s.whatsapp.net', { forward: msg }) // WA forward the message!
```
```getMessageFromStore``` no function

**Comment by frmdeveloper** [comment]
Hehehehe
![Screenshot_20211205-133715](https://user-images.githubusercontent.com/80396521/144736527-d895f781-1662-42ef-8c65-7f72fefa7542.png)

**Comment by BochilGaming** [comment]
You can save all incoming messages to a database, and you can search for them if you want

**Comment by Zobin33** [comment]
> is the feature of searching for messages by ID already available?
> 
> ```js
> const msg = getMessageFromStore('455@s.whatsapp.net', 'HSJHJWH7323HSJSJ') // implement this on your end
> await sock.sendMessage('1234@s.whatsapp.net', { forward: msg }) // WA forward the message!
> ```
> 
> `getMessageFromStore` no function

getMessageFromStore Is Example Function Who Created By U, Implement Only, Baileys Dont Save Chats, Contact, Messages Anymore:)

**Comment by frmdeveloper** [comment]
> getMessageFromStore Is Example Function Who Created By U, Implement Only, Baileys Dont Save Chats, Contact, Messages Anymore:)

If that's the case, provide a solution.

Where should I save the message, how do I make it?

**Comment by frmdeveloper** [comment]
I have used it. However, there are some errors in retrieving message data as follows

```json
{
  "key": {
    "remoteJid": "6596782113-1323612696@g.us",
    "fromMe": false,
    "id": "BAE53E19897A3810",
    "participant": "62882920241908:4@s.whatsapp.net"
  },
  "message": {
    "senderKeyDistributionMessage": {
      "groupId": "6596782113-1323612696@g.us",
      "axolotlSenderKeyDistributionMessage": "Mwid45efBRABGiAhP1h7eZbG77FE/DD+aKuZKVGtm9NAeaMXWQHUynkStiIhBfC2n3eY2bUhvASeBiW7xO+uxEK2/r+1aneq0DmUzdRE"
    }
  },
  "messageTimestamp": "1639127757",
  "pushName": "Hisoka"
}
```

**Comment by Zobin33** [comment]
> I have used it. However, there are some errors in retrieving message data as follows
> 
> ```json
> {
>   "key": {
>     "remoteJid": "6596782113-1323612696@g.us",
>     "fromMe": false,
>     "id": "BAE53E19897A3810",
>     "participant": "62882920241908:4@s.whatsapp.net"
>   },
>   "message": {
>     "senderKeyDistributionMessage": {
>       "groupId": "6596782113-1323612696@g.us",
>       "axolotlSenderKeyDistributionMessage": "Mwid45efBRABGiAhP1h7eZbG77FE/DD+aKuZKVGtm9NAeaMXWQHUynkStiIhBfC2n3eY2bUhvASeBiW7xO+uxEK2/r+1aneq0DmUzdRE"
>     }
>   },
>   "messageTimestamp": "1639127757",
>   "pushName": "Hisoka"
> }
> ```

Really getMessageFromStore Function Is Work?

**Comment by frmdeveloper** [comment]
> Really getMessageFromStore Function Is Work?

I created a new function by getting the message from json
