### ISSUE TITLE
[BUG] [MD] recv request to retry message

### ISSUE THREAD

**Issue by hardianto-cpu** [adiwajshing/Baileys#968]
![Screenshot_2021-12-05-14-17-37-299_com microsoft rdc androidx](https://user-images.githubusercontent.com/74147602/144736090-af7dcfcc-8f89-49f0-8171-5eb80993125e.jpg)
after being connected, it suddenly came out and the error below came out

**Comment by shinainaru** [comment]
![...](https://user-images.githubusercontent.com/90768067/144743025-bcfcbc74-c590-4816-aeb5-b81be6adf254.jpg)

Now it should be back to the way it was

**Comment by burstfreeze** [comment]
@adiwajshing I would suggest making the retry optional. Personally I will implement this feature but for everyone who does not mind some dropped messages, Booming the session will create a very steep learning curve for everyone just trying out the repo for the first time.

Also, there are 2 other somewhat likely scenarios where Booming would not be appropriate:
- database conflict causing the message to be missing
- someone cleaning up their message history regularly (I only save 6 hours worth of messages to JSON and let previous items run out to keep storage usage low)

I love that Baileys can now retry but especially in "fast" chats I can afford some messages to be dropped when someone has their phone turned off for days and it suddenly asks for a 1-week-old message.

**Comment by adiwajshing** [comment]
Hmm, it should only throw an unhandled rejection, however it's ugly on the console & on node v16 it'll crash the app -- so I'll make a change to simply log if it returns undefined

**Comment by adiwajshing** [comment]
https://github.com/adiwajshing/Baileys/commit/cccd9305a26003cafaeff197066981ad66730eb8 should resolve. Feel free to reopen if the issue persists

**Comment by burstfreeze** [comment]
@adiwajshing the commit looks perfect thank you - did I understand correctly that it only crashes in v16 but not v17? I'm not aware of any difference there between 16 and 17 but maybe I misunderstand your comment. Asking because I am wondering if there are other places in Baileys where the Boom could cause discrepancies among node versions potentially?

**Comment by adiwajshing** [comment]
It's not Boom causing an issue, it's unhandled rejection killing the process -- this behaviour changed with node 15 (not 16, as I incorrectly stated)

https://developer.ibm.com/blogs/nodejs-15-release-blog/

**Comment by burstfreeze** [comment]
Thank you for clarifying.
I really appreciate it

**Comment by hardianto-cpu** [comment]
@adiwajshing @burstfreeze  thanks all
