### ISSUE TITLE
Baileys-MD - The function to send documents in pdf does not work

### ISSUE THREAD

**Issue by mateuscdor** [adiwajshing/Baileys#969]
Baileys-md 
https://github.com/adiwajshing/baileys/tree/multi-device#media-messages
The function to send documents in pdf does not work

@adiwajshing 
@PurpShell 

` await client.sendMessage(from, fs.readFileSync('./ArquivoTemp/testedoccument.pdf'), { mimetype: 'application/pdf', filename: 'somefile.pdf' } );`

**Comment by shinainaru** [comment]
- Upload From Storage

`await sock.sendMessage("123456789@s.whatsapp.net", { document: fs.readFileSync("otaku.pdf"), fileName: "Upload From Storage Otaku File.pdf", mimetype: "application/pdf" })`

- Upload From URL

`await sock.sendMessage("123456789@s.whatsapp.net", { document: { url: "https://mogami.neocities.org/files/otaku.pdf" }, fileName: "Upload From URL Otaku File.pdf", mimetype: "application/pdf" })`

I hope this helps you

**Comment by scoder37** [comment]
![Screenshot_20211205-193550](https://user-images.githubusercontent.com/90820338/144746773-93044733-a015-4177-a823-38142f847629.png)

await sock.sendMessage(id, { document: fs.readFileSync("your pdf file.pdf"), fileName: "name.pdf", mimetype: "application/pdf" })
