### ISSUE TITLE
How to forward to more than one user

### ISSUE THREAD

**Issue by monsoontest1** [adiwajshing/Baileys#970]
I use 
```
const message = await conn.loadMessage(from, messageId); 
const fwd = await conn.forwardMessage (to, message)
```
 to forward message. How to forward to more than one user

I tried array of recipient id but not worked

**Comment by SheIITear** [comment]
How is this an issue?

**Comment by monsoontest1** [comment]
This is a question

**Comment by SheIITear** [comment]
Then why'd you open an issue...?

**Comment by monsoontest1** [comment]
I found Issue have question option.
![Screenshot_2021-12-05_19-36-37](https://user-images.githubusercontent.com/77375354/144750035-0b94b397-1958-4d04-a49f-640d4f88aaf2.png)

**Comment by SheIITear** [comment]
You already asked on the discord server tho.

**Comment by monsoontest1** [comment]
Yes, but no one seems to be active there, thats why asked here

**Comment by phaticusthiccy** [comment]
Just convert strings to array stack. Then you can use `forEach` function.

**Comment by phaticusthiccy** [comment]
This is not an issue with the module or not a question to be asked here. You must discuss such things on stackoverflow, gitlab ot any coding forums.
Now you can close the issue.

**Comment by frmdeveloper** [comment]
closed
