### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xYAZUWA** [adiwajshing/Baileys#973]
*
Error:BaileysError: Unexpected status in 'action': Bad Request(400)

when i am trying to send buttons in system_stats.js in whatsapp , it gave me this error.

codes -

const Asena = require('../events');const {MessageType, MessageOptions, Mimetype, Presence} = require('@adiwajshing/baileys');const {spawnSync} = require('child_process');const Config = require('../config');const chalk = require('chalk');const axios = require('axios');const Language = require('../language');const Lang = Language.getString('system_stats');if (Config.WORKTYPE == 'private') { Asena.addCommand({pattern: 'alive', fromMe: true, desc: Lang.ALIVE_DESC}, (async (message, match) => { if (Config.ALIVEMSG == 'default') { var image = await axios.get (Config.ALIVE_LOGO, {responseType: 'arraybuffer'}) await message.client.sendMessage (message.jid, Buffer.from (image.data), MessageType.image, {mimetype: Mimetype.png, caption: "```👸💎 Hey There! I'm Online now. 😙```\n\n*Version:* ```v1.5 - Stable```\n\n*Developer:* ```KgAmda```\n\n*WhatsApp Support Group :* https://chat.whatsapp.com/J7EdUBd7E2OIsXOOeAHcuT\n\n*Youtube channel :* https://www.youtube.com/channel/UCQIo_J1z2MdVeKlY7Wh9TUA\n\n```Thank You For Using Amdibell❤```"}) } else { var image = await axios.get (Config.ALIVE_LOGO, {responseType: 'arraybuffer'}) await message.client.sendMessage (message.jid, Buffer.from (image.data), MessageType.image, {mimetype: Mimetype.png, caption: Config.ALIVEMSG + '\n\n*Copyright © 2021 | 𝖰𝗎𝖾𝖾𝗇 𝖠𝗆𝖽𝗂𝖻𝖾𝗅𝗅*' }) } })); Asena.addCommand({pattern: 'sysd', fromMe: true, desc: Lang.SYSD_DESC}, (async (message, match) => { if (message.jid === '905524317852-1612300121@g.us') { return; } const child = spawnSync('neofetch', ['--stdout']).stdout.toString('utf-8') await message.sendMessage( '```' + child + '```', MessageType.text ); }));}else if (Config.WORKTYPE == 'public') { Asena.addCommand({pattern: 'alive', fromMe: false, desc: Lang.ALIVE_DESC}, (async (message, match) => { if (Config.ALIVEMSG == 'default') { 
const buttons = [ {buttonId: 'id1', buttonText: {displayText: 'I am Fine 😀'}, type: 1}, {buttonId: 'id2', buttonText: {displayText: 'Feeling sad😢 '}, type: 1}, {buttonId: 'id3', buttonText: {displayText: 'Joyfull 😎'}, type: 1} {buttonId: 'id2', buttonText: {displayText: 'Feeling sad😢 '}, type: 1}
]const buttonMessage = { contentText: "🌹Hello How Are You?", footerText: '🔺AloraV3', buttons: buttons, headerType: 1 } var image = await axios.get (Config.ALIVE_LOGO, {responseType: 'arraybuffer'}) await message.client.sendMessage (message.jid, Buffer.from (image.data), MessageType.image, {mimetype: Mimetype.png, caption: "```👸💎 Hey There! I'm Online now. 😙```\n\n*Version:* ```v2.1 - Stable```\n\n*Developer:* ```xYAZUWA```\n\n*WhatsApp Support Group :* https://chat.whatsapp.com/GV6txkbt3D6HKoNexxkzOF\n\n*Youtube channel :* https://m.youtube.com/channel/UCH9RSf1cf3MfiCwLvGYHnOQ/\n\n```Thank You For Using Alora⭐V2❤```"}) await message.client.sendMessage(message.jid, buttonMessage, MessageType.buttonsMessage) } else {
const buttons = [ {buttonId: 'id1', buttonText: {displayText: 'I am Fine 😀'}, type: 1}, {buttonId: 'id2', buttonText: {displayText: 'Feeling sad😢 '}, type: 1}, {buttonId: 'id3', buttonText: {displayText: 'Joyfull 😎'}, type: 1} {buttonId: 'id2', buttonText: {displayText: 'Feeling sad😢 '}, type: 1}
]const buttonMessage = { contentText: "🌹Hello How Are You?", footerText: '🔺AloraV3', buttons: buttons, headerType: 1} var image = await axios.get (Config.ALIVE_LOGO, {responseType: 'arraybuffer'}) await message.client.sendMessage (message.jid, Buffer.from (image.data), MessageType.image, {mimetype: Mimetype.png, caption: Config.ALIVEMSG + '\n\n*Copyright © 2021 | Alora 🎻 V2*' }) await message.client.sendMessage(message.jid, buttonMessage, MessageType.buttonsMessage) } })); Asena.addCommand({pattern: 'sysd', fromMe: false, desc: Lang.SYSD_DESC}, (async (message, match) => { if (message.jid === '905524317852-1612300121@g.us') { return; } const child = spawnSync('neofetch', ['--stdout']).stdout.toString('utf-8') await message.sendMessage( '```' + child + '```', MessageType.text ); }));}

🤗Need Fast help please

**Comment by phaticusthiccy** [comment]
Cloning [WhatsAsena](https://github.com/yusufusta/WhatsAsena) isn't effective way to make something better, right?

**Comment by xYAZUWA** [comment]
> Cloning [WhatsAsena](https://github.com/yusufusta/WhatsAsena) isn't effective way to make something better, right?


Sir i didnt cloned asena. I cloned AmdiBell 😇. And also added new features. Such as buttons
