### ISSUE TITLE
[BUG] Connection login error

### ISSUE THREAD

**Issue by orderku** [adiwajshing/Baileys#974]
←[33mWARN←[39m [2021-12-06 02:35:44.797 +0000] (3772): ←[36mconnect attempt 1 fa
iled: BaileysError: Unexpected error in login←[39m
    class: "Baileys"
    error: {
      "name": "BaileysError",
      "status": 401,
      "context": {
        "response": {
          "status": 401
        },
        "status": 401
      }
    }

**Comment by GabrielBels** [comment]
Same here..
