### ISSUE TITLE
[BUG]: does not work if there is no internet

### ISSUE THREAD

**Issue by adithadirizki** [adiwajshing/Baileys#975]
**can i use it if my whatsapp has no internet?**

when my whatsapp has internet connection, it works fine.
but if i turn off internet connection in whatsapp, it doesn't work.
how to solve it?

**Comment by Zobin33** [comment]
Multi Device?

**Comment by mateuscdor** [comment]
> Multi Device?

Multi Device? false?

**Comment by adithadirizki** [comment]
> Multi Device?

thanks, i will try it

**Comment by PurpShell** [comment]
> > Multi Device?
> 
> thanks, i will try it

Then this issue is resolved? Close it
