### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by melcanz** [adiwajshing/Baileys#977]
![Screenshot_2021-12-06-22-06-58-907_com termux](https://user-images.githubusercontent.com/91192362/144870208-abf6a7f3-ddac-443f-8775-1934c01a8224.jpg)

**Comment by Iucasmaia** [comment]
Just read... this is'nt a bug.

**Comment by melcanz** [comment]
> 

Thx

**Comment by Shubhamrawat5** [comment]
I'm getting same error but i've not used typescript in my bot then why it is showing tsc not found?

**Comment by viniciusgdr** [comment]
> Estou recebendo o mesmo erro, mas não usei o typescript no meu bot, então por que ele está mostrando tsc não encontrado?


Baileys Code was written in Typescript.
