### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by lmGuardon** [adiwajshing/Baileys#98]
npm install baileys
npm WARN deprecated video-thumb@0.0.3: Package is no longer maintained
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@protobufjs%2faspromise - Not found
npm ERR! 404 
npm ERR! 404  '@protobufjs/aspromise@^1.1.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'protobufjs'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by adiwajshing** [comment]
Ah, you're installing the wrong package, try `npm i @adiwajshing/baileys`

**Comment by adiwajshing** [comment]
Assuming it's resolved, closing.
