### ISSUE TITLE
Whatsapp Warning: Waiting for this message. This may take a while.

### ISSUE THREAD

**Issue by denizsult** [adiwajshing/Baileys#981]
Hey there! When I use buttons I get that message from whatsapp. What could be the solution to this problem?

**Comment by BochilGaming** [comment]
> Hey there! When I use buttons I get that message from whatsapp. What could be the solution to this problem?

Your code?

**Comment by hdrstore** [comment]
Help

![Uploading Screenshot_2021-12-07-17-48-13-01_fb47b6c93b99596be3e79670c6246005.jpg…]()

**Comment by denizsult** [comment]
function welcome(sock, msg) {
      const sendMessageWTyping = async (msg: AnyMessageContent, jid: string) => {
            await sock.presenceSubscribe(jid)
            await delay(500)

            await sock.sendPresenceUpdate('composing', jid)
            await delay(2000)

            await sock.sendPresenceUpdate('paused', jid)

            await sock.sendMessage(jid, msg)
      }


      const buttons = [
            { buttonId: 'id1', buttonText: { displayText: 'Taksi Çağır(t)' }, type: 1 },
            { buttonId: 'id2', buttonText: { displayText: 'Nakliye(m)' }, type: 1 },
            { buttonId: 'id3', buttonText: { displayText: 'Müşteri Hizmetleri (m)' }, type: 1 },

      ]

      const buttonMessage = {
            text:  `Welcome ${msg.pushName} ! 👋 \n Size Nasıl Yardımcı Olabilirim?`,
            buttons: buttons,
            headerType: 2
      }


      sendMessageWTyping(buttonMessage, msg.key.remoteJid)}

**Comment by denizsult** [comment]
The other party sometimes receives the message, and sometimes the message "Waiting" appears.

**Comment by hdrstore** [comment]
Can help me

![Screenshot_2021-12-07-17-48-13-01_fb47b6c93b99596be3e79670c6246005](https://user-images.githubusercontent.com/84903910/145027427-19cf230c-647b-4342-aa5e-baff8b95d7d0.jpg)

**Comment by denizsult** [comment]
> > Hey there! When I use buttons I get that message from whatsapp. What could be the solution to this problem?
> 
> Your code?

      
      function welcome(sock, msg) {
      const sendMessageWTyping = async (msg: AnyMessageContent, jid: string) => {
            await sock.presenceSubscribe(jid)
            await delay(500)

            await sock.sendPresenceUpdate('composing', jid)
            await delay(2000)

            await sock.sendPresenceUpdate('paused', jid)

            await sock.sendMessage(jid, msg)
      }


      const buttons = [
            { buttonId: 'id1', buttonText: { displayText: 'Taksi Çağır(t)' }, type: 1 },
            { buttonId: 'id2', buttonText: { displayText: 'Nakliye(m)' }, type: 1 },
            { buttonId: 'id3', buttonText: { displayText: 'Müşteri Hizmetleri (m)' }, type: 1 },

      ]

      const buttonMessage = {
            text:  `Welcome ${msg.pushName} ! 👋 \n Size Nasıl Yardımcı Olabilirim?`,
            buttons: buttons,
            headerType: 2
      }


      sendMessageWTyping(buttonMessage, msg.key.remoteJid)}

**Comment by phaticusthiccy** [comment]
Bu hata bazen olabiliyor. Nedenini tam olarak bilmiyorum. Belki kullandığın wa web sürümünden kaynaklı veya WhatApp sürümünden de kaynaklı olabilir. Belki de kodlarda bir sorun vardır. Profile göz attım fakat projeni göremedim. Sistemi incelemek istemiştim. Benim kullandığım sürüm: `conn.version = [3, 3234, 9]`
Şuanda kullandığın wa sürümü ve wa web sürümü nedir? 


This error can be happen sometimes. I don't know exactly why. It can be caused by the wa web version you are using, or it can also be by the WhatApp version. Maybe there is a problem with the codes. I surfed your profile but couldn't find your project. Here is the version I am using: `conn.version = [3, 3234, 9]`
What is the wa version and wa web version are you currently using?

**Comment by denizsult** [comment]
> Bu hata bazen olabiliyor. Nedenini tam olarak bilmiyorum. Belki kullandığın wa web sürümünden kaynaklı veya WhatApp sürümünden de kaynaklı olabilir. Belki de kodlarda bir sorun vardır. Profile göz attım fakat projeni göremedim. Sistemi incelemek istemiştim. Benim kullandığım sürüm: `conn.version = [3, 3234, 9]` Şuanda kullandığın wa sürümü ve wa web sürümü nedir?
> 
> This error can be happen sometimes. I don't know exactly why. It can be caused by the wa web version you are using, or it can also be by the WhatApp version. Maybe there is a problem with the codes. I surfed your profile but couldn't find your project. Here is the version I am using: `conn.version = [3, 3234, 9]` What is the wa version and wa web version are you currently using?

web version = 2.2146.9  wa = 2.21.23.23

**Comment by BochilGaming** [comment]
> The other party sometimes receives the message, and sometimes the message "Waiting" appears.

try use latest commit

**Comment by nugraizy** [comment]
> > > Hey there! When I use buttons I get that message from whatsapp. What could be the solution to this problem?
> > 
> > 
> > Your code?
> 
> ```
>   function welcome(sock, msg) {
>   const sendMessageWTyping = async (msg: AnyMessageContent, jid: string) => {
>         await sock.presenceSubscribe(jid)
>         await delay(500)
> 
>         await sock.sendPresenceUpdate('composing', jid)
>         await delay(2000)
> 
>         await sock.sendPresenceUpdate('paused', jid)
> 
>         await sock.sendMessage(jid, msg)
>   }
> 
> 
>   const buttons = [
>         { buttonId: 'id1', buttonText: { displayText: 'Taksi Çağır(t)' }, type: 1 },
>         { buttonId: 'id2', buttonText: { displayText: 'Nakliye(m)' }, type: 1 },
>         { buttonId: 'id3', buttonText: { displayText: 'Müşteri Hizmetleri (m)' }, type: 1 },
> 
>   ]
> 
>   const buttonMessage = {
>         text:  `Welcome ${msg.pushName} ! 👋 \n Size Nasıl Yardımcı Olabilirim?`,
>         buttons: buttons,
>         headerType: 2
>   }
> 
> 
>   sendMessageWTyping(buttonMessage, msg.key.remoteJid)}
> ```

Change your headerType to 1.

**Comment by denizsult** [comment]
> > The other party sometimes receives the message, and sometimes the message "Waiting" appears.
> 
> try use latest commit

Problem solved. Thanks.
