### ISSUE TITLE
Save and Load Auth info from database

### ISSUE THREAD

**Issue by mi-khatri** [adiwajshing/Baileys#982]
Hi, i want to know how to i save session authinfo in database (like MySql) and how to retrieve and use it.
Thanks

**Comment by phaticusthiccy** [comment]
This is not about to baileys. You can look at the courses instead of opening an issue here.

**Comment by mi-khatri** [comment]
> This is not about to baileys. You can look at the courses instead of opening an issue here.

sorry, but my question is, normally we save session of Bailey WAConnection in *.json file. but i want to save all of detail of Session of Bailey WAConnection in Database (Not as a file).
So how can it possible?
I am a new so please ignore if i mistake something ...
Thanks

**Comment by akm-akm** [comment]
> > This is not about to baileys. You can look at the courses instead of opening an issue here.
> 
> sorry, but my question is, normally we save session of Bailey WAConnection in *.json file. but i want to save all of detail of Session of Bailey WAConnection in Database (Not as a file).
> So how can it possible?
> I am a new so please ignore if i mistake something ...
> Thanks

https://github.com/akm-akm/xxx-whatsapp-bot

see /events/events.js file. i save the session in database using postgres.

**Comment by mi-khatri** [comment]
> > > This is not about to baileys. You can look at the courses instead of opening an issue here.
> > 
> > 
> > sorry, but my question is, normally we save session of Bailey WAConnection in *.json file. but i want to save all of detail of Session of Bailey WAConnection in Database (Not as a file).
> > So how can it possible?
> > I am a new so please ignore if i mistake something ...
> > Thanks
> 
> https://github.com/akm-akm/xxx-whatsapp-bot
> 
> see /events/events.js file. i save the session in database using postgres.

I tried it and its work great
Thanks you very very much.....
