### ISSUE TITLE
[BUG] (not confirmed) group add causes crash

### ISSUE THREAD

**Issue by HUGEIT** [adiwajshing/Baileys#983]
someone explained their issue on dc but seems to be afraid of signing up to github so I'm forwarding:

![image](https://user-images.githubusercontent.com/94182206/145044285-78503599-d9ec-4339-9967-59ec25c9336e.png)

> it happens when i added to a group that the metadata.owner is undefined.

> I can't show my code/code to reproduce it, because I don't have message event listener or some sort. I found out that my Baileys will crash only after I added my bot into a group that is not displaying who creates the group. So I found out how to "solve" it as it's not crash anymore.
> 
> adding 1 line of code at `/baileys-md/lib/WABinary/jid-utils.js:49`
> `if (jid === undefined) return`

**Comment by nugraizy** [comment]
Sorry for not making an issue about this problem beforehand. I had a school exam.

So this problem appears when I'm adding my bot to the group that has no creator of the group displayed. 

This is the stack trace :

*{"level":10,"time":1638893290163,"pid":3688,"hostname":"CPC-JhonTBox-BE","msgId":"1045387950","fromMe":false,"frame":{"tag":"notification","attrs":{"from":"xxx-1627550512@g.us","type":"w:gp2","id":"1045387950","participant":"xxx@s.whatsapp.net","notify":"nanda","t":"1638893290"},"content":[{"tag":"create","attrs":{},"content":[{"tag":"group","attrs":{"subject":"Artificial Stupidity","id":"xxx-1627550512","creation":"1627550512","s_t":"1634129119","p_v_id":"1638893290065688","a_v_id":"1628352047773565"},"content":[{"tag":"description","attrs":{"id":"E627253D4FAC9D83C859E7345E886F94","t":"1634129603"},"content":[{"tag":"body","attrs":{},"content":{"type":"Buffer","data":[67,108,101,97,110,105,110,103,32,83,101,114,118,105,99,101,115,32,105,115,32,121,111,117,114,32,106,111,98,46,10,67,108,101,97,110,105,110,103,32,121,111,117,114,32,109,111,109,32,112,117,115,115,121,32,105,115,32,111,117,114,32,106,111,98,46,10,10,77,97,107,101,32,116,104,101,32,101,97,114,116,104,32,116,104,101,32,98,101,116,116,101,114,32,112,108,97,99,101,46,32,83,117,114,118,105,118,101,32,104,101,114,101,32,119,105,116,104,111,117,116,32,100,121,105,110,103,46,32,65,110,121,32,109,101,115,115,97,103,101,115,32,119,105,108,108,32,98,101,32,109,111,110,105,116,111,114,101,100,46,10,10,73,110,104,117,109,97,110,105,116,121,32,98,101,121,111,110,100,32,97,110,121,32,114,101,108,105,103,105,111,110,44,32,65,110,121,32,118,105,111,108,97,110,99,101,32,105,115,32,97,108,108,111,119,101,100,44,32,65,110,100,32,116,111,32,116,104,101,32,111,110,101,32,119,101,32,115,104,97,108,108,32,115,101,114,118,101,46]}}]},{"tag":"locked","attrs":{},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"xxx@s.whatsapp.net","type":"admin"},"content":null}]}]}]},"msg":"communication"}
{"level":20,"time":1638893290163,"pid":3688,"hostname":"CPC-JhonTBox-BE","recv":{"from":"xxx-1627550512@g.us","type":"w:gp2","id":"1045387950","participant":"xxx@s.whatsapp.net","notify":"nanda","t":"1638893290"},"sent":{"id":"1045387950","to":"xxx-1627550512@g.us","class":"notification","type":"w:gp2","participant":"xxx@s.whatsapp.net"},"msg":"sent \"notification\" ack"}*

**Comment by nugraizy** [comment]
> Sorry for not making an issue about this problem beforehand. I had a school exam.
> 
> So this problem appears when I'm adding my bot to the group that has no creator of the group displayed.
> 
> This is the stack trace :
> 
> _{"level":10,"time":1638893290163,"pid":3688,"hostname":"CPC-JhonTBox-BE","msgId":"1045387950","fromMe":false,"frame":{"tag":"notification","attrs":{"from":"[xxx-1627550512@g.us](mailto:xxx-1627550512@g.us)","type":"w:gp2","id":"1045387950","participant":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","notify":"nanda","t":"1638893290"},"content":[{"tag":"create","attrs":{},"content":[{"tag":"group","attrs":{"subject":"Artificial Stupidity","id":"xxx-1627550512","creation":"1627550512","s_t":"1634129119","p_v_id":"1638893290065688","a_v_id":"1628352047773565"},"content":[{"tag":"description","attrs":{"id":"E627253D4FAC9D83C859E7345E886F94","t":"1634129603"},"content":[{"tag":"body","attrs":{},"content":{"type":"Buffer","data":[67,108,101,97,110,105,110,103,32,83,101,114,118,105,99,101,115,32,105,115,32,121,111,117,114,32,106,111,98,46,10,67,108,101,97,110,105,110,103,32,121,111,117,114,32,109,111,109,32,112,117,115,115,121,32,105,115,32,111,117,114,32,106,111,98,46,10,10,77,97,107,101,32,116,104,101,32,101,97,114,116,104,32,116,104,101,32,98,101,116,116,101,114,32,112,108,97,99,101,46,32,83,117,114,118,105,118,101,32,104,101,114,101,32,119,105,116,104,111,117,116,32,100,121,105,110,103,46,32,65,110,121,32,109,101,115,115,97,103,101,115,32,119,105,108,108,32,98,101,32,109,111,110,105,116,111,114,101,100,46,10,10,73,110,104,117,109,97,110,105,116,121,32,98,101,121,111,110,100,32,97,110,121,32,114,101,108,105,103,105,111,110,44,32,65,110,121,32,118,105,111,108,97,110,99,101,32,105,115,32,97,108,108,111,119,101,100,44,32,65,110,100,32,116,111,32,116,104,101,32,111,110,101,32,119,101,32,115,104,97,108,108,32,115,101,114,118,101,46]}}]},{"tag":"locked","attrs":{},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","type":"admin"},"content":null},{"tag":"participant","attrs":{"jid":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","type":"admin"},"content":null}]}]}]},"msg":"communication"} {"level":20,"time":1638893290163,"pid":3688,"hostname":"CPC-JhonTBox-BE","recv":{"from":"[xxx-1627550512@g.us](mailto:xxx-1627550512@g.us)","type":"w:gp2","id":"1045387950","participant":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)","notify":"nanda","t":"1638893290"},"sent":{"id":"1045387950","to":"[xxx-1627550512@g.us](mailto:xxx-1627550512@g.us)","class":"notification","type":"w:gp2","participant":"[xxx@s.whatsapp.net](mailto:xxx@s.whatsapp.net)"},"msg":"sent "notification" ack"}_

What I mean by *"not displaying the creator"* is this :
![IMG-20211207-WA0038](https://user-images.githubusercontent.com/69896924/145067883-54c9ffc2-3deb-4000-8081-2727ba8b14b4.jpg)

**Comment by canove** [comment]
@nugraizy , Could you check if the last commit fixed it?
https://github.com/adiwajshing/Baileys/commit/49e7ad4b258026c2368e8a61bc76174e190a4bbd

**Comment by nugraizy** [comment]
> @nugraizy , Could you check if the last commit fixed it? [49e7ad4](https://github.com/adiwajshing/Baileys/commit/49e7ad4b258026c2368e8a61bc76174e190a4bbd)

It fixed.
