### ISSUE TITLE
[BUG] MD - Can't send any message on old groups.

### ISSUE THREAD

**Issue by Iucasmaia** [adiwajshing/Baileys#988]
**Describe the bug**
When I try to send any message to an old group whose id looks like this: 55479xxxxxxx-1611000610@g.us i receive an error code.
When sending to new groups whose id is unique and looks like this: 12036303733987xxxx@g.us, it works perfectly!

**To Reproduce**
1. Connect using baileys-md
2. Try to send any message to a group whose id looks like the old one.
3. Now try to send any message to a group whose id looks like the new.

**Expected behavior**
```
statusCode: 500,
     payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
```

**Environment (please complete the following information):**
 - Is this on a server?
 R: Not.
 - What do your `connectOptions` look like?
 R: `logger: pino({ level: 'error' }),
        printQRInTerminal: true,
        auth: state`
 - Do you have multiple clients on the same IP?
 R: Not.
 - Are you using a proxy?
 R: Not.

**Comment by guiromer** [comment]
Does it help removing the dash with a replace function before querying like your_group_id_here.replace('-', '')?

**Comment by scoder37** [comment]
![Screenshot_20211208-223300](https://user-images.githubusercontent.com/90820338/145236455-1c8b82b3-05b2-41f5-9e0b-c8c80789e106.png)

its work

**Comment by Iucasmaia** [comment]
> ![Screenshot_20211208-223300](https://user-images.githubusercontent.com/90820338/145236455-1c8b82b3-05b2-41f5-9e0b-c8c80789e106.png)
> 
> its work

**Comment by Iucasmaia** [comment]
> Does it help removing the dash with a replace function before querying like your_group_id_here.replace('-', '')?

I tried and this didn't work.

> ![Screenshot_20211208-223300](https://user-images.githubusercontent.com/90820338/145236455-1c8b82b3-05b2-41f5-9e0b-c8c80789e106.png)
> 
> its work

did you use baileys-md?

**Comment by Iucasmaia** [comment]
Updated to latest version on github and worked!
