### ISSUE TITLE
tsc not found

### ISSUE THREAD

**Issue by Shubhamrawat5** [adiwajshing/Baileys#989]
When i did "npm i @adiwajshing/baileys" , it show the error:

'tsc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by viniciusgdr** [comment]
You need to Install the Typescript, it's not a mistake

`npm i -g typescript`

**Comment by viniciusgdr** [comment]
this issue is Repeated from #977

**Comment by Shubhamrawat5** [comment]
But i've not used typescript in my bot and also i'm using baileys from 3 - 4 months and it didn't give this typescript error but now suddenly it is showing.

**Comment by viniciusgdr** [comment]
> Mas eu não usei o texto digitado no meu bot e também estou usando o baileys de 3 a 4 meses e não deu esse erro de texto digitado, mas agora de repente ele está aparecendo.

Baileys Code was written in Typescript.

**Comment by Shubhamrawat5** [comment]
But it's not written anywhere that we need to install typescript first to install baileys.

**Comment by Shubhamrawat5** [comment]
okay so it was installing baileys from github as i had  "@adiwajshing/baileys": "github:adiwajshing/baileys" in package.json
