### ISSUE TITLE
MD - [solved] slow sending messages in large groups

### ISSUE THREAD

**Issue by erickythierry** [adiwajshing/Baileys#990]
**I would just like to ask if there is any better way to store and retrieve saved prekeys?**

I noticed that the code makes an individual check of each participant's prekey every time they send a message in the group.
causing a delay of up to 3min to be able to send a single message in a crowded group.

I made a slight modification to the `useSingleFileAuthState` function
to save the prekeys to a variable and a parallel function saves these prekeys to a json without blocking the main code. I had an improvement in response speed, but there is still a delay

> my function modified below:

_\src\Utils\auth-utils.ts_
```
let testeAuth = null
export const useVarAuthState = (filename: string) => {
    const { readFileSync, writeFileSync, existsSync } = require('fs')
    

	let state: AuthenticationState = undefined

	// save the authentication state
	const saveState = () => {
		//console.log('saving auth state')
		JSON.stringify(state, BufferJSON.replacer, 2)
		updateFile()
	}
	
    if(testeAuth) {
        const { creds, keys } = JSON.parse(
            testeAuth, 
            BufferJSON.reviver
        )
        state = { 
            creds: creds, 
            // stores pre-keys, session & other keys
            // we deserialize it here
            keys: initInMemoryKeyStore(keys, saveState) 
        }
    
    } else if(!testeAuth && existsSync(filename)){
        const { creds, keys } = JSON.parse(
            readFileSync(filename, { encoding: 'utf-8' }), 
            BufferJSON.reviver
        )
        state = { 
            creds: creds, 
            // stores pre-keys, session & other keys
            // we deserialize it here
            keys: initInMemoryKeyStore(keys, saveState) 
        }
        
        
        
    }else {
        const creds = initAuthCreds()
        const keys = initInMemoryKeyStore({ }, saveState)
        state = { creds: creds, keys: keys }
        
    }

    async function updateFile(){
        
        writeFileSync(
			filename,
			// BufferJSON replacer utility saves buffers nicely
			JSON.stringify(state, BufferJSON.replacer, 2)
		)
    }

	return { state, saveState }
}
```

#### my solution was just an improvisation

**Comment by Peticali** [comment]
here big groups takes up to 5 minutes to send a message, and sometimes it doesn't even work

**Comment by guiromer** [comment]
I am experiencing this exact same thing. With bigger groups (more than 150 people) it cant take up to 30 minutes to the message effectively be sent. Nothing abnormal in log trace, also.

**Comment by Peticali** [comment]
> I am experiencing this exact same thing. With bigger groups (more than 150 people) it cant take up to 30 minutes to the message effectively be sent. Nothing abnormal in log trace, also.

one thing I forgot to mention is the log going crazy when it gets a group message, flooding "saving auth state"

**Comment by erickythierry** [comment]
I did some tests and talked with some colleagues and I ended up reaching a conclusion:
baileys md needs to check all prekeys of users in the group before sending each message. however, it ends up updating the prekeys every time which harms performance.

I've found that this strange behavior is caused by the listener `sock.ev.on('creds.update', saveState)`

I replaced this listener with another:
`sock.ev.on('auth-state.update', () => saveState)`

with this change, baileys only updates the prekeys on the first run, after that it just checks the keys, this greatly improved the performance when sending messages (the delay still exists but it is much smaller)

using the modified code I sent above along with this listener modification manages to maintain good overall performance when sending messages

but I'm still looking for a way that doesn't block the code when sending a message

**Comment by erickythierry** [comment]
> > I am experiencing this exact same thing. With bigger groups (more than 150 people) it cant take up to 30 minutes to the message effectively be sent. Nothing abnormal in log trace, also.
> 
> one thing I forgot to mention is the log going crazy when it gets a group message, flooding "saving auth state" ![image](https://user-images.githubusercontent.com/34588988/145621231-97f48d44-2f1b-435c-88e8-68fbd73e36bb.png)

this is because baileys md checks one by one all prekeys of group participants and floods the console for each of the prekeys checked. I deleted this console.log to avoid this.

**Comment by jackcokk** [comment]
>sock.ev.on('auth-state.update', () => saveState)

No such event is defined in Baileys at the moment. Either you are using an older version to begin with or what you are doing simply leaves you with outdated credentials as Baileys does not reach your save function anymore because you are not listening to it.

**Comment by erickythierry** [comment]
> 

I did some tests now and there really isn't this event. so the listener doesn't work, so the script uses the already saved keys. gets faster

**Comment by erickythierry** [comment]
> > sock.ev.on('auth-state.update', () => saveState)
> 
> No such event is defined in Baileys at the moment. Either you are using an older version to begin with or what you are doing simply leaves you with outdated credentials as Baileys does not reach your save function anymore because you are not listening to it.

I did some tests now and there really isn't this event. so the listener doesn't work, so the script uses the already saved keys. gets faster

**Comment by ferhacks** [comment]
when you try to send a message, Baileys tries to correct the "Waiting for message" message, which would not be very efficient as that causes the delay.

**Comment by erickythierry** [comment]
> 

would have any solution?

**Comment by erickythierry** [comment]
> when you try to send a message, Baileys tries to correct the "Waiting for message" message, which would not be very efficient as that causes the delay.

would have any solution?

**Comment by adiwajshing** [comment]
So I've implemented transactions on the auth state, to make the pre-key/session storage more efficient -- if ya'll try the latest commit (https://github.com/adiwajshing/Baileys/pull/696/commits/f284217d35d8352bcf8160df3818ac5b2ab10804) -- it should be way faster and have fewer errors ("Waiting for message")

**Comment by Peticali** [comment]
> So I've implemented transactions on the auth state, to make the pre-key/session storage more efficient -- if ya'll try the latest commit ([f284217](https://github.com/adiwajshing/Baileys/commit/f284217d35d8352bcf8160df3818ac5b2ab10804)) -- it should be way faster and have fewer errors ("Waiting for message")

here in the latest commit auth_info_md is not more being saved, so i'm in a login loop

**Comment by erickythierry** [comment]
> So I've implemented transactions on the auth state, to make the pre-key/session storage more efficient -- if ya'll try the latest commit ([f284217](https://github.com/adiwajshing/Baileys/commit/f284217d35d8352bcf8160df3818ac5b2ab10804)) -- it should be way faster and have fewer errors ("Waiting for message")

Wow. totally solved the problem. thank you very much for the solution! 💓

**Comment by PurpShell** [comment]
> > So I've implemented transactions on the auth state, to make the pre-key/session storage more efficient -- if ya'll try the latest commit ([f284217](https://github.com/adiwajshing/Baileys/commit/f284217d35d8352bcf8160df3818ac5b2ab10804)) -- it should be way faster and have fewer errors ("Waiting for message")
> 
> Wow. totally solved the problem. thank you very much for the solution! heartbeat

close the issue when you resolve something
