### ISSUE TITLE
[BUG] MD - presence.update is not working

### ISSUE THREAD

**Issue by krasymyr** [adiwajshing/Baileys#991]
**Describe the bug**
While working with the example script, chat, message, contact updates are working fine. But the presence.update is not working even tough i can even see the chatting person online from within the app.

**To Reproduce**
1. Followed, and ran the example.ts of MD from the latest git commit
2. Wait for a presence update message

**Expected behavior**
A presence update message must have appeared.

**Environment (please complete the following information):**
 - Is this on a server?
 Running on mac os, node 12.22
 - What do your `connectOptions` look like? 
all options are default as set in the example file.
 - Do you have multiple clients on the same IP?
 no
 - Are you using a proxy?
 No.

**Additional context**
Regular(non-md) version is working fine with presence updates. MD branch is not doing it yet.

**Comment by genseric** [comment]
i guess it's important to request presence update too. We can close this.
