### ISSUE TITLE
[MD] How to get the list of contacts and groups

### ISSUE THREAD

**Issue by AlanMartines** [adiwajshing/Baileys#993]
How to get the list of contacts and groups, with the **"groupMetadata"** function I only get the data of a group in which the id was informed.

**Comment by barkerpedro** [comment]
Groups I managed to pull all of them, but contacts still couldn't make it work.
    
```node
let getGroups = await sock.groupFetchAllParticipating();
let groups = Object.entries(getGroups).slice(0).map(entry => entry[1]);
console.log(groups);
```

**Comment by AlanMartines** [comment]
It worked out perfectly the consultation of the groups, thank you.
