### ISSUE TITLE
✅ [MD] - sendReadReceipt does not work with mobile disconnected from wi-fi ✅

### ISSUE THREAD

**Issue by mateuscdor** [adiwajshing/Baileys#994]
**Version used:** Baileys-md (Multi-device)

the **.sendReadReceipt()** function does not work
with the mobile device disconnected from the internet.

The **.sendReadReceipt** function only works when the
mobile device is connected to internet.

Perform the test with the mobile device disconnected
from Internet.

```
client.ev.on('messages.upsert', async m => 
{ 

 const msg = m.messages[0]

  if(!msg.key.fromMe && m.type === 'notify') 
   {	
	const id          = m.messages[0].key.remoteJid
	const messageID   = m.messages[0].key.id 
	const participant = m.messages[0].key.remoteJid 
	
	await client.sendReadReceipt(id, participant, [messageID])
   }

}
```

![image](https://user-images.githubusercontent.com/90919904/145355207-2de8d30d-3555-431d-872e-83f82ce89b28.png)

![image](https://user-images.githubusercontent.com/90919904/145355434-7fe01f42-889b-4c16-9487-90b525c66ce1.png)

**Comment by adiwajshing** [comment]
Mate you're supplying "remoteJid" as participant -- hence the error

**Comment by mateuscdor** [comment]
Adiw I've tried in several ways with the device disconnected from the wifi doesn't work for me.

I tried in several ways, but with no success with the device disconnected.

**Comment by barkerpedro** [comment]
Try:
```node
client.ev.on('messages.upsert', async m =>
{

 const msg = m.messages[0]

  if(!msg.key.fromMe && m.type === 'notify')
   {
	const id = m.messages[0].key.remoteJid
	const participant = client.user.id
	const messageID = m.messages[0].key.id
	
	await client.sendReadReceipt(id, participant, [messageID])
   }

}
```

**Comment by mateuscdor** [comment]
@barkerpedro  me chama no whats 73 9 9177-6616 tenho um grupo só com br

**Comment by mateuscdor** [comment]
@barkerpedro It also does not work with mobile device disconnected from the Wi-Fi

Também não funciona

**Comment by mateuscdor** [comment]
@barkerpedro 
Resolved
https://github.com/adiwajshing/Baileys/pull/1016
