### ISSUE TITLE
[MD] Error when sending ListMessage 

### ISSUE THREAD

**Issue by Peticali** [adiwajshing/Baileys#995]
i'm trying to send a ListMessage but the following error happens:

```
@adiwajshing\baileys-md\lib\Utils\messages-media.js:146
    if ('stream' in item)
                 ^

TypeError: Cannot use 'in' operator to search for 'stream' in undefined
```

The code to reproduce:
```
const {
    default: makeWASocket,
    useSingleFileAuthState,
    WAMessage,
} = require('@adiwajshing/baileys-md')

const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')

const conn = makeWASocket({
        auth: state,
        printQRInTerminal: true
})


const rows = [
    {title: 'Row 1', description: "Hello it's description 1", rowId:"rowid1"},
    {title: 'Row 2', description: "Hello it's description 2", rowId:"rowid2"}
   ]

const sections = [{title: "Section 1", rows: rows}]

const button = {
buttonText: 'Click Me!',
description: "Hello it's list message",
sections: sections,
listType: 1
}



conn.ev.on('messages.upsert', ({ messages }) => {
    message = messages[0]
    conn.sendMessage(message.key.remoteJid,button)
})


conn.ev.on('creds.update', saveState)

```

ListMessages are not yet supported in Baileys MD?

**Comment by mateuscdor** [comment]
Yes it is supported,

**Comment by barkerpedro** [comment]
Try:

```node
const {
    default: makeWASocket,
    useSingleFileAuthState,
    WAMessage,
    proto, 
    generateWAMessageFromContent
} = require('@adiwajshing/baileys-md')

const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')

const conn = makeWASocket({
        auth: state,
        printQRInTerminal: true
})

const rows = [
    {title: 'Row 1', description: "Hello it's description 1", rowId:"rowid1"},
    {title: 'Row 2', description: "Hello it's description 2", rowId:"rowid2"}
   ]

const sections = [{title: "Section 1", rows: rows}]

const button = {
title: "Title", //optional
description: "Hello it's list message",
footerText: "Footer", //optional
buttonText: 'Click Me!',
listType: 'SINGLE_SELECT',
sections: sections
}

conn.ev.on('messages.upsert', ({ messages }) => {
  message = messages[0]
  const templateList = generateWAMessageFromContent(message.key.remoteJid, proto.Message.fromObject({ "listMessage": button }), {});
  conn.relayMessage(message.key.remoteJid, templateList.message, { messageId: templateList.key.id });
})

conn.ev.on('creds.update', saveState)
```

**Comment by Peticali** [comment]
> Try:
> 
> ```js
> const {
>     default: makeWASocket,
>     useSingleFileAuthState,
>     WAMessage,
>     proto, 
>     generateWAMessageFromContent
> } = require('@adiwajshing/baileys-md')
> 
> const { state, saveState } = useSingleFileAuthState('./auth_info_multi.json')
> 
> const conn = makeWASocket({
>         auth: state,
>         printQRInTerminal: true
> })
> 
> const rows = [
>     {title: 'Row 1', description: "Hello it's description 1", rowId:"rowid1"},
>     {title: 'Row 2', description: "Hello it's description 2", rowId:"rowid2"}
>    ]
> 
> const sections = [{title: "Section 1", rows: rows}]
> 
> const button = {
> title: "Title", //optional
> description: "Hello it's list message",
> footerText: "Footer", //optional
> buttonText: 'Click Me!',
> listType: 'SINGLE_SELECT',
> sections: sections
> }
> 
> conn.ev.on('messages.upsert', ({ messages }) => {
>   message = messages[0]
>   const templateList = generateWAMessageFromContent(message.key.remoteJid, proto.Message.fromObject({ "listMessage": button }), {});
>   conn.relayMessage(message.key.remoteJid, templateList.message, { messageId: templateList.key.id });
> })
> 
> conn.ev.on('creds.update', saveState)
> ```

That worked, thanks!
