### ISSUE TITLE
[MD] Template Buttons Not Send Image, Only Text

### ISSUE THREAD

**Issue by MFarelS** [adiwajshing/Baileys#996]
**Describe the bug**
I have a problem, I follow the code contained in the documentation, send image template, but why only text appears 

**To Reproduce**
```
case prefix+'testt':
const templatetButtons = [
  {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
  {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
  {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const buttonMessage = {
    text: "Hi it's a template message",
    footer: 'Hello World',
    templateButtons: templatetButtons,
    image: { url: 'https://i.ibb.co/DK3qzwy/MFarelS1.jpg' }
}

const sendMsg = await chika.sendMessage(from, buttonMessage)
            break
```

Result : 
![Screenshot_20211209-231453_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/145436228-2c5785d9-0a1b-468c-a530-ac33ff3287b2.jpg)

Ask: Where The Image???

**Comment by mateuscdor** [comment]
change the name text: "Hi it's a template message",
for
caption: "Hi it's a template message",

do it.

**Comment by NexonDzn** [comment]
I'm also having the same problem, did you manage to solve it?

**Comment by tuin007** [comment]
Same problem here, message appears on both BOT and client

**Comment by arifwidianto08** [comment]
I still got the same problem here, is it already fixed yet? Anyway, why did this issue get closed?
