### ISSUE TITLE
[MD] [BUG] send template button with image, not send image, only text

### ISSUE THREAD

**Issue by MFarelS** [adiwajshing/Baileys#998]
**Describe the bug**
I have a problem, I follow the code contained in the documentation, send image template, but why only text appears 

```
case prefix+'testt':
const templatetButtons = [
  {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
  {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
  {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const buttonMessage = {
    text: "Hi it's a template message",
    footer: 'Hello World',
    templateButtons: templatetButtons,
    image: { url: 'https://i.ibb.co/DK3qzwy/MFarelS1.jpg' }
}

const sendMsg = await chika.sendMessage(from, buttonMessage)
            break
```

Result : 
![Screenshot_20211209-231453_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/145436228-2c5785d9-0a1b-468c-a530-ac33ff3287b2.jpg)

Ask: Where The Image???

**To Reproduce**

1. Created a new connection
2. Logout WhatsApp application
3. Wait up to 3 minutes to see the error appear

**Environment (please complete the following information):**
• Is this on a server? Yes
• Do you have multiple clients on the same IP? Not
• Are you using a proxy? Yes

**Comment by barkerpedro** [comment]
Change the "text" to "caption":
```node
case prefix+'testt':
const templatetButtons = [
  {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
  {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
  {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
]

const buttonMessage = {
    caption: "Hi it's a template message",
    footer: 'Hello World',
    templateButtons: templatetButtons,
    image: { url: 'https://i.ibb.co/DK3qzwy/MFarelS1.jpg' }
}

const sendMsg = await chika.sendMessage(from, buttonMessage)
            break
```

**Comment by 4t3n34** [comment]
not show buttons
![image](https://user-images.githubusercontent.com/17351630/145529219-7d4c2331-a964-4a14-ba92-d8bd83f5276a.png)

**Comment by VEXG** [comment]
> not show buttons ![image](https://user-images.githubusercontent.com/17351630/145529219-7d4c2331-a964-4a14-ba92-d8bd83f5276a.png)

it can be your whatsapp is not updated, you are using whatsapp mod, and maybe your code..

**Comment by Zobin33** [comment]
> **Describe the bug** I have a problem, I follow the code contained in the documentation, send image template, but why only text appears
> 
> ```
> case prefix+'testt':
> const templatetButtons = [
>   {index: 1, urlButton: {displayText: '⭐ Star Baileys on GitHub!', url: 'https://github.com/adiwajshing/Baileys'}},
>   {index: 2, callButton: {displayText: 'Call me!', phoneNumber: '+1 (234) 5678-901'}},
>   {index: 3, quickReplyButton: {displayText: 'This is a reply, just like normal buttons!', id: 'id-like-buttons-message'}},
> ]
> 
> const buttonMessage = {
>     text: "Hi it's a template message",
>     footer: 'Hello World',
>     templateButtons: templatetButtons,
>     image: { url: 'https://i.ibb.co/DK3qzwy/MFarelS1.jpg' }
> }
> 
> const sendMsg = await chika.sendMessage(from, buttonMessage)
>             break
> ```
> 
> Result : ![Screenshot_20211209-231453_WhatsAppBusiness](https://user-images.githubusercontent.com/58540890/145436228-2c5785d9-0a1b-468c-a530-ac33ff3287b2.jpg)
> 
> Ask: Where The Image???
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Created a new connection
> 2. Logout WhatsApp application
> 3. Wait up to 3 minutes to see the error appear
> 
> **Environment (please complete the following information):** • Is this on a server? Yes • Do you have multiple clients on the same IP? Not • Are you using a proxy? Yes


Add imageMessage: {} There

**Comment by Zobin33** [comment]
![Uploading Screenshot_2021-12-10-17-28-47-056_com.whatsapp.jpg…]()

**Comment by Zobin33** [comment]
![Screenshot_2021-12-10-17-28-43-254_com whatsapp](https://user-images.githubusercontent.com/48700650/145559504-49145c1b-e5ef-4637-8045-9885b3c98bda.jpg)

**Comment by Zobin33** [comment]
![Screenshot_2021-12-10-17-28-47-056_com whatsapp](https://user-images.githubusercontent.com/48700650/145559746-62fcadf0-7095-4ea9-84d7-66f535530b22.jpg)

**Comment by frmdeveloper** [comment]
> ![Screenshot_2021-12-10-17-28-43-254_com whatsapp](https://user-images.githubusercontent.com/48700650/145559504-49145c1b-e5ef-4637-8045-9885b3c98bda.jpg)

Try removing the "quickReplyButton".
Maybe that's what he wants

**Comment by MFarelS** [comment]
Thankss All

**Comment by muhamad-fadla** [comment]
> Thankss All

wait.., how resolve it?
