### ISSUE TITLE
[BUG] Send audio with pttaudio does not change avatar (show default orange phone icon)

### ISSUE THREAD

**Issue by guiireal** [adiwajshing/Baileys#999]
Hey guys!

After sending audio with pttAudio param, this does not change the avatar image after sending audio.

My Function:
![image](https://user-images.githubusercontent.com/13739343/145507761-a84b68c7-da4d-469d-b324-a786ec405dc8.png)

Using:
![image](https://user-images.githubusercontent.com/13739343/145507841-fe32c5e1-4064-4339-a47c-3fdb09793fd0.png)

Result (The default icon)
![image](https://user-images.githubusercontent.com/13739343/145507884-1acc8dbd-272f-4314-8698-e6bb8325b34b.png)

Expected (The avatar of user)
![image](https://user-images.githubusercontent.com/13739343/145507977-83ea36a2-8b80-45d7-b526-740c20bc2271.png)

**Comment by barkerpedro** [comment]
conn.sendMessage(jid, { audio: { url: './audio.mp3' }, ptt: true });

**Comment by BochilGaming** [comment]
> Hey guys!
> 
> After sending audio with pttAudio param, this does not change the avatar image after sending audio.
> 
> My Function: ![image](https://user-images.githubusercontent.com/13739343/145507761-a84b68c7-da4d-469d-b324-a786ec405dc8.png)
> 
> Using: ![image](https://user-images.githubusercontent.com/13739343/145507841-fe32c5e1-4064-4339-a47c-3fdb09793fd0.png)
> 
> Result (The default icon) ![image](https://user-images.githubusercontent.com/13739343/145507884-1acc8dbd-272f-4314-8698-e6bb8325b34b.png)
> 
> Expected (The avatar of user) ![image](https://user-images.githubusercontent.com/13739343/145507977-83ea36a2-8b80-45d7-b526-740c20bc2271.png)

ptt: true

**Comment by guiireal** [comment]
> > Hey guys!
> > After sending audio with pttAudio param, this does not change the avatar image after sending audio.
> > My Function: ![image](https://user-images.githubusercontent.com/13739343/145507761-a84b68c7-da4d-469d-b324-a786ec405dc8.png)
> > Using: ![image](https://user-images.githubusercontent.com/13739343/145507841-fe32c5e1-4064-4339-a47c-3fdb09793fd0.png)
> > Result (The default icon) ![image](https://user-images.githubusercontent.com/13739343/145507884-1acc8dbd-272f-4314-8698-e6bb8325b34b.png)
> > Expected (The avatar of user) ![image](https://user-images.githubusercontent.com/13739343/145507977-83ea36a2-8b80-45d7-b526-740c20bc2271.png)
> 
> ptt: true

Thanks a lot! But in the doc, the param is pttAudio, not a ptt:


![image](https://user-images.githubusercontent.com/13739343/145596818-6fb24b4a-8b3a-41ab-945d-7afc99369ec6.png)
![image](https://user-images.githubusercontent.com/13739343/145596934-38b6a47a-9c50-44fc-92fd-e80a130b266a.png)
![image](https://user-images.githubusercontent.com/13739343/145596977-de0a24b5-0380-442e-be0e-a42bf2a614f0.png)

**Comment by mateuscdor** [comment]
@guiireal  managed to solve?
